### ISSUE TITLE
System.IO.IsolatedStorage can be referenced by netstandard1.4, but has no associated impl

### ISSUE THREAD

**Issue by xyziemba** [dotnet/corefx#10002]
The [reference assembly](https://github.com/dotnet/corefx/blob/afa634708deb4b921dd1e0e6dc5f26ddd0e143b2/src/System.IO.IsolatedStorage/ref/project.json) for System.IO.IsolatedStorage targets netstandard1.4, but the [implementation](https://github.com/dotnet/corefx/blob/afa634708deb4b921dd1e0e6dc5f26ddd0e143b2/src/System.IO.IsolatedStorage/src/project.json) only targets netcore50. Therefore, you can build an app targeting netcoreapp1.0 (+ imports dnxcore50) that'll throw a FileNotFoundException since it can't load System.IO.IsolatedStorage.

There is discussion to implement IsolatedStorage in other platforms in #9842, but until that's done, you shouldn't be able to reference IsolatedStorage from platforms where it isn't implemented.

**Comment by joshfree** [comment]
cc: @ianhays

**Comment by ericstj** [comment]
That's by-design.  Ref with no lib means not supported.

**Comment by xyziemba** [comment]
I see. Is there a semantic difference between ref-with-no-lib and refs-only-for-the-platforms-where-there-are-libs? VS and dotnet-cli tooling certainly treat the two scenarios differently and give me a much better experience (blocking the reference in NuGet) with the latter scenario.

**Comment by ericstj** [comment]
No ref prohibits creating a PCL that ever targets it.  Having a ref lets someone create a PCL that targets the subset of platforms that support it.

NuGet used to block the both, that's the whole "Package A provides a compile-time reference assembly for A.dll, but there is no run-time assembly compatible with RID".  I believe this was turned off when portable app / shared framework work happened because NuGet didn't have a way to "know" if the runtime asset was missing because it is in the shared framework or missing because it was not supported.  In fact you'll still see this error when referencing the package from a project.json that uses a RID.
EG:
```
error: System.IO.IsolatedStorage 4.0.1 provides a compile-time reference assembly for System.IO.IsolatedStorage on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x86.
```
I believe NuGet turned this off in the expectation that the compat check would be moved later in the build process, but that work was not in scope for V1.0.

**Comment by xyziemba** [comment]
Got it. Thanks for the clarification! Closing this out.
