### ISSUE TITLE
Microsoft.TargetingPack.Private.CoreCLR is not being published

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#10014]
We haven't seen a new build of Microsoft.TargetingPack.Private.CoreCLR out of CoreCLR branch since June 29th.  Can you have a look at why your builds aren't producing this package?

/cc @jhendrixMSFT

**Comment by jhendrixMSFT** [comment]
@wtgodbe Will can you take a look?

**Comment by wtgodbe** [comment]
I'm not actually sure how we were ever producing this package in the first place - all we have for it is a .pkgproj file, while all our other packages have .builds files that we call in build-packages.cmd, as well  as separate .pkgproj files for each OS. Looking at the .pkgproj for TargetingPack, I see that the 'Version' property is set to 1.0.1, which seems out of date. @gkhanna79, we stopped producing this package somewhere between June 29 and June 30, which is around the same time you merged in this change to produce Arm64 packages (https://github.com/dotnet/coreclr/pull/6000) - did you put any filtering mechanisms into place in this PR that might have affected the TargetingPack package?

**Comment by wtgodbe** [comment]
OK, I think I've figured it out. Look at this change from a week ago (https://github.com/dotnet/coreclr/commit/74870facf4fa0f70a0c2ba5ff7ec2bd349faeb32#diff-02389dfac0a172ab80211625efc34318R535) - this fixes a previously incorrect filter in build.cmd which would check whether or not we should skip the package build. In our orchestrated builds, we want to skip the package build in build.cmd so we can do it in build-packages.cmd instead. However, until this change, the filter was wrong, so even though we thought we were skipping the package build in build.cmd, we actually weren't. The package build done by build.cmd is correct, and does build the TargetingPack package, so even though build-packages.cmd wasn't building it, build.cmd was, so the error was invisible. Since Rahul fixed the filter, the error was exposed. The fix should be to just add a block in build-packages.cmd/.sh to build this TargetingPack package in the same way that build.cmd does. I'll put up a PR later today.

**Comment by ericstj** [comment]
Just realized I opened this in the wrong repo.  Should have been in CoreCLR.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/6255 should fix this
