### ISSUE TITLE
System.Data.SqlClient.SqlDataReader has no close method?

### ISSUE THREAD

**Issue by pamanes** [dotnet/corefx#10046]
Do we have  to worry about closing the SqlDataReader? I get the feeling that it's handled upon closing the connection.

thanks for your attention.

**Comment by saurabh500** [comment]
@pamanes You should `Close()` or `Dispose()` the `SqlDataReader` 
We recommend `Dispose()` over Close and this can also be achieved by wrapping the SqlDataReader in a using construct.
This is a good practice and allows connection re-usability. A SqlDataReader on a connection can be closed and another SqlDataReader can be created from the Command on the connection instead of closing and re-opening the connection. 

 Close()/Dispose() clean up the internal objects being used in SqlDataReader to read the data and is recommended.

**Comment by pamanes** [comment]
There is no .close() on a SqlDataReader object in .net core 1.0

**Comment by pamanes** [comment]
@saurabh500 The SqlDataReader object in .net core 1.0 has no .Close() method.

**Comment by saurabh500** [comment]
Yes. The IDataReader interface has the Close method. The interface is implemented by the DbDataReader base class and the base class is extended by the SqlDataReader 
For .Net Core 1.0 Dispose() is preferred over close. They both do the same thing internally.

**Comment by svick** [comment]
@pamanes [`DbDataReader` implements `Close()` explicitly](https://github.com/dotnet/corefx/blob/v1.0.0/src/System.Data.Common/ref/System.Data.Common.cs#L364), which is why you don't see it. You should use `Dispose()` or `using` to close the reader.

If, for some reason, you really wanted to call `Close()`, you would have to cast to `IDataReader`: `((IDataReader)sqlDataReader).Close();`.

**Comment by saurabh500** [comment]
cc @tvrprasad @corivera

**Comment by gerakul** [comment]
((IDataReader)sqlDataReader).Close() is not working correctly. Property IsClosed continues to be false.
