### ISSUE TITLE
Add Ubuntu and CentOS Outerloop test coverage for Linux kernel 4.6.2

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#10076]
We're seeing some CLI / .NET Core bug reports where users have upgraded to 4.x kernels.

We should add some outerloop runs to test this configuration:  

1) Ubuntu 16.04 + kernel 4.6.2
2) CentOS 7.1 + 4.6.2

https://github.com/dotnet/coreclr/issues/6016

https://github.com/dotnet/cli/issues/3681

http://www.techrepublic.com/article/pro-tip-upgrade-ubuntu-to-the-4-x-kernel/

**Comment by danmosemsft** [comment]
@mellinoe if we have a run on Ubuntu 16.10 is that sufficient? It has kernel 4.8.

**Comment by mellinoe** [comment]
We have runs on Ubuntu 16.10, and soon Fedora 24, which should have newer kernels. I may need to update the Ubuntu 16.10 image soon, though, because it was created a couple of months ago and I think it is still on a pre-release version of 16.10. We should verify which kernel version they are using, though.

**Comment by karelz** [comment]
I think we should close this issue. We should use only official distro snapshots. Adding kernel updates into our distro matrix won't help us too much and is quite a lot of work -- we will get the coverage from official distros eventually.

**Comment by mellinoe** [comment]
@karelz Ok, I'll go ahead and close this.
