### ISSUE TITLE
Use Loopback server for HttpClient testing.

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#10156]
Today, we use http://corefx-net.cloudapp.net/ as an endpoint for much of the HttpClient testing.  We've slowly been moving towards using a loopback server that gives back fixed HTTP responses to remove this dependency, (since it's one of the main places we see intermittent network issues that cause spurious test failures) but the set of testing we do against this is currently limited because the loopback server doesn't really understand HTTP so it can't do sophisticated actions based on requests.

It should be possible to take the existing implementation of http://corefx-net.cloudapp.net/ and port it to run on ASP.NET Core 1.0.  Once we've done that, we could use Kestrel locally to host a loop-back server that binds to a random port as part of setting up the HttpClient tests.  This server could live for the lifetime of the dependent tests and then be shut down.  There are a few steps to take here:
- [ ] Port existing server to ASP.NET Core 1.0 (In progress, @ellismg is working on this)
- [ ] Move server from above to be hosted within the tests themselves.
- [ ] Figure out how to handle HTTPS

HTTPS is interesting, because we need need a valid certificate for the server or we need to configure how we validate the remote certificate, which we only support on Windows and Unix when using an openssl based libcurl (not the case on CentOS, OSX and perhaps others).

**Comment by davidsh** [comment]
@ellismg We already are working on this.  We do not plan to move all of the tests to loopback though. But we plan to place a test server within the CI machine constellation so that it will have very low latency.

@CIPop is working on this activity.  So, this issue is duplicative.

cc: @stephentoub

**Comment by davidsh** [comment]
cc: @himadrisarkar

**Comment by ellismg** [comment]
> But we plan to place a test server within the CI machine constellation so that it will have very low latency.

I understand how that helps tests within CI itself, but don't local builds now have the same issue?  What about when we run tests in other environments like Helix which may not share the same infrastructure as the CI machine?  Why is this preferable to simply running the server on the local machine?  We should be able to leverage Kestrel and the ASP.NET stack such that we don't have to re-implement the HTTP goo ourselves.

**Comment by davidsh** [comment]
Agreed.  But porting the tests to ASP.NET core is part of our already planned work that @CIPop is working on.

**Comment by davidsh** [comment]
Basically yes.  I'll @CIPop explain more.  We have parallel work that will 1) move more tests to loopback, 2) move the design/architecture of the test endpoint to use ASP.NET Core (instead of .ashx files) so that it can be deployed cross-plat and used locally by devs, and 3) revise the CI test server deployment to be lower latency.

**Comment by stephentoub** [comment]
Glad to see we're making progress on this.  What's the rationale for having the test server be "within the CI machine constellation" rather than a local loopback server as Matt's proposing?  Or is this just a different way of saying the same thing?

**Comment by davidsh** [comment]
We still need real end-to-end tests with a real test server endpoint machine.  So, for those tests, we will use a test server that is "closer" to the CI machines.  Other tests can be loopback.

**Comment by ellismg** [comment]
> We still need real end-to-end tests with a real test server endpoint machine.

I understand why we would want E2E tests that talk to a real test server, like Kestrel instead of just some thing that's giving back fixed HTTP responses.  I think Steve and I are wondering why that also implies we need to actually talk over the internet to do it, what coverage do we lose by binding Kestrel to some port on localhost and talking to that?

**Comment by davidsh** [comment]
There is test coverage we lose by using loopback. In Windows, for example, there is different network stack optimization for the loopback adapter. And it is difficult to do TLS/SSL testing when using loopback as well.

I understand the desire to make our CI / PR system more reliable. But we shouldn't get rid of important tests (or make too much stuff Outerloop) just because of the CI system is flaky.

**Comment by CIPop** [comment]
@ellismg @stephentoub Please try: https://github.com/dotnet/corefx/tree/master/src/Common/tests/System/Net/Prerequisites
Testing with localhost is already achieved for certain scenarios thanks to @stephentoub's implementation of a test HTTP server. 
Localhost is a special case for most of the networking stack components as well as authentication components. Real and more complicated scenarios require machine to machine communication. The differences may be subtle in some cases (the loopback TCP fast-path may not create as many segments as a real adapter) and obvious in other (auth on the same machine in most cases is handled through NTLM instead of Kerberos according to [my tests](https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/tests/FunctionalTests/NegotiateStreamKerberosTest.cs#L93)).

> @CIPop is taking the existing corefx-net service and rewriting it on top of ASP.NET Core

@davidsh This is incorrect: as previously discussed, we cannot use ASP.Net Core at this time to test our components. The main issue is that Kestrel doesn't support enterprise scenarios such as Kerberos/NTLM auth and the IIS integration is in flux (now requiring a proxy server between IIS and Kestrel as well as specific code to handle headers added by this proxy).

**Comment by davidsh** [comment]
Tracking Http test reliability here: #14519.
