### ISSUE TITLE
System.Security.AccessControl pkg needs to be marked with Windows only runtime 

### ISSUE THREAD

**Issue by niemyjski** [dotnet/corefx#10289]
The package needs to be updated to be marked as "runtime":"win" as it only works on windows for things like named mutexes...  We get errors when trying to install this .netstandard package on xamarin projects due to the windows specific packages. Please see: https://github.com/dotnet/coreclr/issues/1237

**Comment by niemyjski** [comment]
Not sure if this could be related to https://github.com/dotnet/cli/issues/1154 but definitely seeing this when trying to install it via xamarin (I think they use nuget 2.12).

**Comment by ericstj** [comment]
The package does have a Windows-specific and Unix-specific implementation: 
```
System.Security.AccessControl\4.0.0\runtimes\unix\lib\netstandard1.3\System.Security.AccessControl.dll
System.Security.AccessControl\4.0.0\runtimes\win\lib\net46\System.Security.AccessControl.dll
System.Security.AccessControl\4.0.0\runtimes\win\lib\netstandard1.3\System.Security.AccessControl.dll
```

**Comment by ericstj** [comment]
The Unix specific implementation throws PlatformNotSupported for all API.

The errors you see for Xamarin projects are due to those projects not restoring with a runtime.  Even if they did you just get an assembly that throws PlatformNotSupported.

The latest request from Xamarin has been to mark the System.\*AccessControl packages as *inbox* on xamarin platforms: https://github.com/dotnet/buildtools/issues/877, so with that these packages will install.  Even so, I don't suspect Xamarin's inbox implementation of these types will do what you expect since ACLs are a Windows concept.

**Comment by niemyjski** [comment]
Thanks for the heads up. I really don't care too much if they work on a specific platform (everything is a progressive enhancement and is try/catched as we never want to blow up... ) My problem is that it won't install :)

**Comment by niemyjski** [comment]
I'm going to close this as I think 887 is the root issue :)
