### ISSUE TITLE
System.Reflection api does not match lib implementation

### ISSUE THREAD

**Issue by marek-safar** [dotnet/corefx#10327]
System.Reflection contract contains MethodBase method `virtual Invoke` but the implementation (at least for .net 4.6) of the method is not virtual.

Relevant sources

https://github.com/dotnet/corefx/blob/48dc3f4c8eaecafc2d2ed51c6332192d5497e178/src/System.Reflection/ref/System.Reflection.cs#L281

https://github.com/dotnet/coreclr/blob/f1b3fc7b704662903c753dc20681693a69266931/src/mscorlib/src/System/Reflection/MethodBase.cs#L201

**Comment by AtsushiKan** [comment]
The virtual was added to the .NetCore contract since we removed the more general virtual overload that took a BindingFlag. Since the .NetCore contracts never got to the point of supporting general extensibility (hence, the "internal" accessibility of the constructor), it's not a requirement to make the underlying implemention virtual.

Also, the <a href="https://blogs.msdn.microsoft.com/dotnet/2016/05/27/making-it-easier-to-port-to-net-core/">api unification</a> for 2.0 is expected to make the contracts match up with the original full framework definitions, so this sort of thing will be fixed holistically as part of that. Thus, I'm closing this issue.

Thanks.
