### ISSUE TITLE
XPathItem constructor not public

### ISSUE THREAD

**Issue by tim-xmlprime-com** [dotnet/corefx#10325]
I have spent a little while attempting to port XmlPrime (XQuery 3.0, XSLT 2.0) library to .NET core.

XPathItem's constructor is now internal.  This means we cannot derive new XPathItem types.  We rely on this to add XPathAtomicValue, XPathFunctionItem, XPathMap and XPathArray which are part of the XQuery 3.1 data model.

This would essentially mean we would have to entirely abandon use of System.Xml.XPath. 

        // Constructor is internal because abstract member was removed and it might be back in some time.
        // If someone would have created derived class without that member and we would add it back
        // it would break his code.
        internal XPathItem() { }

**Comment by joshfree** [comment]
@sepidehMS

**Comment by danmosemsft** [comment]
This is missing from src\system.private\xml\src\system\xml\xpath\xpathitem.cs -- it should have protected XPathItem() {}

**Comment by sepidehMS** [comment]
@tim-xmlprime-com As mentioned in the comment, the reason this was made internal initially was because the abstract member `XmlType`  was removed, due to XmlSchema not being available. We are currently working on bringing back all System.Xml APIs, including XmlSchema, and very likely it will happen with 1.2.0.

**Comment by sepidehMS** [comment]
I'm closing this as I'm currently working on https://github.com/dotnet/corefx/issues/11888, which will bring this back.
