### ISSUE TITLE
Hang in System.Net.Security.Tests (Windows debug) in CI

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#10344]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/3118/

Looking through the log, System.Net.Security.Tests is the only test that seems to have started, but not finished.

This failed while testing PR #10309, which just changed an attribute on some Sockets tests, so isn't likely to have caused these tests to hang.

**Comment by stephentoub** [comment]
Wild guess, but I think it likely that this is related to @joperezr exposing the APM methods on Stream.  IIRC, System.Net.Security uses Begin/End extension methods to wrap its Task-based implementations; by adding Begin/End to Stream in the contract, those will start to compile agains the Begin/End on Stream rather than against the XxAsync implementations, which means they'll now be queueing work items to call the synchronous Read/Write rather than using the Task-based async implementations.  Different symptom, but I expect it's the same as https://github.com/dotnet/corefx/issues/8472, which started after our last attempt to expose Begin/End.

**Comment by joperezr** [comment]
@stephentoub I can't get a consistent repro of this, but do you think I should revert my the exposure of the APM methods?

**Comment by stephentoub** [comment]
I just realized that my explanation can't be correct... your change was only in dev/api, right?  The failure Eric saw was in master.

**Comment by joperezr** [comment]
Right, I also thought that the CI job was from dev/api branch. These members are not present in master yet.

**Comment by CIPop** [comment]
Clicking on the link I get a 404. 

We need to enable ETW tracing at least for System.Net to get any progress with these intermittent issues. The only alternative is to run the parallel test runner and hope that the issue is hit although that may not always happen.

**Comment by CIPop** [comment]
Ran 20 instances for about 5 minutes and none of them hang.
To continue the investigation please collect a dump with symbols from the affected machine when this happens:
```
        .dump /mA <pathto>.dmp
```
Open another WinDBG on the same machine and open the <pathto>.dmp file then:
```
		.symfix
		.srcfix
		.reload /f
        .dumpcab /a <pathto>.cab
```

[System.Net ETW](https://github.com/dotnet/corefx/blob/master/Documentation/debugging/windows-instructions.md#systemnet-namespaces) traces would also help identifying the API that is hanging.
