### ISSUE TITLE
Investigate why Assert went out of it's way to call MessageBox on a different thread

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#1037]
There's some internal history on why this decision was made that @stephentoub and I both don't fully grok.  I need to take the time and understand if this is still something we need to be doing and why it only mattered for CoreCLR and not desktop at the time.

Once that's done, something like #1012 might be in order.

**Comment by mikedn** [comment]
It's kind of strange that the desktop version uses the separate thread only in WinStore apps, anyway the message box isn't displayed in those apps.

I don't know the history around this but I'm tempted to say that using a separate thread makes sense because blocking on an event is less likely to perturb the thread state. Blocking on MessageBox means blocking on a modal message loop and in turn that means that reentrancy is possible. I know that .NET Core doesn't currently include any desktop UI technologies but who's to say that nobody will ever attempt to build a desktop UI on top of .NET Core?

**Comment by ellismg** [comment]
@mikedn Yes.  For CoreCLR the internal issue that was filed was during the Silverlight time frame, where Debug.Assert was used from Silverlight apps being hosted in the browser, and it was causing re-entrency issues.  I just don't understand why we didn't also make the change for Desktop at the same time (unfortunately for me, I was the person that made the change 6ish years ago, so I only have myself to blame for not explaining why we didn't care to address the issue on Desktop as well).

**Comment by karelz** [comment]
@ellismg is looking at it now. Please update the issue (incl. unassign from yourself + mark up for grabs) when you're done.

**Comment by joperezr** [comment]
Talked to @ellismg offline and this is not any longer so we decided to close this for now and reopen in the future if needed.
