### ISSUE TITLE
Potential issue with RegularExpressionAttribute and differing regex flavors client vs. server side

### ISSUE THREAD

**Issue by JohannStudanski** [dotnet/corefx#10606]
The System.ComponentModel.DataAnnotations.RegularExpressionAttribute is used for client side runtime value checking in ASP.NET Core websites.\* 

The client side validation is run via jquery.validation.*

JavaScript and .Net (Core) use different RegEx engines with different flavors, though, and for example named capturing groups, working as "`(?<groupname>regex)`" in C# code, will _not_ work on the javascript side. This leads to validation silently not taking place on client-side, there's neither an error during compilation of the C# code nor during execution in browser (took me some minutes to figure out what was going on…).

It would be nice if there was either some kind of warning, or—even nicer but a lot harder to manage—an automatic transformation step that makes C# side regexes work even when they're used in the definition for the client side validation, so you don't have to keep the regex around in 2 flavors (for client and server side validation).

*as per https://docs.asp.net/en/latest/tutorials/first-mvc-app/validation.html

**Comment by ajcvickers** [comment]
@JohannStudanski I don't think there is anything we can do _in the data annotation_ that would make this work for all client side validation, or even know or warn when it is not going to work. The consumer of the annotation might be able to do that, so if you feel strongly that this should be done in ASP.NET Core, then you might want to file an issue there. However, my understanding is that their behavior is by design--that is, the client side validation is best effort, but if it is not available or doesn't work, then it doesn't block anything.
