### ISSUE TITLE
Cannot Build For FreeBSD

### ISSUE THREAD

**Issue by wolfspider** [dotnet/corefx#10610]
While trying to follow the directions here: https://github.com/dotnet/coreclr/blob/master/Documentation/building/freebsd-instructions.md

I keep getting the same error Building .NET Core on FreeBSD 10.1 and this is the second install of FreeBSD I've seen this with so far. Here is the console output I am getting:

root@sawzall:/usr/home/jbennett/git/corefx # ./build-packages.sh
Unsupported OS 'FreeBSD' detected. Downloading ubuntu-x64 tools.
Installing dotnet cli...
Restoring BuildTools version 1.0.26-prerelease-00704-01...
ELF binary type "0" not known.
/usr/home/jbennett/git/corefx/init-tools.sh: line 78: /usr/home/jbennett/git/corefx/Tools/dotnetcli/dotnet: cannot execute binary file: Exec format error
ERROR: Could not restore build tools correctly. See '/usr/home/jbennett/git/corefx/init-tools.log' for more details.
Initializing BuildTools...
/usr/home/jbennett/git/corefx/init-tools.sh: line 84: /usr/home/jbennett/git/corefx/packages/Microsoft.DotNet.BuildTools/1.0.26-prerelease-00704-01/lib/init-tools.sh: No such file or directory
ERROR: An error occured when trying to initialize the tools. Please check '/usr/home/jbennett/git/corefx/init-tools.log' for more details.

Obviously, my FreeBSD 10.1 install can't run Linux 64-bit binaries here so I am wondering how would I get this to build without the tools?

**Comment by mellinoe** [comment]
It looks like those are a bit out-of-date with all of the build changes we've made here. Perhaps @janhenke or @josteink could give you more FreeBSD-specific pointers. I can give a broad overview of how to build on unsupported platforms, because I've been figuring out how to do it myself this week :smile: .

The basic pre-requisite you need to build things is a working CLI for your platform. We need it to do pretty much all parts of our managed build. This includes running package restore, running MSBuild, running the C# compiler, and running all of our post-build steps (GenFacades, ApiCompat, etc), as well as all of our custom MSBuild targets.

It's SUPER rough right now, but I have been working on a ["bootstrap" repo](https://github.com/mellinoe/bootstrap) which is supposed to make it easier to get a working CLI on un supported platforms. The basic gist is that the repo has all of the managed components (i.e. platform-agnostic) committed to it, and has a script to build the native components for your specific platform. Then, the script jams all of the components together into the layout expected by the CLI. You can then copy this CLI into corefx's "Tools" directory and run the normal build. I've used this to successfully build on two unsupported platforms so far, Ubuntu 16.10 and openSUSE 42.1. There are a few caveats with this right now:

* The native builds of all components need to already be supported for your platform. I think all of our stuff already supports FreeBSD native builds.
* You have to build System.Private.CoreLib.dll on Windows from a version of coreclr that matches the submodule in https://github.com/mellinoe/bootstrap and then copy that into your bootstrapped CLI.
* Corefx's init-tools.sh doesn't like for you to provide your own CLI. It always tries to download a version from azure, even if you manually copy your bootstrapped version into the Tools directory. This means that you need to delete lines 52-71 in [init-tools.sh](https://github.com/dotnet/corefx/blob/master/init-tools.sh#L52) otherwise it will get overridden with a CLI that doesn't work.
* You can't run tests in corefx because we download runtime dependencies from nuget, and there are none for unsupported platforms. So you need to pass `-SkipTests` to build.sh.

**Comment by mellinoe** [comment]
Another caveat:

* The version of CSC pulled in by buildtools right now isn't compatible with the latest version of coreclr. You need to hack up the tool-runtime/project.json that comes from the buildtools nuget package to use version 1.3.2 of `Microsoft.Net.Compilers.netcore` for the build to work.

We will probably fix this last caveat soon.

**Comment by mellinoe** [comment]
Another missing step: You need to `export __PUBLISH_RID=<some-rid>` in order for init-tools.sh to work. Just use ubuntu.14.04-x64 for now. This doesn't influence any native assets that I can tell, so it doesn't really matter what you put. But it fails if it auto-detects your RID and it doesn't exist.

**Comment by josteink** [comment]
While obviously not "there" yet, this looks like massive progress towards getting a proper FreeBSD build back up and running.

The bootstrap repo was definitely needed. Glad to see some initiative in that regard :)

While I haven't tested any of this yet, I'll just add that I've submitted some patches to address FreeBSD-specific issues in various dotnet projects, including corehost in used by CLI.

It would be very nice if someone could tell me that we have something working now once everything is built :)

**Comment by janhenke** [comment]
I am afraid I cannot add anything to this discussion right now. As much as I wish to see FreeBSD properly supported, after the initial porting changes in my life prevented me from further following along and as such I have no idea about the current state or what is needed. I am sorry guys.

**Comment by mellinoe** [comment]
There are a few things in motion right now that should resolve a few of the above caveats soon. I would say in the next few weeks, we should be able to get a full end-to-end build of corefx if you just provide a bootstrapped CLI on unsupported platforms. Tests will be a bit trickier. I think we can use the `-BuildTestsAgainstPackages`, but we'll still need to do something about the CoreCLR nuget package.

**Comment by wolfspider** [comment]
@mellinoe By following your shell script I built everything one package at a time until finally getting to CoreFX. By the time I got there this is what I got which seems to be an issue with CoreCLR:

Restoring BuildTools version 1.0.26-prerelease-00704-01...

Assert failure(PID 50685 [0x0000c5fd], Thread: 29836288 [0x1c74400]): Consistency check failed: Managed class field offset does not match unmanaged class field offset
man: 0x5d, unman: 0x5c, Class: System.AppDomainSetup, Name: _CheckedForTargetFrameworkName
FAILED: offset == p->expectedFieldOffset
    File: /usr/home/jbennett/git/coreclr/src/vm/binder.cpp Line: 558
    Image: /usr/home/jbennett/git/corefx/Tools/dotnetcli/dotnet

/usr/home/jbennett/git/corefx/init-tools.sh: line 94: 50685 Abort trap              (core dumped) $__DOTNET_CMD restore "$__PROJECT_JSON_FILE" --no-cache --packages $__PACKAGES_DIR --source $__BUILDTOOLS_SOURCE >> $__init_tools_log
ERROR: Could not restore build tools correctly. See '/usr/home/jbennett/git/corefx/init-tools.log' for more details.

I'm going to try building CoreCLR again and verify this is accurate when I have a little more time.

**Comment by mellinoe** [comment]
I believe that is an error from having a `System.Private.CoreLib.dll` which doesn't match the runtime. To make sure you get one that works, you need to do the following on Windows:

* Check out the exact same commit as the one you built coreclr with
* Make sure that Debug/Release also matches
* Run `build.cmd linuxmscorlib <Debug | Release>
* Copy that over to your test machine.

An easy way to see if you're able to even launch the program is to run `./corerun helloworld.dll` from the "Shared" folder of your bootstrapped CLI. This is just a really simple program I threw in there to see if I was able to run anything at all yet.

**Comment by wolfspider** [comment]
@mellinoe Thank you for all the good information so far I think I may have gotten a little further now with your suggestion to build System.Private.CoreLib.dll with the linuxmscorlib flag. Now what I am running into is that the files copied from the Seed CLI are giving a bad image format exception. Where do they come from the dotnet/cli project? When CoreFX tries to do a dotnet restore during its Tools Init I get this error message: 

Unhandled Exception: System.BadImageFormatException: Could not load file or assembly '/usr/home/jbennett/git/corefx/Tools/dotnetcli/sdk/1.0.0-preview3-003223/dotnet.dll'. An attempt was made to load a program with an incorrect format.

And when I do ./corerun helloworld.dll it gives me an error about System.Runtime but of course System.Runtime hasn't build yet:

Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An attempt was made to load a program with an incorrect format.

**Comment by josteink** [comment]
To me that looks like the same issue @sec encountered when trying to get a FreeBSD build going about a month ago. You can follow good attempt in this thread here:

https://github.com/dotnet/coreclr/issues/917#issuecomment-231704372

jkotas offered him some advice. I'm not sure if the same solution is applicable here, but it's definitely worth checking out.

@mellinoe would you be able to verify if any of the referenced or seeded DLLs used in your bootstrap procedure and repo are native ReadToRun assembled or if they are MSIL? If they're not MSIL, we'll probably need to get that fixed.

**Comment by josteink** [comment]
I also see your recommend running build.cmd with the `linuxmscorlib` parameter. I may be wrong, but I think it should be `freebsdmscorlib`.

As you can see in build.cmd that should be a valid target.

**Comment by wolfspider** [comment]
@josteink Very cool, I will definitely give that a try and see how that works. I had read through that too fast but thanks to your comment I re-read it and realized there was a lot there which I missed.

@mellinoe I have been running your build script and its definitely an improvement over having to individually build and run these projects. There are some BSD specific things which may need to be added in there (for instance 'rid' is problematic in BSD for building corehost, I cannot build coreclr without specifiying 'clang3.7 or clang3.8') but I will try and get one good pass before offering up any of those suggestions quite yet.

**Comment by mellinoe** [comment]
Based on the above discussion, I think we know why the instructions didn't work, at least as given above.

* mscorlib should definitely be built with the `freebsdmscorlib` option, not the `linuxmscorlib` option. This one is pretty self-explanatory. I've only been doing my tests on a couple of Linux distros (Ubuntu 16.10, openSUSE 42.1), so this part slipped my mind.
* The assemblies included in the seed-cli folder are definitely Linux ReadyToRun images. I just pulled the managed seed assemblies from the latest build of CLI for Ubuntu 16.04, and all of the CLI builds have ReadyToRun images in them. Based on discussion in the linked issue, it makes sense that they worked for me on Ubuntu 16.10 and openSUSE 42.1, because both are in the Linux family.
  * If we had regular IL images in seed-cli, we could run crossgen on the assemblies after building coreclr, if we thought this was still valuable for the bootstrapped CLI.

I'm on vacation this upcoming week, but I think there's some clear ways forward for the above issues. I'll probably pick this back up when I return to the office.

> There are some BSD specific things which may need to be added in there

Definitely. Like I said, it's really rough and hacky right now; just something I fiddled with to automate the stuff I was doing for multiple platforms. If we think it's valuable then we can try to pull together something more robust.

**Comment by wolfspider** [comment]
@mellinoe Alright sounds good, I did try out the MSIL and DLLs built by dotnet/cli and dotnet.dll worked but organizing all the rest of them and the mscorlib + System.Private situation gets pretty unwieldy fast. Thanks for your consideration and enjoy your vacation I'm looking forward to looking at this again in the future

**Comment by joperezr** [comment]
@wolfspider @mellinoe sounds like this isn't happening anymore, is it ok to close this?

**Comment by mellinoe** [comment]
@joperezr We still don't support FreeBSD, or even support building on FreeBSD.

**Comment by wolfspider** [comment]
@joperezr @mellinoe Yeah, I'd still be interested in pursuing this actually soon- have been through the ringer at work but now I'm finally getting some free time so I can get into it again. I think we know why it doesn't build so the issue can be closed but was under the impression enough people signed up for the Port Team that it was an inevitability. Let me know your thoughts on this but either way I don't think this can be classified as an "issue" anymore.

**Comment by joperezr** [comment]
@mellinoe do we have any other workitem tracking the addition of support for FreeBSD?

**Comment by mellinoe** [comment]
I dunno, sort of. It looks like there's a few different discussions in our history.
https://github.com/dotnet/corefx/search?q=freebsd&type=Issues&utf8=%E2%9C%93.

**Comment by mellinoe** [comment]
Most of the discussion is here: https://github.com/dotnet/corefx/issues/1626

**Comment by joperezr** [comment]
ok, so I'll close this given this isn't an issue anymore, and if we need to then we can add one to track the onboarding of FreeBSD.

**Comment by mellinoe** [comment]
This is still an issue (building is not supported on FreeBSD), but it's fine to track it with #1626.
