### ISSUE TITLE
Append guidelines with how PR feedback should be addressed

### ISSUE THREAD

**Issue by Maxwe11** [dotnet/corefx#1063]
Pull request guidelines should contain something like "rule of a thumb" which rule how PR feedback should be addressed or how merge conflicts should be resolved.

As example consider #972. Commits like `Merge branch 'master' into Issue587` (aaa5434)
clutter history and should be avoided. `git rebase` should be used for updating branch with fix.
Other commits in this PR could be squashed.

As another example consider PR  #1003. It's initial commit of the library so it's OK to address feedback in a separate commit. However in this PR  feedback addressed twice and the second could be amended to the first.

Conclusion:
1. Merge conflicts should be resolved through rebasing.
2. PR feedback should be in a separate commit if it contains important changes. Changes like formatting or renaming variable introduced in PR are not important and could be addressed through amending/rebasing.

**Comment by krwq** [comment]
I agree only and only if each commit does produce successful build. I.e. if a commit broke the build then I'd rebase (to make sure we can binary search in the future)

**Comment by ellismg** [comment]
For short lived work, I agree with your point about rebasing against master (instead of merging).  For longer lived branches, I'm fine with merging master in at points, it's a better reflection of what's going on.

In general, I find it helpful for reviewing when folks don't prematurely rebase/ammend as part of the PR.  I find it very helpful to look at the individual feedback commits to make sure everything was addressed.  The GitHub flow for handling comments on commits which have been force pushed away is not great, IMHO.

If we want to establish a rule where folks can interactively rebase to clean up the interm commits after an LGTM but before a merge, I'd be fine to adopt such a rule.  For folks without commit access, I'd ask that they make a comment in their PR that they'd like a chance to rewrite history before merging.
