### ISSUE TITLE
VS 2015 Update3 .net core nuget problem

### ISSUE THREAD

**Issue by 188** [dotnet/corefx#10641]
Home computer and company environment VS 2015 Update3. Net core
But at home for the class library can get 1.1.0-1-21694 but in the company can only obtain "1.0.0"
What's going on, where you need to set up?
Such as:
``````
"Microsoft.AspNetCore.Authentication.Cookies": "1.1.0-alpha1-21694",
``````

**Comment by jasonwilliams200OK** [comment]
For future reference, this kind of issue belongs to https://github.com/dotnet/cli or the repo where the desired package lives: https://github.com/aspnet/Security.

You can do an organization-wide search https://github.com/aspnet or https://github.com/dotnet to locate the package, e.g. 

https://github.com/search?utf8=✓&q=org%3Aaspnet+org%3Adotnet+Microsoft.AspNetCore.Authentication.Cookies&type=Code&ref=searchresults

---

The reason you are getting v1.0.0 is because that is the latest version available on NuGet.org: http://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.Cookies/.

v1.1 is a preview version which is published at aspnet daily feed: https://myget.org/gallery/aspnetcidev

To use that feed, you can add a `NuGet.Config` file in your project root with the following contents:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="AspNetVNext" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
  </packageSources>
</configuration>
```

Then run `dotnet restore`. Note that this NuGet.config file is local to this project and will not affect any other project. If you wish to have pre-release packages available everywhere in system, you can add `<add key="AspNetVNext" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />` in global config file `%APPDATA%\NuGet\NuGet.Config`.

PS it is probably a good idea to use a *relaxed* version for pre-release packages, e.g.:

```json
"Microsoft.AspNetCore.Authentication.Cookies": "1.1.0-*",
```

so it always pick up the latest pre-release version when computer is connected to the internet.

**Comment by Clockwork-Muse** [comment]
Side note: In corporate environments they often have their own NuGet servers set up, with redirects.  You might need to validate this isn't affecting you also.

**Comment by joshfree** [comment]
Thank you for answering this question @jasonwilliams200OK and @Clockwork-Muse.  @188 feel free to reactivate the issue if there are more follow on questions.
