### ISSUE TITLE
Modifying corefx projects in Visual Studio is slow and hangs

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#10666]
Whenever I move, rename, delete or create a new file in any project in corefx (e.g. src/System.Reflection/tests/System.Reflection.Tests.csproj) VS, updated to the latest Community version, hangs on PC for about 30 seconds to a minute the second I complete that action.

During this time, I can't click, type or use VS. Its the sort of weird issue that doesn't bother you very much the first couple of times, but after months of VS hanging every time I modify the csproj file, things can get annoying.

I think the issue may be that VS is running `dotnet restore` every time, as I noticed in Task Manager that a `dotnet.exe` process spawns during the hang, and when VS stops hanging, the process is gone.

**Comment by Pilchie** [comment]
Tag @srivatsn and @davkean.

**Comment by davkean** [comment]
This is likely caused by lots of work done by the build process during a design-time build, @joshfree @weshaggard see: https://github.com/dotnet/roslyn-project-system/blob/master/docs/design-time-builds.md#diagnosing-design-time-builds for help to diagnose this, and see https://github.com/dotnet/roslyn-project-system/blob/master/docs/design-time-builds.md#designing-targets-for-use-in-design-time-builds for help to place nicely with this.

**Comment by hughbe** [comment]
By external issue, do you mean buildtools or VS? I don't think this is a problem with VS, but buidltools doing too much as David said.

**Comment by weshaggard** [comment]
I suspect it is likely being caused by doing to much stuff in our design-time builds as @davkean points out. @hughbe do you want to take a shot at investigating using the links @davkean provided to see if you can determine from the logs what is take so long?
