### ISSUE TITLE
Missing SqlDataAdapter

### ISSUE THREAD

**Issue by MelbourneDeveloper** [dotnet/corefx#10706]
I noticed today that the DataTable class exists in System.Data in .NET Core, but it also seems that there is no SqlDataAdapter, so there is no way to read the data in to the DataTable

**Comment by VitaliyMF** [comment]
@MelbourneDeveloper  DataSet/DataTable/DataRow (and related classes like DataAdapters) are not available in corefx at this moment; they are considered as over-complicated, too heavy structures and excluded from minimal low-level ADO.NET API set.

You may use EF Core API or 3-rd party libraries if you need schema-less or DataTable-like data access -- for example https://github.com/nreco/data (this is my library specially designed for .NET Core DAL needs).

**Comment by MelbourneDeveloper** [comment]
I implemented these in Silverlight. I could probably port the code. If it comes together, how do I submit the code to the repo?

**Comment by VitaliyMF** [comment]
@MelbourneDeveloper currently NReco.Data targets netstandard1.5 (primarily because it is enough for .NET Core) but I believe that it is possible to have build that targets earlier versions (netstandard1.3 or netstandard1.4 ?). I think it is better to create an issue in nreco/data project if you're interested in using it, and close this issue in corefx.

**Comment by danmosemsft** [comment]
@saurabh500 I'm assuming we're not planning to do this for 2.0 so mvoed to future. feel free to reverse that.

**Comment by saurabh500** [comment]
Added in https://github.com/dotnet/corefx/pull/20883
