### ISSUE TITLE
SharedLibrary libs on netcore50 don't use the latest code

### ISSUE THREAD

**Issue by SolalPirelli** [dotnet/corefx#10747]
I'm writing an UWP app which depends on a Profile111 PCL that uses `System.Linq.Expressions`, particularly the `Expression.IsTrue/IsFalse` methods, which means I need the fix from #3227 to avoid a crash.

I'm new to .NET Core stuff, but from what I've read it seems like I should only need to reference the newest possible `System.Linq.Expressions` package, e.g. `4.1.1-beta-24412-03`, which should contain the fix. But doing that changes nothing; my app still crashes.

So I looked at the contents of the package with ildasm, and it appears that the `netcore50` version doesn't contain the fix (looking at the contents of  `System.Linq.Expressions.Interpreter.LightCompiler::CompileUnaryExpression`), while the `netstandard1.6` version does, and UWP is using the former.

Is this expected, and if so, how can I get a fixed version of that package in an UWP app?

**Comment by weshaggard** [comment]
Yes this is expected. The reason that the UWP version of this library is frozen is because this library is part of our native SharedLibrary that is shipped independent of our nuget packages and cannot be updated easily. Unfortunately that means that you cannot easily get this fix for a UWP app until we can update this library in our native SharedLibrary. We are working on shipping a newer version of that but don't have a clear ETA yet because it requires a fair amount of work to happen before we can update it. 

I think the best you can do right now is try and workaround the issue.

**Comment by SolalPirelli** [comment]
OK, thanks for the info.

Is there a list somewhere of which corefx libs are part of this SharedLibrary, i.e. which can/can't be updated easily?

**Comment by weshaggard** [comment]
There is but I don't have access to it right now I will work on getting it published.

**Comment by weshaggard** [comment]
Sorry for the delay this dropped off my radar:

The list of implementation assemblies that are part of the existing shipped .NET Native shared library are:
```
System.Collections
System.Collections.Concurrent
System.Diagnostics.Tracing
System.Dynamic.Runtime
System.Linq
System.Linq.Expressions
System.ObjectModel
System.Private.CoreLib
System.Private.Interop
System.Private.Reflection.Core
System.Private.Reflection.Execution
System.Private.Reflection.Metadata
System.Private.Threading
System.Private.TypeLoader
System.Private.Uri
System.Reflection.Primitives
System.Reflection.TypeExtensions
System.Resources.ResourceManager
System.Runtime
System.Runtime.Extensions
System.Text.RegularExpressions
```

Those assemblies cannot be updated in nuget packages because they have to be coupled to the build of the shared library we ship with the .NET Native toolchain.

Note that list is a point-in-time with the current released set of tools and it may change in future tooling updates.

**Comment by SolalPirelli** [comment]
Thanks! 

Is this list going to be documented/maintained anywhere? Any plans to decouple them from the shared library?

**Comment by weshaggard** [comment]
I don't think there are plans for either, but I will let @yizhang82 @joshfree address some of those questions.

**Comment by yizhang82** [comment]
Note that the frozen assemblies are a thing of a past now. In the latest 5.3.0+ versions of Microsoft.DotNet.UniversalWindowsPlatform, we are also ship new versions of .NET native compiler with it. This means we no longer have to support backward compat with previous UWP meta package with newer version of compiler - we could simply roll forward. We didn't update those libraries in 5.3.0 for logistical / resource reasons, but as @weshaggard mentioned earlier, we are working on shipping a new set at some point in the future, which should have updated version of those libraries.
