### ISSUE TITLE
Should add a "Scale" property to System.Numerics.Matrix4x4

### ISSUE THREAD

**Issue by joelday** [dotnet/corefx#10772]
(From #10758)
```
        /// <summary>
        /// Gets or sets the scale component of this matrix.
        /// </summary>
        public Vector3 Scale
        {
            get
            {
                return new Vector3(M11, M22, M33);
            }
            set
            {
                M11 = value.X;
                M22 = value.Y;
                M33 = value.Z;
            }
        }
```

Thanks!

**Comment by mellinoe** [comment]
Could you provide a bit more detail to the proposal? Generally, we like to see a few more things before discussing a new API:

* Description: A more complete description of the new method, how it behaves in all different scenarios.
* Motivation: Why do we want to add the API?
* Use cases, with example code, etc.
* Precedent: Are there other libraries with functionality like this, or does this match other parts of the library?
* Do we want this on Matrix3x2 as well, for symmetry?

@shawnhar any thoughts on this one? We have an analogous Translation property already. Some other libraries (Unity, Monogame, SharpDX) do have this property.

**Comment by joelday** [comment]
Not an expert in this area by any stretch. Having given this more thought, it looks like the design intent of this API is to be reasonably agnostic of the context of their usage. So, I can see how it might be a bad design to present users with properties that may not actually behave as they imply. This is definitely in contrast to Unity, MonoGame and SharpDX.

So, despite being syntactically clumsy by comparison, I assume that extension methods may be the right thing to do.

**Comment by shawnhar** [comment]
This proposal is problematic because scale (unlike translation) is not necessarily a simple matter of reading or modifying the diagonal.  The proposed implementation is only valid for simple matrices that contain only scaling and/or translation transforms, but will not work as expected if used on a matrix which contains a rotation, shear, perspective projection, etc.

Assigning to the Translation property will replace any previous translation component of the matrix, but assigning to this Scale implementation will not necessarily do that.  The results depend on what type of transform was previously contained in the matrix, and in many cases will not be meaningful at all.

The robust way to emulate semantics of the Translation property setter would be:

- Decompose to extract existing scale component
- Concatenate with CreateScale(inverse of previous scale * new scale)

The getter would also need to perform a Decompose operation.  But that is expensive, and not always even defined (decompose will fail for some matrices).

I think it is better to rely on CreateScale for constructing scale transforms, plus matrix concatenation as needed.  That is both unambiguous and efficient.

**Comment by cdrnet** [comment]
Would have been great if these questions had been asked earlier as well. Operations like these make very clear that these matrix types are specifically designed for the context of spatial geometry, but do not fit to the broader filed of numerical methods.

**Comment by joelday** [comment]
@shawnhar big XNA fan, by the way.

**Comment by mellinoe** [comment]
I think the above description by @shawnhar explains why the proposed functionality won't necessarily behave as expected in all cases; I'm going to close this issue for now.
