### ISSUE TITLE
Root certificate cannot be found using X509Store.Certificates.Find where validOnly=true in Linux

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/corefx#10801]
Repro: https://gist.github.com/iamjasonp/db0a20a6c4cae5d55b383608941742bb

In Ubuntu14.04, when using the API X509Store.Certificates.Find(X509FindType, string, **bool validOnly**), if _validOnly_ is set to true, no certificate in the root certificate store is deemed valid and no certificates are returned in the X509CertificateCollection

This happens for both the CurrentUser and the LocalMachine _Root_ store, but not the _My_ store

Attached repro does the following: 

* Downloads certificates from WCF test services - a client cert and a root cert
* Writes both certificates to the CurrentUser:My and CurrentUser:Root store 
* Attempts to use X509Store.Certificates.Find to find the certs, _validOnly=true_
  * Expected result: certificates can be found
  * Actual result (Windows): certificates are found
  * Actual result (Ubuntu14.04): cert installed to user store can be found, cert installed to root store cannot be found

* Opens the LocalMachine:Root store (readOnly) 
* Attempts to find a well-known root cert,  _validOnly=true_
  * Expected result: certificates can be found 
  * Actual result (Windows): certificates are found
  * Actual result (Ubuntu14.04): certificate is not found 

Note that if validOnly is set to _false_ when looking in the root certificates stores, the certificates are found

**Comment by bartonjs** [comment]
Jason reported to me offline that this works using the 4.1.0 version of X509Certificates; so it was probably somehow broken during the X509 finalization cleanup change.

**Comment by bartonjs** [comment]
Okay, so if I comment out the part of FindCandidates that disposes things we didn't talk about (https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/OpenSslX509ChainProcessor.cs#L549-L570) the test passes; so that's clearly where the bug is.

Then I stopped, thought, and reshaped that part to account for the certs that get put in the systemStores collection.  And now the test suite is finalizing 5 cert handles.

So there's clearly some middle ground that I've missed.  If worst comes to worst I'll take finalizing and correct over better performance.

**Comment by bartonjs** [comment]
4 of the finalizes were coming from tests (notably, I think, ones reading the CU\My store, which means mine must have been empty when I last checked things for finalization).  And one of them revealed more of where the original bug was from having the same root cert in CU\Root and LM\Root.  Since the finalization count is down to 0; the "same root in both stores" test passes, and the new "are root certs validOnly=true findable" test passes, I think we're good.
