### ISSUE TITLE
Queue<T>.Enumerator still uses the modulo operator during MoveNext

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#10854]
Queue.Enqueue/Dequeue were changed a while ago not to use `div` since it's pretty slow (takes many cycles): #2515

We should do the same for [this method](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/Queue.cs#L290) which is currently still using modulo.

**Comment by GSPP** [comment]
`Dictionary` can be significantly sped up by doing `hashCode & (length - 1)`. I tried this in a custom hash table implementation.

This might dramatically worsen bucket distribution, though. So my idea to combat that was to run a cheap bit-based "whitening" hash on top of the user provided hash code. Should still be faster than the 31 cycles consumed by a 32 bit integer division. For example, `x ^ rol(x, 11) ^ rol (x, 17)` should be about 3 cycles.

**Comment by jamesqo** [comment]
@GSPP 

> So my idea to combat that was to run a cheap bit-based "whitening" hash on top of the user provided hash code.

That sounds interesting; do you have the source code for that still lying around?

**Comment by GSPP** [comment]
I never did that but I'd look at modern fast hashes such as CityHash and others and try to apply their round function. In my previous comment I just made up some bit mixing. I'm not too experienced with that.

If it's supposed to be fast there should be ILP. So the computation should fan out. I think the pattern `f(x) ^g(x) ^ h(x) ...` is nice for that. The Xors can be made into an aggregation tree. `x` is used multiple times but cloning the value of a register can be 0 cycles cost under some circumstances. That bodes well, too.

Maybe one of the components can be a multiplication or an addition with a random constant.

A first test should be how complicated the hash can be to still be faster than `%`. With ILP there could be dozens of instructions.

**Comment by omariom** [comment]
@GSPP 
> Dictionary  can be significantly sped up by doing  hashCode & (length - 1) . I tried this in a custom hash table implementation.

That would be great. This and dynamic dispatch to keys' `GetHasjCode`, `Equals`  was the reason I used a dictionary specialized for `int` keys.

**Comment by GSPP** [comment]
One more idea: Often, a dictionary is used in two phases: build and probe. So if the only supported write operation is adding the dictionary can become a little faster and smaller by removing free list management. I have an implementation of this and it helped.

The `Enumerable` algorithms using hash tables are all build/probe phase separated. They all could make use of this idea.

**Comment by jamesqo** [comment]
@omariom 

> That would be great.

That would also cause many more collisions, since masking via & would essentially mean we are ignoring many bits of the hash code.

@GSPP

> In my custom implementation I exposed the slots array. Dictionary lookups return an index into that array. That way the caller can perform one lookup and then mutate the value in place. This saves 50% of lookups for aggregations such as summing and counting. I think the new C# ref feature could be used to make that API nicer.

Hmm... seems like a nice idea. I could see it causing trouble though if (for example) the dictionary is resized, and it exposes implementation details, so it's probably unlikely to be approved.

**Comment by omariom** [comment]
@jamesqo
I mean hCode & (buckets.Length - 1). Fir ints it  works. Not so well for other keys. 

> it exposes implementation details

ref TValue value = TryGetValue(key);

The question is what to return if the  🔑 was not found.

**Comment by GSPP** [comment]
Of course, usability is terrible! :) Maybe useful for framework-internal code. The full class is like 100 lines. Can be copied around.

**Comment by jamesqo** [comment]
> Maybe useful for framework-internal code.

Yep, LowLevelDictionary probably: https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Collections/Generic/LowLevelDictionary.cs

**Comment by GSPP** [comment]
That looks super slow with the `Entry` class. Not sure what this algorithm design is good for.

**Comment by benaadams** [comment]
`% buckets.Length` is tricky to remove as `buckets.Length` is always a prime number

**Comment by jamesqo** [comment]
For anyone interested, I asked a question on Programmers StackExchange about this and got a couple of answers: http://programmers.stackexchange.com/questions/330310/is-it-possible-to-implement-a-well-distributed-hash-table-without-using-the-op

**Comment by benaadams** [comment]
Don't think you'll be able to change the number of buckets in Dictionary without both an analysis with the randomised string hashing function and a security review; there be dragons :dragon:

**Comment by blowdart** [comment]
What Ben said. We introduce a randomization into string hashing to prevent hashdos attacks in asp.net (and other sources of untrusted input). Using a cheaper hash is a security anathema - it would need careful examination because it carries a huge risk.

If you've not come across hashdos attacks before here's [the best explanation of a hashdos](http://www.anchor.com.au/blog/2012/12/how-to-explain-hash-dos-to-your-parents-by-using-cats/) I've ever seen.

**Comment by GSPP** [comment]
Well, hashdos protection is now there, is it not? The mod operator is not a hard obstacle to overcome when trying to cause collisions. All hash keys that I have ever seen in hash tables in .NET are quite easy to intentionally collide. So that's not much of a protection anyway.

**Comment by benaadams** [comment]
String doesn't use `String.GetHashCode` when added to a dictionary as key but uses `InternalMarvin32HashString`

**Comment by blowdart** [comment]
What Ben said. Again. String hashcodes use a custom algorithm which isn't open.

**Comment by GSPP** [comment]
Is that not one more reason this is safe to do? String is safe under any indexing scheme. The security review argument is more plausible.

**Comment by benaadams** [comment]
Removing the mod is for something faster that produces the exact same outcome is fine. 

Changing the number of buckets from prime to powers of two or changing how the hashcode resolves to a bucket both alter the collision behaviour and would effect the collisions of string keys; so it would require analysis and security review. 

Which due to the knock on work and cost, it would generate across teams at MS to validate it; I'd imagine it would have to be an exceptionally compelling improvement to get anywhere. As well as adding something seen as safe to something potential with a payout from @blowdart's [.NET Core and ASP.NET Core Bug Bounty budget](https://technet.microsoft.com/en-us/mt764065) - which would probably make him unhappy.

Also given the current string key hashing was devised after quite a major [hashdos vulnerability](https://www.troyhunt.com/fixing-hash-dos-good-and-proper-and/) with a full on registered government registered CVE (CVE-2011-3414); I doubt there is great appetite to change it; or have the experience again.

Likely the only way round it would be to split the dictionary behind the scenes into a string key variant that's the same and a non-string key variant with changes; but that's probably not really worth it; just to remove a mod operator... :disappointed:

**Comment by benaadams** [comment]
I'm just highlighting changing it will be an uphill battle at night on sand-dunes in a hurricane; might be possible, but will be very hard. There are plenty of other areas that would benefit much more with the effort it would take.
