### ISSUE TITLE
DataTypeAttribute.GetDataTypeName() throws IndexOutOfRangeException

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#11005]
The following test demonstrates the bug, found in #11004

```
[Theory]
[InlineData((DataType)(-1))]
[InlineData(DataType.Upload + 1)]
public static void GetDataTypeName_InvalidDataType_ThrowsIndexOutOfRangeException(DataType dataType)
{
    DataTypeAttribute attribute = new DataTypeAttribute(dataType);
    Assert.Throws<IndexOutOfRangeException>(() => attribute.GetDataTypeName());
}
```

This is because the method `EnsureValidDataType` should be changed to:

```
private void EnsureValidDataType()
{
    if (DataType < DataType.Custom || DataType > DataType.Upload)
    {
        throw new InvalidOperationException("DataType is Invalid");
    }
    if (DataType == DataType.Custom && string.IsNullOrEmpty(CustomDataType))
    {
        throw new InvalidOperationException(string.Format(CultureInfo.CurrentCulture, SR.DataTypeAttribute_EmptyDataTypeString));
    }
}
```

/cc @stephentoub (not sure who the code owner for this class is, or whether this code is legacy and shouldn't be touched)

**Comment by jasonwilliams200OK** [comment]
Perhaps #11004 and not #1104? :)

**Comment by hughbe** [comment]
@jasonwilliams200OK  Yup, my bad!

**Comment by ajcvickers** [comment]
@hughbe After analyzing this we don't think that there is a compelling enough case to make a change here. It is true that a case can be made for InvalidOperationException instead of IndexOutOfRange exception, but both have reasonable interpretations. Also, changing the exception type thrown would be a breaking change. We think this would be a relatively minor breaking change in this case, but only because we don't think much code would be catching the exception. But that then strengthens the case that there is minimal value in making the change. Therefore, on balance, we think this should stay the way it is.
