### ISSUE TITLE
A duplicate X509 certificate can be added to the user certificates store when using the X509Store API

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/corefx#11016]
This is an edge case race that happens when a certificate is stored using the X509Store.Add API

When adding a previously-unknown certificate to a certificate store in *nix, it is possible that the same certificate can be added twice. The certificate filename will look something like C7979286A20741AE49436142E9D9CD72BA2F59F4.pfx, and C7979286A20741AE49436142E9D9CD72BA2F59F4.1.pfx 
in ~/.dotnet/corefx/cryptography/x509/_storeName_

This is not known to happen in .NET Core or .NET Desktop in Windows (probably since certs are not stored on the filesystem)

Note that I think this will happen only in very rare cases where we're adding the same cert on multiple threads/processes simultaneously - hence it may be a uniqueness in the way we work with our tests. 

I will look separately into preventing this from happening in our test bed

cc: @bartonjs

**Comment by bartonjs** [comment]
Yeah, there are two choices here:
* Make race conditions suffer: Declare this as an unsupported behavior.  Store writes are (in the wild) pretty rare. It also feels pretty unusual for things to care that there's more than one match. -- Certainly there are domain exceptions to both of these statements.
* Make every load suffer: Read the collection into a HashSet (or other good de-duper) every time we're loading from disk.
* Risk deadlock: Try to take some sort of machine-wide lock.  Doesn't solve the problems with any sort of network mount, and is now able to be deadlocked by external processes taking the lock and giggling.

@stephentoub: Would you care to give a off-the-cuff feeling?  How do you feel about deduping a collection of 0 to 1000 items?  (5ish for personal stores, 300ish for machine stores; 1000 seems pretty excessive, so it's my design bar).  When I started typing I was thinking "unsupported", but now I'm feeling like "but, algorithmically the fix is easy..."

**Comment by stephentoub** [comment]
> How do you feel about deduping a collection of 0 to 1000 items?

What's involved in de-duping them?  Would we have to force the loading of a bunch of additional state / perform lots of additional allocations / etc. in order to get the relevant state necessary for the comparison?

**Comment by bartonjs** [comment]
> What's involved in de-duping them?

* A deduper (such as loading into a HashSet instead of / before the current List; or using linear deduping).
* PAL-querying the cert issuer (cached for future calls)
* PAL-querying the cert serial number (cached for future calls)
* PAL-querying the cert thumbprint (cached for future calls)

The last three are the work required for the equality check.

**Comment by bartonjs** [comment]
Actually... I think I should just dedup on read. The system stores already get deduped because we were loading from two places and it "felt weird" that every cert came back twice on Ubuntu (which uses both mechanisms).

**Comment by stephentoub** [comment]
> The last three are the work required for the equality check

In most scenarios, are these likely to be needed, such that we're just loading the state earlier than we otherwise would but not loading state we wouldn't otherwise load?

> I think I should just dedup on read

Ok.
