### ISSUE TITLE
Release these reserved names: COM1-COM9, LPT1-LPT9, CON, AUX, PRN, and NUL

### ISSUE THREAD

**Issue by be5invis** [dotnet/corefx#11033]
Use the `\\?\` prefix to access them internally.

**Comment by JeremyKuhne** [comment]
@be5invis Can you clarify what you're asking for? Reserved where? Thanks!

**Comment by be5invis** [comment]
@JeremyKuhne You cannot create ANY file named them, in ANY directory, with ANY extension, on Windows. This is a limitation of the “default” win32 API, because they are mapped to device names (like, `NUL` means “Null Device”), early in 1970s. Prefixing these paths with `\\?\` will can this problem.

**Comment by JeremyKuhne** [comment]
Thanks for the details!

.NET allows you to create them yourself now if you really want to as we allow you to use `\\?\` and we don't mess with the path if you do (`\\?\C:\Test\LPT1`).

I don't, however, recommend doing so. As you point out, the Win32 API will treat these differently. Most applications aren't going to have logic to allow for legacy device names used as file names. I would also be shocked if .NET was bug free with these- too many places where filenames are recombined with base paths.

Windows is unlikely to ever remove the mapping as the command shell and batch files depend on the current behavior (`copy con foo`, `copy foo bar > nul`). That said, if Windows ever _does_ remove it everything should work fine for .NET apps.

**Comment by be5invis** [comment]
@JeremyKuhne Maybe at least .NET can limit these names in "direct occur" directly. Like, `./LPT1` -> file, `LPT` -> device.

**Comment by JeremyKuhne** [comment]
Generally speaking we're trying very hard to not code specifically to internal details of Windows APIs. Even if we do get things right, doing so risks breaking on future versions of Windows. Trying to be helpful here is risky and could either break with a future Windows change or inhibit them from making a change (say, if they decided to remove or alter the way they handle legacy device names).

As a concrete example: The well-meaning code we had in `Path.GetFullPath()` was full of issues because we didn't mimic `GetFullPathName` correctly. Paths that you could create from the command prompt _without_ `\\?\` .NET couldn't handle.

What I _have_ been doing that impacts this is using \\?\ internally in some cases where we're iterating a fully normalized path (recursive directory deletion for example). I can't do it everywhere, however- allocating extra strings can really impact perf, as paths can be up to 64K in size.

**Comment by JeremyKuhne** [comment]
@be5invis I'm going to close this for now. If you still want to discuss the issue feel free to reopen. If you find any places where we fall over on legacy device filenames please open issues so we can investigate the plausibility of handling them.
