### ISSUE TITLE
`ParallelQuery.Reverse().Take(n)` returning elements from the portion not taken

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#1106]
On unordered `ParallelQuery<int>`s created via `ParallelEnumerable.Range(start, count)`, `Enumerable.Range(start, count).AsParallel()`, and `Partitioner.Create(array).AsParallel()`, running `Reverse().Take(n)` (and `Reverse().Skip(n)`) yields elements from the portion not taken.  
For example:

    ParallelEnumerable.Range(0, 16).Reverse().Take(8)

...will occasionally return 1.  Or 5.  Or 7 (depending on threading whims).   
The expected result is the set of integers from 8 - 15.  Creating and querying via:

    new int[] {0, 1, ... 14, 15}.AsParallel().Reverse().Take(8)

... returns the expected results.  The expected behavior matches that observed in the current consumer .net release.  Note that `Skip`/`Take` alone return the expected results for unordered collections (although the elements aren't returned in source order).

I suspect this is happening because `Reverse()` is too restrictive on the state of the index (`ReverseQueryOperator.cs`, line 42); it only allows `Indexible`, or sets the index state to `Shuffled` (whereas `Skip`/`Take` are both more permissive).  I suspect this can be relaxed to `Correct` (or maybe `Increasing`).
The previous also implies that the results of `ParallelEnumerable.Range(...)` isn't set to `Indexible`, which I would have thought possible (given that the index/element at should be available in constant time)

**Comment by stephentoub** [comment]
Thanks, @Clockwork-Muse.  I appreciate the thoughtful write-up.

> The expected behavior matches that observed in the current consumer .net release.

Can you elaborate on this?  When I run the following program on the desktop release, I see pretty much every iteration yielding elements lower than 8.
```
using System;
using System.Linq;

class Program
{
    static void Main()
    {
        for (int iteration = 0; ; iteration++)
        {
            foreach (int i in ParallelEnumerable.Range(0, 16).Reverse().Take(8))
            {
                if (i < 8)
                    Console.WriteLine(iteration + ": " + i);
            }
        }
    }
}
```

> The expected result is the set of integers from 8 - 15.

Why is that the expectation?  It's unordered; logically Reverse can reverse its input, but if the input is unordered, so too will be the output.  If ordering is required, that's what AsOrdered() is for. It's possible we could do better in certain circumstances, but I don't think we'd want to guarantee that. 

> The previous also implies that the results of ParallelEnumerable.Range(...) isn't set to Indexible

It's not.  With some work it could probably be made OrdinalIndexState.Correct, but RangeEnumerable derives directly from ```ParallelQuery<TOutput>```, which doesn't have any notion of ordinal index state.  The range query type would likely need to be changed to derive from ```QueryOperator<TOutput>```, which is the first base type in the hierarchy that provides that concept.  At that point it could probably override OrdinalIndexState to return Correct, though I've not actually tried.  With more work it could probably also be made Indexible, but again, I've not investigated.

At the moment I don't consider anything here a bug, though you're welcome to try to convince me otherwise :smile: If you wanted to experiment with changes to Range to have it produce the behavior you're expecting, you're also very welcome to submit a PR for it, but this is complicated code with the potential for far-reaching performance implications, so we'd need to see evidence that the changes don't have negative consequences (and unfortunately at the moment we don't have such a performance system set up on GitHub.)

**Comment by Clockwork-Muse** [comment]
I was expecting those results because of how `Skip` and `Take` behaved - they return that portion of the list specified, even when the list is unordered.  In that vein, `Reverse` seemed like it would behave similarly (and not disrupt `Take`/`Skip`)

It also seems I got some of my wires crossed.  I was testing against `Skip(n)` (extrapolating for `Take`), and misread one of my conditions/results.  On both corefx and the current release:

    static void Main()
    {
        for (int iteration = 0; ; iteration++)
        {
            foreach (int i in ParallelEnumerable.Range(0, 16).Reverse().Take(8))
            {
                if (i >= 8) Console.WriteLine(iteration + ": " + i); // I flipped the condition here
            }
        }
    }

... has been running for several minutes without printing anything.  Which means that it's only including stuff from the portion I was expecting to **exclude**.  That feels even stranger - it's essentially ignoring the `Reverse()`.  Flipping the condition and changing to `Skip` produces identical behavior. 
 (Okay, granted, if `Reverse()` is something of an undefined operator for unordered queries then selecting any particular set would be fine.  But to only use elements from the opposite portion?  Especially since, again, arrays have the behavior I was initially expecting.)

**Comment by stephentoub** [comment]
> it's essentially ignoring the  Reverse() 

It's unordered... that's exactly what it's doing :smile: https://github.com/dotnet/corefx/blob/master/src/System.Linq.Parallel/src/System/Linq/Parallel/QueryOperators/Unary/ReverseQueryOperator.cs#L184

> Especially since, again, arrays have the behavior I was initially expecting

Understood.  It's just the difference between whether something is guaranteed or not.  The implementation over arrays is behaving more aggressively towards ordering in the unordered case than it needs to, and the implementation over ParallelEnumerable.Range isn't.

It's possible that there'd be little downside to changing ParallelEnumerable.Range to indicate that its results are indexible.  At present I just don't know what the downstream implications of that would be, and so since I don't believe there's actually a bug here (but rather a difference in expectations), I'd want to be very sure there were no negative consequences to such a feature improvement before taking it (or at least completely understand what those negative consequences were so that we could appropriately weigh them against the benefits).

**Comment by Clockwork-Muse** [comment]
Well, okay, if that's the designed behavior...
It just wasn't what I was epecting! :)

Now I have to figure out what I want to do for the combination tests in those cases....
