### ISSUE TITLE
Port T:System.Security.Cryptography.DESxx

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#11116]
Okayed by the crypto board as it's so heavily used but it must be [EditorBrowsable(Never)] to strongly discourage its use.

```
T:System.Security.Cryptography.DES
T:System.Security.Cryptography.DESCryptoServiceProvider
```
Usage is up to 6% of the tier 1.

**Comment by vincentshow** [comment]
Is there any other solution to resolve des problem before 1.2.0? I'm migrating an old app to dotnet core which has a module that will provide encrypt strings (using des algorithm) to its sub systems. The problem is that these sub systems can't be migrated to dotnet core  by now, so i have to use des algorithm to garentee this is compatible with those sub systems. much thanks...

**Comment by steveharter** [comment]
Is it possible to change to TripleDES? That is available now and like DES it derives from SymmetricAlgorithm so the programming model is the same.

**Comment by vincentshow** [comment]
Sorry, I can't change to TripleDES, because the sub systems must use des algorithm when they consuming the encrypted strings send by current app before they're migrated to dotnet core . However, as this can't be resolved in backend I try to search solutions using front techs, javascript for example. Fortunately, there is an famous library called crypto-js. Thank you, anyway
