### ISSUE TITLE
ZipEntry returns truncated stream on .NET Core (data loss)

### ISSUE THREAD

**Issue by qmfrederik** [dotnet/corefx#11161]
The attached `.zip` file contains a single entry which gets truncated when opened in update mode. The `.zip` file was originally an `.ipa` file (iOS application), and was generated with the Apple toolchain.

The entry reports a size of 246000, but the stream which represents the entry has a length of 245760 bytes, resulting in 1240 (`0xF0`) bytes missing.

This snippet contains the code which was used to open the zip entry:

```
using (Stream stream = File.Open("data-write.zip", FileMode.Open, FileAccess.ReadWrite))
using (ZipArchive archive = new ZipArchive(stream, ZipArchiveMode.Update))
{
    var entry = archive.GetEntry("A/B/C/D");
    var size = entry.Length;

    using (Stream entryStream = entry.Open())
    {
        Assert.Equal(size, entryStream.Length);
    }
}
```

After this snippet executes, .NET Core will update the `.zip` file and the incorrect size data will be written to disk - effectively resulting in data loss.

The code behaves as expected on .NET 4.6.1. 

```
dotnet test -f netstandardapp10
(...)
=== TEST EXECUTION SUMMARY ===
   compression-bug  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0.135s

dotnet test -f net461
(...)
=== TEST EXECUTION SUMMARY ===
   compression-bug  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.134s
```

I've tried with a couple of zip utilities. They all extract the correct data (same behavior as .NET 4.6.1). Furthermore, the CRC32 data matches the data returned by .NET 4.6.1.

While investigating the issue, I also noticed that `ZipEntry` does not expose the CRC32 field and does not use the CRC32 checksum to validate the data being read. This may have helped me catch the issue earlier.

(I tried to debug but couldn't get the debugger working, #11087)

__Repro files__
* .zip file which is not being read correctly by .NET Core: [data.zip](https://github.com/dotnet/corefx/files/438096/data.zip)
* Code used to reproduce the issue: [Program.zip](https://github.com/dotnet/corefx/files/438097/Program.zip)

**Comment by ianhays** [comment]
Thanks for the detailed repro. It looks the behavioral change was introduced by https://github.com/dotnet/corefx/commit/94ba7b83fcf5753437cc50289d95a9e6ff8148d5 - the commit where I modified our decompression to use ZLib instead of the old managed DEFLATE implementation. Using the native decompression results in the size difference, while using the managed one passes without issue.

I'm guessing that zlib is truncating those trailing zeroes since they don't contain anything. I tested this with several versions of zlib: 1.2.3, 1.2.8, and intel. They all have the same result. If we change the value in the zip that determines the compressionmode of the entry to instead treat it as uncompressed, then pipe that uncompressed data to a zlib DeflateStream and decompress it that way, we get the same result. If we instead pipe that data to a managed DeflateStream, we get the 246000 length data.

**Comment by qmfrederik** [comment]
@ianhays Thanks for looking into this. Since you've mentioned that it seems to be related to the usage of zlib, and because [zlib includes a sample .zip utility](http://www.zlib.net/zlib_faq.html#faq11), I gave it a shot and tried to extract the file using zlib's `miniunz` (on Linux):

```
wget http://zlib.net/zlib-1.2.8.tar.gz
tar -xvzf zlib-1.2.8.tar.gz
cd zlib-1.2.8/
./configure 
make
cd contrib/minizip
make
wget https://github.com/dotnet/corefx/files/438096/data.zip
./miniunz -e data.zip
``` 

and when inspecting the size of the extracted file:

```
$ ls -l D
-rw-rw-r-- 1 qmfrederik qmfrederik 246000 Dec  7  2015 D
```

So it appears zlib's `miniunz` utility is capable of using the zlib deflate stream and extracting the file correctly.

**Comment by ianhays** [comment]
I think it's likely that we're interfacing with ZLib under some assumptions that were valid with the managed deflater but invalid with zlib. We don't ever flush on inflating, so it's possible that's an issue. I'll play around with it a bit more.

**Comment by ianhays** [comment]
Yeah, we need to be flushing at some point during inflation. When I add a zlib `Finish` flush to the end of the DeflateStream `Read` method we get the correct number of bytes.

The issue here is that the file size is very close to a multiple of our default Stream buffer size (81920). On the third read, the buffer is filled and those extra zeros are cached by zlib. However, on the fourth and final read our DeflateStream code immediately returns zero because there's no more bytes to pass to zlib, ignoring the fact that there are existing inflated bytes waiting to be flushed.

Since we can't add a final flush during disposal like we do during deflation, we should add a check to Flush when we otherwise wouldn't return any bytes from a Read. I'll work on a fix.

Thanks again for raising the issue! This is a good edge case I need to add a unit test for.

**Comment by qmfrederik** [comment]
@ianhays Thanks!
