### ISSUE TITLE
No way to get the simple name parts of a TypeRef Namespace without many allocations.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/corefx#11160]
Currently, if you are using MetadataReader and you have a handle to a TypeReference, then the only data exposed is:

```c#
        public StringHandle Name { get; }
        public StringHandle Namespace { get; }
        public EntityHandle ResolutionScope { get; }
```

If the typeref is for a type in a namespace called "A.B.C"
This means that if you want the constituent namespace parts (like "A", "B", "C"), you first need to allocate the full string and then split it into smaller strings.  Contrast this to the TypeDefinition where you can get handles to the NamespaceDefinition and can get just the Name off of it and it's parents.

This is an issue in Roslyn because it causes allocations we don't want when we just want to get the namespace pieces (like we do for TypeDefs).  A api to expose the individual pieces would be appreciated.

**Comment by CyrusNajmabadi** [comment]
tagging @tmat

**Comment by tmat** [comment]
@nguerrera FYI
I can see a few ways we can approach this:
1) Add more string APIs to ```MetadataStringComparer```. Unfortunately the name is too specific for the class to contain methods like Split, IndexOf, etc. ...
2) Add MetadataReader.GetNamespaceParts(StringHandle): struct enumerator returning StringHandles for each dot-terminated part (and the last part).
3) Add MetadataReader.GetStringReader(StringHandle): StringReader, where StringReader would be like BlobReader but operating on chars. Any string operation could be implemented on top of that.

I like option (3) since it allows to optimize other string operations, like finding the actual name of a generic type from "backticked" name (```List``` from ```List`1```) without allocating the original string.

**Comment by tmat** [comment]
Thought more about (3) -- since the strings are actually UTF8 (other than projections, which can be presented as UTF8 on demand) it would simply suffice to expose GetBlobReader(StringHandle). The caller would work with the raw UTF8 blob, which is fine. Splitting by '.' or '`' (or any other ascii char) are still simple operations on UTF8 string.

**Comment by nguerrera** [comment]
Perhaps we should have a ReadUTF8 that accepts a list of terminators. So that a caller just interested in getting everything before '.' or '`' doesn't have to deal with UTF8 decoding, etc.

**Comment by CyrusNajmabadi** [comment]
Even though it would be highly specific, i'd be happy with a struct based iterator that just allowed me to get the specific name pieces of the namespace.  If you want to expose more atomic operations that we could build that function out of, that would be fine.  But if that's harder, then just getting the namespace pieces would work.

Thanks!

**Comment by nguerrera** [comment]
```

var reader = mdReader.GetBlobReader(typeRef.Namespace);
while (reader.RemainingBytes > 0)
{

**Comment by tmat** [comment]
@nguerrera Perhaps. For now I'd just prefer to not add additional methods to BlobReader and see what customers need in time. The problem of adding helpers like IndexOf/ReadTerminatedString is they are more complex to implement for non-ASCII terminators. I can't spend too much time on this atm. With my change as is one can get pointer to the string and implement literally anything on top of that.

**Comment by nguerrera** [comment]
Fair. Could we just throw on non-ASCII terminator? I don't think there are genuine use cases for it? The helper doesn't have to be done now, but might be nice for callers that want to avoid allocs, but don't want to drop down to pointers and raw bytes.

FWIW, I started typing this to see what enumeration might look like with such a helper added to BlobReader, in case we want to discuss that further. 

``` C#
var blobReader = mdReader.GetBlobReader(typeRef.Namespace);
while (reader.RemainingBytes > 0)
{
    string part = blobReader.ReadUTF8Terminated('.');
    ...
}
``

**Comment by tmat** [comment]
@nguerrera Yeah, I'm not against such a helper in general, just don't want to add it at this point.
