### ISSUE TITLE
Socket Poll during non-blocking connect broken on linux

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/corefx#11174]
I am writing a library that requires a timeout on a socket connection from a client to a server. I tried implementing this using async methods, however this library needs to support net451 and netstandard, which both do not support the same async methods. In C previously, I've seen programs that do a non blocking connect() call, and the a poll() call to detect if the socket has finally connected, and timing out after enough poll failures have passed. The code below is a simplified version of what I have ported, and it works perfectly on windows, both with .net 4.5.1 and .net core RTM. The poll call returns false and loops until timeout. However, on linux and mac, the poll call always returns true, even when I can verify there is no socket listening on that port. If I try to call connect after the poll call returns true, I end up getting a ConnectionRefused error code. Is there a specific setting that would need to be called additionally on unix systems to make this work properly, or is this an internal library issue?

```
Socket socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);

socket.Blocking=false;

try {
  socket.Connect(IPAddress.Loopback, 2222);
} catch (SocketException ex) {
  if (ex.SocketErrorCode == SocketError.WouldBlock || ex.SocketErrorCode == SocketError.InProgress) {
    while (true) {
      if (socket.Poll(1000, SelectMode.SelectWrite) {
        // Socket connected (or should be anyway)
        return;
      } else {
        // Check if timed out here
      }
    }
  }
}
```

**Comment by ericeil** [comment]
It could just be that on Linux/OSX, the OS fails the connection attempt very quickly, because it knows that you're connecting to a non-existent port on localhost. 

> If I try to call connect after the poll call returns true, I end up getting a ConnectionRefused error code.

Does the `connect` call return immediately?  If so, it sounds to me like `Poll` is correctly indicating that the `Connect` operation is complete.

**Comment by ThadHouse** [comment]
Oh. I just tested going to a non-loopback address, and the call properly worked.  So I think that is fixed.

However, there is still a little oddity on the Localhost attempt. socket.Connected returns true after that poll call returns true, even though it probably shouldn't. That's not as big of an issue, but that probably actually is a bug.

**Comment by ericeil** [comment]
Thanks for the confirmation of the correct behavior, @ThadHouse.  I think it's also correct for the `Connected` property to return true in this case.  It looks like `Connected` actually does a poll internally if there's a pending non-blocking `Connect` call, specifically so that it can return "true" once the connection is established.
