### ISSUE TITLE
Different behavior of Console.Read() on linux and windows

### ISSUE THREAD

**Issue by devlo** [dotnet/corefx#11206]
Is it normal that on windows this code:

```
Console.WriteLine(1);
int r1 = Console.Read();
Console.WriteLine(2);
int r2 = Console.Read();
Console.WriteLine(3);
Console.ReadKey();
```

Will block on first Console.Read() and then it will just pass to the end?

On linux (Ubuntu 16.04) it will block on every Console.Read().

**Comment by stephentoub** [comment]
I believe what you're seeing is a difference in the newline characters between Windows and Unix.  On Unix, a newline is a single character, a '\n'.  On Windows, it's two characters, a '\r' and a '\n'.  Console.Read() blocks until it gets the next character.  So on Unix, each time you press Enter, you're getting one character which will satisfy one Read.  On Windows, each time you press Enter, you're getting two characters, which will satisfy two Reads.

As this is by design, I'm going to close out this issue; please feel free to re-open if you continue to see different behavior from this.
