### ISSUE TITLE
System.IO tests aborting in dev/api

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#11203]
This is happening frequently, e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/dev_api/job/ubuntu14.04_release_prtest/504/
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/dev_api/job/ubuntu14.04_release_prtest/511/
```
./corerun xunit.console.netcore.exe System.IO.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
  
  Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.IO, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  /mnt/j/workspace/dotnet_corefx/dev_api/ubuntu14.04_release_prtest/bin/tests/AnyOS.AnyCPU.Release/System.IO.Tests/netcoreapp1.0/RunTests.sh: line 293: 45732 Aborted                 (core dumped) ./corerun xunit.console.netcore.exe System.IO.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
```

**Comment by jamesqo** [comment]
This may/may not be relevant, however I am getting the same error ("the located assembly's manifest definition does not match the assembly reference") when trying to debug some of the System.Linq tests within Visual Studio.

![linq_tests](https://cloud.githubusercontent.com/assets/9159214/18030646/b5fb1d92-6c8b-11e6-8c7e-4366e3fe2d22.PNG)

It is happening for every test method.

**Comment by stephentoub** [comment]
cc: @weshaggard, @joperezr, @ericstj

**Comment by stephentoub** [comment]
cc: @danmosemsft

**Comment by joperezr** [comment]
I suppose this is the one where you said there is a fix in master already. I'll work on a merge from master to dev/api once I'm done with the ns1.7 CI tests.

**Comment by stephentoub** [comment]
> I suppose this is the one where you said there is a fix in master already

@joperezr, is the "you" here me?  I'm not aware of any fix.

**Comment by joperezr** [comment]
sorry @stephentoub yeah, I meant you. I was talking about #10943 because initally I though they were related, but looks like they are not.

**Comment by ericstj** [comment]
I believe this is happening because the CI specifies TestWithLocalLibraries.  It looks like that will cause the test projects to try to pick up whatever dll is in the root (eg: TargetGroup='') folder for the library.  Now that targetGroup='' build for FileSystem is a netstandard1.1 build this causes a problem when TestWithLocalLibraries=true.  The netstandard1.0 build of the tests is picking up the netstandard1.1 build of filesystem.  The reason this is intermittent is that TestWithLocalLibraries checks at the time the test is executing if any dependency may have already been built.  It appears that some times (passing) FileSystem hasn't yet built at the time the tests are running, and other times (failing) it has.

It's a bit concerning that we're not building all binaries before building tests.  @chcosta that may be a side-effect of some of the build workflow stuff, for example if it was causing the build traversal filtering to be different.

As far as fixing this issue, I think the right thing is to turn off TestWithLocalLibraries.  That thing is an abomination.  If projects need to use a live build of a library they should reference that via a project reference.  I believe @Priya91 fixed the issue where we weren't using live shims, but we should make sure that disabling TestWithLocalLibraries doesn't break that.

**Comment by ericstj** [comment]
Actually it looks like using the live shims is conditioned on the same property.  https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets#L84

Probably we should make that either be a seperate property or the default, then stop using TestWithLocalLibraries.

**Comment by JeremyKuhne** [comment]
I agree with @ericstj. I think we should not be using `TestWithLocalLibraries` for managed code as it is non-deterministic.

**Comment by stephentoub** [comment]
We introduced TestWithLocalLibraries when we had week+ delays between changes being made and those changes getting consumed by the other libraries that depend on them in corefx.  With our move to updating dependency versions typically at least once a day if not multiple times a day, it's less of a concern... but I still have a concern that we're not using the latest code in library A when running library B's tests, and in that regard I still think there's value to TestWithLocalLibraries.  In the workaround for that is to use P2P references, then maybe we should be using P2P references for everything, or TestWithLocalLibraries should be some kind of automation that effectively turns all references into P2P references prior to doing the build.

**Comment by JeremyKuhne** [comment]
Btw, the change that is exposing the `TestWithLocalLibraries` problem is: https://github.com/dotnet/corefx/commit/c31504af97642e9700b01258d72073fd91700298

**Comment by ericstj** [comment]
@weshaggard @chcosta what's your opinion here?

We could do what Steve suggests, but I bet we'd have a bit of perf issues to work out. :wink:

**Comment by danmosemsft** [comment]
This is causing pain to several engineers at present. It sounds like there's a switch we can throw that will make the builds slower (and less up to date) in the near term? If so I suggest we throw it to get folks unblocked while the discussion continues about doing this better.

**Comment by sepidehMS** [comment]
I believe the build failures I'm getting on https://github.com/dotnet/corefx/pull/11099 are also related:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/dev_api/job/ubuntu14.04_release_prtest/523

I'm getting the following error on many tests in runtime:
`System.TypeLoadException : Could not load type 'ConfiguredTaskAwaiter' from assembly 'System.Threading.Tasks, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.`

Background info: This is a nested type inside a type I'm moving from System.Threading.Tasks down to System.Runtime and the typeforward for the containing type has been added (System.Threading.Tasks -> System.Runtime)
This failure does not repro locally. Can anybody confirm if this could be hitting the same issue?

**Comment by stephentoub** [comment]
> I'm getting the following error on many tests in runtime

Have you rebased recently?  That sounds like https://github.com/dotnet/coreclr/pull/6899

> It sounds like there's a switch we can throw that will make the builds slower (and less up to date) in the near term? If so I suggest we throw it to get folks unblocked 

+1.  I was merely saying that we should understand the benefits we're losing by dumping TestWithLocalLibraries, and determine if/how to get that back.

**Comment by chcosta** [comment]
If TestWithLocalLibraries is going to stay, it needs to be something more explicit than just looking for anything available...

https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets#L97

For our official builds / testing, we're building at least some of these tests against the most recent packages instead of a direct implementation (I looked at System.IO.Tests to validate).  In our official builds we test against the most recent packages. I had thought that we were following the same practice and building this test against packages in the CI as well.

I'd be surprised if we weren't building all binaries before building tests, but I'll have to dig around to ascertain if this is true for the CI system and in particular for Unix on the CI system.

**Comment by sepidehMS** [comment]
> Have you rebased recently? That sounds like dotnet/coreclr#6899
Yes, I have rebased. I could finally repro the failures locally and they only happen when building with TestWithLocalLibraries

**Comment by danmosemsft** [comment]
@joperezr Is removing TWLL from the groovy file.

**Comment by weshaggard** [comment]
I agree that TestWithLocalLibraries should be removed as it has done nothing but cause trouble as it has morphed over time. Beyond doing what it said there were issues with CI in the past were we didn't have msbuild support on all the platforms so we couldn't restore all the necessary packages. I think that is no longer an issue so we should stop using TestWithLocalLibraries.

For now I think the best option is to add P2P references were needed, I don't think we should do that for everything by default at this point as I agree with @ericstj that will likely cause some perf issues and still might not be what we want in all cases (i.e. some projects do still want to run on older versions). 

Another option if we want to test with all the latest live built libraries is to build the product before the tests and then point the tests to the local built packages, just like we do for our official test builds.

**Comment by joperezr** [comment]
I've merged my change that removed TestWithLocalLibraries from the CI, @stephentoub do you want me to close this issue and reopen if we hit this again? or should we keep this open until we verify we haven't hit this for a couple of days?

**Comment by stephentoub** [comment]
We can close it and reopen if the issue happens again.
