### ISSUE TITLE
RSA.Create key size inconsistency

### ISSUE THREAD

**Issue by leastprivilege** [dotnet/corefx#11263]
When I call `RSA.Create` on Windows/NETCoraApp1.0 I get a Cng key with 2048 bit key size.

When doing the same on .NET 4.52 - I get an RsaCryptoServiceProvider with only 1024 bits keysize.

I need at least 2048 bits - how can I control that?

**Comment by PinpointTownes** [comment]
This will be fixed by https://github.com/dotnet/corefx/issues/8688 (it will require a newer .NET Standard/.NET Desktop contract, tho).

In the meantime, you basically have 2 options: use `CryptoConfig` to replace the default `RSA` implementation by `RSACng` or re-instantiate a `RSACryptoServiceProvider` using the constructor that accepts a specific key size:

```csharp
var rsa = RSA.Create();

if (rsa.KeySize < 2048) {
    rsa.KeySize = 2048;
}

#if NET451
if (rsa.KeySize < 2048 && rsa is RSACryptoServiceProvider) {
    rsa.Dispose();
    rsa = new RSACryptoServiceProvider(2048);
}
#endif

if (rsa.KeySize < 2048) {
    throw new InvalidOperationException("The ephemeral key generation failed.");
}
```

https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/207

**Comment by leastprivilege** [comment]
thanks!

**Comment by stephentoub** [comment]
Issue covered by #8688. Thanks.
