### ISSUE TITLE
NetworkStream.Write does not send all bytes to the socket 

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/corefx#11295]
I'm not (yet :-) running .NET Core on my ARM platform, but I have been running into an issue with Mono in the NetworkStream class that's part of their implementation from the shared source. I have created https://bugzilla.xamarin.com/show_bug.cgi?id=43902 and try to create awareness of an assumption in a comment that's not true.

For convenience, here is a copy of the issue:

My setup is a program that saturates a network link by `Write`ing `byte[]` buffers of length 16384 until exactly 10 MiB are written. Those are transported via an IPv6 based `TcpClient` from a Linux kernel 3.14.58 USB RNDIS interface to a connected Windows machine. On the Windows machine, I use ncat to write the transported data to a file and verify that exactly 10485760 bytes have been received. The latter sometimes fails for Mono 4.4.1.

I have changed the code around the [`chkStreamSocket.Send`](https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/NetworkStream.cs#L505) call in the `NetworkStream.Write` method to actually check the return value. I can see that the returned number of bytes written is not the length of the buffer (I've seen 4512 or 12736 instead of 16384). The comment above the Send call seems to assume that this doesn't happen for blocking sockets, however this isn't true for this `Blocking==true` socket.

The amount of failures seems to be directly correlated to the speed of the network connection. On my main development machine, the USB network connection saturates above 100Mbit and the issues are very seldom. On another computer, the saturation is already at 35Mbit and there are multiple occurrences in each 10 MiB blob, so this looks like the socket's internal buffer might not have enough room for all data and only accepts less than the full buffer.

**Comment by stephentoub** [comment]
@ericeil, this issue is about Mono, but does a similar issue exist in the corefx implementation?

**Comment by weltkante** [comment]
@Tragetaschen 
> try to create awareness of an assumption in a comment that's not true

You are misinterpreting the cause of the bug, Socket.Send should indeet block until it is done sending.

According to the documentation of [Socket.Send](https://msdn.microsoft.com/en-us/library/4t14718h(v=vs.110).aspx):

> If you are using a connection-oriented protocol, Send will block until the requested number of bytes are sent, unless a time-out was set by using Socket.SendTimeout. If the time-out value was exceeded, the Send call will throw a SocketException.

So either the socket is misconfigured or the socket implementation (on Mono) has a bug.

The assumption in the comment should be correct.

**Comment by ericeil** [comment]
It does appear that we have the same issue in corefx.  `Socket.Send` does not guarantee that all bytes of the buffer are sent, even for blocking connection-oriented sockets.  This is because, unlike Windows, the BSD-based Sockets implementations don't make this guarantee.

We could perhaps work around this by wrapping our native `send` call in a loop, repeatedly sending until all bytes are sent.  But this still wouldn't quite match Windows' behavior, which seems to also guarantee atomicity of sends.  With the loop-based workaround, multiple concurrent `Socket.Send` calls could end up getting interleaved in the data stream on the wire, and there would be no indication to the caller that this had happened. 

However, I don't see how we can get atomic sends in any case.  The best we could do would be to make sure we return the *actual* number of bytes written to the caller, but if it's less than they wanted to write, the interleaving may already have happened.  Portable callers would need to synchronize their sends to get consistent behavior no matter what we do, in which case the loop workaround shouldn't make anything worse.

I'll put together a PR with the loop around the `send` call.

**Comment by ericeil** [comment]
Never mind...we already have a loop around the `send` call.  I just missed it in my previous reading of the code.  So I don't think we have this bug in corefx.

**Comment by stephentoub** [comment]
Thanks, Eric.

**Comment by Tragetaschen** [comment]
Indeed, thanks!

When I checked, I took a wrong turn in SocketPal.Unix and followed the wrong Send overload. The correct one ends in the for loop in [`TryCompleteSendTo`](https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/SocketPal.Unix.cs#L573)
