### ISSUE TITLE
System.Threading.Tasks.Dataflow more targets needed

### ISSUE THREAD

**Issue by CoreyKaylor** [dotnet/corefx#11388]
Currently the dataflow nuget package only targets netstandard1.1. This causes downstream challenges for those still targeting net46 for example because now the only option is to download the world which may or may not even succeed after doing so.

It would be preferable if it was similar to several of the other projects and target net452, etc. and allow for typical framework references to be used when not running on the coreclr.

**Comment by CoreyKaylor** [comment]
This issue has required the Marten project (link below) to work around the issue by depending on the older Microsoft.Tpl.Dataflow for net46. Without the workaround our users were unable to install Marten in a traditional csproj targeting net46.

https://github.com/JasperFx/marten/blob/master/src/Marten/project.json

**Comment by svick** [comment]
Are you talking about https://github.com/JasperFx/marten/issues/491#issuecomment-244147081? As far as I can tell, that issue happened, because `System.Threading.Tasks` in .Net 4.6 is a reference assembly, but not a runtime assembly, so your project.json should contain:

```js
"frameworks": {
  …,
  "net46": {
    "frameworkAssemblies": {
      "System.Threading.Tasks": { "type": "build" },
      …
    }
  } 
}
```

Or did you have another issue specifically with Dataflow?

**Comment by svick** [comment]
Also, as far as I can tell, installing `System.Threading.Tasks.Dataflow` into a .Net 4.6 project does not cause you to download packages like `System.Collections`, the dataflow package has no dependencies on .Net 4.6.

The reason why the latest version of `marten` does download those packages is because of `Remotion.Linq`.

**Comment by CoreyKaylor** [comment]
I will try to do as suggested to see if our end users get past the install problem, but I still think that because you don't find this out until users try to install your package and fail to pull down as a dependency when everything locally works fine. It seems like something could be improved to prevent that.

**Comment by CoreyKaylor** [comment]
What made matters even more confusing is that it works for everyone using coreclr / project.json even if targeting net46, but not those using traditional csproj.

**Comment by CoreyKaylor** [comment]
@svick that did seem to resolve the issues for Marten failing to pull down for our users.

**Comment by alexperovich** [comment]
This is not a problem with System.Threading.Tasks.Dataflow. As @svick said, `Remotion.Linq` is causing the download of many packages.
The fix is for `Remotion.Linq` to add a net45 dependencies section to their nuspec containing only the dependencies that aren't inbox on net45. Inbox assemblies are located in `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades`.
