### ISSUE TITLE
IIListProvider potential optimizations + refactoring

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#11455]
1. `IIListProvider` currently has a `GetCount(bool)` method, the bool parameter indicating whether we only want to get the count if it's "cheap" O(1). I just did a `grep -r 'GetCount(.*false) .` of System.Linq, and it looks like the only place it is ever called with false is [here](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Count.cs#L28). Since the additional bool parameter may hamper readability/performance and forces us to maintain additional logic for `!onlyIfCheap`, we may want to consider changing it to just `int Count { get; }`. The existing usage could become
   
   ``` cs
   if (listProv != null)
   {
       int count = listProv.Count;
       if (count != -1) return count;
   }
   ```
2. `ICollection<T>` has the method `CopyTo` which lets you trade off N interface calls (either the indexer if you are using `IList`, or MoveNext/Current on `IEnumerable`) for 1, the `CopyTo` method itself. This can result in quite substantial perf gains if the collection is large. We should consider adding another interface method to `IIListProvider`:

``` cs
bool TryCopyTo(T[] array, int arrayIndex);
```

This can be used whenever the iterator wraps an `ICollection` and it needs to copy some items to an array. One concrete case where it might benefit:

``` cs
return array // Take an ICollection
    .Select(i => i + 10) // Wrap it in an IIListProvider
    .Append(222) // Call something that uses CopyTo in ToArray
    .ToArray(); // Call ToArray
```

cc @JonHanna, @VSadov

**Comment by stephentoub** [comment]
> I just did a grep -r 'GetCount(.*false) . of System.Linq, and it looks like the only place it is ever called with false is here

That may be the only place it's called with a const of false, but there are a bunch of places where that Boolean is threaded through as a variable argument.

**Comment by jamesqo** [comment]
@stephentoub I just grepped for not true:

```
$ grep -r 'GetCount(.*)'. | grep -v true
src/System/Linq/AppendPrepend.cs:            public abstract int GetCount(bool onlyIfCheap);
src/System/Linq/AppendPrepend.cs:                    int count = listProv.GetCount(onlyIfCheap);
src/System/Linq/AppendPrepend.cs:                    int count = listProv.GetCount(onlyIfCheap);
src/System/Linq/Count.cs:                return listProv.GetCount(onlyIfCheap: false);
src/System/Linq/OrderedEnumerable.cs:                return listProv.GetCount(onlyIfCheap);
src/System/Linq/OrderedEnumerable.cs:            int count = GetCount(onlyIfCheap);
src/System/Linq/Partition.cs:        int GetCount(bool onlyIfCheap);
src/System/Linq/Partition.cs:            return _source.GetCount(_minIndexInclusive, _maxIndexInclusive, onlyIfCheap);
src/System/Linq/Select.cs:                return _source.GetCount(onlyIfCheap);
```

It looks like all the places where it's called with a variable parameter come from other implementations of `GetCount`. (Or in the case of `OrderedEnumerable.GetCount(int, int, bool)`, that's only called by `OrderedPartition.GetCount(bool)`.)

**Comment by stephentoub** [comment]
Yes.  My point was that the both values are used.  If your suggestion was to eliminate the ```false``` path, then that breaks Count which needs to evaluate the count even if it's not cheap.

**Comment by jamesqo** [comment]
@stephentoub Is it not possible to simply go down the regular slow path if we can't get the count cheaply? This is what [`ElementAt`](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/ElementAt.cs#L26) will do if the enumerable is an `IPartition`, but found is false.

**Comment by stephentoub** [comment]
> Is it not possible to simply go down the regular slow path if we can't get the count cheaply? 

Definitely not, at least not in all cases.  It's used, for example, by Select(...).ToArray() to presize the allocated array:
https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Linq/src/System/Linq/Select.cs#L635
You would not want doing so to have to MoveNext through each element of an enumerable just to get a count with which to presize the array.

**Comment by jamesqo** [comment]
@stephentoub The code you linked to calls `GetCount` with `true`, and calls `EnumerableHelpers.ToArray` if the result isn't cheap.

> You would not want doing so to have to MoveNext through each element of an enumerable just to get a count with which to presize the array.

If we cannot get the count in advance, it's likely that the iterator is backed by a non-ICollection/IIListProvider enumerable, and we'll end up calling MoveNext on each of that enumerable's elements anyway.

**Comment by stephentoub** [comment]
> but the code you linked to calls GetCount with true, and calls EnumerableHelpers.ToArray if the result isn't cheap.

Exactly.  It tries to get the count; if it can it takes one path that preallocates the array and then fills it in efficiently, and if it can't it falls back to not-preallocating the array and doing a normal iteration.  If GetCount always got the count, even if it was expensive (i.e. iterating), then we'd call GetCount, do an iteration, presize the array, and then go through everything again to fill in the array.

**Comment by jamesqo** [comment]
> If GetCount always got the count, even if it was expensive (i.e. iterating), then we'd call GetCount, do an iteration, presize the array, and then go through everything again to fill in the array.

So you're basically saying that `GetCount(false)` should *not* be used here, since it will cause 2 iterations through the array, correct?

I think I may have caused some confusion earlier. When I said

> Is it not possible to simply go down the regular slow path if we can't get the count cheaply?

I was not suggesting that `Count` should return the actual count even if it is not cheap to get; it should still return -1, and behave like `GetCount(true)`. I was suggesting how the (only) usage of `GetCount(false)` could be replaced in `Enumerable.Count`, by going down [this path](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Count.cs#L37-L49) if the count is not cheap to get.

**Comment by stephentoub** [comment]
> I was suggesting how the (only) usage of GetCount(false) could be replaced in Enumerable.Count, by going down this slow path if the count is not cheap to get

But that slower path is slower than what implementations can do even in the fallback case.

Consider a case like DefaultIfEmpty:
https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/DefaultIfEmpty.cs
```
            public int GetCount(bool onlyIfCheap)
            {
                int count;
                if (!onlyIfCheap || _source is ICollection<TSource> || _source is ICollection)
                {
                    count = _source.Count();
                }
                else
                {
                    IIListProvider<TSource> listProv = _source as IIListProvider<TSource>;
                    count = listProv == null ? -1 : listProv.GetCount(onlyIfCheap: true);
                }

                return count == 0 ? 1 : count;
            }
```
source.DefaultIfEmpty().Count() today will call GetCount(false) on the DefaultIfEmptyEnumerator, so we'll end up doing _source.Count().  Let's say the _source is a regular enumerable: we'll call MoveNext for each element in the enumerable.  Now let's say that instead of doing that, we instead just return -1, such that Count needs to iterate through the enumerable.  The enumerable Count has is the DefaultIfEmptyEnumerable, so it will end up calling MoveNext on the DefaultIfEmptyEnumerable, and for each of those, we'll end up with a call to MoveNext on the underlying enumerable... meaning two MoveNext calls per element in the enumerable.

Take Concat as another example:
https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Concatenate.cs#L211-L234
```
            public int GetCount(bool onlyIfCheap)
            {
                if (onlyIfCheap)
                {
                    return -1;
                }

                int count = 0;
                for (int i = 0; ; i++)
                {
                    IEnumerable<TSource> source = GetEnumerable(i);
                    if (source == null)
                    {
                        break;
                    }

                    checked
                    {
                        count += source.Count();
                    }
                }

                return count;
            }
```
Let's say you Concat(someCollection, someEnumerable).  Today if you then call Count() on that, we'll call GetCount(false), and we'll end up calling Count() on each of the constituent enumerables.  For someEnumerable, we'll need to call MoveNext on each element, but for the collection, we'll make a single call to its Count.  In contrast, without onlyIfCheap, we'd need to always return -1 from this GetCount method, which means Count would always end doing the full iteration, even though some of it could have been done faster.

**Comment by stephentoub** [comment]
> I was suggesting how the (only) usage of GetCount(false) could be replaced in Enumerable.Count, by going down this slow path if the count is not cheap to get

But that slower path is slower than what implementations can do even in the fallback case.

Consider a case like DefaultIfEmpty:
https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/DefaultIfEmpty.cs
```
            public int GetCount(bool onlyIfCheap)
            {
                int count;
                if (!onlyIfCheap || _source is ICollection<TSource> || _source is ICollection)
                {
                    count = _source.Count();
                }
                else
                {
                    IIListProvider<TSource> listProv = _source as IIListProvider<TSource>;
                    count = listProv == null ? -1 : listProv.GetCount(onlyIfCheap: true);
                }

                return count == 0 ? 1 : count;
            }
```
source.DefaultIfEmpty().Count() today will call GetCount(false) on the DefaultIfEmptyEnumerator, so we'll end up doing _source.Count().  Let's say the _source is a regular enumerable: we'll call MoveNext for each element in the enumerable.  Now let's say that instead of doing that, we instead just return -1, such that Count needs to iterate through the enumerable.  The enumerable Count has is the DefaultIfEmptyEnumerable, so it will end up calling MoveNext on the DefaultIfEmptyEnumerable, and for each of those, we'll end up with a call to MoveNext on the underlying enumerable... meaning two MoveNext calls per element in the enumerable.

Take Concat as another example:
https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Concatenate.cs#L211-L234
```
            public int GetCount(bool onlyIfCheap)
            {
                if (onlyIfCheap)
                {
                    return -1;
                }

                int count = 0;
                for (int i = 0; ; i++)
                {
                    IEnumerable<TSource> source = GetEnumerable(i);
                    if (source == null)
                    {
                        break;
                    }

                    checked
                    {
                        count += source.Count();
                    }
                }

                return count;
            }
```
Let's say you Concat(someCollection, someEnumerable).  Today if you then call Count() on that, we'll call GetCount(false), and we'll end up calling Count() on each of the constituent enumerables.  For someEnumerable, we'll need to call MoveNext on each element, but for the collection, we'll make a single call to its Count.  In contrast, without onlyIfCheap, we'd need to always return -1 from this GetCount method, which means Count would always end doing the full iteration, even though some of it could have been done faster.

**Comment by stephentoub** [comment]
> I was suggesting how the (only) usage of GetCount(false) could be replaced in Enumerable.Count, by going down this slow path if the count is not cheap to get

But that slower path is slower than what implementations can do even in the fallback case.

Consider a case like DefaultIfEmpty:
https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/DefaultIfEmpty.cs
```
            public int GetCount(bool onlyIfCheap)
            {
                int count;
                if (!onlyIfCheap || _source is ICollection<TSource> || _source is ICollection)
                {
                    count = _source.Count();
                }
                else
                {
                    IIListProvider<TSource> listProv = _source as IIListProvider<TSource>;
                    count = listProv == null ? -1 : listProv.GetCount(onlyIfCheap: true);
                }

                return count == 0 ? 1 : count;
            }
```
source.DefaultIfEmpty().Count() today will call GetCount(false) on the DefaultIfEmptyEnumerator, so we'll end up doing _source.Count().  Let's say the _source is a regular enumerable: we'll call MoveNext for each element in the enumerable.  Now let's say that instead of doing that, we instead just return -1, such that Count needs to iterate through the enumerable.  The enumerable Count has is the DefaultIfEmptyEnumerable, so it will end up calling MoveNext on the DefaultIfEmptyEnumerable, and for each of those, we'll end up with a call to MoveNext on the underlying enumerable... meaning two MoveNext calls per element in the enumerable.

Take Concat as another example:
https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Concatenate.cs#L211-L234
```
            public int GetCount(bool onlyIfCheap)
            {
                if (onlyIfCheap)
                {
                    return -1;
                }

                int count = 0;
                for (int i = 0; ; i++)
                {
                    IEnumerable<TSource> source = GetEnumerable(i);
                    if (source == null)
                    {
                        break;
                    }

                    checked
                    {
                        count += source.Count();
                    }
                }

                return count;
            }
```
Let's say you Concat(someCollection, someEnumerable).  Today if you then call Count() on that, we'll call GetCount(false), and we'll end up calling Count() on each of the constituent enumerables.  For someEnumerable, we'll need to call MoveNext on each element, but for the collection, we'll make a single call to its Count.  In contrast, without onlyIfCheap, we'd need to always return -1 from this GetCount method, which means Count would always end doing the full iteration, even though some of it could have been done faster.

**Comment by stephentoub** [comment]
> I was suggesting how the (only) usage of GetCount(false) could be replaced in Enumerable.Count, by going down this slow path if the count is not cheap to get

But that slower path is slower than what implementations can do even in the fallback case.

Consider a case like DefaultIfEmpty:
https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/DefaultIfEmpty.cs
```
            public int GetCount(bool onlyIfCheap)
            {
                int count;
                if (!onlyIfCheap || _source is ICollection<TSource> || _source is ICollection)
                {
                    count = _source.Count();
                }
                else
                {
                    IIListProvider<TSource> listProv = _source as IIListProvider<TSource>;
                    count = listProv == null ? -1 : listProv.GetCount(onlyIfCheap: true);
                }

                return count == 0 ? 1 : count;
            }
```
source.DefaultIfEmpty().Count() today will call GetCount(false) on the DefaultIfEmptyEnumerator, so we'll end up doing _source.Count().  Let's say the _source is a regular enumerable: we'll call MoveNext for each element in the enumerable.  Now let's say that instead of doing that, we instead just return -1, such that Count needs to iterate through the enumerable.  The enumerable Count has is the DefaultIfEmptyEnumerable, so it will end up calling MoveNext on the DefaultIfEmptyEnumerable, and for each of those, we'll end up with a call to MoveNext on the underlying enumerable... meaning two MoveNext calls per element in the enumerable.

Take Concat as another example:
https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Concatenate.cs#L211-L234
```
            public int GetCount(bool onlyIfCheap)
            {
                if (onlyIfCheap)
                {
                    return -1;
                }

                int count = 0;
                for (int i = 0; ; i++)
                {
                    IEnumerable<TSource> source = GetEnumerable(i);
                    if (source == null)
                    {
                        break;
                    }

                    checked
                    {
                        count += source.Count();
                    }
                }

                return count;
            }
```
Let's say you Concat(someCollection, someEnumerable).  Today if you then call Count() on that, we'll call GetCount(false), and we'll end up calling Count() on each of the constituent enumerables.  For someEnumerable, we'll need to call MoveNext on each element, but for the collection, we'll make a single call to its Count.  In contrast, without onlyIfCheap, we'd need to always return -1 from this GetCount method, which means Count would always end doing the full iteration, even though some of it could have been done faster.

**Comment by VSadov** [comment]
The bool argument is there on purpose. In particular in nested cases we would want to propagate it down. Even if the actual ```false``` value is not used much in code, it would be used in many places because of the cascading use.
