### ISSUE TITLE
Fervent request to add true EXI support to .NET

### ISSUE THREAD

**Issue by ericleigh007** [dotnet/corefx#1146]
There are several projects which purport to be .NET implementations of Efficient XML Interchange, but there is no .Serialize .Deserialize support for EXI that mirrors that for XML and JSON in .NET.  EXI has the opportunity to become a very important player in all sorts of things from the desktop to the web to the .NET micro framework, and it would make a lot of sense to adopt it as a key player BEFORE it is needed.

**Comment by akoeplinger** [comment]
Is there a reason why this needs to be done in corefx rather than a separate library like Newtonsoft.Json?

**Comment by ericleigh007** [comment]
I guess the same could be said of XML support.  Why is XML support not a separate package?  XML is there internally Because it is a ubiquitous standard.  JSON was added later because of the same reason.

The reason to do EXI internally is that EXI is "binary XML" and it should be just as prevalent, because the format is probably going to be ubiquitous like XML in the future     Since EXI is just binary XML, one could even expect that the interface could be the same as for serializing and de-serializing EXI and be usable by developers almost immediately after completion.

The others I can think of are 1) Adding to the main library prevents projects from having to have another dependency, and 2) EXI would be more completely supported inside the core (ESPECIALLY if part of the XML interface that exists today) than in some extra nuGet package.  I'll amend this when I think of more reasons.

From a standpoint specifically of JSON.NET, I asked for support the response was that JSON.NET is not interested in supporting EXI.

4 years after W3C adopting the EXI standard, developers are still waiting for support in any of .NET.  I'm just trying to get this somewhere as a turnkey solution, so that it can flourish..

Thanks for your considered responses, .NET community.

**Comment by svick** [comment]
>  the format is probably going to be ubiquitous like XML in the future […]
> 4 years after W3C adopting the EXI standard

This to me shows that EXI isn't likely to become ubiquitous. It's been an official standard for 4 years (and it did exist before that) and still it's not used much.

> Adding to the main library prevents projects from having to have another dependency

That's not how .Net Core works. There, pretty much everything is a dependency, including the existing XML support (see e.g. [the System.Xml.XmlDocument package](https://www.nuget.org/packages/System.Xml.XmlDocument/4.0.0-beta-22605)).

>  EXI would be more completely supported inside the core

I have no idea what is that supposed to mean.

**Comment by ellismg** [comment]
I agree with @svick and @akoeplinger here.  I think there are a few things to keep in mind:

1. One of the goals of .NET Core is that the framework is factored into fine grained contracts with implementations portable across .NET Runtimes (.NET Native, CoreCLR, the Full .NET Framework).  This allows application developers to bring their dependencies with them when deploying their app, they don't have to worry about a runtime having shipped with support for a particular technology.
2. The goal of CoreFX is to not support every single technology under the sun.  We want to have general purpose libraries that are useable in a verity of domains.  Because of this, we'd be hesitant to do something like EXI if there's limited adoption in general.  Additionally, there's a higher chance that we'll build the wrong thing if there aren't many consumers that we can look at to ensure we're hitting all the scenarios.

Don't take the above to mean that we don't want support for EXI as part of the larger .NET Ecosystem.  We'd love for passionate members of the community who are experts to help make existing libraries better or produce their own.  Perhaps you can work with the owners of the existing libraries and help them bring the surface area more in line with the existing .NET types?

**Comment by ericleigh007** [comment]
Okay, guys, I certainly appreciate your time.
I was unaware of the refactoring of the library and the idea to break this into smaller pieces.  If you guys feel that XML (as @svick said) is not general purpose enough, then certainly EXI isn't.

I do disagree that because EXI hasn't found wide adoption that is won't be ubiquitous though.  I have to say that this is very much the chicken or the egg or put in 2015 vernacular, the "app gap" problem.  No one has adopted it because there is no core technology yet that is bullet proof and more than a lab experiment.

Just to close the loop on my comment about the EXI support being better "inside the core", I meant to throw this team a complement.  This team is made up of stars in the industry and I meant to imply that you guys would implement, test, and support better than others ;)

So if you guys have some time, help me to find the right place to get this some support, and obviously close this issue.

I also set this as a wish on UserVoice, and expect the answer will be pretty much the same there, although I have some hope that since in 2008 a Microsoft employee had a favorable response to EXI, perhaps .NET 5.0 or so could have support.

I may try to pitch this over in the ASP.NET community too and see what they think of layering this into the MediaFormatter functionality there.  After all, having just added BSON support, and since BSON isn't a W3C standard, perhaps there may be some interest.

-thanks
-e

**Comment by ellismg** [comment]
@ericleigh007 Opening an issue on User Voice is a great idea.  If there end up being a lot of votes, we will certainly reconsider about creating a first class implementation.

If you wouldn't mind, please do share the link in this issue so folks who find it will know to vote.  I'll close the issue after you've added the link.

**Comment by ericleigh007** [comment]
Here's the link to UserVoice.
http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/7222682-add-efficient-xml-interchange-support-to-net

**Comment by ellismg** [comment]
Thanks!
