### ISSUE TITLE
Uri.CreateUriInfo is locking on a string

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#11471]
https://github.com/dotnet/corefx/blob/ca9e2b068e75898a3b35860632b1fec01cc5af93/src/System.Private.Uri/src/System/Uri.cs#L2199-L2206
```C#
            lock (_string)
            {
                if ((_flags & Flags.MinimalUriInfoSet) == 0)
                {
                    _info = info;
                    _flags = (_flags & ~Flags.IndexMask) | cF;
                }
            }
```
This is a scalability concern, e.g. this Uri could end up sharing the same lock as another that's locking on the same string instance, such as if the string is interned.  Now, given the rarity of this, this might be the best option, as unless there's another object available on which to lock, this is likely the better option than allocating a new object per Uri just for the purposes of this lock.  If there's another existing object that could be used that's not shared, that would be better.  Even better would be getting rid of this lock entirely... since Uri to my knowledge is not deemed to be thread-safe, the purpose of this lock is unclear to me... maybe it could just be removed entirely?

**Comment by svick** [comment]
`Uri` is immutable and I think that people often assume (correctly or not) that reading the same object from multiple threads is fine, so it makes sense to me to make `Uri` thread-safe.

And it seems `Uri` was designed to be thread-safe, since there are some `lock (_info)` in it and also some comments about multi-threading.

Maybe it would make sense to verify that `Uri` indeed is thread-safe and then change the documentation?

**Comment by karelz** [comment]
Also FxCop warning - tracking for 1.2 in #13107.
