### ISSUE TITLE
Bring back Console.ReadKey()

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#1153]
For reference, see issue #311 and the related aspnet/Hosting#140.   Console.ReadKey() can solve both issues (thought explicit support for CancelKeyPress is nice as that can handle different keyboard configurations etc).   

ReadKey() is a helpful API for many console app scenarios and is quite difficult for users to implement in a non-Windows-specific way if they want to get the same functionality.   Please consider bringing it back.

**Comment by txdv** [comment]
What do you mean with ' is quite difficult for users to implement in a non-Windows-specific way'? Is it hard to implement on other platforms?

**Comment by jasonwilliams200OK** [comment]
BTW, both tagged issues are resolved.

**Comment by ellismg** [comment]
@MattGal Do you know if we still need this?

**Comment by mspeterhon** [comment]
yes, this would be super helpful, especially to get modifier keys and keys like escape and tab

**Comment by MattGal** [comment]
@ellismg  I believe the scenario of Ctrl-C being the specific key combination to kill hosting an app is something that hasn't been addressed yet, so it'd be nice to have.  In my experience, I don't find it to be in any way blocking so I am OK if it doesn't happen.

**Comment by NickCraver** [comment]
I'm currently hitting a wall without `ReadKey()` because as far as I'm aware, there's no other way to read and mask console input as it arrives, e.g. when entering a password. Unfortunately, I'll likely have to abandon DNX for a string of projects if I can't do something so simple.

Can we please bring this back? It is rather important.
There are other use cases as well, for example hitting y/n/a for continue without needing to hit enter as well, which is counter-intuitive since with most existing programs and prompts (including system utilities on all platforms) enter is *not* required. The need in that use case is getting input back to the program without needing enter/return.

**Comment by akoeplinger** [comment]
@NickCraver if you're fine with a Windows-only implementation as a temporary workaround you could leverage the implementation in [ReferenceSource](https://github.com/Microsoft/referencesource/blob/74706335e3b8c806f44fa0683dc1e18d3ed747c2/mscorlib/system/console.cs#L1476). I agree this is an important API that should be brought back in corefx.

**Comment by weshaggard** [comment]
We definitely need to have a more holistic look at our Console support. It is on our list but we haven't  focused on it yet. I suspect this is one we will likely need to include.

**Comment by NickCraver** [comment]
To add to the use cases here. On most programs on most platforms where a prompt is involved you'll see something to the effect of:

```
Continue? (y/n):
```

This currently isn't possible, you have to do a much less intuitive "(y/n then enter)" without `.ReadKey()` which allows processing per-character. It's unintuitive because of violating the principle least-surprise - matching the 99% behavior.

In my use case I've (*very* hackily) re-implemented the bare bones of `.ReadKey(bool interrupt)` to get past the lack of things here, and using the reference source @akoeplinger refers to above. I needed it for both the prompts to continue as well as (more importantly) password masking on entry. However, it locks me down to Windows (and only NT-based versions at that, since `CharSet.Auto` isn't present), and eliminates my ability to run on OS X.

To get an idea of what I currently resorted to, here's the *very* minimal implementation that pretty much only supports my one-off use case:

**Note to others: please do not use this, it is not suitable for security sensitive multi-tenant environments and is just a minimum viable implementation**

```C#
public struct TempKeyInfo
{
	public char KeyChar;
	public short KeyCode;
}

public static class TempConsoleKey
{
	public static short Backspace = 8;
	public static short Enter = 13;
}

// Temporary implementation until corefx gets ReadKey
public class TempConsole
{
	[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
	internal struct InputRecord
	{
		internal short eventType;
		internal KeyEventRecord keyEvent;
	}

	[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
	internal struct KeyEventRecord
	{
		internal bool keyDown;
		internal short repeatCount;
		internal short virtualKeyCode;
		internal short virtualScanCode;
		internal char uChar;
		internal int controlKeyState;
	}

	[DllImport("kernel32.dll", SetLastError = true)]
	internal static extern IntPtr GetStdHandle(int nStdHandle);

	[DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
	internal static extern bool ReadConsoleInput(IntPtr hConsoleInput, out InputRecord buffer, int numInputRecords_UseOne, out int numEventsRead);

	private static InputRecord _cachedInputRecord;
	private static volatile IntPtr _consoleInputHandle;
	private static IntPtr ConsoleInputHandle
	{
		get
		{
			if (_consoleInputHandle == IntPtr.Zero)
				_consoleInputHandle = GetStdHandle(-10);
			return _consoleInputHandle;
		}
	}
	
	public static TempKeyInfo ReadKey()
	{
		InputRecord ir;
		int numEventsRead = -1;
		bool r;
		
		if (_cachedInputRecord.eventType == 1)
		{
			ir = _cachedInputRecord;
			if (_cachedInputRecord.keyEvent.repeatCount == 0)
				_cachedInputRecord.eventType = -1;
			else
				_cachedInputRecord.keyEvent.repeatCount--;
		}
		else
		{
			while (true)
			{
				r = ReadConsoleInput(ConsoleInputHandle, out ir, 1, out numEventsRead);
				if (!r || numEventsRead == 0)
				{
					throw new InvalidOperationException("Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.");
				}

				short keyCode = ir.keyEvent.virtualKeyCode;
				if (!(ir.eventType == 1 && ir.keyEvent.keyDown) && keyCode != 0x12) continue;

				char ch = (char)ir.keyEvent.uChar;
				if (ch == 0 && ((keyCode >= 0x10 && keyCode <= 0x12) || keyCode == 0x14 || keyCode == 0x90 || keyCode == 0x91)) continue;

				if (ir.keyEvent.repeatCount > 1)
				{
					ir.keyEvent.repeatCount--;
					_cachedInputRecord = ir;
				}
				break;
			}
		}

		return new TempKeyInfo
		{
			KeyChar = (char)ir.keyEvent.uChar,
			KeyCode = ir.keyEvent.virtualKeyCode
		};
	}
}
```

Please, *please*, bring back the essentials of `Console`, and let me delete the abomination above :)

**Comment by anuchandy** [comment]
+1, having Console.ReadKey in CoreCLR is really required functionality for the project we are building on CoreCLR. @niklasg

**Comment by andschwa** [comment]
:+1: likewise, this is required functionality we need.

**Comment by pallavit** [comment]
I will start looking at the windows implementation soon. From the cross-plat perspective, I could not find a way to capture virtual key codes.  One alternative would be to leverage Console.Read() itself to get the ASCII code however that would leave a whole set of keys as unimplemented - modiifier keys (Shift, Alt), function keys etc. Thoughts?

**Comment by andschwa** [comment]
If we don't have the modifier keys, we would be unable to implement commonly expected shortcuts such as `Ctrl-A` and `Ctrl-E` for home and end in our custom consoles.

**Comment by pallavit** [comment]
I don't think Ctrl key will be the problem. Looking at the https://en.wikipedia.org/wiki/ASCII all the ctrl keys can be correctly intercepted, however, I am not sure, how would we intercept Alt, Shift or function keys.

**Comment by pallavit** [comment]
@stephentoub Do you have any insights into its implementation cross-plat?

**Comment by pallavit** [comment]
I think we can implement Console.KeyAvailable by using poll() API.

**Comment by stephentoub** [comment]
To my knowledge, there's no direct equivalent to "what key is currently pressed" as you have on Windows.  Rather, various character sequences are written to the console to represent the various keys being pressed.  For the most part, these sequences are discernable by reading the terminfo file.  It contains the descriptions for the given terminal of what character sequence will be sent for what key.  If you look at "man 5 terminfo", you'll see all of the capabilities enumerated, including ones that, for example, provide the sequences used for each of the function keys.  The only capabilities we're currently reading are the strings for foreground/background color, so I was lazy and only extracted those two values in the code, but we could certainly augment the code to have the names/values for all of the relevant capabilities we care about (all of the terminfo parsing support is there), and modify the console code to read those out (and cache them) and then use them in ReadKey to understand what's being sent.  I  believe alt generally sends an escape (27).  Not sure about shift... might need to approximate that based on the case of letters, though it's also possible there's some terminfo sequence for it.

**Comment by pallavit** [comment]
@stephentoub Thanks for the direction. I will take a look at it :)

**Comment by pallavit** [comment]
Merges with #3939

**Comment by andschwa** [comment]
Awesome, thanks guys!
