### ISSUE TITLE
System.Data.SqlClient.SqlCredential class missing from corefx

### ISSUE THREAD

**Issue by MitchellSternke** [dotnet/corefx#11542]
I realize this was already raised earlier this year: https://github.com/dotnet/corefx/issues/6948

However, it appears that SecureString has been added to corefx since that issue was closed. Would it be possible to have SqlCredential implemented and the corresponding SqlConnection/SqlConnectionStringBuilder functionality that relies upon it?

**Comment by YoungGah** [comment]
Yes, we will bring it back since SecureString is available. As for SqlConnectionStringBuilder, it should not have any dependency on SqlCredential.

**Comment by saurabh500** [comment]
cc @joelbraun This is the issue for SqlCredential type.

**Comment by joelbraun** [comment]
Got it - I'll try to do the work in two phases as suggested. Move the type itself over, and then integrate it with the rest of the API.

**Comment by saurabh500** [comment]
@joelbraun are you still planning on taking care of this API ?

**Comment by joelbraun** [comment]
@saurabh500 Sorry, I set this aside for a while and just got back to it. I've linked the PR which ports the SqlCredential class itself with tests, and I'll start looking at its dependent APIs.

**Comment by saurabh500** [comment]
Thanks for the update. I will review the PR

**Comment by joelbraun** [comment]
@saurabh500 The port for this is complete and functional, but I'm wondering how to approach writing the integration tests. Creating a connection using SqlCredential or changing a password means I need a username/password combo. How should I handle testing in a situation where the test connection string uses SSPI?

**Comment by iamatinkerer** [comment]
@joelbraun Can you post your branch or post a PR with the product changes? I can look at the implementation/port and advise.

**Comment by saurabh500** [comment]
@joelbraun Thanks. 
We have a set of tests which are dependent on a server in the folder called tests/ManualTests
What you could do is, assume that there is already a connection string which connects to Sql Server with sysadmin permissions. 
For change password, you could create a user and password using the environment connection string and establish another connection using new credentials, then you could change the credentials. 

For the environment connection string reference look at https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/tests/ManualTests/SQL/CommandCancelTest/CommandCancelTest.cs#L17

For these tests we add an attribute called [CheckConnStrSetupFact] on the test which checks if env vars TEST_TCP_CONN_STR and TEST_NP_CONN_STR are setup. If they are setup, then the test execution continues else it is skipped. 
The SqlClient server dependent tests dont run in the CI as the CI doesnt have a SQL server setup. I can validate your changes on our infrastructure. 

I think you should send a PR with the product changes, so that they can be review, with some tests which can login, to the SQL server using SqlCredential. You can then keep working on the change password tests and update the PR or send another one.

This way we can keep the ball rolling.

**Comment by joelbraun** [comment]
Found a bug in my change that took me a little while to fix, but the PR is out now. I used a local setup of Northwind to test, and it looks like everything is good to review.
