### ISSUE TITLE
X509Chain.ChainContext property is not available in dotnetcore. 

### ISSUE THREAD

**Issue by bmanikm** [dotnet/corefx#11565]
X509Chain.ChainContext property is not available in dotnetcore. 

We have some PInvoke code to check if the last element of the first simple chain contains a Microsoft root public key (CERT_CHAIN_POLICY_MICROSOFT_ROOT) using CertVerifyCertificateChainPolicy() CAPI.  

How can we check whether a given X509Chain contains a Microsoft root public key in dotnetcore?
cc: @bartonjs

**Comment by bartonjs** [comment]
@bmanikm The property was removed because it only makes sense on Windows and one of the focuses of .NET Core was cross-platform applicability.  You can't P/Invoke into CAPI on Linux, so what would you want your code (or this property) to do there?

Also, what's your situation where you're a C# application/library which needs something to chain to "a MS root"?  Would embedding the expected root cert into your application and comparing it against the last element in the chain make sense? (root pinning)

**Comment by bmanikm** [comment]
@bartonjs We have a Windows specific feature to ensure that given X509Chain contains a Microsoft root cert. We need this functionality for Windows NanoServer. It is not possible to have a list of expected root certs as different teams in Microsoft release with different root certs and they can be changed too. Please advice how to achieve the expected functionality on Nano Server.

**Comment by bartonjs** [comment]
Actually, it appears I'm mistaken.  We removed `ChainContext` because we were already exposing the newer `SafeHandle` property, which is the SafeHandle version of the IntPtr that ChainContext exposed.  So you should be able to still P/Invoke just fine by switching to the SafeHandle version.

**Comment by bmanikm** [comment]
Thank you @bartonjs !
