### ISSUE TITLE
Consider adding static Socket.Connect methods to support DNS endpoints

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#11564]
See #8768 for background.

**Comment by halter73** [comment]
I was testing an app that connected to Redis on "localhost" that worked fine on Windows, but failed on Linux with a PlatformNotSupportedException.

Reading the background issue, I think I prefer @stephentoub's option 7 with all properties tracked to in order to align the behavior of Socket as closely as possible on all OSs. Now that we're adding the Socket APM methods back for compat, it doesn't really make sense to deprecate the instance Connect methods in favor of the static ones. And once the static methods are added, app developers will still have to wait for library authors to (hopefully) update their libraries to use the new static methods before they will be able use DNS endpoints in application code intended to run on Linux.

**Comment by karelz** [comment]
Next step: We need formal API proposal

**Comment by geoffkizer** [comment]
API proposal:

on Socket:
```
public static Socket Connect(SocketType socketType, ProtocolFamily protocolFamily, EndPoint endpoint);
public static Socket Connect(SocketType socketType, ProtocolFamily protocolFamily, IPAddress address, int port);
public static Socket Connect(SocketType socketType, ProtocolFamily protocolFamily, IPAddress[] addresses, int port);
public static Socket Connect(SocketType socketType, ProtocolFamily protocolFamily, string hostname, int port);

public static Task<Socket> ConnectAsync(SocketType socketType, ProtocolFamily protocolFamily, EndPoint endpoint);
public static Task<Socket> ConnectAsync(SocketType socketType, ProtocolFamily protocolFamily, IPAddress address, int port);
public static Task<Socket> ConnectAsync(SocketType socketType, ProtocolFamily protocolFamily, IPAddress[] addresses, int port);
public static Task<Socket> ConnectAsync(SocketType socketType, ProtocolFamily protocolFamily, string hostname, int port);
```
These correspond to the signatures of the existing instance methods, with socketType/protocolFamily added (as in the SAEA version of ConnectAsync) and returning a Socket/Task<Socket>.

And, similarly for TcpClient, except the socketType/protocolFamily params are unnecessary and the return value is TcpClient/Task<TcpClient>.

**Comment by stephentoub** [comment]
Are there any settings/options that can only be configured on a socket before it's connected (e.g. something to do with the connect operation itself)?  I'm wondering if we may need to have one or more of the overloads take a delegate that would be passed the Socket before we initiate the connection on it, e.g.
```C#
public static Task<Socket> ConnectAsync(
    SocketType socketType, ProtocolFamily protocolFamily,
    string hostname, int port,
    Action<Socket> configurationCallback);
```
If everything can be done after the socket is connected, then this wouldn't be helpful.

**Comment by geoffkizer** [comment]
Yeah, that's a very good point.  We were just talking about TCP Fast Open on a different thread, that would definitely affect connect behavior.  Probably there are others.

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/pull/16373 addressed the key issues here.  I've not heard about any subsequent negative fallout.  @geoffkizer, are additional APIs here something you're still interested, or should we close this for now and accept the current Connect{Async} API surface?

**Comment by scalablecory** [comment]
triage: no strong demand, but not against the idea. revisit in future if we see more demand.
