### ISSUE TITLE
FileSystemWatcher_InternalBufferSize_File test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1165]
FileSystemWatcher_4000_Tests.FileSystemWatcher_InternalBufferSize_File [FAIL]
        Should not observe a error event
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.IO.FileSystem.Watcher\tests\Utility\Utility.cs(100,0): at Utility.ExpectNoEvent(WaitHandle eventOccured, String eventName, Int32 timeout)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.IO.FileSystem.Watcher\tests\FileSystemWatcher.InternalBufferSize.cs(53,0): at FileSystemWatcher_4000_Tests.FileSystemWatcher_InternalBufferSize_File()
  Finished:    System.IO.FileSystem.Watcher.Tests

**Comment by chcosta** [comment]
The test appears to determine a value sufficient to overflow the buffer and then it attempts to overflow the buffer and ensure that an error occurs (this works as expected).  It then increases the size of the buffer to a value which should be sufficient to contain the previous buffer overflow and performs the same operation it previously did.  In the second iteration, because the buffer size was increased, the expectation is that the watcher will not raise an error when the same operation is performed.  The assert is occurring during the second operation.

Was there anything particularly interesting about what you were doing when you encountered this failure?  I wouldn't expect the test itself (in a closed environment) to throw the assertion mentioned.  I could imagine that if you were doing something else in the directory while the test was running, then the watcher may raise multiple error events.  The test would deal with the first error (presuming that it was the error it generated), and then the lingering error would force AutoResetEvent to remain in the signaled state and cause the assert to fire in the second operation.

**Comment by chcosta** [comment]
@stephentoub

**Comment by stephentoub** [comment]
> Was there anything particularly interesting about what you were doing when you encountered this failure?

I don't know; this was part of a CI build for a PR.

**Comment by chcosta** [comment]
Thanks Stephen.

I don't think this test was performing as intended.  UnblockHandler gets reset after the first exception is dealt with.  This causes the watcher to stop receiving change events and thereby to stop raising error events (error events are called, mostly, during System.IO.FileSystem.Watcher's CompletionStatusChanged).  The result is that the 2nd operation in the method which is supposed to validate that we increased the InternalBuffer to a sufficient size, doesn't actually get exercised (events aren't handled).  Thereby, it appeared that the test was working, but it was only performing half of the validations it intended.

There are a couple of things to fix with this test.
1. We should set the ManualEventHandler (unblockHandler) again after we've set up the second operation so that events continue to get handled.
2. The problem was probably exacerbated by the fact that the watcher is using the current directory as its monitor path.  We should be sandboxing this more.
3. If the change events handler was blocking the error event handler, then the only way this test could have failed in the method listed, is if we had an invalid handle (the OS disposed of the native handle we were using).  The above changes wouldn't resolve this, and I don't know that we have a good way to ensure we don't lose the native handle.

**Comment by stephentoub** [comment]
Thanks for investigating.

**Comment by stephentoub** [comment]
This is still happening, and more frequently.  I've seen it several times today, e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/566/
If the test is flaky, we should take it offline until it can be fixed.

**Comment by chcosta** [comment]
I agree. I'm surprised by the frequency with which this has occurred, but don't want any "flakiness" in our CI tests.  I'll disable this test.

**Comment by chcosta** [comment]
@stephentoub, is the preferred way to disable a test just to remove its "[Fact]" attribute?

**Comment by stephentoub** [comment]
Add the [ActiveIssue(...)] attribute with this GitHub issue number; that'll disable it by default.

**Comment by chcosta** [comment]
Thanks Stephen.  My first attempt at adding the ActiveIssue trait failed, so I thought there was something else I was missing.  You confirmed that was the preferred method and I noticed that XUnitTraitsDiscoverers was not being included in the proj.  I'll create a PR for this now.

**Comment by chcosta** [comment]
This test has been disabled.
