### ISSUE TITLE
System.ComponentModel.Win32Exception when trying get Process.StartTime in the exited process on Linux

### ISSUE THREAD

**Issue by SerhiiS-in6k** [dotnet/corefx#11670]
Here example https://github.com/SerhiiS-in6k/Issue-net-core-process/blob/master/Program.cs
The exception occurs only on Linux(Ubuntu14.04-x64) on Windows works fine.

**Comment by mbinette91** [comment]
I think the real bug here is that this works on Windows.
 
From the doc:
 
> **Process.StartTime**
> Type: System.DateTime
> An object that indicates when the process started. An exception is thrown if the process is not running.
> [...]
> InvalidOperationException *The process has exited.*

Which is the behavior displayed on Linux (though not the right exception).

In Windows code, we call GetProcessHandle which can throw InvalidOperationException on an exited process, but we call it with throwOnExited == false.

Having the same behavior on all platforms sounds important, but I'm not sure changing the Windows behavior is the best move. Another option is to return StartTime even when the process has exited on Linux and to update the doc. @stephentoub, Thoughts? 
 
Linux also throws Win32Exceptions on *ProcessorTime (after exit) and those don't mention exited processes in the doc, so I'm not sure how we'd want to handle those.

If we decide to go with the later option, for StartTime on Linux, we can cache it when we first get a chance to query it (as it's not going to change), but for *ProcessorTime, those would change up until we exit (and then /proc/PID will be gone), so I don't know how to address those.

**Comment by Priya91** [comment]
@mbinette91 On windows, if the pinvoke failed to get starttime, we throw Win32Exception, [here](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs#L866), and invalidoperationexception is thrown when the handle is invalid indicating process exit. On Linux, there is no good way to determine why the proc/stat file parsing failed, could be process exited or hasn't started or any other OS error, hence we throw Win32Exception, in accordance to Windows behavior.
