### ISSUE TITLE
ILMerge

### ISSUE THREAD

**Issue by nojaf** [dotnet/corefx#11672]
Hi, sorry if wrong repo.
What would the best option be to create a dotnet core command line application and publish a single executable for Windows?
Is ILMerge still the way to go? Has anyone tried this?

**Comment by mellinoe** [comment]
I am not sure if ILMerge will work on .NET Core assemblies without any changes. It may, or it may need some extensive modifications. After that, though, you will still need to decide how the application actually gets launched / activated. Windows is able to directly launch .NET Framework applications, but the same is not true for .NET Core applications (well, it will try and fail). You need a native CLR host which is generally bundled alongside your managed entry point. Even with ILMerge, you would need to figure out what you find acceptable for that. Two files (native host + managed entry) may be okay for you.

**Comment by jkotas** [comment]
cc @russellhadley @swaroop-sridhar

**Comment by sklivvz** [comment]
I can confirm ILMerge.exe fails with .net core win64 assemblies:

~~~~
"(...) ILMerge.exe" /target:winexe /console-app-full.exe console-app.exe *.dll

An exception occurred during merging:
ILMerge.Merge: Could not load assembly from the location ' (...) \console-app.exe'.
Skipping and processing rest of arguments.
   at ILMerging.ILMerge.Merge()
   at ILMerging.ILMerge.Main(String[] args)
~~~~

**Comment by TerribleDev** [comment]
Hi, is there a plan to add the ability to merge dll's in the future? I can see this being huge for self-contained apps, especially when combined with ILLink #17825 Basically if you could link down your api's and then merge them into a single file that is a self-contained app. We could easily distribute cli based tools, without having to zip a whole directories worth of dll's.

**Comment by jnm2** [comment]
See also: https://github.com/gluck/il-repack

**Comment by TerribleDev** [comment]
@jnm2 oh snap........ I literally want to dance right now 🎉

**Comment by jnm2** [comment]
For that matter, https://github.com/microsoft/ilmerge is open-source and I have contributed code to both projects. ILMerge is in the process of moving to the .NET Foundation.

**Comment by ferventcoder** [comment]
https://github.com/dotnet/core/issues/600

**Comment by sgf** [comment]
im not sure why the project‘s participant close issures like this again and again.
but seems let some issues no process for a few years.
ppl lost the Trace for those.

https://github.com/dotnet/corefx/issues/13329
https://github.com/dotnet/corefx/issues/11672
https://github.com/dotnet/ILMerge/issues/23
https://github.com/dotnet/cli/issues/7737
https://github.com/dotnet/core/issues/600

now,i want to ask,dose the upllowing Issues be soloved?
if soloved,why ppl cant use the feature.
if not,why close they issues?


and:
CoreRT is a distant project. **There are no release plans.** And it is very cumbersome and difficult to use and cannot be used as a publishing tool at all.
The project has been underway for several years, the foreseeable future.
**It is impossible for people to wait a few more years to develop a project for this reason in order to use. Net.**

**Comment by jkotas** [comment]
This issue does not belong to this repo.

> What would the best option be to create a dotnet core command line application and publish a single executable for Windows?

The overall plan for single file solutions is described in: https://github.com/dotnet/designs/blob/master/accepted/single-file/design.md

> Is ILMerge still the way to go?

ILMerge (or its alternative https://github.com/gluck/il-repack) alone is not sufficient to publish a single .NET Core executable on Windows.
