### ISSUE TITLE
Change ref projects to .NET Core

### ISSUE THREAD

**Issue by rahku** [dotnet/corefx#11682]
These AppContext APIs can be in .NET Core but not .NET Standard yet. We will need to change these these ref projects to .NET Core. 
Check file src/System.Runtime/src/ApiCompatBaseline.net463.txt
https://github.com/dotnet/corefx/pull/11275/files#r78505041

**Comment by karelz** [comment]
@weshaggard what is this issue tracking? Even @AlexGhiondea doesn't understand.

**Comment by karelz** [comment]
Actually looks like dupe of #12456.

**Comment by ericstj** [comment]
It's not a dup.  These were APIs previously added for all platforms but they need to be scoped to just NETCore.

**Comment by ericstj** [comment]
Specifically: https://github.com/dotnet/corefx/blob/b8701fabcded3a340b09779bad9f89c1821a05e8/src/System.Runtime/ref/System.Runtime.cs#L87 needs to be if'defed so that it isn't in the netstandard reference assembly.

Surround it in `#if netcoreapp11` and remove https://github.com/dotnet/corefx/blob/b8701fabcded3a340b09779bad9f89c1821a05e8/src/System.Runtime/src/ApiCompatBaseline.net463.txt

**Comment by AlexGhiondea** [comment]
@ericstj that should cover both GetData and TargetFrameworkName, right?

**Comment by ericstj** [comment]
Whichever ones were not in net461.
