### ISSUE TITLE
Arithmetic expressions don't work with implicit numerical/primitive conversions

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#11705]
See the following:
```
// C#
int x = 1;
short y = 2;
int z = x + y;

// System.Linq.Expressions
Expression.Add(Expression.Constant(x), Expression.Constant(y));
```
Not sure if this is intended behaviour
/cc @bartdesmet  @VSadov

**Comment by svick** [comment]
I believe this is intentional. Expression trees are not meant to mirror C#, instead, code in any language (with its own rules about implicit conversions) should be convertible to expression trees.

As evidence of that, [look at the code generated if you let the C# compiler turn such addition to an expression](http://tryroslyn.azurewebsites.net/#b:master/K4Zwlgdg5gBAygTxAFwKYFsDcAoUlaIoYB0AMpAI7ECiAHgA4BOqI4A9hCDvcAEYA2YAMYwh/AIasYAYRgBvbDCUweA4TABubMABMYAWQAUASnmLlFukxbsIAHgBiwCELuRkAGhggAFm0aeMO4AfMEwqDAAvDCGtF4IppFhtDAA1DAIOBYAvtjZQA===):

Original:

```c#
Expression<Func<int, short, int>> e = (x, y) => x + y;
```

Decompiled:

```c#
var e = Expression.Lambda<Func<int, short, int>>(
    Expression.Add(xExpression, Expression.Convert(yExpression, typeof(int))),
    xExpression, yExpression);
```

The C# compiler explicitly adds `Convert()`, so I think you should too, when creating expression trees.

**Comment by hughbe** [comment]
@svick thanks for digging into this. I'll be sure to look at the decompiled output in the future  ill close this issue.

**Comment by svick** [comment]
Though as far as I can tell, [the documentation for `Expression.Add()`](https://msdn.microsoft.com/en-us/library/bb354402) does not talk about this. It probably should?

**Comment by hughbe** [comment]
Another one of those times I wish we could contribute to MSDN! Win-win for all
