### ISSUE TITLE
Arithmetic expressions don't work with enums properly

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#11704]
See the following example for Add:
```
// Valid
Int32Enum r1 = Int32Enum.a + (sbyte)1;
Int32Enum r2 = Int32Enum.a + (byte)1;
Int32Enum r3 = Int32Enum.a + (short)1;
Int32Enum r4 = Int32Enum.a + (ushort)1;
Int32Enum r5 = Int32Enum.a + 1;

// Invalid:
Int32Enum r6 = Int32Enum.a + (uint)1;
Int32Enum r7 = Int32Enum.a + (long)1;
Int32Enum r8 = Int32Enum.a + (ulong)1;

// Throws ArgumentException, incorrectly
Expression.Add(Expression.Constant(Int32Enum.a), Expression.Constant(1, typeof(sbyte)));
Expression.Add(Expression.Constant(Int32Enum.a), Expression.Constant(1, typeof(byte)));
Expression.Add(Expression.Constant(Int32Enum.a), Expression.Constant(1, typeof(short)));
Expression.Add(Expression.Constant(Int32Enum.a), Expression.Constant(1, typeof(ushort)));
Expression.Add(Expression.Constant(Int32Enum.a), Expression.Constant(1, typeof(int)));

// Throws ArgumentException, correctly
Expression.Add(Expression.Constant(Int32Enum.a), Expression.Constant(1, typeof(uint)));
Expression.Add(Expression.Constant(Int32Enum.a), Expression.Constant(1, typeof(long)));
Expression.Add(Expression.Constant(Int32Enum.a), Expression.Constant(1, typeof(ulong)));
```
My understanding is that Linq Expressions try to mimic C#'s behaviour as much as possible, so this could be an area to align with C#.

/cc @bartdesmet @VSadov  @JonHanna @stephentoub

**Comment by bartdesmet** [comment]
Expression trees generally don't insert conversions or other nodes on behalf of the user when calling a factory (a notable example is the automatic insertion of `Quote` nodes around `Lambda` nodes when assigned to an `Expression<T>` parameter). The code generated by the C# compiler for an expression of this kind will include these conversions though.

The factory methods are closer to what-you-see-is-what-you-get rather than introducing implicit behavior automatically, which is left to every front-end language to decide. There are notable exceptions with nullable lifting, some of the voodoo in `Coalesce` on implicit numeric conversions, etc.

For the example above, the enum shouldn't make a difference; you'll get exactly the same error when trying to add an `int` and an `sbyte` together. No widening conversions are considered by the factory.

**Comment by hughbe** [comment]
My bad, closing this (as well as #11705)
