### ISSUE TITLE
Parse (and TryParse) method doesn't work with some locales.

### ISSUE THREAD

**Issue by quincy666** [dotnet/corefx#11742]
Parse (and TryParse) method doesn't work with `prs` and `prs-AF` locale if 'NumberStyles.Any' passed to the method (and number must be 1000 or more).
`var c = new CultureInfo("prs");`
`var t = double.Parse((1000.55).ToString("n2", c), NumberStyles.Any, c);`

It will throw `System.FormatException` (Input string was not in a correct format.)
The same issue with full framework. Tested only on windows.

I tried to use different number styles and it fails when I add `AllowCurrencySymbol`

**Comment by tarekgh** [comment]
This is expected because the specified culture "prs" has the thousand separator and the currency separator as "."

when doing (1000.55).ToString("n2", c) it will give the string "1.000,55" when trying to parse this while passing NumberStyles.Any, The parser will recognize "." as a currency separator and then will proceeded and fail later because this is not well formatted currency. 

Note that the Parser cannot guarantee parsing any number when have something ambiguous like this case.  

To have this succeed is to specify you are parsing decimal numbers and allowing thousand separator. 

```
            var t = double.Parse(s, NumberStyles.AllowDecimalPoint | NumberStyles.AllowThousands, c);
```
