### ISSUE TITLE
Port System.Net.Cache

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#11791]

**Comment by davidsh** [comment]
This will be difficult to implement beyond just stubbing out.  The current System.Net.Cache in .NET Framework (Desktop) uses legacy Windows Wininet APIs to provide a cache for HTTP responses.

**Comment by karelz** [comment]
I assume that means implementing special x-plat solution.
How much of this API is purely perf vs. also some ad-on functionality/behavior? I can imagine we could just stub out the perf code.
I wonder what Mono implementation has.

**Comment by davidsh** [comment]
The actual types in System.Net.Cache namespace are simple.  There are 3 enums and 2 classes.  All of these types specify and control behavior for WebRequest, HttpWebRequest APIs.

So, from a contract perspective, these types will go into the System.Net.Requests contract.

I will look into this.  And yes, stubbing out the types are fine for now.

**Comment by davidsh** [comment]
So, we closed this issue now since the stubs for this are done. But the "port" isn't really done since it is basically a no-op.

Are we opening new issues for the real "port"?

**Comment by karelz** [comment]
What is the impact of leaving in just the stubs? Functional/compat impact? Performance impact on some scenarios?

**Comment by davidsh** [comment]
It depends.  Some scenarios might want/need caching for performance reasons. But the reality is that I don't think many apps really use those old System.Net.Cache APIs.

I think we should see how many Top-N apps are affected by just stubs before we invest a ton of time trying to implement a caching layer for the legacy HttpWebRequest APIs

**Comment by stephentoub** [comment]
I'm not really familiar with the caching design here: is it possible to implement the appropriate caching on top of HttpClient?

**Comment by davidsh** [comment]
First, HttpClient API surface doesn't support specifying caching.  The use of the Cache* APIs and enums only really show up in the HttpWebRequest API surface.

We do have customers that use HttpClient and implement a caching architecture by writing new handlers and using them in their pipeline of handlers.  That would be the only place to implement this given the HttpClient architecture.  And since HttpWebRequest in .NET Core is *implemented* on top of HttpClient, it could, in theory, use additional handlers to do this.  Each HttpWebRequest call basically creates a new HttpClient() for each web request (which is poor for performance but the HttpWebRequest API is really legacy app-compat).

**Comment by karelz** [comment]
I would suggest to not open a new issue, until we get feedback that perf matters for some compat scenario.
