### ISSUE TITLE
Remove Regex Caps and CapNames properties

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#11810]
Follow Up on #11779 

Now that we have exposed the old caps, and capnames fields we should see if we can remove the Caps and CapNames properties.

**Comment by alexperovich** [comment]
@weshaggard

**Comment by karelz** [comment]
Why would we want to remove properties? Are they new in .NET Core 1.0?

**Comment by weshaggard** [comment]
Yes they are new in .NET Core 1.0 we added them to avoid depending on Hashtable but we backtracking a bunch of those type of decisions now with our compat work.

**Comment by karelz** [comment]
Are we concerned about compat with .NET Core 1.0? Or do we treat these instances as 'failed' experiment which is ok to revert?
Sounds like we should track it for 1.1 -- the sooner we make it happen, the better.

**Comment by weshaggard** [comment]
I suspect we will end up keeping these in the name of compat but I marked it as api-ready-for-review to discuss it at our weekly triage meeting.

**Comment by terrajobst** [comment]
While these APIs are part of .NET Standard (1.5+) they are not part of .NET Standard 2.0. We've also shipped them in .NET Core 1.0.

We generally don't do breaking changes for shipped bits. Unless there are very compelling reasons not to have them, we shouldn't remove them now.

We should, however, not expose them in .NET Framework because there is no longer any reason for them to exist. Also, there might be some benefit by avoiding compat issues (the property names only differ by casing from the protected fields).
