### ISSUE TITLE
Add ServicePointManager / ServicePoint

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#11885]
Add stubs for all these APIs.

**Comment by davidsh** [comment]
Place them for now in a new System.Net.ServicePoint contract

**Comment by stephentoub** [comment]
Stubbed out in https://github.com/dotnet/corefx/pull/11929

**Comment by janpieterz** [comment]
Is there currently a way to retrieve the `X509Certificate/2` from a URI while the ServicePoint is not present on the `HttpWebRequest`?

**Comment by davidsh** [comment]
>Is there currently a way to retrieve the X509Certificate/2 from a URI while the ServicePoint is not present on the HttpWebRequest?

Yes. Developers are encouraged to use System.Net.Http.HttpClient APIs instead of HttpWebRequest.

See the `ServerCertificateCustomValidationCallback` property:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/ref/System.Net.Http.cs#L96

Using that will give you access to the `X509Certificate` object during the HTTP connection.

**Comment by janpieterz** [comment]
@davidsh cheers! It seems like that is only available on the core version and not dotnet461. Is there any way that it works for both .net core and dotnet461? ;)

**Comment by davidsh** [comment]
> It seems like that is only available on the core version and not dotnet461. Is there any way that it works for both .net core and dotnet461? ;)

While the .NET Framework 4.6.x has System.Net.Http API, that 'contract" is at 4.0 level, these new APIs are at 4.1 level.  

However, we OOB'd the binary so that you can use the NuGet System.Net.Http 4.1 package on Desktop (.NET Framework 4.6.x).  It will "replace" the GAC'd System.Net.Http reference assemble and implementation binary. So, you can use it on Desktop.

**Comment by janpieterz** [comment]
I get the gist, but am having a bit of trouble getting it to work. Adding 4.1.0 to the dependencies (regardless if it is in all dependencies or per framework) results in the net461 framework resolving to System.Net.Http 4.0.0 (`C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Net.Http.dll`). How do I 'force' this one to resolve it through the nuget 4.1.0? I also don't know the meaning of OOB, which might hold an essential clue. Sorry for the trouble over something this simple.

**Comment by stephentoub** [comment]
Now that these are stubbed out, we at least need a basic implementation for FindServicePoint and ServicePoint, e.g. returning valid ServicePoint objects from FindServicePoint, tracking them in a weak table, etc.
