### ISSUE TITLE
Directory.GetDirectories returns zero sub-directories with search pattern "*." on Unix

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/corefx#11943]
On windows using search pattern "*." returns all the sub-directories but on Unix it returns zero sub-directories. Is there a reason why this difference exist? cc @stephentoub @ianhays 

```csharp
using System;
using System.IO;

class Program
{
    static void Main(string[] args)
    {
        string[] subDirs = Directory.GetDirectories(
            @"C:\Program Files", // On Unix try "/etc"
            "*.");
        Console.WriteLine(subDirs.Length);
        foreach(var dir in subDirs)
        {
            Console.WriteLine(dir);
        }
    }
}
```

**Comment by stephentoub** [comment]
> On windows using search pattern "*." returns all the sub-directories

FWIW, it doesn't, actually.  For example, this program only prints out the two directories that don't include '.' in the name:
```
using System;
using System.IO;

class Program
{
    static void Main()
    {
        DirectoryInfo root = Directory.CreateDirectory("tmpRoot");
        root.CreateSubdirectory("Some Subdir 1");
        root.CreateSubdirectory("Some.Subdir 2");
        root.CreateSubdirectory("Some Subdir 3.0");
        root.CreateSubdirectory("Some Subdir 4");
        foreach (string subdir in Directory.GetDirectories(root.FullName, "*."))
        {
            Console.WriteLine(subdir);
        }
    }
}
```

**Comment by JeremyKuhne** [comment]
This is due to legacy DOS support in Windows.  In DOS the period was only legal as a separator from the file extension, which was technically separate from the file name. In searching for files `*.` meant "any filename with no extension".

`*.` is _technically_ "zero or more characters followed by a period". In order to be compatible with the legacy meaning `*.` and `*.*` are given special handling internally in Windows. `*.` is essentially transformed into "anything that doesn't have a period" (the opposite of what the pattern actually denotes). As a result, if you create a directory named `Foo.Bar`, `GetDirectories()` will *not* return it using `"*."` on Windows.

The only sure way to get all directories is to use `"*"` or filter yourself using file attributes if you're not using an API that already filters for you.
