### ISSUE TITLE
Figure out how to deal with ResourceSet/ResourceManager Hashtable dependency

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#12011]
We need to expose ResourceSet.Table but this would mean exposing Hashtable from corelib.

**Comment by jkotas** [comment]
> System.Resources.ResourceWriter

This type is in corefx. Instead of adding it to CoreLib, you should load it via reflection - it is one of the strategies that we are using to deal with bad deps. Example: https://github.com/dotnet/coreclr/blob/8eec3c5ac8975734836c333187a2724d50bd9af9/src/mscorlib/src/System/Reflection/Emit/ILGenerator.cs#L1176

> System.Resources.ResourceSet.Table

The type of this field is `Hashtable`. To move this into CoreLib, you would need to move the public Hashtable and all it depends on from `System.Collections.NonGeneric` to CoreLib as well ... it would be nice to find a way how to avoid it. cc @weshaggard

**Comment by alexperovich** [comment]
The Table field is already in the sources as internal. Is BclRewriter removing it?

**Comment by jkotas** [comment]
corelib has internal version of Hashtable type that is not visible outside of corelib - BclRewriter flips the Hashtable to internal.

**Comment by alexperovich** [comment]
Okay, I will see about pulling out ResourceSet into a package.

**Comment by alexperovich** [comment]
The ResourceSet/Manager cannot be removed from corelib. I am exposing the new apis without those Hashtable fields.

**Comment by weshaggard** [comment]
Linking to API removal issue https://github.com/dotnet/standard/issues/36.
