### ISSUE TITLE
ProxyAuth test fails on *Nix outerloop runs

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#12015]
PR #11985 added a new test which is failing on *Nix (part of OuterLoop):

`System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.UseCallback_HaveNoCredsAndUseAuthenticatedCustomProxyAndPostToSecureServer_ProxyAuthenticationRequiredStatusCode`

```
System.Net.Http.CurlException : Failure when receiving data from the peer
```

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by Priya91** [comment]
We are tracking this as part of networking test cleanup.

**Comment by Priya91** [comment]
Debugged through this, this failure is happening because of a curl bug/difference in behavior. Curl is parsing the http status code 407 (proxyauthrequired) and throwing a curl (56) CURLE_RECV_ERROR error from curl_multi_info_read when using a proxy to connect to a https server. Although when trying to connect to a http server using proxy, curl returns CURL_OK code, and the call to curl_easy_getinfo return the 407 httpstatuscode.

We will have to accomodate for this difference by using CURLINFO_HTTP_CONNECTCODE in curl_easy_getinfo to get the httpstatuscode 407.
