### ISSUE TITLE
ConcurrentDictionary performance issue

### ISSUE THREAD

**Issue by Opiumtm** [dotnet/corefx#12067]
Dictionary with plain `lock` performs about 10x faster than ConcurrentDictionary

**Comment by stephentoub** [comment]
> Dictionary with plain lock performs about 10x faster than ConcurrentDictionary

For what operation?  What are you testing?

ConcurrentDictionary is optimized for reading and for many parallel updates.  If your test just does serialized adds to the dictionary, yes, Dictionary will be faster than ConcurrentDictionary.

**Comment by Opiumtm** [comment]
I have tested mostly serialized adds

**Comment by stephentoub** [comment]
> I have tested mostly serialized adds

Yes, by design I would expect Dictionary to do better in that test.  ConcurrentDictionary is implemented to provide lock-free reads, so reads are fast compared to a locked Dictionary.  It also uses striped locking, with multiple locks that each protect different buckets of the dictionary; as a result, if you have lots of threads all concurrently doing writes to the dictionary, it also performs better than a Dictionary.  But if all you're doing is simply adding to the dictionary from a single thread, you're better off using a Dictionary.
