### ISSUE TITLE
Sys.Runtime.Int.WindowsRuntime broken on Android

### ISSUE THREAD

**Issue by onovotny** [dotnet/corefx#12070]
We've been getting [reports](https://github.com/Reactive-Extensions/Rx.NET/issues/261) that the `System.Runtime.InteropServices.WindowsRuntime` package may be broken on Android.

Looking at the package, it has a blank impl for `xamarinios1` but not for the other Xamarin types. As Xamarin supports NET Standard 1.6, it's pulling in the `netstandard1.3` impl. This seems to be causing an issue on build:

```
Error   CS1703  Multiple assemblies with equivalent identity have been imported: 'C:\Projects\NS\Kanzi.Mobile\packages\System.Runtime.InteropServices.WindowsRuntime.4.0.1\lib\netstandard1.3\System.Runtime.InteropServices.WindowsRuntime.dll' and 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\System.Runtime.InteropServices.WindowsRuntime.dll'. Remove one of the duplicate references.  Mobile.Core.Android C:\Projects\NS\Kanzi.Mobile\Mobile.Core.Android\CSC 1   Active
```

/cc @ericstj

**Comment by ericstj** [comment]
This should be fixed in the latest packages as of https://github.com/dotnet/corefx/commit/e586f1b2f4eca793de97361aa4b981eb966d13ec.

Can you try referencing the pre-release version of NETStandard.Library and see if you still hit the problem?

Point nuget to `https://dotnet.myget.org/F/dotnet-core/api/v3/index.json`
and reference `"NETStandard.Library": "1.6.1-preview1-24525-03"`

**Comment by danmosemsft** [comment]
@onovotny is this resolved?

**Comment by onovotny** [comment]
Yes, seems to fix it.
