### ISSUE TITLE
Investigate IO differences in sanitizing characters when creating directories

### ISSUE THREAD

**Issue by FiveTimesTheFun** [dotnet/corefx#1222]
Investigate three IO test failures that could imply behavioral difference between desktop / core:
Creating a subdirectory consisting only of spaces
Creating a subdirectory named ".."
Creating a directory with trailing \t\t\t\n whitespace

**Comment by ianhays** [comment]
As of now, the core Directory whitespace behavior functions the same as the core File behavior on Windows. On Unix, whitespace is preserved in a path regardless of location as a result of #2267.

Directory.CreateDirectory("..") will return the parent directory as expected. 

Trailing whitespace is currently removed in the Windows implementation (but of course kept in the Unix implementation) to be in line with desktop. We could change the behavior to match that of Unix and keep the invalid trailing whitespace, but there isn't really a use case for it and it would only raise errors where there didn't use to be any. Although it'd be more consistent for Xplat, it may not be worth changing.

Since these tests no longer fail, I'm going to close this in a few days if no one else has any comments to add.
