### ISSUE TITLE
Investigate IO test - DirectoryInfo.Exists

### ISSUE THREAD

**Issue by FiveTimesTheFun** [dotnet/corefx#1223]
A ported test from desktop verifies the instance property DirectoryInfo.Exists is updated when the directory is deleted from the same instance of DirectoryInfo.  The test fails when ported, need to investigate the desired behavior.

**Comment by ianhays** [comment]
Hmmm, this seems like undesirable behavior; when the DirectoryInfo.Delete method is called, it makes sense that it would update the underlying FileSystemObject such that subsequent calls to DirectoryInfo.Exists return False without having to Refresh first. A quick glance at the implementation suggests the simplest way to do this would be to call Refresh() after deleting the directory, but that will potentially cause problems elsewhere since the entire cache would be overwritten.

However, if we do change this behavior then it raised the question: <i>"when should the cached DirectoryInfo be replaced? Should it only be on Refresh() or when otherwise logically applicable as the result of a DirectoryInfo method call?"</i> Although the ported DirectoryInfo.Exists functions in the latter fashion, all of the other DirectoryInfo attributes (WriteTime, Attributes, etc) function in the former. Why should Exists be the only Property updated without Refreshing first? It is inconsistent in the old implementation, but perhaps less useful in the current implementation.

I agree that it could use more investigation as to which route is best.

**Comment by ianhays** [comment]
@stephentoub what are your thoughts on this? Would invalidating the cached DirectoryInfo on Delete() by refreshing the object be too much? I'm torn 50/50 on which is the better solution.

**Comment by ianhays** [comment]
I'm going to leave this behavior as is to keep it inline with the desktop version. I added the following test for it:
```
DirectoryInfo dir = Directory.CreateDirectory(Path.Combine(TestDirectory, Path.GetRandomFileName()));

Assert.True(dir.Exists);

dir.Delete();

Assert.True(dir.Exists);
dir.Refresh();
Assert.False(dir.Exists);
```
