### ISSUE TITLE
Create new PreviewAttribute that generates compiler warning for using preview/beta functionality

### ISSUE THREAD

**Issue by dotMorten** [dotnet/corefx#12259]
We have ObsoleteAttribute to generated a compiler warning when users are using obsolete APIs.
Similarly it would be amazing to have a PreviewAttribute for functionality that is still considered "beta" and not yet finalized. This notifies the user that this API might change or not be 100% functional.
The alternative is to create special beta-namespaces  or put beta in the member names, but that would most definitely create breaking changes once the new APIs are finalized.

**Comment by svick** [comment]
I don't understand when would this be useful. In a NuGet-based world, you're generally in one of two situations:

* You want only stable APIs, so you use stable versions of packages. In this case, the packages wouldn't have any preview functionality, so you wouldn't get any warnings.
* You want to use preview APIs, so you use preview versions of packages. In this case, you would get preview warnings, but they would all be noise, since you explicitly chose to use preview functionality.

What am I missing?

**Comment by dotMorten** [comment]
It's actually pretty common to release fully supported APIs that the user can rely on and expect support for, while also giving them early access to new APIs that might not be been fully completed yet. 
It also reduces the number of releases you need to simultaneously manage and reduces the number of release cycles requite.

Now I get what you're saying. and that works for small nimble SDKs, but with larger SDKs it greatly reduces overhead by combining them into one.

I don't really see your point about "in a nuget-based world". No idea what that means. I don't see how it would be any different in "an assembly reference based world".

**Comment by AlexGhiondea** [comment]
If you are shipping an assembly as part of a NuGet package then you can use the NuGet package versioning to identify the package as preview/beta.

If you are not shipping as a NuGet then it really depends on how your consumers get the latest API.

I am not sure I see a scenario where you are making an API available but it would not be working.

I don't see the value of having this attribute as part of Core versus having it as part of your project.
