### ISSUE TITLE
StringBuilder.AppendLine(char)

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#12278]
### Rationale
We have a `StringBuilder.AppendLine(string)` method that basically does `Append(string)` followed by `Append(Environment.NewLine)`

However, `StringBuilder`also provides `Append(char)` for performance reasons (avoids string copying, allocations etc)

I spotted this in #12277 where @bartdesmet has multiple calls of `AppendLine(string)` where `string.Length==1` 

### Proposed API
```
class StringBuilder
{
    void AppendLine(char value);
}
```

I'm gonna tag @jamesqo @justinvp @benaadams  @jkotas as you all like your perf stuff and would love your comments

**Comment by justinvp** [comment]
It's certainly a micro optimization, but I do prefer calling `Append(char)` instead of `Append(string)` when `string.Length == 1`.

On the one hand, it would be nice if there was an `AppendLine(char)` to match the existing `AppendLine(string)`, which would basically just be a convenience over `Append(char).AppendLine()`.

On the other hand, there are a lot of `Append` overloads that take various types... Does this open the door to adding many more `AppendLine` overloads to match the existing `Append` overloads? I'm not sure it's worth ballooning the number of `AppendLine` overloads. So what makes `char` special over any of those other types and are there any others in the same bucket?

**Comment by hughbe** [comment]
I certainly wouldn't support an AppendLine for each primitive. Certainly char instinctively seems to be a good fit as it represents text.

**Comment by jkotas** [comment]
> I'm not sure it's worth ballooning the number of `AppendLine` overloads. 

I agree. Single character lines does not seem to be worth to optimize for in StringBuilder API design. Folks who really care about this micro-optimization can always add it locally as extension method.

**Comment by hughbe** [comment]
I think you're right. I'll close this issue. If someone pushes back, we can reopen this, but that's probably unlikely
