### ISSUE TITLE
Dispose MemoryStream

### ISSUE THREAD

**Issue by SunnyWar** [dotnet/corefx#12288]
`private static byte[] ConstructDSSPublicKeyCspBlob(byte[] encodedKeyValue, byte[] encodedParameters)` initializes a MemoryStream without disposing it and without returning it or assigning it. A quick search shows at least a dozen places in corefx that act similiarly.  If there's a reason for this, I'd like to know what it is since the documentation clearly indicates that it should be disposed. If not, then let's clean these up.

**Comment by svick** [comment]
What would be the point? [`MemoryStream.Dispose()`](https://github.com/dotnet/corefx/blob/0cc9db0/src/System.IO/src/System/IO/MemoryStream.cs#L147-L164) does nothing except to prevent most further operations from succeeding.

As far as I can tell, even the comment about cleaning up async resources is wrong (since [`Stream.Dispose()`](https://github.com/dotnet/coreclr/blob/6409491/src/mscorlib/src/System/IO/Stream.cs#L260-L265) does not do anything).

The documentation contains just the standard disclaimer for `IDisposable`, I think it can be safely ignored in this case.

**Comment by SunnyWar** [comment]
@svick I looked through the code and your are right...and it's even worse, it calls the base.Dispose inside a catch clause, which subsequently does nothing at all. So adding Dispose would just but make the code slower with no upside.

Seems to me two things need to happen in this case:
1. The documentation should be updated as most developers (the ones that actually read the docs) aren't fooled into writing slower code.
2. Remove the try/catch and the call base.Dispose in the Dispose method.
