### ISSUE TITLE
Port System.Security.Cryptography.CryptoConfig

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#12327]
- Hard-code various algorithm names, cross referencing Mono
- Add Create(string) factory methods to various algorithm classes per netstandard2.0

```
public class CryptoConfig
M:CryptoConfig.#ctor
P:CryptoConfig.AllowOnlyFipsAlgorithms
M:CryptoConfig.CreateFromName(System.String)
M:CryptoConfig.CreateFromName(System.String,System.Object[])
M:CryptoConfig.EncodeOID(System.String)
M:CryptoConfig.MapNameToOID(System.String)
```

Also these (but throw PNSE)

```
 public static void AddAlgorithm(System.Type algorithm, params string[] names) { }
 public static void AddOID(string oid, params string[] names) { }
```

**Comment by morganbr** [comment]
Does this also imply re-adding FIPS enforcement? If so, would we try to do that cross-platform?

**Comment by bartonjs** [comment]
@morganbr I dunno, that setting has always been weird.  Like FIPS doesn't want you doing RSA-MD5; but (AFAIK) they don't have an objection to computing the Content-MD5 header for HTTP; and we just have a big kill switch.  I think we can let people detect it ('cuz why not?) but we should leave FIPS-ness up to the native library.

@steveharter My thoughts here:
* Everything is hard coded, particularly since we got rid of the mutation methods.
* Nothing that we already have should use CryptoConfig (particularly since it's immutable); only when the thin wrapper Create methods come back should anything internal be calling it.
* What storage? Everything's hard-coded.

**Comment by danmosemsft** [comment]
@steveharter I don't see `public static byte[] EncodeOID(string str);` ... did you omit it intentionally? We should have it even if it only throws.
