### ISSUE TITLE
System.Runtime.CompilerServices.IsConst is defined in both System.Runtime and S.P.CoreLib 

### ISSUE THREAD

**Issue by SedarG** [dotnet/corefx#12449]
be96103263c9d57ce22295dd3906b96c2ae722be brings S.R.CompilerServices.IsConst to System.Runtime. However it already exists in S.P.CoreLib for AOT (see https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/Runtime/CompilerServices/IsConst.cs). It's indeed defined in CoreCLR too (see https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Runtime/CompilerServices/IsConst.cs). This type should have been forwarded to System.Private.CoreLib.

**Comment by ramarag** [comment]
Is this a concrete requirement of corert, i.e. there are internal implementations of corert that use this attribute and can not reference the corefx library. If so assign this issue back to me.

Otherwise the right thing to do is to remove it from corert
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/mscorlib.shared.sources.props#L31 indicates the above file is not compiled for coreclr. [ The file exists because the source is shared with desktop, and desktop indeed gets it from the above file]

**Comment by jkotas** [comment]
I agree with Rama - it should be removed from CoreLib unless there is a good reason to have it there.

**Comment by SedarG** [comment]
This is fixed on CoreRT with this commit: https://github.com/dotnet/corert/commit/e8a98085fcbbba8dccbc6d433a9c366b5d79ae7c
