### ISSUE TITLE
SqlConnection.Open() thrown SqlExceptions do not have an error number on OSX/Linux

### ISSUE THREAD

**Issue by MitchellSternke** [dotnet/corefx#12472]
If you call Open() on a SqlConnection that errors out (for example, because of a bad hostname), the thrown SqlException will not contain an error number on Mac OSX (i.e. SqlException.Number is always 0). 

I specifically noticed this with SqlException error code 53 "A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections."

On Windows for the above scenario, the SqlException that I catch has a Number property value of 53. On OSX, it is 0.

Edit: This also appears to be an issue on Linux

**Comment by saurabh500** [comment]
@corivera Is it possible to get the networking error numbers from Managed SNI as well? 

@MitchellSternke This is expected behavior for now. In case of SqlClient on Windows, the error numbers are present because the SqlClient uses the Windows networking error codes to populate SqlErrors.

For MacOS and Linux we rely upon the errors being sent by the System.Net.* APIs from .Net framework itself which may not have an associated error code AFAIK.

We will evaluate if it is possible to get an error code in this case.

**Comment by saurabh500** [comment]
Since there is no error code returned from the underlying Networking calls, it wouldn't be feasible to send them up to SqlException on OSX and Linux.
