### ISSUE TITLE
FtpWebRequest can throw an exception if FtpWebResponse.Close is called without draining the response stream

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#12542]
This issue exists in the desktop framework as well.

Run the following code:

```c#
string resource = absoluteUri + "LargeFile";
FtpWebRequest r1 = (FtpWebRequest)WebRequest.Create(resource);
r1.Method = WebRequestMethods.Ftp.DownloadFile;
FtpWebResponse resp1 = (FtpWebResponse)r1.GetResponse();
resp1.Close();

```

On occasion, depending on the file size and other factors, you'll hit an exception in Close:

_An unhandled exception of type 'System.Net.WebException' occurred in System.dll
Additional information: The remote server returned an error: (550) File unavailable (e.g., file not found, no access)._

The referenced "LargeFile" needs to be large enough to hit the timing issue here.  I hit it consistently with a 12MB file.  I was using IIS as the server, running on localhost.

The problem here is that when you call Close before you’ve fully downloaded the response, we reset the data connection.  This can make the server unhappy if it hasn't finished writing the requested file to the data connection (at least, it makes IIS unhappy, and it seems likely it would make other servers unhappy too).  IIS sends us a 550, and we then translate this into a WebException in Close.

Assuming that we care about this scenario, then we either need to ignore the 550 in the scenario, or change the logic to not cause the server to generate one.

**Comment by CIPop** [comment]
I agree with @geoffkizer: since all the invocations are synchronous, we need to ensure that GetResponse() will not return until all data is drained.

Testing the fix requires a local FTP server. Since we're touching this code we should properly add a [new Configuration.Ftp.cs](https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Net/Configuration.Http.cs) instead of the one-off Environment variable [here](https://github.com/dotnet/corefx/blob/4d496f8b7387395b07ae99ef48e35390b7e25107/src/System.Net.Requests/tests/FtpWebRequestTest.cs#L79).

**Comment by karelz** [comment]
Triage: 3 years no customer hit this. No takers. Let's close it.
