### ISSUE TITLE
Provide APIs to determine OS, Distribution, Version, Bitness and other useful Info

### ISSUE THREAD

**Issue by richlander** [dotnet/corefx#12737]
I would like to be able to get this information from System.Environment.

I've been recently playing with the lsb_release command. I should be able to get most of this same information from System.Environment.

I saw some earlier discussions on some APIs leading to bad practices (for example, checking feature availability based on versions). All true, but I don't think we should use those bad practices as a reason not to make APIs available. That's the role of documentation and samples, IMO.

Related: https://github.com/dotnet/corefx/issues/1017

**Comment by danmosemsft** [comment]
On Environment we now have OSVersion, Is64Bit, Is64BitProcess

**Comment by richlander** [comment]
Which version of the product is that for? 1.2?

**Comment by danmosemsft** [comment]
Yes

**Comment by mellinoe** [comment]
.NET Core 1.0 actually has more of this information, via `System.Runtime.InteropServices.RuntimeInformation`. We should probably treat the stuff in `Environment` as legacy, anyways, not as a future-proof way to query information about the system. Is there something else you need than is exposed by `RuntimeInformation`?

**Comment by terrajobst** [comment]
`System.Environment` doesn't expose this in .NET Core 1.0 as we were asked to remove versioning APIs due to compat concerns. However, they come back in vNext as part of .NET Standard 2.0.

For 1.0, the APIs that @mellinoe pointed you to should address these concerns partially. Most of the APIs return strings, but depending on your use case this might work.

**Comment by Petermarcu** [comment]
Ok, so is this already addressed then in 1.2 with .NET Standard 2.0 support?

**Comment by mellinoe** [comment]
@Petermarcu `RuntimeInformation` (in .NET Core 1.0) offers quite a bit of this information. The new stuff we are adding back in 2.0 has some related things, but nothing that we don't already expose in `RuntimeInformation`.

@richlander mentioned `lsb_release`, which prints out a couple more things that we don't expose anywhere (in 1.0 or 2.0).

```
Description:    Ubuntu 16.04 LTS
Codename:       xenial
```

`RuntimeInformation.OSDescription` gives the same information as `uname -a` (by design):

```
Linux 4.4.0-42-generic #62-Ubuntu SMP Fri Oct 7 00:00:00 UTC 2016
```

So nothing about "16.04 LTS", or "xenial".

**Comment by Petermarcu** [comment]
So Rich, are you looking to have Description and Codename exposed?

**Comment by weshaggard** [comment]
@richlander are you wanting this information just as a description string or in some other form? Do you expect people to make runtime decisions based on it? 

If we want more APIs we need to put someone on this and write a design proposal for the scenarios we want to support. I also agree with @mellinoe that we should be preferring RuntimeInformation for new APIs over putting them on Environment because the Environment class doesn't have the agility we need in order to support the ever changing number of runtimes/os/etc we want to run on.

**Comment by Priya91** [comment]
Since you mention lsb_release for retrieving this information, not all Linux distributions are LSB compliant. I had considering using this function while implementing ```RuntimeInformation.OSVersion```, and because there is no guarantee on this being available on all distros, POSIX compliant uname was chosen.

**Comment by AlexGhiondea** [comment]
Regardless of how we implement this, @richlander do we want to have the API?

If we do, then we are going to need a formal API proposal for them.

**Comment by richlander** [comment]
Looks like @leecow has a proposal for this, which is great, with #16629.
