### ISSUE TITLE
Merge IO.Pipes and IO.Pipes.AccessControl assemblies

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#12761]
In https://github.com/dotnet/corefx/pull/8930 I brought Pipes AccessControl to CoreFX as its own separate assembly. This was fine with one exception (from the PR comments):

> Behavior is the same as the .NET 4.6 version of PipeSecurity/PipeAuditRule/etc. with the exception that the SetAccessControl extension method does not retain the same exception throwing behavior for NamedPipeClientStream. Since it's an extension method, we don't have access to the internal PipeStream State that is used in the full version to decide which error to throw. The original will throw an InvalidOperation for a WaitingToConnect stream or a IOException for a Broken stream. We just throw an InvalidOperation for either.

Now that back-compat is a higher priority, we should resolve this issue. One way to do that would be to merge the assemblies. Another way would be to make `PipeStream.CheckPipePropertyOperations` public.

caused the ToF test failure https://github.com/dotnet/corefx/issues/10899

**Comment by ianhays** [comment]
@weshaggard is there anything stopping me from merging these assemblies now?

My plan:
- Move all src/tests/ref from the AC assembly into System.IO.Pipes as Windows-specific inclusions
- Create PlatformNotSupported versions of the AC src for Unix systems
- Delete the packaging for the System.IO.Pipes.AccessControl package

**Comment by weshaggard** [comment]
You can do that for the netcoreapp specific build of the Pipes library, you cannot do it for a netstandard build of the library because the ACL APIs are part of .NET Standard. 

However by removing System.IO.Pipes.AccessControl you will prevent folks the .NET Standard version of Pipes from using ACLs for Pipes. They will only be able to use them if they target .NET Framework or .NET Core specifically. So we really should consider keeping the AC library here and have it target .NET Standard still and give folks at least a way to accomplish the scenarios even if it isn't the exact same APIs.
