### ISSUE TITLE
Start running CoreFX tests against Mono

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#12864]
Currently we run these tests against Desktop, Core, UWP on Windows, Unix, OSX where applicable. Now we have an increased focus on compatibility with Xamarin/Unity, we should consider having these tests run against Mono as well.

**Comment by danmosemsft** [comment]
I haven't marked this NS2.0 as although very relevant to the effort it isn't essential and coudl be done later.

**Comment by mellinoe** [comment]
How do we plan to handle behavior incompatibility with mono? Traditionally, bug-for-bug parity with the mono implementation hasn't even been considered, but parity with .NET Framework has been a pretty big priority.

**Comment by jkotas** [comment]
> Traditionally, bug-for-bug parity with the mono implementation hasn't even been considered,

This is not about being bug-for-bug compatible.

**Comment by mellinoe** [comment]
I brought it up because many of our tests will probably fail due to behavior differences on mono. Right now, the tests weren't written with mono in mind, so it will be a bit of work to understand all those differences and re-configure the tests. When we have behavior differences between our current platforms, we usually either remove assertions (aka test coverage), write multiple tests, disable tests on certain platforms, change the platform's behavior etc. How would we handle that stuff for mono?

**Comment by ViktorHofer** [comment]
@danmosemsft is this about running the netstandard suite against mono or is this about adding a mono test configuration in corefx?

**Comment by danmosemsft** [comment]
I think https://github.com/dotnet/corefx/issues/30729 covers this sufficiently. That's just for netstandard surface area, but it's the first step if we/they want to cover more.
