### ISSUE TITLE
Add a more flexible special folder API

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#12892]
The current `Environment.GetFolderPath()` is based on the pre Windows Vista `CSIDL` based `SHGetFolderPath`. This API was depreciated and doesn't have any of the special folders introduced in Vista and beyond. We've updated the internal implementation in CoreFX to use the new `SHGetKnownFolderPath`, which takes a Guid. If we exposed a Guid based API we would allow:
1. Accessing newer or user registered special folders in Windows without code updates
2. Creating entries that we map to some more abstract cross-plat concept
3. Allow adding mappings on different runtimes/platforms that don't require updating all of the others

Something like the following:

``` C#
public static class Environment
{
    public static string GetFolderPath(Guid folderIdentifier)
    {
    }
}

public static class FolderGuids
{
     // commonly used folder ids / concepts

     // potentially even have Windows/Unix specific class/subclass
}
```

Adding values to the `SpecialFolder` enum can be complicated as there are assumptions baked into existing code that the values map directly to `CSIDL`'s. As such, the recommendation would be that the existing API be depreciated and the `Guid` API would be the primary.

Behavior of asking for an unknown `Guid` would be the same as the existing API- we return `String.Empty`.

I'll follow up shortly with a suggested set of predefined `Guid`s.

**Comment by mellinoe** [comment]
A few general, big-picture questions / observations:

* This probably shouldn't be in `Environment` since that would make it much harder to update and version.
* If this is designed with cross-platform behavior in mind, are `Guid`s the right level of abstraction? That seems very Windows-centric, and doesn't map to other platforms in a meaningful way. Folks picking this up on other platforms would probably be confused by that Windows-ism bleeding through in the public interface. If we wanted that specific functionality, should it go in a Windows-only library?
* To what extent are we actually able to support a common set of folders across operating systems? There are some standards for Linux platforms, but they are not universally followed, or are opt-in, or are subtly different across distros. Is this API supposed to give you back a folder that definitely exists, or just "might exist"? Options for mitigating this include creating our own global directory store.

**Comment by JeremyKuhne** [comment]
> This probably shouldn't be in Environment since that would make it much harder to update and version.

What would you suggest? From a discoverability perspective I think it's problematic to put somewhere else. Also, why is it harder to update? The idea is that `Guid`'s are way more version independent than `Enum` and we'd be selective in adding public `Guid` defines, at least in `System`.  Platform specific `Guid`'s can live in platform-specific libraries potentially.

> are Guid's the right level of abstraction?

More so than `CSIDL`s. :) The advantage of following the existing Windows pattern here is that we can provide folder definitions out-of-band and potentially provide user access to a registry of special folders (as already exists on Windows).

> Is this API supposed to give you back a folder that definitely exists, or just "might exist"?

Might exist, as per the existing API. You get back `String.Empty` when there isn't a definition.

**Comment by mellinoe** [comment]
> What would you suggest? From a discoverability perspective I think it's problematic to put somewhere else. Also, why is it harder to update? 

If it is on `Environment`, then that means the whole .NET Framework would need to be updated in order to get new functionality or bug fixes, etc. If it was an OOB assembly (not in the standard platform), then it could be shipped whenever, wherever, however we wanted on all platforms. With our new packaging plans for .NET Core, we would also need to wait for a new version of the .NET Core platform to get new functionality if we put it on `Environment`.

**Comment by knocte** [comment]
>> are Guid's the right level of abstraction?
> More so than CSIDLs. :)

But AFAIU, CSIDLs were never exposed in the .NET API. They were exposed in a higher level enum-based API. Are you planning to do the same for these GUIDs?

**Comment by JeremyKuhne** [comment]
> If it was an OOB assembly (not in the standard platform), then it could be shipped whenever

I'd like to see a good OOB story, but I don't think we have one yet. I'd personally like to see a place where code like this could live in tandem as it works it's way into the Standard.

> But AFAIU, CSIDLs were never exposed in the .NET API. 

They weren't, but I've seen code that has taken advantage of the values actually being CSIDLs.

> They were exposed in a higher level enum-based API. Are you planning to do the same for these GUIDs?

Not in an enum. Common GUIDs will live in the static class I described. Moving away from an enum to identifiers allows out-of-band updating once it makes it into .NET Standard.

For Windows it's a pretty simple front end to what the Shell already provides. In theory we'd never need to make another code change to allow for new folders.

For Unix the closest registry of folders is the XDG user directories, which we already try and [use](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L249). Long term an external guid-to-xdg name map on Unix might be worth considering- as it would allow getting out of having to update code on this end as well.


I also envision potentially adding a `SetFolderPath(Guid)` in the future.

**Comment by JeremyKuhne** [comment]
Bailing on this idea for now. If someone has an interest we can resurrect.
