### ISSUE TITLE
Port x-plat SecureString implementation from CoreFX to mscorlib

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#13062]
@shrah commented on [Wed Oct 26 2016](https://github.com/dotnet/coreclr/issues/7834)

The x-plat SecureString implementation need to be ported from corefx/src/System.Security.SecureString/src/System/Security/SecureString.cs  to mscorlib. This is required in order to port the Marshal.SecureStringTo\* APIs as they take SecureString as parameter.

**Comment by AlexGhiondea** [comment]
I think the right approach is to pull the type (SecureString) and it's closure down into S.Runtime. We can probably re-use the implementation we already have inside S.S.SecureString and move that as well into S.Runtime.

/cc @weshaggard in case he disagrees.

**Comment by stephentoub** [comment]
I was actually wondering if the right answer was to pull most of Marshal up, as we've done with Environment, Thread, etc., exposing from the runtime just the necessary pieces to make it work, e.g. the internal calls.

**Comment by stephentoub** [comment]
(Alex,  maybe we're saying the same thing?)

**Comment by AlexGhiondea** [comment]
@stephentoub from chatting with @yizhang82 it sounds like pulling Marshal up is not really possible. There is code in CoreLib that uses Marshal already.

What I was thinking is more along the lines of:
- Take the implementation of System.Security.SecureString and copy it down into System.Private.CoreLib. That implementation is already cross-plat and it would become **the** SecureString type.
- Expose that type in System.Runtime 
- Type forward from System.Security.SecureString to the type in System.Runtime.
- The Marshal class implementation can now take a dependency on the SecureString type (since they both live in the same place).
- The Marshal class surface area should also be able to use the type (since it is in System.Runtime)
- There are additional APIs that use SecureString and those could start using the type since it would be exposed in System.Runtime.

**Comment by AlexGhiondea** [comment]
Intial work (to port this into CoreCLR) is in PR: https://github.com/dotnet/coreclr/pull/7884

**Comment by weshaggard** [comment]
>Expose that type in System.Runtime

SecureString shouldn't be in System.Runtime contract. The Marshal APIs are in System.Runtime.InteropServices and so to expose those in the contracts we would need to move SecureString into that contract.

**Comment by weshaggard** [comment]
>There are additional APIs that use SecureString and those could start using the type since it would be exposed in System.Runtime.

We would need to take a closer look at those to see but hopefully they can depend either on System.Security.SecureString or System.Runtime.InteropServices.

**Comment by AlexGhiondea** [comment]
Exposing the type in CoreFx is in PR #13362

**Comment by AlexGhiondea** [comment]
This should be done now.
