### ISSUE TITLE
Several System.Transactions types have no serialization constructors.

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#13098]
The following types are serializable but have no serialization constructors.
- System.Transactions.SubordinateTransaction
- System.Transactions.CommittableTransaction
- System.Transactions.DependentTransaction
- System.Transactions.Transaction

This came from running FxCop analyzers on corefx. Reproduce steps found [here](https://gist.github.com/alexperovich/eabc4e9053ee8aca5bcda8caa379ea87).

"E:\corefx\src\src.builds" (default target) (1) ->
"E:\corefx\src\System.Transactions\src\System.Transactions.builds" (Build target) (472) ->
"E:\corefx\src\System.Transactions\src\System.Transactions.csproj" (Build target) (473) ->
  System\Transactions\SubordinateTransaction.cs(8,25): error CA2229: Serializable type SubordinateTransaction doesn't have a serialization constructor [E:\corefx\src\System.Transactions\src\System.Transactions.csproj]
  System\Transactions\CommittableTransaction.cs(11,25): error CA2229: Serializable type CommittableTransaction doesn't have a serialization constructor [E:\corefx\src\System.Transactions\src\System.Transactions.csproj]
  System\Transactions\DependentTransaction.cs(10,25): error CA2229: Serializable type DependentTransaction doesn't have a serialization constructor [E:\corefx\src\System.Transactions\src\System.Transactions.csproj]
  System\Transactions\Transaction.cs(57,18): error CA2229: Serializable type Transaction doesn't have a serialization constructor [E:\corefx\src\System.Transactions\src\System.Transactions.csproj]

**Comment by jimcarley** [comment]
This is due to the current lack of the ability to promote local transactions to distributed transactions.

SubordinateTransaction, CommittableTransaction, and DependentTransaction all derive from Transaction, which is the class that is marked as ISerializable.

Transaction has an implementation of GetObjectData, which calls InternalTransaction.State.GetObjectData.

In TransactionState.cs, there are various states that support GetObjectData. The others throw because serialization of the transaction in those states is invalid.

Serialization of a transaction implies that the transaction is going to "leave the process". This implies the need for distributed transactions.

In .NET Desktop, when a transaction is serialized, it is promoted to be a distributed transaction and there is an internal class that is the "end of the chain" for GetObjectData calls. This internal class is the one which has a serialization constructor implementation.

In .NET Core, transaction promotion to a distributed transaction is currently not supported. So any attempt to serialize a transaction will throw an exception.

When we develop the support for distributed transactions in .NET Core, then the class that will be used to deal with distributed transactions will be the one that has the final GetObjectData implementation and will have the serialization constructor for "rehydrating" the transaction.

If desired, we could remove the ISerializable reference for .NET Core 1.2 and add it back in when we implement the distributed transaction support.

**Comment by alexperovich** [comment]
Would it work to add the constructors and make them throw until the implementation is ready?

**Comment by jimcarley** [comment]
Yes, I suppose that's another alternative. Would it be sufficient from an FxCop perspetive to add that constructor to only the base Transaction class?

**Comment by alexperovich** [comment]
I think all of them need constructors.

**Comment by stephentoub** [comment]
Adding the ctors and having them throw sounds good to me.

**Comment by jimcarley** [comment]
In the pull request review for the changes, @stephentoub has indicated that we should probably just suppress the FXCop warning, given how we envision transaction serialization working when we finally get distributed transaction support.

So how do I go about suppressing the FXCop warning? Is it the same way is done on Desktop, with the SuppressMessage attribute?

**Comment by jimcarley** [comment]
I am thinking something like this on each of the classes:

        [SuppressMessage(FxCop.Category.Usage, FxCop.Rule. ImplementSerializationConstructors, Justification = "Serialization will be done when distributed transactions are supported and will be done through the exposed DistributedTransaction")]

**Comment by alexperovich** [comment]
The SuppressMessage works fine. Something like:

> [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2229", Justification = "<stuff>")]

**Comment by jimcarley** [comment]
Warnings suppressed with https://github.com/dotnet/corefx/pull/13276 and https://github.com/dotnet/corefx/commit/5169c2f5b18c149825cd1198cf86715bc1dbc7f3
