### ISSUE TITLE
Code coverage does not work for types implemented in corlib

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#13094]
Unfortunately many libraries in CoreFX are facades over implementations in mscorlib/System.Private.Corelib so this means right now we cannot get automatic code coverage for much of the types exposed by CoreFX.

mscorlib is consumed via a nuget package from the CoreCLR repo. For code coverage to work mscorlib.pdb and System.Private.Corelib.pdb need to be placed next to their implementations (in the directory of the test assembly). 

These symbols are not in the main nuget package. Possibilities
- get the symbols package manually (eg https://dotnet.myget.org/F/dotnet-core/symbols/runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR/1.2.0-beta-24619-02 ) and then crack it open
- get from the symbol servers by using [symchk](https://msdn.microsoft.com/en-us/library/windows/hardware/ff560157%28v=vs.85%29.aspx) .. example, `symchk.exe /s https://dotnet.myget.org/F/dotnet-core/symbols <path>\System.Private.CoreLib.ni.dll`. Potential issues: symchk is presumably Windows only and also will need to be gotten itself. 

As an aside there currently seems to be an issue with some of these symbols not being correctly propped to the symbol server right now.

@dagood what do you suggest?

/cc @stephentoub

**Comment by danmosemsft** [comment]
@crummel

**Comment by hughbe** [comment]
See: https://github.com/dotnet/corefx/blob/master/Documentation/building/facade-code-coverage.bat

**Comment by dagood** [comment]
I think the best way here is to download and extract the symbol package. We can rely on them being as available as the library package for dev builds, and if you know the package id + version to download, might as well use that instead of doing a lookup based on a DLL. There is also the Windows-only nature of symbol servers at the moment which downloading the symbol package works around.

> As an aside there currently seems to be an issue with some of these symbols not being correctly propped to the symbol server right now.

There was an email thread about this, so for anyone looking at this later we're pretty sure it's because MyGet has a case-sensitive symbol server endpoint when it should be case-insensitive, and we've asked for a fix.

**Comment by stephentoub** [comment]
I'm not sure getting the symbols is going to be sufficient.  For code coverage to be usable (i.e. good reports), the symbols need to point to valid source files, which won't be included in the symbol package.

**Comment by dagood** [comment]
Hmm, symbol packages are designed to carry sources, and CoreFX managed symbol packages do. Maybe we should work towards including them in native and CoreCLR symbol packages.

**Comment by mellinoe** [comment]
We discussed this a bit more, and it is probably a good idea to simply wait until we have finished some of our build refactoring work to address this. When we have full "vertical builds" enabled here, we should easily be able to gather code coverage information for every assembly, due to the nature of that build.

**Comment by danmosemsft** [comment]
@mellinoe how far are we off from making this work -- I'm not sure how much of the necsesary build refactoring remains. The linked issue for example is looking at CC for List. I'm not sure the "manual" instructions are still valid after the engineering work.

**Comment by danmosemsft** [comment]
@MattGal @mmitche should this go to core-eng?

**Comment by mmitche** [comment]
I'm not sure @MattGal what do you think?

**Comment by MattGal** [comment]
Currently I don't think that specific code coverage problems with specific libraries make sense for core-eng, I'd favor those going where the library itself is built.   I think we have some folks in Dan's org who are quite familiar though and may be able to provide guidance.

**Comment by weshaggard** [comment]
@danmosemsft correct me if I'm wrong but I think this works now that we have the pdb's for the corelib, correct?

**Comment by pjanotti** [comment]
Currently manual instructions for CoreLib are working, but we are still missing jump to source for CoreLib on daily coverage runs. Closing this one as the remaining issue is being tracked on #30974
