### ISSUE TITLE
Use roslyn compiler to build corefx

### ISSUE THREAD

**Issue by mmitche** [dotnet/corefx#1316]
We should be using the Roslyn compiler to build

**Comment by Clockwork-Muse** [comment]
I kind of assumed this was waiting on VS2015 to be officially released?  The other option is what, requiring the 2015 build tools to be installed?

**Comment by weshaggard** [comment]
I agree this is waiting for VS2015 to be released. @mmitche why do you want to use Roslyn?

**Comment by ellismg** [comment]
FWIW, build.cmd is set up to prefer VS2015 when installed, so if you have Roslyn, we will use it.

**Comment by mmitche** [comment]
@weshaggard It was suggested...by @richlander I think...that we do this.  I believe the reasoning was that Roslyn is our OSS C# compiler, it would be great to use it to build corefx/other projects.  However, since 2015 isn't far away it might make sense just to wait.  The other option would be to pull in that build tool in a package.  What do you think @richlander?

**Comment by richlander** [comment]
My view is that Roslyn and VS 2015 are logically separate. I don't think that we should gate on release bits, although distribution is a legit concern. There are three distinct scenarios:

- build (mscorlib) coreclr
- build corefx
- build user code

As soon as Roslyn can reliably do any of these scenarios, we should switch to it for that scenario(s). Right now, we don't have a source compiler for Linux and OS X. We should accelerate resolving that as quickly as possible, preferably before VS 2015 RTM. I'd LOVE to rewrite the Linux and OS X instructions to include Roslyn, even if one had to build the Roslyn repo.

I'd glady accept a lower quality compiler (e.g. slower) in order to get cross-platform (and open source).

@jaredpar

**Comment by terrajobst** [comment]
@richlander what's the value we'd get out of it? I understand the desire to use the latest tools for everything but as @ellismg pointed, we already support it indirectly.

As far as cross platform builds go, we're currently depending on MSBuild. It seems solving the cross platform builds would require addressing the MSBuild dependency in a meaningful way first.

**Comment by richlander** [comment]
@terrajobst I was trying to make 2 main points:

- VS 2015 RTM shouldn't be the gating factor. Tangent: I hope its not a gating factor for any of our decisions.
- Once Roslyn is available for a scenario that it unblocks (e.g. compiling simple apps on OS X and Linux), we should recommend that people use it. As Matt says, It is already available for VS 2015, and we already use it there (which is great).

I don't think that this disagrees with what you are saying

The focus of my thinking is OS X and Linux.

**Comment by KrzysztofCwalina** [comment]
I would prefer to do the update asap. I just ran into a problem where code compiles locally (I use 2015 locally) but then fails the CI build.

**Comment by mmitche** [comment]
@KrzysztofCwalina does this imply that as soon as we switch to 2015, we stop supporting building on 2013?

**Comment by KrzysztofCwalina** [comment]
That would be the implication. The alternative is that we switch locally away from dogfooding VS2015, which we probably don't want to do.

**Comment by ellismg** [comment]
I believe the alternative is that we don't use new C# 6.0 features, which is not nearly as bad as not dogfooding 2015.

I think we should decouple the "build using pre RTM Roslyn" from the "adopt 6.0 language features" discussions.

FWIW, I'm very opossed to taking changes that make it impossible to build the stack using only VS2013 Community.

**Comment by jaredpar** [comment]
All Roslyn compilations are done today using the roslyn compiler.  Hence I'm fairly certain there should be no quality / capability or perf issues in doing the same to corefx.  And if there are I'd sure like to find out about them now instead of later :smile: 

Roslyn does this by doing the following:

- Uses the latest NuGet package for Microsoft.Net.ToolsetCompilers.
- In our core [targets file](https://github.com/dotnet/roslyn/blob/master/src/Tools/Microsoft.CodeAnalysis.Toolset.Open/Targets/VSL.Settings.targets#L57) we import the props file from that package.  This redirects `CscToolPath` to point to the roslyn csc.exe in the NuGet package.  

This makes the compilation of the compiler portion of Roslyn completely independent of the Visual Studio install.  That should address @KrzysztofCwalina and @ellismg 's scenario.

**Comment by jaredpar** [comment]
If you all are interested in pursing this for corefx I can definately take a stab at it.

**Comment by ellismg** [comment]
If we do this, we should make sure we understand the impact when building CoreFX internally in razzle.  Are we ok with restoring Roslyn in that case or should we be using the toolset version?

**Comment by mmitche** [comment]
Building using a package we deploy (like @jaredpar suggests) was what I was originally referring to.  We should still only require 2013 as the base installed VS, but we could decouple the compiler actually used from that.

**Comment by ellismg** [comment]
If we did that, and adopt c# 6.0 features, does that break intellisense in VS2013 or does everything just work?

**Comment by jaredpar** [comment]
@ellismg you will not be able to use the NuGet package in a razzle environment due to limitations of razzle.

**Comment by ellismg** [comment]
@jaredpar Okay.  It's a requirement that we continue to be able to build the CoreFX sources here from within Razzle, so whatever we do, we need to make sure that continues to work.

**Comment by jaredpar** [comment]
@ellismg razzle does have a version of Roslyn as the toolset at the moment. Not exactly sure which version but so long as you don't venture into exception filters the code should compile in both scenarios.

**Comment by jaredpar** [comment]
@ellismg had another thought last night.  It is possible for the CoreFx repo to switch to Roslyn and still enforce C# 5.0 compatibility by specifying the [/langversion:5](https://msdn.microsoft.com/en-us/library/f4ckecs0.aspx) switch.  

That would get CoreFx onto roslyn, allow for 2013 to work unaltered and guarantee razzle compatibility.

**Comment by mmitche** [comment]
+1 to that.

**Comment by ellismg** [comment]
That sounds good to me.

**Comment by weshaggard** [comment]
Yes I just learned about the /langversion switch yesterday so I'm also willing to entertain this idea. @jaredpar are you going to put together a PR in our buildtools repo?

**Comment by jaredpar** [comment]
@weshaggard yes.  I've assigned this issue to myself.

**Comment by justinvp** [comment]
This can be closed. Fixed by #6181.
