### ISSUE TITLE
Add [Serializable] on System.Collections.ObjectModel.ReadOnlyDictionary

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#13283]
`System.Collections.ObjectModel.ReadOnlyDictionary` is marked with SerializableAttribute on full framework. It should be marked with the attribute now as the attribute is available in CoreFx.

**Comment by karelz** [comment]
@weshaggard @danmosemsft should it be part of .NET Standard 2.0?

**Comment by danmosemsft** [comment]
This is part of NS2.0 and @shmao's correct that it's missing [Serializable]. @AlexGhiondea did this show up in your/Stephen's tool?

**Comment by shmao** [comment]
@danmosemsft hmm... I just checked NS2.0. In NS2.0, the type does not have [Serializable], see https://github.com/dotnet/standard/blob/master/netstandard/ref/mscorlib.cs#L4844. I'm not sure if we want to add it in NetCore then.

**Comment by danmosemsft** [comment]
The way the tool (genapi I believe) works is it only includes certain attributes when it generates the contract code (what's in the ref folder). It includes [Obsolete] because the compiler cares about it but not [Serializable] as the compiler doesn't care about it. [Serializable] is more an behavior/implementation issue -- and we want the behavior to match desktop.

**Comment by weshaggard** [comment]
Yes we should include it in the implementation but it doesn't need to exist in the reference assembly.

**Comment by stephentoub** [comment]
> did this show up in your/Stephen's tool?

I expect my code isn't handling generics correctly.  I'll take a look.
