### ISSUE TITLE
Consider adding GetAssemblyName() : AssemblyName to AssemblyDefinition and AssemblyReference

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#13295]
Constructing System.Reflection.AssemblyName from metadata is a bit tricky. Providing an easy to use helper would avoid common pitfalls and reduce code duplication. See e.g. http://source.roslyn.io/#Microsoft.CodeAnalysis/InternalUtilities/AssemblyIdentityUtils.cs

**Comment by karelz** [comment]
Approved (cc: @terrajobst @weshaggard should be non-controversial).
We need someone to implement it - it will be medium complex, the code is more or less in Roslyn.

**Comment by terrajobst** [comment]
I've no objection to the concept but what's the actual API that's being approved here? We should have at least an outline.

**Comment by tmat** [comment]
It's in the title :)

```C#
struct AssemblyDefinition
{  
   ...
   public AssemblyName GetAssemblyName() {}
   ...
}

struct AssemblyReference
{  
   ...
   public AssemblyName GetAssemblyName() {}
   ...
}
```

**Comment by terrajobst** [comment]
> It's in the title :)

😄 I really didn't see this. :-)

**Comment by terrajobst** [comment]
APIs look good as proposed.

**Comment by karelz** [comment]
BTW: Me neither until @tmat and @nguerrera told me -- @tam @nguerrera if you can in future add the mini-specs, it will help streamline things :)

**Comment by danmosemsft** [comment]
Assigning to @safern who is going to give this to our new hire shortly.

**Comment by maryamariyan** [comment]
@tmat what should be the expected output for GetAssemblyName() ?

where do I find the underlying logic for GetAssemblyName()?

**Comment by maryamariyan** [comment]
@safern @joperezr I already see a Name getter in AssemblyDefinition. What is the purpose of having a AssemblyName getter and how is it different from assemblyDefinition.Name?

**Comment by safern** [comment]
I believe what @tmat meant was not to add an AssemblyName getter, per comment https://github.com/dotnet/corefx/issues/13295#issuecomment-260037855 he meant to add a public method that returns a System.Reflection.AssemblyName object with the required metadata such as PublicKey, Flags, Culture, Version, etc. Because from the AssemblyDefinition itself to build that object requires a little bit of work like in the link he posted: http://source.roslyn.io/#Microsoft.CodeAnalysis/InternalUtilities/AssemblyIdentityUtils.cs

With this public API we would avoid a lot of code duplication trying to extract the metadata from multiple places from the handles. As you can see the AssemblyDefinition.Name is a StringHandle that needs to be passed to the MetadataReader to get the actual string, so we want to avoid code duplication to convert those handles to actual values with this new APIs.
