### ISSUE TITLE
Excessive Executable Flags on macOS

### ISSUE THREAD

**Issue by wjk** [dotnet/corefx#13342]
(I originally asked about this at dotnet/cli#4260 some two months ago, but never received a response until today. However, since it is not .NET CLI-specific, I figured asking here would be a better idea.)

One of the things that has been driving me crazy about .NET Core is that on my Mac (running macOS Sierra, version 10.12.1), any and every file created by a .NET Core program is marked as executable (specifically, they all have the mode 711). Note that this only affects files created by a Core program; already existing files that are opened or modified remain at their existing mode. This is totally unnecessary, and furthermore complicates interoperability with programs that don’t expect every file to be executable (such as the Mac’s GUI file-management subsystem). Could this possibly be changed? Thanks!

**Comment by stephentoub** [comment]
FWIW, this is by design:
https://github.com/dotnet/corefx/blob/988feb3c733d384a025ef18c4fecafdc5412f7a9/src/System.IO.FileSystem/src/System/IO/FileStream.Unix.cs#L50

**Comment by wjk** [comment]
Huh. That's interesting. Is there any way I can override that, short of P/Invoking into `chmod` and manually calling it on every file I create?

**Comment by jkotas** [comment]
Does mono use the same default? 
It does not sound right to create files as executable by default on Unix from security angle.

**Comment by jkotas** [comment]
cc @blowdart

**Comment by stephentoub** [comment]
> Does mono use the same default? 

No, I just checked and it uses 666 by default rather than 766.  The 766 was chosen to match Windows, as on Windows files written are executable by default.

I don't feel strongly about this either way; I was just pointing out that there was logic behind the choice rather than it being an accident.  If we don't care about matching this scenario on Windows (or matching behavior from previous .NET Core releases), then we can certainly change the default back to 666.  Note that we don't currently provide any exposed wrapper around chmod, so no matter what default we pick, changing it will require a P/Invoke until we either do expose such a wrapper or somehow map the file AccessControl APIs to target chmod on Unix.

**Comment by blowdart** [comment]
What does gcc etc do? It feels odd for a compiler to produce executables which, er, aren't executable, but if the usual suspect compilers on the platform do it, then we probably should match that, rather than match windows.

**Comment by jkotas** [comment]
Right, native compilers should produce executable files. They are a special case. (And it is pretty unlikely that somebody will be writing native linker in C# anytime soon... .)

Majority of the files that programs produce are non-executable. .NET programs set the executable bit on all files. It does not match the Unix platform conventions. On Unix, the executable bit is meant to be set on true executables only.

For example, the consequence of this default is that all junk in the nuget cache downloaded from the internet has executable bit set. You can type `~/nuget/packages/System.Runtime/4.1.0/ThirdPartyNotices.txt` on your shell prompt and it will start executing as a shell script. Now, replace System.Runtime and ThirdPackages.txt with something malicious... .

**Comment by stephentoub** [comment]
If we want to change it, here's the fix:
https://github.com/dotnet/coreclr/pull/7995
