### ISSUE TITLE
Process.GetCurrentProcess().MainModule.FileName returns incorrect path in linux

### ISSUE THREAD

**Issue by codito** [dotnet/corefx#13452]
### Steps to reproduce
1. Use dotnet executable from a path with space. E.g. `/tmp/dotnet 2/dotnet-cli`
2. Use following code:
```
using System;
using System.Diagnostics;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine(GetCurrentProcessFileName());
    }

    public static string GetCurrentProcessFileName()
    {
        return Process.GetCurrentProcess().MainModule.FileName;
    }
}
```
3. Compile and run the app `/tmp/dotnet\ 2/dotnet-cli/dotnet /tmp/app.dll`

### Expected
App should print `/tmp/dotnet 2/dotnet-cli/dotnet`

### Actual
App prints `/tmp/dotnet`

**Comment by vcsjones** [comment]
So the culprit here is, when parsing `/proc/x/maps`, `StringParser` is used to parse each element in the line, and uses a space as a separator. If the path contains a space, StringParser reads up to the first space. The line is [here](https://github.com/dotnet/corefx/blob/aab5e06732e729f3d8bc3baa2e0d0c1ba9cec518/src/Common/src/Interop/Linux/procfs/Interop.ProcFsStat.cs#L164).

The correct thing to do here is read to the end of the line since the path in `maps` is the last thing.

I'll put together a pull request for this.
