### ISSUE TITLE
System.Linq.Expressions code coverage partial report

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#13523]
It currently shows as 27%, while we expect a much higher number (it was 80% or more IIRC before code coverage stopped working in CI). This may be related to https://github.com/dotnet/corefx/issues/13510.

One observation is that all interpreter code isn't covered, so there may be a compilation symbol missing for the test assembly build. Another contributing factor may be the merge of `System.Dynamic.Runtime` functionality. But even then, it seems many tests are not run, e.g. for the `Expression` class we expect a lot more coverage of various code paths (such as argument checking logic in the factories).

**Comment by stephentoub** [comment]
Hmm.  When I do a local code coverage run for System.Linq.Expressions, the report does list line coverage of 74.1% and branch coverage of 72.8%, which sounds in line with where you expected it to be.  In the CI run at https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/62, though, as you suggest, it's showing as 27%.  One interesting thing is that in the log, it does look like the System.Linq.Expressions.pdb isn't getting deployed (#13510):
```
  === TEST EXECUTION SUMMARY ===
     System.Linq.Expressions.Tests  Total: 29704, Errors: 0, Failed: 0, Skipped: 5, Time: 80.697s
  Committing...
  No results, this could be for a number of reasons. The most common reasons are:
      1) missing PDBs for the assemblies that match the filter please review the
      output file and refer to the Usage guide (Usage.rtf) about filters.
      2) the profiler may not be registered correctly, please refer to the Usage
      guide and the -register switch.
```
but in that case, I wouldn't expect to see any results for System.Linq.Expressions at all, rather than 27%.

**Comment by JonHanna** [comment]
Yeah, it had been in the mid-80s before the dynamic stuff was added more untested stuff.

Looking at line 169 at https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/Code_Coverage_Report/System.Linq.Expressions_Expression_1.htm it seems that maybe it's being compiled with FEATURE_INTERPRET not defined, but the results interpreted for coverage as if it was.

**Comment by JonHanna** [comment]
Interestingly, some of the 27% it's showing as covering is in fact not covered in the tests available. Could it be previous tests belonging to System.Dynamic? Could it be use of dynamic and expressions internal to the tester?

**Comment by JonHanna** [comment]
FWIW I ran coverage on one of my PRs to see if things were any different from that context, but it was the same 27%.

**Comment by JonHanna** [comment]
This is fixed.

**Comment by pjanotti** [comment]
Closing this one, from last coverage report: 

Line coverage: 92.9%
Branch coverage: 88.3%
