### ISSUE TITLE
Implement distributed/promoted transactions in System.Transactions.

### ISSUE THREAD

**Issue by jimcarley** [dotnet/corefx#13532]

**Comment by XieJJ99** [comment]
@ajcvickers @stephentoub The SQL Server team had already provided MSDTC for SQL Server on Linux.  Is there any plan to promote the MSDTC for linux as a generic service so that it's possible to support distributed transaction on Linux?

**Comment by ULSTechology** [comment]
A lack of support for distributed transactions is pretty disastrous for anyone wanting to migrate their old system onto .NET Core.

This puts an end to our hopes that we can start using Blazor - we can't rewrite our entire application to work without transactions, there's just too much of it.

**Comment by popcatalin81** [comment]
>  we can't rewrite our entire application to work without transactions, there's just too much of it.

Surely, if you can rewrite for Blazor, which is a significant rewrite anyway, you can also eliminate distributed transactions.

**Comment by ULSTechology** [comment]
> > we can't rewrite our entire application to work without transactions, there's just too much of it.
> 
> Surely, if you can rewrite for Blazor, which is a significant rewrite anyway, you can also eliminate distributed transactions.

Using Blazor requires a rewrite of the UI, and we can start small with that.

Rewriting large chunks of our business layer is a whole other matter. It's not an option we could even consider at the moment.

**Comment by LaterStart** [comment]
I want to vote up for this feature at least for databases on single SQL server instance.

I have case where I would like to enclose two different database commits into single system transaction. For example I have two records which are related and may depend on each other while being in separated databases. (Sort of micro-service architecture).

**Comment by abbotware** [comment]
@LaterStart - I have the same use case so +1  

Creating multiple exe microservices (**service fabric**) sharing a single SQL database (migration of legacy code / data)

I found it is possible on **Net Core** to share transactions/connections between ADO. and EF Core within a single process (https://docs.microsoft.com/en-us/ef/core/saving/transactions) , 

However, what options currently exist when 2 separate **Net Core** exes are involved for implementing a 2 phase-commit like pattern?

1. Can the DTC / Resource Manager be simulated via base classes in Net Standard?  (https://docs.microsoft.com/en-us/previous-versions/ms229975(v=vs.90))

2. Call the DTC directly via Win32 Api and some how enlist?

1-2 seem like a lot of work, but from what I have read (somewhere) I could just target **Net Standard 2.0** and run within a **Net Framework** host - That will allow System.Transactions to enlist / promote into a DTC transaction,  (I can settle for Netstandard + 4.7.2 + new sdk project format if that is my only option)

Even if I use a Net Framework Host (or Net Core if this open issue ever gets implemented), does that mean it should it is possible to obtain the transaction token / correlation id from process A so it can be sent/serialized to process B for manual enlistment?

**Comment by LaterStart** [comment]
@abbotware 
I have implemented such workaround, resource manager backed up with sql server database for temporary data storage. I started with in memory implementation but decided to abandon it because it is too risky if you would ever use more load balanced server instances. 

It can be done by catching distributed transaction exceptions for example. 
I am using generic transaction middleware, both for single database and multi database transactions. When I catch such exception, I'm initiating temporary data tracker while committing each transaction separately. In case of any transaction failure, hard rollback is initiated.
All successful transaction command IDs were previously saved by tracker and deleted from the database. For data updates I do not have a problem because I'm using event sourced design. But you could outcome that too by saving previous state too. 

It wasn't much work. If you would need code sample I could provide it too.

**Comment by pappasa** [comment]
How do you use .NET Core with IBM WebSphere MQ queue? For example, I do not want to remove the message from the queue, and the put to the database to fail.

**Comment by aajmot** [comment]
can someone tell me if the issue has been fix or still there?
It's almost 2020 now?
Is there any other way around, please tell me.

**Comment by pi3k14** [comment]
@dasetser 
wtf - you moved this into the unforeseeable future?
Don't you want to on-board enterprise solutions to .Net Core, you want to push us all over to the dark side (java)?

**Comment by am11** [comment]
Going by https://referencesource.microsoft.com/#System.Transactions/System/Transactions/Oletx/DTCTransactionManager.cs,2c1154236b6b7acf, seems like there are some win32 specific components involved which probably is the main hurdle. Could someone shed light on what are those and what would require to bring them cross platform?

**Comment by dasetser** [comment]
This got moved to future because after investigating it we determined it's going to be a significant rewrite of the feature rather than just a port. We're looking into options for this, but we aren't able to commit to getting this done in the upcoming release.

The main hurdle is that System.Transactions depends on MSDTC when it has to promote transactions, but MSDTC is only available on Windows. In order to get this to work cross platform we would need to rewrite the feature to allow it to work with other distributed transaction coordinators that are available on other platforms, or look into doing something similar to what the SQL Server team did where they brought the DTC components inside the SQL component. Either approach would be a significant change to this feature.

**Comment by Peperud** [comment]
Where do I vote for this?

**Comment by pi3k14** [comment]
@dasetser - I appreciate your clarification.
But, us current users of Distributed transactions don't care about cross platform.
Just support it on Windows, and put this cross platform paradigm that we haven't request into the future.

Thank you.

**Comment by am11** [comment]
Thanks for the explanation @dasetser.
If the target linux machine has [MSDTC component from SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-msdtc?view=sql-server-ver15#msdtc-configuration-steps) installed, and its C API is the same as Windows, can the implementation take advantage -- as in, SQL Server as a prerequisite (for now)? We can separately request and poll SQL Server team to ship MSDTC component as a standalone library. :)

**Comment by randyburden** [comment]
We were planning to begin porting many of our current applications to .NET Core starting next week as well as start writing our new apps on .NET Core but we just ran into this issue of distributed transactions not working which feels like a deal breaker. Almost every application we write or will write in the future requires distributed transactions.

It is very odd to have experienced a platform not supported exception with this particular feature when we all know that it already exists in the full .NET Framework. It's hard to understand why a Windows platform specific implementation wasn't implemented either in CoreFX or as a shim NuGet package.

Is there a workaround?

**Comment by pi3k14** [comment]
@dasetser  - Wouldn't implementing WS-AtomcTransaction be the way to go. And since MSDTC supports it and WCF has an implementation of it https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/using-ws-atomictransaction this shouldn't take that much time. Those wanting distributed transactions on Unix can then get a third party solution.

**Comment by StephenBonikowsky** [comment]
Issue moved to [dotnet/runtime #715](https://github.com/dotnet/runtime/issues/715) via [**ZenHub**](https://www.zenhub.com/)
