### ISSUE TITLE
Failure in System.IO.FileSystem.DriveInfo

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#1355]
```
 Discovering: System.IO.FileSystem.DriveInfo.Tests
 Discovered:  System.IO.FileSystem.DriveInfo.Tests
 Starting:    System.IO.FileSystem.DriveInfo.Tests
    System.IO.FileSystem.DriveInfoTests.DriveInfoWindowsTests.TestVolumeLabel [FAIL]
       Assert.Throws() Failure
       Expected: typeof(System.UnauthorizedAccessException)
       Actual:   typeof(System.IO.IOException): The request is not supported
       Stack Trace:
          e:\oss\corefx\src\System.IO.FileSystem.DriveInfo\src\System\IO\DriveInfo.Windows.cs(235,0): at System.IO.DriveInfo.set_VolumeLabel(String value)
          e:\oss\corefx\src\System.IO.FileSystem.DriveInfo\tests\DriveInfo.Windows.Tests.cs(180,0): at System.IO.FileSystem.DriveInfoTests.DriveInfoWindowsTests.<>c__DisplayClass20.<TestVolumeLabel>b__18()
 Finished:    System.IO.FileSystem.DriveInfo.Tests
```

I think this is consistent failure on my box (at least repeated few times)

This happens for my DVD drive when there is no drive inside. @Priya91 seemed to also have checked it on her computer but she was unable to repro. When I use DriveInfo class on my DVD drive it is able to get the DriveType but trying to access VolumeLabel or DriveFormat (also for read) causes the same failure.

**Comment by joshfree** [comment]
@FiveTimesTheFun can you take a look?

**Comment by ianhays** [comment]
I am unable to repro this on my machine. 

>This happens for my DVD drive when there is no drive inside

In this case the test won't set VolumeLabel because drive.IsReady will be false. IsReady is just a call to Directory.Exists on the name passed to the constructor.

I also tested with a drive loaded but was again unable to get any unexpected errors. It's possible this may have been inadvertently resolved since April. @krwq can you still repro this?
