### ISSUE TITLE
System.Runtime.InteropServices.RuntimeInformation fails when running on full .NET on Win7

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#13566]
The library PInvokes into an api-set which isn't present on Win7 and so when running on .NET Framework there it throws the following exception. 

```
Unhandled Exception: System.TypeInitializationException: The type initializer fo
r 'Microsoft.VisualStudio.TestPlatform.ObjectModel.Constants' threw an exception
. ---> System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-sysinfo-
l1-2-0.dll': The specified module could not be found. (Exception from HRESULT: 0
x8007007E)
   at Interop.mincore.GetNativeSystemInfo(SYSTEM_INFO& lpSystemInfo)
   at System.Runtime.InteropServices.RuntimeInformation.get_OSArchitecture()
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.Utilities.XmlRunSettingsUt
ilities.get_OSArchitecture()
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.Constants..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.Utilities.RunSe
ttingsUtilities.GetEffectiveRunSettings(String runSettings, CommandLineOptions c
ommandLineOptions)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.Utilities.RunSe
ttingsUtilities.GetRunSettings(IRunSettingsProvider runSettingsProvider, Command
LineOptions commandlineOptions)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.RunTestsArgumen
tExecutor.RunTests(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.RunTestsArgumen
tExecutor.Execute()
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.ExecuteArgumentPr
ocessor(IArgumentProcessor processor, Int32& exitCode)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.Execute(String[]
args)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Program.Main(String[] args
)
```

To workaround people can deploy api-ms-win-core-sysinfo-
l1-2-0.dll with their application similar to https://github.com/dotnet/corefx/issues/8091#issuecomment-225641743. 

My expectation is that this should no longer be an issue once @JohnChen0 finishes his work to move us off api-sets.

**Comment by AlexGhiondea** [comment]
It sounds like once @JohnChen0 is done with his work this will no longer be an issue. 

@JohnChen0 can you confirm this is solved after you are done?

**Comment by JohnChen0** [comment]
Verified. This DLL import now works correctly when running on full .NET on Win7.

**Comment by AlexGhiondea** [comment]
@JohnChen0 that's great! thank you!

**Comment by aelij** [comment]
I have users who are experiencing this issue on Windows 7 with the latest (4.3.0) package. Was this fix published?

**Comment by weshaggard** [comment]
@aelij it was never shipped directly as an individual package, it is now part of the core Microsoft.NETCore.App package or the .NET Framework support package. So depending on your needs one of those will have the update or you could also reference https://www.nuget.org/packages/Microsoft.NETCore.Windows.ApiSets/1.0.1 to get the shims needed to run on win7

**Comment by rjmholt** [comment]
Hi all, I've just hit this performing the same OSArchitecture call.

Because we build a cross-platform PowerShell module, we have to assemble the binaries ourselves out of the publish directories.

I've added the Microsoft.NETCore.Windows.ApiSets package to our csproj, but when it builds, it doesn't seem to pull in the DLL that fixes the problem. I've tried both a broad RID and specifying multiple specific RIDs.

Any advice?

**Comment by rjmholt** [comment]
Updating after reading more issues: it looks like https://github.com/dotnet/buildtools/pull/1249 fixed a problem caused by this by upgrading to a newer version of System.Runtime.InteropServices.RuntimeInformation (4.4.0-beta-24813-03), but that was December 2016. The latest version in Nuget is 4.3.0, published November 2016.

Some comments suggest that there is no longer a dependency or desire to use api-ms-win-core-sysinfo-
l1-2-0.dll, but if not I'm not sure what to use instead.

So is there a Nuget package I can pull in that will fix this in a build not targeting a specific RID? Or should I just add a step targeting win7-x(86|64) and copy the DLL in? (Which will complicate our publish/load a fair bit)
