### ISSUE TITLE
System.Data.SqlClient.sln contains stresstest project that does not exist

### ISSUE THREAD

**Issue by svick** [dotnet/corefx#13602]
[System.Data.SqlClient.sln contains a project named stresstest, which does not exist.](https://github.com/dotnet/corefx/blob/768e18c/src/System.Data.SqlClient/System.Data.SqlClient.sln#L13) This causes an error loading the project when opening the solution in VS and also causes running `msbuild` on the solution to fail.

Instead of the single project, [the `tests/StressTests` directory](https://github.com/dotnet/corefx/tree/768e18c53d1e218d77914c207dcb2ba8636397e0/src/System.Data.SqlClient/tests/StressTests) contains 4 projects. But when I tried to add them to the solution, they didn't build (which is why I'm not going to create a PR to fix this).

This seems to have been introduced in https://github.com/dotnet/corefx/pull/10601.

CC: @saurabh500

**Comment by mellinoe** [comment]
Unfortunately, I expect that a lot of our solution files are out of sync. We need a tool that automatically re-generates them, or something of that sort. It's just a matter of spending the time to go and write that thing versus hacking up fixes to individual sln's as we go along.

**Comment by saurabh500** [comment]
The StressTests folder projects are not building because of https://github.com/dotnet/corefx/pull/12345 

@karajas I understand that you have consolidated all deps of tests in single project.json

I think that to build the projects under the stresstests folder, I will have to have their independent project.json along with the csproj files. 

Can you revert the changes for the projects in StressTests folder which don't pick up the dependencies from the consolidated project.json ? I think the csproj ending with .Tests will pick up the dependencies from the project.json you have created, however the build system doesnt allow the other projects to build because they don't end with "tests"
