### ISSUE TITLE
RebuildAndTest sometimes does not run the xUnit tests.

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#13626]
Sometimes, running `msbuild /t:RebuildAndTest` for a particular project will not actually test the project. I've noticed this a couple of times over the past few months, but I'm not quite sure what causes it. I just got some sample output from MSBuild with this happening, though, so I thought it might help to open an issue here. The output can be viewed [here](https://gist.github.com/jamesqo/22d9cde9f2c91569f12d3eebb9f67092); I posted 2 log files, 1 with normal verbosity and 1 with `/v:detailed`.

**Comment by jamesqo** [comment]
This is what the detailed log says about the RunTestsForProject target:

```
Target "RunTestsForProject" in file "C:\Users\james\Code\git\corefx\Tools\tests.targets" from project "C:\Users\james\Code\git\corefx\src\System.Linq\tests\System.Linq.Tests.csproj" (target "Test" depends on it):
Skipping target "RunTestsForProject" because all output files are up-to-date with respect to the input files.
Input files: C:\Users\james\Code\git\corefx\bin\AnyOS.AnyCPU.Debug\System.Linq\System.Linq.dll;C:\Users\james\Code\git\corefx\bin\AnyOS.AnyCPU.Debug\System.Linq\System.Linq.pdb;C:\Users\james\Code\git\corefx\bin/obj/AnyOS.AnyCPU.Debug/System.Linq.Tests/System.Linq.Tests.dll;C:\Users\james\Code\git\corefx\bin/obj/AnyOS.AnyCPU.Debug/System.Linq.Tests/System.Linq.Tests.pdb
Output files: C:\Users\james\Code\git\corefx\bin/tests/AnyOS.AnyCPU.Debug/System.Linq.Tests/default.netcoreapp1.1//tests.passed.without.OuterLoop.failing;C:\Users\james\Code\git\corefx\bin/tests/AnyOS.AnyCPU.Debug/System.Linq.Tests/default.netcoreapp1.1//testResults.xml
Done building target "RunTestsForProject" in project "System.Linq.Tests.csproj".
```

**Comment by danmosemsft** [comment]
It skips the tests if neither the product nor test binaries have changed (as you can see in that snippet, they are the only 'input files')

Is that what you are seeing? I agree it's sometimes not what you want. I personally just 'touch' a .cs file when I want to rerun the tests. There ought to be a flag to force them to run.

**Comment by danmosemsft** [comment]
Looks like you have to pass /p:forceruntests=true (or set as an environment variable)
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets#L131

**Comment by weshaggard** [comment]
FWIW RebuildAndTest should force the test project to rebuild and thus force it to run the tests. Something definitely seems off. I wouldn't expect the needed to pass forceruntests=true in this scenario. 

cc @naamunds another test scenario we should ensure works.

**Comment by naamunds** [comment]
@jamesqo I was unable to repro this issue.  Running `msbuild /t:RebuildAndTest src\System.Linq\tests\System.Linq.Tests.csproj` repeatedly ran tests every time for me.

From looking at the logs you linked to, it seems strange to me that it skipped RunTestsForProject.  From the top of the log, we can see that "C:\Users\james\Code\git\corefx\bin\obj\AnyOS.AnyCPU.Debug\System.Linq.Tests\System.Linq.Tests.dll" was deleted at the beginning; it was then compiled and copied to the output directory:
`Copying file from "C:\Users\james\Code\git\corefx\bin/obj/AnyOS.AnyCPU.Debug/System.Linq.Tests/System.Linq.Tests.dll" to "C:\Users\james\Code\git\corefx\bin/AnyOS.AnyCPU.Debug/System.Linq.Tests/System.Linq.Tests.dll".`
Then, it apparently skipped RunTestsForProject because tests.passed.without.OuterLoop.failing and testResults.xml were at least as new as "C:\Users\james\Code\git\corefx\bin/obj/AnyOS.AnyCPU.Debug/System.Linq.Tests/System.Linq.Tests.dll" (and all of the other input files), but I don't see evidence that either of those files were created or modified as part of the build.

Are you still seeing this issue?  If you have any more insight into what might cause it, that would be useful.

As Dan and Wes stated, if you do hit the issue, you can work around it with `/p:forceruntests=true`, but that shouldn't be necessary if you're using `RebuildAndTest` (it should just be necessary for `BuildAndTest`).
