### ISSUE TITLE
AES missing member

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#13703]
`Create()` should be `new` and we are missing `Create(string algorithmName)`.

```
    public abstract class Aes : SymmetricAlgorithm {
        public static new Aes Create();
        public static new Aes Create(string algorithmName);
    }
```

**Comment by danmosemsft** [comment]
Might as well roll it into this issue, we are also missing AesManaged.FeedbackSize property.

```
    public sealed class AesManaged : Aes {
        public override int FeedbackSize { get; set; }
}
```

**Comment by bartonjs** [comment]
This is not currently actionable. @steveharter - is this one not already on the list of all the Create methods you're already doing?

(The FeedbackSize member can be done, though)

**Comment by danmosemsft** [comment]
Ah I see mention of Create in https://github.com/dotnet/corefx/issues/13703. I did attempt to search for duplicates -- I'm trying to open issues for anything overlooked.
@steveharter if https://github.com/dotnet/corefx/issues/13703 covers that already then I'll edit this issue to just FeedbackSize.

**Comment by steveharter** [comment]
The CryptoConfig work handles all static Create methods - issue #12327. However the X509 Create method mentioned in new issue #13687 can be done there as that's the only member in that assembly and that issue is dealing with other X509 issues, and doesn't require CryptoConfig.

FeedbackSize in issue #12368. If it's not actionable please mention that in the issue

**Comment by danmosemsft** [comment]
My bad for not seeing hte dupes. Great.
