### ISSUE TITLE
Path.GetTempPath does not return a user specific folder on Unix systems

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#13710]
On Unix systems Path.GetTempPath returns "/tmp" unless the TMPDIR envvar is set.

According to the documentation, this method returns the path of the current user's temporary folder.
On Windows it returns: "%USERPROFILE%\AppData\Local\Temp".

This is causing an issue for the NuGet.Client because the program assumes it is the owner of the temp directory, see https://github.com/NuGet/Home/issues/2793.

**Comment by stephentoub** [comment]
What directory are you expecting this to return?  On Linux there is no per-user tmp folder provided by the OS, so the user's temp folder is the global one.  Is the suggestion that we manufacture a per-user subdirectory of /tmp/ (but presumably only if TMPDIR isn't set)?  (Note that the current behavior matches the behavior what Mono has.)

**Comment by vcsjones** [comment]
There really is no such thing as a "per-user" temp directory in all Linux distros. This is likely going to be a problem specific to nuget. The Linux-y way to handle the nuget issue is to have make a unique directory under `/tmp` for a user or a given operation.

>Windows it returns: "%USERPROFILE%\AppData\Local\Temp"

Not quite. It returns `user32::GetTempPath` which is also capable of returning a "global" path, like C:\Windows\Temp (such as an IIS AppPool when the user profile isn't loaded).

I would suggest that Nuget instead create a sub directory under the temp path that is unique and won't collide.

**Comment by tmds** [comment]
GetTempPath _could_ create and return a /tmp/dotnet-tmp-\<uid\> folder with rwx set only to the user (effective UID).

The [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) defines a directory XDG_RUNTIME_DIR with similar semantics.

**Comment by tmds** [comment]
Making a per user nuget folder under /tmp is not straightforward as there doesn't seem to be a netstandard way of identifying a user (e.g. Environment.UserName is not netstandard).

**Comment by vcsjones** [comment]
>GetTempPath could create and return a /tmp/dotnet-tmp-<uid> folder with rwx set only to the user (effective UID).

It could, but I think that's a breaking change. Some applications just want to get the $TMPDIR directory as the rest of the system sees it. I don't think `GetTempPath` should try to solve every problem. It has historically just been "Get me the environment's temporary directory, whatever it is".

This feels more like an API proposal to me for something new, but that's just my thoughts.

**Comment by tmds** [comment]
> It has historically just been "Get me the environment's temporary directory, whatever it is".

According the the MSDN documentation: "Returns the path of the current user's temporary folder."

**Comment by vcsjones** [comment]
The docs also go on to say:

>* The path specified by the TMP environment variable.
* The path specified by the TEMP environment variable.
* The path specified by the USERPROFILE environment variable.
* The Windows directory.

Thought I am splitting hairs here, I believe the documentation is stating it gets the path that the current user believes the temp path to be, even if it is shared one, not a path unique to that user. I've already given a scenario where it can return `C:\Windows\Temp`, so I don't think there were ever firm guarantees this returned a *per user* directory, though when used in NuGet that's practically always the case. It returned the user's configured value for the temp directory.

Even then, changing it would probably require back-compat of some kind with quirking.

**Comment by tmds** [comment]
Definitely the ability to overwrite it with an envvar should be maintained.

> Even then, changing it would probably require back-compat of some kind with quirking.

All programs using the same version of .NET Core will see the same tmp dir so I don't expect backward compat issues.

**Comment by tmds** [comment]
@stephentoub any thoughts from your side?

**Comment by stephentoub** [comment]
> any thoughts from your side?

I agree that the docs could be misleading.  To my knowledge, there was never any intent that GetTempPath would guarantee a per-user folder (it doesn't guarantee that), it just happens that way sometimes on Windows due to the Windows-specific environment variables being checked.  But I also don't think the docs are wrong; the docs state "Returns the path of the current user's temporary folder", and there's nothing that says my temporary folder can't be the same as your temporary folder.

Note that other languages/framework behave the same way as Path.GetTempPath currently does on Linux, e.g. Java's java.io.tmpdir, Go's os.TempDir(), node's os.tmpdir() (even C's tmpnam puts files in the root of /tmp).  Mono's Path.GetTempPath does as well.  I can see the value in having Path.GetTempPath create a per-uid subdirectory, but I'm hesitant to break with what everyone else does, with what Mono does, etc.

If a user wants their temporary files put elsewhere, that's what the environment variable is for.  And if an application wants to create a per-user directory or a per-app/per-user directory under the temp path, it can do so.  It's true that with the APIs exposed from .NET Core 1.1, there isn't a great exposed way to get at the current user's ID (as you mention with 1.2 Environment.UserName is exposed), but it can easily be done with a simple P/Invoke:
```C#
[DllImport("libc")] private static extern uint geteuid();
```
so with a few lines you could create your own version of this, e.g.
```C#
private static string GetUserTempPath()
{
    string path = Path.GetTempPath();
    if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
    {
        path = Path.Combine(path, geteuid().ToString());
        Directory.CreateDirectory(path);
    }
    return path;
}
[DllImport("libc")] private static extern uint geteuid();
```

**Comment by tmds** [comment]
> you'd need to be cognizant of the fact that other users and other apps could create something with the same name in the shared tmp folder, which is another reason I'd shy away from trying to do this in the framework.

Everyone that wants to do something in /tmp should chose names wisely. So if it makes sense to have a user-specific folder returned by GetTempPath, it's 'only' a matter of choosing a good name.

If I have a look at my Windows environment variables, by default: TMP, TEMP and USERPROFILE are set and point to a user-specific Temp folder. So existing Windows .NET code may only work under this condition. Off course, such code can be fixed when making it xplat.

Thanks @stephentoub @vcsjones
