### ISSUE TITLE
Provide support for general non-cryptographic hashing. System.Hashing?

### ISSUE THREAD

**Issue by redknightlois** [dotnet/corefx#13757]
A spin-of of the design discussion to tackle the general problem. References: https://github.com/dotnet/corefx/issues/8034

**Comment by JonHanna** [comment]
I've a port of SpookyHash for .NET, and while it might be a bit dusty, I'd happily add it to such an endeavour.

**Comment by redknightlois** [comment]
We can contribute the code for XXHash32, XXHash64 and Metro128. They can be optimized further, but they are fast enough atm to never show up in profiling runs (even though we use the a lot).

**Comment by JonHanna** [comment]
Mine should perhaps be made a bit slower, in that I'm doing unsafe things with memcpy that might not be strictly necessary, but the main thing is the API is a bit kitchen-sinky. I'd just made a new hammer, and look at all these nails everywhere!

**Comment by Tornhoof** [comment]
If you need another/alternative metro128 Hash implementation, you can have mine too

**Comment by AlgorithmsAreCool** [comment]
It would be great to have a CRC32 implementation provided by the library too.

**Comment by AlgorithmsAreCool** [comment]
A couple of thoughts:

I imagine that the various implementations should share a common interface or abstract class and should be easy to hook into `Stream` (and perhaps pipelines in the future).

I was a fan of the `ICryptoTransform`/`CryptoStream` API since it provided an easy way to either consume or "listen" to a stream and grab the hash from it. I think something similar to it should be a decent shape.

A way to work with `byte[]` and `Span<byte>` would be very welcome for this also.

Lastly what about adding these types to `System.IO`? Perhaps they would be a natural fit there?

**Comment by ssg** [comment]
The answers to "why is this for?" and "how to pick what to include in this?" should be clarified by maintainers. The other thread sheds some light but it's not concrete enough to move this conversation forward. I have fast and tested implementations of [SipHash 2-4, MurmurHash3, FNV-1/1a](https://github.com/ssg/HashDepot/) on fixed size buffers which I can help porting to .NET but this needs clarification.

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/issues/25666 was opened later and is thus technically the dup of this one, but that one has more discussion, so closing this one as a dup.
