### ISSUE TITLE
String iterator over code points (and a corresponded codepoint struct)

### ISSUE THREAD

**Issue by be5invis** [dotnet/corefx#13822]
```C#
foreach (codepoint c in "😀🙃💩".Codepoints){
    // c becomes '😀', '🙃', '💩', respectively
}
```

**Comment by Clockwork-Muse** [comment]
Hmm, ideas for [precomposed characters](https://en.wikipedia.org/wiki/Unicode#Ready-made_versus_composite_characters)?

**Comment by svick** [comment]
@Clockwork-Muse Isn't that what `string.Normalize` is for?

And if you want to iterate graphemes, there's `StringInfo.GetTextElementEnumerator` (though that API is terrible: https://github.com/dotnet/corefx/issues/13824).

**Comment by Clockwork-Muse** [comment]
@svick - well, `Normalize` would possibly transform the string, so at that point are we assuming this would iterate through as-is?

**Comment by JonHanna** [comment]
I don't think we need a codepoint struct when we have `int`. (I'd have perhaps preferred `uint` but it's not CLS-compliant).
A struct could give range-checking, but I think I'd rather explicitly check when needed than have it on every construction.

**Comment by Clockwork-Muse** [comment]
@JonHanna - code points don't necessarily fit into an int.  They can be six bytes.

**Comment by JonHanna** [comment]
@Clockwork-Muse code-points are 21-bit values from 0 to 10FFFF<sub>16</sub>. They can fit into three.

**Comment by be5invis** [comment]
@JonHanna A separate struct can provide more meaningful data, like, `the string form` vs `the integer value`.

**Comment by Clockwork-Muse** [comment]
@JonHanna - I stand corrected.  Must have run into something mentioning the old standard.

Regardless of that, I'd prefer to avoid just passing back a number, to prevent issues with a BOM.  Or having a method to switch between composed/uncomposed characters.
Or hopefully to prevent people from trying to roundtrip through `char`, since those're UTF-16.

**Comment by JonHanna** [comment]
Well a BOM shouldn't be in a string, but if you were going to be handling a string with a BOM in it for some reason then the BOM codepoint should be there.

Dealing with code points is such a low-level thing that too much wrapping can get in the way. It's too high to map directly to `char` as you say (though to another way of looking at it, codepoints are the lowest conceptual level, the UTF-16 encoding then built on that), it's too low to be any use in deciding what to put on the screen or a page, since modifiers have codepoints, but don't give sufficient information on their own to say how they should be rendered.

**Comment by AlexGhiondea** [comment]
@tarekgh what do you think about having something like this? Is there already a solution for doing this?

**Comment by tarekgh** [comment]
how this is different than StringInfo.GetTextElementEnumerator?

**Comment by stephentoub** [comment]
@GrabYourPitchforks, does your work address this?

**Comment by GrabYourPitchforks** [comment]
Yes. See specifically the method [String.EnumerateRunes](https://apisof.net/catalog/System.String.EnumerateRunes()).
