### ISSUE TITLE
Optimize WebUtility.HtmlEncode and WebUtility.HtmlDecode

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#13893]
When porting `WebUtility` missing members:
``` csharp
    public static class WebUtility {
        public static void HtmlDecode(string value, TextWriter output);
        public static void HtmlEncode(string value, TextWriter output);
    }
```

We found that we already had a private method on .NET Core that would do exactly the same as this two members but instead of having a `TextWriter` as the output they have a `StringBuilder`. This members where ported on PR #13875 with a simple solution of just calling the existing private member and writing the result to the `TextWriter output` [Here is the source code](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/Net/WebUtility.cs#L55). 

On PR #13875 we had a large discussion with different solutions. With a conclusion that the best one is @jkotas's solution.

cc @danmosemsft @AlexGhiondea

**Comment by karelz** [comment]
@benjamin-hodgson thanks for working on the issue!
I sent you collaborator invite, so that we can assign the issue to you (GH limitation). Let me know once you accept and I will assign it to you.
GH automatically subscribes collaborators to all repo notifications (500+ per day). We recommend to change repo settings to "Not Watching", which will send you only notifications for issues you subscribed for, or where you are mentioned.
