### ISSUE TITLE
Android: In UnixIPInterfaceProperties.cs, GetDnsAddresses does not work

### ISSUE THREAD

**Issue by softlion** [dotnet/corefx#13946]
Instead on android you should get the linux properties net.dns1, net.dns2, ...

Shell:
`getprop net.dns1
`

Code:
```
for (i = 1; i <= MAX_DNS_PROPERTIES; i++) {
    char prop_name[PROP_NAME_MAX];
    snprintf(prop_name, sizeof(prop_name), "net.dns%d", i);
    __system_property_get(prop_name, dns);
}
```

**Comment by karelz** [comment]
Do you mean changing [NetworkInformation.GetDnsAddress](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/UnixIPInterfaceProperties.cs#L119) implementation? Is it going to work fine on all Linux distros?

@mellinoe I think you wrote the code, can you please comment/advise?

**Comment by softlion** [comment]
Yes implementation of NetworkInformation.GetDnsAddress,  in LinuxIPInterfaceProperties (which currently uses UnixIPInterfaceProperties). Will not work on all linux distro, but should work when UnixIPInterfaceProperties does not (ie resolv.conf is not found).

**Comment by mellinoe** [comment]
Right now it is expected that a lot of things will not work on Android, but I would be happy to review code that added support for it, depending on how complicated it is. A few things to keep in mind:

* We don't have any official support for Android right now, so even if we added code in `NetworkInformation` to support it, it's not clear how you'd even test that or use it.
* We don't have any infrastructure in place to build for Android, and we don't even have any machines to do that as far as I'm aware. I also don't have access to any Android machines that I could test this on.
* With the above in mind, though, I don't see why we couldn't add some basic Android support and put it behind some #ifdef's for now. It could be there for folks to build it if they wanted, and it will help our official bring-up when we want it.

@karelz Should we add a separate "os-android" label? I guess it would be different enough from "os-linux" to warrant it's own category, although I'm not really familiar enough with Android to say for sure.

**Comment by karelz** [comment]
@mellinoe we can add a new label if there is enough bugs which need it :) ... I don't want to add labels just for a few issues (recently I deleted a bunch of os-*-linux-* specific labels in favor of single general os-linux label).
The main question for me is if the code change proposed above would make sense on non-Android Linux as main code path -- in such case we could just change the code and test it only on current Linux distros. If the proposed code should be only fallback path when resolv.conf is not found , then we need to test it (even ad-hoc) on Android prior to making the change.

@softlion were you able to run .NET Core on Android, or did you suggest the change just based on code review?

**Comment by softlion** [comment]
I have successfully tested the code I put here on an android device (os version 4.4) using a xamarin project modified to use netstandard1.6 in its pcl.
I also have been able to use successfully your original unmodified code on an iOS 10 simulator. I have not been able to test on a real iOS device due to a bug in the xamarin linker.

**Comment by mellinoe** [comment]
I agree with @karelz that it's not really worth merging in any changes here until we're able to run them and test them on Android. And unfortunately, .NET Core does not support Android at this time, although there've been some small experiments with it. Once we get to that point, we should revisit this and look for a solution. We may even want to create a "meta-issue" to track things that we know are going to be broken on Android in the future, because I'm sure this is no the only one.

@softlion You are talking about Xamarin here, but this library is not intended to run on Xamarin.Android. It seems like that platform ships its own implementation of this functionality, although I'm not personally familiar with it. Are you not able to use their version of the library?

**Comment by softlion** [comment]
Well unfortunately I'm using your lib in a net standard 1.6 lib in order to
have the same assembly and codebase for all platforms and simplify setup
(no platform service to register). Netstandard1.6 does not include this
functionality by itself so it won't be able to remap it, and finally
xamarin have no implementation of it on any platform. The dns value is
required to query DNS for SVC entries (you can't do it with the dns class)
and implement ZeroConfig/autodiscover feature in enterprise environments.
So this is quite limitative and frustrating, as a 2 line piece of code
prevents a so important enterprise feature from being widely used. My lib
for the feature is open source and can be found here :
https://github.com/softlion/Heijden.Dns

Le sam. 26 nov. 2016 à 06:36, Eric Mellino <notifications@github.com> a
écrit :

I agree with @karelz <https://github.com/karelz> that it's not really worth
merging in any changes here until we're able to run them and test them on
Android. And unfortunately, .NET Core does not support Android at this
time, although there've been some small experiments with it. Once we get to
that point, we should revisit this and look for a solution. We may even
want to create a "meta-issue" to track things that we know are going to be
broken on Android in the future, because I'm sure this is no the only one.

@softlion <https://github.com/softlion> You are talking about Xamarin here,
but this library is not intended to run on Xamarin.Android. It seems like
that platform ships its own implementation of this functionality, although
I'm not personally familiar with it. Are you not able to use their version
of the library?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dotnet/corefx/issues/13946#issuecomment-263045512>, or mute
the thread

**Comment by mellinoe** [comment]
Unless I'm misunderstanding these documents, Xamarin.Android should support this as part of the core platform: https://github.com/dotnet/standard/blob/master/platforms/xamarin.android/System.cs#L7409. So you should be able to use the version that ships with the toolchain there. Since this is part of .NET Standard 2.0, I don't think we have any intention of shipping new versions of the code that lives here in corefx for any platforms other than .NET Core.

@akoeplinger

**Comment by softlion** [comment]
Ok i understand now that corefx is a separate team and product not related
to netstandard and not supporting some specific platforms, so why your
nugets do claim to support netstandard ? They should not, and they should
be marked as corefx only. Or maybe the problem resides in the netstandard
system which makes you falsely think that you can use all those netstandard
nugets in any platform supporting netstandard, which I now know is a false
promise. Again it is the victory of marketing against reality. From now on
netstandard will have my defiance. I'll blog about that. Thks for your time.
Le sam. 26 nov. 2016 à 08:57, Eric Mellino <notifications@github.com> a
écrit :

**Comment by softlion** [comment]
And note that the link you sent does not contain any class able to query a
dns for svc entries, nor able to retrieve iPaddress of dns used by network
interfaces.
Le sam. 26 nov. 2016 à 09:13, Benjamin Mayrargue <benjamin@mayrargue.com> a
écrit :

**Comment by karelz** [comment]
@softlion I think you got the netstandard backwards -- you can read more [here](https://github.com/dotnet/standard), especially the [FAQ on .NET Standard](https://github.com/dotnet/standard/blob/master/docs/faq.md)
The gist is that .NET Standard defines API set which each platform has to satisfy to be .NET Standard compliant. Any portable library (sitting on top of the platforms, not in them) can target .NET Standard 2.0 for example and it knows that it will work well on all platforms which are .NET Standard 2.0 compliant (which is full .NET Framework 4.6.1, Xamarin, will be .NET Core 1.2 soon and UWP eventually).

You are trying to treat part of the platform (.NET Core = CoreFX source code) as portable library which should work everywhere, across all platforms (full .NET, Xamarin, .NET Core and .NET Native). That is not what it is meant to be.
You can use analogy with browsers -- .NET Standard 2.0 (NS2.0) is like HTML 5 standard. Not every browser (analogy to .NET platform / implementation) supports it. Internet Explorer 9 (analogy to .NET Framework 4.6.1) supports fully HTML5 -- both are Windows-only, (at the time) widely used, both have newer versions (IE 10 / .NET Framework 4.6.2) which are also HTML5/NS2.0 compliant and earlier versions (IE 8,7,6 / .NET Framework 4.6, 4.5, 4.0) which are not compliant with the HTML5/NS2.0 standard, but are compliant with earlier standard HTML4/NS1.6, NS1.5, NS1.4, etc.
Now Xamarin is like another browser - let's say Firefox (at the time it was popular). .NET Core like yet another browser - e.g. Chrome (at the time it was new and growing). And .NET Native may be like Edge browser (Windows only, not as widely used as IE, but in places where IE is not - Windows Phone). All this is of course analogy only.

Now, would you components of Chrome to be able to work inside other browsers like Firefox - all versions, all OS versions where Chrome is not supported, but Firefox is? ... I hope not.
But that's exactly what you're trying to do when you use parts of CoreFX (.NET Core) and run them on Xamarin/Mono on Android where .NET Core is not even supported.

I hope it makes it clearer. If you have more questions, please ask.

BTW: .NET Standard and CoreFX are the same team. .NET Standard was for a long time produced out of CoreFX repo which made it technically challenging to add .NET Core only features/APIs which were not part of .NET Standard, because other platforms like Xamarin and full .NET Framework don't have them yet.

**Comment by mellinoe** [comment]
> And note that the link you sent does not contain any class able to query a
dns for svc entries, nor able to retrieve iPaddress of dns used by network
interfaces.

I just linked to the same API that was being discussed here. Am I mistaken about that?

I'd also just like to re-iterate that we'd be happy to review a PR that added an Android-compatible implementation, as long as we are able to test and verify it. Since the code here is for .NET Core, that would mean when CoreCLR itself is runnable on Android, which still has some work per my understanding.

**Comment by softlion** [comment]
You are the ower of the System.Net.NetworkInformation.4.3.0 nuget package or i misundersand something ?
This package does has the TFM MonoAndroid10. And you are explaining me that it is not supported on android. I am confused.
It also has a TFM.NETStandard1.3, but you just explained me that it is unsufficient to be compatible with an app supporting .NetStandard13 as it means it is only built on top and may add incompatible features.

If i understood you, you can not rely on nuget anymore warning you a package is incompatible with a project. And as there is no more "stub" versions in netstandard, even if xamarin android does support this api some day, it won't work as no stub would forward the implementation. But i can understand that.

I will not PR as you will not test on Android. You told me 3 posts ago that it is not your platform and you don't even have the tools, the phones, the skills and the team to test it.

**Comment by softlion** [comment]
Anyway GetDnsAddresses on System.Net.NetworkInformation does exist in Xamarin Android, you are right.

But i thought i could use your nuget in the PCL project using netstandard, and forward types to Xamarin.Android.

**Comment by softlion** [comment]
Ok i understand now. This "bug" is in also in the Xamarin version of System.dll as they use the exact same code as yours. So there may be type forwarding in netstandard finally ....

**Comment by karelz** [comment]
I am surprised that our packages list Mono as one of the supported platforms when we do not support it. That sounds wrong. @ericstj @weshaggard is that some kind of NuGet-ism? Or bug in our packaging?

**Comment by akoeplinger** [comment]
The NuGet package lists MonoAndroid10 as supported which is the legacy name of Xamarin.Android.

The "implementation" in the lib folder is the `_._` placeholder file which means the real implementation needs to be provided by the platform i.e. GAC. Looks like what I'd expect.

**Comment by karelz** [comment]
@akoeplinger why would a library, which is not truly available on Mono be marked as "I support Mono" ... I don't see much logic in that. What am I missing?

**Comment by akoeplinger** [comment]
@karelz the System.Net.NetworkInformation nuget package can be used fine on Xamarin.Android (e.g. as part of a netstandard dependency), it'll just use the implementation from the platform instead. It's the same for `net45`.

**Comment by karelz** [comment]
@akoeplinger ok, so that basically means this bug is filed at the wrong place -- it should be filed against Xamarin.Android.
Also there is no single "System.Net.NetworkInformation" owner. It is rather a collection of implementations on different platforms. netcore implementation happens to live in this repo ...
I guess I need to get educated more on NuGet and how it plays with our libraries ...

**Comment by softlion** [comment]
@karzel i filed the bug on xamarin android. They answered positively by redirecting me to the github implementations.
The problem is, the pr has to be done on 2 repos, first one is an android c repo and code is in c, second one is c# on mono. First pr must be accepted before second can be made. If you want to pr go, i think I won't.

**Comment by karelz** [comment]
Would be useful to link the issue from here.

**Comment by softlion** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=48016
