### ISSUE TITLE
Questionable MSBuild project reference

### ISSUE THREAD

**Issue by StevenLiekens** [dotnet/corefx#1395]
Regarding the first import statement in file `dir.props`
https://github.com/dotnet/corefx/blob/c5295ac33f158a68801a93405a2f105df840cfcc/dir.props#L2

If the file exists, the highlighted line of code imports a project file that is outside of the corefx repository. Why is that?

**Comment by ellismg** [comment]
@weshaggard or @chcosta can confirm, but the rationale, I believe, is to enable some internal scenarios we have where we take this source and build it internally out of our TFS repository.  In this case, the parent directory has some additional build rules we need consume in order to work with that build system.

**Comment by chcosta** [comment]
Confirmed. Matt is correct as to the intention of this file.  Long-term, I'm not certain that this file will be necessary, but as we are transitioning to open source it is a needed gap filler.
