### ISSUE TITLE
CI Failure System.Data.SqlClient.Tests.SqlConnectionBasicTests.ConnectionTest

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#14017]
```
MESSAGE:
System.Net.Sockets.SocketException : Address already in use
+++++++++++++++++++
STACK TRACE:
at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress) at System.Net.Sockets.Socket.Bind(EndPoint localEP) at System.Net.Sockets.TcpListener.Start(Int32 backlog) at Microsoft.SqlServer.TDS.EndPoint.ServerEndPointHandler`1.Start() at System.Data.SqlClient.Tests.TestTdsServer.StartTestServer(Boolean enableFedAuth) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Data.SqlClient/tests/FunctionalTests/SqlConnectionTest.cs:line 61 at System.Data.SqlClient.Tests.SqlConnectionBasicTests.ConnectionTest() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Data.SqlClient/tests/FunctionalTests/SqlConnectionTest.cs:line 22

**Comment by danmosemsft** [comment]
@saurabh500 this is a sporadic CI failure, could you please take a look? Looks like it is part of your test server commit. Tests run in parallel. Is there any possibility of a test running concurrently with this one, that uses the same resources?

**Comment by saurabh500** [comment]
@corivera can you comment out the test or investigate the failure while I am out?

@danmoseft can you post some links to any CI failures?

**Comment by danmosemsft** [comment]
I don't have any information beyond the above -- @JonHanna can you find the full CI log? (What was the PR)

**Comment by JonHanna** [comment]
Sorry, I meant to paste the URI into the report as well as the trace, but clearly didn't. I can't find the PR. I'm not even sure if it was mine, @bartdesmet's or someone else's.

**Comment by danmosemsft** [comment]
@JonHanna no problem. @corivera if you cannot figure the problem out from code inspection, please consider adding logging/tracing so we can solve this next time it's hit (assuming we get the logs in time)

**Comment by danmosemsft** [comment]
@corivera have you had a chance to look?

**Comment by saurabh500** [comment]
@danmosemsft I am going to look into this.
Some questions:
1. Are the failures in a particular OS or the failure occurs in any OS arbitrarily? 
2. Do the CI VMs/machines execute tests from multiple PRs in parallel? 

Based on the output that @JonHanna  has posted, the problem seems like the port needed by the Fake Sql server is in use either by another Fake Sql Server process or by another program outside .Net core. I am going to rule out any other process outside .Net core since this failure is sporadic in nature. 

I should modify the server such that a free port is used everytime the test runs.

**Comment by danmosemsft** [comment]
>Are the failures in a particular OS or the failure occurs in any OS arbitrarily? 

unfortunately without the log I can't tell the OS. I have not seen other reports of this problem so it's possible it only occurred exactly once. We still try to take action even when there's only one instance, as otherwise the sporadic failures add up and the CI pass rate declines. In some cases that means adding logging/hardening if we can't find and fix the issue.

>Do the CI VMs/machines execute tests from multiple PRs in parallel?

No, one PR at a time. And apparently on an unrelated PR in this case.

**Comment by saurabh500** [comment]
Thanks. The log above seems to point to macOS. I will work on the fix.

**Comment by jamesqo** [comment]
I just saw a similar failure occur here: https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/1979/testReport/System.Data.SqlClient.Tests/SqlConnectionBasicTests/ConnectionTest/

Here too: https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/1963/testReport/System.Data.SqlClient.Tests/SqlConnectionBasicTests/ConnectionTest/

**Comment by danmosemsft** [comment]
@saurabh500

**Comment by jamesqo** [comment]
Happened again: https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/1964/testReport/System.Data.SqlClient.Tests/SqlConnectionBasicTests/ConnectionTest/

**Comment by saurabh500** [comment]
I haven't been able to figure out the cause of the issue yet. 
I have executed the failing tests with the other tests, a bunch of times, but it hasn't failed for me. 
Since there are no line numbers in the Exception stack trace, its hard to pinpoint where the exception is coming from.
When I looked at the objects being referenced in the SqlConnection.TryOpen() code, I haven't been able to find any obvious reason for this NRE. The initialization of the objects seem to be fine. 

I will continue looking.

**Comment by stephentoub** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/1990/

**Comment by stephentoub** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/1991/

**Comment by sepidehMS** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/1994 (Windows)

**Stacktrace**

```
MESSAGE:
Assert.Null() Failure\r\nExpected: (null)\r\nActual: System.NullReferenceException: Object reference not set to an instance of an object.\r\n at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n at System.Data.SqlClient.SqlConnection.Open()\r\n at System.Data.SqlClient.Tests.SqlConnectionBasicTests.ConnectionTest() in D:\\j\\workspace\\windows_nt_re---37265eab\\src\\System.Data.SqlClient\\tests\\FunctionalTests\\SqlConnectionTest.cs:line 23
+++++++++++++++++++
STACK TRACE:
at System.Data.SqlClient.Tests.SqlConnectionBasicTests.ConnectionTest() in D:\j\workspace\windows_nt_re---37265eab\src\System.Data.SqlClient\tests\FunctionalTests\SqlConnectionTest.cs:line 30
```

**Comment by danmosemsft** [comment]
@saurabh500 could any logging potentially be useful? Even in the product, if it's temporary. It doesn't seem like it would take long to get a hit.

**Comment by saurabh500** [comment]
I am removing the SqlConnectionTest from the SqlClient test suite to continue investigation offline. 
The coverage for SqlConnectionTest is already provided by the DiagnosticTest in SqlClient.

**Comment by stephentoub** [comment]
again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/2011/

**Comment by saurabh500** [comment]
I have the marked the test with `ActiveIssue` and I will continue to investigate the problem.

**Comment by mellinoe** [comment]
If it's helpful, here's another repro: https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/1998/consoleFull

**Comment by danmosemsft** [comment]
Removing label since test is disabled

**Comment by saurabh500** [comment]
I have a failure with Line numbers 


Assert.Null() Failure\r\nExpected: (null)\r\n
Actual: System.NullReferenceException: Object reference not set to an instance of an object.\r\n 
at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry) in D:\\j\\workspace\\windows_nt_re---37265eab\\src\\System.Data.SqlClient\\src\\System\\Data\\SqlClient\\SqlConnection.cs:line 1011\r\n 
at System.Data.SqlClient.SqlConnection.Open() in D:\\j\\workspace\\windows_nt_re---37265eab\\src\\System.Data.SqlClient\\src\\System\\Data\\SqlClient\\SqlConnection.cs:line 585\r\n 
at System.Data.SqlClient.Tests.SqlConnectionBasicTests.ConnectionTest() in D:\\j\\workspace\\windows_nt_re---37265eab\\src\\System.Data.SqlClient\\tests\\FunctionalTests\\SqlConnectionTest.cs:line 23
