### ISSUE TITLE
ArgumentNullException produces different messages when run on Windows or Docker

### ISSUE THREAD

**Issue by joaoasrosa** [dotnet/corefx#14036]
ArgumentNullException produces different messages when running on Windows or Docker. 
Running a unit test for a method where sanity checks exist (for null values), produces the following output:

- Windows: "Value cannot be null.\r\nParameter name: foo"
- Docker (from microsoft/dotnet:latest): "Value cannot be null.\nParameter name: foo"

Code snippet for the sanity check:
`if (null == foo)
{
    throw new ArgumentNullException(nameof(foo));
}`

Tested with the latest version of .NETCore 1.1

**Comment by stephentoub** [comment]
I assume the docker case is using Linux? If so, this is by design: Windows and Linux use different newlines, and this exception message has a newline in it.

**Comment by Clockwork-Muse** [comment]
I'm curious; the way you've written this implies you're validating the message output.  You generally want to avoid explicitly adding the message, since most messages (especially in exceptions from the base libraries) are going to be translated.  
Message content should be in a resource file anyways, and has to be validated differently.  Probably with, among other things, a test-only mock resource file and custom culture.

**Comment by joaoasrosa** [comment]
@stephentoub your are right. If it is by design I will close it.
@Clockwork-Muse thanks for pointing out, the library is English only, but tomorrow it can change.
