### ISSUE TITLE
New generic TaskFactory.StartNew<T> API

### ISSUE THREAD

**Issue by djechelon** [dotnet/corefx#14053]
Hi,

I would like to suggest to add an additional overload to [TaskFactory](https://msdn.microsoft.com/library/system.threading.tasks.taskfactory_methods(v=vs.110).aspx)

To the existing

     StartNew(Action<Object>, Object, CancellationToken, TaskCreationOptions, TaskScheduler)

I would add

     StartNew(Action<T>, T, CancellationToken, TaskCreationOptions, TaskScheduler)

The reason is not to force the developer to do runtime checks and casts when the invoked method accepts an object (or a collection) of type T which is well-known at compile time

Current code:

```c#
 private void Insert(Object state)
        {
            var entities = state as IEnumerable<Entity>;
            using (var context = GetDataContext())
            {
                context.entities.AddRange(entities);
                context.SaveChanges();
            }
        }

Task.Factory.StartNew(Insert, entityList); //invoked with
```

Desiderata:
```c#
 private void Insert(IEnumerable<Entity> entities)
        {
            using (var context = GetDataContext())
            {
                context.entities.AddRange(entities);
                context.SaveChanges();
            }
        }

Task.Factory.StartNew(Insert, entityList); //invoked with
```

**Comment by svick** [comment]
What's wrong with using a closure? I.e.:

```c#
Task.Factory.StartNew(() => Insert(entityList));
```

I believe the `object` overloads exist mostly so that you can avoid closure allocations. Since it's a performance optimization, convenience does not matter much.

Also, looking at [the source code](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/Tasks/Task.cs#L2841-L2852), I think doing this would require pretty significant changes to the implementation.

**Comment by alexperovich** [comment]
I have no problem with adding the API if it can be done without significant change. If it requires large changes then I don't think it is worth it.

For now this functionality can be added via an extension method on TaskFactory.
