### ISSUE TITLE
LocalAppContext.DisableCaching does not work

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#14064]
`DisableCaching` does not always return the correct value when it has been set to `True` in the tests. 
Please refer to https://github.com/dotnet/corefx/blob/master/src/Common/src/System/LocalAppContext.cs

@AlexGhiondea

**Comment by AlexGhiondea** [comment]
@sepidehMS do you by any chance have a small repro I can take a look at for this?

**Comment by sepidehMS** [comment]
@AlexGhiondea Change `LocalAppContext` to its previous version in [this PR](https://github.com/dotnet/corefx/pull/14065/files) and run [System.Xml.Xsl.XslCompiledTransformApi.Tests.csproj](https://github.com/dotnet/corefx/tree/master/src/System.Private.Xml/tests/Xslt/XslCompiledTransformApi). Few tests should start failing as `XsltCompiledTransform.Load` starts using `XmlNullResolver` instead of `XmlUrlResolver` and would not allow external URIs to be resolved inside a XSL.

**Comment by sepidehMS** [comment]
Reopening as this still happens in two new tests: [this](https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/tests/XmlSchema/XmlSchemaSet/TC_SchemaSet_XmlResolver.cs#L102) and [this](https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/tests/XmlSchema/XmlSchemaSet/TC_SchemaSet_XmlResolver.cs#L133)  (the failure is not consistent though)

**Comment by safern** [comment]
Will take a look to those failures... though the problem that we faced in previous failures wasn't with `DisableCaching` not working, it really was with the test's configurations that weren't setting the switch where they should set it in order to have a consistent behavior without caching values. We just had to set `DisableCaching` switch to true on the tests constructors. @sepidehMS

**Comment by safern** [comment]
Do you have a local repro state yet?

**Comment by sepidehMS** [comment]
@safern I set DisableCaching in the constructor of these tests, but that doesn't always set it in the right time. Yes, I can repro the failure locally, but it only happens in some of the runs. You only need to re-enable the tests and run the a few times, and you should be able to see them fail. Thanks.

**Comment by safern** [comment]
Yes that is what I saw, that you set it correctly... maybe it is happening because of the static constructor in `LocalAppContext` that is being called before the switch is being set in this case and there is the only place where we try to read `DisableCaching` switch value and the value we read there is the value that will persist on the whole run, even if we update the switch's value `LocalAppContext` will never try to read it again. 

Will try to repro locally and use another approach to get the switch's value. Instead of trying to get it in the static constructor I will try to get it in `GetCachedSwitchValue` when it is called the first time. @sepidehMS

**Comment by AlexGhiondea** [comment]
@safern I think moving away from the static constructor on LocalAppContext is the right thing to do even if we can find another way to fix this in the tests.

**Comment by safern** [comment]
@AlexGhiondea I already moved away the static constructor and will leave it that way but the tests are still failing and as @sepidehMS mentioned we don't always have failures because it matters the order that the tests are run. If the tests that are failing are the first to run it wouldn't fail because we're setting `DisableCaching` to true on the constructor. In the other hand if another test is run first and we don't set the switch to true on that test's constructor it will obviously cache the values and we will have test failures.

So my suggestion is to set the switch value to true on every test constructor so that we don't depend on the order the tests are executed. Or do you have any other suggestion like adding a base class with an static constructor so that when the first test is referenced from that constructor we can set the switch value.

Do you have any other suggestion?
