### ISSUE TITLE
Changing Visual Studio debug settings takes a long time

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#14137]
This has been ongoing for a while now, so it may be a duplicate. However, the problem seems to be getting worse so I created this issue.

Changing Debug properties on a project takes 2.5 minutes on my machine. During this time I see that dotnet.exe is launched dozens of times calling apicompat.exe, genfacades.exe or vbcscompiler.exe.

Repro (on Visual Studio 15 Update 3):
1) Open src\System.Security.Cryptography.Algorithms\System.Security.Cryptography.Algorithms.sln
2) Right-click on the Test project and select Properties
3) Click the Debug tab
4) Change "Start external program" to a different value
5) Press tab or lose focus

Result: Visual Studio appears to freeze for 2.5 minutes and using Process Explorer I can tell that it is launching apicompat, genfacades and vbcscompiler many times.

Changing other options including the "Command line arguments" text box or even clicking one of the checkboxes also does the same thing. This is frustrating as normal debugging scenarios often require changing "Start external program" in addition to "Command line arguments", meaning 5 minutes of down time.

Note changing the top-level build type (in the main menu, not the build configuration Debug properties) also takes a long time, but not quite as long - around 1 minute (for example changing from Unix_debug to Windows_debug).

**Comment by danmosemsft** [comment]
These are probably getting hooked into the design time build. That build is supposed to be subsecond.

**Comment by steveharter** [comment]
Related performance issue: https://github.com/dotnet/corefx/issues/12001 about opening up a VS project (which was "fixed" but still seems to take too long and it also launches the same apicompat, genfacades and vbcscompiler)

**Comment by danmosemsft** [comment]
@joperezr @weshaggard

**Comment by joperezr** [comment]
It is a design time build, and the problem is that when you change that you are not only changing the configurationGroup, but you are also changing TargetGroup and maybe even OSGroup, which causes design time build to call restore on the project.json, genfacades to run, and the whole build to happen. Additionally, if that project has a bunch of P2Ps it will trigger a lot of subsequent builds. I agree the experience is not great, but this will hopefully get much better after we are done with our "build from source" effort, since vertical builds will take a bunch of these variables out of the picture.

**Comment by steveharter** [comment]
Why does a build even start? The repro steps are not initiating a build. A standard VS project (non-corefx) will not attempt a build if those same settings are changed.

**Comment by joperezr** [comment]
I believe a build is always triggered, even with standard VS projects. The design time build is used for things like intellisense, so if doesn't run, then intellisense won't work. The difference between this and other projects, is that in corefx, changing the ConfigurationGroup makes it to build not only the current project, but other P2Ps as well, and in most cases it can't reuse the previously built binaries because the TargetGroup is different as well.

**Comment by steveharter** [comment]
Note the repro steps do not change any settings except for the external binary to start when debugging. I don't see why this should trigger a design time build.

**Comment by roncain** [comment]
I can confirm we have been seeing this same issue using any of the test SLN's in the https://github.com/dotnet/wcf repo.  Using project properties Debug tab, both these operations are excruciatingly slow:
1) Change the working directory (just move focus off the field and VS is unusable for several minutes)
2) Change the path to the external binary (same thing, just move focus off that field and wait)

This is true whether or not we start with a clean repo or build all the .csproj's first.

**Comment by weshaggard** [comment]
Sounds like we should turn on design-time build logs and understand more of what is happening here as I agree we shouldn't be doing much in that step.

**Comment by steveharter** [comment]
Closing as the perf issue with the recent build from source changes makes this much better.
