### ISSUE TITLE
Improve Unable to find Curl exception

### ISSUE THREAD

**Issue by ayende** [dotnet/corefx#14151]
I'm running CoreCLR on Raspberry PI and we are running into an issue with HttpClient:

```

 System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Net.Http.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.HttpInitializer.EnsureCurlIsInitialized()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.HttpInitializer.Initialize()
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()   
```

Here are the details on the native module:
```
dotnet/System.Net.Http.Native.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=4f81af5b4f6ce4731ebd55ea7d5427a58271a6b3, stripped
```

The problem  was that it doesn't give a good error message. I fixed that by installing libcurl3, and I think that it should give a suggestion on why this is missing

**Comment by karelz** [comment]
Assuming dynamic loading on Linux works in similar way as on Windows, I guess we truly fail to load System.Net.Http.Native because one of its dependencies does not exist. Is that correct assumption?

In such case we could do try-catch around the [native call](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/Common/src/Interop/Unix/System.Net.Http.Native/Interop.Initialization.cs#L29) and throw more specific exception "Unable to load and initialize cURL library".

How common is this case for existing platforms? (bring up of new platforms is rather rare and special)
Shouldn't we rely just on the exception above + search the internet for solution?

If we decide to change, we should do same for OpenSSL (and other native libraries we depend on, if any).

@janvorli any advice?

**Comment by janvorli** [comment]
We list a set of dependencies that need to be installed in order to use dotnet. curl is one of them. However, we don't list those dependencies on the dotnet/cli page where the current packages can be downloaded. These seem to be well hidden in the corefx / coreclr building docs.
So we should list them side by side with links to download the dotnet packages.
As for the exception, I think we could modify the DllNotFound exception message to say "The specified module **or one of its dependencies** could not be found". Then it would be clearer.
People can then run "ldd -r" on the shared library (System.Net.Http.Native.so) and see what dependecies are missing. This would be a simple change in the coreclr PAL where the message is located.

**Comment by karelz** [comment]
Shouldn't the Linux prereqs be listed primarily here: https://www.microsoft.com/net/core#linuxredhat ?

@janvorli can you please create a bug in core repo for the message change?

**Comment by karelz** [comment]
This issue was moved to dotnet/coreclr#9953
