### ISSUE TITLE
CORS AngularJS Api Controller Error 415 

### ISSUE THREAD

**Issue by LucasArgate** [dotnet/corefx#14164]
Im using .net core (vNext) application with Kestrel.
When i use GET method it works perfectly request, but when i use POST or PUT method it not do complete request.

Im using Api Controller and i created an attribute filter to do pre-flight in OnActionExecuting to return status code 200. When i do POST method it not works.

see my **OnActionExecuting** method:

```c#
public override void OnActionExecuting(ActionExecutingContext filterContext) 
{
    HttpContext context = filterContext.HttpContext;
    context.Response.Headers.Add("Access-Control-Allow-Origin", "*");
    context.Response.Headers.Add("Access-Control-Allow-Headers", "token, content-type");
    context.Response.Headers.Add("Access-Control-Allow-Methods", "GET, POST, OPTIONS");

    if (context.Request.Method == "OPTIONS")
    {
        filterContext.Result = new StatusCodeResult(200);
        return;
    }
}
```

im trying to enable **CORS** in my startup class:

```c#
public void ConfigureServices(IServiceCollection services)
{
    // Add service and create Policy with options
    services.AddCors(options =>{
        options.AddPolicy("CorsPolicy",
            builder => builder.AllowAnyOrigin()
                .AllowAnyMethod()
                .AllowAnyHeader()
                .AllowCredentials());
        });
    // Add framework services.
    services.AddMvc();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    loggerFactory.AddConsole(Configuration.GetSection("Logging"));
    loggerFactory.AddDebug();

    app.UseMvc();
    app.UseCors("CorsPolicy");
}
```

Error request:

**XMLHttpRequest cannot load http://192.168.100.100:5000/api/caixa. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8080' is therefore not allowed access. The response had HTTP status code 500.**

I don't know what i need do to resolve it, i search it and there isn't any solution. Please, I need help.

*Obs: I will use it in WIndow 10 IoT at Raspberry PI3.

**Comment by karelz** [comment]
So I guess what you're saying is that your handler `OnActionExecuting` is not invoked when it should be, right? In that case you should file the bug somewhere in https://github.com/aspnet.
This repo is about base class libraries. ASP.NET is built on top of it.

BTW: It is not clear to me why you AngularJS (is it specific to it?) or if the problem is only on Raspberry Pi. (did you try other platforms?)

**Comment by LucasArgate** [comment]
hey @karelz  sorry! i will post it in right thread!
i will search the right! thanks...

So Im trying in windows 10 (normal) but it will run on Raspberry Pi3. I am using AngularJs i think it can be the error... I Don't know. It is not normal and there isn't ant solution in stackoverflow or git's issues.
When i do the request it not work... and i tried it with AngularJS $resource, $http and now by jQuery and it not works :( 

thanks for your attention.

**Comment by karelz** [comment]
> hey @karelz sorry! i will post it in right thread!

No worries.

>  I am using AngularJs i think it can be the error...

In general I recommend to minimize repros and remove as many technologies as possible - that helps to identify where the problem is. Minimal repros have much higher chance that someone will look into them as they are easier to repro and debug. Debugging large end-to-end across multiple technologies is just gigantic pain :( ... just my 2 cents.

**Comment by LucasArgate** [comment]
HA HA HA HA !
Thanks @karelz  where i pay your 2 cents ?
hahaha
