### ISSUE TITLE
Optimize new ToHashSet api.

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#14173]
#13726 added `Enumerable.ToHashSet`, which is currently equivalent to writing `new HashSet<TSource>(items)`. We may want to look into optimizing it by adding it as another method on `IIListProvider`, and reducing some virtual method calls. Opening this as a tracking issue for that.

cc @JonHanna

**Comment by JonHanna** [comment]
Most optimisations available from IIListProvider are available due to being able to:

1. Predict the size of the collection produced from the size of the source.
2. Pass that information to the collection creation.

In the case of HashSet, knowledge of the source size only gives a maximum, because the size will depend on the number of distinct elements (and that in turn on the equality criteria), so a 10,000 element source could end up creating a 3-element set. There also isn't a constructor that takes a capacity argument (for much the same reason).

**Comment by jamesqo** [comment]
@JonHanna You are correct, most of the time (except for a few fringe cases like `Range`, `Repeat`, and `Union`) we will not be able to predict the size of the end result... however, we can still reduce virtual method calls (i.e. like [here](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Where.cs#L729)) by just looping through the source in `Select` and `Where`, and doing the exact same thing as if we had been called `MoveNext` on.

**Comment by JonHanna** [comment]
Ah, I get you. That would reduce some calls, all right, and not interfere with the optimisations within HashSet itself, for that matter, AFAICT.

**Comment by fujiy** [comment]
Hi, I'll work on it

**Comment by fujiy** [comment]
Hi, I'll work on it.
@karelz would you assign me please?

**Comment by karelz** [comment]
This is no API addition, but perf enhancement. Upfront approval is not necessary.
If you want to focus on impactful issues, check out "up for grabs" + (wishlist or milestone:2.0.0).

**Comment by fujiy** [comment]
Since we have only a few hours to work on it, we'll start with the small issues to learn how the entire process work.
@TiagoSoczek will take this issue

**Comment by fujiy** [comment]
@karelz would you assign @TiagoSoczek?
Thanks

**Comment by karelz** [comment]
Invite sent ...

**Comment by TiagoSoczek** [comment]
Invitation accepted @karelz, thanks. I'll work on it.
