### ISSUE TITLE
Add regression tests for possible bug in OrderedEnumerable.Last{OrDefault}

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#14183]
I am not too familiar with `OrderedEnumerable`, but while making changes during https://github.com/dotnet/corefx/pull/14174 I noticed there was a discrepancy between `Last` and `LastOrDefault`.

Code in `Last`: https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/OrderedEnumerable.cs#L416. The result of `comparer.Compare` is compared with `>=` to 0.

Code in `LastOrDefault`: https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/OrderedEnumerable.cs#L447 The result of `comparer.Compare` is compared with `>` to 0.

I assume this is trying to somehow find the maximum value of the enumerable? If that is the case, is the latter version correct?

cc @JonHanna @VSadov

**Comment by jamesqo** [comment]
Note: I am making changes to the method in https://github.com/dotnet/corefx/pull/14174 so please wait until that goes in first. Thanks.

**Comment by JonHanna** [comment]
The second one is incorrect because in the case of `Enumerable` (unlike for other linq providers) `OrderBy` is specified as being a stable sort. The combination `OrderBy(keySelector).Last(pred)` should therefore not only find the value which produces the largest key and matches the predicate, but also in the case of a tie find the last such value. `>=` does that because it replaces the current match in the case of a tie, `>` does not.

> Note: I am making changes to the method in #14174 so please wait until that goes in first. Thanks.

I see that you are changing the first, but not the second. Shall I go ahead and push my fix for the second?

**Comment by jamesqo** [comment]
@JonHanna Sure, go ahead. I had actually deleted both methods entirely in my editor and then copied-and-pasted, so I assumed this would cause merge conflicts, but it's fortunate that that area is unaffected.
