### ISSUE TITLE
NuGet license information does not match repository

### ISSUE THREAD

**Issue by sharwell** [dotnet/corefx#1429]
I noticed that the LICENSE link on the following page is substantially different from the license included in this repository. Is this intended?

https://www.nuget.org/packages/System.Collections.Immutable

In case things change in the future, the link currently takes you to [MICROSOFT SOFTWARE LICENSE TERMS - MICROSOFT .NET LIBRARY](http://go.microsoft.com/fwlink/?LinkId=329770).

**Comment by richlander** [comment]
For clarity, are you comparing the above MS .NET Library License and [LICENSE.TXT](https://github.com/dotnet/coreclr/blob/master/LICENSE.TXT)?

**Comment by sharwell** [comment]
Yes

**Comment by richlander** [comment]
It didn't occur to us to make the licenses the same, since the scenarios are very different. One is for the source code and the other is for our commercial binary distribution. Very little about our process for commercial distributions has changed since we went open source, and that's how many of our customers want it.

Here's how the typical conversation goes with our larger customers:

- Customer: I see that .NET Core is now open source. Does that mean support and your shipping process is also changing?
- MSFT: No. You don't need to change anything about the way you use our software.
- Customer: OK, great! 

There are also some parts of the commercial license that are legally required (as I understand it). Notice the presence of more than English.

Does that help?

**Comment by sharwell** [comment]
Yes thank you.
