### ISSUE TITLE
where is "System.Runtime.Remoting.Messaging.CallContext"  in dotnetcore

### ISSUE THREAD

**Issue by SimpleDays** [dotnet/corefx#14303]

**Comment by danmosemsft** [comment]
Hi @SimpleDays. Remoting is not currently supported in .NET Core. What is your scenario?

**Comment by SimpleDays** [comment]
I need to use this class. Is there any other substitute in .Net Core? @danmosemsft

**Comment by danmosemsft** [comment]
@stephentoub what alternatives do we recommend to System.Runtime.Remoting?

**Comment by benaadams** [comment]
[AsyncLocal](https://msdn.microsoft.com/en-us/library/dn906268(v=vs.110).aspx) rather than CallContext?

Example usage differences in [AspNetCore's `HttpContextAccessor`](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http/HttpContextAccessor.cs) and ifdefs for frameworks

**Comment by stephentoub** [comment]
> what alternatives do we recommend to System.Runtime.Remoting?

@SimpleDays, I assume you're just looking to flow data across asynchronous operations?  Assuming yes, you want ```AsyncLocal<T>```: https://msdn.microsoft.com/en-us/library/dn906268(v=vs.110).aspx

**Comment by SimpleDays** [comment]
thx @danmosemsft  @benaadams  @stephentoub  i try to use it. :smile:

**Comment by SimpleDays** [comment]
@benaadams @stephentoub  @danmosemsft  
I use `AsyncLocal<T>` to solve the problem. thx! :smile:  :+1: 
i close this issues.
