### ISSUE TITLE
Centralize RID calcuation for build

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#14322]
We have a few scenarios that need a RID during the build.
1. Test execution
2. External package resolution: what RID to use for building out runtime directory?
3. Package building:  what RID to use when packaging the binaries that were built?

Currently this logic is all duplicated and each place is a little different.  We should try to unify it and make it simple to override/specify.

/cc @weshaggard @ellismg @mellinoe

**Comment by mellinoe** [comment]
If we're able to use managed code, then we should just use the [core-setup PlatformAbstractions library](https://github.com/dotnet/core-setup/blob/master/src/Microsoft.DotNet.PlatformAbstractions/RuntimeEnvironment.cs#L30) to retrieve the local system's RID for most of these, at least as a default. I think they all need to be overridable, especially for our official builds. If we are doing a native build with no `dotnet` available, then I'm not sure what we should do. We might need to coordinate with the managed build if it's running, and then just fall back to something like `netcoreapp-linux-x64` instead of a real rid if it isn't.

We default to `win7-x64` for tests on Windows, even though a variety of other rids would be viable to run, and it isn't the actual rid of most developer machines (`win10-x64` probably is). For all other platforms, we default to the local system's rid (using PlatformAbstractions) for tests.

Package building is often different from the local rid so that needs to be configurable. I think it's probably okay to default it to the local rid, though.

**Comment by ericstj** [comment]
@weshaggard  fixed this with https://github.com/dotnet/corefx/commit/4d6c7315359aed4d99ee3402de0f4eac9e606599.  I picked his changes in packaging with https://github.com/dotnet/corefx/commit/fd01a442f216c1f7dc9440606e14a9d9649c50f7.  @mellinoe can you make sure we're using RuntimeOS during testing?

**Comment by weshaggard** [comment]
Yes RuntimeOS is now computed as part of the configuration intialization. RuntiemOS combined with ArchGroup will give folks the correct RID for packaging and restoration.
