### ISSUE TITLE
Improve code coverage for Microsoft.CSharp.dll (72%)

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#14345]
There are almost [no tests](https://github.com/dotnet/corefx/blob/master/src/Microsoft.CSharp/tests/CSharpArgumentInfoTests.cs) so there is [essentially zero coverage](https://dotnetcoverage.blob.core.windows.net/cov1/report/index.htm)

**Comment by JonHanna** [comment]
If we can figure out what's causing #13523 we could see if my guess that it's what prevented #14019 from working, and get about 50% quickly. At least those tests would fail eventually if something breaking the areas they cover (without the coverage being noted) was merged in.

**Comment by danmosemsft** [comment]
@JonHanna when I run code coverage locally it seems to only copy to the test bin directory the symbols for the assembly under test. So coverage of a type would only come from the tests for the assembly it is in. So a P2P to M.CSharp would not help.
That maybe should be changed, but one could argue that such indirect coverage is less valuable (less likely to verify results)

**Comment by JonHanna** [comment]
When I ran that branch locally it certainly did give coverage for M.CSharp too, but that was a single-project run now that I think of it, so maybe it's something to do with how the results are combined in the full runs. (And for that matter, maybe #13523 is related to that too).
The tests aren't totally indirect, in that they live in S.L.Expressions to test classes like e.g. `BinaryOperationBinder` and do some of that by testing e.g. `CSharpBinaryOperationBinder` as a concrete implementation, so said tests really do test both classes rather than test one and just happen to pass through some paths in the other.

**Comment by danmosemsft** [comment]
@VSadov perhaps you could look around for old test sources for this one, while you're looking for the M.VB ones ?

**Comment by JonHanna** [comment]
Currently at 72% as per https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows_prtest/30/artifact/bin/tests/coverage/index.htm and hopefully as per the link from the homepage soon.

**Comment by danmosemsft** [comment]
Hey, that's great. I didn't notice that. This is a relatively low priority to take further then.

**Comment by JonHanna** [comment]
Currently at 80.8%.

Can this one be assigned to me? Chipping away at it is a general focus of mine, when I've time to contribute to corefx.

I'm not sure it's suitable for the "easy" label any more; the bulk of what was done on moving the needle is identifying dead code which isn't always the easiest due to the need to be sure nothing not truly dead is being deleted. (Well, I'm always nervous enough to do another check after the triple-check…) and covering the remaining coverable bits has been a bit fiddly at time, relatively speaking.

**Comment by pjanotti** [comment]
Closing per latest numbers: 

Lines: 87.3%
Branches: 74.7%
