### ISSUE TITLE
How to train your dragon 2!

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#1445]
This is a duplicate of this issue for this repo: https://github.com/dotnet/coreclr/issues/744

As you know, the .NET Team, as a broad group, is new to open source. We're doing some things right and other things less so. We might as well just get this out in the open and detail the specific things that  could/would/should go better. It's an issue!

Certain contributors (*cough* @kangaroo) have been doing an excellent job pointing out various things that MS folks need to change for .NET Core to be a truly successful OSS project. We've been changing some of those things, although maybe not at the scale we should be. I'm sure other folks have ideas too of what could be going better.

Here's are the specific issues that I've heard. Please pile on, with as much detail as needed (including pointing to PRs and issues as examples). It's OK. Point to the specific examples. It's the only way to fix things. The center of the issue is the firewall between the internal MS process and the GitHub repo and community. We need to remove the firewall, not just open ports in it.

I've written several detailed points below. I think that they all boil down to this advice for MS engineers:

> Invest as little time as possible before creating an issue or pushing code to the community. Sharing is a much higher concern than quality.

- **DO** create issues as soon as possible, even before you fully understand the problem. Self-assign or make up-for-grabs.
- **DO** use public feature branches (personal or central) for work in progress.
- **DO** start work in the open as soon as possible, well before you are done, even before you quite know what you are doing. ```git rebase -i``` and ```git branch -D mybranch``` are your friends.
- **DO** use Issues. **DON'T** use email (as much as possible). Internal technical discussions don't help the community learn and don't enable them to participate. It's like keeping a new hire off of mail threads, for reasons.
- **DO** share snapshots of progress externally on an issue if there is an internal discussion going on. Take a picture of a whiteboard and share it!

**Comment by sharwell** [comment]
**DO** tag commits that are used for releases to NuGet. :smile:

**Comment by Maxwe11** [comment]
- **DO** Make comments on the diff of a pull request only [in this way](https://help.github.com/articles/commenting-on-the-diff-of-a-pull-request/)
- **DO** [Close issues via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages)

**Comment by ellismg** [comment]
> **DO** copy text from TFS issues. The community cannot review a pull request with a summary like "Fix TFS devdiv bug 1100110011"

I think this is a general case of "write good commit messages".  Ideally, you don't need anything other than the commit message to understand the problem a change is addressing and how it fixes it (this also means I shouldn't have to go look at some GitHub issue to understand why a change is happening).

We do have a bit of a problem in the sense that we have some changes which we continue to do in TFS (because they need to touch libraries which we have open sourced and libraries we haven't atomically) and sometimes these have less than great commit messages.  We also have a problem around TFS changes which happen by other teams or in other branches that eventually get mirrored into CoreFX or CoreCLR.  In these cases, the commit messages are often not the best (especially in the case where the changes originate in another TFS branch which is then merged into our TFS branch and mirrored in Git).

From time to time, folks internally and externally ask if we can do better here.  The short answer is: "yes, but it's hard", the longer answer is we'd have to do a fair amount of work internally with our mirroring tools to be able to handle a bunch of these cases better.  In my mind, there's high value things we can be doing since the long term goal is to move more and more folks towards developing out of Git directly.  I would rather we spend our time open sourcing more components or bringing more thing cross platform, then trying to mirror at full fidelity everything that happens internally in TFS in a way that is natural to Git.

If folks feel differently, we can certainly try to change things up (in my opinion this is actually a larger problem in CoreCLR than it has been in CoreFX), but I want everyone to understand there are very real engineering costs to doing so.  Our internal and external systems are unfortunately fairly different from one another and I think right now the team would like to spend as much time as possible moving things from the internal system to the external system even if the transition process is a little painful and the experience for the short period of time where we have to work concurrently out of TFS and Git is not the best for work authored in TFS.

**Comment by akoeplinger** [comment]
@ellismg I agree that the focus should be on getting things into GitHub. For the cases where there's a commit mirrored from TFS that mentions a TFS issue, a simple solution might be to just open a GitHub issue and paste the relevant content in, so it shows up in search results.

**Comment by richlander** [comment]
@Maxwe11 I didn't know you close issues in that way. Nice. On the comments point, have you seen that be a problem or its just general guidance?

**Comment by Maxwe11** [comment]
@richlander comments left through "Files changed" tab are persistent comments - stable for amending/rebasing. After amending commit persistent comments marked as "outdated diff" (e.g. #1421). Comments left directly on commit got deleted from PR but left in referenced issue (#924 see referenced commits)

**Comment by richlander** [comment]
Ah, yes. The "Files changed" tab is the way to go. That's what I always do, modulo process comments (@Sally, can you look at this?).  Agreed. We can add that one.

**Comment by sharwell** [comment]
@ellismg I'm not talking about all TFS issues. I'm talking about pull requests like dotnet/roslyn#2056 which are submitted for public code review without context. In those cases we are just left guessing. :smile:

**Comment by ellismg** [comment]
@sharwell Gotcha. For work where the code change originates in git, like the issue to linked to, I agree we could do much better.

**Comment by terrajobst** [comment]
> @ellismg I agree that the focus should be on getting things into GitHub. For the cases where there's a commit mirrored from TFS that mentions a TFS issue, a simple solution might be to just open a GitHub issue and paste the relevant content in, so it shows up in search results.

I think what @ellismg is saying that ideally the details are in the commit and neither buried in TFS work items nor GitHub issues. In the end, the source control is the thing that folks always have. I personally consider the other pieces transient.

**Comment by hpshelton** [comment]
This may be controversial, but since I prefer history without the merge commits, I'd like to see pull requests rebased onto master. See https://github.com/jquery/jquery/commits/master for an example. I believe this means forsaking GitHub's merge pull request functionality since it merges `--no-ff` by default.

**Comment by sharwell** [comment]
Looks like I have another one.

**DO** use `--no-ff` for *all* commits made to the `master` branch (or equivalent), even for commits which are already based on master and consist of only a single commit. Fortunately this is automatic though the GitHub user interface, but all offline merges will require the flag be set explicitly.

**Comment by gafter** [comment]
@hpshelton @sharwell It sounds like you two are at diametrically opposed sides of this issue?

**Comment by sharwell** [comment]
@gafter That appears to be correct. :sos:

**Comment by hpshelton** [comment]
Linking the pull request from GitHub seems fragile. If there's discussion that should be kept long-term shouldn't it be in the source or in the commit message where it can be accessed offline? 

Just my two cents.

**Comment by stephentoub** [comment]
The original issue https://github.com/dotnet/coreclr/issues/744 that this duplicates has been closed as completed, so I'm closing this, too.

**Comment by whoisj** [comment]
> DO use --no-ff for all commits made to the master branch (or equivalent), even for commits which are already based on master and consist of only a single commit. Fortunately this is automatic though the GitHub user interface, but all offline merges will require the flag be set explicitly. All such merge commits (made to the master branch) should include the pull request number which the merge represents.

Yes "RI" and "FI" (Microsoft-ers know what I'm saying here) should always be done with `--no-ff -m "<message>"`.
