### ISSUE TITLE
Enable symbol packages for the CoreFx.NetCoreApp.Private package

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#14594]

**Comment by ericstj** [comment]
Here's what I'm planning:

Instead of "binplacing" to a package location as we do today, instead we will write a text file to the same location.  The text file will contain a list of files that the project wants to include in packaging.  This will cover the binary, symbols, and source.

Then in the Microsoft.Private.CoreFx.NETCoreApp pacakge, instead of including files by wildcard, we'll read all the text files by wild card, then place them in the proper package paths.

**Comment by ericstj** [comment]
We'll still need to think about how we aggregate the symbol packages into the NETCore.App flat packages in core-setup.

@dagood : do you have any pointers for how to fetch symbol packages?

Whatever we do we'll also need to make sure that works for `vertical build, EG: don't exclusively depend on HTTP GET's to nuget feed.  /cc @ellismg

**Comment by dagood** [comment]
There's no common NuGet way, unfortunately: symbol packages are a NuGet feature, but there isn't any typical way to get them back from a server. MyGet only makes symbol packages available through the HTTP GETs you mentioned, and in internal builds that need symbol packages, the first choice is to use a VSTS Drop to transfer them.

There is a potential base case, though: `nuget restore` restores symbol packages as if they were library packages *if* the source feed exposes them. Putting/downloading the symbol packages into a folder and setting that folder as the source feed for a restore would be a simple way to get NuGet to set up the package dir structure for us. One issue is conflicts: `restore` doesn't distinguish between a symbol package and a library package, so we would have to make sure they're isolated. (This gets into the "multiple packages with same id/version" scenario.) I'm not sure if this is worth it over unzipping the symbol packages ourselves.

**Comment by ericstj** [comment]
Does MyGet expose a feed with only symbol packages?

**Comment by dagood** [comment]
They don't, but I could see that being a reasonable ask. We could also publish the symbol packages to an additional feed, if not.

My concern with isolation is mostly about the caches and accidentally poisoning an unrelated build, but I suppose we should be able to trust `--no-cache`.

**Comment by chcosta** [comment]
@ericstj and I discussed this a bit, trying to come up with a solution for providing symbols to the Core.App package that isn't "hacky", w.r.t. source builds.  

Some of the "hacky" solutions we discussed were:
- HTTP GET symbols packages directly from a URL
- grab symbols directly from each repo's build for ingestion into the Core.App package
- use a separate feed source (as @dagood mentions above)
- enable a code path in buildtools where we could toggle adding symbols when packing so that the packages we create in a composed source build carry symbols, but standard packages we publish to myget don't.

The last of those "hacky" solutions sounds the least "hacky", and we should consider it, but...

A less "hacky" solution we discussed was to add symbols to the private packages that we produce today, which are only meant as transportation mechanisms anyways.  For CoreFx, that means adding symbols directly to the Microsoft.Private.CoreFx.NETCoreApp package.  For CoreClr, that means creating private packages which we publish and which Core.App consumes.

@gkhanna79 is not entirely opposed to private packages, but has some concerns with the above plan because it means we are producing another set of packages which are not our product packages and are special cased just for us to do extra things.  That means we produce packages (".nupkg"), symbols packages (".symbols.nupkg"), and private packages (private ".nupkg").  One of his questions was, if we are producing private packages which carry symbols, then why produce symbols packages at all?  I think there are some valid reasons for utilizing supported symbols packages instead of creating separate packages which carry symbols.  For example, if a dev is debugging an issue, we don't want them to have to go manually change all of their package references to now have symbols available.  

I'm certain that there was much discussion before we decided on producing ".symbols.nupkg" packages.  It's worth considering alternatives to those symbols packages before we progress further and also in understanding the pros / cons of producing private packages which carry symbols for core-setup.

/cc @noahfalk @ellismg @gkhanna79 @dagood @ericstj

**Comment by ericstj** [comment]
>  if we are producing private packages which carry symbols, then why produce symbols packages at all

Because the symbol packages are the counterparts for a publicly product package.  Private packages are different, these aren't publicly shipping product packages and don't need to be split.  They are transport-only packages so we can lay them out in a way that makes transport convenient.

**Comment by noahfalk** [comment]
I'm not sure I understand enough of the background to be helpful yet. Is their a brief description somewhere of what the CoreFx.NetCoreApp.Private package is and what problem creating a symbols package for it is attempting to address?

> I think there are some valid reasons for utilizing supported symbols packages instead of creating separate packages which carry symbols. For example, if a dev is debugging an issue, we don't want them to have to go manually change all of their package references to now have symbols available.

I'm not aware that there is any decently supported mechanism for nuget to restore a symbols package right now. Were you thinking that we would be losing out on some scenario we already have or that it would stop us from building that scenario in the future?

**Comment by chcosta** [comment]
@noahfalk, hmm...  This issue diverged slightly from where it originally started.

CoreFx.NETCoreApp.Private refers to the Microsoft.Private.CoreFx.NETCoreApp package which is the private package CoreFx uses as a transport mechanism.

Core.App refers to the Microsoft.NETCore.App which comes out of core-setup and contains repackaged pieces of Microsoft.Private.CoreFx.NETCoreApp and CoreClr.  

So the issue that we're discussing now, is how to produce a Microsoft.NETCore.App symbols package.  ie, we need some way to get symbols from the CoreFx / CoreClr packages.

**Comment by noahfalk** [comment]
Thanks Chris!

> So the issue that we're discussing now, is how to produce a Microsoft.NETCore.App symbols package. ie, we need some way to get symbols from the CoreFx / CoreClr packages.

Assuming we already had a Microsoft.NETCore.App symbols package, who is the intended user of it? (Developers that need to debug? Build processes that will consume the package for some purpose? Something else?)

**Comment by ellismg** [comment]
> Assuming we already had a Microsoft.NETCore.App symbols package, who is the intended user of it? 

From a .NET Core customer's point of view Microsoft.NETCore.App *is* the run-time and framework.  If they want any sort of debugging information for either the runtime or anything in the shared framework, they'd want to consume this symbols package.  There isn't an obvious way to tie components in the Microsoft.NETCore.App package back to whatever NuGet package they may have come from (and in the case of CoreFX, even if you *could* it's unlikely that that package would be provided anywhere since we now view it as a transient package that's only intended to be consumed by the process making Microsoft.NETCore.App)

**Comment by noahfalk** [comment]
> If they want any sort of debugging information for either the runtime or anything in the shared framework, they'd want to consume this symbols package

Thanks that helps. Do you know if there are scenarios today where customers are downloading symbols packages and consuming them as packages? To the best of my knowledge nuget.org won't host such a package and nuget restore won't download it. 

If the individual CoreFX packages are no longer customer facing and now only intended to be transient packages that are published and then immediately re-consumed by the build process presumably you could put all the binaries, symbols, and sources inside the main package?

**Comment by chcosta** [comment]
I think that sounds reasonable.  Then the question turns to how to handle this for CoreClr.  I presume there is a desire to continue shipping stand-alone packages for CoreClr, so do we want to additionally create the transport packages for consumption, or is there another alternative which doesn't require us to produce a new set of packages?

**Comment by noahfalk** [comment]
Ah good point, I think I hadn't quite registered that M.N.App would redistribute the contents of the runtime packages too, so we aren't yet in the case where all the constituent packages are transient, only some of them. I imagine we'd want to have a consistent solution across all the packages, even if a simpler option would have worked for the CoreFX subset.

In that case @dagood's suggestion of a seperate feed (or seperate network share folder if we need this to stay inside corpnet) + a custom nuget restore call sounded pretty good to me. Given that it is a private construction just for our own use presumably we'll optimize based on which one is easiest to implement and maintain over time. I'm guessing the private feed with pre-existing packages is a little easier to stand up, and if we moved to a better solution in the future but 3rd parties still wanted the extra feed its probably not too burdensome to leave in place? Just my two cents.

In the long run I'd love to see nuget support symbol packages in a more first class way, but that will take more design work from the nuget team. They need to figure out when its appropriate to include them in search results, when nuget restore should be downloading them, how to lay them out in package caches, etc.

**Comment by chcosta** [comment]
I think it sounds reasonable to use a separate feed. I wonder if we should move corefx private packages to this separate feed which users can target if they choose to. I'd like to think that nobody has a dependency on the CoreFx private package, but I know that's not true because I have recently made changes which took a direct dependency on that package, so perhaps moving CoreFx private packages is beyond the scope of this (we can ignore that topic for now).

Whether we use existing packages, or create transport packages, there's work involved either way.  I have a couple of concerns that I want to keep in mind.

- I worry that if we create a unique code path for source-builds, it's likely that it will break at some point and nobody involved with the change will know that they broke it.  I realize that largely, there's no way around this because nobody is going to validate a full source build pre-checkin, but you can still catch a large class of issues by ensuring that packages are properly produced from coreclr and published.  That same class of issues would not be caught if you did things one way when building coreclr, and a different way when producing a source-build.  My two-cents here is that if we are going to produce same-named packages for this, then we should do that work with every coreclr build. We'd be publishing a product package and a product / symbols package but pushing to different feeds.  

- I worry about conflicts because those are difficult to track down.   (--no-cache sounds like a nice workaround if everyone knows to use it when mysterious behavior is happening).  This, plus my previous concern, make me think we should just produce differently named transport packages which get published from coreclr to a separate feed and consumed in core-setup.

I do think that the original concern of producing additional packages which in some ways repeat existing behavior, is valid, but without first class support from nuget, we need a current alternative which is sustainable.

**Comment by noahfalk** [comment]
> My two-cents here is that if we are going to produce same-named packages for this, then we should do that work with every coreclr build

I agree. I am assuming that whatever we produce, whether a duplicate package on a new feed or a differently named package, it happens every time.

> I worry about conflicts because those are difficult to track down. (--no-cache sounds like a nice ...

I thought we were proposing that the core-setup project was the only consumer of this, and that would be automated rather than manual which dramatically limits the potential for misuse? I agree that in the event some human attempts to replicate the process in an ad-hoc manner, doing non-standard things increases the chance of error. OTOH specially named transport packages are also a non-standard concept so there seems to be similar risk of getting it wrong in other ways there? 

> This, plus my previous concern

I may have misunderstood, but your previous concern seemed to only argue for being consistent across builds without making any preference for/against differently named packages?

When I think about the risk of someone in the repo making a change that breaks source-build it seems less risky to ask each constiuent repo to publish a package they are already creating to a 2nd feed vs. publishing a new package with its own naming and content guidelines to the 2nd feed. In the first case if they mess up the package build other scenarios will also fail, in the differently named case anything that causes the new package to be mis-built only breaks core-setup.

> make me think we should just produce differently named transport packages which get published from coreclr to a separate feed and consumed in core-setup

Asking every repo build to create an additional package rather than republish one they already built to a new feed seems like a bunch more work to me, but I am not the expect on what is involved. If it turns out that is trivial than feel free to ignore this part : )

**Comment by chcosta** [comment]
> I thought we were proposing that the core-setup project was the only consumer of this
Yes, I worry about the human element. Hopefully this remains just for core-setup use but I don't pretend to know the extent of human creativity.

> When I think about the risk of someone in the repo making a change that breaks source-build it seems...
I'm not certain I follow.  In my mind, for this scenario, the difference between a same named package and a differently named package is semantics.  Either way, the content is going to be different than what the repo is currently publishing.  The only difference is whether we repackage the product with symbols using the same package name or a different package name.  

Train of thought follows...
Thinking that the work involved, in either case, we need to add a switch that allows us to package with or without symbols included and we produce packages twice.  If we repackage with symbols, then we can easily add a prefix to the package name.  So I think that the work involved to create an "additional" package is trivial.  Perhaps I'm underestimating the work involved. In fact, if we don't produce a differently named package, we will have to  consider some other method to prevent package collisions within the build itself, I'd imagine that's something as simple as packaging to a different directory though. Actually, in either case, we should be producing these packages to a different directory so that we can just push that entire directory to a specified feed.  

There is a benefit to producing same named packages with symbols included (which I really like), such that if anybody does just want to consume the packages with symbols, they can intentionally just change their feeds.

All of that leads me to the conclusion that I'm now ambivalent, I think the work involved is nearly identical.

**Comment by chcosta** [comment]
I intend to move forward with enabling same-named packages which include symbols pushed to a separate feed. Enabling developers to switch feeds to choose package content is not an explicit goal. I'll try to enable a solution which allows us to change package namesiff we later desire to (assuming the investment is not large). 

 @noahfalk, I'll sync with you offline to ensure we are aligned

**Comment by chcosta** [comment]
Further discussion has revised the plan slightly (as these things tend to do).

We are going to produce transport packages using the same symbol package mechanisms we use today which will be used for ingestion into Core-Setup.  The packages will go to the same feed as our standard packages.  I'm going to track the details of this plan on an internal GitHub issue, but will revisit this issue once those changes are in place and we are ready to consume the transport packages in Core-Setup / figure out symbol extraction

**Comment by ericstj** [comment]
Removing myself as I believe the plumbing work from CoreFx is done and @chcosta picked up the rest.
