### ISSUE TITLE
Remove dependency to System.Net.WebClient from the DesigntimeLicenseContext type

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/corefx#14695]

**Comment by stephentoub** [comment]
@AlexGhiondea, it looks like WebClient is just used in OpenRead to download the licenseFile, but that only happens if licenseFile is non-null:
https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.TypeConverter/src/System/ComponentModel/Design/DesigntimeLicenseContext.cs#L171
and it's always null.  So is the work here just to delete all of the relevant dead code?

**Comment by AlexGhiondea** [comment]
@stephentoub yes. 

At the time, it was not clear if we were going to bring back the LicenseFile property.

**Comment by AlexGhiondea** [comment]
Thank you @stephentoub
