### ISSUE TITLE
Instructions to work with local coreclr build and API changes on corefx

### ISSUE THREAD

**Issue by xoofx** [dotnet/corefx#14730]
This is related to the work on [collectible AssemblyLoadContext](https://github.com/dotnet/coreclr/pull/8677#issuecomment-269397257) on coreclr and the issue #14724 

I have made changes to `System.Private.CoreLib`  and I would like to add the relevant API changes to `AssemblyLoadContext.cs`  in corefx and add tests against this API, using my local build of coreclr.
So on my branch on corefx, I have started to update `AssemblyLoadContext.cs` with this new API.

But it seems that `BUILDTOOLS_OVERRIDE_RUNTIME` is not taken when performing an APICompat with the API.

We should be able to easily build corefx with a local coreclr and make changes to the ref API to use the new API introduced by the local coreclr.

**Comment by xoofx** [comment]
Found that the build is also downloading some versions from https://github.com/dotnet/versions/tree/master/build-info used later in a [hardcoded metadata](https://github.com/dotnet/buildtools/blob/73375848b73a586a8ac439a1263b605901414ad8/dependencies.props#L44) downloaded through [BuildInfo.Get](https://github.com/dotnet/buildtools/blob/49a09cbaccc39559f12b77566581c97185380d79/src/Microsoft.DotNet.VersionTools/BuildInfo.cs)... 

This infrastructure is making the life of external contributor an absolute pain (and I don't even know how you can work correctly with this system) as I have to go through [tweaking local files in coreclr](https://github.com/dotnet/coreclr/pull/8677#issuecomment-269406391) to try to solve this...

Please, please, don't rely exclusively on online data to allow a build. Local build should have first class support.

**Comment by danmosemsft** [comment]
@xoofx we currently have work in progress to make it easier to exchange changes between coreclr and corefx without going through myget. It is absurdly hard right now as I discovered having joined the team relatively recently. Everyone has their own way and I see that @kouvel offered his own.

Here are some notes I made to myself last time I did it. I'm not writing this up since I'm waiting on the work mentioned.

Figure out where the CoreCLR is that your CoreFX is consuming, from the build log:
C:\git\corefx\packages/Microsoft.TargetingPack.Private.CoreCLR\1.2.0-beta-24628-03\lib\netstandard1.0\System.Private.CoreLib.dll

Version is also listed in dependencies.props in the root of corefx:  <CoreClrExpectedPrerelease>beta-24807-03</CoreClrExpectedPrerelease>

In coreclr root do this:
`build release x64`
`build-packages -BuildNumberMajor=24628 -buildnumberminor=03 -buildtype:release`

Which creates C:\git\coreclr\bin\Product\Windows_NT.x64.Release\.nuget\/pkg/specs/Microsoft.TargetingPack.Private.CoreCLR.nuspec
(which references eg runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR.1.2.0-beta-24628-03.nupkg)

In Corefx root do this:
`Msbuild          /t:BatchRestorePackages /p:OverridePackageSource=C:\git\coreclr\bin\Product\Windows_NT.x64.Release\.nuget\pkg`

Which causes this to run:
`"C:\git\corefx\Tools/dotnetcli/dotnet.exe" restore --no-cache --packages "C:\git\corefx\packages" --source C:\git\coreclr\\bin\Product\Windows_NT.x64.Release\.nuget\pkg --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://www.nuget.org/api/v2/ `

You'll want to delete existing packages if they exist, this will not overwrite them. (c:\git\corefx\packages\Microsoft.NETCore.Runtime.CoreCLR)

This puts it in eg C:\git\corefx\packages\Microsoft.TargetingPack.Private.CoreCLR\1.2.0-beta-24628-03\lib\netstandard1.0\System.Private.CoreLib.dll

You should now be using bits gotten from here
C:\git\coreclr\bin\Product\Windows_NT.x64.Release\System.Private.CoreLib.dll
C:\git\coreclr\bin\Product\Windows_NT.x64.Release\System.Private.CoreLib.ni.dll

So for debugging grab the PDB manually from
C:\git\coreclr\bin\Product\Windows_NT.x64.Release\PDB\System.Private.CoreLib.pdb
C:\git\coreclr\bin\Product\Windows_NT.x64.Release\PDB\System.Private.CoreLib.ni.pdb

**Comment by danmosemsft** [comment]
@karelz in case he has another way.

**Comment by xoofx** [comment]
@danmosemsft the process described by @kouvel is almost working. Now I'm getting errors on other packages that are expecting some stuff on coreclr that I don't have. Where can I find the associated commit between a corefx and coreclr repo? From the [dotnet/versions](https://github.com/dotnet/versions/tree/master/build-info/dotnet/coreclr/master) I only get package number.

**Comment by xoofx** [comment]
rebasing on latest corefx hopefully should fix my issue...

**Comment by xoofx** [comment]
> we currently have work in progress to make it easier to exchange changes between coreclr and corefx without going through myget. 

@danmosemsft glad to learn that this is being work out 👍

**Comment by xoofx** [comment]
@danmosemsft yeah, incidentally I discovered this recently ;)
I was more talking about having this commit id stored in a git repo instead.

Wondering why not use something like git submodules with a top level repo containing `coreclr` and `corefx`? The purpose is somewhat similar to what is doing [dotnet/versions](https://github.com/dotnet/versions) but using submodules would at least automate the process of checking out and verify commit ids when pushing... (though maybe PR there would be difficult...)

**Comment by danmosemsft** [comment]
@xoofx I know the folks doing this considered submodules but last I heard they weren't going in that direction. I haven't used submodules myself but I understand they have some limitations that can cause confusion. Last I heard that are going to remain side by side repos but building one will publish locally to the other. Hopefully when this is done there will be a doc or blog post.

**Comment by ViktorHofer** [comment]
Closing for age. This doesn't apply anymore to master. Making changes in coreclr and transport them over to corefx is now easily possible with https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md#testing-with-private-coreclr-bits
