### ISSUE TITLE
Unable to read appsettings.jason data from Class Library

### ISSUE THREAD

**Issue by AnithaLingam** [dotnet/corefx#14814]
I am creating Class Library and in this I have to read configuration settings from Appsessting.Jason file but I am unable to read the data ,Please provide solution

I have tried with adding reference to "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0" but it is throwing error.

**Comment by jnm2** [comment]
@AnithaLingam Heads up, you're more likely to be helped if you provide all the details you can of the error message.

**Comment by karelz** [comment]
Do you mean AppSettings.json file? (vs. .jason?)
What prevents to use any .json parser?
If you have troubles with the class above, then it would be best to ask on ASP.NET Core repo, where [it lives](https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.extensions.configuration.configurationextensions).

Otherwise, we need (minimal) repro to be able to help.

**Comment by tarekgh** [comment]
yes this issue should be moved to https://github.com/aspnet
