### ISSUE TITLE
System.Private.Xml not Building Assembly for UWP

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#14935]
System.Private.Xml.dll is not supporting uap101aot.

**Comment by sepidehMS** [comment]
AFAIK supporting UWP on System.Private.Xml is part of the .NET Standard 2.0 UWP effort which is under plan and discussion. +@weshaggard who can give more context on the timeline and planning.

**Comment by weshaggard** [comment]
@shmao can you help me understand why you need it right now? We do plan to start supporting it but it isn't currently funded.

**Comment by shmao** [comment]
@weshaggard Sure, the reason I opened the issue is because we are making WCF to consume some 2.0 APIs (see https://github.com/dotnet/wcf/issues/1726 and https://github.com/dotnet/wcf/issues/702). The fix for WCF wouldn't work on UWP due to this issue.

**Comment by weshaggard** [comment]
I just chatted with @zhenlan about this so he knows more details but for now you will not be able to consume the new APIs UWP yet.

**Comment by danmosemsft** [comment]
@joperezr has this in progress already

**Comment by jkotas** [comment]
https://github.com/dotnet/corefx/issues/15809 may need to get fixed as part of this.

**Comment by weshaggard** [comment]
@joperezr is this complete?

**Comment by joperezr** [comment]
It's definitely building for uapaot vertical now, but it doesn't have a special configuration for it, since it's just reusing the uap implementation. From what I can tell, it is building against contracts and we don't seem to have invalid PInvokes so I believe that should be enough but let me know if we want to add a specific uapaot configuration for it. I'll close this for now.
