### ISSUE TITLE
Enhanced styling for System.Console

### ISSUE THREAD

**Issue by tomakita** [dotnet/corefx#14966]
It would be cool if System.Console were to support writing to the console using any RGB color and in predefined styles.  For examples of usage, see [Colorful.Console](https://github.com/tomakita/Colorful.Console/blob/master/README.md).  The idea is to keep current System.Console behavior invariant while adding extra functions to its interface that enable enhanced styling.  

I have no idea if this is the kind of contribution you're interested in, but I figured I'd ask!

**Comment by karelz** [comment]
I assume it would require new APIs, right?
What is the downside of leaving it as external wrapper around Console? In other words: What are the benefits to bring it into Console class? (just trying to understand the motivation and all options, please don't treat it as push back)

**Comment by tomakita** [comment]
Good question.  

The benefit that I have in mind is convenience.  The core of the proposed functionality is the ability to color text using any RGB color, as opposed to the 16 colors that the System.Console class is currently limited to.  This enhancement wouldn't necessarily make System.Console's API much more complicated.  Here is one way it could be implemented which would change System.Console's API only slightly -- Console.ForegroundColor would be a System.Drawing.Color rather than a System.ConsoleColor:

`Console.ForegroundColor = System.Drawing.Color.Pink;`
`Console.WriteLine("...");`

This seems like a nice gain in functionality, given the risk involved, and it would mean that developers wouldn't have to get the Colorful.Console NuGet package every time they create a new Console project if all they want is more colorful text.  For contrast, here is another way in which this could be implemented -- this is the way that Colorful.Console does it.  The color to be used for writing is supplied as an argument to the Write and WriteLine methods.  This would involve adding the appropriate overloads for Write and WriteLine:

`Console.WriteLine("...", System.Drawing.Color.Pink);`

The other salient methods exposed in Colorful.Console don't really have analogs in System.Console.  These methods are:

`Write/WriteLineFormatted` (colors specific substrings of a string individually)
`Write/WriteLineAlternating` (writes strings in alternating colors based on some predicate)
`Write/WriteLineStyled` (colors strings by pattern matching)
`WriteAscii` (writes ASCII art using the FIGlet program)
`WriteWithGradient` (colors strings with a gradient from left to right)

It may be more risky to add these to the System.Console API since they would be relatively large additions.  Speaking of risk, support for RGB colors is implemented in Colorful.Console by P/Invoking Win32's kernel32.dll.  I'm not sure how realistic it will be to support this on Mac and Linux.  

Anyway, thanks for taking a look at this.  You can never have too much color in your console!

**Comment by jnm2** [comment]
@tomakita 

> The core of the proposed functionality is the ability to color text using any RGB color, as opposed to the 16 colors that the System.Console class is currently limited to. 

I'm sorry to point this out, but all it's doing is manipulating a 15-color palette. From https://github.com/tomakita/Colorful.Console/blob/master/README.md#usage-notes:

> Colorful.Console can only write to the console in 16 different colors (including the black that's used as the console's background, by default!) in a single console session. This is a limitation of the Windows console itself (ref: MSDN), and it's one that we weren't able to work our way around. If you know of a workaround, let us know!

> This enhancement wouldn't necessarily make System.Console's API much more complicated.

Managing a palette becomes much more complex than simply taking a dependency on `System.Drawing` and exposing `Color`. What happens if you try to use 17 colors? Do you live with the previous characters turning random colors or do you merge two palette colors try to go back and write them using the merged palette index?

Because of the whole limited palette aspect, it seems too experimental for BCL. :-(

**Comment by mikedn** [comment]
If something is done in this are then that something has to be:
- somehow expose RGB color support on Linux since newer Linux terminal has support for that
- have the Windows implementation optionally enable and use escape sequences on Windows 10 Anniversary Update and newer, that will give you RGB color support on Windows as well

Any other workarounds and improvisations in this area are a complete waste of time.

**Comment by ianhays** [comment]
>It may be more risky to add these to the System.Console API since they would be relatively large additions. 

I tend to agree that this kind of thing is probably out of scope for what we want in CoreFX and would be more fitting as a secondary library e.g. ColorfulConsole, partially because of the reasons mentioned above and partially because the API would be a large addition to what is currently a relatively small API. I'm not at all against its inclusion, but the use cases and need would have to be big enough to justify it, and I'm not certain that is the case.

**Comment by tomakita** [comment]
These are good points.  With this in mind, maybe this is not necessarily a worthwhile enhancement right now.  Thanks for the feedback!

**Comment by karelz** [comment]
Closing per discussion above.
