### ISSUE TITLE
How obtain Process.GetCurrentProcess().Handle?

### ISSUE THREAD

**Issue by jmroyb** [dotnet/corefx#14976]
Hi folks!

I'm building a netstandar1.5 lib and I have downloaded System.Diagnostics.Process v4.3.0 from Nuget, but method .Handle is missing. I try to call this code which works fine in Framework 3.5:

```c#
        [DllImport("kernel32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        static extern bool IsWow64Process([In] IntPtr hProcess, [Out] out bool lpSystemInfo);

        internal static bool IsWowProcess()
        {
            var retVal = false;
            IsWow64Process(Process.GetCurrentProcess().Handle, out retVal);     //missing Handle!
            return retVal;
        }
```

Thanks a lot !

**Comment by stephentoub** [comment]
@jmroyb, for .NET Core 1.x, a bunch of members logically considered obsoleted (even if not marked as obsoleted) were removed.  That included Process.Handle (though it's since been added back for .NET Core 2.0).  It was considered obsoleted by Process.SafeHandle, which provides the same functionality but with the handle wrapped in a SafeProcessHandle, which makes it more reliable to work with.  You should be able to simply change your IsWow64Process signature to take a SafeProcessHandle instead of IntPtr, and pass in process.SafeHandle instead of process.Handle.  Alternatively, you can get the IntPtr out of the SafeProcessHandle by calling its DangerousGetHandle method; as you can see at https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs#L139, that's exactly what the Process.Handle property does, anyway.

Hope that helps.

**Comment by stephentoub** [comment]
@jmroyb, I've closed the issue as I believe my answer addresses your question.  If it doesn't, please reopen. Thanks.

**Comment by jmroyb** [comment]
Hi Stephen, thanks for your answer. It worked
