### ISSUE TITLE
CI running really long

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#1515]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/980/console
I'm not sure on which test it is being stuck (xunit seems to mix output when running tests in parallel - or is it us running commands in parallel?). Anyway running tests for more than 2h sounds a little too much considering that previous run took less than an hour.

**Comment by hpshelton** [comment]
Multiple other builds are stuck "Restoring build tools...", so I think something has generally gone wrong with the agents in question (dci-win-fbld-[2,3,5,6,7]).

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_mac_release_prtest/488/console
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/981/console

**Comment by mmitche** [comment]
@krwq Not sure about your specific job but still seeing some timeouts due to the Linux corefx tests (the timeout is set at 2 hours currently).  @stephentoub We got a couple non-timed out builds but the latest timed out again :/

There is also still occasions when dnx.exe is hanging with a race condition, which is what was happening for your links, @hpshelton.  I think the machines themselves are okay.

**Comment by stephentoub** [comment]
> We got a couple non-timed out builds but the latest timed out again :/

This is something different; the thing that was hanging before is now completing. Do you have a machine that's still hung, or is it reproable?
