### ISSUE TITLE
Purpose of net46 AclExtensions

### ISSUE THREAD

**Issue by marek-safar** [dotnet/corefx#15156]
What's the purpose net46 AclExtension files in CoreFX repo ? They expose different API then their CoreFX/netstandard counterparts and missing quite few checks.

One example is https://github.com/dotnet/corefx/blob/296dc18f32e718280794becd8eccc67aab50251b/src/System.Threading.AccessControl/src/System/Threading/ThreadingAclExtensions.net46.cs

**Comment by karelz** [comment]
@kouvel can you please chime in?
It seems that net46 tries to be fully compatible with Desktop behavior (likely also on Mono), but in .NET Core we do not want the implementation in corlib, we want to keep it in CoreFX. I may be wrong ...

**Comment by marek-safar** [comment]
The implementation is in mscorlib but the public API this new type exposes is different for net46 and netstandard. Secondly the implementation is worse in net46 as it crashes with NRE on null arguments value.

**Comment by weshaggard** [comment]
The reason for the extensions was because we didn't have the ACL APIs on the core types as ACLs aren't part of .NET Standard. So we provided some extension methods to fill the gaps in scenarios so folks could still use ACLs but on top of the core assemblies instead of requiring them in the core assembly. These extensions for net46 should just call the inbox APIs in mscorlib.

**Comment by marek-safar** [comment]
Right but why net46 API is not using `this` even if the type is called Extension and it's not doing any arguments checks ?

**Comment by weshaggard** [comment]
That is a good question. It should probably be using this and in that case it shouldn't be doing argument checking.
