### ISSUE TITLE
Win32FileStream buffer-full flushes are also done in a blocking fashion

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1531]
Win32FileStream flushes its buffer synchronously from the caller's perspective, even when using WriteAsync.

**Comment by WalkingCat** [comment]
well, well, does it mean WriteAsync is actually seldom performing actual async IO ? unless you have a very small buffer size. does it mean buffered stream and async io are incompatible and mutually exclusive ? btw why I can't set buffer size to 0 to indicate a non-buffered FileStream ?

**Comment by stephentoub** [comment]
> why I can't set buffer size to 0 to indicate a non-buffered FileStream ?

You can set it to 1.  That's effectively the same thing.

> does it mean WriteAsync actually seldom performing actual async IO ?

For writes with sizes less than the internal buffer size, that appears to be the case.  Eric can correct me if I'm misreading things.

**Comment by WalkingCat** [comment]
I guess buffer can only be flushed synchronously in some cases because there is no way to return this Task to caller, semantically the user expect the returned Task to express the state of IO operation for the data passed as argument, if the data can not fit into current buffer, then there is no way to combine these two IO operations (buffer and data) into one return value. right ?

**Comment by stephentoub** [comment]
That shouldn't be a problem.  WriteAsync returns a Task, which represents the entire writing operation, even if such operation was multiple actual writes to the OS.

**Comment by Maxwe11** [comment]
For fixing this issue `Task FlushWriteAsync(bool)` should be implemented and used in other *Async methods where it could be `await`-ed ?

**Comment by tymlipari** [comment]
So if I'm reading the code correctly, the issue is that in cases where the internal buffer would overflow by the incoming write, it synchronously flushes the buffer and then immediately writes the incoming data out to the OS/disk (albeit that part is asynchronous).

Is the desire to have a WriteAsync perform only a single write operation? If not, it should be sufficient to chain the incoming write to the flush operation ala something like:

`return FlushWriteAsync().ContinueWith(WriteInternalCoreAsync(...));`

Though that might be more expensive than simply allocating a temporary array that contains the existing buffer + the incoming write and combining them into a single call to WriteInternalCoreAsync.
