### ISSUE TITLE
FileStream constructor should allow bufferSize = 0 to indicate non-buffered stream

### ISSUE THREAD

**Issue by WalkingCat** [dotnet/corefx#1533]
FileStream.Init will throw ArgumentOutOfRangeException if (bufferSize <-0), IMHO it should allow bufferSize = 0 value, indicating this FileStream object nerver uses buffer on this level, provides more flexibility and control for app developer, current workaround is set bufferSize to 1, which is ugly.

**Comment by stephentoub** [comment]
> current workaround is set bufferSize to 1, which is ugly

Can you clarify why that's ugly?

**Comment by WalkingCat** [comment]
because it still has possibility to allocate memory for buffer array when Read/Write actually called with argument numBytes = 1, its not guaranteed non-buffered.

**Comment by stephentoub** [comment]
Right.  I was just clarifying that your concern is purely around a byte[1] getting allocated per FileStream; there's no other difference you're concerned about, right?

**Comment by WalkingCat** [comment]
its not just about memory allocation, buffering can affect the behavior/logic, like at what moment the native IO calls are actually called etc, when I say I want a non-buffered stream, I expect exactly non-buffered behavior, otherwise its suprising.

**Comment by stephentoub** [comment]
I agree that if that were the case, it would be troubling to claim that it never uses the buffer.  I'm missing from the code where that's happening, though.  If the buffer size is 1, then any attempt to write any amount of data will skip the buffer, due to checks that the amount of data is greater than or equal to the buffer size.  Is there something in the code I'm missing where that's not the case?  Can you help me by pointing to a specific example?  It may very well be there, I'm just missing it.

**Comment by stephentoub** [comment]
Actually, on closer look I do see that happening in the async code path here https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/Win32FileStream.cs#L1384.  I don't see it happening in the sync code path.

**Comment by WalkingCat** [comment]
yes I was talking about WriteInternalAsync, it looks like sync methods handle buffering subtly differently, which is just weird implementation details and should not be relied on anyway.

**Comment by stephentoub** [comment]
Right.  So my top-level point is that if/when https://github.com/dotnet/corefx/issues/1530 is fixed such that the async-buffering behavior matches the sync-buffering behavior, then this request is really about   a slight usability benefit (being able to say 0 instead of 1 but to effectively mean the same thing) that also avoids a byte[1] array allocation per FileStream, correct?  I'm not trying to downplay the benefits, just quantify them.

**Comment by WalkingCat** [comment]
correct. but now I feel #1530 is meaningless given #1531 could be difficult to fix, but this should be discussed there.

**Comment by karelz** [comment]
Looks like it would be compat issue and the benefit is rather small. There are decent workarounds (bufferSize=1). Closing, feel free to reopen if I got it wrong.
