### ISSUE TITLE
Should FEATURE_RANDOMIZED_STRING_HASHING be set in corefx

### ISSUE THREAD

**Issue by FiveTimesTheFun** [dotnet/corefx#1534]
For collection types in coreclr, we use randomized string hashing above a threshold.  This is guarded with the feature define FEATURE_RANDOMIZED_STRING_HASHING.  If we use the same behavior in corefx for types including HashSet<T> and HashTable, we need to port its supporting code.

**Comment by ellismg** [comment]
We should do this.

**Comment by krwq** [comment]
I believe we should do it ASAP.

**Comment by mellinoe** [comment]
Which projects need to define this?

**Comment by ellismg** [comment]
In the full .NET framework, we use this in the collections types, so the generic, non-generic and concurrent collections should all be audited.

**Comment by ellismg** [comment]
Thanks, Josh.

**Comment by ellismg** [comment]
/cc @stephentoub 

I am not sure that we actually need to do this. When we added FEATURE_RANDOMIZED_STRING_HASHING to Desktop CLR, we were unable to actually change the default of string's GetHashCode function to preform randomized hashing, for compatibility reasons. So we added the above feature which would cut over to Randomized Hashing after a threshold, if we detected a lot of collisions and you were using a "well known" comparer type.  The thinking here was that in these cases you were under attack and we were okay to take the compat break of different ordering in the hash table in order to mitigate the attack.

On CoreCLR, randomized string hashing is enabled by default.  Therefore the cut-over is less interesting.  It's still useful as it provides per collection entropy in these cases and is mixed with the AppDomain wide seed, but given that we already have randomized string hashing and any work we did here wouldn't help custom collection types or folks using custom compares plus the engineering cost of adding it is non trivial (since all the hashing is done in the VM itself) it seems like what we have is good enough.

My recommendation is that we don't add this feature back.  The incremental improvement isn't wotht the cost we'd pay.

Thoughts?

**Comment by stephentoub** [comment]
I'm fine with that recommendation.

**Comment by ellismg** [comment]
Thanks Steve, Closing.

**Comment by weshaggard** [comment]
cc @tarekgh
