### ISSUE TITLE
Cleanup: remove empty try's

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#15411]
We have about 20 instances of `try { }`

See https://github.com/dotnet/coreclr/issues/8924. 

The PR https://github.com/dotnet/coreclr/pull/8949 makes sure they are not represented in generated code so this is just minor code cleanup.

**Comment by benaadams** [comment]
Can they be removed in corefx? e.g. can corefx be used over a runtime other than coreclr that has ThreadAbort?

**Comment by danmosemsft** [comment]
I was assuming CoreRT/PN (and CoreCLR) do not, and those are the only contexts for CoreRT. @jkotas can you confirm? I don't think we've been maintaining these or considering thread aborts when working on CoreFX.

**Comment by jkotas** [comment]
They can be removed in netcoreapp-specific parts. 

We may want to preserve them in parts that target netstandard because of those parts can run on runtimes that have thread abort. But I would not go out of our way to explicitly harden these parts for threadabort (it is super expensive to do it right).
