### ISSUE TITLE
Remove calls to Contract methods/or change to Debug.Assert as appropriate

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#15443]
There are a bunch of calls to `Contract` methods in corefx: see [gist][1]. Since CONTRACTS_FULL is not defined and the contract rewriter is not used, it's dead code. All methods that assert something (such as `Ensures`) should be replaced with asserts where practical, and all calls to `EndContractBlock` can be deleted.

Context for this issue: https://github.com/dotnet/corefx/issues/11596#issuecomment-274986502

**Comment by karelz** [comment]
@weshaggard @stephentoub do you have background on these?

**Comment by weshaggard** [comment]
See https://github.com/dotnet/corefx/issues/503. Where we had the reverse conversation a while back. In general we didn't go back in and clean these out because we were trying to share code with other places. However even in those other places we no longer run any static analysis tools nor do we enable CONTRACS_FULL, so it really is dead code. The one potential drawback to removing these is they might be useful if we were to ever convert to a hypothetical language feature in the future. Even in that case I don't think they would add much value. 

I would be supportive of cleaning these out but I would defer that decision to @karelz and @danmosemsft. If we were ever to try and merge sources it would likely cause more diff/merge noise but I suspect we are already deeply into that problem anyway.

**Comment by danmosemsft** [comment]
Are there any we can convert into Debug.Assert, to help catch bugs? 

Eg stuff like
`Contract.Assert(0 <= providerInstance->NextOffset && providerInstance->NextOffset < buffSize);`
`Contract.Requires(writer != null);`

I'm not sure about these, are they useless without an analysis tool?
`Contract.Assume(s_EmptyField.IsEmpty);`
`Contract.Ensures(Contract.Result<IBuffer>() != null);`
`Contract.Ensures(Contract.ValueAtReturn(out sign) == +1 || Contract.ValueAtReturn(out sign) == -1);`
`Contract.Ensures(Count == Contract.OldValue(Count) - 1);`

**Comment by danmosemsft** [comment]
@jkotas also

**Comment by karelz** [comment]
Thanks @weshaggard!

> convert to a hypothetical language feature

What do you mean by that?

Given that we are already deep on the path of source code divergence with other products (Desktop), I don't see harm in cleaning up these as well. IMO it is a decision we already made (incl. accepting the risk that we might regret it one day, potentially paying the cost to "undo it"), so let's stick to the decision fully. There is no point to be half-way in.

**Comment by jkotas** [comment]
I am fine with cleaning these up. Most of them are bit-rotten bits of the original annotations. No value in keeping them around.

The one exception is `System.Collections.Immutable` project. It is using these annotations very consistently. I think it may be worth keeping them there, as a form of internal documentation at least. I would leave it to @AArnott to make the call about these annotations in `System.Collections.Immutable` project.

**Comment by karelz** [comment]
cc @ianhays

**Comment by jkotas** [comment]
> > convert to a hypothetical language feature
> What do you mean by that?

https://github.com/dotnet/roslyn/issues/119

**Comment by danmosemsft** [comment]
Meaning all `Contract.Assert` if we converted to `Debug.Assert` would fail/be incorrect?

**Comment by jkotas** [comment]
Converting `Contract.Assert` or `Contract.Assumes` to `Debug.Assert` should be pretty safe operation. 

`Contract.Ensures` is the tricky one to convert. You would need to move from the top of the method to the bottom of the method as part of the conversion. And the conditions asserted by it are typically a pretty low-value ones, so it is probably not worth converting in number of cases.

**Comment by weshaggard** [comment]
We did a pass to convert all Contract.Asserts to Debug.Asserts (https://github.com/dotnet/corefx/issues/682) a while ago and that is our general guideline in the repo so if there are more we should convert those. For the other Contract calls we should probably just remove them.

**Comment by danmosemsft** [comment]
Looks like there's still about 70 of the .Asserts mostly in a couple of contracts. OK I'll create an issue to convert those.

As part of removing the rest, we will be preventing any new ones.

**Comment by stephentoub** [comment]
> Looks like there's still about 70 of the .Asserts mostly in a couple of contracts

We should not remove the ones that are:
- In the Contracts tests: those are left because, well, they're testing the APIs
- In System.Diagnostics.Tracing, at least not before talking with @davmason: I'd previously removed these, and then he switched back to Contract.Assert because this code file is being copied between multiple repos

Besides those, looks like there may be a handful of recently added stragglers, but not much.

**Comment by davmason** [comment]
I am no longer owning EventSource, I have been answering questions while @brianrob was out, but now he is back and can take over.

**Comment by AArnott** [comment]
Thanks, @jkotas. I don't object to their removal from system.collections.immutable. I suspect I put them there to begin with because at the time I wrote the library originally, I was a Believer in ccrewriter.exe. I'm not any more, so fire away.

**Comment by Genbox** [comment]
@AArnott can you elaborate why you think static code analysis, Code Contracts in particular, is not worth believing in?

**Comment by AArnott** [comment]
@genbox I haven't followed code contracts for several years so forgive me any ignorance in my response. When I used code contracts, especially with ccrewrite.exe, I found it lagged behind the compiler in capabilities, and dangerously so. For example, when generator methods first came out, any code contract at the top of those methods would malfunction (I don't remember how) because the rewriter wasn't prepared to recognize and correctly deal with how the compiler converted that method to a whole state machine. And the malfunction was not caught by the build -- it caused runtime errors. This became a repeated pattern. Even when ccrewriter.exe was "fixed", it would inevitably happen again. And again. The [active issues on the rewriter today](https://github.com/Microsoft/CodeContracts/issues) suggest the pattern hasn't changed.

So while I very much like the idea of code contract enriched interfaces, I think I'll personally wait for it to be a properly supported compiler feature rather than a bolt-on IL rewriter. 

In fact generally, I distrust *any* IL rewriter tool. There are some popular ones out there. And from what I've seen if you look at their active Issues, there are never an end to "it malfunctions in case X" issues. I want code contracts to make my life easier -- not harder.

**Comment by Genbox** [comment]
@AArnott In that case, I would agree. Personally, I find Code Contracts to be an invaluable tool and it is detrimental to the whole community that it does not work with VS2017 and Roslyn. I think you are right in that it is because IL rewriting is so difficult to work with.

C# has moved a lot the past couple of years and has become a giant of a language that supports just about every little feature you could want, which makes IL rewriting even harder. There is even a proposal to add contracts directly [to the language](https://github.com/dotnet/csharplang/issues/105). What do you think about that?

**Comment by AArnott** [comment]
I agree with the sentiment that non-nullable ref types will help. But there are all the millions of APIs that already exist that would not benefit from that and code contracts could help with. So yes, I'd like to see something become part of the language.
