### ISSUE TITLE
Bootstrapping for new platform

### ISSUE THREAD

**Issue by hseok-oh** [dotnet/corefx#15503]
As commented at https://github.com/dotnet/corefx/issues/15215#issuecomment-275299116, CoreFX build needs CoreCLR & core-setup nuget packages. And core-setup build needs CoreCLR & CoreFX nuget packages. 

We can build CoreCLR without target platform nuget packages dependency. But CoreFX and core-setup have target platform nuget package dependency for each other. This circular nuget package reference makes confusion and difficulty on implementation & building for new platform (ex. arm32/linux).

@jyoungyun @chunseoklee @hqueue
@ericstj  @weshaggard @gkhanna79

**Comment by gkhanna79** [comment]
CoreFX product build should not need the Host packages since Core-Setup repo is higher in layering  from CoreFX.

The is an infra issue that needs to be fixed in CoreFX. @weshaggard I am assigning this to you to drive this ahead at the earliest to enable bringup of Arm32 for Linux.

**Comment by ericstj** [comment]
@ellismg is teasing out these things as part of build-from-effort.

As I mentioned in the other thread, it isn't the product build of CoreFx that depends on it, it's test.

**Comment by gkhanna79** [comment]
Is there a way to not build tests when product build is issued? Also, wouldnt this circular dependency be an impediment for bringup?

**Comment by ericstj** [comment]
> Is there a way to not build tests when product build is issued?

Yes, in fact its the default when running ./build.sh.  Its just blocking right now if it can't find the host package, but that can be safely ignored if you aren't running tests.  I want to make it clear that there's a workaround here already and folks shouldn't be blocking progress on this.

> Also, wouldnt this circular dependency be an impediment for bringup?

@gkhanna79 that depends on when you run the tests.  Suppose you've run them after you've built the entire vertical.

I'm not saying we should close this issue, we should definitely have some steps for bringing up a new platform without having a core-setup build (that don't involve commenting stuff out).  Folks have already decided we derive significant benefit from testing with the shipping host rather than a test-only host, which is why we've accepted the repo cycle as a tradeoff.  Perhaps in the long-run it'd be better to move the host lower in the stack...

**Comment by ellismg** [comment]
> Perhaps in the long-run it'd be better to move the host lower in the stack...

FWIW, I think this is something we'll want to do long term.  The fact that it lives in core-setup which is primarily focused on actually building a shipable product is an artifact about how the repositories and product evolved, not something we intentionally wanted, IMHO.  I think we also have some circular dependencies between CoreFX and CoreCLR today and I'd like to figure out a way to solve that as well.

**Comment by weshaggard** [comment]
@hseok-oh @gkhanna79 what are you guys looking for with this issue? Would a command line option to build.sh/cmd that disables the restoring of external packages and setup of the test layout be enough?

**Comment by gkhanna79** [comment]
@weshaggard Yes, that should be fine.

**Comment by weshaggard** [comment]
@hseok-oh @gkhanna79 after looking at this a little while I don't think we can do it without further work because we use the CoreCLR package for more then just testing. We use it for building some of our corefx libraries as well. For building we don't need an exact matching architecture just a System.Private.CoreLib.dll to reference so it could really be any. So I think the best workaround is to continue to do what we have been doing and just override the RuntimeIdentifier for new platform bring-up to point it at another existing RID. 

With that I'm going to close this but please let me know if still feel like we need some other solution.

**Comment by gkhanna79** [comment]
@weshaggard Why does CoreFX build reference an implementation assembly and not a contract corresponding to it?

**Comment by weshaggard** [comment]
>@weshaggard Why does CoreFX build reference an implementation assembly and not a contract corresponding to it?

We don't have a contract form of System.Private.CoreLib which we have a number of facades we build in corefx that need that need to type-forward things down to System.Private.CoreLib. We could create a ref for that but I would prefer not doing that.

**Comment by hseok-oh** [comment]
I understand we need System.Private.CoreLib.dll that is generated in CoreCLR to build CoreFX. That's fine. But at least, we need to support that new contributers can build correct CoreCLR + CoreFX set for new target platform(architecture). Can we confirm that there will be no the correctness problem in CoreFX build wth overriding another existing RID? How can they do CoreCLR & CoreFX test in target machine? 

If we cannot remove restore process, it seems to need a document to guide this scenario.

**Comment by weshaggard** [comment]
>If we cannot support disabling restore process, it seems to need a document to guide this scenario.

Agreed I will reopen this and try to at least add some documentation.

**Comment by weshaggard** [comment]
@hseok-oh in order to help me document how to do this can you help me better understand the scenarios you want to work here? Looking at the workaround in https://github.com/dotnet/corefx/pull/16139/files it seems like you could have got everything in corefx building by building the native and managed code separately. Instead of calling `build.sh -buildArch=armel` which is what I assume you guys were doing you could instead just call `build-native.sh -buildArch=armel`, to get the native builds correct and then `build-native.sh -buildArch=x64` to get the managed builds correct. None of the IL in corefx is architecture specific so it only uses the arch parameter for setting the RID for pulling down the external dependencies. 

Let me know if you think that would satisfy your needs and I will add it to one of our docs.

**Comment by hseok-oh** [comment]
@weshaggard Looks good. And it seems better to add the explaination where is the build result in. For example, result of native build is in `bin/runtime/netcoreapp-Linux-Debug-armel`, and the result of managed build is in `bin/runtime/netcorea-Linux-Debug-x64` with x64 CoreCLR and x64 native build result.

**Comment by hseok-oh** [comment]
@weshaggard @jyoungyun By the way, how about circular reference between CoreFX and core-setup packages? Is it cleared in build process and have no problem by using this (#16139) approach?

**Comment by weshaggard** [comment]
Which circular dependency between corefx and core-setup are you referring to?

**Comment by weshaggard** [comment]
I guess you are referring to the dependency on the host which I will have to let @gkhanna79 speak too. Do you only need the host for getting tests runs going or is it needed for other purposes?

**Comment by hseok-oh** [comment]
@weshaggard need host only to build test, may not run.  I found we can avoid circular reference between corefx and core-setup using #16139 too. So never mind my comment about core-setup

**Comment by weshaggard** [comment]
Can you verify if my instructions in #16384 also allow you to avoid that? As I'm undoing #16139 with that PR as well.

**Comment by jyoungyun** [comment]
@weshaggard If you want to remove my workaround code, I think we need to add some comments about runtime directory. First, if we build CoreFX as your guideline, the managed build will not succeed because we can't find the x64 native part in the packaging process. So I think we need to add `-BuildPackages=false` option to managed build command line. And to run CoreFX unittest, we need a runtime directory but in this case the 'netcoreapp-Linux-Debug-armel' directory does not work well due to lack of managed files so we have to add some comments to copy managed dll from 'netcoreapp-Linux-Debug-x64'.

**Comment by weshaggard** [comment]
>the managed build will not succeed because we can't find the x64 native part in the packaging process. 

I just fixed that with PR https://github.com/dotnet/corefx/pull/16390 earlier today. 

>And to run CoreFX unittest, we need a runtime directory but in this case the 'netcoreapp-Linux-Debug-armel' directory does not work well due to lack of managed files.

Yes running tests is another set of problems that need to be solved. Not only are you missing the managed files but you need the matching native assemblies from the coreclr repo as well as the native dotnet host in order to run the tests for armel. However if you would like further clarifications in the docs please leave a note in the PR #16384 and I will try and incorporate them.

**Comment by jyoungyun** [comment]
@weshaggard I missed your commit (#16390). Sorry. And I add some comments to #16384. Thanks.
