### ISSUE TITLE
Figure out the set of CI legs we should run by default on each PR

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#15635]
Today we run various OS's, Architectures, and flavors (Debug/Release) on every PR. I think we should figure out the best set of combinations to get the most bang-for-the-buck in our PR CI system. For example I would not suggest we do Debug/Release for all OS's we should mix and match. 

To see the discussion here is what I would suggest:

Windows - Debug - x64
Windows - Release - x86
OSX - Debug - x64
Ubuntu - Release - x64
CentOS - Debug - x64
PortableLinux - Release - x64

That should give us a decent combination without trying to test the full matrix of configurations.

**Comment by stephentoub** [comment]
> To seed the discussion here is what I would suggest

I suggest we include both debug and release for macOS:
- Some of our assemblies are specialized for macOS separate from Linux
- We've had multiple issues in the past where native builds pass on debug but fail on release due to warnings and the like that only occur in release, e.g. args that were used in debug but not in release resulting in unused argument warnings that are treated as errors

The rest of the suggestion looks reasonable.

**Comment by karelz** [comment]
cc: @danmosemsft @mellinoe

**Comment by karelz** [comment]
Where is current matrix? I thought we were discussing even the rolling [builds & tests](https://github.com/dotnet/corefx#build--test-status).

**Comment by stephentoub** [comment]
> Where is current PR validation matrix?

It's listed at the bottom of every PR.  (Windows_NT + Ubuntu14.04 + CentOS7.1 + macOS) x (Debug + Release)

> I thought we were discussing even the rolling builds & tests.

This PR is titled "Figure out the set of CI legs we should run _by default on each PR_"

**Comment by karelz** [comment]
> This issue is titled

I know - that's why I'm trying to ask about impact and overall VM resources optimization. Where do we spend most VM time - in per-PR CI or the rolling CI?

**Comment by weshaggard** [comment]
I believe the per-PR is where we spend most of our CI budget because it resins on every commit pushed to any branch that is under PR. 

>I suggest we include both debug and release for macOS:

I'm OK with doing debug and release for OSX I suggested only one because I know that the Mac resources are generally the long pole for many CI runs so I thought it might be better to have it only hit once per-PR.

**Comment by weshaggard** [comment]
Also I would suggest we have a more complete matrix like we do today for the rolling CI.

**Comment by danmosemsft** [comment]
What is the problem we are trying to solve -- CI seems to be working pretty smoothly to me and have good covearge.

I wondered whether we were covering both bitnesses for Windows but I see debug is always x86 and retail x64 (perhaps should be in the job name)

@mmitche are we short of VM resources?

**Comment by stephentoub** [comment]
> perhaps should be in the job name

It should be. I didn't know this was the case. Which, if any, of the badges on the home page represent 32-bit rather than 64?

**Comment by danmosemsft** [comment]
32 bit is only fully supported on Windows, so it's obviously just Windows. And for those, netci.groovy has:

```
def buildArchConfiguration = ['Debug': 'x86',
                              'Release': 'x64']
```

So debug is always 32 bit, release always 64 bit. I am not sure what Helix does - hopefully the reverse.

**Comment by stephentoub** [comment]
Ok.  My $.02:
1) We should have legs with badges on the home page for both 32-bit and 64-bit Windows.
2) We should update the home page badges to highlight that some of the badges actually represent 32-bit (e.g. a 32-bit column).
3) We should rename the legs to include the bitness in the name so that we can easily differentiate them, at least for cases like Windows where we have a difference.

**Comment by danmosemsft** [comment]
If I read Helix right @MattGal we don't test x86 at all. We are relying on Jenkins (and debug only) if that's the case.

**Comment by MattGal** [comment]
@danmosemsft, you are correct.  Adding x86 flavor to Windows, build-wise, would be trivial.   I think we'd need to actually generate custom VHDs to do this on Linux, and it wouldn't be an option at all on OSX.

Adding actual OSes that are natively 32-bit (I.e. not using WOW to run x86 code) would be quite a lot of work, since we rely on base Azure images, which are not available in natively x86 format AFAIK.

**Comment by danmosemsft** [comment]
@MattGal I think we should have an x86 Windows release run in Helix, since it doesn't sound too hard. Should I open an issue in core-eng? 

We only officially support 32 bit for Windows (Linux, ARM in progress eg https://github.com/dotnet/coreclr/issues/9265) so it'd just be that.

I don't think an actual 32 bit OS is necessary. In my (limited) experience it's really rare to have a bug that doesn't repro in WOW. Usually setup related issues -- program files and registry.

**Comment by MattGal** [comment]
Sounds good, please create the issue.  It should literally just involve adding a few pipeline JSON entries, I can probably do this today unless @chcosta wants it.

**Comment by chcosta** [comment]
@MattGal , if you have time, please don't block on me.

**Comment by mmitche** [comment]
@danmosemsft We are not short of VM resources.

**Comment by weshaggard** [comment]
Closing as I'm tackling the CI legs in a slightly different way now that we have the portable legs.
