### ISSUE TITLE
unsigned-correctness in interop structures

### ISSUE THREAD

**Issue by willdean** [dotnet/corefx#15680]
I have been looking at the recent port #984 of the SerialPort code , and it raises for me a question about the use of unsigned types in interop signatures.

For example, the native `COMMTIMEOUTS` structure contains 5 `DWORDS` (https://msdn.microsoft.com/en-us/library/windows/desktop/aa363190.aspx).

However, in interop/windows/kernel32/interop.COMMTIMEOUTS.cs, it has 5 ints (this is how it came from the original netfx source).   A corollary of this is that we end up with `MAXDWORD` being an defined as `const int = -1`, where it was originally `0xffffffff`.

Clearly the p/invoke marshalling doesn't care whether a 32-bit number is signed or unsigned, but it seems to me that one should, in general, try to make p/invoke signatures, etc. match window.h as closely as possible.   

I don't see anything in the interop guidelines or previous issues about this - is there some policy against unsigned types in interop signatures?  Or is this some kind of historical 'don't upset VB with unsigned types' sort of thing?

Tagging @JeremyKuhne because he ported the stuff across

**Comment by karelz** [comment]
@tijoytom do you have insight?

**Comment by JeremyKuhne** [comment]
@willdean I'm fine with aligning these closer with the headers.  I didn't have a lot of time to thoroughly scrub the definitions.

I think in general we want to keep closer to the actual type definition (e.g. DWORD is uint). That said we should be cognizant of making things awkward with existing public APIs that had to stick with signed types to support languages that didn't have unsigned.  (Thinking return values being int vs uint.)

In my own library where I've been experimenting with P/Invokes I've written a doc that might be useful as a stepping off point. If folks think it is useful I could look at putting one like it in CoreFX docs:

https://github.com/JeremyKuhne/WInterop/blob/master/docs/pinvoke.md

**Comment by mellinoe** [comment]
We would prefer (at least I would) to have all of our PInvoke declarations be a direct mapping of the native types, but much of the code that we "borrowed" from the .NET Framework does not follow that rule. It hasn't been the highest priority to go and clean up every old PInvoke declaration with mismatched types, but we have done it on occasion. New PInvokes that we write should definitely adhere to that rule, in my opinion, so we should include some rules in our coding guidelines about it. I would guess that most/all of our PInvoke declarations to our Unix shims are already correct, because we control both sides of the equation. So this is most likely exclusive to the old PInvokes we've inherited from old code.

The discussion about other programming languages is a bit of a red herring; our PInvoke's aren't public, and even if they were, changing the signatures would be a breaking change that we couldn't make anyways. The "mental cost" of using the unsigned signatures can be paid entirely within the implementation here.

**Comment by tijoytom** [comment]
@willdean There is no policy against having unsigned types in interop signature.
@JeremyKuhne it's usefull to have the document in CoreFX albeit after some corrections and review.

**Comment by willdean** [comment]
Thanks all.  I will correct the ones that are specific to the SerialPort classes.

**Comment by karelz** [comment]
@willdean please don't change the SerialPort yet. I would rather see the initial implementation fully tested, then we can start making changes like these.
It will IMO tremendously decrease the risk. Also it is easier to track the changes we might eventually port back to Desktop.

**Comment by willdean** [comment]
@karelz I wasn't really going to touch anything on SerialPort until we have the netfx test code across - it doesn't seem worth trying to write new tests before we see what we've already got, and I'm fully on-board with "don't change it if it's not tested".

I fear you may be in for a disappointment about how rigorously it can be tested without additional hardware, but let's see...

**Comment by karelz** [comment]
@willdean perfect, thank you! (not looking forward to the disappointment :()
