### ISSUE TITLE
IEnumerable.Append extension method breaks basic enumerable contract

### ISSUE THREAD

**Issue by olivier-spinelli** [dotnet/corefx#15716]
Hi,

Append extension method does not seem to honor one of the basic IEnumerator contract and this may lead to quite subtle bugs: 
```
        public void buggy_behavior_of_Append_extension_method()
        {
            {
                int[] t = new int[0];
                var e = t.GetEnumerator();
                Should.Throw<InvalidOperationException>(() => Console.Write(e.Current));
            }
            {
                int[] tWithItems = new int[] { 7 };
                var e = tWithItems.GetEnumerator();
                Should.Throw<InvalidOperationException>(() => Console.Write(e.Current));
            }

            {
                int[] t = new int[0];
                var e = t.Append( 3712 ).GetEnumerator();
                // This fails: e.Current is 0, the default(int)...
                Should.Throw<InvalidOperationException>(() => Console.Write(e.Current));
            }
        }
````

**Comment by JonHanna** [comment]
So does `yield` and many other implementations, which is in line with the documentation:

> Current is undefined under any of the following conditions:
> -    The enumerator is positioned before the first element in the collection, immediately after the enumerator is created. MoveNext must be called to advance the enumerator to the first element of the collection before reading the value of Current.
> - The last call to MoveNext returned false, which indicates the end of the collection.
>  - The enumerator is invalidated due to changes made in the collection, such as adding, modifying, or deleting elements.

Arguably while the cases you show here clearly aren't bugs, if you cast the `IEnumerator<T>` to `IEnumerator` it's not in line with the documentation, though that's at odds with the documentation for `IEnumerator<T>` and the flaw lies there. (I was thinking a couple of days ago about filing an issue on exactly that, so this has reminded me.

**Comment by JonHanna** [comment]
Oh, I was misremembering that doc. This is clearly not buggy with that cast either:

> After an enumerator is created or after the Reset method is called, the MoveNext method must be called to advance the enumerator to the first element of the collection before reading the value of the Current property; otherwise, Current is undefined.

(That doc does still disagree with the second case in the bullet points I quote from `IEnumerator<T>` though).

**Comment by olivier-spinelli** [comment]
In all other places, calling Current throws a InvalidOperationException (as the tests demonstrate). 
> Current is undefined

Hopefully `undefined` is not available in .net (I see you javascript :)) and up to me, confusing this "undefined" with default(T) is really very dangerous.

**Comment by JonHanna** [comment]
> In all other places, calling Current throws a InvalidOperationException

No, in some other places it does so. In other places like if you use `yield` in a method, it returns the default value of the type in question. Being undefined implementations are free to return any value or throw any exception, and they all do one or the other. 

> confusing this "undefined" with default(T) is really very dangerous.

I think you are confusing `undefined` which is a possible value in Javascript with *undefined* which is a word meaning something hasn't been defined. 

The behaviour of `Current` prior to the first call to `MoveNext` is undefined and explicitly called out as such in the documentation.

**Comment by olivier-spinelli** [comment]
Just to clarify, my reference to javascript was just a joke. I think I perfectly understand **this undefined** here in the spec. Up to me, the fact that yield enumerator is not perfectly implemented is not a reason to blindly follow this dangerous path.
On the pure spec side you may be right but for API users, this is a terrible design. 
We have here an opportunity to easily early detect more than an API misuses: it is clearly a conception error to not call MoveNext() and this CAN happen, why give up?
Anyway, I guess my "extremist" point of view will not win (and I strongly believe that this kind of approximation in a framework weaknesses it... too much).

**Comment by JonHanna** [comment]
> Up to me, the fact that yield enumerator is not perfectly implemented

It is perfectly implemented in this regard.

> On the pure spec side you may be right but for API users, this is a terrible design.

Why should people who use the interface as specified be penalised by unnecessary checks and in some cases extra state to allow those checks to cause a particular behaviour in the face of buggy uses? Why, given that you're only comparing two different cases, should the first one be considered correct an the second incorrect?

> We have here an opportunity to easily early detect more than an API misuses.

No, because changing the spec in such a way creates a new condition that is considered an API misuse.

.NET has very little in the way of undefined behaviour, and little extremity in it (it would also be valid for the application to crash or for the call to go into an infinite loop, but that would probably be changed in a case that did so, if only to avoid exploits) and much in the way of helping to point out mistakes (and I would pretty much always argue that an invalid argument to a call should result in a reasonable exception, for example), but there are times when the best thing to do in a spec is to say, "there's no rules about what can happen if you do this silly thing, so don't do this silly thing". Especially since *anyone* can implement that interface. Why should every user of .NET be expected to throw a particular exception in a case that almost never comes up?

Saying to implementers (which can be any user) that they don't have to worry about that particular case and hence at least nothing written by Microsoft (the only case that Microsoft can make a promise about) or now that the implementation is open source nothing published in the repositories (where MS share the responsibility for such promises with those of us who contribute) will trigger it is a lot nicer than saying we *have* to do a particular thing as that entails that if we don't do that particular thing we can't depend on other code using our types as we want (since that code is written according to the public spec and as such could assume we were handling that case).

What benefit does putting that burden on the plate of everyone who implements `IEnumerator<T>` give?

If `IEnumerator<T>` was specified in such a way, I would be arguing that the requirement be removed.

**Comment by olivier-spinelli** [comment]
Sorry to disagree. If i like the.net plaform it is for a large part thanks to its ability to actually implement invariants, preferably strong ones.
Since I won't win this battle, I close the issue. 
Thanks for your time!

**Comment by danmosemsft** [comment]
@olivier-spinelli I think my overriding concern would be that this could be a breaking change (not just for existing Core users but for anyone bringing over an existing library), so it would have to bring a compelling benefit which I don't think is there.

**Comment by danmosemsft** [comment]
But -- sure appreciate the suggestion, and others would be welcome, or contributions for existing issues if you are interested.
