### ISSUE TITLE
Improve code coverage of System.IO.FileSystem.AccessControl (8.9%)

### ISSUE THREAD

**Issue by the-dwyer** [dotnet/corefx#15808]
@danmosemsft  created #14352 to increase unit tests.
I added some tests with issue #15375 and a pull request.
I have added some more tests that increase coverage to 8.7%

Please assign me to this issue so that I can create another pull request.

Thanks,

Michael

**Comment by danmosemsft** [comment]
@the-dwyer feel like going further? 8.9% is pretty low I guess there's some low hanging fruit there. 

There are also other areas that need more coverage, could be a good way to get to start familiarizing with other parts of hte codebase:
https://github.com/dotnet/corefx/labels/increase-code-coverage

**Comment by danmosemsft** [comment]
Info on code coverage work:

1) Here's the all up report
https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/Code_Coverage_Report/
Caveat - doesn't show coverage of any types whose implementation is in corelib (eg String, etc). If you want to look at that for now you must gather manually using instructions below.

2) Docs on code coverage work are here
https://github.com/dotnet/corefx/blob/master/Documentation/building/code-coverage.md
and some in
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md

3) There's innumerable places to add coverage -- we would love to focus on the most heavily used types and the least covered types to get the most benefit.

**Comment by karelz** [comment]
Unassigning @the-dwyer as the issue does not seem to be active.

@8to5Developer, thanks for picking it up! I added you as Collaborator to the repo, so that I can assign the issue to you once you accept. Please ping me once you accept, and I will update the temporary assignment.
In future, ping issues when you pic them up to avoid duplicate work / overlap. Thanks!

You might find this useful: [new contributor docs](https://github.com/dotnet/corefx/wiki/New-contributor-Docs#main-page-section-content) (under-construction). The docs are in wiki which is RW for everyone, so feel free to improve the docs as well.

If you need any help, or hit any road blocks, please let us know. Welcome on board!

**Comment by 8to5Developer** [comment]
@karelz, I just accepted the invitation. Thanks for the link to the docs.

**Comment by karelz** [comment]
The code coverage is at 84.3%, closing.
cc @JeremyKuhne @pjanotti
