### ISSUE TITLE
XML API documentation not available for System.ValueTuple

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/corefx#15823]
- Reference System.ValueTuple NuGet package (version 4.3.0)
- Use APIs

**EXPECTED**: API documentation shows up in intellisense
**ACTUAL**: No API documentation shown

It looks like this is an issue with the package authoring, next to `System.ValueTuple.dll`, it has a file named `.xml` instead of `System.ValueTuple.xml`.

@weshaggard @ericstj @stephentoub

**Comment by danmosemsft** [comment]
@jcouv

**Comment by karelz** [comment]
AFAIK CoreFX XML documentation is not always used in IntelliSense - @ericstj @weshaggard can you please clarify this case?

**Comment by weshaggard** [comment]
For any new libraries like System.ValueTuple we don't have any old xml intellisense files to fall back to so we do produce these from the xml doc comments in code. This one is broken because of what @dsplaisted called out which is because the file isn't correctly named. I'm going to submit a PR to fix that.

**Comment by weshaggard** [comment]
PR https://github.com/dotnet/corefx/pull/15880 should take care of this issue.
