### ISSUE TITLE
Span extension methods vs instance methods

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#15914]
This was brought up in the review of #15329.

> We should discuss the extension method pattern for span holistically -- I don't think that this a good idea for our customers. It introduces a somewhat weird type (SpanHelpers) we no additional benefit. What is the reason these should be extension methods?

**Comment by jkotas** [comment]
> somewhat weird type (SpanHelpers)

Where is this weird type?

The extension vs. instance methods on generic types have performance implications. The instance methods on generic types are not pay for play - every instantiations pays for all methods, not just the ones that somebody uses.

We should make heavy weight methods like Sort to be extension methods for this reason.

**Comment by omariom** [comment]
Is there such a rule: "Everything that can be implemented using only the public surface of a type should be implemented as extension methods"?

**Comment by nietras** [comment]
> The instance methods on generic types are not pay for play - every instantiations pays for all methods

Can't instance methods simply forward to implementations elsewhere e.g. SpanHelpers to resolve that? That is, this is an implementation issue, not necessarily an API design issue?

**Comment by jkotas** [comment]
> Can't instance methods simply forward to implementations elsewhere e.g. SpanHelpers to resolve that? 

It does not help. The generic dictionaries are transitive.

**Comment by jkotas** [comment]
> Everything that can be implemented using only the public surface of a type should be implemented as extension methods

I am not sure whether there is such a rule. I do not think there needs to universal rule like this.

My concern is about performance characteristic of basic building blocks. I would like to make sure that any new basic building blocks do not force you into choosing either shiny looking big and slow code or old-fashioned performant code (Linq is the worst offender on this front).

BTW: A recent example where I think we made a mistake is ValueTuple design: https://github.com/dotnet/corefx/blob/master/src/System.ValueTuple/ref/System.ValueTuple.cs#L32 . As you can see, ValueTuple implements many interfaces, some of them are generic. It means that ValueTuple type has many times larger runtime footprint compared to a simple struct with a couple of fields (how many times larger depends on the runtime and codegen strategy used).

**Comment by benaadams** [comment]
Too late to change ValueTuple? Is there any point to the non-generic interfaces on them anyway? At the point you use them the two ValueTuples have been boxed, and then you might have well have just used Tuple... (though the answer might be language features)

**Comment by jamesqo** [comment]
My thoughts: extension methods can be kinda annoying when you have generic types because if you have a second generic type that the compiler can't infer, then you have to write out both types (e.g. like `Unsafe.As<uint, byte>`). This is why Enumerable.Cast/OfType have to accept a non-generic IEnumerable as a workaround. I vote in favor of instance methods.

**Comment by nietras** [comment]
> The generic dictionaries are transitive.

@jkotas I am not sure I fully understand the details, would you mind elaborating on this? Let's say we implement `Sort` as a member method like this (just for arguments sake):
```csharp
public struct Span<T>
{
    public void Sort<TComparer>(TComparer comparer) where TComparer : IComparer<T>
    {    SpanHelper.Sort<T, TComparer>(this, comparer); }
}
```
And `SpanHelper` then contains the actual implementation. What are the concerns here as seen from CLR's point of view? Compared to an extension method defined as:
```csharp
public static class SpanExtensions
{
     public static void Sort<T, TComparer>(this Span<T> span, TComparer comparer) 
        where TComparer : IComparer<T>
     {   }
}
```
Both defer the actual implementation to other types than `Span<T>` itself.

**Comment by jkotas** [comment]
In the first case, generic dictionary of `Span<T>` will have slots for everything used by Sort method. It means that every `Span<T>` instantiation (where T is reference type - assuming current CoreCLR generic code sharing policy) will pay for Sort baggage. Moving the actual implementation into separate type or method does not solve the problem because of the `Span<T>` dictionary is still going to have a pointer to the Sort baggage. It is less of a problem for JIT because of the expansion of the baggage is lazy. It is more of a problem for AOT compilation because of the expansion has to be saved into binary unless some kind of complex analysis can prove that it won't be ever used or figure out where to strategically insert laziness.

It is not the case with separate extension method. The extension method will have its own isolated dictionary, and so you only pay for the baggage that comes with it if you actually call it by design.

I know that the pattern for classic .NET collections is to have a ton of rarely used instance methods. Looking at the footprint of every instantiation in AOT binaries always make me sad.

**Comment by nietras** [comment]
> less of a problem for JIT because of the expansion of the baggage is lazy

Right.

> more of a problem for AOT compilation

Of course, that makes sense then.

@jkotas thanks again! 😃

**Comment by terrajobst** [comment]
OK, that makes sense to me. So there are two arguments for having extension methods.

1. We want to use generic specialization, i.e. having methods specific for `Span<byte>` vs `Span<char>`. For that to work, they need to both be extension methods.
2. Every method on a generic type needs to be instantiated by our AOT compiler. By making them generic methods on a non-generic type, we can make it pay for play friendly, meaning the compiler only has to instantiate the methods being invoked.

Assuming the type is still called `SpanHelpers`, we should change the name to follow existing conventions, such as `SpanExtensions`.
