### ISSUE TITLE
Build system requirements are incorrectly documented

### ISSUE THREAD

**Issue by willdean** [dotnet/corefx#15955]
I'm trying to build corefx on a non-developer machine (i.e. no VS, etc).

I installed msbuild manually from a stand-alone package (nobody told me to, but it seemed sensible).anThen I copied the entire corefx tree to the machine and run build.cmd, and it says this:

```
Error: Visual Studio 2015 required.
       Please see https://github.com/dotnet/corefx/blob/master/Documentation/pro
ject-docs/developer-guide.md for build instructions.
```

I'm sceptical that VS2015 is actually required (that's not the issue however), but I'm 100% sure that the document that which is referred to doesn't answer the question - it doesn't mention VS2015 at all, and only mentions VS in passing about debugging something.

Personally I think these kind of newbie-only paper cuts are worth fixing.

**Comment by danmosemsft** [comment]
@karelz because we SHOULD make this easier.

@mmitche how does Jenkins set up the CI boxes -- I assume they don't have VS on them?

I don't know why the scripts require it. VS in general should be required only for certain things like building VS packages/VSIX (it should not be required on a build machine). VS installs the SDK that includes CL but that should be obtainable separately.

**Comment by willdean** [comment]
@danmosemsft I am not whining about VS2015 (though I can whine about VS anytime anyone wants me to), I'm whining about being referred to a document to see the requirements which doesn't tell me what they are.

**Comment by karelz** [comment]
cc @mellinoe

**Comment by karelz** [comment]
VS is mentioned as prereq (https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md).
The discoverability is not ideal for newbies, I agree - we need the "better newbie contributor guide" I mentioned (started here https://github.com/karelz/corefx/tree/docs). I will share my notes on next steps in the guide this week.

**Comment by mellinoe** [comment]
VS is the easiest thing to document as a pre-req, since it pulls in all of the other things that we need, which is more than just MSBuild. For example, we rely on the developer command prompt script to set up some paths, we need the VC++ compiler and targets, etc. The developer command prompt requirement alone would probably make it tricky to build without VS, although it's not a show-stopper. You'd probably need to make more changes to the build scripts and infrastructure to work around that.

**Comment by mmitche** [comment]
@danmosemsft Most have VS.

**Comment by danmosemsft** [comment]
Ah, OK. In that case I think it's reasonable to require VS instead of 2 separate install paths to document.

**Comment by willdean** [comment]
@karelz It sounds like all that's needed is to either remove the reference to the wrong document which is currently in the error message (if there was no link to a document, I would just take "Error: Visual Studio 2015 required" at face value).  Or change the error message to point to the correct document, though it's probably hard to keep them in sync, long term.
