### ISSUE TITLE
DbDataReader.GetFieldValue<T> fails in SQLite

### ISSUE THREAD

**Issue by tinchou** [dotnet/corefx#15972]
I'm writing `System.Data.Odbc` library for corefx and testing it with a SQLite provider. When you call `reader.GetInt64(i)` to get a big number it'll work great, but if you try to do `reader.GetValue(i)` then it'll fail with and `Unknown SQL type` exception. Given the inner working of SQLite, I'd say this is expected.

The real issue here is that `reader.GetInt64(i)` works fine but  `reader.GetFieldValue<long>(i)` throws the same exception as `GetValue` (since it's just a cast as seen [here](https://github.com/dotnet/corefx/blob/c5c75db7c00047d603522fd6e21f350099e09bbb/src/System.Data.Common/src/System/Data/Common/DbDataReader.cs#L156)). This behavior is really unexpected from APIs with (presumably) the same purpose.

Since this is a newer API added in .NET 4.5, it's a shame that it works worse than the old one. Maybe we can add special cases for the types we already support (e.g. `GetInt64`)?

See https://github.com/aspnet/Microsoft.Data.Sqlite/blob/dev/src/Microsoft.Data.Sqlite/SqliteDataReader.cs#L537 for a possible improvement.

cc @divega.

**Comment by divega** [comment]
@tinchou I talked briefly to @bricelam about how we are handling this in the Microsoft.Data.Sqlite provider and he suspects there maybe a problem in the ODBC driver for SQLite: the fact that `GetValue()` fails for that column makes little sense. If a value is stored it should be able to return it (even if it is not of the type you expect) so the implementation of `GetFiledValue<T>() for System.Data.Odbc could then convert to the desired type rather than casting.

**Comment by divega** [comment]
We also talked about this issue you filed and we both believe it is actually ok for the default implementation of `GetFieldValue<T>()` on `DbDataReader` to be just a cast. Many providers may not need more than that, and if they do, they can always override.

**Comment by tinchou** [comment]
I'll close this, then try to get in touch with the driver owner. Thanks!
