### ISSUE TITLE
Implement DiagnosticSource.IsEnabled with extended context

### ISSUE THREAD

**Issue by lmolkova** [dotnet/corefx#15984]
# Motivation
Our goal is to enable telemetry event correlation. To do this we need incoming requests to be tagged with an ID (and potentially other information), and have this information 'flow' through (be available) to all code run in response to that request and in particular allow this information to be propagated to any outgoing requests.

#15023 Implements this approach and involves additional costs such as maintaining Activity.Current and context propagation.
To reduce such costs, we want to enable advanced sampling and outgoing requests filtering.

DiagnosticSource declares IsEnabled method and allows to filter events based on their names.
* For sampling scenario, IsEnabled(string) allows to implement fixed rate or threshold sampling, however sampling may be done based on other properties: request initiator, particular feature, path, specific Id in the Activity.Baggage
* For outgoing request filtering, users may need to prevent instrumentation of certain requests based on their URI or other properties.

IsEnabled(string) does not allow to efficiently implement such scenarios and we propose to add IsEnabled with additional context.

# Proposed API
```C#
public abstract partial class DiagnosticSource
{
    public virtual bool IsEnabled(string name, object arg1, object arg2 = null) { return IsEnabled(name); }    
}

public partial class DiagnosticListener
{
    public override bool IsEnabled(string name, object arg1, object arg2 = null);
    public virtual IDisposable Subscribe(IObserver<KeyValuePair<string, object>> observer, Func<string, object, object, bool> isEnabled)
}
```

# Usage
```C#
//This code represents web service hosting layer that receives incoming http request
//See more details about this samples and Activity in #15023
//For the filtering, we want to 
//   1) Make sure someone listens to the http incoming request events and only if it's true,
//        create Activity and fill it's baggage and parent id 
//   2) Let user enable instrumentation based on request and Activity properties.
//   3) If user decides to instrument this particular request, we can start Activity and send event
public void OnIncomingRequest(DiagnosticListener httpListener, HttpRequest request)
{ 
    //check if user is interested in such events at all
    if (httpListener.IsEnabled("Http_In"))
    {
        var activity = new Activity("Http_In");

        //parse request headers and add baggage to Activity
        activity.SetParentId(request.headers["x-ms-request-id"])
        foreach (var header in context.Request.Headers)
            if (header.Key.StartsWith("x-ms-baggage-")
            activity.AddBaggage(header.Key, header.Value);
            
            
        //let user decide if he wants this request and activity to be sampled
        if (httpListener.IsEnabled("Http_In", request, activity))
            httpListener.StartActivity(activity);

        //... process request and stop activity
    }
}

//This code demonstrates how user can subscribe to events with advanced filtering based on request and activity properties
public void Startup()
{
   DiagnosticListener.AllListeners.Subscribe(delegate (DiagnosticListener listener)
   {
        var predicate = (string name, object requestObj, object activityObj) =>
        {
            //check for event name
            if (name == "Http_In")
            {
                var request = (HttpRequest)requestObj;
                //filter out some unintersting events
                if (request != null && request.Method == "OPTIONS")
                    return false;
                    
                //sample requests based on CorrelationId in the baggage
                var activity = (Activity)activityObj;                            
                if (activity != null)
                    return IsSampledId(activity.GetBaggage("CorrelationId"));

                //note that if no context (request and activity) provided, we return true,
                //so the first httpListener.IsEnabled("Http_In") check will pass
                return true;
            }
            return false;
        }
   
        if (listener.Name == "System.Net.Http")
        {
            listener.Subscribe(delegate (KeyValuePair<string, object> value, predicate)
            {
                 Console.WriteLine("Event: {0}  Current Operation: {1} Current ID {2}", 
                       value.Key, {Activity.Current.OperationName}, {Activity.Current.Id});
            });
        }
    }
}

// This code demonstrates that it's still possible to filter events based on their names only    
public void Startup()
{
   DiagnosticListener.AllListeners.Subscribe(delegate (DiagnosticListener listener)
   {
        if (listener.Name == "System.Net.Http")
        {
            listener.Subscribe(delegate (KeyValuePair<string, object> value, (name) => name == "Http_In")
            {
                 Console.WriteLine("Event: {0}  Current Operation: {1} Current ID {2}", 
                       value.Key, {Activity.Current.OperationName}, {Activity.Current.Id});
            });
        }
   }
}

```

@vancem @terrajobst

**Comment by vancem** [comment]
I worked with @lmolkova  on this API.  I want to indicate that the need for more context (arguments) to the IsEnabled() call has always been a known issue.    We did not add it initially because we did not need it and at the time and could be added later.   That time has now come (we have a real scenario that needs it.  

Note that there already was the API

     public virtual bool IsEnabled(string name)

This simply adds the overload 

     public virtual bool IsEnabled(string name, object arg1, object arg2)

Which allows up to two more arguments (what we needed for our particular scenario).    In theory we may add more overloads with even more arguments, but we expect that 2 will cover probably all but the most unusual cases.   We can add the others later, so again, we wait until they are needed.

There is a design where you only need one argument object because you use anonymous types to stuff anything you need into that argument.   We rejected this because it requires you to allocated to call IsEnabled, and the whole point of IsEnabled is to be a FAST check to AVOID that kind of overhead.   

We did not add a bool IsEnabled(string name, object arg1) overload because we could achieve that pretty efficiently with a default argument (Thus from  caller of IsEnabled()'s perspective you do have all the overloads.

**Comment by stephentoub** [comment]
> We did not add a bool IsEnabled(string name, object arg1) overload because we could achieve that pretty efficiently with a default argument (Thus from caller of IsEnabled()'s perspective you do have all the overloads.

Are the args supposed to be optional in the proposal then?  They're not currently:
```C#
public virtual bool IsEnabled(string name, object arg1, object arg2) { return IsEnabled(name); }
public override bool IsEnabled(string name, object arg1, object arg2);
```

> We rejected this because it requires you to allocated to call IsEnabled, and the whole point of IsEnabled is to be a FAST check to AVOID that kind of overhead.

What about value type arguments?  Should these be generic?

**Comment by vancem** [comment]
> Are the args supposed to be optional in the proposal then? They're not currently

Yes, that was the original suggestion but @lmolkova may have run into a snag.   @lmolkova  can comment

> What about value type arguments? Should these be generic somehow (though that could be problematic with them also being virtual)?

Bingo.   Generic Virtual methods add non-trivial overhead (since you have to pass a type argument, and frankly we don't optimize this path much).    Moreover, the value type case is likely to be rare (typically you pass 'big' things to DiagnosticsSources, which should be objects, and even if you did want to pass a value type, it is more efficiently handled by having the producer have 'argument object' that he sets a field in and passes along (and reuses for each call).

**Comment by lmolkova** [comment]
> Are the args supposed to be optional in the proposal then? They're not currently:

Correct, second argument could be optional. I updated issue description and PR
