### ISSUE TITLE
ImmutableSortedSet.Builder.DebuggerProxy incorrectly caches contents

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#16007]
https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableSortedSet_1.Builder.DebuggerProxy.cs#L42-L45

`ImmutableSortedSet<T>.Builder` is probably a mutable type, so it's incorrect to cache the contents for display to the debugger. The code was probably copied-and-pasted from the proxy for a collection that actually is immutable, where it would be legal to cache the contents.

**Comment by safern** [comment]
> `ImmutableSortedSet<T>.Builder` is probably a mutable type

What do you mean with that?

**Comment by jamesqo** [comment]
@safern You can ignore the 'probably'. I was 99% sure it was mutable bc it had `Builder` in its name but I hadn't actually looked through its source code.

**Comment by safern** [comment]
@jamesqo do you want to grab this one?

**Comment by karelz** [comment]
@jimparsley thanks for picking it up! I sent you collaborator invite, so that we can assign the issue to you.In future, please ping issues before you pick them up ;)

FYI: We have new contributor docs (under construction) linked from our main page (or directly [here](https://github.com/dotnet/corefx/wiki/New-contributor-Docs))
If you hit any roadblocks, please let us know!

**Comment by jimparsley** [comment]
@karelz you're welcome. I have accepted the invite. Thanks for all the info!
