### ISSUE TITLE
Microsoft.NETCore.UniversalWindowsPlatform 5.3.0 makes my appx crashes when deploy from .ps1

### ISSUE THREAD

**Issue by vRITHNER** [dotnet/corefx#16107]
Hi,

I have an UWP application which crashes when I deploy it manually from PowerShell 
**Add-AppDevPackage.ps1** 's script but the same app works fine when I deploy from my **VS2017 latest RC.**
I can't attach WinDbg because the app is crashing about 4-6 seconds after the launch.

After long hours to restart from earlier working branch, I upgrated each stable Nuget separatly to finally 
found the one causing the issue :
"**Microsoft.NETCore.UniversalWindowsPlatform**": 
a downgrade from "**5.3.0**", to "**5.2.2**", everything is working fine again.

The event viewer is giving this error when it crashes:

> Activation of app xxxxxxxxxxxxxxxxx!App failed with error: The remote procedure call failed. See the Microsoft-Windows-TWinUI/Operational log for additional information.

then in the Microsoft-Windows-TWinUI%4Operational's log:

> Activation of the app xxxxx!App for the Windows.Launch contract failed with error: The remote procedure call failed..

Hope it's helping
Txs
-Vince

**Comment by karelz** [comment]
For .NET Native feedback, please contact dotnetnative@microsoft.com - see [blog post](https://blogs.msdn.microsoft.com/dotnet/2017/01/30/announcing-net-core-net-native-and-nuget-updates-in-vs-2017-rc/). Here's info about how to file bugs: https://github.com/dotnet/core/blob/master/Documentation/ilcRepro.md

cc @MattWhilden

In general: To debug app startup issues, you need to tell OS to launch debugger upon app launch. For non-UWP apps use e.g. gflags, for UWP apps use plmdebug.

**Comment by vRITHNER** [comment]
Hi karelz, txs for the help

ps. I tried  plmdebug stuff but it's not doing anything...
Cheers
-v

**Comment by karelz** [comment]
@vRITHNER I have used plmdebug in the past (though it's been 1+ year) and it worked. It is not easy to use, but eventually you can make it work - I would suggest to search for articles on internet how to debug UWP startup issues for additional tips and tricks.

**Comment by saurabha5** [comment]
I also faced the same issue and figured out that the problem was with the "Dependencies" getting pushed along with the package if you use Microsoft.NETCore.UniversalWindowsPlatform 5.3.0 or later.

Ideally with 5.3.0 or later the .net native compilation tool version should be 1.6, however, the "Dependencies" folder with the package shows 1.4
To be specific Dependencies should have below 

- Microsoft.NET.Native.Framework.1.6.appx
- Microsoft.NET.Native.Runtime.1.6.appx
- Microsoft.VCLibs.x64.14.00.appx

However, in actual below gets added 

- **Microsoft.NET.Native.Framework.1.3.appx**
- **Microsoft.NET.Native.Runtime.1.4.appx**
- Microsoft.VCLibs.x64.14.00.app

This specifically happens when your nuget packages are referred via Project.json file instead of using the new PackageReference in .csproj file. : https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json-to-csproj

More details : http://stackoverflow.com/questions/43593141/msbuild-exe-not-adding-correct-dependency-for-uwp-app-targeting-net-native-1-6?noredirect=1#comment74387802_43593141

**Comment by GregDomjan** [comment]
Don't know if this is the right place, but since I found it here while searching.

Issue described by @saurabha5  is still happening in 5.4.0

Within a clean checkout, 
`MSBuild.exe /t:restore;build /p:Configuration=Release;AppxBundle=Always;AppxBundlePlatforms="x86|x64"`  
builds x86 with appropriate 1.7 dependency,  
however x64 is showing 1.4/1.3 dependency 
and final bundle fails to be produced due to differing dependencies.

Re running the build a second time without cleanup results in success, or running just restore, then just build I'm getting success.
