### ISSUE TITLE
Remove "'$(TargetGroup)'=='netstandard' in configurations in test projects.

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16121]
We should remove these because in the case where a project has a non-netstandard configuration in the configurations.props, that configuration will be picked and this condition will be false causing the tests to not run in the normal case.

When doing this, make sure tests that are NOT conditioned to be netstandard are instead conditioned to only be non-netstandard, eg ,.
 `<ItemGroup Condition="'$(TargetGroup)'=='netcoreapp'">` or 
` <ItemGroup Condition="'$(TargetGroup)'!='netstandard' ">`
This will means that when we do build the netstandard configuration explicitly, we only pick up tests running against netstandard API.

@joperezr to make sure I stated this correctly.

**Comment by danmosemsft** [comment]
I see 53 matches of "= *'netstandard'" in our test csproj's.

**Comment by danmosemsft** [comment]
@weshaggard I believe this is the only work required to make sure netstandard tests actually run (as I expect them anyway). Let mek now if you believe there are tests that should be running but are not running for some other issue.

**Comment by joperezr** [comment]
The only part that I'm not convinced on doing is:

>When doing this, make sure tests that are NOT conditioned to be netstandard are instead conditioned to only be non-netstandard

This is because we have a lot of test projects where we don't currently have a condition, but they are supported by netstandard. I would say that the right way to do this, is to:
 - Remove all Conditions of `'$(TargetGroup)'=='netstandard'`
 - Go through the rest of the ItemGroups, and check if they can actually build as netstandard, by building `msbuild *.csproj /p:TargetGroup=netstandard` and if there are errors because some API is netcoreapp specific, then separate those files to an itemgroup with a condition of `'$(TargetGroup)'=='netcoreapp'`

**Comment by weshaggard** [comment]
>@weshaggard I believe this is the only work required to make sure netstandard tests actually run 

Yes I agree with cleaning up the conditions and that will ensure the tests build and run in the netcoreapp configuration. However there is still a mode where we want to build the test projects as netstandard and run them on netcoreapp, which is ever so slightly different then building the tests as netcoreapp and running them as netcoreapp. I do agree with @jkotas comment in one of the other threads that for the netstandard builds of the tests we can do those as part of an outerloop run.

**Comment by ViktorHofer** [comment]
Closing as we don't have netstandard tests anymore.
