### ISSUE TITLE
Clean-up our build definition files

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#16161]
We have a number of things that should be cleaned up in our official and CI builds.

1. We should delete a lot of unnecessary properties. example FilterToOSGroup, TargetOS, etc. We should also look at cleaning out the amount of paramters we are passing to things like CreateHelixArguments, especially when we are only disabling that step. 
2. We have a lot of duplication things like our PB_*Arguments parameters which are copied multiple places in our pipeline file. We should set the parameters up in the definition and just pass the appropriate parameters. Otherwise we end up duplicating things like ArchGroup, ConfigurationGroup, etc on each set of parameter lines in a pipebuild step.
3.  We should finish the work ensure that all the parameters we are passing are prefixed with PB_ to avoid any more trouble from environment variables changing the official builds. 

cc @chcosta @MattGal

**Comment by chcosta** [comment]
Regarding #2.  I'd actually prefer we went the other direction and reduced our coupling on VSTS.  There are some nice properties of moving arguments into the PB_*Arguments parameters instead of defining them in build definitions.  It allows us to make our build definitions more generic and therefore more re-usable.  it's also a step towards moving away from a dependency on VSTS as we can encapsulate the data in a different format.  There could certainly be further steps taken in this area which allow us to do things like set properties once in the pipeline file and have them flow to the PB_*Arguments properties.  My preference is to move as much data as we can out of the VSTS definition.  This would allow us to conceptually make changes to a build without having to understand the underlying system or know where to go in VSTS.  I'd prefer that VSTS is just a generic thing that runs whatever command we tell it to.  A further step would be to define a build language that gets parsed into a pipeline file (or whatever) for consumption, but we can't make steps in that direction (if desired) if we have a tight coupling with VSTS build definitions.

/cc @mmitche as an FYI and in case he has a preference on encapsulating data within build definitions or outside of them.

**Comment by weshaggard** [comment]
>Regarding #2. I'd actually prefer we went the other direction and reduced our coupling on VSTS.

**Comment by mmitche** [comment]
I would actually prefer fewer parameters that flow from the top level to the lower build levels (where the parameters stay the default, hardcode them), but a mechanism that dynamically creates build definitions for PR type cases.

This is closer to what a full pipeline implementation in either VSTS and Jenkins would look like.  Instead of having to parameterize every way you might want to run things, you enable people to edit the pipeline as necessary to get the behavior they want for a specific branch or whatever.

**Comment by chcosta** [comment]
What do you mean by "top level"?  the pipeline file?

Doesn't that assume you know all the ways people will want to run things and constrain flexibility?  I agree with "enable people to edit the pipeline as necessary to get the behavior they want for a specific branch or whatever."

**Comment by weshaggard** [comment]
Here is an example of what I'm referring too:
```
      "BuildParameters": {
        "PB_ConfigurationGroup": "Release",
        "PB_BuildArguments": "-buildArch=x64 -Release -stripSymbols",
        "PB_BuildTestsArguments": "-buildArch=x64 -Release -SkipTests -- /p:ArchiveTests=true /p:EnableDumpling=true",
        "PB_CreateHelixArguments": "/t:CloudBuild /p:ArchGroup=x64 /p:ConfigurationGroup=Release /p:\"EnableCloudTest=true\" /p:\"TestProduct=corefx /p:\"TimeoutInSeconds=1200\" /p:\"TargetOS=Linux\" /p:FilterToOSGroup=Linux /p:\"BuildMoniker=none\"",
        "PB_SyncArguments": "-p -- /p:ArchGroup=x64"
      },
```

We shouldn't be need to duplicate "Release", "x64", "Linux" on every different build step that is happening. If we can script that away and eliminate duplication I would be fine with that as well but I really hate repeating things and it just makes for common mistakes.

**Comment by chcosta** [comment]
I agree

**Comment by mmitche** [comment]
@weshaggard Totally agreed.

I think we should be parameterizing the most common variations that people want to run, but if they do want to run something custom (like varying the test build configuration vs. the create helix arguments), then you should just submit a private with a new version of the pipeline definition/vsts build definitions.

As part of the pipeline work i've identified that there aren't that many variations of a lot of these arguments.  For instance, the create helix args can be constructed off of just "enable tests" and other parameters.

**Comment by wtgodbe** [comment]
Closing this since we're using the YAML files now
