### ISSUE TITLE
There is no test result generated under "System.Data.SqlClient.Stress.Tests"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#16178]
Failed on OSX.1011.Amd64:AnyCPU-Debug in build 20170215.01, under "System.Data.SqlClient.Stress.Tests".

But there is no test result generated. detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170215.01/workItem/System.Data.SqlClient.Stress.Tests/wilogs

**Comment by danmosemsft** [comment]
@saurabh500 can you please look?

**Comment by saurabh500** [comment]
@danmosemsft that's expected. these tests only build in the repo and we run them locally.

**Comment by danmosemsft** [comment]
@MattGal what is the right way to disable a test from running even in outerloop, but allow it to run locally (presumably with some flag)

**Comment by MattGal** [comment]
The "failure" here was an infra bug caused by running > 1 client at once on Macs (since we only really have 5 machines).  I've brought all the prod macs back to 1 instance per machine and understand the bug, will get a fix for that in the pipeline.

As for what we should do for test assemblies which contain no XUnit facts, the right thing to do here is to not send them off to run at all.   Applying some trait makes little sense since both in Helix and Jenkins if you've reached the point of running XUnit you're quite far into execution.    There's lots of ways to do this;  I favor either:

- a custom property set on a given project that prevents test archiving, perhaps listed as "DisableTestExecution" or something since for Jenkins it wouldn't be be archived.  From the helix perspective, this could be used to not zip the test's output directory; if this doesn't happen, there will be no file uploaded, no work item created for it, and no result.

- Alternately, explicitly setting ArchiveTests=False as an MSBuild property in the test's project/ .builds file itself should work around the issue for Helix alone.

**Comment by danmosemsft** [comment]
I see the pattern that you might use @saurabh500 if you don't want tests to run in Jenkins:

```
   12:         public static bool ManualTestsEnabled => !string.IsNullOrEmpty(Environment.GetEnvironmentVariable("MANUAL_TESTS"));
   13  
   14:         [ConditionalTheory(nameof(ManualTestsEnabled))]
```

**Comment by MattGal** [comment]
@danmosemsft  I think this sort of approach only matters when there are actual theories/facts to be skipped.  I do like that style though.

**Comment by danmosemsft** [comment]
Oh, I missed that there were no XUnit tests in it. 

@saurabh500 sounds like maybe worth doing ` ArchiveTests=False as an MSBuild property in the test's project/ .builds `

**Comment by danmosemsft** [comment]
@Jiayili1  this shoudl be fixed
