### ISSUE TITLE
create sockets and open files with CLOEXEC by default

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#16180]
Sockets should not be shared with child processes. So probably it makes sense to add SOCK_CLOEXEC when creating a socket.

https://github.com/dotnet/corefx/blob/7a230270559cfbef056aaafc022cdfd8fd3d829e/src/Native/Unix/System.Native/pal_networking.cpp#L2363

**Comment by Priya91** [comment]
@tmds Why shouldn't sockets not be shared with child processes? Linux allows child processes to inherit all file descriptors from parent to child, hence it's legal to allow inheritance of sockets as well right.

**Comment by tmds** [comment]
> @tmds Why shouldn't sockets not be shared with child processes? Linux allows child processes to inherit all file descriptors from parent to child, hence it's legal to allow inheritance of sockets as well right.

When a child process inherits the file descriptors, it can do anything with them and the parent process can no longer assume it is the sole controller of those descriptors. The file descriptors which are shared are a random snapshot at the time of exec. They can include even sensitive handles which should only be used by the parent. Close-on-exec should be the default. This also applies to files. On open, they should be close-on-exec unless the user explicitly states FileShare.Inheritable.

**Comment by tmds** [comment]
@Priya91 SOCK_CLOEXEC is the default behavior of [python](https://github.com/python/cpython/blob/5ec08cea9574cf53c985af5dbed6bc3d56ff58b7/Modules/socketmodule.c#L4742) and [go](https://github.com/golang/go/blob/3792db518327c685da17ca6c6faa4e1d2da4c33c/src/net/sock_cloexec.go#L21)

**Comment by Priya91** [comment]
@tmds Thanks for the info, I wanted to look into what windows is doing here, haven't had a chance. 
@CIPop @davidsh What's the windows behavior here?

Also for filesystem we have fileshare.inheritable, but do we have an api to allow user to control this behavior for sockets? I don't see any issues in changing the default, will there be any indirect user scenario breaks because of the change?

**Comment by tmds** [comment]
> @tmds Thanks for the info, I wanted to look into what windows is doing here, haven't had a chance.
@CIPop @davidsh What's the windows behavior here?

AFAIK this doesn't exist on Windows.

> but do we have an api to allow user to control this behavior for sockets?

No there is no API for this.
If desired, one way of adding this could be as a SocketOption. The underlying implementation would not use get/setsocketoption but fcntl. This can be considered as a separate issue.

> don't see any issues in changing the default, will there be any indirect user scenario breaks because of the change?

This is a breaking change. But it is breaking something which is very unlikely to be used in practice.

**Comment by stephentoub** [comment]
@karelz, @Priya91, @geoffkizer, I've changed the milestone from Future to 2.0.  This is an easy change to make, the question is just if we want to make it, and if we do, as it does have an observable impact, we should either do so now or not do it at all.  I lean towards making the change.

**Comment by geoffkizer** [comment]
I agree, this seems like the right thing to do.

**Comment by karelz** [comment]
Sounds good. Given it is cheap, I don't have concerns.
@tmds is it something you plan to contribute?

**Comment by tmds** [comment]
@karelz you can assign it to me

**Comment by tmds** [comment]
@stephentoub @Priya91 I put together a sample app that shows how not setting CLOEXEC affects socket close: https://gist.github.com/tmds/493a1c56cb00e453e131a6c3134b76a3.

**Comment by stephentoub** [comment]
@tmds, one specific case I think we'll need to be careful of, or at least think through: our named pipe support on unix is implemented on domain sockets.  It's extremely common to pass anonymous pipes to child processes, and while certainly less common to do so with named pipes, I wouldn't be surprised if folks do so.

**Comment by tmds** [comment]
> It's extremely common to pass anonymous pipes to child processes, and while certainly less common to do so with named pipes, I wouldn't be surprised if folks do so.

The common pattern is that the receiving process expects to use certain fds. Between fork and exec, the parent process fds are setup to match those using dup2. The Process class does this for std{in,out,err}. There is no API for a user to do this for his own file descriptors, so I wouldn't expect developers to be relying on this. Does that make sense? I don't know about the named pipe implementation (yet), but perhaps the same thing is applicable.

**Comment by stephentoub** [comment]
> Does that make sense?

Yes, but that's not the case I was referring to.  I was referring to something along the lines of the AnonymousPipeServerStream example in the MSDN docs:
https://msdn.microsoft.com/en-us/library/system.io.pipes.anonymouspipeserverstream(v=vs.110).aspx
The "server" process creates an AnonymousPipeServerStream, gets the "client" handle, and launches a child process handing off the client handle to it, which the child process then uses to instantiate an AnonymousPipeClientStream.  If that handle were created as CLOEXEC, all such code would break.  Now, that's not the change being proposed here, and this pattern would be much less common for NamedPipeServer/ClientStream: after all, the reason you use names is so that you don't have to pass around handles / descriptors.  I just wanted to call it out as something that could potentially break.
