### ISSUE TITLE
various .csproj are missing a `<ProjectGuid>{$guid}</ProjectGuid>` element

### ISSUE THREAD

**Issue by ghuntley** [dotnet/corefx#1621]
When opening a solution/project with Visual Studio 2015 and then doing a build the `.csproj` is modified to add a `<ProjectGuid>{$guid}</ProjectGuid>` element.  

First noticed this whilst working on ` src/System.ComponentModel.Annotations/tests/System.ComponentModel.Annotations.Tests.csproj`

* For the pull-requests I've been working on (#1619 / #1602) I've been manually removing the definition before commit. 
* Why is this definition missing and should we allow VS2015 to add this stanza and commit this change back with the pull-request?

> "ProjectGuid is simply a unique identifier for the file, unlike `<ProjectTypeGuids>` which directly impacts the IDE behavior." - @sharwell

**Comment by stephentoub** [comment]
> Why is this definition missing

Probably due to folks creating these initially by copying some existing template .csproj that didn't have it.

>  and should we allow VS2015 to add this stanza and commit this change back with the pull-request?

I think it's fine.  @weshaggard?

**Comment by weshaggard** [comment]
I think it is fine to commit the ProjectGuid's as part of change already touching the project file. As @stephentoub mentioned the reason they were missing to begin with is because internally we don't work in VS much and only do command line builds so they were never really noticed.

**Comment by ebickle** [comment]
@weshaggard In System.Collections.Tests.csproj, it appears to be an intentional change. The project reference back to System.Collections.csproj is a file-level one, and includes the comment "Compile tests against the contract, but copy our local-built implementation for testing".

Switching it back results in other compilation errors in System.Collections.Tests, where none of the System.Collections.Generic types in mscorlib can be found at all. In either case I have no way forward; it looks as if it's impossible to locally test any changes to System.Collections.
It's causing grief when

**Comment by ebickle** [comment]
@weshaggard in System.Collections.Tests.csproj, the lack of a project GUID appears to be intentional for some reason. See #1683.

**Comment by weshaggard** [comment]
@ebickle perhaps I'm missing something as I don't understand how the issue you are calling out has any connection to whether or not a csproj file contains a project GUID or not.

**Comment by ebickle** [comment]
@weshaggard In the Visual Studio IDE, once you set the Project GUID and Name the various properties on the project reference become disabled and read-only. I had incorrectly assumed that the build behavior (specifically ReferenceOutputAssembly) would change, but that doesn't appear to be the case.
