### ISSUE TITLE
Look at the gaps in the netfx test running

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#16236]
@ericstj mention we have a test gap in the way we are running the NetFX tests. Eric want to to run the tests same way the customers runs their app on the desktop. currently we create the NetFX runtime folder and we use a config file for the tests to make it point at the assemblies in the Runtime folder which is different than what customers do in the real scenarios

https://github.com/dotnet/corefx/pull/16215

**Comment by tarekgh** [comment]
CC @weshaggard

**Comment by weshaggard** [comment]
I assume this is mostly to test the auto-binding redirect feature. However I suspect we will have a hard time to recreate that environment in our test infrastructure due to our custom nature. However we should definitely try and we should ideally eliminate our generation if we can get RAR to generate it for us.

**Comment by stephentoub** [comment]
We no longer run netfx tests other than for libraries where we have a netfx implementation.
