### ISSUE TITLE
[CI Failure] System.Transactions.Tests hung and timed out build

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#16283]
Found this in a code coverage build, which did not complete due to this. See https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows_prtest/24/consoleFull#10606384068101fac1-935e-4556-95f9-7a0e25ca0b52; note the difference in times on the left.

**Comment by jimcarley** [comment]
Sorry for my lack of knowledge. Where do I find the testresults.xml for this?

**Comment by danmosemsft** [comment]
Again - https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/106/consoleText

@mmitche - do we archive testresults.xml anywhere?
@jimcarley meanwhile you could try looping it overnight locally. I am not sure if there is a better way than putting the xunit command line in a batch file with a loop.

**Comment by mmitche** [comment]
@danmosemsft Probably not.  It's unlikely to show anything too interesting anyway.  I copied the build to a new version which will not abort after 2 hours.  When we see the issue we can login and take a look live on the machine:

https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows_hangdebug/

**Comment by mmitche** [comment]
@danmosemsft It will run every hour, not concurrently.  We should see a failure today.

**Comment by jimcarley** [comment]
Adding @qizhanMS for visibility.

It's not clear to me. Is this an intermittent problem? Do we have an idea of when the problem started happening? Since this only seems to be happening for coverage builds, could there be something we are missing in the initialization of our tests that could cause this?

**Comment by stephentoub** [comment]
Our code coverage runs appear to be hanging because of this.  I logged on to one of the CI machines and grabbed some data from the hung process.

There are two threads that are stuck:
![image](https://cloud.githubusercontent.com/assets/2642209/23214349/56a84e68-f8dc-11e6-9e35-ae8a2ec39c4c.png)
Both of them are blocked waiting for a Monitor to be signaled inside of CommitableTransaction.Commit:
![image](https://cloud.githubusercontent.com/assets/2642209/23214418/a6004ec0-f8dc-11e6-9c3d-32bc4b1a8ac2.png)

One of them is coming from from CloneTxTests.Run with these options:
![image](https://cloud.githubusercontent.com/assets/2642209/23214514/f49f5468-f8dc-11e6-9356-de47805a9736.png)

The other is coming from the TransactionScopeTest.RMFail2 test.

**Comment by jimcarley** [comment]
Both of these tests expect the transaction to timeout, but apparently it is not.

Is there any chance to get a dump when this happens? We need to see what is going on with the TransactionTable, which is used to timeout transactions. We have had issues with this previously, but those issues were the reverse - transactions were timing out up to half a second too early. The TransactionTable uses a timer to trigger timeouts. I don't know if there is an issue with processing timer wake ups or if the timer is misbehaving in some way.

Note that this might also explain the intermittent failures of the NonMsdtcPromoterTest that we have seen due to transactions not timing out.

**Comment by stephentoub** [comment]
@jimcarley, I'll share a dump with you.

I took a look at the TransactionTable.  Not sure exactly what I'm looking for, but there don't appear to be any transactions in the table:
```
? System.Transactions.TransactionManager.TransactionTable
{System.Transactions.TransactionTable}
    CurrentTime: Cannot evaluate expression because a thread is stopped at a point where garbage collection is impossible, possibly because the code is optimized.
    _headBucketSet: {System.Transactions.BucketSet}
    _lastTimerTime: 636233767260197969
    _rwLock: {System.Transactions.CheapUnfairReaderWriterLock}
    _ticks: 144
    _timer: {System.Threading.Timer}
    _timerEnabled: false
    _timerInterval: 512
? System.Transactions.TransactionManager.TransactionTable._headBucketSet
{System.Transactions.BucketSet}
    AbsoluteTimeout: 9223372036854775807
    _absoluteTimeout: 9223372036854775807
    _table: {System.Transactions.TransactionTable}
    headBucket: {System.Transactions.Bucket}
    nextSetWeak: null
    prevSet: null
? System.Transactions.TransactionManager.TransactionTable._headBucketSet.headBucket
{System.Transactions.Bucket}
    _index: 0
    _owningSet: {System.Transactions.BucketSet}
    _previous: null
    _size: 1024
    _timedOut: false
    _transactions: {System.Transactions.InternalTransaction[1024]}
    nextBucketWeak: null
? System.Linq.Enumerable.Count(System.Transactions.TransactionManager.TransactionTable._headBucketSet.headBucket._transactions, t => t != null)
0
```

**Comment by qizhanMS** [comment]
I tried to run the tests using "build -Coverage -BuildTests", all System.Transactions tests passed. What command should I use to get repro on my dev machine?

**Comment by stephentoub** [comment]
I don't believe any of us have repro'd it locally. But it's been happening frequently in the lab. I sent Jim a dump earlier.

**Comment by danmosemsft** [comment]
@jimcarley any luck?

**Comment by jimcarley** [comment]
Not yet.

In the dump we found that the data structures surrounding the transaction timeout processing were in an "unexpected" state, but we have not yet found how that statecould happen. We had one theory revolving around the single half-second timer we use to wake up and check to see if any transactions needed to be timed out. I hypothesized that we could get the data structures into the state in the dump if a second timer wakeup occurred while the thread that was processing the previous wake up was still processing AND the second wakeup caused the thread of the first wakeup to get "canceled" at an inopportune time. But experimentation with multiple timer wake ups like this showed that the first wakeup thread is not canceled when the second wakeup thread gets started.

I may still put in code that tries to avoid having two timer wakeup threads from running at the same time.


I have also experimented with changes that would help to avoid the "hang" by using asynchronous commit, but the tests would still fail if the transactions did not time out. But this approach would be "ugly" for the TransactionScope test because the commit call is made inside the product code for TransactionScope  rather than in the test code. So I would need to run the test on a separate thread and then wait for that thread to set an event indicating that it is done. That wait for event would then have a timeout that is a bit longer than the transaction timeout and it would fail the test if it timed out waiting for the thread executing the test to complete.

**Comment by danmosemsft** [comment]
This hit CI again. Thanks for your work on this -- especially since it might be a product issue

**Comment by qizhanMS** [comment]
Is this time also failed when running code coverage?

**Comment by stephentoub** [comment]
Yes

**Comment by danmosemsft** [comment]
Hi @jimcarley @qizhanMS any further progress on this one? Did you end up doing this:

> I may still put in code that tries to avoid having two timer wakeup threads from running at the same time.

Given this is code coverage only, I'm going to move to Future. Please correct if you wish.

**Comment by danmosemsft** [comment]
@qizhanMS failed a CI job:

https://ci.dot.net/job/dotnet_corefx/job/master/job/netfx_windows_nt_debug_prtest/752/testReport/junit/System.Transactions.Tests/CloneTxTests/Run_cloneType__BlockingDependent__isoLevel__Snapshot__forcePromote__False__completeClone__False__expectedStatus__Aborted_/

```
System.Transactions.Tests.CloneTxTests.Run(cloneType: BlockingDependent, isoLevel: Snapshot, forcePromote: False, completeClone: False, expectedStatus: Aborted) (from System.Transactions.Local.Tests)

Failing for the past 1 build (Since Failed#752 )
Took 6 ms.
Stacktrace

MESSAGE:
Assert.Equal() Failure\r\nExpected: Active\r\nActual: Aborted
+++++++++++++++++++
STACK TRACE:
at System.Transactions.Tests.CloneTxTests.Run(CloneType cloneType, IsolationLevel isoLevel, Boolean forcePromote, Boolean completeClone, TransactionStatus expectedStatus) in D:\j\workspace\netfx_windows---8c0e8fba\src\System.Transactions.Local\tests\CloneTxTests.cs:line 116
```

**Comment by danmosemsft** [comment]
AGain https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/331/consoleFull#-9314352818101fac1-935e-4556-95f9-7a0e25ca0b52

**Comment by danmosemsft** [comment]
@qizhanMS @jimcarley unless you have more data I suggest closing this now so we can hit zero.

**Comment by jimcarley** [comment]
We did not make any more progress on this. Did tests simply get turned off for Code Coverage builds? If yes, because of this?

It is somewhat interesting that it only happens for code coverage builds/runs and only in the lab (as opposed to locally). At least that is what I recall.

**Comment by jimcarley** [comment]
Where would I find test results for code coverage builds? Or do those simply not exist?

The Code_Coverage_Report doesn't tell me about test results. Only what lines of code got covered. But then again, I could be looking at the wrong stuff.

**Comment by danmosemsft** [comment]
To see more you must go up the URL to https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/
Looks like recent runs failed for other reasons https://github.com/dotnet/corefx/issues/28574
And before that a known build issue
Looking way back to the last success on Mar 1 it seems the missing coverage was due to missing PDB -- which I see on some other libraries as well.
```
  Using D:\j\workspace\code_coverage---b14a30e5\bin\testhost\netcoreapp-Windows_NT-Debug-x64\ as the test runtime folder.
  Executing in D:\j\workspace\code_coverage---b14a30e5\bin\tests\System.Transactions.Local.Tests\netcoreapp-Windows_NT-Debug-x64\ 
  ----- start 12:33:06.00 ===============  To repro directly: ===================================================== 
  pushd D:\j\workspace\code_coverage---b14a30e5\bin\tests\System.Transactions.Local.Tests\netcoreapp-Windows_NT-Debug-x64\
  python DumplingHelper.py install_dumpling
  for /f "delims=" %a in ('python DumplingHelper.py get_timestamp') do @set __TIMESTAMP=%a
  set XUNIT_PERFORMANCE_MIN_ITERATION=1
  set XUNIT_PERFORMANCE_MAX_ITERATION=1
  set XUNIT_PERFORMANCE_MAX_ITERATION_INNER_SPECIFIED=1
  call D:\j\workspace\code_coverage---b14a30e5\packages/OpenCover\4.6.519\tools\OpenCover.Console.exe -oldStyle -filter:"+[System.Transactions.Local]*" -excludebyfile:"*\Common\src\System\SR.*" -nodefaultfilters -excludebyattribute:*.ExcludeFromCodeCoverage* -skipautoprops -hideskipped:All -threshold:1 -returntargetcode -register:user -target:D:\j\workspace\code_coverage---b14a30e5\bin\testhost\netcoreapp-Windows_NT-Debug-x64\\dotnet.exe -output:D:\j\workspace\code_coverage---b14a30e5\bin/tests/coverage\System.Transactions.Local.Tests.coverage.xml -targetargs:"xunit.console.netcore.exe System.Transactions.Local.Tests.dll  -xml testResults.xml -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=IgnoreForCI -notrait category=failing "
  python DumplingHelper.py collect_dump 0 C:\Users\DOTNET~1\AppData\Local\Temp\CoreRunCrashDumps  System.Transactions.Local.Tests D:\j\workspace\code_coverage---b14a30e5\bin/runtime/netcoreapp-Windows_NT-Debug-x64/,D:\j\workspace\code_coverage---b14a30e5\bin/tests/System.Transactions.Local.Tests/netcoreapp-Windows_NT-Debug-x64/
  popd
  ===========================================================================================================
  Dumpling cannot be installed due to: HTTP Error 403 Site Disabled
  Executing: D:\j\workspace\code_coverage---b14a30e5\bin\testhost\netcoreapp-Windows_NT-Debug-x64\dotnet.exe
  xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.
  
  Discovering: System.Transactions.Local.Tests
  Discovered:  System.Transactions.Local.Tests
  Starting:    System.Transactions.Local.Tests
  Finished:    System.Transactions.Local.Tests
  
  === TEST EXECUTION SUMMARY ===
     System.Transactions.Local.Tests  Total: 295, Errors: 0, Failed: 0, Skipped: 0, Time: 14.061s
  Committing...
  No results, this could be for a number of reasons. The most common reasons are:
      1) missing PDBs for the assemblies that match the filter please review the
      output file and refer to the Usage guide (Usage.rtf) about filters.
      2) the profiler may not be registered correctly, please refer to the Usage
      guide and the -register switch.
  ----- end 12:33:23.98 ----- exit code 0 ----------------------------------------------------------
```

Given the other issue I doubt we will get more data soon. We can either clsoe this and reopen if it reoccurs (what I suggest) or leave it open.

**Comment by jimcarley** [comment]
Interesting. In that Mar 1 run, all the SysTx tests passed. And it ran the 5 OuterLoop tests, too.

In looking at the CloneTx tests again, there are 7 that we should probably move to OuterLoop because each one takes 1.5+ seconds because they are waiting for the transaction to timeout. But we can do that later.

I agree that we can close this for now and re-open it if necessary.

Closing with this comment.
