### ISSUE TITLE
Span: System.Memory is missing `unchecked` annotations

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#16298]
It is causing different behaviors between debug and release builds.

Repro: Run this against netfx debug build of System.Memory:

```c#
static void Main() {
    var span = new Span<int>(new int[1]);
    Console.WriteLine(span[-5]);
}
```

Actual result: System.OverflowException
Expected result: System.IndexOutOfRangeException

**Comment by JonHanna** [comment]
CC @dennisdietrich

**Comment by dennisdietrich** [comment]
This looks like it's trivial to fix. Even so, I wouldn't want to submit a PR without a unit test. However, the tests in ```\src\System.Memory\tests\``` don't seem to pickup the assembly compiled from the source in ```\src\System.Memory\src\```. What am I missing here?

**Comment by danmosemsft** [comment]
I edited `src\system.memory\src\System\Span.Extensions.cs` to break it, built `src` with `msbuild` then went to `tests` and ran `msbuild /t:buildandtest` and indeed I broke the tests.

I'm not an expert on the build system though.

**Comment by dennisdietrich** [comment]
@danmosemsft You're right. But try breaking ```Span<T>```, that shouldn't work. Turns out the type is also checked into coreclr: https://github.com/dotnet/coreclr/blob/dcd5eeaf0948e2c5abed49b1c025d65f85c921d3/src/mscorlib/src/System/Span.cs
And I'm pretty sure the tests run against that:
```csharp
var spanType = typeof(Span<>);
Console.WriteLine(spanType.Assembly);
Console.WriteLine(spanType.Assembly.Location);
```
```
System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
R:\corefx\bin\testhost\netcoreapp-Windows_NT-Debug-x64\shared\Microsoft.NETCore.App\9.9.9\System.Private.CoreLib.ni.dll
```
Tests aside, is there a good reason for the type existing in two places?

**Comment by jkotas** [comment]
> is there a good reason for the type existing in two places?

The corefx copy is lower performance version that runs on existing runtimes (.NET Framework in particular).

**Comment by dennisdietrich** [comment]
I see. That still leaves the issue of the tests targeting the wrong binary though.

**Comment by mellinoe** [comment]
The tests are targeting the ".NET Core version" of System.Memory, which is correct based on how things are set up right now. We aren't currently running any of our tests against the ".NET Standard version" of things, except where that's the only version around (if that made sense). In order to work around that in the time being and run the System.Memory tests against the "slow span" version built here, you can:

1. Open up src/System.Memory/src/Configurations.props and remove all the lines with "netcoreapp" in them
2. Rebuild src/System.Memory/src/System.Memory.csproj
3. Re-run the tests

@ahsonkhan

**Comment by ahsonkhan** [comment]
@joshfree, the fix for this is already in PR #16416 submitted by @dennisdietrich.
I don't think this issue should be assigned to me.

**Comment by joshfree** [comment]
@ahsonkhan please help review the PR and see that this issue gets closed out

**Comment by karelz** [comment]
We plan to pull the annotations - see comments in #16416.
