### ISSUE TITLE
Solutions missing cross-platform configurations

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#16353]
We used to have the option in VS of selecting which configuration of the project you want to work with, e.g. a pull down to select Windows vs Linux vs macOS for Debug vs Release.  Now in a solution like System.Net.Sockets, there's only Debug vs Release, which means when working on the Unix side of a project, we don't get IntelliSense in the Unix-specific code.  What's the recommended approach now?

cc: @weshaggard

**Comment by weshaggard** [comment]
That was intentional to try and avoid the explosion of combinations. The recommendation is the open up the solution configuration and change to the Linux/Windows/etc configuration you want and enable build it that way. Unfortunately there isn't an easy way to do that from the toolbar but you can still do it.

**Comment by weshaggard** [comment]
Also remember that you will still need to at least built that configuration from build.cmd once before you can build that individual project for that configuration.

**Comment by stephentoub** [comment]
> The recommendation is the open up the solution configuration and change to the Linux/Windows/etc configuration you want and enable build it that way.

Meaning now to switch back and forth between them I need to edit the solution file, reload the solution, then to switch again re-edit the solution and re-load?  That's very unfortunate.

**Comment by weshaggard** [comment]
You don't need to reload the solution you just need to edit the solution configuration in VS. Right click on the Solution and select configuration manager (or in the configuration drop down on the toolbar and selecting configuration manager). Then change the configuration for the project you want to build.

However that state does update the solution file which is unfortunate but you can just undo those edits instead of committing them.

**Comment by stephentoub** [comment]
> You don't need to reload the solution you just need to edit the solution configuration in VS. Right click on the Solution and select configuration manager (or in the configuration drop down on the toolbar and selecting configuration manager). Then change the configuration for the project you want to build.

Ah, I see, ok.  Unfortunate but not terrible. Thanks.
