### ISSUE TITLE
Add new documentation for new users that has step-by-step instructions

### ISSUE THREAD

**Issue by dhoehna** [dotnet/corefx#16482]
# problem
I had problems on knowing what tools i needed to get corefx to run, test, and get code coverage because I did not know where to look.

# explanation
I had a hard time getting corefx to run because I was expecting to find step-by-step documentation on how to get corefx running on my computer.  Because I was looking for a step-by-step guide, I ignored the page about [building CoreFX on windows](https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md) because I thought "I'm on windows.  I never have to build anything on windows."

# solution
Add additional documentation with the step-by-step instructions for installing tools, building, and testing corefx.  This way, new users can follow the step-by-step guide, but also read the "why" that is in the already existing documentation.

**Comment by karelz** [comment]
Why did you ignore the page with [windows instructions](https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md)? Was it hard to discover? Or did you misjudge its content based on title?

If the content is there, I would rather focus on making sure it is discoverable rather than duplicating the content.

**Comment by dhoehna** [comment]
I misjudged the content based on the title.  Also, I was expecting to find an ordered list.  More bullet points so I can follow the information word for word.

**Comment by ViktorHofer** [comment]
closing for age. the current instructions in master should suffice.
