### ISSUE TITLE
Investigate handle usage in src/common/src/Interop/Windows/secur32/Interop.LSAStructs.cs

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#1650]
This issue came up but was not addressed in the initial commit of System.Security.Principal and System.Security.Principal.WIndows.  See the constructor in UNICODE_INTPTR_STRING.  The comment was regarding whether we need to add DangerousAddRef / DangerousReleasing around DangerousGetHandle.

**Comment by bartonjs** [comment]
Since this is copying an IntPtr into a struct, I'm not really seeing anything better to do here.  Particularly since there's an IntPtr overload.

https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/Windows/sspicli/Interop.LSAStructs.cs#L73

About the only thing I can think of to be safer is to make the IntPtr overload convert to a SafeLocalAllocHandle with ownsHandle=false; which would enable the other version to keep the SafeHandle object lifetime around...

Any thoughts @stephentoub?

**Comment by stephentoub** [comment]
I've not looked at all the usage of it to know what usage patterns are.  Just seems dangerous.  But if you think it's ok, that it's used in such a constrained way as to not be dangerous, etc., we can just close this.
