### ISSUE TITLE
FileSystemWatcher_4000_Tests.FileSystemWatcher_IncludeSubDirectories test failing in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1657]
This test has failed multiple times in the last few days:
```
MESSAGE:
Didn't observe a created event within 500ms
+++++++++++++++++++
STACK TRACE:
at Utility.ExpectEvent(WaitHandle eventOccured, String eventName, Int32 timeout) in d:\j\workspace\dotnet_corefx_windows_release\src\System.IO.FileSystem.Watcher\tests\Utility\Utility.cs:line 94 at FileSystemWatcher_4000_Tests.FileSystemWatcher_IncludeSubDirectories_Directory() in d:\j\workspace\dotnet_corefx_windows_release\src\System.IO.FileSystem.Watcher\tests\FileSystemWatcher.IncludeSubDirectories.cs:line 67
```

**Comment by stephentoub** [comment]
Likely the same root cause as #1165.

**Comment by chcosta** [comment]
I think the issue with this test is due to how Windows performs event dispatching, and this test's use of AutoResetEvent which is not guaranteed to handle an event.  I have a "fix" for this on my private dev box, but there are too many unknown variables at the moment for me to propose the fix as a valid solution.  I'll continue investigating this issue.

**Comment by stephentoub** [comment]
Thanks, Chris.

**Comment by stephentoub** [comment]
FileSystemWatcher_4000_Tests.FileSystemWatcher_Changed_LastWrite_File failed with a similar error in http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release/481/testReport/junit/(root)/FileSystemWatcher_4000_Tests/FileSystemWatcher_Changed_LastWrite_File/
```
MESSAGE:
Didn't observe a changed event within 500ms
+++++++++++++++++++
STACK TRACE:
at Utility.ExpectEvent(WaitHandle eventOccured, String eventName, Int32 timeout) in d:\j\workspace\dotnet_corefx_windows_release\src\System.IO.FileSystem.Watcher\tests\Utility\Utility.cs:line 94 at FileSystemWatcher_4000_Tests.FileSystemWatcher_Changed_LastWrite_File() in d:\j\workspace\dotnet_corefx_windows_release\src\System.IO.FileSystem.Watcher\tests\FileSystemWatcher.Changed.cs:line 24
```

**Comment by chcosta** [comment]
I spent quite a bit of time digging into this, and didn't come up with anything conclusive.

I don't believe that any of the unreliability we've seen is related to our use of AutoResetEvents.  There is a note about autoreset events and overlapped structures in the msdn documentation (https://msdn.microsoft.com/en-us/library/windows/desktop/ms684342(v=vs.85).aspx), but it doesn't directly apply to our scenario and converting auto reset events to manual reset events or directly watching events reported to FSW did not lead me to believe that AutoResetEvents were at all related to the stability of the tests.

FileSystemWatcher is essentially a wrapper class around the ReadDirctoryChanges kernel function.  There are multiple reports online of ReadDirectoryChangesW not returning every event.  Here are two of the common theories which I have investigated.

Theory 1 is that during heavy load, the buffer will overflow and cause you to lose events.  While this may be true, it is not true of our testing scenario.  Increasing buffer size did not have any impact on the frequency of lost event occurrences, and buffer overflows were not detected in either case.  

Theory 2 is that the kernel queues up disk-write requests and you cannot make a guarantee when those requests are actually physically committed to disk and reported by ReadDirectoryChanges.  There is some credence to this theory, but I don't think it's the complete story.  I have noticed, that if we add a thread sleep between the file creation event, and our check for the creation event, then we no longer see failure occurrences.  It is not clear if this means that the disk has processed the change and fired the event, or we've simply perturbed the state of the test enough to mask the underlying issue.

Reducing the cycle time (listen for events, then dispatch them, then resume listening); did decrease the occurrence of lost events, but nothing conclusive, and this did not eliminate the problem.  It would be nice to know what is the behavior of Overlapped.Unpack?  We use Overlapped.Unpack to retrieve the overlapped structure, and then we directly access the _FILE_NOTIFY_INFORMATION blocks from the overlapped buffer.  What is the OS doing with events during this phase before we free the overlapped structure again? I wrote a helper function to dump the buffer after we've already given up on receiving an event, but it didn't appear that any late event had occurred which got put into the buffer but missed in our initial read.  It seems possible that the buffer is being locked while we iterate through notifications and that events fired during this phase are missed. I ran another experiment where I setup a 2nd overlapped method to listen for events while the 1st IOCompletion callback method was handling events, I found nothing to indicate that we were missing events or there was a buffer overflow.  Another interesting note is that the buffer memory address does not appear to be fixed (except when being unpacked and read from) which makes tracking this down even more difficult.

Using one thread to listen for events and then dispatch them to another thread for dispatching events did appear to reduce the frequency of lost event occurrences, but this did not eliminate the problem.  It seems possible that if you had a listening thread queuing events and a separate dispatch thread to act on the event queue, you could reduce the occurrence even further though I'm not convinced that this would eliminate the problem. 

Though my investigation is not exhaustive, I have seen enough evidence to believe that file events are being lost somewhere along the way.

Whether ReadDirectoryChanges is not reporting all events (likely) or we are unable to acquire all events reported (less likely, but possible), it seems, to me, that our implementation has opted for simplicity and performance over reliability.  If we are ok with our current implementation, then we may need to play games with our current "flaky" tests to ensure that they are resilient to the underlying systems failings.  If we want to focus on reliability, then we need to look at coming up with an entirely new implementation of FileSystemWatcher such as using "FindFirstChangeNotification" and a Windows Change Journal instead of ReadDirectoryChanges.
