### ISSUE TITLE
Remove local resolving in System.Security.Cryptography.Xml

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#16586]
Local resolving is defined in CryptoHelpers class
see more info about this issue in: https://github.com/dotnet/corefx/pull/16545

This is currently blocked on https://github.com/dotnet/corefx/issues/16585

**Comment by bartonjs** [comment]
The local resolving (currently called `CreateFromKnownName` just functions as a non-reflection-based accelerator for using CryptoConfig.  The create method itself falls back to CryptoConfig if the strongly-typed lookup fails.

Since this helps keep rd.xml simple for AOT scenarios, and it's not a "we lost extensibility" problem, we should just leave this as-is.
