### ISSUE TITLE
Port System.Security.Cryptography.Csp to Unix/OSX

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#16585]
(scoped to just Security)

As part of figuring out issue https://github.com/dotnet/corefx/issues/16563 we found out that there are more PlatformNotSupportedException-s than expected

CryptoConfig.CreateFromName for some strings may produce PlatformNotSupported exceptions (because System.Security.Cryptography.Csp is missing)

cc: @steveharter @danmosemsft

**Comment by danmosemsft** [comment]
@krwq I'll put you on the thread. Sorry

**Comment by karelz** [comment]
FYI: Scoped just to Security

**Comment by danmosemsft** [comment]
https://github.com/dotnet/standard/issues/235 tracks whether this is required by standard
EVen if not we could choose to try to implement for Unix.

**Comment by karelz** [comment]
I flipped it to 2.0 to force us make the decision in time - I am not sure how much are bugs in dotnet/standard monitored ...

**Comment by steveharter** [comment]
There are two ways to get the raw CryptoConfig to work with the Csp types:
1) Easy: use the neutral string when calling CryptoConfig (e.g. "Aes" instead of "AesCryptoServiceProvider") and modify CryptoConfig to create the corresponding platform specific type (using Aes.Create() which will create Cng or OpenSsl version).
-- Could also map "AesCryptoServiceProvider" to equivalent of "Aes" to create portable type.
2) Not easy: enable S.S.C.Csp.dll to support Linux. These means for Linux, cross-compile the csp types against the corresponding openssl code in S.S.C.Algorithms. Currently every type in csp assembly throws PNSE under Linux.

I'm assuming #2 as that has been the longer-term plan. I believe we also want the Cng types as well.

FWIW here's the CSP strings in netfx CryptoConfig:
AesCryptoServiceProvider
DESCryptoServiceProvider
MD5CryptoServiceProvider
RC2CryptoServiceProvider
SHA1CryptoServiceProvider
SHA256CryptoServiceProvider
SHA384CryptoServiceProvider
SHA512CryptoServiceProvider
TripleDESCryptoServiceProvider
AesCryptoServiceProviderType
SHA1CryptoServiceProviderType
SHA256CryptoServiceProviderType
SHA512CryptoServiceProviderTypeMD5CryptoServiceProviderType
DSACryptoServiceProviderType
DESCryptoServiceProviderType
RC2CryptoServiceProviderType
RNGCryptoServiceProviderType
RSACryptoServiceProviderType
TripleDESCryptoServiceProviderType

**Comment by danmosemsft** [comment]
@karelz given usage and the discussion in https://github.com/dotnet/standard/issues/235 I believe this is a must have for 2.0.
For example RSACryptoServiceProvider has 30% usage in the top Unity apps (at least some likely by BouncyCastle, but that's immaterial)

Can we cost this?

**Comment by karelz** [comment]
@danmosemsft already costed in our System.Security OneNote page :)

**Comment by danmosemsft** [comment]
@steveharter what's your expected ETA for this?

We see CSP absence when testing API compat of popular nuget packages. When we rank PNSE exceptions by popularity, the CSP types together are top of all unimplemented types so it's basically the biggest hole remaining.

**Comment by danmosemsft** [comment]
Note that for some reason `SHA256CryptoServiceProvider`, `SHA384CryptoServiceProvider`, and `SHA512CryptoServiceProvider` are not implemented even on Windows.

I opened https://github.com/dotnet/standard/issues/269 to ask about whether they should be in the standard. Ideally they'd be in Windows either way, but that's not tracked by this issue which concerns stuff that's in Standard.

**Comment by steveharter** [comment]
@danmosemsft I'll start tomorrow; ETA next week
