### ISSUE TITLE
HMACSHA256/HMAC.Create() throw PNSE

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#16640]
cc: @bartonjs @danmosemsft 

HMAC.Create throws PNSE where it could potentially work by simply using a constructor

Is this something we should possibly support?

**Comment by karelz** [comment]
@steveharter can you please comment?

**Comment by bartonjs** [comment]
`HMAC.Create()` is meaningless.  What HMAC?

`HMACSHA256.Create()` is `HMAC.Create()`.

Use `new HMACSHA256()`.

**Comment by stephentoub** [comment]
This is confusing, though. For some of these types we say "don't use the ctor, use the Create method", but for others at say "don't use the Create method, use the ctor". How does someone know what to do? Why not add HMACSHA256.Create, for example?

**Comment by stephentoub** [comment]
Plus, regarding "What HMAC?", isnt there already an answer? "Whatever desktop does"

**Comment by bartonjs** [comment]
Desktop has an answer (the default HMAC, duh); but it makes no sense.  Anyone who calls it has bugs (or is the kind of person which makes us never able to upgrade defaults).

The answer is "if the algorithm class has a ctor, use it; otherwise use a Create method".  I wanted HMAC.Create cut from netstandard; maybe I can at least mark it Obsolete.  AsymmetricAlgorithm has the same problem... you want some algorithm.  Great, is it encryptable? (RSA) Signable? (RSA, DSA, ECDSA) or just key agreement? (DH, ECDH)

**Comment by krwq** [comment]
@bartonjs what about creating overloads like this then to make it less confusing:
```csharp
AsymmetricAlgorithm Create(AssymetricAlgorithmType algorithmType);

enum AssymetricAlgorithmType
{
  Encryptable,
  Signable,
  KeyAgreement
}
```

anyway PSNE is not a good exception to get - wouldn't it be better to throw something like:
`new InvalidOperationException("Use blah instead.")`

**Comment by bartonjs** [comment]
@krwq Doesn't help, each algorithm them has algorithm-specific options :smile:

**Comment by stephentoub** [comment]
@bartonjs, this still doesn't make sense to me.

HMAC.Create(string) takes an argument specifying exactly which algorithm to create, as documented on MSDN:
https://msdn.microsoft.com/en-us/library/kczffhwa(v=vs.110).aspx
yet we throw PNSE in Core.  How is the desktop behavior there so problematic that we need to break compat?

HMAC.Create() is documented on MSDN to create an SHA1 HMAC:
https://msdn.microsoft.com/en-us/library/3a6y9t8s(v=vs.110).aspx
yet we throw PNSE in Core.  How are the docs ambiguous enough here that we need to break compat?

Yes, if derived types don't provide their own Create method, they'll inherit the state from the base and get the wrong kind... but that's inherent to any static factory methods on non-sealed types, and isn't specific to this case.  I can see discouraging further adoption of these methods, but why cause existing usage to break?  And how is the non-descript PNSE (without a message) getting thrown going to steer people in the right direction?

**Comment by bartonjs** [comment]
As it says on MSDN, it **by default** returns "the SHA-1 implementation of HMAC".  In Desktop if *any* executed library in the process decides to do `CryptoConfig.AddAlgorithm(typeof(HMACSHA256), "System.Security.Cryptography.HMAC");` any caller of this code is now using HMACSHA256 instead of HMACSHA1.

Will their code crash? Probably not.  HMAC has no sub-options.  They'll just generate a wrong-sized and wrong-valued value while expecting HMACSHA1.  Does the code work in almost all instances? Yes, because CryptoConfig isn't random.  Does it do what the method designer (most likely) intended? No, because if the system default changes to "a better HMAC" then your code fails. And if some library decided that in their contexts they wanted HMACSHA256 as the "default HMAC" the rest of the process is dragged along (for better... or, more likely... worse).

(Desktop also suffers in that `CryptoConfig.AddAlgorithm(typeof(string), "System.Security.Cryptography.HMAC");` is also a legal line of code to write, which just makes the callers of HMAC.Create() crash when it hard-casts to HMAC.)

So, we could hard-code HMAC.Create() to `return new HMACSHA1()` to make Core do what users expect from Desktop.  Or we could carry forward the terrible that is CryptoConfig.  Or we could throw PNSE (and mark it Obsolete in the contracts) because it's a method that never should have existed and we want people to stop using.

In security, nothing should be a surprise.  HMAC.Create() is just a timebomb of surprise on Desktop.

**Comment by stephentoub** [comment]
> if any executed library in the process decides to do CryptoConfig.AddAlgorithm(typeof(HMACSHA256), "System.Security.Cryptography.HMAC"); any caller of this code is now using HMACSHA256 instead of HMACSHA1.

In .NET Core, AddAlgorithm throws PlatformNotSupportedException:
https://github.com/dotnet/corefx/blob/74faad990a45f99a530038af213196c6c354952b/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/CryptoConfig.cs#L283
so how exactly does someone get into the concerning situation in Core?

**Comment by bartonjs** [comment]
While I'm still not a fan of the sub-algorithm `Create()` methods, I've been convinced by the mantle of compat that they should be done.

I'd probably argue in favor of hard coding the default as the only answer.  Particularly AsymmetricAlgorithm.Create(), since CryptoConfig can't create the opaque object that RSA.Create() returns.

**Comment by stephentoub** [comment]
> I'd probably argue in favor of hard coding the default as the only answer

I'm fine with that (and it's indistinguishable from accessing CryptoConfig as long as AddAlgorithm continues to throw PNSE and CryptoConfig doesn't access mutable configuration data).

**Comment by bartonjs** [comment]
As much as I'm not a fan of CryptoConfig, in particular for the "give me some HMAC, I don't care what, so long as you never ever change what you give me" path; copying the implementation from netfx will lead to the most stability (including if CryptoConfig starts supporting mutation on .NET Core).

CryptoConfig already has the "generic HMAC == HMACSHA1" entry (https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/CryptoConfig.cs#L161), so what needs to be done here is:

* Make HMAC.Create() be `return Create("System.Security.Cryptography.HMAC")`
* Ensure that HMAC.Create(string) is deferring directly to CryptoConfig.CreateFromName(algorithmName).
* Add a test which shows that HMAC.Create() and `new HMACSHA1()` with the same key and same input data produce the same output.

**Comment by WinCPP** [comment]
@bartonjs @karelz  As per [this](https://github.com/dotnet/corefx/issues/16640#issuecomment-292990506) comment, I added code to make [HMAC.Create(string)](https://github.com/dotnet/corefx/blob/ec2a6190efa743ab600317f44d757433e44e859b/src/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/HMAC.cs#L31-L34) defer to `CryptoConfig.CreateFromName(algorithmName)`. But that sets up a cycle between projects giving following error. Not sure if I am doing the right thing.
```
M:\corefx\pkg\frameworkPackage.targets(108,5): error : Cycle detected for M:\corefx\bin\Windows_NT.AnyCPU.Debug\System.Security.Cryptography.Encoding\netcoreapp\System.Security.Cr
yptography.Encoding.dll. [M:\corefx\pkg\Microsoft.Private.CoreFx.NETCoreApp\Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
M:\corefx\pkg\frameworkPackage.targets(108,5): error : System.Security.Cryptography.Encoding > System.Security.Cryptography.Primitives > System.Security.Cryptography.Algorithms >
System.Security.Cryptography.Encoding [M:\corefx\pkg\Microsoft.Private.CoreFx.NETCoreApp\Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
M:\corefx\pkg\frameworkPackage.targets(108,5): error : Cycle detected for M:\corefx\bin\AnyOS.AnyCPU.Debug\System.Security.Cryptography.Primitives\netcoreapp\System.Security.Crypt
ography.Primitives.dll. [M:\corefx\pkg\Microsoft.Private.CoreFx.NETCoreApp\Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
M:\corefx\pkg\frameworkPackage.targets(108,5): error : System.Security.Cryptography.Primitives > System.Security.Cryptography.Algorithms > System.Security.Cryptography.Primitives
[M:\corefx\pkg\Microsoft.Private.CoreFx.NETCoreApp\Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
```

**Comment by steveharter** [comment]
For the other Create methods in Primitives, we throw PNSE because of this.

**Comment by bartonjs** [comment]
Ah, HMAC and friends are in Primitives, but CryptoConfig is in Algorithms.  Yeah, that can't work.

That means it also can't return any specific instance of HMAC (the "hard-code return new HMACSHA1()" strategy), since they're all in Algorithms.  (I thought HMAC was in Algorithms)

So... this might be the opposite of easy; in that it requires collapsing Primitives and Algorithms (and probably Encoding as a consequence), or type-forwarding a bunch of stuff out... which might not even be legal.

@weshaggard Any thoughts? I'll admit that I'm not a fan of the too-low-a-level Create methods so I'm content for them to be marked [Obsolete(true)] and/or throw a PrinterOnFireException.  Especially this close to the end I don't think we want to crack apart our existing layering...

**Comment by steveharter** [comment]
FWIW link to CryptoConfig PR: https://github.com/dotnet/corefx/pull/13734

>>Per offline discussion, CryptoConfig class was placed in S.S.C.Algorithms as it needs access to the Oid class in S.S.C.Encoding. This means the static Create methods added to S.S.C.Primitives throw PNSE. CryptoConfig could not be placed in S.S.C.Primitives as it wouldn't be able to reference Oid\S.S.C.Encoding without an cyclic assembly reference. There are alternatives to remove these PNSE including x-compile Oid and\or CryptoConfig, combining assemblies, moving types, etc but considered not worth the cost at this time. The workaround is to have consumers call CryptoConfig.CreateFromName directly.

**Comment by karelz** [comment]
@WinCPP I am amazed at the bad luck you have with CoreFX issues. I will soon start to doubt every new "easy" issue you pick - based on the trend so far, it will have a good chance to turn into the opposite of easy as Jeremy said above :)
And while I know you have fun with these difficulties on the road and you don't mind them, it still amazes me :)

Anyway, thanks for your help to uncover these hidden complexities! We appreciate your help.

**Comment by WinCPP** [comment]
@karelz I'm lucky that I'm having this bad luck ;-)

So what do we do with this issue...? May I consider that this is not to be fixed?

**Comment by bartonjs** [comment]
Yeah, since we apparently already discussed the inverted dependency and I forgot about it, I think I'm going to close this issue.  Thanks for looking into it, @WinCPP; sorry I was wrong about it being easy :smile:.
