### ISSUE TITLE
Failure in System.Threading.OverlappedTests

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16655]
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_release/lastCompletedBuild/testReport/(root)/OverlappedTests/PropertyTest1/

Note that the Assert.Equal's in this test file are backwards -- the expected value is supposed to go first. So it's actually expecting 0 and getting 2. Please fix...

https://github.com/dotnet/corefx/blob/ec2a6190efa743ab600317f44d757433e44e859b/src/System.Threading.Overlapped/tests/OverlappedTests.cs#L39

```
MESSAGE:
Assert.Equal() Failure\r\nExpected: 2\r\nActual: 0
+++++++++++++++++++
STACK TRACE:
at OverlappedTests.PropertyTest1() in D:\j\workspace\outerloop_win---65ef7d78\src\System.Threading.Overlapped\tests\OverlappedTests.cs:line 40
```

@kouvel @alexperovich

**Comment by danmosemsft** [comment]
I can't figure out what this is. The only thing I notice is that it could happen if somehow two Overlapped classes concurrently got the same OverlappedData from the PinnableBufferCache. Don't know how that could be possible though.

https://github.com/dotnet/coreclr/blob/68f72dd2587c3365a9fe74d1991f93612c3bc62a/src/mscorlib/src/System/Threading/Overlapped.cs#L252

**Comment by Jiayili1** [comment]
Failed here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_release/114/consoleText

**Comment by stephentoub** [comment]
> The only thing I notice is that it could happen if somehow two Overlapped classes concurrently got the same OverlappedData from the PinnableBufferCache. Don't know how that could be possible though.

I imagine it could also happen with misuse such that one thread freed the overlapped concurrently with another thread still using it, and then another thread getting another overlapped that then uses the same overlapped data that was returned from being freed.

**Comment by danmosemsft** [comment]
@kouvel can you please take a look?

**Comment by danmosemsft** [comment]
I suggest we leave in 2.0 for now as this may possibly be a significant product defect.

**Comment by stephentoub** [comment]
I looked into this more.  I believe it's a test bug, and it's actually a little surprising it's not failing more often.

The runtime doesn't clear the offset state from NativeOverlappeds when they're returned to its pool, nor does Overlapped do so when it takes them out, so there's no guarantee the value of these properties will be 0 when an overlapped is constructed.  This is easily seen in a short repro:
```C#
using System;
using System.Threading;

class Program
{
    static unsafe void Main()
    {
        for (int i = 0; i < 4; i++)
        {
            var o = new Overlapped();
            Console.WriteLine(o.OffsetHigh + ":" + o.OffsetLow);
            o.OffsetLow = 123;
            o.OffsetHigh = 456;
            Overlapped.Free(o.Pack(delegate { }, null));
        }
    }
}
```
Very few other tests happen to change these values on their instances, but the MultipleOperationsOverSingleHandle test does set the value to 2... if the order in which xunit ran the test was such that MultipleOperationsOverSingleHandle ran, set the value to 2, put back the NativeOverlapped, and then PropertyTest1 ran next and pulled out that same instance, it would find the value of 2 and fail.

Unless someone disagrees, I'll simply update the test.  Note that there's even a comment in the source here:
https://github.com/dotnet/corefx/blob/master/src/System.Threading.Overlapped/src/System/Threading/ClrThreadPoolBoundHandleOverlapped.cs#L28
about the runtime not resetting these values, so it appears to be by design.
