### ISSUE TITLE
Add 32-bit version of ComplexTests

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#16675]
Broken down from #13592

PR #13572 marked a few tests to be 64-bit only, given that the assumptions they make were only meant for 
64-bit runs. 

Tests: https://github.com/dotnet/corefx/pull/13572/files#diff-19973eb77d5f57cf6c8661e7fe588dc9

**Comment by danmosemsft** [comment]
@hughbe might be up your alley if you want.

**Comment by mellinoe** [comment]
I'll take a look at these.

**Comment by mellinoe** [comment]
I just looked at the first case that is failing, and I wouldn't be surprised if all the test cases are because of the same issue. On 32-bit .NET Core, `Math.Cos(double.MaxValue)` returns `0.90578110220707042`, and on 64-bit .NET Core, it returns `-0.99998768942655991`. The tests are written to expect the negative value, and thus fail on 32-bit.

Historically, `Math.Cos(double.MaxValue)` has just returned `double.MaxValue` (and it's [documented as such](https://msdn.microsoft.com/en-us/library/system.math.cos%28v=vs.110%29.aspx) on .NET Framework). Recently, though, we changed the implementation to just forward to the CRT on Windows (https://github.com/dotnet/coreclr/pull/4847), so the method no longer just returns the unchanged parameter when it is out of range.

@tannergooding

**Comment by tannergooding** [comment]
**As some context:**
32-bit always just ran the CRT version (https://github.com/dotnet/coreclr/pull/4847/files#diff-884cab80438864e5dc66c7e4c1a3c723L144, comment is on L127). Only the 64-bit version forwarded and it had completely different allowed ranges because of this.

Always using the CRT implementation is better because it is faster and allows a greater range of inputs -- the domain of `Cos` is (−∞, +∞).

**Cause of Failure:**
The 32-bit and 64-bit implementation of `Cos` are significantly different. I can provide links and more details on this offline (this falls under the realm of licensed proprietary information).

**Suggested Short-Term Fix:**
Just add 32-bit specific tests that validate the correct value (or branch on Environment.Is64BitProcess) to properly validate values in the upper or lower bounds of the input domain that are not expected to be exact (such as Min/Max Value). Positive/Negative Infinity would be a value on the upper/lower bound that is expected to be exact).

**Suggested Long-Term Fix:**
My suggested long-term fix is still to either implement our own versions of these functions or see if we can get our existing implementation open-sourced. In either case, it will ensure all platforms and architectures are consistent and allow future improvements more readily.

**Comment by mellinoe** [comment]
> 32-bit always just ran the CRT version (https://github.com/dotnet/coreclr/pull/4847/files#diff-884cab80438864e5dc66c7e4c1a3c723L144, comment is on L127). Only the 64-bit version forwarded and it had completely different allowed ranges because of this.

That's probably true for CoreCLR, but 32- and 64-bit .NET Framework seem to be the same to me. They both return `double.MaxValue` for `Math.Cos(double.MaxValue)` and seem to respect the same documented boundary that msdn lists.

> Suggested Short-Term Fix:
I agree, adding 32-bit-specific tests would get us clean and give us some better "coverage" for this stuff. But at the same time, they don't seem very valuable if we are just going to delete them when we get around to the long-term fix. I don't think we validate the behavior of `Math.Cos/Sin` for these parameters anyways, and this is essentially just another layer on top of that.

**Comment by tannergooding** [comment]
> That's probably true for CoreCLR, but 32- and 64-bit .NET Framework seem to be the same to me.

I would be its because desktop isn't on RyuJIT and doesn't support SSE2, so it was likely emitting the x87 `fcos` instruction as well (the range limitation of 2^63 is documented in the Intel Architecture manual).


> I agree, adding 32-bit-specific tests would get us clean and give us some better "coverage" for this stuff. But at the same time, they don't seem very valuable 

I think this depends on how much use we expect in 32-bit CoreCLR as compared to how long we expect it would take to implement the long term fix (which will require us ensuring that the speed and precision is reasonable as compared to the current implementation).

**Comment by tannergooding** [comment]
It would also be worth checking if Mac/Linux have significantly different 32-bit vs 64-bit implementations.

**Comment by mellinoe** [comment]
> It would also be worth checking if Mac/Linux have significantly different 32-bit vs 64-bit implementations.

I'll see if I can get a VM set up quickly to test that.

**Comment by mellinoe** [comment]
> It would also be worth checking if Mac/Linux have significantly different 32-bit vs 64-bit implementations.

I created a 32-bit Ubuntu 16.04 VM, and it seems to output the exact same value for `cos(numeric_limits<double>::max())` (which is `-0.99988`). This is the same value that 64-bit Windows returns (roughly speaking).

**Comment by mellinoe** [comment]
I think what I am going to do is this, for now:

* Re-enable the test methods that are disabled -- 90% of them don't need to be disabled, and it's just one of the `MemberData` test cases that causes a failure.
* File an issue about the 32-bit Cos() discrepancy on Windows.
* "Disable" the problematic test cases by not emitting those test cases on 32-bit Windows, with a link to the above issue.
