### ISSUE TITLE
Some libraries are building implementations for platforms they don't run on

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16696]
eg System.DirectoryServices.Protocols has a single configuration in Configurations.props
``` xml
    <BuildConfigurations>
        netstandard-Windows_NT;
    </BuildConfigurations>
```

This is a Windows specific implementation but as authored it is building that as a generic IL implementation (despite the Windows_NT prefix )

For platforms it doens't currently support (UAP, Unix) it should be building and packaging a PNSE assembly presumably with an appropriately conditioned <GeneratePlatformNotSupportedAssembly> property in the project.

As it is right now for example, this fails the UAP PInvoke checks.

We need to check for others in this condition.

@weshaggard @joperezr

**Comment by danmosemsft** [comment]
In the case of this one, it would be nice to have it work in UWP -- it's Linux that it cannot work in in its current state and that needs a stub building.

There are others in a similar bucket eg serial port.

**Comment by tarekgh** [comment]
CC @ericstj

**Comment by ericstj** [comment]
This thing doesn't even ship anywhere... if it were added to a framework or a package was created we'd be catching the fact that it doesn't have an impl for unix.

It's not clear what this issue is asking or which libraries it applies to.  Once it has that then I think the right thing to do would be to assign that to the library owner...

**Comment by tarekgh** [comment]
@danmosemsft if you have a list we can open issues to the library owners as @ericstj suggested.

**Comment by danmosemsft** [comment]
Changing to future since no evidence this affects shipping code

**Comment by stephentoub** [comment]
@danmosemsft, is this still relevant?

**Comment by danmosemsft** [comment]
Don't know. @joperezr can we close?

**Comment by joperezr** [comment]
I don't think this is much of a concern since as Eric mentioned, we would catch if we are missing implementations for runtimes we should work on if we were shipping the library in question. Today, we have a few experimental libraries in corefx which don't really ship, and I think in general it is good to just do a quick check to make sure that everything not shipping but building in corefx is there for a reason, but I don't think there is much else we should do about this.

**Comment by danmosemsft** [comment]
@ericstj feel free to retain or close as you prefer
