### ISSUE TITLE
Test: System.Private.Xml.Tests.XmlSerializerTests.SequenceEqual_SharedLeft_Cancellation with [ActiveIssue("fails when using CodeGen as well")]

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#16752]
Change [ActiveIssue("fails when using CodeGen as well")] to a new issue:

Detail: https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/tests/XmlSerializer/XmlSerializerTests.cs#L1883

**Comment by danmosemsft** [comment]
This is cleanup of disabled tests to have actual issues.

**Comment by karelz** [comment]
@Jiayili1 can you please file the bugs as 2.0? It will force us to review it prior shipping, also helping us to miss it by accident ... Thanks!

**Comment by danmosemsft** [comment]
@Jiayili1, @karelz means when you open **or reopen** test bugs from now on, please set milestone=2.0.

**Comment by Jiayili1** [comment]
@danmosemsft @karelz Thanks for reminding me, I got it, I will remember to set milestone=2.0 when open or reopen test bugs.

**Comment by karelz** [comment]
Thanks @Jiayili1 and sorry for not being clear.

BTW: We totally understand that mistakes happen. They always will. Sadly, I don't know where to find the latest process to check if it is just a one-off mistake or if it is a systematic gap in our process. That's why I raise up issues like these when I notice them - mainly to help identify gaps in the process and to make sure we don't miss things by accident :).
Thanks for all your help with the test bugs and test failures!

**Comment by shmao** [comment]
We should check the behavior of the desktop framework and see if this scenario is supported.

**Comment by shmao** [comment]
This was fixed by https://github.com/dotnet/corefx/pull/17771.
