### ISSUE TITLE
Why does System.IO.MemoryStream.Read returns 0 if no more bytes are available?

### ISSUE THREAD

**Issue by JonasZ95** [dotnet/corefx#16813]
I think that's something which makes streams very inconsistent. 

System.Net.Sockets.NetworkStream.Read may return 0 if there is no data available right now but there may be some data available in the future.

If you look how System.IO.BinaryReader uses Read you see how It wraps around this inconsistency.

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/BinaryReader.cs#L637

However this means It makes BinaryReader unable to work with a NetworkStream(in theory) because a NetworkStream may return 0, while the end of the stream is not reached.

Example:
https://dotnetfiddle.net/JkakUI

**Comment by stephentoub** [comment]
> Why does System.IO.MemoryStream.Read returns 0 if no more bytes are available?

Because that's how Stream.Read is defined:
https://msdn.microsoft.com/en-us/library/system.io.stream.read%28v=vs.110%29.aspx
"The total number of bytes read into the buffer. This can be less than the number of bytes requested if that many bytes are not currently available, *or zero (0) if the end of the stream has been reached*."

> I think that's something which makes streams very inconsistent.

How so?  This is how all Streams are supposed to behave.

> System.Net.Sockets.NetworkStream.Read may return 0 if there is no data available right now but there may be some data available in the future.

No, and if that's actually happening, it's a bug.  Can you provide a repro for that?

**Comment by JonasZ95** [comment]
Looking more into it, It seems It's more like a documentation error on msdn.


While msdn says: (https://msdn.microsoft.com/en-us/library/system.net.sockets.networkstream.read(v=vs.110).aspx)
' If no data is available for reading, the Read method returns 0.'


corefx doc says: (https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/NetworkStream.cs#L262)

'Number of bytes we read, or 0 if the socket is closed.'


So I think this can be closed and probably has nothing to do with CoreFx.

**Comment by stephentoub** [comment]
Thanks. I agree that sentence on msdn is potentially misleading. (FYI, @mairaw).

**Comment by mairaw** [comment]
we've been assigning the bugs here to me as Documentation. Should I reopen this or do you guys prefer to move this over to https://github.com/dotnet/docs?

**Comment by stephentoub** [comment]
Thanks. Labeled as documentation and reopened.

**Comment by karelz** [comment]
@mairaw regarding tracking here (corefx) vs. docs - it's up to you to decide what is easier for you. [Issue Mover for GitHub](https://github-issue-mover.appspot.com/) is pretty easy to use if you decide to move the bugs to docs.

**Comment by mairaw** [comment]
Cool. Thanks for the tip @karelz. I'll discuss with my team if they have a preference.

**Comment by karelz** [comment]
@mairaw just curious if you had chance to discuss it ...

**Comment by ViktorHofer** [comment]
@mairaw if you haven't had time yet to discuss that issue with your team I could suggest submitting a PR to the docs repo.

**Comment by karelz** [comment]
@ViktorHofer let's do the PR / move the issue into docs repo (as soon as there is clear actionable docs changes identified, we do not want waste docs team time to chase down technical details here and there).

BTW: @mairaw was on vacation for last 1+ week, so that's likely why she didn't answer. (I just learned yesterday on another issue)

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/docs #1929](https://github.com/dotnet/docs/issues/1929) via [**ZenHub**](https://www.zenhub.com/)
