### ISSUE TITLE
Investigate the size of System.Private.Xml 

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#16825]
System.Private.Xml is 3.7 MB of size on disk for IL and 8.4 MB when cross-gen'ed which seems a little large.

For reference System.Xml.dll on desktop is only 2.6 MB. 

We should understand the delta and make sure we aren't including a bunch of dead code.

**Comment by danmosemsft** [comment]
The diff, or almost all of it, is due to the implementation of System.Data,SqlXml.dll being in there. That dll contained most of the XSL implementation, as internal API exposed to System.Xml.dll.

That still leaves a ~400KB discrepancy

 2,657,952 System.XML.dll
734,416 System.Data.SqlXml.dll
======
 3,804,672 System.Private.Xml.dll

There will be some extra due to implementation changes: for example I also see some types relating to ReflectionXmlSerializationReader that seems to be a new feature. Also XmlUntypedStringConverter

On the flip side there is some chunks of code removed in Xml Serialization eg XmlCodeExporter.

We know the code coverage isn't wonderful so improving that may flag dead stuff.

@weshaggard is it worth digging more?

@sepidehMS @krwq

**Comment by danmosemsft** [comment]
Note the diff is fiddly because almost every private field got an underscore prefix.

System.Xml.Xsl.XsltOld.Keywords is also new and apparently unused. The rest of XsltOld is in the old code as well, is it used though?

**Comment by sepidehMS** [comment]
Thank you @danmosemsft. System.Xml.Xsl.XsltOld.Keywords seems to be unused as you mentioned. My guess is it might have been used before we removed CodeDom from System.Xml. The rest of XsltOld is used by System.Xml.Xsl.XslTransform.

**Comment by danmosemsft** [comment]
OK @sepidehMS could you submit a quick PR to delete it..

**Comment by danmosemsft** [comment]
@weshaggard how important is the remaining 400KB? I don't know the full picture .

**Comment by morganbr** [comment]
@danmosemsft for .NET Native and CoreRT, extra dead code and resources can contribute to longer build times and binary size. The tree shaker (linker) does try to get rid of dead code, but it's cautious. It also can't remove dead resources. Deleting them at the source level is more effective.

**Comment by weshaggard** [comment]
400KB is still a sizable amount so I do think it is worth a little more diving to understand if there are any public APIs in here that we don't expose in our public contracts and if there is any implementation code that is just unreachable.

**Comment by danmosemsft** [comment]
OK, let's leave this open and in 2.0. One way to take a closer look would be to decompile both, then run the code formatter on both so we get the underscores on fields. Then windiff.

**Comment by weshaggard** [comment]
@danmosemsft you could also try running the bclrewriter over it to see what it strips out.

**Comment by danmosemsft** [comment]
Using the tree shaker it looks like theres roughly 200KB dead, at least that's a higher bound

**Comment by ericstj** [comment]
Here's the results of running that tree-shaker. https://gist.githubusercontent.com/ericstj/4c5b0c4d54047134ac95e7f8347ccb5e/raw/59008d550d00438df4adedd2e4ad7c25f5fc5148/System.Private.Xml.diff.html

**Comment by danmosemsft** [comment]
YOu'll have to save it locally to see it, they send as text/plain.

**Comment by ericstj** [comment]
Yeah, I don't know of a good way to post an HTML publicly.  http://htmlpreview.github.io/? doesn't seem to work for this (size?)

**Comment by krwq** [comment]
@ericstj try https://jsfiddle.net/

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/pull/18042 is sufficien.t
