### ISSUE TITLE
System.Collections.Tests runs against Nuget package not compiled output

### ISSUE THREAD

**Issue by ebickle** [dotnet/corefx#1683]
Unit tests in System.Collections.Tests.csproj appear to execute against the System.Collections package, and not the compiled output in the bin folder.

Any local changes made to System.Collections are not picked up by System.Collections.Tests during compilation at command line (build.bat, msbuild System.Collections.sln) or in Visual Studio. For example, new types are not found by the test project.

Compiling in verbose mode shows that the reference to System.Collections.dll is being pulled from the packages folder (packages/System.Collections/4.0.10-beta/...) and not the compiled output of the local build. Chicken and the egg scenario, where compiling the solution for System.Collections depends on it having been successfully compiled (in the MS build lab)!

In addition, some of the behavior appears to be intentional. In System.Collections.Tests.csproj, a custom comment was added above the <ProjectReference>: "Compile tests against the contract, but copy our local-built implementation for testing".

The behavior makes it impossible to write unit tests for new logic (e.g. in forks) for System.Collection.dll.

**Comment by weshaggard** [comment]
cc @FiveTimesTheFun 

It is true that there are a number of places where are building and running against the libraries in the packages but tests that are specific for a given library should be running against the live build of the library they are testing. I will have look at this as I suspect it is just an oversight.

**Comment by weshaggard** [comment]
I did a quick test and changed SortedList.Add to always throw an exception and then when I ran the tests a bunch of them failed as expected.

There is however some interesting things going on here with projects like this one which we refer to as "Partial Facades" (see IsPartialFacadeAssembly=true in the System.Collections project). A partial facade contains some type definitions and as well as some type forwards, in this case it forwards some types to mscorlib. I've opened #1690 to get some documentation published about these. 

So for System.Collections you can make changes to the type definitions it contains and they will be picked up by the System.Collections.Tests project as expected but you will not be able to make changes to the types that are getting forwarded to mscorlib and have those picked up live. 

As for the package reference and the project reference, what is happening is we are referencing the System.Collection package in order to compile as it contains a reference assembly for all the types that live in the System.Collections API contract. However for testing we are deploying the output of the referenced project which is the live built version of System.Collections.dll and so it will have any changes you made to it. 

This does have the side-effect that you cannot add new public APIs and consume them in the tests which is what I believe you are trying to do. Unfortunately we don't have a way of modifying the public API contracts, including System.Collections, in our open source repo yet. It is on our list (https://github.com/dotnet/corefx/issues/824) but I don't have an ETA for when it will happen yet.

**Comment by Clockwork-Muse** [comment]
@weshaggard - any updates on this, since 824 was closed?  Trying to modify `BitArray` from corefx doesn't result in any behavior changes (including deleting it from the project entirely, although VS complains for a second).

**Comment by ianhays** [comment]
The System.Collections tests do run against the System.Collections source. I believe the original issue here was that the tests were being compiled against the contract, not the local source, so adding API to the local source wasn't mattering since it wasn't in the contract.

Regardless, classes within mscorlib (e.g. System.Collections BitArray, List, Dictionary) won't be modifiable since we don't compile those sources for the netstandard build in CoreFX. Those sources are only used for the UWP build. Check out out the [System.Collections.csproj](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System.Collections.csproj).

**Comment by Clockwork-Muse** [comment]
...Okay then, so any changes will have to go into both places, gotcha.

**Comment by ianhays** [comment]
Yup, manually. There isn't any sort of consolidation between the two afaik so source drift is a (scary) possibility.

**Comment by Clockwork-Muse** [comment]
yeah, that's an accident waiting to happen.  Or sabotage, maybe.
It would be better to have a single source for things, but I'm ignorant of the packaging strategies being used, so don't know end effects or what can be done.

**Comment by Clockwork-Muse** [comment]
@ianhays - Actually, they've already drifted:
[coreclr](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/BitArray.cs#L390):
```
if (array is int[]) {  // .... }
else if (array is byte[]) { // .... } 
else if (array is bool[]) { // .... }
else
    throw new ArgumentException(Environment.GetResourceString("Arg_BitArrayTypeUnsupported")); 
                                       // No  argument name in this message.
```
[corefx](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/BitArray.cs#L422):
```
if (array is int[]) { // ..... }
else if (array is byte[]) { // .... }
else if (array is bool[]) { // .... }
else
    throw new ArgumentException(SR.Arg_BitArrayTypeUnsupported, nameof(array));   
                               // Uses name of argument 
```
Tests pass against mscorlib, and not the corefx implementation, of course, which is going to cause confusion to somebody in the future.
 (this is ignoring the use of `nameof` and auto-generated message strings)

**Comment by ianhays** [comment]
@weshaggard is there a plan in place to deal with code drift between the sources in mscorlib that live in coreclr for the netstandard build and corefx for the netcore50 build?

**Comment by weshaggard** [comment]
Yes it is unfortunate that we have various forks of the source code that need to be kept in-sync. As much as possible we try to have the source-of-truth be in corefx but for some of the lower libraries there is definitely duplication that needs to be maintained. As you can imagine maintaining them can also be very difficult, especially given various set of requirements for each of the forks (i.e. some of them like the .NET Framework has a very high compat bar (see https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/Documentation/project-docs/triage.md#porting-to-net-framework)). 

As for #824 we do now have the contracts (i.e. src\<LIB>\ref) defined and building in this repo and that is the API definition for a given library. We generally write our tests against that API contract and then run those test on the various implementations to ensure the behaviors are the same. So while the individual source code files might be different they should generally remain semantically the same which is our goal. 

So testing changes to lower level implementations that might come from the coreclr repo or potentially the corert repo can be difficult as you generally need to do some manual overriding to be able to build and test against those bits. It is possible however and I can point you in the right direction if that is still interesting to you. 

I'm going to close this issue now as I think most of the questions have been answered and there isn't really any action item here. Please do feel free to keep asking questions if you have more.
