### ISSUE TITLE
PRs failing due to problem with System.Collections.Immutable package

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1685]
This is taking out a bunch of PRs this afternoon / evening:
```
Discovering: System.Collections.Immutable.Tests
  System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
d:\j\workspace\dotnet_corefx_windows_debug_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00045\lib\tests.targets(101,5): warning MSB3073: The command "corerun.exe xunit.console.netcore.exe System.Collections.Immutable.Tests.dll  -xml testResults.xml -notrait category=nonwindowstests  -notrait category=OuterLoop -notrait category=failing " exited with code 1. [d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Collections.Immutable\tests\System.Collections.Immutable.Tests.csproj]
d:\j\workspace\dotnet_corefx_windows_debug_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00045\lib\tests.targets(112,5): error : One or more tests failed while running tests from 'System.Collections.Immutable.Tests' please check log for details! [d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Collections.Immutable\tests\System.Collections.Immutable.Tests.csproj]
C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. 
```

**Comment by stephentoub** [comment]
This is now also causing the main Windows debug and release builds to fail.

**Comment by stephentoub** [comment]
cc: @jhendrixMSFT, @ericstj, @mmitche

**Comment by mmitche** [comment]
Failing since https://github.com/dotnet/corefx/commit/f6876f10f55a0d1a2e8deedf1fb0b210989e769e

Suggests that it wasn't a commit.  Maybe a package update?  Are we updating packages without updating version numbers?

**Comment by ericstj** [comment]
I'm taking a look.  Chances are we stopped resolving assets from the package.  We've been hitting a number of bugs like this.

**Comment by ericstj** [comment]
It's more likely that my change https://github.com/dotnet/corefx/commit/0ee1f82331cfd061afae5a3540491127758ea02b caused this.  I had to fake the TFM used to resolve assets on this project because DNX was failing to select assets on our internal build machines that don't have the PCL targeting pack (https://github.com/aspnet/dnx/issues/1814).  I can't repro locally, but I do see a couple suspicious things in the log that I am chasing down.

**Comment by ericstj** [comment]
Looks like System.Collections.Immutable.dll is missing from the test output directory, according to the copy logs.  Digging through the logs even more and found the problem (it isn't related to my change as I previously thought).
```
Primary reference "System.Collections.Immutable, Version=1.1.34.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". (TaskId:1294)
    Resolved file path is "d:\j\workspace\dotnet_corefx_windows_release_prtest\bin\Windows_NT.AnyCPU.Release\System.Collections.Immutable\System.Collections.Immutable.dll". (TaskId:1294)
    Reference found at search path location "d:\j\workspace\dotnet_corefx_windows_release_prtest\bin\Windows_NT.AnyCPU.Release\System.Collections.Immutable\System.Collections.Immutable.dll". (TaskId:1294)
    Found related file "d:\j\workspace\dotnet_corefx_windows_release_prtest\bin\Windows_NT.AnyCPU.Release\System.Collections.Immutable\System.Collections.Immutable.pdb". (TaskId:1294)
    Found related file "d:\j\workspace\dotnet_corefx_windows_release_prtest\bin\Windows_NT.AnyCPU.Release\System.Collections.Immutable\System.Collections.Immutable.xml". (TaskId:1294)
    This reference is not "CopyLocal" because it's registered in the GAC.
```

@FiveTimesTheFun  Any idea why System.Collections.Immutable in the GAC?  I would have expected our corefx builds to have a higher version than anything that's ever been released.  RAR is excluding it because of this, but the tests later fail because coreclr doesn't load from the GAC.

**Comment by nguerrera** [comment]
It's installed to the GAC by VS. This was hit and fixed before with https://github.com/dotnet/corefx/pull/1026. Something has reintroduced it.

**Comment by ericstj** [comment]
Ok, I submitted a PR to fix this.  https://github.com/dotnet/corefx/pull/1697
