### ISSUE TITLE
Would it be possible to get rid of collection _syncRoot fields with ConditionalWeakTable?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#16886]
More of a question really because I'm not very familiar with `ConditionalWeakTable`, but from what I understand it can store key/value entries in such a way that the entries don't have to be kept alive. It also says [on MSDN](https://msdn.microsoft.com/en-us/library/dd287757(v=vs.110).aspx#Anchor_7) that the type is thread-safe. Given that `SyncRoot` is a rarely-used property (if I remember correctly @mikedn told me it was baggage from .NET Framework 1.0), maybe it would be beneficial to store it in a static `ConditionalWeakTable` separate from the object? e.g.

```cs
class List<T>
{
    object ICollection.SyncRoot => SyncRootTable.GetSyncRoot(this);
}

static class SyncRootTable
{
    static readonly ConditionalWeakTable<object, object> s_table = new ConditionalWeakTable<object, object>();

    static object GetSyncRoot(object key) => s_table.GetValue(key, _ => new object());
}
```

**Comment by mikedn** [comment]
> maybe it would be beneficial to store it in a static ConditionalWeakTable separate from the object

AFAIR @stephentoub mentioned this possibility in a comment.

Another option would be to "fix" the existing `SyncRoot` implementation to return `this` instead of a separate object. Yes, "fix" because what the code does now is unnecessary according to the [documentation](https://msdn.microsoft.com/en-us/library/system.collections.icollection.syncroot(v=vs.110).aspx):

> For collections whose underlying store is not publicly available, the expected implementation is to return the current instance. Note that the pointer to the current instance might not be sufficient for collections that wrap other collections; those should return the underlying collection's SyncRoot property

**Comment by stephentoub** [comment]
@mikedn's suggestion of returning `this` is certainly better/cheaper if it's a valid option for any given case.  Note that both approaches have potential downsides.  Using a CWT will make SyncRoot much slower, so while it'd help for most workloads that don't use it, it could negatively impact older code that does (there's even code in CoreLib that uses it).  Using `this` would be cheap and easy, but it is a visible change, and theoretically (though unlikely) could be breaking, e.g. if strange code was using the collection and its sync root as two different locks but the change made them the same, if code were doing various reference equality checks related to SyncRoot and the collection, etc.

**Comment by svick** [comment]
[API Port telemetry says that `ICollection.SyncRoot` is used by 10 % of applications](https://apisof.net/catalog/System.Collections.ICollection.SyncRoot), which seems very high to me. Does this mean so many applications actually use it? Or is there some other explanation for this number (like custom collection types that *have to* implement the property, but don't actually use it)?

**Comment by stephentoub** [comment]
@terrajobst, can you comment on @svick's question?  Does any ICollection implementation trigger this to show up in the usage data?

**Comment by jamesqo** [comment]
@stephentoub Regarding your/@mikedn's point about using `this` instead of a CWT, I think unless a lot of legacy code is using `SyncRoot` (and @svick's findings about 10% of apps using `SyncRoot` are because of ICollection implementations), slower code is better than potentially broken code.

> (there's even code in CoreLib that uses it)

If that's true, shouldn't it be possible to convert those usages to lock directly on the collection?

**Comment by stephentoub** [comment]
> shouldn't it be possible to convert those usages to lock directly on the collection?

My point was that a lot of code uses this stuff, including very active code bases like System.Private.CoreLib.

**Comment by danmosemsft** [comment]
The API usage data is even higher when I look at apps. In some groups it's 100%. I bet this is custom ICollections, and many of the usages in apps are a few utility libraries.

**Comment by jamesqo** [comment]
Would be interesting to see if there is way to get usage data counting only the callsites and not the implementations

**Comment by jkotas** [comment]
Changing what SyncRoots returns for existing framework collection classes would be a potential behavior breaking change. I doubt it will fly since we care a lot about compatibility quite a bit.

Changing the implementation of SyncRoot to use ConditionalWeakTable preserves the behavior; and just changes the perf characteristics. You are basically talking about improving memory consumption a tiny bit for say 90% (the exact percentage does not matter) of programs out there; and regressing both memory consumption and time for say 10% of programs out there. You should collect some performance data, for both microbenchmarks (e.g. how much slower will get SyncRoot + fetch element on List under lock becomes) and for some bigger workloads (say music store asp.net sample app). We can then look at the data and discuss whether it is a tradeoff worth taking.

**Comment by danmosemsft** [comment]
We went with `this` -- https://github.com/dotnet/corefx/issues/34149
