### ISSUE TITLE
SafePipeHandle.ReleaseHandle() violates contract on Unix without justification.

### ISSUE THREAD

**Issue by KevinCathcart** [dotnet/corefx#1689]
The contract for ReleaseHandle ([per MSDN](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.safehandle.releasehandle.aspx)) is to only return false on catastrophic failure. However as coded, on Unix it will return false for an `EINTR`, which is hardly catastrophic. Either it should retry on EINTR, or it should have the comment expanded to explain why we should consider that a catastrophic error.

**Comment by stephentoub** [comment]
@KevinCathcart, I'm assuming this is based on code review rather than on hitting something negative from this at run time, right?  Returning false from ReleaseHandle simply causes a Managed Debugging Assistant (MDA) to be raised, if they're supported by the target platform.  And while "catastrophic" does sound severe, based on what the runtime does in this case, I think that's overstating the impact.  Further, as the comment in the code outlines, we don't want to retry in the case of EINTR, for reasons like https://lkml.org/lkml/2005/9/11/49.  The only two options would seem to be either do what the code does today (returning false if close returns non-zero) or always returning true (ignoring the result of close), and at least getting some debugging information about lack of closure seemed like the better way to go.  Are you suggesting we should switch to the latter?  @jkotas, any opinion?

**Comment by jkotas** [comment]
Always returning true sounds like the most appropriate thing to do here.

**Comment by stephentoub** [comment]
Because? It's an easy change to make (here and a few other places), I just want to make sure we're consistent in the future, both on UNIX and Windows. It's not clear to me why this is so different from places where, for example, CloseHandle fails, and in such cases we return false.

**Comment by KevinCathcart** [comment]
Ah, yes. I was investigating the implementation of pipes and reviewing the code to see how well the existing .net API could map to UNIX. I saw that. What I did not know is that it was not safe to retry close on EINTR (just another UNIX design flaw.).

Given that, I agree that retrying is not acceptable. I suppose the question then is if there are any possible negative side effects (i.e. leaks) that occur if it did return with EINTR. (If there are possible leaks that is equally as catastrophic as say a CloseHandle failure in one of Win32 SafeHandles.)

I am also surprised that it only raises an MDA. If that is also true of the desktop framework, that sounds like a bit of a hole in the reliability framework. For example, I would have expected SQL server to react. The idea being that a failure return from a SafeHandle release indicates a likely indicates a leak at best (and process level leaks are completely unacceptable to SQL server, which was most of the point of CriticalFinalizerObject in the first place), or previous process corruption at worst.

**Comment by KevinCathcart** [comment]
To be clear, since the POSIX spec allows for the file to not be closed at all in an EINTR case, I am now favor returning false in that case. (as the code currently does). I would like to see the comment in question being expanded to explain that retrying is not safe because the FD could have been closed, and reassigned in another thread.

That makes it clear the it is a UNIX design flaw that close is even allowed to return EINTR. (Although personally I've always felt that EINTR was a design flaw in and of itself.)

**Comment by jkotas** [comment]
My interpretation of the links and discussion was that the close() failure is ambiguous (different from Windows). It is hard to tell whether there is a real problem (leak), but it is most likely fine on the real Unix systems out there. It made me think that it is most appropriate to just to ignore the error.

Either way, it should not matter a whole lot what we do here because of the result is ignored on CoreCLR. The current implementation is about as good as alternatives, unless this changes.
