### ISSUE TITLE
[Compiler Bug] PropertyInfo retrieved from LambdaExpression reports wrong ReflectedType when property is derived from another class

### ISSUE THREAD

**Issue by dsaf** [dotnet/corefx#1691]
This is an old bug:

https://connect.microsoft.com/VisualStudio/feedback/details/554853

https://connect.microsoft.com/VisualStudio/feedback/details/607165/propertyinfo-retrieved-from-lambdaexpression-reports-wrong-reflectedtype-when-property-is-derived-from-another-class

**Comment by MarkusSintonen** [comment]
I investigated the issue a bit and it seems to be a compiler bug. I created a little test program based on the description of the issue:
````CSharp
class Program
{
	public class A
	{
		public int Prop { get; set; }
	}

	public class B : A
	{

	}

	static void Main(string[] args)
	{
		Expression<Func<B, int>> expr = (B o) => o.Prop;
		var prop = GetProperty(expr);
	}

	public static PropertyInfo GetProperty(Expression<Func<B, int>> expression)
	{
		var result = expression.Body.NodeType == ExpressionType.Convert
			 ? ((MemberExpression)((UnaryExpression)expression.Body).Operand).Member as
				 PropertyInfo
			 : ((MemberExpression)expression.Body).Member as PropertyInfo;

		if (result != null) return result;

		throw new ArgumentException(
			   string.Format("Expression '{0}' does not refer to a property.",
									   expression.ToString()));
	}
}
````

The produced IL code is flawed on the expression creation `Expression<Func<B, int>> expr = (B o) => o.Prop;` Here is the IL code for start of the `Main` function:

````CSharp
L_0001: ldtoken ConsoleTests.Program/B
L_0006: call class [mscorlib]System.Type [mscorlib]System.Type::GetTypeFromHandle(valuetype [mscorlib]System.RuntimeTypeHandle)
L_000b: ldstr "o"
L_0010: call class [System.Core]System.Linq.Expressions.ParameterExpression [System.Core]System.Linq.Expressions.Expression::Parameter(class [mscorlib]System.Type, string)
L_0015: stloc.2 
L_0016: ldloc.2 
L_0017: ldtoken instance int32 ConsoleTests.Program/A::get_Prop()
L_001c: call class [mscorlib]System.Reflection.MethodBase [mscorlib]System.Reflection.MethodBase::GetMethodFromHandle(valuetype [mscorlib]System.RuntimeMethodHandle)
````

`L_001c` shows how we are obtaining the `MethodBase` using `MethodBase.GetMethodFromHandle(RuntimeMethodHandle)` the returned `MethodBase` has `ReflectedType==DeclaringType` since we are only passing handle of `A.get_Prop` Obviously this is a bug since `B` inherits `A` and `ReflectedType` should refer to `B`.

Instead the IL code should call `MethodBase.GetMethodFromHandle(RuntimeMethodHandle,RuntimeTypeHandle)` where the second argument is the handle to the type `B`. Of cource the IL also should load the `B` type handle to the evaluation stack before the function call.

Could someone confirm this?

**Comment by JonHanna** [comment]
`ReflectedType` is only well defined if the `MemberInfo` was obtained using reflection (which is a reason to avoid using it at all if possible).

There's no use of reflection in the call that `GetProperty` so there's no reason to suspect that it will return a `PropertyInfo` with a particular `ReflectedType`.

This is no different to how if `Prop` was defined as:

```C#
public int Prop
{
	get
	{
		return new StackTrace().GetFrame(0).GetMethod().ReflectedType == typeof(A) ? 1 : 2;
	}
}
```

Then `new B().Prop` would return `1`, not `2`.

If reflection is explicitly used, then it behaves as documented:

```C#
var o = Expression.Parameter(typeof(B));
Expression<Func<B, int>> expr = Expression.Lambda<Func<B, int>>
(
    Expression.Property(o, typeof(B).GetProperty("Prop")),
    o
);
var prop = GetProperty(expr);
Console.WriteLine(prop.ReflectedType.Name); // B
```
```C#
var o = Expression.Parameter(typeof(B));
Expression<Func<B, int>> expr = Expression.Lambda<Func<B, int>>
(
    Expression.Property(o, typeof(A).GetProperty("Prop")),
    o
);
var prop = GetProperty(expr);
Console.WriteLine(prop.ReflectedType.Name); // A
```

But since reflection wasn't used, there's no reason to expect any particular result (I would have guessed it would have considered it `A.Prop` rather than `B.Prop`, but not convinced it would be either).

**Comment by JonHanna** [comment]
Further, changing this behaviour would introduce a compiler bug with forward-compatibility issues.

Consider if `A` and `B` were in another assembly.

Someone writing `(B o) => o.Prop` clearly wants the `Prop` property defined in `A` to be accessed.

The compiler creates the expression using `ldtoken method instance int32 A::get_Prop()` to represent this. If someone later tries to obtain `((MemberExpression)expression.Body).Member.ReflectedType` they get `A`.

If someone comes along and changes `B` to include `public new int Prop { get { return 42; }}` then this is perhaps unwise, but at least it's only a source-breaking change. Using the new assembly with the code described above will still work.

If however the compiler used `ldtoken method instance int32 B:get_Prop()` then while that would mean that  `((MemberExpression)expression.Body).Member.ReflectedType` would return `B` (though there's no particular guarantee here) it would mean that source-breaking changes would become compiled-breaking changes. `(B o) => o.Prop` would no longer mean "access the `Prop` property on `B` as declared at `A`" as it currently does, but rather would mean "access the `Prop` property on `B`, calling that declared on `B` if there is on, and that declared on `A` otherwise". Inheritance has just gotten a lot less dependable.

**Comment by VSadov** [comment]
This is how C# compiler creates the expression tree (so nothing to do with Linq.Expressions) and basically ByDesign - C# does call the least derived method.

If you want the change to be considered, the bug should go to https://github.com/dotnet/roslyn , although there could be compatibility reasons why this cannot be changed now.
