### ISSUE TITLE
System.Runtime.Numerics.Tests are not executed

### ISSUE THREAD

**Issue by marek-safar** [dotnet/corefx#17047]
Tests in https://github.com/dotnet/corefx/tree/master/src/System.Runtime.Numerics/tests appears not to be executed as part of build tests and it looks like some of them regressed.

**Comment by stephentoub** [comment]
Which tests in which build?  I see, for example, the following in the build at https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug/1501/consoleText:
```
  === TEST EXECUTION SUMMARY ===
     System.Runtime.Numerics.Tests  Total: 1180, Errors: 0, Failed: 0, Skipped: 6, Time: 14.731s
```

**Comment by marek-safar** [comment]
I looked at Ubuntu 16.10 build

**Comment by stephentoub** [comment]
They appear to only be running on Windows.
cc: @mellinoe, @tarekgh

**Comment by mellinoe** [comment]
This PR made them Windows-only: https://github.com/dotnet/corefx/pull/15743/files#diff-55c3506c014b947ed9b7a9efef3039e9L6. Hopefully we can just turn them back on and there haven't been any regressions since then.

@tarekgh

**Comment by tarekgh** [comment]
> This PR made them Windows-only: https://github.com/dotnet/corefx/pull/15743/files#diff-55c3506c014b947ed9b7a9efef3039e9L6. Hopefully we can just turn them back on and there haven't been any regressions since then.

This is not true. the old configurations were
      netstandard1.3-Windows_NT;
      netstandard;

so when compiling as netstandard,, the configuration netstandard1.3-Windows_NT was preferred over non-OS specific configuration. so we always used to compile as  netstandard1.3-Windows_NT. my change didn't really change that more than compiling with non versioned netstandard.

 +      netstandard-Windows_NT;;

**Comment by mellinoe** [comment]
Do we actually specify `netstandard` as the build configuration for tests anywhere? As far as I know, we just specify `netcoreapp-Windows`, or `netcoreapp-Linux`, etc. When specifying `netcoreapp-Linux`, we will no longer run these tests after the change.

**Comment by tarekgh** [comment]
usually we build the test as netstandard if the test has nothing specific for specific platform (e.g netcoreapp, netfx or UAP). if the test doing something specific for one of these platforms we'll list this platform in the configuration. 

cc @weshaggard @ericstj

**Comment by mellinoe** [comment]
For all of our .NET Core CI jobs, at least, our specified build configuration is never `netstandard`, it is always `netcoreapp-<OS>`. For some tests, the `netstandard` configuration is chosen because it is the most applicable. Even then, a "Unix" flavor should not be picking `netstandard-Windows_NT` over `netstandard`, at least from my understanding of how things work.

**Comment by tarekgh** [comment]
Please differentiate between building and running. when having global build configuration like ntefx for instance and when compiling the test, if the test configuration doesn't specify netfx, we'll fallback to netstandard. then we building the test as netstandard and run it against the desktop. this applies to other platforms netcoreapp and uap too.

so if you have a test that doesn't have any specific code for netcoreapp, uap or netfx then you can just have netstandard configuration. otherwise you'll need to specify the spcific platform in the configuration.

for example System.Numeric test we are talking about here, looks to me doesn't have any netcoreapp, UAP or netfx socific code, so specifying netstandard would be enough for all configurations. when running CI with netcoreapp-OS, it should work as it compile as netstandard and then runs as netcoreapp. 
to make it run on Linux, you would just remove the Windows_NT from the netstandard configuration and this will allow the test runs for Linux too.

**Comment by mellinoe** [comment]
I think we should also take a look at these test projects, since they may also be need to be reconfigured to run outside of Windows:

src/System.IO.FileSystem.DriveInfo/tests/Configurations.props
src/System.Net.WebHeaderCollection/tests/Configurations.props
src/System.Security.Cryptography.Primitives/tests/Configurations.props
src/System.Text.Encoding.CodePages/tests/Configurations.props

**Comment by stephentoub** [comment]
> I think we should also take a look at these test projects

If those aren't running on unix, they absolutely need to be fixed to do so.

**Comment by mellinoe** [comment]
> If those aren't running on unix, they absolutely need to be fixed to do so.

#17058 

I'll follow up with a PR for those projects specifically, and look into whether there are more than that.

**Comment by stephentoub** [comment]
Great, thanks, Eric.
