### ISSUE TITLE
.NET should provide better support for understanding what platform your code is running on

### ISSUE THREAD

**Issue by SirCmpwn** [dotnet/corefx#1710]
`System.Environment` leaves a lot to be desired, especially considering the move to support OSX, Linux, BSD, etc. I have a piece of code I've been passing around through many of my projects over the years that I think would fit well into the standard framework:

```csharp
using System;
using System.Diagnostics;
using System.IO;

namespace foobar
{
    public static class RuntimeInfo
    {
        public static bool Is32Bit { get; private set; }
        public static bool Is64Bit { get; private set; }
        public static bool IsMono { get; private set; }
        public static bool IsWindows { get; private set; }
        public static bool IsUnix { get; private set; }
        public static bool IsLinux { get; private set; }
        public static bool IsMacOSX { get; private set; }

        static RuntimeInfo()
        {
            IsMono = Type.GetType("Mono.Runtime") != null;
            int p = (int)Environment.OSVersion.Platform;
            IsUnix = (p == 4) || (p == 6) || (p == 128);
            IsWindows = Path.DirectorySeparatorChar == '\\';

            Is32Bit = IntPtr.Size == 4;
            Is64Bit = IntPtr.Size == 8;

            if (IsUnix)
            {
                Process uname = new Process();
                uname.StartInfo.FileName = "uname";
                uname.StartInfo.UseShellExecute = false;
                uname.StartInfo.RedirectStandardOutput = true;
                uname.Start();
                string output = uname.StandardOutput.ReadToEnd();
                uname.WaitForExit();

                output = output.ToUpper().Replace("\n", "").Trim();

                IsMacOSX = output == "DARWIN";
                IsLinux = output == "LINUX";
            }
            else
            {
                IsMacOSX = false;
                IsLinux = false;
            }
        }
    }
}
```

This is clearly not ideal for a number of reasons:

* Platforms other than Windows might use \ as a path seperator (hah)
* Calling a process to detect OSX versus Linux is lame

That being said, I think this is a good start. Here are a couple of places this class is already in use:

* [Craft.Net](https://github.com/SirCmpwn/Craft.Net/blob/master/source/Craft.Net.Client/DotMinecraft.cs) has to know what platform it's on to know where Minecraft data is kept
* [Tomato](https://github.com/SirCmpwn/Tomato/search?utf8=%E2%9C%93&q=RuntimeInfo) needs it for several platform-specific workarounds

**Comment by SirCmpwn** [comment]
These APIs could also be made better so it's not as annoying to get what you actually want out of it. It should be easier to get:

* Linux kernel version
* Windows version (i.e. "Windows 8")
* Distribution name (i.e. "Ubuntu 12.04")
* OS X version (i.e. "Mountain Lion")

This may be a seperate issue, though.

**Comment by akoeplinger** [comment]
Parts of your suggestion seem to be covered by https://github.com/dotnet/corefx/pull/1494.

**Comment by SirCmpwn** [comment]
Ah, I should have *also* searched closed issues when I went looking for this.

**Comment by ellismg** [comment]
I'm going to close this as the key focus of the issue seems to be around platforms.  From memory, there are other sort of questions people always think they might want to ask.

1. Understanding if your process is 32 bit or 64bit.  (You can do this today with the IntPtr.Size comparison, but it's not the most discoverable thing.
2. Understand if the host OS is 32bit or 64bit (e,g, on Windows detect if you are in the WoW or not).
3. Understand the processor architecture you're running on.
4. Understand OS Version Information.

Of these, I think that 4 is the scariest for us to go add support for.  In general, we would rather try to design APIs that help you do feature probing (this is an open problem about what the design would look like) than give you the ability to ask for a version number.  Note that some platforms (e.g. newer versions of Windows) will basically always lie when you ask "What Version Is This" so it could be hard for us to expose this sort of thing if we wanted.

@SirCmpwn Feel free to open issues for any or all of the above.

**Comment by SirCmpwn** [comment]
Regarding 4, let the packagers handle it. In the Linux world, the maintainers of the distribution might do something like this when creating the package:

    ./configure --host="Ubuntu 15.04"

Then `Environment.Host` or something would return "Ubuntu 15.04".
