### ISSUE TITLE
When method is not impl, we should not throw NotSupportedException()

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#17136]
We standardized on throwing PlatformNotSupportedException() even if we don't support the API on _any_ platform.

We're throwing NSE in a number of places that we added in 2.0, and according to the above principle we should not. 

Random example https://github.com/dotnet/corefx/blob/master/src/System.Security.Permissions/src/System/Security/SecurityContext.cs#L12

I don't see this as a high priority to fix for 2.0 generally and it would be a breaking change later so we may want to just close this.

@stephentoub since he added the useages above just in case his understanding was different.
@weshaggard

**Comment by stephentoub** [comment]
> We standardized on throwing PlatformNotSupportedException() even if we don't support the API on any platform.

Why is that?  It seems like given the existence of both NSE and PNSE, we'd use NSE when something simply isn't supported (e.g. Stream.Seek throwing NSE when CanSeek is false) and we'd use PNSE when something isn't supported because of the platform on which we're running (e.g. it depends on a piece of OS functionality that's not present on this OS but is on another).

**Comment by stephentoub** [comment]
> it would be a breaking change later 

We've generally said that changing to throw a more derived type is acceptable.  And PlatformNotSupportedException derives from NotSupportedException.

**Comment by danmosemsft** [comment]
You're right about the derivation.

@terrajobst / @weshaggard do we have a policy about PNSE vs. NSE?

**Comment by weshaggard** [comment]
The general guidance is to use NSE when something isn't ever supported anywhere. Consider a base virtual method that you expect to be overridden we throw NSE in the base to indicate that we will never implement in the base, or consider the non-seekable stream example we would throw if you call Seek. NSE is also commonly used when bringing up new libraries to temporarily indicate that we don't yet support the method.

We generally use PNSE when we decide that an API will not work in one of our implementations because of OS or .NET Platform limitations. So I do think the SecurityContext example is in this bucket and should probably throw PNSE. 

As for breaking changes in these cases I wouldn't worry much about because these are APIs that aren't supposed to work and we really hope folks don't end up catching these. However as @stephentoub points out we would also be moving to a more derived exception in this case which we generally allow.

**Comment by danmosemsft** [comment]
OK that's clear -- this means that we would not throw NSE in any situation where Desktop had the type but did not throw NSE

**Comment by stephentoub** [comment]
> where Desktop had the type but did not throw NSE

Basically match desktop behavior: if desktop throws NSE, throw NSE... if we can't match desktop behavior and instead need to throw to say it's not supported, then PNSE.

**Comment by weshaggard** [comment]
Correct, that sounds like a reasonable guideline.

**Comment by stephentoub** [comment]
@danmosemsft, what would you like to do with this two-year old issue?  Close it in the name of compat with code that's now been shipping for several years, or leave it open for longer until someone gets around to auditing stuff at some time? :)

**Comment by danmosemsft** [comment]
Compat
