### ISSUE TITLE
HttpClient crashes when reading a stream with trailing headers on Linux

### ISSUE THREAD

**Issue by Drawaes** [dotnet/corefx#17174]
HttpClient ignores trailing headers on windows, however crash when the same headers are read on Ubuntu with

System.Net.Http.HttpRequestException : Error while copying content to a stream.
---- System.IO.IOException : The read operation failed, see inner exception.
-------- System.Net.Http.CurlException : Failed writing received data to disk/application
Stack Trace:

Failing test on ubuntu

https://travis-ci.org/Drawaes/CondenserDotNet/builds/211566793

Passing on windows

https://ci.appveyor.com/project/Drawaes/condenserdotnet/build/0.7.418

**Comment by Priya91** [comment]
@Drawaes Can you provide a short repro.

**Comment by Drawaes** [comment]
Well the problem is not much supports trailing headers but it has been suggested that it is used for timing. I have some basic middleware and a nuget package that adds it to Kestrel.

https://github.com/Drawaes/CondenserDotNet/blob/master/test/Condenser.Tests.Integration/TrailingHeaderMiddlewareFacts.cs

**Comment by Drawaes** [comment]
Obviously you need to remove the [WindowsOnlyFact] to have it run in xunit on linux

**Comment by Priya91** [comment]
Verified the bug repros with .NET Core. Requires further investigation.

**Comment by stephentoub** [comment]
https://github.com/curl/curl/issues/1354

**Comment by niemyjski** [comment]
I'm also running into this while trying to post a byte array using ByteArrayContent. Any work arounds for this issue?

**Comment by niemyjski** [comment]
I do see the latest version of curl was updated or there was a pr merged in about a year ago, with that stated I'd think I'd have those latest changes but still running into this issue only on non windows which is a huge issue.

**Comment by karelz** [comment]
@niemyjski as a workaround, update your distros to latest curl with the fix.

**Comment by niemyjski** [comment]
@karelz I'm using the latest 2.0.5 linux docker images from Microsoft. Not sure what else I can do here, Also just reformatted everything this morning and using latest sdk / bits on osx.

**Comment by karelz** [comment]
@niemyjski did you check curl version in your Docker image? Is that one with the fix? Did you try to update it? Maybe the underlying Linux distro is either not up to date, or didn't pick the latest curl yet. (my knowledge how Docker images work is limited)

**Comment by davidsh** [comment]
Looks like this was fixed in Curl with this commit.  Probably need Curl version 7.59 or later:
https://github.com/curl/curl/commit/452203341d6e97b8f52f9a886046d9fdb96346a9

![image](https://user-images.githubusercontent.com/7684835/39677611-f065afb4-5132-11e8-91ce-a04a0394d344.png)

Please make sure your Linux Distro has this latest Curl. If you are still having problems, please open up a new issue.

Also, starting with .NET Core 2.1 (available now as Preview 2), we have a new HTTP stack, SocketsHttpHandler.  This new HTTP stack is written with all managed code and works on both Windows and Linux. It does not use Curl.  This new HTTP stack is the default for .NET Core 2.1. Trailing headers should work fine with this HTTP stack. So, you might not need to update your Linux distros with a new Curl if you use .NET Core 2.1

See:
https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-net-core-2-1-preview-2/
