### ISSUE TITLE
DataFlow: Add ability to restrict Duplicates

### ISSUE THREAD

**Issue by ObsidianPhoenix** [dotnet/corefx#17292]
The DataFlow components are great for managing concurrency/queueing. However, they do not provide a way to ensure that items are not added more than once at a given time.

For instance, if you are using an `ActionBlock` to process files received, there is no mechanism to ensure that the file is not added a second time if it is already present (e.g. via a manual catchup process).

    class Program
    {
        private static readonly ActionBlock<string> worker =
            new ActionBlock<string>(file => ProcessFile(file),
                new ExecutionDataflowBlockOptions()
                {
                    MaxDegreeOfParallelism = 1
                });

        private static void ProcessFile(string file)
        {
            //Process the File.
            new ManualResetEvent(false).WaitOne(10000);
            File.Delete(file);
        }

        private static Timer ScanTimer;

        static void Main(string[] args)
        {
            ScanTimer = new Timer()
            {
                Interval = 1000,
                AutoReset = true,
                Enabled = true
            };
            ScanTimer.Elapsed += (sender, eventArgs) => GetFiles();
            ScanTimer.Start();
        }

        private static void GetFiles()
        {
            foreach (var file in
                Directory.EnumerateFiles(@"C:\Temp\Files", "*.*", SearchOption.TopDirectoryOnly))
            {
                worker.Post(file); //Files currently Queued will be added a second time.   
            }
        }
    }

Can we add a mechanism to ensure uniqueness? Some options:

* Expose methods to show InProcess/QueuedItems. Allow users to implement their own checking. e.g. `worker.PostedItems`
* Provide an, `ExecutionDataflowBlockOptions` Property to ensure uniqueness. Options on this:
    * Uniqueness using the default `Equals` mechanism - Devs are required to override this if required for specific use cases.
    * Allow devs to specify an equality method during specification of the option, e.g.
`    new ExecutionDataflowBlockOptions()
    {
        EnsureUniqueness = (a, b) => return a.Id == b.Id
    }`

**Comment by stephentoub** [comment]
Thanks for the suggestion.

> there is no mechanism to ensure that the file is not added a second time if it is already present

This could be done in a variety of ways, e.g.
```C#
var seen = new HashSet<T>();
var filter = new TransformManyBlock<T>(t => seen.Add(t) ? new[] { t } : Array.Empty<T>());
filter.LinkTo(actionBlock);
```
and then targeting filter instead of the action block directly, or just building that filtering logic into the ActionBlock itself.  Or using a BufferBlock that has a filter on its link to the action block and that dumps everything already seen to a null target, e.g.
```C#
var seen = new HashSet<T>();
var filter = new BufferBlock<T>();
filter.LinkTo(actionBlock, seen.Add);
filter.LinkTo(DataflowBlock.NullTarget<T>());
```
Etc.

I'd personally be hesitant to add a mechanism like you suggest directly into the blocks, as it's relatively niche and involves a lot of policy that would likely need to be customized for different devs that cared to use it.

**Comment by stephentoub** [comment]
> Expose methods to show InProcess/QueuedItems. Allow users to implement their own checking. e.g. worker.PostedItems

I see the value in this, but it's complicated.  This information is "exposed", but only to a debugger right now.  The trouble is that by nature the blocks are manipulating these data structures concurrently with any code you might write outside the block to process them.  Exposing this would necessitate adding synchronization to ensure the data was kept consistent.

This could also be accomplished in code today by maintaining one's own tracking, e.g. maintaining a concurrent dictionary of items currently in flight, adding to that dictionary when adding the data into the first block, and removing it from the dictionary when the data is done being handled by the last block.  That could either be done external to blocks, or could be done by, for example, having a TransformBlock at the beginning that just adds the item to the dictionary, using a TransformBlock instead of an ActionBlock in the middle, and having an ActionBlock at the end that removes from the dictionary.  Or just adding to the dictionary yourself when posting and then having the action in the ActionBlock remove it when done.

This also highlights how EnsureUniqueness functionality on an individual block would be limited: it couldn't accommodate "uniqueness" across a chain of blocks.

**Comment by ObsidianPhoenix** [comment]
Your solution with the `BufferBlocks` appears to be solve the primary problem I'm trying to solve. I can see your points on the trickiness of doing so with the concurrency.

**Comment by stephentoub** [comment]
Great.  Glad it works for you.
