### ISSUE TITLE
Update dogfooding instructions

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#17301]
See comments at
https://github.com/dotnet/corefx/commit/38dfde9b867a25db2d98b1fdcb86dddbd87d5928#commitcomment-21392770 from @marksmeltzer. 

There are 2 issues that should be looked at.

1. Why the Microsoft.NETCore.Platforms package isn't built by default.
2. Why does setting BuildNumberMinor not update the package version

cc @ericstj

**Comment by ericstj** [comment]
> 1. Why the Microsoft.NETCore.Platforms package isn't built by default.

Because it is a pkgproj and doesn't specify any BuildConfigurations.  Thus we build it only during the '-allConfigurations' build.  I'm fine changing this but I'd need folks to let me know when they want this thing built.  I'll also need to make it aware of the [`OfficialBuild` property we're adding](https://github.com/dotnet/corefx/issues/16126#issuecomment-287569805).

> 2. Why does setting BuildNumberMinor not update the package version

I suspect that is because these targets are squashing it https://github.com/dotnet/corefx/blob/99511c763b0aeefcef285606baaf0fb60efe7987/Tools-Override/versioning.targets.  /cc @joperezr.  I haven't root caused that.

**Comment by marksmeltzer** [comment]
The current behavior makes sense if (a) the packing isn't affected by debug/release settings and (b) the packaging is a lengthy operation. If both are true, then we just need to have a way to manually invoke the packaging build. We currently have build-native and build-managed. If there is a build-packages, or equivalent, then it is just a matter of updating the documentation.

I would be perfectly happy if I just need to call an extra command to generated updated packages after a build, provided that both (a) and (b) are true. On the other hand, if the packaging is really cheap/quick, it might be better to do it by default and have an opt-out CLI override (e.g. --skipPackaging). In the meantime, it sounds like I can use "build -allConfigurations" as a workaround.

I'd really like to see the build minor version propagating down to the final assets from the build. Right now there's very little tracability since the assemblies don't seem to bring that value in.

**Comment by marksmeltzer** [comment]
These may be non-issues. Please see the comments I added here https://github.com/dotnet/corefx/commit/38dfde9b867a25db2d98b1fdcb86dddbd87d5928#commitcomment-21392770.  Adding the "-packages" modifier to the scripts (or "-allConfgurations") fixes the issue I was having with the Microsoft.NETCore.Platforms package being outdated. So, that just needs to be added to the Dev Guide and/or the dogfooding guide.

Secondly, with this modifier in place, it seems that many of the DLLs are now have minor build number that I specified. While other DLLs have what seems to be their own independent version number. That might be by design. I'm still learning my way through CoreFx by trial-and-error. My expectation, however, is that all of the DLLs from the build would get the same version number. However, if there is a granular versioning policy per DLL within the scope of the whole CoreFx package, I suppose that might make sense too (e.g. where each DLL might have a version less than or equal to the package version, based on when it was last updated). Both versioning strategies are valid. I just don't know if the discrepancy is by design.

![image](https://cloud.githubusercontent.com/assets/19158627/24125982/b03329a6-0d88-11e7-9ebe-b4f32b00efef.png)

Only the highlighted items have odd, unexpected versions. The rest are getting my local build number. So, if this is all by design, then there is no issue to solve. (Other than updating the docs.)

**Comment by marksmeltzer** [comment]
I was wrong. @ericstj was right. I just pulled down the latest changes from master and had to update my local build of CoreFx again, and ran into the same issue. I tried the following steps, but encountered the Microsoft.NETCore.Platforms error again:

```
clean --all
build-native -release
build-managed -release
build-managed -release -packages
```

The end result was that the "dotnet restore" operator still failed.

A working procedure (that I've found so far) is this:

```
clean --all
build -release -allConfigurations
```

Using that procedure, the "dotnet restore" works as expected. This is using the 1808 nightly release of the tooling and the current latest sources (as of right now). So, it looks like Microsoft.NETCore.Platforms is not being updated with the "build-managed -release -packages" command. 

I would really like to see a more efficient way to build. I'm not clear yet on what the -allConfigurations modifier does, but the build definitely takes a lot longer! For instance, if I make some code changes, will I need to rerun the build with "build -release -allConfigurations" to get those changes into my local copy of CoreFx that I can run against? Or can would a "build-managed -release" + "build-packages -release" combo be sufficient to bring in the managed code changes once I've got a baseline Microsoft.NETCore.Platforms (et al)?

/cc: @weshaggard

**Comment by weshaggard** [comment]
>I would really like to see a more efficient way to build.

On other option you could do is to manually update your binaries after building and avoid using nuget all together. To do that all you need to do is copy the binaries from `/bin/runtime/netcoreapp*/*.dll` from your output into your published application. That should allow you do quickly iterate without needing to do a nuget restore you can just requires a copy anytime you update corefx or your application.  I will write up some steps to do this process as well.

**Comment by marksmeltzer** [comment]
That makes sense. I like problems that can be solved with a script 😄

**Comment by karelz** [comment]
@weshaggard if it is docs change, why Future? IMO we should track it in 2.0 ...

**Comment by weshaggard** [comment]
It will be a doc change and perhaps some other tweaking to the build to make it easier. I will move it 2.0 and try and get it fixed in the coming weeks.

**Comment by marksmeltzer** [comment]
Taking your suggestion, I made the following script:
```
xcopy "D:\git\dotnet\corefx\bin\runtime\netcoreapp-Windows_NT-Release-x64\*.dll" .\ /u /y /d /exclude:Copy-CoreFx-Exclude.txt
```
I have the project include both files and treat them as content. That way they end up in the rights spots so that I can call the script from the publish directory.

And the `Copy-CoreFx-Exclude.txt` file looks like this:
```
netstandard.dll
```

I found that the app bombs out if I copy that DLL. Also, I get this really odd result when running the script when nuget has properly cached my recent local CoreFx build:

```
D:\git\LivingAgile\Aspen\bin\CoreFx\vNext\AnyCPU.Release\netcoreapp2.0\win7-x64\publish>xcopy "D:\git\dotnet\corefx\bin\runtime\netcoreapp-Windows_NT-Release-x64\*.dll" .\ /u /y /d /exclude:Copy-CoreFx-Exclude.txt
D:\git\dotnet\corefx\bin\runtime\netcoreapp-Windows_NT-Release-x64\clrcompression.dll
1 File(s) copied
```

It seems the `clrcompression.dll` is out of date in the nuget cached version of my local build? That might be another build bug.

**Comment by weshaggard** [comment]
What error are you seeing when you copy netstandard.dll? 

>It seems the clrcompression.dll is out of date in the nuget cached version of my local build? That might be another build bug.

I'm not sure I'm following you on this one. Is the issue because it keeps copying it? My best guess is because everytime you call build.cmd it builds the native binaries as we don't correctly support incremental builds for those at this time, so it might always be newer and copy.

**Comment by marksmeltzer** [comment]
Repro steps:

1. Clear out the local nuget cache path (" %HOMEPATH%\.nuget\packages\microsoft.private.corefx.netcoreapp")
2. Perform a dotnet restore on the project
3. Perform a publish build of the project
4. Run the xcopy command above, which only copies newer DLLs (except netstandard.dll) that already exist in the publish dir

After those steps, I would expect to see zero DLLs copied. After all, if the nuget cache was cleared, it should have cached all the files from my local build. However, I find that the `clrcompression.dll` in the nuget cache is not the same file in my local build.

I just explored the nuget cache while writing this and discovered that the `clrcompression.dll` is not in the nuget cache. So, it might not be included in the nuget package build. That may be by design. I don't know.

It is however copied from somewhere by the dotnet publish command to my app, and it does exist in my local build. So that is why it is being overwritten by the xcopy command.

The version of `clrcompression.dll` obtained from the publish is 4.6.25122.1, and the version in my local CoreFx build is "4.6.25122.0". Odd. I have not updated my CoreFx fork this week. I'll try again and see if the DLLs sync up, and I'll grab the latest nightly of the tools as well.

Regarding `netstandard.dll`, I was wrong. I just did an xcopy with /p to interactively confirm each copy, and the issue was on the `host*.dll` files. So, if I copy `*.*`, that seems to be where the issue comes from. So I have to exclude the following files from the xcopy:

1. hostfxr.dll
2. hostpolicy.dll

Those two files are present in my publish directory and the local build. So that is why I was seeing an issue with my original script which simply refreshed all existing DLLs from the local build. Adding the "/d" flag seems to cause it to skip the host*.dll files. So the files in my local build must be older than the files brought in by the publish command.

My build has `hostfxr.dll` and `hostpolicy.dll` both version 2.0.0.1828. The publish versions are both version `1.2.0.1259`. My guess is that the issue is with the ".exe" that the publish command is creating. Copying the host DLLs and using the exe yields this error:
```
Error: assembly specified in the dependencies manifest was not found -- package: 'runtime.win7-x64.microsoft.netcore.app', version: '2.0.0-beta-001828-00', path: 'runtimes/win7-x64/native/dotnet.exe'
```
Oddly enough, it still failed with the same error when I tried invoking the dotnet.exe that is in the local release folder that I copied the DLLs from as well:
```
D:\git\LivingAgile\Aspen\bin\CoreFx\vNext\AnyCPU.Release\netcoreapp2.0\win7-x64\publish>D:\git\dotnet\corefx\bin\runtime\netcoreapp-Windows_NT-Release-x64\dotnet.exe aspencli.dll -template "..\..\..\..\..\..\..\SampleTemplates\_Controller.txt" -compiled true -consoleLog -samples 0 -regressions 10
Error: assembly specified in the dependencies manifest was not found -- package: 'runtime.win7-x64.microsoft.netcore.app', version: '2.0.0-beta-001828-00', path: 'runtimes/win7-x64/native/dotnet.exe'
``` 
I expected that one to work.

I will pull all the latest changes and tools release and see if the issue persists with the latest sources. I pulled last Wednesday.

**Comment by marksmeltzer** [comment]
@wadewegner another interesting caveat: after grabbing the nightly from 3/26, my dotnet publish build no longer produces an EXE. Instead, I find there's an "apphost.exe" in the publish folder, but I cannot get it to do anything. Must be a new thing. I'll have to check to see if there's any new info on the publish process.

```
D:\git\LivingAgile\Aspen\bin\CoreFx\vNext\AnyCPU.Release\netcoreapp2.0\win7-x64\publish>apphost
This executable is not bound to a managed DLL to execute. The binding value is: 'c3ab8ff13720e8ad9047dd39466b3c8974e592c2fa383d4a3960714caef0c4f2'
A fatal error was encountered. This executable was not bound to load a managed DLL.

D:\git\LivingAgile\Aspen\bin\CoreFx\vNext\AnyCPU.Release\netcoreapp2.0\win7-x64\publish>apphost aspencli.dll
This executable is not bound to a managed DLL to execute. The binding value is: 'c3ab8ff13720e8ad9047dd39466b3c8974e592c2fa383d4a3960714caef0c4f2'
A fatal error was encountered. This executable was not bound to load a managed DLL.
```
