### ISSUE TITLE
[Performance] Take advantage of new array range check elimination in other collections

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#17318]
See https://github.com/dotnet/coreclr/pull/9539#issuecomment-287937667; doing `if ((uint)index >= (uint)array.Length) { throw something; }` will now elide the range check for `array[index]` afterwards. Probably won't yield a huge benefit in most placecs, but the perf gains would be essentially free. We should probably do this in collections that are backed by arrays, e.g. [here](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/Stack.cs#L207) is one place where the new JIT behavior could be put to use.

**Comment by karelz** [comment]
So what exactly should happen? Adding that if statement before every loop?

**Comment by gfoidl** [comment]
I see the __up-for-grabs__ and submitted https://github.com/dotnet/corefx/pull/26086 and https://github.com/dotnet/corefx/pull/26087, and though I'm tempted to take it I won't because I don't know how much time I can spent, so the result might not be the one I excpect. Anyway I'll try to help where possible.

**Comment by stephentoub** [comment]
This is a very broad recommendation to audit a lot of code looking for small potential improvements.  Someone is welcome to do so, but we don't need an issue tracking it.  Lots of such improvements get submitted as PRs all the time.
