### ISSUE TITLE
Using CoreClr specific types in new SDK

### ISSUE THREAD

**Issue by livarcocc** [dotnet/corefx#17325]
_From @jaredpar on February 4, 2017 1:18_

Looking to do some experiments with `AssemblyLoadContext`.  This is a type specific to CoreClr and I'm having trouble accessing it using the new SDK format.  

I have a standard project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

</Project>
```

I've manually verified that a NuGet reference to System.Runtime.Loader exists in Solution Explorer.  Yet references to System.Runtime.Loader do not resolve when compiling my code.

``` txt
1>Program.cs(2,22,2,28): error CS0234: The type or namespace name 'Loader' does not exist in the namespace 'System.Runtime' (are you missing an assembly reference?)
```

Feel like I'm missing something basic here. 

_Copied from original issue: dotnet/sdk#816_

**Comment by livarcocc** [comment]
_From @nguerrera on February 5, 2017 13:20_

The nuspec for Microsoft.NETCore.App has exclude="Compile" for its System.Runtime.Loader dependency, which prevents the reference being seen by users of Microsoft.NETCore.App. So this would be expected based on how the package is defined. I don't know why it is defined that way. @ericstj?

You can add a direct package reference to System.Runtime.Loader to get the ref and use the API.

It's unfortunate that there is no indication in the solution explorer dependencies tree for this case. cc @abpiskunov @natidea @srivatsn

**Comment by livarcocc** [comment]
_From @jaredpar on February 6, 2017 23:54_

@nguerrera that does seem to be the issue.  Once I added an explicit reference everything lit up as expected.

I do want to second your notion that there is no obvious way for a developer to understand that is the case.  I spent a bit of time digging through solution explorer and the lock file to try and understand the problem here.  Nothing obvious popped out.

**Comment by ericstj** [comment]
> The nuspec for Microsoft.NETCore.App has exclude="Compile" for its System.Runtime.Loader dependency, which prevents the reference being seen by users of Microsoft.NETCore.App. So this would be expected based on how the package is defined. I don't know why it is defined that way. @ericstj?

It was defined that way initially by @weshaggard in https://github.com/dotnet/cli/commit/3ab4a30eb8433c8cd933694ea5008fe1050fdc74.

At that time I believe a group of folks decided what we wanted to be in for ref by default.  There were a few things that folks didn't want referenced by default but did need to be in shared framework (either due to impl closure or RID-specific impl) and they ended up as exclude=compile.

@weshaggard might have more context on this specific case.

**Comment by weshaggard** [comment]
Yes this was by design as we only wanted folks to use the APIs if they explicitly took a package reference to System.Runtime.Loader. We did the same thing for the Roslyn packages as it was a way to pull it into the shared framework but not have it referenced for compiling by default. 

In .NET Core 2.0 System.Runtime.Loader is no longer excluded for compile so it can be referenced and used.
