### ISSUE TITLE
Request: System.Diagnostics.Process support for CREATE_NEW_PROCESS_GROUP creation flag

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#17412]
API Proposal:

```c#
namespace System.Diagnostics
{
     public sealed class ProcessStartInfo
     {
          public bool CreateNewProcessGroup { get; set; }
     }
}
```

Usage:
```c#
var p = new System.Diagnostics.Process();
p.StartInfo.FileName = @"cmd";
p.StartInfo.CreateNewProcessGroup = true;
p.Start();
```

@PaulHigin commented on [Wed Mar 22 2017](https://github.com/dotnet/standard/issues/255)

The Process class currently supports StartInfo class information but no process creation flags.  We (PowerShell) need support for cross platform CREATE_NEW_PROCESS_GROUP creation flag to create processes outside the parent process group.  This is supported in Windows and also Linux (via setpgid()) but needs to be done during process creation.

---

@weshaggard commented on [Wed Mar 22 2017](https://github.com/dotnet/standard/issues/255#issuecomment-288577205)

This request is better served in the dotnet/corefx repo so moving there.

**Comment by iSazonov** [comment]
I should add that the issue blocks a development of remoting in PowerShell Core.

**Comment by karelz** [comment]
Next steps: We need [formal API proposal](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md).

@iSazonov do you plan to tackle it?

**Comment by iSazonov** [comment]
I suppose we would like to have this fix before RTM as it blocks PowerShell Core 6.0 RTM.
I'm not a full time so I can't control "API proposal". Maybe PowerShell team will take it 
/cc @PaulHigin @joeyaiello

**Comment by karelz** [comment]
I am not aware of PowerShell Core 6.0 schedule. If this is critical for its success, we need PowerShell team to drive the API here ASAP. The window for .NET Core 2.0 is getting smaller, we are slowly entering the end game. We can still take high-quality contributions (incl. API additions), but .NET Core team is heavily focusing on stabilization at this moment.
@PaulHigin @joeyaiello can you please chime in o the importance and if you (PowerShell team) plan to engage on this issue?

**Comment by PaulHigin** [comment]
I'll let @joeyaiello and @SteveL-MSFT discuss PowerShell Core 6.0 schedule in detail but in the near term we are trying to align PowerShell Core 6.0-beta with .Net Core 2.0 beta.  

This is a blocking issue for SSH based PowerShell remoting because it prevents Ctrl+C (https://github.com/PowerShell/PowerShell/issues/2321) from working in an interactive remote session.  The reason is that the SSH child process created by PowerShell handles Ctrl+C signals because it is part of PowerShell's process group.  The Ctrl+C signal causes SSH to terminate the current session, instead of letting PowerShell process the signal through its remoting protocol.  

This issue has been fixed for Windows platform by creating the SSH process outside of PowerShell's process group, through the CREATE_NEW_PROCESS_GROUP process creation flag.  But .NET does not support process creation flags and so SSH process creation is currently done using Windows native APIs via PInvoke.  But this won't work on other platforms so we are requesting that this capability be added to .Net System.Diagnostics.Process class.

As for a new API request I feel we should continue following the Windows API and create a new CreationFlags property for the System.Diagnostics.Process type, that takes an enum that includes at minimum CREATE_NEW_PROCESS_GROUP which will work over Windows and Linux platforms.  For Linux platforms the setgpid() API can be used to create a new process group Id during process creation.

**Comment by karelz** [comment]
Given that this is highly specific API and given the tight timelines, I think it would be best if PowerShell uses PInvokes in 6.0 on both Windows and Linux. Once you have implementation which works for your needs, we can think about adding it into .NET Core as general API on Process.
Will that work?

**Comment by PaulHigin** [comment]
For Windows it is Ok since it is already there, but for Linux it means re-producing all of the code now in .Net for creating Linux processes just to add this one flag.  It would be infinitely easier to simply update existing .Net code.

**Comment by karelz** [comment]
OK, in that case please create [formal API proposal](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md) - it has to take into account future cross-platform usage of the API (flags should not be Windows-centric).

Let's see if it can get through, or not. Note: No guarantees on the result - we won't push APIs into the platform, unless we are convinced they are the right thing for the platform, in the right direction, etc. (just stating the obvious ;-))

**Comment by karelz** [comment]
cc @Priya91 @stephentoub if they have deeper insight into the involved `Process` APIs here.

**Comment by karelz** [comment]
Here's proposal from @PaulHigin (from #17481 dupe) 

This is a request for a new CreationFlags property that is identical to creation flags in Windows native API CreateProcess().  This needs to work appropriately for Windows and Linux platforms but should work identically for the CREATE_NEW_PROCESS_GROUP flag since process groups are similar between the two platforms.

Proposed API
---------------
CreationFlags property is of type CreationFlags that is an enum of supported creation flags
```c#
public CreationFlags System.Diagnostics.Process.CreationFlags { get; set; }

[Flags]
public enum CreationFlags
{
    CREATE_NEW_CONSOLE = 0x00000010,
    **CREATE_NEW_PROCESS_GROUP = 0x00000200**,
    CREATE_BREAKAWAY_FROM_JOB = 0x010000000,
    CREATE_DEFAULT_ERROR_MODE = 0x04000000,
    ...
};
```:

**Comment by karelz** [comment]
I think that new APIs should be either designed in a cross-platform way (as I mentioned above), or exposed only for specific OS (e.g. Unix file permissions, etc.).

@PaulHigin your proposal is mix of both - it exposes Windows API shape, yet asks for cross-platform implementation. We did that in the past for APIs which existed prior to .NET Core and prior to .NET cross-platform efforts. However, it is not something we want to do for new APIs. Can you please adjust your proposal from that perspective?

**Comment by Priya91** [comment]
Currently we support only create_no_window and create_unicode_environment creation (set default) flags from windows. The Create no window is exposed as property on StartInfo. 

So I guess the create_new_process_group will be added as another property to startinfo. We might not support the entire creation flags enum from win32.

**Comment by Priya91** [comment]
@PaulHigin I've updated the top comment in the issue with the information on the required API. Does this satisfy your scenario?

**Comment by PaulHigin** [comment]
I am fine making CreateNewProcessGroup a Boolean on the ProcessStartInfo class since this appears to be the pattern already started (with similar CreateNoWindow Boolean).  But it doesn't seem very scalable as more process creation options are added in the future.

**Comment by karelz** [comment]
@PaulHigin what would you propose? Platform independent flags? (not seeded with Windows names)

**Comment by iSazonov** [comment]
The properties look good for C# world, flags for C/C++.
Currently we have 16 flags in [Process Creation Flags](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684863%28v=vs.85%29.aspx) It can be assumed that the properties will be no more.

**Comment by PaulHigin** [comment]
Yes, I feel platform independent flags would be more appropriate and there is nothing wrong with enum flags in C#.  But again I am fine with just a new property in ProcessStartInfo since that follows the existing pattern.

**Comment by karelz** [comment]
@PaulHigin can you please propose both alternatives in formal API proposal form with usage samples (no implementation is needed), so that we can discuss them in next API review meeting?

We are finishing off 2.0 work, and both area experts are OOF, so we will wait with further progress until next week.

**Comment by karelz** [comment]
The API review is not complete yet - see [API review process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md) -
 we're in step 3, steps 4 and 5 didn't happen yet.

**Comment by PaulHigin** [comment]
I have abandoned my original API proposal in favor to what Wes and Priya suggested.  It works fine and fits nicely with the existing implementation.
API as proposed above:
```
namespace System.Diagnostics
{
     public sealed class ProcessStartInfo
     {
          public bool CreateNewProcessGroup { get; set; }
     }
}
```

Usage:
```
var p = new System.Diagnostics.Process();
p.StartInfo.FileName = @"cmd";
p.StartInfo.CreateNewProcessGroup = true;
p.Start();
```

**Comment by karelz** [comment]
OK, let's get it reviewed in next API review session...

**Comment by PaulHigin** [comment]
I spent some time experimenting with CreateNewProcessGroup on Linux platforms and unfortunately it doesn't solve my needs for PowerShell SSH based remoting.  I need to do more custom work when creating the SSH process and it is something that I doubt should be exposed through ProcessStartInfo

So please close this API request since it is no longer useful for me and probably isn't needed for most users.

**Comment by karelz** [comment]
Given that nobody asks for the API currently, let's close it.
It is better to design APIs with consumer at hand. We do not have it now.
If someone needs the API and has a reasonable use case, please ping the issue and we can reopen it.

**Comment by jhallam3** [comment]
Hey, Im currently trying this in Linux, Ive got a MVC .net core 1.1 site. and that currently uses Visudo to run commands. which works ok. Issue is I want to execute command lines from the website to the server IE update files from a git pull, delete files etc. I cant see any guidelines for this or examples any where so my last option is on here. 

why I need this.. my application can be updated from the website without going to the backend. this lets users update the app and from here stops uses from having command line to the linux console. I cant see anyone else doing this yet but would want to build a package for this so others can use it.

**Comment by cbuxbaum** [comment]
Hi, I am looking to be able to set the flag CREATE_BREAKAWAY_FROM_JOB when I create the Process.  I need this so the Native Host when called from Firefox Native Messaging can spawn a Windows program that will continue to run after the Native Messaging Host ends:
 From the Firefox documentation:

On Windows, the browser puts the native application's process into a Job object, and kills the job. If the native application launches any additional processes and wants them to remain open after the native application itself is killed, then the native application must launch the additional process with the CREATE_BREAKAWAY_FROM_JOB flag

Thanks!

Carl

**Comment by karelz** [comment]
@cbuxbaum this is closed issue. If you think such API is necessary, please file a new formal [API proposal](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md).
Please consider also cross-platform implementation and behavior on Linux/Mac.

**Comment by cbuxbaum** [comment]
Hi, Thanks.

Under FireFox Native Messaging, the behavior I mention is only an issue with SendNativeMessage.   There is an alternative, ConnectNative, that establishes a Port to the running Native Host until the window is closed or Port is disconnected.  Therefore, the Windows executable called from System.Diagnostics.Process.Start() remains running until the Host is shut down.

So I have what I need through a different approach.

Thanks!

Carl Buxbaum
Senior Software Architect
17 Rogers St
Gloucester, MA 01930
1-978-515-5128

[cid:image001.png@01D2DBB9.68CF1440]<https://www.bamboorose.com/>   [cid:image002.png@01D2DBB9.68CF1440] <http://www.facebook.com/BambooRoseCommunity>    [cid:image003.png@01D2DBB9.68CF1440] <https://www.linkedin.com/company/2814733>    [cid:image004.png@01D2DBB9.68CF1440] <https://twitter.com/GoBambooRose>    [cid:image005.png@01D2DBB9.68CF1440] <https://www.youtube.com/channel/UCmVhcuiXr9JbN9H8DBZcNNg>    [cid:image006.png@01D2DBB9.68CF1440] <https://www.bamboorose.com/blog/>

**Comment by TicoDePano** [comment]
News on PGID?

I really need it to cleanly close a console Process started from another console application in NETCORE.

And a way to find parent and children processes from the Process class, including evaluating PGID, would be nice in the Process class API.
