### ISSUE TITLE
Request: Support for System.Security.Cryptography.RSACryptoServiceProvider or similar

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#17410]
@PaulHigin commented on [Wed Mar 22 2017](https://github.com/dotnet/standard/issues/256)

Just want to make a formal request for this crypto provider or similar.  We (PowerShell) need it over multiple platforms for secure credential passing.  We also need ephemeral keys (no UI interaction), CRYPT_VERIFYCONTEXT, that is supported in native Windows API but apparently not in the .Net implementation.

---

@weshaggard commented on [Wed Mar 22 2017](https://github.com/dotnet/standard/issues/256#issuecomment-288577138)

I think this request is better served in the dotnet/corefx repo so moving it there.

**Comment by PaulHigin** [comment]
@bartonjs /cc @SteveL-MSFT
This is old PowerShell remoting code that I am not yet very familiar with.  It is used for a key exchange needed for PSCredential (based on SecureString) passing.  The only code comment about why Windows native APIs are used is that .Net did not support (at that time) ephemeral key generation.  

Since .Net does support ephemeral keys (as you describe above) then AFAIK there is no reason not to use the .Net implementation as long as it works across platforms (Windows and Linux).

I'll look at refactoring the code using RSA.Create() as you suggest above.  As long as this works on Windows/Linux we should be good.  If I run into problems I'll report back here.

**Comment by karelz** [comment]
Sounds like we can close this issue.
