### ISSUE TITLE
FileSystemWatcher degenerate file rename events (In reference source)

### ISSUE THREAD

**Issue by bthomp2420** [dotnet/corefx#17438]
It appears that in a rare case where a large volume of file changes and file renames are occurring, The processing loop for an IO Completion callback to consume the directory change events can have the first part of a rename event pair at the *very end* of the buffer and then the next completion event containing the second part at the *very beginning* of the following buffer.  This results in a degenerate pair of rename events where the first event has an old name and empty new name followed by a second event that has a new name and empty old name.

**Comment by bthomp2420** [comment]
This doesn't appear to be a bug in the CoreFx implementation of FileSystemWatcher but it does appear to be a bug in the .NET 4.6.1 reference source implementation.

**Comment by karelz** [comment]
We do not track non-.NET Core bugs in CoreFX GitHub. Hence closing the issue.
If you need the bug fixed in Desktop, please contact Microsoft support.

Alternative: If you identified the PR which fixed it in CoreFX, link it here and I can mark it as netfx-port-consider -- that way we will consider it for porting once we get to porting bug fixes from .NET Core / CoreFX to Desktop. However, note that marking bug with netfx-port-consider is not guarantee we will port it. The risk of change and its value will play key roles during decisions of what to port to Desktop and what not to port.

**Comment by stephentoub** [comment]
This code is the same in core as it is in desktop.  If it's a bug in desktop, it's almost certainly a bug in core as well.
https://referencesource.microsoft.com/#System/services/io/system/io/FileSystemWatcher.cs,519
https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs#L269

**Comment by karelz** [comment]
@bthomp2420 why did you think it is not a problem in CoreFX? A mistake or something we overlooked?

**Comment by ianhays** [comment]
[This behavior is present in both netcore and netfx](https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs#L295), though I'm not certain there's much we can do about it without potentially messing up another scenario. The issue with waiting until the next buffer comes is that we're not certain it *will* come, so if we wait then we would end up dropping the OLD_NAME Renamed event. We would at the very least be required to add in some sort of delayed event raising until the following callback, which is a heavy solution for an edge case like this.

Since this is an edge case with behavior matching desktop, I'm pushing it out of 2.0.0. @bthomp2420 I'd be interested to hear if you have any ideas on cleanly combining Renamed events across callbacks.

**Comment by JeremyKuhne** [comment]
Triage: Closing due to low interest on this edge case.
