### ISSUE TITLE
Xml Serialization code vs documentation

### ISSUE THREAD

**Issue by crone66** [dotnet/corefx#17483]
Hello,

I want to use xml serialization to share (load and save) structs between a .net Core and .net Framework application but the XmlSerializer is unavailable in .net Core.

According to the .net core API reference the XmlSerializer is implemented, what I'm missing? Is the documentation out of date or what I've to do in .net Core to use the XmlSerializer?

Version: .Net Core 1.1/.Net Standard 1.6 - VS 2017 Commuity

API-Ref:
https://docs.microsoft.com/de-de/dotnet/core/api/system.xml.serialization.xmlserializer

**Comment by svick** [comment]
[`XmlSerializer`](https://apisof.net/catalog/System.Xml.Serialization.XmlSerializer) is in the `System.Xml.XmlSerializer` package. You will need to reference that package from your project to use it.

**Comment by crone66** [comment]
Thanks, didn't checked for packages. Its my first real .net Core project and it wasn't that clear in the documentation that most parts of the framework are not included and have to be added manually.

It would be great to add some kind of note to every not included namespace in the API reference. It is quite confusing for .net core newbies like me 😃 

In addition it would be great if the intellisense could automaticlly detect missing packages like its done with missing references.

**Comment by svick** [comment]
> It would be great to add some kind of note to every not included namespace in the API reference. It is quite confusing for .net core newbies like me 😃

It's not just newbies, that information is useful for everyone who does not remember every single package (which I assume is everyone 😄). Which is why I proposed that this information should be added to the API reference: https://github.com/dotnet/docs/issues/320.

> In addition it would be great if the intellisense could automatically detect missing packages like its done with missing references.

It should be able to do that, [if you enable the option](https://www.hanselman.com/blog/VisualStudio2017CanAutomaticallyRecommendNuGetPackagesForUnknownTypes.aspx). (Though I just tried it and couldn't get it to work, maybe you will have more luck.)

**Comment by karelz** [comment]
@crone66 please upvote the docs issue, so that the right folks know about the feedback (cc @mairaw)

Regarding your other suggestion, it seems to be answered by @svick above.

There doesn't seem to be anything actionable for CoreFX repo left in the issue, so closing. Please let me know if I missed anything.
