### ISSUE TITLE
Overzealous "URI not absolute" InvalidOperationExceptions from Uri instance members

### ISSUE THREAD

**Issue by ColinWade** [dotnet/corefx#1751]
Many of Uri's instance properties throw an InvalidOperationException complaining that the operation is not supported for a relative URI. In some cases, this doesn't really make sense. 

The best example I can think of is the Uri.HostNameType property. Consider the scenario where one constructs an instance of the Uri class with the path "www.domain.com". As expected, this evaluates to a relative path, because the protocol has not been specified. However, absolute or not, one would expect the value of its Uri.HostNameType to be UriHostNameType.Dns. Instead, checking the HostNameType throws an exception.

This particular scenario also exhibits an inconsistency with other members of the Uri class. Uri.CheckHostName(string name) is a static method which returns a UriHostNameType value, just the same as the Uri.HostNameType instance property. One could reasonably expect the following two calls to return the same value:

var hostType = new Uri("www.domain.com", UriKind.RelativeOrAbsolute).HostNameType;
var hostType = Uri.CheckHostName("www.domain.com");

Unfortunately, the first call throws an exception. The second call using CheckHostName, however, returns the expected value: UriHostNameType.Dns.

**Comment by MikePopoloski** [comment]
I agree. In general, Uri is ridiculously exception-happy. It makes it very difficult to work with.

**Comment by hackcraft** [comment]
All of this seems appropriate.

> Consider the scenario where one constructs an instance of the Uri class with the path "www.domain.com". As expected, this evaluates to a relative path, because the protocol has not been specified.

And also the hostname hasn't been specified, nor the full path, just a relative path.

> However, absolute or not, one would expect the value of its Uri.HostNameType to be UriHostNameType.Dns

No, because it doesn't have a host name.

> One could reasonably expect the following two calls to return the same value:

No, because `Uri.CheckHostName` receives a string that represents a host name, which a the part of your URI that is missing.

If we start with your relative URI `var relUri = new Uri("www.domain.com", UriKind.Relative‎OrAbsolute)`, then it's hostname will depend on how we create an absolute URI with it:

    var absUri = new Uri(new Uri("http://example.org/"), relUri);
    // result  was <http://example.org/www.domain.com>, HostNameType was Dns
    var absUri = new Uri(
      new Uri("https://127.0.0.1/somewhere/over.the?rainbow"),
      new Uri("www.domain.com", UriKind.Relative‎OrAbsolute));
    // result was <https://127.0.0.1/somewhere/www.domain.com>, HostNameType was IPv4

That the two absolute URIs produced by applying your relative URI to a base had different `HostNameType` values points to the inappropriateness of trying to get the `HostNameType` from the relative URI.

Since `new Uri("www.domain.com", UriKind.Relative‎OrAbsolute)` doesn't have a host name, any method that needs its host name must fail either with an exception or with a value that represents a lack of host name.

Now, `new Uri("//www.domain.com", UriKind.Relative‎OrAbsolute)` on the other hand does have a host name, and if passed to the examples above would result in absolute URIs of `http://www.domain.com/` and `https://www.domain.com/` respectively; always `Dns` in any case. In this case the lack of support for `HostNametype` does seem to be overzealous.

**Comment by SidharthNabar** [comment]
Assigning to future milestone since we will not be able to make these changes before RTM timeline due to other higher priority issues.

**Comment by karelz** [comment]
It looks like a good idea and overall goodness, however we might run into bad compat problems with security implications. It would be best to expose this functionality as opt-in API, so that we don't accidentally break old apps.

For example - new argument in constructor.

Next steps: We need formal API proposal.

**Comment by karelz** [comment]
Open question: What to prepend to strings: 'http:' or 'https:' or 'mailto:', etc,?
Idea: Mimic what browsers do.

**Comment by JonHanna** [comment]
Making Uri guess a string is a domain name and then guest it's meant to be used as a host would break anything that looked like a domain name that really had been intended to be a relative path.

**Comment by rmkerr** [comment]
This probably isn't feasible, just because of the broad set of use cases for System.Uri. For example, it's perfectly legal to name a file system folder like this: `Folder.With.Dots`. If we create a relative file path using system URI, the suggested change would result in `HostNameType` evaluating to DNS. While this change would be _convenient_ in web only scenarios, it would impact _correctness_ in other situations.

The case Jon brought up is similar. `//www.domain.com` can be interpreted two ways. As a UNC share with the host `www.domain.com`, or as a relative path with an empty segment: `/<empty>/www.domain.com/`. Since the correct parsing is ambiguous without a scheme, we again have to err on the side of caution and cannot safely return the host name type.
