### ISSUE TITLE
Two MathF Tan tests failing on some Unix distros

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#17518]
Failing on at least Ubuntu 16.04, Ubuntu 16.10, Fedora 23, and Fedora 24.  Passing on Ubuntu 14.04, CentOS 7.1, and some others.
```
     System.Tests.MathFTests.Tan(value: 1.570796, expectedResult: -2.287733E+07, allowedVariance: 0) [FAIL]
        Assert.Equal() Failure
        Expected:  -22877332
        Actual:    -22877334
        Stack Trace:
           /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu16.10_debug/src/System.Runtime.Extensions/tests/System/MathF.netcoreapp.cs(123,0): at System.Tests.MathFTests.AssertEqual(Single expected, Single actual, Single variance)
           /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu16.10_debug/src/System.Runtime.Extensions/tests/System/MathF.netcoreapp.cs(1103,0): at System.Tests.MathFTests.Tan(Single value, Single expectedResult, Single allowedVariance)
     System.Tests.MathFTests.Tan(value: -1.570796, expectedResult: 2.287733E+07, allowedVariance: 0) [FAIL]
        Assert.Equal() Failure
        Expected:   22877332
        Actual:     22877334
        Stack Trace:
           /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu16.10_debug/src/System.Runtime.Extensions/tests/System/MathF.netcoreapp.cs(123,0): at System.Tests.MathFTests.AssertEqual(Single expected, Single actual, Single variance)
           /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu16.10_debug/src/System.Runtime.Extensions/tests/System/MathF.netcoreapp.cs(1103,0): at System.Tests.MathFTests.Tan(Single value, Single expectedResult, Single allowedVariance)
```
cc: @tannergooding, @mellinoe

**Comment by tannergooding** [comment]
It might actually be worth just removing this test. It isn't an edge case specified by the IEEE spec but it is an edge case at (essentially) the upper bound of the allowed input ranges.

I only added it because it is the inverse of `Atan(double.PositiveInfinity)`. However, since floating-point numbers are imprecise, `Math.Tan(π / 2)` returns a large number, rather than `double.PositiveInfinity`.

We aren't likely to have this passing on all platforms unless we standardize on a single implementation for these core math functions (read as: either implement ourselves or get approval to open source the implementation we have in the UCRT).

**Comment by stephentoub** [comment]
Would it make sense to keep the tests but allow some range of outputs rather than a specific output?

**Comment by tannergooding** [comment]
Yes, we could. The current output is only off in the 8th significant digit, and values should ideally be accurate to within 6-9 digits.
