### ISSUE TITLE
System.Runtime.Serialization.Formatters for NETStandard.Library 1.6.0

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#17528]
Why is there no System.Runtime.Serialization.Formatters package that depends on the packages from NETStandard.Library.1.6.0? There is only a version that is 4.3.0 which means to include binary serialization I have had to target packages from 4.3.0 which then appears to copy them all into apps that are netcoreapp1.0.

https://github.com/JamesNK/Newtonsoft.Json/issues/1252#issuecomment-289250145

**Comment by karelz** [comment]
For context: [System.Runtime.Serialization.Formatters package](https://www.nuget.org/packages/System.Runtime.Serialization.Formatters/).

@ericstj @weshaggard can you please chime in?

**Comment by weshaggard** [comment]
The reason this is the case is because for all our release we base-line our package dependencies to match that release. This does cause some issues for new packages like this one because it doesn't have a target for the older platforms. @ericstj what do you think about fixing this?

On top of potentially fixing this individual package I know @ericstj is looking at fixing the NETStandard.Library package to handle the LTS issue (https://github.com/dotnet/corefx/issues/15735).

**Comment by JamesNK** [comment]
I don't want System.Runtime.Serialization.Formatters package in NETStandard.Library 1.6.0, I want it to depend on similar packages. If I reference it with NETStandard.Library 1.6.0 then there are a lot of warnings about packages having mis-matching versions.

There was an RC that did depend on the same version of packages as 1.6.0 but there was never a final version of it - https://www.nuget.org/packages/System.Runtime.Serialization.Formatters/4.0.0-rc3-24212-01

Why?

**Comment by weshaggard** [comment]
>Why?

There was a decision made to make all our corefx packages that shipped with .NET Core 1.1 to be self-contained, so the dependencies were baselined to match what was shipped at that time.

**Comment by JamesNK** [comment]
But why did you never release a .NET Core 1.0 version?

**Comment by ericstj** [comment]
IIRC it was brand new API that wasn't done until .NET Core 1.1.

**Comment by JamesNK** [comment]
So you didn't create a 1.0 version?

The problem is right now I'd like to use it with Json.NET but having 1.1 dependencies is causing DLLs to be copied into netcoreapp1.0 outputs which people don't like. If I want to only depend on 1.0 DLLs then I can't reference System.Runtime.Serialization.Formatters.

**Comment by davidfowl** [comment]
We wee supposed to denounce LTD and FTS for packages because it really doesn't work. We have this problem all over the stack and even for 3rd party packages. There's no sane way to fork packages along LTS and FTS lines when the only real pivot is a TFM.

All this to say my advice to you is not to worry about 1.0. The assets get copied to the output folder and there's no workaround other than to cross compile for netcoreapp1.0 which would be unfortunate.

**Comment by weshaggard** [comment]
@ericstj is it safe to assume there isn't anything we plan to do with this?

**Comment by weshaggard** [comment]
Closing as I believe this is expected. If I'm missing something please let me know.
