### ISSUE TITLE
System.Diagnostics.Tracing.EventSource EventAttribute does not have a Channel property.

### ISSUE THREAD

**Issue by Jtfinlay** [dotnet/corefx#17559]
Hitting an issue when trying to use EventSource as an interface to the Event Log, where Channel property support is not implemented.

> Exception thrown: 'System.Reflection.MissingMetadataException' in System.Diagnostics.Tracing.dll
>
> Additional information: Reflection_InsufficientMetadata_EdbNeeded: System.Diagnostics.Tracing.EventAttribute. For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485

From discussion with @vancem and others on the team:

> Your usage case has taken us by surprise.    Originally EventSource on .NET Native was pruned to remove channel support.   Indeed it was only because of a what amounts to a bug (reference assemblies were updated for harmonization (it was important that the API be the same across all our platforms), but the implementation was not turned on, and testing was not done).  This is why it compiles but fails at runtime.    Obviously this is a bug in the .NET Native runtime/toolchain.  
> 
> It looks like you are really trying to use EventSource not to log windows Asimov-style telemetry but as an interface to the EventLog (which we did not think was an interesting scenario for .NET Native).   
> 
> It is probably not hard to fix (there are probably some #ifdefs that need to be adjusted and tests need to be turned on).    However it would require an updated runtime/toolchain, so that does not help you in the very short term.   
> 
> I think in the very short term(until we fix the runtime/toolchain and you pick up a new toolchain), you have to stick with Microsoft.Diagnostics.Tracing.EventSource (but what I said before is still true, we don’t like people to do this and it really is not supported).  

We are using the Microsoft.Diagnostics.Tracing NuGet package in the meantime, but we want to remove it to use System.Diagnostics as soon as possible. The NuGet package is outdated and inflating our dll.

Let me know of any other details needed to debug this issue.

Thanks for the help,
James

**Comment by karelz** [comment]
@MichalStrehovsky FYI: We do not assign issues to folks, unless they work on them - see [triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified)

**Comment by vancem** [comment]
I believe the particular issue (not having access to the Channel property in the EventAttribute has been resolved (we basically added the necessary properties to the reference assemblies).  

However this is not particularly useful, however things *Might* work on windows now that this is unblocked (We don't seem to have testing for channels on .NET Core .NET Native, so we should determine the level of support.

It would help us if you at least tested determined if your scenario worked or not.

**Comment by agm59** [comment]
We depend on Channel support and similarly are using the Microsoft.Diagnostics.Tracing NuGet package.
We were hoping and assumed that it would follow immediately into System.Diagnostics.Tracing.
Etw has the potential to be fantastic but is being badly let down by the supporting infrastructure and your decisions on this component need to be intimated to the developer community rather than letting us try to discern the direction by reading tea leaves.....

**Comment by Jtfinlay** [comment]
Apologies for late reply, did not see these earlier responses. What would be the best way to test these changes? In our project, we include the Microosft.NETCore.UniversalWindowsPlatform nuget. We are on 5.3.3, which includes .Net Native 1.6. 

Latest UWP package  is 5.4.0, which includes .Net Native 1.7. I still hit the problem after updating to this and deploying the app on RS3.

Can you provide some details on the easiest way to test out the changes?

**Comment by vancem** [comment]
adding @brianrob 

Note however, that the main problem with Channel support is that (to my knowledge at least) windows channels are not xcopy deployable).  That is in order to use channels you have to create a manifest and register that manifest with the operating system before you use the code (typically at install time).   Do you do this?   

Or to put it another way, I don't understand your scenario (in particular with regard to manifest for the channels and how it is registered).   We need to work through  this to see if the scenario can even be made to work.

**Comment by Jtfinlay** [comment]
This is for the C# UWP Store client across Windows devices. We are checked in as an inbox app to Windows, and updateable through the dev centre. 

Let me reach out over email and I can share some of our implementation for how we are working with Channels.
