### ISSUE TITLE
Non-shipping packages for .NET Core 2.0

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#17611]
This issue is tracking packages that we shouldn't make stable for the .NET Core 2.0 release. @ericstj  do you have any suggestion for how to do this in code so we don't accidentally stabilize these? 

- System.Memory 

cc @ericstj @Petermarcu

**Comment by Petermarcu** [comment]
We also need to make sure it isn't exposed in the surface area of netcoreapp,

**Comment by ericstj** [comment]
@Petermarcu it is not.  That's already handled by not including it and the closure walks that we do.  Folks can disable this stuff, and we'd have to catch that in code review.  We could add more redundant checks but really that's just more stuff that folks can delete and we'd have to catch in code-review.

The process for stabalizing things isn't done in code.  We check in an update to the packageIndex to do that.

We could do that work now and just have it ready and make sure that certain things are excluded.  We could go and add some target to that ensures things aren't stable to just create another place someone would have to change in order to make it stable.

I'm really not sure how far you want to go here.  The way I read this issue is "make more redundant checks to make it harder to move packages stable".

**Comment by weshaggard** [comment]
@ericstj do you think we should keep this issue around as a forcing function to audit the other packages? Or do you feel that will get covered by our other auditing issues?

**Comment by ericstj** [comment]
I don't assume that this is even a comprehensive list.  I expect to get explicit sign-off at the time we mark things stable that folks want to ship them as stable.  I'm only doing this proactively if folks want to volunteer that information now and I'll record it.

Please let me know if you have specific packages you want to mark now and I'll do it.
