### ISSUE TITLE
[Netfx]: HttpUtility.UrlDecodeToBytes doesn't decode correctly when having a UTF8 encoded character.

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#17627]
In full framework `HttpUtility.UrlDecodeToBytes` when the string to decode has a UTF8 encoded character e.g (%u0061 -> a) it wouldn't decode it and would leave it as it is.

Example

```cs
string encoded = "http://127.0.0.1:8080/appDir/page.aspx?foo=b%u0061r";
Console.WriteLine(Encoding.UTF8.GetString(HttpUtility.UrlDecodeToBytes(encoded, Encoding.UTF8)));
```

Would print out the same string and it should print: `"http://127.0.0.1:8080/appDir/page.aspx?foo=bar"`

cc: @davidsh

**Comment by davidsh** [comment]
>In full framework HttpUtility.UrlDecodeToBytes when the string to decode has a UTF8 encoded character e.g (%u0061 -> a) it wouldn't decode it and would leave it as it is.

The .NET Framework behavior is the correct behavior.

See:
https://docs.microsoft.com/en-us/dotnet/api/System.Web.HttpUtility.UrlDecodeToBytes?view=netframework-4.7#System_Web_HttpUtility_UrlDecodeToBytes_System_String_

In general URL encoding/decoding does this:

>URL encoding converts characters that are not allowed in a URL into character-entity equivalents; URL decoding reverses the encoding.

In terms of "normal" characters, i.e. characters that *are* allowed in a URL as-is such as ASCII characters "a", i.e. 0x0061, URL decode will not reverse the percent encoding if it was explicitly made.

If .NET Core, however, is un-doing the percent encoding of normal ASCII characters such as 0x0061 ('a'), then the bug is with .NET Core implementation.

**Comment by safern** [comment]
>If .NET Core, however, is un-doing the percent encoding of normal ASCII characters such as 0x0061 ('a'), then the bug is with .NET Core implementation.

Then we should rename the [Netfx] in the title and fix the tests to expect the netfx behavior since I splitted them into two different tests in PR: #17618 

And should add 2.0.0 milestone right?

**Comment by davidsh** [comment]
How was this bug discovered in the first place?  Did the existing HttpUtility tests fail in some way?  Which ones? Are we missing test coverage or perhaps the tests are wrongly written i.e. they "pass" on .NET Core because they assumed the wrong behavior?

**Comment by safern** [comment]
>How was this bug discovered in the first place? Did the existing HttpUtility tests fail in some way? Which ones? Are we missing test coverage or perhaps the tests are wrongly written i.e. they "pass" on .NET Core because they assumed the wrong behavior?

The HttpUtility tests were failing in Desktop so I thought this was a bug in desktop and I opened this issue. The tests assumed the wrong behavior and passed on .NET Core but failed in desktop.

See PR: https://github.com/dotnet/corefx/pull/17618 where I separated the tests cases -- one to be .NET Core with the wrong behavior (didn't know at that time it was a wrong behavior) and the other one is desktop specific.
