### ISSUE TITLE
System.Net.Http.FunctionalTests show a debug assert window in desktop

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#17621]
The following tests marked as Outerloop show a debug assert window when running in desktop:

* System.Net.Http.Functional.Tests.PostScenarioTest.PostRewindableContentUsingAuth_NoPreAuthenticate_Success
* System.Net.Http.Functional.Tests.PostScenarioTest.PostUsingNoSpecifiedSemantics_UsesChunkedSemantics
* System.Net.Http.Functional.Tests.PostScenarioTest.PostNonRewindableContentUsingAuth_NoPreAuthenticate_ThrowsInvalidOperationException

They seem to fail on the same Assert.

cc: @davidsh

**Comment by stephentoub** [comment]
> They seem to fail on the same Assert.

Which one?

**Comment by safern** [comment]
> Which one?

This is the assert failure:

![image](https://cloud.githubusercontent.com/assets/22899328/24429855/b3c76c12-13c8-11e7-98fe-501e19bf6c37.png)

**Comment by davidsh** [comment]
This is a behavior difference between Desktop and Core.  I need to figure out if we need to "fix" this.

**Comment by davidsh** [comment]
We currently use `Contract.Assert` in NETFX code. Normally we don't use Contract.Assert in .NET Core....we have changed to use Debug.Assert.  But since we ported that code to build the OOB System.Net.Http for NETFX, we didn't want to change any of that Desktop code.

**Comment by davidsh** [comment]
And regarding this test failure on NETFX.  What is really happening here is that the test was written to validate the .NET Core behavior (which is different from NETFX).  So, the real "fix" here is to 1) update the test to validate NETFX behavior and 2) update the product code to make it behave like Desktop.

**Comment by safern** [comment]
Well I think we should be as compatible as possible with NETFX, why is the behavior different in this case? 

Should we close this issue and open another one to track this difference in behavior?

**Comment by davidsh** [comment]
While tests have been disabled...need to investigate to see if there is an app-compat behavior difference between .NET Framework and .NET Core.

**Comment by davidsh** [comment]
After analyzing this, it turns out that this is a test-bug in the .NET Core tests, but it only occurs when running against .NET Framework.

.NET Framework HttpClientHandler (including the OOB) uses a different algorithm to resolve the ambiguity when neither 'Content-Length' nor 'Transfer-Encoding: chunked' is specified for the request body when doing POSTs.  On .NET Core, this is resolved by always switching to chunked mode. But on .NET Framework, the handler loads the request content into a buffer using an internal call to LoadIntoBufferAsync(). And it uses the HttpClientHandler.MaxRequestContentBufferSize as the maximum buffer size.

Doing the LoadIntoBufferAsync() will then cause the content size to be known.  Doing a property get on requestContent.Headers.ContentLength will then cause a side-affect of calculating the content-length of the buffered content. But it only does that caluculation if the ContentLength property has never been set  at all.

See code from HttpContentHeaders.cs

```c#
        public long? ContentLength
        {
            get
            {
                // 'Content-Length' can only hold one value. So either we get 'null' back or a boxed long value.
                object storedValue = GetParsedValues(HttpKnownHeaderNames.ContentLength);

                // Only try to calculate the length if the user didn't set the value explicitly using the setter.
                if (!contentLengthSet && (storedValue == null))
                {
                    // If we don't have a value for Content-Length in the store, try to let the content calculate
                    // it's length. If the content object is able to calculate the length, we'll store it in the
                    // store.
                    long? calculatedLength = calculateLengthFunc();

                    if (calculatedLength != null)
                    {
                        SetParsedValue(HttpKnownHeaderNames.ContentLength, (object)calculatedLength.Value);
                    }

                    return calculatedLength;
                }

                if (storedValue == null)
                {
                    return null;
                }
                else
                {
                    return (long)storedValue;
                }
            }
            set
            {
                SetOrRemoveParsedValue(HttpKnownHeaderNames.ContentLength, value); // box long value
                contentLengthSet = true;
            }
        }
```

However, this test is artificially creating this ambiguous situation by first creating a StringContent (which always has a ContentLength added to it) and then manually null'ing out the ContentLength property. However, doing it this way causes an internal property in HttpContent (base class of StringContent) to set the contentLengthSet field. This means that the ContentLength will never automatically go back to being non-null.  That is why this assert is being fired in the HttpClientHandler.net46.cs code.

The fix to this issue is to fix the test to use a custom HttpContent that is similar to StringContent but hasn't yet set the 'ContentLength' property.

**Comment by davidsh** [comment]
You could also argue that this is a defect in the net46 HttpClientHandler because it needs to be able to handle this kind of situation and somehow re-update the 'ContentLength' property to have a non-null value. This test is doing something that a dev, in theory, could do as well.

In PrepareAndStartContentUpload() method in the HttpClientHandler.net46.cs, there is this code:

```c#
// HttpContent couldn't calculate the content length. Chunked is not specified. Buffer the
// content to get the content length.
requestContent.LoadIntoBufferAsync(_maxRequestContentBufferSize).ContinueWithStandard(task =>
{
    if (task.IsFaulted)
    {
        HandleAsyncException(state, task.Exception.GetBaseException());
        return;
    }

    try
    {
        contentLength = requestContent.Headers.ContentLength;
        Contract.Assert(contentLength != null, "After buffering content, ContentLength must not be null.");
        state.webRequest.ContentLength = (long)contentLength;
        StartGettingRequestStream(state);
    }
    catch (Exception e)
    {
        HandleAsyncException(state, e);
    }
});
```
