### ISSUE TITLE
Audit configurations of CoreFX packages

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#17633]
We should probably do these two audits on packages in CoreFX:

1. If the refs has a netstandard configuration but the impl does not, satisfy ourselves that this is reasonable. For example if the impl is never going to work on anything but one platform, we might want to make the refs configuration platform specific.

1. If the impl has platform specific configurations, satisfy ourselves that they can't be replaced with netstandard configurations either trivially or with some minor change - extending the reach of the library. Particularly worth doing if the refs is netstandard, suggesting we think the impl is close.

@weshaggard @ericstj @joperezr

**Comment by tarekgh** [comment]
@danmosemsft who is going to do this task?

**Comment by danmosemsft** [comment]
@tarekgh I don't know --  unless @weshaggard or @ericstj plan to. :|

**Comment by tarekgh** [comment]
@weshaggard @ericstj any thoughts around this issue to have it done soon?

**Comment by karelz** [comment]
Moving to Infra where we track packaging ... Meta has plenty code-related cross-cutting stuff.

**Comment by weshaggard** [comment]
@ericstj did your recent PR cover this?

**Comment by ericstj** [comment]
I didn't do any "what if" scenarios in my PR.  I merely asserted we must have a netstandard impl if we have a nestandard ref.

> If the refs has a netstandard configuration but the impl does not

We validate for this.  My previous PR filled in any gaps with PNSE assemblies where necessary.

> For example if the impl is never going to work on anything but one platform, we might want to make the refs configuration platform specific.

That's not feasible for existing libraries since its a breaking change.  For new stuff we should try be conscious of this.  We can do an audit of all the new packages from this release and for any in this boat make sure we are intentional about exposion the netstandard ref.

> If the impl has platform specific configurations, satisfy ourselves that they can't be replaced with netstandard configurations either trivially or with some minor change

I can take a look at this and highlight any of these as well.

**Comment by ericstj** [comment]
## New packages in 2.0
- Microsoft.XmlSerializer.Generator
- NETStandard.Library.NETFramework
- System.CodeDom
- System.Configuration.ConfigurationManager
- System.IO.Ports
  - not supported on unix, has netstandard2.0 PNS assembly, win-specific impl
- System.Json
- System.Memory
- System.Security.Cryptography.Xml
- System.Security.Permissions

So only one of these is in the boat of having a netstandard ref but only a Windows-specific impl.  I see this in a similar boat to Registry so I recommend leaving as-is.

## RID Specific implementations in packages

Windows impl, rid-less PNS:
- Microsoft.Win32.Registry.AccessControl
- System.DirectoryServices
- System.DirectoryServices.AccountManagement
- System.DirectoryServices.Protocols
- System.IO.FileSystem.AccessControl*
- System.IO.Pipes.AccessControl
- System.IO.Ports
- System.Net.Http.WinHttpHandler
- System.Security.AccessControl*
- System.Security.Cryptography.Cng
- System.Security.Cryptography.Pkcs
- System.Security.Cryptography.ProtectedData
- System.Security.Principal.Windows*
- System.ServiceProcess.ServiceController
- System.Threading.AccessControl

\* means also has unix netcoreapp PNS for layering

Unix impl, rid-less PNS:
- System.Security.Cryptography.OpenSsl

Windows impl, Unix impl, rid-less PNS:
- Microsoft.Win32.Registry
- System.Data.SqlClient
 
Windows impl, Unix impl, rid-less impl
- System.Buffers
- System.Memory
- System.Reflection.TypeExtensions

Windows impl, rid-less impl
- System.Text.Encoding.CodePages

None of these stand out to me as opportunity for refactoring, but please analyze this to your content.

## Method
To gather this data I hacked targets into the build that dumped configuration rather than building the projects: https://github.com/ericstj/corefx/commit/7f84c19fc77fdf5af139db65e6c66bbe8274a446

Sample output is here: https://gist.github.com/ericstj/12091fa9c7db878deca9ed0e6e334502

Load in excel and convert to table to do analysis.
