### ISSUE TITLE
Porting to .Net Core Technical Question

### ISSUE THREAD

**Issue by TheSoftwareArchitect** [dotnet/corefx#17688]
I was walking through your "Porting to .Net Core" document here:  
https://github.com/dotnet/corefx/blob/2b15de70c1cf9f585c4878a722de4dbe42b4940b/Documentation/project-docs/porting.md#binary-serialization
and came across this slightly edited (for brevity) content:

"Remoting
Justification. The idea of .NET remoting -- which is transparent remote procedure calls -- has been identified as a problematic architecture...

Replacement. For communication across processes, inter-process communication (IPC) should be used, such as pipes or memory mapped files. Across machines, you should use a network based solution, preferably a low-overhead plain text protocol such as HTTP."

I'm not sure I agree with the justification, but I wanted to focus on the replacement suggestions.   Let's pick a very fast IPC method: "memory mapped files".  Unless I'm wrong (and if I am, please let me know), there's no way easy way to do this in .Net.  It's one of the most useful pieces of technology that got washed away by the "managed code" model.  Yeah; I guess if I wanted to drop back to native, unmanaged C++ I can still use memory mapped files, but that seems like a hack -- kind of like a donut spare on a sport/utility vehicle.

Since you are doing away with .Net Remoting, are you planning to support memory mapped files in managed code on all platforms?

**Comment by karelz** [comment]
@janvorli @jkotas do we have some concrete advice for Remoting replacement?
Are memory mapped files the best approach?

@TheSoftwareArchitect BTW: regarding the justification -- I have seen the code, believe me, it is super-complicated and super-fragile. The architecture is truly problematic, take our words for it.
It doesn't necessarily mean that the idea of Remoting is entirely bad, but the way it is done in CLR is not quite sustainable in CoreCLR. Doing something new form scratch would be a lot of work and competes with may other Runtime needs ...

**Comment by jkotas** [comment]
> are you planning to support memory mapped files in managed code on all platforms?

Yes. https://github.com/dotnet/corefx/tree/master/src/System.IO.MemoryMappedFiles package is supported on all .NET Core platforms. Some Windows-specific features of memory mapped files do not work on Unix.

I would not say that memory mapped files are replacement for remoting. Remoting serializes a method call on one end and deserializes it on the other end. Memory mapped files do not really help you with this problem.

**Comment by karelz** [comment]
You're right it is not Remoting replacement, I misspoke. What I meant: What kind of cross-platform/Windows-only IPC would we recommend to our customers? (are mapped file the best/only thing we have to offer in .NET Core platform)

cc @terrajobst

**Comment by jkotas** [comment]
> What I meant: What kind of cross-platform/Windows-only IPC would we recommend to our customers?

The recommendation is in the document linked above:

Replacement. For communication across processes, inter-process communication (IPC) should be used, such as pipes or memory mapped files. Across machines, you should use a network based solution, preferably a low-overhead plain text protocol such as HTTP.

**Comment by karelz** [comment]
Ah, I missed that. Third one this morning :(, I guess it is not my best day.

It would be nice to link those hints into real APIs. I can link the memory mapped files (thanks for link @jkotas). I'll find out if we have Pipes APIs.

For Http, I wonder if HttpListener is the right guidance for server-side, given that it is legacy API. OTOH for IPC purposes it should be fine ...

**Comment by tarekgh** [comment]
@TheSoftwareArchitect I am closing this issue as the question is answered but feel free to post more question or re-open. thanks.

**Comment by karelz** [comment]
I'll keep it open to track updates to the docs if you don't mind @tarekgh ...

**Comment by tarekgh** [comment]
@karelz that is totally fine. 

do yo mean the doc https://github.com/dotnet/corefx/blob/2b15de70c1cf9f585c4878a722de4dbe42b4940b/Documentation/project-docs/porting.md#binary-serialization?

**Comment by karelz** [comment]
Yep, the [Remoting part](https://github.com/dotnet/corefx/blob/2b15de70c1cf9f585c4878a722de4dbe42b4940b/Documentation/project-docs/porting.md#remoting)

Motivation: This is not the first time I see folks asking about Remoting replacement, so I'd shoot for improving our docs and to make them more discoverable.
I am collecting info about Pipes and HttpListener offline ...

**Comment by TheSoftwareArchitect** [comment]
Thanks everyone.  @karelz:  when you get the docs together, can you post the location back to this thread?  I'd like to have a good look at them.
I truly appreciate your speedy reply on the original question.

**Comment by karelz** [comment]
BTW: Internal discussion lead to agreement that we should recommend **`Sockets`** for cross-process communication. And that we should release a sample, because apparently it is easy to do it incorrectly :).
It may take a while before we get to it. If someone wants to experiment with a sample, we will be happy to guide the work and review it.

cc @geoffkizer

**Comment by davidmatson** [comment]
Here's a synthesis of options & tradeoffs after an internal survey (more from the Windows/platform mechanism side than from the .NET side) on what options to consider for local IPC in .NET. (Hopefully this is helpful for documenting when each option would be recommended/worth considering.)

* Things that operate above the stream level/at an app contract level:
    * Modern option: HTTP
    * Legacy options: WCF, .NET Remoting, COM Interop (?)
* Things that operate at the stream level: Sockets, Pipes
* Things that operate below the stream level: File Mapping (unsynchronized access to whole chunks of bytes, rather than synchronized communication via streams of bytes)

Some details regarding tradeoffs:
* File Mapping: Very low level; does not even provide a signaling mechanism to say when data is ready to be read. It requires some other IPC/signaling mechanism to do that part. But because it's just shared memory, there's not even any data copying, so it's extremely fast (basically can't get faster than this).
* Pipes:
    * vs sockets: Pipes can handle message framing for you (splitting up a stream of bytes into distinct messages, via Message mode), while with sockets you have to add that part yourself (or use something higher level-like HTTP that already does it), so in at least that one sense pipes are a slightly higher-level abstraction (not to say they’re better that sockets).
    * vs file mapping/shared memory: I think I've heard that pipes are fairly close to an abstraction that just takes file mapping/shared memory + signaling and packages them together into a synchronized byte stream view, so it should be very fast/cheap for local IPC.

If that's all accurate, a summary would be that for .NET, the closest modern replacement to .NET Remoting is some kind of HTTP stack, and that for general purpose local IPC there are two good byte stream-level options: sockets (cross-plat; easy to move off-machine if remote IPC is needed) or pipes (Windows-only, but likely excellent performance for local IPC). For the ultra-perf-critical, there’s also file mapping/shared memory, with the tradeoff that it’s even lower-level and requires handling signaling separately.

**Comment by karelz** [comment]
I forgot that we had this issue. We had a dupe which lead to docs improvement - see #8598
I am tracking `Sockets` sample in #18394 which sparked discussion about other alternatives.

Closing this issue as dupe. @davidmatson please chime in on #18394 if your findings are not covered there. PR with docs change would be also welcome!

**Comment by vodevil** [comment]
Why not using named pipe like system ?

Create a file (or memory handle) for input and another for output then tail them ? The use of Rx can be useful for that.

Exemple of tail in .net : https://github.com/RolandPheasant/TailBlazer .
