### ISSUE TITLE
Desktop: System.Threading.Tasks.Tests.EtwTests.TestEtw failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#17727]
Configuration: outerloop_netfx_windows_nt_debug ([build#1](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/1/testReport/System.IO.MemoryMappedFiles.Tests/MemoryMappedFileTests_CreateFromFile/FileDoesNotExist_mode__Truncate_/))

Failed test: System.Threading.Tasks.Tests.EtwTests.TestEtw

Message:
~~~
Assert.Equal() Failure\r\nExpected: 1\r\nActual: 0
~~~

Stack Trace:
~~~
at System.Threading.Tasks.Tests.EtwTests.TestEtw() in D:\j\workspace\outerloop_net---903ddde6\src\System.Threading.Tasks.Parallel\tests\EtwTests.cs:line 32
~~~

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/1/testReport/System.Threading.Tasks.Tests/EtwTests/TestEtw/

**Comment by danmosemsft** [comment]
@alexperovich What's your reasoning for Future? We need to get the run clean so it either needs to be disabled temporarily or permanently for netfx. Same as the netcoreapp runs.

Anyway the fix is trivial. The code to fire the event is the same
https://referencesource.microsoft.com/#mscorlib/system/threading/Tasks/TPLETWProvider.cs,253
however the provider name is `[EventSource(Name = "System.Threading.Tasks.Parallel.EventSource")]` but was
```
    [EventSource(
        Name = "System.Threading.Tasks.TplEventSource",
        Guid = "2e5dba47-a3d2-4d16-8ee0-6671ffdcd7b5", 
        LocalizationResources = "mscorlib")]
```

I'l put out a PR.
