### ISSUE TITLE
Enum.Format(no such value) returns different values with netcoreapp and netfx

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#17730]
The following test demonstrates this:
```c#
public enum AnEnum
{
    Case1 = 1
}

[Fact]
[SkipOnTargetFramework(TargetFrameworkMonikers.NetFramework, ".NET Framework returns value.ToString() if the value doesn't exist")]
public static void Format_NoSuchValue_ReturnsElementToString_Netcore()
{
    Assert.Null(Enum.Format(typeof(AnEnum), 2, "G"));
}

[Fact]
[SkipOnTargetFramework(~TargetFrameworkMonikers.NetFramework, ".NET Core returns null if the value doesn't exist")]
public static void Format_NoSuchValue_ReturnsElementToString_Netfx()
{
    Assert.Equal("2", Enum.Format(typeof(AnEnum), 2, "G"));
}
```

Netfx returns `value.ToString()`
Netcoreapp returns `null`

**Comment by svick** [comment]
For me, `Enum.Format(typeof(AnEnum), 2, "G")` returns `"2"` on .Net Core 1.0 and `null` on .Net Core 1.1.

I think this regression was caused by https://github.com/dotnet/coreclr/pull/6645:

* [`Format` directly returns the value returned by  `GetEnumName`](https://github.com/dotnet/coreclr/blob/07fa3a3/src/mscorlib/src/System/Enum.cs#L691)
* [`GetEnumName` returns `null`, with a comment saying it's the caller's responsibility to check](https://github.com/dotnet/coreclr/blob/07fa3a3/src/mscorlib/src/System/Enum.cs#L122)

cc: @benaadams @jkotas

**Comment by benaadams** [comment]
>  a comment saying it's the caller's responsibility to check

Comment is `// return null so the caller knows to .ToString() the input` as at this point the value has been converted to a `ulong`; so its to propagate back up the chain that `.ToString()` should be run on the orignal input, rather than the mangled one; as is done by [`Enum.ToString()`](https://github.com/dotnet/coreclr/blob/07fa3a3/src/mscorlib/src/System/Enum.cs#L885)

On the line highlighted `Enum.Format(... "G")` should likely have the addition of `?? value.ToString();`?

As used by `ToString` and `F` a few lines below
