### ISSUE TITLE
netstandard configurations for System.Security.Cryptography.Cng and System.Security.Cryptography.X509Certificates

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#17764]
netstandard configurations for System.Security.Cryptography.Cng and System.Security.Cryptography.X509Certificates were causing build breaks in uap and uapaot verticals. Disabled in https://github.com/dotnet/corefx/commit/a00139c78398e88bfae1649fe07fc673b9a390c3 to unblock updates.

**Comment by jkotas** [comment]
@joperezr Could you please take a look?

**Comment by joperezr** [comment]
This is expected because new types were added to standard that made these two contracts be an implementation of standard, so we can't have netstandard implementations anymore. The right way to fix is to remove netstandard as it was done, but then add back platform specific configurations (netcoreapp, uap, netfx). Looks like the only thing that was done was to remove the netstandard configs, but we need to re-add the uap and netfx builds in order to still build those assemblies for those platforms.

**Comment by joperezr** [comment]
Reopening since it looks like only Cng configurations were fixed, but X509Certificates were not.

**Comment by danmosemsft** [comment]
@joperezr this can be in the UWP milestone right?

**Comment by joperezr** [comment]
oh sorry, yes it should.

**Comment by danmosemsft** [comment]
@joperezr are you taking this - if so please assign to yourself. ...
