### ISSUE TITLE
System.Net.Security.SslStream - AuthenticateAsClientAsync is not presenting intermediate certs unless they are installed in the cert store

### ISSUE THREAD

**Issue by alextolp** [dotnet/corefx#17802]
SslStream::AuthenticateAsClientAsync is not presenting intermediate certificates unless they are installed in the cert store. I've attached a repro of the issue and confirmed this behavior with Windows and Mac.

The desired behavior is that the contents of the X509CertificateCollection parameter should appear on the server side even if the certs are not installed in the cert store.

[SslStream.zip](https://github.com/dotnet/corefx/files/888897/SslStream.zip)

**Comment by davidsh** [comment]
@alextolp Have you checked .NET Framework?  It is possible the behavior is the same.

cc: @bartonjs @CIPop

**Comment by alextolp** [comment]
Yes, the behavior is the same in .NET Framework, I tried 4.5.2 and 4.6.2.

**Comment by sbebrys** [comment]
I have the same problem on Windows Server 2012 R2 but not in Win10

**Comment by alextolp** [comment]
I've reproed this on Win10. @sbebrys have you tried the attached solution on Win10 and see the chain on the server side?

**Comment by sbebrys** [comment]
Sorry, my fault I have uncomplete chain when I use HttpClient on runtime win81-x64, when on win10 and debian everything looks ok. 
But I test my custom cert validation callback using TcpClient with SslStream and there chain is complete (root, intermediate, server cert) on all runtimes.

**Comment by alextolp** [comment]
@sbebrys interesting! Do you mind sharing your solution with HttpClient? I'm not seeing a chain on the server side with HttpClient either, unless it's installed in the cert store where HttpClient is running.

**Comment by davidsh** [comment]
>@sbebrys interesting! Do you mind sharing your solution with HttpClient? I'm not seeing a chain on the server side with HttpClient either, unless it's installed in the cert store where HttpClient is running.

Regarding HttpClient, this GitHub issue is about SslStream.  SslStream is not part of HttpClient.  So, please keep the repro instructions specific to SslStream only.  If there are issues regarding HttpClient and TLS/SSL problems, please open a separate issue.  Thx.

**Comment by karelz** [comment]
Triage: This is the same as Desktop, so not critical for 2.0. Moving to Future.

**Comment by CIPop** [comment]
This may be related to:

https://technet.microsoft.com/en-us/library/hh831771.aspx#BKMK_Changes2012R2

**Management of trusted issuers for client authentication**

When authentication of the client computer is required using SSL or TLS, the server can be configured to send a list of trusted certificate issuers. This list contains the set of certificate issuers which the server will trust and is a hint to the client computer as to which client certificate to select if there are multiple certificates present. In addition, the certificate chain the client computer sends to the server must be validated against the configured trusted issuers list.
Prior to Windows Server 2012 and Windows 8, applications or processes that used the Schannel SSP (including HTTP.sys and IIS) could provide a list of the trusted issuers that they supported for Client Authentication through a Certificate Trust List (CTL).
In Windows Server 2012 and Windows 8, changes were made to the underlying authentication process so that:
* CTL-based trusted issuer list management is no longer supported.
* The behavior to send the Trusted Issuer List by default is off: Default value of the SendTrustedIssuerList registry key is now 0 (off by default) instead of 1.
* Compatibility to previous versions of Windows operating systems is preserved.

**Comment by CIPop** [comment]
@alextolp This is by design. The _clientCertificates_ is a collection of multiple client certificates (private key is required) from which one will be selected during the TLS handshake based on the server issuer specification.
The chain will be automatically computed using the My\Intermediate Certificate Authorities on the local machine and sent part of the TLS Client Certificate response. If the chain cannot be built this way, only the selected client certificate will be sent.

For Windows, importing certificates can be achieved using mmc.exe.
For non-Windows, I've written this small script: https://gist.github.com/CIPop/baf530337cc6b29e3d6a88047661f69c

/cc @bartonjs @davidsh 

@karelz @davidsh I think this can be closed. PTAL

**Comment by karelz** [comment]
Agreed, looks like by design. Closing.
