### ISSUE TITLE
Cryptography types in core and netstandard20 more restricted than in netfx

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#17820]
These classes are marked as sealed (static) in core and netstandard but aren't in netfx:

```
System.Security.Cryptography.SHA1Managed
System.Security.Cryptography.SHA256Managed
System.Security.Cryptography.SHA384Managed
System.Security.Cryptography.SHA512Managed
```

We are getting a few omission errors:
- CannotRemoveBaseTypeOrInterface 
- CannotMakeMemberNonVirtual
https://github.com/dotnet/corefx/issues/15255#issuecomment-291137517

Are these classes intentionally now more restrict than before (also in NS2.0)? Some members are also now not virtual anymore. Wouldn't that be a breaking change for netfx NS2.0 compatibility?

cc: @bartonjs @danmosemsft

**Comment by bartonjs** [comment]
@steveharter Did the SHA*Managed types end up sealed due to copy/paste, or did we have a technical reason we had to do it?

**Comment by ViktorHofer** [comment]
@bartonjs @steveharter: Any update on this?

**Comment by bartonjs** [comment]
@steveharter?  I'm guessing we sealed them since they weren't actually managed any more, so overriding them becomes... interesting.  But if we can't seal them in netstandard, maybe we need to unseal them here.

**Comment by steveharter** [comment]
Those types and members can be un-sealed if we want to do that.

It is not necessarily breaking w.r.t. netstandard if a type because sealed, at least from past discussions on this. Also it is not possible to derive from the the other SHA* implementations because they are private and sealed types.

The original plan for these types was to use a shim\proxy pattern to forward to the 'real' implementation, like we do with some other types added to ns2.0. Because the 'real' implementation may call virtual methods, it would get ugly since the 'real' virtual methods would be called, not the 'shim' virtual methods, so overloads would not work correctly for any user-derived type. Plus those types have protected fields which we would have to set on every call in case a user-dervied class set those. Thus sealed was added. However, during implementation we found that it was easier\better to just have a copy of the code, and not shim\proxy pattern, but did not remove the 'sealed' aspect during that conversion.

**Comment by ViktorHofer** [comment]
So I will unseal the types and members.

@weshaggard I think we should also unseal them in netstandard

**Comment by weshaggard** [comment]
We intentionally sealed these types in netstandard (https://github.com/dotnet/standard/commit/6d04955a71f4789c7a10f5430d1802d1768460cc) because they were sealed in Xamarin. I personally would keep the sealed given we don't want them to be used. It is OK for netstandard and netcore to be different from netfx in these cases.

**Comment by bartonjs** [comment]
Oh, yeah, I read this wrong.  I thought it was that we sealed them here, but not netstandard.  Yeah; if they're sealed in netstandard that makes me happy.

**Comment by ViktorHofer** [comment]
Thanks wes, I will close the PR and add them to the ignore list.
