### ISSUE TITLE
NameResolutionPalTests.GetHostByName_HostName failures in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#17878]
https://ci.dot.net/job/dotnet_corefx/job/master/job/portablelinux_release_prtest/2914/consoleText
```
     System.Net.NameResolution.PalTests.NameResolutionPalTests.GetHostByName_HostName [FAIL]
        System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No such device or address
        Stack Trace:
           /mnt/resource/j/workspace/dotnet_corefx/master/portablelinux_release_prtest/src/System.Net.NameResolution/src/System/Net/NameResolutionPal.Unix.cs(148,0): at System.Net.NameResolutionPal.GetHostByName(String hostName)
           /mnt/resource/j/workspace/dotnet_corefx/master/portablelinux_release_prtest/src/System.Net.NameResolution/tests/PalTests/NameResolutionPalTests.cs(53,0): at System.Net.NameResolution.PalTests.NameResolutionPalTests.GetHostByName_HostName()
     System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName [FAIL]
        Assert.Equal() Failure
        Expected: Success
        Actual:   HostNotFound
        Stack Trace:
           /mnt/resource/j/workspace/dotnet_corefx/master/portablelinux_release_prtest/src/System.Net.NameResolution/tests/PalTests/NameResolutionPalTests.cs(129,0): at System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName()
```

**Comment by stephentoub** [comment]
Again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/portablelinux_debug_prtest/2922/

**Comment by Jiayili1** [comment]
This issue is repro on core tests in build 20170418.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170418.01/workItem/System.Net.NameResolution.Pal.Tests/analysis/xunit/System.Net.NameResolution.PalTests.NameResolutionPalTests~2FGetHostByName_HostName

**Comment by karelz** [comment]
@steveharter did you hit it in your CI runs in a loop?

@Priya91 says it is likely similar to #10764. Either way very unlikely a product bug, moving to Future.

**Comment by steveharter** [comment]
I do not have CI results for NameResolution.Pal.Tests; I will include those in next run. Did not repro running locally.

**Comment by Jiayili1** [comment]
This issue is repro on core tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170426.01/workItem/System.Net.NameResolution.Pal.Tests/analysis/xunit/System.Net.NameResolution.PalTests.NameResolutionPalTests~2FGetHostByName_HostName

**Comment by karelz** [comment]
Another occurence on 5/10 in #19636

**Comment by karelz** [comment]
Duplicate of #20245
