### ISSUE TITLE
GIT fails to sync frequently in internal corefx-dev-metadata-realsigned queue.

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#1791]
```
EXEC: src refspec dev/metadata does not match any.
EXEC: failed to push some refs to 'https://github.com/dotnet/corefx.git'
corefx-dev-metadata-realsigned\src\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00048\lib\UpdateBuildValues.targets (39): The command "git push origin dev/metadata" exited with code 1.
```

**Comment by nguerrera** [comment]
Assigning to @jhendrixMSFT

**Comment by jhendrixMSFT** [comment]
git status
HEAD detached from origin/dev/metadata
nothing to commit, working directory clean

I believe this is because the build script didn’t check out the dev/metadata branch before committing the change.  I've cherry-picked the detached change and pushed it to origin.  Now working on updating the build script so this doesn't happen in the future.

**Comment by jhendrixMSFT** [comment]
The fix is now in CoreFx master, see https://github.com/dotnet/corefx/commit/5aaaad5fbea8d1d8be7ee7af8b723ef6d2954729.  Please merge this into dev/metadata.

**Comment by jhendrixMSFT** [comment]
Fix is now in dev/metadata and has resolved the issue.
