### ISSUE TITLE
Please add support for BufferedStream type in .NET Core

### ISSUE THREAD

**Issue by abhishekram** [dotnet/corefx#1793]
We have a scenario where we implement our own stream and use the BufferedStream class to add a buffering layer on top of it.

**Comment by stephentoub** [comment]
@ericstj, do you know why we don't currently expose this from System.IO.dll?

**Comment by weshaggard** [comment]
@stephentoub It is just something we haven't gotten to exposing. It is something we should do however.

**Comment by joshfree** [comment]
@ianhays can you please look into this for RC?

**Comment by ianhays** [comment]
Sure thing :)

**Comment by stephentoub** [comment]
@ianhays, @joshfree, is this happening for RC1?

**Comment by joshfree** [comment]
It's not happening for rc1; it's currently on the backlog

**Comment by manu-silicon** [comment]
Any time estimate?

**Comment by ianhays** [comment]
Hard to say. The big question right now is the necessity and subsequently the priority of the addition of the BufferedStream. Since existing .NET streams already have built-in buffering, the BufferedStream class is only useful when wrapping a custom implemented stream (such as in the original post). General consensus in the design docs and API catalog for .NET core suggests that BufferedStream should be left out of .NET core and I tend to agree with that. 

With that said, I'd be glad to add BufferedStream to Core but I first want to be sure that we <i>should</i>. Use cases for the BufferedStream are pretty slim; FileStream, Compression, and other IO operations already have built-in buffers that preclude the necessity of additional buffering. [The MSDN example page](https://msdn.microsoft.com/en-us/library/system.io.bufferedstream(v=vs.110).aspx) uses it over a NetworkStream but I don't think that's even necessary since Sockets already have the notion of a send/receive buffer built in. The justification for leaving BufferedStream out up to this point was that it is as often misused (e.g. wrapping a FileStream) as it is properly used (i.e. wrapping a custom stream).

For those reasons, I'd like to do some more research into use cases of the BufferedStream before moving forward with bringing it to .NET core.

**Comment by stephentoub** [comment]
> The MSDN example page uses it over a NetworkStream but I don't think that's even necessary since Sockets already have the notion of a send/receive buffer built in

This is not correct.  Here's an example:

```C#
using System;
using System.Diagnostics;
using System.IO;
using System.Net;
using System.Net.Sockets;
using System.Threading.Tasks;

class Program
{
    const int NumWrites = 100000;

    static void Main()
    {
        while (true)
        {
            RunWithConnectedNetworkStreamsAsync(async (server, client) =>
            {
                var sw = Stopwatch.StartNew();
                using (var bufferedServer = new BufferedStream(server))
                using (var bufferedClient = new BufferedStream(client))
                    await TransferAsync(bufferedServer, bufferedClient);
                Console.WriteLine("Buffered:   " + sw.Elapsed.TotalSeconds);
            }).Wait();

            RunWithConnectedNetworkStreamsAsync(async (server, client) =>
            {
                var sw = Stopwatch.StartNew();
                await TransferAsync(server, client);
                Console.WriteLine("Unbuffered: " + sw.Elapsed.TotalSeconds);
            }).Wait();

            Console.WriteLine();
        }
    }

    static Task TransferAsync(Stream server, Stream client)
    {
        return Task.WhenAll(
            Task.Run(() =>
            {
                for (int i = 0; i < NumWrites; i++)
                    server.WriteByte((byte)i);
                server.Flush();
            }),
            Task.Run(() =>
            {
                for (int i = 0; i < NumWrites; i++)
                    client.ReadByte();
            }));
    }

    private static async Task RunWithConnectedNetworkStreamsAsync(Func<NetworkStream, NetworkStream, Task> func)
    {
        var listener = new TcpListener(IPAddress.Loopback, 0);
        try
        {
            listener.Start(1);
            var clientEndpoint = (IPEndPoint)listener.LocalEndpoint;

            using (var client = new TcpClient(clientEndpoint.AddressFamily))
            {
                Task<TcpClient> remoteTask = listener.AcceptTcpClientAsync();
                Task clientConnectTask = client.ConnectAsync(clientEndpoint.Address, clientEndpoint.Port);

                await Task.WhenAll(remoteTask, clientConnectTask);

                using (TcpClient remote = remoteTask.Result)
                using (NetworkStream serverStream = remote.GetStream())
                using (NetworkStream clientStream = client.GetStream())
                {
                    await func(serverStream, clientStream);
                }
            }
        }
        finally
        {
            listener.Stop();
        }
    }

}
```

Example output:
```
Buffered:   0.0092045
Unbuffered: 1.499033

Buffered:   0.003249
Unbuffered: 1.5468928

Buffered:   0.0031306
Unbuffered: 1.4093606

Buffered:   0.0028306
Unbuffered: 1.5218004
```
That's a 500x difference.

> I first want to be sure that we should

I think we should.  It's useful when someone builds a custom stream, and as shown it's useful for some streams we ship in the Framework.  I think we're being trying to be overly protective by not including it; sure, some people could use it incorrectly, but others need it and will use it correctly.  I'd rather have some people have unnecessary buffering due to using it when they shouldn't than have people try to port to .NET Core and be unable to because they're using BufferedStream, even though they're using it validly, and then force them to go and implement their own buffering solution, which is not trivial to get right.

My $.02.

**Comment by ianhays** [comment]
>This is not correct. Here's an example:

Thanks for the clarification and nice repro; looks like my hunch was incorrect on the NetworkStream.

>as shown it's useful for some streams we ship in the Framework.

I clearly placed too much emphasis on the API Catalog notes for BufferedStream:

>NetCore Design Notes: We are different; most of our streams automatically provide buffering.
Recommended Changes: Use other Stream types.  Most stream implementations in .Net framework already buffer their content, which is preferable to wrapping in a buffered stream.

;

>I'd rather have some people have unnecessary buffering due to using it when they shouldn't

This is a good counter-argument to my point about incorrect usage. If the result of incorrect usage is additional buffering that (although not helpful) will not be detrimental, then that's likely an acceptable risk. I want to be sure we're not opening people up to shoot themselves in the foot too easily but double-buffering is probably more like wearing two hats: not hurtful but unhelpful to most people. 

A comment on the BufferedStream class that it shouldn't be used to wrap the IO streams that already implement buffering would be good.

>My $.02.

Thanks for your opinion :) Like I said, I'd be glad to add the BufferedStream but wanted to be sure of its necessity before I go through with it. I've yet to find someone strongly opposed to it's inclusion, so it is likely that I will go through with bringing it in the Open at some point soon.

**Comment by stephentoub** [comment]
Thanks, Ian.

**Comment by ianhays** [comment]
There is the question of where to put it that I would like to get some discussion on. Some options:
- It currently lives in mscorlib but isn't exposed in the core build. We could toggle it to be exposed by modifying the models.xml file to not hide it.
- Move the code to CoreFX and put it in System.IO
- Move the code to CoreFX and put it somewhere else

The proposed API contains two non-inherited/overridden methods and they're both constructors that wrap around Stream:
```
    public sealed class BufferedStream : Stream {
        public BufferedStream(Stream stream);
        public BufferedStream(Stream stream, int bufferSize);
        public override bool CanRead { get; }
        public override bool CanSeek { get; }
        public override bool CanWrite { get; }
        public override long Length { get; }
        public override long Position { get; set; }
        public override IAsyncResult BeginRead(byte[] buffer, int offset, int count, AsyncCallback callback, object state);
        public override IAsyncResult BeginWrite(byte[] buffer, int offset, int count, AsyncCallback callback, object state);
        protected override void Dispose(bool disposing);
        public override int EndRead(IAsyncResult asyncResult);
        public override void EndWrite(IAsyncResult asyncResult);
        public override void Flush();
        public override Task FlushAsync(CancellationToken cancellationToken);
        public override int Read(byte[] array, int offset, int count);
        public override Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken);
        public override int ReadByte();
        public override long Seek(long offset, SeekOrigin origin);
        public override void SetLength(long value);
        public override void Write(byte[] array, int offset, int count);
        public override Task WriteAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken);
        public override void WriteByte(byte value);
    }
```

**Comment by manu-silicon** [comment]
As a user, I would have it in System.IO in CoreFX.

**Comment by terrajobst** [comment]
@ianhays, we shouldn't expose the old async APIs (`BeginXxx`, `EndXxx`). Otherwise, looks fine. Exposing it in System.IO.dll seems fine, too.

**Comment by ianhays** [comment]
Thanks @terrajobst, will do!

**Comment by mellinoe** [comment]
Generally, we should always expose things in a portable implementation if we are able to. That's only not possible if the type is in mscorlib (or System.Private.CoreLib), and leaks through some other part of the API. For example, System.IO.Stream is returned from a lot of different things in mscorlib, so we can't pull the implementation out into the partial facade. If we did, then the two type definitions wouldn't agree. I.e. you would get errors at runtime when you tried to assign an [mscorlib]Stream to a [System.IO]Stream.

There are also some other corner cases that we had to examine in the past. For example, sometimes in mscorlib we attempt to blindly cast things from one type to another, which prevents us from moving the derived type (the target of the cast) to a partial facade. Because the cast would no longer work if the type identity was not the same as the one used in mscorlib. It's theoretically possible that some code in mscorlib attempts to cast a Stream -> BufferedStream, but I doubt that happens. Also, sometimes this is just done as an optimization (to take a quicker code path for some subtype), so in that case it isn't as important.

For a niche type like this, I doubt that anything will leak the type identity of BufferedStream, so we are probably fine to move it to the partial facade.

**Comment by NickCraver** [comment]
What's the status on this one? It's a blocker on a few high-performance projects here and we'd love to see it soon as we can :)

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/pull/4456

**Comment by ianhays** [comment]
I'm in the progress of testing on the internal side of things to make sure it doesn't break anything unexpectedly when we merge. Should be merged sometime next week unless something goes horribly awry :)

**Comment by ianhays** [comment]
closed in mirror https://github.com/dotnet/corefx/pull/5225

**Comment by stephentoub** [comment]
@ianhays, do we have a separate work item tracking adding tests for BufferedStream?

**Comment by ianhays** [comment]
Yes. https://github.com/dotnet/corefx/issues/5086. I've already got them done, just need to rebase on master and submit a PR.

**Comment by stephentoub** [comment]
Great, thanks.
