### ISSUE TITLE
win10-x64 vs ubuntu.14.04-arm CultureInfo.CreateSpecificCulture("en-us").DateTimeFormat.ShortDatePattern

### ISSUE THREAD

**Issue by KSebion** [dotnet/corefx#17961]
I am not sure that this is the correct place for this or if this is not a bug but a setting I need to change somewhere.

In a publish for win10-x64, `CultureInfo.CreateSpecificCulture("en-us").DateTimeFormat.ShortDatePattern == "M/d/yyyy"`.
In a publish for ubuntu.14.04-arm, `CultureInfo.CreateSpecificCulture("en-us").DateTimeFormat.ShortDatePattern == "M/d/yy"`.
In mono on linux, `CultureInfo.CreateSpecificCulture("en-us").DateTimeFormat.ShortDatePattern == "M/d/yyyy"`.

The difference caused an exception during `DateTime.ParseExact(<string>, "G", CultureInfo.CreateSpecificCulture("en-us"))` on ubuntu.14.04-arm.
`DateTime.ParseExact(<string>, "G", CultureInfo.CreateSpecificCulture("en-us"))` on win10-x64 worked fine.

I used a kludge to detect/fix the incorrect ShortDatePattern.

Any information would be great if I am doing something wrong.
Thanks!

**Comment by tarekgh** [comment]
@KSebion it is expected to get different data on different OS's because we depend on the OS for that. you can find more differences in the data and the behavior in the globalization space. 
what is the string you are trying to parse on Ubuntu? I mean how did you format the date which you are trying to parse?  did you format it on one OS and trying to parse it on other OS? please send more info so we can help you with your question.

**Comment by KSebion** [comment]
@tarekgh The string is based on XML from a system I don't control like the following:
```
  <root>
    <month>4</month>
    <day>5</day>
    <year>2017</year>
    <hour>9</hour>
    <minute>19</minute>
    <second>49</second>
    <meridiem>AM</meridiem>
  </root>
```
Rather than parsing most of the element values to a number and using the DateTime ctor, I created a string using code like the following:
```
  var DateTimeString = String.Format(
    "{0}/{1}/{2} {3}:{4}:{5} {6}",
    month,
    day,
    year,
    hour,
    minute,
    second,
    meridiem);
```

Therefore, I am not formatting on one OS and parsing on another.
#11221 seems related to the problem.

I did not expect that a CultureInfo instance for a distinct culture could differ based on the OS.
I can understand why said instance would though.
Said difference could result in more developer confusion though since [this](https://msdn.microsoft.com/en-us/library/system.globalization.datetimeformatinfo.shortdatepattern%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) seems to imply that en-US ShortDatePattern should always be "M/d/yyyy".

I think my best solution, as you may be implying, is to use a CultureInfo instance and standard format specifier for parsing and formatting only when the string and DateTime object are from the same OS.
I will also change from using the "G" format to a custom format.

Is InvariantCulture supposed to have the same properties regardless of the OS?

**Comment by tarekgh** [comment]
> Said difference could result in more developers being confused though since this seems to imply that en-US ShortDatePattern should always be "M/d/yyyy".

We cannot gauranetee consistency across the OS's because we don't carry the globalization data and we depend on the OS for that. also users can change the default pattern in their systems and you expect to get whatever the user used. so the assumption to always have same pattern all the time is not valid assumption.

Yes in your scenario you need to use the Invariant culture which is guarantee getting exact pattern across the OS's and OS versions. I would say you create DateTime object from your data and then use DateTime.ToString("G", CultureInfo.InvariantCulture); and then you can parse it back by DateTime.ParseExact(dateString, "G",  CultureInfo.InvariantCulture). doing that will guarantee the round tripping of the date formatting and parsing.

feel free to send more questions if you have any, I'll be happy to answer all of them. thanks for bringing the issue.

**Comment by effyteva** [comment]
Hi,
For anyone suffering from this issue, I've create a simple solution.
https://github.com/effyteva/Teva.Common.Cultures
