### ISSUE TITLE
Security.Cryptography tests are failing on portable Linux runs

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#18009]
[System.Security.Cryptography.Algorithms.Tests](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170406.01/workItem/System.Security.Cryptography.Algorithms.Tests)   (see page 2 on that link)
[System.Security.Cryptography.OpenSsl.Tests](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170406.01/workItem/System.Security.Cryptography.OpenSsl.Tests)

are failing in our portable linux-x64 build test runs on a few different linux distros in Helix.  These tests are passing for the distro-specific build runs.  We should investigate why they are failing and fix them.

I dug into one:

TestExplicitCurves(curveDef: CurveDef { Curve = System.Security.Cryptography.ECCurve, CurveType = Characteristic2, IncludePrivat...

And see it failed with:

Interop+Crypto+OpenSslCryptographicException : error:0D06407A:asn1 encoding routines:a2d_ASN1_OBJECT:first num too large

### Note
Here are the distro-specific build run logs:

[System.Security.Cryptography.Algorithms.Tests distro-specific](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170406.02/workItem/System.Security.Cryptography.Algorithms.Tests)
[System.Security.Cryptography.OpenSsl.Tests distro-specific](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170406.02/workItem/System.Security.Cryptography.OpenSsl.Tests)

/cc @janvorli @bartonjs @steveharter

**Comment by janvorli** [comment]
I have tried it locally on Ubuntu 14.40 with a debug version of System.Security.Cryptography.Native.OpenSsl.so built on CentOS 7 and I can reproduce it. 
The test System.Security.Cryptography.EcDsa.Tests.ECDsaImportExportTests.TestExplicitCurves has 16 cases, 8 with CurveType = Characteristic2 and 8 with curveType=PrimeShortWeierstrass. The Characteristic2 always fails while the PrimeShortWeierstrass always succeeds.
The failure happens in call to CryptoNative_EcKeyCreateByExplicitParameters. The `curveMethod = CurveTypeToMethod(curveType);` returns NULL for the Characteristic2 and so the CryptoNative_EcKeyCreateByExplicitParameters fails.
It is not surprising though since the HAVE_OPENSSL_EC2M is false and so the only curve types supported are PrimeShortWeierstrass and PrimeMontgomery.
The question though is why we get such a weird error for the first failure in the suite (  `error:0D06407A:asn1 encoding routines:a2d_ASN1_OBJECT:first num too large`). The following errors are valid and expected - `Error occurred during a cryptographic operation.`. It looks to me that the message is actually a bug, because in this case, there was no failure in the third party crypto code, just our function returned NULL because it didn't have any Crypto function to call for the Characteristic2.
Here is the code that calls the native function CryptoNative_EcKeyCreateByExplicitParameters that returns NULL in our case and throws an exception if the returned value is null.
```C#
            SafeEcKeyHandle key = Interop.Crypto.EcKeyCreateByExplicitParameters(
                curve.CurveType,
                null, 0,
                null, 0,
                null, 0,
                p, p.Length,
                curve.A, curve.A.Length,
                curve.B, curve.B.Length,
                curve.G.X, curve.G.X.Length,
                curve.G.Y, curve.G.Y.Length,
                curve.Order, curve.Order.Length,
                curve.Cofactor, curve.Cofactor.Length,
                curve.Seed, curve.Seed == null ? 0 : curve.Seed.Length);

            if (key == null || key.IsInvalid)
            {
                if (key != null)
                    key.Dispose();
                throw Interop.Crypto.CreateOpenSslCryptographicException();
            }
```
The error message is gathered in the CreateOpenSslCryptographicException function. And that one uses ErrGetErrorAlloc function to extract the error code. And that ends up calling ERR_get_error() from the third party crypto library.
So my conclusion is that since we just return NULL from CryptoNative_EcKeyCreateByExplicitParameters when we don't recognize the Characteristic2 as something we can work with and no Crypto code is called, the error code returned is some stale code unrelated to our failure.

**Comment by bartonjs** [comment]
Thanks, Jan.  I can understand the error being spillover (the queue is a lot noisier than Win32GetLastError).  But why are we in a different path for portable vs not?  The non-portable case is either succeeding, or the capabilities probe says that Char2 doesn't work (and in the portable case it clearly says Char2 does work).

Assuming they're using the same libcrypto, the delta has to be coming from the shim...

**Comment by janvorli** [comment]
@bartonjs the non-portable versions have the HAVE_OPENSSL_EC2M detected at build time as set and so they support the Characteristic2 curve.

**Comment by janvorli** [comment]
@bartonjs I've overlooked the `the capabilities probe says that Char2 doesn't work`. So we probably have a bug in there for the portable case.

**Comment by Jiayili1** [comment]
Failed again on build 20170407.01: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170407.01/workItem/System.Security.Cryptography.Algorithms.Tests

**Comment by janvorli** [comment]
Is there a way to find commit # for which the test was built? I believe this failed build didn't contain my fix yet.

**Comment by eerhardt** [comment]
There's a core-eng bug to allow you to do this easily:  https://github.com/dotnet/core-eng/issues/507.

The only way I know how to do it is documented internally at:

https://microsoft.sharepoint.com/teams/netfx/corefx/_layouts/OneNote.aspx?id=%2Fteams%2Fnetfx%2Fcorefx%2FDocuments%2FCoreFx%20Notes&wd=target%28Engineering%2FDev%20HOWTOs.one%7C20E388BF-8C41-4D6C-814C-63118AA79B52%2FHow%20to%20find%20the%20Commit%20for%20a%20build%7CAE35F836-F0E3-48B5-86B8-58FF419B9FCE%2F%29

and it involves needing to go to the VSTS build definition.

**Comment by bartonjs** [comment]
I don't see any failures starting with 20170407.02: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170407.02; so we can probably close this, @janvorli.
