### ISSUE TITLE
Build UAP identity package during -targetGroup:uapaot build

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#18098]
The UAPAOT build currently doesn't build the identity package due to an explicit condition:
https://github.com/dotnet/corefx/blob/001fdf5538b27259f845d7ce7cc5daa8f1d179aa/pkg/Microsoft.Private.CoreFx.UAP/Microsoft.Private.CoreFx.UAP.builds#L9

To fix this we need to do the following:
1. Remove that condition.
2. Remove `uapaot` from configurations.props.
3. Use something other than 'targetgroup' for inferring the _aotSuffix.  Perhaps _bc_TargetGroup.

**Comment by danmosemsft** [comment]
@alexperovich @joperezr is this actually already done?

**Comment by alexperovich** [comment]
This is not done yet.

**Comment by danmosemsft** [comment]
Moving out of UWP milestone since AFAIK it's not required to ship.
@alexperovich can you explain the benfit of doing this work?

**Comment by joperezr** [comment]
I guess there is no real benefit, but it is the right thing that should happen. When building a vertical of uapaot, you would expect that at the end of the build, two packages were produced: the runtime specific package with the implementation for the arch that you built, and the identity package containing the reference assemblies that imports the runtime package. This is how netcoreapp behaves, so this shouldn't be different. You are right though in the statement that this is not required to ship, since we are still building the identity package on the AllConfigurations leg.

**Comment by wtgodbe** [comment]
@ericstj do we still need this?

**Comment by joperezr** [comment]
as pointed out in my previous comment, this is not something that is needed, but it is a nice to have as it is the right behavior. I haven't checked if this has been fixed with all the changes that have gone in to the configuration system, but if it is not then it would be a nice to have.

**Comment by ViktorHofer** [comment]
Closing as we don't build uapaot anymore in master.
