### ISSUE TITLE
Microsoft.VisualBasic.ControlChars.NewLine defined to be "\r\n"

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1817]
This is correct on Windows but not on Unix.  We should consider making it a property or static readonly field that either delegates to or gets its value from Environment.NewLine.

**Comment by jasonwilliams200OK** [comment]
[This is](https://github.com/dotnet/coreclr/blob/f1c0c7d95164abbbc4dfbd5bc312ef543256b0e0/src/mscorlib/src/System/Environment.cs#L1038-L1047) how it is done in microlib:

```c#
public static String NewLine {
    get {
        Contract.Ensures(Contract.Result<String>() != null);
#if !PLATFORM_UNIX 
        return "\r\n"; 
#else
        return "\n";
#endif // !PLATFORM_UNIX 
    }
}
```

Can compiler preprocessor directives be used in `ControlChars.vb`?
Does VB share same microlib code (then I think `Environment.NewLine` can probably work [here](https://github.com/dotnet/corefx/blob/37f397ec6bb4282441dc1d2d0331381e988135bb/src/Microsoft.VisualBasic/src/Microsoft/VisualBasic/ControlChars.vb#L9))?

**Comment by stephentoub** [comment]
> Does VB share same microlib code

Yes, the same mscorlib is used as with C#.

> Can compiler preprocessor directives be used in  ControlChars.vb ?

Yes, but that would mean this library would then need to be compiled multiple times and shipped per platform, which would be overkill when we already have the functionality exposed for this from Environment. And even then with such preprocessor directives, we'd still need to make the const into a either a property or a field initialized at run time, as otherwise the call sites would bake the value in at compilation time.

Better to just make it a property and delegate to Environment for the right value.

**Comment by jasonwilliams200OK** [comment]
> Better to just make it a property and delegate to Environment for the right value.

Sounds like a killer plan! :facepunch:

**Comment by stephentoub** [comment]
The difficulty is that it's a binary breaking change. 

@VSadov?

**Comment by jasonwilliams200OK** [comment]
There is another instance for `vbNewLine`: [src/Microsoft.VisualBasic/src/Microsoft/VisualBasic/Constants.vb#L8](https://github.com/dotnet/corefx/blob/37f397ec6bb4282441dc1d2d0331381e988135bb/src/Microsoft.VisualBasic/src/Microsoft/VisualBasic/Constants.vb#L8)

**Comment by VSadov** [comment]
I think this should be left alone for historical/compat reasons. It is just a string constant at this point. We cannot know how users use it.
If someone writes multiplatform code he should just use Environment
The only reason for various vb string contants to exist is because they always existed and the code was ported over and over, from VB6 and so on...

**Comment by VSadov** [comment]
@ljw1004 @AnthonyDGreen ?

**Comment by ljw1004** [comment]
I think the premise of this issue is wrong. Let's spell out the three scenarios:

* My app reads+writes text files that are stored in the native format of the platform it's running on.
* My app reads any format text file, and writes in (not sure which format)
* My app reads and writes internet messages. Most internet protocols mandate specifically that you use \r\n.

If someone's writing an internet message and uses vbNewline as the separator, then the proposed change here would break it.

If someone's writing some code to read any format text file, and does String.Replace(vbNewLine,...).Replace(vbCr,...).Replace(vbLf,...), then the proposed change here would break it.

I think it's reasonable for Environment.NewLine to change, since that specifically calls out the fact that it's designed to return the current environment's notion of what NewLine should be. Certainly vbCr/vbLf/vbCrLf should never change. It's a difficult question as to whether vbNewLine is more like Environment.NewLine, or more like the other vb* constants. I vote that it's more like the other VB constants.

Note that the vb* constants play an important role in VB. In C# it's easy to use \r and \n. But VB lacks escape characters, so every VB developer is very familiar with using vb* constants.

I would be loathe to make a #ifdef in Microsoft.VisualBasic.dll. That would force it to have different implementations on all platforms. I can understand doing that for mscorlib, but it's a tax that I don't want VB to have to pay going forwards. You can't change vbNewLine into a wrapper around Environment.NewLine because it's currently a constant, and changing that would break it.

I notice that the mscorlib code at the top of this issue looks incorrect. It should have a third case for Mac which uses "\r".

The general guidance that folks will find on the internet is to use Environment.NewLine:
http://www.jaypm.com/2012/08/the-difference-between-vbcrlf-vbnewline-and-environment-newline/
http://stackoverflow.com/questions/8930202/vbcrlf-or-environment-newline
but there are exceptions, e.g. http://programmersheaven.com/discussion/92393/vbcrlf-and-vbnewline


CONCLUSION: I **strongly recommend** not to change this. It would be a silent breaking change in a bunch of code, and there aren't good-enough reasons to change it.

**Comment by stephentoub** [comment]
> I think the premise of this issue is wrong.

The premise of the issue stated "We should consider..."... that's what we're doing ;)

> f someone's writing some code...

And if someone's writing some code to display some text to the console, write some text to a file, etc., the current implementation will be wrong on non-Windows. The MSDN docs do say "represents a newline character for print and display functions."

> Certainly vbCr/vbLf/vbCrLf should never change

Of course.

> It's a difficult question as to whether vbNewLine is more like Environment.NewLine, or more like the other vb* constants.

Seems strange that we have both vbCrLf and vbNewLine if the latter is guaranteed to be the former; the fact that both exist makes me think the same way as one of the posters in one of the links you shared, that the latter would be platform-specific.  I realize these are all legacy.

> I would be loathe to make a #ifdef in Microsoft.VisualBasic.dll. 

Sure, there'd be no reason to do that.  As I noted in one of my responses in the thread, as a constant doing that wouldn't actually solve the problem, as it would burn the constant into the call site at compile time, rather than using the right value for the current platform at run time.

> You can't change vbNewLine into a wrapper around Environment.NewLine because it's currently a constant, and changing that would break it.

Yes, I noted that in a previous response as well.  If we're not ok with such a change (which I realized  after posting my previous reply could also be a source breaking change in addition to the binary breaking change I called out, as you could have been assigning it to another constant, which would no longer compile), then we may as well close this issue now.

> I notice that the mscorlib code at the top of this issue looks incorrect. It should have a third case for Mac which uses "\r".

To my knowledge, Mac OS used "\r" as the newline for versions OS 9 and earlier, whereas OSX (like most other Unix implementations) uses "\n".  We have no plans for supporting pre-OSX.

> The general guidance

I believe the final decision should be up to you and the rest of the VB team; if you're firmly against a change here, and Anthony is as well, then we should leave it as-is.  However, I'd suggest at least updating the MSDN documentation to make this very clear, telling any reader that they should really use Environment.NewLine, and many uses of this will be wrong on platforms where NewLine is not "\r\n".  Ideally there'd also be a comment added to the code.

**Comment by govert** [comment]
vbNewLine might have a different meaning in VBA on the Office for Mac.

Maybe vbNewLine could be marked [Obsolete] with a message indicating that either Environment.NewLine or vbCrLf should be used instead. That would at least pop up a warning when recompiling.

**Comment by AnthonyDGreen** [comment]
Hmm,

vbNewLine exists in VBA. I think that predates the cross-platform scenario but if it is in fact defined differently on Office for Mac that would be valuable information on both the original intention of the constant and the user expectation of it. If there is no evidence of it ever having exhibited platform-specific behavior then I agree that we should leave it as is.

**Comment by stephentoub** [comment]
> vbNewLine exists in VBA. I think that predates the cross-platform scenario but if it is in fact defined differently on Office for Mac that would be valuable information on both the original intention of the constant and the user expectation of it. 

I just tried with VBA in Office 2016 on both a Windows machine and an OS X machine.  vbNewLine is Chr(13) & Chr(10) on Windows and just Chr(10) on OS X, as you'd expect.

**Comment by AnthonyDGreen** [comment]
Hmm, we could change it to be a field but Obsoleting it in favor of Environment.NewLine could be the right way to go. Everything else in ControlChars is a compile-time constant and this wouldn't be which could get confusing with user expectations around things like constant folding and what's permitted in an attribute argument. We weren't very clear on the intention of this constant. Environment.NewLine is very explicit that its purpose is to use machine-specific line endings. We definitely don't want to compile this library per platform, that defeats the whole point of portable assemblies.

**Comment by VSadov** [comment]
Compiling per platform would not help because it is the run time platform that matters.

+1 for obsoleting and suggesting vbCrLf or Env.NewLine instead.

**Comment by stephentoub** [comment]
> Compiling per platform would not help because it is the run time platform that matters.

It would help in that we'd deploy/use the relevant binary on the relevant platform, as we do with most of our other assemblies that have platform-specific implementations.  But that does feel particularly onerous given that we're talking about a single constant that would need to change.  That's why I was suggesting changing it to a field or a property, where we could set it at run time from Environment.NewLine.  I understand the arguments again that, however.

> obsoleting 

I'm fine with that if that's the decided outcome.
