### ISSUE TITLE
[Linux Mint] Http client to call Soap service over https.

### ISSUE THREAD

**Issue by AndreiFuse** [dotnet/corefx#18207]
I'm trying to access existing SOAP webservice using `HttpClient`. Works fine on Windows 10, but fails in Linux Mint with `TaskCanceledException: A task was canceled.`, which masks a timeout. Is there a way to run it on Linux?

```c#
    [HttpGet("test")]
    public IActionResult Login()
    {
      HttpClientHandler clientHandler = new HttpClientHandler();
      clientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; };
      HttpClient client = new HttpClient(clientHandler);
      HttpRequestMessage request = CreateSoapWebRequest();
      HttpResponseMessage response = client.SendAsync(request).Result;
    }

    public HttpRequestMessage CreateSoapWebRequest()
    {
      string xmlString = String.Format(<my xml here>);
      HttpRequestMessage result = new HttpRequestMessage(new HttpMethod("POST"), myUrl);
      result.Content = new StringContent(xmlString, Encoding.UTF8, "text/xml");
      result.Headers.Add("SOAPAction","http://tempuri.org/IAuthorizationService/AuthorizeUser");
      return result;
    }
```

The request works fine with http and also with https when there are valid certificates.

To problem occurs when we are testing in our DEV environment with no valid https certificate available.
The request seems to time out. Just before the TaskCanceledException: A task was canceled gets thrown the ServerCertificateCustomValidationCallback gets called (takes about 2 minutes). Returning true/false doesn't seem to make a difference, I think it's too late at this point. Shouldn't this callback be called in the very beginning?

Would appreciate everything that helps.

**Comment by stephentoub** [comment]
@AndreiFuse, a few questions/comments:
- What version of .NET Core are you using?
- What version of curl are you using? i.e. what output do you see from `curl --version` at the terminal?
- Is there a reason you're blocking with `.Result` rather than using `await`?
- `HttpClient` is meant to be used multiple times and used concurrently; you don't need to / ideally shouldn't create one per request.

**Comment by AndreiFuse** [comment]
* .Net Core version `1.0.1`
* Curl `7.47.0`
* No reason, just assumed that's the same thing.
* Didn't know that, I'll refactor this part accordingly once we pass this problem.

**Comment by stephentoub** [comment]
> .Net Core version 1.0.1

Have you tried a more recent version?

> Curl 7.47.0

Can you share the full output of `curl --version`?  In particular I'm interested in seeing what SSL backend is being used.

> No reason, just assumed that's the same thing.

It's not: `.Result` will block synchronously, whereas `await` will result in the remainder of the method being hooked up as an asynchronous continuation.  This could be important as the blocking could potentially cause a deadlock, and since you're seeing a timeout, it's possible that's related.

> Linux Mint

Have you tried on another distro, like Ubuntu?  Do you have a standalone repro you could share for us to run?

**Comment by AndreiFuse** [comment]
* Correction. If I type just `dotnet`, I get version `1.1.0` for both Win and Linux environments.
* Here's the full curl version.
```
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
```
* I'm on Mint and I can't change that.

**Comment by PeterSmithRedmond** [comment]
Does switching to Await help?

**Comment by davidsh** [comment]
Does this problem still occur for you?  We recommend you try out .NET Core 2.1 Preview 2:
https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-net-core-2-1-preview-2/

If this still repros using the latest .NET Core, we can re-open this issue.  Thanks!
