### ISSUE TITLE
Desktop: System.Runtime.Serialization.Xml.Tests.XmlDictionaryReaderTests.ReadElementContentAsDateTimeTest failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18205]
Failed test: System.Runtime.Serialization.Xml.Tests.XmlDictionaryReaderTests.ReadElementContentAsDateTimeTest

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/14/testReport/System.Runtime.Serialization.Xml.Tests/XmlDictionaryReaderTests/ReadElementContentAsDateTimeTest/

MESSAGE:
Assert.Equal() Failure\r\nExpected: 2003-01-08T15:00:00.0000000\r\nActual: 2003-01-08T07:00:00.0000000-08:00
+++++++++++++++++++

STACK TRACE:
at System.Runtime.Serialization.Xml.Tests.XmlDictionaryReaderTests.ReadElementContentAsDateTimeTest() in D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Serialization.Xml\tests\XmlDictionaryReaderTests.cs:line 101

**Comment by shmao** [comment]
The bug is with [`XmlDictionaryReader.ReadElementContentAsDateTime()`](https://github.com/dotnet/corefx/blob/6c53c9572258b5b208e9a74efc170494de4de822/src/System.Private.DataContractSerialization/src/System/Xml/XmlDictionaryReader.cs#L859). The method should use `ReadContentAsDateTime` instead of `ReadContentAsDateTimeOffset` to read string into DateTime. 

The test was verifying the behavior on NetCore, which was wrong. Since we started running the test on Desktop recently, the test started failing. 

We need to fix both the code and the test.
