### ISSUE TITLE
Suggestion: NamedPipe classes should support interop with other languages on Unix

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/corefx#18257]
Currently, as far as I can tell at least, there is no good way to interop with a node.js/C++/etc with the .NET Core pipe code on non-Windows platforms. The problem is that on Unix you would like to get the full path to the underlying domain socket and somehow be able to open an arbitrary domain socket. But .NET Core doesn't have any APIs for this.

In node.js, for example, `net.createServer` ([examples](http://stackoverflow.com/questions/11750041/how-to-create-a-named-pipe-in-node-js)) provides one abstraction that works with named pipes and Unix domain sockets. It does require a few lines of platform-specific code to work out the server name correctly. But once that is done you have code that is nice and unified and can interop with any other framework.

Suggestions:
1. Named pipe server should have a method to get the underlying full pipe name
2. Named pipe client and server should have overloads that allow specifying the full pipe name

**Comment by vjrantal** [comment]
@gregg-miskelly I'd agree with the suggestions you posted and would prefer number 2. This is because you might have a node.js server using a pipe file in a code that is not under your control and from c# need to point to exactly that file.

If you can control both ends, as a bit silly workaround, you can have something like this in node.js:

```
var PIPE_NAME = "CoreFxPipe_testpipe";
var PIPE_PATH = process.env.TMPDIR + PIPE_NAME;
```

And like this in c#:

```
NamedPipeClientStream pipeClient = new NamedPipeClientStream("testpipe");
```

Due to [this line](https://github.com/dotnet/corefx/blob/9acd18446df25f246510450abf3feac653da2faa/src/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs#L28) above approach should give a match for the pipe file.

**Comment by pjanotti** [comment]
On 2.1 it is possible to specify an absolute path see [here](https://github.com/dotnet/corefx/blob/dd8449ded9dda04f50d8394341e2b9a59bee2b0e/src/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs#L49). I think that covers a good chunk of the uses, one could still want suggestion 1 but instead they can specify an absolute path. 

Regarding the name schema used in the workaround by @vjrantal I don't see CoreFx changing that since it breaks compatibility between different versions of the runtime.

Closing, let's know if something is missing here.
