### ISSUE TITLE
System.Text.Encodings.Web package name - why plural?

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/corefx#1827]
I just noticed a naming inconsistency with the new System.Text.*Encodings*.Web package: it doesn't match the other package names like System.Text.*Encoding*.CodePages or System.Text.*Encoding*.Extensions. Is this deliberate?

/cc @KrzysztofCwalina

**Comment by KrzysztofCwalina** [comment]
Yeah, this is unfortunate, but deliberate. The problem is that we cannot have a namespace (or root)System.Text.Encoding because it's a name of a type. And so, I made the root namespace plural (System.Text.Encodings) and then wanted to have consistency between namespace and assembly name. The other "encoding" dlls don't have this problem because their APIs are directly in the System.Text namespace.

**Comment by akoeplinger** [comment]
Ok, I suspected as much, thanks for confirming :)
