### ISSUE TITLE
Area-Serialization Sprint 117

### ISSUE THREAD

**Issue by zhenlan** [dotnet/corefx#18354]
The issue is for tracking issues to be done in sprint 117 (due by 5/5/2017)

**Comment by olivier-spinelli** [comment]
The [Serializable] is back (I don't need it since I think it is as useless as a generic in-depth Clone method) but fine. Howerver, I have one major design concern. Current design forces us to store transient serialization data  in the object itself. It is awful by design and, IMO, defeats the "simple-safe-easy-to-use-principle" of the API: 
- It is not obvious that storing this transient sate should be the way to go (even for beginners, it hurts).
- Failing to set this state to null in OnDeserialization (or OnDeserialized "event') will lead to memory leaks. This will happen for sure.
- Understanding OnDeserialized event vs. IDeserializationCallback.OnDeserialization is... fun but not as much as the SafeSerializationManager...

Since I understand the ".Net Framework API surface compatibility" goal, I think we (the .Net community at large) are missing here a great opportunity to fix what is clearly a bad design option.

Is there any issue with the following approach?
1 - Offer a way to the deserialization ctor to store a transient state object.
  - Thanks to a new SetDeserialiazationState method on the StreamingContext?
  - Ouch! it's a struct that cannot be changed/extended... let's handle another deserialization ctor with an enhanced StreamingContext or one new parameter. 
2 - Give back this object to the OnDeserialization method.
  - Thanks to a new IDeserializationStateCallback may be?
  - And, may be also, the OnDeserialized event could allow a new "object state" in its signature (since this one is more "duck typed".

The ObjectManager should be able to manage this transient state correctly.
Am I missing something here? 
I think so... SafeSerialization introduce other complexities. And the attribute/event approach is better than the potentially virtual OnDeserialization method.

Again, am I missing something here? Are there hidden/secret plans to handle this more correctly?
I guess I'm not the only one that feel a little bit sad to see those stuff coming back into the clean .Net Core code base...

**Comment by zhenlan** [comment]
Hi @olivier-spinelli thanks for the feedback. This issue is really only meant to track work items we will be doing in Sprint 117 and it will be closed when its associated work items are finished. I don't want your feedback/question gets lost as part of it. Do you mind to open a new issue for it? I can open a new issue for you too but wondering you may like to open the issue in your name. Please let me know.

BTW, do you have a particular serializer, for example binary serializer, in mind in the context of this discussion? If so, it may be helpful to call it out.
