### ISSUE TITLE
Two FtpWebRequest tests taking long time to fail

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#18424]
Two FtpWebRequests tests are each taking upwards of 20 seconds, but all they're doing is trying to connect to targets that don't exist.  I'm not familiar enough with the FtpWebRequest APIs to know what can be done about this, but these two tests are the long poles in the suite.
`GetResponse_ServerNameNotInDns_ThrowsWebException`
`GetResponse_ConnectFailure_ThrowsWebException`

**Comment by robosek** [comment]
I’ve investigated this issue and I’ve discovered that test **GetResponse_ConnectFailure_ThrowsWebException** is the slowest one. It’s because this test tries to call some address (ftp://192.0.2.1) which actually doesn’t exist and searching this address takes too long time. I’ve switched this address to local address (ftp://127.0.0.1) and basically it’s much better right now. The second test **GetResponse_ServerNameNotInDns_ThrowsWebException** in my opinion works good (There is about half second difference of time when I run all tests and tests without this one).  Running all tests on my local machine takes now about 25 seconds and before change it took about 45 seconds. Should I make pull request with that fix?

**Comment by karelz** [comment]
@robosek thanks for your contribution! I sent you collaborator invite, so that we can assign the issue to you (GH limitation). Please let me know when you accept. Thanks and welcome on board!

**Comment by robosek** [comment]
Thanks for that @karelz . I accepted the invitation.

**Comment by stephentoub** [comment]
Determined in https://github.com/dotnet/corefx/pull/19818 that the current tests are ok.
