### ISSUE TITLE
Desktop: System.Security.Cryptography.Hashing.Tests.HmacAlgorithmTest.SetNullAlgorithmName failed with "System.ArgumentNullException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18479]
Failed test: System.Security.Cryptography.Hashing.Tests.HmacAlgorithmTest.SetNullAlgorithmName

Configuration: outerloop_netfx_windows_nt_debug

Message:
~~~
System.ArgumentNullException : Value cannot be null.
     Parameter name: name
~~~

Stack Trace:
~~~
at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args) 
at System.Security.Cryptography.HMAC.set_HashName(String value) 
at System.Security.Cryptography.Hashing.Tests.HmacAlgorithmTest.SetNullAlgorithmName() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Primitives\tests\HmacAlgorithmTest.cs:line 17
~~~

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/21/testReport/System.Security.Cryptography.Hashing.Tests/HmacAlgorithmTest/SetNullAlgorithmName/

**Comment by danmosemsft** [comment]
@jkotas @stephentoub @terrajobst of course we usually want to fix cases where .NET Core rejects code that full framework would accept. How much of a concern is the reverse - someone writes a library that works on .NET Core (or, soon, UWP) but later turns out to break on Framework? This one is an example albeit not a great one.

**Comment by jkotas** [comment]
There are many bug fixes in .NET Core that are not in .NET Framework yet. It is by design that you can write a library that works on .NET Core and it does not break on .NET Framework - if it takes dependency on one of the bug fixes.

.NET Standard does not save you from testing your library on different runtimes and platforms to verify that it actually works, and add workarounds for runtime-specific bugs as necessary.

**Comment by danmosemsft** [comment]
OK that's what I thought.

@bartonjs this seems expected since we don't call Cryptoconfig in Core. Doesn't seem valuable to mimic the exception here. 
https://github.com/dotnet/corefx/blob/ec2a6190efa743ab600317f44d757433e44e859b/src/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/HMAC.cs#L44

**Comment by bartonjs** [comment]
Validating null before the existing check seems reasonable to me.  The intention of the version in corefx is "throw if you're making me do soemthing I can't".  Since null is always illegal, ArgumentNullException seems good for both.  So, corefx bug.

**Comment by bartonjs** [comment]
Both bug and testbug, because the test is testing the wrong behavior, and the product is supplying it.

**Comment by krwq** [comment]
@bartonjs - I do not agree on that for properties - setting a property is not an action - if I'd serialize this object as is and deserialize it I'd get exception currently and would need to add special logic to workaround this. Setting a property should be transparent IMO

**Comment by krwq** [comment]
Fixed with https://github.com/dotnet/corefx/pull/18575
