### ISSUE TITLE
System.Security.Cryptography.X509Certificates.Tests.ChainTests.BuildChain_MicrosoftDotCom_WithRootCertInUserAndSystemRootCertStores failed with "System.Security.Cryptography.CryptographicException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18603]
Failed test: System.Security.Cryptography.X509Certificates.Tests.ChainTests.BuildChain_MicrosoftDotCom_WithRootCertInUserAndSystemRootCertStores

Configuration: outerloop_netcoreapp_fedora24_debug

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_fedora24_debug/26/testReport/System.Security.Cryptography.X509Certificates.Tests/ChainTests/BuildChain_MicrosoftDotCom_WithRootCertInUserAndSystemRootCertStores/

MESSAGE:
~~~
System.Security.Cryptography.CryptographicException : Invalid file permissions. 
The file '/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug/tempHome/.dotnet/corefx/cryptography/x509stores/root/4EB6D578499B1CCF5F581EAD56BE3D9B6744A5E5.pfx' must readable and writable by the current owner and by no one else, and the permissions could not be changed to meet that criteria.
~~~
STACK TRACE:
~~~
at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.EnsureFilePermissions(FileStream stream, UInt32 userId) at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal) 
at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate) 
at System.Security.Cryptography.X509Certificates.Tests.ChainTests.BuildChain_MicrosoftDotCom_WithRootCertInUserAndSystemRootCertStores()
~~~

**Comment by steveharter** [comment]
Uncovered due to #14166; previously assert and seg fault. Will disable test via IsReliableInCI

**Comment by bartonjs** [comment]
> previously assert and seg fault.

Do we have an existing issue for that?  Since all we did here was change assert to throw we shouldn't have changed the pass/fail state of any debug tests.

**Comment by steveharter** [comment]
No there wasn't an issue logged, although Fedora 24 has been failing on X509 tests with seg fault for last few days presumingly due to the Debug.Assert. I did not generate a dump however.

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_fedora24_debug/25/consoleFull
```
02:28:38   Discovering: System.Security.Cryptography.X509Certificates.Tests
02:28:38   command exited with ExitCode: 134
02:28:38   command failed, trying to collect dumps
02:28:38   /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug/bin/Unix.AnyCPU.Debug/System.Security.Cryptography.X509Certificates.Tests/netcoreapp/RunTests.sh: line 89: 46295 Aborted                 (core dumped) $RUNTIME_PATH/dotnet xunit.console.netcore.exe System.Security.Cryptography.X509Certificates.Tests.dll -xml testResults.xml -notrait category=nonnetcoreapptests -notrait category=IgnoreForCI -notrait category=failing -notrait category=nonlinuxtests
02:28:38   corefile:
02:28:38   no coredump file was found
02:28:38   /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug/src/System.Security.Cryptography.X509Certificates/tests
02:28:38   Finished running tests. End time=00:28:38. Return value was 134
02:28:38 /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug/Tools/tests.targets(326,5): warning MSB3073: The command "/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug/bin/Unix.AnyCPU.Debug/System.Security.Cryptography.X509Certificates.Tests/netcoreapp/RunTests.sh /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug/bin/testhost/netcoreapp-Linux-Debug-x64/" exited with code 134. [/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug/src/System.Security.Cryptography.X509Certificates/tests/System.Security.Cryptography.X509Certificates.Tests.csproj]
02:28:38 
/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug/Tools/tests.targets(334,5): error : One or more tests failed while running tests from 'System.Security.Cryptography.X509Certificates.Tests' please check /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug/bin/Unix.AnyCPU.Debug/System.Security.Cryptography.X509Certificates.Tests/netcoreapp/testResults.xml for details! [/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug/src/System.Security.Cryptography.X509Certificates/tests/System.Security.Cryptography.X509Certificates.Tests.csproj]
```

**Comment by bartonjs** [comment]
> No previous issue logged, although Fedora 24 has been failing on X509 tests with seg fault for last few days

This state makes me sad.  Oh, well.

**Comment by karelz** [comment]
Just discussed with @bartonjs and @danmosemsft -- we have 3 problems here:
1. Our CoreFX CI & Helix runs don't report Debug.Asserts as failures - we are running blind. We have to fix it - @danmosemsft to follow up with vendors
2. For every customer: Debug.Assert should print to console "This is why I exited your process" - it's not happening today - @bartonjs is poking at it in https://github.com/dotnet/coreclr/pull/10652
3. xunit should report Debug.Asserts as test failures, it should not kill the process (i.e. same as an exception from test) - it may need to register custom Debug.Assert handler (whatever that is)
4. CoreFX test runs in CI/Helix need the behavior in [3] ASAP - otherwise each Debug.Assert in a test will prevent all other tests to run - @danmosemsft can you please follow up?
5. CoreFX CI/Helix runs - we should make sure that we don't have other 'silent' failures -- maybe check which logs we don't look at at all? - @danmosemsft is that reasonable?

cc @jkotas

**Comment by jkotas** [comment]
> Our CoreFX CI & Helix runs don't report Debug.Asserts as failures 

Debug.Assert should be killing the process today via FailFast. Does this mean that CoreFX CI & Helix are not reporting test that just die silently for whatever reason?

> Debug.Assert should print to console "This is why I exited your process

More specifically - FailFast should print to console the message.

> xunit should report Debug.Asserts as test failures, it should not kill the process (i.e. same as an exception from test) - it may need to register custom Debug.Assert handler

This is a new feature. Also, it is not clear to me whether it is a good idea. It tends to lead to really long and confusing recursive logs when something really goes wrong.

**Comment by bartonjs** [comment]
@jkotas The problem with the FailFast approach for the unit tests is that it doesn't tell you where the problem isn't.  The X509Certificates library has ~700 test cases in it.  One test tripped an assert, so we lost reporting on 699 other cases... and we also don't know what test to have been looking at (for a single failure; when it's the whole library then there's probably just a contaminated state somewhere).

The example I have of in the past intercepting an assert to prevent a Watson dialog used 

```C#
Trace.Listeners.Clear();
Trace.Listeners.Add(new FailingTraceListener());
```

So maybe it'd be hard for xunit to be able to pin it to a particular test.

If we figure out what part of our process went wrong with us not noticing that we had no test results from a library for 4 days, and we get FailFast to print the termination reason, that'll eliminate most of my concerns... since the callstack will tell you (for non-async tests, at least) what test you were in when the assert tripped.

**Comment by steveharter** [comment]
I think the first baby step is to add a call stack to the reporting, either from a dump or some other mechanism. Today we don't even know what Assert was tripped (at least on Linux)

**Comment by stephentoub** [comment]
> Today we don't even know what Assert was tripped (at least on Linux)

A few days ago I updated the dumpling script to print out the exception as part of its trace to stdout. Not a replacement for FailFast itself printing out, but it should be a stopgap, add it'll include the message, stack, etc. We just need to ensure we using the latest script. cc: @mellinoe

**Comment by danmosemsft** [comment]
I tried Environment.FailFast(msg, ex) on Desktop and it dumps the message and callstack to console. On Core, it doesn't do that. It sounds like we're all in agreement it should do that? If so I'll open an issue.

I was going to change Debug.cs to write to stderr first (on both Unix and Windows) but it seems that the above would make that unnecessary and also catch other FailFast paths.

Separately I'll follow up about not overlooking when the test dies.

Does that cover everything?

**Comment by danmosemsft** [comment]
>  Also, it is not clear to me whether it is a good idea. It tends to lead to really long and confusing recursive logs when something really goes wrong.

The advantages are (1) other tests in the fixture continue to run. Which is probably quite reasonable since the Debug.Assert generally does not mean the process is in a bad state. Otherwise we are blind to those failures (2) existing infrastructure that parses the XUnit log will show all the results nicely. Without the XUnit log, you just get a console dump.

I don't think the above is vital to fix now assuming there aren't many Debug.Assert cases firing right now.

**Comment by danmosemsft** [comment]
I misspoke. On Desktop, Environment.FailFast does not write to the console either. Still, we can fix Core.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/coreclr/issues/11114
