### ISSUE TITLE
HttpWebRequest.AllowReadStreamBuffering can't be set to true

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/corefx#18668]
Found during UWP apps testing. In the version 4.0.10.0 the System.Net.Requests.dll did implement the HttpWebRequest.AllowReadStreamBuffering and allowed it to be set to true (and it actually did make a difference in behavior).
In the latest code, the property always returns false, and can't be set to true. It throws InvalidOperationException if something tries to set it to true.
This obviously breaks backward compatibility.

**Comment by davidsh** [comment]
This is a known issue.

**Comment by davidsh** [comment]
Ok.  My error.  Your issue has nothing to do with #11873.  That was about `AllowWriteStreamBuffering`.

This issue is about `AllowReadStreamBuffering`.  That means it is about the buffering of the HTTP response body content.

The reason we don't allow the property to be changed on .NET Core is due to the way we implement HttpWebRequest over HttpClient.  It is possible we could, though, allow the property to be set and toggle the way we call HttpClient so that it will buffer the response body.

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by davidsh** [comment]
Setting to 2.0 milestone as is it app-compat difference.

cc: @karelz

**Comment by karelz** [comment]
@vitek-karas were there any real-world UWP apps broken by this? Or how did you discover the breaking change?

**Comment by vitek-karas** [comment]
Yes, there's a real-world app broken by this.

**Comment by karelz** [comment]
Impact: 1 app in Top2000 app startup compat run (internal bug number 410815).

There's no way to tell how many apps/libraries would run into it during app execution ...

**Comment by davidsh** [comment]
So, I looked into this.  And it can be made to work on .NET Core very easily especially because HttpWebRequest is implemented on top of HttpClient in .NET Core.

However, looking at the original .NET Framework code for HttpWebRequest.AllowReadStreamBuffering, I see this:

```c#
        // For portability only
        public virtual bool AllowReadStreamBuffering {
            get {
                return false;
            }
            set {
                if (value) {
                    throw new InvalidOperationException(SR.GetString(SR.NotSupported));
                }
            }
        }
```

I have a vague memory of why this code is like this.  But for .NET Framework, it appears that `AllowReadStreamBuffering` isn't allowed to be set to `true` for Desktop. I think this property was made virtual a few releases ago because the Windows Phone or other portable version of this allowed this buffering.

I will do more research on this.  @vitek-karas what "app" is broken by this?  If this never worked in .NET Framework, was this app perhaps a Windows Phone or Windows 8.x Store app, etc. ?

cc: @ericstj @terrajobst do you remember this property?

**Comment by davidsh** [comment]
So, it looks like in .NET Core 1.0 and 1.1, we allowed this property to be set and used.

In a recent PR #18163, I made a a bunch of .NET Framework vs. .NET Core app-compat fixes and made this property throw that exception again (so that it was now the same as .NET Framework).

 I can undo that (and thus fix this issue).  We will have to modify our tests so that when we test this property on Desktop, it will have a different (and original) behavior of still throwing the exception.

So, summary, in this case, it looks like our .NET Core version is "better" than .NET Framework because it allows for convenient automatic buffering of the response body. This was not normally achievable on Desktop because of the architecture there.

**Comment by vitek-karas** [comment]
As far as I can tell the app is not completely broken, but part of it won't work for sure (seems to be some kind of telemetry web request it's sending while it fails like this). What I do know for sure is, that on our previous release of .NET Native this failure didn't occur. So from the point of the view of the app, we broke it.
It's a standard UWP app (so targeting Win10). My understanding is that UWP apps never run on desktop .NET. They run on either CoreCLR (while debugging) or .NET Native (release builds and in the store).
