### ISSUE TITLE
EnvelopedCms.Encrypt on Desktop rejects zero length content (unlike Core)

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18724]
Failed test: System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.EdgeCasesTests.ZeroLengthContent_RoundTrip 

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/26/testReport/System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests/EdgeCasesTests/ZeroLengthContent_RoundTrip/

MESSAGE:
~~~
System.InvalidOperationException : The CMS message is not encrypted.
~~~
STACK TRACE:
~~~
at System.Security.Cryptography.Pkcs.EnvelopedCms.Encode() 
at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.EdgeCasesTests.ZeroLengthContent_RoundTrip() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Pkcs\tests\EnvelopedCms\EdgeCasesTests.cs:line 110
~~~

**Comment by krwq** [comment]
@bartonjs also not reproing for me - is this also in-place non-quirked change?

**Comment by bartonjs** [comment]
Repros just fine for me.

The problem is that the catch (https://github.com/dotnet/corefx/blob/2c5c14b9176b4bc17dfbca8404961ba5f813869a/src/System.Security.Cryptography.Pkcs/tests/EnvelopedCms/EdgeCasesTests.cs#L108) eats the desktop exception and moves on to call Encode(), but since Encrypt() didn't succeed it's in an invalid state.

The catch body should return.

**Comment by danmosemsft** [comment]
Why doesn't this repro for core?
