### ISSUE TITLE
Add Directory.CreateDirectory(string, out bool)

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#18749]
When you want to make sure that a directory exists on a certain path you call `Directory.CreateDirectory(string)` which is great because it also handles creation if it's non-existent. That member call returns a `DirectoryInfo` object but doesn't tell you, whether it already existed or was just created. In scenarios where you want to execute code only if the directory was just created, you have to add extra code.

### Proposal

```C#
namespace System.IO
{
    public static partial class Directory
    {
        // Existing API:
        // public DirectoryInfo CreateDirectory(string path);

        public DirectoryInfo CreateDirectory(string path, out bool created);
    }
}
```

### Usage

```C#
System.IO.Directory.CreateDirectory("<path>", out bool created);
if (created) {
 // Some code which should only be executed if the directory was created
}
```

I came up with this proposal while working in System.IO.IsolatedStorage for https://github.com/dotnet/corefx/pull/18647#discussion_r112710798

### Alternatives
Calling `Directory.Exists(string)` first:
``` c#
bool alreadyExisted = Directory.Exists(path);
DirectoryInfo info = Directory.CreateDirectory(path);
if (!alreadyExisted) {
   // Some code which should only be executed if the directory was created
}
```
This is problematic as between `Directory.Exists(string)` and `Directory.CreateDirectory(string)` a race condition could happen like the state of the directory has changed (e.g. deleted).

/cc @terrajobst @JeremyKuhne

**Comment by JeremyKuhne** [comment]
One thing to remember is that the directory can be created/removed at *any* time. You could, for example, call `Directory.Exists()` and have the state already be changed by the time you get the result. Given that, really all you're saying is that you successfully called [`CreateDirectory()`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363855(v=vs.85).aspx)

As such I'm not really sure this is more valuable than calling `Directory.Exists()` or:

``` c#
DirectoryInfo info = new DirectoryInfo(path);
if (!info.Exists)
{
    info.Create();
    // other stuff
}
```

**Comment by carlossanlop** [comment]
If the method fails to create the directory, should we expect it to throw?

An alternative would be to use a Try* method:

```cs
public bool TryCreateDirectory(string path, out DirectoryInfo directoryInfo);
```

I suspect a reason not to use this is because "Try*" methods usually return `true` if the action was successful, `false` otherwise. But that's why we would make sure to document the slightly different-than-usual behavior.

If we used `TryCreateDirectory`, then we could determine created vs existing vs error like this:

- Returns `true` + `directoryInfo != null` = **directory was created**
- Returns `false` + `directoryInfo != null` = **directory already existed**
- Returns `false` + `directoryInfo == null` = **error**

**Comment by JeremyKuhne** [comment]
Triage: closing as the workaround in https://github.com/dotnet/corefx/issues/18749#issuecomment-296818568 should be sufficient.
