### ISSUE TITLE
API Proposal: Span<T> - find if one span contains another; perhaps IsSliceOf

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#18750]
From https://github.com/dotnet/corefxlab/issues/827 by @mgravell

A scenario I find myself needing is to see whether one span is a sub-span of another. This test is semantically valid for  both array and pointer spans, and is a related operation to `Slice`

Suggested API:

```
Span<T>
    bool IsSliceOf(Span<T> span);
    bool IsSliceOf(Span<T> span, out int offset);
```

where it is:
- `true` if both spans are array-based, for the exact same array, where the inner offet >= outer offset, and inner offset+count <= outer offset+count
- `true` if both spans are pointer-based, and inner ptr >= outer ptr and inner ptr+count <= outer ptr+count
- `false`  otherwise

or could be unified to:

```
    int GetSliceIndex(Span<T> span)
```

(returns -1 if not a slice; kinda ugly)

Would be happy to contribute towards the code, but wanted to discuss API first.

https://github.com/dotnet/corefxlab/issues/827#issuecomment-296100325:
> The specific example was trying to find the parent block that owns a range (one of several known blocks) so we can do a slice and dice - however, it occurs that the moment I say "one of several" it is clear that we aren't talking just about stack-based spans, so all of this could work just as well against Buffer-T if that would be preferable. The exact scenario was: https://github.com/davidfowl/Channels/pull/86/files#diff-2265f88526c85122b370d0d37969d072R620 (search IsSliceOf).

Related to: https://github.com/dotnet/corefx/issues/17793

Previous PR: https://github.com/dotnet/corefxlab/pull/830

**Comment by shiftylogic** [comment]
This is almost a direct duplicate of #17793. If we added an Overlaps extension, this would be trivial to implement, but not strictly necessary.

**Comment by nietras** [comment]
@ahsonkhan one might consider reversing this and rename so it would be something like:
```csharp
public static class SpanExtensions
{
    bool Contains(this ReadOnlySpan<T> parent, ReadOnlySpan<T> child);
    bool Contains(this ReadOnlySpan<T> parent, ReadOnlySpan<T> child, out int offset);
}
```
`Contains` might be ambiguous as some might think this just checks if it contains the **values** in question and not the **slice** or memory region. So alternative names could be `ContainsSlice` fx I think these should be extension methods.

@shiftylogic yes this does relate to overlap and I think these need to be considered as a whole, but we probably need dedicated methods for each since there are different optimizations paths for each.

@ahsonkhan we might consider consolidating this and overlaps proposal to a single proposal regarding slice overlap detection.

**Comment by mgravell** [comment]
You need to consider what "index" means, though - if it is the element
index (which would be the most natural), it is possible for 2 spans to
overlap / contain / etc and yet not have any "index" that makes sense -
specifically, if the two spans aren't *aligned* in whole multiples of
sizeof(T). Not a blocker, but definitely something to keep in mind.

On 24 Apr 2017 10:57 a.m., "nietras" <notifications@github.com> wrote:

@ahsonkhan <https://github.com/ahsonkhan> one might consider reversing this
and rename so it would be something like:

public static class SpanExtensions
{
    bool Contains(this ReadOnlySpan<T> parent, ReadOnlySpan<T> child);
    bool Contains(this ReadOnlySpan<T> parent, ReadOnlySpan<T> child,
out int offset);
}

Contains might be ambiguous as some might think this just checks if it
contains the *values* in question and not the *slice* or memory region. So
alternative names could be ContainsSlice fx I think these should be
extension methods.

@shiftylogic <https://github.com/shiftylogic> yes this does relate to
overlap and I think these need to be considered as a whole, but we probably
need dedicated methods for each since there are different optimizations
paths for each.

@ahsonkhan <https://github.com/ahsonkhan> we might consider consolidating
this and overlaps proposal to a single proposal regarding slice overlap
detection.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dotnet/corefx/issues/18750#issuecomment-296601237>, or mute
the thread

**Comment by nietras** [comment]
> need to consider what "index" means, though - if it is the element
index (which would be the most natural), it is possible for 2 spans to
overlap / contain / etc and yet not have any "index" that makes sense -
specifically, if the two spans aren't *aligned* in whole multiples of
sizeof(T)

@mgravell yes of course, but in my view (also see https://github.com/dotnet/corefxlab/pull/830#issuecomment-296952602) that would be an "invalid state", since having a `Span<double>` that does not have correct alignment is really bad. It is in my view comparable to in:
```c
void Foo(double* p, int length)
```
assuming that you have to check that `p` is in fact 8-byte aligned since the pointer might come from a source where this would be the case. We do not do that, since that is a completely invalid program state. So I would never just return `false` for that case, I would just ignore it since it is an invalid program state. But if we want to check it, I would throw an exception instead, since this should never happen.

What should the program do if this returns false due to alignment issue but the span is actually contained within parent? How can that go wrong? Will this lead to a memory leak? Etc.

**Comment by mgravell** [comment]
@nietras  the reality, however, is that they *are* both legal slices via NonPortableCast. Which *yes* only works correctly on platforms that support unaligned access, but: it *is* ultimately possible. If the issue is "misaligned slices are bad on platforms that don't support misaligned slices" - then sure, I agree with you 100%, and NonPortableCast should throw. But: that *is* a thing, and *is* supported on platforms that allow misaligned access. As such, I don't see that it is legal to throw in this scenario. Rather: the answers to the questions (of overlapped spans with different alignment) are:

- does it overlap: yes
- is it a slice-of: no (i.e. no `var y = x.Slice(...)` would produce `y` from `x`)

there are various ways we could expose this, but: I maintain that it *is* a scenario that exists. I don't agree that it is a "completely invalid program state" - and if it is: that's the job of NonPortableCast to throw. And AFAIK: it doesn't.

**Comment by ahsonkhan** [comment]
Closing this in favor of https://github.com/dotnet/corefx/issues/24103

Let's finalize the proposed API there and push it to review :)
