### ISSUE TITLE
UWP ILC runs should run in appcontainer

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#18760]
We get some coverage from UWP CoreCLR runs but some cases have emerged where API in the ILC context needs an app identity. (Plus, it's more realistic anyway)

@AlexGhiondea can you remind me what is required to do this? You mentioned it wasn't too bad.

@DnlHarvey

**Comment by yizhang82** [comment]
Please don't run them in AppX unless we have to. Let's only run the tests that require AppX (resource, managed WinRT, assembly binding, etc) inside AppX. Running inside AppX has significant cost:
* building AppX package takes time and deployment takes longer
* AppX packages are more difficult to debug
* Launching AppX is not quite reliable
* Communicating logs/error code requires additional plumbing and is often unreliable (has race condition that are difficult to track)
* Executables in AppX are not directly runnable from command line (you need to remove the AppConatiner bit)
* You need to do additional work to make the tests AppX / AppContainer friendly
* I'm not quite sure if you can activate multiple AppX in parallel without issue

**Comment by AlexGhiondea** [comment]
@danmosemsft what I meant to say was that we could figure out what needs to happen (since it would be the same thing 'release' builds in VS do). 

That being said, I thought I mentioned that the AppX coverage we get from UAP runs (which runs all the tests as AppX) should be enough coverage and the rest of the tests could run using TestILC.

> API in the ILC context needs an app identity

What does that mean -- that the APIs only work from an AppX ?

**Comment by danmosemsft** [comment]
@DnlHarvey should answer that.

**Comment by DnlHarvey** [comment]
Yes we have tests and APIs that only work from an app container. for instance anything that calls into ApplicationData.Current won't succeed.

**Comment by danmosemsft** [comment]
@ViktorHofer

**Comment by danmosemsft** [comment]
@tijoytom @joshfree I'm not seeing this happening before ZBB given the lack of infrastructure commitment and consensus on whether we should do it. We clearly should do at least some targeted testing, which may not be automated. LMK if you have concerns.

**Comment by tijoytom** [comment]
@joshfree @danmosemsft I am not too worried about testing in app-container , we have app-compact runs . Once the CoreFX automatic ingestion to DotNet Native comes oneline , we can enable Top 50 app run as part of validation and it should cover the app-container part.

**Comment by danmosemsft** [comment]
Let's leave this one unassigned as it's not planned. I'll move to Future.

**Comment by DavidGoll** [comment]
@CIPop, can we get by with the Top 50 app validation mentioned above for the time-being?

**Comment by CIPop** [comment]
@DavidGoll none of the Top 50 apps would ever hit these scenarios since they are in new APIs added in netstandard 2.0 for the UWP profile.

The tests I found to behave differently are in NegotiateStream and Ping. Right now the Nego tests in UAPAOT are disabled against this issue to eliminate CI noise. Ping is currently investigated but I believe NetNative testing will end up getting blocked by this same issue. /cc @Diego-Perez-Botero

**Comment by DavidGoll** [comment]
@joshfree @danmosemsft @tijoytom We need to reconsider the plan for supporting this in UWP6.0 (as an opt-in).

**Comment by joshfree** [comment]
@MattGal would it be feasible to cheaply add an opt-in option for some set of tests?

**Comment by MattGal** [comment]
@joshfree I think this is the sort of thing where if we figure out how to turn it on, it costs the same amount to do so for 1 test versus all of them.

If we can figure out how to do this once manually with a CoreFX test, it should be very similar to the UAP F5 scenario tests were to automate.  I don't know how this would work right off though, since normal ILC tests are a .NET-Native-compiled version of a console executable, which is very, very different from the kind of executable that runs inside an AppX (i.e. with WinRT specific startup boilerplate code, etc).

**Comment by yizhang82** [comment]
@MattGal I don't think this is unique to ILC tests. At the end of the day very few of our tests are real apps (have a main XAML window and loop, etc) so it needs a application wrapper thing to wrap the unit-style test code into something resembling an app. I don't see why ILC compiled tests needs any more special treatment (other than getting necessary dependencies into the package).

**Comment by MattGal** [comment]
@yizhang82  that's great, then we just have to do the "figure out how to do this once manually" part with one of the console apps, then convince ourselves that it actually ran in the container, and I'll help to drive getting this in official runs.

**Comment by yizhang82** [comment]
@MattGal @danmosemsft I thought CoreFX tests running on CoreCLR are already running on AppContainer/AppX. If so, we should be able to repurpose that infra.

**Comment by MattGal** [comment]
Yes, that's what I'm referring to.  If anyone can manually hack together that specific AppX to instead launch the ILC console app we use in the other tests, automating it will be not much more work.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by wtgodbe** [comment]
Closing this as dead, please re-open if it's something that we still want
