### ISSUE TITLE
TypeBuilder.CreateTypeInfo() throws COMException instead of a more descriptive managed exception

### ISSUE THREAD

**Issue by mattnischan** [dotnet/corefx#18790]
With the following code:

```csharp
var assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("RefField"), AssemblyBuilderAccess.Run);
var moduleBuilder = assemblyBuilder.DefineDynamicModule("RefFieldModule.dll");

var typeBuilder = moduleBuilder.DefineType("RefFieldClass");
typeBuilder.DefineField("RefInt", typeof(int).MakeByRefType(), FieldAttributes.Public);

var typeInfo = typeBuilder.CreateTypeInfo();
```

The last line correctly throws, in that the runtime doesn't support a ByRef field. However, it throws a `System.Runtime.InteropServices.COMException`. As far as I can see, there aren't any try/catch blocks around the QCalls into the CLR, so this exception is actually bubbling up through the invoke.

Seems like we should be returning some kind of better named and/or more descriptive managed exception in these cases. `COMException` is pretty unusual to see coming out of a framework API.

**Comment by karelz** [comment]
What is the behavior on .NET Framework?

**Comment by mattnischan** [comment]
Just tried it out, looks to be the same on Framework.

**Comment by hughbe** [comment]
This is a kind of tricky issue. We have a bunch of different exceptions thrown in CreateTypeInfo. S.R.Emit. E. TypeLoadException, BadImageFormatException, ArgumentException, COMException and InvalidOperationException. At least those are the ones I discovered writing unit tests a while ago. There are more that we can do.

For me, it's not really an issue of what type of exception is thrown - I don't really know how we got to the messy situation we did now. I think it's because the CLR shares type creation code with RefEmit.

I'd rather what the message of the exception is.
E.g. Does an ArgumentException tell me more than a COMException? Not really!
In my experience, the messages are usually descriptive enough that I know what the problem is. This is part of the power of RefEmit IMO.

**Comment by mattnischan** [comment]
I agree somewhat, and the message in this case told me mostly what the issue was. But, I only expect to get a COMException when I'm doing interop, and having that pop up here shows an implementation detail that could change, say, if Roslyn were used in some way instead of the QCall.

It's a pretty small thing, but was surprising.

**Comment by AtsushiKan** [comment]
If the message has the right guidance, we shouldn't mess with this. It's technically a breaking change for little impact.
