### ISSUE TITLE
Desktop: System.IO.IsolatedStorage.CreateDirectoryTests.CreateDirectory_ThrowsIsolatedStorageException failed with "System.InvalidOperationException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18803]
Failed test: System.IO.IsolatedStorage.CreateDirectoryTests.CreateDirectory_ThrowsIsolatedStorageException

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.IO.IsolatedStorage/CreateDirectoryTests/CreateDirectory_ThrowsIsolatedStorageException/

Configuration: outerloop_netfx_windows_nt_debug

MESSAGE:
~~~
Assert.Throws() Failure
    Expected: typeof(System.IO.IsolatedStorage.IsolatedStorageException)
    Actual: typeof(System.InvalidOperationException): Store must be open for this operation.
~~~
STACK TRACE:
~~~
at System.IO.IsolatedStorage.IsolatedStorageFile.Reserve(UInt64 lReserve) 
at System.IO.IsolatedStorage.IsolatedStorageFile.CreateDirectory(String dir) 
at System.IO.IsolatedStorage.CreateDirectoryTests.<>c__DisplayClass1_0.<CreateDirectory_ThrowsIsolatedStorageException>b__0() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.IO.IsolatedStorage\tests\System\IO\IsolatedStorage\CreateDirectoryTests.cs:line 26
~~~

**Comment by danmosemsft** [comment]
The divergence from desktop would be fixed in Core by removing the `IsDeleted` check here": https://github.com/dotnet/corefx/blob/88c289e553652e2dfb343a169452e18aad959490/src/System.IO.IsolatedStorage/src/System/IO/IsolatedStorage/IsolatedStorageFile.cs#L694
and instead relying on `if (_closed)`. 

In Desktop, `IsolatedStorageFile.Delete()` does not call `EnsureStoreIsValid` but the exceptoin comes from `Reserve` but there is it doing th echeck of `if (_closed)`.

**Comment by danmosemsft** [comment]
@safern wanna make that change above

**Comment by safern** [comment]
Yes I'll take it no problem.
