### ISSUE TITLE
Desktop: System.Xml.Tests.CReaderTestModule.TCMaxSettings failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18812]
Failed test: System.Xml.Tests.CReaderTestModule.TCMaxSettings

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.Xml.Tests/CReaderTestModule/TCMaxSettings/

MESSAGE:
~~~
Assert.Equal() Failure
    Expected: 0
    Actual: 38
~~~
STACK TRACE:
~~~
at System.Xml.Tests.CReaderTestModule.RunTestCase(Func`1 testCaseGenerator) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Private.Xml\tests\Readers\ReaderSettings\CReaderTestModule.cs:line 20 
at System.Xml.Tests.CReaderTestModule.RunTest(Func`1 testCaseGenerator) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Private.Xml\tests\Readers\ReaderSettings\CReaderTestModule.cs:line 26 
at System.Xml.Tests.CReaderTestModule.TCMaxSettings() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Private.Xml\tests\Readers\ReaderSettings\CReaderTestModule.cs:line 63
~~~

**Comment by Jiayili1** [comment]
Closed issue: https://github.com/dotnet/corefx/issues/16024

**Comment by sepidehMS** [comment]
@danmosemsft This failure is due to a behavior change between Desktop and Core, which was caused when removing System.Private.Xml's dependency on Microsoft.Win32. Prior to that change, `XmlReaderSettings` used to read full framework registry keys to decide the default value of entity resolving limit. Default used to be 0 (=unlimited), but is 10 million characters now.
[The user can still override it with any value.]
Based on this, I believe this change is OK to keep and we can only update the test here. Is that right?

**Comment by danmosemsft** [comment]
The limit is for security / robustness I assume?
Any feasible way a valid doicument would need a higher limit?

**Comment by sepidehMS** [comment]
@danmosemsft Lookin at the Desktop code, looks like in from version 4.5.2 this limit was changed to 10 million characters instead of being unlimited. Since the option was given to the user to set this limit to anything needed, I believe there are ways to need higher limit.

**Comment by danmosemsft** [comment]
Right but that doesn't answer why there is a limit nor why the user might not want one. Maybe @krwq knows.

**Comment by krwq** [comment]
@sepidehMS @danmosemsft the limit is because of this: https://en.wikipedia.org/wiki/Billion_laughs 😉 

Limit should be ON by default - for most of the normal XML documents you should not have problems with limits - only really large documents with many xml entities might need to increase or disable it.

**Comment by danmosemsft** [comment]
OK, if we don't have evidence that signfiicant folks need a higher limit, I'm OK with shipping 2.0 with our current limit. If we get feedback, we'll add a parameter. Please update the test.
