### ISSUE TITLE
HttpClient (libcurl + SecureTransport) client certificate support (macOS)

### ISSUE THREAD

**Issue by tlbdk** [dotnet/corefx#18873]
Did a bit of digging on how libcurl with SecureTransport on macOS loads it's client side certificate, and it seems it can be loaded from a file on disk or from a label in keychain.

https://github.com/curl/curl/blob/33cfcfd9f0378625d3bddbd2c8ac5aad4b646f26/lib/vtls/darwinssl.c#L1354

Given how X509Certificate2 does it certificate handling on windows would it be possible to something similar:

Approach 1:

1. Save the certificate on import to a temp folder encrypted with a random generated password stored with X509Certificate2 object.
2. Pass the file location and random password to libcurl.

Approach 2.

1. Load the certificate into the keychain and get back label save with with X509Certificate2 object.
2. Pass label to libcurl.

I would be happy to give either option a go if I got a bit of help to get started.

**Comment by tlbdk** [comment]
@bartonjs Seems you are the one that handles this kind of stuff, what do you think?

**Comment by bartonjs** [comment]
For approach 1: Who is responsible for cleaning up the file? How do we know when it's safe to do so? And what about non-exportable private keys?

For approach 2: Non-exportable keys are going to be a problem again, because what curl is going to look for is a certificate in the default keychain search list.  On macOS you can have lots of keychains, and lots of them can not be in the search list.  Adding and removing certificates from the keychain can actually change how Apple trust rules work, so I really don't like this option, either.  (And in headless sessions like a cron job the keychain is in readonly mode)

Both of these also carry with them a surprise notion of needing a writable filesystem (and, optionally, keychain); and they make me very uncomfortable.

**Comment by tlbdk** [comment]
Approach 1:
X509Certificate2 should implement the IDisposable interface according to the docs from  .NET Framework 4.6, so the creator would responsible for calling dispose. And also don't we more or less have the same issue on Windows with certificates and keys being left behind in the certificate store?

Non-exportable private keys won't be supported with this option, but I guess that's also not an option with the openssl backed solution?

Approach 2:
Again it feels very much like windows land as you pointer out; MachineKeySet: Requires admin rights, UserKeySet: Requires a loaded user profile, etc. So you will need to know how the keychain works much like you need to know how certificate store works on windows.

Given that all this is just a thin wrapper around the native implementation, requiring writable filesystem or some keychain magic I think is ok.

Alternatively if we want consistant API's cross platform shipping your own http and ssl implementation might be the only option, this is what Java does and that also has it's issues and will require quite a bit of work.

**Comment by bartonjs** [comment]
The file lifetime in this proposal is more complicated than the key file on Windows.  The Windows scenario is it's there from PFX import until the cert is disposed/finalized.  This one would need to be there from the time it was used as a client cert until it isn't needed anymore.

That turns out to be slightly moot, since I ran across a comment (by me, which just shows why comments are useful) that the file-based approach actually causes libcurl to import it into your default keychain and leave it there forever.

I'm not okay with HttpClient usage altering the user keychains (particularly given how the default keychain interacts with the trust system).  Having a cert/key there isn't really HttpClient's decision; it's up to someone using the X509Store API (or other system approaches to it).

**Comment by karelz** [comment]
This does not look like critical for 2.0, moving to Future. Please speak up if you disagree (in which case, please describe the user scenarios).

**Comment by tlbdk** [comment]
Any update on this, it would be nice to have any client side certificate support on mac

**Comment by karelz** [comment]
The issue should be gone with new SocketsHttpHandler, which is default in .NET Core 2.1.
