### ISSUE TITLE
MemoryStream.GetBuffer() does not exist

### ISSUE THREAD

**Issue by xanather** [dotnet/corefx#1897]
Is there a reason why this method does not exist in the contracts? TryGetBuffer() is there while GetBuffer() is not. Looking at the source on CoreCLR I see the methods are basically the same. Is there a reason why TryGetBuffer() would fail?

In my case copying bytes from a memory stream to obtain the byte[] array is not an option and I would be throwing an exception is TryGetBuffer() failed anyway, might as well have used GetBuffer().

**Comment by stephentoub** [comment]
> Is there a reason why TryGetBuffer() would fail?

TryGetBuffer and GetBuffer will fail in the same situation: when the buffer isn't allowed to be exposed, which is based on which constructor is used to create the MemoryStream.  If the buffer isn't exposable, TryGetBuffer will return false and GetBuffer will throw an UnauthorizedAccessException.

**Comment by xanather** [comment]
@stephentoub Thanks for the reply. Okay, so if GetBuffer() will never fail if the MemoryStream was constructed right is there a reason why its not included in the contracts? https://github.com/dotnet/corefx-progress/blob/master/src-full/System.IO.cs#L98

**Comment by stephentoub** [comment]
Not sure.  My guess would be that since you might want TryGetBuffer (e.g. if you were provided with an arbitrary MemoryStream and didn't know how it was constructed), and since you can do with TryGetBuffer exactly what you can do with GetBuffer, that the latter was deemed superfluous.  @weshaggard?

**Comment by xanather** [comment]
Yea, I am using TryGetBuffer now, I just found it odd that is was removed as it breaks compatibility with trying to compile things against .NET Framework and .NET Core for no good reason (DNX can support both at the same time).

**Comment by weshaggard** [comment]
@xanather the reason GetBuffer is removed is because it is broken in the general case and would only work for folks that actually constructed the MemoryBuffer themselves and know the exact part of the underlying buffer that is being used. For example there are constructors on MemoryBuffer that take the buffer and a start index and that start index is not at all reflected in what is returned from GetBuffer so other people that call that without knowing the start index will potentially be looking at memory outside the MemoryStream. That is why TryGetBuffer uses an ArraySegment so it can communicate the start index and the length to the callers so they can properly scope to the underlying buffer being used by MemoryStream.

**Comment by whoisj** [comment]
Search is failing me or MemoryStream isn't open sourced.

Does memory stream use the supplied array if one is provided in the constructor? If so, then I believe the issue is solved. Then I would ask, how does it manage concurrency on the buffer or does it just not care?

**Comment by weshaggard** [comment]
The source for it can be found in the CoreCLR repo:
https://github.com/dotnet/coreclr/blob/cbf46fb0b6a0b209ed1caf4a680910b383e68cba/src/mscorlib/src/System/IO/MemoryStream.cs#L99

Yes it does use the array if one is provided and I don't think it makes any guarantees around concurrency.

**Comment by xanather** [comment]
@weshaggard makes sense. Ill close this issue.

**Comment by whoisj** [comment]
@weshaggard thank you! Looks like it does what you said. Sounds exactly like what the original poster needs :smile:
