### ISSUE TITLE
Make sure object initialization in System.Text.Encodings.Web is synchronized

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefx#1900]
See comments in https://github.com/dotnet/corefx/pull/1889

**Comment by ericeil** [comment]
It's true that the new code, without the volatile write, will happen to work on the CLR memory model.  However, as @stephentoub pointed out, this is not guaranteed by the ECMA CLI spec, so this code may *not* work on other CLI implementations.  Also, I'm not sure what value we get out of removing the volatile write, given that we only run this code once.  If there's real value there, I'd go ahead and keep the new code.  Otherwise my preference would be to put the volatile write back.

**Comment by ericeil** [comment]
One more thought: I think you'll find that you end up with the same native code either way, because the CLR essentially makes this write volatile for you.  So there is likely zero runtime cost difference here.  The only difference is portability to other CLI implementations, and arguably readability.  However, I'd argue that the call to Volatile.Write more clearly expresses the intention of this code.

**Comment by karelz** [comment]
@KrzysztofCwalina we need more info about it ...

**Comment by karelz** [comment]
@KrzysztofCwalina ping?

**Comment by krwq** [comment]
I talked offline with @KrzysztofCwalina and we both agree that the volatile writes are most likely not needed. If we ever see any issue with that we will know what to revert but most likely will never happen.
