### ISSUE TITLE
zip_InvalidParametersAndStrangeFiles.StrangeFiles4 disabled on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1904]
I'm disabling the System.IO.Compression.Tests.zip_InvalidParametersAndStrangeFiles.StrangeFiles4 test on Unix as it fails once we fix the Path.AltDirectorySeparatorChar to be '/' instead of '\' ('\' isn't a valid directory separator char on Unix).

The problem stems from an assert in ZipTestHelpers:
```C#
Assert.Equal(file.Name, entry.Name);
```
This particular "strange" zip file (dataDescriptor.zip) contains an entry named "notempty\second.txt", and the assert is expecting the entry.Name to be "second.txt", but when '\' isn't a separator character, the entry.Name (which just returns Path.GetFileName(...)) is coming back as "notempty\second.txt".

This is after all a "strange" zip file, so I don't know whether this is a product issue or a test issue.

**Comment by ianhays** [comment]
Well if the FullName of the entry is getting set to "notempty/second.txt" (it is) then the Name should be set to "second.txt". 

However, my concern is how the unzipping distinguishes between a file named ```file\ffds``` that is in the current directory and the file ```file\ffds``` that is really the file ```ffds``` in folder ```file```.

I ran some tests and came to these results:

- File Name ```k\k\k\k\k\k\k\k\k``` compressed on Unix using ```zip```
  - Decompressed on Windows using C# ZipArchive: Name = ```k```, FullName = ```k\k\k\k\k\k\k\k\k```. In this scenario the Name is incorrect.
  - Decompressed on Unix using ```unzip```: we get a warning: ``` longslash.zip appears to use backslashes as path separators```. Intermediate directories are created and the file name is ```k```
- File Name ```k\k\k\k\k\k\k\k\k``` compressed on Unix using C# ZipArchive
   - Same results as above
- A file ```k``` from within several intermediate directories ```k\k\k``` on Windows
 - Decompressed on Unix using the ```unzip``` command: ```warning:  longslash.zip appears to use backslashes as path separators``` but it otherwise creates those subdirectories without issue as they were on Windows. Unzip does it correctly here.
  - Decompressed on Unix using the C# unzipper on Unix: I receive no such warning nor do I get the intermediate directories. I instead get a ZipEntry with name set to ```k\k\k\k``` and FullName also set to ```k\k\k\k```. This is incorrect since on Windows these were directories.

so it seems like what we want to do is modify the Unix behavior to act as ```unzip``` does and treat the alternate Directory separator character as equivalent to the directory separator character, regardless of whether it <i>should</i> be.

**Comment by ianhays** [comment]
>act as unzip does and treat the alternate Directory separator character as equivalent to the directory separator character, regardless of whether it should be.

This comment is incorrect. Unix Unzip works as expected when given zip files created using Zip. Example:

- touch "a\b\c\d"
- zip new.zip "a\b\c\d"
- rm "a\b\c\d"
- unzip new.zip

The resulting file is correctly unzipped without warning or creation of intermediate directories.

So there's something about the way we're writing zip files on Unix that is incompatible with how ```unzip``` interprets the backslash. ZipArchive is currently working from a Windows-centric viewpoint on what the backslash means when really there should be special casing for the scenario where the backlash is a valid filename char and not a path separator.

Conveniently enough, it seems like this may be more easily resolvable thanks to the change in #4917. The discussion there was questioning the usefulness of setting the OS field and it would appear that in this situation it would be particularly helpful in determining how to treat the backslash in files compressed within the zip that could have come from any machine. This of course doesn't solve the problem for zip files where the field isn't set (such as those produced by Java or Go), but it at least enables proper treatment of those created by dotnet and by Zip/Unzip.

Will investigate more.
