### ISSUE TITLE
To Fix rd.xml for Serialization Reflection Only Mode

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#19067]
#19006 added rd.xml to `System.Runtime.Serialization.*.ReflectionOnly.Tests`, which made many serialization tests to pass in reflection only mode on UWP. The rd.xml, however, include metadata for the entire System.Private.DataContractSerialization, which is not what we want. We need to fix the rd.xml for System.Private.DataContractSerialization to include just the necessary metadata info.

**Comment by MichalStrehovsky** [comment]
We need to make sure there are reflection-based serializer tests that don't have **any RD.XML whatsoever**. Even if the need for RD.XML here is justifiable ("the test is reflecting on framework types"), we need test coverage that will run reflection-based serialization *the way customers run it*. Ideally there should be two tests (one that has RD.XML and tests internal behaviors that can't be properly exercised by customer code, and another one that tests actual customer scenarios with no RD.XML.)

Otherwise we might end up in a situation where we think serialization works, but only because the test RD.XML opted in a bunch of stuff that customers don't have.
