### ISSUE TITLE
Desktop: System.TypeLoadException: Could not load type 'System.Security.Cryptography.TripleDESCng' from assembly 'System.Security.Cryptography.Cng'

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#19081]
Failed test: System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESReusabilityTests.TripleDESReuseEncryptorDecryptor

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/34/testReport/System.Security.Cryptography.Encryption.TripleDes.Tests/TripleDESReusabilityTests/TripleDESReuseEncryptorDecryptor/

MESSAGE:
~~~
System.TypeLoadException : 
Could not load type 'System.Security.Cryptography.TripleDESCng' from assembly 'System.Security.Cryptography.Cng, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
~~~
STACK TRACE:
~~~
at System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESCngProvider.Create() 
at System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESFactory.Create() 
in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\TripleDES\TripleDESFactory.cs:line 19 
at System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDESReusabilityTests.TripleDESReuseEncryptorDecryptor() 
in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\TripleDES\TripleDESReusabilityTests.cs:line 18
~~~

**Comment by danmosemsft** [comment]
@safern why is it trying to load it from S.S.Cryptography.Cng when it's a desktop test, it should load it from System.Core?

**Comment by safern** [comment]
System.Security.Cryptography.Cng is a facade when building on netfx that has type forwards to mscorlib and System.Core, but this type that is missing is available until 462 and currently the facades when building against netfx are generated against 461 so that is why the type forwards are missing on S.S.Cryptography.Cng... This is the same issue as: https://github.com/dotnet/corefx/issues/18720

See: https://github.com/dotnet/corefx/issues/18720#issuecomment-296741455

I already have a progress on this, should open a PR tomorrow.

**Comment by bartonjs** [comment]
@safern You said a week ago that we should expect a PR "tomorrow".  Any updates?

**Comment by safern** [comment]
@bartonjs sorry, dragged by other issues and I needed to wait for some infra work to happen. Will focus on that now :)
