### ISSUE TITLE
Desktop: System.Security.Cryptography.Hashing.Algorithms.Tests.InvalidUsageTests.InvalidHashCoreArgumentsFromStream failed with "System.Security.Cryptography.CryptographicException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#19092]
Failed test: System.Security.Cryptography.Hashing.Algorithms.Tests.InvalidUsageTests.InvalidHashCoreArgumentsFromStream

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/34/testReport/System.Security.Cryptography.Hashing.Algorithms.Tests/InvalidUsageTests/InvalidHashCoreArgumentsFromStream/

MESSAGE:
~~~
Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual: typeof(System.Security.Cryptography.CryptographicException): Bad Data.\r\n
~~~
STACK TRACE:
~~~
at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr) 
at System.Security.Cryptography.Utils.HashData(SafeHashHandle hHash, Byte[] data, Int32 cbData, Int32 ibStart, Int32 cbSize) 
at System.Security.Cryptography.SHA1CryptoServiceProvider.HashCore(Byte[] rgb, Int32 ibStart, Int32 cbSize) 
at System.Security.Cryptography.HashAlgorithm.ComputeHash(Stream inputStream) 
at System.Security.Cryptography.Hashing.Algorithms.Tests.InvalidUsageTests.<>c__DisplayClass1_0.<InvalidHashCoreArgumentsFromStream>b__0() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Algorithms\tests\InvalidUsageTests.cs:line 32
~~~

**Comment by danmosemsft** [comment]
This one needs to go the other way -- back from AE to CE.

**Comment by ianhays** [comment]
For this one we may want to keep the ArgumentException. The CryptoException is being thrown on netfx because we're not doing boundary checking before attempting to do the hashing. The ArgumentException on netcoreapp is being thrown [in the HashProvider common file before doing the actual hashing](https://github.com/dotnet/corefx/blob/master/src/Common/src/Internal/Cryptography/HashProvider.cs#L30).

We can't really change the helper class's ArgumentException to be a CryptographicException instead, because then we'll get [a bunch of other failures where the code on both netfx and netcoreapp is (rightly) expecting an ArgumentException](https://github.com/dotnet/corefx/blob/7d268bee96866c82829835b5aeaf8de086195fed/src/System.Security.Cryptography.Algorithms/tests/InvalidUsageTests.cs#L13)

cc: @bartonjs

**Comment by bartonjs** [comment]
Yeah, this one seems like we want to keep the corefx fix.
