### ISSUE TITLE
Type.GetType Behaves Differently on netfx and netcore

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#19104]
The following test present different behaviors on netfx and netcore.

```c#
    [Fact]
    public static void TypeGetTypeTest()
    {
        Type t = Type.GetType("Employee, http://www.contoso.com");
        Assert.Null(t);
    }
```

When targeting netstandard or netcoreapp, `Type.GetType` returns null and the test passes; when targeting netfx, the test fails with the following exception,

```
---- System.IO.FileLoadException : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
    Stack Trace:
         at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
         at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtrpPrivHostBinder, Boolean loadTypeFromPartialName)
         at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
         at System.Type.GetType(String typeName)
```

**Comment by danmosemsft** [comment]
@gkhanna79 who is best to investigate this? GetType is implemented in the VM and I can't make much of this unfamliar code.

**Comment by gkhanna79** [comment]
@kouvel Can you PTAL?

**Comment by sjoerdverweij** [comment]
This is an intentional break, to make Reflection cheaper. See "Reflection" under
https://blogs.msdn.microsoft.com/dotnet/2016/02/10/porting-to-net-core/

If you want to use this test for both platforms, you'll have to #ifdef.

**Comment by danmosemsft** [comment]
Apparently we're missing a test or this would show up in our desktop runs.

**Comment by danmosemsft** [comment]
@sjoerdverweij Since 1.x and that blog post we have brought back thousands of types including Type and excepting a few specific technologies (eg appdomains, remoting, CAS) and clear exceptions we are working hard to be compatible across the board. In some cases that even includes throwing to match Desktop. I don't know about this instance specifically.

**Comment by pjanotti** [comment]
The original test is gone, currently netcore and Fx have the same behavior: both return null. Per [documentation](https://msdn.microsoft.com/en-us/library/w3f99sx1.aspx) this seems like a bug that was fixed in Fx: the original error "The assembly or one of its dependencies was found, but could not be loaded."  is incorrect, since nothing could have been found.

Test cases already covering this scenario: 
https://github.com/dotnet/corefx/blob/313d0d29725a347b5ef869aa9de0e9b545be0205/src/System.Reflection/tests/GetTypeTests.cs#L89-L101
