### ISSUE TITLE
Tests in System.Data.Common crash on uapaot

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#19202]
The following tests crash on uapaot:

- System.Data.Tests.SqlTypes.SqlXmlTest.Constructor2_Stream_Unicode
- System.Data.Tests.SqlTypes.SqlXmlTest.Constructor2_Stream_Empty
- System.Data.Tests.SqlTypes.SqlXmlTest.Constructor3
- System.Data.Tests.SqlTypes.SqlXmlTest.Constructor3_XmlReader_Empty
- System.Data.Tests.SqlTypes.SqlXmlTest.CreateReader_Stream_Unicode
- System.Data.Tests.SqlTypes.SqlXmlTest.SqlXml_fromXmlReader_CreateReaderTest
- System.Data.Tests.SqlTypes.SqlXmlTest.SqlXml_fromZeroLengthStream_CreateReaderTest
- System.Data.Tests.SqlTypes.SqlXmlTest.SqlXml_fromZeroLengthXmlReader_CreateReaderTest_withFragment

**Comment by sjoerdverweij** [comment]
I can fix SqlDateTimeTest (not a contributor yet)

**Comment by danmosemsft** [comment]
@sjoerdverweij missed your post. That would be welcome except there is no way for ocmmunity folk to run uapaot tests...

**Comment by saurabh500** [comment]
These tests still fail while running with TargetGroup=aot

**Comment by saurabh500** [comment]
So far we have the following findings:
1. The Internal method XmlReader.CreateSqlReader cannot be accessed without modifying the rd.xml file.
The modifications suggested are 
<Assembly Name="System.Private.Xml">
      <Namespace Name="System.Xml">
        
        <Type Name="XmlQualifiedName" DataContractSerializer="Excluded" DataContractJsonSerializer="Excluded"/>               
                <Type Name="XmlReader" Dynamic="Required" />
      </Namespace>
 
 
Add this to System.Private.Xml.csproj
    <BlockReflectionAttribute>false</BlockReflectionAttribute>


2. Make the method public and make System.Data.Common depend on System.Private.Xml to access the public method instead of accessing the method via reflection.

**Comment by safern** [comment]
@saurabh500  could you please take a look and fix this?

**Comment by saurabh500** [comment]
@Safern are you talking about reverting the PR which enable this test or a real fix? 
I am working with different folks to get a fix in. 

I am stuck at figuring out how to make System.Data.COmmon build with System.Private.Xml instead of the System.Xml.ReaderWriter. Any clues?

**Comment by safern** [comment]
I'm talking about a real fix. Will not revert the PR as the DateTimeTest seems to be fixed. I'm just confirming locally.

> I am stuck at figuring out how to make System.Data.COmmon build with System.Private.Xml instead of the System.Xml.ReaderWriter. Any clues?

Not that come to my mind now but @joperezr might know.

**Comment by safern** [comment]
System.Data.Tests.SqlTypes.SqlDateTimeTest.GetTypeTest is indeed fixed. I don't see it failing anymore. Updating the issue description

**Comment by saurabh500** [comment]
A little context here : I have already tried using ProjectReference to include the System.Private.Xml.csproj in the System.Data.Common.csproj (after removing the System.Xml.ReaderWriter) dependency. However I get compilation errors for all the Xml namespaces.

**Comment by joperezr** [comment]
> I am stuck at figuring out how to make System.Data.COmmon build with System.Private.Xml instead of the System.Xml.ReaderWriter

Well, System.Xml.ReaderWriter is a contract assembly and System.Private.Xml is the implementation of that contract. Do you need an internal type or something that only exists at runtime for this? If so, you basically have to move all of your dependencies to be implementation assemblies instead. For an example of this, you can take a look at the implementation project of System.Collections, which builds against implementations instead of contracts. I can help you accomplish this offline if you'd like.

**Comment by saurabh500** [comment]
@joperezr I need to change System.Private.Xml to expose an internal function for uapaot. That's why I need to change this dependency to compile System.Data.Common against System.Private.Xml.csproj

I don't think I need to change all my dependencies to implementation. I could verify it by adding 
```
<ItemGroup>
    <ProjectReference Include="..\..\System.Private.Xml\src\System.Private.Xml.csproj" />
  </ItemGroup>
```
and compiling  with `msbuild /p:TargetGroup=uapaot`

However the problems arise when I use a Condition on the above ItemGroup 
```
<ItemGroup Condition="'$(TargetGroup)' == 'uapaot' and '$(TargetGroup)' != 'netfx'">
    <ProjectReference Include="..\..\System.Private.Xml\src\System.Private.Xml.csproj" />
  </ItemGroup>
```

Msbuild /v:d /p:TargetGroup=uapaot shows the TG being set to uap instead of uapaot 
As a result, the csproj is not referenced. What else do I need to change to make sure that System.Data.Common can have a target group of uapaot instead of a fallback to uap?

**Comment by saurabh500** [comment]
The plan is to make the changes so that they are specific only to uapaot.

**Comment by joperezr** [comment]
I believe that you have fixed this by looking at the email thread we have going on, but let me know if I can be of any help in here.

**Comment by safern** [comment]
@saurabh500 you closed this from your PR but I didn't see that you re-enabled the tests in your PR. Could you please re-enabled them?

**Comment by saurabh500** [comment]
Ah ok. I was working with a fork before you disabled the tests again. So in my workspace I always had the tests enabled. I should have rebased.
PR at https://github.com/dotnet/corefx/pull/22111
