### ISSUE TITLE
Proposal : runtime attributes

### ISSUE THREAD

**Issue by Pzixel** [dotnet/corefx#19295]
**Summary**

Making easier to extend existing classes with attributes

**Motivation**

Sometimes we find us in situation when we want to attribute being dynamically added to a class that didn't have it before. It may be `Serializable`, `DataContract` or tons of `Validation`. Very viable example is that we want to display some model in UI and validate user inputs. In Microsoft stack you have to do it using `unobtrusive attributes` and MVC takes all care about it. But you cannot reference `Microsoft.Mvc.Razor` from model just because you want some validation for obvious reasons. And here you have to write some ViewModels that is just like a model, but has attributes. You have to write a ViewModel not because you want to add some indirection, but because language itself makes you to do it. 

**Design**

I propose use the same mechanism that is using for inheritance and interfaces. Object can inherit one and only one parent (and overrides address in methodtable) and it has a list of interfaces and implementations of interface methods. I propose something similar: we can just add something like `DynamicAttributesList`, which can be freely populated and cleared by reflection methods. When you call `GetAttributes` it concat results of current implementation of `GetAttributes` and attributes from this list. We already have `System.ComponentModel.TypeDescriptor`, but we may want closer integration with methods such as mentioned `GetAttributes`, because otherwise it's a bit useless.

I don't see this change breaks anything in any way, it's quietly easy to implement it and it simplify some cases a lot.

**Comment by AtsushiKan** [comment]
One problem with this idea is that Reflection CustomAttribute apis are only one way of consuming attributes, and increasingly, not even the preferred way. There's the unmanaged IMetadataImport interface, CCI, System.Reflection.Metadata.dll, and probably others I've overlooked.

So if the idea is to inject new attributes into consumers unaware of your scheme, you have a lot of paths to integrate with.

**Comment by karelz** [comment]
I don't fully understand the motivation. Can you please provide simplest example? Is Mvc the simplest one?
What about security & reliability implications? Imagine when you inject new invalid attributes on Framework types when they should not be there.

Implementation is IMO far from simple - there's tons of code checking for special attributes in Runtimes that does not call into GetAttributes due to speed. Same goes for profilers, debuggers, etc. - they work on the IMetadataImport native interface as mentioned above.
Most code is not resilient to dynamic changes to the list, what will happen if you add attribute later, yet some important decisions have been made.

Overall it sounds much simpler for the frameworks which need the capability to have HashMap on the side and map Type to list of additional attributes. Make it a library "ReflectionAddons". Only the apps/libraries that call into those methods will get the right behavior.

**Comment by Pzixel** [comment]
Here is simple example:

```
public class Foo
{
	public int Value { get; set; }
	public string AnotherValue { get; set; }
}

...

var typeInfo = typeof(Foo).GetTypeInfo();
typeInfo.CustomAttributes.Add(new DataContractAttribute());
typeInfo.GetProperty(nameof(Foo.Value)).CustomAttributes.Add(new DataMemberAttribute(){Name = "FooValue"});
var foo = new Foo
{
	Value = 10,
	AnotherValue = "15050"
};
var ser = JsonConvert.SerializeObject(foo);
// should be `{FooValue: 10}`
```

Maybe we want some syntax to decorate objects more nicely, for example:
```
[DataContract]
public decoration FooDecoration for Foo
{
	[DataMember]
	public int Value { get; set; }
}
```
and usage:
var typeInfo = typeof(Foo).GetTypeInfo();
typeInfo.AddDecoration<FooDecoration >();
// the rest is the same

It may look ugly but it's just to show the idea.  And I see your point that it's not this easy. I wasn't aware of `IMetadataImport`.

**Comment by MichalStrehovsky** [comment]
```
CustomAttributes.Add(new DataMemberAttribute(){Name = "FooValue"});
```

How would this be exposed to [GetCustomAttributesData](https://msdn.microsoft.com/en-us/library/system.reflection.memberinfo.getcustomattributesdata(v=vs.110).aspx)?

E.g. it's legal to have

```csharp
class FooAttribute : Attribute
{
    public FooAttribute(bool isFrobber) { }
}
```

`GetCustomAttributesData` is the only API that lets you access the value of the `isFrobber` passed to the constructor, because it gets lost when the attribute is allocated with `new` (as you can see, it's not stored anywhere within the instance). Actually allocating an instance of the custom attribute type is not the only scenario people use custom attributes for because it's pretty slow.

Most frameworks already provide extensibility points to let them operate on types that were not "enlightened" (don't have attributes sprinkled on them). For the JsonConvert sample, you [write a converter](http://stackoverflow.com/questions/6404881/custom-conversion-of-specific-objects-in-json-net).

**Comment by Pzixel** [comment]
@MichalStrehovsky I don't see any reason why it is working at compile time but inpossible to do at runtime. Runtime's capabilites is superset of compile-time ones.

**Comment by davidfowl** [comment]
This is the sort of thing that `TypeDescriptionProvider` was used for on .NET Framework.

**Comment by MichalStrehovsky** [comment]
> I don't see any reason why not store value in some property

@Pzixel The API surface around custom attributes was designed to also work in situations where running the constructor of the custom attributes is undesirable ([reflection-only load](https://msdn.microsoft.com/en-us/library/ms172331(v=vs.110).aspx)). People also have other reasons why they don't want to actually allocate an instance of the attribute - they just want to read some additional piece of data without that performance overhead. A scheme where these existing APIs give different results is not a good experience. What you call a dirty hack is some other developer's normal workflow.

**Comment by Pzixel** [comment]
@MichalStrehovsky I agree that expirience should be consistent. 

>  The API surface around custom attributes was designed to also work in situations where running the constructor of the custom attributes is undesirable or impossible (reflection-only load). 

But it's totally possible to be done with Expressions/Reflection/... , it's just not this easy as I expected before. If people don't want to allocate an instance - then ok, inspect its code via reflection, but gods, you must specify all required code in body even if you want to inspect it instead of executing. 

Thus, even if we want to perform such kind of work as you propose, I don't see why it's not possible to add runtime attributes. You just have to change some APIs to respect new dynamic attibutes by concating them with readonly compiled attributes, for example.
