### ISSUE TITLE
Check libcurl TLS backend version to avoid calling into OpenSSL 1.1

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#19306]
If we end up in a sheared state where we're linked against OpenSSL 1.0(.2) (the best we currently support) but libcurl is linked against OpenSSL 1.1 (the newest version) we'll try interpreting incompatible pointers; leading to strange behaviors, including segfaults.

Since the distro changing libcurl to use openssl11 could occur even with OpenSSL 1.0 still being on the system the only sign of problems we have are things like segfaults; so we should fix this for the 2.0 release before it becomes prevalent.

The data has to be there somewhere, since it's included in `curl --version`:

```sh
$ curl --version
curl 7.53.0 (i686-pc-linux-gnu) libcurl/7.53.0 OpenSSL/1.0.2k zlib/1.2.11
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: IPv6 Largefile NTLM SSL libz TLS-SRP UnixSockets HTTPS-proxy
```

**Comment by bartonjs** [comment]
Actually, what we probably actually want to know is if it's using OpenSSL is it the exact same libssl/libcrypto.  So if anyone knows any way of determining that, that'd be great.

(Not just "same version"... if it's different `.so` files then they could have different compile options, making pointer-passing still unsafe)

**Comment by optlink** [comment]
@bartonjs I can already build different versions of curl with openssl 1.0 linked or not, the problem I'm having is that System.Net.Http.Native.so won't be linked to it because cmake won't find it even if I pass in DCURL_LIBRARIES. I don't think I can rebuild my distro's default curl without openssl without causing issues in other places, so it's going to have to be overridden somewhere. 

Any ideas on how to tell cmake to use a specific build of curl as a workaround for this issue would be much appreciated.

**Comment by karelz** [comment]
@Priya91 can you please take a look & cost it?

**Comment by Priya91** [comment]
@bartonjs Should we block using httpclient on systems which use libcurl with openssl/1.0? Should we throw PNSE from SetSslOptions [here](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/OSX/CurlHandler.SslProvider.cs)
