### ISSUE TITLE
Path.GetFileName does not correctly handle file names with : character.

### ISSUE THREAD

**Issue by Haacked** [dotnet/corefx#1934]
On my machine, I added the following line to [this test](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/tests/System/IO/Path.cs#L48).

```csharp
Assert.Equal("file:name.exe", Path.GetFileName(Path.Combine("bar", "baz", "file:name.exe")));
```

That test fails because `Path.GetFileName(Path.Combine("bar", "baz", "file:name.exe"))` returns "name.exe".

That doesn't seem to be the correct behavior on any platform.

I'd expect this to either throw an exception (as it would in the case of "file|name.exe") OR I'd expect this to return "file:name.exe" since `:` is an allowed character in file names on non-Windows systems. Given the cross-platform goals of CoreFx, I assume the latter behavior is correct?

_As an aside, I noticed this repository contains [Path.cs](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/IO/Path.cs) but that file is not included in the [project file](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System.Runtime.Extensions.CoreCLR.csproj)._

**Comment by akoeplinger** [comment]
>As an aside, I noticed this repository contains Path.cs but that file is not included in the project file.

See https://github.com/dotnet/corefx/pull/1842#issuecomment-105874238 for an explanation.

**Comment by Haacked** [comment]
Thanks @akoeplinger! So it looks like I should open this issue on dotnet/coreclr. Problem is, I couldn't find any tests of `Path.cs` over there.

**Comment by stephentoub** [comment]
@Haacked, the source for the Path tests are in corefx (https://github.com/dotnet/corefx/tree/master/src/System.Runtime.Extensions/tests/System/IO).  I realize it's a bit confusing.  In general, the surface area of the libraries is tested via tests in corefx, even if some of the implementations live in mscorlib in coreclr.

**Comment by Haacked** [comment]
@stephentoub Thanks! So the implementation is in coreclr, right? If I did this correctly, I should close this since I opened https://github.com/dotnet/coreclr/issues/1104

**Comment by stephentoub** [comment]
> So the implementation is in coreclr, right?

Correct, at least that's the way it is today.  Eventually we'd like to fix up the Path.cs in the corefx repo, which is currently only used for .NET Native, but doing so will take some work, in particular because of our cross-platform requirements.  In mscorlib, functionality that tries to access kernel32 functionality on Unix gets redirected to a PAL layer in libcoreclr, so all of the Win32 functions that Path uses are really being served by Win32 emulations on top of Unix functions.  When we switch to using Path.cs in corefx, we'll want to reimplement that functionality in a better way, going to the Unix functionality directly rather than roundabout through a Win32-like layer.  In the meantime, because we don't include Path.cs in the System.Runtime.Extensions.csproj, the build adds a type forwarder to the assembly for Path so that it can be used via a System.Runtime.Extensions.dll reference but is actually forwarded to the implementation in mscorlib.
