### ISSUE TITLE
Issue with WindowsIdentity.RunImpersonated

### ISSUE THREAD

**Issue by csalgo70** [dotnet/corefx#19375]
I am having issue using RunImpersonated with dotnet core 1.1. I have a web API that is trying to run a stored proc on SQL server using a service account, and hence the need for impersonation. 

At the point where I create the db context I get an exception that its not able to load the Microsoft.EntityFrameworkCore.Relational due to access denied error. 

Note that the login succeeds with service account. Also if I try this whole thing with my own credentials it works fine, but only has the issue when I use another service account.

I tried to add the service account to local machine administrators group just to test but still got the same error.

Any ideas what could be the issue ?

Code Snippet:
```c#
bool LoggedIn = LogonUser(_svcAccount.UserName, _svcAccount.Domain, _svcAccount.Pwd,
                LOGON32_LOGON_INTERACTIVE, LOGON32_PROVIDER_DEFAULT,
                out safeAccessTokenHandle);

if (LoggedIn == false)
{
	int ret = Marshal.GetLastWin32Error();
	Console.WriteLine("LogonUser failed with error code : {0}", ret);
	throw new System.ComponentModel.Win32Exception(ret);
}

var timeCards = WindowsIdentity.RunImpersonated(
safeAccessTokenHandle,
   () => 
   {
   
       // At this point it fails with the following error.
	   //   FileLoadException: Could not load file or assembly 
	   //  'Microsoft.EntityFrameworkCore.Relational, Version=1.1.1.0, 
	   //   Culture=neutral, PublicKeyToken=adb9793829ddae60'. Access is denied.
       using (var db = new TarDbContext(_config, _options))
       {
   
   
   }
 );
```

**Comment by karelz** [comment]
@ianhays any insight here?

**Comment by ianhays** [comment]
Being unable to load the aspnet db dll is interesting... @csalgo70 I assume you've checked that your service account has the right accesscontrol to all of the ASPNet binaries?

**Comment by csalgo70** [comment]
The service account is now an administrator on this machine ( added it to test suspecting it might have some permission issue). So it should have full access.

**Comment by ianhays** [comment]
Have you tried doing other similar operations instead of the `TarDbContext` instantiation? Maybe try modifying a file in the directory that the dll lives in, that kind of thing. Test if the issue is with the permissions not being correctly applied to the Impersonation or if the issue is with the specific APSNet dll.

**Comment by csalgo70** [comment]
I eventually found the issue. In the LongonUser I was passing LOGON32_LOGON_INTERACTIVE which is incorrect. After changing it to value 9, it worked. So closing this issue. Thanks for the responses.

**Comment by Rabadash8820** [comment]
> ... I was passing LOGON32_LOGON_INTERACTIVE which is incorrect.

@csalgo70 I had been using a logon type of `LOGON32_LOGON_INTERACTIVE` (2) for several months, and only in the last week did it start giving me problems (that is, throwing a `FileLoadException`, though in my case there was no exception message).  Changing the logon type to `LOGON32_LOGON_NEW_CREDENTIALS` (9) fixed the problems for me as well.

Since a logon type of 2 had been working for me for so long, can you explain why it is "incorrect", and why 9 is correct?
