### ISSUE TITLE
OverflowPositionPointer test failing

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#19444]
Recently added test is failing on 32-bit (passes on 64-bit):
```
UmsSecurityTests.OverflowPositionPointer [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentOutOfRangeException)
        Actual:   (No exception was thrown)
  Copyright (C) 2014 Outercurve Foundation.
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.IO.UnmanagedMemoryStream\tests\UmsSecurityTest.cs(52,0): at UmsSecurityTests.OverflowPositionPointer()
```

**Comment by stephentoub** [comment]
Hmm, it failed in CI, but it's not failing for me locally.  Closing for now.

**Comment by stephentoub** [comment]
Fails on 32-bit

**Comment by ianhays** [comment]
This check can't pass on 32 bit systems. The purpose of the test is to make the `PositionPointer` setter cast `ulong.MaxValue` to a `long`, producing `-1` which will always be less than the UMS pointer so the final `newPosition` will be negative.

On a 32 bit system where the pointer length is 4, the max value passable to the `PositionPointer` setter is `uint.MaxValue`. So in the test when we cast a value greater than `uint.MaxValue` to the 4-byte `byte*` we only get the `uint.MaxValue` bytes.

Since casting a 4-byte pointer to a `long` will never result in overflow, the AOoRE can never be hit.

cc: @jkotas

**Comment by jkotas** [comment]
I agree with your analysis.
