### ISSUE TITLE
Availability of System.DirectoryServices.* outside of Windows

### ISSUE THREAD

**Issue by snickler** [dotnet/corefx#19453]
I've been wondering whether we would be able to use System.DirectoryServices.* on environments outside of Windows on .NET Core 2.x. Currently I'm running a project that sits on top of .NET 4.6.2 and that's fine, but it requires me to switch back and forth between my OSX & Windows machine while debugging Xamarin.iOS & my MVC project locally. 

I also have to think about others like me who are looking for a supported means of handling AD/LDAP authentication and querying while outside the bounds of Windows.

**Comment by karelz** [comment]
Hello @snickler - I noticed your question on the ASP.NET Core thread. Happy we can take this particular subject offline here.

DirectoryServices porting work is tracked here: #2089 - check the execution plan I updated in the top-post. Note that code is migrated (on Windows only), we just lack tests.

Regarding non-Windows (Linux/Mac) support - System.DirectoryServices.Protocols is doable, all other pieces (System.DirectoryServices, System.DirectoryServices.AccountManagement, and System.DirectoryServices.ActiveDirectory) are unknown/non-trivial. Some may be doable, some may need brand new implementation as they are just wrappers around Windows native DLL implementations (i.e. LOTS of from-scratch work). See details in https://github.com/dotnet/corefx/issues/2089#issuecomment-261061121
If you can raise specific questions about the "unknown" APIs on the main issue, that would be great (please read the linked comment and its many replies - some things are already answered there).

Closing as dupe, if you have follow up questions, please raise them on the main issue #2089, so that all info is in one place. Thank you!

cc @tquerec @j98014
