### ISSUE TITLE
Socket - SendAsync()

### ISSUE THREAD

**Issue by deinok** [dotnet/corefx#19451]
Socket.cs should have an async method for:
```cs
public int Send(byte[] buffer, int offset, int size, SocketFlags socketFlags);
public int Send(byte[] buffer, int offset, int size, SocketFlags socketFlags, out SocketError errorCode);
```

Expected:
```cs
public async Task<int> SendAsync(byte[] buffer, int offset, int size, SocketFlags socketFlags);
public async Task<int> SendAsync(byte[] buffer, int offset, int size, SocketFlags socketFlags, out SocketError errorCode);
```
Probably an extension method would be ok ;)

**Comment by svick** [comment]
There is [`public static Task<int> SendAsync(this Socket socket, ArraySegment<byte> buffer, SocketFlags socketFlags)`](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.sockettaskextensions.sendasync?view=netstandard-1.3#System_Net_Sockets_SocketTaskExtensions_SendAsync_System_Net_Sockets_Socket_System_ArraySegment_System_Byte__System_Net_Sockets_SocketFlags_) in `Socket​Task​Extensions`. Isn't that enough?

**Comment by deinok** [comment]
@svick No, I expect asyncronus code for the POSIX methods. And also i found there is no exact method for the POSIX send http://pubs.opengroup.org/onlinepubs/009695399/functions/send.html

```c#
public int Send(byte[] buffer, int size, SocketFlags socketFlags);
```

**Comment by stephentoub** [comment]
> I expect asyncronus code for the POSIX methods

What do you mean by this?  The implementation of those SendAsync methods on both Windows and Unix does use asynchronous I/O.

> i found there is no exact method for the POSIX send

I don't know what you mean by this either.  What functionality were you hoping to find that's not available?

**Comment by svick** [comment]
@deinok 

The C signature of the method you linked to is:

```c
ssize_t send(int socket, const void *buffer, size_t length, int flags);
```

If you wanted to translate that to C# literally, it would probably be:

```c#
static IntPtr send(int socket, void* buffer, IntPtr length, int flags);
```

Such method would hard to use from C# and very likely not acceptable (no OOP, no enum, using `IntPtr`, etc.).

So, it seems you're okay with making some changes to make the method signature more in line with C#. Then why is changing from `(void*, size_t)` to either `(byte[], int, int)` or `ArraySegment<byte>` not acceptable? Especially considering that `(byte[], int)` is not really equivalent to the C original, since `void*` can point to the middle of an array.

**Comment by deinok** [comment]
@svick 

> Especially considering that (byte[], int) is not really equivalent to the C original, since void* can point to the middle of an array.

That explains the offset var, thanks.
But why is no async method for the two methods i reference in the issue?

**Comment by stephentoub** [comment]
There is. @svick cited it. The arguments are just wrapped in an ArraySegment. What functionality are you hoping for that's missing?

**Comment by svick** [comment]
@deinok `ArraySegment<byte>` is effectively the same thing as the three parameters `(byte[] buffer, int offset, int size)`. There should be nothing stopping you from using that.

And `out` parameters don't make sense in async methods, since the parameter has to be assigned before the returned `Task` completes. That can be worked around by returning a more complicated `Task` (e.g. using a tuple: `Task<(int, SocketError)>`). But I don't see a good way to add that, since you can't overload on return type.

Do you have a use case that needs `SocketError`? And do you have an idea about how the overload should look (like I said, it can't use `out` parameter)?

**Comment by deinok** [comment]
I miss that async is not compat with out params.

Its not a functionality requirement, its only that if you came from another lang, you expect the the signature i said, not the arraysegment.

Seems like this can be closed.

**Comment by stephentoub** [comment]
Thanks.
