### ISSUE TITLE
Win7 test legs failing in Jenkins

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#19480]
With errors like this:
```
  Finished running tests.  End time=13:33:33.49, Exit code = 0
Command execution succeeded.
[outerloop_net---15cfbbd5] $ cmd /c call C:\Users\DOTNET~1\AppData\Local\Temp\hudson4212507020438352447.bat

D:\j\workspace\outerloop_net---15cfbbd5>C:\Packer\Packer.exe .\bin\build.pack .\bin\runtime\netcoreapp-null-Release-x64 
[00:00:00.0000029] Walking Files

Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\j\workspace\outerloop_net---15cfbbd5\bin\runtime\netcoreapp-null-Release-x64'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.EnumerateFileSystemInfos(String searchPattern, SearchOption searchOption)
   at Packer.Main(String[] args) in C:\Users\Matt G. Ellis\Documents\Visual Studio 2015\Projects\Packer\Packer\Packer.cs:line 58
Build timed out (after 120 minutes). Marking the build as aborted.
Build was aborted
```
cc: @danmosemsft, @ellismg

**Comment by danmosemsft** [comment]
What is `packer.cs` and why was it built on Matt's machine? What changed here recently?

**Comment by stephentoub** [comment]
>  What changed here recently?

Not sure how recent it is... looks like they've been failing for weeks!
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_debug/
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/

**Comment by danmosemsft** [comment]
@stephentoub I watch the badges every day -- looks like the problem is that they reflect  `.../lastCompletedBuild/testReport/` and that last completed build could be a while ago.

I opened https://github.com/dotnet/corefx/issues/19483 to add separate build badges.

Meanwhile, Helix has been covering Win7 for us, and it looks like the latest debug build worked: 
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_debug/39/

**Comment by danmosemsft** [comment]
@ellismg can you speak to `packer.cs` please?

**Comment by stephentoub** [comment]
> I watch the badges every day -- looks like the problem is that they reflect .../lastCompletedBuild/testReport/ and that last completed build could be a while ago.

I never look at /lastCompletedBuild/testReport... I click on the badge and then immediately delete that part of the URL because I don't find that testReport nearly as useful as the actual build number and the consoleText.

And I was referring to the sidebar that shows the last N builds, many/most of which failed for the last few weeks.  I didn't look at each individual one... it does look like some of the builds failed for other reasons, but close to none actually passed.

> it looks like the latest debug build worked https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_debug/39/

Build 39 is from May 3rd.  But more recently:
May 7th: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_debug/43/consoleText
May 5th:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_debug/41/consoleText

**Comment by ellismg** [comment]
> @ellismg can you speak to packer.cs please?

Packer was a tool I built in the past to de-dupe the output that we were shuttling across machines.  In the past, we did not build the test on all platforms and so we needed to copy all the built artifacts to other machines for testing (this is how we handled Nano and Linux).  Also, at that time every single test got its own copy of the runtime and libraries (instead of running against a shared copy, like they do today) so our test drops were multiple gigabytes and archiving the test drop was taking 30+mins)  Packer was a simple way to de-dupe a zip file so we could shuttle the entire drop around in only a few hundred megabytes).

Given the changes that have happened in corefx recently, I don't think you need it anymore.  It should be safe to just remove it from the netci.groovy file and update the archiving steps to save all of bin.  You'll also need to update the Nano job: https://github.com/dotnet/corefx/blob/master/netci.groovy#L163

**Comment by weshaggard** [comment]
This `netcoreapp-null-Release-x64` looks suspect in the script. We should never have "null", as it should be the OS.
