### ISSUE TITLE
Constructing a SortedSet<T> from an enumerable with lots of dups is O(N^2)

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1953]
The set's implementation iterates from start to end, comparing each element against the previous one.  Each time it finds a match, it calls list.RemoveAt to remove that element.  This results in the list needing to shift down all elements after the current one. There are some other inefficiencies, too, such as copying to temporary arrays.

**Comment by sharwell** [comment]
I agree with this analysis. For reference, the problem is caused by [this loop](https://github.com/dotnet/corefx/blob/9aa63493a5400b10c153a23d0cac58b6cda04004/src/System.Collections/src/System/Collections/Generic/SortedSet.cs#L147-L154).

I noticed that the line before this uses `List<T>.Sort`, which is documented as a potentially unstable sort. This means the specific instance which appears in the final `SortedSet<T>` among a group of duplicates is unspecified. While the documentation for this construction mechanism isn't clear, I believe most users would expect the first instance returned by the `IEnumerable<T>` to be used.
