### ISSUE TITLE
Fail to parse the valid DateTime string to DateTime

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#19550]
Throw FormatException when convert the string to DateTime .
```
var dateTimeFormat = new DateTimeFormat("hh:mm:ss.ff tt", CultureInfo.CreateSpecificCulture("es-AR"));
DateTime.ParseExact("03:58:32.00 a.m.", dateTimeFormat.FormatString, dateTimeFormat.FormatProvider, dateTimeFormat.DateTimeStyles);
DateTime.ParseExact("03:58:32.00 a. m.", dateTimeFormat.FormatString, dateTimeFormat.FormatProvider, dateTimeFormat.DateTimeStyles);
```
Either "03:58:32.00 a.m." "03:58:32.00 **a. m.**" will fail when converted to DateTime depend on the OS. 
It will cause the serialization/deserialization through different machines fail.

**Comment by danmosemsft** [comment]
@tarekgh ?

**Comment by tarekgh** [comment]
This is expected/By Design. We never guarantee parsing DateTime across OS's or machines. The parser cannot know if a.m. is a valid AM designator if the culture "es-AR" have different designator like "a. m.". there is no way the parser can know that (imaging the designator changed to something like "ص", how the parser can parse "a.m."

To ensure formatting and parsing work you have to use Invariant Culture during the formatting and during the parsing.
