### ISSUE TITLE
Why have a 302 Exception when i put a request

### ISSUE THREAD

**Issue by Circlecirclecircle** [dotnet/corefx#19596]
Url:https://xxxx.xxxxx.xxxxxx.com/
Use:~\.nuget\packages\system.net.requests\4.3.0\ref\netstandard1.3\System.Net.Requests.dll
Exception.Message:The remote server returned an error: (302) Moved Temporarily.

Exception.StackTrace:
at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
at System.Net.WebRequest.<>c.b__37_2(IAsyncResult iar)
at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization)

```
private static HttpWebResponse _Request(string url)
{
    HttpWebRequest request = WebRequest.CreateHttp(url);
    HttpWebResponse response =(HttpWebResponse)request.GetResponseAsync().Result;
    return response;
}
```

**Comment by stephentoub** [comment]
What URL were you trying to reach, and what was the Location it sent back?  Most likely:
- It was an https URL attempting to redirect to an http Location, which isn't followed for security reasons, or
- The number of redirects exceeded the max allowed.

**Comment by Circlecirclecircle** [comment]
this request have 11 Redirect ,and the first time is https Redirect to http,
so how can i not allow auto Redirect?
I don't fount AllowAutoRedirect in HttpWebRequest.
because i Reference library is error?

i use SDK Microsoft.NETCore.App 1.1.1 

Reference library from .nuget\packages\system.net.requests\4.3.0\ref\netstandard1.3\System.Net.Requests.dll

**Comment by Circlecirclecircle** [comment]
the .NETStandard 1.6 can found AllowAutoRedirect in HttpWebRequest. 
so I write a Common Library include HttpRequest  function.


thanks you @stephentoub

**Comment by Circlecirclecircle** [comment]
i was wrong,  the .NETStandard 1.6 not include HttpWebReponse

**Comment by davidsh** [comment]
.NET Core 2.0 (and thus .NETStandard 2.0) includes the full set of HttpWebRequest, HttpWebResponse APIs and matches .NET Framework.

The 'AllowAutoRedirect' property of HttpWebRequest is there:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/ref/System.Net.Requests.cs#L151

Since you want to do a redirect from HTTPS to HTTP (which is not supported in .NET Core), you will need to turn off 'AllowAutoRedirect'.  Then you can handle the 3xx response yourself, parse the HTTP response header "Location:" and do a new request.
