### ISSUE TITLE
HttpStreamAsyncResult.CompletedSynchronously is broken on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#19744]
In the managed implementation of HttpListener, it always returns true.

**Comment by karelz** [comment]
Sounds like 2.0 blocker to me ... thoughts?

**Comment by stephentoub** [comment]
Yes... but the issue to improve testing of HttpListener was long ago deprioritized and marked as Future (https://github.com/dotnet/corefx/issues/13618), we have only ~40% code coverage of the library, and s such I expect there are many such issues we'd consider ship blockers if we were far enough here to even know about them. 😦

**Comment by karelz** [comment]
Understood.
I view the lack of testing as result of prioritization (as you point out) - cost/value/risk exercise. It is legacy API (lower value), the implementation came from another code base (lower risk that regressions will get in, hence also lower value) and it was rather costly.

However, known differences (even in legacy API with low usage) should go through separate cost/value/risk exercise:
* value is typically non-trivial (unless it is some very obscure API),
* cost is cost of the fix - so TBD here
* risk is higher as it is known difference from Desktop (unless it is very obscure API with near-0 usage)

So if the fix is low cost, I'd say let's do it to eliminate any risk. If the cost is non-trivial, we can look at usage data and potentially punt it and run with the risk of shipping known compat break -- we should document it in the API compat list at minimum in such case.

**Comment by hughbe** [comment]
I could work on this as part of consolidating the IAsyncResults between managed and windows. This would also give us the side effect of adding extra argument validation in the managed side that was kidding before.

In terms of code coverage for HttpListener - it's bad, but also a lot of it (at least branch coverage) is tracing.
Authentication tests are missing but I got caught up in recent PRs so I couldn't add tests right now.

**Comment by karelz** [comment]
Thanks @hughbe for you insights about code coverage!
I think that in the authentication space we took some shortcuts on Linux and/or Windows? (@Priya91 knows details) - something we will document in [API compat](https://github.com/dotnet/corefx/wiki/ApiCompat) soon-ish.

If you plan to work on this particular issue, please ping us here when you start the work.
Given it is 2.0, we are a bit on the clock, so we might need to fund it from our side before you get time ... However, if you start working on it, I don't want to snatch it away from you ;-)

**Comment by stephentoub** [comment]
I was wrong about this issue.  Doesn't look like it's actually a problem.
