### ISSUE TITLE
UWP Compability with .NET Standard System.Net.Security

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#19783]
@taoyouh commented on [Sat May 13 2017](https://github.com/dotnet/standard/issues/343)

Though System.Net.Security.SslStream is not in the .Net Standard 1.4, but the NuGet package System.Net.Security supports .NET Standard 1.3. So it's supposed to support Universal Windows Platform 10.0. I installed the package to a UWP project targeting 10.0.15063 and try to reference it, only getting the following exception:

> System.IO.FileNotFoundException:“Could not load file or assembly 'System.Net.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. 系统找不到指定的文件。（System cannot find the file）”

The referencing code is very simple:
`            Stream str = new MemoryStream();
            SslStream stream = new SslStream(str);`

**Comment by davidsh** [comment]
System.Net.Security will be available for UWP platform in .NET Core 2.1 release timeframe.

**Comment by taoyouh** [comment]
So I think it is currently unsafe to reference a .NET standard library from a UWP project? What about Xamarin?

**Comment by ViktorHofer** [comment]
I wouldn't say unsafe. It's just not supported yet in UWP. Xamarin should support it as they have all the APIs from Mono. When targeting .NET Standard 2.0 you should cover all targets except UWP. For more info see here: https://apisof.net/catalog/System.Net.Security.SslStream

**Comment by taoyouh** [comment]
The problem is that I get no error when installing a NuGet package that use System.Net.Security to a UWP project, only getting exceptions at runtime. 
Allowing referencing System.Net.Security in UWP makes it necessary to check if all the dependencies are supported in UWP. 
In .NET standard 2.1, will there still be any packages that are not supported by UWP?

**Comment by CIPop** [comment]
The majority of S.N.Security features should now be available in UWP (from the master branch). We're still tracking some behavior differences when running in an AppContainer with #20033.

**Comment by Puiu** [comment]
Hi,
I am getting the same error when I am trying to use Serilog.Sinks.Email in my UWP project. Is there any way to automatically send an email from a UWP headless project right now?

**Comment by ViktorHofer** [comment]
Not that I'm aware of. Of that's fine for you, you could open the default mail application with prefilled To, Subject and Body so that the user only has to click the send button... Some apps are doing that, e.g. MyTube

**Comment by Puiu** [comment]
It is not an option because it is an app that runs in the background with no gui.

**Comment by ViktorHofer** [comment]
I see... I'm curious, is UWP already supporting non GUI applications?

**Comment by taoyouh** [comment]
Yes. UWP runs on headless Windows IoT Core devices.

在 2017年8月3日，下午4:54，Viktor Hofer <notifications@github.com<mailto:notifications@github.com>> 写道：


I see... I'm curious, is UWP already supporting non GUI applications?

**Comment by Puiu** [comment]
Yes, for ARM devices at least:
https://developer.microsoft.com/en-us/windows/iot/Docs/HeadlessMode

**Comment by ViktorHofer** [comment]
thanks

**Comment by davidsh** [comment]
>Is there any way to automatically send an email from a UWP headless project right now?

For UWP6.0 release later this year, that release supports more .NET APIs including all APIs that are part of .NETStandard2.0.  System.Net.Mail, for example, will be available as part of that expanded API set.  That library will be available for UWP6.0 release.

You might want to try System.Net.Mail library, which has the SmtpClient() class, which can send email thru an SMTP server.

**Comment by borrrden** [comment]
This has gotten a bit off track.  As far as SslStream goes, is it available yet in UWP 6.0.1?  Do I have to upgrade my library to .NET Standard 2.x to take advantage of it, or will a .NET Standard 1.4 library with UWP 6.0.1 work?  The apisof website appears to be down...

**Comment by davidsh** [comment]
>This has gotten a bit off track. As far as SslStream goes, is it available yet in UWP 6.0.1? Do I have to upgrade my library to .NET Standard 2.x to take advantage of it, or will a .NET Standard 1.4 library with UWP 6.0.1 work?

System.Net.Security.SslStream class is available in UWP 6.0.x.  You will have to update your library to .NET Standard 2.x most likely in order to use UWP 6.0.x platform.

**Comment by borrrden** [comment]
I was able to update the UWP nuget package to 6.0.1 against a 1.4 library (but still it complains about not finding the class).  It's a bit confusing if I have to upgrade the actual library to 2.0 as well because there is no indication of that.  What exactly does this "6.0" number refer to?  Is this independent of Windows versions?

**Comment by davidsh** [comment]
I recommend you open a new issue because closed issues are not regularly monitored.

In general, though, System.Net.Security is only available when using NETStandard2.0 if running on UWP platform. The "6.0" is UWP6.0.x is the milestone that represents running UWP apps on latest version of Windows 10 that supports NETStandard2.0.

You will probably have to have your library reference NETStandard20 in order to fully support System.Net.Security APIs on UWP.

**Comment by taoyouh** [comment]
@borrrden You just need to know the System.Net.Security NuGet package is not compatible with UWP. You need to remove its reference. But if you use .NET Standard 1.6 or above, you don't need that package to use System.Net.Security namespace.
So if you want to use that in UWP, you need to use .NET Standard 1.6 or above, which is only supported in UWP 6.
