### ISSUE TITLE
Proposal: dynamic array with lazy reallocation feature

### ISSUE THREAD

**Issue by ygc369** [dotnet/corefx#19817]
Copied from https://github.com/dotnet/csharplang/issues/586
The current C# array can "resize", but it acturally allocates new memory and copies data, and the old memory can neither be freed nor be used until next GC. 
I hope to have a kind of dynamic array which can change its length without memory reallocation until next GC. When this kind of array extend its length, only allocate memory of "extended" size, and use an internal list to manage the old and new memory. Users needn't know how many internal fragments the dynamic array has, they should be able to use it as a normal array. When GC occurs, the CLR should put all fragments of a dynamic array together and update internal link pointers. If the dynamic array reduces its length, the CLR should be able to "free" some memory after next GC.
All these CLR actions should be transparent to users. 
The dynamic array should be a new class, and do not affect the behavior of the current array.
For example:
```C#
DynamicArray<int> da=new DynamicArray<int>(100); //length is initialized to be 100
......
da.Resize(200); 
/*new size is 200, but only allocate new memory of size 100. Old memory is still in use and links to new memory. Now 'da' has internal fragments, but it will have contiguous memory of size 200 after next GC. */
......
da.Resize(10);
/* No allocation. Free memory of size 190 after next GC. */
```

**Comment by ygc369** [comment]
Nobody are interested in this?

**Comment by svick** [comment]
My worry is that the performance benefit is unclear (mostly because indexing into a linked list is not O(1), but also because it adds one level of abstraction) and the cost of making GC do all the work you describe is probably very high. Instead, I think a better solution would be to have an array which can be resized without reallocating, which is why I have just opened https://github.com/dotnet/coreclr/issues/11686.
