### ISSUE TITLE
[HttpListener] Multiple HttpListeners on same IP Endpoint

### ISSUE THREAD

**Issue by baulig** [dotnet/corefx#19827]
In both .NET 4.5 and Mono, you could have have `HttpListener` instances listen on the same IP Endpoint with different paths, such as for instance

			HttpListener listener1 = new HttpListener ();
			listener1.Prefixes.Add ("http://127.0.0.1:" + port + "/");
			HttpListener listener2 = new HttpListener ();
			listener2.Prefixes.Add ("http://127.0.0.1:" + port + "/hola/");
			listener1.Start ();
			listener2.Start ();

This behavior has changed in https://github.com/dotnet/corefx/commit/7a48e11efae5b163a6c3b3d49a7066960e40a5c2 with no explanation why this change has happened.

It is a problem for two reasons:

1. It changes behavior from .NET 4.5 in a way that could possibly break many existing customer applications.
2. It shifts the burden of maintaining endpoint listeners from the backend to the user.

I discovered this problem while trying to replace Mono's HttpListener implementation with the one from CoreFX (see https://github.com/mono/mono/pull/4850).  Since this change could possibly break an unknown amount of existing customer code (apart from our failing unit test), it currently blocks us on going forward with the change.

Going forward, I would like to understand why this change happened and work with you towards a solution.

**Comment by davidsh** [comment]
cc: @hughbe @stephentoub @Priya91

**Comment by stephentoub** [comment]
> I would like to understand why this change happened and work with you towards a solution

We have a dearth of testing on HttpListener right now.  Some works are working to improve that and fix issues found in the managed/Unix implementation to match it to the Windows one; that was the purpose of that PR.  But it sounds like something got messed up along the way and needs to be fixed asap.

@baulig, it's sounds like you're saying this broke something not just in the managed implementation on Unix but also in the Windows implementation for .NET Core?

@baulig, are there tests you can add from Mono a) for this specific issue and b) to help avoid other such regressions in the future?

@hughbe, please take a look at this asap.  If you're unable to look soon, we'll need to revert the whole PR.

**Comment by stephentoub** [comment]
> @baulig, it's sounds like you're saying this broke something not just in the managed implementation on Unix but also in the Windows implementation for .NET Core?

I just tried... the Windows implementation behaves as expected, so you were just referring to the managed implementation used on Unix, correct?

**Comment by baulig** [comment]
Yeah, it's just the Unix implementation.  I also checked with .NET 4.7 in a Windows 10 Azure VM and it's working as expected.

For tests, we have this in Mono: https://github.com/mono/mono/blob/master/mcs/class/System/Test/System.Net/HttpListenerTest.cs#L200

**Comment by stephentoub** [comment]
> For tests, we have this in Mono

Would you be able to / have the time to port those tests to corefx?  That should hopefully make it much easier for folks making changes in corefx to avoid breaking Mono again, once this issue is addressed and you're able to use the exact same sources.

> Yeah, it's just the Unix implementation

Ok, thanks for confirming.  I assume it's this that caused the break:
https://github.com/dotnet/corefx/commit/7a48e11efae5b163a6c3b3d49a7066960e40a5c2#diff-ffb41bfd49a253762a27f303f9ae6817R106
I assume @hughbe added that because some other test was passing on Windows and failing on Unix as a result.  And indeed when I comment out that throw, these tests (which are passing on Windows) fail:
https://github.com/dotnet/corefx/blob/42ea4be840ccb94ec6c39a38d46d395089b533d3/src/System.Net.HttpListener/tests/HttpListenerPrefixCollectionTests.cs#L186
https://github.com/dotnet/corefx/blob/42ea4be840ccb94ec6c39a38d46d395089b533d3/src/System.Net.HttpListener/tests/HttpListenerPrefixCollectionTests.cs#L228
so presumably there's some subtlety that needs to be addressed.

**Comment by baulig** [comment]
Looking at your `Add_AlreadyStarted_ReturnsExpected`, it seems like `HttpListenerFactory` will start `"http://{Hostname}:{port}/{_path}/"` and `factory.Path` returns `_path`.

The test uses `http://localhost:{port}/{factory.Path}/`.

Depending on which port the factory is using, the loop may or may not try the same one first.  So in theory, the `listener.Prefixes.Add(uriPrefix)` in line 199 may attempt to add the same prefix that the factory is using.

**Comment by baulig** [comment]
If I understand the `Add_PrefixAlreadyRegisteredAndStarted_ThrowsHttpListenerException` correctly, then the `Assert.Single` will return the prefix that `HttpListenerFactory`s constructor used to start the default listener.

Line 235 then attempts to add that same prefix - which should throw.
The next line then attempts to add a sub-path of that prefix - this should work.

**Comment by hughbe** [comment]
Yup I addded these tests and caused this - sorry! I'd like to clarify what the problem is before I push a fix.
Basically we are aligning the managed implementation with Windows with a view to have almost 100% comparability with Windows. One of the reasons for this is that we plan to use the managed implementation for UWP on Windows.

Now that I've got some context out of the way: do you expect  the test that adds on a sub path (L235 in AddPrefix_PrefixAlreadyRegisteredAndStarted_ThrowsHttpListenerException) not to throw?
I think that's what I understood from your previous comment.

It seems like we explicitly test this scenario, which settles my nerves slightly, but obviously I will look into a fix and add more tests when I get your response - thanks

**Comment by hughbe** [comment]
Going forward, I agree it'd be helpful to port the Mono tests to corefx and this is something I'd be happy to assist with or drive.
You may also be interested in https://github.com/dotnet/corefx/issues/18128

Also, are you sure about Net45? We run the unit tests for System.Net.HttpListener against netfx so any regressions should be caught.

**Comment by stephentoub** [comment]
> so any regressions should be caught.

Any regressions for which we have a test... but we don't have the test that caught this... the test that caught this was from Mono.

**Comment by hughbe** [comment]
> Any regressions for which we have a test... but we don't have the test that caught this... the test that caught this was from Mono.

I meant regressions for `AddPrefix_PrefixAlreadyRegisteredAndStarted_ThrowsHttpListenerException` but I misunderstood the issue. This issue is multiple listeners on the same port rather than the same listener on the same port.

**Comment by hughbe** [comment]
I've sent in https://github.com/dotnet/corefx/pull/19874.

> Going forward, I would like to understand why this change happened and work with you towards a solution.

First thanks for reporting this and I apologize for the problems it caused mono folks and for the disruption. The unit test coverage of HttpListener is not very high - this is something I've been working on by hand writing new tests and (soon) porting Mono tests. There was a bit of a rush to get things fixed quickly for a 2.0 issue before ZBB.

**Comment by karelz** [comment]
Reopening to track 2.0 port

**Comment by karelz** [comment]
Tracked in large port bug: https://github.com/dotnet/corefx/issues/20060#issuecomment-302956042
