### ISSUE TITLE
String.IndexOf broken for 'ʻ'

### ISSUE THREAD

**Issue by faimada** [dotnet/corefx#1983]
var tmp = "aʻ";
Console.WriteLine( tmp.Contains("a") ); // True
Console.WriteLine( tmp.IndexOf("a") );  // -1

**Comment by ellismg** [comment]
The problem here is `Contains` does an ordinal comparison, whereas `IndexOf` does a linguistic comparison.  In this case, the second character (U+02BB, MODIFIER LETTER TURNED COMMA) modifies the previous letter such that the pair is treated differently from the raw letter a.

This happens with other characters as well, for example U+0303 (COMBINING TILDE).

If you change your sample to be:

```csharp
var tmp = "aʻ";
Console.WriteLine(tmp.Contains("a")); // True
Console.WriteLine(tmp.IndexOf("a", StringComparison.Ordinal)); // 0
```

Then you get the behavior you expect, since now both functions are doing ordinal comparisons.

**Comment by stephentoub** [comment]
@faimada, I'm going to close this out; please reopen if you still believe there's a problem.  Thanks.
