### ISSUE TITLE
X509Certificate2.CopyWithPrivateKey does not work as expected.

### ISSUE THREAD

**Issue by devunt** [dotnet/corefx#19888]
```c#
using (var rsa = RSA.Create())
{
    var request = new CertificateRequest("CN=localhost", rsa, HashAlgorithmName.SHA256);

    var serialNumber = new byte[8];
    using (var rng = RandomNumberGenerator.Create())
    {
        rng.GetBytes(serialNumber);
    }

    var now = DateTimeOffset.UtcNow;
    var rootCertificate = new X509Certificate2(@"C:\path\to\root\certificate.pfx");
    var certificate = request.Create(rootCertificate, now, now.AddYears(1), serialNumber);

    var certificate1 = certificate.CopyWithPrivateKey(rsa);
    var certificate2 = new X509Certificate2(certificate1.Export(X509ContentType.Pkcs12));

    // NullReferenceException
    Console.WriteLine(certificate1.ToString(true));

    // Works well
    Console.WriteLine(certificate2.ToString(true));
}
```

After checking both certificate with inspector, it was discovered that some fields of `X509Certificate2.PrivateKey.Key` objects such as `KeyName`, `IsEphemeral`, `UniqueId` are different from each certificates.

Because of this issue, `certificate1` cannot be used for `SslStream.AuthenticateAsServer` method.
To workaround this, generated certificate should be exported as pcks#12 and reimported agian.

**Comment by karelz** [comment]
@bartonjs is it serious for 2.0?

**Comment by bartonjs** [comment]
It's not just CopyWithPrivateKey, it's EphemeralKeySet.  Apparently we don't have a test that loads from a PFX and calls `ToString(true)`.

Well, we will now.  (LocalFixed).

**Comment by henning-krause** [comment]
Should this be fixed by now? I'm asking because I have a netstandard2.0 app with this exact problem.

Exporting and importing the certificate again fixes the issue. And this only happens on Windows. On Linux, everything is fine.

**Comment by bartonjs** [comment]
@henning-krause The fix is in the release branch and ready to go, but we haven't published any updates to 2.0 yet.  I think we're planning on next month for an update release.

Public daily builds, or private builds from the release branch, would have this fixed.

**Comment by karelz** [comment]
@bartonjs if the fix didn't get into 2.0 RTW, can you please change the milestone to 2.0.x to capture the fact? Thanks!

**Comment by bartonjs** [comment]
Hmm, okay, good point @karelz.  While the commit didn't show the v2.0.0 tag I do see that the fix is present there: https://github.com/dotnet/corefx/blob/v2.0.0/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Windows/CertificatePal.cs#L406-L418.

So @henning-krause, if you're using the released version of 2.0 you should have the fix for this.  If you're having a similar-but-different problem, please open a new issue.

**Comment by devunt** [comment]
As indicated in the original comment, the problem here is with `CopyWithPrivateKey` method, not with the stringification process.

**Comment by bartonjs** [comment]
@devunt What do you think the problem is?  Aside from the NullReferenceException, everything works as expected.  (You attached an ephemeral key; but the PFX export (as ephemeral) and import (to non-ephemeral) changes that)

**Comment by henning-krause** [comment]
I think I have the exact same issue, not a different one. 

I construct the private certificate using CopyWithPrivateKey and than pass the new certificate to an SslStream and call AuthenticateAsServer.

The result a Win32Exception:
```` 
{System.ComponentModel.Win32Exception (0x80004005): No credentials are available in the security package
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
   at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c__DisplayClass35_0.<AuthenticateAsServerAsync>b__0(AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync(Func`3 beginMethod, Action`1 endMethod, Object state)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)

```

If I export the key and import it again, I can use the certificate with the SslStream.

**Comment by bartonjs** [comment]
It's possible that SslStream doesn't work with ephemeral-key certificates (I don't know that they have any tests for it).  So that's a different bug.  `CopyWithPrivateKey` is doing what it's supposed to.

CopyWithPrivateKey leaves the private key alone (mostly), it just associates it with the certificate.

* If you just do RSA.Create() (or ECDsa.Create(), etc) you have an ephemeral key.
* If you do `new RSACryptoServiceProvider(2048, new CspParameters { KeyContainerName = Guid.NewGuid().ToString("N") }) you have a named (as a GUID in this case) / persisted key.
* If you do `CngKey.Create` to make a named RSA key and do `new RSACng(cngKey)` you have a named/persisted key.

If, on Windows, you call CopyWithPrivateKey using a persisted RSACryptoServiceProvider or a persisted RSACng object you get a certificate which understands that the key is already persisted on disk.  Otherwise, the key is cloned into a new in-memory-only (ephemeral) CNG key and the key pointer is associated with the certificate.  This is the same as opening a PFX with `X509KeyStorageFlags.EphemeralKeySet` asserted.  CopyWithPrivateKey never writes anything to the hard drive.  Pretty much it's "ephemeral in, ephemeral out".

When you load a PFX on Windows and do not assert `EphemeralKeySet` the private key is written to the hard drive.  If you assert `PersistKeySet` that file stays forever.  Otherwise the file is best-effort deleted when the certificate gets freed (the state I call "perphemeral")

So the observation that `((RSACng)cert.GetRSAPrivateKey()).Key.KeyName` is `null` when the input was ephemeral is correct.  If SslStream on Windows (unfortunately) doesn't work with ephemeral private keys then them not working is (unfortunately) correct as far as CopyWithPrivateKey is concerned.

Please open a new issue reporting that certificates with ephemeral private keys don't work via SslStream on Windows; and any other issues with ephemeral private keys.

**Comment by henning-krause** [comment]
Alright, will do that.

**Comment by smudge202** [comment]
I just experienced this issue and ended up here. Please note that assigning a `KeyContainerName` to `CspParameters` when instantiating your private key provider seems to trick everything into thinking the key is persisted and works as intended.

In my case, I'm decoding an RSA key and setting up the crypto provider as follows:

```csharp
private static RSACryptoServiceProvider DecodeRsaKey(this byte[] key)
{
	using (var stream = new MemoryStream(key))
	using (var reader = new BinaryReader(stream))
	{
		var endian = reader.ReadUInt16();
		if (endian == 0x8130) reader.ReadByte();
		else if (endian == 0x8230) reader.ReadInt16();
		else throw new InvalidOperationException("No endian");

		var version = reader.ReadUInt16();
		if (version != 0x0102 || reader.ReadByte() != 0x00)
			throw new InvalidOperationException("Unknown version");
		var param = new RSAParameters
		{
			Modulus = reader.ReadBytes(reader.GetIntSize()),
			Exponent = reader.ReadBytes(reader.GetIntSize()),
			D = reader.ReadBytes(reader.GetIntSize()),
			P = reader.ReadBytes(reader.GetIntSize()),
			Q = reader.ReadBytes(reader.GetIntSize()),
			DP = reader.ReadBytes(reader.GetIntSize()),
			DQ = reader.ReadBytes(reader.GetIntSize()),
			InverseQ = reader.ReadBytes(reader.GetIntSize())
		};
		using (var hash = new SHA256Managed())
		{
			var result = new RSACryptoServiceProvider(new CspParameters
			{
				KeyContainerName = Convert.ToBase64String(hash.ComputeHash(key))
			});
			result.ImportParameters(param);
			return result;
		}
	}
}
```

If you use the result of this in the `CopyWithPrivateKey` call, everything works (for me at least). More details available on how I got it working on request (in case I missed anything).

I'm not sure if this is working around a bug or working as intended.

**Comment by bartonjs** [comment]
> Please note that assigning a KeyContainerName to CspParameters when instantiating your private key provider seems to trick everything into thinking the key is persisted and works as intended.

That doesn't "trick it".  It persists the key.  And then `CopyWithPrivateKey` understands it was bonded to a persisted key.

**Comment by smudge202** [comment]
Thanks for the info. Unfortunately, it doesn't work on Linux (PSNE on `CspParameters`).
