### ISSUE TITLE
Need PlatformDetection.IsUAP to allow testing of UAP specific behaviors

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#19907]
#1395 talks about making `TargetFrameworkMonikers.Uap` more useful to be used in a Skip* attribute on a test method/class.

But what can we use within tests where we have different behaviors between platforms? For example, we have the `PlatformDectection` class.  We can use things like "if (PlatformDetection.IsFullFramework)" etc.

However, for UAP apps, it is confusing.

We have PlatformDetection.IsWinRT.  That seems to do a runtime check on the exe itself to determine if it is app-container, etc.  But I've heard that uap-aot testing doesn't actually run as app-container. It is a synthentic ILC.EXE conversion of the managed test assembly creating a native console win32 app.  So, `IsWinRT` would work in uap test runs (UWP F5) but not uap-aot test runs (UWP ILC).

We also have PlatformDetection.IsNotOneCoreUap but that seems to check for the existence of httpapi.sys which is weird....that really is a SKU check and not a runtime check of the type of the application.

We need a PlatformDetection.IsUAP that works reliably for UAP or UAP-AOT test runs.  Do we have something to address this?

cc: @weshaggard @AlexGhiondea @danmosemsft @stephentoub

**Comment by davidsh** [comment]
cc: @ViktorHofer

**Comment by ViktorHofer** [comment]
> But I've heard that uap-aot testing doesn't actually run as app-container.

Correct, but it is planned to run inside an AppContainer. Discussion is still ongoing.

> It is a synthentic ILC.EXE conversion of the managed test assembly creating a native console win32 app

Interesting not mention, it also merges all referenced assemblies together, so the generated output is only one big (native) exe.

> So, IsWinRT would work in uap test runs (UWP F5) but not uap-aot test runs (UWP ILC).

Currently correct, yes! I haven't yet seen a lot cases where we need to differentiate between uapaot and uap. As I said above, uapaot will in future also run inside an AppContainer, because we need to test it the same way as the customer will be using it (at least with a compiler switch). In regards to UWP we spoke about two modes: Debug (uap with coreclr) and Release (uap with ahead of time compilation --> uapaot). Debug mode could be used in enterprise environments where apps won't be submitted to the store and shouldn't be compiled to native code. 
The only case which I have in my mind is Assembly.Load which is currently not supported in uapaot but could be supported in uap (https://github.com/dotnet/coreclr/issues/9912#issuecomment-302152460). Long story short, even though we don't have a lot of cases where we need to differentiate, we at least have one therefore I think your suggestion to introduce `PlatformDetection.IsUAP` makes sense. Sidenote: we already have `PlatformDetection.IsNetNative` for uapaot.

**Comment by davidsh** [comment]
>Long story short, even though we don't have a lot of cases where we need to differentiate, we at least have one therefore I think your suggestion to introduce `PlatformDetection.IsUAP` makes sense. Sidenote: we already have `PlatformDetection.IsNetNative` for uapaot.


Perhaps we can implement a `PlatformDetection.IsUAP` being basically equivalent to `PlatformDetection.IsWinRT` or `PlatformDetection.IsNetNative'.

**Comment by davidsh** [comment]
cc: @CIPop
