### ISSUE TITLE
Reenable the tests ActiveIssue'd on 19909 this in Uap (not UapAot)

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#19909]
```
System.IO.MemoryMappedFiles.Tests -method System.IO.MemoryMappedFiles.Tests.DataShared

System.Net.Primitives.Functional.Tests -method System.Net.Primitives.Functional.Tests.EventSource_EventsRaisedAsExpected

System.Net.Security.Tests -method System.Net.Security.Tests.EventSource_EventsRaisedAsExpected
```

These tests are ActiveIssue'd against this issue but for Uap, not UapAot. Chances are they were intended to be ActiveIssued against some other process-related issue that prevents them from running in UWP (non-AOT) but since we've fix the aot-related issues, zombie'ing this issue to track reenabling these two tests.

**Comment by davidsh** [comment]
cc: @ViktorHofer 

This is a known issue and there is discussion on other issues about ways to solve this.

**Comment by AtsushiKan** [comment]
If there's an existing issue, please let me know. I just need an issue # in order to put into some ActiveAttribute annotations.

**Comment by ViktorHofer** [comment]
We have an offline discussion going on where I will cc you.

**Comment by safern** [comment]
This also causes that `Process.Start` returns null as a the started process.

**Comment by AtsushiKan** [comment]
```
System.IO.MemoryMappedFiles.Tests -method System.IO.MemoryMappedFiles.Tests.DataShared

System.Net.Primitives.Functional.Tests -method System.Net.Primitives.Functional.Tests.EventSource_EventsRaisedAsExpected

```

These two tests are ActiveIssue'd against this issue but for Uap, not UapAot. Chances are they were intended to be ActiveIssued against some other process-related issue that prevents them from running in UWP (non-AOT) but since we've fix the aot-related issues, zombie'ing this issue to track reenabling these two tests.

**Comment by davidsh** [comment]
>These two tests are ActiveIssue'd against this issue but for Uap, not UapAot. Chances are they were intended to be ActiveIssued against some other process-related issue that prevents them from running in UWP (non-AOT) but since we've fix the aot-related issues, zombie'ing this issue to track reenabling these two tests.

Regarding the System.Net.Primitives test:

>System.Net.Primitives.Functional.Tests -method System.Net.Primitives.Functional.Tests.EventSource_EventsRaisedAsExpected

That was disabled because the RemoteExecutor did not work in UWP F5 test runs.  It also appeared to not work in UAPAOT test runs as well.

Has it been fixed for UAP test runs?  That test runner uses a real app-container Windows Store App.  @tarekgh  can you comment on that?

**Comment by tarekgh** [comment]
for remote execution in F5 scenario, we have the needed changes ready but not enabled yet because we are waiting to have Helix runs upgrade to run against RS2 (as this is the requirements to have the remote execution work). 

https://github.com/dotnet/corefx/pull/20719 is the revert of enabling this which we need to return back this change when Helix have RS2 images. 

I am wondering why the test is failing on UAPAOT? we are not running inside app containers there so I expect this shouldn't fail. did you look at it?

**Comment by davidsh** [comment]
>I am wondering why the test is failing on UAPAOT? we are not running inside app containers there so I expect this shouldn't fail. did you look at it?

In general, when we set TargetFrameworkMonikers.Uap, it also includes UapAot as well, where-as UapAot is just UapAot.  Our team was first focusing on UWP F5 test passes and not UWP ILC test passes.  We really just used this issue number as a convenience to disable the Uap tests.  Since TargetFrameworkMoniker.Uap includes both uap and uapaot (which is ok and @safern made that tooling change), it ends up disabling the test for both uap and uapaot test runs.  We will enable our System.Net.* tests for RemoteExecutor once it works on both uap and uapaot.

**Comment by tarekgh** [comment]
I talked offline to @safern and I think it make sense to have different TargetFrameworkMoniker for uap and uapaot so we can avoid disabling the test in one platform cause the test be disabled on the other.

CC @danmosemsft

**Comment by safern** [comment]
Yes we should definitely add this TargetFrameworkMoniker to include both uap and aot and have the originals (uap and uapaot) to behave as they did. If @danmosemsft agrees I can do that change and just replace whatever we have now as Uap to be that new moniker and then we can start reenabling tests on the go for either uap or aot (as it is needed in this issue).

**Comment by davidsh** [comment]
>I talked offline to @safern and I think it make sense to have different TargetFrameworkMoniker for uap and uapaot so we can avoid disabling the test in one platform cause the test be disabled on the other.

Perhaps we can do that but for most things in our codebase, for example, when we ifdef code for "UAP", we mean both uap and uapaot because that is how the source code is compiled.  The whole AOT stuff happens after compilation.  So in the minds of developers when they work on source code for Windows Store App focused packages, "uap" means both uap and uapaot.

**Comment by safern** [comment]
> when we ifdef code for "UAP", we mean both uap and uapaot because that is how the source code is compiled. The whole AOT stuff happens after compilation. So in the minds of developers when they work on source code for Windows Store App focused packages, "uap" means both uap and uapaot.

That is a good point, I think that was the initial idea of disabling both for when disabling for Uap.

**Comment by danmosemsft** [comment]
I agree with @davidsh...it is good to match the target group and define behavior.
What about creating a new one named like UapNotUapAOt for those that need it.

**Comment by tarekgh** [comment]
I think we can have UapNoAot and UapWithAot and then 
```
Uap = UapNoAot | UapWithAot
```

doing that will address all the concerns here

**Comment by danmosemsft** [comment]
@safern I guess we have this and you can clean this up now?

**Comment by safern** [comment]
> @safern I guess we have this and you can clean this up now?

Yes we can now use the new TFM you added. I will do that clean up.
