### ISSUE TITLE
System.Net.Http package doesn't target 4.5.x TFMs in latest build

### ISSUE THREAD

**Issue by aggieben** [dotnet/corefx#1994]
I'm using System.Net.Http-4.0.0-beta-23008 (afaik, the latest) and the TFMs in the package are "DNXCore50", "netcore50", and "net46".  `lib/net46` directory in the latest package contains nothing but a `_._` empty file.

Should there be a TFM for `dnx451` or similar?

**Comment by SidharthNabar** [comment]
Hi @aggieben - I think this is a known issue and folks are working on it. @ericstj - Can you please confirm?

**Comment by ericstj** [comment]
23008 should have different folders, are you sure you are looking at https://www.myget.org/F/dotnet-core/api/v2/package/System.Net.Http/4.0.0-beta-23008?

We actually recently fixed up all the packages to better support downlevel platforms.  Let me give you a walkthrough of this one.  We had a bug here that is being fixed in today's build, which I'll outline below.

ref\any\System.Net.Http.dll
 - the reference assembly, used when it is not part of the targeting pack

ref\net45\_._
 - the reference assembly is already part of the targeting pack for net46 and onward, instead we have a frameworkAssembly entry in the nuspec to add a reference to the assembly from the targeting pack.

ref\win8\_._
 - the reference assembly is already part of the targeting pack and added automatically to all projects.

ref\netcore50\System.Net.Http.dll **missing**
- we needed to add this reference assembly since netcore50 is OOB and doesn't have a targeting pack but is compatible with win8.  **Today's build (23011) will have this fix**, @jhendrixMSFT will push to myget shortly once the build completes.

lib\DNXCore50\System.Net.Http.dll
 - the DNX core implementation of HttpClient that builds on WinHTTP

lib\net45\_._
 - no implementation is needed since it is part of the inbox framework

lib\netcore50\System.Net.Http.dll
 - the NET core implementation of HttpClient that builds on WinINET via Windows.Web.Http

lib\win8\_._
 - no implementation is needed since it is part of the inbox framework

**Comment by davidsh** [comment]
@ericstj Why is there both a "lib\DNXCore50\System.Net.Http.dll" and "lib\netcore50\System.Net.Http.dll" but only a "ref\netcore50\System.Net.Http.dll"?  Shouldn't there be a "ref\DNXCore50\System.Net.Http.dll"?  It is true that the API surface is the same.  But I don't understand why it doesn't exist.

**Comment by jhendrixMSFT** [comment]
Just FYI the 23011.00 build has been pushed to the dotnet-core feed.

**Comment by ericstj** [comment]
@davidsh ref\netcore50\System.Net.Http.dll  is needed to override ref\win8\_._.
DNXCore gets ref\any\System.Net.Http.dll.

**Comment by ericstj** [comment]
With the new 23011.00 you'll see that 'any' becomes 'dotnet' but it effectively behaves the same for the TFMs we are discussing here.

**Comment by aggieben** [comment]
@SidharthNabar yep, I'm looking at 23008.  @ericstj I'm not sure this bug is the cause of the problems I've experienced.  Here's what's in the package:

```
C:\Users\Benjamin\.dnx\packages\System.Net.Http\4.0.0-beta-23008> gci -rec | select -ExpandProperty Fullname
C:\Users\Benjamin\.dnx\packages\System.Net.Http\4.0.0-beta-23008\lib
C:\Users\Benjamin\.dnx\packages\System.Net.Http\4.0.0-beta-23008\ref
C:\Users\Benjamin\.dnx\packages\System.Net.Http\4.0.0-beta-23008\System.Net.Http.4.0.0-beta-23008.nupkg
C:\Users\Benjamin\.dnx\packages\System.Net.Http\4.0.0-beta-23008\System.Net.Http.4.0.0-beta-23008.nupkg.sha512
C:\Users\Benjamin\.dnx\packages\System.Net.Http\4.0.0-beta-23008\System.Net.Http.nuspec
C:\Users\Benjamin\.dnx\packages\System.Net.Http\4.0.0-beta-23008\lib\DNXCore50
C:\Users\Benjamin\.dnx\packages\System.Net.Http\4.0.0-beta-23008\lib\net46
C:\Users\Benjamin\.dnx\packages\System.Net.Http\4.0.0-beta-23008\lib\netcore50
C:\Users\Benjamin\.dnx\packages\System.Net.Http\4.0.0-beta-23008\lib\DNXCore50\System.Net.Http.dll
C:\Users\Benjamin\.dnx\packages\System.Net.Http\4.0.0-beta-23008\lib\net46\_._
C:\Users\Benjamin\.dnx\packages\System.Net.Http\4.0.0-beta-23008\lib\netcore50\System.Net.Http.dll
C:\Users\Benjamin\.dnx\packages\System.Net.Http\4.0.0-beta-23008\ref\any
C:\Users\Benjamin\.dnx\packages\System.Net.Http\4.0.0-beta-23008\ref\net46
C:\Users\Benjamin\.dnx\packages\System.Net.Http\4.0.0-beta-23008\ref\any\System.Net.Http.dll
C:\Users\Benjamin\.dnx\packages\System.Net.Http\4.0.0-beta-23008\ref\net46\_._
```

It did occur to me though that I should be able to reference `System.Net.Http` for `dnx45x` TFMs without a dependency on this package, so I tried adding a `frameworkAssembly` reference in my `project.json`, and I still wind up with errors like so:

```
C:\Users\Benjamin\Projects\TR\TrinityRepublic.Framework\src\TrinityRepublic.Framework\Net\Http\UriBuilderExtensions.cs(7,23): error CS0246: The type or namespace name 'UriBuilder' could not be found (are you missing a using directive or an assembly reference?)
```

Although I *should* be able to take a dependency on this package even for the 45x targets, right?

**Comment by ericstj** [comment]
Ok, that's the version from https://www.myget.org/gallery/aspnetrelease.  That is lagging behind https://www.myget.org/gallery/dotnet-core.  Try the version from dotnet-core.

For the UriBuilder error you need a reference to System.Runtime.Extensions, or if you are targeting a desktop profile (net* or dnx4|5*) you can add a frameworkRefernce to System.

**Comment by aggieben** [comment]
All my packages are coming from https://www.myget.org/gallery/aspnetvnext which has v4.0.0-beta-23008 as of 2 days ago.  I'm not sure what the version on the aspnetrelease feed is, but it looks *way* out of date (and I don't use that feed anyway).

I'm confused, though: why would a reference to `System.Runtime.Extensions` help, and why can't I just reference `System.Net.Http` directly?

**Comment by ericstj** [comment]
You can reference System.Net.Http directly, but you need to use the new package.  https://www.myget.org/gallery/aspnetvnext is behind https://www.myget.org/gallery/dotnet-core as well. @danroth27 can tell you when the aspnet feed will be updated, but as it stands that package has a bug when consumed on net45/dnx45.

The reason why the reference to System.Runtime.Extensions will help is because that is where UriBuilder lives.  You added a direct reference to the framework assembly System.Net.Http.  That is just an assembly (not a package) so DNX/nuget can't see any of its dependencies.  That's why the compiler complains that it can't find UriBuilder.  Adding a reference to system.dll (via framework assembly ref) or System.Runtime.Extensions (via package ref) will fix this problem.  Neither of these are required if you are using the new package ref for System.Net.Http which should be fixed.

**Comment by aggieben** [comment]
Ok - I fully understand what you said about the framework assemblies; thanks for that.  I'm still confused about how the System.Runtime.Extensions package works, though.  I realize you have no obligation to educate me about this, but how does `UriBuilder` "live" in `System.Runtime.Extensions`?  In the sources, `UriBuilder` is in `System.Private.Uri` and nowhere else.  I can't tell in the sources for `System.Runtime.Extensions` that there are any external references to sources, or even any reference to a runtime other than CoreCLR.

**Comment by davidsh** [comment]
The UriBuilder class is defined as part of the System.Runtime.Extensions "contract".  As such the System.Runtime.Extensions dll (binary) is really a façade and just forwards the calls to the actual implementation binary, System.Private.Uri.dll.   We have many instances of type forwarding from a façade dll to the implementation dll.   For example, currently many of the System.Net types are in implemented in the System.Private.Networking.dll even though the types are "defined" in the facades such as System.Net.Primitives, System.Net.Sockets, etc.

**Comment by aggieben** [comment]
Ok, cool - I get the idea of contract assemblies and figured that might be what was going on here, but I wasn't seeing evidence of anything in Reflector, which might just be an artifact of Reflector (or my misconfiguration/mis-use of it, anyway).  

If I might, I have another related and probably dumb couple of questions: 

1. what is the purpose in the two folders in the package containing the assemblies?  As shown in my paste of console output above, there is the `ref\any\System.Net.Http.dll`, but also `lib\DNXCore50\System.Net.Http.dll` and `lib\netcore50\System.Net.Http.dll`.  Are assemblies in `ref` reference assemblies?  If so, then why do you need both reference assemblies *and* `lib` (or vice versa)?

2. What is the purpose of the `_._` files where one might expect to see assemblies?

**Comment by ericstj** [comment]
1. Reference assemblies are used at compile time, they represent the surface area of the package.  We use a common reference assembly to enable both portable libraries and 3rd party extensibility.  
  * PCL in the new world works using guardrails https://github.com/NuGet/NuGet3/pull/40.  Essentially a package exposes common surface area and nuget "hit-tests" all the supported platforms to make sure it is supported on those platforms.  
  * 3rd party extensibility works with a runtime.json in a nuget package that can permit someone to say that whenever System.Net.Http is installed, and you're targeting a runtime with identifier, say, "microsoft_bob_x86", use bobs.System.Net.Http : 4.0.59.  This allows someone to extend our packages by implementing the common surface area on new platforms.
Libs are used at runtime and can be specific to a target-framework/runtime.

2. The _._ is a placeholder.  As I mentioned previously this is meant to indicate to nuget that the particular target is supported, but the asset comes from somewhere else.  For ref, that somewhere else is usually a targeting pack.  For lib it's usually a system wide location for a non app-local framework (eg: GAC).

**Comment by stephentoub** [comment]
> I wasn't seeing evidence of anything in Reflector

Try looking at the assembly-level attributes; you'll hopefully see something like this:
```C#
[assembly: TypeForwardedTo(typeof(UriBuilder))]
```

**Comment by aggieben** [comment]
@ericstj perfect, thank you.  @stephentoub I'm not finding it along with the other assembly attributes, although I'll take your word for it and keep fishing around.

**Comment by aggieben** [comment]
I've updated to `System.Net.Http-beta-23011`, but things are still breaking, and now they're breaking for both `dnx451` and `dnxcore50`.  For the net/dnx45 side of things, see #2059.  On core50, the `System.Private.Uri` package goes unresolved, seemingly because there is no target for core50 in the package:

![image](https://cloud.githubusercontent.com/assets/1321/8172843/db5d0056-138a-11e5-8803-b95921e4510c.png)

Interpreting from your earlier comments, it seems that net/dnxcore50 are _intended_ to be supported:

![image](https://cloud.githubusercontent.com/assets/1321/8172886/4a862a34-138b-11e5-8c05-4c90e0885d2e.png)

If the `_._` filename is a placeholder indicating that the reference assembly should be found elsewhere, where should it be found in this case?

**Comment by ericstj** [comment]
The placeholder '_._' in the ref folder for the System.Private.* packages means that these are implementation only and do not provide any surface area to compile against.

How are things breaking for you?  As I mentioned above it is intentional that System.Private.Uri and System.Private.Networking do not provide compile time assets, so the screenshots look correct.  DNX will locate these assemblies at runtime and load them.  If not, you'd see a FileNotFoundException at runtime.

The latest packages with a recent build of DNX restore fine for me and produce the correct results in the .lock.json.  Please let me know specifically what is failing for you and I can help.

**Comment by aggieben** [comment]
As typically the case when what looks like a problem to me doesn't look like a problem to you, it's a case of the problem being between the keyboard and chair.  The symptom I was experiencing was a failure to find the type `UriBuilder`, and referencing `System.Runtime.Extensions` was the answer, just as pointed out earlier on.
