### ISSUE TITLE
System.Net.* marked as ConditionalFact/Theory tests fail in Desktop 

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#19967]
These tests are currently not running for Desktop in Helix/CI/Jenkins due to: https://github.com/xunit/xunit/issues/1291 in our side we are tracking this with https://github.com/dotnet/corefx/issues/18483

Affected projects:
* `System.Net.WebSockets.Client.Tests`
* `System.Net.HttpListener.Tests`

I currently have a fix out for this that needs to go in on Xunit's repo, be published to nuget, and then we can consume it. (https://github.com/xunit/xunit/pull/1292)

However there is a way to execute this tests on the meantime:

Download: https://1drv.ms/u/s!AmGrqT8fQnxGryZOE1E5KSce4WwT

build corefx from root for netfx (`build.cmd -framework:netfx`)

Move the dlls that are inside the .zip that you download (Debug or Release) to corefx\bin\testhost\netfx-BuildConfiguration\ and corefx\bin\runtime\netfx-BuildConfiguration\ 

Then run the test project with `/p:TargetGroup=netfx`

Pointing this out as we should at least take a look at the failures to see if there is concerning reason why they are failing. i.e Compat Issue. 

cc: @davidsh @CIPop @danmosemsft @stephentoub 

FYI: @hughbe

**Comment by safern** [comment]
cc: @karelz

**Comment by karelz** [comment]
Is it a problem in rel/2.0.0 branch? Or just master?

**Comment by karelz** [comment]
Assigning to you @safern as you work on it

cc @Priya91 @geoffkizer @wfurt

**Comment by safern** [comment]
> Is it a problem in rel/2.0.0 branch? Or just master?

It depends on why we are getting those failures. I will have to take a look at the failures to see if it is a rel/2.0.0 problem. 

I'll give an update once I've done the failures investigation.

**Comment by karelz** [comment]
Thanks!

**Comment by safern** [comment]
So the fix for [ConditonalFact/Theory] was merged today on buildtools: https://github.com/dotnet/buildtools/pull/1507 in order to consume the new version I will have to disable this tests and all the failing in other areas so that we can catch new tests failures on CI/Helix, after I'm done disabling tests and new buildtools are consumed in corefx I can investigate the failures.

**Comment by hughbe** [comment]
Heads up - can I grab the HttpListener failures?

**Comment by karelz** [comment]
I don't see why not - I let @safern confirm though.

**Comment by safern** [comment]
Assigned to you @hughbe

**Comment by safern** [comment]
@hughbe a simpler way to run this tests locally until I merge the fix is to change `<XunitNetcoreExtensionsVersion>` version inside dependencies.props ([see it here](https://github.com/dotnet/corefx/blob/master/dependencies.props#L42)) to: `1.0.1-prerelease-01622-05`

I should be opening a PR soon to update them with the last tests to disable in order to be able to consume the new Xunit.Netcore.Extensions

**Comment by karelz** [comment]
@schen381 can you please look at `System.Net.WebSockets.Client.Tests` failures?

@hughbe I assume `HttpListener` part is done, right? (given how many bugs you filed against it ;))

**Comment by schen381** [comment]
Finished investigation for `System.Net.WebSockets.Client.Tests` failures. I think the fix could be done in 2.1 or future.

Issue 1: https://github.com/dotnet/corefx/pull/20145/files#diff-7aa69802a8cce1ee13af0ddf6044342bR167
Test bug, should await first ReceiveAsync() finish, then do second ReceiveAsync().

Issue 2: https://github.com/dotnet/corefx/pull/20145/files#diff-142a110ba6941456cc5d5b7c34ab6b58R37 
Solution: skip on .net framework
Reason: Different implementation between core (https://github.com/dotnet/corefx/blob/master/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/ClientWebSocketOptions.cs#L168 ) and desktop (https://github.com/Microsoft/referencesource/blob/master/System/net/System/Net/WebSockets/WebSocketHelpers.cs#L471 ). Have discussed offline, should write separate test for desktop, UWP, etc. Move to future. https://github.com/dotnet/corefx/issues/20358

Issue 3: https://github.com/dotnet/corefx/pull/20145/files#diff-969dcec6580549a9c8b042f8a60be448L262
This is a new test case for .Net Core. See more here: https://github.com/dotnet/corefx/issues/20362

Issue 4: https://github.com/dotnet/corefx/pull/20145/files#diff-4cd310b8b5b02b2d0bb05a32b224cfc2R32 
New test. We did have similar test before, but never tested on ex.Message. 
In framework, status 101 is the first case to throw, and has error message 1: https://github.com/Microsoft/referencesource/blob/master/System/net/System/Net/WebSockets/ClientWebSocket.cs#L265 
In core, status 101 is the third case to throw, and has error message 2 (a different error message): https://github.com/dotnet/corefx/blob/master/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs#L325 
Need to change implementations on all platforms, and make sure that no other tests are failing because of the change. https://github.com/dotnet/corefx/issues/20360

Issue 5:  https://github.com/dotnet/corefx/pull/20145/files#diff-4cd310b8b5b02b2d0bb05a32b224cfc2R101 
In framework, we use set to set the value, (and set will check value for us): https://github.com/Microsoft/referencesource/blob/master/System/net/System/Net/WebSockets/ClientWebSocket.cs#L429
In net core, we also have set, and it will check value for us as well. Problem is, we choose a different way to set value (not using set() ): https://github.com/dotnet/corefx/blob/master/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/ClientWebSocketOptions.cs#L42
It has comment that “WebHeaderCollection performs validation of headerName/headerValue.” It didn't do the validation.

cc: @karelz

**Comment by karelz** [comment]
Thanks @schen381!
@CIPop @stephentoub @geoffkizer can one of you please double check @schen381's proposal to push it into 2.1 from area expert point of view? (I don't have enough context to make a good call here)

@schen381 if you already discussed it with @CIPop offline, please say so and we can save @stephentoub and @geoffkizer time looking at it. Thanks!

**Comment by schen381** [comment]
I didn't confirm with Cristian, and I need are expert's confirmation. @karelz

**Comment by karelz** [comment]
Triage: The PR above has 2 parts:
1. Product fix - add validation of invalid header values. Impact on customers is low: Only development scenario. Not worth fixing in 2.0.
2. Test fixes - Only 1 test added, the rest have known active issues. Not worth 2.0 port.

**Comment by karelz** [comment]
Everything worth tracking except `System.Net.HttpListener.Tests` has it's own issue or is fixed in PR #20376.

@schen381 please file new issue for investigating `System.Net.HttpListener.Tests` and update the ActiveIssue attributes for those disabled against this one. We can then close this issue.

**Comment by schen381** [comment]
All disabled tests for `System.Net.HttpListener.Tests` have been fixed, no new issue needed.

To track disabled tests for `System.Net.WebSockets.Client.Tests`, see: #20358 #20362 #20360 

cc: @karelz
