### ISSUE TITLE
[Managed bug] Adding the prefix "http://192./" should fail

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#19986]
Following tests are disabled with this change:

- Add_InvalidPrefix_ThrowsHttpListenerException_Windows

**Comment by Priya91** [comment]
Investigated this a bit, on Unix, httplistener is trying to resolve the hostname to a valid ipadress, if it can't then it uses IPAddress.Any [here](https://github.com/dotnet/corefx/blob/master/src/System.Net.HttpListener/src/System/Net/Managed/HttpEndPointManager.cs#L132). On windows, the native httpapi throws "errorcode 50, request is not supported." The windows behavior is inconsistent in that, when using an unknown host that's not in dns record, like ```http://{Guid.NewGuid().ToString("N"}/``` it adds this prefix successfully, listening to IPAddress.Any, whereas ````http://192./```, ```http://192.255.255.255/``` case fails. On Unix, we are not able to differentiate between these cases, as the ```Dns.GetHostEntry``` throws ```SocketException````, hostnotfound error for both cases, and we handle this as listen to IPAddress.Any. 

We can make the decision to either throw for all unresolved hostnames or make it listen to IPAddress.Any. But applying rules to which set of unresolved hosts to accept and ignore is beyond the scope of the Dns apis. I would prefer to throw in all cases, rather than listen to IPAddress.Any, to match windows behavior, as uwp will also use managed implementation, and hence get same behavior as windows.

**Comment by Priya91** [comment]
fixed in #19955

**Comment by karelz** [comment]
We need to port it into rel/2.0.0 branch

**Comment by stephentoub** [comment]
Closing and replacing by https://github.com/dotnet/corefx/issues/20060.
