### ISSUE TITLE
Add option for building corefx in deterministic mode

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/corefx#2003]
Roslyn will support compiling in [deterministic mode](https://github.com/dotnet/roslyn/issues/372) where same inputs generate same outputs. There should be an option of building corefx in this mode.

Note: this depends on the deterministic build feature being implemented in Roslyn, there's nothing actionable for corefx for now, but I wanted to have something to track :)

**Comment by weshaggard** [comment]
@akoeplinger I didn't realize you already filed this issue long ago. I created #7261 to track similar functionality. I closed that one and I'm going to copy the extra content here:

We need to enable /deterministic flag for the compiler and work through any other tools that cause the builds to not be deterministic.

See https://github.com/dotnet/roslyn/blob/master/build/scripts/test-determinism.ps1 for how Roslyn tests this.

**Comment by karelz** [comment]
Next step: Flip the bit and see what breaks, and we need list of things that depend on time/date (version.c analogy).

**Comment by KirillOsenkov** [comment]
@karelz  missing .pdb and rebuilding a single .dll in debug to remove optimizations.

Also tooling like SourceBrowser really loves determinism because there’s less changes on every reindex (it’s heavily incremental, massive data upload to Azure).

Also for Symbol cache (less symbol downloading due to more cache hits). It hurts me a lot with Desktop framework because it’s not deterministic and every time we ship an update it invalidates the symbols cache.

**Comment by karelz** [comment]
Sounds reasonable, thanks for the list.
@wtgodbe can you please prioritize it after the top must-haves in Infrastructure backlog?

@danmosemsft @joshfree are you supportive?

**Comment by KirillOsenkov** [comment]
@karelz forgot about MEF cache invalidation!

Imagine your app uses MEF, so every update of CoreFX it would invalidate the cache even if the app disn’t change.

**Comment by danmosemsft** [comment]
It's a good idea, if it's feasible (given corefx build has so many steps that do things like rewrite outputs)

**Comment by ericstj** [comment]
Latest script is here: https://github.com/dotnet/roslyn/blob/162ab0213cc3e2be73117c564bd2e6d362ba1492/eng/test-determinism.ps1

I think we can do this now. I wonder how determinism and ILLinker interact: does ILLinker deterministically link?  Does it reset the MVID so that pre-linked and post-linked assemblies have different PDBs.  Just a thought on what we might want to look for when enabling this.

**Comment by weshaggard** [comment]
It would be awesome if we can do this now. The IL rewriters were always one of our big problems but also the versioning is another issue we have to solve to make our builds deterministic, especially if the goal is to build the same sha multiple times at different points in time because our build version numbering is based on date.
