### ISSUE TITLE
HttpWebRequest.ReadWriteTimeout property returns NotImplemented

### ISSUE THREAD

**Issue by RickStrahl** [dotnet/corefx#20043]
Looks like HttpWebRequest.ReadWriteTimeout throws a NotImplemented exception.
Also HttpWebRequest.ConnectionGroupName

Expected:
Either work with expected behavior, or remove from NET Core altogether as this will result in an unexpected runtime error.

**Comment by davidsh** [comment]
There is no ReadWriteTimeout on The System.Net.WebRequest class.

Can you provide a link to the source code in question in .NET Core?

**Comment by davidsh** [comment]
Perhaps you meant the "Timeout" property in WebRequest.  
https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/src/System/Net/WebRequest.cs#L469

The WebRequest class is an abstract class and many of the properties are virtual and aren't implemented in this base class.

The behavior is the same on .NET Framework:
https://github.com/Microsoft/referencesource/blob/master/System/net/System/Net/WebRequest.cs#L794

**Comment by RickStrahl** [comment]
Sorry HttpWebRequest... updated the title to reflect.

https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.readwritetimeout?view=netframework-4.7#System_Net_HttpWebRequest_ReadWriteTimeout

Here's what I see when debugging through:

![image](https://cloud.githubusercontent.com/assets/1374013/26280877/4872332a-3d99-11e7-98f2-678470b0d063.png)

This code compiles in both .NET 4.5 and netcoreapp2.0, but gives the not implemented exception on Core.

**Comment by davidsh** [comment]
Thanks for clarifying.  Yes, I can see that in .NET Core it is currently left as NotImplemented which is different than .NET Framework.

@ViktorHofer Do you know why your prior PRs for HttpWebRequest (#19118) did not fix this?

**Comment by ViktorHofer** [comment]
Not sure. I'm definitely surprised. Will take a look later today.

**Comment by stephentoub** [comment]
It looks like HttpWebRequest.ConnectionGroupName also throws a NotImplementedException?  That should probably be addressed as well, though I expect it's less impactful.

**Comment by ViktorHofer** [comment]
> Do you know why your prior PRs for HttpWebRequest (#19118) did not fix this?

Sorry I had to take one day off. Yes the reason is this:
`throw NotImplemented.ByDesignWithMessage(SR.net_PropertyNotImplementedException);`
I supposed we aren't implementing the property correctly because of the `NotImplemented.ByDesignWithMessage` call. So I guess this should be implemented?

**Comment by ViktorHofer** [comment]
> It looks like HttpWebRequest.ConnectionGroupName also throws a NotImplementedException? That should probably be addressed as well, though I expect it's less impactful.

Same reason as ReadWriteTimeout.

**Comment by ViktorHofer** [comment]
@davidsh @stephentoub We are using a HttpClient in HttpWebRequest which doesn't give us access to the request stream, therefore we can't set the Read and Write properties: https://referencesource.microsoft.com/#System/net/System/Net/HttpWebRequest.cs,3343

How should we proceed? I noticed that WebRequestHandler would have the necessary properties, but that type isn't ported yet to core: https://apisof.net/catalog/System.Net.Http.WebRequestHandler.ReadWriteTimeout

**Comment by ViktorHofer** [comment]
Same applies to ConnectionGroupName. We can't use this property with the current HttpClient impl. Should we make it a NOP or keep it throwing?

**Comment by davidsh** [comment]
>I noticed that WebRequestHandler would have the necessary properties, but that type isn't ported yet to core: https://apisof.net/catalog/System.Net.Http.WebRequestHandler.ReadWriteTimeout

WebRequestHandler class will never be ported to .NET Core.

**Comment by davidsh** [comment]
>Should we make it a NOP or keep it throwing?

That is a good question and applies generally to properties we can't implement due to architecture differences.

**Comment by RickStrahl** [comment]
NOP is better perhaps with a conditional [Obsolete] based on platform so you can catch this at Compile time. 

So is the behavior of this timeout handled by the `Timeout` property in Core? The only reason to use ReadWriteTimeout was that it was necessary to deal with timeouts properly in older versions.

**Comment by stephentoub** [comment]
> Same applies to ConnectionGroupName

This can just be:
```C#
public override string ConnectionGroupName { get; set; }
```
The implementation will end up ignoring the value, but that's ok.

> We are using a HttpClient in HttpWebRequest which doesn't give us access to the request stream

Well, HttpClient does, but the implementation of HttpWebRequest isn't taking advantage of that, and is instead always buffering the request stream entirely.  From a ReadWriteTimeout perspective, though, that means it'll never timeout, because all requests to it would be satisfied synchronously.  So for the request stream side of things, ReadWriteTimeout could simply be a roundtripping nop and it'd be fine.

The response side is harder.  The right way to implement it would probably be to set the Read/WriteTimeout properties on the response stream if the response stream supports timeouts.  But the response streams used by both have CanTimeout==false, which means that won't actually make a difference in practice (it would "light up" and start working in the future if we ever enabled timeout support).  An alternative approach would be to wrap the response stream in one that added a cancellation token to each read/write, where the token would be canceled after the specified timeout.  That would probably work, but it's also a fair amount of work and would likely add non-trivial overheads on top of the already significant overheads HttpWebRequest has in core.

We should not keep the current behavior of throwing NotImplementedException.  Worst case we should change it to throw PlatformNotSupportedException.  But I'd also be ok in this case just making it a roundtripping nop, i.e. validate the arguments, store the data, return the stored data from the getter, but not actually respect it in terms of actually timing out.  If we feel we need to actually timeout, then we either need to implement timeouts on the response streams used by HttpClient or do the response stream wrapping with cancellation token.

**Comment by davidsh** [comment]
>We should not keep the current behavior of throwing NotImplementedException. Worst case we should change it to throw PlatformNotSupportedException. But I'd also be ok in this case just making it a roundtripping nop, i.e. validate the arguments, store the data, return the stored data from the getter, but not actually respect it in terms of actually timing out. 

I agree we should throw PNSE instead of NIE if we are throwing exceptions.

The question we run into is whether or not we should throw exceptions which can break apps that don't expect the exception.  Being silent (noop) might then lead to getting bugs raised since devs will think it should work.  This problem of deciding what to do impacts several problems we have in HttpClientHandler that can't work on UWP, for example.

So, it would be good to get a general design pattern in place for how to handle this platform differences.

cc: @weshaggard @karelz @CIPop

**Comment by ViktorHofer** [comment]
That's really tough. @stephentoub as you explained thoroughly I think we can't fully satisfy the HttpWebRequest API contract with our current implementation. I would be fine making it a NOP but not 100% happy...

**Comment by RickStrahl** [comment]
An attribute marker that shows a warning at compile time for this sort of thing would be useful so you can catch issues like this before they bite you at runtime especially with code already in production and getting ported.

[Obsolete] based on platform would work but something more specific might be really useful for many other use cases.

**Comment by karelz** [comment]
@RickStrahl we have tooling for that: https://github.com/dotnet/corefx/wiki/ApiCompat

**Comment by ViktorHofer** [comment]
Maybe it's worth to mention that with our current implementation we are also facing the issue that we are creating a dedicated HttpClient instance for each request...

**Comment by karelz** [comment]
And HttpWebRequest is already called out here: https://github.com/terrajobst/platform-compat/blob/master/docs/DE0003.md as legacy API

**Comment by RickStrahl** [comment]
Not sure how that works - doesn't HttpClient on full framework use HttpWebRequest as its implementation? Has that changed?

**Comment by davidsh** [comment]
>doesn't HttpClient on full framework use HttpWebRequest as its implementation?

Yes.  But that architecture is not how it works on .NET Core.

**Comment by danmosemsft** [comment]
@karelz @davidsh just to be explicit, @ViktorHofer can't look at this as he's engaged on a DCR this week.

**Comment by karelz** [comment]
@davidsh can you please help with this fix?
cc @DavidGoll

**Comment by karelz** [comment]
Triage: We agree that both properties should do "noop". Currently we throw for both. Code change is needed.

We should also document it in https://github.com/dotnet/corefx/wiki/ApiCompat (can happen during Escrow)

**Comment by loop-evgeny** [comment]
> being silent (noop) might then lead to getting bugs raised since devs will think it should work.

Yep, this dev thought it should work and raised a bug: https://github.com/dotnet/corefx/issues/34550
