### ISSUE TITLE
SyncRoot and IsSynchronized on X509 collections should be explicitly implemented (private)

### ISSUE THREAD

**Issue by justinvp** [dotnet/corefx#2009]
I noticed that [`X509ChainElementCollection`](https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509ChainElementCollection.cs#L24-L32) and [`X509ExtensionCollection`](https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509ExtensionCollection.cs#L28-L36) implement `ICollection`'s  `SyncRoot` and `IsSynchronized` properties implicitly (public).

These should be explicit (private).

I believe this is a compatible change from a subsetting perspective (between desktop and corefx) as this was done on the Regex collections, for example. Other collections in this assembly, like [`X509CertificateCollection`](https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509CertificateCollection.cs#L43-L54) already implement these properties explicitly (private).

I'd be happy to submit a PR.

cc @bartonjs

**Comment by bartonjs** [comment]
@stephentoub @ellismg This seems reasonable to me, but you guys are more familiar with the API surface change/reduction process.  Thoughts?

**Comment by stephentoub** [comment]
If the contracts haven't previously shipped and we still have time to update them, I'd be fine with that.  @nguerrera?

**Comment by nguerrera** [comment]
:+1:

We still have time and they have not shipped. I agree with the proposal. @sandkum is looking at doing some sweeping cleanup to crypto surface area. I'd hold off on the PR, though, because there are some unfortunate infrastructure issues around keeping the reference assemblies in sync with that infrastructure not yet on GitHub. For adding new API, it's not a problem as it just creates some debt to do some additional work to get them exposed in the reference assemblies, but this is effectively a deletion and that would mean a period of time with broken reference assemblies.
