### ISSUE TITLE
RemoteExecutorConsoleApp is becoming too complex

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#20114]
The [RemoteExecutorConsoleApp](https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs) is becoming too complex and is duplicating a lot of logic from our build generation scripts. Logic like picking the correct runner or setting up the environment or the correct configuration. We should eliminate most of this duplicated logic that we have here and in test.targets and instead generate a RunTest.Remote.cmd/sh (or something like that) that encapsulate the logic for running the remote application for the given platform. Then RemoteExecutorTestBase.cs can simply call run on that cmd or sh script that we generate and we don't have to keep maintaining the logic for figuring out how to run in multiple locations.

cc @stephentoub @ViktorHofer @safern @danmosemsft 

This became pretty clear to me while helping with https://github.com/dotnet/corefx/pull/19232 and the UWP RemoteExecutor issues we are still having.

**Comment by ViktorHofer** [comment]
cc @tarekgh

**Comment by tarekgh** [comment]
Currently I am looking at supporting remote execution for UAP (F5 scenario). and the current design is not going to work there anyway. I am working to get code execute remotely but the logic of RemoteExecutorConsoleApp is not going to work there because it is based on Process while in UAP we'll do kind of package activation (and background tasks). I am still prototyping this so I can tell more details about all problems with have with RemoteExecutorConsoleApp

**Comment by ViktorHofer** [comment]
The uap and uapaot remote executor functionality is integrated in the runner itself. The RemoteExecutorConsoleApp in corefx which builds against netstandard is just doing the minimum necessary stuff. I don't think we need to clean stuff up.

Also related: https://github.com/dotnet/corefx/issues/35761

Closing.
