### ISSUE TITLE
Segregate Networking outer loop tests into their own run

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20121]
The outer loop netcore runs are on the verge of being 100% green excepting networking tests which have some broad reliability issues. In order to focus attention on those, and more easily keep the non-networking tests 100% green, we want to break out the networking tests into their own run and their own badge on Helix.

@karelz to assign...

**Comment by davidsh** [comment]
There are also inner loop networking tests.  Should those be moved also to this new "networking test run"?

**Comment by danmosemsft** [comment]
If any inner loop tests are flaky we should move them to OuterLoop so they don't affect CI. My feeling is that it's not so common to see networking flakiness in innerloop whereas in outerloop it's happening every run. So that's why I suggest we ignore inner loop right now.

**Comment by davidsh** [comment]
We only moved most networking tests to outerloop bcause at the time they were considered "flaky".

If we're going to have a separate system to run networking tests with a separate "badge" to measure it, we should do it via library/contract regardless of inner/outer loop.  So, take library tests for System.Net.Http, System.Net.Requests, System.Net.HttpListener, System.Net.Sockets, etc. and then run them in the separate loop.  That will be the way to really measure this.  And that separate loop should include inner and outer. Eventually, a lot of outer tests can be moved back to inner since they would be running in the separate test run.

cc: @DavidGoll @CIPop @stephentoub

**Comment by danmosemsft** [comment]
All Helix runs as far as I know run both inner and outer loop - there is no run that is only outer loop. So I think this run will be as you describe. There would still be purpose in moving a test to outerloop -- if it is flaky in CI. And of course back -- if it is no longer flaky.

**Comment by CIPop** [comment]
We should ensure we have documented ways to:
- run the tests manually (via msbuild / build)
- run the tests manually via dotnet-bot prior networking PRs are approved

**Comment by karelz** [comment]
The dev workflow and CI will not change. Only Helix.

**Comment by CIPop** [comment]
> The dev workflow and CI will not change. Only Helix.

Thanks for clarifying! Title's confusing... Read "break" as we're going to change their class (code markings) so they are not part of Outerloop anymore.

**Comment by karelz** [comment]
We do not plan to do that unless we can't make Networking tests more stable (which is something we're actively work on).
