### ISSUE TITLE
UWP: System.Net.Sockets

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#20135]
Tracking work for System.Net.Sockets in UWP

**Comment by caesar1995** [comment]
I'm doing the final revision for S.N.Sockets Functional tests, and I have a question. For LoggingTests, I am not able to find an issue to disable it (I was using this epic number before). Since now I need to close this epic, what number should I use?
https://github.com/dotnet/corefx/pull/21019#discussion_r121818578

@davidsh @CIPop

**Comment by CIPop** [comment]
I think it's #20470

**Comment by caesar1995** [comment]
Status update:

- Blocking issues: #20470 #21158 #21391

- Followed the checklist, we are not able to remove dependencies on ContextAwareResult.Uap.cs and CompletionPortHelper.Uap.cs. They are important components for Sockets synchronous completion support.

I will start UWP: System.Net.NetworkInformation work.

**Comment by caesar1995** [comment]
Sorry I made a mistake, CompletionPortHelper.Uap.cs cannot be removed, while ContextAwareResult.Uap.cs can be removed.

Analysis:
For SafeCloseSocket Windows' implementation, we need [CompletionPortHelper.SkipCompletionPortOnSuccess()](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Net/SafeCloseSocket.Windows.cs#L77) to decide whether we need to disable completions for synchronous success. `[CompletionPortHelper.SkipCompletionPortOnSuccess()` is using an api (`Interop.Kernel32.SetFileCompletionNotificationModes`) which has not been approved for UAP yet. That's why we need the PAL for CompletionPortHelper.

While ContextAwareResult.Uap.cs doesn't has this problem and can be removed.

I will submit a PR to correct my mistake.

cc: @CIPop @davidsh @DavidGoll

**Comment by CIPop** [comment]
> SetFileCompletionNotificationModes which has not been approved for UAP yet

@caesar1995 @DavidGoll I believe the synchronous completion mode for Sockets enhancement was added after we had the UAP profile discussions and analyzed the API surface. 
Let's follow-up offline. Ideally we should have the same implementation for both Windows Desktop and UAP.

**Comment by caesar1995** [comment]
I wasn't aware that the API has been approved. 

Last time I built the project without the `CompletionPortHelper.Uap.cs` in UAP mode, the compiler complained that "error: SetFileCompletionNotificationModes() is not supported on UAP". But now the error goes away. I will delete both of the files.

**Comment by DavidGoll** [comment]
@caesar1995 The use of SetFileCompletionNotificationModes was added to the implementation after the API scans, so we did not know we needed it for UAP. That's what @CIPop explained above.
