### ISSUE TITLE
System.Security.Principal.Windows.WellKnownSidTypeTests.CanCreateSecurityIdentifierFromWellKnownSidType fails on Desktop

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#20152]
This test is marked as `[ConditionalTheory]` and we haven't seen a failure because in netfx this test attribute is broken. I have the local fix so I was able to run it and it is failing with error:

```
System.ArgumentException : Value was invalid.
        Parameter name: sidType
        Stack Trace:
             at System.Security.Principal.SecurityIdentifier..ctor(WellKnownSidType sidType, SecurityIdentifier domainSid)
          D:\repos\corefxCopy\corefx\src\System.Security.Principal.Windows\tests\WellKnownSidTypeTests.cs(123,0): at WellKnownSidTypeTests.CanCreateSecurityIdentifierFromWellKnownSidType(WellKnownSidType sidType)
```
Will go ahead and disable it so that we can get the fix for this attributes in Corefx

cc: @steveharter @bartonjs

**Comment by danmosemsft** [comment]
This is because .NET Core has many more entries in WellKnownSidTypes than Desktop does.

http://referencesource.microsoft.com/#mscorlib/system/security/principal/sid.cs,124
http://source.dot.net/#System.Security.Principal.Windows/System/Security/Principal/SID.cs,176

The fix is to change the test or split the test so that we don't pass anything higher than `    [InlineData(WellKnownSidType.WinBuiltinTerminalServerLicenseServersSid)]` to NETFX.

**Comment by safern** [comment]
Sounds good. Will fix it instead of disabling on the PR I have open. Thanks!

**Comment by karelz** [comment]
@safern do we need it for 2.0? There was no milestone ...

**Comment by safern** [comment]
Same as: https://github.com/dotnet/corefx/issues/20154#issuecomment-303570228
