### ISSUE TITLE
Can't add System.Runtime.WindowsRuntime nuget package to .net 4.6.1 project

### ISSUE THREAD

**Issue by v-tbert** [dotnet/corefx#20253]
If you try to add the package, you get the following error:

Could not install package 'System.Runtime.WindowsRuntime 4.3.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by danmosemsft** [comment]
@weshaggard does @v-tbert need to add a nuget reference to netstandard package?

**Comment by weshaggard** [comment]
@ericstj to confirm but this is just a case of a package we don't support on .NET Framework. @v-tbert is there a reason you are trying to use this package on .NET Framework?

**Comment by v-tbert** [comment]
Sort of. I have the System.Runtime.WindowsRuntime package added to a portable library where the win 10 calls live. That was created as an old style PCL project targeting .net 4.6 and win 10. In the project properties I selected the option to switch it to a .net standard 1.4 project which should have the same platform compatibility<https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/>. That all builds fine. I then created a small 4.6.1 console app that references said project, added some calls to it, and attempted to run it. At that point it tells me it can't find System.Runtime.WindowsRuntime.dll as referencing a portable project doesn't seem to include the dependent projects nuget dlls in the build output folder (incidentally breaking with traditional .net project behavior I believe). I then attempted to add the nuget package and got the error I previously mentioned.

I can supply a test solution if it helps illustrate the scenario…

**Comment by v-tbert** [comment]
The package is produced and working on .Net 4.5.1 just fine, so I don't know why this wouldn't be the case for 4.6.1?

**Comment by v-tbert** [comment]
I had some offline discussions with the team and I think the verdict is:

- There is no nuget package for this today as calling the WinRT api from classic .net desktop apps was previously unsupported, though it worked. 

- Support for calling WinRT is coming soon as demonstrated at //BUILD.
 Eventually there will be an easier way, but until such time you can reference the needed .net core assemblies and WinRT winmd files as demonstrated in the video: [https://channel9.msdn.com/Events/Build/2017/B8110](url)

**Comment by ericleigh007** [comment]
Wanted to get a Net Standard library to be callable from UWP and WPF but ultimately had to give up due to this one.  The videos and blogs didn't give me enough info to solve.
The specific API I wanted to use with the AppServiceConnection.SendMessageAsync .  This returns an IASyncOperation, which is (I guess) found in System.Runtime.WindowsRuntime, but seems extremely problematic taking a dependency on that one.

Ultimately had to refactor to add an event to be registered by the app, so the app can do the Send.

I think that calling UWP from WPF is no problem these days, but doing the same from a library isn't working for me.  If there is nothing wrong with the WinRT stuff, then I guess we need some complete and correct working examples. Thx
