### ISSUE TITLE
[HttpListener] [porting] HttpListenerRequest.ContentLength64 can be overriden from Request.Headers but can't be with netfx

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#20294]
Following tests pass with netfx but are disabled for netcoreapp:
```cs
  [ConditionalTheory(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotOneCoreUAP))]
  [InlineData(100)]
  [InlineData("-100")]
  [InlineData("")]
  [InlineData("abc")]
  [InlineData("9223372036854775808")]
  [ActiveIssue(123, TargetFrameworkMonikers.Netcoreapp)]
  public async Task ContentLength_ManuallySetInHeaders_ReturnsExpected(string newValue)
  {
      await GetRequest("POST", null, new string[] { "Content-Length: 1" }, (_, request) =>
      {
          Assert.Equal("1", request.Headers["Content-Length"]);

          request.Headers.Set("Content-Length", newValue);
          Assert.Equal(newValue, request.Headers["Content-Length"]);
          Assert.Equal(1, request.ContentLength64);

          Assert.True(request.HasEntityBody);
      }, content: "\r\n");
  }

  [ConditionalFact(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotOneCoreUAP))]
  [ActiveIssue(123, TargetFrameworkMonikers.Netcoreapp)]
  public async Task ContentLength_ManuallyRemovedFromHeaders_DoesNotAffect()
  {
      await GetRequest("POST", null, new string[] { "Content-Length: 1" }, (_, request) =>
      {
          Assert.Equal("1", request.Headers["Content-Length"]);

          request.Headers.Remove("Content-Length");
          Assert.Equal(1, request.ContentLength64);

          Assert.True(request.HasEntityBody);
      }, content: "\r\n");
  }
```

Looking at referencesource the code is exactly the same give or take some formatting.

**Comment by karelz** [comment]
@CIPop @DavidGoll can you please take a look? What's the impact? 2.0?

**Comment by karelz** [comment]
Triage: @CIPop please assess impact of this one. If it is 2.0, please investigate.

**Comment by CIPop** [comment]
I was able to repro and debug. A difference was introduced during porting: 
- In .Net Framework the code is always calling [HttpApi ](https://github.com/Microsoft/referencesource/blob/90b323fe52bec428fe4bd5f007e9ead6b265d553/System/net/System/Net/HttpListenerRequest.cs#L393)to query the ContentLength header.
- In .Net Core the code is instead referencing the [Headers](https://github.com/dotnet/corefx/blob/f81984bcd0843e05e51a9280573ec67a28fc41f4/src/System.Net.HttpListener/src/System/Net/Windows/HttpListenerRequest.Windows.cs#L164) property instead which doesn't have the same effect.

While nice to have, I don't see this as a critical change for 2.0. Moving to 2.1.

**Comment by karelz** [comment]
Which customer scenarios does it affect? How common they are?

**Comment by CIPop** [comment]
> Which customer scenarios does it affect?

On Desktop apps expect that ContentLength64 returns the original header value regardless of changes to the Headers["Content-Length"] collection element. 
On CoreFX, a change to the Headers collection will change the ContentLength64 value as well.

> How common they are?

I don't think this is common.

**Comment by caesar1995** [comment]
From both [MSDN (.Net Framework)](https://msdn.microsoft.com/en-us/library/system.net.httplistenerrequest.contentlength64(v=vs.113).aspx) and [Microsoft docs (.NetCore)](https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistenerrequest.contentlength64?view=netframework-4.7#System_Net_HttpListenerRequest_ContentLength64) documentations for ContentLength64:

Return value:
> The value from the request's Content-Length header. This value is -1 if the content length is not known.

So I if we `request.Headers.Set("Content-Length", newValue);` to set the Content-Length header to a newValue, I think the value of ContentLength64 should be changed accordingly.

In .NetFramework (As @CIPop has mentioned): ContentLength64 returns the original header value regardless of changes to the Headers["Content-Length"] collection element.
In .NetCore: If we set the `Content-Length` to a valid value, the `ContentLength64 ` will be changed accordingly. Otherwise (set the `Content-Length` to a **_invalid_** value), the `ContentLength64` == 0. (which I think it's incorrect, it should be -1).

@davidsh @CIPop

**Comment by davidsh** [comment]
This documentation link you quote above:

[MSDN (.Net Framework)](https://msdn.microsoft.com/en-us/library/system.net.httplistenerrequest.contentlength64(v=vs.113).aspx) 

takes me to a page about HttpClient and not HttpListener:
![image](https://user-images.githubusercontent.com/7684835/28982769-d162f2e8-790b-11e7-8879-c401ea109d4f.png)

**Comment by davidsh** [comment]
The other thing is that I don't understand what this test rrepresents.  If it is testing the HttpListenerRequest.ContentLength* properties, then those properties are read-only.  They can not be set.  They represent what comes in on the wire from a client.

So, this test as written is really confusing.  Not sure what the bug is here exactly.

**Comment by caesar1995** [comment]
@hughbe Where did you port the tests from?

**Comment by hughbe** [comment]
I wrote them by hand

**Comment by PeterSmithRedmond** [comment]
Recommend close.  I agree with CIPop; it's hard to come up with a customer scenario for changing the content-length64 value from code at all.

**Comment by caesar1995** [comment]
Closing as suggested.
