### ISSUE TITLE
Certificate store issues on OSX

### ISSUE THREAD

**Issue by javiercn** [dotnet/corefx#20324]
Create a self-signed certificate in memory like in:
https://github.com/aspnet/DotNetTools/blob/dev/src/Microsoft.AspNetCore.CertificateGeneration.Task/CertificateManager.cs#L24

When you try to add the certificate to the store, the following exception is thrown:
```
Error Message:
Interop+AppleCrypto+AppleCommonCryptoCryptographicException : User interaction is not allowed.
```
We've seen this happen intermittently, but when it happens on a machine, it reproduces consistently.

**Comment by danroth27** [comment]
@bartonjs @karelz Can you guys take a look? This is blocking our preview2 work in ASP.NET Core

**Comment by karelz** [comment]
Is it a recent regression? Can you identify from which build?

@steveharter can you please help here?

**Comment by steveharter** [comment]
@javiercn does the exception occur in code during the store.Add or store.Close as in here https://github.com/aspnet/DotNetTools/blob/dev/src/Microsoft.AspNetCore.CertificateGeneration.Task/CertificateManager.cs#L74?

**Comment by javiercn** [comment]
It happens when doing store.Add

**Comment by steveharter** [comment]
Are you able to repro the issue? If so I can attempt debugging on my mac.

>> but when it happens on a machine, it reproduces consistently
Perhaps this is an issue with the cert already existing and triggering some sort of warning? Can you do a preemptive store.Remove(cert) first?

FWIW other general areas that have been troublesome in the past w.r.t. certs and stores are disk I\O permissions, file or name collisions, disk full, and user\process permissions.

**Comment by danroth27** [comment]
Unfortunately, this appears to be machine dependent. I was able to add the certificate to my store on my mac without issue.

**Comment by karelz** [comment]
OK, so do we need to do anything here? Is the 'bad' machine config something typical / wide-spread, or is it test-lab specific?

**Comment by bartonjs** [comment]
My guess is this only fails on machines where there isn't a UI session; and something somewhere has manually locked your default keychain (or you've done a password reset which was via `passwd` instead of the UI password change tool).

The documented cases for that error message is that someone called [SecKeychainSetUserInteractionAllowed](https://developer.apple.com/reference/security/1396453-seckeychainsetuserinteractionall?language=objc)(false) (and then later UI needed to pop); but we never use that function in corefx.  So it either starts off as true for a UI login and false for a SSH/cron login, or something outside of corefx code has P/invoked to change the state of the keychain APIs.

But I'm not seeing anything to be done here, if there's not a way for Keychain to pop UI then it can't recover from whatever state your machine is in...

Maybe reboot whatever machine is misbehaving?

**Comment by danmosemsft** [comment]
@karelz we can move this out of 2.0 right?

**Comment by karelz** [comment]
If it is machine specific and OS induced, we should close it / move it to 2.1 or Future.
@bartonjs thoughts? Is anyone still blocked by this?

**Comment by bartonjs** [comment]
There's a possibility that this had something to do with the automatic lock on our temporary keychains, so it could already be fixed.

I'm just going to close this.  If it's still happening, try preview2.  If it's still happening then, reopen the issue, hopefully with a stable repro.

**Comment by natemcmaster** [comment]
FYI - we are still hitting this consistently in 2.0.0 on our CI agents. As suggested above, it appears rebooting the machine can solve the problem, but we're not sure why. Do we have more details why rebooting works? And is there some kind of configuration that we can add to CI agents to avoid this issue permanently?

**Comment by bartonjs** [comment]
Are you adding the certificates to the LocalMachine\My store?  That's backed by `/Library/Keychains/System.keychain`, and on my mac I see

```sh
$ security show-keychain-info /Library/Keychains/System.keychain
Keychain "/Library/Keychains/System.keychain" lock-on-sleep timeout=300s
```

So if the computer has gone to sleep or 300s have elapsed since (whatever Apple considers to be the start of the countdown) that keychain will become readonly.  The solution that Apple has in that case is to pop a cred/consent dialog; but if you're running headless then it can't, so it emits that error.

CurrentUser\My is backed by `~/Library/Keychains/login.keychain-db` (or whatever `security login-keychain` reports), and my keychain reports no timeout and no lock-on-sleep for that one.

**Comment by natemcmaster** [comment]
The failing tests are adding to CurrentUser\My. 

https://github.com/aspnet/DotNetTools/blob/14dcbdb9dd37f3a3d91649c3deb685b77e481709/test/Microsoft.AspNetcore.CertificateGeneration.Task.Tests/GenerateSSLCertificateTaskTest.cs#L206-L210

This is interesting. If I login to the agent via SSH, I get the same error when executing "security show-keychain-info".
 
```
aspnetci-mac:~ asplab$ security show-keychain-info ~/Library/Keychains/login.keychain-db 
security: SecKeychainCopySettings /Users/asplab/Library/Keychains/login.keychain-db: User interaction is not allowed.
```

If I login with "Screen Sharing", I get this:
```
aspnetci-mac:~ asplab$ security show-keychain-info ~/Library/Keychains/login.keychain-db 
Keychain "/Users/asplab/Library/Keychains/login.keychain-db" no-timeout
```

**Comment by natemcmaster** [comment]
We dug into this more and I believe we found the issue.

The problem: SSH session on macOS does not allow GUI interaction. Any process started from an SSH session will not be able to access keychains.

The reason restart fixed it: our CI agent normally starts as a LaunchAgent (not a LaunchDaemon). LaunchAgents start the process in a context that allows GUI interaction. This agent crashed for some reason and a dev on our team restarted the agent process via SSH and `launchctl`. This is when the problems began. By restarting, the CI agent process began from the LaunchAgent with a GUI context. We could have done the same without a reboot by restarting the CI agent process from "Screen Sharing", not SSH.
