### ISSUE TITLE
Exposed Immutable Collections APIs should allow `null` comparers

### ISSUE THREAD

**Issue by sharwell** [dotnet/corefx#2036]
Several immutable collections APIs throw an `ArgumentNullException` if a null `IComparer<T>` or `IEqualityComparer<T>` is provided. This is not intuitive, and deviates from a very common pattern established by the .NET framework. All publicly-exposed API methods in this assembly should be updated to ensure the following:

1. If a null value is provided for `IComparer<T>`, `Comparer<T>.Default` should be used instead.
2. If a null value is provided for `IEqualityComparer<T>`, `EqualityComparer<T>.Default` should be used instead.

**Comment by AArnott** [comment]
This seems like a safe behavioral change to make, since it seems very unlikely to break anyone.
As for the precedent set by the .NET Framework, there are APIs where there are overloads with and without some parameter and if the overload with the parameter is called but with a null value, an exception is thrown. But I agree that's at least inconvenient, and not something we need to emulate.
