### ISSUE TITLE
ClientWebSocket.CloseAsync should match netfx behaviour and throw InvalidOperationException instead of hanging if not connected

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#20393]
```cs
[Fact]
public async Task Test()
{
    const string Prefix = "http://localhost:9200/";
    var server = new HttpListener();
    server.Prefixes.Add(Prefix);
    server.Start();

    var client = new ClientWebSocket();

    var uriBuilder = new UriBuilder(Prefix) { Scheme = "ws" };
    Task<HttpListenerContext> serverContextTask = server.GetContextAsync();

    Task clientConnectTask = client.ConnectAsync(uriBuilder.Uri, CancellationToken.None);
    if (clientConnectTask == await Task.WhenAny(serverContextTask, clientConnectTask))
    {
        await clientConnectTask;
        Assert.True(false, "Client should not have completed prior to server sending response");
    }

    HttpListenerContext context = await serverContextTask;
    HttpListenerWebSocketContext webSocketContext = await context.AcceptWebSocketAsync(null);

    await client.CloseAsync(WebSocketCloseStatus.EndpointUnavailable, "Hello", new CancellationToken());
}
```

Netfx: InvalidOperationException thrown
Netcoreapp: hang, then WinHttpException thrown for timeout

**Comment by karelz** [comment]
Is it Porting vs. Managed implementation?

**Comment by hughbe** [comment]
No, this is a netcoreapp vs netfx issue.
The reason why I didn't mark it as [HttpListener] or [managed] or [porting] is because I don't know if this issue is with ClientWebSocket or HttpListener.

**Comment by hughbe** [comment]
@schen381 you might be interested in this

**Comment by stephentoub** [comment]
This test is faulty.  It has a race condition: the client may not yet be in the Open state by the time CloseAsync is called... if it is, then the test hangs in CloseAsync, and if it's not, then it throws an InvalidOperationException from CloseAsync because at that point the state is still Connecting rather than Open.  If as an experiment you add `await Task.Delay(1000)` before the CloseAsync call, to give the client time to transition from Connecting to Open, you'll see the same behavior on both desktop and core.  I've not investigated to see why the desktop implementation is so much slower in transitioning, but I don't think it's relevant.

**Comment by karelz** [comment]
Should we track fixing the test? Or the test wasn't checked in yet?

**Comment by stephentoub** [comment]
> Should we track fixing the test?

I don't see this issue referenced in code anywhere.

**Comment by karelz** [comment]
I didn't look, I let @hughbe comment.
