### ISSUE TITLE
16.0.8067.2115 breaks <select> Tags in Outlook Add-In Browser Component?! (System.Net.WebClient | System.Windows.Forms.WebBrowser?)

### ISSUE THREAD

**Issue by futureweb** [dotnet/corefx#20448]
Hello

since 16.0.8067.2115 Update the Outlook Add-In-Browser-Component no longer displays \<select> Tags correct. (System.Net.WebClient | System.Windows.Forms.WebBrowser?!?)

With 16.0.7967.2161 it's working without Problems. Reproduced on several Workstation.

Drop Down is simply not shown when a click is executed on the Select Element. But one can select the Drop-Down Elements with the Arrow Keys.

HTML Source Code isn't changed - so I guess it must be a rendering Problem ...

Sample to reproduce: http://demo.ex.ortsinfo.at/tools/test2.php

Any Ideas on that?

Thank you, bye from Austria
Andreas Schnederle-Wagner

Also asked: https://answers.microsoft.com/en-us/msoffice/forum/msoffice_outlook-mso_win10/16080672115-breaks-select-tags-in-outlook-add-in/d9998470-f1bd-4cf6-85aa-ea5519bc9121

**Comment by danmosemsft** [comment]
@futureweb this sounds like a bug in Office? This is the repo for .NET Core framework.

**Comment by karelz** [comment]
Doesn't seem to be problem in .NET Core. Please contact Microsoft Support for Office.

**Comment by futureweb** [comment]
As it's a .NET VB coded Add-In for Outlook I thought this was the right place to ask ... ;-)
Was thinking that "System.Net.WebClient" is the Problem - but since it looks like a rendering Problem it seems like "System.Net.WebClient" is the Problem (or am I wrong here too?) - unfortunately not that experienced in that area ... just need to make the Add-In running again .... ;-)

**Comment by karelz** [comment]
What you describe uses the "full" .NET Framework (also called "Desktop) - see [how to provide feedback](https://github.com/dotnet/corefx#how-to-engage-contribute-and-provide-feedback).

Moreover, from your description and analysis, it is not clear that it is truly problem in .NET and not in Office, the OS or your plugin (e.g. an update might have exposed pre-existing bug in your code - that happens more than one would think). Isolating where the problem is, is the key (costly) work and that does not automatically fall under .NET team (otherwise we would get half of the bugs in all Microsoft products and we would need 100+ developers just analyzing the incoming problems) - you can either contact Microsoft (paid) support, or you can try to isolate a minimal repro which will hint where the regression comes from.

**Comment by futureweb** [comment]
Alright - will contact MS - sorry for bothering you with that! ;-)

**Comment by karelz** [comment]
No worries and thanks!
