### ISSUE TITLE
System.IO.UnmanagedMemoryAccessor throws different exceptions because CoreRT copy is out of date wrt CoreCLR

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#20522]
CoreLib throws wrong exception in this case.

Test failure on UWP ILC:

```
System.IO.Tests.Uma_ReadWriteStructArray.UmaReadWriteStructArray_InvalidParameters [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentOutOfRangeException)
        Actual:   typeof(System.ArgumentException): Argument_NotEnoughBytesToWrite. For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485
        Stack Trace:
           F:\corefx\src\System.IO.UnmanagedMemoryStream\tests\Uma.ReadWriteStructArray.cs(45,0): at System.IO.Tests.Uma_ReadWriteStructArray.<>c__DisplayClass0_0.<UmaReadWriteStructArray_InvalidParameters>b__12()
  xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.
```

**Comment by danmosemsft** [comment]
The test is expecting `throw new ArgumentException(SR.Argument_NotEnoughBytesToWrite, nameof(position));` but it's getting `throw new ArgumentOutOfRangeException(nameof(position), SR.ArgumentOutOfRange_NeedNonNegNum);` which is only in the coreclr copy.

C:\git\corert\src\System.Private.CoreLib\src\System\IO\UnmanagedMemoryAccessor.cs  needs to 
 be brought up to date to match C:\git\coreclr\src\mscorlib\src\System\IO\UnmanagedMemoryAccessor.cs, and moved into the 'shared' folder so it stays in sync.

the other option is to hack the test, which will get it passing but leaves customers with observably different behavior in ILC builds.

**Comment by AtsushiKan** [comment]
https://github.com/dotnet/corefx/blob/ea1bc38c237dfb768e7d442efa95cab785e89ac3/src/System.IO.UnmanagedMemoryStream/tests/Uma.ReadWriteStructArray.cs#L14

(People, at least indicate which test project the test lives in!)

**Comment by AtsushiKan** [comment]
Please assign to area owner for this api.

I believe that that CoreCLR and the test are in conflict with MSDN and CoreRT. And I think MSDN/CoreRT's position should prevail:

https://msdn.microsoft.com/en-us/library/dd267754(v=vs.110).aspx

https://msdn.microsoft.com/en-us/library/dd267761(v=vs.110).aspx

MSDN states clearly that ARE is thrown when "position is less than zero or **greater than** the capacity of the accessor". This is consistent with how C programmers view arrays - it's valid to compute a pointer that lies "one past the end" of the array, and it's valid degenerate case to copy a 0-length array into it (it's a nop.) Similarly, it's valid to read a 0-length array from it (another nop) and since UMA.ReadArray() is designed to truncate reads when hitting the end, it should accept n-element arrays too (and copy nothing.)

Unfortunately, CoreCLR has a specific check for "greater than **or equals**": <a href="https://github.com/dotnet/coreclr/blob/44f57065649af5f8bcbb7c71d827221a7bc1bf7a/src/mscorlib/src/System/IO/UnmanagedMemoryAccessor.cs#L960">here</a> and <a href="https://github.com/dotnet/coreclr/blob/44f57065649af5f8bcbb7c71d827221a7bc1bf7a/src/mscorlib/src/System/IO/UnmanagedMemoryAccessor.cs#L578">here</a>.

CoreRT consolidated many of the argument checks into a common EnsureSafeToRead/EnsureSafeToWrite helper. Those helpers missed this case, but probably did so precisely because ReadArray/WriteArray's check is inconsistent with everyone else.

In my opinion, the WriteArray test should expect an ArgumentException (not enough room) rather than an ArgumentOutOfRangeException, and the ReadArray test should expect no exception at all.

Whoever owns this class should make a decision as whether to make the apis consistent with MSDN or whether to make CoreRT consistent with CoreCLR.

**Comment by danmosemsft** [comment]
@ianhays @JeremyKuhne thoughts?

**Comment by danmosemsft** [comment]
@AtsushiKan offered to take this thanks @AtsushiKan !

**Comment by danmosemsft** [comment]
@ianhays comments on issue above?

**Comment by ianhays** [comment]
In general I'm more inclined to make sure they're consistent with the desktop behavior than any other behavior, regardless of what MSDN or CoreFX say/do. This kind of change generally doesn't meet the bar to differ from netfx.

Either way, CoreRT and CoreCLR should definitely do the same thing.

**Comment by Jiayili1** [comment]
This issue is repro, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170704.01/workItem/System.IO.UnmanagedMemoryStream.Tests/analysis/xunit/System.IO.Tests.Uma_ReadWriteStructArray~2FUmaReadWriteStructArray_InvalidParameters

**Comment by danmosemsft** [comment]
@Jiayili1 please reactivate if it happens in 2 days.

**Comment by Jiayili1** [comment]
@danmosemsft I will check this issue in recent 2 days.
