### ISSUE TITLE
System.Data.Common.Tests InvokeCodeThatShouldFirEvents_EnsureEventsFired test disabled.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#20589]
-method System.Data.Tests.DataCommonEventSourceTest.InvokeCodeThatShouldFirEvents_EnsureEventsFired

````
   System.Data.Tests.DataCommonEventSourceTest.InvokeCodeThatShouldFirEvents_EnsureEventsFired [FAIL]
      Assert.InRange() Failure
      Range:  (1 - 2147483647)
      Actual: 0
      Stack Trace:
         c:\dd\CoreFxN\src\System.Data.Common\tests\System\Data\DataCommonEventSourceTest.cs(35,0): at System.Data.Tests.DataCommonEventSourceTest.InvokeCodeThatShouldFirEvents_EnsureEventsFired()
            at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetV(Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean targetIsThisCall)
            at System.InvokeUtils.CalliIntrinsics.Call(IntPtr dynamicInvokeHelperMethod, Object thisPtrForDynamicInvokeHelperMethod, Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState)
         c:\dd\ProjectN\src\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\InvokeUtils.cs(400,0): at System.InvokeUtils.CallDynamicInvokeMethod(Object thisPtr, IntPtr methodToCall, Object thisPtrDynamicInvokeMethod, IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, Object targetMethodOrDelegate, Object[] parameters, BinderBundle binderBundle, Boolean invokeMethodHelperIsThisCall, Boolean methodToCallIsThisCall)

```

**Comment by joshfree** [comment]
@saurabh500 PTAL

**Comment by saurabh500** [comment]
@stephentoub @danmosemsft Is EventSource supported on uapaot? Or do we need additional configuration so that event sources can be emitted?
This failure is happening because no events were emitted from System.Data.Common when these tests were run.

**Comment by tijoytom** [comment]
@saurabh500 Please work with @brianrob on this one.

**Comment by saurabh500** [comment]
@brianrob any advice here?

**Comment by brianrob** [comment]
@saurabh500, I just checked in some changes to ProjectN TFS that may address this.  Can you please try running the test again with the latest ProjectN TFS sources?

**Comment by saurabh500** [comment]
@brianrob  I think I need to wait for the next build of the tools for ProjectN to consume your checkin. Is there a nightly build that can be consumed from the VS nuget feed?

**Comment by brianrob** [comment]
Not sure.  @joshfree, @danmosemsft?

**Comment by joshfree** [comment]
You'll see a ProjectNTfs PR (for example https://github.com/dotnet/corefx/pull/21915) tomorrow morning

**Comment by brianrob** [comment]
@saurabh500, FYI, my changes got backed out of the official build last night, so they won't be in today's ProjectNTfs PR.  I need to investigate and try to re-submit.

**Comment by saurabh500** [comment]
@brianrob Thank you for the update. Let us know when the changes make their way back in.

cc @ajlam @corivera 
@corivera When the Brian's changes get into TFS, we need to enable this test and make sure that it passes on uapaot.

**Comment by brianrob** [comment]
These went in a short while ago with a fix for the break. Keep an eye out on Monday for the ProjectNTfs PR.

________________________________

**Comment by corivera** [comment]
Still seeing these test failures in the latest code. Looking into it.

**Comment by corivera** [comment]
In the TestEventListener, OnEventSourceCreated is being passed an EventSource with a Name like "$BlockedFromReflection". In non-uapaot tests this name should resolve to "System.Data.DataCommonEventSource". Since the name of this event doesn't match the expected name, the TestEventListener doesn't enable that event as seen here: https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs#L81

@brianrob Do you know anything about why we're getting "$BlockedFromReflection" in the EventSource name?

**Comment by corivera** [comment]
Test, for reference: https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/tests/System/Data/DataCommonEventSourceTest.cs#L18

Here's the EventSource it uses: https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/src/System/Data/Common/DataCommonEventSource.cs

**Comment by brianrob** [comment]
@corivera, the issue here is that assemblies in CoreFX are reflection blocked for any non-public surface area.  This would imply that your EventSource type is non-public.  There are three choices that you can make here:

1. Add the EventSource to the EventSource IL transform in ProjectN TFS (see ProjectN\ndp\pntoolchain\Microsoft.NetNative.ILTransform\Transforms\EventSourceTransform.cs).  Look at the IsEventSource method.  This should generate the metadata that you need at compile time to avoid reflection.
2. Make the type public.  You'll also likely need to make the methods public as well, though they won't be listed in the contracts, so they're not easily targetable (this is desirable).
3. Opt the entire assembly out of reflection blocking for non-public surface.

I'd recommend doing the first option as it is the cleanest.
