### ISSUE TITLE
Consider adding WebSocket.CopyToAsync() to avoid copies and allocations on ReceiveAsync

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#20583]
So that websocket implementations that keep an internal buffer e.g. (https://github.com/dotnet/corefx/blob/6d796f18bb24762e16ba0337a4bae75c09d83b22/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L39) can be pushed to the destination without allocating a buffer.

### API Proposal

```C#
public class WebSocket
{
    public Task<WebSocketReceiveResult> CopyToAsync(
        Func<WebSocketReceiveResult, ArraySegment<byte>, object, Task> callback,
        object state);
```

### Usage

You could even pipe to a `Stream` like this:

```C#
await webSocket.CopyToAsync((data, state) => { 
    return ((Stream)state).WriteAsync(data.Array, data.Offset, data.Count);
}, 
stream);
```

# Original Proposal

```c#
WebSocket.CopyToAsync(Func<ArraySegment<byte>, object, Task> callback, object state);
```

/cc @stephentoub @CIPop @davidsh

**Comment by stephentoub** [comment]
I agree this seems like it would be a nice addition (though I don't have a good sense of the use cases that would benefit from it.)

**Comment by davidfowl** [comment]
@stephentoub Same reason we have CopyToAsync on Stream, push based systems can use this to get data handed to then instead of pulling it. It also makes the API a bit easier to use as the callback mirrors the javascript event handler. I didn't want an event because async events aren't a thing and this marries better to the Stream API.

For SignalR, we would use this instead of having to allocate our own buffers. Since the managed websocket implementation uses the array pool, we would be getting those pooled buffers for free.

**Comment by stephentoub** [comment]
@davidfowl, sure, what I meant was, there's various pieces of information that's returned as part of the web socket receive result, e.g. the kind of packet, whether a packet was partial or not, etc., and I'm not familiar enough with websocket use cases to know whether dropping that info would matter in an API like this.  That, plus this would seem to handle the case where you just want to consume all of the data as a stream, rather than a back and forth with the sender, and again I'm not familiar enough with use cases to understand how common that need is.  For the case where you just want to consume the entire stream of bytes, this would be a nice enhancement.

**Comment by davidfowl** [comment]
The API should probably look like this:

```C#
Task<WebSocketReceiveResult> CopyToAsync(Func<WebSocketReceiveResult, object, Task> callback, object state);
```

The overall CopyToAsync method would end once a close frame was received. Each callback for data would give you the receive result telling you if there was a partial message or not.

**Comment by stephentoub** [comment]
And presumably the implementation would be allowed to reuse the same WebSocketReceiveResult on each callback, such that the callback couldn't expect to use it beyond when the delegate returned and the returned task completed.

**Comment by davidfowl** [comment]
@stephentoub correct.

**Comment by davidfowl** [comment]
One added bonus, this API could be truer to the underlying protocol. Today, EndOfMessage returns false even if there are no continuation frames. This is because it needs to be false if the buffer passed into ReceiveAsync is < the received data. It doesn't truly represent the Fin flag in the websocket protocol.

**Comment by stephentoub** [comment]
The suggested:
```C#
public Task<WebSocketReceiveResult> CopyToAsync(Func<WebSocketReceiveResult, object, Task> callback, object state);
```
looks pretty good to me, maybe with state having a null default value.

**Comment by karelz** [comment]
API Review:
Do we want the API on WebSocket or ManagedWebSocket?

If @stephentoub agrees, it is approved.

**Comment by stephentoub** [comment]
> Do we want the API on WebSocket or ManagedWebSocket?

I don't understand the question... ManagedWebSocket is an internal type, an implementation detail.

**Comment by karelz** [comment]
> ManagedWebSocket is an internal type, an implementation detail.

That is a detail we overlooked :) ... if there is only 1 public type, then this is approved.

**Comment by karelz** [comment]
@stephentoub can you please comment if it is suitable for up-for-grabs? (with rough complexity)

**Comment by stephentoub** [comment]
It's fine to be up-for-grabs, and it's medium complexity.  The base virtual method is pretty simple to implement, as at its core it's just a loop that'll do ReceiveAsyncs and then invoke the callback, similar to what someone would do today if they were implementing this as an extension method.  The more complicated part is the efficient overrides in our various implementations.

One thing we may want to consider (even though it was approved as I'd outlined above) is that in https://github.com/dotnet/corefx/issues/21281 I've proposed adding new ReceiveAsync/SendAsync overloads.  Implementation-wise, this base method should almost certainly switch to using the new ReceiveAsync when it's available, but that can be done any time in the future.  The more interesting and time-sensitive piece is whether instead of using `ArraySegment<byte>` in this new method, should we use `ReadOnlyBuffer<byte>`? And instead of using `WebSocketReceiveResult`, should we use the `ValueWebSocketReceiveResult` struct?  `ReadOnlyBuffer<byte>` is more flexible in that it would allow an implementation using native memory to share out its data without copy/allocation.  For this API, the `ValueWebSocketReceiveResult` may not save a whole lot, as we already discussed reusing the same `WebSocketReceiveResult` for each callback invocation rather than allocating a new one for each, but maybe it's still worthwhile to avoid any confusion.

**Comment by davidfowl** [comment]
I'm beginning to look closer at websocket performance in ASP.NET Core And SignalR and this might be the best way to get the required performance. In particular I'm worried about idle memory usage so I'd like a mode where there's a bufferless read outstanding when waiting for more data.

**Comment by davidfowl** [comment]
Not sure we need this anymore. We've made the WebSocket APIs pretty low allocation with the new ValueTask. In the future I'd like to see a lower level API that can be used with pipes that expose the underlying frames without a copy but i'll file another issue with an API proposal.
