### ISSUE TITLE
System.IO.Ports.Test OpenEveryPortName disabled on UapAot.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#20588]
-method System.IO.Ports.Tests.GetPortNames.OpenEveryPortName

This is probably by design but I don't want to make the call as I don't exactly own this area and there may be another way for that api to work that I don't know of.

SerialPort.GetPortNames() needs to read the registry and its uses Microsoft.Win32.Registry to do so. For Aot, that package is the autogenerated PNSE version. (Unfortunately, OpenEveryPortName() NullRefs rather than PNSE'ing as it tries to execute Registry.LocalMachine.OpenSubKey() - Registry.LocalMachine is a static field which never gets initialized in an autogenerated PNSE assembly.)

**Comment by danmosemsft** [comment]
We don't want M.Win32.Registry in the UWP package because it won't work 99% of the time. However Windows did agree to let us read HARDWARE\DEVICEMAP\SERIALCOMM specifically. We may want to link in a minimal piece of the registry code in UWP only into this library.

**Comment by willdean** [comment]
There was recent discussion about `SerialPort.GetPortNames` in #18023, because problems with the reg-key are also present on other versions of Windows (like the Raspberry PI Win 10 IOT build).

There are umpteen (9) different ways for applications to discover the list of serial ports on Windows, all of them broken in some way or another, but we could perhaps use a different mechanism in UWP?  (I have no idea what's available there).   This is a useful reference: http://www.naughter.com/enumser.html

The System.IO.SerialPort test framework itself p/invokes into QueryDosDevices to get a list of ports - is that an option on UWP?

**Comment by danmosemsft** [comment]
Pending guidance from Windows on the API to use here.

**Comment by vbaderks** [comment]
Is there any progress on this topic?

It seems that for UWP, there is a new function exported to get the COM ports: GetCommPorts@12 api-ms-win-core-comm-l1-1-2.dll

**Comment by pjanotti** [comment]
Thanks for pointing that out @vbaderks I will take a look at this.

**Comment by pjanotti** [comment]
Per documentation GetCommPorts reads from the registry, so it won't find ports that are not properly present on the registry (as described above). That said, it will avoid adding the Microsoft.Win32.Registry to the UWP package, it seems worth using it in UWP.

**Comment by pjanotti** [comment]
Changes are ready but need to wait buildtools change reach CoreFx.
