### ISSUE TITLE
System.Threading.Tests TestEtw disabled.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#20592]
System.Threading.Tests -method System.Threading.Tests.EtwTests.TestEtw

Events that should be firing aren't.

**Comment by stephentoub** [comment]
@AtsushiKan, @tijoytom, it seems like we've been opening a lot of individual issues, one for each library's ETW tests that are getting disabled.  Are these all due to the same root issue?  I'm wondering if we should just have a single issue they're all disabled against, and then when the underlying issue is fixed, we re-enable them all in one fell swoop.
cc: @danmosemsft

**Comment by AtsushiKan** [comment]
ETW - Unknown. We're under the gun to get the tests clean this week so we have very limited time to do root-cause analysis for areas that aren't part of our expertise. So there will probably some test-spamming this week. All I can say about the ETW stuff is that I earlier fixed one ETW bug hoping to kill all the ETW failures in one swoop and it didn't. So I'm being conservative and opening these individually.

**Comment by tijoytom** [comment]
In an nutshell when event tracing was ported for NS2.0 and there wasn't much testing done so see if it really works in UWP. This happened mostly because of time constraint and @brianrob is going to work in it in the common weeks. I will work with Brain to fold these in to one issue.

**Comment by AntonLapounov** [comment]
I disabled System.Threading.Tasks.Dataflow.Tests.EtwTests.TestEtw with this issue number as well.

**Comment by brianrob** [comment]
@AtsushiKan, after fixing EventSource, this it appears that the last remaining issue is that the EventSource type is reflection blocked.  Thus, the EventSource name and GUID can't be retrieved.  I'm not sure if you're the owner, but if you are, then I'd like to ask that you make the call (and change) to fix this.  My understanding is that you can either make the type public or you can opt the entire assembly out of reflection blocking.

**Comment by AtsushiKan** [comment]
This has nothing to do with Reflection. The event source code was if'd out in uapaot.

**Comment by brianrob** [comment]
@AtsushiKan, thanks for fixing this.  I was trying to square your comment with the fact that I spent a bunch of time debugging the code and it was in fact present and running.  It turns out that this issue is tracking two disabled tests in two different places - you can see this in @AntonLapounov comment above.  I debugged System.Threading.Tasks.Dataflow.Tests.EtwTests.TestEtw, which is different than the one you just enabled.  Glad to see that one is working.

@AntonLapounov, can you please look at System.Threading.Tasks.Dataflow.Tests.EtwTests.TestEtw?  This one is currently broken because the EventSource type is reflection blocked.
