### ISSUE TITLE
Information about runtime.ubuntu.14.04-x64.runtime.native.System (for example)

### ISSUE THREAD

**Issue by jmroyb** [dotnet/corefx#20701]
Folks,

First of all, I know that (just to avoid comments about this phrase) ...

"Internal implementation package not meant for direct consumption.  Please do not reference directly."

I have some classes built in Mono I would like to move to netstandard. These classes were called
by Windows and Linux some like this:

            if (Environment.OSVersion.Platform == PlatformID.Unix)
            {
                l = new Linux.Virtualization();
                l.Run();
				...
            }
            else if (Environment.OSVersion.Platform == PlatformID.Win32NT)
            {
                l = new Windows.Virtualization();
                l.Run();
				...
			}

This method had the problem all code (both Windows and Linux) was in same Dll.

I would like to use new corefx style: runtime.ubuntu ..., runtime.native ...

Please can you provide a link, some example about:
1. platform discrimination
2. how are referenced from corefx high level libraries to these runtime.xxx
3. where are placed runtime.xxx libraries?

I appreciate information, links, examples ...

Thanks a million

**Comment by mellinoe** [comment]
System.Native.so is what we refer to as a "native shim". The "native shims" here are a solution to a very particular problem (interfacing with native API's in a friendly and portable way); they aren't a general solution to "platform-specific" code. Without knowing much about what you're trying to do, I would recommend that you either:

* Just keep doing runtime branching as in the code you shared.
* Build multiple managed assemblies (not native binaries) which each have an implementation for a specific platform.

Could you give a little more information about what you're trying to accomplish?

**Comment by jmroyb** [comment]
Hi @mellinoe I will try to explain myself better:

I use a library within Console and Wpf apps. It is 4Mb size (60% Windows api calls and 40% Linux bash calls). Console app can run in Windows and Linux.

I would like to split it into two libraries, in other words that is shorter and platform specific : one for Windows (with old lib 60% api calls) and other for Linux (with old lib 40% api calls). I want to reuse Console app (and use Windows library with Wpf). I know I have to apply come changes both new libraries to fit them to netstandard and some changes at Console and Wpf apps.

But I do not know how replace next block and load right library in Windows and right in Linux because this implies have both libs together:

        if (Environment.OSVersion.Platform == PlatformID.Unix)
        { ...
        }
        else if (Environment.OSVersion.Platform == PlatformID.Win32NT)
        { ...
	}

But what app code I need to choose from one specific library or other? Should I use same block? How corefx manage this scenario with runtime.XXX platform-specific libraries? And where are runtime.XXX installed (I did not find in my Windows !?!)

Thanks for your help

**Comment by mellinoe** [comment]
@jmroyb I'm afraid this is more of an application architecture question, so I'm not sure how much help my advice is going to be without knowing very much about what you're trying to accomplish.

As for the "runtime.xyz" packages: I don't think they are related to your problem. For .NET Core, we produce a number of "runtime" NuGet packages in order to support a wide variety of systems in the .NET Core platform itself. Developing an application on top of that platform has very different requirements, so you almost certainly shouldn't concern yourself with producing runtime-specific NuGet packages as we are doing here.

If I was designing an application like this, I might create the following projects:

* ApplicationLogic.dll -- A simple re-usable library which has most of your "business logic" in it. It doesn't have anything platform-specific in it. It may contain a few abstractions (interfaces/abstract classes) which need to be filled in by platform-specific types.
* WPFApplication.exe -- A windows-only WPF application, which references ApplicationLogic.dll.
* ConsoleApplication.exe -- A console application, which references ApplicationLogic.dll. If you need to have platform-specific functionality in here, and do not want the "overhead" of carrying around code for other platforms, then I would just use #if blocks, depending on the size of the code. Instead of this:

```C#
if (Environment.OSVersion.Platform == PlatformID.Unix) { }
else { }
```

You can just have:
```
#if WINDOWS
// Stuff
#else
// Other stuff
#endif
```

You might need or want other projects based on how much is shared between the Windows WPF application and the Windows console application. You could have something like "ApplicationLogic.Windows.dll" in that case. WPFApplication.exe would reference it, as would ConsoleApplication.exe, when building for Windows. You could do something similar if you wanted to build a cross-platform UI application, and share logic with the console application.

**Comment by jmroyb** [comment]
Hi @mellinoe ,

thanks for your comments.
