### ISSUE TITLE
INotifyCollectionChanged : IEnumerable

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/corefx#20721]
Why doesn't `INotifyCollectionChanged` inherit from `IEnumerable`?

**Comment by omariom** [comment]
I think that's because there is no non-generic version of `IReadOnlyList` which would be most logical to inherit INPC from.

**Comment by weitzhandler** [comment]
I didn't understand you. How are `IReadOnlyList` and INPC related here? I was asking for non-generic `IEnumerable` to enable direct iteration on `INotifyCollectionChanged`.

**Comment by mikedn** [comment]
Why should it inherit from `IEnumerable`? `INotifyCollectionChanged` is a "feature" certain collection have, it's not itself a collection. That is, I wouldn't expect anyone to pass around a `INotifyCollectionChanged` and use it with `foreach` or LINQ.

**Comment by weitzhandler** [comment]
@mikedn, I mean the name itself implies its a collection, so why not provide the collection itself by it somehow, are there any `INotifyCollectionChange` implementations that are not collections? Is this necessary?

**Comment by mikedn** [comment]
> so why not provide the collection itself by it somehow

I'll quote one of your own question as an answer: "Is this necessary?" :)

**Comment by weitzhandler** [comment]
Lol and I meant is casting necessary

**Comment by mikedn** [comment]
Well, casting is usually necessary since not all collection types implement `INotifyCollectionChange`. The usual pattern is that you get an `IEnumerable` (or some other collection type) from somewhere and try to cast it to `INotifyCollectionChange` to check if it supports change notifications.

The only way to avoid casting is to force people to give you a `INotifyCollectionChange` to begin with but that's unnecessarily restrictive most of the time. For example, WPF's `ItemsControl.ItemsSource` could have type `INotifyCollectionChange` instead of `IEnumerable` but that would force everyone to use an `ObservableCollection` as items source and that's not necessary, there are many cases where collection change notifications aren't needed.

**Comment by weitzhandler** [comment]
Are there proper purse cases for an INCC that's not an `IEnumerable`?

**Comment by mikedn** [comment]
> Are there proper purse cases for an INCC that's not an IEnumerable?

Likely not, code that's using INCC would need to access the collection items somehow.

**Comment by weitzhandler** [comment]
So I don't understand why not `INotifyCollectionChanged : IEnumerable`.

**Comment by mikedn** [comment]
And I don't understand why `INotifyCollectionChanged` should inherit `IEnumerable` :)

In general, just because something is possible doesn't mean that it has to be done. And when it comes to interfaces this is IMO even more true.
