### ISSUE TITLE
System.IO test failure since the right exception is not thrown in uap-aot

### ISSUE THREAD

**Issue by tijoytom** [dotnet/corefx#20753]
These tests are expecting ArgumentNull , but never gets it. Should be a simple fix.
TestNullStream_CopyToAsyncValidation()

**Comment by karelz** [comment]
@tijoytom is it a test bug or bug? Can you please follow [triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified)?

**Comment by tijoytom** [comment]
Not sure if you notice the title it says 
"System.IO test failure since the right exception is not thrown in uap-aot" . I don't see what that confusion is here?

**Comment by karelz** [comment]
@tijoytom no, I did not notice the title. I don't scale to read everything - that's the confusion. That's why we have lightweight process ([triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified)) which we expect everyone to follow more or less. Makes sense? Happy to explain motivation in person if it is not clear yet.
The rules are pretty simple and mostly common-sense. There's even motivation to help people understand the intent better.

**Comment by danmosemsft** [comment]
Brekaing out BinaryReader.Read_InvalidEncoding() which is different.
