### ISSUE TITLE
Append/Prepend

### ISSUE THREAD

**Issue by eatdrinksleepcode** [dotnet/corefx#2075]
## Summary

Two of the IEnumerable extension methods that I carry in my collection (we all have a personal collection of IEnumerable extension methods, am I right?) are Append and Prepend, for adding a single element to the end or beginning of a sequence respectively. Though not quite as common as concatenating sequences, I have been surprised at how often this need arises. Doing this inside of an expression today is not straightforward; the best equivalent that I have found is far from ideal:
```
sequence.Concat(Enumerable.Repeat(singleValue, 1))
```

I propose adding Prepend and Append extension methods to Enumerable to fill this need.

## API

```
public static class Enumerable
{
    public static IEnumerable<T> Append<T>(this IEnumerable<T> source, T value);
    public static IEnumerable<T> Prepend<T>(this IEnumerable<T> source, T value)
}
```

## Usage

```
optionalValues.Prepend("<None>")
```

**Comment by whoisj** [comment]
Being enumerable does not imply accepting new entries.

In fact, requiring these entry points would completely break the "yield is enumerator" pattern. Given your suggestion how would classes like the following exist?

```
public class Foo<T> : IEnumerable<T>
{
    public IEnumerator<T> GetEnumerator()
    {
        yield return 0;
        yield return 1;
        yield return 2;
    }
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }
}
```

**Comment by stephentoub** [comment]
@whoisj, I don't believe he's proposing modifying the original source.  As with most of the Enumerable extension methods, they consume an existing enumerable and do something with it, e.g.
```C#
public static IEnumerable<T> Prepend<T>(this IEnumerable<T> source, T value)
{
    yield return value;
    foreach (T t in source) yield return t;
}

public static IEnumerable<T> Append<T>(this IEnumerable<T> source, T value)
{
    foreach (T t in source) yield return t;
    yield return value;
}
```

**Comment by whoisj** [comment]
@stephentoub ahh I see. Elegant solution. Never had a need or want for it, but I can see how it would be useful. :smile:

**Comment by mellinoe** [comment]
I think this would be useful :+1:

**Comment by MgSam** [comment]
:+1:

**Comment by KrzysztofCwalina** [comment]
I like the proposed additions; simple and useful.

**Comment by axel-habermaier** [comment]
Nice suggestion, very useful; I usually use ``new[] { myObject }.Concat(myOtherObject)`` to do the same thing, but this is way more concise and clearly expresses the intent.

**Comment by svick** [comment]
The only problem I have with this proposal is that if you use these methods repeatedly, enumerating the resulting collection will be O(n<sup>2</sup>) (assuming the implementation isn't specifically written to counter that).

Example of code that would cause the issue:

```c#
var collection = Enumerable.Empty<int>();

for (int i = 0; i < n; i++)
{
    collection = collection.Append(i);
}
```

I don't actually think the implementation should be written to make this O(n), since there are better choices for code like this (including the common .Net collections and Immutable collections). But I do think it would be nice to warn against this issue in the documentation.

**Comment by eatdrinksleepcode** [comment]
@svick Why would enumerating the result of your code be O(n<sup>2</sup>)?

Append is exactly like Concat, it just takes a single element as an argument instead of a sequence. It could even reasonably be called Concat; the motivation for naming it Append instead is for symmetry with Prepend, which cannot reasonbly be called Concat.

**Comment by svick** [comment]
> Append is exactly like Concat

Yes, it is, `Concat` also has this problem of being O(n<sup>2</sup>) when used in this manner. What I'm afraid of is that having `Append` and `Prepend` would encourage this kind of pattern.

> Why would enumerating the result of your code be O(n<sup>2</sup>)?

Because you have n layers of enumerators and you have to get through those layers for each call to `MoveNext`. [Quick googling resulted in a more detailed explanation (specifically about `Concat`) here.](http://blogs.msdn.com/b/michste/archive/2011/09/26/lack-of-nested-iterators-in-c.aspx)

**Comment by eatdrinksleepcode** [comment]
I'll be honest, I had to read both of those articles (the one you linked and [the one that it linked](http://blogs.msdn.com/b/wesdyer/archive/2007/03/23/all-about-iterators.aspx)) multiple times before I understood what they were trying to say. I think I was thrown off by the tree diagram in the first article, which while accurate, is also misleading since tree traversal is (usually) O(n).

I can see the point that the danger of this kind of performance problem occurring might be greater if it is easier to build sequences by concatenating single items together. I don't think that's a reason not to do it - as you say, there are much better ways to perform that kind of operation. But it may be worth investigating during implementation whether there are some simple ways of mitigating the performance problem in case it does happen (I have some ideas).

**Comment by hackcraft** [comment]
> we all have a personal collection of IEnumerable extension methods, am I right?

... and simplified them when 2.0 came out, and threw a lot away when 3.5 came out when the survivors became extension methods, am I right?

One of mine is an `Emit()` that works like:

    public IEnumerable<T> Emit(this T item)
    {
        yield return item;
    }

I combine it with `Concat()` to get what you get with `Prepend()` and `Append()`, while it also serves some other purposes too. I had a prepend and append, but decided to cut down to just `Concat()` because it's known, and the issues with hitting it in a loop or otherwise using it excessively are also known.

**Comment by terrajobst** [comment]
API looks fine.

@VSadov, we think the RTM timeline would be reasonable, but it's your call really.

**Comment by VSadov** [comment]
Seems like a good idea. 

NOTE: While implementing this might be fairly simple. Merging this in could be a bit delicate.

Since this is a public API, refs will need to be updated to ensure this is a part of contract assemblies (or noone using contracts will see the new API). That has a potential of breaking builds for other runtimes not getting the new API.

**Comment by HappyNomad** [comment]
In a .Net Standard 2.0 library, I have access to the very useful .Append and .Prepend extension methods of the System.Linq.Enumerable class.
	1) Why are these methods marked with EditorBrowsableState.Never?  I didn't stumble upon them until recently, before which I'd been using the cumbersome .Concat with an array initializer.
	2) Why aren't these methods available in a .NET Framework 4.6.1 Console App?  I thought such apps were, implicitly, .NET Standard 2.0 so should have the same methods available to them.
