### ISSUE TITLE
Support JSON-LD in DataContractJsonSerializer

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/corefx#2077]
There is an issue raised by dotnet/wcf#28 requesting support for JSON-LD. 

If more info is needed, @akuckartz would be a good person to start with, as the original issue-raiser. It would be great to hear from the community if JSON-LD is useful so this work can be prioritized appropriately. 

Thanks!

**Comment by terrajobst** [comment]
Can you make a proposal on how this would look like?

**Comment by karelz** [comment]
We need formal API proposal

**Comment by akuckartz** [comment]
Why was this closed?

**Comment by karelz** [comment]
I don't know why @shmao closed it, but by looking at the issue I have to agree, because for one year no one was interested in coming ahead with a proposal. I don't see much value in keeping API ideas opened for more than 6 months when there is nothing concrete.

**Comment by akuckartz** [comment]
Why can't issues be kept open until they are resolved?

**Comment by karelz** [comment]
@akuckartz because we would drown in them.
Do you file all wishes for all your projects into your backlogs? Even those you know are not realistic in next year or two and are not in high demand? What is the point to have them filed? What if the requirements change, or there is something else fulfilling the role? Maintaining opened issues is cost and it makes focus more challenging, so if there is little value, closing is fine.

Moreover anyone can browse through closed issues and suggest reopening of those he/she wants to work on. You can view 'Closed' as more distant Future.

**Comment by akuckartz** [comment]
Closed but unresolved issues can realistically only be found if they are tagged so that they can be differentiated from those which are resolved.

**Comment by karelz** [comment]
@akuckartz true - if you look at the labels, there are some combos which indicate the issue has been closed without fixing (e.g. api-needs-work).
If there is interest and someone wants to push this particular idea forward to something actionable, or if we have few people voting it up, we can reopen it (or we can create a new tracking issue).
