### ISSUE TITLE
X509Certificates: TestByExtension_FriendlyName fails on non-English locale

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/corefx#2079]
The [System.Security.Cryptography.X509Certificates.Tests.FindTests.TestByExtension_FriendlyName](https://github.com/dotnet/corefx/blob/bb05410bceded36abaf165050ed249187f13ea45/src/System.Security.Cryptography.X509Certificates/tests/FindTests.cs#L335-L338) fails on my German Windows: `System.ArgumentException : The OID value was invalid.`.

The culprit seems to be the string "Enhanced Key Usage", if I change it to the German equivalent "Erweiterte Schlüsselverwendung" the test passes again.

/cc @bartonjs

**Comment by bartonjs** [comment]
Wow, those tests really were Redmond-centric :smile:.

The fact that FriendlyName is localized makes sense, and it really drives home my silent campaign to never see references to it in code (it's just intended as a helpful thing for UX/error strings).  (I'm guessing that algorithm names ("SHA1", etc) get 'localized' as-is, and it's only ancillary things like extensions that are really localized, but still.)

Since the test is testing something useful (that someone -can- ask for it by friendly name) I guess the correct form of the test would be to use `new Oid("2.5.29.37").FriendlyName`, since it would be using the same localized Windows for both directions of that mapping.
