### ISSUE TITLE
Invalid sequences of bytes debug asserts in System.Drawing.Icon

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#20808]
The following test causes a debug assertition to be hit in System.Drawing.Icon.Initialize:

```cs
byte[] bytes = new byte[] { 0, 0, 1, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
byte[] bytes = new byte[] { 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 255, 255, 255 };
byte[] bytes = new byte[] { 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 255, 127, 255, 255, 255, 127 };
byte[] bytes = new byte[] { 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 12, 0, 0, 0 };

```

```cs
using (var stream = new MemoryStream())
{
    stream.Write(bytes, 0, bytes.Length);

    stream.Position = 0;
    Assert.Throws(exceptionType, () => new Icon(stream));
}
```

I can't reproduce this issue with netfx, but that might be because of release vs debug mode

**Comment by hughbe** [comment]
I think this is just a bad assertion: https://github.com/dotnet/corefx/blob/e15746e75068eb21b6dfaa5cad1799b1ad2069ba/src/System.Drawing.Common/src/System/Drawing/Icon.cs#L655-L660

@mellinoe what do you think? I'd like to submit a PR

**Comment by mellinoe** [comment]
I do suspect that there might be some faulty Debug assertions in the codebase. When I was testing out some of the mono tests, I noticed that `Font` will always trigger an assertion if you call any methods that touch [`NativeFont`](https://github.com/dotnet/corefx/blob/master/src/System.Drawing.Common/src/System/Drawing/Advanced/Font.cs#L454) after it has been disposed, because the field is set to `IntPtr.Zero`. Without the assertion, the code still ends up throwing an ArgumentException later on, as expected. The code is exactly the same as the .NET Framework code, so it would also give you that assertion if you had a debug version.
