### ISSUE TITLE
ActiveDirectorySite.GetComputerSite for Linux domain joined OS

### ISSUE THREAD

**Issue by mikes-gh** [dotnet/corefx#20871]
If a Linux OS is joined to an AD site is there not a way to Get the AD site?

Look like the code only supports windows API at present.

**Comment by karelz** [comment]
There is no port to Linux yet - see #2089 for details.
Also note that only `System.DirectoryServices.Protocol` is easy to port to Linux, the other namespaces are very difficult (if not impossible) to port due to their dependencies on Windows components. The Windows components would have to be reimplemented from scratch on Linux.

cc @tquerec @jay98014

**Comment by mikes-gh** [comment]
In this case it is LDAP and DNS that can provide this info.  Shouldn't be impossible.

https://patternbuffer.wordpress.com/2007/12/13/finding-your-active-directory-site-and-domain-controllers/

**Comment by karelz** [comment]
Can it implement the entire class? Entire namespace?
Implementing just a few methods and throwing for the rest is something many people would like to avoid ...

**Comment by mikes-gh** [comment]
Good point I was too focused on one method I needed.  Need to look at the bigger picture.
