### ISSUE TITLE
System.Linq.Parallel.WithCancellation(token) doesn't validate token source.

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#2104]
... and doesn't perform a couple of other checks it probably should.

[`WithCancellation`](https://github.com/dotnet/corefx/blob/master/src/System.Linq.Parallel/src/System/Linq/ParallelEnumerable.cs#L341-L383) is documented as throwing `ObjectDisposedException` if "The.CancellationTokenSource associated with the cancellationToken has been disposed.", and then checks it by attempting to register a call-back.  Unfortunately, chasing this down to [CancellationTokenSource.cs](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/CancellationTokenSource.cs#L631-L708) yields:

```
if (AppContextSwitches.ThrowExceptionIfDisposedCancellationTokenSource)
{
    ThrowIfDisposed();
}
```
... yup, the error condition is based on stuff outside our control.

The relevant tests _comment_ that they look for exception... and [that they don't](https://github.com/dotnet/corefx/blob/master/src/System.Linq.Parallel/tests/WithCancellationTests.cs#L629) (... really?), and the tests don't actually expect it. 

So `WithCancellation` is currently doing work that will, sometimes (not on any of our test machines), succeed.  The only method available on the token that would throw the exception is `WaitHandle`, but this looks to involve heavier work than should probably be dealt with (the check should be removed).

`WithCancellation` also doesn't check for a few conditions that are probable errors:
 1. It doesn't verify the token is cancellable (useless)
 2. It doesn't verify the token isn't already cancelled (query will perform no actual work)

 (In case 1, this has the side effect of allowing multiple calls to it, which you're not supposed to be able to do either... from the look of things it'll probably take the right-most one if they are all non-cancellable, but I haven't checked all the binary operators).

This is issue is mostly about... what change should be made?  Remove the check and update the documentation?  Change to call `WaitHandle`?  Maybe add checks for unusable tokens?  Changes ought to be simple enough for me if something needs to be done....

<hr />
Side note: I've been investigating immediacy of cancellation as part of this, and it turns out `ToArray` is getting all the way to the point of submitting tasks (which perform the first `MoveNext`/`Current`), and `SequenceEqual` will try to enumerate the left sequence if the right has the actual token.  Thoughts?

**Comment by Clockwork-Muse** [comment]
There's another wrinkle to this; a way you can use two different cancelable tokens, but they're really for two different portions of the query.

`ParallelEnumerable.Range(0, 8).WithCancellation(tokenFromSource).AsParallel().WithCancellation(tokenFromOtherSource)`  
...turns out to be perfectly valid, because it ends up being wrapped during the `AsParallel` call.  This _feels_ like an error, and not what was intended (I'd understand if there was an `AsSequential` call).

@stephentoub - write tests to cover this, or something we should look into dealing with?

**Comment by stephentoub** [comment]
> is documented as throwing ObjectDisposedException if "The.CancellationTokenSource associated with the cancellationToken has been disposed."

The docs just need to be updated for .NET Core / .NET 4.6.  It was only documented as such because this behavior was built in to CancellationToken, and CancellationToken has become more forgiving in this regard for .NET 4.6, so places that used to throw ObjectDisposedException may not anymore.

> It doesn't verify the token is cancellable (useless)

This is by-design.  Imagine you're using PLINQ inside of an API that accepts a CancellationToken and you're just passing it through to PLINQ; you want it to work correctly regardless of whether the token is cancelable or not, as it's often perfectly reasonable for the caller of such an API to pass CancellationToken.None.

> It doesn't verify the token isn't already cancelled (query will perform no actual work)

What verification would you expect?  We wouldn't want to throw an OperationCanceledException from WithCancellation, as that would be subject to race conditions as to whether the OCE emerged from WithCancellation or from the query processing.  And logically the token is about canceling the query, not about canceling the WithCancellation function call, so it doesn't really make sense to come from WithCancellation anyway. (And of course it would also be a non-trivial breaking change from behavior today.)  I believe it to be correct as-is.  It's possible there's some faster path that could be taken in the query's processing, but I haven't seen this to be an issue.

**Comment by Clockwork-Muse** [comment]
@stephentoub - I agree with you about the OCE, I was thinking _maybe_ an ArgumentException if the token was already canceled, but it would be a big breaking change.
