### ISSUE TITLE
don't ask end users to link to openssl

### ISSUE THREAD

**Issue by john7doe** [dotnet/corefx#21047]
In step 1 here https://www.microsoft.com/net/core#macos, you ask the end users to symlink openssl dylibs. Instead use dydl's rpath support and do this at build time:

```
# Path for Homebrew OpenSSL installation path
install_name_tool -add_rpath /usr/local/opt/openssl/lib/ System.Security.Cryptography.Native.OpenSsl.dylib
# Path for MacPorts OpenSSL insallation path
install_name_tool -add_rpath /opt/local/lib/ System.Security.Cryptography.Native.OpenSsl.dylib
```

And why do I need to download and run a visual installer to get a cli? I would love to be able to do: `brew install dotnetcore`

**Comment by danmosemsft** [comment]
@bartonjs

**Comment by bartonjs** [comment]
We chose to not include either the Homebrew or MacPorts default paths because they're defaults instead of fixed values; and we don't want to add probing to a path that you may or may not even expect to exist.

The manual instructions specify symlinks over install_name_tool because symlinks are a once-ever step, and install_name_tool has to be repeated for each patch-build you download.

In .NET Core 2.0 these steps are no longer mandatory, unless you want to specifically use OpenSSL (e.g. `new RSAOpenSsl()`); 2.0 uses Security.framework instead.
