### ISSUE TITLE
Fire Issue: System.Linq.Expressions.Tests on windows.81.amd64

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#21127]
Detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170616.01/workItem/System.Linq.Expressions.Tests

**Comment by danmosemsft** [comment]
@jiayili1 I don't see a failure here?

**Comment by Jiayili1** [comment]
@danmosemsft On WIndows.81.Amd64, there is the fire icon, detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170616.01/workItem/System.Linq.Expressions.Tests

If it doesn't the issue, I will close it.

**Comment by danmosemsft** [comment]
Thanks @jiayli. You're right. @dotnet/dnceng can you explain the fireball here? I see no failures in the log.

https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170616.01/workItem/System.Linq.Expressions.Tests

**Comment by MattGal** [comment]
Looks like we're still hitting https://github.com/dotnet/core-eng/issues/779.  Basically when the processor is trying to put stuff in the SQL DB, if it has trouble downloading the Result XML we ended up doing that. 

@ChadNedzlek introduced some retry logic there but if it was a persistent issue with the storage account it could still reproduce since he has a very limited amount of time to process stuff in the telemetry event stream.  A more aggressive workaround, such as starting a worker thread which is not time constrained by the work of checkpoint-ing in the EventHub stream for instance, may be in order.

**Comment by ChadNedzlek** [comment]
I believe the retry logic has fixed this fairly well, so I'm going to close this issue unless someone sees this again (we also have more explicit logging around this now)

**Comment by MattGal** [comment]
+1.  Haven't seen any repros since 6/19.
