### ISSUE TITLE
Enumerable.SequenceEqual takes IEqualityComparer rather than a predicate

### ISSUE THREAD

**Issue by breyed** [dotnet/corefx#2114]
Why does [Enumerable.SequenceEqual](http://msdn.microsoft.com/en-us/library/vstudio/bb342073.aspx) take its comparer as an [IEqualityComparer](http://msdn.microsoft.com/en-us/library/vstudio/ms132151.aspx)? The algorithm seems to make no use of [GetHashCode](http://msdn.microsoft.com/en-us/library/vstudio/ms132155.aspx). Why does it not instead take a `Func<TSource, TSource, bool>` predicate, similar to how [First](http://msdn.microsoft.com/en-us/library/vstudio/bb535050.aspx) takes a `Func<TSource, bool>`?

**Comment by breyed** [comment]
FWIW, there is a [StackOverflow question](http://stackoverflow.com/q/23087969/145173) on this same topic from before corefx was open sourced.

**Comment by Clockwork-Muse** [comment]
I'm with aanund (in the SO question) on this one; because it's the 'correct' way.  Note that most cases of identity are going to involve multiple properties, which you'd probably want to pull off into a separate predicate for readability/reuse purposes.  For all practical purposes, this would be an implementation of `IEqualityComparer`.

`First` (and most of the methods taking an equivalent predicate) aren't meant to be checking for equality per-se - they're usually going to be looking based on a simple condition.  The difference between "find me the first person who lives in Milwaukee", and "Anybody who has the same name and lives in Milwaukee is the same person".

**Comment by breyed** [comment]
`IEqualityComparer`, despite its name, really does two things: hashes and checks for equality. The only behavioral difference between a `Func<TSource, TSource, bool>` and `IEqualityComparer` is that `IEqualityComparer` has a `GetHashCode` method. If all you want to do is check for sequence equality, with `IEqualityComparer` you have to write the hashing code (which can be tricky to do well), even though it will likely never be used (but you can't count on it never being used because `SequenceEqual` doesn't document that it won't use it).

Often, types that you compare with `SequenceEqual` will happen to have one or more`IEqualityComparer` companion types so that they can be stored in hashed containers. Probably, that is why `IEqualityComparer` was chosen as the parameter. However, there are also plenty of times when there isn't an `IEqualityComparer` and there is no hashing requirement. In those cases, having to create a class and implement `GetHashCode` is wasteful.

**Comment by hackcraft** [comment]
`IEqualityComparer` does one thing; implement a concept of equality for a type. That entails an equals method and a hash-code method because hash-codes depend upon equality and an equality concept that doesn't include one cannot be used most of the places in the framework equality concepts come up. One is reasonably likely to want to use `SequenceEqual` with an equality comparer that is also used somewhere where hash-codes are relevant.

`Func<TSource, TSource, bool>` on the other hand does both more and less; it does something to two `TSource` and returns a boolean based on that. As an equality comparer generally it's incomplete. As an input to `sequence0.Zip(sequence1, comparisonFunc).All(b => b)` it can serve as an equality comparer if desired, or a less-than comparer, greater-or-equal-than comparer, overlaps-with comparer, fewer-number-of-movies-between-them-and-Kevin-Bacon-than comparer, whatever. `sequence0.Zip(sequence1, comparisonFunc).All(b => b)` is useful, but if it were wrapped in one (perhaps optimised) method, it shouldn't be called `SequenceEquals`.

**Comment by breyed** [comment]
@hackcraft I generally agree with your analysis, but would touch on these points:
* The `Zip`-`All` construct differs from `SequenceEqual` if the sequences have different lengths.
* Hash codes do not necessarily depend on equality, just as equality does not necessarily depend on equality. Although many algorithms depend on both, some depend on just one or the other (e.g. cache eviction can use just a hash code).
* `IEqualityComparer`, despite its name and its MSDN summary, really does two things. It supports equality and hashes. These two things can feel like one, since they go together like chocolate and peanut butter to make an object useful in hash-based containers.

For those cases when both methods of `IEqualityComparer` are not needed, it is over-specified. To address this, you could change `IEqualityComparer` to derive from `IJustEqualityComparer` and `IHasher`. Then `SequenceEqual` could take `IJustEqualityComparer`, which is all it needs. However, this still wouldn't help much with using `SequenceEqual` if you don't happen to have an `IJustEqualityComparer` (and to your point, if you did need to implement an interface for other purposes, chances are you'd need all of `IEqualityComparer`). Moreover, chopping `IEqualityComparer` into smaller pieces adds a lot of noise just to support not-so-common use cases.

Another approach is an overload that takes just the equality comparison as a `Func`, as I suggested earlier. You could even name the argument `equalityComparer` to make it clear that it's not an arbitrary predicate. To your point again, if the comparer argument were an arbitrary predicate, you don't really have `SequenceEqual`, but rather something else, probably better called `SequenceAligned`.

Perhaps that's the best answer: add an additional method that checks if two sequences are the same length and are aligned with each other by checking their pairs against a predicate. From my experience, that would come in handy ever so often.

**Comment by hackcraft** [comment]
> Hash codes do not necessarily depend on equality.

Yes they do. By definition a hash code must be such that if eq(x, y) then eq(hash(x), hash(y)). As such you cannot define a hash code without reference to what "equality" means in a given context.

**Comment by breyed** [comment]
@hackcraft Good point. The correct statement is that `GetHashCode` is useful without `Equals` and vice versa.

**Comment by VSadov** [comment]
Generally LINQ takes Funcs to abstract away very open ended user action like projecting an element or filtering. Here we are dealing with equality and  IEqualityComparer  is specifically an interface that represents equality with particular expectations from its implementation.

For example if we are given two sequences that are arrays of different lengths, it would seem to be ok to just return "false". Caller is hardly expecting that IEqualityComparer.Equals will be called at least N times where N is the length of the shorter sequence. 
On the other hand if we are given ```Func<T, T, bool>``` , the expectations around sideeffects are not that clear. - it is just a Func after all.

The other reason is of course because we already have SequenceEqual and many other operators that rely on specific interfaces (IEqualityComparer, IComparer, etc). FWIW that was the direction taken when LINQ was initially created. In every case we could add an alternative that takes one or two Funcs instead, but that would lead to significantly larger API surface and it does not seem to be worth it.

Adding just couple Func-based-equality overloads here and there would seem inconsistent considering how element equality is parameterized in queries to the general

**Comment by breyed** [comment]
@VSadov I share your sentiment for keeping API surface area small and keeping consistency among the members. I agree that adding Func-based overloads for the equality and hashing operations would be a bad idea, especially considering the tight coupling between the two methods.

What makes the current design a bit of a hard pill to swallow is that of all the methods that take an IEqualityComparer, Contains, Distinct, Except, GroupBy, GroupJoin, Intersect, Join, SequenceEqual, ToDictionary, ToLookup, and Union. there is something unique about SequenceEqual. Unlike its cousins, it doesn't do indexed lookup. IEqualityComparer was handy, but it really was overspecified, since the hashing bit isn't necessary. SequenceEqual isn't quite as similar to other methods as it might first appear.

Writing good hashing functions can be a difficult task. The overspecification to require one can leave a programmer with kind of lousy options:

1. Write a replacement for SequenceEqual.
2. Create a quick-but-not-so-performant hash function, and hope that if someone writes code later that actually uses it, he will discover that it should be improved.
3. Throw an exception from GetHashCode and rely on SequenceEqual's undocumented behavior of not using it.
