### ISSUE TITLE
User Environment variable tests should pass on uap/uapaot

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#21231]
On the RS3 images, get/set of user environment variables should work and the tests should be enabled.

get/set of machine environment variables will be blocked by appcontainer and the tests shoudl be disabled for uap/uapaot.

**Comment by AtsushiKan** [comment]
The user key tests aren't disabled - they probe to see if the appcontainer will let them into the regkey. So they should just start running (and passing) on their own.

The machine key tests have always expected to be hit with a SecurityException (due to elevation) so with luck, nothing changes there.

It'd be nice at some point to remove the probe so the tests no longer have an excuse to fail, but it might also be to nice to wait on that until RS3 actually ships so that people running them on RS2 for other reasons don't see all the noise.

**Comment by danmosemsft** [comment]
>  remove the probe so the tests no longer have an excuse to fail

If we don't do this, the tests aren't giving much value since they can start failing and we wouldn't know. Perhaps we can introduce PlatformDetection.IsRS3 and use that.

Having said that I'm not sure there is any platform dependency here. They are adding the Env API to the WACK, and choosing to not constrain the behavior any more than AC already does. So they will work the same on RS2 -- in fact since WACK doesn't apply to our tests, the only thing necessary to change the behavior the user sees is for us to stop throwing in our Environment code (or rather in this case - to expose the API on our Environment class)

**Comment by AtsushiKan** [comment]
>They are adding the Env API 

Just want to make sure: are you talking about EnvironmentVariableTargets.Process (which use the env api) or EnvironmentVariableTargets.User (which use the registry api.)?

The Process ones aren't disabled or skipped or conditionalized at all (except maybe in Viktor's open PR but I requested he revert that part.)

**Comment by danmosemsft** [comment]
.Process. I don't know of any plans to have .User work in an app.

OK then great -- maybe I should have just checked that instead of opening this :)

**Comment by AtsushiKan** [comment]
We should remove the probing for .User now then (and just replace the test with "if (!PlatformDetection.WinRT)". Actually, judging from the F5 helix runs, the probing that's ther isn't getting the job done anyway...

**Comment by danmosemsft** [comment]
Seems to  be all good now and tests working
