### ISSUE TITLE
ObservableCollection.OnDeserialized NullRefs when called from JSON.Net

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/corefx#21304]
When JSON.Net deserializes ObservableCollection it will call OnDeserialized on it with the below callstack:
Newtonsoft.Json!Newtonsoft::Json::Serialization::JsonContract::<>c__DisplayClass1.<CreateSerializationCallback>b__0+0x57
Newtonsoft.Json!Newtonsoft::Json::Serialization::SerializationCallback.Invoke+0x25
Newtonsoft.Json!Newtonsoft::Json::Serialization::JsonContract.InvokeOnDeserialized+0x76
Newtonsoft.Json!Newtonsoft::Json::Serialization::JsonSerializerInternalReader.OnDeserialized+0xc4
Newtonsoft.Json!Newtonsoft::Json::Serialization::JsonSerializerInternalReader.PopulateList+0x268

The method will NullRef because the _monitor field is null.
I'm guessing this was caused by #20643 . There seems to be a mismatch where we override OnDeserialized, but not OnDeserializing where would initialize the monitor.

@justinvp @ViktorHofer

**Comment by vitek-karas** [comment]
Note that this is causing AppCompat failures (5 apps in Top2000).

**Comment by ViktorHofer** [comment]
@justinvp do you have some free cycles to look into it?
@vitek-karas does that only affect uapaot or also release/2.0.0 with coreclr?

**Comment by vitek-karas** [comment]
I can repro it on uapaot, I don't have an easy way to test this on coreclr... so I don't know. But given how and where it fails, I would expect it to be runtime independent.

**Comment by justinvp** [comment]
I'll take a look now.

**Comment by justinvp** [comment]
I can repro this on CoreCLR. The issue looks very similar to #18893 when deserializing `ConcurrentDictionary<TKey, TValue>` with Json.NET, which is set to the Future milestone.

Json.NET serializes the collection by enumerating it, without taking into account any of its fields like the binary serializer does, and deserializes it by adding the items back to the collection, without initializing the fields. However, it does still call the `OnSerializing`/`OnSerialized`/`OnDeserializing`/`OnDeserialized` methods.

In this case, when it calls `OnDeserialized`, a NullRef exception is thrown when we try to access the `_monitor` field because the field has not been initialized, unlike with binary deserialization, where the field would have been initialized from the serialized binary data.

A workaround is to simply check `if (_monitor != null)` before accessing it in `OnDeserialized`. I'll open a PR.

Does this need to be in release/2.0.0? While serializing `ObservableCollection<T>` to json might be common for UWP apps where `ObservableCollection<T>` is very often used in ViewModels with the MVVM pattern, I'm guessing it isn't as common for server-side apps on CoreCLR. Like #18893, I'm guessing a workaround isn't required for release/2.0.0.

**Comment by justinvp** [comment]
@JamesNK, FYI, a recent change I made to `ObservableCollection<T>` for an upcoming 2.0 preview will break Json.NET deserialization. Sorry about that. I opened #21322 to address the issue in .NET Core 2.1 and UWP 6.0. However, I'm not sure if the fix will meet the bar for 2.0, which is currently deep in escrow. If the fix isn't going to be taken for 2.0, would you like me to submit a PR to Json.NET that temporarily works around the issue for `ObservableCollection<T>`, like you did for `ConcurrentDictionary<TKey, TValue>`?

**Comment by JamesNK** [comment]
Sure but I just released a new version of json.net so it might be a while before it is publicly available
