### ISSUE TITLE
Error running UAP tests in clean repo: The Appx package's manifest is invalid.

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#21401]
In the log, immediately after the linking stuff

```
 Cannot create a file when that file already exists.
  Cannot create a file when that file already exists.
  Cannot create a file when that file already exists.
  Cannot create a file when that file already exists.
  Cannot create a file when that file already exists.
  Cannot create a file when that file already exists.
  Cannot create a file when that file already exists.
  Cannot create a file when that file already exists.
          1 file(s) copied.
  Got manifest file appxmanifest.xml

  FAILED 0x80080204 (The Appx package's manifest is invalid.

  )
  The system cannot find the file specified.
  The system cannot find the file specified.
  The system cannot find the file specified.
  Finished running tests.  End time= 9:31:39.88, Exit code = 1
```

I'm running `msbuild /T:RebuildAndTest /P:TargetGroup=uap`

Has anyone seen this before?

**Comment by danmosemsft** [comment]
@joperezr ?

**Comment by joperezr** [comment]
yeah, this will happen if you don't have the latest version of Windows (RS2) installed. We are now using a couple of properties that got recently added in order to be able to launch RemoteExecution tasks on their own thread. You could manually tweek the manifest locally in order for it to work again, but then some other tests will start failing since they require each reamoteExec to be on their own thread.

To tweek it manually as a temp workaround while you update Windows, try editing your manifest file(located at bin\testhost\<buildConfiguration>\Runner\AppxManifest.xml) and remove these two properties:
```
xmlns:uap4="http://schemas.microsoft.com/appx/manifest/uap/windows10/4"
uap4:SupportsMultipleInstances="true"
```
After doing that, you should be able to run the tests again.

**Comment by hughbe** [comment]
Updated to RS2 and everything works beautifully. Cheers

**Comment by joperezr** [comment]
good to know 😄
