### ISSUE TITLE
Overridden ToString not being called (IOrderedQueryable)

### ISSUE THREAD

**Issue by neil-119** [dotnet/corefx#2159]
I have a class which implements `IOrderedQueryable<T>`. With DNX 4, I can print out my LINQ queries as described in [this LINQ provider tutorial](http://blogs.msdn.com/b/mattwar/archive/2007/07/31/linq-building-an-iqueryable-provider-part-ii.aspx) (i.e. `Console.WriteLine(ExampleQueryable.Where(x => ...))` should call the overridden `ToString()` on my class implementing `IOrderedQueryable<T>`). It works fine in DNX 4, but with DNX Core, it skips my overridden `ToString()` completely (I tested this by placing a breakpoint), and instead seems to be calling `ToString()` on `System.Object`.

**Comment by VSadov** [comment]
Generally the overriding is very robust in CLR 
If something is truly overridden, it is very hard to force a 3rd party call to actually invoke the base implementation. So I assume ToString in this example is not getting overridden in the first place or you are using an instance of a different type.

I would need a more concrete repro scenario to tell why this is happening.

**Comment by neil-119** [comment]
I see. I created a repo here:
https://github.com/neil-119/CoreCLR-Queryable-Test

**Comment by VSadov** [comment]
@neil-119    Hi, sorry for not getting to this earlier. I have tried the referenced repro and I am having troubles compiling it. That could be because it beta5 bits, that might be unavailable (I cannot say I am an expert in DNX/Core packages and versioning)

If the problem is still reproducing, could you please update/fix the repro to make it work again?

Thanks!

**Comment by karelz** [comment]
@VSadov couldn't reproduce it, no response for 10 days -> closing. Feel free to reopen if there is more info.
