### ISSUE TITLE
X509Chain doesn't detect cert with invalid signature on Ubuntu, properly detected on Windows

### ISSUE THREAD

**Issue by mregen** [dotnet/corefx#21622]
I'm working UACTT test cases for the https://github.com/OPCFoundation/UA-.NETStandardLibrary. (VS2017 15.2/Ubuntu dotnet-dev-1.0.4)
This is a cert with invalid signature: [opcuactt_incorrectsign.zip](https://github.com/dotnet/corefx/files/1105376/opcuactt_incorrectsign.zip)

```
           // setup policy chain
            X509ChainPolicy policy = new X509ChainPolicy();

            policy.RevocationFlag = X509RevocationFlag.EntireChain;
            policy.RevocationMode = X509RevocationMode.NoCheck;
            policy.VerificationFlags = X509VerificationFlags.NoFlag;

            // build chain.
            X509Chain chain = new X509Chain();
            chain.ChainPolicy = policy;
            chain.Build(certificate);

```

On Windows, the chain status after this code for the attached cert contains `NotSignatureInvalid `and `UntrustedRoot`. However, on Ubuntu the chain status returned is just `UntrustedRoot`, so the cert with invalid signature can be used to start communication over a secure channel despite a security violation.

Any issues with my code for the security check? Is this a bug in the calling code or in the X509Chain implementation?

**Comment by stephentoub** [comment]
cc: @bartonjs

**Comment by bartonjs** [comment]
Congratulations, you found a rough spot :smile:.  .NET Core doesn't actually have a chain building algorithm, we leave that up to an underlying system library and we just reinterpret the answers.

When building a chain on a tampered self-issued certificate the responses are:

* Windows: NotSignatureValid, UntrustedRoot
* macOS: UntrustedRoot
* Other Unix (OpenSSL): UntrustedRoot.

All three agree UntrustedRoot because it doesn't byte-for-byte match a certificate in their trust lists.  Windows sort of goes the extra mile to tell you why.  OpenSSL has an opt-in to do check the signature on a self-issued cert, and since we've now seen someone be confused by not doing it we're considering telling OpenSSL to do the check in the future; but macOS doesn't (or, at least, doesn't obviously).

Things get... differently corner-cased when you have a tampered non-self-issued certificate.

* Windows:
  * Tampered cert: NotSignatureValid
  * Intermediate cert: OK
  * Root cert: OK
* Linux (OpenSSL):
  * Tampered cert: NotSignatureValid
  * Intermediate cert: OK
  * Root cert: OK
* macOS:
  * Tampered cert: PartialChain
  * Intermediate cert: (missing)
  * Root cert: (missing)

It's not that macOS thinks the signature is valid... it seems instead to be suggesting that the cert is fine... but it can't find an issuer with the right name whose key validates the signature... so the problem must be with finding an issuer.  Hence `PartialChain`.

They do all agree that the response from `chain.Build(cert)` (with default suppression flags) is `false`.

**Comment by mregen** [comment]
@bartonjs Are you planning to fix the behaviour on Mac/Linux for self signed certs? For us this is rather important because OPC UA happens to use a lot the self signed certs which are not necessarily part of the cert store, so we need to rely on the 'NotSignatureValid' to detect at least a tampered cert.
