### ISSUE TITLE
HttpClient::GetStreamAsync() - Leaking handles on *nix when not disposing HttpResponse 

### ISSUE THREAD

**Issue by icanhasjonas** [dotnet/corefx#21626]
Hello Community,

It seems that there's a leak using the short hand `GetStreamAsync()` on `HttpClient`

The `HttpResponseMessage` is never disposed and therefore leaking handles on the cURL version used on *nix by default.

Relevant: 
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L250-L256
https://github.com/dotnet/corefx/blob/4709a5cda50ec3d141b5b460bc05c8b576332659/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.cs#L84-L87

**Comment by davidsh** [comment]
Is this really a leak or just it hasn't yet been disposed by the finalizers?

cc: @stephen

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by davidsh** [comment]
I will say, thought, that disposing an HttpResponseMessage object will dispose everything inside of it which includes the .Content object and related response stream (which is returned by APIs like HttpClient.GetStreamAsync().  So, the code in HttpClient itself can not dispose of the internally used HttpResponseMessage. Otherwise, it would invalidate (dispose) the returned response stream.

**Comment by icanhasjonas** [comment]
Sure, the finalizes take care of it. 
But I've been running out of handles on unix machines specifically by not disposing the HttpResponseMessage, so I'm assuming it's related. And I understand you can't just dispose the response and expect the stream to be functional. I simply wanted to point out where the response is consumed and not disposed.

Instead of `GetStreamAsync()`, this works as a workaround for me;
```csharp
using( var response = await httpClient.GetAsync( /*...*/ ) ) 
using( var stream = await response.Content.ReadAsStreamAsync() ) {
  /* .... */
}
```

**Comment by stephentoub** [comment]
@icanhasjonas, can you share a small repro that highlights how handles are being leaked?  There should not be a difference in this behavior based on whether the response message is disposed or whether the response stream is disposed, since the former essentially just invokes the latter (disposing of the response message disposes the response content, and disposing the response content disposes the response stream).

**Comment by icanhasjonas** [comment]
So... it turns out, I may have been a bit premature in this.. I was totally convinced the issue was down to not disposing the `response`, but it turns out, a minimal reconstruct doesn't show the same issues I've experienced.

I'll hunt further.

Here's the repo btw, https://github.com/icanhasjonas/check-httpclient-leak/

**Comment by stephentoub** [comment]
Thanks for the update, @icanhasjonas.

**Comment by stephentoub** [comment]
@icanhasjonas, I'm going to close this issue for now.  Please re-open it when you have more info if you still find it to be due to a bug in .NET Core. Thanks!
