### ISSUE TITLE
Add ImmutableArray.Builder.Sort(Comparison<T> comparison)

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#2167]
List<T> has an overload of Sort that takes a delegate. It's useful when writing an inline comparer using a lambda:

```C#
list.Sort((x, y) => <comparison>);
```

**Comment by stephentoub** [comment]
cc: @AArnott, @terrajobst

**Comment by AArnott** [comment]
The issue title only mentions `ImmutableArray.Builder.Sort`. Should `ImmutableArray<T>.Sort` also be added? Does it already have it?
If it already has it, we should *definitely* add it to the Builder because we want the Builder to be no less useful than the immutable type. If we add it to the Builder, I think we should add it to the immutable type too.
