### ISSUE TITLE
Extract Resources from assemblies and write them into the runner's pri file for UAP

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#21692]
- [x]  Add MakePri.exe to buildtools package
- [x]  Modify [GenerateResourcesCode](https://github.com/dotnet/buildtools/blob/78260239e4db68ad5c2df774a27d5f9a54fd92e5/src/Microsoft.DotNet.Build.Tasks/GenerateResourcesCode.cs) to write the resources to a ResW file per assembly when building for UAP. This can be done through a parameter to the task when calling it in the build process.
- [x]  Bin place the ResW files to the runtime folder.

- [x]  Create test's assembly ResW file when building the test project and bin place it to the ResW runtime folder.

- [x]  Add task to merge ResW files to runner's PRI file using MakePri.exe

- [x] Delete mklink for runner's PRI file from RunTests.cmd for UAP

This are the steps that I will be following to extract the resources from the assemblies to merge them to the PRI file.

cc: @tarekgh @danmosemsft @weshaggard

**Comment by tarekgh** [comment]
@safern could you please hold a little on this PR. I am investigating some issue which may require us to change a little in this plan. thanks.

**Comment by safern** [comment]
> @safern could you please hold a little on this PR. I am investigating some issue which may require us to change a little in this plan. thanks.

Sure. No problem, just let me know whenever we are ready to move forward with this. Also feel free to update the steps in the issue description if you think we need to change something

**Comment by tarekgh** [comment]
@safern I have done the investigation and I confirm our original plan should be fine. just to let you know what I was investigating:

- I was looking at the real UWP apps created in VS and how the resources get handled there especially the framework libraries resources. I wanted to make sure our corefx is doing exactly what VS targets are doing. I found in F5 scenario, VS resource targets is merging the framework resources to the app PRI files which is exactly what we are going to do here. Note that, in .NetNative (i.e. uap-oat) if running inside app containers as appx app, the framework resources are not merged to the PRI. so if we enable running uap-oat in appcontainers in the future we should not merge the framework resources to the PRI.
- I was looking if there is any other non framework libraries we are using in our corefx tests. I was looking at that because if we do then we'll need to merge these libraries resources to the PRI too. I found we are using XUnit libraries but I found these libraries doesn't have resources :-) so we should be fine. I suggest to enable this scenario for the future use in case we use non framework library that has resources then we'll have a way to merge it resources to the PRI. this is not a priority now though

**Comment by tarekgh** [comment]
by the way, I'll try to look at the changes here later.

**Comment by safern** [comment]
@tarekgh thanks for the investigation! Is great to know that our original plan should work fine. Ok, so then we should just do this for UAPVertical. 

Shouldn't be much work to enable to extract the resources from non framework libraries as they are part of the Runtime folder right?

**Comment by tarekgh** [comment]
> Shouldn't be much work to enable to extract the resources from non framework libraries as they are part of the Runtime folder right?

So far we don't have any case like that. if we got one some day, either will be part of the test runtime restored early in the compilation or it may be used by specific test which can be part of the test output itself. let's not worry about this case now and we can handle that when we get a case.

**Comment by safern** [comment]
> So far we don't have any case like that. if we got one some day, either will be part of the test runtime restored early in the compilation or it may be used by specific test which can be part of the test output itself. let's not worry about this case now and we can handle that when we get a case.

Sounds like a plan. Thanks for confirming the plan is the good path to go.
