### ISSUE TITLE
Certain TcpClient (and potentially other class) constructors perform I/O

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#21729]
Performing I/O in a constructor is not supported by the UWP policies if that constructor is called on an UI thread.
We need to investigate if we need to change the implementation, obsolete the constructors or at least document this behavior.

**Comment by stephentoub** [comment]
> We need to investigate if we need to change the implementation

What's the exact limitation?  It's it a technical thing (i.e. an exception occurs) or a policy thing (i.e. it's frowned upon and apps that do it are disallowed).  If the former, I'm wondering if, for example, on UWP the I/O could just be moved off of the current thread, e.g. instead of:
```C#
Connect(hostname, port);
```
doing the equivalent of:
```C#
Task.Run(() => Connect(hostname, port)).GetAwaiter().GetResult();
```
to initiate the I/O from a non-UI thread.

**Comment by DavidGoll** [comment]
@stephentoub It's policy (to prevent perceivable UI hangs).
This issue was opened to determine whether these constructors are causing *perceivable* hangs.

**Comment by DavidGoll** [comment]
Triage: This is not expected to have any perceived impact. If it proves to be an issue (e.g., throwing on the constructor, hanging the UI), we will revisit. Will handle via new issues opened for the specific constructor(s) as they are opened.
