### ISSUE TITLE
HttpClientEKUTest hang in UAP

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#21738]
The HttpClientEKUTest tests require several prerequisites installed to run.
I've noticed that the tests hang if the root CA is installed. 

The tests make use of most of the server certificate callback and client certificates so it may be that this issue is related to (or just a side effect of) #21627 and #21628

**Comment by CIPop** [comment]
@davidsh @DavidGoll PTAL

**Comment by davidsh** [comment]
The tests are probably hanging because since I haven't implemented those 2 properties yet for HttpClient UAP, they are throwing PlatformNotSupporteException.  And I bet that exception is getting lost and the async task never completes with the error.

**Comment by DavidGoll** [comment]
Are we planning to implement those 2 properties for UWP6.0? If so, please reference the issue or issues.

**Comment by davidsh** [comment]
>Are we planning to implement those 2 properties for UWP6.0? If so, please reference the issue or issues.

Yes.  They are referenced above: #21627 and #21628.

**Comment by davidsh** [comment]
So, I've completed my checkins to implement the missing features in HttpClient for server certificate callback and client certificates.  And yet, the EKU tests are still hanging.

@CIPop  One question I have is why do these tests use a different "loopback" server from the rest of the HttpClient tests?

These tests are using this loopback server:
https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Net/HttpsTestServer.cs

And yet we already have a loopback server that we use and it already supports HTTPS:
https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Net/Http/LoopbackServer.cs

Why do we have two of them?

cc: @stephentoub

**Comment by CIPop** [comment]
@davidsh I've ported the loopback server that we had for a long time in .Net Framework. It supports several scenarios that are not supported on the current one. 
We should pick one that makes sense and unify at some point.

**Comment by davidsh** [comment]
Update:

Two tests are passing:
        public async Task HttpClient_NoEKUServerAuth_Ok()
        public async Task HttpClient_ClientEKUServerAuth_Fails()

One test is failing with "System.TimeoutException : The operation has timed out."
        public async Task HttpClient_NoEKUClientAuth_Ok()
It would have hung forever, but the test has a timeout.

One test is hanging forever (doesn't have any timeout logic):
        public async Task HttpClient_ServerEKUClientAuth_Fails()

**Comment by davidsh** [comment]
I know why the two tests are failing.  Both of the two tests use client certificates. The other two tests do not.

Both tests are trying to pop up UI:
![image](https://user-images.githubusercontent.com/7684835/28046624-da851e3a-6599-11e7-99e5-921f07ac8deb.png)

but can't due to the way the tests are written.

That UI happens when a UWP app want to use a client certificate that is installed in the per-user certificate store.  All of our client certificate tests (including the ones that Diego added to ClientWebSocket and the ones I added to HttpClient) end up showing that piece of UI during the test runner.

In fact, I was just discussing this issue with Diego today. If, instead, we had installed the client certificates into the app-container (test runner UWP in this case), the UI doesn't show because it doesn't need permission.  Our internal TAEF tests for Windows stuff has that capability to set up "test initialize" stuff such as loading certificates etc.  But our CoreFx UWP test runner doesn't. So, right now, we are putting them into the per-user certificate store.

This is probably also part of the hang I noticed when trying to use the loopback server for the HttpClient client certificate tests. I ended up using the Azure test server endpoint.

In general, our use of any loopback server will not work if we continue to need to have this UI be displayed during client certificate tests.

**Comment by davidsh** [comment]
cc: @Diego-Perez-Botero

**Comment by CIPop** [comment]
@davidsh The server EKU test should have failed as HttpClient analyzes the EKU and finds the wrong one (before the request is sent out). The no-EKU test is hanging most likely because the server side is not receiving any request with a client certificate. Both cases are related with the PR you've submitted yesterday.

The HttpsTestClient/HttpsTestServer have logging: try to obtain the logs and see where each of them are hanging.

**Comment by CIPop** [comment]
@davidsh I've properly installed all certificates and all tests pass if the user presses "Allow" within the 15s timeout.
