### ISSUE TITLE
Disabled Performance tests for UAP in arm have to be investigated and re-enabled

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#21754]
System.Numerics.Vectors.Performance.Tests and System.Collections.Performance.Tests where hanging in official build for UAP in ARM.

We need to investigate if it was an actual hang or just because the ARM computers are slower.

They where disabled in: https://github.com/dotnet/corefx/pull/21674

cc: @joperezr @danmosemsft

**Comment by danmosemsft** [comment]
@jorive I asked this somewhere else but I can't find it -- will we/do we record perf from ARM runs? If not we don't need this until we do.

**Comment by joperezr** [comment]
I believe we don't but even if we did this seems to be a bug in our infrastructure, since the test projects actually have 0 tests to run, but from looking at the logs the Launcher is timing out waiting for the application to finish executing. After debugging it on a ARM machine (without being able to repro) I suspect that what is happening is that since we have 0 tests to run the app is quitting too fast, so the launcher doesn't register it and keeps waiting.

**Comment by danmosemsft** [comment]
Looking at the launcher code, it isn't obvious why the process exiting immediately would cause it to hang. It does WaitForSingleObject on the process handle, which one would expect to return immediately. It would need debugging if we want to fix that.

The launcher does accept a `timeout` parameter. I'm not sure whether we'd be any better off though. It would still time out it just wouldn't be Helix doing it.

**Comment by joperezr** [comment]
agreed, this needs debugging. Unfortunately, being ARM machines there are not many good debuggers I'm familiar with out there. If this becomes an issue were assemblies that do have tests start seeing this I think we should fix it but for now we could postpone it.

**Comment by ViktorHofer** [comment]
Outdated, closing. we don't run perf tests on UAP and we moved all tests over to dotnet/benchmark.
