### ISSUE TITLE
DSA-SHA1 SignedXml issues .netcore 2.0

### ISSUE THREAD

**Issue by eByte23** [dotnet/corefx#21811]
I have a SAMLlibrary which I am trying to piece together on .net core 2.0, however I have hit an issue it some pre-existing tests.

The tests pass fine on net461 but when using netcoreapp2.0 fail.

All the test is doing is 
```c#
  private static bool VerifySignature(XmlDocument assertion)
        {
            var signedXml = new SignedXml(assertion.DocumentElement);

            var nodeList = assertion.GetElementsByTagName("Signature", "http://www.w3.org/2000/09/xmldsig#");
            signedXml.LoadXml((XmlElement)nodeList[0]);

            Assert.NotNull(signedXml.Signature);

            return signedXml.CheckSignature();
        }

```

The xml files that is being passed in is located in the tests here:
[DSA-SHA1 Saml2Assertion_01](https://github.com/eByte23/SAMLSilly/blob/dev/2.0/tests/SAMLSilly.Tests/Assertions/Saml2Assertion_01)
[DSA-SHA1 Saml2Assertion_02](https://github.com/eByte23/SAMLSilly/blob/dev/2.0/tests/SAMLSilly.Tests/Assertions/Saml2Assertion_01)

All other non-DSA pass e.g. RSA1,RSA256 just these I believe to be completely valid XMLDSIGS validated online as well as on dotnet FF.

Any help would be appreciated as this is a blocker for me/

**Comment by bartonjs** [comment]
@eByte23 When you say the tests fail, I assume you mean they return false when true was expected?

**Comment by eByte23** [comment]
@bartonjs my apologies I wasn't very clear.
These signatures should be 'Valid'. They pass validation in net 461 and other versions of FF but when running tests against netcoreapp2.0 they fail.

For example the current code I have in [this branch](https://github.com/eByte23/SAMLSilly/blob/dev/2.0/tests/SAMLSilly.Tests).

when running `dotnet test --framework netcoreapp2.0` the tests fail
when running  `dotnet test --framework net461` the tests pass (correct expected result)

**Comment by karelz** [comment]
@krwq @bartonjs please check if it is important scenario for 2.0. Moving to 2.1 for now.

**Comment by krwq** [comment]
@eByte23 any particular reason why to choose deprecated DSA algorithm?

Automatic validating with DSA is currently not supported in netstandard. I currently do not know about the future plans. (@karelz & @bartonjs would have to comment)

For your case one way to validate would be to extract DSA key manually, i.e.:

```csharp
        private static AsymmetricAlgorithm GetFirstX509PublicKey(XmlDocument doc)
        {
            KeyInfoX509Data keyInfo = new KeyInfoX509Data();
            var elements = doc.GetElementsByTagName("X509Data", "http://www.w3.org/2000/09/xmldsig#");
            var keyNode = (XmlElement)elements[0];
            keyInfo.LoadXml(keyNode);
            foreach (var cert in keyInfo.Certificates)
            {
                X509Certificate2 x509cert = cert as X509Certificate2;
                if (x509cert != null)
                    return x509cert.PublicKey.Key;
            }
            
            return null;
        }
```

and pass the key to the CheckSignature method. **If you simply do that it will be really unsafe as anyone can change your document and change signature to use different key and this will gladly verify it since we use first key here**.

I'm not the expert in this area so take it with the grain of salt - @bartonjs would have to comment here:
I believe simplest way to secure yourself would be to manually validate if you trust the public key used for signing. I.e. have a list of trusted public keys in your app and only verify if public key is known to you otherwise assume document is not trusted. If you do not actually know public key used for signing and got a third party telling you which public keys should you trust it will be more complicated - you would need to verify certificate chain and check if you trust it and also check that against some known certificate revocation list - possibly there exists some .NET API which could help with this but I'm not really familiar with those. It is really easy to get this wrong (making the test pass is easy but that will not guarantee your security) so if your case is more complicated I recommend to either wait for @bartonjs comment (possibly with some better workaround) or simply switch to RSA certificates.

**Comment by krwq** [comment]
@karelz we removed this capability in this PR: https://github.com/dotnet/corefx/pull/19189 - we should either close this or change milestone

**Comment by bartonjs** [comment]
Oh, yep, we documented it.  https://github.com/dotnet/corefx/wiki/ApiCompat#signedxml-will-not-be-able-to-find-public-key-for-dsa-certificates.  Thanks for reminding me, @krwq.

@eByte23 The problem is that DSA is part of netcoreapp20, but not netstandard20.  We built the SignedXml package as a netstandard20 package, and therefore it can't knowingly talk about DSA.

.NET Framework, until recently, only supported 1024-bit DSA, which NIST classifies as having 80 bits of security (per http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-57pt1r4.pdf, table 2), and unsuitable for modern utilization.  So not supporting DSA (FIPS 186-2) signed SAML tokens shouldn't be a severe loss.

(Even with FIPS 186-3 DSA, which allows larger keys, you need DSA+SHA2 support to get better than 80 bits of security; and we don't have that for SignedXml in either CoreFX or NetFX)

**Comment by karelz** [comment]
@bartonjs can help drive the decision.

**Comment by eByte23** [comment]
Hi guys.

@krwq I'm keeping DSA so not to break support for SamlServers that may be using that, no DSA is not saml spec but there originally where a lot of servers that used DSA.

@bartonjs DSA I can see when using netstandard2.0 so I do not understand what you mean by it cannot be access by singedxml. Also if it was not accessible it should throw NotImplemented or something not just work but return not valid.

So thus my confusion on the matter.

If this is not going to be supported at all then that's all good and well but it should throw and exception like not supported or something.

**Comment by eByte23** [comment]
Also do note I currently support RSA1,RSA256,RSA512. This is purely just keeping legacy support.

**Comment by bartonjs** [comment]
Sorry, the `GetDSAPublicKey()` (extension) method for certificates isn't in netstandard20, so SignedXml can't figure out what the key is.

The behavior of SignedXml is to ignore any certificates it doesn't know about, and try the ones it does.  If it finishes without finding a public key that validated successfully then it returns false.

Yes, this is a behavioral change from .NET Framework; but it's on our breaking changes from .NET Framework warning list.

**Comment by eByte23** [comment]
@bartonjs Okay no worries looked through it all I see what you mean. No worries, I think I'll just drop DSA then if it becomes and issue I'll implement it manually as suggested. 

Thanks.
