### ISSUE TITLE
FormatException for invalid dates should show the date and format that were passed in

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#21825]
Currently, we just get an error like:

> FormatException: String was not recognized as a valid DateTime.

This is a pain as you don't know what actually went wrong where. For example, I'm parsing a CSV file and the dates it contains are constantly changing their formats. So when something goes wrong, it's unclear and I have to catch and rethrow the exception, taking note of the date and format

**Comment by danmosemsft** [comment]
I recently added the path to IO exceptions (https://github.com/dotnet/coreclr/commit/6ba74dc2a7194f8d6c86c3aeab572a074ef645c8) and it was useful when we investigated test failures.

I think it would be a great idea to include values in more error messages. There are many others in this format:

```xml
C:\git\coreclr\src\mscorlib\Resources\Strings.resx:
 2235:     <value>String was not recognized as a valid Boolean.</value>
 2241:     <value>String was not recognized as a valid DateTime.</value>
 2247:     <value>String was not recognized as a valid DateTime because the day of week was incorrect.</value>
 2256:     <value>String was not recognized as a valid TimeSpan.</value>
 2325:     <value>The string was not recognized as a valid DateTime. There is an unknown word starting at index {0}.</value>
C:\git\corefx\src\System.Private.Xml\src\Resources\Strings.resx:
  652:     <value>The string was not recognized as a valid Uri.</value>
```

and many others in other forms eg

```xml
    <value>Invalid digits for the specified base.</value>
    <value>Invalid length for a Base-64 char array or string.</value>
    <value>Format String can be only "G", "g", "X", "x", "F", "f", "D" or "d".</value>
    <value>String must be exactly one character long.</value>
    <value>The collection backing this List contains too many elements.</value>
...etc
```

If we are incurring the cost of an exception, presumably it's OK to also format an error string. @stephentoub would you have any concerns about that?

**Comment by stephentoub** [comment]
> @stephentoub would you have any concerns about that?

I think it's ok.  Historically we had some concerns about information disclosure in exception messages, but from subsequent discussions decided we're not worried about that.

**Comment by danmosemsft** [comment]
@hughbe do you have an interest in attacking some of these? As I mentioned there's a lot of places that could potentially be improved this way.

**Comment by hughbe** [comment]
Yeah I'd be happy to - I'm kinda busy in these final few weeks so it might have to wait till the weekend.

These are the kind of small changes that add up and make people's lives easier :)

**Comment by danmosemsft** [comment]
I wonder if we should have a bigger tracking issue since you're not going to fix them all together.

**Comment by joperezr** [comment]
Hey @hughbe still interested in doing this? if not then we can flag it as up-for-grabs

**Comment by hughbe** [comment]
Unfortunately I'm probably not going to have the time so please. Thanks!

**Comment by joperezr** [comment]
@hughbe  no problem, thanks for reporting the problem!

*Next Steps*:
 - Let's keep this issue specific to Format Exception on dateTime objects. The idea next, is to figure out what info do we want to add to the exception. 

cc: @tarekgh since he is familiar with the type.

**Comment by tarekgh** [comment]
More info in the exception makes sense to me. there are some places deep in the stack that may not have enough context but at least can display something helpful.

**Comment by FSou1** [comment]
Probably it's a good candidate to start:
```
<data name="Format_BadDateTime" xml:space="preserve">
  <value>String was not recognized as a valid DateTime.</value>
</data>
```
I propose to extend it with the parsed value: `String '{0}' was not recognized as a valid DateTime`.

1. Have you got any concerns about backward compatibility based on exceptions messages?
2. Are there any unit tests with `DateTime.ParseExact` coverage?

**Comment by stephentoub** [comment]
> Have you got any concerns about backward compatibility based on exceptions messages?

No, tweaking exception messages is fine.

> Are there any unit tests with DateTime.ParseExact coverage?

Yes:
https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/DateTimeTests.cs
https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/DateTimeTests.netcoreapp.cs

**Comment by dezsiszabi** [comment]
I started working on this in my coreclr fork and while running the corefx tests with my local coreclr changes related to this issue, I got the below test failure:

> h:\Practice\GitHub\corefx\Tools\tests.targets(492,5): error : One or more tests failed while running tests from 'System.Globalization.Tests' please check h:\Practice\GitHub\corefx\bin/tests/System.Globalization.Tests/netcoreapp-Windows_
NT-Debug-x64/testResults.xml for details! [h:\Practice\GitHub\corefx\src\System.Globalization\tests\System.Globalization.Tests.csproj]
h:\Practice\GitHub\corefx\Tools\tests.targets(492,5): error : One or more tests failed while running tests from 'System.Linq.Expressions.Tests' please check h:\Practice\GitHub\corefx\bin/tests/System.Linq.Expressions.Tests/netcoreapp-Wi
ndows_NT-Debug-x64/testResults.xml for details! [h:\Practice\GitHub\corefx\src\System.Linq.Expressions\tests\System.Linq.Expressions.Tests.csproj]
h:\Practice\GitHub\corefx\Tools\tests.targets(492,5): error : One or more tests failed while running tests from 'System.Drawing.Common.Tests' please check h:\Practice\GitHub\corefx\bin/tests/System.Drawing.Common.Tests/netcoreapp-Window
s_NT-Debug-x64/testResults.xml for details! [h:\Practice\GitHub\corefx\src\System.Drawing.Common\tests\System.Drawing.Common.Tests.csproj]
h:\Practice\GitHub\corefx\dir.traversal.targets(77,5): error : (No message specified) [h:\Practice\GitHub\corefx\src\tests.builds]

I only started investigating the error related to the System.Globalization.Tests failure, since that seems to be the most related to my changes which are only in `src/mscorlib/Resources/Strings.resx` and `src/mscorlib/shared/System/Globalization/DateTimeParse.cs`.

One of the test failures is the following:

<test name="System.Globalization.Tests.DateTimeFormatInfoFirstDayOfWeek.FirstDayOfWeek(format: DateTimeFormatInfo { AbbreviatedDayNames = [\&quot;Sun\&quot;, \&quot;Mon\&quot;, \&quot;Tue\&quot;, \&quot;Wed\&quot;, \&quot;Thu\&quot;, ...], AbbreviatedMonthGenitiveNames = [\&quot;Jan\&quot;, \&quot;Feb\&quot;, \&quot;Mar\&quot;, \&quot;Apr\&quot;, \&quot;May\&quot;, ...], AbbreviatedMonthNames = [\&quot;Jan\&quot;, \&quot;Feb\&quot;, \&quot;Mar\&quot;, \&quot;Apr\&quot;, \&quot;May\&quot;, ...], AMDesignator = \&quot;AM\&quot;, Calendar = GregorianCalendar { AlgorithmType = SolarCalendar, CalendarType = Localized, Eras = [...], IsReadOnly = False, MaxSupportedDateTime = 9999-12-31T23:59:59.9999999, ... }, ... }, expected: Sunday)" type="System.Globalization.Tests.DateTimeFormatInfoFirstDayOfWeek" method="FirstDayOfWeek" time="0.1440871" result="Fail">
  <failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\r\nExpected: Sunday\r\nActual:   Monday]]></message>
    <stack-trace><![CDATA[   at System.Globalization.Tests.DateTimeFormatInfoFirstDayOfWeek.FirstDayOfWeek(DateTimeFormatInfo format, DayOfWeek expected) in h:\Practice\GitHub\corefx\src\System.Globalization\tests\DateTimeFormatInfo\DateTimeFormatInfoFirstDayOfWeek.cs:line 23]]></stack-trace>
  </failure>
</test>

The test expects the first day of week to be Sunday in the en-US culture. In Windows I changed the first day of week to be Monday, so `new CultureInfo("en-US").DateTimeFormat.FirstDayOfWeek` gives back Monday for me. Is this an issue in the test or an issue with `DateTimeFormatInfo.FirstDayOfWeek`?

**Comment by danmosemsft** [comment]
The test should not be broken by your windows settings.

**Comment by dezsiszabi** [comment]
So just to confirm, that test is incorrect in its current form, right?

**Comment by danmosemsft** [comment]
Right it some how needs to be made more robust, eg to get the day of week through another API and compare the value, or just check there is some non empty value, or set the first day of the week just in the test, get, then set back. The latter seems appealing if it can be done through a.NET API.

**Comment by Mpdreamz** [comment]
Taking a look at this one during the hackathon

**Comment by ViktorHofer** [comment]
I believe this issue can be closed as the exceptions already contain all the necessary information.

> Additionally this issue also states that the value of the format string should be in the exception message, when using ParseExact. This is not yet the case.

http://source.dot.net/#System.Private.CoreLib/shared/System/Globalization/DateTimeParse.cs,4624
This shows that if a format was given it's being logged inside the exception message.
