### ISSUE TITLE
Partial send support for ClientWebSocket on UWP

### ISSUE THREAD

**Issue by caesar1995** [dotnet/corefx#22053]
The UWP implementation of ClientWebSocket (WinRTWebSocket.cs) buffers the entire message before it can pass it to the underlying WinRT MessageWebSocket. This is due to missing support for sending partial messages in WinRT MessageWebSocket.

#21102 improved the receive path of partial messages in UWP, but the existing WinRT APIs still lack partial message support in the send path.

System.Net.HttpListener HttpListenerWebSocketTests will hang in UAP mode.

**Comment by caesar1995** [comment]
This is the test case causing the hang: `ReceiveAsync_ReadWholeBuffer_Success()`

**Comment by CIPop** [comment]
@Diego-Perez-Botero could this be related to client-side changes for WebSockets?

**Comment by caesar1995** [comment]
The test will only hang when `endOfMessage == false`

After discussion with @Diego-Perez-Botero, the root cause of this issue is because ClientWebSocket's UWP implementation is using the winRT websocket, which doesn't support sending partial message.
The detailed explanation can be found here: #21102

**Comment by caesar1995** [comment]
I have a question though, can we disable a test using [Activeissue] of a closed issue? If not, should we re-open #21102?

@davidsh

**Comment by davidsh** [comment]
>I have a question though, can we disable a test using [Activeissue] of a closed issue? If not, should we re-open #21102?

If you need to disable a test forever due to platform differences, you need to use SkipOnTargetFramework attribute and not ActiveIssue attribute.  We have many examples of this in other tests such Http.

**Comment by davidsh** [comment]
See: https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs#L181

for example.

In your case, you would use TargetFrameworkMonikers.Uap to disable that test for UAP forever.  Please add an appropriate explanation in the attribute field.

**Comment by caesar1995** [comment]
>Please add an appropriate explanation in the attribute field.

sure.

**Comment by Diego-Perez-Botero** [comment]
As Caesar mentioned, only the test variants where _endOfMessage_ is **false** are hanging. This is because the UWP implementation of ClientWebSocket ([WinRTWebSocket.cs](https://github.com/dotnet/corefx/blob/472b8d8ec212c2afb107dea305b4624c4989a79f/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WinRTWebSocket.cs)) buffers the entire message before it can pass it to the underlying WinRT MessageWebSocket. This is due to missing support for _sending_ partial messages in WinRT MessageWebSocket.

#21102 improved the _receive_ path of partial messages in UWP, but the existing WinRT APIs still lack partial message support in the _send_ path.

**Comment by Diego-Perez-Botero** [comment]
IMHO, #21102 should remain closed. The _send_ path improvements should be tracked with a different issue.

**Comment by CIPop** [comment]
/cc @DavidGoll 
This is a behavior difference from .Net Desktop. Let's keep this open and have an ActiveIssue for now until we decide it's OK to ship as-is or document.

**Comment by davidsh** [comment]
>until we decide it's OK to ship as-is or document.

If we ship as-is (and thus have a behavior difference from .NET Framework), we need to document it here:
https://github.com/dotnet/corefx/wiki/ApiCompat

**Comment by DavidGoll** [comment]
@caesar1995 document this as a compat issue... there will not be a fix for this in RS3, thus not in UWP6.0.

**Comment by DavidGoll** [comment]
cc: @mconnew

**Comment by caesar1995** [comment]
The behavior now is documented by @davidsh : https://github.com/dotnet/corefx/wiki/ApiCompat

**Comment by CIPop** [comment]
> Can we close this issue?

I think it's good that we have documented the limitation but I still think fixing this may be valuable for developers in the future. Unfortunately the fix depends on Windows and cannot be achieved by modifying CoreFX.

**Comment by davidsh** [comment]
>

Latest Windows 10 OS now has partial send support for the WinRT WebSocket APIs. But .NET Core isn't yet using that in the current WebSockets.Client WinRTWebSocket class.

However, the new plan is to switch away from using the WinRT WebSocket APIs and instead use the managed WebSocket implementation for all platforms (including UWP).  See: #29644

So, closing this issue since we're tracking #29644.
