### ISSUE TITLE
TypeInfo.GetGenericArguments() differences between Core/Full CLR

### ISSUE THREAD

**Issue by smudge202** [dotnet/corefx#2214]
Our [Compose project](https://github.com/smudge202/compose) is failing tests run with CoreCLR (though passing with full .Net). The issue is when reflecting a particular interface:

```c#
public interface IFoo<TBase> 
{ 
    void Method<TDerivative>(TDerivative derivative) where TDerivative : TBase; 
}
```

Specifically, calling `TypeInfo.GetGenericArguments()` on `typeof(IFoo<Bar>).GetGenericTypeDefinition()` with the Full CLR will return a `Type[]` containing a single `Type` with the name `TBase`, though details such as `FullName` are null.

In CoreCLR the method returns a `TypeInfo[]` containing no elements.

Perhaps there's a different way of achieving this?

The linked repo demonstrates the above issue on [this line](https://github.com/smudge202/compose/blob/dev/src/Compose/DynamicExtensions.cs#L96), which causes [this test](https://github.com/smudge202/compose/blob/dev/tests/Compose.Tests/EmissionTests.cs#L314) to fail.

**Comment by nguerrera** [comment]
Hmm, it took me a while to figure out how that line even compiles for you on DNX Core, but then I found [Compose/TypeExtensions.cs](https://github.com/smudge202/compose/blob/5d52a8e6d79be47fa29c04b729aa3a4ea5e2780f/src/Compose/TypeInfoExtensions.cs#L8).  ;)

There is actually no TypeInfo.GetGenericArguments() in the .NET Core surface. The new surface makes a distinction between generic *parameters* (which generic definitions have) and generic *arguments* (which generic instances) have. In this case since you always go to the definition, you want TypeInfo.GenericTypeParameters. 

If you need to retain that extension method and have it work like the desktop Type.GetGenericArguments, you could rewrite is as follows:
```diff
public static TypeInfo[] GetGenericArguments(this TypeInfo typeInfo) 
{
-    return typeInfo.GenericTypeArguments.Select(x => x.GetTypeInfo()).ToArray(); 
+    IEnumerable<Type> arguments = typeInfo.IsGenericTypeDefinition 
+                                ? typeInfo.GenericTypeParameters
+                                : typeInfo.GenericTypeArguments;
+    return arguments.Select(x => x.GetTypeInfo()).ToArray(); 
} 
```

**Comment by smudge202** [comment]
Ohhhh, of course! Yeh, I get completely lost in that repo too because of all the extensions. It took me 4 attempts to report the issue, because each time I was reporting my own extension method as opposed to the actual .Net method. :D

Extra thanks for providing the fix, @nguerrera . You're a boss. :) I'll try to remember the Argument/Parameter distinction going forward.
