### ISSUE TITLE
UTF8Encoding should support encoding/decoding of unpaired surrogates

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#2217]
According to RFC 3629 encoding/decoding unmatched surrogates should be disallowed:

"The definition of UTF-8 prohibits encoding character numbers between U+D800 and U+DFFF, which are reserved for use with the UTF-16 encoding form (as surrogate pairs) and do not directly represent    characters."

However, this hasn't been followed by real world encoders/decoders. For example, the ECMA-335 standard encodes string arguments of custom attributes using UTF8 and the compilers allowed unpaired surrogates in the attribute argument. Another example is PDB - the file paths in PDB are stored as UTF8 encoded strings and unpaired surrogates are also allowed. The same for values of local string constants (e.g. `const string surrogate = "\ud800"`).

To avoid breaking changes Roslyn needs to allow unpaired surrogates in the above cases and the MetadataReader should also use a variant of UTF8 encoding that is able to decode them. Currently Roslyn has a custom implementation of UTF8 encoder originating from CCI. In general, it seems that pragmatically a UTF16-UTF8 round-tripping is desirable in certain scenarios and UTF8Encoding should support it.

I propose to add a constructor to UTF8 Encoding that takes a bool allowUnpairedSurrogates (false by default) that can be used by both Roslyn and MetadataReader.

**Comment by KrzysztofCwalina** [comment]
cc @krwq

**Comment by tarekgh** [comment]
@tmat when encoding UTF16 "\ud800" to UTF8 bytes, what you expect to get as bytes i few allow the encoding? I am asking because there could be a workaround you can use but before I propose it I need to understand what you expect.

**Comment by tmat** [comment]
I expect this:
http://source.roslyn.io/#Microsoft.CodeAnalysis/PEWriter/BlobUtilities.cs,15d9d2fb5564ddbc,references

**Comment by tarekgh** [comment]
You can achieve this result by simple implementation of custom EncoderFallback and EncoderFallbackBuffer

https://msdn.microsoft.com/en-us/library/system.text.encoderfallback(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/system.text.encoderfallbackbuffer(v=vs.110).aspx

Encoding fallback mechanism is originally introduced to address the scenarios like yours.

**Comment by tmat** [comment]
Yes, i know. The point is I shouldn't need to be doing this.

**Comment by tarekgh** [comment]
why? the default behavior is conforming with the standard. any other behavior is achieved by the fallback mechanism. why we need to add more configuration to the API to let it do that while there is already unified way to do it? also looks this is not main stream case either as we didn't get anyone raising this issue.

**Comment by tmat** [comment]
Are encoding fallbacks available on CoreCLR?

**Comment by tarekgh** [comment]
Yes it is supported in System.Text.Encoding 4.0.10.0 contract

**Comment by tmat** [comment]
Can you point me to an example of how this is supposed to be used?

**Comment by tarekgh** [comment]
You may look at https://github.com/dotnet/corefx/blob/ceae1d38c93e3f53210ad91884dabc1bd6d30a90/src/System.Text.Encoding.Extensions/tests/Fallback.cs 
it has simple example which you can modify to make it work the way you like. let me know if you want me help with that too.

**Comment by tmat** [comment]
I don't understand what GetNextChar is supposed to do? I need to return 3 bytes for the unpaired surrogate. Where do I return those bytes?

**Comment by tarekgh** [comment]
first you may not need to implement anything if you just used the replacement fallback. something like 

            Encoding utf8 = Encoding.GetEncoding("utf-8", new EncoderReplacementFallback("\uFFFD"), new DecoderReplacementFallback("\uFFFD"));
            byte[] bytes = new byte[10];
            int count = utf8.GetBytes("\ud800", 0, 1, bytes, 0);

to answer your question just in case you still need to implement your fallback, the way fallback work is it'll pass you the character that cannot encode. this done by the call to the method EncoderFallbackBuffer.Fallback methods. if your Fallback methods implementation return true, this means you can handle the fallback for such character. this will cause EncoderFallbackBuffer.GetNextChar get called and in this method you need to return the char and not bytes. in your case you'll need to return '\uFFFD' to match your original implementation. GetNextChar will keep get called again till you return 0 that is because you can fallback using multiple characters and not only one character. 
please let me know if there is anything unclear here.

**Comment by tmat** [comment]
From what you describes it looks to me that the fallbacks are not designed to support the scenario.

I don't need to replace an unpaired surrogate with another character. I need to encode it as 3 bytes (using the encoding I described above). I don't see how I can achieve it using the fallbacks.

**Comment by tarekgh** [comment]
actually you are doing exactly the same as the fallback is doing. you have the code which is doing the check 
                     const char ReplacementCharacter = '\uFFFD';
                            if (!allowUnpairedSurrogates)
                            {
                                c = ReplacementCharacter;
                            }
and then you encode \uFFFD to utf8 using 

(byte)(((c >> 12) & 0xF) | 0xE0)
(byte)(((c >> 6) & 0x3F) | 0x80)
(byte)((c & 0x3F) | 0x80)

if you use 
        Encoding utf8 = Encoding.GetEncoding("utf-8", new EncoderReplacementFallback("\uFFFD"), new DecoderReplacementFallback("\uFFFD"));
        byte[] bytes = new byte[10];
        int count = utf8.GetBytes("\ud800", 0, 1, bytes, 0);

you will get the exact result

**Comment by tmat** [comment]
Not quite. That replacement with \uFFFD only happens when we *don't* allow unpaired surrogates. If we do the surrogate itself gets encoded into the 3 bytes.

**Comment by tmat** [comment]
(the method I pointed at above implements 2 kinds of encodings).

**Comment by tarekgh** [comment]
in your code if you have valid paired surrogate you'll encode it in 4 bytes 

                            // surrogate pair
                            if (IsHighSurrogateChar(c) && charPtr < strEnd && IsLowSurrogateChar(*charPtr))
                            {
                                int highSurrogate = c;
                                int lowSurrogate = *charPtr++;
                                int codepoint = (((highSurrogate - 0xd800) << 10) + lowSurrogate - 0xdc00) + 0x10000;
                                ptr[0] = (byte)(((codepoint >> 18) & 0x7) | 0xF0);
                                ptr[1] = (byte)(((codepoint >> 12) & 0x3F) | 0x80);
                                ptr[2] = (byte)(((codepoint >> 6) & 0x3F) | 0x80);
                                ptr[3] = (byte)((codepoint & 0x3F) | 0x80);
                                ptr += 4;
                                continue;
                            }

and that is what UTF8 encoding will do too. the fallback will get involved only if you have invalid surrogate.
I suggest if you have some test work with your implementation, try to run it with the way I suggested 

Encoding utf8 = Encoding.GetEncoding("utf-8", new EncoderReplacementFallback("\uFFFD"), new DecoderReplacementFallback("\uFFFD"));

and then let me know what differences you are seeing.

**Comment by tmat** [comment]
The difference for "\uD800" is:

```ED-A0-A0``` (our impl with allowUnpairedSurrogates = true)
```EF-BF-BF``` (our impl with allowUnpairedSurrogates = false) 
```EF-BF-BF``` (fallback)

**Comment by tarekgh** [comment]
Will look at  that and will get back to you. thanks.

**Comment by tmat** [comment]
Thanks Tarek.

**Comment by tarekgh** [comment]
Thanks Tomáš for your patience 

I had a chance to look more at that. There is no good way to encode the invalid surrogate the way you mentioned here. I mean encoding \uD800 to { 0xED, 0xA0, 0x80 }. And it is still not a good idea to support this scenario in the framework because we always promise encoding the string with valid bytes in the target encoding. If we produce something like {0xED, 0xA0, 0x80}, those are invalid byte sequence for UTF8 and it will not be right to have it. This is why our encoders fallback is using Unicode characters and not allowing passing fallback bytes.

I understand in your scenario you have used to produce such sequence and you may need to keep it for compatibility reason but I am wondering how the output really get used if the byte sequence is invalid anyway? Note that you cannot even round trip these sequence to UTF16 without special handling too or you’ll end the \uFFFD fallback again.

My suggestion is, if possible you deprecate this behavior and always use the case allowUnpairedSurrogates = false. Otherwise you’ll need to keep your current code.

**Comment by tmat** [comment]
@tarekgh We won't deprecate this. This is a feature and not a bug.

See https://en.wikipedia.org/wiki/UTF-8#WTF-8

**Comment by karelz** [comment]
We need formal API proposal -- a flag on UTF8Encoding class.

**Comment by JonHanna** [comment]
Why not
```
WTF8Encoding : Encoding
{
}
```
?

This could provide the encoding needed while remaining distinct from UTF-8, not called UTF-8 (though perhaps called something else, I'm pretty sure Wobbly Transformation Format is a tongue-in-cheek reference to another expansion of the same acronym), and need not even necessarily be in System.Text.

**Comment by tarekgh** [comment]
@JonHanna WTF8Encoding is option too we can consider. the question is, is it better to have whole new class to handle the unpaired surrogate or can we just let UTF8Encoding class support this with some property or flag? 

if we are going to have WTF8Encoding, I think it should be inherited from UTF8Encoding. but anyway we need to see the complete proposal so we can discuss it. Thanks.

**Comment by bendono** [comment]
I am a little concerned about this proposal. Unpaired surrogates are invalid in UTF-16, and the corresponding UTF-8 is ill-formed. In fact, this very issue is handled in the [Unicode FAQ](http://unicode.org/faq/utf_bom.html#utf8-5):

> Q: How do I convert an unpaired UTF-16 surrogate to UTF-8?
> 
> A different issue arises if an unpaired surrogate is encountered when converting ill-formed UTF-16 data. By represented such an unpaired surrogate on its own as a 3-byte sequence, the resulting UTF-8 data stream would become ill-formed. While it faithfully reflects the nature of the input, Unicode conformance requires that encoding form conversion always results in valid data stream. Therefore a converter must treat this as an error. [AF]
> 

I realize that there are use cases because some external processes do not strictly enforce the rules. However, the line needs to be drawn somewhere. Not enforcing well-formed data is **infectious**: people can no longer depend on their data being well defined so will need to drop UTF-8 and instead use WTF-8 by default.

I would much rather see the invalid data stopped at the source. Produce an error for unpaired surrogates in attributes. Produce an error when a path contains an unpaired. Letting these errors propagate is the only reason that WTF-8 has any use.

Also note that WTF-8 is not a real Unicode encoding defined in the Unicode Standard.

While I highly caution against it, if it must be, then WTF-8 should be an internal class. It should not be available publicly in the framework. Any use of it publicly is an abuse in my opinion.

It may also be wise to consult with Unicode. There is a public mailing list with many experts.

**Comment by tmat** [comment]
@bendono There are legitimate scenarios where WTF8 is needed. For example, C# string literals are UTF16 encoded, so they can express unpaired surrogates. 

```C#
const str = "\uD800";
```

Is a valid constant literal. Now, in order to serialize it in metadata we either need to use UTF16 or WTF8, in order for the string to be deserializable without data loss. ECMA CLI metadata standard chose UTF16, which is space inefficient. If we want to represent the string efficiently we need to use something like WTF8.

In libraries like System.Reflection.Metadata we indeed have an internal [UTF8 encoder/decoder that supports WTF8](https://source.dot.net/#System.Reflection.Metadata/System/Reflection/Internal/Utilities/BlobUtilities.cs,004a5421a72bfd1f,references). It's not desirable to have a copy of such code in all libraries that need to do this.

**Comment by tmat** [comment]
Re whether it should be a new class or a flag in UTF8Encoding ctor. Adding a constructor overload with ```allowUnpairedSurrogates``` flag would make this feature less visible than adding a new class. Which seems to be desirable based on the opinions expressed above. It would also be consistent with the existing constructors that accept flags ```bool encoderShouldEmitUTF8Identifier``` and ```bool throwOnInvalidBytes```.

**Comment by bendono** [comment]
@tmat There needs to be a distinction between a string (for example System.String) and an encoding. A string may be encoded in UTF-16, but that is an implementation detail and not important. (There have been calls for it to be encoded as UTF-8 and several other schemes.) An encoded string is a byte array / stream. I am referring to the later.

In fact, this distinction too is handled in the [Unicode Standard](http://www.unicode.org/versions/Unicode9.0.0/ch02.pdf). See section 2.7 where it discusses that a string may not always be well defined. As such, you can have a string that contains unpaired surrogates, as you point out. However, it should fail (see Unicode FAQ) if that same string is output into a encoded UTF-8 byte array / stream.

I do not dismiss the use cases that you mention. I would prefer raising an error in these cases, but as I wrote above if it must be done, do it in private. It will be abused as part of the larger, general framework. If you don't want to have a copy in multiple libraries, then make a public implementation in your own library that can be shared.  I don't see the need for this to be in the BCL.

**Comment by tmat** [comment]
@bendono I indeed distinguish between those two. By "UTF16 encoded" i mean in memory they are represented as UTF16 bytes and support storage of unpaired surrogates. In metadata they can be inefficiently stored the same way as in memory or more efficiently as WTF8 encoded.

BTW, System.Reflection.Metadata is in CoreFX. So if we make it public there it will be public in BCL ;)

**Comment by jnm2** [comment]
> or more efficiently as WTF8 encoded.

😆 This made my day!

**Comment by GrabYourPitchforks** [comment]
Given that (a) this is a violation of the UTF-8 specification, (b) there has been little demand for this feature aside from domain-specific use cases, (c) this issue has existed for multiple years without action, and (d) alternatives exist via use of private implementation encoding routines, I'm closing this as won't fix.
