### ISSUE TITLE
IOException message for ERROR_SHARING_VIOLATION should say which process ID(s) are holding the file

### ISSUE THREAD

**Issue by ghost** [dotnet/corefx#22276]
It would be great that instead of saying:
>The process cannot access the file '{0}' because it is being used by another process."

The error message would be:
>The process cannot access the file '{0}' because it is being used by process ID {1}."

Originally by @stephentoub had written code that could do this for the article "Restart Manager and Generic Method Compilation"
https://msdn.microsoft.com/sl-si/magazine/mt149362?author=stephen+toub
https://web.archive.org/web/20140403112957/https://msdn.microsoft.com/en-us/magazine/cc163450.aspx

**Comment by cklutz** [comment]
I like the idea quite a lot (and actually use a variation thereof in a production application), however I think there are a couple of conceptual things that might need to be addressed:

**Information in the error message**

The problem with just printing the PID is that the processing having the PID might be (long) gone, when you actually come around to analyzing the issue. That leaves you no trace of what application / process actually had the file locked.

Consider this error message:

> "The process cannot access the file 'c:\foo\bar.txt' because it is being used by process ID 4711."

If you see this, say, in your logs repeatedly and probably with varying PIDs, you have not a good chance to find out which process actually caused it.

I'd say the process name (main module, executable name, etc.) should be included in the error message as well:

>  "The process cannot access the file 'c:\foo\bar.txt' because it is being used by process 'other.exe', process ID 4711."

That would give you a much better chance even after the (other) process has long exited.

**Availability of Information**

Sometimes, the process causing a sharing violation will be gone by the time the victim process comes around to gather such information. This is probably not a big deal, but should at least be addressed in accompanying documentation so that users (or other devs) are not confused when their particular instance of such an exception message contains no additional information.

**Performance Implications**

Apart from that I'm curious about the performance implications such a feature would have. Maybe it should be some sort of diagnostics switch to toggle or some API for the user to opt in if he/she sees fit for a particular region of code (e.g. when doing a recursive directory delete, or such). 

Even if considered bad style, some code _does_ use exceptions for control flow. If every `IOException` that stems from a sharing violation did this analysis, some applications might get into trouble.

Albeit I must admit I have never really measured the impact. ;-)

**Comment by JeremyKuhne** [comment]
There is a way to get this information without the restart manager, but it isn't particularly well-known or documented. For Windows to get the information (restart manager or otherwise) it is basically a scrape of all OS handles, so it is expensive and we need to find a way to make it optional (opt-in or out).

**Comment by stephentoub** [comment]
The original proposer is now a ghost, the only known ways to do this are very expensive, and no progress had been made in years. Closing.

**Comment by danmosemsft** [comment]
Sample code for the Restart Manager approach is here 
https://github.com/microsoft/msbuild/blob/e70a3159d64f9ed6ec3b60253ef863fa883a99b1/src/Tasks/LockCheck.cs
As well as the cost of the operation, it is also racy.
