### ISSUE TITLE
How can I detect my code is running on top of .net core?

### ISSUE THREAD

**Issue by ysmoradi** [dotnet/corefx#22293]
```csharp
    public class PlatformUtilities
    {
        public static bool IsRunningOnMono
        {
            get
            {
                return Type.GetType("Mono.Runtime") != null; // I need something like this.
            }
        }

        public static bool IsRunningOnDotNetCore
        {
            get
            {
                // What should I return here?
            }
        }
    }
```

Thanks in advance.

**Comment by svick** [comment]
The option that comes to mind is to check for the `System.Runtime.Loader.AssemblyLoadContext` type, which exists in .Net Core, but not in .Net Framework:

```c#
public static bool IsRunningOnDotNetCore =>
    Type.GetType("System.Runtime.Loader.AssemblyLoadContext") != null;
```

Though I don't know if there are any guarantees this will work the same in the future.

**Comment by karelz** [comment]
I think you can use [`System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription`](https://apisof.net/catalog/System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription) API, which is part of .NET Standard 1.1+, also see [source code](https://github.com/dotnet/corefx/blob/c46e2e98b77d8c5eb2bc147df13b1505cf9c041e/src/System.Runtime.InteropServices.RuntimeInformation/src/System/Runtime/InteropServices/RuntimeInformation/RuntimeInformation.cs#L22-L35).

Check out [`IsNetCore`](https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/PlatformDetection.cs#L24) implementation from our test sources.

**Comment by danmosemsft** [comment]
@ysmoradi Please reopen if the solution above is insufficient. For a better way you may want to see/contribute to https://github.com/dotnet/corefx/issues/17452

**Comment by fredericDelaporte** [comment]
@karelz's `IsNetCore` link is now dead due to the file having moved [here](https://github.com/dotnet/corefx/blob/master/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.cs). A more permanent link could be [this](https://github.com/dotnet/corefx/blob/v2.1-preview1/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.cs#L23-L25) (tag based link).

**Comment by karelz** [comment]
@fredericDelaporte thanks! Link updated in my post above to avoid further confusion. Thanks!

**Comment by rjmholt** [comment]
I have a need for this but I can't introduce a new dependency in the project to get `System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription`.

Is there anything I could reach into inside something like System.Private.CoreLib/mscorlib to differentiate Core from Framework?

**Comment by karelz** [comment]
@rjmholt why cannot you introduce new ref-assembly dependency? That is THE official API and how it should be referenced.
Anything else will be brittle and unsupported.

**Comment by danmosemsft** [comment]
@rjmholt https://github.com/dotnet/corefx/issues/22293#issuecomment-315527735 should at least tell you whether you are not on.NET Framework. Amother option get the path to the assembly in which typeof(string) is found and look at the name.
As @karelz says, brittle.

**Comment by rjmholt** [comment]
Thanks for the help @karelz and @danmosemsft. For some more context, I've got a C# project currently targeted to net46 whose assembly I'm trying to be able to run from PowerShell Core. I can change the C# code, but due to project requirements I can't add new dependencies. I may be able to retarget the .NET Framework version, so I'm going to investigate that. My ideal would be to use the correct API, but I'm just aware I likely need a fallback.
