### ISSUE TITLE
Add support to use custom structs to create System.Numerics.Vector<T>

### ISSUE THREAD

**Issue by acecebov** [dotnet/corefx#22379]
Add support for unsafe creation of System.Numerics.Vector<T> with additional parameters:
new Vector<T>(T* values) - will work similar like new Vector<T>(T[])
new Vector<T>(T* values, int index) - will work similar like new Vector<T>(T[], int index)

this way we can easily use our custom structs (like Vector3d, Vector4d) to create Vector<T>.

Additionally, it would be really nice to improve new Vector<T>(T[] array) to accept array with less elements than Vector<T>.Length (the remaining bytes on the register can be defaulted to 0). This also applies for Vector<T>(T* values), internally it can get sizeof(T) and set rest of register to 0.

**Comment by mellinoe** [comment]
> new Vector(T* values) - will work similar like new Vector(T[])
new Vector(T* values, int index) - will work similar like new Vector(T[], int index)

These overloads are impossible in C#, because pointer types cannot be generic. The only way it would be expressible is as a static factory method ,e.g. `Vector.CreateInt32(int*, index)`, but this would need to be repeated for every type.

The supported way to create `Vector<T>` instances from a pointer is to use the `Unsafe` class.

```C#
void* arbitraryData = GetArbitraryData();
Vector<int> vecInt = Unsafe.Read<Vector<int>>(arbitraryData);
Vector<byte> vecByte = Unsafe.Read<Vector<byte>>(arbitraryData);
Vector<float> vecByte = Unsafe.Read<Vector<float>>(arbitraryData);
// etc.
Unsafe.Write(arbitraryData, vecInt); // Write the value back.
```

> Additionally, it would be really nice to improve new Vector(T[] array) to accept array with less elements than Vector.Length (the remaining bytes on the register can be defaulted to 0).

I agree that this is a good suggestion. We've considered it in the past and have an issue tracking it here: https://github.com/dotnet/corefx/issues/5360. We didn't fully design it, though.

**Comment by acecebov** [comment]
Interesting idea to use Unsafe.Read, it might do the trick.
I agree the best solution would be to implement #5360!
