### ISSUE TITLE
System.IO.FileNotFoundException when opening connection in UWP

### ISSUE THREAD

**Issue by mahoekst** [dotnet/corefx#22427]
I try to get SQL Client to work in UWP. When I try to connect to a localdb I get an error.

In debug mode: 
System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.'

In release mode: 
System.TypeLoadException: 'Unresolved P/Invoke method 'RegOpenKeyEx!api-ms-win-core-registry-l1-1-0.dll' from this method. Please look for this method in build warnings for more details. '
It fails on the open command
```
using (SqlConnection conn = new SqlConnection())
{
	// Create the connectionString
	// Trusted_Connection is used to denote the connection uses Windows Authentication
	//conn.ConnectionString = "Server=(localdb)\\MSSQLLocalDB;Database=Northwind;Trusted_Connection=true";
	conn.ConnectionString = "Server=(localdb)\\MSSQLLocalDB;Database=Northwind;Persist Security Info=False;User ID = test123; Password = xxxxxxx";
	conn.Open();
}
```
4.5.0-preview2-25518-02 of System.Data.SqlClient

**Comment by joshfree** [comment]
@corivera PTAL

**Comment by corivera** [comment]
Looks like registry functions are not available in UWP. I'll submit a PR to throw a NotSupportedException from SqlClient localdb connections on UWP

**Comment by mahoekst** [comment]
But it's a very common scenario. How do we fix this for UWP?

**Comment by corivera** [comment]
Registry APIs are not a part of netstandard

**Comment by mahoekst** [comment]
Ah ok, so SQLClient is not fully standard compliant?

**Comment by danmosemsft** [comment]
@mahoekst it does build in a netstandard configuration) however it's explicitly referencing registry
```c#
  <ItemGroup Condition="'$(TargetsWindows)' == 'true' And '$(IsPartialFacadeAssembly)' != 'true' ">
    <Reference Include="Microsoft.Win32.Registry" />
  </ItemGroup>
```
Registry provides a dummy version for netstandard use that simply throws PlatformNotSupportedException. 

@corivera I see another problem. The use of LoadLibrary (which is not legal in UWP) is not getting blocked by the build because we still have these lines in the project:
```
-    <!-- Although we have a NS configuration, we know we use API that's not currently whitelisted: just validate against OneCore -->
-    <UWPCompatible>false</UWPCompatible>
```

Given you want to work on UWP, we should work to remove those so the build helps us. That probably means adding a specific UAP configuration in Configurations.props, so that you can include the LocalDB code (which uses LoadLibrary, and registry) and the Registry reference, only when the TargetGroup is netstandard. Taht would clean all this up at once.

**Comment by danmosemsft** [comment]
cc @weshaggard

**Comment by corivera** [comment]
@danmosemsft Is there a UAP compliant way to use the SSPI interop calls? Looks like that also breaks the uap build after removing the UWPCompatible tag.

**Comment by danmosemsft** [comment]
They should all be coming. I'll check. Please baseline them for now by adding a file similar to src\System.Net.Security\src\PinvokeAnalyzerExceptionList.analyzerdata.uap.

**Comment by danmosemsft** [comment]
@pjanotti note we will have a baseline for System.Data.SQlClient as well (it was being bypassed by `<UWPCompatible>false</UWPCompatible>` in the project, which @corivera is removing)
