### ISSUE TITLE
.NET Core 2.0 test should support Windows IoT Core checking

### ISSUE THREAD

**Issue by xumins** [dotnet/corefx#22482]
We are testing .NET Core 2.0 on Windows IoT Core in response to the growing popularity of developing managed apps on IoT Core platforms. Currently there is only one test flag 'IsNanoServer' to test .NET Core 2.0 for both Nano Server and IoT Core platforms.  Because there is no specific flag for Windows IoT Core, it results in at least 2 false test failures.  We suggest to add a specific test flag for Windows IoT Core, or OneCore UAP, in the CoreFx testing framework.

**Comment by danmosemsft** [comment]
@xumins how should it determine IoT Core? For Nano server we are doing this, which is falsely triggering on IoT Core.

public static bool IsWindowsNanoServer => (IsWindows && !File.Exists(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Windows), "regedit.exe")));

Generally Windows versioning API's prefer you do capabilities checks rather than identify the specific SKU although in this case (test runs) we probably have a good reason. What should we use?

**Comment by danmosemsft** [comment]
Could your team throw up a PR which added this to https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/PlatformDetection.cs ? Sounds like it should use GetProductInfo and look at pdwReturnedProductType.

**Comment by danmosemsft** [comment]
this is done
