### ISSUE TITLE
CodeCoverage runs are failing with various test faults

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#22480]
The last 8 runs have failed with the message "NuGet hit a corrupted cache on this machine. Please email @jaredpar with a link to this run."

**Comment by jaredpar** [comment]
We should update that message. It was written when we were still debugging into the failure.

The problem here is that a Jenkins VM gets restarted abruptly during a package restore. It's done in such a way that the package directory ends up in a corrupted state. Any future nuget operation on that machine, other than clear, is pretty much guaranteed to fail. Once we discover a machine in that state the only option is to delete it. 

Related NuGet Issues:

- https://github.com/NuGet/Home/issues/5438
- https://github.com/NuGet/Home/issues/1705

**Comment by JonHanna** [comment]
>Once we discover a machine in that state the only option is to delete it.

Guess someone's going to have to do that for the coverage runs, so.

**Comment by danmosemsft** [comment]
I don't think that's the cause, @jaredpar your message appears whenever the text `.*XmlException.*` is in the log 
https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/failure-cause-management/4caf22c3-f09b-4ab4-99f1-9fb264c1b418/

IO test faiulre  https://github.com/dotnet/corefx/issues/22443
https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/259/consoleFull#-137930154679fe3b83-f408-404c-b9e7-9207d232e5fc
https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/260/consoleFull#-137930154679fe3b83-f408-404c-b9e7-9207d232e5fc

Heap corruption in System.Data.Common tests
https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/261/consoleFull#-137930154679fe3b83-f408-404c-b9e7-9207d232e5fc

AV in WebClient tests
https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/262/consoleFull#-137930154679fe3b83-f408-404c-b9e7-9207d232e5fc

**Comment by danmosemsft** [comment]
I deleted the .*XmlException.* pattern as I don't think that's a sufficiently specific indication.

**Comment by danmosemsft** [comment]
This won't fix itself. We aren't seeing these more recent issues on the regular runs so it seems code coverage related.

**Comment by JonHanna** [comment]
I'm guessing yesterday's run working means this is okay now.
