### ISSUE TITLE
SecureString uses the wrong crypt32 export on Windows

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/corefx#2251]
See https://github.com/dotnet/corefx/blob/master/src/System.Security.SecureString/src/System/Security/SecureString.Windows.cs.

Currently the CoreFX version of SecureString calls CryptProtectData to encrypt the contents of its memory. CryptProtectData isn't guaranteed to work correctly when the user profile isn't loaded (so could fail in service applications). Additionally, some hosting environments throttle the rate at which you can call APIs like CryptProtectData.

Calling CryptProtectMemory instead of CryptProtectData would solve these issues.

**Comment by pallavit** [comment]
The use of CryptProtectData was recommended by the CryptProtectXXX APIs owners since DPAPIs provide better security than the CryptProtectMemory invariants.


> CryptProtectData isn't guaranteed to work correctly when the user profile isn't loaded (so could fail in service applications). 

 I would like to follow-up with the API owners on this, would you mind sharing some links with this information? I could only find this old thread https://support.microsoft.com/en-us/kb/309408 which did not seem relevant.

**Comment by GrabYourPitchforks** [comment]
Followed up offline.

**Comment by pallavit** [comment]
This should be a non-issue after merging PR #3536
