### ISSUE TITLE
IntersectIterator not optimized to exit early

### ISSUE THREAD

**Issue by Arithmomaniac** [dotnet/corefx#2255]
In System/Linq/Enumerable.cs, the `IntersectIterator<TSource>` method will iterate over all of the items of `first`, even if the `set` created by `second` is empty.

A simple performance optimization would be to `yield break` when `set` is empty.

**Comment by leppie** [comment]
How would you know the second is empty without iterating through it? (aka `Count()`)

For collections with a known/computed length, this could be beneficial.

**Comment by svick** [comment]
@leppie That's what I thought at first too, but then I looked at [the code](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Enumerable.cs#L968):

```c#
private static IEnumerable<TSource> IntersectIterator<TSource>(IEnumerable<TSource> first, IEnumerable<TSource> second, IEqualityComparer<TSource> comparer)
{
    Set<TSource> set = new Set<TSource>(comparer);
    foreach (TSource element in second) set.Add(element);
    foreach (TSource element in first)
        if (set.Remove(element)) yield return element;
}
```

[`Set`](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Enumerable.cs#L2789) doesn't seem to expose `Count`, but that should be trivial to add. With that, the code could be changed to something like:

```c#
Set<TSource> set = new Set<TSource>(comparer);
foreach (TSource element in second) set.Add(element);
if (set.Count == 0) yield break;
foreach (TSource element in first)
    if (set.Remove(element)) yield return element;
```

Another option would be to also check the count after every `Remove()`:

```c#
Set<TSource> set = new Set<TSource>(comparer);
foreach (TSource element in second) set.Add(element);
if (set.Count == 0) yield break;
foreach (TSource element in first)
{
    if (set.Remove(element)) yield return element;
    if (set.Count == 0) yield break;
}
```

That could be a significant optimization in other edge cases, but it might also slightly (?) decrease performance of the common case, so I think it's a more questionable change.

@Arithmomaniac How badly did I misrepresent your proposal? :smiley:

**Comment by omariom** [comment]
Another small optimization:
```C#
if (set.Remove(element))
{
    yield return element;
    if (set.Count == 0) yield break;
}
```

**Comment by Arithmomaniac** [comment]
@svick The latter nailed it. (Couldn't flesh it out on company time.)

FWIW, my use case it the following function for intersecting two `IEnumerable`s that cannot fit in memory:

```csharp
public IEnumerable<TSource> BatchedIntersect<TSource>(
    this IEnumerable<TSource> first, IEnumerable<TSource> second)
{
	//using https://bitbucket.org/morelinq
	foreach (var sec secondBatch in MoreLinq.Batch(second, 10000))
	{
		foreach (var element in first.Intersect(secondBatch)) yield return element;
	}	
}
```
Needless to day, I wouldn't want to iterate over a `first` of 1M items if I didn't have to.

**Comment by hackcraft** [comment]
I came across this separately while looking at the xxxBy variants 2146 asks for, since IntersectBy would have the same pattern, and left it commented with a FIXME in what I've done so far on that for this reason; this change obviously improves performance when it short-circuits, which is obviously an improvement (but see comments on 2238 on how short-circuiting is a breaking change), but it adds work to every loop which would decrease performance in cases where it took relatively long to empty the set.
The question then is which patterns we see more often in real code. In particular, note that is the first sequence is not a subset of the second then the short-circuiting never comes up, and this can only make things slower.
If I had to guess, I'd guess that the majority of uses of Intersect did not have such a subset-superset relationship between its arguments and therefore would suffer from this change. On the other hand some that benefitted would benefit massively. I wonder if there would be a good way to survey real uses across a lot of different applications.

**Comment by VSadov** [comment]
Not iterating an IEnumerable in general is observable. If we do this optimization internally, we would have to constrain it just to some known source types like `T[]` or `List<T>`.

I would wonder how common it is to have sources that have `T[]` or `List<T>` types and also either of two is empty. Probably not often.

Also It seems like something that is easier to be done externally and could cover more cases.

The App may have extra knowledge that not iterating is ok and be more aggressive with shortcircuiting on "Count"  checks for a wider range of types.
As a general-purpose library Linq cannot not be that aggressive.

**Comment by JonHanna** [comment]
There are certainly changes that have been made that are comparable (#5372, #6061). Having just come across the code with fresh eyes after not looked at it in some time, I was coming here to withdraw my scepticism, though only for the form that aborts on empty `second` rather than the form that continually checks if it can short-circuit (which adds more continual checks).
