### ISSUE TITLE
Min/Max properties for SortedDictionary<TKey, TValue>

### ISSUE THREAD

**Issue by cosborne83** [dotnet/corefx#22591]
The `SortedDictionary<TKey, TValue>` does not provide any way to efficiently access the minimum and maximum key values, despite being built upon `SortedSet<T>`, which provides `Min` and `Max` properties for this purpose.

It would be useful if similar properties for accessing the minimum and maximum keys were available for the SortedDictionary, perhaps via similar `Min` and `Max` properties to follow the naming in SortedSet, or via `MinKey`/`MaxKey` to be explicit.

**Comment by jnm2** [comment]
We have `ContainsKey` rather than `Contains`, so I would expect `MinKey`.

**Comment by svick** [comment]
Related closed proposal: https://github.com/dotnet/corefx/issues/11976.

**Comment by safern** [comment]
We are going to close this issue and re-open the closed proposal (#11976). We would like to have a proposal spec with performance benchmarks on having new instances method (First, Last or Max, Min) vs existing Linq extensions methods (First, Last).

We are moving it to that issue since we've already had a good discussion on that side. @cosborne83 please feel free to update that issue with your proposal spec.
