### ISSUE TITLE
Null ref thrown in System.Text RegEx

### ISSUE THREAD

**Issue by brentschmaltz** [dotnet/corefx#22646]
The user posted an image with issue here:

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/649

**Comment by danmosemsft** [comment]
@nicksav  can you give a repro case, or more detailed callstack?

**Comment by danmosemsft** [comment]
@krwq can you see how this https://github.com/dotnet/corefx/blob/986ffdb1053d334b862f96b53c67ca3bae222219/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs#L941 could throw NRE? I have looked at the code carefully and I don't see it.

**Comment by krwq** [comment]
I think it will be:
`s_livecode.Remove(current);` + `current = current.Next` - I guess removing current will set its next to null - will check it tomorrow (aka later today)

**Comment by nicksav** [comment]
Guys, the issue might be related to me running .net core 2.o prev 1 with libs from 1.2.  I have all code to 2 prev 2 Haven't seen this for 6 days. Before was quite often.

**Comment by krwq** [comment]
@nicksav thanks for trying out 2.0! I'll close this for now then since I can't see anything wrong with that code, please reopen if you see this again.

**Comment by krwq** [comment]
Also, if it repros could you try also adding this to you App.Config?
```
<runtime>
    <useLegacyJit enabled="1" />
</runtime> 
```

or setting environmental variable on the server: `COMPlus_TailCallLoopOpt=1` - we recently have seen a JIT bug which was producing random NREs - this is a workaround

**Comment by danmosemsft** [comment]
Thanks guys, I was starting to not trust my eyes.

**Comment by jnm2** [comment]
Do you think the JIT bug is also responsible for VS refusing to close and giving me a message box with the text of the NRE message? https://developercommunity.visualstudio.com/content/problem/61470/visual-studio-2017-object-reference-exception-when.html?childToView=85733#comment-85733

**Comment by krwq** [comment]
@jnm2 - I do not know about that (I doubt it though) but you can definitely try if you got consistent repro - I think the JIT bug is already fixed in new versions of clr but it might take a while until fix is being consumed everywhere.

Usually if you provide a step by step instruction how to recreate a bug it is being fixed fairly quickly. If you do not have a consistent repro then when it happens do not click anything in that instance of VS - open second instance of VS, click feedback and in the second or third tab during filing issue you should be able to choose the instance with the error (you might need to click record or something like that - I do not remember from the top of my head) - that should make it so that dump file will be created on the failing instance and attached to a bug - that should make it much easier to diagnose and fix.

**Comment by jnm2** [comment]
I don't have a consistent repro, so I will do that.

**Comment by jnm2** [comment]
@krwq Here you are. https://developercommunity.visualstudio.com/content/problem/86999/cannot-close-vs-shows-simple-object-reference-is-n.html

**Comment by krwq** [comment]
@jnm2 nice - thank you for reporting this! Hopefully someone will take a look at it soon!

**Comment by krwq** [comment]
@jnm2 - in case you've missed - you just got response in the issue - they suspect this is coming from some extension you might have installed since they couldn't find symbols and gave you instructions on how to create better (?) dump
