### ISSUE TITLE
DBNull exists in both System.Data.Common and System.Net.NameResolution

### ISSUE THREAD

**Issue by massi100** [dotnet/corefx#22681]
Using VS2017 /NET core 1.1,  I get this error:
The type 'DBNull' exists in both 'System.Data.Common, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Net.NameResolution, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

when I execute the following lines:
var dbNullValue = typeof(System.DBNull).GetField("Value");
var dbNullExp = Expression.Field(Expression.Parameter(typeof(System.DBNull), "System.DBNull"), dbNullValue);

![untitled](https://user-images.githubusercontent.com/25195490/28665763-c5dc6640-7292-11e7-8eb1-281ee35419c4.jpg)

**Comment by jnm2** [comment]
Why is DBNull in System.Net.NameResolution?

**Comment by danmosemsft** [comment]
@jnm2 it isn't. I see it moved from System.Data.Common to System.Runtime in 2.0, with a type forward. 
@weshaggard can you figure what is going on?

**Comment by weshaggard** [comment]
Looks like DBNull was an internal type in System.Net.NameResolution in the past So reflection could get that type however from the code I see there I don't know why you would get that error. I can understand the watch window might get that error because it looks at both public and private types. 

@massi100 Are you also hitting that error at runtime?

**Comment by davidsh** [comment]
DBNull was defined as an internal type in System.Net.NameResolution back in .NET Core 1.1.  This was because it was not available in System.Runtime.

However, with .NET Core 2.0 (NETStandard20), DBNull was added back to System.Runtime.  So, the internal type definition was removed from System.Net.NameResolution.

Looking in the master branch, the only places it is even used in System.Net is in the Common\src includes as part of `LazyAsyncResult` code:

```
s:\GitHub\corefx\src\Common\src>findstr /s /i /c:"DBNull" *.cs
System\Data\Common\AdapterUtil.cs:            if ((null == value) || (DBNull.Value == value))
System\Net\LazyAsyncResult.cs:            _result = DBNull.Value;
System\Net\LazyAsyncResult.cs:            if (result == DBNull.Value)
System\Net\LazyAsyncResult.cs:                NetEventSource.Fail(this, "Result can't be set to DBNull - it's a special internal value.");
System\Net\LazyAsyncResult.cs:                return _result == DBNull.Value ? null : _result;
System\Net\LazyAsyncResult.cs:                // It's an error to call after the result has been completed or with DBNull.
System\Net\LazyAsyncResult.cs:                if (value == DBNull.Value)
System\Net\LazyAsyncResult.cs:                    NetEventSource.Fail(this, "Result can't be set to DBNull - it's a special internal value.");
System\Net\LazyAsyncResult.cs:            // Critical to disallow DBNull here - it could result in a stuck spinlock in WaitForCompletion.
System\Net\LazyAsyncResult.cs:            if (result == DBNull.Value)
System\Net\LazyAsyncResult.cs:                // DBNull.Value is used to guarantee that the first caller wins,
System\Net\LazyAsyncResult.cs:                if (_result == DBNull.Value)
System\Net\LazyAsyncResult.cs:            while (_result == DBNull.Value)
```

The definition of DBNull appears in the System.Runtime ref file:
https://github.com/dotnet/corefx/blob/master/src/System.Runtime/ref/System.Runtime.cs#L853

**Comment by davidsh** [comment]
Since the type is no longer defined in a duplicate manner with .NET Core 2.0, I will close this issue.
