### ISSUE TITLE
Linux sockets: async connect on already connected socket does not throw

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#22765]
If you do a ConnectAsync on an already connected socket, no exception is thrown.

Synchronous Connect correctly throws a SocketException with errorcode SocketError.IsConnected.

**Comment by karelz** [comment]
Should be fairly straightforward.

**Comment by wtgodbe** [comment]
@geoffkizer does this block look fishy to you? https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/SocketPal.Unix.cs#L518-L520. From my understanding, `IsDisconnected` means we were connected in the past, but are no longer; while `IsConnected` means we are currently connected. Is that correct? If that's the case, shouldn't that `IsDisconnected` be switched to `IsConnected`? I'm running tests right now with that assumption, but I want to make sure I'm not misunderstanding anything.

**Comment by wtgodbe** [comment]
Looks like we call Connect here https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/SocketPal.Unix.cs#L527, which calls into a native library - 
https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/Common/src/Interop/Unix/System.Native/Interop.Connect.cs#L13. Debugging this shows that the call to the Interop function returns success, so we probably want to fail out in a similar way to https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/SocketPal.Unix.cs#L518-L520 before the call ever happens. However, the SafeCloseSocket object for Unix doesn't seem to have a notion of being "Connected", only "Disconnected" - https://github.com/dotnet/corefx/blob/6dec6e3638adaf3ad332c1cb8def1dd10a2a7de9/src/Common/src/System/Net/SafeCloseSocket.Unix.cs#L193-L199. I'm not sure what the best way to expose/create that information in SafeCloseSocket.Unix.cs is, since if I add a field for it, I'm unsure if I could find every location that would need to set that variable. @geoffkizer any thoughts?

**Comment by geoffkizer** [comment]
It's weird that the native code succeeds.  

Not sure how to expose the IsConnected info; I'll dig through the code a bit...

**Comment by wtgodbe** [comment]
@geoffkizer have you had a chance to take a closer look at the code here yet?

**Comment by geoffkizer** [comment]
Not really.  One quick thought is that we probably don't need to track this at the SafeCloseSocket level.  I think we track if we're connected or not on the Socket somewhere, so APIs like ConnectAsync could just check that.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/corefx/pull/27173 should hopefully resolve

**Comment by wtgodbe** [comment]
Resolved by https://github.com/dotnet/corefx/pull/27173

**Comment by rmkerr** [comment]
Closing since Will resolved this with #27173.
