### ISSUE TITLE
Serialization test case DCS_BasicPerSerializerRoundTripAndCompare_SampleTypes_FailedInuapaot_InheritedFromIList_CanPassInReflectionOnly failed when targeting uapaot

### ISSUE THREAD

**Issue by JimboWei** [dotnet/corefx#22778]
This case is a part of test case DCS_BasicPerSerializerRoundTripAndCompare_SampleTypes , it failed when **targeting `uapaot`** , so we move these scenarios into a new case.

**Detail** : the class in these scenarios inherit from **IList** will fail when serialization, but it can pass in project ReflectionOnly. 

**Error Message** : System.Runtime.Serialization.InvalidDataContractException : Collection type 'SerializationTestTypes.SampleListExplicitWithoutDC' does not have a valid Add method.

**Note** : I checked the test classes they already implement interface **IList** explicitly and have a method named **IList.Add**.

**Comment by shmao** [comment]
The issue is due to a bug in  `CollectionDataContract.GetCollectionMethods`. The method depends on the order of a type's interfaces. The order was different on NetCore and full framework, so we saw different behaviors. The fix was to make sure the order of the interfaces is consistent on different platforms.
