### ISSUE TITLE
Serialization test case DCS_BasicPerSerializerRoundTripAndCompare_SampleTypes_FailedInuapaot_IncludeDataSet failed when targeting uapaot

### ISSUE THREAD

**Issue by JimboWei** [dotnet/corefx#22776]
This case is a part of test case DCS_BasicPerSerializerRoundTripAndCompare_SampleTypes , it was failed when **targeting `uapaot`** , so we move these scenarios into a new case.

**Detail** : the class include **DataSet** will fail when serialization.

**Error Message** : System.Runtime.Serialization.InvalidDataContractException : Type 'System.Data.DataSet' does not have a static method 'GetDataSetSchema' that takes a parameter of type 'System.Xml.Schema.XmlSchemaSet' as specified by the XmlSchemaProviderAttribute attribute.

**Comment by shmao** [comment]
`SchemaExporter.InvokeSchemaProviderMethod` needs to reflect the method specified in a type's `XmlSchemaProviderAttribute`. For example, `SchemaExporter` needs to call `DataSet.GetDataSetSchema` via reflection. 

``` c#
    [
    ResDescriptionAttribute(Res.DataSetDescr),
    DefaultProperty("DataSetName"),
    ToolboxItem("Microsoft.VSDesigner.Data.VS.DataSetToolboxItem, " + AssemblyRef.MicrosoftVSDesigner),
    Designer("Microsoft.VSDesigner.Data.VS.DataSetDesigner, " + AssemblyRef.MicrosoftVSDesigner),
    Serializable,
    XmlSchemaProvider("GetDataSetSchema"), // <----- THIS ATTRIBUTE.
    XmlRoot("DataSet")
    ]
    public class DataSet
```

The test failed on uapaot because the metadata of the method to be called was reduced. To make the test pass, we can add the following in rd.xml,

```xml
    <Namespace Name="System.Data">
      <Type Name="DataSet">
        <Method Name="GetDataSetSchema" Dynamic="Required Public"/>
      </Type>
      <Type Name="DataTable">
        <Method Name="GetDataTableSchema" Dynamic="Required Public"/>
      </Type>
    </Namespace>
```

@morganbr Is this something we want to fix in the analysis engine? We may want to keep the metadata for the method that specified in a type's `XmlSchemaProviderAttribute`.
