### ISSUE TITLE
Add support for System.Runtime.WindowsRuntime to .NETCore

### ISSUE THREAD

**Issue by bdlou** [dotnet/corefx#22789]
We have a need to develop tooling using .NETCore to do hardware validation scenarios.  .NETCore currently has no ways to talk to hardware.  Exposing System.Runtime.WindowsRuntime would enable us to perform many query and validation scenarios on hardware devices.

**Comment by pjanotti** [comment]
@bdlou have you tried using the nuget package? https://www.nuget.org/packages/System.Runtime.WindowsRuntime let us know how that goes.

**Comment by bdlou** [comment]
We more specifically need access to things like Windows.Devices.Enumeration, which are not available currently.

**Comment by tarekgh** [comment]
CC @tijoytom @yizhang82 looking at http://index/?query=Windows.Devices.Enumeration&rightProject=Dotnet(Repo)&file=NDP%5Crh%5Cpublic%5Csdk%5Cinc%5Cabi%5Cwindows.devices.enumeration.h&line=132 looks to me this issue is more related to the interop service but you can advise if this is not true.

cc @weshaggard

**Comment by ericstj** [comment]
> have you tried using the nuget package? 

@pjanotti we've [stopped building it in 2.0](https://github.com/dotnet/corefx/commit/72002dbb7e3e657adaeb002feca0399d9667a54b) and never had good "official" support for it on .NETCore

This issue should track re-enabling the package, ensuring a windows implementation for .NET core and a platform-not-supported implementation elsewhere.

**Comment by luqunl** [comment]
We are working on enable WinRT(WindowsRuntime) for .NETCore. In order to enable WinRT support, Currently Customer have to explicitly reference System.Runtime.WindowsRuntime reference assembly.  This experience will be improved in future.

Current rough plan:
1. Add System.Runtime.WindowsRuntime implementation assembly into .NetCoreApp nuget package
2. Publish System.Runtime.WindowsRuntime reference assembly 
3. Add  Platform-not-supported implementation elsewhere(such as Win7)

**Comment by ericstj** [comment]
Where will the reference assembly ship?  Will this be part of the NETCoreApp framework package or will you have a dedicated nuget package that supports multiple frameworks?

**Comment by luqunl** [comment]
Current plan is to ship reference assembly in a dedicated nuget package.

**Comment by ericstj** [comment]
I see, in that case the nuget package will also have the implementation assembly?  Just trying to understand why we're putting this in .NETCoreApp package if we aren't exposing it and it isn't a dependency of anything already in there.

**Comment by weshaggard** [comment]
The reason we are putting the implementation inbox is because of the coupling between this and the runtime. We felt it was better to keep it inbox and just expose the ref in the package with a placeholder for the implementation.

**Comment by ericstj** [comment]
I see, I believe this may be the first package to do that, so you may run into some new cases in validation that need to be suppressed.  I'd also be careful about ensuring its a placeholder everywhere (and not just windows). I could imagine our host could get confused if, for example, we had a RID-less not supported aseembly and a windows-placeholder and then ran as a portable app.

**Comment by andriysavin** [comment]
Any milestones/rodmap on where to expect this?

**Comment by rido-min** [comment]
@riverar yes, with .NET Core 3 preview2 we published [https://www.nuget.org/packages/System.Runtime.WindowsRuntime/4.6.0-preview.19073.11](https://www.nuget.org/packages/System.Runtime.WindowsRuntime/4.6.0-preview.19073.11) to support S.R.WR in `netcoreapp3` apps.

@jeffschwMSFT  can we close this issue?

**Comment by jeffschwMSFT** [comment]
Fixed with https://github.com/dotnet/corefx/pull/33654
