### ISSUE TITLE
CookieParser.Get() not Returning Cookie Correctly.

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#22925]
I have a cookie string as shown below,
    `cookie_name1=cookie_value1;cookie_name2=cookie_value2`

I have the following test code,
```c#
            var parser = new CookieParser(cookieString);
            while (true)
            {
                Cookie cookie = parser.Get();
                if (cookie == null)
                {
                    break;
                }

                cookieCount++;
            } 
```

I expected the cookieCount to be the count of the cookies in the string. For the example, I expected the count to be 2. But the actual value was 1.

If I used parser.GetServer() instead of Get() in the test code, the cookieCount is as expected. So I wondered if the behavior is as expected.  

Please see test CookieParserGet_SetCookieHeaderValue_Success. The test failed due to the issue.

**Comment by rmkerr** [comment]
Hey @shmao, I believe that this is just a test issue. Those tests are written as if cookies are separated by semicolons, when they in fact should be separated by commas. That's based off of my RFC 2109, which says:
```
Informally, the Set-Cookie response header comprises the token Set-Cookie:,
followed by a comma-separated list of one or more cookies. 
```
Cookie _attributes_ are separated by semicolons, so what CookieParser.Get sees in the tests is a single cookie with several attributes that it does not recognize. Redoing the tests to separate the cookies with commas will cause this test to pass.

**Comment by shmao** [comment]
Hmm, I'm a bit confused. Check out https://tools.ietf.org/html/rfc6265#page-8. You can see that the semi-colon is a separator of cookie-pair's as defined in the 'set-cookie-string'. 

```
4.1.1.  Syntax
   Informally, the Set-Cookie response header contains the header name
   "Set-Cookie" followed by a ":" and a cookie.  Each cookie begins with
   a name-value-pair, followed by zero or more attribute-value pairs.
   Servers SHOULD NOT send Set-Cookie headers that fail to conform to
   the following grammar:

 set-cookie-header = "Set-Cookie:" SP set-cookie-string
 set-cookie-string = cookie-pair *( ";" SP cookie-av )
 cookie-pair       = cookie-name "=" cookie-value
 cookie-name       = token
 cookie-value      = *cookie-octet / ( DQUOTE *cookie-octet DQUOTE )
 cookie-octet      = %x21 / %x23-2B / %x2D-3A / %x3C-5B / %x5D-7E
                       ; US-ASCII characters excluding CTLs,
                       ; whitespace DQUOTE, comma, semicolon,
                       ; and backslash
 token             = <token, defined in [RFC2616], Section 2.2>
```

According to [this answer](https://stackoverflow.com/a/4843598), RFC2109 seems obsoleted. 

Besides, the other issue was that I found,

> If I used parser.GetServer() instead of Get() in the test code, the cookieCount is as expected. So I wondered if the behavior is as expected.

**Comment by rmkerr** [comment]
I think that you're missing a key line of the ABNF there:
```
 cookie-av     = expires-av / max-age-av / domain-av /
                 path-av / secure-av / httponly-av /
                 extension-av
```
So my interpretation is that a `set-cookie-header` consists of a the string `"Set-Cookie:"` followed by a space and a `set-cookie-string` [1]. A `set-cookie-string` consists of a _single_ `cookie-pair` followed by any number of cookie attribute values (`cookie-av`) [2]. Those attribute values are separated but not terminated by a semicolon [2]. As defined above, `cookie-av` is a set of special attributes like max age and expires, not a list of additional cookies.

That being said, I'm not sure we are up to date with the latest RFCs. It looks like we are willing to accept cookies in a comma separated list, which may be an obsolete behavior.

What is the expected behavior of GetServer? I don't see any indication that the behavior should be identical.

[1] `set-cookie-header = "Set-Cookie:" SP set-cookie-string`
[2] `set-cookie-string = cookie-pair *( ";" SP cookie-av )`

**Comment by davidsh** [comment]
As a reminder, we do not support RFC 6265 (and neither does the Windows native stacks Wininet, WinHttp).  See: https://github.com/dotnet/corefx/issues/14674

**Comment by shmao** [comment]
@davidsh RFC 6265 is the one to which you pointed me. See https://github.com/dotnet/corefx/issues/22877#issuecomment-319807918

**Comment by rmkerr** [comment]
Regardless, I don't think these tests are testing the correct behavior. Those semicolon separated values are attributes that give us special information about the cookie, like the domain or the expiration. They don't represent a list of additional cookies, whichever spec we follow. Since CookieParser.Get is looking for cookies and not attributes, it gets only the first name value pair.

**Comment by shmao** [comment]
@rmkerr sounds good. Thanks for looking into this. It may worth to fix the tests added by #22895.

@mconnew, I am probably wrong, but I thought I saw "Set-Cookie" followed by a list of cookies in WCF tests.

**Comment by rmkerr** [comment]
I'm not really sure how we would go about fixing that test short of just removing it -- it isn't really clear what is being tested, especially now that we know that the expected behavior is not correct.

@davidsh what are your thoughts on just removing the incorrect test?

**Comment by davidsh** [comment]
>@davidsh what are your thoughts on just removing the incorrect test?

Is the test wrong (and which test is it, can link to source code?)?  Or is the product code wrong?

**Comment by rmkerr** [comment]
The test is wrong. It has been disabled since it was added. You can find it here: https://github.com/dotnet/corefx/blob/c714216f2a07a8b9963839b5c87b56f33ec0327e/src/System.Net.Primitives/tests/UnitTests/CookieInternalTest.cs#L84-L90

**Comment by davidsh** [comment]
>The test is wrong. It has been disabled since it was added

If the test is wrong, then fix or remove it.

But what about the internal `CookieParser.Get()` method?  How is that used in our product code?  Is there a problem with that method?

**Comment by rmkerr** [comment]
`CookieParser.Get()` is used in the product code to process cookie attributes such as expires, max age, domain, etc. The test was written as if `CookieParser.Get()` was designed to get multiple cookies from a single header, which it is not. Those cookie attributes are tested elsewhere in the code, and I do not believe there are any known issues. I also didn't see any problems in my own manual testing

We could convert this into a test for the actual behavior of `CookieParser`, but it would basically just mean deleting the test and rewriting it to test something completely different. Since the test was wrong from the start, and there is coverage elsewhere I think we should just delete the test.

**Comment by davidsh** [comment]
>Since the test was wrong from the start, and there is coverage elsewhere I think we should just delete the test.

Seems like a plan.
