### ISSUE TITLE
Test class SRE GenericTypeParameterBuilderSetGenericParameterAttributes is wrong

### ISSUE THREAD

**Issue by lambdageek** [dotnet/corefx#22968]
The `SetGenericParameterAttributes` test calls `GenericTypeParameterBuilder:SetGenericParameterAttributes` and then immediately accesses the `GenericParameterAttributes` property of the builder.

According to https://msdn.microsoft.com/en-us/library/system.reflection.emit.generictypeparameterbuilder.setgenericparameterattributes(v=vs.110).aspx

> Special constraints cannot be retrieved using methods of the GenericTypeParameterBuilder class. Once you have created the generic type that contains the type parameter, you can use its Type object to reflect the type parameters and their constraints. To get the type parameters of a completed generic type, use the Type.GetGenericArguments method. To get the special constraints for each type parameter, use the Type.GenericParameterAttributes property.

So the test should first call `CreateType` on the generic class and then retrieve the parameter attributes.

The test in question: https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Emit/tests/GenericTypeParameterBuilder/GenericTypeParameterBuilderSetGenericParameterAttributes.cs#L28

**Comment by AtsushiKan** [comment]
"Special constraints cannot be retrieved using methods of the GenericTypeParameterBuilder class. "

While this appears to be a rather unnecessary phrase in MSDN (though technically correct since GenericParameterAttributes is a property, not a method), the fact is that the actual implementation does expose the value through that property, the behavior is not surprising or unreasonable, it's something you can easily imagine real-world code taking advantage of it (imagine code that incrementally adds bits to the flags from different places), and thus its worth testing to ensure compatibility. I don't see a CoreFX issue to fix here.
