### ISSUE TITLE
Update `System.Runtime.Extensions` references version

### ISSUE THREAD

**Issue by anfomin** [dotnet/corefx#2304]
Current `System.Runtime.Extensions` dev build has version `4.0.10-*`. But many projects still references to version `4.0.0-*`. This breaks packages restore:

```
Error: DownloadPackageAsync: https://www.myget.org/F/aspnetvnext/api/v2/package/System.Runtime.Extensions/4.0.0-beta-23109
  Response status code does not indicate success: 404 (Not Found).
```

For example: https://github.com/dotnet/corefx/blob/master/src/System.Security.Principal.Windows/src/project.json

**Comment by nguerrera** [comment]
cc @ericstj

**Comment by ericstj** [comment]
This is intentional and does not break package restore.  We publish the older version packages:
```
d:\tools>nuget list -source https://www.myget.org/F/aspnetvnext/ -pre System.Runtime.extensions -allversions
...
System.Runtime.Extensions 4.0.0-beta-23109
...
System.Runtime.Extensions 4.0.10-beta-23109
```

Indeed if I browse to the very [URL](https://www.myget.org/F/aspnetvnext/api/v2/package/System.Runtime.Extensions/4.0.0-beta-23109) you list above it successfully downloads the package.

I think you hit a problem where the ASP.Net team accidentally deleted some packages.  They've fixed that.
