### ISSUE TITLE
Can we extend the timeout on the coverage builds?

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#23054]
Timing out has always been common with them, and of the last 10 runs, 1 had a test failure and the other 9 timed out. The time required to run will generally tend to increase too (more tests are common and desired, ideas on how to make tests quicker much rarer). Most seem like they could well have completed (rather than being stuck somewhere). Could the time allowed for the run be increased?

**Comment by stephentoub** [comment]
cc: @dotnet/dnceng

**Comment by danmosemsft** [comment]
@dotnet/dnceng should we move this to core-eng?

**Comment by mmitche** [comment]
@danmosemsft @stephentoub This seems like something that should be handled by the product team.  There are a bunch of places already in the CI definitions where we extend the timeout.

**Comment by MattGal** [comment]
I just want to point out that in regular execution we see individual work items time out semi-randomly in the official runs ( A quick query shows it to be biased towards Performance, Xml, and Network tests).  If a single work item spins forever in a Jenkins run, the job will timeout.

As such it may make more sense to do a coverage run where you keep track of test start/stop times in one of these timeouts may help you figure out what the real problem is, since if any test is spinning forever the only effect of increased timeout is more time wasted.

**Comment by JonHanna** [comment]
Diagnostics catching why something timed out when it should have would certainly also be good. 

Meanwhile all of the six coverage runs since I opened this have also timed out.

**Comment by stephentoub** [comment]
> Meanwhile all of the six coverage runs since I opened this have also timed out.

I don't think extending the timeout will solve all of these woes (it may help with some, it's worth seeing).  Most of them appear to be hitting https://github.com/dotnet/corefx/issues/23201.

**Comment by JonHanna** [comment]
I'll reopen after that is resolved if it still seems to timeout due just to running out of time.

**Comment by JonHanna** [comment]
#23201 did fix things at the time, but of the runs that have timed out over the last month many (most) seem to have failed solely due to running out of time, and the last successful run just scraped in after 2 hours, 57 minutes against a 3-hour deadline, so I'm reopening this.

CC: @dotnet/dnceng

**Comment by ViktorHofer** [comment]
Closing as the current timeout is 10h. We are still hitting issues with it but we are looking into alternatives for test coverage reports. @pjanotti
