### ISSUE TITLE
AppContext.TargetFrameworkName differs between CoreRT and CoreCLR

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#23063]
https://github.com/dotnet/coreclr/pull/13266#pullrequestreview-55061899

 In CoreCLR, AppContext.TargetFrameworkName will always return null. On CoreRT/ProjectN, it will return attribute value from main exe https://github.com/dotnet/corert/blob/ff7eba504516fa0bc0a50357ad559c19b45d1d51/src/System.Private.CoreLib/src/System/AppContext.cs#L45

If we are OK with updating CoreCLR, we return `                return Assembly.GetEntryAssembly()?.GetCustomAttribute<TargetFrameworkAttribute>()?.FrameworkName;
` from AppDomainSetup.TargetFrameworkName

 this will cause AppContext to parse ".NETCoreApp,Version=v2.0" and have an identifier and version instead of empty/null as it currently has and I don't know what that will do downstream.

**Comment by danmosemsft** [comment]
@AlexGhiondea is this a type you have context on? It's the Core equivalent of Quirking? Should we take this change?

**Comment by onovotny** [comment]
This would be very useful, as there's no current reliable way at runtime to get the currently executing framework and version.

For applications that may run on multiple versions, it can be useful diagnostic info to output (".NET Framework 4.7.1" or ".NET Core App 2.0.1", etc). 

As far as I can see, there's no way to do this since `TargetFrameworkAttribute` is not present on either `mscorlib` or `System.Private.CoreLib`. Putting those on would be very helpful as well. At least `mscorlib` has an `AssemblyFileVersion` of `4.7.2542.1`. I don't see any such thing on .NET Core app that maps to its "real" version. Instead, .NET Core App 1.0.5 has `[assembly: AssemblyFileVersion("4.6.25211.02")]`.

**Comment by AlexGhiondea** [comment]
@danmosemsft the `AppContext` type is primarily used for quirking but has also a few other uses.

On CoreCLR we don't return null. We actually look at [AppDomain.CurrentDomain.SetupInformation.TargetFrameworkName.](
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/AppContext/AppContext.cs#L47)

On CoreCLR I am not sure we want to read the value from the main exe as a) there might not be an entry assembly and b) the host can choose to put a different TFM on the default AppDomain.

/cc @jkotas

**Comment by jkotas** [comment]
We should return value from the TargetFrameworkName attribute in CoreCLR, I think. It is one line change - copy the implementation from CoreRT:

```
        public static string TargetFrameworkName => Assembly.GetEntryAssembly()?.GetCustomAttribute<TargetFrameworkAttribute>()?.FrameworkName;
```

**Comment by Anipik** [comment]
@jkotas I tried this change. But still the value being returned in the Corefx Tests is null

**Comment by danmosemsft** [comment]
This is because xunit.console.netcore.exe is the entrypoint assembly for your test and it is missing the attribute. I assume it does work when you do "dotnet.exe myapp.dll" as myapp.dll is the entrypoint assembly and should have it.
For testing purposes I would either update the xunit exe's or better still use RemoteInvoke(), adding the TargetFrameworkAttribute manually into https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Diagnostics/RemoteExecutorConsoleApp/AssemblyAttributes.cs  if you need to
