### ISSUE TITLE
Consistency of sealed modifiers on methods of sealed classes

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23086]
The general style across corefx is that if a type is sealed, its virtual members are not also annotated as sealed.  There are a few projects within the repo, however, where that is not maintained.  We should be consistent across the repo.

**Comment by AtsushiKan** [comment]
This is a perfect example of attempting to legislate something that does not need to be legislated. I have not heard a single reason how imposing one rule across the repo for this improves dev productivity, or makes the code more robust, performant or easier to understand. Consistency is meant to promote these aspects - I do not regard it as an end in itself.

As I've said elsewhere, I find it useful to know that the implementation is the final destination of that method and I find it productive to have that information directly on the method definition instead of many lines away on a type definition. It is far easier to scan code that follows this discipline for methods that should be sealed but were inadvertently left unsealed. (Yes, I do these kind of scans.)

I also find it useful to ensure that everything remains sealed by default when a future change unseals a type. 

Typing "sealed" when overriding a method is a habit I find useful. I do not intend to change it simply because the declaring type is sealed, or to yo-yo back and forth as types becomes sealed and unsealed during the early stages of development.

I have yet to hear from anyone who felt that having explicit 'sealed' made the code less productive or readable for them.

**Comment by stephentoub** [comment]
> This is a perfect example of attempting to legislate something that does not need to be legislated

You raised the issue of consistency.  If it doesn't need to be legislated in one direction, then it doesn't need to be legislated in the other direction either.

> I have not heard a single reason how imposing one rule across the repo for this improves dev productivity

Because it sets expectations that allows devs familiar with the style to better understand the code.  Or to avoid generalizing, it absolutely does that for me.

> Consistency is meant to promote these aspects - I do not regard it as an end in itself.

Agreed.  And in this case, for me it's the easier to understand.

> I have yet to hear from anyone who felt that having explicit 'sealed' made the code less productive or readable for them.

You've heard from me.
- I find it less readable, in that it's more to read and internalize when I don't care about that aspect of it. Most of the time when looking at a method I don't need to know whether it could be overridden or not, and in situations where I do care, I'm rarely looking at just that one method: I'm looking at the whole type for context, at which point having one place to look is valuable.
- I find it makes me less productive, as when I see sealed on the method, I immediately start wondering why it's sealed, and I look around to understand why it's sealed... only to then realize I've wasted my time because the whole type is sealed.

**Comment by AtsushiKan** [comment]
>If it doesn't need to be legislated in one direction, then it doesn't need to be legislated in the other direction either.

I'm fine with not legislating it in either direction. Not all components have the same needs.

**Comment by stephentoub** [comment]
> I'm fine with not legislating it in either direction.

And yet you commented that I need to add a "missing" sealed.

I actually do think this is something where style should be enforced.  Some devs work on lots of different components in the repos, others are entirely unassociated with the repo other than this or that PR they submit, and there are folks (like me) who spend a lot of time reviewing lots of PRs.  I cannot keep track of different style rules for different components nor keep in mind which components certain shared files are associated with.  I do believe we need to pick a style for this kind of thing and adhere to it.

> Not all components have the same needs.

Can you explain what makes the crypto components different in this regard?  And has it hurt the crypto project that many sealed types are not following your desired approach?

**Comment by AtsushiKan** [comment]
> in situations where I do care, I'm rarely looking at just that one method: I'm looking at the whole type for >context, at which point having one place to look is valuable.

I don't see how explicit sealed on method works against that. It's not like I'm advocating doing **in lieu of** sealing the type itself.

**Comment by stephentoub** [comment]
> I don't see how explicit sealed on method works against that.

My point was it doesn't help, and for me it hurts other things, namely that seeing it makes me think I actually need to spend time understanding why it was applied.

**Comment by AtsushiKan** [comment]
>> I'm fine with not legislating it in either direction.
>
>And yet you commented that I need to add a "missing" sealed.

Well yes, because you were specifically changing a class that did follow that discipline and that I used to work on. I haven't been going around projects that I never touched (or even projects that I may have touched once or twice) and insisting they adopt this.

>I cannot keep track of different style rules for different components nor keep in mind which >components certain shared files are associated with.  I do believe we need to pick a style for this kind >of thing and adhere to it.

Having fewer unnecessary style rules would promote just that.

**Comment by stephentoub** [comment]
> Having fewer unnecessary style rules would promote just that.

And leave the code very haphazard, which has its own downsides.  There is value in style guidelines.  It's one of the reasons VS has recently invested heavily in enabling style to be enforced, why projects like stylecop have flourished, etc.

> because you were specifically changing a class that did follow that discipline and that I used to work on

Nowhere in the class was it commented that it was explicitly following such a discipline.  If it's not guided at a repo level, how do you expect a developer making a change to understand whether a particular class they're editing is adhering to a particular unannounced style?  Every time they make a change, review all related code to try to discern what policies a previous developer may have been attempting to adhere to?

**Comment by AtsushiKan** [comment]
>when I see sealed on the method, I immediately start wondering why it's sealed, and I look around to understand why it's sealed

For me, it's exactly the opposite. When I see a method that's unsealed (or appears unsealed), I find myself asking who's expected to override it, why there's an extension point here, whether the fix I'm making in this method requires similar fixes in the overrides. That's extra overhead that can be avoided if there's no need for a method override to be further overridable.

**Comment by AtsushiKan** [comment]
>Nowhere in the class was it commented that it was explicitly following such a discipline. If it's not guided 
>at a repo level, how do you expect a developer making a change to understand whether a particular class 
>they're editing is adhering to a particular unannounced style? 

In this specific case, local consistency is a good guide. And when that fails, note it in a PR that was done here.

**Comment by stephentoub** [comment]
> In this specific case, local consistency is a good guide

I don’t believe that’s a viable approach.  It encumbers the developer with needing to spend time analyzing the style of every file they touch, and it encumbers the reviewer(s) with needing to do the same.

> And when that fails, note it in a PR that was done here.

So a subsequent developer touching a file needs to go through the commit history to review every change made to that file?

> For me, it's exactly the opposite.

And that's of course fine: every developer has their own preferences, their own mental models, their own expectations, etc.  Which is one of the reasons it's important to have repo-wide guidelines and consistency: whatever your default preferences may be, you can easily understand the repo's guidelines and then no matter what code you're reviewing or modifying in the repo, set your expectations accordingly.

And when looking at the whole repo, not using "sealed" on such methods is by far the preference exhibited by the code.  I threw together a roslyn analyzer to look over all source files in the repo for sealed types, and then on those types, for overrides, and whether those overrides were marked sealed or not.  This isn't 100% exact, e.g. due to partial files and other such things that could confuse it, but it should be good enough for estimate purposes:
- The analyzer found 6064 non-sealed overrides on sealed types and only 162 sealed overrides on sealed types (so 97% of overrides on sealed types don't use "sealed").
- Of those 162, 113 were in crypto code (based on a heuristic of looking for “crypt” in the path, ignoring case).
- And even in the crypto code, there was far from a discipline of always using sealed: there were 113 sealed overrides on sealed types, but 455 non-sealed overrides on sealed types.
- And even then, the files that used sealed weren’t always purely using sealed: there were 38 crypto files that had sealed overrides on sealed types (98 that had non-sealed overrides on sealed types), and more than 20% of those also had non-sealed overrides on sealed types.

**Comment by AtsushiKan** [comment]
>>In this specific case, local consistency is a good guide
>
>I don’t believe that’s a viable approach. It encumbers the developer with needing to spend time analyzing >the style of every file they touch, and it encumbers the reviewer(s) with needing to do the same.

I don't think the encumbrance is anywhere near as high as you're making it out to be. The 90% case is that same group of developers is working on the project. These people will know the local tradition for sealed and whether anyone even cares about that edge case in that project (so far, we only have two people who care - albeit in opposite directions.) Every once in a while, you get the "guest" contributor to that project. If he doesn't notice that pattern, someone in the PR notices or they don't - they eventually tidy it up later if it matters to them. In the space about 4 years, I've probably spent five minutes total mentioning in a codeflow - "hey, I'd prefer you mark this method sealed" and it's done - no fuss. And occasionally, one slips by me - again, not the end of the world - I eventually catch it and I still get 99% of the value of the signposting.

>97% of overrides on sealed types don't use "sealed"

I suspect that's just because most people don't bother to use the keyword if the compiler doesn't nag them - I wouldn't be surprised if a lot of un-overridden overrides on their unsealed types are also left without the keyword. C# just made the wrong default here in my opinion - after all, non-overrides are "sealed" (non-virtual) without a special keyword. We can't change that now, but the fact remains that I work often in code bases where classes have dozens of virtuals and overrides and deep hierarchies, and I **do not** want to hunt through a sea of " override " lines to find the 2% that isn't really "sealed override." I'd rather mark it once when I write the method and be done with it and not have to remember "oh if it doesn't have "sealed", scroll up to find the class definition which may not even be in this file (partial classes) and see if it has the "sealed."" That algorithm is not grep-friendly, nor it it VS find-friendly. Quite frankly, I would simply choose to leave the the internal types unsealed with private constructors rather than deal with that.
