### ISSUE TITLE
Test failure: HttpClientEKUTest tests are disabled

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23139]
These tests are disabled due to failures.  The failures need to be investigated to determine whether there's missing functionality, bugs, etc., or whether the tests should be fixed, aren't applicable, etc.

**Comment by wfurt** [comment]
This seems to be configuration problem. When I import https://github.com/dotnet/corefx-testdata/blob/master/System.Net.TestData/contoso.com.p7b into OS trusted CA storage I can pass the tests. 

Existing test is explicitly loading them from user store and I guess the underlaying ssl stream may not do that by default. I'll work on fix but it seems like something we do not need to worry about too much.

      <test name="System.Net.Http.Functional.Tests.ManagedHandler_HttpClientEKUTest.HttpClient_NoEKUServerAuth_Ok" type="System.Net.Http.Functional.Tests.ManagedHandler_HttpClientEKUTest" method="HttpClient_NoEKUServerAuth_Ok" time="0.0356458" result="Pass" />
      <test name="System.Net.Http.Functional.Tests.ManagedHandler_HttpClientEKUTest.ShowVersion" type="System.Net.Http.Functional.Tests.ManagedHandler_HttpClientEKUTest" method="ShowVersion" time="0.0132012" result="Pass" />
      <test name="System.Net.Http.Functional.Tests.ManagedHandler_HttpClientEKUTest.HttpClient_ServerEKUClientAuth_Fails" type="System.Net.Http.Functional.Tests.ManagedHandler_HttpClientEKUTest" method="HttpClient_ServerEKUClientAuth_Fails" time="0.0450032" result="Pass" />
      <test name="System.Net.Http.Functional.Tests.ManagedHandler_HttpClientEKUTest.HttpClient_ClientEKUServerAuth_Fails" type="System.Net.Http.Functional.Tests.ManagedHandler_HttpClientEKUTest" method="HttpClient_ClientEKUServerAuth_Fails" time="0.0200869" result="Pass" />
      <test name="System.Net.Http.Functional.Tests.ManagedHandler_HttpClientEKUTest.HttpClient_NoEKUClientAuth_Ok" type="System.Net.Http.Functional.Tests.ManagedHandler_HttpClientEKUTest" method="HttpClient_NoEKUClientAuth_Ok" time="0.0396614" result="Pass" />

**Comment by pjanotti** [comment]
Tests were enabled by #23754 but in practice they are not running because conditions `CanTestCertificates` and `CanTestClientCertificates` are not met, at least in local runs, when looking at MC they are also skipped both for managed and unmanaged.

@dotnet/dnceng when looking for the skip reasons for this [test](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180130.05/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ManagedHandler_HttpClientEKUTest~2FHttpClient_ClientEKUServerAuth_Fails) the box is empty - I think the intention was to show why they were skipped, no?

**Comment by MattGal** [comment]
Thanks for pointing that out @pjanotti!  We were actually ignoring those skip results in the XML currently (I think the reason we show the page you point out was a side effect of showing XUnit failure reasons)

I filed https://github.com/dotnet/core-eng/issues/2553 to fix this.

**Comment by davidsh** [comment]
PR #23754 re-enabled these tests.  So, there is no actionable work for this issue anymore.
