### ISSUE TITLE
[ManagedHandler] Improve cancellation support when sending/receiving data

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23141]
The ManagedHandler_CancellationTest tests are disabled because sockets don't support canceling individual operations.  We might be able to address this once https://github.com/dotnet/corefx/issues/22608 is implemented and the associated cancellation support is enabled.  We could also employ a variety of workarounds, including ending the whole request on cancellation by disposing of the connection, wrapping the operations in ones that can be canceled even though the underlying operation may continue running, etc.

**Comment by WinCPP** [comment]
@stephentoub Before submitting any fix, I wanted to witness the error, so uncommented the associated test `ManagedHandler_CancellationTest` at this [link](https://github.com/dotnet/corefx/blob/08802ff9c877f7f75a82d6704d84d321e99eb5c8/src/System.Net.Http/tests/FunctionalTests/ManagedHandlerTest.cs#L107-L116) where I found reference for this issue #23141. I also commented of the reference to `ActiveIssue` #19038 at [this](https://github.com/dotnet/corefx/blob/1adc5b27283de6e9627e183ef24e0631ee7bab9a/src/System.Net.Http/tests/FunctionalTests/CancellationTest.cs#L32) line.

Still, I am not able to reproduce the issue by giving command `msbuild /t:RebuildAndTest` in the folder `./src/System.Net.Http/tests/FunctionalTests` where the test resides. I even tried with parameter `/p;framework=netcoreapp` to `msbuild` command.

Am I missing something? Appreciate your inputs.

**Comment by stephentoub** [comment]
@WinCPP, the test is marked `[OuterLoop]`, so you need to add `/p:Outerloop=true` to the msbuild command.

**Comment by WinCPP** [comment]
Hi @stephentoub , I think I have some solution. The method `GetAsync_ResponseContentRead_CancelUsingTimeoutOrToken_TaskCanceledQuickly` ([link](https://github.com/dotnet/corefx/blob/1adc5b27283de6e9627e183ef24e0631ee7bab9a/src/System.Net.Http/tests/FunctionalTests/CancellationTest.cs#L33)) annotated with attribute `ActiveIssue` #19038 no more fails. However I noticed that the test case 'ReadAsStreamAsync_ReadAsync_Cancel_TaskCanceledQuickly' ([link](https://github.com/dotnet/corefx/blob/1adc5b27283de6e9627e183ef24e0631ee7bab9a/src/System.Net.Http/tests/FunctionalTests/CancellationTest.cs#L110)) in the same file fails i.e. blocks, on my PC and, without commenting it out, I am not able to test the `GetAsync...` method.

I am not sure if `ReadAsStreamAsync_ReadAsync_Cancel_TaskCanceledQuickly` should block; it doesn't have any `ActiveIssue` annotation for netcoreapp framework. Please let me know if this is expected behavior on PC.

Also should I raise a PR for whatever code changes I have done...? Appreciate your inputs.

**Comment by stephentoub** [comment]
> However I noticed that the test case 'ReadAsStreamAsync_ReadAsync_Cancel_TaskCanceledQuickly' (link) in the same file fails i.e. blocks

That would seem to be due to your changes then.  It's currently passing on .NET Core.

**Comment by stephentoub** [comment]
> Also should I raise a PR for whatever code changes I have done...?

Sure, but I'm not sure how you'll be successful at this presently, given that the underlying sockets don't yet have actual support for cancellation enabled.  What is the solution you're attempting?

**Comment by WinCPP** [comment]
Hi @stephentoub,

The solution that I am attempting is based on one of the ways that you mentioned in the opening comment for this issue, quoted below,

> wrapping the operations in ones that can be canceled even though the underlying operation may continue running, etc.

I came across [this](https://blogs.msdn.microsoft.com/pfxteam/2012/10/05/how-do-i-cancel-non-cancelable-async-operations/) blog of yours on which the solution is based. I understand that it may not be clean solution but it kind of adheres to one of the suggested solutions (for now until sockets get support for cancellation)...

I am fine tuning the code and also checking why `ReadAsStreamAsync_ReadAsync_Cancel_TaskCanceledQuickly` hangs... else will publish a PR for whatever I have coded in a day or two...

**Comment by WinCPP** [comment]
Hi @stephentoub I could make some progress on this. As for the hang in `ReadAsStreamAsync_ReadAsync_Cancel_TaskCanceledQuickly`, I found that it needs separate fix in 'ContentLengthReadStream' as after the response has been obtained, since `ContentLengthReadStream` doesn't handle cancellation via token and hence the hang. I am working on this. Also instead of allowing the underlying operation to continue, I am trying to find a way to close the httpconnection or the underlying stream (NetworkStream) so that there is an IOException or ObjectDisposedException, either of them triggered because the connection and / or the stream was disposed.

**Comment by WinCPP** [comment]
Hi @stephentoub thanks for the inputs in [this](https://github.com/dotnet/corefx/pull/25511#issuecomment-348285760) comment. I will try working on it for #24430 and then make use of it here...

**Comment by geoffkizer** [comment]
@stephentoub per our email discussion, sounds like you have a solution for this...

**Comment by stephentoub** [comment]
We can do something similar to what WinCPP was working on. I'm working through some of the more intricate details. It's far from ideal, but I think it'll be shippable.
