### ISSUE TITLE
[ManagedHandler] Support Windows & Unix environment variables for proxy configuration

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23150]
libcurl and other clients respect an established convention for environment variables used to configure proxies.  We should respect these in ManagedHandler as well.

**Comment by geoffkizer** [comment]
Dumb question, why isn't this already done by the IWebProxy stuff?

**Comment by stephentoub** [comment]
> why isn't this already done by the IWebProxy stuff?

I'm not sure what you mean.  Can you clarify?

**Comment by geoffkizer** [comment]
I'm trying to page back in how all this stuff works.  I believe it's as follows:

There's a method on WebRequest called GetSystemWebProxy.  By default, WebRequest.DefaultWebProxy is set to this.

Unfortunately, the thing returned by GetSystemWebProxy is a fake proxy that just acts as a sentinel to the lower layers, i.e. WinHttpHandler and CurlHandler.

I guess what I'm suggesting is:
(1) We should make GetSystemWebProxy work properly (read OS settings, perform appropriate proxy resolution)
(2) We should probably expose this somewhere other than WebRequest, to avoid the dependency
(3) We should use this in ManagedHandler

I seem to recall there was a separate request for (1) previously, but I can't seem to find it now.

Dumb question: Do we respect IE proxy settings in ManagedHandler?  I can't find it anywhere.  Do we want to?

**Comment by davidsh** [comment]
>(1) We should make GetSystemWebProxy work properly (read OS settings, perform appropriate proxy resolution)

fyi. This is non-trivial.  reading OS settings might involve WPAD protocol which means using DHCP and looking for a PAC (JavaScript) file on the network. This means using a JavaScript interpreter, etc.  We use WinHttpAuto Proxy Discover service on Windows for this.  Long ago, .NET Framework did JavaScript execution but we deprecated that.

**Comment by geoffkizer** [comment]
Here are some related issues:

https://github.com/dotnet/corefx/issues/7037
https://github.com/dotnet/corefx/issues/16695

**Comment by geoffkizer** [comment]
@davidsh yeah, I recall that from previous discussions.

That said,
(a) WinHttpClientHandler respects these settings (because WinHTTP does) -- and similarly, CurlHandler respects the Linux convention for these things
(b) We want the managed handler to do the same, I believe
(c) So, we need to do something here to get the settings from the OS

Does that sound right?

**Comment by geoffkizer** [comment]
For future reference: https://msdn.microsoft.com/en-us/library/windows/desktop/aa384122(v=vs.85).aspx

**Comment by davidsh** [comment]
WinHttpHandler uses this code (on Windows 7) to support proxy detection/evaluation:

https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinInetProxyHelper.cs

This code is needed on Windows 7 since WinHTTP didn't have the "automatic detect proxy settings" logic built-in to the main request logic.  This code basically does what .NET Framework does in that it call WinHTTP APis to invoke the WinHttp AutoProxy Discover Service. It looks for "system proxy settings" (i.e. IE settings) and then uses that information, retrieves a PAC file if necessary, and returns a proxy uri given an input destination uri.  This code could in theory be adapted to fully implement System.Net.WebProxy class on Windows.

**Comment by stephentoub** [comment]
@wfurt, this is done and can be closed, right?

**Comment by wfurt** [comment]
The missing part us bypass list on Windows @stephentoub.  I know what needs to be done now and I started on it - but did not finished yet. That can possibly be tracked as separate issue.
