### ISSUE TITLE
[ManagedHandler] Investigate adding connection draining support

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23156]
Today when we cancel/dispose a response and we've not yet handled all of the expected response data from the server, we abandon the connection rather than putting it back into the pool.  We should investigate adding support for draining the remaining data from the connection, and whether it's worthwhile from a performance perspective (maybe just for https, given the additional overhead associated with establishing the connection?).  WinHttp drains up to 1MB by default.

**Comment by clrjunkie** [comment]
Does WinHttp drain the response if cancellation happened after issuing the request but before receiving response bytes?

**Comment by scalablecory** [comment]
Perhaps keep track of connect speed and use that as a timeout to drain before giving up on the connection.

**Comment by Tratcher** [comment]
Yes please. HttpWebRequest had a lot of trouble with this around 4.5.1. It originally drained forever. Around 4.5.1 they decided to abort connections rather than draining. This immediately regressed perf and exhausted ports in a wide variety of applications. The most common repro was a chunked response with structured data. The data parse had read all of the structured data but had stopped reading before the stream consumed the final chunked terminator and returned 0.

There were multiple QFE's and GDRs to try to address the issue.
https://support.microsoft.com/en-us/help/2745583/a-hotfix-is-available-for-the--net-framework-4-5-which-resolves-severa

**Comment by geoffkizer** [comment]
We should also look at draining behavior when we consume a response internally -- i.e. auth challenges, redirects, etc.  If we aren't draining properly here then we're just throwing away valid connections.

We need to at least look at this for 2.1.

**Comment by geoffkizer** [comment]
Having looked at this a bit more, I think we definitely need to add draining support in 2.1.

**Comment by geoffkizer** [comment]
I think there are really two cases here.

One is "internal drain" for when we are consuming a response internally -- specifically auth challenges (401 or 407, i.e. regular or proxy) or redirects (30x).  In this case, the server often sends a short response body.  We want to drain this up to some limit before proceeding with the next request, so that we can send the next request on the same connection instead of abandoning the current connection and using a new one.

The other is "external drain" for when a user calls Dispose on an HttpResponseMessage without having read the entire response body, *when using* HttpCompletionOption.ResponseHeadersRead (otherwise the response body is always buffered).  This case is a little more complicated, because we probably don't want to block Dispose on draining the connection.  However:
(1) If we already have read off the wire to the end of the response body, but just haven't returned it to the user yet, then there's no reason not to just discard this data and return the connection to the pool immediately.
(2) If we haven't, then it seems reasonable to do some amount of draining asynchronously from the Dispose call.  This means the connection will eventually be put back in the pool (if the drain succeeds), but not necessarily immediately after the Dispose call.  

From some quick testing, WinHttp seems to do (1) but not (2).  I'm going to test Curl etc as well.

**Comment by geoffkizer** [comment]
"Internal drain" is the issue relevant to #26732.

**Comment by Tratcher** [comment]
From the handler's perspective both internal drain and external drain are the same. There's a connection that may still have data on it, drain the data so you can re-use it. Draining on a background thread is a good idea, there's no reason to block the caller for data it has abandon. Allowing the auth code to call Dispose on the response would simplify the logic at that layer.

**Comment by geoffkizer** [comment]
> Allowing the auth code to call Dispose on the abandoned response would simplify the logic at that layer.

I agree, but it also opens up the possibility that we will go into the async-drain case ((2) above) and then end up grabbing a different connection.  Maybe that's fine though.

**Comment by geoffkizer** [comment]
A slightly different approach would be to drain "on-demand" instead of asynchronously.  That is, put the connection back in the pool with a "needs drain" flag.  Then if/when it's retrieved from the pool, do the drain then, or fail the connection if we can't drain it and get another.

I think this would simplify usage; e.g. auth code can just call Dispose.

**Comment by Tratcher** [comment]
That would add latency and possible errors to outgoing requests.  There's some discussion in the NTLM mail thread about trying to re-use the same connection for internal re-submissions so you can avoid a trip back through the connection pool queue.

**Comment by geoffkizer** [comment]
It wouldn't be an error for outgoing requests; if the drain fails we'd just get a different connection.

Re latency: 

For "internal drain" (i.e. auth) it's a wash; we are going to drain the connection before the next request anyway.  

For "external drain", it seems like there are various tradeoffs here.  Sync drain blocks the original response.Dispose(); that seems bad.  Async drain is better, but then then connection isn't available until the async drain completes.  Is it better to wait for the async drain on an existing connection or just create a new connection?  On-demand drain favors the former, which seems good.  So maybe we want both; try to proactively drain asynchronously, but then drain on-demand if the connection is needed.

Honestly I'm not sure it matters that much, since in most cases we are talking about (a) a small amount of data that (b) hopefully has already arrived in the kernel receive buffer at the point when we start to drain.  And if (a) or (b) is not the case we can simply discard the connection.

**Comment by stephentoub** [comment]
I suggest starting just with async drain, initiated inside the logic that returns a connection to the pool.

**Comment by geoffkizer** [comment]
Fixed by #27315
