### ISSUE TITLE
Invalid results of the function GetAttributeFromHeader in System.Net.HttpListenerRequest

### ISSUE THREAD

**Issue by chessar** [dotnet/corefx#23506]
https://github.com/dotnet/corefx/blob/ff7f4ba7ab0a9f50a0e4c1d3a3195165afd96d8f/src/System.Net.HttpListener/src/System/Net/HttpListenerRequest.cs#L293

For example, for parameters
headerValue = `"multipart/form-data; boundary=abc; charset=UTF-8"` (from Content-Type header) and
attrName = `"boundary"`
The result will be

>"abc;"

instead

>"abc"

**Comment by caesar1995** [comment]
Quote RFC 7578:

> it is often necessary to enclose the
   "boundary" parameter values in quotes in the Content-Type header
   field.

We don't have problem parsing boundary value enclosed in quotes. But I agree that if boundary value doesn't have quote around it, we should not include `;` at the end.

**Comment by caesar1995** [comment]
Hey @chessar, thanks for reporting this issue!

I'm curious how did you discover this problem, and why do you need to call this function?

The `GetAttributeFromHeader` is an internal helper method inside a private class, which is only used in one place: `string charSet = Helpers.GetAttributeFromHeader(ContentType, "charset");` to get the content type in header.

We will only use it to get headerValue for attrName = `"charset"`, and nowhere else. Is there a reason/scenario you need to use this function for "boundary" attribute?

**Comment by chessar** [comment]
Hello @caesar1995,
Initially, I post a bug in [https://github.com/Microsoft/referencesource/issues/32](https://github.com/Microsoft/referencesource/issues/32). And there, this is used when getting Files, Form in System.Web.HttpRequest (in the `GetMultipartBoundary`). And then post it here, too. It uses an absolutely identical code.

**Comment by caesar1995** [comment]
This is .NET Framework issue, and in .NET Core, this legacy function is only used to parse `charset` attribute for `HttpListenerRequest` header value.

It's a convention that we put `charset` parameter at the end of `Content-Type` header (there is no RFC explicitly defines it), so there is no semicolon after it. For now, we don't have issue parsing the value.

@karelz Could you point @chessar a place to report Framework bug?

**Comment by karelz** [comment]
@caesar1995 why is it not a problem on .NET Core? I assume we are parsing headers from client. If client doesn't put `Content-Type` at the end, we will have a problem. Or did I misunderstand?

The guidance for .NET Framework bugs is on our main page: https://github.com/dotnet/corefx#how-to-engage-contribute-and-provide-feedback

**Comment by caesar1995** [comment]
> If client doesn't put Content-Type at the end, we will have a problem. Or did I misunderstand?

If client doesn't put `charset` parameter at the end of `ContentType` header (very unlikely), we will have a problem. But I think we should wait for customer's report, then to fix it. We can discuss offline.

In .NET Core, the function `GetAttributeFromHeader` is an internal helper method inside a private class, which is _**only**_ used in [one place](https://github.com/dotnet/corefx/blob/ff7f4ba7ab0a9f50a0e4c1d3a3195165afd96d8f/src/System.Net.HttpListener/src/System/Net/HttpListenerRequest.cs#L95).

1. It's purpose is to get the `charset` value from `ContentType` header, and that's it only purpose.
 - It's a convention (not requirement) that we put the `charset` parameter at the end of `ContentType` header, so that its value should not append the semicolon at the end. We have no problem parsing its value.
 - If there is a real world scenario that we cannot correctly parse the `charset` value from `ContentType` header, then we will need to make product change to correct it.
 - Consider that's a legacy function, and I have checked Framework's source code and found very interesting comment for this function (don't think it's appropriate to post here). We can discuss offline if we want to actively fix it now, or wait for customer report to understand real world scenario and fix it.

2. Developer should not able to access/use this function.

**Comment by caesar1995** [comment]
> He often adds the charset to the header `multipart/form-data; boundary=...; charset=UTF-8`.

I have tried this data in Core, seems we don't have issue getting the `charset` value (correctly get `UTF-8`). Did you observe anything different?

**Comment by chessar** [comment]
I agree that .NET Core has no problems with this function and apparently it is necessary to close this issue here. 
Moreover, if this function is considered obsolete, and (hopefully) it will not be used anywhere else (for example, for `boundary`, as in the .NET Framework). But for System.Web.HttpRequest in the .NET Framework, I think this is an error. In the near future I will make a report in accordance with the guidance for .NET Framework bugs

**Comment by caesar1995** [comment]
> if this function is considered obsolete, and (hopefully) it will not be used anywhere else 

Yes, I can confirm it.

> But for System.Web.HttpRequest in the .NET Framework, I think this is an error. In the near future I will make a report in accordance with the guidance for .NET Framework bugs

I agree. Notice that Microsoft/referencesource is a not-monitored repository. Please follow instructions on this link https://github.com/dotnet/corefx#how-to-engage-contribute-and-provide-feedback to report Framework issue. Thanks!

Closing.

**Comment by chessar** [comment]
OK, @caesar1995 , and thank you.

**Comment by karelz** [comment]
Discussed offline. In theory client can send the `charset` in the middle. Let's try to fix the function. If it is too difficult I am ok to give up, given that we do not have any real-world scenario broken (yet).
However, the parsing doesn't sound correct, so if we can fix it cheaply and with low-risk that would be great.
