### ISSUE TITLE
I can't find a coreclr equivalent of System.Environment.Exit(int)

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/corefx#2353]
I would like to be able to exit an Application and set and exitcode without falling through main ().  On the desktop this Api allowed me to do this.

https://msdn.microsoft.com/en-us/library/vstudio/system.environment.exit(v=vs.100).aspx

This is especially useful for scripts.

Thanks

**Comment by terrajobst** [comment]
According to our design notes the replacement is:

> Use `Environment.FailFast(string, Exception)`

It seems that's not 1:1 replacement given that the purpose of failing fast is to not run finally handlers. However, it seems F# would want to properly exit.

@stephentoub, @weshaggard any thoughts on this? Would this have any cross-platform impact?

**Comment by stephentoub** [comment]
> Would this have any cross-platform impact?

Should be fine.

**Comment by weshaggard** [comment]
We have always been hesitant to expose Exit for CoreCLR because it is generally hosted and Exit is a app-model concept. For example if you were hosting CoreCLR in a larger application like a browser or VS would you want to exit the process? Our general guidance is to try and simply return out until you return from the entry point method, that would allow everything to clean-up and then the host can chose how to exit. 

However with that said as we start supporting console applications we may need to figure out a good way to expose some application level concepts like exit so we can set correct return codes and such. That seems like a app-model concern that we may want to figure out how to expose in an app-model specific contract.

**Comment by tparnell8** [comment]
I'd like to see a way people can set error codes...

here is a use case. I make tools that are console based for things like jenkins. Now I return error codes so that tools like jenkins know if there were errors or not, and also callers of my tools can catch expected error codes and take action based on the code.

I think returning an error code is pretty meaningful and the FailFast method doesn't seem to give the ability to add the code to the environment.
