### ISSUE TITLE
Math.Sin(double) returning incorrect result on .NET Standard 2.0

### ISSUE THREAD

**Issue by NightOwl888** [dotnet/corefx#23587]
I have put together a test case as proof. It passes on .NET Framework 4.5.1 and .NET Standard 1.5 (with a .NET Core 1.0 client), but fails on .NET Standard 2.0 (with a .NET Core 2.0 client). The test requires NUnit (I am using 3.7.1), but I have ruled out NUnit as the cause:

```c#
        public static readonly double DEGREES_TO_RADIANS = Math.PI / 180;
        public static readonly double RADIANS_TO_DEGREES = 1 / DEGREES_TO_RADIANS;

        [Test]
        public void CalcDistanceIncorrectOnNetStandard2_0()
        {
            double lat2 = 1.5707963267948966;
            double dist1 = DistHaversineRAD(0, 0, lat2, 0);
            double dist2 = ToDegrees(dist1);

            Assert.AreEqual(90, dist2, 0);
        }

        public static double DistHaversineRAD(double lat1, double lon1, double lat2, double lon2)
        {
            // Check for same position
            if (lat1 == lat2 && lon1 == lon2)
                return 0.0;
            double hsinX = Math.Sin((lon1 - lon2) * 0.5);
            double hsinY = Math.Sin((lat1 - lat2) * 0.5);
            double h = hsinY * hsinY +
                    (Math.Cos(lat1) * Math.Cos(lat2) * hsinX * hsinX);
            return 2 * Math.Atan2(Math.Sqrt(h), Math.Sqrt(1 - h));
        }

        public static double ToDegrees(double radians)
        {
            return radians * RADIANS_TO_DEGREES;
        }
```

The result of this line

```c#
double hsinY = Math.Sin((lat1 - lat2) * 0.5);
```

is `-0.70710678118654746` on .NET Framework 4.5.1 and .NET Standard 1.5, but it is `-0.70710678118654757` on .NET Standard 2.0. I have confirmed the result of `(lat1 - lat2) * 0.5` is `-0.78539816339744828` in both cases (the value being passed into `Math.Sin(double)`).

Note also the program is being ported from Java, and a similar test passes there with the same input and expected output.

## Environment

.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by danmosemsft** [comment]
@tannergooding do you know of issues in our Sin?

**Comment by tannergooding** [comment]
The "new" result is well within a "reasonable" tolerance range for floating-point computations. `sin(-0.78539816339744828)`, computed to 17 digits is `-0.70710678118654750`, which is not exactly representable. The nearest representable value is `-0.70710678118654746` (binary: `0xBFE6A09E667F3BCC`). We are returning `-0.70710678118654757` (binary: `0xBFE6A09E667F3BCD`) which is only off by 1 bit.

The change that resulted in the different computed output came with: https://github.com/dotnet/coreclr/pull/4847 in netcore1.1.

Previously, we were using the x86 `fsin`, `fcos`, and `ftan` x87 FPU instructions to compute `Math.Sin`, `Math.Cos`, and `Math.Tan`. Outside of these instructions being slow (moving off of them introduced a `68%`, `59%`, and `59%` performance improvment) they are also well known to be inaccurate in the larger input domain (https://software.intel.com/blogs/2014/10/09/fsin-documentation-improvements-in-the-intel-64-and-ia-32-architectures-software and https://randomascii.wordpress.com/2014/10/09/intel-underestimates-error-bounds-by-1-3-quintillion/).

Today, we are just compiling down to use the C Runtime implementation (as we were doing with the rest of the `System.Math` APIs) which generally provides greater speed and accuracy across the entire input domain for a function. However, this also means that certain outputs may be different between architectures (x86, x64, ARM, etc) or between different Operating Systems (Windows, Mac, Linux, etc), but this is really no different from the behavior you would get today when compiling native code (C/C++ or anything else using libc, libm, or msvcr).

**Comment by tannergooding** [comment]
@danmosemsft, as a summary, I don't think this is an issue. This is well within a reasonable tolerance range and the commit that introduced this change brought along performance and input/output improvements across the entire domain of inputs.

**Comment by NightOwl888** [comment]
> I don't think this is an issue. This is well within a reasonable tolerance range and the commit that introduced this change brought along performance and input/output improvements across the entire domain of inputs.

Microsoft has historically always sided with providing a high degree of backward compatibility over "new and improved". Ok, so maybe this doesn't have to be default calculation, but it should at least be available so it is possible to port applications from Java and also to support multi-targeted applications across .NET Framework and .NET Core without having different results. Can we put in some kind of configuration switch (`Math.BackwardCompatibleMode = true` or `System.Compatibility.Math.Sin(double value)`) so we don't have to have ugly branching code just to get the same result as .NET Core 1.0, .NET Framework and Java?

If not, can you at least point me to the implementation you had in .NET Core 1.0 so I can copy it? Not so much interested in speed and "accuracy" as I am concerned that my result is exactly 90 degrees so the test passes.

**Comment by danmosemsft** [comment]
@NightOwl888 is this causing a bug in your application (or just making your unit test fail)?
I put this into Wolfram Alpha (sqrt(2)/2) and it gives a result between the two.

**Comment by jnm2** [comment]
@NightOwl888 Typically when unit testing floating point calculations, don't you typically compare the absolute value of the difference to a sufficiently small number? I've found that if I don't do that, my tests are brittle (and ReSharper yells at me for using `==` on a floating point).

In NUnit, this is `Assert.That(actual, Is.EqualTo(expected).Within(delta))` or `Assert.AreEqual(expected, actual, delta)` for some delta greater than zero.

Floating point is inherently lossy.

**Comment by Kosat** [comment]
.NET of any kind follows IEEE 754 double-precision limitations with its 53-52 bits or 15-17 meaningful digits mantissa size. From the 15-17 digits, to the managed developer only 15-16 are guaranteed.

The C# spec explicitly states *"The double type can represent values ranging from approximately 5.0 * 10^-324 to 1.7 × 10^308 with a precision of 15-16 digits"*.

Also, this MSDN article says about 15 digits guarantee: 
https://msdn.microsoft.com/en-us/library/system.double(v=vs.110).aspx

In your case **-0.70710678118654757** you have got 17 meaningful digits which are beyond the formally guaranteed 15 digits.

Perhaps, after [#4847](https://github.com/dotnet/coreclr/pull/4847) changes those 16-17 bits are now contain different values for new implementation utilizes different CPU instructions. 

But, most interestingly, **corefx** related tests also does checks on 17 digits.
https://github.com/dotnet/corefx/blob/0f8c08739b1c97895f4910535164031f13014bf0/src/System.Runtime.Extensions/tests/System/Math.cs#L1481

**Comment by tannergooding** [comment]
@NightOwl888 

> If not, can you at least point me to the implementation you had in .NET Core 1.0 so I can copy it? Not so much interested in speed and "accuracy" as I am concerned that my result is exactly 90 degrees so the test passes.

Code is here: https://github.com/dotnet/coreclr/pull/4847/files#diff-18adb492eaf36900c31745060ddbabeaL922.

It is in raw assembly and not easily consumable externally. Even if you do write your own C Library, and P/Invoke to it, the performance decrease may be considerable enough that it is not worthwhile. It will also no longer be portable if you don't provide some fallback mechanism for architectures or platforms where `fsin` isn't available.

> Microsoft has historically always sided with providing a high degree of backward compatibility over "new and improved".

This is all fine and good, but was already not guaranteed by the existing implementation. Essentially any API that is listed as `extern` in its signature cannot not have a guranteed back-compat implementation between different versions of the runtime. They are inherently tied to unmanaged code at some level which may have different behavior due to changes in the C Runtime, changes in the native compiler, etc.

They inherently have a chance to "break" anytime a new architecture or Operating System is introduced.

Several of the Math function (`Math.Ceiling` and `Math.Floor` for example) are not considered 'intrinsic' and instead are just implemented by the underlying C Runtime. They already differ between x86 and x64 (and even between versions of the CLR) due to changes in the underlying C Runtime.

`Math.Sin` was also implemented as a call to the underlying C Runtime for x86. The second x86 ryuJIT switched to enable SSE/SSE2 codgen by default for x86, this implementation no longer used the `fsin` instruction. The x64 implementation did not call the underlying C Runtime and instead had a manually implemented method that called the `fsin` instruction. The only reason this was done was due to a performance issue in the underlying C Runtime implementation for the SSE/SSE2 implementation. The bug was fixed in the C Runtime and the workaround was removed from the CLR.

> so it is possible to port applications from Java

This wasn't even guaranteed before the change. This assumes that the underlying implementation for the Math functions (or any function for that matter) is identical between Java and CoreCLR and that is almost certainly not the case (especially if they are not using a singular hardware instruction for the computations). Just because they happened to return the same output for `x` does not mean that they would also return the same output for `y`.

**Comment by tannergooding** [comment]
@kosat, it is important to note that the 15-17 digit rule comes from the IEEE spec for value->string and string->value conversions.

That is, a string of 15 significant digits, converted to double and back to a string should return an identical string.
And, a double converted to a string of 17 significant digits and back to a double should return an identical double.

CoreCLR, CoreFX, and C# are all meant to be IEEE compliant (this doesn't necessarily mean they always are, as based on various other bugs that get logged).

However, IEEE compliance does not guarantee that any computed result will be accurate to within 15-17 digits. It only guarantees value to string and string to value roundtripping for specific inputs.

It also only guarantees certain outputs for a set of inputs (generally, +0, -0, NaN, +Infinity, and -Infinity). It doesn't really say anything about the precision for `sin(-0.78539816339744828)` or for other arbitrary inputs.

That being said, most native compilers provide a "precise" and a "fast" mode.

Computing a result to 17 significant digits that most closesly represents the actual result is considered to be the "precise" computation.
Computing a result to within a certain ulp of error is generally considered to be the "fast" computation.

CoreCLR has always opted to be "fast" by default and has not provided a "precise" computation.

That being said, it would likely be useful to provide a switch so that users can opt-in to a "precise" mode if they need or want it. It would also be useful if we had consistent implementations across the various architectures and Operating Systems. Both may be more readily possible once the hardware intrinsics proposal gets implemented since that would allow us to have the algorithm exclusively in CoreFX without being dependent on taking fixes in CoreCLR.

**Comment by Kosat** [comment]
I'm sorry for the off-topic, but can somebody explain why in C# it was initially decided to allow floating point literals to extend those 15-16 digits, without even giving a warning? 
It is quite misleading, I recon.

**Comment by tannergooding** [comment]
@Kosat, likely just oversight. The spec indicates it is IEEE compliant and that `double` and `float` are explicitly the IEEE types (binary32 and binary64, respectively), so the IEEE spec likely wins on the formal behavior (regardless of what the C# spec says later on).

Someone like @MadsTorgersen could likely comment further (and confirm or deny the above).

**Comment by Kosat** [comment]
@tannergooding  The MSDN article I've mentioned before pretty much explains the reasoning of introducing the 15-digits formal limit.
> A Double value has up to 15 decimal digits of precision, although a maximum of 17 digits is maintained internally. This means that some floating-point operations may lack the precision to change a floating point value. 

And then even gives an example. 

I think, this artificial limitation was introduced with a good intention of keeping managed developers away from troubles.  :smile:

**Comment by tannergooding** [comment]
> I think, this artificial limitation was introduced with a good intention of keeping managed developers away from troubles.

I'm not sure that is the reason. Even two numbers with 15 significant digits (or fewer) might not cause a change in floating-point value. For example: `100000000 + 0.000000001` returns `100000000` even though we only have 9 and 1 significant digits and both are well within the IEEE range (this is because the next representable value is `100000000.00000002`).

**Comment by 4creators** [comment]
> I am concerned that my result is exactly 90 degrees so the test passes.

@NightOwl888 This not true since not very basic math (a bit higher one) tells that you cannot get exactly 90 degrees in this representation. I am afraid you have false sense of what means exact in computer world of reals. First of all 90 degrees is Pi/2 what cannot be represented exactly by any binary or decimal representation ..... Similar goes for majority of sin values. The only thing which can be done on computers is to calculate with reals with an error (even built in processor functions return values with errors). So you have to come to terms with delta or etta as was indicated by @jnm2 and write code with explicit handling of floating point calculation errors, otherwise, you will run into false statements about exact values.

**Comment by NightOwl888** [comment]
Unfortunately, I don't know enough about the implications of changing the test to meet this "new" set of expectations are to make a constructive argument against it, just that usually we change the software to make the tests pass, not the other way around. 

All I can say for certain is that this test was written on 2013-01-23 by someone who knows more about the way the software works than I do and it passes on Windows x86/x64 on Java, .NET Framework 4.5.1, and .NET Core 1.0 but fails on .NET Core 2.0. It *probably* also passes on Linux, Sun OS, Mac OSx, and Free BSD, but I haven't confirmed. The original test looks like this:

```java
  public void calcDistanceFromErrPct() {
    final SpatialContext ctx = SpatialContext.GEO;
    final double DEP = 0.5;//distErrPct

    //the result is the diagonal distance from the center to the closest corner,
    // times distErrPct

    Shape superwide = ctx.makeRectangle(-180, 180, 0, 0);
    //0 distErrPct means 0 distance always
    assertEquals(0, SpatialArgs.calcDistanceFromErrPct(superwide, 0, ctx), 0);
    assertEquals(180 * DEP, SpatialArgs.calcDistanceFromErrPct(superwide, DEP, ctx), 0);

    Shape supertall = ctx.makeRectangle(0, 0, -90, 90);
    assertEquals(90 * DEP, SpatialArgs.calcDistanceFromErrPct(supertall, DEP, ctx), 0);

    Shape upperhalf = ctx.makeRectangle(-180, 180, 0, 90);
    assertEquals(45 * DEP, SpatialArgs.calcDistanceFromErrPct(upperhalf, DEP, ctx), 0.0001);

    Shape midCircle = ctx.makeCircle(0, 0, 45);
    assertEquals(60 * DEP, SpatialArgs.calcDistanceFromErrPct(midCircle, DEP, ctx), 0.0001);
  }
```

It is unclear why the author of the test chose not to allow any delta on the first three assertions but did on the last two.

I have done my part - I have informed you that you have broken backward compatibility with .NET Core 1.0 and .NET Framework 4.5.1. But if that doesn't bother you because it is within the spec, then it doesn't bother me. Let's just close this as a won't fix, I will add some delta to the test expectations, and if any of our users have an issue with it (which I can't say with any certainty will happen) we can point them to this issue.

**Comment by jnm2** [comment]
> It is unclear why the author of the test chose not to allow any delta on the first three assertions but did on the last two.

My guess would be, he only added delta where he was forced to at the time. If that's the case, he would have added delta in every case if he was targeting .NET Standard 2.0.

**Comment by 4creators** [comment]
IMO it would be helpful if .NET docs introducing floating point math would contain short theoretical introduction to numerical analysis with scope consisting of (i) representation of reals in computers, (ii) nature of reals representation errors and their magnitude, (iii) calculation with floats, (iv) how errors accumulate during calculations with floats, (iv) stability of numerical algorithms, (v) strategies for mathematically sound testing of numerical calculations with floats.

@NightOwl888  The following references should help to better understand problems we are discussing:

- [Goldberg, David. "What every computer scientist should know about floating-point arithmetic." ACM Computing Surveys (CSUR) 23.1 (1991): 5-48.](https://people.eecs.berkeley.edu/~fateman/264/papers/goldberg.pdf)

- [Higham, Nicholas J. Accuracy and stability of numerical algorithms. Society for Industrial and Applied Mathematics, 2002.](http://epubs.siam.org/doi/abs/10.1137/1.9780898718027.bm)

Checking your test code:
```Java
    Shape superwide = ctx.makeRectangle(-180, 180, 0, 0);
    //0 distErrPct means 0 distance always
    assertEquals(0, SpatialArgs.calcDistanceFromErrPct(superwide, 0, ctx), 0);
    assertEquals(180 * DEP, SpatialArgs.calcDistanceFromErrPct(superwide, DEP, ctx), 0);

    Shape supertall = ctx.makeRectangle(0, 0, -90, 90);
    assertEquals(90 * DEP, SpatialArgs.calcDistanceFromErrPct(supertall, DEP, ctx), 0);
```
the source of representation errors comes from every function which operates on floats and every operation on floats with error _e_ will cause it's accumulation according to approximate formula `k*e` where _k_ is a number of operations and _e_ is an error expressed in number of digits or bits used in number representation. Therefore term 0 as an error level for the above tests is obviously incorrect and should be adjusted to correctly account for errors accumulated in calls to `ctx.makeRectangle`, `SpatialArgs.calcDistanceFromErrPct`, `90 * DEP`, and `180 * DEP`. I am convinced that once you adjust test errors according to rules from above mentioned publications tests wil pass and software will retain it's functionality. As far as I can read code snippet DEP is an error term and is roughly 0,5 degree or Pi/360 so the range of allowable calculation error is quite large in comparison to representation used in code.

**Comment by tannergooding** [comment]
> IMO it would be helpful if .NET docs introducing floating point math would contain short theoretical introduction to numerical analysis with scope consisting of (i) representation of reals in computers, (ii) nature of reals representation errors and their magnitude, (iii) calculation with floats, (iv) how errors accumulate during calculations with floats, (iv) stability of numerical algorithms, (v) strategies for mathematically sound testing of numerical calculations with floats.

This would be nice, but at the same time I feel its something you should learn in your introductory course to the language (or even in the introductory course to computer programming as a whole). IEEE floating-point math is prominent enough that anyone who learns to program should get a run down of them, especially if you are going to be learning C/C++, C#, Java, etc.

There are hundreds, if not thousands, of sample code that uses floating-point math. Providing a link to "understanding the basics of IEEE 754" at all of these places is not really reasonable. Providing a link on the docs for `System.Single`, `System.Double`, and on `Learn C#` seems like it is actually possible to do.

**Comment by NightOwl888** [comment]
Actually, rather than spending time recycling the floating point number documents, which last time I looked were completely adequate to explain how it works, it would make more sense to write a short blog post explaining why the implementation has changed since the last version. This issue is not about calling the math into question (which I concur is well within tolerance), but about a change in behavior, which in the Microsoft world happens less than once in a blue moon. In fact, I did a Google search before opening this and had there been such a post explaining why `Math.Sin()`'s result is slightly different in .NET Core 2.0 that would have probably been enough to sway me from opening this issue in the first place.

There are likely to be others on the receiving end of software with poorly written tests in it that will jump to the wrong conclusion like I did. After all, a test that has been passing for years suddenly failing sounds like cause for concern. And getting from "the author of the test had to have intended that" to "the author couldn't have possibly intended that" is not always obvious.

**Comment by mellinoe** [comment]
@NightOwl888 You have a good point, and we should message these changes more clearly. We have compiled a list of compatibility-affecting changes that have been made to the product [here](https://github.com/dotnet/corefx/wiki/ApiCompat), but I don't think a lot of folks are going to scour through that whole document.

@karelz @danmosemsft Were we planning on creating a blog or announcement of some sort with the information contained in that wiki page? There's a lot of good details in there, but they aren't very easily discoverable.

**Comment by mellinoe** [comment]
Here are the compatibility notes for System.Numerics:

https://github.com/dotnet/corefx/wiki/ApiCompat#systemnumerics

**Comment by tannergooding** [comment]
@mellinoe, it's probably worth both:
* Documenting that there was known "breaks" in `Sin`, `Cos`, and `Tan` that occurred in netcoreapp1.1
* Documenting that these functions are dependent on the underlying C Runtime and can potentially differ between Operating System (Mac, Linux, Windows, etc) and between architectures (ARM, x86, x64, etc)
* Documenting that, because of the C Runtime dependency, these functions can potentially differ if the runtime is compiled with a newer version of the C Runtime

**Comment by karelz** [comment]
@mellinoe yes, it is described at the top of the wiki page ;) -- the content will be transferred into the ApiCompat tool. @pjanotti is actually actively working on it now.
