### ISSUE TITLE
Using latest System.Memory package with netcoreapp2.0 fails due to S.N.V depenedency

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#23656]
If we bump up the version of the packages we reference in corefxlab to: 4.5.0-preview2-25628-01
https://github.com/dotnet/corefxlab/blob/master/tools/dependencies.props#L6-L8

..\.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Numerics.Vectors.dll
has version ver 4:1:3:0

But the latest System.Memory depends on 4.1.4
.assembly extern System.Numerics.Vectors
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 4:1:4:0
}

Our tests (which target netcoreapp2.0) fail with the following error:
Failed   System.Buffers.Tests.EqualityTests.SpansReferencingSameMemoryAreEqualInEveryAspect(bytes: [0, 0], start: 0, length: 2)
Error Message:
 System.IO.FileNotFoundException : Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Stack Trace:
   at System.SpanHelpers.SequenceEqual(Byte& first, Byte& second, Int32 length)
   at System.Buffers.Tests.EqualityTests.SpansReferencingSameMemoryAreEqualInEveryAspect(Span`1 span, Span`1 pointingToSameMemory) in D:\GitHub\Fork\corefxlab\tests\System.Buffers.Primitives.Tests\EqualityTests.cs:line 163
   at System.Buffers.Tests.EqualityTests.SpansReferencingSameMemoryAreEqualInEveryAspect(Byte[] bytes, Int32 start, Int32 length) in D:\GitHub\Fork\corefxlab\tests\System.Buffers.Primitives.Tests\EqualityTests.cs:line 45

cc @weshaggard, @ericstj, @KrzysztofCwalina, @shiftylogic, @mellinoe

**Comment by ericstj** [comment]
Which System.Memory are you using?

**Comment by ahsonkhan** [comment]
> Which System.Memory are you using? Please be specific: both package version and path.

System.Memory 4.5.0-preview2-25628-01 from myget (https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Memory)
What do you mean by path?

**Comment by ericstj** [comment]
Looked at this in the latest package and I understand the issue.  Its the consequence of moving things inbox in netcoreapp2.0, representing that as a placeholder (so as not to trigger conflict resolution) then versioning the assembly post 2.0.   This means that new netstandard2.0 assemblies that use the inbox assembly will get a reference to the newer version, but won't get that newer version in a netcoreapp2 project.

/cc @weshaggard 

I see two options for fixing this:
1. Remove the placeholders and let conflict resolution use the newer assembly.  This could have side-effects since the version that's inbox is actually built specially for netcoreapp (depends on System.Runtime) and is crossgen'ed. 
2. Keep the placeholders, but freeze the assembly version so that folks building new libraries in corefx don't get new dependencies.

This is essentially the same problem we [had before with desktop](https://github.com/dotnet/corefx/issues/5842) and the inbox references there.  Once an assembly is "inbox" in some framework you can no longer touch its surface area (either assembly version or actual types) in any assembly which will be considered compatible with that framework.

Doing 2 actually has some bad implications for these standalone packages.  It means that their API is effectively frozen on all netstandard versions since they cannot add things that weren't already inbox in NETCoreApp2.0.

@ahsonkhan you can workaround this on

**Comment by ericstj** [comment]
Here's the set of packages impacted by this problem:
```
Microsoft.CSharp
Microsoft.VisualBasic
System.Buffers
System.Collections.Immutable
System.ComponentModel.Annotations
System.Diagnostics.DiagnosticSource
System.Numerics.Vectors
System.Reflection.DispatchProxy
System.Reflection.Metadata
System.Reflection.TypeExtensions
System.Threading.Tasks.Dataflow
System.Threading.Tasks.Extensions
System.ValueTuple
```

For some we're already hardcoding the assembly version.  As a temporary fix, I'm going to dial back the assembly version for those that just became inbox in netcoreapp2.0 until we decide the right long term fix.

**Comment by ericstj** [comment]
The more I think about this the more I think that removing the placeholders is the only thing that will work long term.

Consider cases like Immutable.Collections: we can't freeze the API just because it shipped inbox in NETCoreApp2.0.  Forcing API additions to go in a TFM that's not compatible with netcoreapp2.0 is a non-starter.

Freezing assembly versions will only work where things build an unfrozen desktop assembly: otherwise we'll be creating load issues for these assemblies on desktop (GAC wins).

**Comment by karelz** [comment]
Is it something we should address in 2.0.x servicing?

**Comment by ericstj** [comment]
Not a servicing issue, per-se but something we need to be cognizant of should we service one of these packages.  We need to decide what to do for 2.1.

**Comment by ahsonkhan** [comment]
> you can workaround this by directly referencing the netstandard2.0 lib out of the System.Numerics.Vectors package

I am not sure how to do that exactly. Can you provide additional pointers?

> or by targeting netcoreapp2.1 instead.

We can do that: https://github.com/dotnet/corefxlab/pull/1736
However, shouldn't we be able to create a netcore 2.0 app, reference system.memory and have the APIs like SequenceEqual (that rely on vectors) still work?

**Comment by ericstj** [comment]
Here's a hack to directly reference the netstandard2 version of vectors from package, its only a *workaround* until this issue is fixed.
```xml
  <Target Name="ReferenceNS2VectorsLibs" BeforeTargets="ResolveLockFileReferences">
    <PropertyGroup>
      <_numericsVectorsPackagePath Condition="'%(PackageDefinitions.Name)' == 'System.Numerics.Vectors'">%(PackageDefinitions.ResolvedPath)</_numericsVectorsPackagePath>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="$(_numericsVectorsPackagePath)\lib\netstandard2.0\System.Numerics.Vectors.dll" />
    </ItemGroup>
  </Target>
```

> shouldn't we be able to create a netcore 2.0 app, reference system.memory, use APIs like SequenceEqual (that rely on vectors) and still have the app work?

Yeah, we'll fix the bug, that's why this issue remains open and I am discussing *solutions*.  I was just giving you *workarounds*.

**Comment by ericstj** [comment]
The plot thickens.  For some of these bringing back *live* builds that are compatible with past versions of netcoreapp2.0 may become a burden.  I think I'd like to classify the packages in two buckets.

1. API that's already anchored to a netstandard version because its part of desktop.  For these packages I'll opt to continue using placeholders and freeze the reference assembly version.

2. API that completely OOB. For these packages I'll opt to remove the placeholders and maintain live builds compatible with all frameworks.

@weshaggard what do you think?

**Comment by weshaggard** [comment]
For (1) it is more then freezing the reference assembly version correct? You also need to not allow any more APIs to be added. 

For (2) while I don't really like that solution I don't have a better one so I think we might be stuck.

**Comment by ericstj** [comment]
(1) Yes, no more APIs to the netstandard ref.  Freezing effectively does this.  If we wanted to be strict we could disable the build and restore the past ref from the package for the ref folder (and harvest it).  That hasn't been the pattern we've followed so far (Microsoft.CSharp) so I didn't do that, but I could implement it: similar to the old `ContractStatus=shipped` we had in TFS.

Can you let me know what you don't like about removing placeholders?

**Comment by weshaggard** [comment]
>Yes, no more APIs to the netstandard ref. Freezing effectively does this. If we wanted to be strict we could disable the build and restore the past ref from the package for the ref folder (and harvest it).

I think that is a good idea to help ensure we don't end up adding APIs accidently.

>Can you let me know what you don't like about removing placeholders?

Removing the placeholders themselves aren't my issue it is the fact we are going to be shipping more implementations in more places and we have to maintain them all. We are also essentially depending even more heavily on the conflict resolution which I worry about. We don't want conflict resolution to become the new binding policy.

**Comment by ericstj** [comment]
We also don't want putting things inbox in .NETCore and UWP to be the same thing as killing those types for future innovation.  I opened https://github.com/dotnet/corefx/issues/23743 with my initial thoughts.  Let's take this discussion over there and define what future work we want to do.
