### ISSUE TITLE
SymmetricAlgorithm and CryptoStream.Write throws ArgumentException with DES and RC2

### ISSUE THREAD

**Issue by JuanZamudioGBM** [dotnet/corefx#23688]
Hi, I'm trying to port an class library to .net core 2.0, I have a class that uses SymmetricAlgorithm that Ciphers and deciphers some strings and files, in my unit tests when the Algorithm is DES or RC2 and try to decipher (cipher works OK ) the method CryptoStream.Write throws an argument exception with the message : "Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection." (TriplesDes and Rijndael works fine), the problem is in the following line

 ```c#
using (CryptoStream cryptoStream = new CryptoStream(destinyStream, symmetric.CreateDecryptor(), CryptoStreamMode.Write))
{
    long total = sourceStream.Length;  //// total number of bytes to read
    byte[] temporal = new byte[4096];  //// temporal storage
    long read = 0; //// number of bytes read in the cycle
    int actualRead;   //// number of bytes actually read
    while (read < total)
    {
        actualRead = sourceStream.Read(temporal, 0, CipherBuffer);
        cryptoStream.Write(temporal, 0, actualRead); // <- here is the error
        read += actualRead;
    }
    cryptoStream.FlushFinalBlock();
}
```

I created a new project (File -> new Project -> Console Project) and I'm attaching the project where I can reproduce the issue, in this project I'm using a salt and IV with just zeroes (I don't know if that's the problem)

Thanks a lot for your time

Edit:
I added a Console app to the solution with the full framework with the same code and the program runs fine.

[ClassLibraryVer2.zip](https://github.com/dotnet/corefx/files/1264804/ClassLibraryVer2.zip)

[EDIT] Fix code formatting, add C# syntax by @karelz

**Comment by karelz** [comment]
@bartonjs potentially a compat issue?

**Comment by bartonjs** [comment]
@JuanZamudioGBM are your RC2 and DES instances RC2CryptoServiceProvider and DESCryptoServiceProvider, or are they from RC2.Create() and DES.Create()?  I think this is a duplicate of #23311 (which is now fixed in master)

**Comment by JuanZamudioGBM** [comment]
@bartonjs  I'm using SymmetricAlgorithm symmetricDES = (SymmetricAlgorithm)CryptoConfig.CreateFromName("DES");

**Comment by bartonjs** [comment]
@JuanZamudioGBM Yeah, that's DESCryptoServiceProvider.  The recommended way to get a DES instance (or an instance of any algorithm) is to use `\[Algorithm\].Create()`.  On .NET Framework that does the same thing you've done, on .NET Core it returns a non-castable type (well, not castable beyond the algorithm base class) which performs the algorithm using whatever "the best" library is for the current OS.

Since this reduces down to an already fixed-in-master-and-tracking-for-servicing problem I'm going to close it.  But thanks for reporting it, please let us know if you run into anything else.
