### ISSUE TITLE
Inconsistent certificate handling between Linux and Windows

### ISSUE THREAD

**Issue by mrgleba** [dotnet/corefx#23681]
The following code yields different results on Linux and Windows (STARTTLS in SMTP)

On Windows the cert is handled correctly and the cert subj is printed to stdout.
On Linux (Fedora 26, Debian 9) cert is null in the CertificateValidationCallback (null if printed to stdout)

```c#
using System;
using Newtonsoft.Json;
using System.Net.Sockets;
using System.Net.Security;
using System.Security;
using System.IO;
using System.Security.Cryptography.X509Certificates;
using System.Security.Authentication;
using System.Text;
namespace code3
{
    class Program
    {
        static void Main(string[] args)
        {
            var host = "mail.galapp.net";
            using (var c = new TcpClient(host, 587))
            using (var s = c.GetStream())
            using (var sw = new StreamWriter(s, Encoding.ASCII))
            using (var sr = new StreamReader(s, Encoding.ASCII))
            {
                var l = read();
                sw.Write("EHLO localhost\r\n");
                sw.Flush();
                var l1 = read();
                sw.Write("STARTTLS\r\n");
                sw.Flush();
                var l2 = read();
                
                using (var ss = new SslStream(s, false, (snd, cert, chain, err) => {
                    Console.WriteLine(cert == null ? "null": cert.Subject);
                    return true;
                })) {
                    ss.AuthenticateAsClient(host, new X509CertificateCollection(), SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12, false);                    
                }

                // handle SMTP response
                string read()
                {
                    byte[] buffer = new byte[1024];
                    int position = 0;
                    bool lastLine = false;

                    do
                    {
                        int readLength = s.Read(buffer, position, buffer.Length - position);
                        if (readLength > 0)
                        {
                            int available = position + readLength - 1;
                            if (available > 4 && (buffer[available] == '\n' || buffer[available] == '\r'))
                                for (int index = available - 3; ; index--)
                                {
                                    if (index < 0 || buffer[index] == '\n' || buffer[index] == '\r')
                                    {
                                        lastLine = buffer[index + 4] == ' ';
                                        break;
                                    }
                                }

                            position += readLength;

                            if (position == buffer.Length)
                            {
                                byte[] newBuffer = new byte[buffer.Length * 2];
                                Array.Copy(buffer, 0, newBuffer, 0, buffer.Length);
                                buffer = newBuffer;
                            }
                        }
                        else
                        {
                            break;
                        }
                    } while (!lastLine);

                    return Encoding.ASCII.GetString(buffer, 0, position - 1);
                }                    
            }
        }
    }
}
```

[EDIT] Add C# syntax highlighting by @karelz

**Comment by mrgleba** [comment]
Some more info:
 - both win and linux running core 2.0

Curiously enough when I try to establish a SSL stream with the same host port 465 (SMTPS) (no STARTTLS this time - we go to SSL right at the start) everything is ok on both win and linux.
The cert is the same in both cases (587 STARTTLS & 465 TLS).

**Comment by davidsh** [comment]
I repro'd the problem.  Yes, it does get the certificate on Windows.  But I repro'd the "null" certificate on Fedora 26 using .NET Core 2.1 RC1.

I set up a Fedora 26 docker container using the follow "script":

```ps
docker run -it --name smtpssltest -v s:\dotnet:/home/usr/corefx fedora:26 bash
rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
dnf update
dnf install libunwind libicu compat-openssl10
dnf install dotnet-sdk-2.1.300-rc1-008673
```

Then used "dotnet run" on the sample code above.

**Comment by davidsh** [comment]
cc: @wfurt @karelz 

We should look into this since it looks like an SslStream bug of some sort.

**Comment by wfurt** [comment]
This is because server is *not* sending certificate. 
You can look at attached snapshot of Wireshark trace:

Cipher Suite: TLS_ECDH_anon_WITH_AES_256_CBC_SHA (0xc019)

<img width="1577" alt="ssl" src="https://user-images.githubusercontent.com/14356188/40446875-87457ef0-5e85-11e8-927f-4975770afd8e.png">

With that, there is no certificate exchange.  
I tested same code against different server and callback works as expected. 
The reason why it works on Windows and OSX is that SSL Client hello does not offer anonymous cipher suites. 

I verified that everything works as expected if I add "!aNULL" to cipher selection in PAL layer. 
However there is no public API at the moment to do that from managed code.

CC: @bartonjs if he wants share some thoughts on using anonymous suites.

**Comment by davidsh** [comment]
>I tested same code against different server and callback works as expected.
The reason why it works on Windows and OSX is that SSL Client hello does not offer anonymous cipher suites.
I verified that everything works as expected if I add "!aNULL" to cipher selection in PAL layer.
However there is no public API at the moment to do that from managed code.

.NET Framework/.NET Core do support APIs to control whether the "NULL" cipher suite is allowed (normally by default is not allowed).

See:
https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.-ctor?view=netcore-2.0#System_Net_Security_SslStream__ctor_System_IO_Stream_System_Boolean_System_Net_Security_RemoteCertificateValidationCallback_System_Net_Security_LocalCertificateSelectionCallback_System_Net_Security_EncryptionPolicy_
https://docs.microsoft.com/en-us/dotnet/api/system.net.security.encryptionpolicy?view=netcore-2.0

**Comment by wfurt** [comment]
That flips "eNULL" at OpenSSL layer.  In the example above, the encryption is AES_256_CBC_SHA but peers are not authenticated . Adding "aNULL" disables that behavior.

**Comment by bartonjs** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/mt813794(v=vs.85).aspx doesn't describe any of the `_anon_` ciphersuites, so having them disabled for both client and server sessions with OpenSSL seems like the best thing for understanding a compatibility matrix.

Absent disabling those ciphersuites, it seems like we would need to treat the SslPolicyErrors enum as `RemoteCertificateNotAvailable` to a client, and it should probably or-in the `RemoteCertificateNameMismatch` value (unless the match was against string.Empty?), because of the risk of callbacks indicating accidental success because they only looked for NameMismatch and ChainErrors (expecting NotAvailable only for client auth certs or the NoEncryption ciphersuite).  Though I don't know if there's any way to get a good "before data goes over the wire" callback from OpenSSL in the `_anon_` case.  (If it's not already firing, that is).
