### ISSUE TITLE
Add GetGenericMethodDefinition and MakeGenericMethod to MethodBase

### ISSUE THREAD

**Issue by kingces95** [dotnet/corefx#23763]
# Proposed Additions

````
class MethodBase
{
    public virtual MethodBase MakeGenericMethod(params Type[] typeArguments) 
        => (this as MethodInfo)?.MakeGenericMethod(typeArguments) ?? 
            throw new InvalidOperationException();

    public virtual MethodBase GetGenericMethodDefinition() 
        => (this as MethodInfo)?.GetGenericMethodDefinition() ?? 
            throw new InvalidOperationException();
}
````
# Proposed Modifications
These virtuals need to be made `new virtual`:
````
class MethodInfo
{
    public new virtual MethodInfo MakeGenericMethod(params Type[] typeArguments) { ... }
    public new virtual MethodInfo GetGenericMethodDefinition() { ... }
}
````

# Rationale

## Complete The Move
Originally, generic APIs for methods were all added to `MethodInfo` as opposed to `MethodBase`. Subsequently, many, but not all of, the generic APIs on `MethodInfo` have been moved to `MethodBase`. We should complete the move for the same reason the move was initiated, whatever that was. 

## Symmetry with `Type`
If we wish to maintain the same symmetry in generic functionality that exists between `Type` and `MethodInfo` for `Type` and `MethodBase` then we need to add `MakeGenericMethod` and `GetGenericMethodDefinition` to `MethodBase`:

| TypeInfo | MethodInfo | MethodBase |
| ---- | ---- | ---- |
| IsGenericType | IsGenericMethod | IsGenericMethod |
| IsGenericTypeDefinition| IsGenericMethodDefinition | IsGenericMethodDefinition |
| GetGenericArguments | GetGenericArguments | GetGenericArguments |
| GetGenericTypeDefinition | GetGenericMethodDefinition | GetGenericMethodDefinition [new] |
| MakeGenericType | MakeGenericMethod | MakeGenericMethod [new] |
| IsConstructedGenericType | IsConstructedGenericMethod | IsConstructedGenericMethod |
| ContainsGenericParameters | ContainsGenericParameters | ContainsGenericParameters |
| GenericTypeArguments | GenericMethodArguments† | GenericMethodArguments† |
| GenericTypeParameters‡ | GenericMethodParameters† | GenericMethodParameters† |

†See #23741 
‡See #23762 

## Ease Of Use
Algorithms are forced to cast to `MethodInfo` because some functionality, like `GetGenericTypeDefinition()`, is only available there. That might have been palatable when there was some reason, some invariant, like _functionality that doesn't exist on constructors lives on `MethodInfo`_ justified that design. But that invariant no longer exists (and good riddance IMHO!) so the cast just feels unnecessary. Moving the functionality down to `MethodBase` removes the need for the cast:
````
if (methodBase.IsGenericMethodDefinition) {
    var methodDefinition = ((MethodInfo)methodBase).GetGenericMethodDefinition();
    // ... do something with methodDefinition
} 
````
could instead be
````
if (methodBase.IsGenericMethodDefinition) {
    var methodDefinition = methodBase.GetGenericMethodDefinition();
    // ... do something with methodDefinition
} 
````

# New Virtuals on `MethodInfo`
The existing methods on `MethodInfo` cannot directly override the new additions to `MethodBase` as the former return `MethodInfo` and the latter (should) return `MethodBase`. As such, the existing virtual methods need a new vtable slot. Hence the `new virtual`.

While there may be objection to exposing `new virtual` methods, in practice, derivation of the reflection API is rare, and those that do derive tend to derive from `ConstructorInfo` and `MethodInfo` and not from `MethodBase` (e.g. `Reflection.Emit`). 

For those unicorns that did derive from `MethodBase`, they can still make due. But there is no need to go into those weeds. Unless, that is, someone can think of a customer doing this and suggest why they might not like the `new virtuals`.

**Comment by AtsushiKan** [comment]
I don't think this one will fly.

Let me address this rationale first since it seems to motivating many of these api requests:

>If we wish to maintain the same symmetry in generic functionality that exists between Type and MethodInfo for Type and MethodBase 

That's not a goal for us. This ignores the different roles that `Type` and `MethodBase` play. 

`MethodBase` is a union for two other types (`MethodInfo` and `ConstructorInfo`) `MethodBase` captures the apis that make sense for both, while apis that are specific to constructors and methods go on the appropriate subtype. This ensures compile-time detection of errors involving calling the api on the type which is preferable to getting an exception at runtime.

Now, for whatever reason, .Net did not make the same choice regarding `Type`. Had it done so, i.e. making `Type` a common base class for `DefinitionType`, `ArrayType`, `ByRefType`, `ConstructedGenericType` etc., then it too would have distributed the apis accordingly. In particular, `GenericTypeDefinition` would have been on `ConstructedGenericType`, and `MakeGenericType` on `DefinitionType`. 

But as history played out, `Type` is the only class and thus, all the flavor-specific apis are sprawled on it, each burdened with fine-print of "this predicate must be true before it's valid to call this." But just because `Type` is stuck with that design doesn't mean we should follow suit for `MethodBase`. There, it makes sense to put the apis on the class where it's 100% legal.

>Originally, generic APIs for methods were all added to MethodInfo as opposed to MethodBase. 

As far as I know, that was never the case. At any rate, there is a consistent rule being applied here: the "generic" apis that are on `MethodBase` are there because they don't require overloading to make them usable on `MethodInfo`. The two that aren't do require overloading because of the return type, and thus, would result in twice the documentation, and confront developers with a choice that wouldn't be that useful.

>Ease Of Use

How often does real code want to call these apis on a `MethodBase`? Most of the time, the code building generic methods is written with a specific method in mind and would thus want a `MethodInfo` back.

Given that generic constructors aren't actually a planned feature any time on the horizon, I do not think it makes sense to overload these methods on the base class. It's extra metadata, documentation and extra cognitive work on the developer ("which one am I supposed to use") for something that doesn't add any new functionality. It just doesn't meet the -100 points test.
