### ISSUE TITLE
Building on Server Core

### ISSUE THREAD

**Issue by bazzilic** [dotnet/corefx#23774]
According to this (https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md), building requires VS 2015 or 2017 installed. And the build script actually stops if they are not found.

Then, according to this (https://www.visualstudio.com/en-us/productinfo/vs2017-system-requirements-vs), VS 2017 can't be installed on Windows Server Core (or can it?).

Does this mean, we can't build dotnet on a Server Core? Specifically, I want to build from source in a docker container to have clean, reproducible environments.

**Comment by danmosemsft** [comment]
@weshaggard @joperezr  you guys are working to enable this I think?

**Comment by weshaggard** [comment]
Yes this is something we are working towards but as it stands we don't have all the pieces ready and so building our repo's directly on Windows Server Core doesn't work yet. 

There are currently 2 big dependencies on VS.

1) We currently depend on the msbuild from VS
2) We depend on the VC++ headers and libs

We are actively working on (1) but it is still a ways out. For (2) we don't yet have a solution I've started conversations with the VC++ team but we don't have a working solution yet.

**Comment by bazzilic** [comment]
@weshaggard I see. Is there any place where I can track updates on this? I'd like to try it out as soon as this is available.

**Comment by joperezr** [comment]
@bazzilic for now we only have some part of these changes in a private fork: https://github.com/joperezr/corefx/tree/WIP 

That said, in order for that fork to build correctly you would also need buildtools changes that are not checked in yet which is why there is no real easy way to try this out for now. The plan is that in the next few days/weeks we will eventually get these changes on the main fork (probably not in master branch, but in a feature branch instead). I will update this issue when that happens so that you can sync and try it out.

**Comment by bazzilic** [comment]
@joperezr thank you, looking forward to it.

**Comment by ViktorHofer** [comment]
@joperezr @weshaggard is there an update on this? Which pieces in corefx still require the desktop msbuild? What about the VC++ libs?

**Comment by joperezr** [comment]
# 1 from above is done since we already use the CLI's msbuild in order to build corefx. Also, we made a lot of progress into removing dependencies to VS by transforming all of our projects into SDK-style projects. However, we still have # 2 pending, since we still have that external dependency of needing the VC++ headers and libs. In theory, you should be able to build all of our managed build without VS installation though since the VC++ libs and headers are only required for the native build.

**Comment by ViktorHofer** [comment]
Correct me if I'm wrong but aren't we still using the Developer Command Prompt (probably to use the desktop msbuild) during .\build for some parts? i.e. native parts

**Comment by joperezr** [comment]
We are using developer command prompt, but we don't call msbuild anymore. If you build using `build.cmd` script, then what we are going to use to build all the projects will be `.\Tools\dotnetcli\dotnet.exe msbuild ...` which basically uses the CLI's msbuild instead of the one in the PATH that comes with VS. We use Developer command prompt because of the build of native parts, which as I said earlier, can't really build without VS for now.

**Comment by ViktorHofer** [comment]
I strongly believe we should find a solution for `We depend on the VC++ headers and libs` as soon as possible. It would sweet if we could get rid of the Developer Command Prompt necessity for the native part till 3.0.

**Comment by ViktorHofer** [comment]
Duplicates https://github.com/dotnet/arcade/issues/64
