### ISSUE TITLE
Tests for OOB packages in NETFX need to run against OOB binaries.

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#23889]
@davidsh words: "This test is failing now because it is running against the "Full Framework". But for System.Net.Http tests, even running against "Full Framework" means that it should use the OOB System.Net.Http and not the inbox System.Net.Http from the .NET Framework.

Something has changed in how the test binaries are laid out and consumed. The tests appear to be using the inbox System.Net.Http binary and not the OOB System.Net.Http binary (net46 build from package). I think this all broke when individual packages for contracts (such as System.Net.Http) went away and were replaced with mega-packages."

Please see: https://github.com/dotnet/corefx/issues/23702#issuecomment-326674472

cc: @weshaggard @ericstj @karelz

**Comment by safern** [comment]
We need to investigate that all the OOB shipped packages for NETFX are running against those binaries (i.e Compression, System.Net.Http, etc)

**Comment by ericstj** [comment]
Note that they should be running against the support package, which is binplaced to the runtime path.

Note that this is different than the live-build since the we are no longer shipping new implementation assemblies for all these desktop binaries.  See https://github.com/dotnet/corefx/pull/23611

If the tests aren't actually using the assemblies in the netfx runtime path that's a problem, if they are then the test failure might be indicative of the need to ship a fix that was made in master through release/2.0.0 in servicing.

**Comment by ViktorHofer** [comment]
Hitting the same with System.ComponentModel.Composition now. cc @maryamariyan

**Comment by safern** [comment]
> Hitting the same with System.ComponentModel.Composition now

Yes, I'm currently working on this. See: https://github.com/dotnet/corefx/issues/24903

**Comment by safern** [comment]
Please just remove the netfx configurations for the System.ComponentModel.Composition tests and with the fix I will revisit the projects that are hitting that and enable them to run on netfx.

**Comment by ViktorHofer** [comment]
Yes I'm currently working on that. Should be done in a few minutes.

**Comment by weshaggard** [comment]
Estimate of 5 includes remaining work to fix build/test to work against actual NETFX, and add missing NETFX configurations
