### ISSUE TITLE
When Process.Start is used to open a program, ProcessName value is incorrectly set as "dotnet" on OSX 

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#23972]
When using Process.Start in order to open a program:

- On OSX, the ProcessName value is dotnet for some reason, which I believe is wrong behavior.
- But on Linux, the ProcessName value is correctly set as the input program to Process.Start.

Code Sample:

```
// string programToOpenWith = "/usr/bin/open" or "/usr/bin/nano" for OSX or
// string programToOpenWith = "nano" or "vi" for Linux

using (var px = Process.Start(programToOpenWith, fileToOpen))
            {
                Console.WriteLine($"in OSX, {nameof(programToOpenWith)} is {programToOpenWith}, while {nameof(px.ProcessName)} is {px.ProcessName}.");
                // Assert.Equal(programToOpenWith, px.ProcessName); // on OSX, process name is dotnet for some reason
            }
```

**Comment by romangrewal** [comment]
Hello, I can try to work on this issue.

**Comment by danmosemsft** [comment]
@romangrewal do you need any pointers? Instructions for starting to contribute, building, debugging etc are here: https://github.com/dotnet/corefx/tree/master/Documentation

**Comment by danmosemsft** [comment]
Your help is welcome.

**Comment by rogaps** [comment]
Hi, may I take this issue?

**Comment by maryamariyan** [comment]
@rogaps you can go ahead. the issue is up for grabs.

**Comment by rogaps** [comment]
This a1f16ad25941ba6a8df3a0c83d245661572b4d0f workaround doesn't seem working on OSX because OSX doesn't have pipe2.

**Comment by tmds** [comment]
@maryamariyan this should be osx label instead of linux.

**Comment by jmezach** [comment]
I'll try to have a look at this. I'm on OSX, so that helps :).

**Comment by jmezach** [comment]
I had a look at this and I think that to make this work correctly we might need to call into **proc_pidpath** in *libproc*. There's already a function in Interop.libproc to do this. However, after changing the source of the ProcessName on the ProcessInfo instance to use the output of proc_pidpath (instead of proc_taskallinfo) I'm getting 8 failing tests. while the test that I added to verify the behaviour is now passing.

**Comment by jmezach** [comment]
Actually, I think there is a timing or threading issue going on here. If I run all the tests it is returning dotnet for the process name, thus my test fails. If I run only my own test it is returning the correct filename (although without changes it is returning only the filename, and not the full path).

**Comment by ViktorHofer** [comment]
cc @maryamariyan

**Comment by ViktorHofer** [comment]
cc @danmosemsft

**Comment by stephentoub** [comment]
> Actually, I think there is a timing or threading issue going on here.

Yes, there is.  To launch a new process, the pattern is to fork() (which effectively duplicates the current process into a new one) and then exec(...) the new executable in that forked process.  That means for some period of time, the child process' name is the same as the parent process, and then the name changes to the target name when exec is executed.  On Linux, we use pipe2 to create a pipe with O_CLOEXEC that'll be closed when exec is invoked, and then the parent process blocks waiting on that pipe:
https://github.com/dotnet/corefx/blob/b987a3bd0dcbc5d7ec2268529252739e7441acbe/src/Native/Unix/System.Native/pal_process.cpp#L201-L215
That way, we don't allow Start to return until exec has been invoked in the child process and the name appropriately changed.  But pipe2 doesn't exist on macOS.  And we don't want to simulate it using pipe and fcntl to set O_CLOEXEC on the already created file descriptor, because there's then a window where another child process could be created, inheriting that pipe, at which point the parent process waiting for the pipe to be closed would now erroneously be waiting for that other child process to complete.

**Comment by stephentoub** [comment]
This was fixed by https://github.com/dotnet/corefx/pull/33097.
