### ISSUE TITLE
NuGet package compability issue

### ISSUE THREAD

**Issue by taoyouh** [dotnet/corefx#23994]
Some .NET packages are not supported on UWP, but they declare to support .NET Standard on NuGet.org. For example, System.Net.Security on NuGet says it supports .NET Standard, but it doesn't work on UWP.
A ,NET standard package is supposed to be compatible with all platforms that supports .NET standard. But this isn't compatible with UWP.
Even I know this package doesn't work with UWP, any .NET standard packages may include reference to these packages. They compile but don't work. It's hard for a developer to check compatibility for every packages.

So, these packages shouldn't declare it supports .NET Standard.

**Comment by davidsh** [comment]
System.Net.Security is now part of .NET Core 2.0 and thus .NETStandard2.0.  It will be included as part of the UWP6.0 release.  You can try it out now in prerelease by installing the Visual Studio 2017 15.4 Preview:

https://blogs.msdn.microsoft.com/visualstudio/2017/08/25/visual-studio-2017-version-15-4-preview/
https://www.visualstudio.com/en-us/news/releasenotes/vs2017-preview-relnotes

**Comment by taoyouh** [comment]
@davidsh This is true. However, according to .NET Standard document, developers find the lowest .NET Standard version available by lowering the version and compile:

> Target the next lower version of .NET Standard and build your project.
> If your project builds successfully, repeat step 1. Otherwise, retarget to the next higher version and that's the version you should use.

The problem is not that UWP doesn't implement System.Net.Security. The problem is that any UWP projects may reference System.Net.Security or other packages that referenced it, will crash without getting any errors or warnings. In other words, the problem is that is doesn't work without noticing.

**Comment by davidsh** [comment]
cc: @ericstj @karelz

**Comment by ericstj** [comment]
> System.Net.Security on NuGet says it supports .NET Standard

I think you're misinterpreting NuGet's representation of the package content as support designation.  If there was a way to declare support on NuGet we would declare it appropriately (or in this case, designate it is not supported).

When these packages were first released, NuGet would give you an install failure (due to ref with no lib) which these packages relied on.  We wanted them to fail at build time but still provide portable surface area: thus the netstandard ref and missing lib for UWP.  NuGet later removed this.  Meanwhile we cannot remove the netstandard refs because we've established those and folks rely on them to build portable libraries between desktop and netcore.  In the latest packages we've stopped doing this ref-no-lib pattern, instead we provide a netstandard lib that throws platformnotsupported.  As you've mentioned, this doesn't help at build time.  You need to run the app to see the exception.

There isn't much we can do for those old packages and we had to decide where to focus efforts: add support for the libraries, or build a different guardrails system to expose the error at build time.  We chose to focus on adding support.  I believe @terrajobst is tracking the need for a better guardrails.

**Comment by taoyouh** [comment]
If the NuGet page describes this behavior in English it will be much better. I can hardly know this behavior from any documents.

**Comment by ericstj** [comment]
That's a good suggestion.  We actually calculate all of the supported platforms when we build the packages and emit that as a data file in our build.  We could easily transform that into some text that gets added to the NuSpec and shows up in the package description.

**Comment by jnm2** [comment]
:+1: for better guardrails.

**Comment by ericstj** [comment]
I believe @terrajobst and @pjanotti are working on a project over at https://github.com/dotnet/platform-compat that aims at doing that.

**Comment by jnm2** [comment]
I think that's only going to be helpful if it comes as part of the csproj SDK. Having to discover failures on your own, take the initiative to research ways to manage to broken abstraction going forward, discover the platform-compat package, and add it defensively to every csproj– seems a bit much to me.

**Comment by pjanotti** [comment]
We are aware of this limitation of having it as an analyzer but to get to the point of having it automatically added to any csproj we will need more tuning of it (we know it is not going to be perfect, but it needs to be right most of the time). As of today the analyzer is not covering UWP yet.

**Comment by jnm2** [comment]
@pjanotti As long as it's in a temporary development phase, I'm cool with that. Though I do hope it'll come out of that phase in under a year if not months.
