### ISSUE TITLE
ObsoleteAttribute does not cause error when message is null

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/corefx#24062]
```csharp
private static void Foo()
{
    Foo1(); // warning CS0612
    Foo2(); // error CS0619
}

[Obsolete(null, error: true)]
private static void Foo1()
{
}

[Obsolete("", error: true)]
private static void Foo2()
{
}
```
Tested with .NET Core 1.1.0

Where is this behaviour documented?

**Comment by JonHanna** [comment]
Since the `new ObsoleteAttribute(null, true).IsError` returns `true` this is more a matter of how Roslyn treats the attribute, than how the attribute class works as a class.

See https://github.com/dotnet/roslyn/blob/f1864f80b82aad39f2249e3929bd0c3d7d8cffbf/src/Compilers/CSharp/Portable/Symbols/ObsoleteAttributeHelpers.cs#L160

The old compiler has the same behaviour.

It's reasonable enough, in that if you're going to deliberately break someone's build, you really should say why, but I agree that this should be documented, both in the documentation for the attribute, and the documentation for CS0619 and perhaps CS0612, and for any other language that has the same behaviour (VB has two separate errors and two separate warnings, for the four possible permutations).

**Comment by karelz** [comment]
Can you please file new documentation bug in Roslyn repo? (closing this one in the mean time)

**Comment by JosefPihrt** [comment]
Thanks for answer @JonHanna.
