### ISSUE TITLE
Failed FileStream construction truncates files on Linux

### ISSUE THREAD

**Issue by chlowell** [dotnet/corefx#24081]
On Linux, the second `FileStream` construction below truncates the file and throws an `IOException`:

```cs
using System.IO;
using System.Text;

class Program
{
    static void Main(string[] args)
    {
        var filename = "file";
        using (var fs1 = new FileStream(filename, FileMode.Create, FileAccess.Write, FileShare.None))
        {
            fs1.Write(Encoding.ASCII.GetBytes("fs1"), 0, 3);
            fs1.Flush();

            // throws IOException: file being used by another process
            using (var fs2 = new FileStream(filename, FileMode.Create, FileAccess.Write, FileShare.None))
            { }
        }
    }
}
```
I understand `FileMode.Create` specifies truncation of extant files, and that Linux file locking is advisory, but this behavior seems incorrect to me. If it can be known the file is in use, why not throw before truncating it?

The exception is also misleading in that it implies an external process has locked the file and that lock has been respected, i.e. the file has not been modified, when in fact the file has been destructively modified.

**Comment by stephentoub** [comment]
> If it can be known the file is in use, why not throw before truncating it?

The truncation happens as part of opening the file, with O_CREAT | O_TRUNC passed to the open syscall; it's not until after we open it and have the file descriptor that we can call flock to get/set the advisory lock. If you have a suggestion for how to achieve the semantics you're hoping for, please share.

**Comment by poizan42** [comment]
@stephentoub Wouldn't this work?

1. Open with O_CREAT but not O_TRUNC
2. Call flock
3. If locked then call ftruncate(fd, 0)

**Comment by stephentoub** [comment]
Possibly. I was actually asking, not challenging. :) I've not investigated what if any difference there would be in observable behavior.

**Comment by poizan42** [comment]
open on linux (and I think macOS too) allows O_TRUNC with O_RDONLY while ftruncate will fail in that case, but combining FileMode.Truncate and FileMode.Create with FileAccess.Read is illegal anyways. I cannot find anywhere that anyone has described any semantic differences.

The observable behavior at least differs in that:

1.  It is possible to observe the process having opened the file before truncating it.
2. Two inotify events will be fired instead of one.

There may also be filesystem specific differences, e.g. two operations on network filesystems instead of one.

**Comment by karelz** [comment]
@poizan42 I assume you grabbed this issue. Once you accept collaborator invite, please let me know and I will assign it to you. (assigning to myself as temporary solution)
