### ISSUE TITLE
Update CoreFx build to shipping nuget

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#2427]
Need to do the following to bring ourselves current with the shipping nuget scenarios.
- [x] switch from DNX to nuget.exe
- [x] move projects from `dnxcore50` to `netstandard1.x`
- [ ] use PCL meta-package in all test projects 
- [x] eliminate `test-runtime\project.json` hack
- [ ] ensure we use inbox nuget task/targets when present and only use BuildTools version when inbox is missing
- [x] switch to stable version consumption of packages

**Comment by mellinoe** [comment]
Just looking for some clarification, as someone who isn't as familiar with how everything is expected to work.

> switch from DNX to nuget.exe

So presumably we will still be downloading NuGet.exe as we are today, but instead of using it to restore dnx/dnu, we will just use it to restore the rest of the packages?

> move projects from dnxcore50 to dotnet with appropriate supports gaurdrails

What "guardrails" do we need and/or what are they for?

**Comment by davidfowl** [comment]
>  move projects from dnxcore50 to dotnet with appropriate supports gaurdrails

I don't think so, this needs to be updated to use a specific platform standard.

>  use PCL meta-package in all test projects

Maybe? That'll all of the packages all the time. Which is insanity.

**Comment by ericstj** [comment]
Opened https://github.com/dotnet/buildtools/issues/917 to track the ResolveNuGetPackageAssets task.
PCL meta-package for tests is a non-goal.
