### ISSUE TITLE
sync does not restore all packages during the UAP build

### ISSUE THREAD

**Issue by karajas** [dotnet/corefx#24403]
/cc @joperezr 

- The sync step during the UAP legs of the official build do not include all the dependencies upfront. The System.Globalization.Calenders project supports only uap, so during the build of uapaot it causes a restore of uap on runtime.depproj which requires different resources than uapaot.

- The optional tooling is brought down only during build.

**Comment by joperezr** [comment]
mm not sure what you meant about the optional tooling only coming down during build, as that actually happens during sync step.

The basic problem here is that if you run `sync.cmd -- /p:TargetGroup=uapaot` it will only restore the uapaot dependencies of runtime.depproj(which are different than the uap dependencies of that project). When doing a vertical build of uapaot, some projects that have a P2P reference to the runtime.depproj only have a uap configuration, which causes that runtime.depproj is built again but now using the uap configuration which will restore additional packages. The basic problem here, is that on the airplane scenario, you would want to only have to run sync.cmd once for your vertical, and then go offline and be able to build, which won't work in this case since the call to `build.cmd -framework:uapaot` would have to restore additional dependencies.

cc: @weshaggard

**Comment by joperezr** [comment]
My suggestion here would probably be that runtime.depproj should probably be built for all applicable configurations when running `sync.cmd -- /p:TargetGroup=<target group>`  cc: @ericstj

**Comment by wtgodbe** [comment]
Closing this as it refers to the old workflow
