### ISSUE TITLE
[Uri] System.Uri handles '%' characters in local path incorrectly

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#24439]
@agr reported this issue here: https://github.com/dotnet/core/issues/1004

.NET Core 2.0, Windows 10:

```
using System;

namespace uri_from_path_test
{
    class Program
    {
        static void Main(string[] args)
        {
            var uri = new Uri(@"e:\%41foo%20bar%25.baz");
            Console.WriteLine("{0} {1}", uri.AbsoluteUri, uri.LocalPath);
        }
    }
}
```

produces the following output:
```
file:///e:/Afoo%20bar%2525.baz e:\Afoo bar%25.baz
```

while the expected output would be:
```
file:///e:/%2541foo%2520bar%2525.baz e:\%41foo%20bar%25.baz
```

**Comment by davidsh** [comment]
cc: @rmkerr

**Comment by poizan42** [comment]
Also see my comments here: https://stackoverflow.com/questions/1546419/convert-file-path-to-a-file-uri/35734486#35734486

**Comment by rmkerr** [comment]
Something is definitely going wrong here. I've tested the same code on .NET Framework and the issue shows up there too.

As for the repro code keep in mind that the provided URI is particularly ambiguous in that the %41, %20, and %25 can be interpreted as literals or as percent encoded octets.  To ensure that we don't change the meaning of a URI, we should only automatically percent encode characters that we're _really_ sure are not already encoded. So if a file name contained the literal "%25", the user would have to to encode that percent sign before passing it in as "%2525". That seems to be the behavior that is implied by the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.uri?view=netcore-2.0#Remarks).

Once we figure out what the correct behavior is we can start thinking about a fix. Because of all the compatibility concerns this might not be something we change in Framework, but if it is I can certainly port the fix here too.

**Comment by danmosemsft** [comment]
One of these?
https://github.com/dotnet/corefx/issues/23574 
https://github.com/dotnet/corefx/issues/23582

**Comment by davidsh** [comment]
>One of these?
#23574
#23582

Those bugs are about a different component, System.Web.HttpUtility.  It is different from System.Uri.

**Comment by poizan42** [comment]
@rmkerr I think the underlying issue is that the Uri constructor is simply trying to do too much. The problem people have is that they have a raw file path and they want a file uri representing that file path. But the Uri constructor does not distinguish between whether the input is escaped or not.

My suggestion would be to add a static public factory method "FromFilePath" that would simply expect the given path to be an unescaped file path (my FilePathToFileUrl function in my earlier mentioned stackoverflow answer could be a basis for the implementation). This would avoid any ambiguity and preserve backwards compatibility at the same time.

**Comment by agr** [comment]
Two thoughts:
* at the very least, I think, `uri.LocalPath` should return the same as was provided to the constructor;
* somehow, it works as I would expect it to work in Powershell:
```
> New-Object System.Uri 'e:\%41foo%20bar%25.baz'


AbsolutePath   : e:/%2541foo%2520bar%2525.baz
AbsoluteUri    : file:///e:/%2541foo%2520bar%2525.baz
LocalPath      : e:\%41foo%20bar%25.baz
Authority      :
HostNameType   : Basic
IsDefaultPort  : True
IsFile         : True
IsLoopback     : True
PathAndQuery   : e:/%2541foo%2520bar%2525.baz
Segments       : {/, e:/, %2541foo%2520bar%2525.baz}
IsUnc          : False
Host           :
Port           : -1
Query          :
Fragment       :
Scheme         : file
OriginalString : e:\%41foo%20bar%25.baz
DnsSafeHost    :
IdnHost        :
IsAbsoluteUri  : True
UserEscaped    : False
UserInfo       :

> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.15063.608
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.608
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by rmkerr** [comment]
I agree that the URI constructor is trying to do too much. The problem seems to be specific to implicit file URIs though -- it doesn't occur when the file:/// scheme is specified. For the time being I think that we should recommend that file names be escaped in advance, and that potentially dangerous file URIs be created with the file:/// prefix. 

Thanks for pointing out the behavior difference @agr. That's interesting, and could definitely be helpful in tracking down where things are going wrong.

**Comment by davidsh** [comment]
@agr 

There have been several changes to System.Uri for localpath properties for .NET Core 3.0.

Please try out the latest preview:
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-9/

If this is still a problem, please open a new issue.
