### ISSUE TITLE
DisplayFormatAttribute not used while rendering control

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#24440]
@johanskoldekrans opened this issue here: https://github.com/dotnet/core/issues/1000

We have two datecontrols (startdate and enddate) that we used the attribute DisplayFormatAttriute with a DataFormatString("{0:d}") as well as ApplyFormatInEditMode = true. This was rendered as an input with type date in the past but now is rendered as a datetime-local input. So the user has to enter the time as well.

Code from View:
```
<div class="form-group m-l-3">
                                <span>Från</span>
                                <input asp-for="StartDate" asp-format="{0:d}" />
                            </div>
                            <div class="form-group">
                                <span>Till</span>
                                <input asp-for="EndDate" asp-format="{0:d}" />
                            </div>
```

Code From Class (ViewModel):
```
[Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateTime StartDate { get; set; }

        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateTime EndDate { get; set; }
```

Usings in the ViewModel:
```
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
```

Have you changed the behaviour for this?

Using:
VS 2017 15.3.5
.Net Core 2.0.0

**Comment by ajcvickers** [comment]
@dougbu Any thoughts on this?

**Comment by dougbu** [comment]
@Petermarcu do you have a sample application demonstrating "rendered as an input with type date in the past"?

The `type` attribute used for `DateTime` values should not have changed since the 2.0.0 release. MVC 5.2.3 and ASP.NET Core MVC 1.x.y used `type="datetime"` for that datatype (not `type="date"`) but recent HTML specs have deprecated that choice.

`type="date"` should only be used if the property has a `[DateType("date")]` or `[UiHint("date")]` attribute or if the `<input/>` already has `type="date"` in the .cshtml file.

FYI `[DisplayFormat]` shouldn't affect the `type` attribute value. If it does, we have a bizarre bug. (On the other hand, various `type` choices lead to different default formats.)

**Comment by Petermarcu** [comment]
@johanskoldekrans will have to give details. I just moved this issue :)

**Comment by johanskoldekrans** [comment]
@Petermarcu @dougbu The below HTML is generated from an empty project where I just made a class to send through the controller and render. 

[AttributeExample.zip](https://github.com/dotnet/corefx/files/1361979/AttributeExample.zip)

The first example is using 1.1 and the below HTML is generated from the same project (just changed to the metapackage and netapp-version 2.0).

```
<input name="StartDate" id="StartDate" type="datetime" value="2017-10-05" data-val-required="The StartDate field is required." data-val="true">

<input type="datetime-local" data-val="true" data-val-required="The StartDate field is required." id="StartDate" name="StartDate" value="2017-10-05">
```

**Comment by dougbu** [comment]
@johanskoldekrans you originally said earlier versions had used `type="date"`. If you meant, `type="datetime"` then all is as-expected. That `type` has been deprecated and MVC has used `type="datetime-local"` since 2.0.0.

I'd also expect browsers to have trouble rendering a control for either `type`. The `d` format doesn't include the time portion a date/time picker needs.

**Comment by ajcvickers** [comment]
@dougbu Fair to say we can close this as by-design?

**Comment by dougbu** [comment]
@ajcvickers yup.

@johanskoldekrans the 2.0.0 choices weren't the end of the story e.g. because our default formats for `type="datetime-local"` don't round-trip `DateTimeOffset` offsets. We've fixed a few bugs in this area in the MVC [repo](https://github.com/aspnet/Mvc) and issues with the current code should be filed [there](https://github.com/aspnet/Mvc/issues).

**Comment by dougbu** [comment]
(This repo doesn't have by-design, won't fix, or similar labels. Should it?)

**Comment by ajcvickers** [comment]
Thanks @dougbu. Appreciate your help!

**Comment by ajcvickers** [comment]
@dougbu It's corefx, so it's like a wonderful collision of the Microsoft galaxy with the open-source galaxy which results in a lot of beautiful stuff, but it's not quite like what we're used to. So, no, apparently not.

**Comment by johanskoldekrans** [comment]
@dougbu @ajcvickers @Petermarcu Thanks for the time and effort. I immediately set the type to date in the html and skipped the serverside rendering of the html but it is always good to know why something was changed.
