### ISSUE TITLE
.Net WebClient.DownloadData api result in different behavior in some kind of project

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#24477]
@treeicnliu commented on [Sat May 27 2017](https://github.com/dotnet/core/issues/664)

I got different http packages by fiddler4 when i call the same fucntion WebClient.DownloadData(string uri) api with the same param uri on web proj and console proj.

I found that webclient will auto decode uri in web proj,and keep the origin uri in console proj.

is it a .net issue ? 

The uri below can't access,but it can be used for test

http://objstore.qa.nt.ctripcorp.com/smartemailstorage/2017%5C4%5C6%5Cf809530b-0ded-49b4-8532-002c7ad73b41%5C%E9%98%BF%E9%87%8C%E5%B7%B4%E5%B7%B4Java%E5%BC%80%E5%8F%91%E6%89%8B%E5%86%8C.pdf?AWSAccessKeyId=D1NNJCXLEF0O7JIB2U3L&Expires=1511426288&Signature=iJjQCreO6F7avac86Tg2S4e4Miw%3D

---

@karelz commented on [Sun Jun 11 2017](https://github.com/dotnet/core/issues/664#issuecomment-307703162)

Do both of your projects use the same .NET Core 2.0-preview1 version?
The class is in `System.Net` namespace, if you still have troubles, please file it in CoreFX repo.

---

@richlander commented on [Sat Jul 01 2017](https://github.com/dotnet/core/issues/664#issuecomment-312471536)

@treeicnliu can you share the before and after of the return value in both cases. 

Can you share how this property is set in both cases? https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient.encoding?view=netcore-2.0#System_Net_WebClient_Encoding

---

@richlander commented on [Mon Jul 03 2017](https://github.com/dotnet/core/issues/664#issuecomment-312734798)

@treeicnliu can you share a repro? I'm not quite sure what to test based on your description.

---

@treeicnliu commented on [Fri Aug 11 2017](https://github.com/dotnet/core/issues/664#issuecomment-321776665)

[test.docx](https://github.com/dotnet/core/files/1217516/test.docx)

@richlander , i want to dowdload data from the url(with fixed signature) in .net web proj ,it doesn't work since the url has changed(broke the signature),but worked in console proj.  see the file test.docx i uploaded.   

btw, both proj based on .net 4 framework.

**Comment by davidsh** [comment]
This is probably not a WebClient issue. Rather, it is a System.Uri issue dealing with percent encoded octets.  We have several behavior differences in this area between NETFX and NETCore. We are working on fixing several bugs in NETFX (Desktop) (and probably will have AppContext quirking for those).  After that, we can determine what fixes are appropriate to bring to NETCore for System.Uri changes that might address this.

**Comment by rmkerr** [comment]
The only difference between the two resulting URIs is the '/' character. In both versions it is passed in encoded as '%5C'. According to the spec it should be left encoded in the resulting URI. In the example given the console app behaves correctly, but the web app incorrectly decodes '%5C' to '/'.

However, @treeicnliu mentioned that he was running into this issue on .NET Framework 4. I've gone ahead and tested the same situation with .Net Core 2.0 in both an ASP.NET web app and a console app. I see the correct output on both. Since this repository doesn't track issues with Framework and I can't repro the problem in Core, I'm going to close this issue.

That being said, I'll be looking into whether or not I the issue occurs on the latest versions of .Net Framework. If anything comes up I'll add it to the list of things we may need to port back from CoreFx.
