### ISSUE TITLE
Strange generic expressions type check behavior

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#24481]
@chrbaeu commented on [Thu Aug 17 2017](https://github.com/dotnet/core/issues/856)

The following code prints with netcoreapp1.0 and net461:
```
IsExpression: True
IsExpression: True
```
And  with netcoreapp2.0:
```
IsExpression: False
IsExpression: True
```
I think netcoreapp2.0 should show the same results as the other.
```
namespace ExpressionBugTest {
    class Program {
        static void Main(string[] args) {
            Expression<Func<string, bool>> predicate = x => x != null;
            Console.WriteLine("IsExpression: " + (predicate.GetType().GetGenericTypeDefinition() == typeof(Expression<>)));
            Console.WriteLine("IsExpression: " + (typeof(Expression<Func<string, bool>>).GetGenericTypeDefinition() == typeof(Expression<>)));
            Console.ReadKey();
        }
    }
}
```

---

@svick commented on [Thu Aug 17 2017](https://github.com/dotnet/core/issues/856#issuecomment-323069527)

As far as I can tell, the reason for this is that `predicate.GetType().GetGenericTypeDefinition()` returns the internal type [`Expression1<T>`](https://github.com/dotnet/corefx/blob/43f78840284de81bfd1b5fe4deceedf95c673cf8/src/System.Linq.Expressions/src/System/Linq/Expressions/LambdaExpression.cs#L358), which inherits from `Expression<T>` and was introduced as an optimization in https://github.com/dotnet/corefx/pull/13133.

I'm not sure what is the best way to correctly check that a `Type` is an `Expression<T>`.

---

@stephentoub commented on [Thu Aug 17 2017](https://github.com/dotnet/core/issues/856#issuecomment-323075860)

cc: @bartdesmet, @VSadov

**Comment by Petermarcu** [comment]
cc: @bartdesmet, @VSadov

**Comment by jnm2** [comment]
`typeof(Type) == typeof(object).GetType()` gives `false` too. Maybe the code is overly brittle and should have been `IsAssignableFrom` instead of `==` all along?

**Comment by bartdesmet** [comment]
There's a breaking change indeed due to the removal of `sealed` on the `Expression<TDelegate>` type, so it was reasonable to use a type equality check before this change.

I'm not sure whether unsealing of types should be regarded as a breaking change (because one can observe differences through reflection) that prevents forward progress. It's often easier to start off with a type being sealed to relax it later when thought has been given to extensibility points or performance implications. I guess this is something for the corefx members to establish guidelines around.

For this particular case, an assignability check would indeed provide a solution. The rub is that open generics and assignability checks are a bit tricky. The alternative would be to walk the base type chain to the first public type encountered, which will still be `Expression<TDelegate>`. In fact, reflection omitting non-public types and members is often advisable to be robust against internal changes. Yet another alternative is to use an assignability check against `LambdaExpression`. It all depends on what the check is trying to achieve.

**Comment by stephentoub** [comment]
> I'm not sure whether unsealing of types should be regarded as a breaking change

In general I believe we've treated such changes as non-breaking, as they're only observable through reflection, and once using reflection, pretty much any change can be breaking if something was checking for that exact shape or metadata or whatever.
cc: @weshaggard, @terrajobst, @KrzysztofCwalina 

Obviously, though, we still need to be thoughtful about such changes, and ensure the change is worth the cost, as code like this that did take such a dependency can break.

**Comment by jnm2** [comment]
@stephentoub Where's the line between seeing reflection as an education issue and holding back from unsealing a class? I would hope for my own sake (who uses `static` where possible,` then `sealed`, then `abstract`, then virtual), that I can assume brittle dependencies on reflection behavior to be an education issue rather than my responsibility.

**Comment by stephentoub** [comment]
@jnm2, as I noted, to my knowledge we've never considered such changes to be "breaking" in the core libraries, but for any change we still need to be thoughtful about what the potential impact could be. Even something that's generally considered pure goodness like a performance improvement can and has broken customer code (e.g. we make something faster and expose race conditions in consuming code).  That doesn't mean we avoid such changes, it just means we need to consider the pros and cons of changes and whether they're actually worthwhile, accepting the associated risk.  For your own libraries and the customers of your own libraries, presumably you need to make similar decisions that weigh the pros against the cons.  You might not care at all about breaking consumers, you might care heavily about any potential break regardless of how likely or how significant the impact, or you might fall somewhere in between.

**Comment by OmarTawfik** [comment]
@bartdesmet @stephentoub if I'm reading this correctly, then this issue is a no-op. I'll close as such. Please feel free to re-open if you think this needs further investigation.
