### ISSUE TITLE
Is not possible to create custom cultures in .Net Core

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#24559]
@carcarbe commented on [Tue Oct 10 2017](https://github.com/dotnet/core/issues/1020)

Is not possible to create custom cultures in .Net Core

In .Net framework is possible to create custom cultures, e.g en-US-NY (English from New York). using CultureAndRegionInfoBuilder class  as is describe in this example http://www.c-sharpcorner.com/UploadFile/GemingLeader/creatingextending-a-culture/  .

Are there any plans to implement this in .Net Core?

In the project were I am working at the moment we need this to be able to create different localizations for different dialects  of the same language.

**Comment by danmosemsft** [comment]
@krwq on whether this can be done and whethere there are plans.

**Comment by tarekgh** [comment]
We have been awhile depending on the OS for getting the locales. You still can create a custom cultures on Windows using the locale builder tool https://www.microsoft.com/en-us/download/confirmation.aspx?id=41158 and the framework will just read this custom locale through the OS. Actually, this is the recomendation from OS team because CultureAndRegionInfoBuilder needs to know the internal structure of the custom culture files which is changing by the OS, so they don't recommend using CultureAndRegionInfoBuilder at all. 

For Linux, you can still use the techniques mentioned in https://askubuntu.com/questions/21316/how-can-i-customize-a-system-locale and net core will just read the custom locale through the OS too.

**Comment by softlion** [comment]
+1

I would like to use RegionInfo and add some missing regions like Guadeloupe, Saint-Martin, Nouvelle-Caledonie ....

**Comment by tarekgh** [comment]
> I would like to use RegionInfo and add some missing regions like Guadeloupe, Saint-Martin, Nouvelle-Caledonie ...

Are there any locales currently support such regions? if not, then I would ask you to report your request to ICU to add locales support such regions. Otherwise, you may create your own custom locale (as I mentioned in my previous comment) but such regions would not be portable on the machines don't have your custom locale.
