### ISSUE TITLE
Incorrect SSLStream cipher suites on Linux

### ISSUE THREAD

**Issue by morganbr** [dotnet/corefx#24648]
Currently SSLStream just passes "All" to OpenSSL for cipher suites. This is causing two unwanted choices:
1. It doesn't enable ECDHE or DHE cipher suites as that requires a separate call to set up. 
2. It enables cipher suites using the SEED and CAMELLIA block ciphers, which can cause compliance issues. 

We should consider this as a servicing candidate since a better set of suites improves defense-in-depth.

**Comment by danielamkaer** [comment]
I just stumbled into this issue, while trying to run my .NET Core application on Linux instead of Windows.
Do you know if there is a workaround to enable ECDHE cipher suites? Something like configuring openssl outside of the application.

**Comment by bartonjs** [comment]
@danielamkaer I don't think there's anything external to the process you can do to fix it.

The problem is that after creating the SSL_CTX `SSL_CTX_set_ecdh_auto(ctx, 1)` needs to be called (because it's, apparently, not the default).  Or (for OpenSSL 1.0.1) `SSL_CTX_set_tmp_ecdh` to a secp256r1 key (since everyone who supports ECDH supports that one it's a good "well, if we can't negotiate for it" value).  http://openssl.6102.n7.nabble.com/SSL-CTX-set-tmp-ecdh-callback-semantics-in-1-0-1-td51401.html

Technically when this gets fixed someone should probably also enable autogen for (FFC) DHE as well, but apparently some people disagree with how OpenSSL does auto on DHE.

My proof-of-concept-but-not-thorougly-tested fix was

```diff
$ git diff
diff --git a/src/Native/Unix/System.Security.Cryptography.Native/pal_ssl.cpp b/src/Native/Unix/System.Security.Cryptography.Native/pal_ssl.cpp
index fda1f4d..8119ff6 100644
--- a/src/Native/Unix/System.Security.Cryptography.Native/pal_ssl.cpp
+++ b/src/Native/Unix/System.Security.Cryptography.Native/pal_ssl.cpp
@@ -82,6 +82,7 @@ extern "C" void CryptoNative_SetProtocolOptions(SSL_CTX* ctx, SslProtocols proto
 #endif

     SSL_CTX_set_options(ctx, protocolOptions);
+    SSL_CTX_set_ecdh_auto(ctx, 1);
 }
```

**Comment by Priya91** [comment]
cc @bartonjs @morganbr Should this be fixed for 2.1?

**Comment by bartonjs** [comment]
Yes, and serviced for 2.0.

**Comment by Priya91** [comment]
This is fixed in the linked PRs.
