### ISSUE TITLE
Console.CursorLeft/Console.CursorTop blocks when other thread is executing Console.ReadLine()

### ISSUE THREAD

**Issue by joejoepie** [dotnet/corefx#24654]
In a mulithreaded linux console application, if you try to get the position of the cursor in one thread, while another thread is executing a blocking read from the console (aka Console.ReadLine()/Console.Read() ) both threads will block.

What is weird is that getting or setting the cursor position via the variables Console.CursorLeft and/or Console.CursorTop will block any thread while another is reading, the function Console.SetCursorPosition works fine, and does not block. This can't be the intended functionality.

**Comment by stephentoub** [comment]
set_CursorLeft and set_CursorTop are identical in implementation to SetCursorPosition because they literally just call SetCursorPosition.

get_CursorLeft and get_CursorTop take a lock with respect to other threads doing reads because on Unix terminals, they way you get the current cursor position is by writing a special character sequence to stdout and then reading a response from stdin; as such, we need to make sure that some other thread doesn't read the response that we need to read in order to determine the position. If you're suggesting we should wake up other threads doing the blocking read in order to interject the request/response for the cursor position on another thread, that may be possible but is also likely very non-trivial, and the value of it is questionable.

**Comment by joejoepie** [comment]
I encountered this when trying to receive messages from a socket and immediatly writing them out, while the user could be typing at the same time. Problem is when i write out the incomming messages the cursor is moved, and so the place where the user types is also moved, which is not desirable. I'll have to find another way to find a workaround. Thanks a lot for your time!
