### ISSUE TITLE
WinForms application referencing NuGet library (.NETStandard 1.3) will not deploy System.Net.Http

### ISSUE THREAD

**Issue by curdincaspar** [dotnet/corefx#24661]
Installing a NuGet package to a WinForms application which targets .NETStandard 1.3 results in an incomplete deployment. The dll System.Net.Http is not deployed (it's in the Debug/Release folder but not in the Publish folder) and also missing in Publish/Application Files.

Steps to reproduce
1) Create a new WinForms project.
2) Reference (in my case) YouTrackSharp (3.1.0).
3) Publish the project and see that System.Net.Http is missing.

**Comment by karelz** [comment]
@ericstj @weshaggard is that expected?

**Comment by weshaggard** [comment]
I suspect you are hitting one of the issues outlined in https://github.com/dotnet/standard/issues/481.

**Comment by curdincaspar** [comment]
I tried the workaround to use PackageReference but this did not help.
The default System.Net.Http package in the project had a warning and needed to be removed as it's referenced in the YouTrackSharp package and is then again missing in the "Application Files" of the Publish settings.

**Comment by karelz** [comment]
I tried it with VS 15.7.1, WinForms project targeting .NET 4.7.1. The deploy directory contains file `System.Net.Http.dll.deploy` (in subdirectory `Application Files\WindowsFormsApp1_1_0_0_0`). Seems like it is fixed in latest tooling (there have been bunch of fixes in the tooling around System.Net.Http and few other similar DLLs.
Closing. If you can still reproduce with latest tooling, feel free to reopen.
