### ISSUE TITLE
Add Security transparency

### ISSUE THREAD

**Issue by MrJul** [dotnet/corefx#247]
Since Code Access Security is a thing of the past with .NET Core, I wouldn't expect permissions or security attributes to be used (or even to exist).

I didn't see permissions anywhere in the current code: they seem to have be completely removed from .NET Core as expected.

However, [several committed files](https://github.com/dotnet/corefx/search?q=SecurityCritical+OR+SecuritySafeCritical&type=Code) still use `SecurityCriticalAttribute` or `SecuritySafeCriticalAttribute`. Is this a left-over from the .NET framework code? I expect so, since they mean nothing without permission checks. If this is intended, what are the guidelines about using them?

**Comment by ellismg** [comment]
@jkotas recently made a change in CoreCLR so that .NET Core projects ignore these attributes.  I believe the plan is to do a pass across all of CoreFX and remove the attributes.  Is that correct @jkotas and @stephentoub?

**Comment by jkotas** [comment]
Correct. It was done by change https://github.com/dotnet-bot/coreclr/commit/725d6a91fffdf4603c8a9c74e15cbc83ebf0e3d6.

We should clean this up when we get a chance.

**Comment by kangaroo** [comment]
I think we shouldn't clean this up.  Security transparency has many uses outside of the browser security model.  Think if I have a large application, and I want to conduct a security review.  The safe-critical and critical levels are of the most important, and I can have some lower level of concern with transparent code.

I agree CAS should be removed, but I think the coreclr and corefx should retain security transparency, and ensure that it works in the shipped assemblies.

We should not worry about, or try to enforce transparent security in 'random nuget module from the internet', but the BCL and runtime should support it so that consumers can use this as an attack surface area reduction.

**Comment by danmosemsft** [comment]
Clarifying title, this is a feature request for Core.

**Comment by tarekgh** [comment]
@weshaggard @jkotas do you think we can bring back security attributes? looks this what requested by @kangaroo

**Comment by jkotas** [comment]
We do not have

**Comment by jkotas** [comment]
We do not have security annotations in most of the code, and the few remaining places that still have them are not maintained and checked for consistency. We are removing them as we run into them. I do not think that they are coming back.
