### ISSUE TITLE
Want features for data annotation 

### ISSUE THREAD

**Issue by Eilon** [dotnet/corefx#24738]
_From @amitsaini12345 on October 14, 2017 14:21_

Please bring features to share common data annotations between each entity or model.  I will be no need to define separate separate data annotations for each properties of each entity.  

It would be more easy and bring code reusablity more if one can declare common data annotations of different properties because we see that common data annotation is like max length 50, int,  required etc. Are used to once and common for all entities. 

_Copied from original issue: aspnet/Mvc#6955_

**Comment by rynowak** [comment]
Java has a cool solution to this problem - you create high-level bean validators that represent your business domain, and then apply those: http://beanvalidation.org/2.0/spec/#constraintsdefinitionimplementation-constraintcomposition

**Comment by ajcvickers** [comment]
@amitsaini12345 This is not something we are planning to do in the core data annotations. One of the problems with any changes to data annotations is that at least some of the consumers of the annotations need to be updated to understand the changes, and when consumers are not updated it results in a confusion experience. Due to that, it might be better to do this by having some tool/package that makes it easy to apply annotations in bulk, although it would take some work to do this and make it a good experience. If there is no concern about current consumers, then probably a new third-party package is more appropriate.
