### ISSUE TITLE
WinHttpHandler throws exception for redirect when there's no location header

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#24819]
The .NET Framework does not.

**Comment by davidsh** [comment]
This issue has come up before.  If automatic redirect is enabled (which is the default), then it is an "error" that WinHTTP will detect.  The workaround is to disable automatic redirection in HttpClientHandler.

There are no plans to change this behavior in WinHTTP.

**Comment by davidsh** [comment]
There isn't any possible fix to this except to disable the use of WinHttp's auto-redirect functijnality.  That would impact performance of WinHttpHandler if we have to manually read the redirect response and then submit a new request.

I agree that the behavior is different from .NET Framework.  Perhaps, if/when the ManagedHandler comes online, we can then have its behavior match .NET Framework.  Although, I think an error is actually the better behavior since the developer is expecting auto-redirect to work and the server is violating the RFC by not including a Location: header in the HTTP 3xx redirect response.

For now, I'm going to close this as WON'T FIX in terms of WinHttpHandler behavior.
