### ISSUE TITLE
Using latest System.Memory with old S.N.V causes NU1605 package downgrade error

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#24910]
Since @weshaggard fixed https://github.com/dotnet/corefx/issues/24606 with https://github.com/dotnet/corefx/pull/24645, we have an issue where if we have an app targeting netcoreapp2.0 that references both System.Memory and an older version of System.Numerics.Vectors, we get a package downgrade error.
`D:\Debugger\Template.csproj : error NU1605: Detected package downgrade: System.Numerics.Vectors from 4.5.0-preview1-25825-08 to 4.3.0. Reference the package directly from the project to select a different version.
D:\Debugger\Template.csproj : error NU1605:  Template -> System.Memory 4.5.0-preview1-25825-08 -> System.Numerics.Vectors (>= 4.5.0-preview1-25825-08)
D:\Debugger\Template.csproj : error NU1605:  Template -> System.Numerics.Vectors (>= 4.3.0)`

This issue is reproducible for netcoreapp2.0 (but not for netcoreapp2.1).

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework> 
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Memory" Version="4.5.0-preview1-25825-08" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.5.0-preview1-25825-08" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.3.0" />
  </ItemGroup>

</Project>
```

- One workaround would be to update the application to target netcoreapp2.1. Why exactly does that resolve the package dependency issue?

- Another workaround would be to explicitly reference the latest version of System.Numerics.Vectors (that System.Memory was built against). This shouldn't be required.

**One solution for this issue would be to do the following (from https://github.com/dotnet/corefxlab/pull/1861#issuecomment-337747682):**
>  One thing to consider with System.Memory: shouldn't the netcoreapp2.0 implementation use the *inbox* version of System.Numerics.Vectors?  If it did so we wouldn't emit a package dependency.

How would we be able to do this? Any ideas how to resolve this issue?

> You need to investigate how System.Memory is building for netcoreapp2.0 and where it is getting the System.Numerics.Vectors that it is building against.

cc @KrzysztofCwalina, @ericstj, @weshaggard

**Comment by weshaggard** [comment]
>One workaround would be to update the application to target netcoreapp2.1. Why exactly does that resolve the package dependency issue?

Because the System.Memory package doesn't have a package dependency to System.Numeric.Vectors when targeting netcoreapp2.1 so there is no conflict.

>One thing to consider with System.Memory: shouldn't the netcoreapp2.0 implementation use the inbox version of System.Numerics.Vectors? If it did so we wouldn't emit a package dependency.
How would we be able to do this? Any ideas how to resolve this issue?

System.Memory doesn't have a netcoreapp2.0 build it only has a netstandard2.0 build configuration which is what gets selected. In that configuration it cannot make any assumptions about what platform is is running on so it has to reference the numerics package. 

The fix here is to do what nuget points out and deal with the downgrade issue by upgrading your version of System.Numerics.Vectors package. 

The only other option would be to add more build configurations to the System.Memory package which I don't think is really worth it for a case like this.

**Comment by ahsonkhan** [comment]
Closing this issue as "won't fix" given Wes' recommendation to upgrade the version of S.N.V as the workaround.
