### ISSUE TITLE
GZipStream not working as expected on compress.

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#24920]
@jgauffin commented on [Thu Oct 26 2017](https://github.com/dotnet/standard/issues/556)

I'm using .NET standard and had ported some code from .NET 4.5.2.

## Expected outcome:

`Dispose()` **_or_** `Flush()` should be enough for the compressed contents to get copied to the inner stream.

## Actual outcome

***Both*** Flush and Dispose are required to get the correct amount of bytes back from the gzipstream:

```
using (var gzip = new GZipStream(ms, CompressionLevel.Optimal, true))
{
    gzip.Write(jsonBytes, 0, jsonBytes.Length);
    gzip.Flush();
}
buffer = ms.ToArray();
```

With just flush, I get 190 instead of 200 bytes:

```csharp
using (var gzip = new GZipStream(ms, CompressionLevel.Optimal))
{
    gzip.Write(jsonBytes, 0, jsonBytes.Length);
    gzip.Flush();
    buffer = ms.ToArray();
}
```

With only Dispose i get 194 of the 200 expected bytes:

```csharp
using (var gzip = new GZipStream(ms, CompressionLevel.Optimal, true))
{
    gzip.Write(jsonBytes, 0, jsonBytes.Length);
}
buffer = ms.ToArray();
```

---

@Petermarcu commented on [Fri Oct 27 2017](https://github.com/dotnet/standard/issues/556#issuecomment-340018033)

I am assuming you are trying to run the library on .NET Core? We need to get this bug to whichever implementation of .NET Standard you are running on.

---

@jgauffin commented on [Fri Oct 27 2017](https://github.com/dotnet/standard/issues/556#issuecomment-340019795)

The .NET library is compiled as .NET standard. I discovered the error in a .NET ASP.NET Core MVC application and reproduced it in a .NET Core console application.

---

@Petermarcu commented on [Fri Oct 27 2017](https://github.com/dotnet/standard/issues/556#issuecomment-340022551)

Great. Yeah, it will be compiled against .NET Standard but will run on an implementation of .NET Standard in one of the implementations. Sounds like this one is in .NET Core. I'm going to move this issue to the repo that has the Compression code for .NET Core.

**Comment by ianhays** [comment]
Since 4.6.2 we've used zlib for Deflate which has two different versions of flush: Flush and Finish. Finish is used at the end of compression to close out the zlib internal buffers and flush **all** data, finishing the current block regardless of how much data there is to go into that block. This is the mode we call on disposal.

The non-disposal flush has some different requirements because it can't invalidate the compressor i.e. subsequent writes should be allowed.

Are you comparing the length of the compressed byte array? Because that will differ based on the circumstances under which you flush/dispose and isn't a good method to compare actual correctness. Two arrays of compressed data can be different but decompress to the same bytes. Have you tried decompressing your buffer and then verifying that the bytes are correct?

**Comment by jgauffin** [comment]
Now that I try, I cannot reproduce it.

I think that I did a mistake and allocated a too small destination buffer (same size as the compressed content) and that's why I got a partial decompressed message.

Sorry for that.

**Comment by ianhays** [comment]
No worries @jgauffin :) Let me know if there's anything else and I'll go ahead and close out this issue.
