### ISSUE TITLE
Performance improvements (CoreFX) Epic

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#24931]
This sub epic is to track specific investments to improve performance in CoreFX functionality - other than networking performance which is tracked [elsewhere](https://github.com/dotnet/corefx/issues/24742).

We plan to use data - such as Azure profiler; customer traces; CLBG, TechEmpower - to target performance improvements where they matter most, generally in widely-used existing API. Candidate areas include: Timers, Async methods, Cancellation, Synchronization, Linq, Regex, Collections, Strings. Often changes will be candidates for porting to .NET Framework.

Performance improvements are made all the time they do not necessarily need to be linked to this. This is to track specific focus areas.

**Comment by AceHack** [comment]
Please add File I/O to this list as well.  Would include things like SSD, HDD, Sequential Access, Random Access, Async, Sync, Parallel/Overlapped, Small Size, Large Size, Unbuffered (Hardware, OS, App), Buffered, etc...  I really wish there was similar benchmark like TechEmpower for all these file access patterns.

http://fsbench.filesystems.org/

**Comment by danmosemsft** [comment]
@AceHack good list -- perhaps you could open issues for some of those? Especially if you see room for improvement, we are not competitive, or it is showing up in real world traces.

We want to focus our own resources using data, for example @JeremyKuhne 's work on GetFiles right now is because it shows up in profiles of MSBuild, NuGet, VS, and Azure services etc (and we know we can improve it).

Even without data, if improvement is possible, community folks may be interested in investigating.

**Comment by powercode** [comment]
I have looked at the performance of `Select-String` in PowerShell. A common scenario using directory traversals, file IO with StreamReader and RegEx matching.  It is quite slow today, both in finding the files to search , reading the file content and doing the regex matching. There is a lot  of string allocations when reading each line of the file, byte arrays allocated for decoding utf8 and generally slow performance in Regex.

This is a scenario that exercises several different systems and would be a good benchmark to track.

**Comment by danmosemsft** [comment]
Good suggestion. We are working on regex and file enumeration. Regarding reading the file content into strings -- perhaps Powershell should not be reading linewise. @karelz who is our Powershell contact?

**Comment by karelz** [comment]
I would suggest to start with PowerShell repo - filing perf enhancement: https://github.com/powershell
I don't have active contacts with PowerShell team, only few one time emails about a year ago.

**Comment by powercode** [comment]
We cannot do much about this on the PowerShell side without the improvements in the core framework. Many of the changes you are doing are very promising, like all the work on Directory traversal/GetFiles and all the Span/low alloc things. All these will greatly benefit PowerShell. 

My suggestion is actually more basic - have regex filtering of file content as a core scenario.

If that can be done fast in CoreFX, we can make if fast from PowerShell.

**Comment by danmosemsft** [comment]
> regex filtering of file content as a core scenario.

Powershell can do this just as efficiently, right? Over a FileStream. Of course, it may make sense for us to have an API for it -- I'd encourage you to open an issue with an API proposal if you think it is generally interesting (and especially if somehow only we can do it as fast)

**Comment by powercode** [comment]
Well, maybe this is just my ignorance speaking, but I haven't found a low-alloc path for matching each line in a file to a regex. I know for example that Rust uses a memory mapped file when matching, but since the RegEx class only has a `string` as input to the Match function, it is hard to avoid allocating a string for each line in every searched file.

This is where I am under the impression that we cannot do it well from PowerShell, as the users of the current API.

**Comment by powercode** [comment]
To be clear, I'm not at all certain what the solution should look like, but the scenario is clear: run a regex over each line of a file content with as few allocations as possible. I did some more research here and it seems you already have a nice plan for faster directory traversal.

**Comment by benaadams** [comment]
RegEx returning either `Memory<char>` or `Span<char>` for matches and match param?

/cc @KrzysztofCwalina

**Comment by 4creators** [comment]
> I haven't found a low-alloc path for matching each line in a file to a regex

During my `dogfooding` experiment I have faced exactly the same problem while writing simple C# script `.csx` to generate one of coreclr repo docs [clr-configuration-knobs.md](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/clr-configuration-knobs.md). The idea was to get first hand experience with C# scripting and csi and compare to other languages like `Perl`, `Python` in simple text processing task.

 The problem is that currently parsing of simple, macro only C++ header file is at least order of magnitude faster with string search functions rather than with .NET Core Regex implementation. This can be attributed partially to lack of non-allocating APIs in regex functions. 

I do not want to hijack thread but another big, regex related problem is lack of regex literals which could be used instead of OO code which is too explicit - this is obviously the C# language problem but it should be easy to fix.

**Comment by svick** [comment]
There is already an issue about adding `Span` support to `Regex`: https://github.com/dotnet/corefx/issues/24145.

**Comment by powercode** [comment]
To be really efficient, I think that the regex implementation have to be able to get the next char/rune/byte to match from some enumeration, that should be able to convert the raw memory of a file buffer/memory map using a selected encoding.
Otherwise I don't see how we could get rid of the allocations.

**Comment by danmosemsft** [comment]
OK, this is probably covered by #24145 then - let's continue discussion there - assuming there is an appropriate buffer to put the Span over. 
cc @ViktorHofer for info as he owns regex.

>  lack of regex literals 
@4creators if you are looking for compile time checking then this may be interesting. https://github.com/dotnet/roslyn/pull/23984

**Comment by 4creators** [comment]
@danmosemsft Yes, that is one side of the story. The other one is that writing regex code which comprises literals only is more efficient from developer perspective.

**Comment by stephentoub** [comment]
@danmosemsft, what is this issue tracking at this point?

**Comment by danmosemsft** [comment]
Nothing, we aren't using Epics anymore, we use Github projects.
