### ISSUE TITLE
Closing NamedPipeServerStream does not cancel WaitForConnection on Linux

### ISSUE THREAD

**Issue by khyperia** [dotnet/corefx#24973]
As far as I can tell, there is _no_ way to cancel a WaitForConnection call on Linux.

Repro code: https://github.com/khyperia/UnixDomainSocketTest/blob/81d792a083da340a28795054665390c7a7417ef9/Program.cs#L52-L81 - run with `dotnet run closeserver`

Expected behavior, and actual behavior on Windows:

```
Go!
Begin wait for connection
Started thread, closing stream
Closed stream, Join()'ing thread
Exception!
System.IO.IOException: The pipe has been ended
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.Pipes.NamedPipeServerStream.WaitForConnection()
   at UnixDomainSocketTest.Program.<>c__DisplayClass3_0.<WaitForConnectionClose>b__0() in C:\c\UnixDomainSocketTest\Program.cs:line 65
End wait for connection
Joined thread, done
```

Actual behavior on Linux:

```
Go!
Begin wait for connection
Started thread, closing stream
Closed stream, Join()'ing thread
[[ infinite hang ]]
```

Related: https://github.com/dotnet/corefx/pull/24798

(workaround in Roslyn is to set `IsBackgroundThread = true` on the thread calling `WaitForConnection`)

**Comment by stephentoub** [comment]
Using the synchronous WaitForConnection does a synchronous `accept` on the underlying socket; closing a socket file descriptor while in use in a synchronous/blocking `accept`/`connect`/`recv`/`send` has undefined behavior in BSD Sockets, and typically hangs on Linux.

WaitForConnectionAsync, however, takes a CancellationToken.  If you want to be able to cancel the operation, you should use that rather than the synchronous WaitForConnection.  At the moment that won't do you much good, but once https://github.com/dotnet/corefx/issues/24430 is implemented, it should "just work".

Closing a Stream while it's in use is generally considered poor form, with undefined behavior.  It happens to provide the behavior you're seeing on Windows as a side-effect of its implementation.  If you want to rely on similar side effects on Linux, you could use `WaitForConnectionAsync()` regardless of the cancellation token, and I'd expect that by closing the stream you'd similarly see an exception occur, as at that point the underlying socket is non-blocking and we have more control over the behavior.  Again, though, that behavior isn't guaranteed.

**Comment by stephentoub** [comment]
That said, https://github.com/dotnet/corefx/pull/24798 might mitigate this for you, anyway, as it itself uses AcceptAsync() instead of Accept for WaitForConnection().

**Comment by khyperia** [comment]
Fantastic, thanks for the advice. Turns out that us using `WaitForConnection` (non-async) was just legacy from when that API was not available, and we've since upgraded.

**Comment by danmosemsft** [comment]
This seems resolved then..
