### ISSUE TITLE
Add validation of contract/implementation consistency for readonly structs, parameters and returns

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#25039]
readonliness is part of the contract. We need to add validation for this to our contract tooling to ensure consistency between reference assembly and implementation.

From @weshaggard : It should be easy enough to add for anyone that wants to verify it. The code lives in Microsoft.Cci.Extensions in Buildtools.

https://github.com/dotnet/coreclr/pull/14789#issuecomment-341579931

**Comment by weshaggard** [comment]
We essentially just need to add the logic to support the readonly keyword and then our compat tools will validate it correctly. The logic should be added in here https://github.com/dotnet/buildtools/blob/master/src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Types.cs#L147.

**Comment by Petermarcu** [comment]
Who should this be assigned to?

**Comment by weshaggard** [comment]
I suspect anyone could pick it up but ideally it would be someone familiar with the new IL patterns for this new compiler feature.

**Comment by weshaggard** [comment]
Investigate what IL is emitted for readonly structs, parameters, returns.
Update CCIExtensions to understand readonly structs, parameters, returns (based on IL metadata)
UPdate APICompat to verify each of these match
Update GenAPI's to emit these into the reference assembly code.

Cost assumes its @weshaggard 

Will be done along with #6185. Total 5 days between them.

**Comment by weshaggard** [comment]
@jkotas @jaredpar I'm going to make some updates to our tooling to understand the new C# features. I will add support for readonly and ref returns are there any other interesting keywords/features we need to make sure exist?

**Comment by jkotas** [comment]
Here are the different cases that I can think of:
- ref structs: `ref struct MyStruct { }`
- ref returns: `ref int MyMethod()`
- readonly arguments: `void MyMethod(in DateTime arg)`
- readonly ref returns `ref readonly DateTime MyMethod()`
- readonly structs: `readonly struct MyStruct { }`
- tuple arguments/returns: `(int My1, int My2) MyMethod()`

**Comment by weshaggard** [comment]
@jkotas I started adding some rules to our APICompat tool and come to realize that a number of these are actually compatible changes (i.e. I assume you could add ref or readonly to a struct in V2) so we don't currently have any tool beyond our APICompat tool to verify consistency between our contracts and implementation, so it won't catch inconsistencies that are compatible. 

It can catch things marked as readonly or ref in the implementation but not in the contract but not the other direction because those are compatible. 

Just to clarify the rules, please check my work:
- ref structs: `ref struct MyStruct { }`
  - Can be added in the future but once it exists cannot be removed
- ref returns: `ref int MyMethod()`
  - Must always match cannot change a return type modifier. 
- readonly arguments: `void MyMethod(in DateTime arg)`
  - Must always match cannot change a parameter modifer
- readonly ref returns `ref readonly DateTime MyMethod()`
  - Must always match cannot change a return type modifier. 
- readonly structs: `readonly struct MyStruct { }`
 -  Can be added in the future but once it exists cannot be removed
- tuple arguments/returns: `(int My1, int My2) MyMethod()`
 - Not really a compat issue (beyond they must always match) just a syntax output format issue which I'm going to ignore for this issue.

**Comment by jkotas** [comment]
> ref structs: ref struct MyStruct { }
> Can be added in the future but once it exists cannot be removed

This is other way around. `ref` cannot be added in future. It should be a compatible change to remove it, but I doubt that we will ever have situation like that. I think we should require match for it.

> tuple arguments/returns
> Not really a compat issue

The concern are the names of the tuple components. They cannot change in future.

@VSadov Does this look right?

**Comment by jaredpar** [comment]
> This is other way around. ref cannot be added in future. It should be a compatible change to remove it, but I doubt that we will ever have situation like that

I think at this moment removing `ref` from a struct is a compat preserving change. There were some suggestions that we change overload resolution to understand `ref struct` so that we can remove candidates where generic parameters bind to type parameters. There were a few scenarios that @KrzysztofCwalina found that would benefit from this. If we made this change then removing `ref` would cause previously unambiguous overloads to become ambiguous.

**Comment by jkotas** [comment]
> I think at this moment removing `ref` from a struct is a compat preserving change

There are ideas about `ref struct` specific optimizations: https://github.com/dotnet/coreclr/pull/15745#issuecomment-355481958 . They will also turn it into non-compatible change. I think we should make `ref` to be part of the contract that you cannot add or remove.

**Comment by jaredpar** [comment]
> I think we should make ref to be part of the contract that you cannot add or remove.

Agree.

**Comment by weshaggard** [comment]
Filed https://github.com/dotnet/buildtools/issues/1850 to track adding tuple support to the tools.

**Comment by weshaggard** [comment]
This work has been down.
