### ISSUE TITLE
System.IO.MemoryMappedFiles.Tests.CrossProcessTests.DataShared failed in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#25037]
Failed test: System.IO.MemoryMappedFiles.Tests.CrossProcessTests.DataShared

Configuration: osx10.12_release

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/3498/testReport/System.IO.MemoryMappedFiles.Tests/CrossProcessTests/DataShared/

MESSAGE:
~~~
Exit code was 131 but it should have been 42\nExpected: True\nActual: False
~~~
STACK TRACE:
~~~
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 203 
at System.IO.MemoryMappedFiles.Tests.CrossProcessTests.DataShared() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/System.IO.MemoryMappedFiles/tests/MemoryMappedFile.CrossProcess.cs:line 33
~~~

**Comment by danmosemsft** [comment]
@stephentoub do you have ideas what could cause the remote process to fail with SIGQUIT? It's not tests in any particular library. I believe it's generally OSX. Perhaps there's some logging we can add.

**Comment by stephentoub** [comment]
I'm not sure.  Generally infrastructure like docker or jenkins will use SIGTERM rather than SIGQUIT, and if I remember correctly, Jenkins even blocked SIGQUIT signals, hence https://github.com/dotnet/corefx/blob/dd1a1f9b12c177b0f6e3d239d3e9b1961fd1f840/src/System.Console/tests/CancelKeyPress.Unix.cs#L19.

**Comment by danmosemsft** [comment]
Another SIGQUIT failure on OSX 10.12...

https://github.com/dotnet/corefx/issues/25311

I am always seeing this just before it ... 

  A fatal error occurred, the required library libhostfxr.dylib could not be found at /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/bin/testhost/netcoreapp-OSX-Debug-x64/shared/Microsoft.NETCore.App/9.9.9/

This seems to come from corehost.cpp in which case it will return   CoreHostLibMissingFailure   = 0x80008083 from main(). I am not sure how that is interpreted as SIGQUIT. Nevertheless it seems the problem.

**Comment by danmosemsft** [comment]
@steveharter we are periodically getting OSX 10.12 test failures with `A fatal error occurred, the required library libhostfxr.dylib could not be found at /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/bin/testhost/netcoreapp-OSX-Debug-x64/shared/Microsoft.NETCore.App/9.9.9/`. This comes from corehost. Any idea why this might happen?

I guess we have to set COREHOST_TRACE on these runs.

**Comment by danmosemsft** [comment]
COREHOST_TRACE may not help us, but since I added the extra logging, we know that this folder does exist or the error would be different:

/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/bin/testhost/netcoreapp-OSX-Debug-x64/shared/Microsoft.NETCore.App/9.9.9

In other cases, we see `  A fatal error occurred, the folder [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/bin/testhost/netcoreapp-OSX-Release-x64/shared/Microsoft.NETCore.App/9.9.9/host/fxr] does not exist`

https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/4258/consoleText

@dotnet/dnceng a question: in this log, https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/4258/consoleText we see exactly one test library failed, seemingly because the test folder was not set up correctly. In this case, are all the test libraries running on the same machine, as it appears from the log? I'm not sure in what circumnstances they all run on the same machine vs. distributed. If they're all on the same machien, it is quite odd that only one test library failed because I would expect them all to have a bad setup.

**Comment by MattGal** [comment]
@danmosemsft apologies for the late response.   This was indeed a non-Helix setup where the tests all ran on the local machine.  

I am confused how you think added logging has addressed this though, since the string ```/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/bin/testhost/netcoreapp-OSX-Release-x64/shared/Microsoft.NETCore.App/9.9.9``` only shows up in the described error.

Generally when this happens, I'd expect either one of the following:  a) Binary depended on by single test (perhaps via being built slightly differently) is missing and exception is very strange or b) one of the many weird things logging in parallel to the console tried to use a non-existent shared fx version for this run.  I think it's b.

Given all the tests around your error did run to completion (System.Threading.Tasks.Parallel.Tests and System.Threading.Tasks.Dataflow.Tests did actually have a failure where it was trying to start a process, I think there may be a problem specific to the RemoteExecutor Console app thing you guys use.

**Comment by steveharter** [comment]
The `libhostfxr.dylib` should exist in a `/host/fxr/<version>/` directory underneath the host executable (dotnet.exe), at least for portable apps. I don't see how it should ever be nested under in the framework directory `/shared/Microsoft.NETCore.App/<version>/` like some of the logs have.

**Comment by stephentoub** [comment]
> Let's see if it reoccurs

It reoccurred.
https://github.com/dotnet/corefx/issues/29449#issuecomment-385977373

**Comment by stephentoub** [comment]
Closing again, as haven't seen this in a year.
