### ISSUE TITLE
Asp.Net Core App restarts when controller return type is void on Exception

### ISSUE THREAD

**Issue by avireddy02** [dotnet/corefx#25122]
Use the the below code as a controller action.
```
 [HttpGet("Test")]
 public async void Test()
 {
         await _mgr.HttpContext.Request.ReadFormAsync(); //just to use an async method
         throw new Exception("Test");
 }
```

Ideally async method should return Task but returning void should not bring the application down.

**Comment by Joe4evr** [comment]
When you `await` something in an `async void`, the method returns to the caller, but it has no way to capture the context on which it was called. The caller always considers it completed successfully because `void` can't carry any state. So when an exception happens later, it goes off into the wild and brings down the whole process because there's no context to throw it on.

This is ***exactly*** the reason that you should [***never*** write an `async void`](https://twitter.com/brianpeek/status/556228864389558272) if it's at all avoidable.

**Comment by avireddy02** [comment]
I did understand async void should not be used.

but in Asp.Net 4.6.1 -Web Api below is the error and its doesn't not Crashing the application

```
An asynchronous module or handler completed while an asynchronous operation was still pending.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: An asynchronous module or handler completed while an asynchronous operation was still pending.

**Source Error:** 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

**Stack Trace:** 


[InvalidOperationException: An asynchronous module or handler completed while an asynchronous operation was still pending.]
```

**Comment by karelz** [comment]
If ASP.NET 4.6.1 behaves differently, it would be best to follow up on ASP.NET repos to find out what is different. I don't think it is difference in async behavior.
Closing as answered.
