### ISSUE TITLE
Improve Diagnose Api of (Buffered)Channel

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#25162]
_From @JanEggers on September 23, 2017 9:39_

hi there,

im currently experimenting with System.Threading.Tasks.Channels.Channel.

for perfromance analysis it would be really great if BoundedChannel would be a public type and has properties that express the current buffer fill level.

Right now im using reflection to get that Info but i wonder why you make that an internal. (the info is there via debugview but neither toString or any public api can be used to get that information)

im using that information to determine performance bottlenecks in my app. I know that consumers of buffers with growing fill level have to be optimized. 
  

_Copied from original issue: dotnet/corefxlab#1782_

**Comment by stephentoub** [comment]
_From @KrzysztofCwalina on November 9, 2017 20:9_

@stephentoub, is this still relevant? If yes, should we move it to corefx? I would like to remove System.Threadin.Channels issues from corfxlab

**Comment by stephentoub** [comment]
It's still relevant (though debatable whether we should do it or not).  Feel free to move it to corefx. Thanks.

**Comment by stephentoub** [comment]
_From @KrzysztofCwalina on November 9, 2017 21:51_

@JanEggers, could I please ask you to move this to corefx repo? The component itself was moved there and it would be good to have the issue there as well.

**Comment by kouvel** [comment]
CC @tarekgh, marking as Future for now, feel free to change

**Comment by tebeco** [comment]
As proposed in #39998
I'm wondering if the LTS of 3.1 could contains API that returns buffer level as proposed in this issue.

It can also be relevant for `Unbounded` as it give an indication on the Consumer "readiness" / blocked / too slow

i have no idea how a new api like `channel.QueueSize` impact `netstandard2.1`
since the 3.1 LTS is for `netcoreapp` i supposed the only change is for the runtime ?
as we have streaming libraries it's targeting `netstandard2.x`

As the LTS is going to be a `Minor` (new API)
if `netstandard` is affected by it, it could be part about f `netstandard2.2` with a sub-set of api that could not make the cut for 2.1 right ?

i know i'm probably too optimistic, i'm just really curious to know what doe sit really impact i. order to understand if/how/why it would land on either 3.1 or 5.0

As @JanEggers noted, in order to access it :
we could use reflexion but it's subject to change
or doing it on our own ... but it would affect the hot path (see #39998)

**Comment by stephentoub** [comment]
https://github.com/dotnet/runtime/pull/312 added a Count property to ChannelReader.

**Comment by tebeco** [comment]
will try to find time by the week to take a look at it
thx a lot for everyone involved in it
