### ISSUE TITLE
Do not change the request object provided by the user

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#25163]
It is general implementation policy in other handlers in System.Net.Http, to not modify the HttpRequestMessage object provided by the user through the SendAsync method. In managed handler implementation, this object is modified in several places, revisit this design to minimize altering the request object from user. For more information refer to the conversation in PR #25090

**Comment by geoffkizer** [comment]
I read through the linked discussion and I think I understand the issue now.  Let me know if I'm missing anything.

The managed handler is built in such a way that the "layered" features (auth, cookies, decompression, redirect) modify the user's HttpRequestMessage, by adding headers (e.g. Accept-Encoding for decompression).

There is concern (particularly from @davidsh) that this is contrary to the principles of HttpClient; that is, the user's HttpRequestMessage should not be modified.

There are basically three things we could do here, as I see it:
(1) Store added/modified headers in some sort of separate bag, and then write these out along with the user-specified headers.
(2) "Clone" the original request and modify the headers of the cloned request.
(3) Live with the current behavior.

Both (1) and (2) seem possible, at some cost in terms of effort and possibly perf (particularly for 2).

I'm not clear on what the downside of (3) is in practice.  As @stephentoub pointed out in the other thread, we're already modifying the user request in certain circumstances; the managed handler just does this in more places.  

Also, it doesn't seem unreasonable that if the user chooses these behaviors, their requests will be modified as appropriate to satisfy these behaviors.

So I'd propose we just live with the way things work today.  That said, I don't understand completely what we would be losing by doing this.  Thoughts?

**Comment by karelz** [comment]
Sounds reasonable to me - @davidsh is it ok to close the issue? Or do you have concerns regarding @geoffkizer's assessment?

**Comment by davidsh** [comment]
>That said, I don't understand completely what we would be losing by doing this.

Some users want might want to resend the same HttpRequestMessage multiple times.  Mutating it will prevent that.  That said, some of our implementations already disallowed that behavior by internally marking the HttpRequestMessage as "sent' and prevented future sends of it.

>do you have concerns regarding @geoffkizer's assessment?

If we decide to trend in this new direction (by allowing our implementation to mutate the user inputs), at the very least we need to document this.  I'm not 100% comfortable with this direction but I understand it is what it is due to early architecture decisions made in the SocketsHttpHandler.  And since performance is a P0/P1 for this HTTP stack, making large copies of headers etc would degrade that. So, I guess I can live with this direction.

**Comment by stephentoub** [comment]
> That said, some of our implementations already disallowed that behavior by internally marking the HttpRequestMessage as "sent' and prevented future sends of it.

Yeah, HttpClient does this, but HttpMessageInvoker does not, e.g. the only call in System.Net.Http.dll to MarkAsSent is here:
https://source.dot.net/#System.Net.Http/System/Net/Http/HttpClient.cs,632

**Comment by wfurt** [comment]
If we want to reuse HttpRequestMessage multiple times can we add some function to sanitize it back to pristine state (or do it automatically)

**Comment by geoffkizer** [comment]
> Some users want might want to resend the same HttpRequestMessage multiple times. Mutating it will prevent that. That said, some of our implementations already disallowed that behavior by internally marking the HttpRequestMessage as "sent' and prevented future sends of it.

I agree that being able to reuse the same HttpRequestMessage multiple times is interesting.  It's convenient, and it might also provide a perf win in some scenarios (though these may be largely artificial, benchmark scenarios; I'm not sure).

That said, I think we already prevent this today in practice.  And I believe WinHttpHandler does mutate the request in certain scenarios, right?  So the managed handler isn't making things any worse here, is it?  Except in the sense of "it's making it harder to enable this in the future".

For what it's worth, I'm planning to reduce the amout of HttpRequestMessage mutation that occurs in the managed handler.  (It turns out that mutating the object doesn't always provide the right semantics, e.g. cookies in combination with auth and redirects.)

I've already made this change for our cookie handling, and I'm planning on doing something similar for auth handling.  That means we will only mutate the object in a couple situations:

(1) Redirect (I believe other handlers are mutating here too, right?)
(2) Compression (adding Accept-Encoding header)
(3) Basic message framing stuff like Transfer-Encoding.

So, I think this will leave us in a place where we are not much worse than where we are today, in terms of enabling HttpRequestMessage reuse in the future.

Thoughts?

Unfortunately, even if we were to change all handlers to never mutate, we still have DefaultRequestHeaders and I'm not sure how we'd fix that.

**Comment by karelz** [comment]
Discussion
* We should not change the verb (we probably do on POST to GET redirect).
* Changing URI is ok - that is even documented
* Changing headers should be ideally avoided - @geoffkizer will check out full list and analyze if we can easily do it

**Comment by karelz** [comment]
Reusing Request objects is not officially supported & encouraged, so we can move it to Future. If we get feedback, we can reconsider.

**Comment by campersau** [comment]
NuGet.Client [resends requests](https://github.com/NuGet/NuGet.Client/blob/caac28293a4032de8629b39597a179df988a612a/src/NuGet.Core/NuGet.Protocol/HttpSource/HttpSourceAuthenticationHandler.cs#L74-L107) inside of a custom `DelegatingHandler` (which is not prevented).

This can lead to unexpected authentification issues with some servers which don't send a `Www-Authenticate` header back if an `Authorization` header was sent. The GitHub NuGet Package API does that.

For example using the NuGet.Client library to connect to GitHub NuGet feeds will result in a loop if the user inputs the wrong credentials the first time because the next time the users gets prompted for credentials they will be ignored because of the existing `Authorization` header and the server not responding with a `Www-Authenticate` header.

Here is a sample program which mimics the NuGet.Client behavior. This program works when **not** using the `SocketsHttpHandler`.

```c#
public class Program
{
    static void Main() => MainAsync().GetAwaiter().GetResult();

    // change `username` in this url to your user
    public static readonly string Url = "https://nuget.pkg.github.com/username/query?q=&skip=0&take=10&prerelease=false&semVerLevel=2.0.0";
    public static readonly NetworkCredential[] Credentials = new[]
    {
        new NetworkCredential("a", "b"), // intentional wrong credentials
        new NetworkCredential("username", "token"), // change `username` and `token` to your github user and [token](https://github.com/settings/tokens) with package access
    };

    static async Task MainAsync()
    {
        // uncomment this to fix the issue
        //AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);

        var mutableCredentials = new MutableCredentials();

        var clientHandler = new HttpClientHandler();
        clientHandler.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;
        clientHandler.Credentials = mutableCredentials;
        clientHandler.UseDefaultCredentials = false;

        var authentificationHandler = new AuthentificationHandler(mutableCredentials)
        {
            InnerHandler = clientHandler
        };

        var client = new HttpClient(authentificationHandler);

        await client.GetAsync(Url);
    }
}

public class MutableCredentials : ICredentials
{
    public NetworkCredential Credentials { get; set; }
    public NetworkCredential GetCredential(Uri uri, string authType) => Credentials;
}

public class AuthentificationHandler : DelegatingHandler
{
    private readonly MutableCredentials _mutableCredentials;

    public AuthentificationHandler(MutableCredentials mutableCredentials)
    {
        _mutableCredentials = mutableCredentials;
    }

    protected async override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        var credentialIndex = 0;

        while (true)
        {
            var response = await base.SendAsync(request, cancellationToken);

            if (response.StatusCode == HttpStatusCode.Unauthorized)
            {
                if (credentialIndex < Program.Credentials.Length)
                {
                    _mutableCredentials.Credentials = Program.Credentials[credentialIndex];
                    credentialIndex++;
                    continue;
                }

                throw new Exception("None of the credentials worked");
            }

            return response;
        }
    }
}
```

@onovotny for your information this is also an issue with the current [NuGetPackageExplorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer)

**Comment by karelz** [comment]
Triage: So far we got only 1 feedback on reusing Requests in 2 years. Overall we still don't think it is worth the complications at this moment. Closing.
We can reconsider again in future if we get more customers and/or data showing perf benefits on end-to-end scenarios.
