### ISSUE TITLE
[API] Stack constructed from another Stack is not the same as the original.

### ISSUE THREAD

**Issue by Ark-kun** [dotnet/corefx#25172]
`Stack<T>` has only only  one copy constructor and it accepts `IEnumerable<T>`.

The constructor does not try to check whether the given collection is another `Stack<T>`. The constructor just enumerates the source stack (in the `Pop()` order) and pushes all values in the new stack.

The result is that the new stack is actually reversed.

I consider this behavior unexpected and an example of bad API.

http://referencesource.microsoft.com/#System/compmod/system/collections/generic/stack.cs,66

**Comment by JonHanna** [comment]
It's not really a copy constructor at all though, it's a filling constructor.

If stack did have a copy constructor, then it would be a breaking change upon recompilation, precisely because it would be called by code currently calling the filling constructor, and do so in the reverse order to before the change.

A `Clone()` or similar method could fulfil the use case of producing a copy, without breaking any existing code.

**Comment by Ark-kun** [comment]
There is an neat rule of thumb that if class constructor accepts instance of the same class, then the resulting instance equals the original instance.

Whenever this rule of thumb is broken, it brings bad surprises to the API users.

I understand that this would never be fixed given the back-compat problems (even though I seriously doubt anyone is constructing stack from stack due to the current "broken" behavior).

I just wish the .Net devs are extra careful about this when designing future collection APIs.

**Comment by karelz** [comment]
Seems to be answered and agreed that there is nothing to fix here.
