### ISSUE TITLE
Remove the P2P reference from S.IO.FileSystem.Tests to S.Runtime.Extensions

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#2519]
We should remove the P2P reference added with https://github.com/dotnet/corefx/pull/2518, once an updated System.Runtime.Extensions package is published with the changes.

**Comment by ericstj** [comment]
I also had to add a P2P reference to the System.Diagnostics.Debug due to this issue in conjunction with https://github.com/dotnet/corefx/issues/2817.  I tried to remove the S.R.E reference but it looks like Jeremy added new tests here which depend on a newer version of S.R.E than even yesterday's build.  I think once we get a build newer than yesterday we can remove both of these :)
