### ISSUE TITLE
System.Runtime.Serialization.Primitives (DataContractSerializer) 4.3 is not compatible with coreapp 2.0 Derived Exceptions

### ISSUE THREAD

**Issue by scegg** [dotnet/corefx#25259]
DataContractSerializer in System.Runtime.Serialization.Primitives 4.3 is not compatible with Derived Exception objects in coreapp2.

In coreapp2, run this code below:
```c#
            Type type = typeof(NotSupportedException);
            DataContractSerializer serializer = new DataContractSerializer(type);

            var test = new NotSupportedException();

            object target;

            using (var stream = new MemoryStream())
            {
                serializer.WriteObject(stream, test);
                stream.Seek(0, SeekOrigin.Begin);

                try
                {
                    target = serializer.ReadObject(stream);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.ToString());
                    Console.ReadKey();
                    throw;
                }
            }

            Console.WriteLine("OK");
            Console.ReadKey();
```

System.PlatformNotSupportedException will be observed.

This code works like a charm in coreapp1.

Problem is still existed in System.Runtime.Serialization.Primitives 4.4.0-beta-24913-02.

[EDIT] Add C# syntax highlighting by @karelz

**Comment by shmao** [comment]
This worked on netcoreapp1.X because we had a special ExceptionDataContract for serializing exceptions. The drawback was that DataContractSerializer only serialized partial information of the exceptions.

On netcoreapp2.0, types like `ISerializable` and `SerializableAttribute` became available. As Exceptions implement `ISerializable` interface, DataContractSerializer would respect the interface and treat exceptions as `ISerializable` instances instead of using the ExceptionDataContract. The `PlatformNotSupportedException` is due to the exception either does not implement `ISerializable.GetObjectData` or does not have `ctor(SerializationInfo info, StreamingContext context)`.

While most of the System exceptions cannot be serialized, DataContractSerializer can still serialize a custom exception.

@danmosemsft @ViktorHofer do we have plan to support serializing System exceptions on 2.1?

**Comment by ViktorHofer** [comment]
We are bringing exception serialization back with the imminent servicing release (2.0.4). You can already inspect the changes to the types in the release/2.0.0 and master branches.

**Comment by ViktorHofer** [comment]
@scegg Please retry your scenario after upgrading to the next servicing release (2.0.4, rough release date: ~December) and get back to us if you are still having troubles. I'll close the issue for now.
