### ISSUE TITLE
How to implement System.IO.MemoryMappedFiles on FreeBSD?

### ISSUE THREAD

**Issue by janhenke** [dotnet/corefx#2527]
The assembly ```System.IO.MemoryMappedFiles``` does not build on FreeBSD.

We should discuss here how to implement it.

/cc @josteink

**Comment by josteink** [comment]
I don't think I know enough about memory mapped files in general. Not in theory nor in practice and definitely not on FreeBSD.

Maybe @saper can be of more help here?

**Comment by stephentoub** [comment]
I'd expect the existing MemoryMappedFiles implementation to "just work", or maybe almost "just work"; I would not expect it to need a lot of rewriting.  It doesn't compile right now because a bunch of the necessary constants haven't been defined/mapped for FreeBSD.  That said, that work shouldn't mostly become unnecessary as part of #2137.  Note that other than these .h values, the only differences between the Linux and OS X implementations are:
- What the storage mechanism is used to back anonymous maps (we need to be able to create multiple  "views" over the same backing store, which means we can't just rely on the ANON feature of mmap): for Linux we use a POSIX shared memory object (https://github.com/dotnet/corefx/blob/master/src/System.IO.MemoryMappedFiles/src/System/IO/MemoryMappedFiles/MemoryMappedFile.Unix.BackingObject_Memory.cs), and for OS X due to some shared memory object limitations we use a file (https://github.com/dotnet/corefx/blob/master/src/System.IO.MemoryMappedFiles/src/System/IO/MemoryMappedFiles/MemoryMappedFile.Unix.BackingObject_File.cs)
- Linux supports an MADV_DONTFORK flag with madvise, which we use to disable map inheritance
My guess is that with some work in the .csproj and filling out the appropriate constant values (e.g. filling out the equivalent of https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/OSX/libc/Interop.MemoryMappedFlags.cs), things should mostly fall into place.

**Comment by saper** [comment]
Can you elaborate on this part a bit? "What the storage mechanism is used to back anonymous maps (we need to be able to create multiple "views" over the same backing store, which means we can't just rely on the ANON feature of mmap):"

For the purposes of checking Linux kernel emulation in FreeBSD I wrote once a simple `mmap()` fingerprinter:

http://people.freebsd.org/~jkim/mmap_test.c

You might want to run that on Linux and OS-X as well to see some subtle differences on what happens in various situations.

Here's what I have for FreeBSD 10.x STABLE https://gist.github.com/aa996f523fc53dcbca7a

and for Linux 3.8.13: https://gist.github.com/15a764aed9b619f46804

**Comment by stephentoub** [comment]
> Can you elaborate on this part a bit?

The .NET API corresponds very closely to the Windows API, in that there are two functions used to create maps: one that actually creates the mapping (e.g. ```MemoryMappedFile.CreateFromFile``` / ```CreateFileMapping```), and then one that creates a view over that map (e.g. ```MemoryMappedFile.CreateViewAccessor``` / ```MapViewOfFile```).  This is in contrast to on Unix where there's just the one function, ```mmap```, that essentially serves both purposes.  That discrepancy causes some complications in implementing the .NET functionality on Unix, and in particular for the case where you create an unnamed, non-file backed map (e.g. ```MemoryMappedFile.CreateNew(null, 4096)```).  If we were sure that the developer would then only ever create a single view from this map, we could just implement that with ```mmap``` and MAP_ANONYMOUS.  But we have no way of knowing in advance whether that'll be the case, and we need to be able to support multiple views over the same map.  So, to achieve that, in CreateNew we create an object over which the anonymous map is created (we actually create the map as part of creating the view); on Linux we use a shared memory object, and on OS X we use a temporary file.  That way, all of the views/maps are created over the same data, and we get the basic behavior expected from the .NET API.

**Comment by nguerrera** [comment]
I have pending shim changes that let it build fine, but I have not tested it on FreeBSD.

**Comment by janhenke** [comment]
Once that shim changes are merged, I will test build it on FreeBSD.

**Comment by nguerrera** [comment]
It should build now that #3143 is merged.

**Comment by janhenke** [comment]
The recent update to build tools introduced an unrelated breakage. We need to fix that first before I can test the MemoryMappedFile assembly.

**Comment by janhenke** [comment]
I was able to build the updated shims on FreeBSD, but not the managed part due to #3173. Given that the managed code is the same for all Unix, I guess we can consider this issue solved and another assembly ready.
