### ISSUE TITLE
How to implement System.IO.Pipes on FreeBSD?

### ISSUE THREAD

**Issue by janhenke** [dotnet/corefx#2528]
The assembly ```System.IO.Pipes``` does not build for FreeBSD.

Here we want to discuss how to implement this assembly.

**Comment by stephentoub** [comment]
The implementation is almost entirely POSIX compliant; IIRC, the only places it's not are:
- On Linux, we're able to use pipe2 instead of pipe to create an anonymous pipe, which is beneficial because we can appropriately support HandleInheritability (https://github.com/dotnet/corefx/blob/master/src/System.IO.Pipes/src/System/IO/Pipes/AnonymousPipeServerStream.Linux.cs).  On OSX we just use pipe (https://github.com/dotnet/corefx/blob/master/src/System.IO.Pipes/src/System/IO/Pipes/AnonymousPipeServerStream.OSX.cs).
- On Linux, we're able to use fcntl to control the buffer size for the pipe (https://github.com/dotnet/corefx/blob/master/src/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Linux.cs); on OSX that support doesn't exist (https://github.com/dotnet/corefx/blob/master/src/System.IO.Pipes/src/System/IO/Pipes/PipeStream.OSX.cs)

As with MemoryMappedFiles, I'd expect that getting this assembly to work on FreeBSD should mostly be an exercise in editing the .csproj to pull in the right files and defining the necessary constant values from FreeBSD headers.  I'd also expect that most of that will be unnecessary with #2137.

**Comment by jasonwilliams200OK** [comment]
@janhenke, here is the ship for `System.IO.Pipes`: https://github.com/dotnet/corefx/pull/2974.

**Comment by janhenke** [comment]
The native shim builds fine on FreeBSD. So I guess this is fixed by it. As intended we can now simply use the generic Unix implementation.

**Comment by jasonwilliams200OK** [comment]
Thanks for the confirmation and updating the checklist: https://github.com/dotnet/corefx/issues/1626#issuecomment-111800540. :smile: :+1: 
Thanks @nguerrera & @stephentoub for the help! :tada:
