### ISSUE TITLE
"Don't directly throw Exception" System.Drawing

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/corefx#25526]
@safern i'm trying to fix "throw new Exception()" on System.Drawing(#23748) but as @karelz thought may be a compatibility concerns, with netfx. What do you think?I could split tests per platform, but i think that is not a good idea. Is it better to skip System.Drawing and go on with other?

**Comment by karelz** [comment]
I think it should be fine for System.Drawing the same way it is fine for anything else. We will likely need split test - I let @safern decide how best to do that.

**Comment by safern** [comment]
I think it should be fine for System.Drawing since `ArgumentException` and `InvalidOperationException` inherit from `Exception` so it is still typeof(Exception) and when people port their libraries from .NET Framework into .NET Core and expect an `Exception` it will still be caught. 

I think splitting tests is good, or we have an `AssertExtension` method in corefx that can receive 2 exception types, one for .NET Core and one for netfx: https://github.com/dotnet/corefx/blob/master/src/CoreFx.Private.TestUtilities/src/System/AssertExtensions.cs#L82

And in the cases where you can't do that it would be great to split the tests.

Also, for the ArgumentException that we will be throwing could we add ParamName to it please?

**Comment by MarcoRossignoli** [comment]
@safern i understand, i'll work on it.

**Comment by MarcoRossignoli** [comment]
@safern the AssertExtension accept only ArgumentException based exception, i cannot use it with Exception,ArgumentException. The solution could be write an overload Exception,Exception or split tests. In case of splits, is there a guideline or some sample to follow?

**Comment by safern** [comment]
Oh you're right, I was assuming both sides where ArgumentException based but netfx is throwing Exception. Let's split the tests, just name them the same and for the netfx just add a postfix like: ConstructorThrowsException_Netfx

and then you will add a `SkipOnTargetFramework` attribute. So you'll do something like:

```cs
[Fact]
[SkipOnTargetFramework(TargetFrameworkMonikers.NetFramework, "Difference in behavior, netfx throws Exception")]
public static void ConstructorThrowsArgumentException()
{ 
   ...
}

[Fact]
[SkipOnTargetFramework(TargetFrameworkMonikers.Netcoreapp, "Difference in behavior, netfx throws Exception")]
public static void ConstructorThrowsException_Netfx()
{ 
   ...
}
