### ISSUE TITLE
HttpCompletionOption.ResponseHeadersRead behavior with AllowAutoRedirect=true

### ISSUE THREAD

**Issue by shravan2x** [dotnet/corefx#25629]
This is a question regarding the behavior of `HttpCompletionOption.ResponseHeadersRead` when `AllowAutoRedirect` is set to true. When a redirect occurs, which of the following behaviors takes place?

1. The completion option is only respected for the first request (i.e. it is "best-effort"; since a redirect took place, we cannot respect the completion option. So we read the response body and then follow redirects ignoring the original completion option).
2. The completion option is respected for all requests (a new connection is created for each redirect, wasting a new connection each time).
3. The completion option is only respected for the last request (we read response bodies as long as the status code asks us to redirect. The destination response body is not read).
4. When a redirect occurs, the completion option has no effect.

Since HTTP/1.1 is the default protocol, `keep-alive`s are enabled. This means that if a response body is not read, then a new request cannot be made on the same TCP connection. So it seems that (3) or (4) are most likely.

However, RFC2616 does not forbid `HTTP 302` responses from having response bodies. So a problem arises when the responses are huge (say many GBs each). In this case, every redirect will take very long and it would actually be beneficial to re-create a new connection for each redirect.

I realize that this is a hypothetical scenario, but wanted to check anyway since the behavior was not documented (and I couldn't make much from the source).

**Extra**: How do timeouts work with regard to redirects? Are they per-request or for all of them?

**Comment by davidsh** [comment]
First, `HttpCompletionOption.ResponseHeadersRead` has nothing to do with whether or not connections get reused or not during HTTP request/response processing.  That option simply means when the async HttpClientHandler.SendAsync() method will complete.  If ResponseHeadersRead is specified, then it will complete when the headers are read but it will NOT read nor buffer in the response body content.

In the case of AutomaticRedirect processing, that option only has meaning for the final HTTP request/response, i.e. following any Location: header in the 3xx redirect response and then doing the final request/response.

So, in the list of choices you list above, number 3 is the behavior for the HTTP stacks.

>So a problem arises when the responses are huge (say many GBs each). In this case, every redirect will take very long and it would actually be beneficial to re-create a new connection for each redirect.

That comment above is very interesting and does impact how efficient HTTP stacks can be.  In order to reuse an existing connection for a redirect, the response body payload must be "drained" from the wire in order to reuse the same connection for the subsequent HTTP request (assuming it is going to the same server endpoint).  Each platform HTTP stack makes different decision here about this.  In fact, on Windows, the HttpClientHandler/WinHttpHandler has a special property 'MaxResponseDrainSize` that controls the low-level efficiency of this.  In practice, though, most redirect responses don't have much payload and that property isn't used.

**Comment by shravan2x** [comment]
> In fact, on Windows, the HttpClientHandler/WinHttpHandler has a special property 'MaxResponseDrainSize` that controls the low-level efficiency of this.

I didn't know that; Is it possible to change this from code without hacks like reflection?

Also, how do timeouts work with regard to redirects? Are they per-request or for all of them?

**Comment by davidsh** [comment]
>I didn't know that; Is it possible to change this from code without hacks like reflection?

If you use WinHttpHandler directly, you can change the value of 'MaxResponseDrainSize' property.  But the current default of 64KB is usually fine.

In terms of "timeouts", there is an overall HttpClient timeout that governs the whole request/response.  There are also internal TCP level timeouts for making connections but those are not controllable.

It is very rare that controlling any of those low-level things will impact most scenarios.

**Comment by shravan2x** [comment]
Sorry, I happened to update my comment while you were answering.

> In terms of "timeouts", there is an overall HttpClient timeout that governs the whole request/response. There are also internal TCP level timeouts for making connections but those are not controllable.

So if I understand correctly, if a request has `AllowRedirects` set to `true` and it redirects 8 times, the total time `SendAsync` might take is `8*Timeout`?

**Comment by davidsh** [comment]
>the total time SendAsync might take is 8*Timeout?

No.  HttpClient.Timeout is for the whole thing regardless of how many auto redirects are being processed.

**Comment by shravan2x** [comment]
I see. My last question is - how does MaxResponseDrainSize work when the transfer-encoding is chunked?

**Comment by davidsh** [comment]
>I see. My last question is - how does MaxResponseDrainSize work when the response body size is unknown i.e. the transfer-encoding is chunked?
Does it read up to 64KB and then terminate the connection?

The answers to those questions vary depending on the platforms (Windows vs. Linux) and also different versions of Windows.  I don't have any crisp answers to tell you about that.  On .NET Core and Windows, the .NET layer of HTTP is built on top of native Windows APIs (WinHTTP for non-UWP apps and WinINet for UWP apps).  The details you ask about are low-level native implementation details.  Even for Linux .NET Core (which currently uses Curl), I'm not sure of the answers.

**Comment by shravan2x** [comment]
> The answers to those questions vary depending on the platforms (Windows vs. Linux) and also different versions of Windows.

That's fine, I was just curious anyway. Thanks for the answers!
