### ISSUE TITLE
Please add RememberMe to NetworkCredentials

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/corefx#25655]
### Suggestion

Would be nice to have a `RemeberMe` property in the `NetworkCredentials` class, to make it easier to use as a standard username and password DTO unit.

### Proposed API

Add a `bool` or `bool?` property named `RememberMe` to the `NetworkCredential` class, to make it easier to attach this piece of info with the request.

### Motive

In the client side it will make it easier to use the `NetworkCredential` class as a DTO from the UI/ViewModel or some other high layer in the app down to the DAL and embedded in the request, and in the server side to be able to store cookies accordingly.
Not something that will always be used, but something that's many times worth sitting there.

**Comment by karelz** [comment]
What should it do? Your PR exposes just a field for RW. Why cannot be stored outside of the
Please do not submit PRs for new APIs, until they are approved. Also, please fill the [formal API proposal](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md) first with API shape, example, motivation, etc.

**Comment by JonHanna** [comment]
I don't think such a field belongs there.

A network credential identifies an agent and offers proof that they are who they claim to be, which preferences don't fit naturally *in* though they sometimes do fit *beside* that.

Indeed the whole point of "remember me" is to not need to use the credentials.

**Comment by weitzhandler** [comment]
I merely requested this for convenience, so we can use the `NetworkCredential` as a general credentials DTO.

**Comment by JonHanna** [comment]
I don't see why the handling of "is this someone I know" would care whether someone wants to later bypass that. I don't see why the credential needn't be opaque to the handling of setting that if they are use a different authentication (how ever the "remembering" is implemented) scheme next time.

I'm not sure what type would be best for this either. `TimeSpan` seems reasonable (`Zero` for don't remember, the time limit itself for "remember me for…" and `MaxValue` for simple boolean do/don't), but I'm not sure there won't be people having to pass their "remember me" beside an object that has a "remember me" field, because they need something beyond that.

**Comment by davidsh** [comment]
Thank you for submitting this suggestion.  After review by the .NET design team and the community of .NET developers including comments here, the feedback is that this type of property/data is not appropriate for the NetworkCredential class.  It would be better suited to a data type outside of this class where that data type uses the NetworkCredential or ICredentials interface.
