### ISSUE TITLE
PlinqModeTests failing in outerloop

### ISSUE THREAD

**Issue by mmitche** [dotnet/corefx#2569]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_outerloop_windows_release/536/

Test.PlinqModesTests.WithExecutionMode(labeled: Partitioner, count: 1024, operation: TakeWhile+Select+ToArray, mode: ForceParallelism)
Test.PlinqModesTests.WithExecutionMode(labeled: Partitioner, count: 1024, operation: TakeWhile+Select+foreach, mode: Default)
Test.PlinqModesTests.WithExecutionMode(labeled: Partitioner, count: 1024, operation: Take+Select+foreach, mode: Default)

**Comment by stephentoub** [comment]
cc: @Clockwork-Muse

**Comment by Clockwork-Muse** [comment]
@mmitche , @stephentoub - I can get this to repro on my machine for `Take+Select+foreach` by _increasing element count_ to `1024 * 2 - 3`, and "fix" it by adding one to the number taken (although it's for `ParallelEnumerable.Range` instead, for whatever reason).  I can't get either the partitioner or `TakeWhile` to repro (not without hitting OOM first).  So I'm guessing the tests are being run with only two threads available (as opposed to my four).  The part that's failing requires the process to be single-threaded for 30 seconds.  I'd rather not increase that any further, although I'm tweaking the setup just slightly there (so that _any_ thread, not just the second one, can unlock it).  So one solution might be to increase the number of elements taken, although that doesn't help with `TakeWhile`.  I want to poke into a couple of other things first, though.

Can I claim a test-infrastructure bug?  Like before when this test was deadlocking, this is brittle because other tests are running at the same time (and thus consuming threads).  Oh, sure, the other PLINQ tests have to run in sequence (and presumably are), but we're running multiple other test packages at the same time.  List appears to include:

 > System.Runtime.InteropServices.Tests
System.Threading.Tests <- this might be a problem...
System.Xml.XPath.XDocument.Tests

(this is all stuff that started after the PLINQ tests.  There's a few other things discovered in that time, but not listed as started in the logs.)

**Comment by stephentoub** [comment]
I'll take a look...

**Comment by Clockwork-Muse** [comment]
Okay, able to get `TakeWhile+Select` to repro (...aaannd for more source types, too), by decreasing the percentage of elements chosen (previously it was grabbing everything).  Placing the verifier inside `TakeWhile` (instead of `Select`) yields fewer failures, and at many fewer elements, leading me to believe we're actually running afoul of partitions - that is, the process would be multi-threaded, but the rows chosen fit in one partition (and it's range partitioned, presumably), and the rest never get run.  Because `Select` doesn't re-partition anything, if the percentage of rows fits in the first partition then `Select` only gets one partition, and thus one thread.

@stephentoub - recommendations?  I can increase the percentage of rows taken (this now feels less like the 'wrong' solution, but still hacky).  Not going to help if we still only get a single thread, and may run afoul of partitions regardless.  Ah, the perils of attempting to observe internal state...

**Comment by stephentoub** [comment]
Thanks, @Clockwork-Muse.

I took a look and the problem is indeed assumptions about how partitioning will happen that doesn't hold across the queries and data sources being used.  I've also been nervous about the blocking in the ParVerifier since it was added.

I have a fix locally which I'll put out a PR for.  I've changed the test to just run against data sources that do fixed partitioning, and I've changed the verifier to track current task IDs rather than blocking and verifying that two threads are actually running in parallel.  While this isn't perfect validation (the tasks could run sequentially rather than in parallel), I believe it's good enough to meet the spirit of the test while also allowing this to be inner loop and avoiding these kinds of issues in this test in the future.

**Comment by Clockwork-Muse** [comment]
@stephentoub - k, thanks!
I'd also come up with a (mostly) non-blocking version using `ThreadLocal`s (and an interlocked counter), but whatever works.

...do you think we need to worry about some of the other tests that deliberately block?  eg, the `WithDegreeOfParallelism` test that issues a barrier to confirm all threads are created?  Well, it's explicitly creating its partition count, so it's probably fine, but I'll do a pass over everything to look more at assumptions.

<hr />
After looking at the underlying operator, I also had fun writing an index-is-Correct enumerator that didn't require the buffers.  I'm curious about the buffers, though - there's one per partition, plus the shared (and locked) index one.  Would it be worth it to investigate memory savings possible by just adding to the shared array (given we lock it anyways), or the struct overhead, shared memeory, or whatever would be too big a cost?
