### ISSUE TITLE
In-place Array.Resize

### ISSUE THREAD

**Issue by MarcinJuraszek** [dotnet/corefx#25704]
Is there anything blocking us from providing in-place `Array.Resize` experience when the new size is smaller than the current size of the array? It would leave empty space in the heap, but that would be fixed the next time GC compaction runs.

**Comment by svick** [comment]
What happens when the array is concurrently iterated in a loop? The JIT often performs bounds checking only once before the loop. If the size of the array changed while in the loop, it could result in memory corruption.

I have created a somewhat related issue: https://github.com/dotnet/coreclr/issues/11686, but that's mostly about increasing the size of the array.

**Comment by jkotas** [comment]
> Is there anything blocking us from providing in-place `Array.Resize`

- The operation would be unsafe. Some other thread can be accessing the array that is getting resized. We prefer to not add unsafe operations to .NET.

- The current GC requires the heap to be walkable (be able to go from one object to one that follows) at all times by looking at the object size. The GC can be walking the heap on the background thread in parallel with the resize operation. Hard to sychronize background GC heap walk with Array.Size without performance penalty.

- The GC requires object size to be a certain minimal size. Shrinking e.g `int[]` by a single element would not be possible since the minimum object size is 24 bytes currently (on 64-bit platforms), but single int is just 4 bytes.
