### ISSUE TITLE
.Net Core cryptography 

### ISSUE THREAD

**Issue by albertolo** [dotnet/corefx#25733]
I want to sign a xml file with net core 2 

```c#
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Security.Cryptography;
    using System.Security.Cryptography.X509Certificates;
    using System.Security.Cryptography.Xml;
    using System.Security.Cryptography.Pkcs;
    using System.Text;
    using System.Threading.Tasks;
    RSACryptoServiceProvider rsa = OpenKeyFile(filename, pPassword);
    RSAParameters rsaParameters = rsa.ExportParameters(true);

    X509Certificate cert = new X509Certificate(pCerFile);
    KeyInfoX509Data keyData = new KeyInfoX509Data(cert);

    string X509SerialNumber = (System.Text.Encoding.ASCII.GetString(cert.GetSerialNumber())).Reverse();
    string X509IssuerName = cert.Issuer.RemoveDiacritics();
    
    X509IssuerSerial xserial;
```
The X509IssuerSerial  declaration show the following error: 
The type name 'X509IssuerSerial' could not be found in the namespace 'System.Security.Cryptography.XML'. 
This type has been forwarded to assembly 'System.Security.Cryptography.Pkcs

The documentation shows that I should be in the System.Security.Cryptography.Xml namespace. 

Is the other way should I use? 

Thanks
Alberto Lopez

[EDIT] Add C# syntax highlighting by @karelz

**Comment by bartonjs** [comment]
You may need to add a reference to the `System.Security.Cryptography.Pkcs` package, but you shouldn't need any reference to that namespace in a using statement.

**Comment by albertolo** [comment]
Hi, I already tried that without success. 

The documentation says its in the  System.Security.Cryptography.Xml package
![image](https://user-images.githubusercontent.com/1964766/33673955-d01982c0-da73-11e7-8c3a-ebab04b0f537.png)

**Comment by bartonjs** [comment]
@albertolo The documentation says it is in the `System.Security.Cryptography.Xml` **namespace**.

https://apisof.net/catalog/System.Security.Cryptography.Xml.X509IssuerSerial shows that it is in `System.Security, Version=4.0.0.0, PublicKeyToken=b03f5f7f11d50a3a` for .NET Framework (4.7.1) and `System.Security.Cryptography.Pkcs, Version=4.0.3.0, PublicKeyToken=b03f5f7f11d50a3a` for .NET Core (2.0).

It ended up in a nuget package other than one named for its namespace because the type is shared between EnvelopedCms (which was added for .NET Core 1.0) and SignedXml (which was added for .NET Core 2.0).

**Comment by bartonjs** [comment]
Since there hasn't been any followup, closing the issue.  If something's still not working, feel free to reply.
