### ISSUE TITLE
SocketAsyncEventArgs returns null when accessing buffer then throws when trying to set BufferList

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/corefx#25782]
We have the following code now throwing `SR.net_ambiguousbuffers` after https://github.com/dotnet/corefx/pull/25402

```
if (_eventArgs.Buffer != null)
{
    _eventArgs.SetBuffer(null, 0, 0);
}

_eventArgs.BufferList = GetBufferList(buffers); // throws 
```

The reason is we do `_eventArgs.SetBuffer(buffer); // buffer is Memory<byte>` earlier, then when checking if `_eventArgs.Buffer` is null it returns null since the `_bufferIsExplicitArray` was set to false when using `Memory<byte>`

**Comment by BrennanConroy** [comment]
@stephentoub @halter73

**Comment by stephentoub** [comment]
> The reason is we do _eventArgs.SetBuffer(buffer);

It sounds like the bug is that you're using the new _eventArgs.SetBuffer(Memory) but then still expecting _eventArgs.Buffer to be non-null.  With the change in your code to use _eventArgs.SetBuffer(Memory) rather than _eventArgs.SetBuffer(byte[], int, int), your code that checks _eventArgs.Buffer should also be changed.

**Comment by halter73** [comment]
I see. I didn't see until now that SocketAsyncEventArgs.MemoryBuffer got added. The current behavior seems fine then. We can close this, right @BrennanConroy?

**Comment by BrennanConroy** [comment]
Yeah it was just a confusing API

**Comment by stephentoub** [comment]
Thanks.
