### ISSUE TITLE
Use consistent test reporting api to record remote server failure in networking tests.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#25892]
One such method was proposed in this PR: #25879 

Several opinions on the thread was voiced:

1. What's the motivation of doing this, does this add value or only adds more clutter - @davidsh  @wfurt 
2. Use xunit apis for the same - proposed by @wfurt

**Comment by Priya91** [comment]
Related to issues like #25878 , where the ssllabs went down for 3 days, and the tests were failing due to unavailability of remote server.

**Comment by Priya91** [comment]
cc @karelz @wfurt @davidsh

**Comment by wfurt** [comment]
Can we replicate somehow functionality of ssllabs internally? I would expect that for certificate handling tests and other ssl features the IO/real networking does mot matter that much.
(what I'm trying to get is if there is stong motivation to use this particular site)

**Comment by Priya91** [comment]
> Can we replicate somehow functionality of ssllabs internally?

We already have loopback tests that perform the same testing, but the comment on the code says, 

```
// This test is logically the same as the above test, albeit using remote servers
// instead of local ones.  We're keeping it for now (as outerloop) because it helps
// to validate against another SSL implementation that what we mean by a particular
// TLS version matches that other implementation.
```

**Comment by karelz** [comment]
@wfurt let's treat that as a solution to particular problem.

**Problem:** In general we have bunch of external servers. They are sometimes unreliable.
**Goal:** I would like to have a way that test failures which are likely caused by the remote server unresponsivness are clearly marked in test results -- with special exception and/or text.
It will make triaging of test failures easier by ANYONE - we will be able easily filter out internet hiccups, while not losing information that tests fail in a row (which may indicate problems with the remote server we may need to adjust for).

**Comment by davidsh** [comment]
I was planning to move away from ssllabs.com and set up Azure servers for that.

Loopback is not always a good idea especially for ssl protocol tests because of caching issues w/ loopback in SCHANNEL on Windows etc.

**Comment by karelz** [comment]
I think we need the same detection of unreliable external/remote server even for the Azure servers.
It will make everyone's life MUCH easier.
