### ISSUE TITLE
Environment.OSVersion returns 6.2.9 in Windows 10

### ISSUE THREAD

**Issue by RockyTV** [dotnet/corefx#2602]
I don't really know if this issue should be reported here, but when using Environment.OSVersion on Windows 10, it returns the same version as Windows 8.

**Comment by weshaggard** [comment]
I assume this in reference to the full .NET Framework as we don't support Environment.OSVersion in .NET Core, partly because of this very reason. The windows team has decided to start lying about the OS version when asking about it via their APIs because so many applications are written badly and break when the version number changes. So the fact that the version number is unchanged is by design. I believe you can set some property in your application manifest to say I'm really a Win10 application and it will give you the correct version number, but I don't remember exactly what that property is.

So this isn't a bug in the .NET framework as we just make a call to the windows OS to get this value.
