### ISSUE TITLE
Intermittent PLINQ test deadlock on Linux

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#2607]
I saw this once on my machine and here it has happened in CI: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/1460/console

**Comment by nguerrera** [comment]
I will try to repro without my change and investigate if it's in fact something in #2606 that can cause this.

**Comment by Clockwork-Muse** [comment]
@nguerrera - I'd be interested in knowing what's causing the deadlock, since I've been maintaining most of the code.  Unfortunately I can't test against Linux myself.

There's at least one test that states that it can [straight-up deadlock](https://github.com/dotnet/corefx/blob/d9ad8dc965d5c1b57eb0942b164953fddaf021a9/src/System.Linq.Parallel/tests/WithCancellationTests.cs#L221-L247) (apparently, I don't think I had it happen to me...), although it may be just a regression comment.

There's a couple of other tests that are regressions for deadlock situations, although I'm not aware of any *nix-specific behavior in PLINQ.

I rather wish we could get the output of any blocked xunit threads when this sort of thing occurs.  Unfortunately it appears that xunit doesn't build the testResult file incrementally, so we don't even know how far along it was.

**Comment by nguerrera** [comment]
I think that's referring to the issue before it was fixed and that's checking for regression. I'll see if I can get a dump of all threads. There's nothing Linux specific in PLINQ itself that I know of, but it could be due to an issue in Threading, or possibly coincidence that I've only seen it on Linux.

**Comment by nguerrera** [comment]
I have not see this for a long time, so assuming #2612 fixed it and we can reopen if there's a re-occurrence.
