### ISSUE TITLE
Configuration - Invalid file paths

### ISSUE THREAD

**Issue by saluton-mundo** [dotnet/corefx#26126]
To reproduce create a pfx file and add it your machine. Make a note of where you hold it on the file system. 

For simplicity I just created a Test.pfx within a directory named "Test" on my machine's D drive. I inspected the directory permissions and made sure the read access is permitted. I opened a new Project targeting Core 2.0.1 with Visual Studio 2017 running as administrator (full env details at the end)

Add a section to your config file (appsetting-{env}.json as follows: 

`"CertificateConfig": {
           "CertificatePath":"D:\\Test\\test.pfx",
           "CertificatePassword":"secret"
  }`

Create a strongly typed POCO CertificateConfig.cs with a public string property named "CertificatePath" with get/set. Another property for the password in the same way. 

Then in your Startup.cs do the necessary Configuration binding to IOptions as follows: 

`services.Configure<CertificateConfig>(options => Configuration.GetSection("CertificateConfig").Bind(options));`

Don't forget to add the `services.AddOptions();` to Startup.cs within `void ConfigureServices(IServiceCollection services)` method. 

Now create a simple Controller (or a method within a separate service layer etc) and inject the `IOptions<CertificateConfig> config` into the constructor. 

Now if you did the following: 

` X509Certificate2 certificate = new X509Certificate2(config.Value.CertificatePath, config.Value.CertificatePassword);`

you should get an exception saying the file path is invalid. 

How are you meant to store file paths within the JSON config files? 

If I hard code a string as follows:

`string path = @"D:\Test\test.pfx";` 

it works flawlessly. 

The same result is present if you use `File.Open` or try to pass a `FileInfo` object instead of a filepath. 

I can't use \ as a value within a json config file and \/ would result in an equally invalid file path. 

I get that Core is meant to be OS agnostic but how can supply a file path in a config which satisfies the separator without using `Path.DirectorySeparatorChar`

Any help would be appreciated. 

ENVIRONMENT
================
Microsoft Visual Studio Community 2017
Version 15.5.2
VisualStudio.15.Release/15.5.2+27130.2010
Microsoft .NET Framework
Version 4.6.01038
assemblyref://Microsoft.NETCore.App (2.0)

**Comment by saluton-mundo** [comment]
![image](https://user-images.githubusercontent.com/7760994/34533910-16f0f7fe-f0b4-11e7-8c30-b4e4d9d4cae2.png)

Thanks for the response. Perhaps I am doing something silly here but a / in my case results in 

 'The filename, directory name, or volume label syntax is incorrect'

and my config simply has a strongly typed config class with a string with a value of "‪C:/Test.pfx"

**Comment by Clockwork-Muse** [comment]
:shrug: 
Don't know what to tell you there, other than "double check the value under debug".  Maybe you have errant non-valid whitespace or something.  Works just fine, including under vanilla .NET Framework.

**Comment by bartonjs** [comment]
@karelz This doesn't really have anything to do with security/certificates; it's more a question for whatever reads the configuration.

**Comment by karelz** [comment]
@bartonjs ok, can you update the area path then?

**Comment by bartonjs** [comment]
@karelz I don't know where the config stuff comes from.  I was hoping you would, and that you'd update the path :).

**Comment by karelz** [comment]
Oh, the repro is pretty confusing - why does it involve `X509Certificate2` when the problem is in reading json config file?
I assume you get unexpected values even if you just print the value to console or check it under debugger. Or if you use any other `File` API.

Check your configuration file, JSON syntax. If you think the JSON reader has a bug, ask on their repo under https://github.com/aspnet (that's where `IOptions` lives - assuming it is where the value comes from).

**Comment by saluton-mundo** [comment]
I've altered the issue title. I've been able to replicate the issue with File.Open and ReadAllBytes. 

Created an example project, [https://github.com/saluton-mundo/config-path-example](https://github.com/saluton-mundo/config-path-example)

Thanks to all for taking the time to read my reports. It's such a simple thing I;m trying to do here and I fear I may be doing something silly.

**Comment by saluton-mundo** [comment]
@karelz do you think you could reopen and assign it to the appropriate area path? I have no idea which corefx team is dealing but the issue is active. 

If you slap a breakpoint on line 20 in `CertificateService.cs` within the project I created for this issue you can inspect the value which _should_ work. Yet I get a path exception. 

Obviously create a Certificate.txt and store it on your file system away from the project's directory and set the path in the appsettings.json to that. 

Let me know if you need anything else.

**Comment by karelz** [comment]
@saluton-mundo per your description, it seems you have troubles to retrieve value from json file, is that not the case?
That part is not in CoreFX, but either problem of your json file, or in json parser / the API wrapped around it by ASP.NET (https://github.com/aspnet). Disclaimer: I am not familiar with `IOptions` and ASP.NET configuration system myself.

If you think that CoreFX APIs have problems, then it would be best to create a minimal repro (console app) that shows which path values it can't handle (without involving json, ASP.NET, etc.).
Given that you said it works fine with hardcoded value, I assume it is not that case and that the problem is rather in the phase1 "retrieving correct value from json/somewhere". Let me know if that is not the case.
