### ISSUE TITLE
System.IO.Packaging 4.4.0 in .NET Framework depends on .NETStandard.Library

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#26129]
@msmolka commented on [Thu Aug 31 2017](https://github.com/dotnet/core/issues/919)

# System.IO.Packaging 4.4.0 in .NET Framework depends on .NETStandard.Library

I'm trying to upgrade System.IO.Packaging in my old project .NET Framework 4.6.2  from version 4.3. However it tries to install a lot of useless dependencies already available inside framework, because it depends on  .NETStandard.Library 1.6.1+

---

@svick commented on [Thu Aug 31 2017](https://github.com/dotnet/core/issues/919#issuecomment-326272735)

Interesting. That package has two variants: one for .Net Standard 1.3 and one for .Net Framework 4.6. But both depend on `NETStandard.Library`. I don't think that's a common pattern and I don't know why does that dependency exist.

On the other hand, those "useless" packages should not cause any issues. And they're even less visible if you use the new `<PackageReference>` instead of `packages.config`.

---

@msmolka commented on [Thu Aug 31 2017](https://github.com/dotnet/core/issues/919#issuecomment-326285744)

@svick `<PackageReference>` is not a option. I have old not Core project. I need this reference to use OpenXml nuget package which relies on Packaging one. Also it is problem because I have a lot duplicate dependency errors.

---

@svick commented on [Thu Aug 31 2017](https://github.com/dotnet/core/issues/919#issuecomment-326311082)

@msmolka

> `<PackageReference>` is not a option. I have old not Core project.

 You can use `<PackageReference>` in .Net Framework projects too.

> Also it is problem because I have a lot duplicate dependency errors.

What exactly are the errors?

---

@msmolka commented on [Thu Aug 31 2017](https://github.com/dotnet/core/issues/919#issuecomment-326331093)

@svick are you sure:
based on that: [Microsoft Docs](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)

> At present, package references are supported in Visual Studio 2017 only, for .NET Core projects, .NET Standard projects, and UWP projects targeting Windows 10 Build 15063 (Creators Update).

About the error I cannot reproduce it right now

---

@svick commented on [Thu Aug 31 2017](https://github.com/dotnet/core/issues/919#issuecomment-326341432)

@msmolka Yes. If I set PackageReference as the "Default package management format", then I'm able to use `<PackageReference>` in a brand new .Net Framework project in VS 15.3.

I think the docs are out of date, so I opened https://github.com/NuGet/docs.microsoft.com-nuget/issues/443.

---

@Petermarcu commented on [Tue Oct 10 2017](https://github.com/dotnet/core/issues/919#issuecomment-335670260)

@terrajobst 

---

@Petermarcu commented on [Fri Oct 13 2017](https://github.com/dotnet/core/issues/919#issuecomment-336547379)

I'm going to close this issue for now. Let us know if more follow up is needed.

---

@Sc0tTyXL commented on [Tue Oct 31 2017](https://github.com/dotnet/core/issues/919#issuecomment-340780847)

We still have an issue where is tries to load .NET Standard in a .NET Framework application. We do not want to be dependent on Standard, could somebody please fix this error? There shouldn't be a dependency!

We cannot downgrade because the previous version of the package (https://www.nuget.org/packages/DocumentFormat.OpenXml/) that is dependent on this package has a bug (we ourselves don't use this package).

---

@JCPuerto commented on [Tue Dec 19 2017](https://github.com/dotnet/core/issues/919#issuecomment-352805002)

Updating to 4.4.0 is causing errors in the Visual Studio Team Services Build:

`Error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\packages\NETStandard.Library.2.0.1\build\NETStandard.Library.targets
`

Since it's adding some extra lines to the web.config:

```
  <Import Project="..\..\..\packages\NETStandard.Library.2.0.1\build\NETStandard.Library.targets" Condition="Exists('..\..\..\packages\NETStandard.Library.2.0.1\build\NETStandard.Library.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\..\..\packages\NETStandard.Library.2.0.1\build\NETStandard.Library.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\..\packages\NETStandard.Library.2.0.1\build\NETStandard.Library.targets'))" />
  </Target>
```

So please remove that dependency.

Thank you!

---

@msmolka commented on [Wed Jan 03 2018](https://github.com/dotnet/core/issues/919#issuecomment-355008349)

@Petermarcu Could you reopen this issue? My project is using .NET Framework 4.7.1 which is compatible with .NETStandard 2.0, So there is no need to install tens of dependencies, but because of this bug it is painful with deployment. 
I'm considering this as bug, because no other package has such strange dependency.
Even in latest alfa version this dependency exists. And I cannot find reason for that.

I've tried <PackageReference> but gave up after 5 hours. I have some incompatible msbuild references, which are not working. And simply don't want to create workarounds for bugs.
  

---

@Petermarcu commented on [Wed Jan 03 2018](https://github.com/dotnet/core/issues/919#issuecomment-355072351)

@weshaggard @terrajobst do you have any insight on why this package is "special"?

**Comment by weshaggard** [comment]
For tracking purposes https://github.com/dotnet/corefx/issues/25171 is similar in nature in that more dependencies are showing up because we switched to referencing NETStandard.LIbrary package instead of the individual packages. 

@JCPuerto it looks like that error is a different issue, it appears as though a restore was not done. If you still have the issue please file a separate issue and I can try to help you with it.

@msmolka I'm trying to understand the issue you are hitting can you please give more details on the errors or perhaps create a repro project demonstrating your issue for me to take a closer look at? While I do think you might be seeing more package dependencies I would expect everything to still work with the newer System.IO.Packaging package.

**Comment by msmolka** [comment]
@weshaggard my issue is related to create workarounds for multiple binding issues. I cannot migrate to `<PackageReference>`, because some of my packages are incompatible (MsBuild ones). Also migrating is big pain. I've spend 5 hours to do that, and still was hit with different errors, and losing references by VS.

I'm using standard .NET Framework MVC 5 application. I've recently successfully migrated to .NET Framework 4.7.1 which is compatible with .NETStandard 2. And adding this package is adding multiple older references, that again are causing version differences and requires a lot of binding redirects. 

It is big pain to add this single one dll.

**Comment by weshaggard** [comment]
Thanks for the info @msmolka. I agree the extra dependencies may cause some extra binding redirects to be generated but that should be done automatically by the tools, is that not happening for you? 

We will look at what options we have to reduce the package dependency graph.

**Comment by weshaggard** [comment]
@msmolka I did a little more investigation and I released that you don't even need this package to use the System.IO.Packaging APIs if you are targeting .NET Framework 4.7.1 as they already exist in the platform. You would only ever need to reference this package if you are writing a .NET Standard Library or you are consuming another .NET Standard Library that uses these APIs. So for you I would start with just removing this package completely and see if everything still works.

Assuming you still need this package there is a workaround to help clean-up the dependencies, given you targeting a .NET Standard 2.0 compatible platform (which .NET 4.7.1 is), which is to reference the latest .NET Standard library package before referencing System.IO.Packaging.

So assuming you can easily rollback and start from a clean state please do the following:
1. Install latest NETStandard.Library package (current 2.0.1) into your project. This will install both NETStandard.Library and Microsoft.NETCore.Platforms packages, which for your project should contribute no new assemblies, but will eliminate package closures.
2. Install latest System.IO.Packaging package. When looking at the its dependencies it will see NETStandard.Library 1.6.1 as a dependency and nuget will realize you already have the 2.0.1 version installed which is higher version and thus not install it or it's dependencies.

This should get you to a state where you only have one new binary in your output which is System.IO.Packaging.

All that said I do believe some of this can be fixed in the package itself which I'm going to use this issue to track fixing.

**Comment by msmolka** [comment]
@weshaggard I'm referencing OpenXml library, which references IO.Packaging.
Like I mentioned, I have standard .NET ASP application, not Core.
IO.Packaging in version 4.3.0 did not referenced .NET standard library. But from version 4.4.0 started.

 I will try your advise tomorrow

**Comment by weshaggard** [comment]
The extra dependencies for net46 no longer exists now. See our latest nightly at https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.IO.Packaging/4.5.0-preview1-26108-02.

**Comment by twsouthwick** [comment]
@weshaggard The NuGet package still has a dependency on `System.IO.FileSystem.Primitives` for net46, but when I look at the dll, there is no reference to that library. Is there some reason this is required even though everything is just forwarded to `WindowsBase`?

**Comment by weshaggard** [comment]
@ericstj could you take a look?

**Comment by ericstj** [comment]
That's normal since the reference assembly [depends on it](https://github.com/dotnet/corefx/blob/master/src/System.IO.Packaging/ref/System.IO.Packaging.csproj#L31).  We must preserve the dependency so that folks compiling against the portable ref get all the facades.
