### ISSUE TITLE
Improve System.Data.SqlClient Error messages

### ISSUE THREAD

**Issue by eschneider999** [dotnet/corefx#26121]
I would like to improve some error message, why it has never been done "Who knows"

example: String or binary data would be truncated.

Include the column name or parameter name would be helpful right?

There's a few others that have been driving us devs nuts for years...

Currently I'm targeting Sql Client and I think I have a fix for it, but can't figure out how to test it. The tests in the sln are strange to me, have no idea how to run them. Can't seem to reference the built dll either.

Don't they have regular unit tests?

I'm look for a way to write a unit test for the change I did and test the new code.

Thanks,
Eric

**Comment by eschneider999** [comment]
tried the f5 run of System.Data.SqlClient.Tests:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'D:\Dev_Temp\corefx-master\bin\AnyOS.AnyCPU.Debug\RemoteExecutorConsoleApp\netstandard\RemoteExecutorConsoleApp.exe' could not be found	System.Data.SqlClient.Tests	D:\Dev_Temp\corefx-master\src\System.Data.SqlClient\tests\FunctionalTests\CSC	1	Active

**Comment by danmosemsft** [comment]
@eschneider999 did you first do "build" and "build-tests" from the root of corefx? You need to do that once before any builds will work at project level.

**Comment by danmosemsft** [comment]
If you haven't already, take a look at https://github.com/dotnet/corefx/tree/master/Documentation/building particularly https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md

**Comment by danmosemsft** [comment]
By the way, I think in general the improvements to error messages that you describe would be welcomed. It is consistent with what we are doing elsewhere to add parameter values into error messages eg for IO errors. I suggest putting up a small PR first to gauge area owner feedback.

**Comment by eschneider999** [comment]
I did the batch build from the root, also the tools set-up thing prior, but still having issues.

**Comment by danmosemsft** [comment]
Does it work from hte command line? ie in System.Data.SqlClient\tests, do `msbuild /t:buildandtest`

**Comment by danmosemsft** [comment]
Or you could do "nuke from orbit". From the root
```
git reset --hard
clean -all
build
build-tests
```

**Comment by bgribaudo** [comment]
@eschneider999, improved error messages would be _really_ nice, particularly in the example case you mention!

However, I think it's going to be challenging to pull this off for many of the messages because they are generated by SQL Server, not the client. The client is simply reporting what the server told it. 

In the case of the "String or binary data would be truncated" error, there's an [active Connect item](https://connect.microsoft.com/SQLServer/feedback/details/339410/please-fix-the-string-or-binary-data-would-be-truncated-message-to-give-the-column-name) that's almost 10 years old asking for this SQL Server error message to be improved.

**Comment by eschneider999** [comment]
Ok, I can run the test project after "build-tests", but I get a ton of thrown exceptions.

Not sure about this DB connection?
"Data Source=9ae3ff15-f214-46e0-beab-9ffc9d614b74; Integrated Security=true; Connect Timeout=1;Enlist=False"

Is there any docs on test projects?

Why don't they just use unit tests?

**Comment by saurabh500** [comment]
@eschneider999 All the errors coming to SqlClient during command execution due to bad data or bad query are sent by Sql Server and SqlClient cannot do much about these error messages. 
The messages that the client produces are more around connectivity and timeouts which if needed can be improved. 
I agree that the messages like `String or binary data would be truncated.` are frustrating, especially if you are inserting large number of rows in table with many columns. Some indication of what went wrong would be nice. 
Since this enhancement is out of scope of the client, I am closing this issue.
