### ISSUE TITLE
Convert System.Runtime.Caching project to support Unix 

### ISSUE THREAD

**Issue by KKhurin** [dotnet/corefx#26172]
This work items is to convert the project to support all platforms and to adjust the code to do the right thing without having all the functionality on all platforms.

With the current S.R.Caching.MemoryCache memory management design the main missing external piece to fully support all platforms is #25617. Once this is implemented, the cache will still likely need some "adjustments" as the way of deriving "cache memory pressure" from "memory usage" is likely to be different on Linux (or even different on different versions of Linux). This invites further design decisions whether to let the cache "translate" memory readings into memory pressure itself or to delegate this to the user code (or have both the default algorithm and an opportunity to override it)...

Until then the plan is to support netstandard but the cache will throw PNSE if the corresponding memory settings are provided on the platforms where we don't have comprehensive memory info yet.

**Comment by shar0119** [comment]
Any idea when System.Runtime.Caching will be available on NuGet?

**Comment by KKhurin** [comment]
Fixed with https://github.com/dotnet/corefx/pull/26354

@danmosemsft what needs to happen for S.R.Caching to become a stable release?

**Comment by danmosemsft** [comment]
@KKhurin there will be a refresh on Nuget when we ship 2.1 preview 1 (even though it's not part of 2.1 it's in the same branch) which will be "not long from now". Again for subsequent 2.1 pre releases, then we plan to mark it stable with 2.1 final release.

As you know it's just the marker in nuget -- we consider the code stable at this point.

Meanwhile it is on myget
https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Runtime.Caching

**Comment by danmosemsft** [comment]
I see the question was from @shar0119 . @shar0119 does that help? Is it feasible for you to consume from myget in the near term?

**Comment by shar0119** [comment]
@danmosemsft Yes, this works well for now. Thanks!

**Comment by Phrohdoh** [comment]
Unless I am misunderstanding something there are still portions of `System.Runtime.Caching` that will throw `PlatformNotSupportedException`s for `netstandard20` in `4.6.0-preview1-26801-04`.

Steps I took that lead to ^:
- Download and unzip: https://dotnet.myget.org/F/dotnet-core/api/v2/package/System.Runtime.Caching/4.6.0-preview1-26801-04
- Decompile `/lib/netstandard2.0/System.Runtime.Caching.dll` with ILSpy
- Look at `CacheItemPolicy`

```csharp
using System.Collections.ObjectModel;

namespace System.Runtime.Caching
{
	public class CacheItemPolicy
	{
		public DateTimeOffset AbsoluteExpiration
		{
			get => throw new PlatformNotSupportedException(SR.PlatformNotSupported_Caching);
			set => throw new PlatformNotSupportedException(SR.PlatformNotSupported_Caching);
		}

		public Collection<ChangeMonitor> ChangeMonitors
		{
			get => throw new PlatformNotSupportedException(SR.PlatformNotSupported_Caching);
		}

		public CacheItemPriority Priority
		{
			get => throw new PlatformNotSupportedException(SR.PlatformNotSupported_Caching);
			set => throw new PlatformNotSupportedException(SR.PlatformNotSupported_Caching);
		}

		public CacheEntryRemovedCallback RemovedCallback
		{
			get => throw new PlatformNotSupportedException(SR.PlatformNotSupported_Caching);
			set => throw new PlatformNotSupportedException(SR.PlatformNotSupported_Caching);
		}

		public TimeSpan SlidingExpiration
		{
			get => throw new PlatformNotSupportedException(SR.PlatformNotSupported_Caching);
			set => throw new PlatformNotSupportedException(SR.PlatformNotSupported_Caching);
		}

		public CacheEntryUpdateCallback UpdateCallback
		{
			get => throw new PlatformNotSupportedException(SR.PlatformNotSupported_Caching);
			set => throw new PlatformNotSupportedException(SR.PlatformNotSupported_Caching);
		}

		public CacheItemPolicy()
		{
			throw new PlatformNotSupportedException(SR.PlatformNotSupported_Caching);
		}
	}
}
```

Yet if we look at [current master of corefx's `CacheItemPolicy`](https://github.com/dotnet/corefx/blob/7534eddc90495eac1d7276b740367db0cd04fdc4/src/System.Runtime.Caching/src/System/Runtime/Caching/CacheItemPolicy.cs) we see that it is implemented.

Why are these two different?

**Comment by Phrohdoh** [comment]
Note that the `nuspec` download via myget contains the following:

```xml
    <dependencies>
      <group targetFramework="MonoAndroid1.0" />
      <group targetFramework="MonoTouch1.0" />
      <group targetFramework=".NETFramework4.5" />
      <group targetFramework=".NETCoreApp2.0">
        <dependency id="Microsoft.NETCore.Platforms" version="2.0.0" />
        <dependency id="System.Configuration.ConfigurationManager" version="4.6.0-preview1-26801-04" exclude="Compile" />
      </group>
      <group targetFramework=".NETStandard2.0" />
      <group targetFramework="Xamarin.iOS1.0" />
      <group targetFramework="Xamarin.Mac2.0" />
      <group targetFramework="Xamarin.TVOS1.0" />
      <group targetFramework="Xamarin.WatchOS1.0" />
    </dependencies>
```

Which, I believe, means it should not generate a "turd assembly" as @safern puts it [here](https://github.com/dotnet/corefx/pull/26354#issuecomment-401140341) due to the tfm of the decompiled assembly being `netstandard2.0`.

Please correct me if I am wrong.

**Comment by safern** [comment]
> Will the 'final stable' package contain the implementation for CacheItemPolicy (for example)?

For .netstandard the implementation will always be a turd assembly for this package since it is not supported in UAP. However, we give a .netstandard reference assembly with all the available apis for you to be able to reference this package and build your netstandard library, however this is a tfm and runtime specific assembly, so that means that the implementation to be chosen should be depending on what your current TFM and runtime is.

For example if you look at the contents of the package, under runtimes/netcoreapp2.0/ you will see a `win` and a `unix` folder, each one containing the implementation for the platform that you're running on when using .NETCoreApp2.0 or later. 

For net45 you'll see a folder with a `.` file in it, meaning that if you're running in net45 or later it should take the implementation that is shipped within the .NET Framework. This being said, if your netstandard library depends on a nuget package that is netstandard compatible, you should never publish your application and redistribute the layout of the application with all the dependencies since you could get an implementation that is "generic" and it might work in some cases, but not when you hit implementation details that are runtime specific or tfm specific. For example if you where to distribute a netstandard library by publishing it with its dependencies and try to consume it from a .NET Framework application, you'll most likely end up having a compilation error saying you the same type in multiple assemblies (inbox assembly and netstandard assembly pulled as a dependency from your library).

The best practice to distribute a .NET Standard library is to only be the library and consume it through a project reference or a nuget package if it depends on an OOB package that is not shipped within the framework (example .NET CoreApp in this case), that way you will leave the resolution of dependencies to the framework depending on the runtime.
