### ISSUE TITLE
No match was found for the specified search criteria and package name 'System.Runtime.Serialization.Primitives'

### ISSUE THREAD

**Issue by zhenlan** [dotnet/corefx#26222]
@StingyJack commented on [Tue Jan 02 2018](https://github.com/dotnet/wcf/issues/2469)

This was working recently, but now its breaking builds as the package cannot be downloaded. 

I tried to push a copy to our private nugetserver repo, but it barks about the nuspec being somehow invalid 
```
 Process information: 
    Process ID: 5016 
    Process name: w3wp.exe 
    Account name: IIS APPPOOL\ASP.NET v4.0 
 
Exception information: 
    Exception type: InvalidOperationException 
    Exception message: 'System.Runtime.Serialization.Primitives' already has a dependency defined for 'System.Runtime'.
   at NuGet.Manifest.ValidateDependencySets(IPackageMetadata metadata)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.ZipPackage.EnsureManifest(Func`1 manifestStreamFactory)
   at NuGet.ZipPackage..ctor(Stream stream)
   at NuGet.Server.Publishing.PackageService.CreatePackage(HttpContextBase context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
``

**Comment by StingyJack** [comment]
I was able to get around this by removing the package and pointing code to what I think is the correct reference assembly. It compiles and seems to run OK. 

FWIW. I'm not using .net core, and the package listed .net framework. Is this the correct repo?

**Comment by zhenlan** [comment]
Thanks for updating, @StingyJack. Referencing directly to full framework reference assembly is the right approach for a full framework application. This repo is for .NET Core issues only.

**Comment by StingyJack** [comment]
@zhenlan - Two things...
1) The nuget package didnt prevent me from using it in a netfx project if it was supposed to. That problem is still not addressed.
2) I logged this issue in the WCF issues list, because it was a problem with finding that package in nuget.org. You moved the issue here. If it needs to go back there or somewhere else, then please do so but issue 1 needs to be addressed.

**Comment by zhenlan** [comment]
@StingyJack, to answer your questions
1. Are we talking about `System.Runtime.Serialization.Primitives` package? Which version are you using? When it's referenced in a full framework application, all it does is to type-forward everything to full framework assembly.
2. From your call stack, it mentions only `System.Runtime.Serialization.Primitives`, which is a serialization component living in this repo. It mentions WCF nowhere. This is why the issue is moved to corefx repo. If  this is a WCF issue, can you please provide more context of what you are doing?

**Comment by StingyJack** [comment]
Yes, that package. The one with [DataContract] and other common WCF attributes. Searching for datamember finds it easily. 

It was fine for several months, and then it started giving the error specified in the issue title and causing build failures. 

I could still download it from it's web page on nuget.org, so I tried putting a copy on our local nuget repo and got the stack trace above in the event log.

**Comment by zhenlan** [comment]
DataContract serializer can be used independently from WCF. Anyway, this is the right repo for System.Runtime.Serialization.* components.

I am wondering what has changed so you started to see this issue. You didn't mention which version of `System.Runtime.Serialization.Primitives` you are using but as you can see from nuget.org the package has not been updated for a long time (it is included in net standard since .NET Core 2.0).
https://www.nuget.org/packages/System.Runtime.Serialization.Primitives/

Normally, people reference packages in their project and package-restore will download packages. Does package-restore fail in your case? I am lack of context of what you are doing, but according to the call stack, are you calling nuget APIs and download packages from a web request? Have you updated VS recently? I wondering if it could be due to an update of nuget library you are using. You may like to post the issue to nuget repo.

**Comment by StingyJack** [comment]
Focus on the issue title more than the stack trace. That title was the error produced during package restore for this package in a tfs 2015.4 vNext NuGet Installer task, which also happened locally in my VS 15.5.2 dev env. No other packages had this issue, and I've run at least 100 builds across our codebase in the last week or so. 

Due to package ref being terribly buggy and costing us several days of lost time, everything is using packages.config. Also, its the 4.3.0 version as System.* packages before that had all kinds of componentmodel and system.net.http problems that were unresolved for months . I'm using the package as "Normally" as a .net framework library is supposed to be used.


The stack trace was from me trying to upload the package to our local Nuget.Server in an effort to work around the first problem. It's probably complaining because the server doesn't have a dependency package present on the server (which if true, kind of negates the MSFT position held in [these](https://github.com/NuGet/Home/issues/6373) two [issues](https://github.com/NuGet/docs.microsoft.com-nuget/issues/407 )

I'm pretty sure I've contacted the "package owners" via the package page, but I am not 100% positive. Its always hard to find the right place as there is not a general "map" of component to supporting team, and emails or stuff logged at devcomm stays unanswered for days if not months at a time.

> You may like to post the issue to nuget repo.
I'll leave that to you. Once they read "packages.config", requests get "closed - wont fix".

**Comment by StingyJack** [comment]
@zhenlan - its been a week. please either reopen or relocate this issue.

**Comment by StingyJack** [comment]
@zhenlan @karelz - its been more than a month now. If this issue is within your program area, please reopen this. If its not, please continue relocating it to where it needs to be.

**Comment by karelz** [comment]
I don't think the issue is actionable at this point. It is not clear what the problem/repro is, therefore we can't route it / help to solve.

I would suggest to post a clear step-by-step **minimal** repro steps that reproduce on any machine (incl. nuget package version number, starting with new simplest project - ideally console app, etc.). Clarify what is the current outcome of the repro vs. expected.
Please check that your repro steps reproduce same problem on vanilla machine (with latest VS) to rule out impact of machine settings / configuration changes.

**Comment by StingyJack** [comment]
The problem is in the title. And then described a few times, in addition to it's fallout and "descendant" bugs.

Nuget PM UI can't download a package from nuget.org. This started breaking builds one day, across several codebases that hadn't been changed. I saved a copy of the package and tried to push it to our private nuget repo, and got an error (the stack trace).

Since it's WCF related I opened the issue there, as it's the closest thing to a correct contact that I can find. 

@zhenlan moved it here.

Plenty of other actionables in here to pick from too.

**Comment by StingyJack** [comment]
*Nuget PM UI and the CLI tool that TFS build tasks use both failed to download this (and only this) package.

**Comment by karelz** [comment]
@StingyJack I can't make heads and details from your description and following comments - there is mix of several problems, incl. attempts for workaround (uploading to private nuget server), which muddy the description. It is not clear what is the primary problem and how to reproduce it (does it reproduce on new project, with which version, etc.).
As I said, in current state the issue is not actionable. We can take a look if you can provide easy step-by-step minimal repro (make it as simple and as clear as possible, leave out workaround attempts at this point).

**Comment by StingyJack** [comment]
Nuget PM UI and CLI could not download a package from nuget.org. This started breaking builds on the day it was reported, across multiple codebases that hadn't been changed. 


Adding attempted workarounds saves you from having to ask me to repeat something I may have already done.

Adding additional experiences with the same package that may help you to troubleshoot what the actual problem with the package is.

**Comment by StingyJack** [comment]
@karelz - The report was... 
> No match was found for the specified search criteria and package name 'System.Runtime.Serialization.Primitives'

Where could I possibly receive that error?  It seems kind of obvious, but it was explained again on 1/2 (Jan 2)
> This was working recently, but now its breaking builds as the package cannot be downloaded.

then again on 1/10
> It was fine for several months, and then it started giving the error specified in the issue title and causing build failures.

and on 1/11
>  That title was the error produced during package restore for this package in a tfs 2015.4 vNext NuGet Installer task, which also happened locally in my VS 15.5.2 dev env. No other packages had this issue, and I've run at least 100 builds across our codebase in the last week or so.

and on 3/4
>Nuget PM UI can't download a package from nuget.org. This started breaking builds one day, across several codebases that hadn't been changed.


@zhenlan went right to a stack trace for a secondary problem that you have and missed the title.  It happens, I'm not upset about that, everyone gets a bit of tunnel vision from time to time. I am cheesed at the feigned reading comprehension issue and followup push-off attempts after I've repeated the problem plainly.

The first was actionable enough to at least try adding the package to a project to see for yourself.  That hasn't been attempted yet from what I can tell in this conversation. 

That secondary problem is also actionable and its repro was listed as well. It has the bonus of either being a bug itself - or if its correct its pointing out another [bug](https://github.com/NuGet/Home/issues/6373).

**Comment by karelz** [comment]
@StingyJack it seems there is a significant disconnect here. You claim it is "clear" how to reproduce the problem, but honestly, I have **no clue**. (as I said above - https://github.com/dotnet/corefx/issues/26222#issuecomment-370251707)
I'll be happy to take further look / route it, but I need simple step-by-step repro steps (starting with freshly opened VS session) to be able to do that.

**Comment by StingyJack** [comment]
I had a project with this nuget package referenced that was created several months prior to this report. It had a TFS vNext build def, and compiled fine. The codebase and build def had no changes since the last time the build was run.

In prepping for some upcoming work, I ran the build on the on-prem tfs server. It got the error stated in the title. 

I tried locally in VS, and got the same error. 

Since I could not get a compile-able program at that point, and the reality being that I cant wait 5+ days for someone to get back to me I started hacking at it. It looked like something was wrong with nuget.org's feed for this package, trying from different locations and computers had the same problem. I tried to get around it first by trying to upload the package to an in house repo and not being able to, then finally by dropping the package entirely and using the regular assembly reference. @zhenlan confirmed this is what should be done anyway, so it seems like only an opportunity for strange errors like this to even offer the package for netfx. 

Today, I dont have a problem getting the package from nuget.org, but it was a problem through Jan and at least the first half of Feb. I keep VS reasonably up to date, maybe lagging a minor version, and had no problems downloading other packages from nuget.org or our private repo at that time.  

At this point I dont really care about or even seem to need that package, but there are probably a half dozen feedback/takeaways in this conversation that may benefit you both, and a few for myself as well.

This can be left closed unless you want to discuss further.
