### ISSUE TITLE
[ManagedHandler] Add equivalent of ServicePoint.ConnectionLeaseTimeout 

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#26331]
This is necessary to support DNS based routing with TTLs.  See #11224 for more details.

**Comment by stephentoub** [comment]
> This is necessary to support DNS based routing with TTLs

It seems like an alternative to that, rather than being a way to implement that.  to support DNS based routing with TTLs

**Comment by stephentoub** [comment]
(hit wrong button :)

**Comment by geoffkizer** [comment]
Yes, that's correct.

If we had proper TTL handling, we (probably) wouldn't need ConnectionLeaseTimeout.

Supporting ConnectionLeaseTimeout gives us a way to make DNS TTL-based routing work reasonably well, without actually retrieving and respecting the TTL.

**Comment by Tratcher** [comment]
Related discussions: https://github.com/aspnet/HttpClientFactory/issues/44

**Comment by Tratcher** [comment]
Also related: https://msdn.microsoft.com/en-us/library/system.net.servicepointmanager.dnsrefreshtimeout(v=vs.110).aspx

**Comment by geoffkizer** [comment]
@Tratcher What's the difference between the two?  Seems like we probably don't need both, but which is preferable for DNS TTL scenarios?

**Comment by Tratcher** [comment]
It's an artifact of the ServicePoint impelementation, you won't necessarily need both settings, but you will need to cover the end-to-end scenario.

ServicePoint internally caches DNS resolves for the given DnsRefreshTimeout. It also re-uses connections for the given ConnectionLeaseTimeout. The two are implemented separately, it doesn't drop all active connections when it does a DNS refresh, nor refresh DNS for every new connection.

Things for ManagedHandler to address:
- Periodically resolve DNS
  - Don't do it for every new connection, this causes overhead and is one more operation that could sporadically fail.
  - The resolve period should be related to the DNS TTL. Unfortunately that's not available with any of the .NET DNS APIs, nor is it clear how to get it from native the APIs. That's why ServicePoint used DnsRefreshTimeout.
  - Async DNS would be a bonus, now available on Win10.
  - Refreshing in the background rather than blocking all new connections would be nice too. It would also help limit concurrent DNS calls and smooth over sporadic failures.
  - Round robin DNS is another common request.
- Don't keep connections open forever, you won't move to the new IPs/servers. Using the DNS TTL as the connection lifetime would be one approach, if it were available. ServicePoint used ConnectionLeaseTimeout for this.

Really people expect a basic load ballancer functionality to be built in, rather than using a dedicated load ballancer intermediate.
