### ISSUE TITLE
SignedCms extensibility to support external private keys

### ISSUE THREAD

**Issue by onovotny** [dotnet/corefx#26406]
This is an issue to document: https://github.com/dotnet/designs/issues/11#issuecomment-336327669

The core issue is that there's no way to use anything other than an X509Certificate2 to provide the signatures needed within the SignedCms types. There are cases where the private key is not accessible via a CSP where the signing must be handled by a provided function. A concrete example is wanting to use SignedCms with certificates in Azure Key Vault. There is no way to do this with SignedCms today, so I have to rely on BouncyCastle for this. It is very painful/complicated to use the BouncyCastle API’s compared to doing the same thing with the built-in logic should it have the right extensibility points.

A starting proposal from the linked discussion suggests  `CmsSigner` taking an `AsymetricSignatureFormatter`. I believe that could ultimately meet the needs here.

An easy implementation to meet the Key Vault example could use the `RSAPKCS1SignatureFormatter` formatter and use a custom RSA-derived type in its `SetKey(AsymmetricAlgorithm)` method.

The hard part will be the .NET Framework implementation, which uses the `CryptMsg*` API's.  

EDIT by @krwq:

API proposal:

```diff
  namespace System.Security.Cryptography.Pkcs
  {
      public sealed partial class CmsSigner
      {
+        public CmsSigner(SubjectIdentifierType signerIdentifierType, System.Security.Cryptography.X509Certificates.X509Certificate2 certificate, System.Security.Cryptography.AsymmetricAlgorithm privateKey) => throw null;
+        public System.Security.Cryptography.AsymmetricAlgorithm PrivateKey { get => throw null; set => throw null; }
      }
  }
```

**Comment by krwq** [comment]
@bartonjs @onovotny, since we likely will need to pass certificate so that we can get signer info would it make sense to simply pass public key to `AsymmetricSignatureFormatter.SetKey` and let AsymmetricSignatureFormatter obtain private key however they want from that? (or if cert has already private key we could pass private key directly - although for consistently it makes sense to always pass public key since they could just not use that overload in this case).

**Comment by onovotny** [comment]
@krwq not 100% sure, but I'm ok passing the public cert always as I do have that. I have an impl of `RSA` that I'd want SignedCms to use:

https://github.com/onovotny/RSAKeyVaultProvider/blob/master/RSAKeyVaultProvider/RSAKeyVault.cs#L8

That implementation calls Key Vault for the signing method.

**Comment by bartonjs** [comment]
AsymmetricSignatureFormatter isn't involved in SignedCms.

My thoughts:

* Add a new constructor to CmsSigner: CmsSigner(SubjectIdentifierType, X509Certificate2, AsymmetricAlgorithm).
* During the signing operation, if an explicit AsymmetricAlgorithm object was provided use that object for signing, then verify the signature against the public key in the certificate (throw if it doesn't validate).

**Comment by krwq** [comment]
@bartonjs do you mean to verify directly after signing to check if AsymmetricSignatureFormatter implementation did the right thing?

How would passing AsymmetricAlgorithm work? I do not see it having any API like Sign or Encrypt which is needed for signing externally

**Comment by bartonjs** [comment]
> How would passing AsymmetricAlgorithm work?

Add it as a parameter to CmsSignature.Sign.  In each of the algorithm-specific resolvers you then understand how to cast it.

**Comment by krwq** [comment]
I've updated the proposal and PR to take AsymmetricAlgorithm, makes more sense after @bartonjs have explained me what's the problem with AsymmetricSignatureFormatter in CMS context

**Comment by krwq** [comment]
@bartonjs, I've talked with @morganbr offline and he has brough a point that if we have cert with RSA key we sometimes might still want to use different padding in CMS. With AsymmetricSignatureFormatter we could still do that (not the way I implemented but we could do additional formatting for DSA, ECDsa after using formatter), other option would be to create another overload with RSA padding (now or in the future) but that would be slightly confusing since it would enforce RSA key on the cert and possibly bad design in the future if someone breaks RSA and new asymmetric algorithm shows up

**Comment by bartonjs** [comment]
If a different RSA padding is used then a different OID needs to be written down, and the parameters object is very different.  It's a new scenario.  AsymmetricSignatureFormatter cannot be used with CMS.

**Comment by terrajobst** [comment]
Looks good, any reason we wouldn't expose a matching property? @bartonjs suggested to use the name `privateKey` instead of just `key`, which seems reasonable to me too.

**Comment by bartonjs** [comment]
Didn't make it for 2.2, already in 3.0
