### ISSUE TITLE
Not Stripping Auth in HttpClientHandler redirects by default

### ISSUE THREAD

**Issue by paulgmiller** [dotnet/corefx#26426]
In net 461 if a basic auth header is included using httpclient/httprequestmessage
`req.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", base64EncodedString);`

And the response of the request is redirect (say 302) then the client will automatically redirect by default but will strip the auth header from the request to the new location.
IN dotnet 2.0 on windows redirect is still automatic but the auth header is not stripped. 
This is bad beause 
1) the redirect may be a different host who shouldn't have the credentials.
2) the redirect might already have auth in the queryparams (sas token) and reject a valid request because there are now two types of auth. This is the case when querying some visualstudio.com api;s. 
You can repo this with dotnet 2 by creating a console app that queries something that will redirect and then  watching the fiddler traces.  Switching from netcoreapp2.0 to net461 will change the behavior. 
```
dotnet --version
2.1.2

```
Here's a gist that you can use to repo this. 
https://gist.github.com/paulgmiller/403904c387f7e282d611ec86abd2cb1a
Have another internal thread with visualstudio.com examples.

**Comment by Priya91** [comment]
cc @Tratcher @geoffkizer We should do this for managedhandler as well, strip auth fields on redirect.

**Comment by Tratcher** [comment]
@Priya91 you already did that last time you refactored the auth and redirects in ManagedHandler.

**Comment by paulgmiller** [comment]
Yep managed handler does it. How bad of an idea would it be to try and use the managed handler?

**Comment by rmkerr** [comment]
I've got a repro and a rough fix put together for this issue. I believe that we should be handling this in [WinHttpRequestCallback::OnRequestRedirect](https://github.com/dotnet/corefx/blob/473a4cf05c28f95d8a93b826647f755dbdec8728/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpRequestCallback.cs#L182), which gets called by WinHttp to notify us that a redirect is about to happen.

Since the headers have already been added to the request on the WinHttp side of things, we need to take the same approach as is used in [WinHttpCookieContainerAdapter::ResetCookieRequestHeaders](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpCookieContainerAdapter.cs#L48) and make the required WinHttp native calls required to remove the headers.
