### ISSUE TITLE
Adding a null value to ConcurrentDictionary using System.Collections.IDictionary interface causes exception

### ISSUE THREAD

**Issue by testfirstcoder** [dotnet/corefx#26447]
According to the code in [ConcurrentDictionary](https://github.com/dotnet/corefx/blame/master/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L1580) it is not possible to add a null value to ConcurrentDictionary using System.Collections.IDictionary interface.

Is this type checking for a value really required?

Examples: 

```c#
var key = "key";
string value = null; 
	
{
    // using ConcurrentDictionary<TKey, TValue> class
    ConcurrentDictionary<string, string> d = new ConcurrentDictionary<string, string>();
    d[key] = value; // OK
}

{
    // using IDictionary<TKey, TValue> interface 
    IDictionary<string, string> d = new ConcurrentDictionary<string, string>();
    d[key] = value; // OK
}

{
    // using IDictionary interface 
    IDictionary d = new ConcurrentDictionary<string, string>();
    d[key] = value; // ArgumentException - The value was of an incorrect type for this dictionary.
}
```

**Comment by mikedn** [comment]
Hmm, probably the intention was to prevent NREs due to unboxing null when `TValue` is a value type but the check ended up blocking all nulls. This is inconsistent with the `Dictionary` implementation:
https://github.com/dotnet/coreclr/blob/38cf93013c1dd1efc7137a6f4930cab7cc653411/src/mscorlib/shared/System/Collections/Generic/Dictionary.cs#L831-L838

**Comment by satano** [comment]
Can I take this one?

**Comment by danmosemsft** [comment]
@satano yo'ure assigned..
