### ISSUE TITLE
Span<T> GetHashCode

### ISSUE THREAD

**Issue by Ziriax** [dotnet/corefx#26449]
Currenty  `Span<T>` throws an exception when calling `GetHashCode`.

Why not just returning the `Length` of the `Span`, or fully implementing it with `RuntimeHelpers.GetHashCode(_pinnable)` and `_byteOffset.ToInt64()`?

The comment clarifies that `GetHashCode` is not implemented because `Span` cannot be boxed, but I'm using it unboxed in several classes  that implement `IEqualityComparer<T>`, and now I have to workaround this exception.

Thanks for the insight,
Peter

**Comment by mikedn** [comment]
> The comment clarifies that GetHashCode is not implemented because Span cannot be boxed

**Comment by Ziriax** [comment]
Ouch, it seems I misunderstood `Span`, I'm currently using it as a field in classes in a .NET 4.7.1 project, and according to the spec, this is not allowed, `Span` is stack-only typed... 

So I guess the .NET 4.7.1 platform implements the 'slow' span version, as all my code compiles and runs fine?

**Comment by mikedn** [comment]
> So I guess the .NET 4.7.1 platform implements the 'slow' span version, as all my code compiles and runs fine?

Hmm, you're probably using an older C# compiler that doesn't understand `ref struct` and thus doesn't prevent you from creating a field of span type. Or the span nuget package has not yet been updated to use `ref struct` for the "slow" span implementation.

Anyway, neither span implementation supports being stored outside of the stack. The fast span contains a `ref` field and these can't ever be on the GC heap. The slow span doesn't have a `ref` field but it is still problematic to use outside the stack due to the lack of thread safety.

**Comment by Ziriax** [comment]
I was using VS 2017 15.5.3, I'm now upgrading to 15.5.4.

I was using nuget package System.Memory 4.4.0-preview1-25305-02. It's pretty old, but that's the only one I found on nuget.org.

I switched to the latest build https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Memory, and indeed, now I get compiler errors when trying to use Span as a field!

Thanks so much for all the clarifications.
