### ISSUE TITLE
Support https proxy

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#26460]
It is currently not implemented:
https://github.com/dotnet/corefx/blob/b265a0f0066dbce3cf4845c25444fe85266c81d0/src/System.Net.Http/src/System/Net/Http/Managed/HttpProxyConnectionHandler.cs#L57-L60

**Comment by stephentoub** [comment]
@karelz, how is this different from https://github.com/dotnet/corefx/issues/23136?

**Comment by stephentoub** [comment]
Oh, this is the proxy server itself actually being accessed over https instead of http?

**Comment by davidsh** [comment]
fyi.  HTTPS proxies are not supported in .NET Framework HTTP stack.

**Comment by stephentoub** [comment]
> fyi. HTTPS proxies are not supported in .NET Framework HTTP stack.

Thanks, yeah, hence my confusion at the issue.

**Comment by karelz** [comment]
OK, if HTTPS proxies are not supported, our life is a bit easier. Closing as won't fix.

**Comment by stephentoub** [comment]
FWIW, if we really wanted this, the core piece of it would I expect be trivial via SslStream. But then there are likely a bunch of missing APIs, basically all of the support we have for SSL (e.g. callbacks, client certs, etc.) might also need to be exposed separately for the proxy.

**Comment by davidsh** [comment]
fyi.  There were a bunch of enterprise customers that requested HTTPS support for proxy.  This was because they wanted all possible network connections protected with TLS.  The only missing piece was the initial connection to the proxy when doing the CONNECT tunneling.

It was very costly to add this support for .NET Framework HTTP stack.  So, we didn't do it. However, that customer ended up using a different solution and used native HTTP stack Wininet.  And Wininet recently added support for HTTPS proxies.  Adding that support also required the ability to fetch the PAC file (using WPAD or explicit registration) via HTTPS schemes.
