### ISSUE TITLE
Support HttpWebRequest.GetSystemWebProxy() properly

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#26494]
Today, on .net core, the IWebProxy returned from HttpWebRequest.GetSystemWebProxy() is a fake web proxy, a sentinel value which is checked for and handled specially in the existing WinHttpHandler/CurlHandler.

See: https://github.com/dotnet/corefx/blob/6abde68de9611895fa8697fb7fc17105e906081e/src/System.Net.Requests/src/System/Net/SystemWebProxy.cs#L21

Now that we are adding real system proxy support for the managed handler, we should expose this via HttpWebRequest.GetSystemWebProxy().  This means updating the code in WinHttpHandler/CurlHandler so that the real proxy is appropriately handled.

Related: It's slightly weird that we expose this only via HttpWebRequest.  Ideally this would be factored separately from HttpWebRequest, e.g. something like SystemProxy.GetDefault in an assembly that both HttpWebRequest and HttpClient depend on.

**Comment by stephentoub** [comment]
> Ideally this would be factored separately from HttpWebRequest, e.g. something like SystemProxy.GetDefault in an assembly that both HttpWebRequest and HttpClient depend on.

Could we just implement https://github.com/dotnet/corefx/blob/master/src/System.Net.WebProxy/src/System/Net/WebProxy.cs#L223-L229 and remove the [Obsolete]?

**Comment by davidsh** [comment]
>his means updating the code in WinHttpHandler/CurlHandler so that the real proxy is appropriately handled.

WinHttpHandler already uses the "real" proxy settings and reads them from the IE settings, processes PAC files etc.  It does this by using the WinHttp helper APIs to access the background WinHttp AutoProxy Discover service.

We did not want WinHttpHandler nor HttpClient APIs to have to reference anything from System.Net.Requests (such as SystemWebProxy) because it meant having to add a contract dependency to that from those libraries.

**Comment by davidsh** [comment]
>Now that we are adding real system proxy support for the managed handler, we should expose this via HttpWebRequest.GetSystemWebProxy()

FWIW, developers don't tend to use that.  But WebRequest.DefaultWebProxy is something that developers use.  Initially, the value of that app-domain-wide property is the "system proxy".  But developer can set it to any custom IWebProxy and thus any subsequent HttpWebRequest's would use that as the default proxy.

We wanted to get away from all of those app domain-wide settings which is why the API surface for HttpClient doesn't reference those objects.  I don't think adding back dependencies to those things is a good idea.  This is similar to how we started down a path of removing dependencies on ServicePointManager/ServicePoint in .NET Core.

**Comment by stephentoub** [comment]
> WinHttpHandler already uses the "real" proxy settings

As does CurlHandler, where "real" is defined as the environment variables libcurl consults.

**Comment by davidsh** [comment]
>and remove the [Obsolete]?

This is not a good idea.  For simple proxy settings, providing this isn't hard.  But when proxies are calculated using javascript from a PAC file (which could be in a fixed location or discovered using network protocols), this is very expensive.   We originally did this in .NET Framework when we supported actually finding the PAC file (JavaScript file) and processing it by launching the javascript interpreter in-process.  That later was dropped in favor of using the OS and WinHttp Proxy Auto-Discovery Service which can cache the PAC file and run the JavaScript in a protected process.

**Comment by stephentoub** [comment]
Why can't an IWebProxy implementation used the same APIs to access that same service/cache?

**Comment by davidsh** [comment]
>Why can't an IWebProxy implementation use the same APIs to access that same service/cache?

It can.  The question is whether we want to add dependencies from System.Net.Http API library to System.Net.Requests API library to solve that.  We currently don't have such dependencies.

In the new .NET Core 2.0 where separate NuGet packages don't exist per library (but rather large packages contain multiple library binaries) maybe it doesn't matter anymore.

**Comment by stephentoub** [comment]
> The question is whether we want to add dependencies from System.Net.Http API library to System.Net.Requests API library to solve that.

The WebProxy class I mentioned isn't in System.Net.Requests, is it?

**Comment by davidsh** [comment]
HttpWebRequest, WebRequest  classes are in System.Net.Requests library:

**Comment by stephentoub** [comment]
Yes, but the obsolete method I mentioned and you commented on is on WebProxy, not the request classes.

**Comment by davidsh** [comment]
Ok.  Yes, you are right that the WebProxy class itself is in the separate System.Net.WebProxy library.

That particular method has been obsoleted for a long time in .NET Framework.  Even when it wasn't, it didn't do much and could not handle PAC/WPAD protocol. I'm not sure it would be a good choice to bring back.

https://docs.microsoft.com/en-us/dotnet/api/system.net.webproxy.getdefaultproxy?view=netframework-4.7

>Remarks
The GetDefaultProxy method reads the nondynamic proxy settings stored by Internet Explorer 5.5 and later, and creates a WebProxy instance with those settings.
The GetDefaultProxy method does not pick up any dynamic settings that are generated from scripts run by Internet Explorer, from automatic configuration entries, or from DHCP or DNS lookups.
Applications should use the WebRequest.DefaultWebProxy property and the WebRequest.GetSystemWebProxy method instead of the GetDefaultProxy method.

**Comment by geoffkizer** [comment]
> Could we just implement https://github.com/dotnet/corefx/blob/master/src/System.Net.WebProxy/src/System/Net/WebProxy.cs#L223-L229 and remove the [Obsolete]? (Though it might be slightly complicated as unfortunately it returns a WebProxy rather than an IWebProxy.)

Yeah, it's weird that it returns a WebProxy.  If it weren't for that, it would probably be the right thing.  

> We did not want WinHttpHandler nor HttpClient APIs to have to reference anything from System.Net.Requests (such as SystemWebProxy) because it meant having to add a contract dependency to that from those libraries.

I agree.  So let's assume this API is in a separate assembly, presumably System.Net.WebProxy (whether it is literally the one Stephen mentioned or a new one).  Both HttpClient and WebRequest would take a dependency on this.

> We wanted to get away from all of those app domain-wide settings which is why the API surface for HttpClient doesn't reference those objects. I don't think adding back dependencies to those things is a good idea. This is similar to how we started down a path of removing dependencies on ServicePointManager/ServicePoint in .NET Core.

As above, I agree we don't want to add a dependency on WebRequest here.  And I agree we don't want to add any global settings.  But I do think we should:

(a) Allow the user to retrieve the "system proxy" via some API
(b) Use this API in managed handler

On further thought, WinHttpHandler and CurlHandler don't need to change at all here.

**Comment by karelz** [comment]
It seems the only remaining work item is to add public API which exposes system proxy information. Is that correct? (ManagedHandler work is tracked by #23150)
Marking as API addition + moving to Future.

**Comment by anmenaga** [comment]
@davidsh @karelz Is there any way today that a .Net Core application can work with HTTP using `HttpClient`/`HttpClientHandler` while respecting proxy settings in "LAN Settings, supporting WPAD and PAC files" ?
You mentioned [here](https://github.com/dotnet/corefx/issues/24574#issuecomment-358720833) that `On .NET Core, WinHttpHandler is used as the underlying stack for HttpClientHandler.`:

- in this case, is it possible to configure `WinHttpHandler.WindowsProxyUsePolicy = WindowsProxyUsePolicy:UseWinInetProxy` for a `HttpClient`/`HttpClientHandler` ?

-  if "[WinHttpHandler is implemented as a thin wrapper on the WinHTTP interface of Windows and is only supported on Windows systems](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.winhttphandler?view=dotnet-plat-ext-2.1).", then what does `HttpClientHandler` use on Non-Windows?

Thank you.

**Comment by davidsh** [comment]
>@davidsh @karelz Is there any way today that a .Net Core application can work with HTTP using HttpClient/HttpClientHandler while respecting proxy settings in "LAN Settings, supporting WPAD and PAC files" ?

As of .NET Core 2.1, the HTTP protocol stack used in .NET Core was changed. It no longer uses native Windows WinHTTP nor Linux 'libcurl'.  Those are considered now the 'legacy' stacks.  We have a new HTTP protocol stack called "SocketsHttpHandler".  It used by default.

See: https://devblogs.microsoft.com/dotnet/announcing-net-core-2-1/ and 'Network Performance Improvements' section.

SocketsHttpHandler is a cross-platform managed implementation of the HTTP protocol stack.  And starting with .NET Core 3.0, it supports HTTP/2.0 protocol as well.

On Windows, SocketsHttpHandler automatically will use the Internet Explorer/IESettings (also known as 'wininet settings') for proxy discovery.  As part of this, you can specify a PAC file directly or use WPAD protocol to discover a PAC file.

On Linux, however, PAC files nor WPAD protocol are supported.

On all platforms (Windows, Linux, Mac OS etc.) as of .NET Core 3.0 we also support environment variables which can specify an explicit proxy.  See #37238.

By the way, this particular issue, #26494, represents a discussion of an older API that really is no longer necessary. And we don't plan any direct support of because proxy support is built into the HttpClient APIs.  However, see #37333 as well if you want to grab the IWebProxy that represents the system proxy.

**Comment by anmenaga** [comment]
@Thanks a lot @davidsh , this is great info!
You mentioned that on .NET Core 2.1 and  .NET Core 3.0 `the default HttpClientHandler that you create (or implicitly via new HttpClient() will use SocketsHttpHandler as the implementation`, so a code like this will use `SocketsHttpHandler` internally?
```
HttpClientHandler handler = new HttpClientHandler();
HttpClient httpClient = new HttpClient(handler);
```
What is the easiest way to verify that `SocketsHttpHandler` is being used internally and it is attempting WPAD protocol when that 'Automatically detect settings' flag is checked?

**Comment by davidsh** [comment]
>What is the easiest way to verify that SocketsHttpHandler is being used internally and it is attempting WPAD protocol when that 'Automatically detect settings' flag is checked?

You can always the debugger to step into the code. The sources should download if you've turned on Visual Studio and 'source server' etc.

You can also turn on System.Net tracing as well:
https://github.com/dotnet/corefx/blob/master/Documentation/debugging/windows-instructions.md

See 'Use PerfView'

**Comment by davidsh** [comment]
Now that #37333 is implemented, we already have a way to return a real IWebProxy that is the default system proxy on the machine.  

```c#
// The initial value of the static property HttpClient.DefaultProxy
// represents the system proxy on the machine.
IWebProxy systemDefaultProxy = HttpClient.DefaultProxy;
```

So, we don't plan to bring back the deprecated HttpWebRequest.GetSystemWebProxy property.
