### ISSUE TITLE
Include TaskCreationOptions in Task.Run

### ISSUE THREAD

**Issue by StanRoze** [dotnet/corefx#2652]
Recently I was trying to create a LongRunning task. The only way I'm aware of doing so is through the Task constructor or through Task.Factory.StartNew

When I created these tasks, I put them into a Task.WhenAll and to my surprise it seemed as though Task.WhenAll was not working.

Here is an example

```
 static async Task RunAsync()
        {
            var w = Stopwatch.StartNew();
            await Task.WhenAll(Delay(1), Delay(2), Delay(5));
            w.Stop();
            
            Console.WriteLine("Done Waiting For Tasks {0}", w.Elapsed);
        }

       private static Task Delay(int seconds)
        {
            return Task.Factory.StartNew(async () =>
            {
                await Task.Delay(seconds*1000);
                Console.WriteLine("Done delaying {0}", seconds);

            }, TaskCreationOptions.LongRunning);
        }
```

Obviously I realized this doesn't work because you have to Unwrap the Task, since StartNew return `Task<Task>`

However the same exact code substituted with Task.Run, which is what is usually suggested, works perfectly without unwrapping. However, I can't specify TaskCreationOptions in Task.Run

I figured, I'll make a new Task, start it and return it.

```
private static Task Delay(int seconds)
        {
            var t = new Task(async () =>
            {
                await Task.Delay(seconds*1000);
                Console.WriteLine("Done delaying {0}", seconds);

            }, TaskCreationOptions.LongRunning);
           
           t.Start();
           return t;
        }
```

This also doesn't work and you can't unwrap `t` because it's a void Task, when it really is a `Task<Task>` and has to be explicitly defined as such so it can be Unwrapped.

Perhaps this is the intended behavior due to how Tasks are created internally, but the fact that Task.Run does the Unwrap for you but other options don't make it a little bit confusing and perhaps can be confusing and misleading to other developers as the code compiles and runs but doesn't do what is expected. These types of bugs maybe really difficult to pin-point, so maybe a compiler warning is sufficient if nothing else.

**Comment by weltkante** [comment]
As far as I gathered it's intentional because LongRunning is most often misused and the other options aren't really useful for async/await programming either, they are artefacts of the TPL and aren't useful for async/await programming.

As far as I understand it (someone correct me if I'm wrong) you are misusing it in your example as well, because your task isn't long running (when it is awaiting it isn't running).

http://blog.stephencleary.com/2013/08/startnew-is-dangerous.html

Quote from the link:
> That only leaves LongRunning and PreferFairness, which are both optimization hints that should only be specified after application profiling. I often see LongRunning misused in particular. In the vast majority of situations, the threadpool will adjust to any long-running task in 0.5 seconds - without the LongRunning flag. Most likely, you don’t really need it.

**Comment by StanRoze** [comment]
@weltkante My example was just showing the TaskCreation option, i am not actually running that as a long running task by any means. It's just a simulation to show something "long running"

**Comment by weltkante** [comment]
Well, if you have a special scenario where it's appropriate to use it, StartNew is there for that and not going away.

Task.Run was introduced to make the most common use cases easy to discover [[1]](http://blogs.msdn.com/b/pfxteam/archive/2011/10/24/10229468.aspx) and preventing you from making mistakes when using the TPL APIs for async/await programming. In particular most of the TaskCreationOptions make no sense for async/await and TaskCreationOptions.None is not the proper default for async/await either. Task.Run sets proper options for the common async/await usage.

Adding overloads with TaskCreationOptions would invite passing the wrong parameters, if anything a new enum should be made which is tailored for the Task.Run and async/await usecase to avoid people making mistakes by using defaults. But imho that is overkill just for surfacing the LongRunning setting when there is already a sensible way to use it for educated people.

[1] http://blogs.msdn.com/b/pfxteam/archive/2011/10/24/10229468.aspx

**Comment by svick** [comment]
The problem is, it doesn't make sense to combine `async` and `LongRunning` (at least not in the current form). If you do it, your `Task` will *start* on a dedicated thread. But it will leave it on the first `await` (which means the thread will end) and then it will resume on a `ThreadPool` thread (since the `LongRunning` thread didn't have any synchronization context or task scheduler).

`LongRunning` makes sense when the thread is actually busy (either running CPU-bound code or being blocked) for long periods of time, not when you spend a lot of time `await`ing something (you don't need a thread for that).

So your code doesn't make much sense, and adding such option to `Task.Run()` would be entirely inappropriate.

**Comment by StanRoze** [comment]
@svick thanks for the helpful comment, it cleared up what I thought was happening, but wasn't sure if it was. You articulated it perfectly and in that I do agree with you, that it wouldn't make sense to await in a LongRunning task. I'm closing this issue.
