### ISSUE TITLE
Naming decision behind ref structs

### ISSUE THREAD

**Issue by SinnersSumit** [dotnet/corefx#26616]
I am confused as to why the new stack-only structs are called `ref struct`. I understand the desire to reuse keywords, but why are they not titled `stackalloc struct` instead? They are after all objects which must never leave the stack, and I think `ref` would tend to imply the opposite. I understand that this is past the point where it can be changed, but I would still like to know why `ref struct` was chosen.

**Comment by mikedn** [comment]
> I think ref would tend to imply the opposite.

Why? `ref` can't never leave the stack either.

> but I would still like to know why ref struct was chosen

Mainly because it all tends to revolve around `ref`. Normally you can't have a `ref` field in a struct but `Span<T>` pulled some magic strings and got one. The there was a need to create custom structs that contain `Span<T>` field and then these struct must also be confined to the stack like `Span<T>`. And having a `ref` field in a struct also has implications to the `ref` return C# feature. And so on, `ref` is everywhere.

**Comment by SinnersSumit** [comment]
I can see the logic of that, but I was mostly thinking about this from the angle of _reference types_ being heap only, and in that context `ref struct`s being stack only is counter intuitive. Thank you for the answer.

**Comment by JonHanna** [comment]
Maybe being something that further shows that `ref` is unrelated to reference types is a minor didactic benefit!

**Comment by mikedn** [comment]
>  I was mostly thinking about this from the angle of reference types being heap only

Ah, but `ref` doesn't have anything to do with reference types except the perhaps unfortunate naming overload. A `ref` is a "managed pointer" that can point anywhere - GC heap, native memory, stack memory.
