### ISSUE TITLE
System.Diagnostics.Tests.ProcessTests.TestStartWithRootUser failed with "Assert.Equal() Failure\nExpected: 0\nActual: 134" in CI.

### ISSUE THREAD

**Issue by Sunny-pu** [dotnet/corefx#26675]
Failed tests: System.Diagnostics.Tests.ProcessTests.TestStartWithRootUserCannotElevate
                    System.Diagnostics.Tests.ProcessTests.TestStartWithRootUser

Details:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_centos7.1_debug/301/testReport/
Failed configuration: Outerloop_netcoreapp_centos7.1_debug
MESSAGE:
Assert.Equal() Failure\nExpected: 0\nActual: 134

~~~
STACK TRACE:
at System.Diagnostics.Tests.ProcessTests.RunTestAsSudo(Func`1 testMethod) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_centos7.1_debug/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 431 at System.Diagnostics.Tests.ProcessTests.TestStartWithRootUserCannotElevate() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_centos7.1_debug/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 386
~~~

**Comment by danmosemsft** [comment]
@eerhardt

**Comment by danmosemsft** [comment]
Is SUDO_USER set wrong on our Centos?

**Comment by eerhardt** [comment]
I'm not sure what the issue is.  I'm going to have to debug this...

**Comment by wfurt** [comment]
we should try to get repro environment. Who shall set the SUDO_USER? 
We may fall back  to "nobody" on Linux/OSX.

**Comment by danmosemsft** [comment]
You could update DumpRuntimeInformationToConsole (or a similar test, but marked OuterLoop) to dump environment to the console so we can easily see.

Or, the repro tool is supposed to be working now so it should be possible to get SSH to a box in the exact configuration: @maririos can help if needed.

**Comment by eerhardt** [comment]
I got a repro machine, and this appears to be a general issue with CentOS7.1.  See https://bugs.centos.org/view.php?id=7324.

The issue is we are passing in a buffer size that is too small in DEBUG mode (purposefully in order to test the fallback code).  CentOS7.1 (and it appears RedHat from that bug report above) had an OS kernel bug with `getpwnam_r` where it returns the wrong error code when passed a buffer size that is too small.  Thus, the OS is telling us that the user doesn't exist, when in fact the OS should be telling us the buffer is too small.

The fix would be to take out that `#if DEBUG` code, and always start with a buffer of `1024`.

https://github.com/dotnet/corefx/blob/4464cceace7615502a1003bc7488f206a47c82ee/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L629

@danmosemsft - your idea caught a bug.  It just happens to be a bug in the OS, that we can't fix.  😉

**Comment by danmosemsft** [comment]
Nice sleuthing!

**Comment by eerhardt** [comment]
Upon further review, this test failure is actually different than #26673.  This test failure is because the test is failing when run in the outerloop with an Assert that the current real user isn't "root".

The tests expect to be able to get a non-root "real" user, so they can start a process as that user.  When we run the outerloop tests, we call "sudo build-tests.sh", which means the tests are executing with euid = 0, and "SUDO_USER" = non-0.  But then when inside the test we start another process with "sudo", we are losing the real user (normally dotnet-bot) because "SUDO_USER" is getting set to "root" (the user who called this process).

To fix this, we need to get the real user name during the test process, and not the process that is started from the test process.
