### ISSUE TITLE
NetworkInterface.GetAllNetworkInterfaces() can't handle all interfaces on WSL

### ISSUE THREAD

**Issue by pjanotti** [dotnet/corefx#26813]
It is hitting an assert while testing System.Net.Http for the `NetworkInterface.GetAllNetworkInterfaces()`. The issue is that one of the `AF_PACKET` enumerated by `getifaddrs` has an address large than the 8 bytes expected, so `memcpy_s` hits the assert:

```
System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandlerTest.GetAsync_IPv6LinkLocalAddressUri_Success [STARTING]
  dotnet: /home/pauloja/corefx/src/Native/Unix/Common/pal_safecrt.h:102: errno_t memcpy_s(void *, size_t, const void *, size_t): Assertion `sizeInBytes >= count' failed.
```

Running a quick code calling `getifaddrs` I can see that one of the interfaces, eth4, has size 16 for `sll_halen`.

```
eth0     AF_PACKET (17)
        sll_halen = 6
eth1     AF_PACKET (17)
        sll_halen = 6
eth2     AF_PACKET (17)
        sll_halen = 6
eth3     AF_PACKET (17)
        sll_halen = 6
lo       AF_PACKET (17)
        sll_halen = 6
wifi0    AF_PACKET (17)
        sll_halen = 6
eth4     AF_PACKET (17)
        sll_halen = 16
eth0     AF_INET (2)
eth0     AF_INET6 (10)
eth1     AF_INET (2)
eth1     AF_INET6 (10)
eth2     AF_INET (2)
eth2     AF_INET6 (10)
eth3     AF_INET (2)
eth3     AF_INET6 (10)
lo       AF_INET (2)
lo       AF_INET6 (10)
wifi0    AF_INET (2)
wifi0    AF_INET6 (10)
eth4     AF_INET6 (10)
```

**Comment by danmosemsft** [comment]
See https://github.com/dotnet/corefx/issues/26476 -- I'm surprised it's working for you, since for me, it throws.

**Comment by karelz** [comment]
Maybe different Win10 build/version?
Should we close it as dupe?

**Comment by pjanotti** [comment]
It is not working for me either: it is *asserting* at an earlier stage, I am sure it will hit #26476 if it passed the assert.

The assert seems to deserve attention since we are attempting to copy the address of an AF_PACKET but the struct that we use doesn't have enough space to do it. In principle this can also be an issue outside WSL: we hit it if we get an AF_PACKET with address larger than 8 bytes - however man pages for packet shows that the expected `struct sockaddr_ll` should also have a size of 8. Some possible actions/questions here:

0. Can we ignore AF_PACKETs? This one seems a special case for one AF_PACKET in which we have an `unspec addr` (see below).
1. We can increase the size on the `LinkLayerAddressInfo` to support the larger size (is it guaranteed the max to be 16? Like an IPv6?)
2. If it is fine to truncate the address to 8 bytes we can change the `memcpy_s` call to avoid the assert. 

I am not that familiar with this code/area to make a call at this point, I can dive into it but perhaps someone more experienced here already knows the answer...

Here is the info on the eth4 on my WSL that has the issue (notice the "unspec addr"):
```
eth4      Link encap:Ethernet  HWaddr 00:00:00:00:00:00
          unspec addr:[NONE SET]  Mask:00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet6 addr: fe80::ffff:ffff:fffe/64 Scope:Global
          RUNNING  MTU:1472  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

**Comment by safern** [comment]
The reason why @danmosemsft might not be hitting this is because this interface showing with `sll_halen` is a VPN interface, so you need to have a VPN running in order to hit it. 

After investigating and reading different code bases like `ifconfig` source and talking to @wfurt I got to some conclusions so I can answer the questions above:

> Can we ignore AF_PACKETs? This one seems a special case for one AF_PACKET in which we have an unspec addr (see below).

No we can't we should return them as they are network interfaces that we can send packets to through a socket.

> We can increase the size on the LinkLayerAddressInfo to support the larger size (is it guaranteed the max to be 16? Like an IPv6?)

This doesn't seem like the right approach because `LinkLayerAddressInfo` is just mapping `struct sockaddr_ll` which is defined as follows: 
```c
struct sockaddr_ll {
   unsigned short sll_family;   /* Always AF_PACKET */
   unsigned short sll_protocol; /* Physical-layer protocol */
   int            sll_ifindex;  /* Interface number */
   unsigned short sll_hatype;   /* ARP hardware type */
   unsigned char  sll_pkttype;  /* Packet type */
   unsigned char  sll_halen;    /* Length of address */
   unsigned char  sll_addr[8];  /* Physical-layer address */
};
```
This is from the `packet()` linux api.

So as we can see the physical-layer address is expected to have a maximum of 8 bytes, `unsigned char  sll_addr[8];` so that is coming from the linux specs, where the MAC Addresses will not have more than 8 bytes, so I think the best solution is to follow your last suggestion:

> If it is fine to truncate the address to 8 bytes we can change the memcpy_s call to avoid the assert.

This seems like a bug or an edge case the the WSL team missed -- probably this interface's HWAddress is coming from Windows like that and they are not handling correctly as the Linux apis expose it.

As a note, If we look at the `ifconfig -a` output for this interface, the HWaddr is tuncated to 6 octets which is the Ethernet address size. The reason of that is because the interface type is ethernet, so it assumes it only needs the first 6 octets in the address.

So I will open a PR to truncate the address to 8 bytes if it is greater than it.

**Comment by danmosemsft** [comment]
Good investigation!

**Comment by danmosemsft** [comment]
> This seems like a bug or an edge case the the WSL team missed -- probably this interface's HWAddress is coming from Windows like that and they are not handling correctly as the Linux apis expose it.

Needs a WSL issue I guess?

**Comment by safern** [comment]
Needs a WSL issue I guess?

Yes, I just opened one related do files missing, I’ll open one for this.
