### ISSUE TITLE
Update System.Numerics.Vectors packaging for Vector<T> changes

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#26834]
This part does not seem to right anymore: https://github.com/dotnet/corefx/blob/master/src/System.Numerics.Vectors/pkg/System.Numerics.Vectors.pkgproj#L25

**Comment by eerhardt** [comment]
I spoke with @ericstj about these lines in the pkgproj.  We concluded that the packaging is still correct.  Even though `System.Numerics.Vectors` is inbox on the .NET Core shared framework, we still want to enable shipping new versions of this package as NuGet packages.  So the referenced packaging code allows for this to be both inbox and OOB.

**Comment by ericstj** [comment]
So I was running some testing and this is actually problematic because we don't currently include the facade version of System.Numerics.Vectors in the package.  As a result, when using the package we switch from using type-forwards to using the types defined in the assembly.  This will break type unification.

We can decide to either:
1. Put placeholders in the package and effectively freeze the API.
2. Put the partial facades in the package.


System.Buffers had a similar problem and we decided to use placeholders.  It was slightly different since it was a full facade.

The pro of going with 1 is that it simplifies the build, the con is that it freezes the API (future additions would need to be in a new netstandard version), but we can always unfreeze the API in the future by bringing back a live build for netcoreapp2.1 that builds against S.P.C.  As a result I'll go ahead and do 1.
