### ISSUE TITLE
SocketException: Invalid argument with SocketOptionName.Linger on Linux (Debian 9)

### ISSUE THREAD

**Issue by Ekkeir** [dotnet/corefx#26889]
When executing `socket.Bind()` on a socket preconfigured with a `SocketOptionName.Linger` the following exception is observed on a Linux (Debian) machine.

```
    System.Net.Sockets.SocketException: Invalid argument
    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
    at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
    at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
```

the same code executes and works well without exceptions on a Windows (Win8.1) machine.

Example code for reproducing the issue
```c#
    using System;
    using System.Net.Sockets;
    using System.Net;

    public class Repro
    {
        static void Main()
        {
            //system ip
            string ipStr = "127.0.1.1";
            int port = 40000;

            IPAddress ipAddress;
            IPAddress.TryParse(ipStr, out ipAddress);

            int optionValue = 1;
            IPEndPoint ipEnd = new IPEndPoint(ipAddress, port);
            var s = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
            s.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.Linger, optionValue);
            s.Bind(ipEnd);
            Console.WriteLine(s);
            Console.ReadLine();
        }
    }
```

[EDIT] Add syntax highlighting by @karelz

**Comment by stephentoub** [comment]
It happens to work on Windows but only because of the size of the data types involved in the native definitions.  SO_LINGER doesn't take an `int` value, rather it takes a `linger` value, which on Windows is defined as:
```
typedef struct linger {
  u_short l_onoff;
  u_short l_linger;
} linger;
```
and on Linux is defined as:
```
struct linger {
    int l_onoff;    /* linger active */
    int l_linger;   /* how many seconds to linger for */
};
```
That `u_short` is 2 bytes, meaning `linger` is 4 bytes, and thus it happens to be the same size as the 4-byte `int` you're passing in from C#.  But the 4 bytes you're passing is an insufficient size for the 8-bytes the Linux setsockopt expects, which is why you're getting an "Invalid argument" back from the SetSocketOption call.

If you want to change the linger options, you should use `Socket.LingerState`:
https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.lingerstate?view=netcore-2.0#System_Net_Sockets_Socket_LingerState

**Comment by karelz** [comment]
Seems to be answered, closing. If you think we missed anything, please let us know and we can reopen.

**Comment by Ekkeir** [comment]
@stephentoub , thank you for your explanation and help. Was out of my depth there. Porting legacy code can be tricky sometimes.
@karelz, the issue can indeed be closed, thank you.

**Comment by stephentoub** [comment]
> Porting legacy code can be tricky sometimes.

Definitely :)
