### ISSUE TITLE
Registry.GetValue returns an Int32 for REG_DWORD instead of an Uint32

### ISSUE THREAD

**Issue by TheMinefighter** [dotnet/corefx#26936]
When you read a REG_DWORD value with Microsoft.Win32.Registry.GetValue it will return an Int32 but the Windows Registry Editor (Regedit.exe) interprets REG_DWORD as unsigned integers with an upper limit of 2^32-1 in the decimal input filed. If you read a REG_DWORD, which was set in regedit.exe to 2^32-1, C# will give you -1 in an Int32, but it should give you an Uint32 with the value 2^32-1. The same issue applies for REG_QWORD with an Int64 returned instead of Uint64.

**Comment by danmosemsft** [comment]
I agree that it should have been uint. My guess is that it is int because originally uint was not CLS compilant, the same reason why int is used in many other places for quantities that are unsigned.
If you may be dealing with numbers this large, you can cast to and from int. (You may need the unchecked keyword if you are compiling with `/checked`.)
As far as I can see we cannot "fix" this now because it would break anyone currently casting the object return value to int, which is surely very common given the value is a number.

**Comment by TheMinefighter** [comment]
That sound logical, now using the following code (is there a cleaner solution for converting -1  to 2^32-1  
 , because I use full 32bit ?) to  :
```
            toReturn = Registry.GetValue(key, valueName, null);
         if (toReturn is int)
         {
            toReturn = uint.Parse(((int) toReturn).ToString("X"));
         }

         if (toReturn is long)
         {
            toReturn = ulong.Parse(((long) toReturn).ToString("X"));
         }
```

**Comment by danmosemsft** [comment]
Right. @stephentoub do you see any way we could solve this ourselves? I do not (short of providing new methods)

**Comment by stephentoub** [comment]
> do you see any way we could solve this ourselves? I do not (short of providing new methods)

Nope.  If we're currently returning a boxed Int32, changing to return a boxed Int64 or UInt32 would be breaking, as casts to Int32 to unbox it would fail.

**Comment by danmosemsft** [comment]
Closing as above - I don't believe we can fix. Thanks for the report, though.
