### ISSUE TITLE
Remove USE_ETW Compilation Constant from System.Diagnostics.Tracing.Tests

### ISSUE THREAD

**Issue by brianrob** [dotnet/corefx#27116]
It may be possible to remove USE_ETW and just mark the tests as Windows only.  We should see if this is possible to simplify the test code.

**Comment by brianrob** [comment]
Marking this for Hackathon.  Recommend starting by removing the ifdef and instead using programmatic checks or attributes to only run the ETW paths on Windows.

**Comment by sgaliamov** [comment]
good thing to start, I'll try it.

**Comment by ViktorHofer** [comment]
@sgaliamov I sent you a collaboration invite so that I can assign you to the issue. It's a good thing to joing the gitter channel as I can support you there: https://gitter.im/dotnet/corefx-hackathon

**Comment by sgaliamov** [comment]
Hello @ViktorHofer! I have couple questions, maybe @brianrob can also help:
1. As I understand, *EtwListener* class is Windows specific class. Should it be excluded from compiling on "non Windows" environments? If yes, then I still need kind of conditional compilation. I've solved it by configuring *csproj* file with *Condition="'$(TargetsWindows)' == 'true'"*. Is it acceptable solution? Or I just need to refactor code by removing *USE_ETW*, and all not windows code just won't run on linux because of *PlatformDetection.IsWindows* attribute on test methods?
1. As I need include more changes in the pull request, should I create new one or continue with this?

**Comment by brianrob** [comment]
@sgaliamov, thanks for working on this.  I suspect that you won't be able to completely get rid of all conditional compilation because there is surface here as you point out that I don't think we can or want to compile on Unix.  I think that using '$(TargetsWindows)' == 'true' in the csproj is a good way to go about it.

Feel free to modify the existing PR.  I'll also go take a look at it.
