### ISSUE TITLE
Fix failing authentication test cases on different httpclienthandlers.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#27113]
Search for issue number in code.

**Comment by davidsh** [comment]
Is this a product bug or test bug?

**Comment by Priya91** [comment]
Most likely product bug, there are 2 scenarios:

1. Some cases pass on winhttphandler and socketshttphandler, but don't on curlhandler. 
2. Some corner cases where the input is incorrect, winhttphandler and curlhandler hangs in native code,  socketshttphandler returns unauthorized.
3. Some corner cases of auth header string, socketshttphandler returns OK, winhttphandler and curlhandler return Unauthorized, not sure which is the correct behavior. In case of socketshttphandler, the ```HttpResponseMessage.Headers.WwwAuthenticate``` returns valid auth headers for these cases, whereas on other handlers the native code (Schannel or libcurl) treats these headers as invalid.

**Comment by geoffkizer** [comment]
(1) and (3) scare me a bit.  

For (1), it's certainly possible (even likely) CurlHandler is broken, but we should confirm that, otherwise there may be something we're missing here.

For (3), it's scary that we're accepting auth header strings that other handlers don't.  If the WWW-Authenticate parsing in HttpClient proper is too lenient, then we should probably just fix that.

**Comment by geoffkizer** [comment]
@Priya91, could we add separate issues for (1)-(3) and track them in the tests?

**Comment by caesar1995** [comment]
All failures are tracked by:
SocketsHttpHandler: No failure.
WinHttpHandler: #28065
CurlHandler: #28065
Netfx: #28060

**Comment by karelz** [comment]
@caesar1995 please update the disabled test against the new bugs and close this one.
