### ISSUE TITLE
Point the Readme test badges to Helix runs

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#27130]
We should abandon the Jenkins testing infrastructure for innerloop/outerloop which is currently only being used for the badges and instead point our badges at daily/onPush helix runs (daily outerloop added in https://github.com/dotnet/corefx/pull/27129).

This greatly reduces the cost of updating our test OS versions and also makes the badges more accurately reflect our current build&test state.

Forked from https://github.com/dotnet/corefx/issues/27095
Depends on https://github.com/dotnet/core-eng/issues/1901

**Comment by danmosemsft** [comment]
We should take care not to lose coverage if we can. IIRC it was noted last time this came up that Jenkins was running configurations that official builds do not. Just today I opened a bug against some tests that were failing in Jenkins because they were not elevated, apparently the Jenkins Windows runs are not elevated and the Helix ones are elevated.

**Comment by ianhays** [comment]
>apparently the Jenkins Windows runs are not elevated and the Helix ones are elevated.

The innerloop on-Push and manually triggered Jenkins runs are run non-elevated, yes. The on-PR and official build Helix runs that run by default on every PR and show up as ```Windows x64 Debug Build``` are  elevated.

Do we want to retain test machines that run non-elevated?  If so, then we should add those to Helix as daily runs. cc: @MattGal

**Comment by MattGal** [comment]
We have the ability to run our clients in a non-elevated Windows context in Helix, it was explicitly requested that we stop doing that because there were tests that required it that would fail or not run.  It's non-trivial to get things working both ways in Windows.

On linux, I believe it's flipped; helix clients don't ever run as root, where Jenkins runs do.

**Comment by ianhays** [comment]
>It's non-trivial to get things working both ways in Windows, but if this is a real priority we can discuss it.

I'm not certain whether it is a priority. Up until this week I assumed we ran all of our tests elevated. 

One could certainly argue that stopping non-elevated tests reduces our total coverage, but I question whether that coverage justifies the cost of maintaining two test builds. And if that coverage is valuable enough to keep, then it should probably be applied to the official builds instead of just the Jenkins runs.

**Comment by MattGal** [comment]
It's not two builds, it's more like two machine configurations.  The elevation context of the Helix client determines the elevation context of its child processes.  There used to be non-public console utilities that allowed test machines to start with any UAC context they liked, but I'm unsure if we can find or even use those.

**Comment by danmosemsft** [comment]
Note that we don't get code coverage out of Helix right now. We rely on Jenkins for that. WE should either get it going in Helix or at least leave that one run. It is Windows only. Please don't delete it...

**Comment by ianhays** [comment]
Don't worry @danmosemsft , I won't delete the code coverage build :) We've got a few special-case Jenkins runs like that e.g. Linux Arm that I'm leaving as Jenkins runs for now. It's just the innerloop and outerloop runs that I'm focusing on first.

**Comment by ViktorHofer** [comment]
AFAIK we are going to point the readme badges to the Azure DevOps runs as soon we have fully migrated. Closing in favor of https://github.com/dotnet/corefx/issues/30558
