### ISSUE TITLE
Are there plans to support GetSchema in System.Data.Odbc?

### ISSUE THREAD

**Issue by jbb352** [dotnet/corefx#27260]
I'm currently using the System.Data.Odbc 4.5.0-preview1-25914-04.  Works great for connecting to various sources both on Windows and Linux.  I do however have a requirement to get the schema list for the source and when trying to use GetSchema I get a NotImplemented error.
Are there plans to implement this feature?

**Comment by danmosemsft** [comment]
@jbb352 the code should have the same level of functionality as in regular .NET Framework (plus Unix support with unixODBC). I am not aware of plans to add to it, but that doesn't mean we can't.

@divega are we likely to add features to S.D.Odbc? If not, would you consider community contributions?

**Comment by danmosemsft** [comment]
cc @saurabh500

**Comment by divega** [comment]
*System.Data triage:* moving to the System.Data.SqlClient for the managed providers team to ultimately handle the issue.

**Comment by divega** [comment]
@jbb352 I assume you are asking about `GetSchema()` on `OdbcConnection` because I believe the one on `OdbcDataReader` is already implemented. 

As far as I remember, the version of the method on the connection is a hard problem because there is very little standardization across ADO.NET providers on what the returned DataTable contains. I also think this was never implemented in the ODBC provider in .NET Framework. 

So far we haven't implemented any new functionality in this code base (i.e. the original code form .NET Framework was ported with minimal changes to .NET Core), but I don't discard that we could do so in the future.

**Comment by jbb352** [comment]
Hi @saurabh500 just to confirm, yes I have it working with .Net Framework 4.6 just not with dotnet core/standard

**Comment by divega** [comment]
>  I looked into the OdbcConnection.GetSchema() and if it works on .Net Framework...

Good to hear @saurabh500. I guess I was looking at the wrong code :blush:

**Comment by iamatinkerer** [comment]
Can I work on the fix for this issue? 
Since the work was done for SqlClient in https://github.com/dotnet/corefx/pull/19937/files, I will have a good idea of what to do. I think a bunch of code for this particular issue can be moved to the Common/src/System/Data/ProviderBase folder and can be reused in Odbc and SqlClient. 

However, I don't know where to get the System.Data.Odbc.OdbcMetadata.xml used in OdbcConnectionFactory.cs at https://github.com/Microsoft/referencesource/blob/90b323fe52bec428fe4bd5f007e9ead6b265d553/System.Data/System/Data/Odbc/OdbcConnectionFactory.cs#L108 
If the XML is provided, then I could send a PR for this issue.

**Comment by saurabh500** [comment]
@iamatinkerer Thanks for showing interest. We haven't started working on this issue actively. I will upload the `System.Data.Odbc.OdbcMetadata.xml` on Github and provide the link.

**Comment by saurabh500** [comment]
@iamatinkerer Here you go https://github.com/saurabh500/corefx/blob/67468a0b81f46702471716965f01817ec2adb9a2/src/System.Data.Odbc/src/Resources/System.Data.Odbc.OdbcMetaData.xml

**Comment by karelz** [comment]
@iamatinkerer thanks for your help!
I sent you collaborator invite (that way we can assign the issue to you - GH limitation). Please let me know when you accept and I will assign it to you (temporarily assigning it to myself).
Note: Collaborators are automatically subscribed to all notifications per repo (500+ per day). We recommend to switch the repo to "Not Watching" - that will send you notifications only where you are mentioned, assigned or explicitly subscribed.

**Comment by iamatinkerer** [comment]
@karelz Thanks for the email subscription tip. I have accepted the collaborator invitation.
