### ISSUE TITLE
CurlHandler: Transfer-Encoding incorrectly sent on redirect from POST to GET

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#27301]
If the initial request is a POST, and Transfer-Encoding: chunked is true for the request, and we receive a redirect code that forces the method to GET instead of POST, then CurlHandler is incorrectly sending Transfer-Encoding: chunked on the redirected GET request.

**Comment by rmkerr** [comment]
Based purely off of #26434 I think that as-is we would expect this test to fail for the 300 case, since cURL won't change the method to GET.
https://github.com/dotnet/corefx/blob/4dc401be87a7662132973ac4f43309b3dc534926/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs#L637-L714
There is definitely some incorrect behavior there in the case of 301, 302, and 303 though. Unfortunately it looks like the current method for suppressing `Content-Length` is just to modify the value of the header in the request message:

https://github.com/dotnet/corefx/blob/4dc401be87a7662132973ac4f43309b3dc534926/src/System.Net.Http/src/System/Net/Http/CurlHandler/CurlHandler.cs#L783-L788
So it looks like we have two options. I'd like to hear your thoughts on these @davidsh 

1. Keep the current pattern and modify the request headers on redirect. I've tried this and it works.
2. Stop modifying the request headers everywhere. Add a field to EasyRequest that tracks whether or not we should skip the header later when passing it to cURL.

**Comment by davidsh** [comment]
>I'd like to hear your thoughts on these @davidsh

If (1) means modifying the original HttpRequest.Content.Headers, then I am not a fan of that unless it is very difficult/perf-impacting to do (2). Otherwise (2) is preferred.

**Comment by rmkerr** [comment]
The test fix I have now involves adding a boolean to `CurlHandler.EasyRequest`, and changing the `CurlHandler.EasyRequest.AddRequestHeaders` static method to be non-static so that it can then check the state of that boolean. The change would allow me to remove an existing modification to the headers, but there would still be one more left in `CurlHandler`.

There are a lot of ways to make the fix, and I think that we can find a way that will have a very minimal impact. To be honest I just don't know enough about performance analysis to know what that way is. I'll get the PR out today though so I can get feedback on my attempt.

**Comment by rmkerr** [comment]
I'm actually going to have to go back on that -- it is much more complicated to remove the existing modifications to the `TransferEncoding: Chunked` header than I anticipated. Most of the complexity comes from ensuring that a `ContentLength` is sent once we remove `TransferEncoding: Chunked`. The value is cached in cURL, and in `HttpContentHeaders`, and I can't seem to get them all working in sync without major modifications.
