### ISSUE TITLE
Graphics.MeasureString wrong results in case of PageUnit is Point and all chars fitted

### ISSUE THREAD

**Issue by RusKnyaz** [dotnet/corefx#27312]
charsFitted and linesFitted output paramters values are 0 in case of text fitted in provided area and graphics's PageUnit is Point. The issue is reproducible under linux, but not reproducible under Windows.

Run the following code under linux
```c#
    var bmp = new Bitmap(200, 50);
    using (var graphics = Graphics.FromImage(bmp))
    using(var font = new Font("Arial", 10))
    {
        graphics.PageUnit = GraphicsUnit.Point;
        graphics.MeasureString("HELLO", font, new SizeF(float.MaxValue, float.MaxValue),
                    StringFormat.GenericTypographic, out var chars, out var lines);
                
         Console.WriteLine($"Chars fitted: {chars}");
         Console.WriteLine($"Lines fitted: {lines}");
      }
```
Observed: Console output is
Chars fitted: 0
Lines fitted: 0

Expected: Console output is
Chars fitted: 5
Lines fitted: 1

**Comment by safern** [comment]
Most likely libgdiplus issue. @RusKnyaz might be worth opening an issued there pointing to these issues to see if they can be investigated/fixed there.

**Comment by RusKnyaz** [comment]
And these guys out of lizhdilos not send me then some guys from libgdi? I have not programmed in C for a very long time. It takes too much time for me to create a simple example to reproduce the issue.

When I saw that cross-platform System.Drawign came out, I thought, "they are either geniuses or crazy!". But when I realized that this is just a wrapper over Mono's libgdiplus (BTW, why not Wine's one?). I was somewhat disappointed and began to post bugs. In the end, you chose this library yourself.

**Comment by safern** [comment]
@RusKnyaz I'm sorry to hear about you being disappointed, we're trying to do our best to have a cross-platform System.Drawing with the same behavior in between Windows and Unix and the reason why we chose libgdiplus is because of all the native calls being similar to GDI+, without that, it would've been somehow impossible to have a cross System.Drawing in this time frame.

However we really appreciate you posting this bugs, and they will definitely be investigated and if they come from libgdiplus then we will push for them to be fixed on their end. Thank you very much for your interest in our product and helping us make it better.

**Comment by shibaev** [comment]
I found similar issue related to PageUnit: https://github.com/mono/libgdiplus/issues/545. Might be related to this one.

**Comment by safern** [comment]
Thanks @shibaev -- I moved this issue to: https://github.com/mono/libgdiplus/issues/548
