### ISSUE TITLE
Proposal: Add pre-defined regular expressions

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/corefx#27342]
# Suggestion:
I suggest to add pre-defined regular exertions as static fields in Regex class or in a new Regexs class. There are some famous widely used expressions, such as Phone numbers, dates, times, zip codes, emails…. etc.
Regexs class can be put in a separate NuGet, to allow contributors to add as many Expressions as they want.

Note: 
Regexs should appears in the auto-complete list displayed with Regex methods that expects expressions.

# Implementation:
```
public static class Regexs
{
  public static readonly string Email = @"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$";
        // ...........
}

```
# Usage:
`var rgx = new Regex(Regexs.Email);
`
# Benefit:
This will be a time saver for repeated Regex tasks, and will make it easier for beginners to use Regex,

**Comment by Clockwork-Muse** [comment]
....[email is much more complex than that](https://stackoverflow.com/questions/201323/how-to-validate-an-email-address-using-a-regular-expression), so that may make a better or worse example.

What you'd really want to do is precompile all of them, though, probably with a specified list of options (for instance, ECMAScript compliance is going to have a large effect on what `\w` matches).

**Comment by MohammadHamdyGhanem** [comment]
> email is much more complex than that

**Comment by MohammadHamdyGhanem** [comment]
In one of my pld apps, I used this regex for email:
`"\b[.a-z0-9_-]{1,20}@[.a-z_-]{3,20}\.[a-z]{2,4}\b"`
It covers most famous emails, but still misses some.

**Comment by MgSam** [comment]
This is a bad fit for the BCL, because which are the "correct" Regexes that get this blessed status will vary widely by culture. Even things like email are open to argument, as is pointed out.

**Comment by MohammadHamdyGhanem** [comment]
Let's start with English culture, and let contrubuters cover thier cultures if they want. As I said, this can be a NuGet that grows over time. Also, we can declare exxpressions as methods with one or more parameters to indicate the culture and any other options. This can be a powefull helper class.

**Comment by Clockwork-Muse** [comment]
>This is a bad fit for the BCL, because which are the "correct" Regexes that get this blessed status will vary widely by culture. Even things like email are open to argument, as is pointed out.

Email, thankfully, isn't culture-dependent, although it might be **provider**-dependent (ie, gmail might allow different addresses than outlook, although most of the time this tends to show up in other websites).

>Let's start with English culture, and let contrubuters cover thier cultures if they want. As I said, this can be a NuGet that grows over time. Also, we can declare exxpressions as methods with one or more parameters to indicate the culture and any other options. This can be a powefull helper class.

We almost certainly wouldn't want any culture-dependent regex matchers.  There's not even a single version of "English" in this context - for example, you can't do a regex for "phone number" since that's country or region specific (well, you can just accept any set of ...15, I think... digits for ITU, but that's not terribly helpful).

Then there's the problem of, what happens if the relevant standard changes?  Presumably the library gets updated, which would be... interesting... especially if two different versions were trying to talk to each other.

**Comment by danmosemsft** [comment]
I also feel this is not a good fit for the platform, for these reasons

* The correct pattern is not always well defined. Maybe there's an RFC, maybe there's a defacto variation on the RFC,. ..
* These need to be maintained, and may vary with region/culture. Eg., phone numbers change in locale X. For globalization data we largely offload this to Windows/ICU.
* There is no reason this cannot be a community developed Nuget package, which would also allow a variety to choose from depending on needs. Likely there are already such packages.
The BCL itself does not need them. That's not a strike against it, but it's sometimes a reason for having something in the BCL as we avoid outward dependencies.

Thanks for the suggestion though.

**Comment by MohammadHamdyGhanem** [comment]
@Clockwork-Muse @MgSam @joshfree 
Here is Verex (my verbal regex builder):
https://github.com/MohammadHamdyGhanem/Verex
Thanks
