### ISSUE TITLE
Memory leak in SendAsync in HttpClient

### ISSUE THREAD

**Issue by galmok** [dotnet/corefx#27468]
In corefx/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:SendAsync there seems to be a memory leak that is triggered when CancellationToken.None is used.

We have created HttpClient once and reuse it:

```c#
    var httpClientHandler = new HttpClientHandler();
    httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => true;
    httpClient = new HttpClient(httpClientHandler);
    httpClient.Timeout = Timeout.InfiniteTimeSpan;
```

And are calling like this:

```c#
    using (var content = PrepareHttpContentJson(input))
    using (HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, new Uri(fullUrl, UriKind.RelativeOrAbsolute)))
    {
      request.Content = content;
      using (HttpResponseMessage result = await httpClient.SendAsync(request, CancellationToken.None))
      {
        // work on result
      }
    }
```

PrepareHttpContentJson returns a ByteArrayContent (json content) with ContentType set.

If this code is called repeatably, it leaks every `ByteArrayContent` created.

Looking to the memory using Diagnostic Tools in Visual Studio, this is what seems to lock the memory:

    ByteArrayContent
       > Action<Stream>
        > HttpWebRequest
          > ConnectStream
          > ContextAwareResult
          > HttpClientHandler+RequestState
          > CancellationCallbackInfo

If I replace `CancellationToken.None` with `cts.Token` in `SendAsync` and create `var cts = new CancellationTokenSource();` just before the first `using`, the memory leak stops.

I made this attempt as I checked the source code for HttpClient.cs and noticed some handling of cancellation tokens going on and figured this might be the cause.

Note: This MAY be an interaction issue with Autofac, but I don't think so. The `using` code block is resolve by Autofac, but there is only ever 1 instance (registered as single instance) of it (so it wont be disposed between usages).

[EDIT] Add C# syntax highlighting by @karelz

**Comment by galmok** [comment]
Yes, you are correct. It is running net462.

But the System.Net.Http nuget package is version 4.3.3 and links to the project url https://dot.net/ which I believe is from this project, right?

**Comment by davidsh** [comment]
cc: @karelz

**Comment by mikeparker** [comment]
Interestingly, we're just looking at exactly the same issue on dotnetcore. We're using client.SendAsync with JsonContent, and without a CancellationToken we have a memory leak, with a CancellationToken memory is fine.

**Comment by mikeparker** [comment]
We found our issue, it's because we have a DelegatingHandler to do Retrying, which had a linked cancellation token source which was not being disposed.
```
        async Task<HttpResponseMessage> Retry(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            for (var attempt = 1; attempt <= _attempts; attempt++)
            {
                var cancellationTokenSource = new CancellationTokenSource();

                var linkedSource = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, cancellationTokenSource.Token);
```

Whilst this is technically 'our fault' we do feel it'd be good if the framework had a better safeguard against this kind of thing. It has taken us over 2 months to figure out what it was as we're generally not experts in diagnosing memory leaks as they are so rare in a managed memory language like C#, and also since you can't start the performance profiler in VS with an ASP.NET Core project.

**Comment by galmok** [comment]
Your posted code uses no cancellation token (default token is a None token), yet you still claim it is a fault with your code? Unless you pass in the linkedSource to SendAsync in which case it could be your error.

**Comment by Clockwork-Muse** [comment]
>we're generally not experts in diagnosing memory leaks as they are so rare in a managed memory language like C#

Not necessarily true.  A big source of memory leaks in managed memory languages is object pools with non-expiring members (for the obvious reason that a reference to the object still exists).

**Comment by Lexcess** [comment]
We're re-using an HttpClient (v4.3.3) on .Net 4.6.1 without a cancellation token and seem to be seeing the same memory leak. We only recently updated to 4.3.3 so this seems to be an issue introduced relatively recently (we were previously several versions behind, and I can get the exact prior version if it will help diagnosis)..

**Comment by pabmcdonald** [comment]
We have a customer that is using our product had this issue is causing a pain point with memory leaking.  I see that this in on the Future Milestone.  Is there any plans on when we could expect a fix?

**Comment by karelz** [comment]
@Lexcess which NuGet package do you use exactly? [System.Net.Http](https://www.nuget.org/packages/System.Net.Http/)? Which one was the previous version?

@pabmcdonald based on previous post (https://github.com/dotnet/corefx/issues/27468#issuecomment-371505770) it doesn't seem to be a problem in .NET Framework code. Which information is incorrect?

Can someone please clarify if there is simple repro that showcases the memory leak? (please post it here, so that we can try it in-house) Does it repro on .NET Framework or .NET Core?

**Comment by pabmcdonald** [comment]
@karelz  We are seeing this for a customer using .Net Core Standard 2.0.  If we pass a CancellationToken on the calls to HttpClient it seems to NOT leak.  Just when the calls don't have a token it does.  We can't seem to create a smaller set of code to show it failing.  We can only repro on customers system with their code calling us (we are a library to them).

**Comment by karelz** [comment]
@pabmcdonald check if they run on .NET Framework or .NET Core and what are their dependencies (esp. System.Net.Http nuget). You as a library probably target .NET Standard.
Without a confirmed repro there is not much we can do :(.

@caesar1995 can you please in parallel try the original repro? I wonder if it demonstrates a memory leak on .NET Framework.

**Comment by caesar1995** [comment]
I have tried the configuration mentioned by @Lexcess : HttpClient (v4.3.3) on .Net 4.6.1, and re-using an HttpClient sending requests without cancellation token (using the code from the issue description). Not able to repro the memory leak.

Can anyone post a repro here to further investigation?

**Comment by Lexcess** [comment]
@karelz @caesar1995 So this was a few weeks ago but I believe the version was actually System.Net.Http 4.0.0 (as shipped in .Net FX). At the time our team felt they could knock together a repro so give us a little time to revisit it and we'll see if we can post one here. 

If it helps we were seeing the behaviour when under significant load (performing around a thousand requests per second). Also this might be a red herring but we were also seeing some task cancelled exceptions (this appears to be due to hitting the default timeout not manual cancellation), we aren't sure if this was more a symptom or a cause.

**Comment by caesar1995** [comment]
> I believe the version was actually System.Net.Http 4.0.0 

I have tried 4.0.0, still no luck there :(

> At the time our team felt they could knock together a repro so give us a little time to revisit it and we'll see if we can post one here.

A working repro will be very useful. Thanks for the efforts!

A question for you: Is there a proxy used/involved?

**Comment by Lexcess** [comment]
@caesar1995 I don't believe there is a proxy in play, but I will double check.

**Comment by caesar1995** [comment]
Yeah, please make sure App.Config/machine.config doesn't include a proxy, and Fiddler is not used.

Previously we have solved a memory leak issue in .NET Framework, which will happen if connecting to a HTTPs server through a proxy. I want to make sure it's not the same issue.

**Comment by Lexcess** [comment]
Hello again, so we've been working to create a reproduction of this issue I wanted to give an update.

We can only consistently repro the behaviour in our production environment with the newer Nuget package. We don't see it if we change the environment (to say a local desktop, an Azure web app etc...). We haven't had the time to trying reverting the Nuget package, but older existing builds with that version don't show the behaviour.

The other thing we have noticed is that it only seems to be affecting calls to a specific domain. The calls are over HTTPS to a web service (using an Entrust certificate if that makes a difference). We wonder therefore if the HttpClient is trying to do something with the certificate and that is failing? For reference the team has confirmed there is no proxy involved and the Server with the issue is running Windows Server 2008 R2 (which is listed as a supported OS), on IIS. When the behaviour occurs it seems like there is a CPU spike and something related to the request is not released (but the client doesn't appear to be blocking which suggests async work is happening).

Given we can't give you access to the production machine, is there any additional information we can give that might help diagnose the issue?

**Comment by caesar1995** [comment]
@Lexcess Thanks for looking into it!

Since we are not able to repro it on our side, we will need a working repro/dump file to further the investigation.

**Comment by Lexcess** [comment]
@caesar1995

**Comment by karelz** [comment]
@Lexcess we do not have a secure file transport to use.  In general, we prefer to not receive NDA data directly from GitHub issues.  In such cases we recommend customers to contact official Microsoft support channel (I assume you have one).

Regarding this specific issue:  The problem is that a dump may not be sufficient to root cause the problem.  Also there is possibility that the problem is in the code which calls into Networking APIs.  That's the main reason why we ask for isolated repros which involve as few pieces as possible.

The history of System.Net.Http NuGet package is that in versions 4.1.0-4.3.0 it had different code base under the hood -- we tried to deliver "better" WinHttpHandler as out-of-band replacement of the one inbox.  That turned out to be troublesome (see https://github.com/dotnet/corefx/issues/17522#issuecomment-338418610).  In version 4.3.1 we undid all that and reshipped the same code that is part of .NET Framework.
Therefore when you say that you updated version 4.0.0 to 4.3.3, it is highly suspicious -- those 2 things should be exactly the same.

I would recommend couple of experiments:
* Confirm which NuGet packages reproduce the problem vs. not -- using 4.0.0, 4.1.0/4.3.0 and 4.3.1 respectively.
* Try to NOT use System.Net.Http nuget at all -- the latest version just reships what is part of .NET Framework inbox after all.  If you have indirect dependencies on it you cannot change, you may consider to try to use downgrading bindingRedirect on the assembly (at least for an experiment - it may prove to be troublesome to maintain as tooling overrides it upon nuget packages update):
```xml
<assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-4.9.0.0" newVersion="4.0.0.0" />
</dependentAssembly>
```
* Experiment with the repro more, try to isolate it / minimize it.
* Do proper memory leak analysis (see e.g. [PerfView tutorial](https://channel9.msdn.com/Series/PerfView-Tutorial/Tutorial-10-Investigating-NET-Heap-Memory-Leaks-Part1-Collecting-the-data)).  That should tell you who holds on the memory.

**Comment by Lexcess** [comment]
Hi @karelz, Appreciate the long post. We're just trying to find the fastest way to get the information you need to find and fix the issue. We were already trying to isolate the issue but @caesar1995 suggested a memory dump, and at the time that would have had to be from our production application. 

On the other points you raise. Please appreciate that the process of getting a working repro on this issue has taken a fair amount of effort on our part, and we don't really have the resources to run all the tests for the various Microsoft packages you suggest nor make drastic changes to the applications.

That all said the good news is that it looks like one of our developers might have reproduced the issue locally. We are now working on getting a cut-down application to show the problem. It is going to take us a little longer to get that to you (I'm hoping in the next day or so). We've had a number of public holidays (internationally) that have slowed things down.

**Comment by caesar1995** [comment]
Hey @Lexcess sorry that it took me a while before trying the repro. It's still not clear to me what's the problem here.

My summary for the discussion thread is that: passing `CancellationToken.None` to `HttpClient.SendAsync` will result in memory leak - the `request.Content` is held and not get GCed. But based on the description above, it sounds like: using static HttpClient to send request will result in `TaskCancelledException`, and change the `HttpClient` to an instance member will resolve the problem. So I want to confirm, did you observe the memory leak AND the `TaskCancelledException`? What about passing a CancellationToken to `GetAsync` method, does it solve the memory leak?

Also I want to ask why need to create a static HttpClient in the controller? I don't know much about ASP.NET coding standard, can you point me to some documents on this?

I have tried your repro: on my dev box, I quickly get the [HTTP Error 503.2 - Service Unavailable](https://stackoverflow.com/questions/9774826/http-error-503-2-service-unavailable-the-serverruntimeappconcurrentrequestli?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa), and I have tried some [workarounds](https://docs.microsoft.com/en-us/iis/configuration/system.webserver/serverruntime) to increase the [appConcurrentRequestLimit](https://blogs.technet.microsoft.com/kristinw/2013/03/28/recommended-changes-and-tweaks-for-exchange-servers-in-an-enterprise-environment-whew/), but they are not working. Still cannot repro the memory leak or `TaskCancelledException`. I used WinDBG to check the heap for the process, and did `!gcroot` on several `HttpWebRequest` on the heap. It turns out their reference are correctly hold by `System.Net.Sockets.OverlappedAsyncResult`, not `CancellationCallbackInfo` (from the top post).

```
0:053> !gcroot -all 0e0e8e1c
Finalizer Queue:
    0d004bec
    -> 0d004bec System.Net.Sockets.OverlappedAsyncResult
    -> 0d004bdc System.Net.WriteHeadersCallbackState
    -> 0e0e8e1c System.Net.HttpWebRequest
```

On my one core test VM, I can repro the `TaskCancelledException` with non-static HttpClient (which is opposite to your description), but still didn't observe memory growing out-of-bounds.

An ideal repro would be a isolated console app without any external dependencies. That can speed our investigation. Thanks!

**Comment by karelz** [comment]
Looks like it is not actionable now.
Let us know if you have repro and how you detect the leak (ideally via steps from @caesar1995 above) - we can then reopen. Thanks!

**Comment by karelz** [comment]
So you can reproduce it only on .NET Framework, right? And it seems you are not using System.Net.Http package.
If that is correct, then the problem is outside of scope of GitHub - we do not track .NET Framework issues on GH - see https://github.com/dotnet/corefx#how-to-engage-contribute-and-provide-feedback

I would also suggest to confirm if it is truly a memory leak, or just GC not kicking in. You can confirm that via profilers, or via explicitly kicking off GC.

**Comment by Uzza** [comment]
I just checked, and the GC fires sparsely, but the memory is still not released. Manually triggering have no difference.
However, since I was running 4.6.1 I decided to try newer versions, and it seems the issue was resolved in 4.7.2 since my sample code works without any issues there.

**Comment by caesar1995** [comment]
@Uzza Did you use a proxy? If so, see comment here: https://github.com/dotnet/corefx/issues/27468#issuecomment-385540888

**Comment by Uzza** [comment]
@caesar1995 No proxy.

**Comment by robertmuehsig** [comment]
It seems that I had the same problem when using "CancellationToken.None" and the HttpClient:

![image](https://user-images.githubusercontent.com/756703/51253734-72eadd80-199f-11e9-8492-95128bff264d.png)

I'm running on .NET Core 2.2 (SDK 2.2.102) and using the HttpClientFactory.

This is more or less my setup:

Startup.cs:
```
services.AddHttpClient<IDatasourceInfoClient, DatasourceInfoClient>(client =>
            {
                client.BaseAddress = webApiBaseUrl;
            });
```

Startup.cs:
```
services.AddHttpClient<IDatasourceInfoClient, DatasourceInfoClient>(client =>
            {
                client.BaseAddress = webApiBaseUrl;
            });
```

Client Code like this:
```
    public interface IDatasourceInfoClient
    {
        Task<DatasourceInfo> GetAsync(Guid datasourceId, int? uiLcid, string authToken, CancellationToken cancellationToken);
    }

    public class DatasourceInfoClient : BaseClient, IDatasourceInfoClient
    {
        public DatasourceInfoClient(HttpClient client) : base(client)
        {
        }

        public Task<DatasourceInfo> GetAsync(Guid datasourceId, int? uiLcid, string authToken, CancellationToken cancellationToken)
        {
            string url = $"api/v1/DatasourceInfo/{datasourceId}?uiLcid={uiLcid}";
            return HttpClient.GetAsync<DatasourceInfo>(url, authToken, cancellationToken);

        }
    }

    public static class HttpClientExtensions
    {
        public static async Task<T> GetAsync<T>(this HttpClient httpClient, string url, string authToken, CancellationToken cancellationToken)
        {
            using (var request = new HttpRequestMessage())
            {
                request.Method = HttpMethod.Get;
                request.RequestUri = new Uri(url, UriKind.RelativeOrAbsolute);
                request.Headers.Authorization = AuthenticationHeaderValue.Parse("Bearer " + authToken);

                var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken);

                response.EnsureSuccessStatusCode();

                var textContent = await response.Content.ReadAsStringAsync();
                var result = ConvertResponse<T>(textContent);
                return result;
            }
        }
    }

```

The problem occurred when I was using this implementation:

```
        public Task<DatasourceInfo> GetAsync(Guid datasourceId, int? uiLcid, string authToken, CancellationToken cancellationToken = default)
        {
            string url = $"api/v1/DatasourceInfo/{datasourceId}?uiLcid={uiLcid}";
            return HttpClient.GetAsync<DatasourceInfo>(url, authToken, cancellationToken);

        }
    }
```

**CancellationToken cancellationToken = default** seems to be registred somewhere and never been removed.

My "workaround" (maybe this is even the right thing to do) is just to "pipe through" the CancellationToken from the Controller to my "HttpClient"-Invoke-Stuff.
