### ISSUE TITLE
AsyncTaskMethodBuilder<decimal> incorrectly caches decimal tasks with zero value

### ISSUE THREAD

**Issue by GSPP** [dotnet/corefx#27471]
`AsyncTaskMethodBuilder<decimal>` uses cached tasks for common zero values. There's a check for `(decimal)result == 0m`. The decimal type can store trailing zeroes, though. But `==` is blind to this: `0m == 0.0m`. (I also found no other way to get this comparison to return false. This is in my view an API omission.)

This makes caching observable and creates a wrong result:

        static void Main()
        {
            Console.WriteLine(Return(0m) + " / " + Return(0.0m)); // 0 / 0.0
            Console.WriteLine(ReturnAsync(0m).Result + " / " + ReturnAsync(0.0m).Result); // 0 / 0
        }

        static decimal Return(decimal value) => value;
        static async Task<decimal> ReturnAsync(decimal value) => value;

Both lines should return the same string. The async line is wrong.

I tested this on .NET 4.7.1 but it should apply to all .NET versions where this particular optimization landed.

**Comment by stephentoub** [comment]
> But == is blind to this

Interesting.  Isn't that the problem then?  That == is saying things are equal when they're not?  If == can't be trusted, the fix is to delete this line:
https://github.com/dotnet/coreclr/blob/66aec8606d2714dc1f0a558817bdb93a87bf35b1/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs#L822
```C#
(typeof(TResult) == typeof(Decimal) && default(Decimal) == (Decimal)(object)result) ||
```

cc: @tannergooding, @jkotas

**Comment by jkotas** [comment]
I do not think it is a problem. Similar situation exists for floats, e.g. `0.0 == -0.0`, but `0.0` and `-0.0` are not same bits.

**Comment by JonHanna** [comment]
That's also a problem if something using it considers the difference significant.

**Comment by tannergooding** [comment]
> That's also a problem if something using it considers the difference significant.

This isn't an issue unique to `AsyncMethodBuilder`, it is an issue with anything that relies on the equality operator for a type where two different bit representations are treated as equal.

The primitive types (float and double) as well as `System.Decimal` are just some of the core types where this issue is more likely to be encountered.
