### ISSUE TITLE
TimeZoneInfo.DisplayName values are not localized on Linux

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#2748]
Currently the DisplayNames of TimeZoneInfos on Linux are coming from the tzfile abbreviation file, which has the 3 or 4 character abbreviation for the time zone, ex. "PST" or "CST".

We should make use of the CLDR data in the ICU library to read the correct display name values for the TimeZoneInfo.

**Comment by mj1856** [comment]
This may also be a good time to fix localization for `TimeZoneInfo` in general.  Currently:

- `DisplayName`, `StandardName`, and `DaylightName` are localized by Windows, not by .NET `CurrentCulture` or `CurrentUICulture`.

- There's also no way to specify a different culture.

- The names provided by Windows are absurd in several cases, such as "GMT Daylight Time".

CLDR (via ICU, or otherwise) is a much more reliable source for this sort of data - and it's portable to Linux.
