### ISSUE TITLE
[Perf] Investigate System/Globalization benchmarks improvements in 2.1

### ISSUE THREAD

**Issue by valenis** [dotnet/corefx#27518]
[Perf] Investigate System/Globalization benchmarks improvements in 2.1

Several DateTimeCultureInfo and NumberCultureInfo tests show improvements in 2.1

**Comment by tarekgh** [comment]
@valenis is this something you already do? or are you asking the owners to do it? could you clarify?

**Comment by tarekgh** [comment]
also, we tag the issues with one area. so I have removed the globalization tag.

**Comment by danmosemsft** [comment]
@valenis @adamsitnik are you already planning to investigate?

If not can you please share a benchview link showing the improvement, and point to ETL for us?

**Comment by danmosemsft** [comment]
@tarekgh here is a view of the history of these tests (does it seem to you that we might need more perf tests for globalization?)

https://benchview/trendline?build_selector=latest&count=2000&aggregate=arithmeticMean&filterTail=one&filterVal=100&interval=INTERVAL_MIN_MAX&rtids=[957]&archids=[23]&mpids=[1292]&cfgids=[2706]&testids=[60201,60203,60202,60204,60212,60210,60209,60211,60208,60206,60205,60207,60213,60217,60215,60214,60216]&jobid=94205&

There are some pretty nice improvements. The biggest are some 50% wins from this CoreCLR update
https://github.com/dotnet/corefx/compare/454220d87dc118a6cb039ef5bd68707de20b79a5...dotnet:39742d3f1eac73898ad1b153141419e1f6e866d0

It is very likely these improvements are real but @tarekgh you might want to scan the CoreCLR changes in that interval to see what it was.

This issue is now completely actionable.

**Comment by tarekgh** [comment]
CC @AlexGhiondea @krwq 

@danmosemsft there is always areas for improvements :-) the question is, should this improvement be done in 2.1? One area that I think we should add perf tests for is string comparisons and searching.

**Comment by tarekgh** [comment]
@valenis @danmosemsft could you please clarify the ask here for this issue? Yes, I am aware of different improvements in the globalization area which is done by different people for a different feature. what investigation is this issue asking here?

**Comment by danmosemsft** [comment]
That is a question for @valenis : perhaps he wants to check the win is real and not a bad test? If so this issue can probably be just closed.

**Comment by tarekgh** [comment]
ok, the perf tests are reliable enough. I am going to close the issue and let @valenis reopen if he wants to do something more.
