### ISSUE TITLE
UnixSearchPatternFileValidChar test failed on Linux in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#27534]
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/80ee09145e8bfc94263218893ca47dcf67675ae5/workItem/System.IO.FileSystem.Tests/analysis/xunit/System.IO.Tests.DirectoryInfo_EnumFSI_str_str~2FUnixSearchPatternFileValidChar(valid:%20%5C%22%20%20%20%20%20%20%20%20%20%5C%22)
```
Unhandled Exception of Type Xunit.Sdk.ContainsException
Message :
Assert.Contains() Failure
Not found: /tmp/DirectoryInfo_EnumFSI_str_str_maxzoa0e.h5p/UnixSearchPatternFileValidChar_999_3530a72b/         
In value:  String[] []
Stack Trace :
   at System.IO.Tests.Directory_GetFileSystemEntries_str_str.UnixSearchPatternFileValidChar(String valid) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.IO.FileSystem/tests/Directory/GetFileSystemEntries_str_str.cs:line 1004
```

**Comment by danmosemsft** [comment]
@JeremyKuhne

**Comment by danmosemsft** [comment]
@stephentoub fwiw I try to include the distro for CI failures since once you rerun your tests that mc.dot.net link is no use. A link to the Jenkins job URL is another way to go back.

Counting the spaces in the text above 🔍 it seems it is `InlineData("         "),` that is failing. ie., it did not find a file whose name was all spaces.

The next inlinedata is a single space, it would be interesting to know whether that failed also. And the similar directory test.

**Comment by stephentoub** [comment]
According to the link, it was Fedora 26.

**Comment by danmosemsft** [comment]
Per discussion with @JeremyKuhne this hasn't happened since, given code churn this is not worth investigating further unless ith appens again.
