### ISSUE TITLE
Is the upcoming .net core 2.1 going to include System.Drawing.common?

### ISSUE THREAD

**Issue by e0003315** [dotnet/corefx#27537]
Does anyone know where i can find the list of libraries that are going to be included in each new release of .Net Core? I am trying to use System.Drawing.Common in particular. 

If it is not, does anyone know when it will be included?

**Comment by kasper3** [comment]
New additions usually get listed in release notes: https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.0-preview1.md

**Comment by e0003315** [comment]
ok thanks. Apparently, System.Drawing.Common is not inside. Does anyone know if there are currently plans to include it in, maybe in later versions?

**Comment by svick** [comment]
As far as I know, `System.Drawing.Common` will not become part of .Net Core. Instead, it will be part of [the Windows Compatibility Pack](https://blogs.msdn.microsoft.com/dotnet/2017/11/16/announcing-the-windows-compatibility-pack-for-net-core/). Though I suspect that won't be ready to be released by the time .Net Core 2.1 is released.

**Comment by karelz** [comment]
We do not have plans for post-2.1 yet. Which parts do you need and why (which scenarios)?

cc @danmosemsft @terrajobst

**Comment by danmosemsft** [comment]
@e0003315 the library is in the compat package that @svick linked to. It is just as supported as more popular parts of.NET Core you just have to reference the package. There are no plans to reference it by default. Does that answer your question?

**Comment by e0003315** [comment]
@danmosemsft @karelz I am trying to use system.drawing to convert icons to byte array for .netstandard2.0 project. I was looking at System.drawing.common since it support .netstandard 2.0. But I do not want to use it since it is still in the prerelease stage. 
Since it is not going to come out in the next 3 months, do you guys have any alternatives to convert icons to byte array for .net standard2.0??

**Comment by danmosemsft** [comment]
@e0003315 it is marked prerelease only because it will ship with 2.1 for engineering reasons. It is unlikely to get more changes before we release. Does that help?

Generally we don't recommend new code take a dependency on System.Drawing as it is a fairly legacy API. There are various 3rd party libraries that eg convert icons. I do not recall names: you could look around.

**Comment by e0003315** [comment]
@danmosemsft  When you say that it will ship with 2.1, does that mean that it will be released with 2.1? because @svick mention that it will not be shipped with 2.1.

**Comment by e0003315** [comment]
@danmosemsft if it is, may I know the tentative release date?

**Comment by danmosemsft** [comment]
I believe what @svick means is that it's not part of the "netcoreapp" package -- this is what you get referenced by default. By a narrow definition, that is .NET Core. 

We will mark the package "stable" when we ship .NET Core 2.1. This is primarily because it is building out of the same infrastructure. It is not dependent on .NET Core 2.1 proper.

We haven't shared a release date however we did just ship the Preview 1 this week so we are entering in the later phases of this cycle.

**Comment by e0003315** [comment]
@danmosemsft Does that mean that tentatively, it will be officially be released with .NET Core 2.1 at the end of this cycle which is in Q2 2018 (which is in the next 3 months)??

**Comment by danmosemsft** [comment]
@e0003315 I can't say (and I personally don't know for sure) -- we try to announce ship dates publicly on the .NET Blog and the dotnet/announcements repo. Why do you ask?

**Comment by e0003315** [comment]
@danmosemsft This way, I can plan whether I will want to wait and use System.drawing.common when it is released. If it is going to be release within the next few months, It still fits into my plan to implement it later.
But then again I am also looking into alternatives to not be dependent on system.drawings.
