### ISSUE TITLE
NamedPipeServerStream constructor allows MaxNumberOfServerInstances > 1 

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#2764]
The constructor for NamedPipeServerStream allows MaxNumberOfServerInstances > 1 and we even do the same validity checks (between 1-255) as we do on Windows. However, Unix Named pipes don't support more than one connection and an exception is thrown when more are attempted.

**Comment by ianhays** [comment]
So then the question becomes <i>when do we want to throw?</i> Our options are:
- Allow the user to create a pipe with a higher specified number of server instances and throw if they actually try to make more than one. Mimics the Windows constructor behavior and holds off on throwing until absolutely necessary.
- Throw an exception when trying to create a pipe with MaxNumberOfServerInstances > 1 so that the user knows right away that the behavior isn't supported on Unix.

The first option is only better if there are use cases where a pipe is created with MaxNumberOfServerInstances > 1 but no more than one are ever created. This is a narrow case and seems like it's begging for unexpected errors.

I vote we change the behavior to throw a PlatformNotSupportedException when MaxNumberOfServerInstances > 1 on Unix.

**Comment by ellismg** [comment]
/cc @stephentoub 

+1.  In this case, I prefer failing early.

**Comment by stephentoub** [comment]
> and an exception is thrown when more are attempted

Is that only in a specific case, or in general?  Can you share an example snippet that fails with an exception?  The following program works for me on both Windows and Unix:
```C#
using System;
using System.IO.Pipes;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static void Main()
    {
        int numServers = 4;
        const string serverName = "NamedPipeTest1";

        var servers = Enumerable.Range(0, numServers).Select(_ => new NamedPipeServerStream(serverName, PipeDirection.In, numServers)).ToArray();
        var clients = Enumerable.Range(0, numServers).Select(_ => new NamedPipeClientStream(".", serverName, PipeDirection.Out)).ToArray();

        var serverTasks = servers.Select((s, i) => Task.Run(() =>
         {
             s.WaitForConnection();
             byte[] buffer = new byte[0x1000];
             int numRead;
             while ((numRead = s.Read(buffer, 0, buffer.Length)) > 0)
             {
                 Console.WriteLine($"{i}: Received {numRead} bytes.");
             }
             Console.WriteLine($"{i}: Done.");
         })).ToArray();

        int counter = 0;
        var clientTasks = clients.Select(c => Task.Run(async () =>
        {
            c.Connect();
            while (true)
            {
                await Task.Delay(1000);
                int count = Interlocked.Increment(ref counter);
                c.Write(new byte[count], 0, count);
            }
        })).ToArray();

        Console.ReadLine();
    }
}
```
Are you seeing otherwise?

Now, there is a subtle difference here in behavior between our Windows and Unix implementations.  On Windows, each client in this example will establish a connection with a specific server.  In contrast, on Unix all communication is going through the same shared FIFO, so rather than there being a 1:1 connection being made, there's more of an any:any connection being made, and writes from a client may not be picked up by the same server each time.  That can be more clearly seen in this example:
```C#
using System;
using System.IO.Pipes;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static void Main()
    {
        int numServers = 4;
        const string serverName = "NamedPipeTest1";

        var servers = Enumerable.Range(0, numServers).Select(i => Task.Run(() =>
        {
            var s = new NamedPipeServerStream(serverName, PipeDirection.In, numServers);
            s.WaitForConnection();
            int byteRead;
            while ((byteRead = s.ReadByte()) >= 0)
            {
                Console.WriteLine($"{i} got data {byteRead}");
            }
            Console.WriteLine($"{i}: Done.");
        })).ToArray();

        var c = new NamedPipeClientStream(".", serverName, PipeDirection.Out);
        c.Connect();
        for (byte b = 0; ; b++)
        {
            Thread.Sleep(1000);
            c.WriteByte(b);
        }
    }
}
```
On Windows you'll see output like:
```
3 got data 0
3 got data 1
3 got data 2
3 got data 3
3 got data 4
3 got data 5
3 got data 6
3 got data 7
3 got data 8
3 got data 9
3 got data 10
3 got data 11
3 got data 12
3 got data 13
3 got data 14
3 got data 15
3 got data 16
3 got data 17
3 got data 18
3 got data 19
```
with the same one server instance getting all of the data, whereas on Unix you'll see output something like:
```
2 got data 0
2 got data 1
2 got data 2
0 got data 3
0 got data 4
0 got data 5
1 got data 6
1 got data 7
1 got data 8
2 got data 9
0 got data 10
1 got data 11
0 got data 12
1 got data 13
2 got data 14
1 got data 15
2 got data 16
1 got data 17
1 got data 18
2 got data 19
```
where each of the servers is connected and may be the one to pick up the data next from the client.

Preventing this entirely is going to be challening.  When a named pipe server is created today, we create a FIFO with the relevant name in the temporary directory.  Because it's a file on disk, we don't have a robust way of cleaning it up: we can try to remove it when the server is Disposed/finalized, but that may not always happen, e.g. if the process is torn down or crashes before then (and we can't just unlink it immediately after it's created, because then the client could never find it).  That means that creating a named pipe server needs to be robust against the FIFO already existing.  Today we just say if it already exists, use it, which is why multiple servers like this are supported.  If we were to instead see its existence as failure, that'd be problematic if a program ran, was torn down, and was then restarted, as attempting to recreate the server would fail.  If we were to instead delete the existing FIFO and create a new one would also be problematic, as another process could be using it.

All that said, that doesn't mean we have to allow MaxNumberOfServerInstances to be greater than 1.  We could artificially limit it to 1 in an attempt to minimize the visible differences between Windows and Unix (ironically, since we'd be throwing an exception on Unix in a case where we didn't on Windows); you could still work around it by having multiple servers from different processes, but at least this one process wouldn't be able to create multiple.

However, there are scenarios (similar to my previous examples) that could benefit from the functionality, so I'm not sure we want to limit it, especially since we wouldn't really be limiting it.

@ianhays, I'd like to better understand the scenarios that are failing / throwing today, and maybe we need to be more restrictive in what we disallow.

**Comment by ianhays** [comment]
I mispoke; I was internally correlating "undefined" with "unsupported" and came upon the incorrect assumption that the latter implied throwing. My understanding of ```maxNumberOfServerInstances``` and the use cases for it were faint, so I've done some more research and code-crawling before respond to your comment (sorry for the delay).

Some thoughts on scenarios:
<b>MaxNumberOfServerInstances is checked but never actually used on Unix</b>
```
string uniqueServerName = GetUniquePipeName();
using (NamedPipeServerStream server = new NamedPipeServerStream(uniqueServerName, PipeDirection.Out, 1, PipeTransmissionMode.Byte, PipeOptions.Asynchronous))
{
    new NamedPipeServerStream(uniqueServerName); // Throws an IOException on Windows, passes on Unix
}
```
It seems like we should either remove the checks around MaxNumberOfServerInstances, or we should find a way to enforce it. Since enforcing isn't going to be easy on Unix because of the issues you mentioned in your post, removing the checks would probably be better... but then the constructors with this unused variable will still exist and they'll still have an unused variable. 

<b>A few questions and comments:</b>

>Today we just say if it already exists, use it, which is why multiple servers like this are supported.

Isn't this the same as on Windows where multiple instances of NamedPipeServerStream("name") all point to the same NamedPipe object but have their own handles? Or did you mean that we use the same handle on Unix for multiple NamedPipeServerStreams that point to the same FIFO?

>If we were to instead see its existence as failure, that'd be problematic if a program ran, was torn down, and was then restarted, as attempting to recreate the server would fail.

Isn't the FIFO <i>eventually</i> cleaned up somehow (whether by us or the system) and the pipeName freed? Is this cleanup too slow for what you mentioned?

>If we were to instead delete the existing FIFO and create a new one would also be problematic, as another process could be using it.

Yeah, better to reuse than replace.

>However, there are scenarios (similar to my previous examples) that could benefit from the functionality, so I'm not sure we want to limit it, especially since we wouldn't really be limiting it.

I'm not convinced that limiting the Unix behavior is the correct decision either... FIFO pipes are already different enough from Windows Named Pipes that having behavior match in all cases isn't feasible (the above examples several such instances of this), but I also probably don't think it's right to enforce validity checks that aren't valid just for consistency's sake.

**Comment by stephentoub** [comment]
> It seems like we should either remove the checks around MaxNumberOfServerInstances, or we should find a way to enforce it

I'm assuming the checks you're referring to are these? https://github.com/dotnet/corefx/blob/master/src/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.cs#L105-L110

If so, I'm fine with removing (for Unix) the upper bound check.  We'd still want to verify that the value was either positive or -1.  Seems like we'd just want to add a ValidateMaxNumberOfServerInstances to each of the NamedPipeServerStream.Windows/Unix.cs files, implemented appropriately for each and then used here.

> but then the constructors with this unused variable will still exist and they'll still have an unused variable.

Worthy of a comment.  Not much more we can do about it than that.

> Isn't this the same as on Windows where multiple instances of NamedPipeServerStream("name") all point to the same NamedPipe object but have their own handles?

Yes.  But on Windows it goes away the moment the last handle to it closes; that's not the case here.

> Isn't the FIFO eventually cleaned up somehow (whether by us or the system) and the pipeName freed? Is this cleanup too slow for what you mentioned?

We're creating it in the user's temp folder.  Whenever that's cleared out, it'll go away.  So, yeah, waaaaay too slow ;)

**Comment by stephentoub** [comment]
Just to add to this, I realized in looking over the code this evening that we do actually attempt to clean up the FIFO file when the NamedPipeServerStream that created it gets disposed.  That's slightly different than how I remembered it and reported it above, and adds a small wrinkle here.  If we keep that behavior and we allow multiple servers to be created with the same name, it means that we could end up in a situation where multiple servers with that name are active but no clients can find them because the FIFO has been unlinked by the initial server that created it.  That's not good.  The alternative is to leave that temp file around, which isn't great, but it seems like a better option.

**Comment by ianhays** [comment]
> I'm assuming the checks you're referring to are these?

Yup. There are also some Debug.Asserts for maxNumberofServerInstances in NamedPipeServerStream.Unix.

> Seems like we'd just want to add a ValidateMaxNumberOfServerInstances to each of the NamedPipeServerStream.Windows/Unix.cs files, implemented appropriately for each and then used here.

That is along the lines of what I was thinking as well. I'll do that today and add some Unix tests with higher numbers.

>The alternative is to leave that temp file around, which isn't great, but it seems like a better option.

Three options come to mind:
1. (current) Multiple servers are created and linked to the same FIFO. When the original server that created the FIFO is disposed, we cleanup the FIFO along with it. All other servers now link to a nonexistent FIFO and no clients can connect to those servers.
2. Multiple servers are created and linked to the same FIFO. We remove all attempts to clean up a disposed FIFO and leave it in the temp directory. This way, multiple servers from the same FIFO will be unaffected by the disposal of one another. However, we will have zombie FIFOs laying around after they are no longer needed.
3. Artificially limit number of servers per FIFO to one. Will not work cross-process/cross-machine and if used in that way will be subject to the same issues from (1). If we assume same-process, we can leave the current behavior of removing the FIFO when the server stream that created it is disposed. Limits the Unix implementation to one server per fifo per process, but solves the connection issue in (1) although only for same-process server creation.

(2) seems like the best option, but I'm not sure how serious of an issue it will be to leave around an unused FIFO.

**Comment by stephentoub** [comment]
> but I'm not sure how serious of an issue it will be to leave around an unused FIFO

I don't think it's great, but given the options, I think it's what we should go with.
