### ISSUE TITLE
IValueTaskSource doesn't work on netcoreapp2.0

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#27714]
Strangely, if you reference System.Threading.Tasks.Extensions on a .NET Core 2.0 project IValueTaskSource doesn't exist. The netcoreapp2.0 folder in the nuget package has a `_._` and ValueTask gets resolved from the shared framework instead of the package (System.Threading.Tasks.Extensions is in Microsoft.NETCore.App 2.0 but an older version)

This leads to the following error when trying to use ValueTask with IValueTaskSource on .NET Core 2.0 projects:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Could not load type 'System.Threading.Tasks.Sources.IValueTaskSource`1' from assembly 'System.Threading.Tasks.Extensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.) ---> System.TypeLoadException: Could not load type 'System.Threading.Tasks.Sources.IValueTaskSource`1' from assembly 'System.Threading.Tasks.Extensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at System.IO.Pipelines.Pipe..ctor(PipeOptions options)
   at ConsoleApp41.Program.<DefaultPipe>d__1.MoveNext() in C:\Users\dfowler\documents\visual studio 2017\Projects\ConsoleApp41\ConsoleApp41\Program.cs:line 20
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ConsoleApp41.Program.Main(String[] args) in C:\Users\dfowler\documents\visual studio 2017\Projects\ConsoleApp41\ConsoleApp41\Program.cs:line 16
```

Seems like this package should lift on netcoreapp2.0 instead of skip. I know we had other instances of this in the netcoreapp2.0 timeframe (things that shipped in box that were then taken out of band). This looks like another category of this issue.

/cc @stephentoub @weshaggard @ericstj @terrajobst @KrzysztofCwalina

**Comment by stephentoub** [comment]
Wes, Eric, how do I fix this?

**Comment by jkotas** [comment]
Related #25932

**Comment by ericstj** [comment]
When you made this change https://github.com/dotnet/corefx/commit/6d1671b2cfcf130b7bc6c059bb0508073426532a#diff-ef60abd9cf887b950d31edcb03b6f485 you changed the netstandard2.0 ref.  If that was your intention you need to implement that surface area on all netstandard2.0 frameworks.  Right now you're not including an implementation for NCA2.0 nor UAP, which you'll need to add if you want to ref the ns2.0 surface area.  Do so by removing the [placeholders](https://github.com/dotnet/corefx/commit/6d1671b2cfcf130b7bc6c059bb0508073426532a#diff-ef60abd9cf887b950d31edcb03b6f485) and potentially adding a [suppression](https://github.com/dotnet/corefx/blob/35e0a7fcc693dbb73996e8dae5d8841a4ba00d6f/src/System.Collections.Immutable/pkg/System.Collections.Immutable.pkgproj#L18), though that shouldn't be needed if you correctly rev'ed the minor assembly version.  Looking at release/2.0.0 we didn't actually ifdef anything for nca2.0 (this wasn't a partial facade at that point) so I think you should be good to just allow the ns2.0 implementation apply to nca2.0.  /cc @joperezr

**Comment by stephentoub** [comment]
> If that was your intention you need to implement that surface area on all netstandard2.0 frameworks

My intention is that:
- the System.Threading.Tasks.Extensions.dll assembly that's a partial facade works with .NET Core 2.1.
- the System.Threading.Tasks.Extensions.dll assembly that's not a partial facade is used everywhere else.

> though that shouldn't be needed if you correctly rev'ed the minor assembly version

I didn't rev any versions, didn't know I needed to.  In general in this release we haven't been changing any version numbers when we've added APIs, but maybe that's because we were only adding APIs to things that already had their version number rev'd?  I see now that https://github.com/dotnet/corefx/pull/25932 happened while I was out.

> so I think you should be good to just allow the ns2.0 implementation apply to nca2.0

How?

**Comment by weshaggard** [comment]
>the System.Threading.Tasks.Extensions.dll assembly that's not a partial facade is used everywhere else.

That isn't going to work for .NET Core 2.0 given these were moved inbox and type-forwarded into CoreLib. We cannot use an OOB for this library on .NET Core 2.0 because ValueTask is an exchange type and things will not unify correctly. 

We are going to need to decide how far we want to support these APIs. Our general rule going forward is to only support them on the new platforms which for these new APIs would mean we need a netcoreapp2.1 ref assembly for this library and we don't add them to the netstandard ref. If we want to support these new APIs on older platforms then we have some work to do to figure out how to go about that.

**Comment by ericstj** [comment]
@weshaggard I think that happened in 2.1, not 2.0.  In 2.0 I still see this is a simple assembly with no type forwards.

Note that because you are pushing these types down into System.Runtime on NETCoreApp 2.1 this is your last chance for adding API to the netstandard2 ref for this assembly.  After 2.1 ships you won't be able to deliver new API out of band easily since all the types have been pushed down, as @weshaggard mentions.

To make the changes, you can bump the minor assembly version, then remove the `InboxOn...` entries in the pkgproj and add just one for netcoreapp2.1.

FWIW the general rule for assembly versioning when adding API is to ask: did I add API for all the latest frameworks supported by this package?  If so, bump the minor version.  If not then you shouldn't, the revision will be bumped as part of the release already.

**Comment by weshaggard** [comment]
>@weshaggard I think that happened in 2.1, not 2.0. In 2.0 I still see this is a simple assembly with no type forwards.

Your correct. I was going based on my incorrect comments in https://github.com/dotnet/corefx/pull/25932. The library was inbox on .NET Core 2.0 but the types were not forwarded down yet so there is the opportunity to override the library OOB on .NET Core 2.0. After 2.1 ships though as @ericstj states you will no longer be able to change the netstandard ref.

**Comment by stephentoub** [comment]
> We are going to need to decide how far we want to support these APIs.

Libraries that target netstandard20, like pipelines, channels, and ASP.NET, need this.  If we can't make these changes, then we're going to need to scrap the changes to ValueTask, effectively obsolete it, and create new types in its stead that we then use everywhere we're now using ValueTask.

> I think that happened in 2.1, not 2.0. In 2.0 I still see this is a simple assembly with no type forwards.

The type forwards / partial facade-ness was added in 2.1 in support of being able to use ValueTask in public APIs on methods in Corelib, e.g. Stream.  I believe System.Threading.Tasks.Extensions.dll shipped inbox in 2.0 because some libraries used it internally, but it wasn't part of any public surface area until 2.1.

> this is your last chance for adding API to the netstandard2 ref for this assembly

Ok.  It's a good reminder, though I'm not entirely sure what the ramifications of that are.  If we want to use types from public API that's in corelib, then it seems this is a built-in limitation, regardless of what assembly the APIs live in, right?  It wouldn't matter, for example, if we decided to use a new CoolThing type instead of ValueTask; no matter where we put CoolThing, we would have a similar limitation on every API in CoolThing's assembly?

Also, once 2.1 ships, we can't rev the netstandard2 ref for this assembly, but we can continue to add new APIs for netcoreapp2.1 and beyond, and if/when there's a netstandard2.1, we could add the APIs to that, correct?

**Comment by weshaggard** [comment]
> we would have a similar limitation on every API in CoolThing's assembly?

Correct.

>Also, once 2.1 ships, we can't rev the netstandard2 ref for this assembly, but we can continue to add new APIs for netcoreapp2.1 and beyond, and if/when there's a netstandard2.1, we could add the APIs to that, correct?

Correct.

>Ok. It's a good reminder, though I'm not entirely sure what the ramifications of that are

It basically means what you stated that you will not be able to add new APIs (at least members) that can be consumed by a netstandard2.0 library.

**Comment by stephentoub** [comment]
Ok, thanks.  I'll give this a go:
> To make the changes, you can bump the minor assembly version, then remove the InboxOn... entries in the pkgproj and add just one for netcoreapp2.1.

Also, do we have the ability in corefx to update Configuration.props for a test library to have it run on netcoreapp2.0, not just targeting that API surface area, but actually running on that shared framework such that it would have caught this?

**Comment by weshaggard** [comment]
>Also, do we have the ability in corefx to update Configuration.props for a test library to have it run on netcoreapp2.0, not just targeting that API surface area, but actually running on that shared framework such that it would have caught this?

No we don't have this ability. We have chosen to only allow running tests on the latest versions of each of the platforms to avoid even more complexity.

**Comment by davidfowl** [comment]
@stephentoub are you looking at this?

**Comment by stephentoub** [comment]
> are you looking at this?

https://github.com/dotnet/corefx/pull/27760/
