### ISSUE TITLE
[UWP] Windows Auth Issue from UWP Applications

### ISSUE THREAD

**Issue by luvhsail** [dotnet/corefx#27761]
Hi @rmkerr 
As discussed I have created a sample project, you may download it from the repository path below.
The code as three projects, a WebAPI with windows Authentication and two consumers that have more or less the same code. The console application is able to make the call while the UWP gets a 500 error. 

Another thing that I noted is if I remove the Authorize attribute from the API it works fine for both.

https://github.com/luvhsail/Samples.git

**Comment by davidsh** [comment]
@luvhsail Looking at the code of the repro you posted, I think I understand the problem with the UWP app.

Your repro is trying to pass Default Credentials for the Windows Authentication to connect to your website/service.  I see this in your code:

```c#
hand.UseDefaultCredentials = true;
```

In order for a UWP app to send Default Credentials to a server, there are 2 requirements.

First, the capability for EnterpriseAuthentication must be listed in the manifest.  I see that your project has that:

```xml
<uap:Capability Name="enterpriseAuthentication" />
```

Second, this website/DNS name for the server must be considered to be in the Local Intranet zone.  This is a non-obvious requirement. But it is due to the current implementation of the UWP HTTP stack which uses WinRT Windows.Web.Http APIs (which builds on native Windows WinINet).  You need to list the DNS name of the server in the Local Intranet zone by modifying the Internet Explorer settings.

For example:
![image](https://user-images.githubusercontent.com/7684835/39677167-4779d742-512b-11e8-96fc-7d82e869ef9d.png)

![image](https://user-images.githubusercontent.com/7684835/39677171-59fdd148-512b-11e8-9799-5debb1eac55f.png)

![image](https://user-images.githubusercontent.com/7684835/39677177-6c699d26-512b-11e8-81e7-f976c05dc774.png)

This is a current limitation of the UWP HTTP stack. We are considering ways to mitigate this in the future.

**Comment by davidsh** [comment]
Please make the modifications as indicated above for your app/service.  If your are still having problems after that, then please reply back to this issue. Closing for now.

cc: @karelz @rmkerr

**Comment by davidsh** [comment]
Note that using explicit credentials doesn't require listing the DNS name in the Local Intranet zone. But not sure if that is a possibility for your app.
