### ISSUE TITLE
System.IO.File.Open should open the file with shared write access

### ISSUE THREAD

**Issue by JackGrinningCat** [dotnet/corefx#27816]
Hi, 

following two lines to fail, because OpenRead does not share the write access, even if it does not need/use and configure it beforehand.

var stream1 = new FileStream(filename, FileMode.Create, FileAccess.ReadWrite, FileShare.Read);
var stream2 = File.OpenRead(filename);

Kind regards

p.s. I write here, because I do not know a better place.

**Comment by stephentoub** [comment]
The docs for File.OpenRead state:
"This method is equivalent to the FileStream(String, FileMode, FileAccess, FileShare) constructor overload with a FileMode value of Open, a FileAccess value of Read and a FileShare value of Read."

**Comment by danmosemsft** [comment]
@JackGrinningCat to enlarge on that, your FileStream is indicating it wishes to write (FileAccess.ReadWrite) and will allow others to read (FileShare.Read). Your File.Open read is indicating it wishes to read (FileAccess.Read), and will allow others to read -- but not write (FileShare.Read). Because the file is already open for read/write, the operating system rejects the attempt to open another handle to the file with those conditions.

Please reactivate if this doesn't answer your question.
