### ISSUE TITLE
Add a way to create a suspended Process

### ISSUE THREAD

**Issue by radekm** [dotnet/corefx#2782]
It seems that there is no way to create a suspended `Process` and resume it later.

Ability to create a suspended process is useful when you want to run the process and its children in a job object. If the process isn't created as suspended it may create child processes before it is assigned to the job object which means that these child processes won't be assigned to the job object.

**Comment by pallavit** [comment]
Windows does support creating suspended processes using CREATE_SUSPENDED flag, however to be honest I am not sure if this scenario makes sense cross-plat or can even be implemented across the board. One other thing to consider would be to double check if this will have any impact on the process debuggability, since ResumeThread and SuspendThread are also used by Debuggers. /cc:@stephentoub @ellismg on the cross-plat aspect of it.  Do you know of a way to create suspended processes in Linux? My understanding is once created one can send SIGSTOP and SIGCONT signals to suspend and resume processes but the state can't be controlled at the creation time. Also, do you think this scenario adds value cross-plat?

**Comment by radekm** [comment]
> Do you know of a way to create suspended processes in Linux?

After `fork`ing the child process could send SIGSTOP to itself before doing `exec`. Another approach is to use `ptrace` like `linux_create_inferior` function from GDB ([`gdb/gdbserver/linux-low.c`](http://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=gdb/gdbserver/linux-low.c;h=41ab510fa4ac5654f101f08efb68e26b5bc5dbd7;hb=HEAD#l856)). It seems that the child process calls `ptrace (PTRACE_TRACEME, 0, (PTRACE_TYPE_ARG3) 0, (PTRACE_TYPE_ARG4) 0)` before doing `execv`.

**Comment by whoisj** [comment]
It would be good to support de-elevated processes as well (ala Safer*Level handles on Windows). Not sure these options can all be mapped to every OS.

Is it better to have OS specific versions?

**Comment by Priya91** [comment]
@radekm Is there a cross-plat way to support this scenario across Windows Onecore, LInux and OSX? If so can you provide an API proposal.

**Comment by GrabYourPitchforks** [comment]
Closing this issue as it seems to have gone stale. If there's demand for this functionality, please reopen the issue.
