### ISSUE TITLE
DBConnectionStringBuilder doesn't correctly serialize empty strings

### ISSUE THREAD

**Issue by Porges** [dotnet/corefx#27849]
`DBConnectionStringBuilder` serializes empty strings as `"key="` instead of `"key=''"` (or `"key=\"\""`). This is incorrect as this is the syntax to _remove_ a key from a connection string (e.g. `"key=foo;key="` will parse as an empty connection string).

Demo code:

```csharp
var builder = new DbConnectionStringBuilder();
builder.ConnectionString = "empty=''";

Console.WriteLine(builder.ContainsKey("empty"));
// true

Console.WriteLine(builder.ConnectionString);
// prints "empty="

// re-parse the conn string
builder.ConnectionString = builder.ConnectionString;

Console.WriteLine(builder.ContainsKey("empty"));
// false

Console.WriteLine(builder.ConnectionString);
// prints "" (empty string)
```

Expected outputs when this is fixed would be that the last 2 outputs are the same as the first 2 outputs.

**Comment by divega** [comment]
Thanks @Porges for raising this. Nice catch! I theory we could change empty key values to be serialized as `''` but we don't require values in connection strings to be quoted, so wouldn't it be strange if `"empty="` meant something different form `"empty=''"`?

Based on this, I think there is another interpretation for the issue:

In the connection string "mini-language", there isn't a distinction between an empty key and a missing key. Hence, I think I would expect the first 2 outputs to also be `false`, and `""`.

Regardless of the interpretation, am I right to assume that this is not blocking anything for you, but you just found the inconsistency to be annoying and decided to report it?

**Comment by divega** [comment]
Copying @bricelam @roji @saurabh500 @ajcvickers, in case any of them has an opinion on this.

**Comment by Porges** [comment]
Hi @divega 

`empty=''` and `empty=` already mean different things - the latter unsets a previously set value. (I assume this is so that you can remove defaults or something like that.)

For example:

```csharp
var builder = new DbConnectionStringBuilder();
builder.ConnectionString = "key1=1;key2=2;key1=";
Console.WriteLine(builder.ConnectionString);
// prints "key2=2", as `key1=` removes the `key1` value
```


> Regardless of the interpretation, am I right to assume that this is not blocking anything for you, but you just found the inconsistency to be annoying and decided to report it?

Yes, I was writing some tests for my own implementation and found this. 🙂

**Comment by divega** [comment]
> the latter unsets a previously set value

Are you sure that what you are seeing doesn't just mean that the last setting wins?

**Comment by Porges** [comment]
If you dump the list of keys, only `key2` is present.

**Comment by divega** [comment]
Ok, I get that this is the behavior you observe immediately, hence currently `"empty="` does mean something different form `"empty=''"`. 

However the behavior after you roundtrip to the ConnectionString property is inconsistent, and what I am saying is that if we made `"empty=''"` mean exactly the same as `"empty="`, then the behavior would become consistent. 

And I like this alternative more because I don't believe they should be different in the first place, as quotes are in general optional for key values.

All that said, probably this just an academic exercise :smile:

**Comment by Porges** [comment]
Yes, either solution works for me :grin:

**Comment by roji** [comment]
Agree with @divega that `empty=` should simply be processed as the absence of the key, i.e. that `ContainsKey("empty")` should return false for string `empty=`. I can't imagine any practical usefulness for specifying a key without a value, and the syntax distinguishing an empty value from a non-existent key would be very specific as said above (i.e. quotes aren't used anywhere else).

**Comment by divega** [comment]
**System.Data triage:** Although in principle we are not against changing the behavior so that `empty=''` starts having the exact same semantics as `empty=` (i.e. Contains returns false, the key doesn't get rendered in the connection string again), it doesn't seem important enough for us to address it or to spend much time doing a deeper analysis on whether this could break anything. 

I am going to go ahead and close the issue but if we see more feedback in the future we can reconsider it.
