### ISSUE TITLE
ExportFactory works differently between MEF/Portable MEF

### ISSUE THREAD

**Issue by molinch** [dotnet/corefx#27848]
I am currently porting code from MEF to portable MEF (System.Composition).
There is a major difference with ExportFactory.

Before if an export was defined as PartCreationPolicy.Any (which was the default) when ExportFactory was used, it would always return a new instance. Furthermore Any was very similar to Shared: injecting the dependency in normal scenarios would always return the same instances.

Now with Portable MEF, there is no such concept as .Any.
If the dependency is exported as Shared, then we always get the same instance, even when using the ExportFactory to control its lifetime.
If the dependency is exported as NonShared, then we always get a new instance.

Is there a way to have back the behaviour of .Any?

**Comment by molinch** [comment]
Repro here: https://gist.github.com/molinch/5386ee5c0ed56e4ccc39ab0b8757ca58

**Comment by molinch** [comment]
Based on this test, it seems like it's on purpose:
https://github.com/dotnet/corefx/blob/6bac4088aadf09a6e4864c78979dc54290015b9d/src/System.Composition/tests/ExportFactoryTests.cs#L110

However that's clearly a breaking change.

**Comment by danmosemsft** [comment]
@weshaggard do you know the answer?

**Comment by weshaggard** [comment]
It has been a long time since I've looked at this code but I do believe the change is intentional. Having the "Any" option can break some of the assumptions for things that are intended to be Shared. MEF v2 makes this more explicit to avoid some of those complications.

Out of curiosity why are you moving to System.Composition/MEF v2? If you want this behavior you there isn't anything wrong with sticking with MEF v1 which still works good for a lot of extensibility scenarios. MEF v2 is mostly targeting ASP.NET through-put scenarios and improves the through-put performance by pre-computing the graph which is difficult with MEF v1 because it was too extensible in some scenarios. So if you aren't trying to maximize your through-put then I would suggest not spending the time to move to MEF v2.

**Comment by molinch** [comment]
@weshaggard Basically we have a huge WPF app, and while benchmarking it we figured out that a lot of time is spent by MEF: 
- creating object graph
- resolving dependencies

For this reason we thought it would be a good idea to move to MEF2.
Furthermore it seems to be more "future proof".

What is your opinion on these?

**Comment by molinch** [comment]
Btw, with MEF2 we save 3 seconds during startup.
So that's a huge gain.

**Comment by weshaggard** [comment]
>Btw, with MEF2 we save 3 seconds during startup (that's a huge gain for a client app).

That is great to hear and if you have all your scenarios covered then by all means move to MEF v2. 

>It would be great to know more about core changes, that lead to these performance improvements.

The primary improvements come at the cost of cutting features like rejection and our general primitive model. MEF v2 moved to a pure type-based model which uses expression trees to compile and cache the graph which is why through-put is better. I'm sure depending on your usage scenarios even a client app can get some benefits but it just isn't as dramatic. Overall MEFv2 is a breaking change because it changes defaults and loses some of the scenarios that MEFv1 (rejection, etc) which is why we needed to rename the types and make it a parallel stack, but it does gain performance because of its simplification. 

As for this particular issue of Any are you able to make your scenarios work without it?

**Comment by molinch** [comment]
Thanks for the detailed feedback

Yes we managed to get rid of Any by deeply looking at our usages and refactoring code when needed.
This was definitely not straight forward, 25 years old app so huge code base, but as a result the code is cleaner and faster. So no need to keep this open.

We could convert a lot of code thanks to Roslyn!
- Adding Shared attribute when there wasn't any, removing NonShared policy, ...
- Making imported constructor and injected properties public
