### ISSUE TITLE
SocketHttpHandler is failing to parse properly proxy environment variables with special characters.

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#27871]
Consider situation like:

export all_proxy='corefx\foo:SecretPass#1@clrperftst003:3128'

when using curl or curl handler from c# auth to proxy works as expected. 

However when I switch to SocketHttpHandler, it fails to parse the string because we use Uri parsing function and that does not like the special characters. With that we fail to instantiate HttpEnvironmentProxy and handler attempts direct connections ignoring proxy setting. 
Also note, that we only split user and password. That may possibly create troubles with certain authentication schemes. 

Also note, that curl works properly if the string is URL encoded. SocketHTTPHandler also fails in such case.

export all_proxy='corefx%5Cfoo:SecretPass%231@clrperftst003:3128'

**Comment by pjanotti** [comment]
Did we start to support those env variables because we were using libcurl before and now we need to keep supporting them to not break code targetting 2.0? It seems odd to do this type of thing via environment variable...

**Comment by wfurt** [comment]
yes @pjanotti. The goal is to make new HttpHandler behave as old CurlHandler. 
There is #23313 to possibly read credentials from a file. Curl can do that now, but HttpCurlHandler does not. There is always option to set credentials explicitly if anybody needs to.

**Comment by stephentoub** [comment]
> Did we start to support those env variables because we were using libcurl before and now we need to keep supporting them to not break code targetting 2.0? It seems odd to do this type of thing via environment variable...

That's not actually my top goal here.  Rather, libcurl supports these because they're a defacto standard for this kind of thing on unix, e.g.
https://wiki.archlinux.org/index.php/proxy_settings
https://msdn.microsoft.com/en-us/library/hh272656(v=vs.120).aspx
https://docs.cloudfoundry.org/cf-cli/http-proxy.html
https://unix.stackexchange.com/questions/212894/whats-the-right-format-for-the-http-proxy-environment-variable-caps-or-no-ca
etc.
