### ISSUE TITLE
Socket async callbacks on Windows process the callback's ExecutionContext twice

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#27892]
We have logic to capture the ExecutionContext and restore it for callbacks in both the IAsyncResult path and the SocketAsyncEventArgs path.  However, on Windows, we are already getting dispatched to the correct ExecutionContext by the Overlapped infrastructure, which on .NET Core always handles the execution context capture and dispatch.

On Unix, the equivalent infrastructure in SocketAsyncContext.Unix.cs does not handle ExecutionContext, so it's only being handled once.

We should add ExecutionContext capture and dispatch to SocketAsyncContext.Unix.cs and then remove it from the higher layers in the Socket stack.

The impact here is small, but every bit helps.

**Comment by stephentoub** [comment]
> We should add ExecutionContext capture and dispatch to SocketAsyncContext.Unix.cs and then remove it from the higher layers in the Socket stack.

I took a look at this, and I actually think we should do the opposite, try to avoid capturing in the lower levels and then only capture at the API level if the API needs it.  For example, async Task/ValueTask-returning methods always flow execution context across await points, and then tell the awaiter it doesn't need to flow context by calling UnsafeOnCompleted instead of OnCompleted.  So in such a common case we can avoid doing any extra ExecutionContext capture and flow in SocketAsyncEventArgs used by, for example, the Task and ValueTask returning async methods.

The capturing that's done in the lower levels today also appears to just capture the ExecutionContext once when the PreAllocatedOverlapped is created, and that captured context is then used to run all continuations, which won't properly flow changes made to the context from where the operation is initiated.

**Comment by geoffkizer** [comment]
That all makes sense.

We can remove the lower-level capture by doing UnsafePack instead of Pack.

**Comment by stephentoub** [comment]
> We can remove the lower-level capture by doing UnsafePack instead of Pack.

Yeah, though it's hidden away from us.  I plan to just suppress flow while creating the PreAllocatedOverlapped, which internally calls Pack.

**Comment by geoffkizer** [comment]
Seems fine.

**Comment by geoffkizer** [comment]
BTW, somewhere along the way ExecutionContext got changed so that EC.Capture no longer returns null when you're in the default context.

This means that we aren't avoiding the EC.Run call in places like SAEA.FinishOperationAsyncSuccess.  And in fact I'm not sure how we would avoid it, since we can't seem to detect default EC anymore.  (We can detect SuppressFlow, since that returns null for EC.Capture.)

Not sure this will matter once you've changed this, but I thought I'd mention it...

**Comment by geoffkizer** [comment]
Though weirdly, it looks like in some cases it may return the default EC even if flow is suppressed...

```csharp
        public static ExecutionContext Capture()
        {
            ExecutionContext executionContext = Thread.CurrentThread.ExecutionContext;
            return
                executionContext == null ? Default :
                executionContext.m_isFlowSuppressed ? null :
                executionContext;
        }
```

**Comment by stephentoub** [comment]
> BTW, somewhere along the way ExecutionContext got changed so that EC.Capture no longer returns null when you're in the default context.

I don't remember it ever being the case that Capture would return null in the default context.

> it looks like in some cases it may return the default EC even if flow is suppressed

For flow to be suppressed, Thread.CurrentThread.ExecutionContext can't be null, because whether it's suppressed is stored on that instance.

**Comment by geoffkizer** [comment]
> I don't remember it ever being the case that Capture would return null in the default context.

Probably I'm misremembering, then.  Anyway, I'll leave you alone now... :)

**Comment by stephentoub** [comment]
:smile:
