### ISSUE TITLE
TestSchedulerNesting occasionally fails

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#2797]
The test for nested ConcurrentExclusiveSchedulerPair's seems to fail very occasionally, about 1-5 times per 1000 runs in my machine. The root cause seems to be that some of the tasks are being scheduled to run after the scheduler pair has been completed (after the Complete() method is called). Based on the structure of the test, this shouldn't necessarily be possible, as all of the previous tasks are Wait()'d before the call to Complete(). There may be a product bug here.

**Comment by stephentoub** [comment]
Looked into what's going on here, and the behavior is by-design / the test is faulty.  The relevant code/comment is here: https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/Tasks/ConcurrentExclusiveSchedulerPair.cs#L277-L283 .  The test effectively has two schedulers, one layered on top of the other, and it's ripping out the underlying scheduler while the one above it is still potentially using it.  Just because the one on top has completed all of the tasks queued to it doesn't mean that it's done with the underlying scheduler, as it may still have some tasks of its own to queue for housekeeping purposes.  In short, it's not valid to complete the underlying scheduler until the one layered on top of it has itself completed.

I'll submit a PR to fix the test and re-enable it.
