### ISSUE TITLE
System.Net.Tests.HttpRequestStreamTests failures with SocketsHttpHandler

### ISSUE THREAD

**Issue by caesar1995** [dotnet/corefx#27996]
These tests only fail on OSX in `HttpListener` if set SocketsHttpHandler as the default handler:

[Read_FullLengthAsynchronous_Success(transferEncodingChunked: False, text: \"Non-Empty\") 
Read_FullLengthSynchronous_Success(transferEncodingChunked: False, text: \"Non-Empty\")
Read_NotEnoughThenCloseAsynchronous_Success(transferEncodingChunked: False)](https://mc.dot.net/#/user/caesar1995/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/7e55e2a154087633b5f365bb05310e1700e835a4/workItem/System.Net.HttpListener.Tests)

[Read_FullLengthAsynchronous_PadBuffer_Success(transferEncodingChunked: False, text: \"Non-Empty\") 
Read_FullLengthAsynchronous_Success(transferEncodingChunked: False, text: \"Non-Empty\")
Read_NotEnoughThenCloseAsynchronous_Success(transferEncodingChunked: False)
Read_TooMuchAsynchronous_Success(transferEncodingChunked: False)
Read_TooMuchSynchronous_Success(transferEncodingChunked: False)](https://mc.dot.net/#/user/pjanotti/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/fc263ec2f48b14a381d2c5ebbbfb75e3163d3891/workItem/System.Net.HttpListener.Tests)

These failures cannot be repro-ed consistently.

**Comment by caesar1995** [comment]
We may need to look into it for 2.1.

**Comment by caesar1995** [comment]
Those tests will also fail on CentOS intermittently. (#28049)

**Comment by danmosemsft** [comment]
These failed on a CHK run on Fedora, Debian, Redhat.

Read_FullLengthAsynchronous_PadBuffer_Success(transferEncodingChunked: False, text: \"Non-Empty\") 
Read_FullLengthAsynchronous_Success(transferEncodingChunked: False, text: \"Non-Empty\") 
Read_FullLengthSynchronous_Success(transferEncodingChunked: False, text: \"Non-Empty\")


https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180314.07/workItem/System.Net.HttpListener.Tests

**Comment by danmosemsft** [comment]
Assert.Equal() Failure
Expected: 9
Actual:   6

**Comment by wfurt** [comment]
I think this is bad test:

                byte[] buffer = new byte[expected.Length];
                int bytesRead = await context.Request.InputStream.ReadAsync(buffer, 0, buffer.Length);
                Assert.Equal(expected.Length, bytesRead);
                Assert.Equal(expected, buffer);


The documentation is pretty clear that  ReadAsync may return less data than asked for e.g. expecting everything in on chunk is wrong.

However why it did work before before? 
SocketsHttpHandler/HttpConnection.cs:
        private const int InitialReadBufferSize =
#if DEBUG
            10;
#else
            4096;
#endif

So we will fragment IO to very small operations in SocketHandler with DEBUG enabled. That does increase likelihood that we will not succeed in single read. You can also see it when capturing packets for the test (or simply using debug version of the assembly). For the test we send 62 packets instead of 50 e.g. ~20% difference. 

I can wrap the code above in some loop to read again if needed but this may be common pattern and fix may be tedious. It may be worth of increasing buffer limit to something more reasonable or create some test helper. 

Any thoughts @geoffkizer or @stephentoub ?

**Comment by geoffkizer** [comment]
> The documentation is pretty clear that ReadAsync may return less data than asked for e.g. expecting everything in on chunk is wrong.

Yep, I agree.

> I can wrap the code above in some loop to read again if needed but this may be common pattern and fix may be tedious. It may be worth of increasing buffer limit to something more reasonable or create some test helper.

I'd create some sort of test helper, e.g. an extension method like ReadToEndAsync on Stream.  As you say, this is pretty common and we should handle this consistently.

TextReader actually has a ReadToEndAsync() method already, but we're not using TextReader here.  But we can do something similar.
