### ISSUE TITLE
HttpClientUsesSslCertEnvironmentVariables() test will fail on Linux with SocketsHttpHandler

### ISSUE THREAD

**Issue by caesar1995** [dotnet/corefx#28002]
The [HttpClientUsesSslCertEnvironmentVariables test](https://github.com/dotnet/corefx/blob/eb892471f8691dad65ff47f5b12ddc8d378ae460/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ServerCertificates.Unix.cs#L79) will fail on Linux with SocketsHttpHandler for these two test data:

`[InlineData(false, false, true, true, true)]`
`[InlineData(false, false, true, false, true)]`

```diff
        [Theory]
        [PlatformSpecific(~TestPlatforms.OSX)] // Not implemented
        [InlineData(false, false, false, false, false)] // system -> ok
        [InlineData(true, true, true, true, true)]      // empty dir, empty bundle file -> fail
        // It is enough to override the bundle, since all tested platforms don't have a default dir:
        [InlineData(false, false, true, true, true)]    // empty bundle -> fail
        [InlineData(false, false, true, false, true)]   // non-existing bundle -> fail
        public void HttpClientUsesSslCertEnvironmentVariables(bool setSslCertDir, bool createSslCertDir,
            bool setSslCertFile, bool createSslCertFile, bool expectedFailure)
        {
            // This test sets SSL_CERT_DIR and SSL_CERT_FILE to empty/non-existing locations and then
            // checks the http request fails.
            // Some platforms will use the system default when not specifying a value, while others
            // will not use those certificates. Due to these platform differences, we only check specific
            // combinations that are expected to work the same cross-platform.
            var psi = new ProcessStartInfo();
            if (setSslCertDir)
            {
                string sslCertDir = GetTestFilePath();
                if (createSslCertDir)
                {
                    Directory.CreateDirectory(sslCertDir);
                }
                psi.Environment.Add("SSL_CERT_DIR", sslCertDir);
            }

            if (setSslCertFile)
            {
                string sslCertFile = GetTestFilePath();
                if (createSslCertFile)
                {
                    File.WriteAllText(sslCertFile, "");
                }
                psi.Environment.Add("SSL_CERT_FILE", sslCertFile);
            }

            RemoteInvoke(async arg =>
            {
                bool shouldFail = bool.Parse(arg);
                const string Url = "https://www.microsoft.com";

+                // Here, if we change to client = CreateHttpClient(useSocketsHttpHandlerBoolString: "true"), the test will always fail. Test will pass if client = CreateHttpClient(useSocketsHttpHandlerBoolString: "false"). (Not using SocketsHttpHandler)
+                using (HttpClient client = new HttpClient())
                {
                    if (shouldFail)
                    {
                        await Assert.ThrowsAsync<HttpRequestException>(() => client.GetAsync(Url));
                    }
                    else
                    {
                        await client.GetAsync(Url);
                    }
                }
                return SuccessExitCode;
            }, expectedFailure.ToString(), new RemoteInvokeOptions { StartInfo = psi }).Dispose();
        }
```

Callstack:

```
Unhandled Exception: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
2018-03-12 22:36:11,472: INFO: proc(54): run_and_log_output: Output: Expected: typeof(System.Net.Http.HttpRequestException)
2018-03-12 22:36:11,472: INFO: proc(54): run_and_log_output: Output: Actual:   (No exception was thrown)
2018-03-12 22:36:11,472: INFO: proc(54): run_and_log_output: Output:    at Xunit.Assert.Throws(Type exceptionType, Exception exception)
2018-03-12 22:36:11,472: INFO: proc(54): run_and_log_output: Output:    at Xunit.Assert.ThrowsAsync[T](Func`1 testCode)
2018-03-12 22:36:11,473: INFO: proc(54): run_and_log_output: Output:    at System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.<>c.<<HttpClientUsesSslCertEnvironmentVariables>b__29_0>d.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_true_prtest/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ServerCertificates.Unix.cs:line 117
2018-03-12 22:36:11,474: INFO: proc(54): run_and_log_output: Output: --- End of stack trace from previous location where exception was thrown ---
2018-03-12 22:36:11,474: INFO: proc(54): run_and_log_output: Output:    at RemoteExecutorConsoleApp.Program.Main(String[] args) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_true_prtest/src/Common/tests/System/Diagnostics/RemoteExecutorConsoleApp/RemoteExecutorConsoleApp.cs:line 63
2018-03-12 22:36:11,475: INFO: proc(54): run_and_log_output: Output: --- End of stack trace from previous location where exception was thrown ---
2018-03-12 22:36:11,475: INFO: proc(54): run_and_log_output: Output:    at RemoteExecutorConsoleApp.Program.Main(String[] args) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_true_prtest/src/Common/tests/System/Diagnostics/RemoteExecutorConsoleApp/RemoteExecutorConsoleApp.cs:line 92
2018-03-12 22:36:12,308: INFO: proc(54): run_and_log_output: Output:    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Test.HttpClientUsesSslCertEnvironmentVariables(setSslCertDir: False, createSslCertDir: False, setSslCertFile: True, createSslCertFile: True, expectedFailure: True) [FAIL]
2018-03-12 22:36:12,310: INFO: proc(54): run_and_log_output: Output:       System.Diagnostics.RemoteExecutorTestBase+RemoteInvokeHandle+RemoteExecutionException : Remote process failed with an unhandled exception.
2018-03-12 22:36:12,342: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-03-12 22:36:12,767: INFO: proc(54): run_and_log_output: Output:          
2018-03-12 22:36:12,768: INFO: proc(54): run_and_log_output: Output:          Child exception:
2018-03-12 22:36:12,778: INFO: proc(54): run_and_log_output: Output:            Xunit.Sdk.ThrowsException: Assert.Throws() Failure
2018-03-12 22:36:12,779: INFO: proc(54): run_and_log_output: Output:          Expected: typeof(System.Net.Http.HttpRequestException)
2018-03-12 22:36:12,779: INFO: proc(54): run_and_log_output: Output:          Actual:   (No exception was thrown)
2018-03-12 22:36:12,796: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_true_prtest/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ServerCertificates.Unix.cs(117,0): at System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.<>c.<<HttpClientUsesSslCertEnvironmentVariables>b__29_0>d.MoveNext()
2018-03-12 22:36:12,797: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2018-03-12 22:36:12,797: INFO: proc(54): run_and_log_output: Output:          /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_true_prtest/src/Common/tests/System/Diagnostics/RemoteExecutorConsoleApp/RemoteExecutorConsoleApp.cs(63,0): at RemoteExecutorConsoleApp.Program.Main(String[] args)
2018-03-12 22:36:12,798: INFO: proc(54): run_and_log_output: Output:          
2018-03-12 22:36:12,798: INFO: proc(54): run_and_log_output: Output:          Child process:
2018-03-12 22:36:12,798: INFO: proc(54): run_and_log_output: Output:            System.Net.Http.Functional.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test+<>c System.Threading.Tasks.Task`1[System.Int32] <HttpClientUsesSslCertEnvironmentVariables>b__29_0(System.String)
2018-03-12 22:36:12,799: INFO: proc(54): run_and_log_output: Output:          
2018-03-12 22:36:12,799: INFO: proc(54): run_and_log_output: Output:          Child arguments:
2018-03-12 22:36:12,799: INFO: proc(54): run_and_log_output: Output:            True
2018-03-12 22:36:12,799: INFO: proc(54): run_and_log_output: Output:          
```

**Comment by caesar1995** [comment]
I think probably we wrote the test case wrong in the first place, because SocketsHttpHandler will not be tested at all if we do `HttpClient client = new HttpClient()`.

Since now we make the SocketsHttpHandler as the default handler, the test will consistently fail.

If this is a bug in SocketHttpHandler, we need to fix the test as well, i,e,. `using (HttpClient client = CreateHttpClient(useSocketsHttpHandler))` for the coverage on PlatformHandler.

**Comment by stephentoub** [comment]
I think this was intended to work only with CurlHandler. @tmds?

**Comment by tmds** [comment]
We want this to work with the SocketsHttpHandler too.
For example, we see users want to do this when running their builds in a non-root container that accesses a local NuGet server with a custom cert.

From the test results it looks the variables are in effect when they are both set. Only setting SSL_CERT_FILE is not enough for the SocketsHttpHandler.

**Comment by tmds** [comment]
Suppose SSL_CERT_FILE is set and SSL_CERT_DIR is not set.
curl will then only load certificates from SSL_CERT_FILE:

```C
  if(ssl_cafile || ssl_capath) {
    /* tell SSL where to find CA certificates that are used to verify
       the servers certificate. */
    if(!SSL_CTX_load_verify_locations(BACKEND->ctx, ssl_cafile, ssl_capath)) {
```

And corefx falls back to loading from the default for the unset envvar:

https://github.com/dotnet/corefx/blob/bf36018813d2724e5bc9140d72e0d8bf92f2b621/src/Native/Unix/System.Security.Cryptography.Native/pal_x509_root.cpp#L11-L16

**Comment by stephentoub** [comment]
cc: @bartonjs 

@tmds, are you suggesting that the logic in pal_x509_root.cpp be updated?

**Comment by wfurt** [comment]
I think there was similar port asking to preserver SSL_XXX variables for new SocketHandler. 
It seems like we have user relying on current behavior on Unix and it would be nice to preserve it.

**Comment by tmds** [comment]
> @tmds, are you suggesting that the logic in pal_x509_root.cpp be updated?

Yes. When one envvar is set, we shouldn't fall back to the default for the other. I can make a PR for this.

**Comment by bartonjs** [comment]
The environment variable behavior that we have matches what the openssl commandline utility does (I'm pretty sure).

It's more important to match the openssl CLI than to match curl.

**Comment by tmds** [comment]
> It's more important to match the openssl CLI than to match curl.

`curl` does it with  1 envvar

So does `node`:
```
$ node https.js 
$ SSL_CERT_FILE=/tmp/empty_bundle node https.js 
problem with request: unable to get local issuer certificate
```

And `python` too:
```
$ python3 https.py 
$ REQUESTS_CA_BUNDLE=/tmp/empty_bundle python3 https.py 
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/util/ssl_.py", line 295, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
ssl.SSLError: unknown error (_ssl.c:3165)
```

**Comment by bartonjs** [comment]
The environment variables used by .NET are the environment variables used by the openssl commandline utility.  The goal is to be able to use the openssl CLI and .NET in the same way, since we're using OpenSSL as the processing engine.

Comparison to other tools, while interesting, doesn't change the design goal.

**Comment by bartonjs** [comment]
> Can we for example separate system and user certificates to separate stores?

Sure.  The user store is the user store.  The environment variables only control the system store.

> as we also need to be consistent with old HttpCurlHandler as we use ssl streams now to do ssl instead of curl. 

That's not going to be possible in any reasonable fashion.  You've moved from letting curl make decisions (sometimes falling back to X509Chain) to letting OpenSSL and X509Chain make decisions.  That means that HttpClient is now consistent with SslStream (which is good).

Changing the way the environment variables are processed affect all X509 processing done with .NET.  I'd recommend simply documenting the change (as "consistent with SslStream").

**Comment by tmds** [comment]
> The goal is to be able to use the openssl CLI and .NET in the same way

I think it makes sense to look at how other runtimes (node, python) do this. Our users are devs/runtime users, not openssl cli users.

**Comment by wfurt** [comment]
cc: @geoffkizer @karelz

**Comment by bartonjs** [comment]
@tmds The only reason that we read the environment variables at all is to be consistent with OpenSSL, and it's a behavior we've had since long before .NET Core 1.0 released.  It is primarily so that the default utilization of OpenSSL's TLS trust and .NET's X509Chain don't produce different answers.   (Or, rather, that we aren't ever in a case where the TLS default validator says "yes" but X509Chain says "no")

If this were only about HttpClient I'd agree with a different comparison, but this is about fundamentally changing the way that we handle X.509 processing, and the consequences are potentially far-reaching.  (e.g. SslStream would have to either customize the native trust handler (like curl did) or stop using it entirely and jump back to managed code in more cases)

It's an impactful change to some users either way.  Making HttpClient agree with what any manual calls to X509Chain would have done makes way more sense to me.

**Comment by karelz** [comment]
Can we scope the change just to HttpClient code paths? Being compatible with curl / .NET Core 2.0 is important.

**Comment by tmds** [comment]
@bartonjs I don't understand how _OpenSSL's TLS trust_ and _.NET's X509Chain_ could produce different results if they take into account SSL_CERT_DIR/SSL_CERT_FILE the same way. My view is from usability perspective rather than implementation perspective.

@karelz SSL_CERT_DIR/SSL_CERT_FILE was not a feature in 2.0 (although we are backporting it to .NET Core 2.0 for RHEL due to customer requests).

**Comment by karelz** [comment]
@tmds I am lost then. What is the customer ask exactly? To work as other tools do (curl, node, python)?

**Comment by bartonjs** [comment]
> Can we scope the change just to HttpClient code paths? 

No, SslStream would need to know about it, and X509Chain would need to know about it.  That's a lot of plumbing to a security-critical component.

> SSL_CERT_DIR/SSL_CERT_FILE for HttpClient was not a feature in 2.0 

Then it seems like there's not a compat issue here.  The change to the sockets handler means HttpClient behaves like SslStream already did.

> I don't understand how OpenSSL's TLS trust and .NET's X509Chain could produce different results if they take into account SSL_CERT_DIR/SSL_CERT_FILE the same way. 

My assertion is that they do *currently* take them into account the same way.  Curl didn't let OpenSSL do the defaults once an environment variable was set.  It took control of interpretation.

If my assertion is wrong then we have a different problem, which we should address.

> (although we are backporting it to .NET Core 2.0 for RHEL due to customer requests).

Then I'd recommend backporting the way that SslStream already behaves in 2.0, which should be the "two independent variables" behavior.

> I am lost then.

Me, too.

**Comment by tmds** [comment]
> I am lost then. What is the customer ask exactly? To work as other tools do (curl, node, python)?

The use-case is to allow a non-root user to specify trusted certificates.

This is what was implemented here: https://github.com/dotnet/corefx/pull/25219
The behavior of using SSL_CERT_DIR/SSL_CERT_FILE is same as curl/node/python.

The test added then fails for SocketHttpHandler, which behaves the same as openssl cli.

> My assertion is that they do currently take them into account the same way.

And even when changed, they can take them into account the same way.

> Curl didn't let OpenSSL do the defaults once an environment variable was set. It took control of interpretation.

Just like python and node. And we can do the same thing, if we choose to.

**Comment by tmds** [comment]
> And even when changed, they can take them into account the same way.

... but that would be a breaking change for SslStream (and other?), which probably is a no-go.

**Comment by tmds** [comment]
Based on what was said I think we want SslStream/HttpClient to use SSL_CERT_DIR/SSL_CERT_FILE in the same way. Since SslStream is already consuming those variables, the preference is for HttpClient to use them in the same way (instead of behaving like curl/node/...). Technically it would be challenging to make SslStream and HttpClient behave different since for SocketHttpHandler they share this code.

I'll make a PR to update curlhandler.

**Comment by wfurt** [comment]
thanks @tmds. It would be great if you can summarize the behavior and differences. 
I think it would be nice for other readers to get some context as not everybody knows all the details.

**Comment by tmds** [comment]
@wfurt this is a summary based on my understanding of the problem and implementation:

The use-case is to allow a non-root user to specify trusted certificates.
It is common to use SSL_CERT_DIR/SSL_CERT_FILE environment variables for this.

curl and nodejs allow to override all certificates used using a single environment variable: SSL_CERT_FILE that points to a certificate bundle file.

.NET Core 1.x, 2.0 uses these variables for SslStream/X509Store. To override the system certificates, both variables need to be set. Only setting SSL_CERT_FILE is not enough. When SSL_CERT_DIR is not set, the implementation falls back to the default directory, which causes system certificates to be loaded.

SocketsHttpHandler builds on top of SslStream/X509Store, so it has the same behavior.

CurlHandler is setting the curl options for path/cainfo, so it is behaving like the curl command (and node).

So we can either:
- make SslStream/X509Store behave like curl/node
- make CurlHandler behave like SslStream/X509Store.

The first would be a breaking change, since the interpretation of the environment variables is changing. So I guess preference is for the latter.

@bartonjs please correct/comment if I missed something.

**Comment by bartonjs** [comment]
> Only setting SSL_CERT_FILE is not enough. When SSL_CERT_DIR is not set, the implementation falls back to the default directory, which causes system certificates to be loaded.

It depends on the goal of the user.

* If they want to completely replace the system trust (permanently or during this program execution)
  * Set both variables
* If they want to add a certificate to their trust list permanently, being in addition to system trust
  * Open X509Store(Root, CurrentUser) and add the cert
* If they want to add a bundle of certificates for this program execution, but not generally, and they don't care if other things are also trusted
  * Set either SSL_CERT_FILE or SSL_CERT_DIR, as needed.

The platform uses additive behaviors.  That is, a certificate is considered trusted if it is in *either* the SSL_CERT_FILE file or the SSL_CERT_DIR directory.  The test assumes that by setting just SSL_CERT_FILE that it has replaced the entire store, when in reality it has (depending on the particular distro's certificate configurations, "probably") just added to the store.

Another way of expressing the correct actions is

* if "I want requests to fail because if they aren't in this list"
   * Set both
* else if "I want to always trust these CAs in addition to what the system trusts"
  * if admin
    * Edit system trust
  * else if "not part of an interleaved program execution via a script"
    * Use the .NET API to add the cert to the user Root store
  * else if "distro uses only _DIR"
    * set SSL_CERT_FILE to point to a (possibly-multi-)PEM
  * else if "distro uses only _FILE"
    * set SSL_CERT_DIR to point to a directory containing single-PEM certificates
  * else
     * set whichever one
* else if "I want to trust these CAs in addition to what the system trusts only when this script/program runs"
  * if "distro uses only _DIR"
    * set SSL_CERT_FILE to point to a (possibly-multi-)PEM
  * else if "distro uses only _FILE"
    * set SSL_CERT_DIR to point to a directory containing single-PEM certificates
  * else
     * set whichever one
* else
  * Don't do anything, system trust just happens.

**Comment by tmds** [comment]
> The test assumes that by setting just SSL_CERT_FILE that it has replaced the entire store, when in reality it has (depending on the particular distro's certificate configurations, "probably") just added to the store.

The behavior of curl is to replace the entire store when 1 variable is set. This is the same for every distro with OpenSSL backend.

Your comment provides a nice overview of how people can achieve various scenarios with custom certificates. Perhaps this should be in some documentation?

I'll make a PR that makes the curlhandler behave like SslStream/X509Store.
