### ISSUE TITLE
Assembly.ReflectionOnlyLoad replacement - TypeInfo and family implementation over System.Reflection.Metadata

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#2800]
### Proposed Surface Area
```c#
namespace System.Reflection
{
    public abstract class MetadataAssemblyResolver
    {
        public abstract Assembly Resolve(MetadataLoadContext context, AssemblyName assemblyName = null);
    }

    public class PathAssemblyResolver : MetadataAssemblyResolver
    {
        public PathAssemblyResolver(IEnumerable<string> assemblyPaths);
        public override Assembly Resolve(MetadataLoadContext context, AssemblyName assemblyName);
    }

    public sealed partial class MetadataLoadContext : System.IDisposable
    {
        public MetadataLoadContext(MetadataAssemblyResolver resolver, string coreAssemblyName = null);
        public Assembly CoreAssembly { get; }
        public void Dispose();
        public System.Collections.Generic.IEnumerable<Assembly> GetAssemblies();
        public Assembly LoadFromAssemblyName(AssemblyName assemblyName);
        public Assembly LoadFromAssemblyName(string assemblyName);
        public Assembly LoadFromAssemblyPath(string assemblyPath);
        public Assembly LoadFromByteArray(byte[] assembly);
        public Assembly LoadFromStream(System.IO.Stream assembly);
    }
}
```

### Scenario: Inspecting IL metadata assemblies in custom directories.

```C#
    var mscorlibpath = @"D:\temp\myselfcontainedapp\mscorlib.dll";
    var mydllpath = @"D:\temp\myselfcontainedapp\myap.dll";
    var resolver = new PathAssemblyResolver(new string[] {mscorlibpath, mydllpath});
    using (var context = new MetadataLoadContext(resolver, "mscorlib"))
    {
        Assembly a = context.LoadFromAssemblyPath(@"D:\temp\myselfcontainedapp\myapp.dll");

        var type = a.GetType("MyApp.MyClass", throwOnError: true);
    }
```

This creates a load context with a policy to probe for external assemblies in a specific directory. An external assembly is loaded on demand when there is a type reference to that assembly.

`MetadataLoadContext` implements `IDisposable`. Disposing releases any file locks that may be held on the underlying assembly files. Once disposed, any Assembly objects dispensed by the MetadataLoadContext (and any Reflection objects dispensed by those Assemblies) must no longer be called. Their behavior is undefined. (We'll make a good faith effort to throw `ObjectDisposedExceptions` but some properties may returned cached data. The primary goal is to avoid the really anti-social behavior such as accessing freed native memory.)

You determine the bind algorithm by selecting a pre-existing resolver (MetadataAssemblyResolver-derived class) or writing you own MetadataAssemblyResolver-derived class and overriding the `Resolve` method. The Resolve method should return either `null` or an `Assembly` object dispensed by one of the `Load` methods on the `MetadataLoadContext` that was passed to the Resolve method.

The provided DirectoryAssemblyResolver policy probes each directory in order to find a given assembly by name and stops once the first provided assembly file is found. It does not compare assembly versions or try to find the best matching assembly (if the assembly exists in more than one location). It appends ".dll" to the assembly name in order to find the file. If no assembly is found, a FileNotFoundExcepton is raised. DirectoryAssemblyResolver also sets the context.CoreAssemblyName property to "mscorlib", but that can be changed by the consumer before the first access to the core assembly is requested; the first access to the core assembly occurs by a reference to primitive type such as System.Object or System.Int32.

### Scenario: Inspecting IL metadata assemblies using the runtime loader.

In .NET Framework, a common pattern is creating a new AppDomain (using the existing AppDomainSetup) just to load a single assembly, inspect its types and custom attributes, then unload in order to free the memory. 

We've looked into the idea of allowing runtime-supplied Assemblies to be injected into the TypeLoader but this is a snake pit. For this idea to work at all, the cooperation needs to work both ways and runtime Assemblies aren't designed to interoperate with externals. In particular, Type.MakeGenericType() is not copacetic with instantiating runtime types on non-runtime type arguments.

A possible midway solution is for TypeLoader (or the calling app) to reload the runtime assembly (from it's Location property) as a TypeLoader-supplied assembly. This allows users to use the binding algorithm of the current runtime if that's what they want. But it does mean "loading the assemblies twice" so there is a perf hit.

Currently there is no MetadataAssemblyResolver that supports this policy, but it would not be difficult to create.

### Earlier Proposal and Notes
```C#
namespace System.Reflection
{
    public sealed class TypeLoader : IDisposable
    {
        public TypeLoader();
        public TypeLoader(string coreAssemblyName);

        public Assembly LoadFromAssemblyPath(string assemblyPath);
        public Assembly LoadFromByteArray(byte[] assembly);
        public Assembly LoadFromStream(Stream assembly);

        public Assembly LoadFromAssemblyName(AssemblyName assemblyName);
        public Assembly LoadFromAssemblyName(string assemblyName);

        public string CoreAssemblyName { get; set; }

        public event Func<TypeLoader, AssemblyName, Assembly> Resolving;

        public IEnumerable<Assembly> GetAssemblies();

        public void Dispose();
    }
}
```

#### Scenario : Legacy ReflectionOnlyLoad emulation

```

     Assembly a = TypeLoader.Default.Load("Foo, Version=1.2.3.4, PublicKeyToken=xxxxxxxxxx");

```

The static `Default` property returns a global `TypeLoader` that serves as a (compatible within reason) replacement for `Assembly.ReflectionOnlyLoad`. As with `ReflectionOnlyLoad`, you must preload all dependencies (other than mscorlib) either in advance or on-demand by subscribing to the `AppDomain.ReflectionOnlyAssemblyResolve` event.

This approach is not recommended for new code. It's for porting old code only. 

#### Issue - Throw FileLoadException or FileNotFoundException when the Resolving event handler returns null?

ReflectionOnlyLoad (the feature we're officially replacing) throws `FileLoadException`.
AssemblyLoadContext (the new feature) throws `FileNotFoundException.`

The former is more compatible, the latter is more logical.

#### Issue - Semantics of LoadFromAssemblyName() - be like ReflectionOnlyLoad or like AssemblyLoadContext?

On the surface, `LoadFromAssemblyName()` looks like the equivalent of `ReflectionOnlyLoad(AssemblyName)`. But in fact, it's not.

`Assembly.ReflectionOnlyLoad(AssemblyName)` only returns an Assembly that had already been loaded via a prior operation. If no assembly matching the name had been loaded, it throws `FileNotFoundException` (unlike when it fails a dependency load, which throws `FileLoadException`.) It does not invoke the `ReflectionOnlyAssemblyResolve` event.

So the name is misleading since it never _loads_ an assembly. It only fetches a previously loaded Assembly. I'm not sure what the use case for it is - if it return `null` rather than throwing, it could be seen as the `TryGet` api but given that it throws without giving the resolve event handler a chance to bind, what is the rationale for this behavior?

`AssemblyLoadContext.LoadFromAssemblyName()`, on the other hand, works much more like I'd expect. It triggers the `Load` overload and the event handler as needed. It's basically a manual way of triggering the same process that happens when the runtime internally resolves an assembly reference.

I'd rather adopt `AssemblyLoadContext`'s behavior here as we're adopting the api name and the behavior is less surprising. On the other hand, we're supposed to be replacing `ReflectionOnlyLoad`. I see three choices:

1. Adopt the `AssemblyLoadContext` behavior.

2. Adopt the `ReflectionOnly` behavior.

3. Have both `Load` and `LoadFromAssemblyName` overloads.

**Comment by nguerrera** [comment]
This is something we've wanted to do for a long time. Thanks for filing an issue to track it.

**Comment by karelz** [comment]
@tmat @nguerrera we think it belongs to Sytem.Reflection.Metadata

**Comment by tmat** [comment]
@karelz I don't think it does. We don't want to implement a specific object model in SRM. Rather System.Reflection should build on top of SRM.

**Comment by karelz** [comment]
@AtsushiKan @DnlHarvey you guys didn't think it is doable/feasible. Can you please comment?

**Comment by AtsushiKan** [comment]
It's feasible - it's just a <i>big</i> work item.

CoreRt's Reflection is being refactored to work over SRM (Ecma) - this would be a similar sort of thing but extracted from CoreLib and the execution-related paths stubbed out.

**Comment by AtsushiKan** [comment]
Ideally, I'd prefer it not automatically load dependencies but that may be difficult given that the Reflection surface area doesn't have a `Resolve` api (we could have an extension method) and does not distinguish between references and definitions. But this is the kind of thing that would have to be hashed out as part of the design of this thing. Do we go for a policy-free lightweight layer or do we go for something "easier to use" with some default binding rules and the ability to plug in your own.

**Comment by jkotas** [comment]
> TypeLoader

I do not think this should be called TypeLoader. We have many different TypeLoaders in the system and this is just one of them. Maybe something like ReflectionOnlyAssemblyLoadContext ?

> public Assembly Load(AssemblyName assemblyRef);
> public Assembly Load(string assemblyRef);
> public Assembly LoadFrom(string path);

These APIs look very similar to AssemblyLoadContext. Should we use the same names for them? e.g. LoadFromAssemblyPath instead of LoadFrom. IIRC, the original proposal for AssemblyLoadContext had simpler names like you have as well - but API review folks change it to the long names.

> public Collection<string> Extensions { get; }

What is the scenario where this needs to be customizable? If there is some corner case that needs customizing it, it can be always done by subscribing to the resolve event.

> Binding is very simple -  take the simple name (ignoring version, PKT)

Is the simple binding going to work for everybody? What if somebody wants binding that pays attention to versions or PKT?

> public Assembly Load(byte[] rawAssembly);

I think it would be useful to have overload that loads from Stream as well.

> Scenario

I think that a fairly common scenario is to resolve against everything that runtime loader can load. I have seen people doing following many times:

1. Create AppDomain (with inherited AppDomainSetup - to get the same probing paths, etc.)
2. Load an assembly into the AppDomain and inspect it (e.g. enumerate types and fetch custom attributes on each). If this ends up loading dependencies, they are resolved by the runtime loader.
3. Unload AppDomain

This API will be our migration story from AppDomains for the above. It should be reasonably straightforward.

**Comment by AtsushiKan** [comment]
>I do not think this should be called TypeLoader. We have many different TypeLoaders in the system and this is just one of them. Maybe something like ReflectionOnlyAssemblyLoadContext ?

If the issue is that the name "monopolizes" the general concept, we could qualify it or stick it in a more specialized namespace (System.Reflection.CrossPlatform?). I don't think we want the qualifier to be "ReflectionOnly" because (1) it's long and (2) I expect that TypeLoaders will eventually host "dynamic" or "authoring" assemblies too for the RefEmit.Save() issue. The thing this class brings to the table is cross-runtime - the Reflection objects it dispenses are not tied to the executing runtime.

I'd have two issues with `ReflectionOnlyAssemblyLoadContext` as a name:

1. It's a mouthful.
2. It implies an "isa" relationship to `AssemblyLoadContext` that isn't there. `TypeLoader` doesn't and can't derive from `AssemblyLoadContext`, nor would it be apropos to do so as `AssemblyLoadContext` is very much about runtime-tied types. It's more accurate to say that both `AssemblyLoadContext` and `TypeLoader` both have an "isa" relationship to a more abstract notion of a type universe. 

> public Assembly Load(AssemblyName assemblyRef);
> public Assembly Load(string assemblyRef);
> public Assembly LoadFrom(string path);
> These APIs look very similar to AssemblyLoadContext. Should we use the same names for them? e.g. 
> LoadFromAssemblyPath instead of LoadFrom. IIRC, the original proposal for AssemblyLoadContext 
> had  simpler names like you have as well - but API review folks change it to the long names.

The names were taken directly from the ReflectionOnly apis (as well as the AppDomain apis.) 

Interesting that the API review folks changed these now. I don't have a strong objection to the longer names if that's the way they want the future to go.

> public Collection Extensions { get; }
> What is the scenario where this needs to be customizable? If there is some corner case that needs 
> customizing it, it can be always done by subscribing to the resolve event.
> Binding is very simple - take the simple name (ignoring version, PKT)
> Is the simple binding going to work for everybody? What if somebody wants binding that pays attention to > versions or PKT?

The idea was to provide some baseline functionality for the easy cases (as opposed to ReflectionOnly leaving you to handle all the binding.) Having said that, there's nothing the simple binding can do that an app couldn't do by hooking the resolve event and writing about 15 lines of code so I could be persuaded to keep the base `TypeLoader` class policy free and leave the simple binder as a sample. This was a tradeoff between simplicity (not introducing multiple classes or forcing the developer to write a binder for even the easy cases) and architectural cleanliness (separating concerns of binding policy implementation vs. loader interface.)

> public Assembly Load(byte[] rawAssembly);
> I think it would be useful to have overload that loads from Stream as well.

No problem - I already have that as a private worker so it's just a matter of making it public.

> Scenario
> I think that a fairly common scenario is to resolve against everything that runtime loader can load. I have seen people doing following many times:
> Create AppDomain (with inherited AppDomainSetup - to get the same probing paths, etc.)
> Load an assembly into the AppDomain and inspect it (e.g. enumerate types and fetch custom attributes 
> on each). If this ends up loading dependencies, they are resolved by the runtime loader.
> Unload AppDomain
> This API will be our migration story from AppDomains for the above. It should be 
> reasonably straightforward.

Right, I'll add that as a scenario. I assume I just need a way (if one doesn't already exist?) to ask an AppDomain or AssemblyLoadContext to bind an assembly name to a location (or Stream) and stop there. (The ask for this is tracked in https://github.com/dotnet/corefx/issues/24026)  

Then we hand the result over to `TypeLoader` and let it build the Ecma-based Assembly wrapper.

**Comment by AtsushiKan** [comment]
Edited top post:

- Adopted `AssemblyLoadContext`-style names for the `Load` overloads and the `Resolve` event.
- Added `LoadFromStream(Stream)` overload.
- Eliminated the probe directories support. So hooking the event is compulsory now. (Maybe the constructor could take a delegate?)

**Comment by jkotas** [comment]
> Right, I'll add that as a scenario. I assume I just need a way (if one doesn't already exist?) to ask an AppDomain or AssemblyLoadContext to bind an assembly name to a location

I was expecting that this scenario will be handled by delegating the assembly resolve event to `Assembly.Load` so that the framework assemblies are not loaded multiple times.

Or is the expectation that all Assembly objects in the universe will be created by the same context? It would be useful to clarify what are acceptable return values from Resolve event.

**Comment by AtsushiKan** [comment]
Each `TypeLoader` is an independent universe of types. The expectation is that `Resolve` must return an Assembly that was dispensed by calling one of the `Load` overloads on the "TypeLoader sender" parameter.

**Comment by AtsushiKan** [comment]
BTW, I noticed that `AssemblyLoadContext` has a different way of handling the same named assembly loaded from two different locations. `ReflectionOnlyLoad` always failed if you loaded the assembly from a byte array twice (even if the contents were identical) or from two different locations on disk (even if the files were identical.)

I'm guessing `AssemblyLoadContext` looks at the contents or the MVID to decide whether to throw?

**Comment by jkotas** [comment]
> Each TypeLoader is an independent universe of types. The expectation is that Resolve must return an Assembly that was dispensed by calling one of the Load overloads on the "TypeLoader sender" parameter.

Is there fundamental reason why this restriction exists? It may result into performance regression in the AppDomain migration case (types loaded in shared domain are reused between all appdomains). Maybe it is ok. Just want to make sure that there is a good reason for it.

**Comment by AtsushiKan** [comment]
>Is there fundamental reason why this restriction exists? 

The main reason is that the whole notion of a type universe is that there's a single assembly binding policy for that universe and one list of "canonically loaded assembly instances" for a given assembly identity.

If you mix and match Type objects from different universes (let alone, different implementations), you break that premise. Our EcmaType objects will use the TypeLoader's binding rules to resolve tokens as intended. The System.RuntimeType objects from an AssemblyLoadContext will continue to use the load context's binding policy. You have two separate entities maintaing a "list of bound assemblies." 

AssemblyLoadContext's themselves refuse to accept any Assembly that's not `System.RuntimeAssembly`, RuntimeTypes themselves are pretty strict about accepting externally built Types as input. I don't know that we have precedent for building this kind of heterogenous type universe.

Now we could split the type hierarchy even further so that the base `TypeLoader` class is a pure abstract class and the SRM universe is a derived class from that that provides the isolated universe experience. Then `TypeLoader` could also be layered over the Assembly.Load. I'm not sure how much value the latter brings (you're creating a newer interface for calling the same stuff) but if there's value, we could do it that way.

**Comment by nguerrera** [comment]
I know this is a hard problem, but it can be cumbersome to have to supply the core assembly name up front. There's a long history of tooling bugs due to incorrect assumptions about what the core assembly name must be. Roslyn can determine which assembly in the reference set has the system.object typedef. To do this with the proposed API, I think I would have to crack all the assemblies separately before using TypeLoader. This would be inefficient and require dropping to lower level API. Can we possibly have a way to say "here all all the dlls/exes in the universe" and let the system deal with identifying the core one?

**Comment by jkotas** [comment]
> The main reason is that the whole notion of a type universe is that there's a single assembly binding policy for that universe and one list of "canonically loaded assembly instances" for a given assembly identity.

I agree that there needs to be list of "canonically loaded assembly instances" for a given assembly identity. I do not think that it requires a single assembly binding policy. Different assembly names can be resolved by different assembly binding policy.

**Comment by AtsushiKan** [comment]
>Different assembly names can be resolved by different assembly binding policy.

The thing it, it would depend just on the name but who happened to be the first to do the binding.

So say, you have a Type in a EcmaAssembly and a different Type in an RuntimeAssembly that both define a field of a Type in a third assembly ("Foo"). So if you call `GetField()` on the first Type, it binds "Foo" according to the TypeLoader binding policy and commits the result to the TypeLoader's assembly list. If you call `GetField()` on the second Type, _that_ binds "Foo" according the runtime's binding policy and commits the result to the runtime's list. Either way, you get back two different instances of the "Foo" assembly from the "same" TypeLoader. The idea of a single unified canonical Assembly instance for "Foo" gets broken.

**Comment by AtsushiKan** [comment]
>This would be inefficient and require dropping to lower level API. Can we possibly have a way to say "here all all the dlls/exes in the universe" and let the system deal with identifying the core one?

So just something that takes a list of dlls/exe's and inspects each one until it founds one exporting a System.Object type? (along some reasonable heuristics like searching the ones named "mscorlib", "System.Runtime", "netstandard" and "System.Private.Corelib" first?)

I guess something like that could be done... I would think "mscorlib" would work fine in 99% of the cases, though. Even .NETCore supplies an mscorlib façade (and `TypeLoader` is perfectly fine with the core assembly being a façade.)

**Comment by nguerrera** [comment]
If the loader can deal with that argument being a facade, then it's much better. I was imagining that it could not. Still there will be cases where you don't necessarily have an mscorlib facade in your reference set.

**Comment by jkotas** [comment]
> The thing it, it would depend just on the name but who happened to be the first to do the binding.

Right, when you have multiple binding policies in play, they need to cooperate to ensure that the same identity gets returned in all cases. As long as the users of this feature guarantee this, there is no fundamental problem. Correct?

**Comment by nguerrera** [comment]
When I'm talking about "reference set", I'm thinking of build tools. Some that are yet to be ported (like xaml compilation) use reflection only load or LMR and have had bugs with this. Trying to see if there's a pit of success we can build to address that.

**Comment by AtsushiKan** [comment]
> So if the core assembly name can correspond to a facade, then it means that the system doesn't need the actual assembly defining the primitive types to be loaded first, right? If so, can we possibly discover the core assembly lazily?
> I'm imagining that when we first encounter the need for a core assembly (e.g. to resolve a primitive type encountered in a signature), then we start walking/loading assembly references (possibly with the common core names first heuristic for perf) and designate the first one we find with system.object typedef as the core assembly. Naively, this doesn't seem very different from following a type forward for System.Object from mscorlib facade to the actual assembly that defines System.Object.


Right, it is loading the core assembly lazily - the constructor only stores the name for later reference.

Following assembly references might work. (It's probably a rare assembly that doesn't reference the core assembly :-) I could picture that as a fallback, though the option should remain to specify the core assembly name explicitly.

**Comment by nguerrera** [comment]
cc @ericstj who recently had to hack around a xaml compiler issue with core assembly identity in a prototype.

**Comment by jkotas** [comment]
> The "load an appdomain to inspect an assembly" is something that people can do now without this feature, right?

Here is a real world example of the code: https://github.com/RssBandit/RssBandit/blob/master/source/RssBandit/Core/ServiceManager.cs#L74

This code is not easy to migrate to .NET Core today. This feature should make this much easier. We should have an example how this code would need to change, and we should make sure that the performance is same or better compared to the AppDomain solution.

**Comment by nguerrera** [comment]
It would be great and fully address my concern if the core assembly name was optional.

**Comment by AtsushiKan** [comment]
>Here is a real world example of existing code: >https://github.com/RssBandit/RssBandit/blob/master/source/RssBandit/Core/ServiceManager.cs#L74

This code is creating object instances (code execution) so it wouldn't be using a metadata only feature like ours anyway. But even assuming that's not part of the problem, isn't `AssemblyLoadContext` already the solution for this? What's the missing piece that this feature would be expected to fill in? It is  intended to be portable managed library with no special hooks into the runtime that user code would have.

**Comment by AtsushiKan** [comment]
Okay, so this paticular example would have to save the _names_ of the types and retrieve them again in the executable Assembly again if it were to use a reflection-only assembly to do the inspection. The Type objects that our EcmaAssemblies hands out aren't instantiable, naturally.  

So we're talking about the set of cases where the assembly dependencies only go from EcmaAssembly's to RuntimeAssembly's and not vice versa (since the runtime's Type implementations sure aren't equipped to reference non-RuntimeType objects) _As long as those conditions are maintained_, we can still have a self-consistent type universe. The `TypeLoader` maintains the canonical assembly list for the Ecma assemblies and trusts the runtime to preserve uniqueness for the Runtime assemblies.

I _think_ we can make that work - I'll need to poke at this for a while though before I can be sure.

**Comment by jkotas** [comment]
Ok, I think you have convinced me that the mixing of the different words is a bad idea.

**Comment by AtsushiKan** [comment]
Initial commit is now in corefxlab repo 

(https://github.com/dotnet/corefxlab/tree/master/src/System.Reflection.TypeLoader)

The documentation is here: https://github.com/dotnet/corefxlab/blob/master/docs/specs/typeloader.md

Current status regarding the various issues:

- CoreAssemblyName - changed the CoreAssemblyName to be settable so you can set the CoreAssemblyName post-construction. Enough apis work (details in the above link) that heuristics like searching assembly refs for assemblies with "system-like" names exporting System.Object can be done by the caller before supplying a core name. I don't think we should hard-code a heuristic into TypeLoader itself.

- FileNotFound vs. FileLoadException: choosing FileNotFound (as AssemblyLoadContext does.) 

- LoadFromAssemblyName invokes the resolve event handler if the assembly wasn't previously loaded (again, following AssemblyLoadContext behavior.)
