### ISSUE TITLE
Get the .NET Core version number at runtime

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#28132]
@IvanFarkas commented on [Sat Jan 27 2018](https://github.com/dotnet/core/issues/1242)

Is there a reliable way to get the **.NET Core version number** at runtime that works on **Nano Server** and **Ubuntu** **Docker** containers as well, please?
I've seen some hacks deriving it from folder structure that breaks when the app is deployed onto Nano Server and Ubuntu Docker container images.

**Comment by danmosemsft** [comment]
@IvanFarkas I'm curious for what purpose you need the version at runtime?

**Comment by IvanFarkas** [comment]
:-)
I need to know.

**Comment by Clockwork-Muse** [comment]
@IvanFarkas - well, there's a difference between "I'd like to know to log it on program startup", and "I'd like to know for feature detection/bug workarounds"....

**Comment by svick** [comment]
Personally, considering that I'm using various versions of .Net Framework and .Net Core (including previews) and that I'm sometimes investigating behaviors that differ depending on which framework I'm using, I'd like to be able to print what framework I'm running on, so that I could easily write code that does something like:

```
> dotnet run -f net47
.Net Framework 4.7.1: Everything's fine
> dotnet run -f netcoreapp1.0
.Net Core 1.0: Everything's fine
> dotnet run -f netcoreapp2.0
.Net Core 2.0: BUG!
```

To do this today, I copied [this code](https://github.com/dotnet/BenchmarkDotNet/blob/16b6118/src/BenchmarkDotNet.Core/Portability/RuntimeInformation.cs#L135-L143) from BenchmarkDotNet.

**Comment by IvanFarkas** [comment]
@Clockwork-Muse I like contributors answering questions constructively, instead of interrogating about the motivation.
This is how we roll in the better part of Europe.

**Comment by svick** [comment]
@IvanFarkas Motivation is important, because it can affect the shape of the API. For example, should the API be `bool isNetCore20 = RuntimeInformation.IsFramework(FrameworkVersion.NetCore20);`, or `string frameworkVersion = RuntimeInformation.GetFrameworkVersion();`?

**Comment by IvanFarkas** [comment]
Run time statistics is basic to me and the lack of it is a serious oversight!
I can just use the Docker env, reporting .net runtime info if it’s too much trouble implementing this obviously lacking piece.

**Comment by kasper3** [comment]
We have a property ([RuntimeInformation.FrameworkDescription](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.frameworkdescription?view=netcore-2.0#System_Runtime_InteropServices_RuntimeInformation_FrameworkDescription)) but it is missing the framework version.
If it is not a huge breaking change, then the version can be added to the existing description string, otherwise a new Property `static string FrameworkVersion` may even suffice the requirement (and `IsFramework(<enum FrameworkVersion>)` might not be necessary). Otherwise we can have both, property and the method, just like `OSDescription` and `IsOSPlatform()` are present in the same class.

**Comment by IvanFarkas** [comment]
I am running 

- different versions of .NET Core runtime
- cross-compiled with different versions of .NET Core SDK 
- on different versions of Linux distro 
- inside different versions of Docker.

At runtime, I'd like to know 
- what am I running on 
- what am I running
- and where it came from.

Thank you very much for your help in advance.

**Comment by loop-evgeny** [comment]
Please add a simple way to get the runtime version. No, not `IsRuntimeVersion(x)`, just `public System.Version RuntimeVersion` and maybe a human-readable string with more details (if any). Use case: troubleshooting. I have several versions of the runtime and the SDK instealled and I want to *know*, not guess, what runtime version my application is *actually* running on (as opposed to *should* run on).

**Comment by loop-evgeny** [comment]
I'm now trying out self-contained deployment and have no idea how to get the .NET Core version included with the deployed application - either at runtime or by inspecting the binaries.

**Comment by loop-evgeny** [comment]
Another use case is benchmarking: I need to know what .NET Core runtime version I'm running on to see if it's the same as on the server I'm comparing against.

This use case: security updates - how do I know when I need to rebuild and re-deploy my self-contained deployment application?

**Comment by doublnt** [comment]
I am using the following method:
First Get the RunTime Directory:  `System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory()`
Next, Use Regex to pick up the Runtime Info and Version

**Comment by loop-evgeny** [comment]
@doublnt That doesn't help for self-contained deployments. `GetRuntimeDirectory()` then returns the directory containing the EXE (which is correct - that's where the runtime is).

**Comment by ViktorHofer** [comment]
Closing in favor of https://github.com/dotnet/corefx/issues/16629. A hacky solution would be using what https://github.com/dotnet/corefx/pull/35436 offers.
