### ISSUE TITLE
[Regression] Wrong target type in System.ComponentModel.UInt16Converter.cs

### ISSUE THREAD

**Issue by pseudobjorn** [dotnet/corefx#28195]
The target type on line 18 is wrong. 
It should be typeof(**ushort**), and not typeof(short) as it is today.
Ref https://stackoverflow.com/questions/49361595/why-does-the-formatexception-returned-by-a-typeconverter-for-an-ushort-type-refe

**Comment by karelz** [comment]
Could you please post the code here as well?
It seems you know the fix, do you plan to submit a PR? It would be very appreciated. Thanks!

**Comment by AlexGhiondea** [comment]
This commit (https://github.com/dotnet/corefx/commit/6f48f1959c292aa78fe38902f62e9dd33436c6c5#diff-4934d3603a94cae7e5f39a5bd171982a) changed the target type from Uint16 to short (instead of ushort)

https://github.com/dotnet/corefx/blob/6f48f1959c292aa78fe38902f62e9dd33436c6c5/src/System.ComponentModel.TypeConverter/src/System/ComponentModel/UInt16Converter.cs#L18

**Comment by karelz** [comment]
Looks like a regression against 2.0. Probably copy-paste error / oversight.

**Comment by AlexGhiondea** [comment]
This only impacts the exception message and should be a trivial fix. 

When we fix this we should add tests to validate that the target type of the converters are the expected ones.
