### ISSUE TITLE
Add Path.TryGetRelativePath()

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#28257]
From API proposal #27418.

Need to add a span based version of `Path.GetRelativePath()`:

``` C#
namespace System.IO
{
    public static class Path
    {
        public static bool TryGetRelativePath(ReadOnlySpan<char> relativeTo, ReadOnlySpan<char> path, Span<char> destination, out int charsWritten);
    }
}
```

Returns false if the destination isn't large enough to fit the full path into.

The best way to handle this is probably to rewrite the existing internal logic to use ValueStringBuilder (instead of StringBuilder). The Span overload above can use `destination` as it's original buffer and fail out if the builder has grown to grab from the ArrayPool.

Converting `Path.GetRelativePath()` to use ValueStringBuilder can (and probably should) be done as an initial change. Removing StringBuilder usage (and replacing with ValueStringBuilder) is perf goal.

**Comment by BhaaLseN** [comment]
2 questions:
1. Does this support _any_ relation between 2 paths on the same root? ie. does `C:\Temp\somefile.txt` relative-to `C:\Users\myself\Documents\test\test.exe` return `..\..\..\..\Temp\somefile.txt` (or some platform-appropriate equivalent) or does it only work if `path` is a subfolder of `relativeTo` (hoping the former, because I had to hand-roll one of those way too often)
2. How will this API handle 2 paths on _different_ roots (probably windows-specific)? ie. `D:\temp\seconddisk.txt` relative-to `C:\temp\firstdisk.txt`

**Comment by danmosemsft** [comment]
@Anipik if you haven't started on this please unassign and mark has a hackathon candidate.

**Comment by Anipik** [comment]
@danmosemsft I havenot started it as @JeremyKuhne said these apis need to be approved again.

**Comment by danmosemsft** [comment]
@JeremyKuhne is that the case? If so this should not have the approved label...?

**Comment by JeremyKuhne** [comment]
> these apis need to be approved again.

This particular one is ok.

> Does this support any relation between 2 paths on the same root?

Yes, you can look at the existing API (`Path.GetRelativePath`) to see the behavior.

> How will this API handle 2 paths on different roots

You get the [second path](https://source.dot.net/#System.Private.CoreLib/shared/System/IO/Path.cs,697).

**Comment by ivlevkonstantin** [comment]
I'll work on it.

**Comment by karelz** [comment]
I sent you Collaborator invite - see details here: https://github.com/dotnet/corefx/wiki/Hackathon#how-can-i-grab-an-issue

**Comment by ivlevkonstantin** [comment]
@JeremyKuhne , I've got the same question as @danmosemsft . What should we do with case (should it be case sensitive, or case insensitive by default)? For me It does not make big sense to get case sensitive relative path.

**Comment by ivlevkonstantin** [comment]
This issue depends on [Path.TryGetFullPath](https://github.com/dotnet/corefx/issues/28258) (which has not been merged yet), because GetFullPath is called in the original GetRelativePath method implementation.

> Returns false if the destination isn't large enough to fit the full path into.
There is [comment](https://github.com/dotnet/coreclr/pull/17429/files#r179645599) in the PR for TryGetFullPath method, which has not been addressed since April. This issue sounds reasonable, so, I'll need to wait for the resolution for [issue](https://github.com/dotnet/corefx/issues/28258)

**Comment by karelz** [comment]
It looks like we may need to go back and rethink the API - returning false for both buffer-too-small and permanent error case is not good - @JeremyKuhne can you please comment?
Also, the dependency on the not-yet-merged API will require waiting for it, sorry.

**Comment by JeremyKuhne** [comment]
> This issue depends on Path.TryGetFullPath (which has not been merged yet), because GetFullPath is called in the original GetRelativePath method implementation.

There is actually an internal ValueStringBuilder version that could be used (that Path.GetFullPath calls).

That said, we're closing this for now until we re-review the API proposal as we're considering postponing until we have ValueStringBuilder (or an equivalent type) public to make this API more straight forward.
