### ISSUE TITLE
System.Data.SqlClient.TdsParser  performance  improvement

### ISSUE THREAD

**Issue by AndrewZ1989** [dotnet/corefx#28270]
I've done a little research and it looks like we do a lot of unnecessary allocations in the 'TryReadSqlDateTime' method.

For each call of the method we allocate the array of bytes (`` byte[] datetimeBuffer = new byte[length];``)
instead of allocating it once and then reuse existing array.

Let's imagine that we read 1 million DateTime values from database. Using existing implementation of TdsParser we will have 1 million allocations of byte[] what causes unnecessary memory traffic and isn't so good for GC.

So, if nobody minds, I'd make the described changes and then estimate benefits.

**Comment by saurabh500** [comment]
@AndrewZ1989 Sounds good. What approach do you intend to follow? 
Create a field in TdsParser with the byte array? Or use something Like ArrayPool to rent out the byte array?

**Comment by AndrewZ1989** [comment]
@saurabh500  Actually I've considered both options which you mentioned. 
In the long term using of `ArrayPool` is more perspective because we will be able to replace all `new byte[]` constructions by ArrayPool's methods calling (instead of using a new field for each case). 
But I'm not sure which approach is better : creating a new instance of `ArrayPool` for each new `TdsParser` object or using `ArrayPool.Shared` instance. The first approach seems better because no one can be block us when we read data from DB ( but what value of `maxArrayLength` parameter should we use in this case? ).
However, if we don't want to change anything except `TryReadSqlDateTime` method, then I'd like to create a private field with the byte array.

**Comment by AndrewZ1989** [comment]
I'm going to try both of mentioned solutions and evaluate performance with the help of **BenchmarkDotNet** library.

**Comment by FSou1** [comment]
I've taken a look at this issue and would like to mention that:
1. Based on the [benchmark](http://adamsitnik.com/Array-Pool/) "Allocate" vs "RentAndReturn_Shared" significant enchancement of performance could be achieved once the buffer > 1000 bytes;
2. `datetime` stored as two 4-byte integers which is 8 bytes in total;
Taking into account the above I'm not quite sure here is a real opportunity of a performance improvements.
Does someone have other thoughts?

**Comment by AndrewZ1989** [comment]
FSoul1, the main goal is to reduce number of unnecessary memory allocations.

As I wrote in my original post, 
"...Let's imagine that we read 1 million DateTime values from database. Using existing implementation of TdsParser we will have 1 million allocations of byte[] what causes unnecessary memory traffic and isn't so good for GC."

The size of allocated arrays is small, but there are too many allocations ( you could see huge memory traffic using dotMemory utility ).

And don't focus on ArrayPool or something like that, please. There are other solutions.

**Comment by Wraith2** [comment]
This looks like a good candidate for Spanification. The changes to do so are pretty easy and the existing tests all pass when they're made. The only thing I'm not sure about is whether the existing tests cover the method changed.

**Comment by Wraith2** [comment]
The changes are made in [my branch](https://github.com/Wraith2/corefx/tree/sqldate) and the existing tests pass. 
The [contribution guide](https://github.com/dotnet/corefx/wiki/New-contributor-Docs#contributing-guide) only has a TODO entry about testing changes. I'm unsure how to use my newly compiled assemblies, Attempts to do so in a naïve way adding them as single references fail with binding failures because of nuget package mismatches. I could use some guidance. I need to benchmark both the original and the new versions and run the new one through some tests.

**Comment by danmosemsft** [comment]
@wraith2 does this help?
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md

**Comment by danmosemsft** [comment]
Also this should help you get benchmark results: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/benchmarking.md

**Comment by Wraith2** [comment]
The code changes are done and I've got benchmarks now. 
The changes are only in the netcoreapp builds because they require System.Memory which is currently only used in the netcore builds. KarelZ advised #ifdefing in this way rather than pushing the dependency out to other configurations.

Benchmark results are pretty simple. The test involved reading 100K date, date2 and dateoffsets from a constructed table and iterating through getting their values. Perf is what you'd expect on the original, the more you read of larger sizes the higher the heap usage, with the span version the heap allocs are removed to memory usage is linearly dependent on reading from the database.

``` ini
.NET Core SDK=2.1.300
  [Host]  : .NET Core ? (CoreCLR 4.6.26515.07, CoreFX 4.6.26515.06), 64bit RyuJIT
  Core2.1 : .NET Core 2.1.0 (CoreCLR 4.6.26515.07, CoreFX 4.6.26515.06), 64bit RyuJIT

Job=Core2.1  Runtime=Core  Toolchain=local Core2.1  
LaunchCount=2  TargetCount=15  WarmupCount=10  

```
|         Method |     Mean |     Error |    StdDev | Scaled | ScaledSD |    Gen 0 |  Allocated |
|--------------- |---------:|----------:|----------:|-------:|---------:|---------:|-----------:|
|           Read | 6.301 ms | 0.0210 ms | 0.0301 ms |   1.00 |     0.00 | 226.5625 |  707.73 KB |
|           Date | 7.231 ms | 0.0374 ms | 0.0524 ms |   1.15 |     0.01 | 226.5625 |  707.73 KB |
|          Date2 | 7.378 ms | 0.3344 ms | 0.4902 ms |   1.17 |     0.08 | 531.2500 | 1645.23 KB |
| DateTimeOffset | 7.497 ms | 0.0106 ms | 0.0159 ms |   1.19 |     0.01 | 609.3750 |  1879.6 KB |

``` ini
.NET Core SDK=2.2.100-preview1-009007
  [Host]  : .NET Core ? (CoreCLR 4.6.26525.04, CoreFX 4.6.26707.0), 64bit RyuJIT
  Core2.2 : .NET Core 2.2.0-preview1-26529-01 (CoreCLR 4.6.26525.04, CoreFX 4.6.26525.01), 64bit RyuJIT

Job=Core2.2  Runtime=Core  Toolchain=sdk Core2.2  
LaunchCount=2  TargetCount=15  WarmupCount=10  

```
| Method         |     Mean |     Error |    StdDev | Scaled |    Gen 0 | Allocated |
| -------------- | -------: | --------: | --------: | -----: | -------: | --------: |
| Read           | 6.312 ms | 0.0188 ms | 0.0269 ms |   1.00 | 226.5625 | 707.73 KB |
| Date           | 7.125 ms | 0.0357 ms | 0.0511 ms |   1.13 | 226.5625 | 707.73 KB |
| Date2          | 7.162 ms | 0.0129 ms | 0.0186 ms |   1.13 | 218.7500 | 707.73 KB |
| DateTimeOffset | 7.451 ms | 0.0094 ms | 0.0122 ms |   1.18 | 226.5625 | 707.73 KB |
