### ISSUE TITLE
Memory<T> should implement IReadOnlyList<T>

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#28282]
Migrating corefxlab issue https://github.com/dotnet/corefxlab/issues/903 on behalf of @smmalis37 now that Span/Memory have moved to the corefx repo for .NET Core 2.1:

> Essentially we're constructing a list of objects in C++ code and then accessing this list on the C# side. Since we don't want to duplicate all of these objects (as the lists can be quite large and memory consumption is a concern) we've created a type that acts similarly to the unsafe constructor on Span to access the items without duplicating them and handle type safety. There are some other lists we create on the C# side, and so to make consumption of our API simpler we just expose everything as an IReadOnlyList (since users shouldn't be modifying what we expose). **I'd love to be able to replace our type with Span for simplicity and for "official" support.**

**Comment by benaadams** [comment]
`Memory<T>`'s performance for `IReadOnlyList` would be dreadful as it would need to do a check and create a `Span<T>` for each element access.

Could you expose it as a `ReadOnlyMemory<T>` for same effect?

**Comment by ahsonkhan** [comment]
From https://github.com/dotnet/corefxlab/issues/903#issuecomment-258036803:
> That'd work fine for us as long as there's a constructor that takes a pointer and a count and I can use it to index into it like an array. The reason I initially looked at ReadOnlySpan was because of its `public unsafe ReadOnlySpan(void* ptr, int length)` constructor. I don't see a similar constructor on ReadOnlyMemory?

We likely will not be adding such a ctor to ReadOnlyMemory. @smmalis37, is that a hard requirement for your scenario? Have you tried implementing a `MemoryManager` to provide the functionality you need?

**Comment by smmalis37** [comment]
My scenario just boils down to the following:

- I am returned a T* dataPointer and an int count by calling into some C++ code
- I have no control over how these are constructed and allocated
- I want to expose these as an IReadOnlyList<T>
- The lists may be quite large (millions of elements), so simply duplicating all of the entries would use too much memory
- Iterating through the entire list is common, so minimal overhead would be nice
- The list is guaranteed to never move or be freed once the pointer has been given to me

I currently do have my own type that works just fine for this, so I'm not stuck or anything, I just thought it might be nice if I was able to replace my own type with a built-in one. However since the only values I have are the data pointer and count, having some way to transform those two parameters into something that implements IReadOnlyList is a hard requirement for 'official' support of my scenario.

**Comment by GrabYourPitchforks** [comment]
Think of `Memory<T>` as an abstraction where the sole purpose is to extract a `Span<T>` from some backing store. Getting the backing `Span<T>` might take some amount of work. And while we try to keep the overhead of that small, it's still expensive enough that you definitely _don't_ want to be getting the `Span<T>` over and over again in a tight loop. That's also at the heart of @benaadams's comment. Since the usage pattern is to get the `Span<T>` once, then to iterate over the `Span<T>`, implementing an interface like `IReadOnlyList<T>` from within `Memory<T>` would give callers the wrong impression as to the performance characteristics of the APIs.

Something you might be able to do as an alternative is to define your own `MemoryManager<T>`-subclassed type which wraps your `(T*, int)` backing data. You can have this derived type implement `IReadOnlyList<T>` and whatever other interfaces you find appropriate, and those implementations could be very fast because you'd directly control the implementation and wouldn't need to go through an abstraction. It'd be a length check and dereference. Quick, simple, cheap. You can also wrap a `Memory<T>` around this `MemoryManager<T>` instance if you need to interface with parts of the Framework which accept `Memory<T>` as a parameter.

**Comment by benaadams** [comment]
> You can also wrap a `Memory<T>` around this `MemoryManager<T>` instance if you need to interface with parts of the Framework which accept `Memory<T>` as a parameter.

Or `ReadOnlyMemory<T>` for this case :wink:

> Iterating through the entire list is common, so minimal overhead would be nice

You could then do `.Span` on that to get a `ReadOnlySpan<T>` which would be the smallest overhead to iterate.

**Comment by GrabYourPitchforks** [comment]
@smmalis37 did the comments above help unblock your scenario? Is there any further information you need from us?

**Comment by smmalis37** [comment]
Like I mentioned earlier I have my own type that just performs pointer arithmetic (without using MemoryManager), so I've never really been blocked here. I will look into MemoryManager to see if it supports what I need.

**Comment by GrabYourPitchforks** [comment]
Ok. I'll close this for now because I believe it is resolved, but feel free to reopen if you need to.
