### ISSUE TITLE
SqlDateTime.MinValue returns year 1953 instead of 1753 on netcoreapp2.0

### ISSUE THREAD

**Issue by rmandvikar** [dotnet/corefx#28335]
`SqlDateTime.MinValue` returns year 1953 instead of 1753 on `netcoreapp2.0`. I get the correct year on `net471` (date 1/1/1753). 

```
public static class DateTimeExtension
{
	/// <summary>
	/// Min value for Sql datetime to save in sql db.
	/// </summary>
	public static readonly DateTime SqlDateTimeMinUtc =
		DateTime.SpecifyKind(
			DateTime.Parse(SqlDateTime.MinValue.ToString()),
			DateTimeKind.Utc
			);

	/// <summary>
	/// Gets the min value for Sql datetime.
	/// </summary>
	public static DateTime ToSqlDateTimeMinUtc(this DateTime date)
	{
		return SqlDateTimeMinUtc;
	}
}

[Test]
public void ToSqlDateTimeMinUtc01()
{
	var date = new DateTime().ToSqlDateTimeMinUtc();
	Assert.AreEqual(DateTimeKind.Utc, date.Kind);
	Assert.AreEqual("1/1/1753 12:00:00 AM", date.ToString(CompareDateFormat));
}
```
Below is the travis-ci log snippet and here is [full travis-ci log link](https://travis-ci.org/rmandvikar/csharp-extensions/builds/356540020#L692-L696). 

```
Failed   ToSqlDateTimeMinUtc01
Error Message:
   String lengths are both 20. Strings differ at index 5.
  Expected: "1/1/1753 12:00:00 AM"
  But was:  "1/1/1953 12:00:00 AM"
  ----------------^
```

**Comment by Clockwork-Muse** [comment]
>`DateTime.Parse(SqlDateTime.MinValue.ToString())`

You're converting to text and back.  My first guess is that it's giving/using a 2-digit year.  What is the output of `SqlDateTime.MinValue.ToString()`, please?

Also, is there a reason you're not using [`SqlDateTime.Value`](https://msdn.microsoft.com/en-us/library/system.data.sqltypes.sqldatetime.value(v=vs.110).aspx)?  To/From text seems like a lot of extra work.

**Comment by rmandvikar** [comment]
That was it, the date string had `yy` format instead of `yyyy` format. I changed to use `SqlDateTime.Value`.

Is there a reason why `datetime.ToString()` returns string in `yy` format (ex: `"6/15/09 1:45:30 PM"`) instead of `yyyy` format for `netcoreapp2.0` or perhaps has to do with travis CI machines? On my local machine, I get `yyyy` format on `net471`.

**Comment by Clockwork-Muse** [comment]
Because the culture of the running process on your travis CI machine has a culture set that includes that date format.  This is not guaranteed to be the same culture as whoever ends up using your code - so it might work fine elsewhere, or fail in a similar manner.  Under some circumstances you could use the `InvariantCulture`, but `SqlDateTime.ToString(CultureInfo)` doesn't exist (and having a library change the current process culture is a **terrible** idea).

The correct fix for this problem is also what you should have been doing in the first place: using an explicit cast or the `Value` property.

<hr />

Also, I'm a little lost about why you might have both a property and an extension method....

**Comment by rmandvikar** [comment]
I should simply check the `DateTime` value and its `Kind` instead of round-tripping. You can close this issue if required.

I understand why and how culture works. I should have mentioned this before. On travis ci machines, I get `yy` format dates even when I give the `en-US` culture and/or `"G"` format. This threw me off. On my local machine, I always get `yyyy` format dates ( [full travis log](https://travis-ci.org/rmandvikar/csharp-extensions/builds/357011305#L703-L710) ). 

```
Console.WriteLine(date.ToString());
1/1/53 12:00:00 AM
Console.WriteLine(date.ToString("G"));
1/1/53 12:00:00 AM
Console.WriteLine(date.ToString(new CultureInfo("en-US")));
1/1/53 12:00:00 AM
Console.WriteLine(date.ToString("G", new CultureInfo("en-US")));
1/1/53 12:00:00 AM
Console.WriteLine(date.ToString("M/d/yyyy h:mm:ss tt"));
1/1/1753 12:00:00 AM
Console.WriteLine(CultureInfo.CurrentCulture);
en-US
Console.WriteLine(Thread.CurrentThread.CurrentCulture);
en-US
```

I have a property and extension method for discoverability and to not have to type `DateTimeExtension` (I understand it's confusing).

**Comment by Clockwork-Muse** [comment]
[The travis machine probably has a local override](https://stackoverflow.com/questions/46934175/net-datetime-tostring-culture-en-us-outputs-4-digit-years-on-some-boxes-and-2-d).  

Culture is one of the most insidious runtime dependencies, which is why a library can't blindly do text work (it should rely on either an explicit parameter, or use a permanent one - and ignore all/most overrides - which is usually the invariant culture).

**Comment by rmandvikar** [comment]
Ah, I did not know that. Even
```
date.ToString(new CultureInfo("en-US", false));
```
does not override the culture and I still get date in `yy` format ([travis log](https://travis-ci.org/rmandvikar/csharp-extensions/builds/357099193#L696-L699)). So I gave up and am comparing datetime's value and kind (which is what I should have done in first place).

**Comment by Clockwork-Muse** [comment]
I'm a little fuzzy on all the details (especially since the travis machine seems to be running linux, which I missed earlier), but it's possible that the _only_ "short" format it knows about generates a 2-digit year.  I'm not sure how to set the culture/formats for the travis process, though....
