### ISSUE TITLE
System.Security.Cryptography.Algorithms has reference on the .net4.6.3

### ISSUE THREAD

**Issue by GeorgeAlexandria** [dotnet/corefx#28366]
Hi,

I'm tried to include to the project that targets .net462 **System.Security.Cryptography.Algorithms** 4.3.1 nuget package using nuget package manager and I was surprised when found the reference on the ***.NETFramework4.6.3*** instead of ***.NETFramework4.6.2***, and that package manager added to the project the corresponding assembly for ***.NETFramework4.6.1.***

Does it a small mistake?

**Comment by joshfree** [comment]
@joperezr

**Comment by joperezr** [comment]
I'm not sure what do you mean by:
>I was surprised when found the reference on the .NETFramework4.6.3 instead of .NETFramework4.6.2

I just tried this locally and it correctly resolves the 4.6.1 assembly: 
```xml
    <Reference Include="System.Security.Cryptography.Algorithms, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>..\packages\System.Security.Cryptography.Algorithms.4.3.1\lib\net461\System.Security.Cryptography.Algorithms.dll</HintPath>
    </Reference>
```

If what you refer is to why do we add the reference to a 4.6.1 implementation instead of 4.6.2 then that is by design. NuGet will automatically add a reference from a package to the asset that best applies to the framework you are targetting. In this case, it the asset that best applies from that package is the .NET Framework 4.6.1 one because we don't provide one for 4.6.2.

I'm closing this issue as this is NuGet's design, but please feel free to re-open in case I misunderstood the question.

**Comment by GeorgeAlexandria** [comment]
@joperezr, I know that the Nuget by design uses the asset that best applies to the framework that I'm targeting, so for a .net462 it will apply a .net461 for the current nuget package.

I'm sorry, if I didn't clarify my question, but my question was why does this nuget package contain reference to .net461 and .net463 (as I know .net463 [doesn't exists](https://docs.microsoft.com/en-us/dotnet/framework/whats-new/index)) instead of .net461 and .net462 ? (сonsequently nuget resolves .net461 for `[.net461; .net462]` and .net463 for `[.net4.7; _)` ). 

I tried to find a some article or description why it is, but didn't found anything.

**Comment by bartonjs** [comment]
Because we built that nupkg before the version after net462 got named net47
