### ISSUE TITLE
SemaphoreSlim Dispose thread safety

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#2837]
The documentation of SemaphoreSlim says 'Dispose should only be used when all other operations have completed'.

In practice, for me, I don't bother to Dispose the SemaphoreSlim because I would need to add synchronization to Dispose of this synchronization class. See also, this [question on stackoverflow](http://stackoverflow.com/questions/32035891/dispose-a-semaphoreslim-while-waitasync).

Can SemaphoreSlim be extended so pending operations on other threads throw ObjectDisposedException?

Related to this, I noticed some of the other synchronization classes in System.Threading do not properly document the thread safety behavior of their Dispose method.

Furthermore, the reference source of ReaderWriterLockSlim shows a check in the Dispose method which throws a SynchronizationLockException when the Dispose conditions are not met. SemaphoreSlim and other classes could do the same.

**Comment by hackcraft** [comment]
I'm inclined to think that if you don't reach a point where you know, from the nature of the code already there, that there will be no further use of the semaphore from any thread, it's better to let the finaliser handle it.

**Comment by tmds** [comment]
@hackcraft I agree that is the best approach in those cases.

The code I am writing is a library and my end-user could write his code that he can easily Dispose of the class using 'using'. Other users might never call Dispose and rely on the finalizer. While yet another category of users will want to call Dispose when there are pending operations.
My preferred type of usage is the first, so I would like to support the Dispose operation. For the latter, I think throwing ObjectDisposedException on the pending operation is the proper thing to do.

I think that in general, classes with disposable members should be disposable themselves and disposing a class should throw ObjectDisposedException on pending operations. It is easiest to implement this behavior when the base classes (like SemaphoreSlim) also behave like this.
I haven't found many usages in the corefx repository of SemaphoreSlim, one find shows me that BlockingCollection inherits the dispose restriction from SemaphoreSlim.

**Comment by hackcraft** [comment]
If the pending work "belongs" to your class, then it is up to that classes `Dispose()` to cancel that work. **Then** it could `Dispose()` the semaphor.

**Comment by tmds** [comment]
The work a library does, is typically done for the caller of the library.

Let me summarize the 3 things I am pointing out in this issue:
- Dispose should throw when used inappropriately (e.g. ReaderWriterLockSlim  does this, SemaphoreSlim doesn't)
- Behavior of Dispose should be documented (e.g. not documented for ReaderWriterLockSlim)
- Recommended behavior for async operations when Disposing a class should be described and facilitated by the low level classes (like SemaphoreSlim). In my opinion the recommended behaviour is to throw ObjectDisposedException on those async operations which isn't facilitated by the low level classes.

**Comment by hackcraft** [comment]
SemaphoreSlim correctly cleans up all of its resources when `Dispose()` is called. That fulfils the requirement of `IDisposable` as per how it is documented.

**Comment by tmds** [comment]
@hackcraft you are right, don't you think the semantics of Dispose should be extended to describe the recommended behavior for async operations when calling Dispose?

**Comment by hackcraft** [comment]
I think SemaphorSlim should be slim. If it could be done without impact, then it would seem to be all gain and no loss, so great, but otherwise no, especially since I don't know why you would be disposing of an semaphor that is not ready to be disposed.

**Comment by mikedn** [comment]
> Dispose should throw when used inappropriately (e.g. ReaderWriterLockSlim does this, SemaphoreSlim doesn't)

I'm not sure that `ReaderWriterLockSlim.Dispose` can be relied on, it looks like a giant race condition.

> Behavior of Dispose should be documented (e.g. not documented for ReaderWriterLockSlim)

It's not clear what is not documented about that, the documentation does say that `SynchronizationLockException` can be thrown.

> In my opinion the recommended behaviour is to throw ObjectDisposedException on those async operations which isn't facilitated by the low level classes.

That's likely impractical because it would require Dispose to synchronize with whatever other operation the object allows and synchronization could introducing blocking in a place where it didn't exist before. Even if a blocking Dispose implementation is deemed acceptable there will certain be compatibility concerns about such a change.

Besides, most synchronization primitives use event wait handles under the covers (that's why they need Dispose to begin with) and two things can happen if you try to dispose an event another thread is waiting on:
* The current situation - nothing happens because SafeHandle actively prevents you from disposing a handle that's used in a PInvoke call
* An alternative situation - have SafeHandle to allow Dispose and close the handle (with certain precautions). In this case the waiting thread will forever block on that event as there's no handle left to use in a SetEvent call.

**Comment by tmds** [comment]
@mikedn, in the alternative situation, when thread A calls Dispose, can't the waiting thread (thread B) unblock (e.g. via SetEvent), then Dispose the SafeHandle and throw an ObjectDisposedException?

**Comment by JonHanna** [comment]
If its got a waiting thread, then you have not finished using it.

If you have not finished using it, then why are you calling `Dispose()`?

You seem to want some sort of `ThrowOnAllWaitingThreads()` method, but instead of discussing the pros and cons of that, are talking about `Dispose()` not being `ThrowOnAllWaitingThreads()` as if its some sort of bug.

**Comment by mikedn** [comment]
> in the alternative situation, when thread A calls Dispose, can't the waiting thread (thread B) unblock (e.g. via SetEvent), then Dispose the SafeHandle and throw an ObjectDisposedException?

If I understand correctly you suggest something along the following lines:

```C#
class Event
{
    public void Dispose()
    {
        disposed = true;
        SetEvent(handle);
        handle.Dispose();     
    }

    void WaitOne()
    {
        if (disposed) throw ObjectDisposedException();
        WaitForSingleObject(handle);
        if (disposed) throw ObjectDisposedException();
    }
}
```
Of course, the implementation above is naïve and it has races but the main idea here is that Wait throws **after** the wait is completed if the object was disposed. This should avoid most problems that could be introduced by releasing threads that were not expecting to be released. Unfortunately the same exception can also cause problems in code that didn't expect an exception to be thrown and uses dispose incorrectly.

Another problem with this approach is that in only works for manual reset event and that would make its behavior inconsistent with other synchronization primitives. You can't do it for semaphores because you'd need to call release multiple times. You can't do it for mutexes because only the owner of the mutex can call release. I won't even comment about auto reset events...

Also, it may be worth mentioning that none of the user space synchronization primitives that I've seen (Win32, C++, pthreads) support this, they all treat destroy while in use attempts as undefined behavior. And Java classes such as Semaphore seem to not even have any sort of close/dispose functionality, they probably leave cleanup to the GC.

**Comment by tmds** [comment]
Indeed something along those lines (except for the race conditions).

This shouldn't cause issues for existing implementations as those should not Dispose while there are pending operations.

What's interesting: the behavior is somewhat viral. When the base primitives support this, it becomes easier to implement it when using those primitives. Perhaps the same implementation cannot be shared among all base primitives.

Based on your feedback, I wonder:
- whether it is possible?
- and what would be the cost (cfr @JonHanna's comment)?

**Comment by mikedn** [comment]
> This shouldn't cause issues for existing implementations as those should not Dispose while there are pending operations.

Well, it might cause issues as today Dispose can be accidentally called while another thread waits on the event and everything "works". The code below prints "thread 2 done" "thread 1 done" as if Dispose was not called. No exceptions are thrown in either thread.

```C#
var e = new ManualResetEvent(false);

var t = new Thread(() =>
{
    e.WaitOne();
    Console.WriteLine("thread 2 done");
});

t.Start();
Thread.Sleep(1); // do some other unrelated work
e.Dispose(); // accidental dispose
e.Set(); // works because dispose didn't actually dispose
Console.WriteLine("thread 1 done");
```

Now, I'm not sure if it's worth considering such as a scenario but the fact is that there is a behavior change.

> whether it is possible?

It's very likely possible to do this but getting it right is another matter. Getting rid of race conditions doesn't seem so trivial, using a lock would take care of that but to me it seems very peculiar to use a lock to make a manual reset event thread safe.

**Comment by kouvel** [comment]
Throwing when the object is already disposed or when disposing with unexpected state may make it more consistent but it seems like it would not be very beneficial. The bugs it would find would likely be lifetime/race issues with Dispose, with what may be a missing wait for a task to complete before the object is disposed. The exception is not deterministic in that typical case, and relying on that to find such issues is probably not a good idea.

I'm suggesting no changes here and closing for now.

**Comment by tmds** [comment]
@kouvel Throwing as a means to make lifetime/race issues visible seems like a very beneficial thing to me. I don't get what you mean.

**Comment by kouvel** [comment]
I mean it doesn't seem to me like a frequently enough occurring issue or an important enough issue that requires a fix. It may come useful from time to time, although I don't remember a case where this would have been useful to me, as I'm usually pretty explicit about managing object lifetimes and lifetime of background work.

Even if it is useful, when object lifetime is concerned, I would actually prefer to keep the contract simple by stating that using an object during or after Dispose is undefined. If one really wanted, they could wrap the object in their own disposable object that throws, asserts, logs, or whatever they want in such a case.
