### ISSUE TITLE
System.Numerics.Vector4 calculates incorrect in some inlining situations.

### ISSUE THREAD

**Issue by soyemi** [dotnet/corefx#28499]
Sample Code
```csharp
using System;
using System.Numerics;
namespace DotNetNumericTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var rect = new Vector4(10, 20, 100, 30);
            var v = Test(rect, new Vector2(100, 100));
            Console.WriteLine(v);
            Console.ReadLine();
        }
        public static Vector4 Test(Vector4 v, Vector2 off)
        {
            v.X += off.X;
            v.Y += off.Y;
            return v;
        }
    }
```
Excepted output: `<110, 120, 100, 30>`
Incorrect output: `<10, 20, 100, 30>` using release build.

After attatching `MethodImplOptions.NoInlining` to the method Test(), it prints right answer.
It seems like the operator '+=' affects the result.

Test on .netcore 2.1.103, windows.

**Comment by joshfree** [comment]
@CarolEidt @eerhardt

**Comment by eerhardt** [comment]
I can't seem to repro this.  I tried with both `2.0.6` and `2.1.0-preview2-26228-02` runtimes on Windows.  Similarly, I couldn't repro it on my macOS either.

@soyemi - can you give more information on your environment?  What processor?  What Windows version, etc?

/cc @tannergooding - in case he has any ideas.

**Comment by soyemi** [comment]
system-Windows10 1709 16299.309, CPU-i7 4790, dotnet version 2.1.100.
I have reproduced these on two different Windows10 devices.

test command line outputs.
```console
F:\NumericTest\NumericTest>dotnet build -c Debug
用于 .NET Core 的 Microsoft (R) 生成引擎版本 15.6.82.30579
版权所有(C) Microsoft Corporation。保留所有权利。

  Restore completed in 35.69 ms for F:\NumericTest\NumericTest\NumericTest.csproj.
  NumericTest -> F:\NumericTest\NumericTest\bin\Debug\netcoreapp2.0\NumericTest.dll

已成功生成。
    0 个警告
    0 个错误

已用时间 00:00:01.61

F:\NumericTest\NumericTest>dotnet run -c Debug
<110, 120, 100, 30>

F:\NumericTest\NumericTest>dotnet build -c Release
用于 .NET Core 的 Microsoft (R) 生成引擎版本 15.6.82.30579
版权所有(C) Microsoft Corporation。保留所有权利。

  Restore completed in 35.85 ms for F:\NumericTest\NumericTest\NumericTest.csproj.
  NumericTest -> F:\NumericTest\NumericTest\bin\Release\netcoreapp2.0\NumericTest.dll

已成功生成。
    0 个警告
    0 个错误

已用时间 00:00:01.60

F:\NumericTest\NumericTest>dotnet run -c Release
<10, 20, 100, 30>
```
Here is the project files, see if anything helps.
[NumericTest.zip](https://github.com/dotnet/corefx/files/1852297/NumericTest.zip)

**Comment by eerhardt** [comment]
Ok, I know my mistake, I was running against a `Debug` build of my project.  Using `dotnet run -c Release` I was able to repro this on the `2.0.6` runtime on Windows, but not on macOS.

The good news is that this appears to be fixed in the latest .NET Core `2.1` runtime builds.  I used `2.1.0-preview2-26228-02` on Windows, and it no longer repro'd.

@CarolEidt @AndyAyersMS @RussKeldorph @jkotas - Do any of you feel this is important enough to fix in a `2.0.x` service release?  If so, we should move this issue to `dotnet/coreclr`.

**Comment by CarolEidt** [comment]
Since there is a workaround, and it appears to be fixed in 2.1, it doesn't seem critical to fix it in a service release, but it would be good to verify that the problem has been fixed, rather than simply hidden by some other change.

**Comment by tannergooding** [comment]
Here are the disassembly and dumps for the program using release/2.0.0 and release/2.1 in x64 Checked mode:
* [JitDisasm_2.0.txt](https://github.com/dotnet/corefx/files/1852787/JitDisasm_2.0.txt)
* [JitDisasm_2.1.txt](https://github.com/dotnet/corefx/files/1852788/JitDisasm_2.1.txt)
* [JitDump_2.0.txt](https://github.com/dotnet/corefx/files/1852789/JitDump_2.0.txt)
* [JitDump_2.1.txt](https://github.com/dotnet/corefx/files/1852790/JitDump_2.1.txt)

The dumps are different enough now that it is actually a bit difficult to review the changes.

The disassembly is much easier to parse and is indeed doing all the right things. They are also functionally identical (aside from register allocations) up until the `System.Console.WriteLine` call.

For 2.0, the code just loads the value form xmm6, which still contains the originally initialized value `{ 10, 20, 100, 30 }`, rather than the updated value which is stored at `[rsp + 0x30]`.

For 2.1, the code correctly copies the value from `[rsp + 0x30]` to the shadow stack space (`[rcx + 0x08]`).

It is probably worth noting that the overall codegen here is pretty bad in both cases and could probably be improved (but that is a separate issue)...

**Comment by tannergooding** [comment]
I logged a couple of bugs for the most obvious codegen issues.

**Comment by eerhardt** [comment]
Closing since this bug is fixed in `.NET Core 2.1`.

If this needs to be back ported to `.NET Core 2.0.x`, please open an issue in `dotnet/coreclr` for it.
