### ISSUE TITLE
Test System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent failed in CI.

### ISSUE THREAD

**Issue by Sunny-pu** [dotnet/corefx#28497]
Test System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent failed.

Details: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/417/testReport/System.Threading.Threads.Tests/ThreadTests/ApartmentState_AttributePresent_AppName____STAMain_exe____mode____GetApartmentState___/

MESSAGE:
Assert.Equal() Failure\nExpected: 2\nActual: 32899
+++++++++++++++++++
STACK TRACE:
at System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(String AppName, String mode) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/System.Threading.Thread/tests/ThreadTests.cs:line 169

**Comment by kouvel** [comment]
This exit status 32899 is odd, according to [this](https://developer.apple.com/library/content/documentation/OpenSource/Conceptual/ShellScripting/ResultCodes,Chaining,andArgumentParsing/ResultCodes,Chaining,andArgumentParsing.html), they are supposed to be in 0-255 range. In the System.Native Process PAL, it looks like [here](https://github.com/dotnet/corefx/blob/master/src/Native/Unix/System.Native/pal_process.cpp#L448), `exitCode` is not initialized on all paths. The caller checks, but is it possible in any case for the caller's check following this call to succeed without this call having initialized `exitCode`?

CC @joperezr @wtgodbe

**Comment by joperezr** [comment]
@kouvel do you have a consistent repro of this? I'm not sure exactly why you would get that error code back, but this still feels like a Threading issue to me.

**Comment by kouvel** [comment]
It doesn't look like a consistent repro, the test has been around for a few months and is not disabled. Unless I'm missing something, the threading part seems pretty straightfoward - it's basically just testing the behavior of a function that returns a constant value in a child process. On Unix, GetApartmentState() returns ApartmentState.Unknown (https://github.com/dotnet/corefx/blob/master/src/System.Threading.Thread/src/System/Threading/Thread.Unix.cs#L11) and any attempt to change it would throw. The child process portion of the test is pretty straight forward: https://github.com/dotnet/corefx/blob/master/src/System.Threading.Thread/tests/STAMain/STAMain.cs#L32. If this is not likely to be a Process / exit status issue, I would propose to close it and see if it happens again. May have been a one-off issue that has since been fixed elsewhere.

**Comment by joperezr** [comment]
sounds good to me. Closing.
