### ISSUE TITLE
Mega-solution needed

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/corefx#28538]
As a newbie to this repo, I find it very difficult to figure out where anything is. And when I do finally find what I need, I then have to try finding out where the test classes are. I'm sure it makes sense once you get it, but I don't get it. Beyond just finding classes, I'd love to able to navigate from project to project using F12 and Shift-F12, to see where the member was defined or what other members access it.

I think a solution that contained all the projects and all the test projects would be immensely beneficial. I couldn't find an issue here on this topic, but I have seen other baffled developers on the forums.

Thoughts?

**Comment by weshaggard** [comment]
We don't have a specific issue on this top but it is by design that we don't have a single solution for the entire repo. The repo is just too large and diverse to make that work in a reasonable way. Instead we have solutions per library which allows developers to focus on development of a given library. 

In case your interested there is a large discussion at https://github.com/dotnet/corefx/issues/20570 which is about the development experience for contributors to corefx.

**Comment by wfurt** [comment]
should this be closed @weshaggard ? It seems like we do not expect any work here.
