### ISSUE TITLE
Crypo transforms should truncate long initialization vectors for compatibility

### ISSUE THREAD

**Issue by mjrousos** [dotnet/corefx#28553]
TripleDESCryptoServiceProvider expects a 24 byte key and 8 byte initialization vector. 

In .NET Framework, if an IV longer than the algorithm's block size (8 bytes) was used, [it would be truncated](https://referencesource.microsoft.com/#mscorlib/system/security/cryptography/tripledescryptoserviceprovider.cs,101). In .NET Core, though, [an exception is thrown](https://github.com/dotnet/corefx/blob/1ce37dfb5a03e5decdb25ee67ef765f89424ceb1/src/System.Security.Cryptography.Algorithms/src/Internal/Cryptography/TripleDesImplementation.cs#L64). 

This makes .NET Framework-targeted libraries that would otherwise be usable from .NET Core fail. It would be good to truncate the IV for compatibility's sake.

Repro
------

Create a .NET Framework-targeted library using a too-long IV:

```CSharp
public class CryptoHelper
{
    public static string Encrypt(string input)
    {
        var key = new byte[24] { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B,
                                 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, };

        // This should only be 8 bytes
        var iv = new byte[24] { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B,
                                 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, };

        var des = new TripleDESCryptoServiceProvider();
        var encryptor = des.CreateEncryptor(key, iv);
        
        var data = Encoding.UTF8.GetBytes(input);
        return Convert.ToBase64String(encryptor.TransformFinalBlock(data, 0 , data.Length));
    }
}
```

Use the library from a .NET Core application:
```CSharp
Console.WriteLine(CryptoHelper.Encrypt("Hello world!"));
```

This results in the following exception:

```
Unhandled Exception: System.ArgumentException: Specified initialization vector (IV) does not match the block size for this algorithm.
Parameter name: rgbIV
   at Internal.Cryptography.TripleDesImplementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting)
   at Internal.Cryptography.TripleDesImplementation.CreateEncryptor(Byte[] rgbKey, Byte[] rgbIV)
   at System.Security.Cryptography.TripleDESCryptoServiceProvider.CreateEncryptor(Byte[] rgbKey, Byte[] rgbIV)
   at CryptoHelper.Encrypt(String input)
   at console.Program.Main(String[] args) in C:\temp\console\Program.cs:line 12
```

If the .NET Core app targets net461 instead, however, it works!
```
C:\temp\console>type console.csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="CryptoHelper">
      <HintPath>CryptoHelper.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>

C:\temp\console>dotnet run
jOr/uvaiDXmJ/aKNevYkgQ==
```

**Comment by bartonjs** [comment]
It depends on how much we care about preserving wrong behaviors.  While TripleDESCryptoServiceProvider has this bug AesCryptoServiceProvider doesn't: https://referencesource.microsoft.com/#System.Core/System/Security/Cryptography/AesCryptoServiceProvider.cs,233

We're intentionally not preserving all of the bugs with the RijndaelManaged implementation and the fact that it was the (more full) Rijndael algorithm instead of the (restricted Rijndael) AES algorithm; because we intentionally got rid of the managed implementation.

So in this case I think there's arguably an action to make the TripleDESCryptoServiceProvider fake wrapper type trim down the IV.

Personally, I'd rather see bugs like this in cryptography NOT be preserved, since it's not interoperable.

**Comment by mjrousos** [comment]
Yea, we definitely don't want bug-for-bug compatibility. This one (truncating the IV) feels pretty harmless, though, and may make NetFX -> NetCore transitions a little easier.

What do you mean that it isn't interoperable?

**Comment by bartonjs** [comment]
> What do you mean that it isn't interoperable?

The bug is on TripleDESCryptoServiceProvider  (in netfx), but probably not TripleDESCng (which, for some reason, isn't on referencesource so I can't check right now), and the same data against other platforms/libraries may also fail.  Assuming that any library which accepted "too big" just reads the first block-size of inputs it would produce the same data, but once it's the wrong size there's no "correct" answer to rely on.

**Comment by bartonjs** [comment]
Let's see how well a checklist works for this:

* DES
  * DESCryptoServiceProvider
    * [ ] Already matches netfx
    * [ ] Needs work
* TripleDES
  * TripleDESCryptoServiceProvider
    * [ ] Already matches netfx
    * [ ] Needs work
  * TripleDESCng
    * [ ] Already matches netfx
    * [ ] Needs work
* Rijndael
  * RijndaelManaged
    * [ ] Already matches netfx
    * [ ] Needs work
* AES
  * AesManaged
    * [ ] Already matches netfx
    * [ ] Needs work
  * AesCryptoServiceProvider
    * [ ] Already matches netfx
    * [ ] Needs work
  * AesCng
    * [ ] Already matches netfx
    * [ ] Needs work
* RC2
  * RC2CryptoServiceProvider
    * [ ] Already matches netfx
    * [ ] Needs work

**Comment by ianhays** [comment]
## Net471
```
DESCryptoServiceProvider      : Passes
TripleDESCryptoServiceProvider: Passes
TripleDESCng                  : Throws ArgumentException     : The specified initialization vector (IV) does not match the
RijndaelManaged               : Throws CryptographicException: Specified initialization vector (IV) does not match the bloc
AesManaged                    : Throws ArgumentException     : The specified initialization vector (IV) does not match the
AesCryptoServiceProvider      : Throws ArgumentException     : The specified initialization vector (IV) does not match the
AesCng                        : Throws ArgumentException     : The specified initialization vector (IV) does not match the
RC2CryptoServiceProvider      : Passes
```

## Netcoreapp
```
DESCryptoServiceProvider      : Passes
TripleDESCryptoServiceProvider: Throws ArgumentException     : Specified initialization vector (IV) does not match the bloc
TripleDESCng                  : Throws ArgumentException     : Specified initialization vector (IV) does not match the bloc
RijndaelManaged               : Throws ArgumentException     : Specified initialization vector (IV) does not match the bloc
AesManaged                    : Throws ArgumentException     : Specified initialization vector (IV) does not match the bloc
AesCryptoServiceProvider      : Throws ArgumentException     : Specified initialization vector (IV) does not match the bloc
AesCng                        : Throws ArgumentException     : Specified initialization vector (IV) does not match the bloc
RC2CryptoServiceProvider      : Passes
```

## Differences
```
DESCryptoServiceProvider      : Same
TripleDESCryptoServiceProvider: Pass net471, throws ArgException on netcoreapp
TripleDESCng                  : Same
RijndaelManaged               : CryptoException on net471, ArgException on netcoreapp
AesManaged                    : Same
AesCryptoServiceProvider      : Same
AesCng                        : Same
RC2CryptoServiceProvider      : Same


In my opinion the ArgumentExceptions we're doing in netcoreapp are the best option as easy interoperability between the algorithms it preferable to the varying behaviors of netfx.

**Comment by ianhays** [comment]
I'm strongly in favor of having the implementations of an algorithm behave as closely as possible. So in this case we should either have 3DESCng and 3DESCsp both throw or have them both trim.

**Comment by bartonjs** [comment]
@ianhays Cool, your test looks like the same conclusion I was building up to.

My personal opinion is that the real bug is within TripleDESCryptoServiceProvider:netfx (and a "wrong type" one in RijndaelManaged:netfx).  But I'm willing to sigh and add the compatibility thing where TripleDESCryptoServiceProvider:corefx will make a smaller copy (when needed) when passing the IV down to the real implementation.

After all, the type TripleDESCryptoServiceProvider only exists in corefx _for_ compatibility.  We certainly don't actually call into CAPI anymore.  (TripleDESCng has extra platform capabilities like having an out-of-proc key)
