### ISSUE TITLE
HttpClient Timeout Confusion

### ISSUE THREAD

**Issue by normj** [dotnet/corefx#2857]
The HttpClient from the System.Net.Http package has Timeout property that defaults to a 100 seconds which as I read through the code just means how long till the task is cancelled. The underlying windows handler WinHttpHandler has the timeout properties ConnectionTimeout, SendTimeout, ReceiveHeadersTimeout and ReceiveDataTimeout which default to 30 seconds except for ConnectionTimeout which defaults to 60 seconds.

If you have an operations that takes say 40 seconds before it return back any data it will always timeout after 30 seconds. Only way to get around this is to code against the platform specific WinHttpHandler and set the timeout properties.

Am I missing something about how to set timeout in a platform agnositic approach?

Here is the code I wrote that directly uses the WinHttpHandler but I want to code just against the HttpClientHandler.

```
private HttpClient CreateHttpClient()
{
    var httpMessageHandler = new System.Net.Http.WinHttpHandler();

    httpMessageHandler.SendTimeout = TimeSpan.FromSeconds(200);
    httpMessageHandler.ReceiveDataTimeout = TimeSpan.FromSeconds(200);
    httpMessageHandler.ReceiveHeadersTimeout = TimeSpan.FromSeconds(200);
    var httpClient = new HttpClient(httpMessageHandler);
    httpClient.Timeout = TimeSpan.FromSeconds(200);


    return httpClient;
}
```

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar @ericstj

**Comment by davidsh** [comment]
That is probably a bug.  If you're using the HttpClientHandler directly, then it is supposed to set the inner WinHttpHandler timeouts to basically infinite so that the HttpClientHandler API surface area will thus control the operation's timeouts.

**Comment by GSPP** [comment]
I don't know why we need all those timeouts anyway. Probably there should be a `TotalTimeout` property that covers the entire process from the connection attempt until the stream is drained. This is the behavior that most apps want. They want a time bound so that the app is guaranteed to make progress.

I can see the need for the individual timeouts as well but the `TotalTimeout` proposal seems to be what 99% of the use cases are about.

**Comment by hackcraft** [comment]
Individual timeouts are more useful as a guarantee that you aren't going to wait indefinitely.

If I need something done in e.g. 5 seconds, then the total timeout of 5 seconds is all I care about.

But if I just need something done, then there's a difference between something that's been stuck for 90 seconds, but is now on its 3rd of 4 steps, and something that's been stuck on the 2nd step for all of those 90 seconds.

**Comment by GSPP** [comment]
I think in your first statement you meant the total timeout, right? Because that is a stricter bound than individual timeouts.

Even if the HTTP call is slowly making progress this is unhealthy and should be shut down. Arbitrarily slow apps are often worse than quick failures. Resource usage accumulates. I cannot think of any case where I would want an HTTP call to carry on if I receive 1KB of data every few seconds (except of course if it is explicitly a slow streaming call which is extremely rare).

In all the apps I have written I never wanted to extend the timeout of anything when progress slowly trickles in. Especially not in a non-deterministic way. Can you make concrete examples where you would want that to happen (excluding the valid but rare case of long-term streaming)?

**Comment by hackcraft** [comment]
I often have things that are going to do a lot of downloads, often large, over a long period of time. I don't care how long it takes in that case, and the fewer failed attempts in the logs on Monday morning, the better.

Individual timeouts and total timeouts serve different purposes differently well.

**Comment by SidharthNabar** [comment]
@hackcraft , @GSPP  The HttpClient.Timeout property is intended to be exactly what you are referring to as the 99% case: an end-to-end timeout after which the request expires. The WinHttpHandler API is intended to provide a deeper control to developers for more advanced scenarios. In keeping with this intention, we have more granular timeouts on that type since we have gotten developer requests in the past who asked for control over a specific stage of the request.

If you see that the HttpClient.Timeout property value is not being respected and the request is timing out prematurely, that should be a bug - please report that along with repro code to us.

Thanks
Sid

**Comment by normj** [comment]
Okay, I'll put together repro code.

**Comment by normj** [comment]
Here is the code to reproduce the bug. 

A simple webserver that will sleep in a request if there is a timeout query parameter exists.
```
    public class Startup
    {
        // For more information on how to configure your application, visit http://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
        }

        public void Configure(IApplicationBuilder app)
        {
            app.Run(async (context) =>
            {
                var value = context.Request.Query["Timeout"];
                if(value != null)
                {
                    var timeout = int.Parse(value);
                    Console.WriteLine("Got request to wait for {0} seconds", timeout);
                    Thread.Sleep(TimeSpan.FromSeconds(timeout));
                    await context.Response.WriteAsync(string.Format("Waiting for {0} seconds", timeout));
                }
                else
                {
                    await context.Response.WriteAsync("No timeout");
                }
                
            });
        }
    }
```
In this client application I set the timeout to 60 seconds on the HttpClient and make 2 requests. The first with a timeout of 20 seconds which succeeds and the second with a timeout of 40 seconds which fails ignoring my original 60 second timeout set on the HttpClient.

```
    public class Program
    {
        public void Main(string[] args)
        {
            HttpClient client = new HttpClient() { BaseAddress = new Uri("http://localhost:5000") };
            client.Timeout = TimeSpan.FromSeconds(60);

            // This one will work because it is below the 30 second HttpClient will wait regardless of Timeout
            AttemptCall(client, 20); 

            // This one will fail because it is past 30 seconds.
            AttemptCall(client, 40); 

            Console.WriteLine("All Done");
        }

        public void AttemptCall(HttpClient client, int timeout)
        {
            Console.WriteLine("Attempting request with {0} wait time", timeout);
            try
            {
                HttpRequestMessage message = new HttpRequestMessage(HttpMethod.Put, "?Timeout=" + timeout);
                var response = client.SendAsync(message).Result;
                response.EnsureSuccessStatusCode();
            }
            catch(Exception e)
            {
                WriteException(e);
            }
        }

        public static void WriteException(Exception exception)
        {
            var writer = new System.IO.StringWriter();
            var lastStacktrace = exception.StackTrace;
            var tabCount = 0;
            var currentException = exception;

            while (currentException != null)
            {
                writer.WriteLine("{0}{1}", new string('\t', tabCount), currentException.Message);
                lastStacktrace = currentException.StackTrace;

                tabCount++;
                currentException = currentException.InnerException;
            }

            writer.WriteLine(lastStacktrace);

            Console.Error.WriteLine(writer.ToString());
        }
```

**Comment by davidsh** [comment]
Fixed by #2973.

**Comment by normj** [comment]
Awesome Thanks!

**Comment by hbksagar** [comment]
Hi @SidharthNabar, Thanks for mentioning WinHTTPhandler. 

I have a requirement where I need to support ConnectTimeout and ReceiveDataTimeout on a native SDK which will be running on windows server 2008 r1 sp2 and has a support for dotnet 4.0. 

As far as the [WinHTTPhandler nuget package](https://www.nuget.org/packages/System.Net.Http.WinHttpHandler/) requires dotnet 4.6. Is there anyway I could use this package or is there any alternative for the same.

Thank you in Advance.

**Comment by davidsh** [comment]
>As far as the WinHTTPhandler nuget package requires dotnet 4.6. Is there anyway I could use this package or is there any alternative for the same.

Unfortunately, no.  You need to be on a more recent version of .NET Framework in order to use the WinHttpHandler.

**Comment by rolandh** [comment]
You say that this is fixed. What release is it fixed in? I am using .net 4.6.1 building x86 and I find the timeout value is actually a strange multiple of what it should be.
