### ISSUE TITLE
Build fails with System.Threading.Tasks.Extensions.4.4.0

### ISSUE THREAD

**Issue by mogikanin** [dotnet/corefx#28597]
I attached simple sample project - just empty class library with one dependency `System.Threading.Tasks.Extensions.4.4.0`. 
Build from Visual Studio works fine, but if you try to build solution via msbuild (Build.bat near solution file) then build fails.

```
"c:\Projects\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj" (Rebuild target) (2) ->
(ImplicitlyExpandNETStandardFacades target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\Micro
soft.NET.Build.Extensions.NETFramework.targets(65,5): error MSB4062: The "NETBuildExtensionsError" task could not be lo
aded from the assembly C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.B
uild.Extensions\\tools\net46\Microsoft.NET.Build.Extensions.Tasks.dll.  Confirm that the <UsingTask> declaration is cor
rect, that the assembly and all its dependencies are available, and that the task contains a public class that implemen
ts Microsoft.Build.Framework.ITask. [c:\Projects\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj]
```

The issue is not reproduced with  System.Threading.Tasks.Extensions.4.3.0

[ClassLibrary1.zip](https://github.com/dotnet/corefx/files/1860435/ClassLibrary1.zip)

**Comment by joperezr** [comment]
It might very well be that we use the TargetFramework property for something else in our build, so the user passing in the wrong property on the build command is not expected and breaks the build. I don't think that there is an issue here since as @tarekgh suggests, running just MSBuild on the solution works fine. For that reason, I will close the issue. Also, just for future reference, these kind of issues are not related to the framework itself, so a more appropriate place for them would probably be https://github.com/Microsoft/MSBuild

**Comment by mogikanin** [comment]
Yeah, thanks! Don't know why we used `TargetFramework` instead of `TargetFrameworkVersion`, probably it was silly typo :)
