### ISSUE TITLE
Add CI leg for non ENU Windows

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#28729]
Roslyn has successfully added such a leg based on es-ES

Please add a CI leg for corefx following this pattern: https://github.com/dotnet/roslyn/commit/b282a6486f1a7f09ceee7fcd9ed5d24d67cc4af7

It should be optional at first until we get it clean.

When in place this should avoid introducing many of the kinds of issues @AlexRadch has recently been working through

**Comment by danmosemsft** [comment]
cc @jaredpar I found your commit.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/roslyn/pull/25874

**Comment by svick** [comment]
It probably doesn't make much of a difference, but why choose es-ES?

I think that the best culture to use is one that has the most differences from en-US. The ones that come to my mind are:

* tr-TR (Turkish), because in addition to using comma as decimal separator, it also has different rules for lower/uppercasing.
* cs-CZ (Czech), because in addition to using comma as decimal separator, it also uses non-ASCII character (U+00A0 NO-BREAK SPACE) as thousand separator.

**Comment by jaredpar** [comment]
> It probably doesn't make much of a difference, but why choose es-ES?

It was chosen for roslyn for a very critical reason: there was a VM available 😄 

I agree there could be other more challenging languages for us to choose. At the time we started this though only es-ES was on hand to try. Hence we started there.
