### ISSUE TITLE
HttpClientHandler.UseDefaultCredentials does not work on Unix platforms

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#28847]
When this this is set to True, we should use identity of currently logged user for authentication to HTTP(s) severs or proxies. 

Note, that on Windows  this works only for NTLM and NEGOTIATE as there is no way how to extract clear text password for  Basic or Digest authentication.

On Unix, there is typically not centralized identity management nor strong cryptographic ID.

However when Kerberos is configured, curl is able to use default principal from ticket if user previously authenticated using kinit.  

> build@toweinfu-ubu17:~/github/corefx/src$ klist
> Ticket cache: FILE:/tmp/krb5cc_1000
> Default principal: testuser@TEST.NET
> 
> Valid starting       Expires              Service principal
> 04/05/2018 06:12:30  04/05/2018 16:12:30  krbtgt/TEST.NET@TEST.NET
> 	renew until 04/06/2018 06:12:24
> 

This does not work neither for CurlHandler nor for SocketsHttpHandler.

Further more, ,many Unix utilities (wget, curl, git, ftp, ...) can read credentials from .netrc file.
That is not great but it is still better than hardcoding secrets in code or passing them via environmental variable. If we choose to, this could be also source of default credentials (basic support tracked by #23313)

**Comment by davidsh** [comment]
>This does not work neither for CurlHandler nor for SocketsHttpHandler.

Based on my investigations in #30203, I showed that HttpClientHandler.UseDefaultCredentials will work on a Linux client to a Windows server as long as the machines are correctly configured.  And that means that not only is kerberos installed on the Linux client, but the Linux client is properly joined to the Windows domain (i.e. the presence of a .keytab file etc.).

And for default credentials to work, there needs to be a initial "kinit" so that there is a kerberos ticket available.

See: https://github.com/dotnet/corefx/issues/30203#issuecomment-395990520

So, is there any action item left for this current issue?

**Comment by wfurt** [comment]
Socker handler was fixed by #28982. I think it is ok to close this.
