### ISSUE TITLE
Test System.Data.Tests.SqlTypes.SqlInt64Test.ReadWriteXmlTest failed with "System.NullReferenceException : Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by Sunny-pu** [dotnet/corefx#28921]
Test System.Data.Tests.SqlTypes.SqlInt64Test.ReadWriteXmlTest has failed.

MESSAGE:
System.NullReferenceException : Object reference not set to an instance of an object.
~~~
STACK TRACE:
at System.Collections.Generic.Dictionary`2.FindEntry(TKey key) in /root/coreclr/src/mscorlib/shared/System/Collections/Generic/Dictionary.cs:line 410 at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value) in /root/coreclr/src/mscorlib/shared/System/Collections/Generic/Dictionary.cs:line 873 at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_centos7.1_release/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs:line 267 at System.Data.Tests.SqlTypes.SqlInt64Test.ReadWriteXmlTestInternal(String xml, Int64 testval, String unit_test_id) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_centos7.1_release/src/System.Data.Common/tests/System/Data/SqlTypes/SqlInt64Test.cs:line 724 at System.Data.Tests.SqlTypes.SqlInt64Test.ReadWriteXmlTest() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_centos7.1_release/src/System.Data.Common/tests/System/Data/SqlTypes/SqlInt64Test.cs:line 750
~~~

Details:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_centos7.1_release/364/testReport/System.Data.Tests.SqlTypes/SqlInt64Test/ReadWriteXmlTest/

**Comment by danmosemsft** [comment]
@v-haren can you please try to format callstacks so they're easier to read? eg in this case like this would work:
```

at System.Collections.Generic.Dictionary`2.FindEntry(TKey key) in /root/coreclr/src/mscorlib/shared/System/Collections/Generic/Dictionary.cs:line 410

System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value) in /root/coreclr/src/mscorlib/shared/System/Collections/Generic/Dictionary.cs:line 873

System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_centos7.1_release/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs:line 267

System.Data.Tests.SqlTypes.SqlInt64Test.ReadWriteXmlTestInternal(String xml, Int64 testval, String unit_test_id) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_centos7.1_release/src/System.Data.Common/tests/System/Data/SqlTypes/SqlInt64Test.cs:line 724

System.Data.Tests.SqlTypes.SqlInt64Test.ReadWriteXmlTest() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_centos7.1_release/src/System.Data.Common/tests/System/Data/SqlTypes/SqlInt64Test.cs:line 750
```

**Comment by saurabh500** [comment]
This issue boils down to an exception thrown in XmlSerializer constructor, when invoked at line https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/tests/System/Data/SqlTypes/SqlInt64Test.cs#L724 

At the line above, there is no System.Data stack involved.
This should be looked at by the area owners of System.Xml

**Comment by krwq** [comment]
@saurabh500 any chance you could simplify the repro to Xml/Serialization?

**Comment by krwq** [comment]
cc: @huanwu @zhenlan

**Comment by saurabh500** [comment]
I don't think there is much to simplify here. As you mentioned the call failed when `new XmlSerializer(typeof(SqlInt64));` is called. 
Looks like there is a single hit of this failure, so repro may not be trivial.

**Comment by saurabh500** [comment]
It seems to me that there could be concurrent reads and writes to the Dictionary backing TempAssemblyCache causing this problem or NRE. 
There is a static `s_cache` at `private static TempAssemblyCache s_cache = new TempAssemblyCache();` which is backed by a dictionary https://github.com/dotnet/corefx/blob/91a83313344bd96127dbc2c50723a930f93c33c5/src/System.Private.Xml/src/System/Xml/Serialization/Compilation.cs#L656

There are concurrent reads and writes possible to this dictionary.
The reads can happen at  https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs#L267
 and the writes happen at https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs#L301 

At the same time, since `s_cache` is static this can be written to or read from any other test running in .Net Core.

Dictionary was never designed for concurrent reads and writes as shown by @stephentoub in https://github.com/dotnet/corefx/issues/28198 and a simplified repro is posted here https://github.com/dotnet/corefx/issues/28198#issuecomment-374444105

The fix that was made for such concurrent reads and writes to `Dictionary` was to replace it with a `ConcurrentDictionary` in the PR https://github.com/dotnet/corefx/pull/28248 for a related issue. 

This usage was probably not caught, because the Dictionary object is itself not static, but the class encapsulating the dictionary is.

**Comment by stephentoub** [comment]
@saurabh500's analysis looks right to me.

**Comment by mconnew** [comment]
@stephentoub and @saurabh500, there is a race condition here but it's due to a bug in TempAssemblyCache and not in the usage of Dictionary vs ConcurrentDictionary. TempAssemblyCache.Add creates a new instance of Dictionary containing the contents of the previous instance, and then adds the new entry to the dictionary. The bug is that it replaces TempAssemblyCache._cache too soon. It replaces it before adding the new entry. The fix is to assign the new Dictionary instance to a local variable on the copy instantiation, add the new entry and then assign it to the _cache field. TempAssemblyCache.Add takes a lock so this is only happening on one thread at a time to prevent one thread from losing the work that another thread did.  
As this dictionary isn't holding arbitrary data and is bounded by the number of types you create a serializer for, it's usage is basically a handful of writes and a very large number of reads. So the code was written to optimize reads at the cost of relatively expensive writes (because a whole new copy of dictionary is instantiated for every write).
