### ISSUE TITLE
URI fails to find when # is present in local file path

### ISSUE THREAD

**Issue by JCBurnside** [dotnet/corefx#29027]
**Steps to Reproduce:**

1)Create a directory with # in it's name.
2)Try to access the directory via URI and FileInfo(Uri)

**Expected Behavior:**
Able to access resources contained within the directory.

**Actual Behavior:**
URI fails to locate any files contained within the directory.

**Comment by davidsh** [comment]
cc: @rmkerr

**Comment by rmkerr** [comment]
Hey @JCBurnsidem, thanks for the report! What OS and what version of .NET Core are you using?

**Comment by JCBurnside** [comment]
win10.  and I was sent here from https://github.com/dotnet/roslyn but it is targeting net461.

**Comment by rmkerr** [comment]
This repository specifically tracks .NET Core, which is separate from .NET Framework. If you can provide a small isolated repro of the issue though, we can test it and see if it occurs in .NET Core and newer versions of .NET Framework.

**Comment by rmkerr** [comment]
Actually, I took a look at how FileInfo works and I have a better suggestion. Try to access the directory using `FileInfo(Uri.LocalPath)` instead. That should keep System.Uri from treating the section of the path following the '#' as a URI fragment.

**Comment by JCBurnside** [comment]
same result.  also I tried using the string version of the path (that I would put into the URI anyways) so it is something to do with how FileInfo loads the filepath
example repo: https://github.com/JCBurnside/UriErrorExample

**Comment by rmkerr** [comment]
Thanks for the repro! I'll take a look.

**Comment by rmkerr** [comment]
These lines are incorrect:
```csharp
FileInfo uriFile = new FileInfo(new Uri(typeof(Program).Assembly.Location + "/testingfolder/testingdoc.txt").LocalPath);
FileInfo stringFile = new FileInfo(typeof(Program).Assembly.Location + "/testingfolder/testingdoc.txt");
```

When I write out the actual URI being created there, I get the following:
```
C:\Users\rikerr\UriErrorExample\UriErrorExample\bin\Debug\netcoreapp2.0\UriErrorExample.dll\testing#folder\testingdoc.txt
```

Notice how **UriErrorExample.dll** is included there in the middle? That's what is making the path invalid :)
[As it turns out](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.location?view=netcore-2.0#System_Reflection_Assembly_Location), `Assembly.Location` includes the actual name of the assembly too! When I remove the assembly name from the path I am able to load the file, with or without the '#'.

@JCBurnside does that work for you?

**Comment by rmkerr** [comment]
Okay -- I'm going to close this issue for now. If you're able to repro the other issue don't hesitate to reopen this.
