### ISSUE TITLE
Consider pinning the C# language version to 7.2 instead of latest

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#29035]
We are currently using latest (in our release/2.1 branch). Should it be pinned to C# 7.2 instead?

https://github.com/dotnet/corefx/blob/cb372752e0cc03123459f57484ec2ea2c40cc85b/dir.props#L231

cc @joperezr, @weshaggard, @GrabYourPitchforks, @joshfree, @danmosemsft, @leecow

**Comment by joshfree** [comment]
Please update this in master before Friday.  It'll flow into release/2.1 normally from there.

**Comment by stephentoub** [comment]
We're going in the opposite direction in coreclr:
https://github.com/dotnet/coreclr/pull/17483#discussion_r180262758
cc: @jkotas

**Comment by weshaggard** [comment]
Thanks for the pointer @stephentoub I just added a note to that PR .

**Comment by stephentoub** [comment]
Thanks.  My point, though, regardless of milestone, is that we should be consistent: we should either use "Latest" everywhere, or we should use a specific version number that's the same everywhere and manually bump it when we want to move to the newer language.

**Comment by jkotas** [comment]
I think we should be using `latest`. We are referencing a fixed version of the compiler, so it is not like things can change under neath us without warning. It is just a busy work to keep bumping it manually.

**Comment by jkotas** [comment]
IMHO, this is nice to have cleanup. It should not be 2.1 blocking-release.

**Comment by weshaggard** [comment]
>We are referencing a fixed version of the compiler, so it is not like things can change under neath us without warning. It is just a busy work to keep bumping it manually.

While the compiler doesn't change often it does change and there is a goal to automate updating of this compiler so using the "latest" seems like it could set us up for trouble.

@jaredpar what is your opinion? Should we keep pinned to a language version or let it float in a world where we start updating to pre-release versions of the compiler often?

**Comment by weshaggard** [comment]
We don't have any clear consensus yet so I think we can stay with "latest" until we have a clear reason we cannot do that. I'm still curious on what @jaredpar or other compiler folks think about this though so keeping the issue open to continue the discussion, but removing blocking-release and moving to future.

**Comment by GrabYourPitchforks** [comment]
(not on the language team and not speaking for them)

The compiler has on rare occasion made breaking changes between language versions; e.g., changing how locals are hoisted into closures within a `foreach` statement. I wouldn't want to end up in a world where developers such as we get in the habit of saying "pull the latest compiler and use the latest language features," which would bind the language team's hands as to what they'd be able to introduce without subtly breaking people's automated build environments. Using the `foreach` example from earlier, it means that the exact same .csproj with the exact same compiler switches results in different runtime behavior based on which compiler version the build environment happens to be using.

So my vote would be to use nightly compilers (for dogfooding purposes) but pin on a particular language version for behavioral stability.

**Comment by jkotas** [comment]
> changing how locals are hoisted into closures within a foreach statement

Was this change between compiler versions or between language versions?

I believe most of the behaviors like these are considered internal implementation details and not based on the language version. You always get the latest behavior with latest compiler, regardless of the language version switch.

**Comment by jkotas** [comment]
I think the tradeoff is: 

- Use latest: We pay the price for the occasional breaks in small chunks over time. Roslyn team gets more immediate feedback about bad breaks if there are any.
- Pinned to fixed version. Once in a while, somebody will need to update the language version because of new language features are required to make progress. We pay the price in one large chunk.

**Comment by GrabYourPitchforks** [comment]
> Was this change between compiler versions or between language versions?

Ah, you're right. It was between compiler versions, not language versions.

**Comment by weshaggard** [comment]
Pasting @jaredpar response from email:

IMHO: I think most Microsoft teams should prefer latest vs. pinning a version. 
 
The latest vs. default vs pinning is really a feature we added for enterprise customers. Keeping our commitment that different parts of a team can use different updates of VS and not break each other. That is Employee1 can use VS 15.3 and Employee2 can use VS 15.5 and the code will either compile or not compiler on both of the machines. Language point releases make it easy to break that promise. Hence we introduced default (last major) and latest (bleeding edge) and had MSBuild default to passing default. 
 
I’m still a bit unclear why pinning specific versions rose to any prominence. Either you care about new stuff and should use “latest” or you don’t and you should use “default”. Pinning a specific version is an odd middle ground that just causes you work every release. 
 
Roslyn does pin a specific version but that is due to the realities of being the compiler team. 

-----
 
 >	In a world where we continuously update the compilers (not yet but that is our hope) would you still suggest we stick to “latest” over “default”? I’m unsure if taking a nightly build 

Yes I would still recommend this design. In part because we are not taking nightly builds anymore. Due to our product construction and source build efforts the teams should be stabilizing on our LKG builds of SDK which in turn moderates the pace at which C# compilers are adopted. The pace should be closer to sprintly vs. nightly. 

>	I’m unsure if taking a nightly build would ever put us in a state of where some new language feature is only half done and the design is still iterating where we might break on the next update.

Our current design process should avoid that problem. We don’t merge our language features back into our main tree until we are very far along in the design, have the VS support added, etc … Essentially we’re much closer to done than not by the time we merge features into shipping branches. Precisely because changes once we ship are expensive for us and customers.

There does tend to be a bit of churn in the week or two after we introduce a new large language feature. But that typically gets handled in our repository before it ever ships out to customers. 

>	I’m also curious about release/servicing branches where we might take a toolset update but are more adverse to risk, does floating the language version add more risk than just the compiler update itself? 

Taking a new compiler is comparatively a greater risk than using a floating language version. Both still pretty small

**Comment by weshaggard** [comment]
Based on that I'm going to suggest we continue to use "latest" until if there comes a time where it is problematic and then we can revisit.
