### ISSUE TITLE
Add support for secp256k1

### ISSUE THREAD

**Issue by dennisfurrer** [dotnet/corefx#29057]
corefx/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/ECCurve.NamedCurves.cs

**Comment by bartonjs** [comment]
@steveharter Do you know/remember why `secp256k1` was left out?  It has an OID (so it'll work with Linux/OpenSSL) and it looks like it was there in the initial expanded curve set for Win10.

Maybe it just got missed for having too similar a name to `secp256r1` aka `nistP256`?

**Comment by steveharter** [comment]
At one point we had all common curves there (not checked in, but I have the old code) but reduced the set to the "common" curves including 3 NIST curves + brainpool.

You can still create the named curve manually...

**Comment by steveharter** [comment]
From the API review: "Keep the factory methods for common compliance scenarios. Includes nist, brainpool and curve25519. Exact list TBD."

From https://github.com/dotnet/corefx/issues/7688: "Discussion topic: the set of static factory methods on NamedCurves are a subset of those from Windows 10. OpenSsl supports the nist curves, but not the brainpool, plus supports several additional (varies depending on OpenSsl version). RESOLUTION: this list was chosen because the nist and brainpool curves are likely to be the normally recommended curves."

**Comment by bartonjs** [comment]
While I agree that secp256k1 is a "standard" curve I also agree that it isn't very common.  Since there was an API review request to keep the list trimmed down to common things, it's not something we would add right now.

ECCurve.CreateFromValue("1.3.132.0.10") works in the meantime, on platforms which support that curve.

**Comment by wjmelements** [comment]
Because secp256k1 is used by the top two blockchains, Bitcoin and Ethereum, it probably deserves a spot on a trim list.

**Comment by MithrilMan** [comment]
@karelz  @bartonjs  can we re-open the issue? Last comment makes sense because nowaday blockchain is on fire

**Comment by karelz** [comment]
So how many applications / libraries will use it directly?
Is the blockchain usage only through Bitcoin and Etherum, or do people write their own decryptions?

**Comment by wizicer** [comment]
@karelz 
Just here to add some clues:
My blockchain project which is not a fork of any other blockchain, still utilizing secp256k1 which is de facto standard for blockchain, (IMHO). Currently, I'm maintaining a nuget library for this purpose: https://github.com/uchaindb/Cryptography.EcDsa.Secp256k1

**Comment by bartonjs** [comment]
The functionality is there, it's just the accelerator isn't.  The question, really, is "how many people will really want or need to type `ECCurve.NamedCurves.secp256k1`?"  If it's on the order of dozens or less, it's not much different than `ECCurve.CreateFromValue("1.3.132.0.10")`.  If it's hundreds to thousands, then the discoverability is probably worthwhile.

OpenSSL 1.0.2 had/has 81 different named curves... most aren't commonly used, and at some point things are so rare they're clutter.  We're just trying to find a balance.
