### ISSUE TITLE
Optional capacity parameter for ToArray extension method.

### ISSUE THREAD

**Issue by DixonD-git** [dotnet/corefx#2926]
ToArray can create a number of arrays internally and copy the content many times. Sometimes, we may know an estimated number of elements we may have in IEnumerable. Thus we can add optional parameter to specify the initial size of the internal array, and so improve performance by avoiding excessive memory allocations and copying operations.

Basically, you can see the changes to be done in this PR: https://github.com/dotnet/corefx/pull/2925/files

**Comment by stephentoub** [comment]
cc: @terrajobst, @VSadov

**Comment by hackcraft** [comment]
Well, it certainly couldn't be done like that; you've deleted the `ToArray()` method so this breaks all uses of it in current use, and that's a lot. (Optional parameters are syntactic sugar, so the CIL for calling `ToArray()` today and calling it on your version are completely different, and existing code would report that `Enumerable.ToArray()` didn't exist).

If I ask for too many elements, should I get that many, with the excess set to `default(T)` or should it be trimmed? I can see either as being confusing.

If we get excess, should this happen even with the types that set the size for `ToArray()` themselves E.g. `new []{1, 2, 3, 4, 5}.Select(i => i.ToString()).ToArray()` currently creates a 5-element array directly without starting from 4 and growing. Should `new []{1, 2, 3, 4, 5}.Select(i => i.ToString()).ToArray(6)` give us 6 elements? Should `new []{1, 2, 3, 4, 5}.Select(i => i.ToString()).ToArray(4)` behave any differently than it does?

If this is meant to be a hint, rather than an instruction (so `Enumerable.Range(1, 3).ToArray(40)` returns a 3-element array) then at the very least I'd say this should be indicated in the parameter name; e.g. `sizeHint` rather than `capacity`.

If it is a hint, I think though it might be better to increase the number of times `ToArray()` does what it's currently specified as doing with a single allocation (there's definitely scope for that, though the trade-offs are sometimes tricky to judge).

If on the other hand we are meant to have the excess left in such a call, then perhaps a `CopyTo<TSource>(this IEnumerable<TSource> source, TSource[] array, int arrayIndex)` would be better in providing for that case, being flexible beyond that, and in having straightforward fast-pathing for the cases where `source` implements `ICollection<TSource>` and perhaps beyond.

**Comment by DixonD-git** [comment]
Yes, it was meant to be a hint, so `capacity` might be indeed not the best name. On other hand, there is `List<T>` constructor which allows to specify the initial size of the internal structure and it is called `capacity` there: https://msdn.microsoft.com/en-us/library/dw8e0z9z%28v=vs.110%29.aspx

> If it is a hint, I think though it might be better to increase the number of times ToArray() does what it's currently specified as doing with a single allocation (there's definitely scope for that, though the trade-offs are sometimes tricky to judge).

Could you please elaborate? I'm not sure I understand.

**Comment by hackcraft** [comment]
I mean it might be better to have more cases like you get when you call `.Select()` on a `List<T>` and then call `ToArray()` on that. That case does a single allocation of the correct-sized array, without the caller having to do anything (or even have the ability to make a guess from the information directly available to the calling method). If we're concerned about the cost of allocations in `ToArray()` that seems to me to be a more promising place to look.

**Comment by hackcraft** [comment]
> there is `List<T>` constructor which allows to specify the initial size of the internal structure and it is called `capacity`

And when you call `new List<string>(42)` you get a `List<string>` with a capacity of 42, which has an effect on the performance of subsequent operations on that list. This does not compare with `ToArray()`.

**Comment by VSadov** [comment]
The generalized ToArray(int) will need to deal with cases where the hint does not match the actual count of elements one way or another - expand, trim, throw...

In actual situations the API would only be helpful if the size is known exactly and in those cases one can  simply introduce an extension that looks something like:

```C#
        public static void ToArray(this IEnumerable<int> e, int capacity)
        {
            var arr = new int[capacity];
            int i = 0;
            foreach (var element in e)
            {
                arr[i++] = element;
            }
        }
```

The generalized version will hardly add any value compared to an extension like this, but will need to be more complex just because it will be forced to handle "impossible" cases.

I am not convinced that there is enough value in introducing such an API in the core library.

List constructor does not seem a good example here because List has well established concepts of Capacity and Count.

**Comment by weshaggard** [comment]
I agree with @VSadov I don't think there is enough value to warrant the complexity of adding this new overload.  However perhaps there is some room to improve our internal Buffer class to try and be smarter and get the count/length of some well known implementations of IEnumerable when they implement ICollection/IList for example.

**Comment by DixonD-git** [comment]
>The generalized ToArray(int) will need to deal with cases where the hint does not match the actual count of elements one way or another - expand, trim, throw...

@VSadov If you check the PR referenced in the first comment and/or the actual code, you'll see that those cases are already handled.

**Comment by stephentoub** [comment]
I agree with @weshaggard and @VSadov: good suggestion, but not enough value here to warrant a new built-in overload.  As @VSadov demonstrated, in the cases where you know the length and so could supply it but the concrete implementation doesn't know its own length, it's possible to implement this with a few lines of code, and is no worse than what could be done internally.

**Comment by terrajobst** [comment]
@VSadov, since you own Linq you're the one that has to make a decision whether we believe it has enough value. If you think it doesn't, close the issue. Otherwise, add back the `ready for api review` label.

**Comment by VSadov** [comment]
It does not look like there would be enough additional value to justify expanding of the public surface. The functionality can be done externally and possibly in a way that is more efficient for the targeted scenario than a generalized implementation that Linq would have to provide.
