### ISSUE TITLE
The type initializer for 'TimeZoneConverter.TZConvert' threw an exception.

### ISSUE THREAD

**Issue by liguangkk** [dotnet/corefx#29325]
I got this error on aws lambda.
The type initializer for 'TimeZoneConverter.TZConvert' threw an exception.
"errorMessage": "An item with the same key has already been added. Key: Canada/East-Saskatchewan",

**Comment by tarekgh** [comment]
@mj1856  could you please look to know if this issue is because of TimeZoneInfo enumeration or it is TimeZoneConverter issue? Thanks.

**Comment by tarekgh** [comment]
https://github.com/mj1856/TimeZoneConverter

**Comment by mj1856** [comment]
Yeah, should be logged on my repo, not here.  

@liguangkk, please log over there.  When you do, please give version and code to reproduce.  I thought I had addressed this one already.  Thanks.

**Comment by tarekgh** [comment]
@liguangkk could you please add the full stack? 

@mj1856 I looked briefly at your code, although I am not sure exactly what the problem is, could it be because of the line  

https://github.com/mj1856/TimeZoneConverter/blob/master/src/TimeZoneConverter/TZConvert.cs#L327

which looks we didn't encounter Canada/East-Saskatchewan before but now we do.

I'll move this issue to your repo. Thanks.

**Comment by tarekgh** [comment]
This issue was moved to mj1856/TimeZoneConverter#28
