### ISSUE TITLE
Bad HResult error codes with IOException on Linux

### ISSUE THREAD

**Issue by Odirb** [dotnet/corefx#29342]
Hi,

When a file cannot be access because it's used by another process, or when a file cannot be created because it already exists, the System.IO.File Open function throws an IOException with an invalid HResult value.

Sample code below returns 11 (EAGAIN?) instead of -2147024864 (ERROR_SHARING_VIOLATION). For a file in use it returns 17 (EEXIST?) instead of -2147024816 (ERROR_FILE_EXISTS). 

Since HResult is ok for a file not found (-2147024894 correspond to ERROR_FILE_NOT_FOUND) , it seems there is some missing mapping for conversion between Linux error code and Windows error code.

| Test | HResult on Windows | HResult on Linux | Result  |
| --- | --- | --- | --- |
| File in use | -2147024864 | 11 | Invalid |
| File already exists | -2147024816 | 17 | Invalid |
| File not found | -2147024894 | -2147024894 | Correct |

This problem is reproductible with dotnet core 2.0 running on an Ubuntu 16.04

# Code sample

```c#
using System;
using System.IO;

namespace FileInUseException
{
    class Program
    {
        static void Main(string[] args)
        {
            var file = @"locked.bin";
            using (File.Create(file))
            {
                Console.WriteLine("=== File in use");
                try
                {
                    File.OpenRead(file);
                    Console.WriteLine("No exception! Weird...");
                }
                catch (IOException ex)
                {
                    Console.WriteLine($"Get an IOException with code {ex.HResult}, message {ex.Message}");
                }
            }

            Console.WriteLine("\n=== File already exists");
            try
            {
                File.Open(file, FileMode.CreateNew, FileAccess.ReadWrite);
                Console.WriteLine("No exception! Weird...");
            }
            catch (IOException ex)
            {
                Console.WriteLine($"Get an IOException with code {ex.HResult}, message {ex.Message}");
            }


            Console.WriteLine("\n=== File not found");
            try
            {
                File.OpenRead("Not Here.bin");
            }
            catch (IOException ex)
            {
                Console.WriteLine($"Get an IOException with code {ex.HResult}, message {ex.Message}");
            }
        }
    }
}
```

**Comment by JeremyKuhne** [comment]
@pjanotti, @stephentoub 

The problem here is that we have the HResults hardcoded for FileNotFoundException and a few other places without flipping on platform. Presuming we should be consistent and return the platform specific error code as we do for general IO exceptions. We wouldn't be able to map all Unix error codes to Windows codes reliably so I don't think trying to do so would be wise.

We should also:

1. Fix the docs
2. Consider providing docs / api to map ones we can?

**Comment by pjanotti** [comment]
I am not so sure: HResult was a bad name choice, perhaps it should have been just Error (or something similar) but I think there is code around relying on its value to do the correct thing. While there is no way to reliably map all codes, we should consider mapping at least the typical exceptions (starting w/ the 3 listed above), otherwise becomes very hard to abstract the OS away (this is already hard to do in practice, but we should minimize that). The alternative that I see will be to have derived types of IOException for the common ones but that is a new API and doesn't work for legacy. Are we using some consistent approach around HResult in Core?

.

**Comment by jkotas** [comment]
FWIW, fairly well debugged mapping between Unix error codes and Windows error codes (that are 1:1 with HResults) is in https://github.com/dotnet/coreclr/blob/6954cb2f716c4d46b8bcc2bb0501bede7cad2bc0/src/pal/src/file/file.cpp#L3330

**Comment by jkotas** [comment]
@marek-safar How does Mono implement `Exception.HResult` for I/O related exceptions?

**Comment by marek-safar** [comment]
@jkotas we try to map them where we found a reasonable match. See https://github.com/mono/mono/blob/85181dc80842e18c787795ba583aaa9cdd208d62/mono/metadata/w32error-unix.c#L38

**Comment by jkotas** [comment]
If we can still change at this point, I think we should try to map the platform specific error code to HResult as well. To be more compatible with Mono and to be more compatible across platforms. The current state where HResult is sometimes HResult and sometimes platform specific error code is confusing.

**Comment by danmosemsft** [comment]
I think this is covered by https://github.com/dotnet/corefx/issues/34221. Please reactivate if I'm mistaken.

**Comment by danmosemsft** [comment]
(Basically the idea is -- the error code is never going to be necessarily consistent across platforms. Invent an enumeration)
