### ISSUE TITLE
IsolatedStorage fails on Mac if ~/.local/share directory does not exist

### ISSUE THREAD

**Issue by jasongin** [dotnet/corefx#29354]
**Repro steps:**

1. Start with a clean Mac OS machine, or at least a clean user account on Mac that does not have any `~/.local/share` directory created yet.
2. From a .NET Core app, call `IsolatedStorageFile.GetUserStoreForAssembly()`

**Result**
```
System.UnauthorizedAccessException: Access to the path '/IsolatedStorage/0czktn4d.axp/p4g300la.ihj' is denied. ---> System.IO.IOException: Permission denied
--- End of inner exception stack trace ---
at System.IO.UnixFileSystem.CreateDirectory(String fullPath)
at System.IO.Directory.CreateDirectory(String path)
at System.IO.IsolatedStorage.Helper.GetRandomDirectory(String rootDirectory, IsolatedStorageScope scope)
at System.IO.IsolatedStorage.Helper.GetRootDirectory(IsolatedStorageScope scope
)
at System.IO.IsolatedStorage.IsolatedStorageFile.Initialize(IsolatedStorageScope scope)
```

**Explanation**
Apparently the [IsolatedStorage call to `Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)`](https://github.com/dotnet/corefx/blob/master/src/System.IO.IsolatedStorage/src/System/IO/IsolatedStorage/Helper.Win32Unix.cs#L35) returns an empty string if the `~/.local/share` directory does not exist. Then the `IsolatedStorage` directory name is combined with that empty string, and the resulting path (seen in the exception message above) cannot be accessed because it does not exist.

**Comment by danmosemsft** [comment]
Environment.GetFolderPath behavior
https://github.com/dotnet/corefx/blob/5cbac95f5530695a31a43e7748a4561e3a2dd32d/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L72
matches docs `The path to the specified system special folder, if that folder physically exists on your computer; otherwise, an empty string ("").`

Fix is probably for GetDataDirectory() 
https://github.com/dotnet/corefx/blob/6c7f3ac27caad2b7c510199767c9f6a9099f550e/src/System.IO.IsolatedStorage/src/System/IO/IsolatedStorage/Helper.Win32Unix.cs#L13
to ensure the folder it provides does exist. Either by passing SpecialFolderOption.Create, by passing SpecialFolderOption.DoNotVerify and then creating, or by falling back to some other location like GetTempPath().

@MarcoRossignoli do you have a Mac ? 😄

**Comment by MarcoRossignoli** [comment]
@danmosemsft unfortunately not accessible right now :disappointed: .
In past i did some tests on remote mac borrowed in office...but i can't reach at the moment(unexpected).
If nobody grab this next days i can try install vs code and fix it(i got a repo copy on that mac to run cross tests), i work on win, linux thanks to corefx contrib experience...i'd like help also on mac(if i could use VM...aahhh...:rage:)

**Comment by danmosemsft** [comment]
@MarcoRossignoli no problem. What sort of issues would you like me to look out for for you?

@maryamariyan I believe you have Mac access. Not urgent.

**Comment by MarcoRossignoli** [comment]
@danmosemsft i don't have specific taste at the moment. For now i enjoied more with bug(like this) and new api(i've got a pair of PR waiting on new Span path api). But also working out of my confort zone(es. Linux/Mac, i work on win) stimulates me...i work with .net since 1.0 and now work on this codebase is amazing...i'm learning and growing a lot as dev. Thank's to all of you for this chance.

**Comment by danmosemsft** [comment]
@MarcoRossignoli OK sounds good we'll ping you on issues you might want.
cc @karelz fyi.

**Comment by danmosemsft** [comment]
@jasongin do you know how a Mac machine gets into a state where there is no `~/.local/share`?

**Comment by jasongin** [comment]
We encountered this on some test machines that had the OS & user account freshly set up.

**Comment by danmosemsft** [comment]
OK it seems fine it's not in 2.1 then given isolated storage isn't super commonly used .

**Comment by jasongin** [comment]
As a data point, Live Share private preview telemetry showed about 18% of our Mac users were hitting this. (We initially didn’t catch it in internal testing.) Many of them were probably not .NET developers.

Anyway we’ve added a workaround so it’s not blocking us.

**Comment by karelz** [comment]
@jasongin what is the workaround? Is it reasonable for others to use?
Impact on 18% Mac users is pretty large. Although we treated Mac as dev-only scenario so far.

**Comment by danmosemsft** [comment]
Presumably to create the folder

**Comment by jasongin** [comment]
Yes.
