### ISSUE TITLE
Brotli_External_DecompressesResponse_Success is consistently failing because httpbin.org is down

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#29400]
This test has been failing in local runs for me all day.  Apparently httpbin.org has been down all day (or at least every time I run tests).

If httpbin.org is this unreliable, then I don't think we should be depending on it in functional tests.

**Comment by davidsh** [comment]
>If httpbin.org is this unreliable, then I don't think we should be depending on it in functional tests.

Can we enhance the test loopback server code and use that instead of this external 3rd party server?

**Comment by stephentoub** [comment]
> Can we enhance the test loopback server code and use that instead of this external 3rd party server?

We already have a separate test that does that:
https://github.com/dotnet/corefx/blob/175984f5c05de918effd97bf322fb002e0da925b/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Decompression.cs#L16

I added both because I wanted to be able to also test against a different implementation of Brotli.  But if it's problematic we can just delete the external one.

**Comment by stephentoub** [comment]
I have no idea what implementation is being used by httpbin.org, but I assume it's not the .NET implementation.  If we were to update our endpoint to use the same .NET implementation, that would kind of defeat the purpose.  At which point, we may as well just get rid of this test.

**Comment by davidsh** [comment]
>I have no idea what implementation is being used by httpbin.org

Most of the source for httpbin.org is open source here: https://github.com/requests/httpbin

I haven't looked at it to see whether the Brotli is there.

**Comment by geoffkizer** [comment]
There's also this: https://www.iis.net/downloads/community/2016/03/iis-brotli
