### ISSUE TITLE
Request to Add Timer.Dispose(WaitHandle) API in CoreCLR.

### ISSUE THREAD

**Issue by mehuljvora** [dotnet/corefx#2942]
We are working on porting our .Net 4.5 application to the .Net Core CLR platform. 
                                                                                      
We have multiple services implemented in our application which need to do some work every so often. Currently this is implemented using System.Threading.Timer with a callback method that is responsible for scheduling the next callback. 

During cleanup, we want to wait until we are sure that the callback is no longer running and will not run in future. Currently we do this using Threading.Timer.Dispose(WaitHandle) with additional synchronization mechanism to avoid the ObjectDisposedException.

Since CoreCLR doesn't have Timer.Dispose(WaitHandle) implemented, every application/service now has to implement Timer.Dispose(WaitHandle) logic using some synchronization mechanism in their code. This adds complexity at each place where this API is used currently.

We would like to carry forward the same behavior and so would request to add this API [Timer.Dispose(WaitHandle)] back in CoreCLR.

Thanks,
Mehul.

**Comment by ericeil** [comment]
We omitted `Dispose(WaitHandle)` because it's awkward to use, and very error-prone.  Correct usage is not at all obvious from the signature (what kind of WaitHandle should be passed in?  Do I need to do anything after calling Dispose?), and most uses I've seen are not correct.  

That said, this is useful functionality, I just think it should be exposed differently.  Perhaps something like this:

```C#
public Task DisposeAsync()
```

The returned Task would be completed after the Timer is fully disposed *and* all callbacks have finished execution.  This way the caller could synchronize with the pending callbacks in all the usual ways, instead of the odd custom mechanism implemented by the current `Dispose(WaitHandle)` method.

**Comment by ericeil** [comment]
I should mention also that I'm a little unhappy with the name "DisposeAsync," as it implies that it does what `Dispose` does, but asynchronously.  In fact this new API would do *more* than the existing `Dispose()`.  Perhaps it should be:

```c#
public Task DisposeAndWaitAsync();
```
Any alternate suggestions would be appreciated.

**Comment by mehuljvora** [comment]
DisposeAndWaitAsync() -- Sounds Great! 

When will this API be available in CoreCLR?

**Comment by ericeil** [comment]
@sergiy-k another ThreadPool feature request.

**Comment by dsplaisted** [comment]
Thanks to @ericeil, I've added sample code for how you can wait for Timer callbacks to finish running in .NET Core here: Microsoft/dotnet-apiport#283

**Comment by weshaggard** [comment]
@kouvel as part of our API work can you please be sure we get this API added back to Timer?

**Comment by kouvel** [comment]
This will be done as part of #11631
