### ISSUE TITLE
Make System.Net.Http.WebRequestHandler more extensible

### ISSUE THREAD

**Issue by atykhyy** [dotnet/corefx#29450]
Specifically, add an overridable virtual method equivalent to `InitializeWebRequest` to allow classes extending `WebRequestHandler` to control the properties of the `HttpWebRequest` and related objects that cannot be specified in `HttpClientHandler`/`WebRequestHandler` (example: `ServicePoint.ConnectionLeaseTimeout`). `InitializeWebRequest` is declared internal in the .NET Framework implementation of `HttpClientHandler`, which is as it should be since `HttpClientHandler` is not specific to .NET Framework. However, `WebRequestHandler` *is* specific to .NET Framework, so there is no reason for it not to provide an extensibility point. In the absence of such an extensibility point, users may end up reimplementing the whole of `HttpClientHandler` just to set a couple of request properties, or having to avoid `HttpClient` altogether.

**Comment by davidsh** [comment]
`InitializeWebRequest` is an internal method in the .NET Framework.  When HttpClient was first introduced in .NET 4.5, it had to wrap around the legacy HttpWebRequest stack.  HttpClient and related classes were placed into a separate System.Net.Http.dll binary while the rest of the networking stack is in System.dll.  HttpClient needed to call internal methods of HttpWebRequest and so various mitigations were done in .NET Framework to complete the implementation.  `InitializeWebRequest` is an implementation detail of this and is not intended to be exposed as a public API.

The `WebRequestHandler` class is specific to .NET Framework.  It has a few extra properties compared with `HttpClientHandler` class. However, `HttpClientHandler` has been updated now and has additional properties which makes `WebRequestHandler` duplicative now.  It not available in .NET Core since it is considered a legacy class.

We recommend developer use System.Net.Http classes including HttpClientHandler.

**Comment by davidsh** [comment]
>example: ServicePoint.ConnectionLeaseTimeout

In terms of being able to manipulate ServicePointManager/ServicePoint classes, those classes are not functional in .NET Core.  New mechanisms for controlling connection related properties are now available directly in the HttpClientHandler class.  And, as always, we welcome feedback, API proposals, and PR's to make enhancements to these modern HTTP types.

**Comment by davidsh** [comment]
cc: @karelz

**Comment by karelz** [comment]
Technically, we do not track .NET Framework bugs/feature asks on GitHub (see our [main page](https://github.com/dotnet/corefx#how-to-engage-contribute-and-provide-feedback) for recommended way to report problems.
That said, our team owns also .NET Framework networking stack, so you got to the right people.
BTW: Referencesource is read-only view of some .NET Framework sources, it was never meant to take PRs.

The truth is that the bar for bug fixes and new APIs in .NET Framework is currently fairly high. The key reason is to mitigate compatibility-risk (nobody likes their app to be broken with an update).
From that perspective, I would recommend to either look into the suggested workarounds above, or file a new issue on [VS Developer Community Portal](https://developercommunity.visualstudio.com/) and gather more upvotes & provide justification why the workarounds are not acceptable.

Closing the issue here as it does not apply to .NET Core (CoreFX repo).
We can keep discussing feasibility of the above workarounds or other suggestions.
