### ISSUE TITLE
Enumerable.Cast() throws wrong exception in casting null to non-nullable value-type.

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#2947]
Enumerable.Cast() is documented as throwing:

`ArgumentNullException`: source enumerable is null.
`InvalidCastException`: (upon enumerating) an element in the sequence cannot be cast to the requested type.

If however a null element is in a sequence being cast to a non-nullable value-type, the exception thrown is `NullReferenceException`, which is both not documented, and an inappropriate exception in any case as the calling code has not directly used a null reference.

Example:

    new int?[]{1, null}.Cast<int>().ToList()

**Comment by VSadov** [comment]
I actually think that the current behavior is preferable since it makes sequence operator to match the behavior of a single element cast repeated:

```C#
            object o = (int?)null;
            int i = (int)o;
```

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.

It looks like the documentation is just missing the case of null elements.

CC @billchi-ms @MadsTorgersen   -  any comments on this?

**Comment by JonHanna** [comment]
A `NullReferenceException` from within a method is somewhat strange, but maybe it's the docs that should be changed rather than the code.

**Comment by stephentoub** [comment]
I agree with @VSadov we should leave the behavior as is.  And I also agree @JonHanna that we should get the docs updated to reflect this.

**Comment by stephentoub** [comment]
Spoke with @billchi-ms and @MadsTorgersen as well.  They'd like to leave the behavior as-is, too.  And the docs folks are following up on getting the docs fixed up. Given that, I'm going to close this and the associated PR out.  Thanks.
