### ISSUE TITLE
ArraySegment<T> as readonly struct

### ISSUE THREAD

**Issue by sdrapkin** [dotnet/corefx#29582]
Are there plans to convert `ArraySegment<T>` into `readonly` struct?
If not, why not?

Motivation: many scenarios use `ArraySegment<T>` extension methods, and they would benefit from not copying (ie. passing by ref without a backing variable).

**Comment by jkotas** [comment]
It is readonly struct in .NET Core 2.1

https://github.com/dotnet/corefx/blob/master/src/System.Runtime/ref/System.Runtime.cs#L269

**Comment by jkotas** [comment]
It was fixed by https://github.com/dotnet/corefx/pull/24997 and related PRs.

**Comment by sdrapkin** [comment]
@jkotas Thanks for pointing that out. It would be nice to document that change somewhere visible (ex. NetCore2.1 "what's new" MSDN blogs.

However, my question was about .NET Framework. When will `readonly struct ArraySegment<T>` be coming to .NET framework? Is it on the roadmap? Is it in .NET 4.8 that's 12 months out?

**Comment by jkotas** [comment]
This change is just one of the hundreds of performance improvements in .NET Core 2.1. The "what's new" blogs mention the most signficant improvements only. It is not practical for them to mention every single performance improvement. This change is certainly nice, but pales in comparison with many other more significant ones.

.NET Framework updates receive high-compatible targeted improvements only. Marking types readonly can introduce unexpected behavior changes as we have learned hard way when we marked `Nullable<T>` as readonly and then undone it. I do not expect that this change will be ever coming to .NET Framework 4.x because of the compat risk.
