### ISSUE TITLE
Regex $+ replacement pattern is inconsistent when both named and numbered groups are present

### ISSUE THREAD

**Issue by kendfrey** [dotnet/corefx#29590]
**Example code:**

```cs
Console.Write(Regex.Replace("ab", @"(?<A>a)(?<1>b)", "$+"));
Console.Write(Regex.Replace("ab", @"(?<A>a)(?<2>b)", "$+"));
```

**Result:** `ab`

**Expected result:** Either `aa` or `bb`

**Notes:**

The `$+` regex replacement syntax should:

- [x] If only numbered groups (including e.g. `(?<1>...)`) are present, select the group with the highest number.
- [x] If only named groups (excluding e.g. `(?<1>...)`) are present, select the group whose first appearance comes last in the regex. For example, `(?<A>)(?<B>)(?<A>)` would select `B`, because its first appearance comes after `A`'s.
- [ ] If both numbered and named groups are present, select one of the first two behaviours in all cases.

Currently if both numbered and named groups are present, it appears to select from one of the first two behaviours depending on whether all group numbers are consecutive from 1, or have gaps.

**Comment by ViktorHofer** [comment]
Thanks for reporting. I'm currently on holiday and will look into it when I'm back 😊

**Comment by danmosemsft** [comment]
Same in .NET Framework.

**Comment by kendfrey** [comment]
I've implemented this assuming that numbered groups should take precedence over named groups (the example would output `bb`). If this is wrong, I'd love to be corrected.

**Comment by ViktorHofer** [comment]
Quick question, where did you find the rules that you put into the notes section? Is that documented somewhere or is that the behavior that you observed? It's hard to tell here what the exact behavior should be as I can't find any documentation about it and .NET is one of the only languages that Support $+ and explicit numbered groups.

**Comment by kendfrey** [comment]
I don't think much if any of this is documented. It's all from testing various regexes. That's part of the problem, as there's no spec/standard, so I'm having to go by "sensibility".

**Comment by ViktorHofer** [comment]
Ok understood, then I will look into the parser and check myself what makes sense here and why it's currently doing what it is doing. We probably want to add the desired behavior to the docs.

**Comment by ViktorHofer** [comment]
Hi @kendfrey, I browsed through the code and the behavior seems fine because we treat named capture groups also as numbered capture groups. We first scan for unnamed capture groups as described here: 

> In .NET, however, unnamed capturing groups are assigned numbers first, counting their opening parentheses from left to right, skipping all named groups. After that, named groups are assigned the numbers that follow by counting the opening parentheses of the named groups from left to right.

```
Console.WriteLine(Regex.Replace("ab", @"(?<A>a)(?<1>b)", "$+"));
```
Result: `GroupCollection(3) { [ab], [b], [a] }`.
The first (zero index) capture group is always the entire match; if there is one. The second capture group here is the unnamed group, it doesn't really matter that the number is explicitly set.
The second capture group is the named group `A`.

```
Console.WriteLine(Regex.Replace("ab", @"(?<A>a)(?<2>b)", "$+"));
```
Result: `GroupCollection(3) { [ab], [a], [b] }`.
The first (zero index) capture group again is the entire match.
The second capture group would be the unnamed group `<2>` but as its index is explicitly set it won't be at index 1 but 2. That means there is now a hole after the first capture group which is filled by the named capture group.
The third capture group now is the numbered one.

`$+` will always return the last capture group. Therefore I believe the current behavior is correct.

**Comment by kendfrey** [comment]
Ah, I understand the behaviour better now. It's very confusing because it doesn't go by the order of groups in the regex, and it doesn't treat numbered groups consistently. (It seems like it's leaking an implementation detail that should not apply to `$+`.) Is this intended behaviour, unintended-but-by-design behaviour, or erroneous behaviour?

**Comment by ViktorHofer** [comment]
That's intentional as far as I can read out of it from the sources. We couldn't change it as it would break customers. I'm closing this now. If you think there is more to be done here, feel free to reopen :)
