### ISSUE TITLE
GenericHeaderParser.ParseSingleEntityTag() does not allow an etag value of *

### ISSUE THREAD

**Issue by troyhughes** [dotnet/corefx#29613]
This is the first issue I've brought up on here or GitHub in general. Please forgive (and correct) me if there are any conventions I have not followed.  

I was attempting to use the Azure Storage blob client to get a blob reference along with an IfExists AccessCondition which sets my etag header to '\*'.  From what I can tell this is a supported action and would avoid an exception when calling the API when the blob does not exist.  However when I use the API I get the error that "The format of value '*' is invalid.".  This error is from HttpHeaderParser.ParseValue() in HttpHeaderParser.cs.  After looking at the code the problem seems to stem from the following code in GenericHeaderParser.cs.

https://github.com/dotnet/corefx/blob/5c521c8dd9e46c2da34ead4046000c3c3c4e998f/src/System.Net.Http/src/System/Net/Http/Headers/GenericHeaderParser.cs#L92-L107

- Is it really the right thing to return zero any time an etag is set to '*' ? This causes BaseHeaderParser.TryParseValue() to return false when the etag is valid which in turn breaks a number of Azure storage APIs.
- This comment seems a bit odd.  _"// If we don't allow '*' ("Any") as valid ETag value, return false (e.g. 'ETag' header)_". In the code nothing is checked to see if '\*' is allowed. It's simply not allowed from how I'm interpreting this code.

[EDIT] Replace code with reference into repo by @karelz

**Comment by davidsh** [comment]
>I was attempting to use the Azure Storage blob client to get a blob reference along with an IfExists AccessCondition which sets my etag header to '*'. From what I can tell this is a supported action and would avoid an exception when calling the API when the blob does not exist. However when I use the API I get the error that "The format of value '*' is invalid.". This error is from HttpHeaderParser.ParseValue() in HttpHeaderParser.cs. After looking at the code the problem seems to stem from the following code in GenericHeaderParser.cs.

I'm not sure if this issue is actually describing a problem with .NET Core or with the Azure Blob Storage SDK. There is no "IfExistsAccessCondition" property or method in HttpClient.

The only reference to the "ETag" header is in the [HttpResponseMessage.ETag](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.httpresponseheaders.etag?view=netcore-2.2#System_Net_Http_Headers_HttpResponseHeaders_ETag) property.

I suspect this issue is really about a problem with how the Azure Storage SDK BlobClient is using .NET underneath.

I recommend if there is still a problem with the Azure Storage SDK, that an issue be created in the Azure Storage SDK [repo](https://github.com/Azure/azure-storage-net/).
