### ISSUE TITLE
Needless calls to comparer in EnumerableSorter

### ISSUE THREAD

**Issue by epsitec** [dotnet/corefx#2962]
I was surprised to see that when sorting items using `System.Linq.Enumerable.OrderBy<TSource, TKey>`, while specifying a comparer:

```c#
var sort = new MySort();
var sorted = items.OrderBy(x => x, sort);
...
class MySort : IComparer<Foo>
{
    public int Compare(Foo x, Foo y) { ... }
}
```

the implementation of `EnumerableSorter<T>.QuickSort` happens to call `MySort.Compare` for comparisons which are bound to result to equality, i.e. where arguments `x` and `y` refer to the same object.

I can't see why this does not get caught earlier, either in the Quick Sort implementation, or in the call to `CompareKeys`, where `0` could be returned immediately if `index1` equals `index2`:

![enumerable](https://cloud.githubusercontent.com/assets/3872435/9463960/8e2d3102-4b20-11e5-9990-df0966cfb9c4.png)

https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Enumerable.cs#L3363

Can this design be altered to avoid useless calls to compare objects to themselves?

**Comment by epsitec** [comment]
Sorting `[ "A", "C", "B" ]` results in a total of six (6) comparisons, three (3) of them being useless:

  * C, A
  * _C, C_
  * C, B
  * _A, A_
  * A, B
  * _A, A_

**Comment by JonHanna** [comment]
It's common enough with quicksort generally, since the number of comparisons tends to be proportional to `n log n` (more precisely, if we consider that as meaning `k * n log n` comparisons, then the average `k` depends on partition strategy; around `1.386` for random and probably less good here were the strategy is just to pick the middle, in any case `k` is always greater than `1`)  while the number of comparisons with self tends to be close to `n`.

And as such if the comparison itself is cheap, the `n log n * k` tests for identity of comparands could outweight the `n` times it allows a short-circuit.

Before: `n log n * k * cost-of-comparison`
After: `(n log n * k * cost-of-comparison) - (n * cost-of-identity-test)`

When we add in the fact that comparers very often have themselves a short-circuit on identity, this means that as a general strategy, just allowing the compare-with-self to happen is generally the best approach. (I note though, that `GenericComparer<T>` does not short-circuit on that directly, though sometimes the implementation it calls into does, perhaps considering that such a check would include the `x == null && y == null` possibility that it has to checked for, that would be a worthwhile change in itself).

Here though, we have the further disadvantage, in that if we have a chain of `ThenBy` then the cost of these compares-with-self could be relatively high. Identifying such cases could bypass the whole chain.

Hence, it might be worth not only catching this case, but doing so in a earlier step:

    private int DoCompareKeys(int index1, int index2) // Actual call is to this
    {
      return index1 == index2 ? 0 : CompareKeys(index1, index2); 
    }

Otherwise even if `CompareKeys` was changed to short-circuit on this case, it would still continue with the recursive comparison, albeit short-circuiting each time.

**Comment by epsitec** [comment]
Thank you for your explanation. My feeling was that comparing two `int` indexes would add almost insignificant execution time -- sure, I'd have to measure it to prove it ;-) -- compared to the cost of dereferencing items in two arrays, calling a function, etc.

Doing the short-circuit is best done in the caller to `CompareKeys`, so your suggestion of adding a `DoCompareKeys` called by the `QuickSort` method would do just fine.

How do we proceed? Do I have to create a PR for this? Do you handle this on your side?

**Comment by JonHanna** [comment]
I'm just a fellow enthusiast, so "my side" is no different to your side.

You could create a PR though perhaps the naming I suggest is the wrong way around (`CompareKeys` should be the new version, and the old renamed to `DoCompareKeys`). I think this change would need measurements to show it actually is a win.

**Comment by JonHanna** [comment]
72d5c9f459e020074c7ccb8f96ce8b56c1034da8 in my own fork is a quick stab at this. It passes all the current tests, but whether it actually improves anything is another matter.

**Comment by JonHanna** [comment]
Experimenting with that, it seems to give a very slight improvement (around 1.5%) in the case of a simple comparison of a simple type (array of `int` compared by itself) that grows as the complication of the comparison grows; add more and more `ThenBy()` operations onto the ordering, and the difference between the two increases, especially since with equivalent item every one of the comparisons possible will be made.

I think it's worth while on that basis.

@epsitec do you want to submit a PR to see if the project owners agree?

**Comment by epsitec** [comment]
@JonHanna yes, having me submit a PR would be a good exercise.

**Comment by epsitec** [comment]
It is the first time that I try to submit a PR to dotnet/corefx. I re-read [GitHub's article on creating a pull request](https://help.github.com/articles/creating-a-pull-request/), but somehow I must be missing something. I expected that when _comparing changes_ of commit 72d5c9f with master, the expected _Create pull request_ button would show up. But no:

![github](https://cloud.githubusercontent.com/assets/3872435/9468121/18bf5402-4b40-11e5-9c67-9919d12c789d.png)

What am I missing?

**Comment by JonHanna** [comment]
I don't see a fork in your repositories. (I assume one can do a PR from a non-github hosted repository, but the github way is easy, so I've never tried).

Try this:
1. Fork corefx in github, so you've a `epsitec/corefx` repository in github.
2. Clone that to your local machine.
3. Create a branch.
4. Do changes in the branch, and commit them.
5. Push that branch, so it goes to `epsitec/corefx`

At that point you should see the button you suggest either when you go to `dotnet/corefx` or go to that branch in your own repository.

**Comment by JonHanna** [comment]
@epsitec how's it going? If you want I can just create a PR from my version, but if you are looking at this I don't want to duplicate your efforts needlessly.

**Comment by epsitec** [comment]
@JonHanna thank you for your detailed explanations. I was trying to do the PR directly from your commit. I'll do the fork/clone/branch/commit/push tomorrow morning. It has been a long day here.

**Comment by epsitec** [comment]
Sice PR #2977 was closed, this can be closed too...

**Comment by JonHanna** [comment]
@epsitec btw, you can set your commit messages or pull request messages to automatically close issues if merged. See https://help.github.com/articles/closing-issues-via-commit-messages/ and https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by epsitec** [comment]
Thank you. I'm still learning ;-)
