### ISSUE TITLE
Handle leak with WinHttpHandler

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2963]
The following test demonstrates an unbounded leak of both memory and handles:
```C#
[Fact]
public void TestLeak()
{
    while (true)
    {
        HttpClient client = new HttpClient();
        client.GetStringAsync("http://www.httpbin.org").Wait();
        // client.Dispose();
    }
}
```
At least one problem appears to be that without explicitly Dispose'ing of the HttpClient instance, the underlying session SafeHandle is never cleaned up.  When the session handle is created, it's DangerousAddRef'd (https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L992), and then DangerousRelease is only called if explicitly Dispose'ing (https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L555).

**Comment by davidsh** [comment]
Could be related to #2762

**Comment by JonHanna** [comment]
Part of the problem seems to be that it should do that DangerousRelease whether it's a `Dispose()` or a finaliser, and another that there's no finaliser in the base class though it uses a pattern that only makes sense if there is.

Am I missing something, or does ab11374 do what we need?

**Comment by davidsh** [comment]
Thx for your input on this.  You are correct that since we're doing a `DangerousAddRef` always, then we need to do a `DangerousRelease` always including both deterministic `Dispose` as well as finalizers.

We're currently re-designing a lot of the logic for WinHttpHandler as we move it to async APi patterns (#3000).  We typically do not want to define finalizers at all for the classes.  This particular bug is a problem with the way we are using the SafeHandle pattern.  And in general, the SafeHandle pattern doesn't need any finalizers to be written in consuming code since it already takes care of that in the base class.

I plan to make some tactical fixes to this soon.  But we will be modifying it more significantly in the coming weeks.

**Comment by davidsh** [comment]
The fix for the memory leaks is checked into the sources for System.Net.Http in the CoreFx repro.  

The fix is also available in the latest System.Net.Http/System.Net.Http.WinHttpHandler package version v4.0.1-beta-23310 from the CoreFx dev feed: https://www.myget.org/gallery/dotnet-core.
