### ISSUE TITLE
[UWP] Use managed WebSockets implementation for UWP

### ISSUE THREAD

**Issue by caesar-chen** [dotnet/corefx#29644]
The UWP version of WebSockets.Client currently uses WinRT WebSocket APIs.

We should use managed WebSockets on all Windows (including UWP), and obsolete WinRT implementation.

Related: #9503

**Comment by caesar1995** [comment]
@karelz I set the Milestone to future, since we will not address it for 2.2. Is that ok?

**Comment by karelz** [comment]
Yep, that's good. Thanks!

**Comment by davidsh** [comment]
I started looking into this.  One problem doing this is that the managed websocket implementation uses SocketsHttpHandler.  And SocketsHttpHandler uses native WinHTTP APIs in order to read the system proxy settings (IE settings) and calculate a proxy (even doing WPAD protcol and Javascript compiling the PAC file).

I don't think the native WinHTTP APIs are in the "allowed" list for a UWP app.  We will need to add them.

cc: @danmosemsft

**Comment by danmosemsft** [comment]
@ptorr-msft is your contact for that

**Comment by davidsh** [comment]
This issue was specific to the UAP implementation of the networking stack which had a different implementation for things like HTTP and WebSockets.

As of PR #41759, we no longer build the separate implementation for the UAP platform. So, this issue can't occur anymore with .NET 5 because we now will be using the same .NET Core implementation as on Windows, Linux, Mac.
