### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by mobi12** [dotnet/corefx#29650]
On ubuntu18.04 
下列软件包有未满足的依赖关系：
 dotnet-sdk-2.1.4 : 依赖: dotnet-runtime-2.0.5 但是它将不会被安装
E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。
and if I try install dotnet-runtime
下列软件包有未满足的依赖关系：
 dotnet-runtime-2.0.5 : 依赖: libicu57 但无法安装它
                        依赖: dotnet-hostfxr-2.0.5 但是它将不会被安装
then I install libicu57
没有可用的软件包 libicu57，但是它被其它的软件包引用了。
这可能意味着这个缺失的软件包可能已被废弃，
或者只能在其他发布源中找到

**Comment by stephentoub** [comment]
From Bing Translator:

On ubuntu18.04
The following packages have unsatisfied dependencies:
dotnet-sdk-2.1.4: Dependent: dotnet-runtime-2.0.5 But it will not be installed
E: Errors cannot be fixed because you want some packages to stay the way they are, which destroys dependencies between packages.
And if I try install Dotnet-runtime
The following packages have unsatisfied dependencies:
dotnet-runtime-2.0.5: Dependent: libicu57 but cannot install it
Dependencies: dotnet-hostfxr-2.0.5 But it will not be installed
Then I install libicu57
There is no package libicu57 available, but it is referenced by other packages.
This may mean that the missing package may have been discarded, Or only found in other publishing sources

**Comment by karelz** [comment]
This issue was moved to dotnet/core-setup#4144
