### ISSUE TITLE
runtimeGroups.props is missing some new .NET Core 2.1 RIDs

### ISSUE THREAD

**Issue by bording** [dotnet/corefx#29674]
While reading the [.NET Core 2.1 RC1 announcement](https://blogs.msdn.microsoft.com/dotnet/2018/05/07/announcing-net-core-2-1-rc-1/), I noticed that new linux distros and architectures are mentioned being supported in .NET Core 2.1.

However, when I checked the current [runtimeGroups.props](https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtimeGroups.props) file, I noticed that it hasn't been updated to cover everything mentioned in the article.

Alpine 3.8 needs to be added.

Is Raspbian going to be a supported distro? It's completely missing from the file.

I'd really like to make sure this gets updated for the final 2.1 release. Should I open a PR? If so, is there anything else not mentioned in the announcement article that should be added as well?

CC: @weshaggard

**Comment by karelz** [comment]
I believe Alpine is supported via musl entries. @weshaggard will know for sure.

**Comment by karelz** [comment]
cc @janvorli @eerhardt

**Comment by bording** [comment]
@karelz As I've pointed out [before](https://github.com/dotnet/corefx/issues/23699), while the generic RIDs work for .NET Core itself, the RID graph is also used by NuGet to resolve package assets. When a package needs to ship distro-specific native assets, falling back to the generic RIDs makes that impossible.

I've already had one PR that's added missing RIDs for 2.1 (https://github.com/dotnet/corefx/pull/26439), so I'd really like to see these additional ones be added as well.

**Comment by kasper3** [comment]
Doesn't seem like a blocker for 2.1?
Alpine Linux 3.8 is not a released product, it is late (3.8 hasn't even been branched yet). 3.7 is still the latest release.

**Comment by weshaggard** [comment]
@bording alpine is the only new officially supported distro but there could very well be new versions that aren't in the RID graph yet. @ianhays you have been looking at a lot of our distro support lately could you have a look over the RID graph and check the versions are upto date.

2.1 is basically done so I don't expect we will take any update for 2.1 RTM but we may consider updating it in 2.1 servicing if we find entries that are necessary.

**Comment by ianhays** [comment]
> you have been looking at a lot of our distro support lately could you have a look over the RID graph and check the versions are upto date.

The versions are good for the current state of the world.

> Is Raspbian going to be a supported distro? It's completely missing from the file.

We're missing things like raspbian because it's expected that those don't need their own specific RIDs and can use the debian ones instead. It does complicate things somewhat if you have nuget assets specifically for those flavors, though the move has been more towards making those things as portable as possible. 

> while the generic RIDs work for .NET Core itself, the RID graph is also used by NuGet to resolve package assets. When a package needs to ship distro-specific native assets, falling back to the generic RIDs makes that impossible.

If the above approach is inadequate, we should be able to add a raspbian member as its own runtime group as a child of debian so package restoration will fallback to debian when a raspbian specific package isn't available. That shouldn't break the restoration world on raspbian. That isn't something we'd block on, though.

> Alpine Linux 3.8 is not a released product, it is late (3.8 hasn't even been branched yet). 3.7 is still the latest release.

There's no harm in adding new versions of existing distros to the runtimes.json like for Alpine3.8, but it also isn't something we'd block a release on, particularly not if the new version is unreleased.

**Comment by wtgodbe** [comment]
Looks like this is resolved, closing
