### ISSUE TITLE
System.DirectoryServices nuget package not shipped in output folder

### ISSUE THREAD

**Issue by xaviergxf** [dotnet/corefx#29707]
Hi,

 Can i use the nuget package System.DirectoryServices with vs 15.7.1? I've added the nuget packages 4.5.0-rc1 but it mixes with the one on the gac and in the output folder(bin/debug) no System.DirectoryServices.dll is created. Should this nuget package produce dll's on my bin/Debug/net471 folder? 

This is related to issue #18090 

Thanks

**Comment by safern** [comment]
Hi @xaviergxf from what I know since the assemblies inside the package have the same identity as the ones in the GAC, when you target net45 or older you will not get a dll bin placed in your output folder since it should use the one in the GAC, which means that this assemblies are shipped inbox in full framework. Actually if you look at the package itself we're adding a placeholder file into the package for net45 -> https://github.com/dotnet/corefx/blob/release/2.1/src/System.DirectoryServices/pkg/System.DirectoryServices.pkgproj#L13

This to tell NuGet that it is inbox in that or any compatible framework in this case net471 and that should use the inbox dll (in this case the one in the GAC). 

cc: @weshaggard @tarekgh

**Comment by danmosemsft** [comment]
@xaviergxf what are you trying to achieve? Directory Services is already in .NET 4.7.1.

**Comment by xaviergxf** [comment]
I'm trying to have this dll independent on the output folder to be independent of what's installed on the GAC. The end goal is to be able to do a AppDomain.AssemblyResolve using this dll, since i don't know how to load a dll that is in the gac (I want to use this code with .net core and .net framework).

**Comment by danmosemsft** [comment]
@jeffschwMSFT can you advise? We presumably don't support loading .NET Framework assemblies from outside of the GAC, and we don't support the CoreFX implementation running on .NET Framework. Can @xaviergxf write code that will run on both and load it either way?

**Comment by jeffschwMSFT** [comment]
@danmosemsft you are correct.  If you try to load an assembly that has the same identity as one you are trying to load it will prefer the gac.

**Comment by xaviergxf** [comment]
@jeffschwMSFT can you advice how should i procede? Should i remove my custom AssemblyResolve handler and let it use the default .net? How can i add a another path for the assembly probing in both .net frameworks(core/classic)?

**Comment by jeffschwMSFT** [comment]
I would recommend using the one that comes on the box, will that work for your scenario?  In .NET Framework the best way to expand the probing locations is through an AssemblyResolve event.

**Comment by ViktorHofer** [comment]
Advise is to use the .NET Framework inbox assembly. Closing. Feel free to reopen if you disagree.
