### ISSUE TITLE
DTLS support for UDP client

### ISSUE THREAD

**Issue by l0nley** [dotnet/corefx#29711]
Hi!
I am looking for DTLS implementation for .NET.
It looks like this is not supported yet? Do you have any plans to support it?

**Comment by karelz** [comment]
Currently we do not have plans to add DTLS support.

There are some community projects though: https://github.com/CreatorDev/DTLS.Net

**Comment by l0nley** [comment]
Its very sad to hear. I can imagine many appliances, such as IoT.  I am aware about community projects, but as you can see project you suggested not maintained for 2 years, as well as it has tons of limitations, like "No support for fragmentation of handshake packets" which limits its usability.

**Comment by davidfowl** [comment]
How widespread is DTLS I haven't seen it used anywhere...

**Comment by l0nley** [comment]
Well, DTLS is implemented by several projects including Cisco AnyConnect, F5 Networks Edge VPN Client, Citrix Systems NetScaler, OpenSSL, and actually web browsers support DTLS-SRTP for WebRTC.

**Comment by SunnyWar** [comment]
Add me as someone that wants this. I'm working on a project right now that will take _significantly_ longer to complete without it.

**Comment by davidfowl** [comment]
Do other platforms have DTLS built in or are they all 3rd party packages? I can't see this getting prioritized over other networking work tbh. We still need to implement HTTP/2 and QUIC and HTTP/3... Not to mention the other issues and general improvements for the existing networking stack.

**Comment by l0nley** [comment]
What do you mean under other platforms? And, just in case these "platforms" do not have build-in support of DTLS, does it mean .NET should not have this feature?

**Comment by davidfowl** [comment]
Other platforms - java, golang, python, etc.

It’s a data point, we don’t just do features because issues are filed. There’s are thousands of issues and feature requests and this one in particular doesn’t bubble to the top. As I said before, AFAIK, I’ve rarely seen DTLS requested and there are 3rd party libraries that have this functionality. I’m not convicned this needs to be in the BCL.

**Comment by karelz** [comment]
As @davidfowl said, it is one of the data points. It is not wide statement we only follow others.

Regarding this specific ask, given the (low) number of upvotes, the complexity of such feature, the fact there is existing community project and the fact that we have much higher priority gaps in our networking story (HTTP/2, QUICK, HTTP/3, other high-impctful issues in networking filed in this repo), it is highly unlikely we will get to this in next couple of years (just setting realistic expectations).
I am fine keeping it open to solicit more feedback and upvotes over time.

**Comment by karelz** [comment]
Triage: We believe that QUIC protocol (which we are looking into) will supersede DTLS protocol. We may have some APIs exposed for QUIC too, which will fullfill this ask.
Closing as it is not needed to be tracked separately.

**Comment by SunnyWar** [comment]
@karelz perhaps include a reference the item related to QUIC so that we can track its progress?

**Comment by sipsorcery** [comment]
Perhaps the reason at least some of us are asking for DTLS is because it's required for WebRTC which has gained a lot of momentum. QUIC is highly unlikely to replace DTLS for WebRTC anytime soon (if ever).

There also seem to already be a few [DTLS implementations](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tsgu/7b1c3b62-c241-4a98-a3f3-6c393ceadfb4) in Microsoft products perhaps one of those could be leveraged for dotnet.
