### ISSUE TITLE
Extremely poor performance of ConcurrentQueue.Count

### ISSUE THREAD

**Issue by douglasg14b** [dotnet/corefx#29759]
Getting the `Count` property is very slow, and as the size of the queue grows it takes longer and longer to retrieve this property. Eventually almost all processing power is utilized by the retrieval of `Count`.

This is a non-issue on .NET Framework (tested v4.6.2).

**Example:**

```cs
using System;
using System.Collections.Concurrent;
using System.Diagnostics;

namespace ConsoleApp1
{
    class Program
    {
        //Measures the time it takes to get Count 1000 times as the number of queue elements increases
        static void Main(string[] args)
        {
            ConcurrentQueue<int> queue = new ConcurrentQueue<int>();

            Stopwatch sw = new Stopwatch();
            Console.WriteLine($"Ms ---- Elements");
            for (int i = 0; i < 1000000; i++)//1 million
            {
                sw.Start();

                if (queue.Count >= 100000) //100k
                {
                    break;
                }

                sw.Stop();

                queue.Enqueue(i);
                if (i % 1000 == 0)
                {
                    
                    Console.WriteLine($"{sw.ElapsedMilliseconds} ---- {i}");
                    sw.Reset();
                }
                
                
            }

            Console.ReadLine();
        }
    }
}

```
 
**Example output:**

![image](https://user-images.githubusercontent.com/1400380/40155578-5c852562-5949-11e8-9452-56ae0c8ef332.png)

**Comment by danmosemsft** [comment]
I believe this is a consequence of tradeoffs made in its implementation to favor performance of concurrent queueing and dequeueing. Can you avoid calling Count on the hot path? @stephentoub

**Comment by benaadams** [comment]
Why do you want to call count so much? 

If to check if queue is empty `IsEmpty` should remain fast. If for bounding (as in example) would something more like a BoundedConcurrentQueue be desirable? https://github.com/dotnet/corefx/issues/24365

**Comment by douglasg14b** [comment]
@benaadams 

I'm calling it so much in my example to show how rapidly it slows down. I noticed this on an app where I was using Count more than necessary, and the performance hit on large queues brought it to my attention when I switched to .Net Core.

A BoundedConcurrentQueue is definitely desirable, would the use cases be much different from a BlockingCollection?

**Comment by stephentoub** [comment]
Ok, I think I have a solution that should avoid the need to freeze the segments when calling Count.  That freezing is the cause of the expense, as Count is O(N) in the number of segments, and if Count is called after every enqueue/dequeue operation, we'll end up with a segment per element, which is abysmal.  Even with this change, though, Count is still not cheap, and it should still be avoided as much as possible on hot paths.

**Comment by stephentoub** [comment]
Just to close this out, using the above repro, on my machine, before the fix:
```
Ms ---- Elements
0 ---- 0
4 ---- 1000
26 ---- 2000
44 ---- 3000
58 ---- 4000
78 ---- 5000
97 ---- 6000
112 ---- 7000
136 ---- 8000
156 ---- 9000
226 ---- 10000
282 ---- 11000
324 ---- 12000
348 ---- 13000
384 ---- 14000
409 ---- 15000
445 ---- 16000
483 ---- 17000
544 ---- 18000
605 ---- 19000
639 ---- 20000
886 ---- 21000
723 ---- 22000
768 ---- 23000
769 ---- 24000
1070 ---- 25000
981 ---- 26000
995 ---- 27000
977 ---- 28000
1109 ---- 29000
1173 ---- 30000
1515 ---- 31000
1578 ---- 32000
2351 ---- 33000
1642 ---- 34000
1594 ---- 35000
1626 ---- 36000
1665 ---- 37000
1830 ---- 38000
1976 ---- 39000
2063 ---- 40000
```
and after https://github.com/dotnet/coreclr/pull/18035:
```
Ms ---- Elements
1 ---- 0
0 ---- 1000
0 ---- 2000
0 ---- 3000
0 ---- 4000
0 ---- 5000
0 ---- 6000
0 ---- 7000
0 ---- 8000
0 ---- 9000
0 ---- 10000
0 ---- 11000
0 ---- 12000
0 ---- 13000
0 ---- 14000
0 ---- 15000
0 ---- 16000
0 ---- 17000
0 ---- 18000
0 ---- 19000
0 ---- 20000
0 ---- 21000
0 ---- 22000
0 ---- 23000
0 ---- 24000
0 ---- 25000
0 ---- 26000
0 ---- 27000
0 ---- 28000
0 ---- 29000
0 ---- 30000
0 ---- 31000
0 ---- 32000
0 ---- 33000
0 ---- 34000
0 ---- 35000
0 ---- 36000
0 ---- 37000
0 ---- 38000
0 ---- 39000
0 ---- 40000
```

**Comment by danmosemsft** [comment]
Nice improvement! How does count perform on the other concurrent collections?

**Comment by stephentoub** [comment]
> How does count perform on the other concurrent collections?

It's not really the direct cost of Count that's being measured in this repro, but rather the impact of it on the Enqueue call.  ConcurrentQueue as of my changes for .NET Core 2.0 is implemented as a linked list of circular buffers.  When a buffer fills, we allocate a new buffer (typically of twice the size of the previous one), and link the previous one to it... all new enqueues go into the new segment, and the previous segment will be dropped once all of its items have been dequeued.  In order to provide snapshot enumeration of the ConcurrentQueue while still supporting concurrent enqueues and dequeues from any numbers of threads, ConcurrentQueue supports freezing a segment: when a segment is frozen, it prevents new items from being enqueued to it, as allowing items to be enqueued could overwrite items that have already been dequeued but that are still part of an active enumeration.  That means the next item to be enqueued will cause a new segment to be created, a relatively expensive operation but one that generally doesn't happen frequently because in the common fast path of just enqueueing and dequeueing, you end up eventually with a segment size large enough to handle the steady state.  Count, however, was implemented such that when there were more than two segments, it would behave similarly to enumeration.  That means that if, as in this repro, you call Count before every Enqueue, every Enqueue ends up creating a new segment.  That makes the cost of Enqueue way, way more expensive than it would otherwise be, both in time and space.  The fix essentially allows Count to avoid freezing segments, which in turn allows Enqueue to be as cheap as it should be.

**Comment by danmosemsft** [comment]
Interesting thanks.

**Comment by fujiy** [comment]
It will be release in 2.2? The next milestone is still 3.0 (https://github.com/dotnet/corefx/milestone/21)
