### ISSUE TITLE
Problem with forwarding http request after update to 2.1 rc1

### ISSUE THREAD

**Issue by JefStat** [dotnet/corefx#29771]
After updating from aspcore 2.0.7 to 2.1-RC1 the following block of code copying headers results in an ssl cert verification error. The code block is for proxying an incoming http request to another api endpoint.

```c#
public async Task Invoke(HttpContext context) {
...
            foreach (var header in context.Request.Headers)
            {
                if (!requestMessage.Headers.TryAddWithoutValidation(header.Key, header.Value.ToArray()))
                {
                    requestMessage.Content?.Headers.TryAddWithoutValidation(header.Key, header.Value.ToArray());
                }
            }
....
/// fails due to an ssl error
 using (var responseMessage = await httpClient.SendAsync(requestMessage, HttpCompletionOption.ResponseHeadersRead, context.RequestAborted)) {
}
}
```

**Comment by JefStat** [comment]
In my unit test that fails after updating to 2.1-rc1, the only header being added is 
```
Host: localhost
```
The header is added in both 2.0.7 and 2.1, but in 2.1 the request fails unless I comment out the code block adding the header.

**Comment by davidsh** [comment]
Can you post a standalone repro that shows the error?  Otherwise, we can't really debug this.

Also, it's possible this is an ASP.NET issue in which case this issue will move to that repo.

**Comment by JefStat** [comment]
sure here's a sample https://github.com/JefStat/aspcore-rc1-proxy-bug-sample . You'll need to add your own host in Proxy.cs

**Comment by davidsh** [comment]
>In my unit test that fails after updating to 2.1-rc1, the only header being added is
"Host: localhost"
The header is added in both 2.0.7 and 2.1, but in 2.1 the request fails to validate the ssl unless I comment out the code block adding the header.

@JefStat I think I understand the problem.  You need to avoid adding the "Host: localhost" header.  That is because starting in .NET Core 2.1, we will use Host: request headers as part of determining the validation process for matching TLS received server certificate's name attribute when connecting to an TLS/SSL endpoint.

**Comment by JefStat** [comment]
@davidsh Thanks that fixes it.
