### ISSUE TITLE
System.Reflection.Emit.Lightweight is missing

### ISSUE THREAD

**Issue by Lersubem** [dotnet/corefx#29808]
The error code says:
MissingMethodException: Method 'DynamicMethod..ctor(string, Type, Type[], Type, bool)' from assembly 'System.Reflection.Emit.Lightweight' was not included in compilation, but was referenced in CompilerContext..ctor(Type, bool, bool, TypeModel, Type). There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
this happens only when testing the app in Release but not in Debug
I am using the latest stable Universal Windows Application SDK and testing on Desktop
Can you guys help me?

**Comment by svick** [comment]
[That `CompilerContext` constructor](https://github.com/mgravell/protobuf-net/blob/fb56bb9/src/protobuf-net/Compiler/CompilerContext.cs#L290) seems to come from [protobuf-net](https://github.com/mgravell/protobuf-net), so this issue probably belongs to that repo.

Though I suspect the issue is that System.Reflection.Emit is not supported in UWP's AOT compiler (which is only used in Release mode).

**Comment by Pinox** [comment]
I get a similar issue in my UWP project , when trying the build in release mode then I get the following errors.

using Microsoft.NETCore.UniversalWindowsPlatform version 6.0.7

Any ideas or pointing me in the right direction will be appreciated.

![reflection](https://user-images.githubusercontent.com/5297255/40909077-fa84c2c4-67e8-11e8-9285-cc7d3cc7c762.PNG)
