### ISSUE TITLE
DbProviderFactories not found in System.Data.Common

### ISSUE THREAD

**Issue by nd-srogers** [dotnet/corefx#29811]
I have a .NetStandard class library using NetStandard 2.0.3 with .Net Core SDK 2.1.300-rc1 installed on my machine. I am trying to use the `DbProviderFactories` methods to get an instance of a `DbProviderFactory` only known at runtime.

Looking through older GitHub issues, it appears `DbProviderFactories` was ported over around December 2017 (https://github.com/dotnet/corefx/issues/4571 and https://github.com/dotnet/corefx/pull/25410), however when I look through the `System.Data.Common` namespace, and even when I decompile the NetStandard.dll file I cannot find the class anywhere. I do see the other classes around it including `DbProviderFactory` but not the static `DbProviderFactories` itself.

Am I missing something, or do I need to update anything else to get access to this class?

![image](https://user-images.githubusercontent.com/33408863/40287722-c633dfba-5cf2-11e8-925f-dee88c445adc.png)

![image](https://user-images.githubusercontent.com/33408863/40287727-d4ee60f2-5cf2-11e8-81b6-90c3d29c5f11.png)

**Comment by danmosemsft** [comment]
@nd-srogers DbProviderFactories is available in .NET Core so you can see it from a .NET Core library however it is not part of the common .NET Standard surface area which is why you can't see it from your .NET Standard library.

I cannot figure out why DbProviderFactories was not part of .NET Standard. It is in Mono: https://apisof.net/catalog/System.Data.Common.DbProviderFactories

There is some discussion about it
https://github.com/dotnet/standard/issues/59

@weshaggard have you got context?

@nd-srogers since .NET Standard 2.0 is what we have right now, your only options are to either not use this type, or create a .NET Core library instead.

**Comment by weshaggard** [comment]
@danmosemsft is correct that these are not .NET Standard APIs and are only available in .NET Core. 

@danmosemsft these APIs didn't exist in .NET Core when we created .NET Standard 2.0 which is why they weren't included, we will consider adding them to a future version of .NET Standard.

**Comment by danmosemsft** [comment]
@nd-srogers I suggest you close this in favor of https://github.com/dotnet/standard/issues/356. We will rev .NET Standard but not imminently so I suggest workarounds.

**Comment by nd-srogers** [comment]
Thanks all, I'll follow https://github.com/dotnet/standard/issues/356 for updates.
