### ISSUE TITLE
Missing resources for shared sources

### ISSUE THREAD

**Issue by marek-safar** [dotnet/corefx#29842]
The sources located under src/Common/src/CoreLib can have references to SR type but that the resources used to generate it are not synchronized.

One example is `src/Common/src/CoreLib/System/HashCode.cs` which uses `SR.HashCode_HashCodeNotSupported` but `HashCode_HashCodeNotSupported` is not available anywhere in the repo

**Comment by karelz** [comment]
@danmosemsft should we include it in shared source MQ work?

**Comment by tarekgh** [comment]
@marek-safar this is expected. there are some files exist under ```src/Common/src/CoreLib``` which is not used at all in corefx and only used in coreclr. coreclr should have resources for these. also, Also, if we are missing any resources we'll get a compilation errors. 

closing this issue and let me know if you have any specific broken issue with the resources.

**Comment by tarekgh** [comment]
> Well, this is not expected if we are using this part of the repo as shared sources for mscorlib implementation.

At that time you'll need to include the needed resource in your project. Yes, I understand this is a resource duplication with the corelib but we cannot create a dependency from any library on corelib resources. we already do that on all libraries that have some shared code between corelib and the library project.

**Comment by danmosemsft** [comment]
> Well, this is not expected if we are using this part of the repo as shared sources for mscorlib implementation.

Hmm, I didn't realize (or possibly forgot) that you were consuming shared mscorlib sources from here. I guess that makes sense if you don't want to submodule CoreCLR. We hvae an issue https://github.com/dotnet/coreclr/issues/10234 to track splitting the resx but nobody's working on it. We would possibly want to have the build merge the resx's rather than have two resource streams and need to update the code to pick one or the other. 

How important is this to you?

**Comment by marek-safar** [comment]
It's not high priority as we only have 2 strings in this category for now

**Comment by jkotas** [comment]
Tracked by #29842
