### ISSUE TITLE
DotNet SDK doesn't depend on all dependencies?

### ISSUE THREAD

**Issue by matthid** [dotnet/corefx#29844]
cc @akoeplinger

from https://github.com/travis-ci/travis-ci/issues/9644

When updating on travis from latest stable to `2.1.300-rc1-008673`. I can publish my application but it fails at runtime with:

```
Error: Failed to load ï¿½3�, error: libunwind.so.8: cannot open shared object file: No such file or directory
  Failed to bind to CoreCLR at '/home/travis/build/fsharp/FAKE/nuget/dotnetcore/Fake.netcore/current/libcoreclr.so
```

Installing libunwind fixes the problem. Does the sdk installer no longer depend on libunwind?

**Comment by karelz** [comment]
@janvorli can you please help route it?

**Comment by matthid** [comment]
Ok I understand the issue. No we have not upgraded to target netcore2.1.

Is it recommended to update SDK (even without upgrading the application itself)?
I guess the answer is yes (while there is probably no reason to stay on 2.0), that might introduce quite some "unexpectedness" when upgrading.

"area-Meta" fits perfectly because the question is: If I install the sdk via packages and publish an app with it should I have to install additional dependencies or should it depend on everything?

I guess I leave that up to you. Thanks for clarifying.

**Comment by janvorli** [comment]
> should I have to install additional dependencies or should it depend on everything

That's a good point. It seems to me that since the 2.1 SDK can target both 2.0 and 2.1 runtimes, its package should still have the dependency on libunwind (and libuuid) or we should clearly inform the user that in case the app published for 2.0 is to be run locally, the 2.0 dependencies need to be installed too.
But I am not an expert in our SDK packaging, so I'd rather let someone more knowledgable in this area to share the intended behavior here. @livarcocc can you please comment on this?

**Comment by tarekgh** [comment]
Issue moved to [dotnet/sdk #2262](https://github.com/dotnet/sdk/issues/2262) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tarekgh** [comment]
I moved this issue to the SDK repo as it looks the issue is the SDK packaging now.
