### ISSUE TITLE
Add UAP tests to CI

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#29863]
Apparently few people run them locally as they keep regressing. They aren't that slow -- seems like we could have them in CI now. @safern @joperezr do you know why we don't? Maybe CI didn't have RS3 then?

They are close to 100% passing now.

**Comment by safern** [comment]
They where disabled here: https://github.com/dotnet/corefx/commit/3fca26cedf6c54aabc100e69106fc7e263db7815#diff-f111cef164b89c1f83f8bacb425e94fc because they where blocking 2.1 stuff. Then the UAP builds where re-enabled here: https://github.com/dotnet/corefx/pull/27531 but the test execution was never enabled. It wasn't because they where slow that where removed, it was because they where failing. We should try to enable them asap before we regress the passing rate more.

**Comment by ViktorHofer** [comment]
Added with https://github.com/dotnet/corefx/pull/31260
