### ISSUE TITLE
Microsoft.Windows.Compatibility.Shims shims targeting 2.1 but supports 2.0

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#29899]
Looks like we are taking the live shims https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.Windows.Compatibility.Shims/Microsoft.Windows.Compatibility.Shims.pkgproj#L7. However we are putting them in 2.0 folder in package https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.Windows.Compatibility.Shims/Microsoft.Windows.Compatibility.Shims.pkgproj#L32. This is likely going to cause problems with folks using these shims on 2.0 because we moved some types down in 2.1. I'm not sure how big of an issue this is right now but we should do a diff and decide what to do about this and decide whether or not we want to cross-compile the shims or something else.

cc @ericstj @safern

**Comment by weshaggard** [comment]
I marked as 2.1.x currently until we understand the full extent of the problem.

**Comment by ericstj** [comment]
Just did a quick diff of mscorlib/system/system.core and I see the following forwards will be broken:
- System.ComponentModel.InvalidEnumArgumentException
- System.Collections.Comparer
- System.Diagnostics.DebuggerStepperBoundaryAttribute
- System.Diagnostics.DebuggerVisualizerAttribute
- System.IO.StreamReader
- System.IO.StreamWriter
- System.IO.TextReader
- System.IO.TextWriter

I also saw a number of removals from 2.0 mscorlib that were a bit odd.  Things like Int32EnumComparer which were internals that were removed.  I think this might break some serialization scenarios.

**Comment by safern** [comment]
So then that means that we will need to cross compile them for 2.0 and have the 2.0 shims and the 2.1 shims included in their own folder, right?

**Comment by ericstj** [comment]
Yeah.  That'd do the trick and is probably the safest thing to do for now.

If we wanted something that was more future proof we could generate one set that was based on the superset of the types forwarding to the original location when they first appeared in .NETCore.  Since we'll always add typeforwards when we push types down and compiler/runtime are resilient to dangling forwards this would work.  It may be difficult to accomplish though, since the tools we use to generate these require seed assemblies.  I've started thinking about some of this and filed https://github.com/dotnet/corefx/issues/29900, which is what I was working on when I noticed this issue and reported to @weshaggard.

**Comment by weshaggard** [comment]
Actually thinking about this a little more it isn't as simply as cross-compiling just for 2.0 as we need to take the live version (that support 2.0) of the compat package libraries as well. So it will be 2.0 for the core platform and the live version of all the compat packages.

**Comment by ericstj** [comment]
> it isn't as simply as cross-compiling just for 2.0

It is actually that simple.  The build system ensures the right set of bits get binplaced.  When you build a "live" build of allconfigurations it gets the 2.0 ref/runtime binplaced and then the latest assemblies (where they target 2.0) are dropped on top.

**Comment by ericstj** [comment]
@safern that's fine.  `netstandard` should binplace for `netcoreapp2.0` if that's the best config available.  You may want to include a runtime binplace config for netcoreapp2.0 here, https://github.com/dotnet/corefx/blob/master/dir.targets#L76, because shims like mscorlib target runtime assemblies so that they can expose internal types that may surface in serialization.

**Comment by safern** [comment]
Ok, thanks. Also, should all the packages under the compat pack, including the shims package, should be harvested once we release the stable versions? Because all of them still have nca2.0 package configurations in our master branch.

**Comment by danmosemsft** [comment]
@safern can you please create that PR and update the table with  the link

**Comment by karelz** [comment]
Fixed in 2.1 servicing (release/2.1 branch) in PR #30522.
