### ISSUE TITLE
Need a way to run packages tests without requiring netfx targeting pack being installed

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#29906]
Right now if I want to run the package tests and I don't have all the targeting packs installed for all the net* full framework TFMs that we build packages for, then the package tests fail with error: 

```
E:\repos\corefx\bin\testPkg\tools\sdk\2.1.300-rc1-008673\Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644
: The reference assemblies for framework ".NETFramework,Version=v4.6.2" were not found. To resolve this, install the SD
K or Targeting Pack for this framework version or retarget your application to a version of the framework for which you
 have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) a
nd will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framewo
rk you intend. [E:\repos\corefx\bin\testPkg\projects\System.ValueTuple\net462\project.csproj] [E:\repos\corefx\pkg\test
\testPackages.proj]
E:\repos\corefx\pkg\test\testPackages.proj(177,5): error MSB3073: The command "E:\repos\corefx\bin/testPkg/tools//dotne
t msbuild /t:Test "E:\repos\corefx\bin/testPkg/test.msbuild" /p:TestPackages=System.ValueTuple" exited with code 1.
```

cc: @ericstj @joperezr

**Comment by joperezr** [comment]
I guess that for this we could manually restore the targeting packs and have the generated projects to reference that instead, but it does go a bit against what we try to do with these tests. The point of the tests is to try to test our packages against a real-world environment, and see if they restore correctly, so that also means referencing the same targeting pack that our customers will. Also, these tests are only ever run by CI, which I believe it is not super hard to update once a new targeting pack is available. 

All of that said though, if we still think it's better to reference packages that are restored from NuGet then I'm fine with that.

**Comment by ericstj** [comment]
I think there is a middle ground here that's still in the spirit of the tests without making them too artificial.

If we had packages that completely duplicate the structure under `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\<version>` and then ensured that MSBuild examined the package's directory for file-list / references / facades / etc then I think it would be reasonable.  Eventually that'll even be a supported scenario, but we can fake it until then.  The existing private targeting pack packages aren't quite good enough since they don't include everything and don't plug into MSBuild targets, but I think we can make it work easily enough.  Make sure we call them 'private' so as not to imply official support for that scenario.

**Comment by safern** [comment]
Fixed by: https://github.com/dotnet/corefx/pull/34764
