### ISSUE TITLE
System.Globalization: Expose DateTimeFormat GetShortestDayName to .NET Core contract

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#2996]
I found what looks like a mistake in the .NET Core contracts for DateTimeFormat.
 
This class exposes two sets of APIs:  some methods, and their corresponding properties.
 
For example, DateTimeFormat has a GetMonthName(int) method, that returns the name of the specified month.  And then it has a corresponding property MonthNames, that is a string array of all the month names.
 
This is true for Month Names, Abbreviated Month Names, Day Names, and Abbreviated Day Names.  And in the full framework, this holds true for Shortest Day Names:  string GetShortestDayName(DayOfWeek) & string[] ShortestDayNames.
 
However, in the .NET Core contracts, the string[] property ShortestDayNames is public, but the method GetShortestDayName(DayOfWeek) is not exposed.  I see this [is true for Silverlight](https://msdn.microsoft.com/en-us/library/system.globalization.datetimeformatinfo(v=vs.95).aspx) as well.

We should expose this method in the .NET Core.

**Comment by ellismg** [comment]
There was a quick internal discussion on this.  The general feeling is that we should correct this oversight.  My only question was that it probably means we have to version the contract which means the in box facades from 4.6 are not going to work (since they have different version numbers).  So this might be something we have to do post 1.0.

**Comment by weshaggard** [comment]
cc @tarekgh

**Comment by tarekgh** [comment]
I believe we have some other APIs we need to expose in the same contracts. one example is returning the date/time patterns array. I know the current contract is close to what exposed in Silverlight and we didn't expose such missing APIs because nobody really requested it to be exposed or blocked by it. 
@ellismg I agree with you this should wait to post 1.0 as no one blocked by it and we'll have a chance to update the inbox façades too.

**Comment by terrajobst** [comment]
We should do a full review of this item to figure out what the façade implications are. Since it's already marked as 'ready for api review' we'll pick it up in one of the next slots.

**Comment by tarekgh** [comment]
we may consider exposing the following APIs too 

GetAllDateTimePatterns()
GetAllDateTimePatterns(Char)

SetAllDateTimePatterns

I would say the first 2 are important (especially the second). The third is not that important so I don't feel strongly about it..

**Comment by terrajobst** [comment]
@tarekgh / @eerhardt can you create an C# syntax list of the APIs you need to add. We believe the additions are fine; it would need to go into the future branch because of the overlap with the .NET Framework. Once we have the API list, we can approval offline.

**Comment by tarekgh** [comment]
@terrajobst 

Here is the extra APIs we need to expose, please let's know if there is anything else needed for the approval.

public sealed class DateTimeFormatInfo
{
    public String GetShortestDayName(DayOfWeek dayOfWeek) { return null;  }
    public String[] GetAllDateTimePatterns() { return null;  }
    public String[] GetAllDateTimePatterns(char format) { return null; }
}

**Comment by tarekgh** [comment]
These APIs should be now exposed in dev/api .net standard 1.7 and the full implementation is in for Windows. we are tracking to get the implementation soon for other platforms.
