### ISSUE TITLE
Optimize ConcurrentDictionary.IsEmpty for non-empty case.

### ISSUE THREAD

**Issue by IlyaGrebnov** [dotnet/corefx#29994]
Today we always take locks to check if concurrent dictionary not empty. But we could avoid taking this locks under assumption that non-empty dictionaries are more common. Proposed optimization is to check if any bucket non-empty without locks first and if we could not find any fallback to approach with locks. See example below on why locks are still important.

[Example by @stephentoub for why it takes all the locks, to ensure a consistent view]
ConcurrentDictionary is partitioned into multiple buckets, each of which is protected by its own lock, in order to minimize contention when multiple threads are mutating different buckets.  Now imagine that the dictionary has two buckets, one with 0 elements and one with 1 element, so the total number of items is 1.  Consider if IsEmpty just iterated through through the buckets looking at their counts and without any additional synchronization.  Let’s say it looks at the first bucket, and sees 0 elements.  Then, another thread adds an element to the first bucket and then removes the element from the second bucket.  And then the original thread calling IsEmpty proceeds to look at the second bucket, sees that it’s also empty, and returns true, it’s empty.  At no point during the entire operation was the dictionary ever empty, as it had 1 element, then 2 elements, and then 1 element, but IsEmpty erroneously returned true.

**Comment by riezebosch** [comment]
Elaborating on the example, does it make sense to have an IsEmpty property on a concurrent dictionary? What's the use if you cannot safely expect it to be empty directly after the moment you checked?

That being said I suspect the emptiness being related to number of items and the concurrency level. When there are more items than threads you can safely tell it to be not empty. When 3 threads are mutating the buckets and a 4th thread checks for emptiness it is not when there are more than 3 items in the different buckets. Otherwise you have to wait because all items could be in the process of being removed. And that's my point: are you empty on that specific moment or not.

**Comment by stephentoub** [comment]
First, just because the dictionary can be used concurrently doesn't mean it always is.  For example, you might manipulate it concurrently, but then in a serialized context want to see whether it contains anything.

Second, even in a concurrent context emptiness is relevant in some scenarios.  For example, imagine you've populated the dictionary and you know there aren't going to be any more additions, only removals.  Then IsEmpty returning true is a known final state that'll never be transitioned out of.

Third, even if that's not the case you may have some polling operation that wants to perform an operation if it's empty or if it's not empty, and it doesn't matter that the value has changed after that.  For example, imagine a cleanup routine that needs to run once a second.  If it checks IsEmpty and finds that it returns true, it skips doing expensive set up for its cleanup; if it happened to be the case that something was added after IsEmpty returned true, that's fine, it'll get noticed the next time around (plus in a cleanup scenario, if it was added immediately after IsEmpty returned true, it's probably not going to be cleaned up anyway).  Or if IsEmpty returned false but then the last thing was removed, well, worst case you've expended the energy to start the cleanup routine and it won't find anything to clean up.

**Comment by drewnoakes** [comment]
@karelz, I'd be happy to look at this for the hackathon.

**Comment by karelz** [comment]
@drewnoakes I sent you collaborator invite - see details here: https://github.com/dotnet/corefx/wiki/Hackathon#how-can-i-grab-an-issue
(assigning temporarily to myself)

**Comment by drewnoakes** [comment]
@karelz accepted. Thanks.
