### ISSUE TITLE
Add string-based alternatives for Path.Join

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#30049]
In #25536 we've added 

```csharp
namespace System.IO
{
    public static class Path
    {
        public static string Join(ReadOnlySpan<char> path1, ReadOnlySpan<char> path2);
        public static string Join(ReadOnlySpan<char> path1, ReadOnlySpan<char> path2, ReadOnlySpan<char> path3);
    }
}
```

The intent was that people will be able to call these APIs when they have a span or a string (because `string` has an implicit conversion to `ReadOnlySpan<char>`). However, some languages, such as F#, do not support implicit conversions. Also, it forces developers to know that this conversion exists. Normally, this isn't a big deal as developers learn common conversion between primitives but we don't expect the vast majority of developers having to use spans much -- it's meant as a low-level building block. Thus, they will largely remain unaware of the existence of that conversion.

So, to call these APIs from F# developers have write this:

```ml
Path.Join(p.AsSpan(), "obj".AsSpan())
```

To address these issues, we should just add `string`-based overloads which simply call the the other APIs:

```csharp
namespace System.IO
{
    public static class Path
    {
        // Existing
        public static string Join(ReadOnlySpan<char> path1, ReadOnlySpan<char> path2);
        public static string Join(ReadOnlySpan<char> path1, ReadOnlySpan<char> path2, ReadOnlySpan<char> path3);

        // New
        public static string Join(string path1, string path2);
        public static string Join(string path1, string path2, string path3);
    }
}
```

**Comment by stephentoub** [comment]
So for any new API that takes a `ReadOnlySpan<char>` we're going to add a `string`-based overload?  Why not "fix" the languages where the implicit conversion isn't supported to instead be supported rather than double the number of APIs?

**Comment by terrajobst** [comment]
> Why not "fix" the languages where the implicit conversion isn't supported to instead be supported rather than double the number of APIs?

F# (or more specifically ML) deliberately decided not support implicit conversions. I'm not a language expert, but this have to do with other aspects, such as global type inference. I think it's fair to ask why F# couldn't change that but by an large type system constraints like this tend to be fundamental aspects that are hard, impossible or just undesirable to change. For better or worse, as API designers we have to think about this (and we already do, albeit with a super heavy bias towards C#).

> So for any new API that takes a `ReadOnlySpan<char>` we're going to add a `string`-based overload? 

I don't think so. But we should consider that general purpose APIs like `Path.Join()` which will be used by many people who don't use `Span<T>` at all. We shouldn't force them having to know that `string` can be converted to `ReadOnlySpan<char>`. I think within feature areas that heavily deal with spans (`System.Buffers`, `System.IO.Pipelines`) I think it's acceptable to rely on these conversions. Furthermore, I think it's impractical not to rely on them, otherwise we have to offer `Span<T>` overloads every time we offer `ReadOnlySpan<T>` API.

Distilled to a guideline I'd say:

**DO NOT** rely on implicit conversions from spans to `T[]` or `string` in general purpose APIs that aren't specific to buffers. Instead, offer overloads that operate on spans, strings, and arrays.

**Comment by cartermp** [comment]
I agree with @terrajobst here:

* For namespaces which are designed to be used in performance-critical scenarios, having everything be `Span`/`ReadonlySpan` based seems perfectly reasonable.
* For namespaces which are general-purpose, relying on an implicit conversion between e.g., `string` and `Span` is troublesome. Not just because F# may not support that, but because it sort of violates a rule of least surprise and forces someone new to .NET to understand this concept just to understand the API.

As for what F# can do, it is possible to add an ad-hoc implicit conversion for scenarios like this, but we really don't want to get in the business of doing so unless it's overwhelmingly useful with no reasonable alternative. For example, we implicitly convert the result of `TryParse(string, out int)` into a tuple of `bool * int`. The only other alternative is to juggle the `byref<int>` yourself, which isn't very fun.

But I'd like to avoid that sort of thing for F# if the problem can be covered by a design principle for non-performance critical API areas.

**Comment by dsyme** [comment]
My little-rant-that-Krzysztof-very-kindly-said-was-not-a-rant is [here](https://github.com/fsharp/fslang-suggestions/issues/648#issuecomment-393714831)

>  .NET, 99% of programmers should never need to know or think about Span. If we force that 99% to think about it, we will lose 50% of them, since the thing that the vast majority of programmers value above everything else is simplicity.

So TBH I don't think this is particularly an F# issue, though @terrajobst wrote it up like that.  The surprising thing here was to see what I regard as a "ultra beginner" API (in `System.IO`) using both implicit conversions and new memory primitives. Both make APIs a harder to understand, even for C# programmers, e.g. when accessing the API via reflection.  

My feeling is that if an existing API doesn’t rely on implicit conversions, then please don’t start using them.  Adding Span overloads also feels risky from a cognitive-simplicity POV for beginners.  But there's a larger topic lurking there: how do we make .NET APIs friendly again to, say, my teenage son or daughter?

p.s. I’m not totally opposed to implicit conversions. The F# language design doesn't implement them, that's partly because some .NET APIs that use them heavily can reasonably be kept "at arms length" (e.g. some wrapper helpers to access the most common functionality), and partly for lots of good cognitive-simplicity reasons in a globally type-inferred language.   I understand some .NET API design relies on them and I'm not launching a crusade against that :)

**Comment by danmosemsft** [comment]
cc @JeremyKuhne

**Comment by zpodlovics** [comment]
@terrajobst  As most of the server / desktop / mobile hardware is multi-core now, **how the concurrencty/atomicity story supposed to work here**? 

Right now I can atomically replace two strings with Interlocked CAS (Compare And Swap) because it has a reference type semantics, but implicit string conversion paths will change this semantics. **How the atomic operations - that are already possible now - supposed to work with these implicit type conversions (for example: reference type -> value type ...)?**

**Comment by stephentoub** [comment]
@zpodlovics, I'm not understanding the relevance of the concern.  Can you share an example?

**Comment by zpodlovics** [comment]
Let's assume future apis wills be only available as ReadOnlySpan arguments with implicit type conversions:

1) How can I do volatile read/write with ReadOnlySpan?

```csharp
        static bool VolatileEq(ref String s1, ref String s2) 
        {            
            String sv1 = Volatile.Read(ref s1);
            String sv2 = Volatile.Read(ref s2);
            return (0 == String.CompareOrdinal(sv1,sv2));
        }

```

2) How can I do CAS with ReadOnlySpan?

```csharp
        static void StringCAS(ref string value, string newValue, string oldValue) 
        {
            do 
            {
            } while(!Object.ReferenceEquals(Interlocked.CompareExchange(ref value, newValue, oldValue), oldValue));
        }
```
Let's assume I have a method with String argument. I can safely combine this with the earlier examples in 1) and 2) because it has reference semantics.

```csharp
        static String Identity(String s)
        {            
            return s;
        }
```

Can I safely combine this with the earlier examples in 1) and 2)? What could possibly go wrong when somewhere in the callchain there is a String -> ReadOnlySpan -> String implicit conversion and I combine it with examples in 1) and 2)??

```csharp

        static String Identity(ReadOnlySpan<Char> s) 
        {            
            return new string(s);
        }
```

**Comment by stephentoub** [comment]
> Let's assume future apis wills be only available as ReadOnlySpan arguments with implicit type conversions

That's not at all what's being said. If a method can't be implemented with span arguments, of course it's not going to take span arguments.

**Comment by stephentoub** [comment]
Which methods in .NET Core 2.1 for example that take spans are you concerned about? There are hundreds of them.

**Comment by jnm2** [comment]
@zpodlovics Reference equality isn't intended to be meaningful with the `string` type, as far as I know.

**Comment by terrajobst** [comment]
Implemented by https://github.com/dotnet/coreclr/pull/18458.
