### ISSUE TITLE
System.Reflection.Emit.Lightweight in UWP Release mode

### ISSUE THREAD

**Issue by Pinox** [dotnet/corefx#30127]
My UWP app has always been building fine in release mode , until recently.
I now get various System.Reflection.Emit type errors. I have been battling with these errors for the past 2 weeks , very frustrating indeed );

Not sure what I'm suppose todo in this case. Can someone please advise or steer me in the right direction.

using Microsoft.NETCore.UniversalWindowsPlatform version 6.0.7 with various .net standard 2.0 libraries that are also used cross platform.  VS 15.7.3 Stable release

In debug mode everything works as expected.

![reflection](https://user-images.githubusercontent.com/5297255/40934382-e51af54c-6834-11e8-9bf7-77536c71ffc1.PNG)

**Comment by davidfowl** [comment]
AFAIK you can’t use reflection emit with UWP applications (at least not in release mode). This is becuse of the native compilation step that happens in release mode. This is why you only see it then.

**Comment by Pinox** [comment]
Thanks @davidfowl for the reply.  This used to work before in release mode so just trying to figure out my next step to eliminate this issue.  Just for my own clarity are we talking about reflection in general in the main UWP app + .net standard 2.0 dll's.    Therefor I shouldn't use system.reflection namespace in any of the above although it's .net standard 2 compliant or are we talking something more specific in the system,reflection namespace.

Sorry for my ignorance here but how do I check what is using reflection.emit so that I can start eliminating it if possible.

**Comment by MichalStrehovsky** [comment]
Yes, Reflection.Emit is not supported in UWP applications.

@joshfree @weshaggard If these contracts are in the targeting pack for UAPAOT, should we just have throwing implementations in UAPAOT CoreLib for these? It's what we do for the other APIs that UAPAOT doesn't support. These seem to be baselined in `ApiCompatBaseline.uapaot.txt` to shut up tooling warnings instead and it feels strange because customers get warnings/errors at build time instead.

**Comment by jkotas** [comment]
> should we just have throwing implementations in UAPAOT CoreLib for these?

cc @morganbr

**Comment by benaadams** [comment]
Crashes CoreRT at compile time https://github.com/dotnet/corert/issues/5720 and https://github.com/dotnet/corert/issues/5913 for .NET Core 2.1/ASP.NET Core 2.1

**Comment by morganbr** [comment]
I'm ok with throwing implementations. It'd be nice to add a feature detection API so the compile errors don't just turn into runtime errors though.

**Comment by Pinox** [comment]
Hi @morganbr , are you saying we can wait for future release where we will be able to compile app in release mode without it throwing errors that prevents compilation and submitting to store. Currently as far I can see my application reference libraries are the problem , so just throwing warnings will help as I don't have to replace my existing libraries or get third parties to change their code.

**Comment by morganbr** [comment]
@Pinox, yes that's what @MichalStrehovsky is suggesting and I'm ok with.

That said, my point was that your app will start compiling, but that it might not actually work because those libraries may need some System.Reflection.Emit feature in order to work (which isn't proposed here). Ideally, we can also add an API something like ```DynamicMethod.IsSupported()``` where the libraries can test whether it works and do something else if it doesn't.

**Comment by Pinox** [comment]
thanks @morganbr for the clarity.  Any timing on when the app will start compiling again (.net native runtime version number ? ) as I have been using the libraries for the past 2 years without issues in release mode , this is a recent issue where errors are shown. I will obviously also take it up with the vendors to fix but short term I'm stuck as I can't go back on many of the libraries as it is deeply rooted in my current app.

**Comment by ViktorHofer** [comment]
Closing as System.Reflection.Emit.Lightweight isn't supported on UWP.
