### ISSUE TITLE
X509Certificate2, subject and issuer properties, does not match with fields from .pem .pfx files

### ISSUE THREAD

**Issue by rdcm** [dotnet/corefx#30264]
In both cases after creation `X509Certificate2` object, properties `Subject` and `Issuer` has different value then from my .pem or .pfx file.

```
var cert = new X509Certificate2(AppDomain.CurrentDomain.BaseDirectory + "client_name.pfx", "super_secret_pass");
```
or
```
        public static X509Certificate2 CreateFromCertFile()
        {
            var cerFile = AppDomain.CurrentDomain.BaseDirectory + "client_name.crt";
            var keyFile = AppDomain.CurrentDomain.BaseDirectory + "client_name.key";

            var cert = new X509Certificate2(cerFile);
            cert.PrivateKey = CreateRSAFromFile(keyFile);

            return  cert;
        }
```

```
openssl pkcs12 -info -in client_name.pfx
CN=client_name, OU=clients, O=MongoDB China, L=Shenzhen, ST=GD, C=CN
```

```
openssl x509 -in client_name.pem -inform PEM -subject -nameopt RFC2253
CN=client_name, OU=clients, O=MongoDB China, L=Shenzhen, ST=GD, C=CN
```

but X509Certificate2 read this info like
Subject: `CN=client_name, OU=clients, O=MongoDB China, L=Shenzhen, S=GD,  C=CN`
Issuer:   `CN=CA-SIGNER, O=MongoDB China, L=Shenzhen, S=GD, C=CN`

Look like difference between `S=GD` and `ST=GD` affect authentication on db server.

**Comment by bartonjs** [comment]
Neither the subject nor issuer contains "S=" or "ST=".  What they actually contain are the object identifier 2.5.4.8.

The OpenSSL command-line tool uses "ST" as the human-friendly version of that identifier, but .NET uses "S" (because that's what .NET Framework did, because that's what Windows does).  It's just a presentation thing, no corruption.

**Comment by Clockwork-Muse** [comment]
....so at this point the question to be asking is, "Why are you using the subject string as part of the authentication?", since that's the most trivial thing to spoof.  Most issuers aren't going to check any of those values (Let's Encrypt, say, or any other auto-issuer), simply because there's no way to do so.  If you're doing something like a search for the cert, doing so by thumbprint or serial number (spoofable) is likely to yield better results.

**Comment by rdcm** [comment]
@bartonjs 
Seems I found the source of the problems, this is incorrect information in the connection string(wrong replica set name). Where i can find more info about presentation ssl certificates on windows/linux?

@Clockwork-Muse 
At this moment i just playing with mongo TLS auth mechanism localy. Mongodb store user info like this:
`CN=client_name, OU=clients, O=MongoDB China, L=Shenzhen, ST=GD, C=CN` with list of issued roles.
Nowhere explicit did not use `ST=GD` for auth logic.
