### ISSUE TITLE
IGrouping Should Implement IQueryable

### ISSUE THREAD

**Issue by GrantHoffman** [dotnet/corefx#30403]
I'm trying to filter a `GroupBy` without materializing,  I would like to `OrderBy` using an `Expression`  so my logic can be Translated into SQL, Instead of having to pull my Entire Grouping Entire Results Set back.

I have an Entity which looks like so:

```c#
    public class ConfigurationValue
    { 
        public int Id {get; set;}
        public string KeyField {get; set;}
        public string Value {get; set;}
        public Guid OwnerId { get; set; }
    }
```

My query looks like so:

```c#
    var groupQuery = context.ConfigurationValues.GroupBy(x => x.Namespace);
    Func<ConfigurationValue, bool> orderFunc = y => y.Type == "Int";

    //This should call Enumerable because there is no direct conversion to Queryable
    var shouldCallInMemory = groupQuery.Select(x => x.FirstOrDefault(y => y.Type == "Int"))
                                                     .ToArray();

    var usingExplicitFunc = groupQuery.Select(x => x.FirstOrDefault(orderFunc)).ToArray();
```

If you look at the `IGrouping<,>` interface it only implements IEnumerable

```c#
    public interface IGrouping<out TKey, out TElement> : IEnumerable<TElement>, 
          IEnumerable
    {
        //...
    }
```

My first variable which should be called in Memory because my Lambda Expression should be converted into a `Func` which means there would be no way to translate that into SQL.  Yet It generates the Proper SQL As Seen here:

```sql
    SELECT 
    [Limit1].[ConfigurationValueId] AS [ConfigurationValueId], 
    [Limit1].[Namespace] AS [Namespace], 
    [Limit1].[Key] AS [Key], 
    [Limit1].[Value] AS [Value], 
    [Limit1].[Type] AS [Type], 
    [Limit1].[ModifiedOn] AS [ModifiedOn], 
    [Limit1].[CreatedOn] AS [CreatedOn], 
    [Limit1].[OwnerGlobalId] AS [OwnerGlobalId]
    FROM   (SELECT DISTINCT 
        [Extent1].[Namespace] AS [Namespace]
        FROM [dbo].[ConfigurationValue] AS [Extent1] ) AS [Distinct1]
    OUTER APPLY  (SELECT TOP (1) 
        [Extent2].[ConfigurationValueId] AS [ConfigurationValueId], 
        [Extent2].[Namespace] AS [Namespace], 
        [Extent2].[Key] AS [Key], 
        [Extent2].[Value] AS [Value], 
        [Extent2].[Type] AS [Type], 
        [Extent2].[ModifiedOn] AS [ModifiedOn], 
        [Extent2].[CreatedOn] AS [CreatedOn], 
        [Extent2].[OwnerGlobalId] AS [OwnerGlobalId]
        FROM [dbo].[ConfigurationValue] AS [Extent2]
        WHERE ([Distinct1].[Namespace] = [Extent2].[Namespace]) AND (N'Int' = [Extent2].[Type]) ) AS [Limit1]
```

Using an explicit Func I would expect then to do the same yet it generates an error:

>Unsupported overload used for query operator 'FirstOrDefault'

This is extremely confusing and inconsistent, as it's misleading to the proper behavior.

What appears to be happening is the Select generates the proper expression, however when you are using an Explicit Func this will break compilation, meaning Prior to the select you must Materialize.

While if you wanted to use a custom expression `AsQueryable` would be required to be called

**Comment by divega** [comment]
@GrantHoffman It seems to me that your primary goal is to be able to pass a predicate created outside the query to `FirstOrDefault()`, so that it can be parsed by the query provider and translated to SQL. 

You also found (and I agree) that this is an area in which some of the complexity of how LINQ actually works "leaks through the seams" and you have had to form a deeper understanding in order to clear up the confusion.

Assuming my interpretation is accurate, calling `AsQueryable` (as you mentioned at the end of your post) is a common idiom you can use in to achieve this in LINQ. 

You can argue that this isn't very discoverable and that it is relatively hard to even understand why you need it, but this is not the only scenario in which you would call `AsQueryable` inside a query to achieve a similar outcome. 

A scenario I have seen more often comes up while writing a method that applies an `Expression<Func<T, bool>>` predicate where `T` is the element type of a collection on the objects you need to filter, e.g.:

``` C#
    public IEnumerable<Customer> GetCustomersByOrderCriteria(
        Expression<Func<Order, bool>> predicate)
    {
        return context.Customer.Where(c => c.Orders.AsQueryable.Any(predicate)).ToList();
    }
```

On the other hand, changing an interface like `IGrouping` would be very impactful. I think someone creating an alternate version of `GroupBy` that returns a new version of the 'IGrouping` interface that is based on `IQueryable` is possible, but I don't think that would happen in the base class libraries of .NET. Having this additional complexity doesn't seem justified.

**Comment by cston** [comment]
@GrantHoffman, thanks for reporting this issue. It looks like the behavior is by design.
