### ISSUE TITLE
X509Certificate2.GetCertContentType documented behaviour

### ISSUE THREAD

**Issue by filipnavara** [dotnet/corefx#30416]
The `X509Certificate2.GetCertContentType` API is documented to throw only `ArgumentException`. However, given invalid data such as `X509Certificate2.GetCertContentType(new byte[1])` it throws `CryptographicException` on Windows. This is consistent with the behaviour on .NET Framework. On non-Windows systems it returns `X509ContentType.Unknown`, which is consistent with the documentation. Either the documentation or the implementation should be fixed.

**Comment by filipnavara** [comment]
Partially resolved by #35322. I guess the documentation needs to be fixed now.

**Comment by vcsjones** [comment]
Oh, ha - I didn't see there was an issue for this. I can try getting the docs updated.

>On non-Windows systems it returns `X509ContentType.Unknown`

Kind of. Unix (the OpenSSL PAL) also threw; macOS was the outlier here. It seemed more reasonable to me make macOS match OpenSSL / CAPI rather than trying to change both Unix and Windows behavior.

I do think the behavior is strange and returning `Unknown` seems much more desirable. In the meantime though; consistent behavior across all the platforms was more important to me. It's more likely to me that a developer took a dependency on it throwing for Windows / Unix than a dependency on macOS returning Unknown.

**Comment by filipnavara** [comment]
It was an issue that was found through Mono test suite. I don't remember what the OpenSSL behavior was, but I mostly tested on macOS (even the OpenSSL builds) so it's quite possible I just overlooked it.

Intuitively I would expect the documented behavior, but I understand that there could be compatibility concerns and I am generally fine with either choice. All code I inspected was prepared to handle the CryptographicException.

**Comment by bartonjs** [comment]
Since @vcsjones already fixed the inconsistency, this is now just a docs issue; which should be created using the flow from https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2.getcertcontenttype?view=netframework-4.7.2

(https://github.com/dotnet/dotnet-api-docs/blob/40032d55704974a9ea9a7ff3b65e67a91fc9b1bb/xml/System.Security.Cryptography.X509Certificates/X509Certificate2.xml is the actual location for anyone who wants to jump straight to a PR)
