### ISSUE TITLE
System.Threading.Channels 4.5.0 does not work for net452

### ISSUE THREAD

**Issue by JanEggers** [dotnet/corefx#30454]
I thought that channels would be available for net452 but seems they require net46.

why is the package named 4.5 if it depends on 4.6?

is there a chance to port it to net452?

**Comment by karelz** [comment]
The 4.5.0 version is NuGet version, it has nothing to do with .NET Framework version.
I assume that 4.5.2 didn't have some APIs/constructs the implementation needed and therefore it targets 4.6. I let area experts to chime in.

**Comment by tarekgh** [comment]
@JanEggers

> why is the package named 4.5 if it depends on 4.6?
As @karelz mentioned, 4.5 is the package version and not the supported platform version

This library support 4.6 as the minimum full framework version because it is part of netstandard 1.3 which require full framework 4.6 as a platform 
https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.3.md

Why can you not target 4.6 or later versions?

I am closing the issue but feel free to reply with any more questions.

CC @stephentoub

**Comment by JanEggers** [comment]
@tarekgh  I am personally on net472 but im contributing to a library that still targets net452 so I would be totally willing to update to the latest greatest but the author of the package is not...

**Comment by davidfowl** [comment]
The library might need to cross compile but I’m guessing this can’t easily be abstracted.
