### ISSUE TITLE
SpreadsheetLight not restored against correct framework

### ISSUE THREAD

**Issue by Bridgeway** [dotnet/corefx#30547]
I'm trying to use the package manager console in VS 2017 to install SpreadsheetLight 3.4.9 to my web api .net core 2.1 project, but I get a yellow triangle on NuGet node in Solution Explorer and this message:

Package 'SpreadsheetLight 3.4.9' was restored using '.NETFramework, Version =v4.6.1' instead of the project  target framework '.NETCoreApp, Version=v2.1'. This package may not be fully compatible with your project.

**Comment by svick** [comment]
The SpreadsheetLight package does not support .Net Core. It's possible that it will still work, if it doesn't use any APIs that are .Net Framework only, which is why you're getting a warning, not an error.

Though looking at the package, you might also need to manually install DocumentFormat.OpenXml.

**Comment by karelz** [comment]
Answered & not CoreFX related, closing.
