### ISSUE TITLE
Why doesn't ContentDispositionHeaderValue just _always_ use quoted strings for name and filename?

### ISSUE THREAD

**Issue by tmenier** [dotnet/corefx#30611]
I'm trying to decide how to address an [issue](https://github.com/tmenier/Flurl/pull/327) with my library where multipart requests sent to an older ASP.NET site are failing due to names not being quoted:

```
Content-Disposition: form-data; name=file;
```

The simple solution is to just ensure they're always quoted. But I hesitate, because Flurl is just delegating to the System.Net.Http stack for this, and it seems like a [very deliberate decision was made](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Headers/ContentDispositionHeaderValue.cs#L428-L460) to only quote names when absolutely necessary, such as when the value contains a space.

I understand that the most recent RFCs imply that quotes are not strictly required. But it seems like the safe path (and simplest implementation) is to just always include them. But before I make this change to my library and inflict it on all users, I'd like to have a better understanding of why the .NET team(s) decided to do it the way they did. Could anyone shed any light on that decision? Are there any potential pitfalls to always quoting that I'm not thinking of? Thank you.

**Comment by karelz** [comment]
@caesar1995 I think you did investigations in the space - can you please answer?

**Comment by tmenier** [comment]
@caesar1995 Any thoughts here? Is it "safe" for a general-purpose HTTP client library to just always use quoted values for `name` and `filename` in `Content-Disposition` headers?

**Comment by caesar1995** [comment]
We _**only**_ add quotes around those parameters when RFC specifies that [it's required](https://tools.ietf.org/html/rfc6266#appendix-D). The reason is that we want to preserve user's input, and avoid unknown issues which will caused by always appending quotes. Also this behavior is same on .NET Framework, and we don't want to break it.

I don't know (not aware of) about potential pitfalls to always quoting, but users can always pass in quoted strings for name and filename themselves in such case.

cc: @davidsh

**Comment by tmenier** [comment]
Thank you, that's helpful.
