### ISSUE TITLE
Add advance math class

### ISSUE THREAD

**Issue by leecow** [dotnet/corefx#30671]
@khoshroomahdi commented on [Mon Jun 25 2018](https://github.com/dotnet/core/issues/1724)

# Issue Title
Please add a library like math.net to. Net core
Be as descriptive as you can with your title.

# General

Provide details on the problem you are experiencing including the .NET Core version, operating system version and anything else that is relevant.

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by khoshroomahdi** [comment]
something like mathpy or Math.net

**Comment by tannergooding** [comment]
@khoshroomahdi, those are very large and fairly well established libraries.

It would be very helpful to provide explicit examples of APIs that are missing, how adding them to corefx would be helpful, and why doing that is better than telling people to use the already well established libraries.

There is a process to getting APIs added (see https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md#steps) of which the first step is logging an issue in the correct format. As it is now, this issue will only lead t ok discussion rather than any actual API review.

A good example for the general layout of an API proposal can be seen here:https://github.com/dotnet/corefx/issues/271

**Comment by tannergooding** [comment]
Closing, as there is nothing currently actionable here and no acting discussion.

If there are particular APIs you would like to see exposed, please open an API proposal, following the steps I listed above.
