### ISSUE TITLE
Convert.FromBase64String different behavior in .NET Core 2.1 vs 2.0

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#30793]
The following code does not throw in .NET Core 2.0:

```C#
string input = "randonendorsementkeyfortest==";
Convert.FromBase64String(input);
```

In .NET Core 2.1 this will throw:

```
Unhandled Exception: System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
```

It's very likely that the exception is correctly identifying a malformed base64 string that we were using to test (I've verified that `randonendorsementkeyfortest=` - only one padding (`=`) character - is accepted by the decoder in 2.1).

I think it's worth noting the difference in the [API Compat list](https://github.com/dotnet/corefx/wiki/ApiCompat). 
Due to [another bug](https://github.com/Microsoft/vstest/issues/1669), this caused our tests to fail after upgrading our Docker container to .NET Core 2.1 runtime for a __vstest__ project (TFM remained the same).

**Comment by danmosemsft** [comment]
@AtsushiKan looks like you made the last significant changes to base 64 decode in e0fa11308de58684cde6bf8b7d0da287b48f01e9

I guess strictly this input should have only 1 padding? If the old implementation was tolerant of extra padding, it seems to me that we should do: it does not introduce any ambiguity, and avoids breaking code. If that's the case, this might be a servicing candidate?

**Comment by AtsushiKan** [comment]
I'll look at this tomorrow.

**Comment by AtsushiKan** [comment]
Stepping through the older implementation:

- The behavior is clearly the result of a subtle logic error, not an intended behavior. An extra "=" at the end of a empty string, for example, throws the correct exception.

- The extra "=" is not just ignored. It causes the api to return a garbage byte array. It decodes the last complete subgroup as if it were "bc==" rather than "abc=". In other words, it's the **_fifth from last_** character that's ignored, not the illicit "=".

Unless we see widespread compat problems, I don't think it's worth replicating this quirk.

**Comment by stephentoub** [comment]
> Unless we see widespread compat problems, I don't think it's worth replicating this quirk.

+1

> The behavior is clearly the result of a subtle logic error, not an intended behavior.

Can we make sure we have tests for these various bugs?

**Comment by danmosemsft** [comment]
Thanks for investigating @AtsushiKan . @CIPop since you mention this was a test string, and the result produced in the old behavior is garbage, I don't think we will want to change this. Appreciate the report though.

**Comment by gfoidl** [comment]
@tracker1 

> decode authentication tokens

these are [base64url](https://en.wikipedia.org/wiki/Base64#URL_applications) encoded, where `+` is replaced with `-` and `/` is replaced with `_`, and no padding `=` is added.
Hence in this case it isn't a bug, because it's a "different" encoding (while still based on base64).

For _base64url_ you can use [WebEncoders](https://github.com/aspnet/Common/blob/master/shared/Microsoft.Extensions.WebEncoders.Sources/WebEncoders.cs) (and hopefully sometime https://github.com/aspnet/Common/pull/338), which handles these encoding w/o need for manually fixing up things.

**Comment by gfoidl** [comment]
> Blows up... it's valid, padded, base64 ...

Yeah, it has to blow up when it follows the rules.

A valid base64-encoded string length is always a multiple of 4. (If there is not enough input-data, padding `=` will therefore get added).

Your given string has length 402, so 402 % 4 = 2. Hence it is not a valid base64 string.
Try to decode without the final padding, it won't blow up and give you the expected `byte[300]` result.

BTW: your workaround is really hacky :wink:

**Comment by tracker1** [comment]
@gfoidl no, a valid base64 string is divisible by 3 characters... there are 4 bytes encoded as 3 characters in base64.

**Comment by tracker1** [comment]
@gfoidl My bad... I remembered incorrectly.. for some reason was thinking 3 encoded characters for every 2 bytes, not 4 encoded per 3 bytes.  You are correct.  :-)

and yeah, it was incredibly hacky...  I should have looked back at the spec instead of working from memory.  I found this bug, and thought it applied.

**Comment by mithunta** [comment]
Looks like issue is not fixed in 3.0 as well. Do we know when this issue will be fixed?

**Comment by gfoidl** [comment]
@mithunta just to make sure you're not mixing _base64_ with _base64url_ as they are similar, but different encodings (see above).

What issue do you want to have fixed?
For _base64url_ you can use something like https://www.nuget.org/packages/gfoidl.Base64/ which supports that.

**Comment by mithunta** [comment]
@gfoidl - I was using built in System function - Convert.FromBase64String(data). I used the suggested solution from the post by @tracker1 by replacing the literals. I did not try this base64url package.
