### ISSUE TITLE
System.Threading.Channels : Expose Channel.EstimatedCount

### ISSUE THREAD

**Issue by mgravell** [dotnet/corefx#30852]
This is already available internally via things like `ItemsCountForDebugger`, but it would be invaluable for system monitoring purposes.

Yes, I know about the inherent race condition of a `Count`; however, the purpose is not for making decisions; it isn't to decide between `0` or `2`, nor is it to decide between `10000` or `10002` - it is so that when shit hits the fan, in my automated "what the hell happened" scanning, I can tell the difference between a backlog of `2` (probably fine) and `10002` (probably part of the problem).

Happy for it to be hidden via attribs, hard to find, given a name from hell (`int RoughCountEstimateDontTrustThisSeriously()`) - but I **really really want it**.

Happy to PR etc.

---

Edit: API proposal: add

```
public abstract int EstimatedCount {get;}
```

with suitable implementations, for example ala `ItemsCountForDebugger`.

It probably makes sense to change the debugger display attribute to use `"EstimatedCount"` and remove the extra non-public property.

**Comment by stephentoub** [comment]
I'm fine with such a property as long as we can come up with a name that is as much of a warning as Marc's "RoughCountEstimateDontTrustThisSeriously" but obviously not quite as verbose :)

**Comment by stephentoub** [comment]
cc: @tarekgh

**Comment by tarekgh** [comment]
@mgravell can't you get this using the reflection?

**Comment by mgravell** [comment]
yes, but that's kinda defeating the purpose of an API, no?

**Comment by Drawaes** [comment]
Having (even a quick and dirty) backlog counts for queues is a hard requirement for any real system. We run a lightweight custom actor style model that we currently use Data flow for and are looking to move. One key feature for measuring system health is a background thread that goes around watching no actor is getting backed up and if so alerts operators....

**Comment by mgravell** [comment]
@stephentoub  just for comparison... `ConcurrentQueue<T>` has all the same thread-race concerns; the name of the count property is... `Count` :)

**Comment by tarekgh** [comment]
> this type is essentially a queue; knowing the length of the queue is, to me as a consumer, a fundamental property of the type.

Using queue is an internal implementation of specific types of channels we support so if anyone else implements a custom channel, it is not necessary to be a queue. I am just thinking if providing this property will not be confusing in the future when providing more types of channels or even changing the internal implementation of current channels if we need to.

**Comment by stephentoub** [comment]
@mgravell, ConcurrentQueue provides snapshot semantics, such that the Count it provides is guaranteed to have been the number of items in the queue at some time (even if it's changed since).  It actually makes its Count more expensive to be able to do that.  I would like to avoid such expectations here.

**Comment by NickCraver** [comment]
How about `.ApproximateCount`?

**Comment by mgravell** [comment]
I'd also be fine with `bool TryGetApproximateCount(out int count)` (or `bool TryGetCount(out int count`) - and if the custom implementation can't provide that: then: don't! or an `int?`, whatever

**Comment by tarekgh** [comment]
@stephentoub do you think having count property will make sense for any user's custom channels or for any channel we support later. if you think so, here is the suggested list for the name we may choose from:

- Count
- ApproximateCount
- EstimatedCount
- VolatileCount
- UnsteadyCount
- UnsafeCount

**Comment by stephentoub** [comment]
> @stephentoub do you think having count property will make sense for any user's custom channels or for any channel we support later

I'm having trouble coming up with a case where the concept wouldn't make sense.  The closest I've come is a channel that's not actually backed by anything, e.g. an InfiniteChannel, where a read will always succeed, in which case the count would effectively be infinite.  But even in such a case you could argue that a Count of 1 always makes sense, such that there's always 1 item available, and the moment that one is consumed, another comes into existence.  Otherwise, since a channel is all about being a producer/consumer data structure that allows a producer to hand off items to a consumer, and since that number of items should be "countable", it should be possible to always come up with a count.

The question for me isn't whether the concept is possible, but whether it'll always be possible to implement efficiently and safely.  One of the problems we've had with Count members on concurrent collections in the past is that they're often much slower than developers expect, and as such developers end up calling Count expecting it to be O(1) and fast, but get perf issues as a result of their expectations not being met.  We can alleviate that by choosing a name like one of the ones you suggest.  However, there's still the possible issue that needing to support it could have an impact on the rest of the implementation.  It's one thing if adding Count is pay-for-play, such that you only pay the costs of getting the count if you try to get the count; my larger concern would be if exposing Count was not pay-for-play and if doing so actually caused other things to get slower, e.g. if in order to support getting the count, enqueue and dequeue required more synchronization.

For example, when `Channel.CreateUnbounded` is used with `ChannelOptions.SingleReader`, the implementation will use a `SingleProducerSingleConsumerQueue` as the implementation: that queue not only has no locks, it also has no interlockeds, using only volatile operations to implement the required thread-safety for a single producer and a single consumer.  The implementation is currently commented that it's only valid when nothing is concurrently mutating the collection:
https://github.com/dotnet/corefx/blob/5f3d22a7f335ae4c1dd57f9ac8b7460a13d57ee0/src/Common/src/System/Collections/Concurrent/SingleProducerConsumerQueue.cs#L219-L220
We would need to review the code to understand why that is.  Right now, it likely doesn't matter, as the count is only used when everything is frozen in the debugger.  But if we expose this such that it may end up being used concurrently with either readers or writers, both of which mutate the collection, would the worst case just be an inaccurate count? If so, that's probably ok, as long as it's named correctly.  Or would the worst case be some kind of infinite loop?  That's not ok (if it can't be fixed).  We would need to validate the worst case here.

**Comment by tarekgh** [comment]
ok, let's choose a name to indicate that this count is not safe at all and would be the responsibility of the caller how to use it. I mentioned the name suggestions so far we can choose one of them or come up with one better name.

**Comment by Drawaes** [comment]
I don't mind most of the names except for what my opinion is worth I would leave "unsafe" out of it. In the lexicon of .net it has a pretty specific meaning around memory. The count method will give a stronger guarantee than "I will leak memory in some circumstances" its more "I might be inaccurate".

**Comment by Joe4evr** [comment]
`EstimatedCount` sounds like the best option, then.

**Comment by tarekgh** [comment]
If all agree, @mgravell may need to get the API proposal written in the top of this page and we can proceed from here.

**Comment by mgravell** [comment]
@tarekgh  like that? or did you mean something else?

**Comment by tarekgh** [comment]
@mgravell here is some example regarding the format we prefer 

https://github.com/dotnet/corefx/issues/271

**Comment by jafaber** [comment]
A bit late, but if "Count" gives the wrong idea:

- EstimatedCapacityUsed
- EstimatedCapacityUsage

All I'm personally interested in is knowing when I hit say 90% capacity, so I can signal the producers to slow down.

**Comment by tarekgh** [comment]
@stephentoub I marked this as ready for review. please let me know if you you have different suggestions.

**Comment by stephentoub** [comment]
I've thought about this a bit more, and I think I'd actually be ok with just "Count".  I still have all the same concerns, but on reflection I'm not sure that the more complicated naming options are actually safer in any meaningful way.  So, whichever is fine.

**Comment by terrajobst** [comment]
* We considered naming the property with `EstimatedCount` but that seems overkill because you never get an exact count unless you freeze the world, but that's the nature of concurrent APIs.

```C#
namespace System.Threading.Channels
{
    public abstract partial class Channel<T>
    {
        public abstract int Count { get; }
    }
}
```

**Comment by scalablecory** [comment]
@terrajobst what was decision re: throwing VS magic number?

**Comment by stephentoub** [comment]
Because we're adding the CanCount property, we then throw from Count if CanCount is false.

FWIW, as I just sat down to implement this quickly, I think the {Can}Count on `ChannelWriter<T>` is strange, as what you'd really want to know on the writer is how much room is available, not how many items you could consume, which you can't on a "writer".  I'm going to skip the writer side for now and just do the reader.  If we find a strong need later, we can revisit the writer side separately, but I think it would need a different API.
