### ISSUE TITLE
Use fast copy on Mac

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#30865]
Port https://github.com/mono/mono/pull/9038 to corefx

**Comment by stephentoub** [comment]
It looks like Mono also passes COPYFILE_CLONE in addition to COPYFILE_ALL that we currently pass.

**Comment by stephentoub** [comment]
Actually, it looks like the COPYFILE_CLONE flag only applies to copyfile, not to fcopyfile, so specifying that as well will require more refactoring.  Currently we open the files in C# and then pass down the file descriptors, but to use copyfile instead of fcopyfile, we'd need to pass down the paths and other open options to have the native code handle it:
https://github.com/dotnet/corefx/blob/0e021636e10782fdd0245fb0cb3ba3986b60dce8/src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs#L24-L29

**Comment by danmosemsft** [comment]
@JeremyKuhne fyi

**Comment by akoeplinger** [comment]
Note that we had to remove `COPYFILE_CLONE` and switch to calling `clonefile()` API instead since the former had some unintended sideeffects: https://github.com/mono/mono/pull/10020

**Comment by marek-safar** [comment]
@stephentoub could you help with this?

**Comment by akoeplinger** [comment]
or @filipnavara who contributed the improvement to Mono.

**Comment by filipnavara** [comment]
I can look into it once I am done with my patch queue (roughly estimated to be next Monday). If anyone wants to pick it up earlier I will be happy help/review.
