### ISSUE TITLE
Span<T> cannot be used to keep native memory alive?

### ISSUE THREAD

**Issue by carlreinke** [dotnet/corefx#30877]
I have a type that holds some native memory.  I want to implement `AsSpan()` on it so that the native memory can be accessed safely.

Below is a naïve attempt that shows what I'm trying to do.  Clearly `Span<T>` won't keep the holder object alive because it has only the pointer to the native memory and not a reference to the holder object.  I have also tried implementing `MemoryManager<T>` but I can't see how to make `Span<T>` keep the manager object alive either.

```csharp
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

internal class Program
{
    public static void Main()
    {
        Span<byte> span = GetSpan();
        GC.Collect();
        GC.WaitForPendingFinalizers();
        span[span.Length - 1] = 0;  // Access violation
    }

    private static Span<byte> GetSpan()
    {
        Span<byte> span = new Holder(1 << 20).AsSpan();
        GC.Collect();
        GC.WaitForPendingFinalizers();
        span[span.Length - 1] = 0;  // OK
        return span;
    }
}

public class Holder
{
    private readonly int _size;
    private readonly IntPtr _pointer;

    public Holder(int size)
    {
        _size = size;
        _pointer = Marshal.AllocHGlobal(_size);
    }

    ~Holder()
    {
        Marshal.FreeHGlobal(_pointer);
        Debug.WriteLine("{0:X} was freed", _pointer);
    }

    public Span<byte> AsSpan()
    {
        unsafe { return new Span<byte>((void*)_pointer, _size); }
    }
}
```

`Memory<T>`  supports this use case via `MemoryManager<T>`, but it has to be turned into `Span<T>` to get at the memory.

Is this a use case that  `Span<T>` supports?  If not, could it be designed to support this use case?

(I also asked this as a [question on StackOverflow](https://stackoverflow.com/q/51213806/959866), but if `Span<T>` isn't intended to support this then I won't expect a helpful answer.)

**Comment by benaadams** [comment]
I think @GrabYourPitchforks has some guidelines somewhere

**Comment by stephentoub** [comment]
> Span<T> cannot be used to keep native memory alive?

Correct. `Span<T>` just stores a pointer / reference and a length.

**Comment by GrabYourPitchforks** [comment]
You'll need to use `Memory<T>` with a custom `MemoryManager<T>` if you want to keep the underlying reference alive.

See https://gist.github.com/GrabYourPitchforks/8efb15abbd90bc5b128f64981766e834 for samples. I've been meaning to update these docs, especially with the feedback that Steve and others gave a few months ago. Maybe this'll be the kick in the pants I need to incorporate all of that feedback and hit publish. :)

**Comment by carlreinke** [comment]
> **Never** give your `MemoryManger<T>`-derived type a finalizer. If an incorrectly-written component loses its reference to the `IMemoryOwner<T>` and forgets to call `Dispose`, the garbage collector could kick in unexpectedly, even while a component still has a reference to the `Span<T>` backed by the custom `MemoryManager<T>`.

This is unfortunate.  It would have been very useful to be able to safely expose unmanaged memory in a `Span<T>` without requiring that the consumer use the `MemoryManager<T>` correctly.

It seems like portable-`Span<T>` could have stored a reference to `MemoryManager<T>` the same way that `Memory<T>` does, but fast-`Span<T>` can't support keeping a reference to the `MemoryManager<T>` because it would have significant performance implications.  (Just my suppositions from looking at the implementations.)

Given the choice between exposing a `Span<T>` that can be used unsafely and not exposing `Span<T>`, I might have to choose the latter.  😢

The balance might be slightly different if the worst that could happen is a memory leak, but there's no way to prevent the consumer from calling `MemoryManager<T>.GetSpan()`, calling `MemoryManager<T>.Dispose()`, and then using the `Span<T>`.

**Comment by GrabYourPitchforks** [comment]
What kind of safety guarantees do you need to make for your consumers? I don't really think it'll be common for somebody to dispose of a `MemoryManager<T>` while somebody is still using the `Span<T>`. Remember, you can't throw a `Span<T>` across a thread boundary or store it as a field in a class, so it's unlikely that somebody will hold on to the `Span<T>` for longer than they're supposed to. Rather, I think what will be more common is that somebody will get a `Span<T>`, _forget to `GC.KeepAlive` the underlying `MemoryManager<T>`_, and be surprised when the GC finalizes the backing memory object in the middle of their method using the `Span<T>`. That's why I suggested in the guidance not to implement a finalizer and instead to rely on the dispose method. But I admit this is a bit of a contentious point with confusing messaging, and we need to figure out as a team what we want our official guidance to be. (The draft guidance I linked above isn't official.)

The upshot of this is that if you have a standard `using` statement around your `MemoryManager<T>`, you can safely pass that `Span<T>` to any target methods within the scope of your `using` block (since the backing memory is rooted). You just can't let it escape the `using` block, otherwise you may encounter problems.

**Comment by joshfree** [comment]
related tracking docs issue for this https://github.com/dotnet/docs/issues/4823

**Comment by carlreinke** [comment]
I would like to guarantee that "using my library cannot corrupt memory".  (Obviously with `unsafe` or poking around with reflection, all bets are off.)

I'd like good performance and interoperability, so exposing a `Span<T>` for the consumer to use sounds great.  But if, then, the best guarantee that I can provide is that "using my library _as long as you don't do anything weird_ cannot corrupt memory", it sounds a little less great.

**Comment by carlreinke** [comment]
It looks like the answer is that `Span<T>` exposed on types that hold unmanaged memory cannot absolutely guarantee no use-after-free.
