### ISSUE TITLE
Test_BadEventSource_MismatchedIds_WithEtwListener failing on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#30876]
With the updated coreclr imported in https://github.com/dotnet/corefx/pull/30840, the Test_BadEventSource_MismatchedIds_WithEtwListener test is now failing on all Windows legs:
```
Unhandled Exception of Type System.IndexOutOfRangeException
Message :
System.IndexOutOfRangeException : Index was outside the bounds of the array.
Stack Trace :
   at BasicEventSourceTests.EtwListener.EtwEvent.PayloadString(Int32 propertyIndex, String propertyName) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\Harness\EtwListener.cs:line 154
   at BasicEventSourceTests.TestsUserErrors.Test_Bad_EventSource_Startup(Boolean onStartup, Listener listener, EventSourceSettings settings) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestsUserErrors.cs:line 130
   at BasicEventSourceTests.TestsUserErrors.Test_BadEventSource_MismatchedIds_WithEtwListener() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestsUserErrors.Etw.cs:line 50
```

**Comment by brianrob** [comment]
This failure occurs when we write an event to the ETW event stream stating that one of the EventSource methods is incorrectly authored.  The incorrect authoring is expected and an event is supposed to be written that contains a string describing what is wrong (this is the point of the test).

Last good commit: https://github.com/dotnet/coreclr/commit/7d048c01f8eb4b7591f71556dff5cb4ae9a79d9a
First bad commit: https://github.com/dotnet/coreclr/commit/c5dce0a3c0c5046aacde93c7ee2e35371d15ad6f

On release builds of CoreCLR starting with https://github.com/dotnet/coreclr/commit/c5dce0a3c0c5046aacde93c7ee2e35371d15ad6f the event that is written has malformed metadata and so the string parameter doesn't make it out the other end when parsing the trace.  This does not occur on debug builds (the test passes).

The event itself is a TraceLogging ETW event, which means that the base type is an anonymous type containing one or more fields.  In the case of the error message, we create an anonymous type with a single field containing the message using the following code:

```
string strMsg = "EventSource error message text here."
var msg = new { message = strMsg };
```

The TraceLoggingEventSource code then generates metadata for the anonymous type based on the set of fields present in the type.  In debug builds, ```msg.GetType().GetProperties()``` returns one property (message), but in release builds, ```msg.GetType().GetProperties()``` returns zero fields.

I have tried debugging this further, but I can't seem to figure out how the reflection cache is populated.  The breakpoints that I am setting in this area seem to not be hit, and of course debug builds don't show this error.

I am suspicious that this could be a codegen bug, as the first bad commit where this repros really isn't related at all.  I am wondering if the bug has existed for some time and we're only now hitting it due to some other change causing this to trip.

@AtsushiKan, would you be able to take a look at this and see if you see something in our usage of reflection or in the reflection system itself that might cause this?  Otherwise, we should probably ask @RussKeldorph to have a look.  Thanks.

**Comment by brianrob** [comment]
In case it's helpful, here is the callsite where we call Type.GetProperties(): https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Diagnostics/Tracing/TraceLogging/Statics.cs#L383.

**Comment by AtsushiKan** [comment]
If this generated code is compiled to IL, I'd suggest ildasm'ing the IL to see if the "message" property is still there, and is still **public** visibility (the method you're calling only returns **public** properties.)

That's all I can think of on a five minute look.

**Comment by brianrob** [comment]
Thanks @AtsushiKan - that is a good pointer.

It turns out that in the good case, the message property exists (see below), but in the bad case it does not.

```
.class private auto ansi sealed beforefieldinit '<>f__AnonymousType0`1'<'<message>j__TPar'>
       extends System.Object
{
  .custom instance void System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor() = ( 01 00 00 00 ) 
  .field private initonly !'<message>j__TPar' '<message>i__Field'
  .custom instance void System.Diagnostics.DebuggerBrowsableAttribute::.ctor(valuetype System.Diagnostics.DebuggerBrowsableState) = ( 01 00 00 00 00 00 00 00 ) 
  .method public hidebysig specialname instance !'<message>j__TPar' 
          get_message() cil managed
  {
    // Code size       7 (0x7)
    .maxstack  8
    IL_0000:  ldarg.0
    IL_0001:  ldfld      !0 class '<>f__AnonymousType0`1'<!'<message>j__TPar'>::'<message>i__Field'
    IL_0006:  ret
  } // end of method '<>f__AnonymousType0`1'::get_message

  ...

  .property instance !'<message>j__TPar' message()
  {
    .get instance !'<message>j__TPar' '<>f__AnonymousType0`1'::get_message()
  } // end of property '<>f__AnonymousType0`1'::message
} // end of class '<>f__AnonymousType0`1'
```

Taking this a step further, the pre-trim (prior to ILLink) version contains the property, and the post-trim version does not.

Since this started occurring at dotnet/coreclr@c5dce0a, which removes an InternalsVisibleTo attribute (I think the last one) from System.Private.CoreLib, I'm wondering if that has caused ILLink to strip more aggressively because it believes that it can.  @erozenfeld, @sbomer, does this make sense?  If so, what is the right way to tell ILLink not to do this (at least for this compiler-generated type)?

**Comment by danmosemsft** [comment]
@brianrob you probably need to add it to https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/ILLinkTrim.xml

**Comment by brianrob** [comment]
@danmosemsft, that's my expectation, but considering it is compiler generated, I'm not sure if it's name is stable.

**Comment by stephentoub** [comment]
We've done it elsewhere with https://github.com/dotnet/corefx/blob/711c42810b8b9f8b7736b7b175cf9e330932b5f3/src/System.Net.Http/src/ILLinkTrim.xml#L4
but that's of course subject to needing to change if the compiler changes its naming scheme.

**Comment by brianrob** [comment]
Thanks @stephentoub.  @erozenfeld, @sbomer, is this the right way to proceed in this case?

**Comment by brianrob** [comment]
I have pre-emptively created #18835 and have confirmed locally that this fixes the broken test.

**Comment by erozenfeld** [comment]
Yes, this is the right way to proceed.

**Comment by brianrob** [comment]
Thanks @erozenfeld.
