### ISSUE TITLE
different CaseInsensitive across operating systems 

### ISSUE THREAD

**Issue by DanielSSilva** [dotnet/corefx#30887]
Comparing the char `º` to `o` or `O` (capital o) have different results for different OS. A repro can be found here: https://github.com/markekraus/CaseInsnsitiveOs

At the moment, it seems like it's not possible to use `º` and `o` or `O` on an hash table on Linux and MacOS, as it throws the following error (taken from PowerShell, where it was firstly detected):
```
Duplicate keys 'º' are not allowed in hash literals.
+ CategoryInfo          : InvalidOperation: (System.Collections.Hashtable:Hashtable) [], RuntimeException
+ FullyQualifiedErrorId : DuplicateKeyInHashLiteral
```
On Windows, the result of this comparison is 1, whereas in Linux and MacOS the result is 0

Thanks @markekraus for the help

**Comment by markekraus** [comment]
For clarity, this issue can ignore PowerShell altogether. PowerShell HashTable literals use case-insensitive key and detect a key clash in the literal. The reason this error happens in PowerShell is that .NET Core evaluates `º`, `o`, or `O` as case-insensitively equivalent. 

`º`, `o`, and `O` may be case-insensitively equivalent by design, but if so then the results of case-insensitive matching of these should be consistent with the same culture across all platforms. However, it appears that is not the case and (assuming the en-US culture) across different platforms there are different results.

**Comment by Clockwork-Muse** [comment]
We rely on the OS for most underlying string operations, including casing.   [Given @tarekgh 's comment here](https://github.com/dotnet/corefx/issues/29330#issuecomment-384718448), this is going to be "by design".

(If you think string stuff is bad, we delegate timezone definitions to the OS too, and there's two completely different databases in use between Windows/Everybody else)

**Comment by markekraus** [comment]
That makes sense. I was aware of the timezone craziness. I'm glad in 2.1 I no longer have to deal with the libcurl differences between platforms causing all kinds of broken x-plat behavior in HttpClient.

@DanielSSilva It looks like this is `by design` in .NET Core and there is nothing much we can do to remedy it PowerShell.

**Comment by tarekgh** [comment]
@DanielSSilva yes this is by design as @Clockwork-Muse mentioned in his comment. if you are seeing some wrong behavior in the casing when running on specific OS, you may report this issue to Windows team if this is reported on Windows or report it to the ICU library if you are running on Linux/OSX.

**Comment by DanielSSilva** [comment]
Thanks for the clarification @tarekgh , @Clockwork-Muse, @markekraus . I thought it would be compared to the ascii characters...
