### ISSUE TITLE
Implement Marshal.GetComObjectData and Marshal.SetComObjectData in .NET Core

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#31015]
These methods are stubbed out and throw PNSE in .NET Core. Looking at reference source it should be easy to implement (https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/__ComObject.cs#L66-L108)

```cs
public static Object GetComObjectData(Object obj, Object key)
{
    if (obj == null)
    {
        throw new ArgumentNullException(nameof(obj));
    }
    if (key == null)
    {
        throw new ArgumentNullException(nameof(key));
    }

    __ComObject comObj = null;

    // Make sure the obj is an __ComObject.
    try
    {
        comObj = (__ComObject)obj;
    }
    catch (InvalidCastException)
    {
        throw new ArgumentException(SR.Argument_ObjNotComObject, nameof(obj))
    }

    if (obj.GetType().IsWindowsRuntimeObject)
    {
        throw new ArgumentException(SR.Argument_ObjIsWinRTObject, nameof(obj));
    }

    // Retrieve the data from the __ComObject.
    return comObj.GetData(key);
}
```

**Comment by danmosemsft** [comment]
Both API's have 2.5% usage in .NET compat lab data.
@ericstj did this show up for you?

**Comment by hughbe** [comment]
This also breaks the `CreateWrapperOfType` API which relies on `GetComObjectData` and `SetComObjectData` so actual impact may be a little higher

**Comment by ericstj** [comment]
@hughbe nice find.

None of the apps I brought up hit a codepath where they'd crash due to this, but that doesn't mean its not important.  

Did a quick check and here's a couple suspect commits:
https://github.com/dotnet/coreclr/commit/3103a70d1fbe733d2b4e7ed9e2ff795b888b8b79
https://github.com/dotnet/coreclr/commit/16f5695839f753b803149c9e012a924733a46a5b

For the first I think it just used the wrong ifdef, FEATURE_CORECLR instead of FEATURE_COMINTEROP, then later got removed when folks did define cleanup.

For the latter I think it was a bad change to take.  We don't get to remove API just because its confusing.  /cc @luqun @jkotas

**Comment by hughbe** [comment]
I believe that was temporary and we've now implemented `Read*`/`Write*`

e.g. https://github.com/dotnet/coreclr/tree/master/src/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.cs#L382-L385

**Comment by ericstj** [comment]
Indeed the right thing was done later on with https://github.com/dotnet/coreclr/commit/88779dc83763dc199ad1666282316d393473609d. 

I think https://github.com/dotnet/coreclr/commit/3103a70d1fbe733d2b4e7ed9e2ff795b888b8b79 still introduced throwing APIs where it should have only made them throw on unix.
