### ISSUE TITLE
Breaking change on WebSocket.ReceiveAsync

### ISSUE THREAD

**Issue by kblok** [dotnet/corefx#31076]
I started getting a `WebSocketException` sent from [ThrowIfEOFUnexpected](https://github.com/dotnet/corefx/blame/06aa6f0ce4cdf78985f029f218007a7d55f8965f/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L1203) when I upgraded the [Puppeteer-Sharp demo app](https://github.com/kblok/puppeteer-sharp/tree/master/demos) from .NET Core 2.0 to 2.1.

The [GetResponseAsync](https://github.com/kblok/puppeteer-sharp/blob/features/core-21/lib/PuppeteerSharp/Connection.cs#L159) method is pretty straight forward. It's a `while true` with a ReceiveAsync call inside. You can take a look at it [here](https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Connection.cs#L180).

I didn't find any note on the [.NET Core Release Notes](https://github.com/dotnet/core/blob/master/release-notes/download-archive.md) but I did find a change made by @stephentoub  in the WebSocket class  here https://github.com/dotnet/corefx/commit/06aa6f0ce4cdf78985f029f218007a7d55f8965f.

I created a [branch on my Repo](https://github.com/kblok/puppeteer-sharp/tree/features/core-21) with the failing demo app. You just need to run [PuppeteerSharpDemos-Local.sln](https://github.com/kblok/puppeteer-sharp/blob/features/core-21/demos/PuppeteerSharpDemos-Local.sln). You can see the error if you break [here](https://github.com/kblok/puppeteer-sharp/blob/features/core-21/lib/PuppeteerSharp/Connection.cs#L194).

Let me know if you need me to test something or if you need something else from me.

**Comment by stephentoub** [comment]
Is this WebSocket created for the server side or the client side?

What OS?

What version of .NET Core are you using? You said 2.1, but is that 2.1.0, 2.1.1, 2.1.2, etc.?

**Comment by kblok** [comment]
WebSocket created on the server side, it's a chromium process.
I got this on Windows 10 and also on macOS Sierra.

I was on 2.1.0. I just downloaded the latest SDK, now `dotnet --version` returns 2.1.302.

Another thing. It only happens when I add a `await Task.Delay(3000);` between calls.  KeepAliveInterval is set to 60 seconds

**Comment by stephentoub** [comment]
I took a look at your repro.  Thanks for sharing it. I don't believe this is a breaking change; in fact, I don't believe there's a bug here in .NET Core; rather, there appears to be a bug in whatever code is being used to implement web sockets for chromium.

The exception is correct: the server is closing the connection.  And it's doing so immediately after the client sends a ping frame for the keep-alive interval, which in your repro is 30 seconds (you said 60 above, but it's actually getting set to 30).  So whatever code is listening on the chromium side is failing when ClientWebSocket sends a ping for the keep-alive interval and is closing the connection abruptly, which is why the client then gets an unexpected EOF and fails.

The reason you never saw this on 2.0 is that it used a different WebSocket implementation under the covers (it was based on WinHttp in 2.0 and is a managed implementation on top of SocketsHttpHandler in 2.1), and WinHttp appears to have a different notion of keep-alive: this is based purely on observation, but it appears to only send a keep-alive if nothing has happened in the last interval, so any send performed on the connection in that interval effectively resets the clock.  In 2.0, as with most of the ClientWebSocketOptions, the keep-alive interval was also ignored, so no matter what you provided, you'd always get the default 30 second interval from WinHttp.  You can see then that the aforementioned server behavior repros even on 2.0, by changing the repro code to wait for more than 30 seconds between attempts (i.e. change your `await Task.Delay(3000)` to be something like `await Task.Delay(40000)`... the next time you try to receive, it'll fail, because the ping sent by the client causes the server to close the connection.

You can even see this happening with a proxy like Fiddler:
```
18:04:26:3641 WSSession3.WebSocket'WebSocket #3'
MessageID:	Client.360
MessageType:	Ping
PayloadString:	
Masking:	5A-9B-6C-8C

18:04:26:3641 [WebSocket #3] Read from Server returned error: 0
```
The client sends a ping for keep-alive, and then its next read returns 0 unexpectedly.

I suggest following up with whatever vendor owns the web socket being used on the chromium side, as it's apparently not understanding / failing in response to pings.

**Comment by davidsh** [comment]
>WinHttp appears to have a different notion of keep-alive: this is based purely on observation, but it appears to only send a keep-alive if nothing has happened in the last interval,

The native Windows WebSocket stacks (WinHTTP, WinINet) don't send ping frames (but they will respond with pong frames if the server sends a ping frame). Instead, the stacks send unsolicited-pong frames to the server.

https://tools.ietf.org/html/rfc6455#section-5.5.3

```
A Pong frame MAY be sent unsolicited.  This serves as a  unidirectional heartbeat.  A response to an unsolicited Pong frame is not expected.
```

**Comment by kblok** [comment]
Thank you guys for the super quick response. I ran Fiddler locally and confirmed what @stephentoub said. As far as I read from you it seems that .NET is honoring the spec. 
I had this issue in the past (Core 2.0) when the connection needed to send a ping but I considered it a "temporary fail".

I'm creating an issue on Chromium. I'll let you know what I find.

**Comment by stephentoub** [comment]
In the meantime, since 2.1 does respect the keep alive interval you specify, you could try working around this by setting an infinite interval, in which case it'll never send pings.

**Comment by stephentoub** [comment]
> I'm creating an issue on Chromium.

Could you share the link?

**Comment by kblok** [comment]
>Could you share the link?

https://groups.google.com/a/chromium.org/forum/#!topic/chromium-discuss/nPiz9ukGJfo

Feel free to step in. I bet your insights will be super helpful.

**Comment by kblok** [comment]
@stephentoub closing this issue. They just said they don't support pings.
So I would need to set [keepAliveInterval](https://github.com/dotnet/corefx/blob/06aa6f0ce4cdf78985f029f218007a7d55f8965f/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L209) to TimeSpan.Zero.
