### ISSUE TITLE
Bring back Console.CancelKeyPress

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#311]
We need this so that we can wait on Ctrl + C events in console applications. See https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/Program.cs#L69.

**Comment by terrajobst** [comment]
[We've reviewed this proposal](https://github.com/dotnet/apireviews/blob/master/2015-01-14-misc/README.md#311-bring-back-consolecancelkeypress) and think it's a good addition. However, we haven't marked it as accepting PRs because we want to port the existing code from the .NET Framework. We'll resolve this issue when we ported the code.

**Comment by davidfowl** [comment]
Whats the state of this?

**Comment by ellismg** [comment]
Going to take care of this in the next few days.

**Comment by Praburaj** [comment]
@ellismg - is this available now?

**Comment by ellismg** [comment]
Sorry, been busy with other stuff.  Will try to get to this soon.
