### ISSUE TITLE
Investigate vectorizing Marvin

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#31195]
As discussed in https://github.com/dotnet/corefx/issues/30994 it may be possible to speed up GetHashCode by using intrinsics. If so this would help close the gap over the older implementation.

This would of course need careful perf measurements.

Note there are two copies right now, and that should probably be reconciled into one as part of (or before) this work: https://github.com/dotnet/corefx/issues/30748

cc @fiigii  @tannergooding

**Comment by danmosemsft** [comment]
cc @GrabYourPitchforks

**Comment by ViktorHofer** [comment]
Related to that we wanted to get rid of the Marvin class and incorporate its functionality into HashCode so that end customer can also benefit from it. cc @jkotas

**Comment by GrabYourPitchforks** [comment]
I investigated this previously, but one of the intrinsic properties of Marvin is that data early in the stream gets mixed with later data in the stream; this has a cascading effect on the resulting hash code. Serializing algorithms like this are inherently difficult to vectorize because.. well.. they're serializing, and vectorization is primarily meant for parallelization. Maybe there's something I missed previously when I investigated this, but I'm not holding out much hope here.

Regardless, even if we did vectorize it, the majority use case for String.GetHashCode() is for keys in a dictionary, and such keys are almost always under 256 bytes (16 wide chars) anyway.

**Comment by iSazonov** [comment]
I see comment in the code:

https://github.com/dotnet/corert/blob/87e58839d6629b5f90777f886a2f52d7a99c076f/src/System.Private.CoreLib/src/System/Marvin.cs#L120-L124

If it is possible to replace the three instructions with one we could get some gain.

**Comment by adamsitnik** [comment]
Please let me know if you need any help with benchmarking it

**Comment by danmosemsft** [comment]
@iSazonov I read that comment to mean that the JIT will currently do the replacement. You should be able to verify in the debugger.

**Comment by GrabYourPitchforks** [comment]
Vectorization seems out (for reasons discussed earlier), but we're in the process of making other improvements to Marvin that should speed it up in common cases. See also https://github.com/dotnet/coreclr/pull/19331 and https://github.com/dotnet/coreclr/pull/20309.
