### ISSUE TITLE
SocketsHttpHandler roots Timer - leads to higher memory usage

### ISSUE THREAD

**Issue by michaeljfarr** [dotnet/corefx#31262]
I have just discovered the cause of an annoying memory leak was that one of our libraries what creating a new HttpClient in every request and not disposing it (gaah).  When using WinHttpHandler, the cost was a few hundred managed bytes per HttpClient.  With SocketsHttpHandler, the cost was more like 22KB and some increasingly long TimerQueueTimer chains in HttpConnectionPoolManager (that showed up in the memory snapshot.

I have some suggestions to help detect/minimise such leaks in the future.  I couldn't really come up with anything solid, but hopefully, you can.

1. Do you think it would be possible for the DiagnosticsHandler or some other component to track the number of HttpClients instances and log a warning if the number gets above a certain level?  

2. Instead of creating an Infinite timer (see below), would it be better to just dispose the timer entirely when it isn't in use?  I'm not 100% sure why unreferenced handlers aren't being released from memory but this is probably holding the reference.  _cleaningTimer = new Timer(s => ((HttpConnectionPoolManager)s).RemoveStalePools(), this, Timeout.Infinite, Timeout.Infinite);  (I imagine there is a performance cost to this, but I am not sure how much)
               
3. Would it be ok for HttpMessageInvoker to have a Finalizer that tidies up the HttpMessageHandler (if _disposeHandler is true)?

hopefully, some of that is helpful, but I am not sure there is any proper solution to this other than just having everyone dispose their objects properly (or not create loads of HttpClients to begin with).  thanks ;-)

btw: for testing this my TargetFramework is netcoreapp2.1

**Comment by stephentoub** [comment]
> When using WinHttpHandler, the cost was a few hundred managed bytes per HttpClient. With SocketsHttpHandler, the cost was more like 22KB

The majority of WinHttpHandler's implementation is in native code, so it's allocating, it's just not showing in tracking of managed allocations.  Interestingly, even with all of SocketHttpHandler's allocations being managed, it common cases ends up having a better per-request allocation profile than does WinHttpHandler.

> some increasingly long TimerQueueTimer chains in HttpConnectionPoolManager (that showed up in the memory snapshot.

Can you share a repro?

> Do you think it would be possible for the DiagnosticsHandler or some other component to track the number of HttpClients instances and log a warning if the number gets above a certain level?

I think it'd be reasonable to add some tracing, either to SocketsHttpHandler or to DiagnosticsHandler, that raises events when an instance is created and when it's Dispose'd.  A consumer could then choose to subscribe to those events and do its own logic in response.  I don't think we're in a good position to pick a "level" and raise events only above that level... whatever level we picked, we'd get it wrong for someone.

> Instead of creating an Infinite timer (see below), would it be better to just dispose the timer entirely when it isn't in use?

This timer isn't rooted.  If you drop all of your references to the HttpClient, the Timer will similarly no longer be rooted and will become available for finalization.  If you're seeing otherwise, can you please share a repro?  It's of course possible there's a bug here, but my initial reaction is that most likely the finalizer just hadn't run yet.

> Would it be ok for HttpMessageInvoker to have a Finalizer that tidies up the HttpMessageHandler (if _disposeHandler is true)?

What would it do that's not already being done?  Finalizers shouldn't invoke Dispose on other managed objects, and everything the handler references that has stuff to be cleaned up should already have its own finalizers.

**Comment by michaeljfarr** [comment]
Hi Stephen.  Sure, I've added the repro project here (https://github.com/michaeljfarr/HttpClientCleanupRepro).  It is only built as an API because that is the usecase that I was diagnosing the original memory leak from, but it would probably make more sense as a simpler command line application now that I know what is going on.  If you look in Startup.cs, you will see a couple of comments asking you to run memory snapshots (it expects you to set a breakpoint and do it manually), that should help you pin down the situation immediately.  In the snapshot object diff you will see a few things that there are exactly 10 of (because that is how many undisposed HttpClients are created) like TimerQueueTimer and HttpClientHandler etc.  If you explicitly dispose the HttpClients, then those leaks do not occur.

Your comments at the end there are interesting, from that I would say the behaviour I see is unexpected.  I'm happy to explain further exactly what is happening, but I think you will quickly see just by using the repro.  Conversely, if you see how I can avoid the leak (without disposing the HttpClients), then please let me know.

I'm happy to tidy up the repro or write some explanations for what is happening.  Feel free to ask for anything like that, I should be able to get back to you right away.  Fortunately, in my case, the 3rd party library owners fixed up the issue straight away - so this isn't pressing for me personally, but I am keen to get this sorted for next time.

**Comment by stephentoub** [comment]
Tracking potential 2.1.x port

**Comment by danmosemsft** [comment]
@michaeljfarr if we back ported to 2.2 (expected release not far off) would you be able to upgrade to that? Or are you locked in to 2.1 indefinitely?

**Comment by michaeljfarr** [comment]
@danmosemsft I will be able to upgrade to 2.2, thanks ;-)

**Comment by stephentoub** [comment]
Fixed in 2.2 and 3.0.

**Comment by karelz** [comment]
Thanks @stephentoub!
