### ISSUE TITLE
Support an optional exception handler in TelemetryListener/TelemetrySource

### ISSUE THREAD

**Issue by Kieranties** [dotnet/corefx#3135]
I've been playing around with the new `TelemetryListener`/`TelemetrySource` classes and have found them to be a great fit for a simple eventing pattern.

However an unexpected impact on firing `WriteTelemetry` was that if a subscriber fails, no subsequent subscribers will have their `OnNext` method called.  From reading the various comments - particularly @vancem's https://github.com/dotnet/corefx/pull/2932#issuecomment-134328582 - on the PR I understand that this stems from how RX approaches exceptions, yet in the case of telemetry and multi-cast events it seems like there will be many cases where one broken subscriber shouldn't bring the system down.

Would it be possible to consider an overload to `WriteTelemetry` which looks like this:
``` c#
public override void WriteTelemetry(string telemetryName, object arguments, Func<Exception, bool> exHandler)
{
    for (TelemetrySubscription curSubscription = _subscriptions; curSubscription != null; curSubscription = curSubscription.Next)
    {
       try
       {
           curSubscription.Observer.OnNext(new KeyValuePair<string, object>(telemetryName, arguments));
       }
       catch (Exception ex)
       {
           if (!exHandler(ex))
           {
               break;
           }
       }
    }
}
```

This would then support calls that would allow the sender to pass a function that can evaluate for each exception if the calls should continue:
``` c#
source.WriteTelemetry("Send", o, ex => !(ex is CatastrophicException) );
```

Alternatively an approach could be considered that uses `AggregateException` that simply collects all exceptions and throws them collectively at the end.

**Comment by vancem** [comment]
As you already know, we are ambivalent on the point of whether errors in Observers should be caught or not.   Currently we resolve this opting for simplicity (less code), which is to not catch.   

I don't really see how another overload helps, as the sender really does not want to be involved.   Really our current strategy is that it is really part of the contract of an observer to not throw exceptions and if they do it is considered catastrophic (thus we don't care what happens after that). 

What would help move the conversation is more information where it is unreasonable to expect listeners to uniformly achieve this bar, and thus inject random failures.    There really is ALOT of trust going on here, because listeners can MODIFY the data handed to them, which frankly they should not be doing (but we can't prevent them).     Thus 'Don't throw' is just one more requirement on Listeners.  

If you can supply interesting examples where this is not true that would be helpful.

**Comment by Kieranties** [comment]
@vancem Thanks for the response, I'll continue investigating and see what I can come up with

**Comment by Kieranties** [comment]
> Really our current strategy is that it is really part of the contract of an observer to not throw exceptions and if they do it is considered catastrophic (thus we don't care what happens after that).

This is the crux of the issue for me.  If the data sent causes a catastrophic error for a single observer, that error impacts all other observers.  What is catastrophic for one observer may not be catastrophic for all.

By providing the overload the sender can choose if it wants to be involved, evaluating each exception and deciding if it wants to continue the chain of notifications.  A lot of trust is placed on the observers, but some of that can be pulled back and managed safely using the overload.

An overload on the base class itself may not be the best way to go about this, but as the implementation of `TelemetryListener` has private classes and variables handling the subscriptions, it cannot be introduced without reimplementing the entire class and providing an isolated listener.

**Comment by vancem** [comment]
As mentioned, I hearing about particular cases where you can't trust observers not to throw exceptions would be the most helpful in moving the conversation further.    Keep in mind that this API is really not an generic producer-consumer model.  It is really designed for rich telemetry (hence its name).  Thus the number of consumers (rich telemetry consumers) is supposed to be low (I can count them on my fingers), and frankly have incentives to be as 'invisible' as possible.  

My current belief is that if we want to insure that observers can't accidentally throw exceptions we should not add another overload (I would not know how to tell people when to use which one.  Under what conditions does the SENDER know that he does not want to see exceptions?   Presumably ALL the time, so why not make the exception catching unconditional?).   For me that is the question.  

Putting in the catch clause makes the code less efficient (try blocks do have a cost), and is likely to be redundant (since listeners really should be catching exception AND logging that something went wrong).    

Now if this API was going to be by everyone, I would be more inclined to sacrifice efficiency for safety since larger number guarantee that someone will make a mistake.  However the number of clients will be quite small, so again it is unclear, and again I am left with ambivalence that I resolve by keeping it simple (do no harm)....

**Comment by karelz** [comment]
Seems to be concluded (or at least without further discussion), so closing.

@Kieranties feel free to reopen if you disagree.
