### ISSUE TITLE
SslStream KeyExchangeAlgorithm issues on Linux

### ISSUE THREAD

**Issue by samdearden** [dotnet/corefx#31420]
We have a server application running in a Docker container (using the microsoft/dotnet:2.1-sdk container image) on linux that uses TcpListener to accept connections from client applications on a socket. We are using SslStream to secure the connection with a server certificate using SslStream.AuthenticateAsServer.

We have a requirement to ensure that connections are made with a Key Exchange algorithm that provides forward secrecy. Running OpenSsl commands from the console of the container shows that PFS ciphers are at the top of the priority list. 

When calling SslStream.AuthenticateAsServer and passing SslProtocols.None in the enabledSslProtocols behaviour the KeyExchangeAlgorithm is negotiated to RsaKeyX (which does not provide forward secrecy). The same behaviour is observed if we use an overload without the enabledSslProtocols parameter. 

If when calling SslStream.AuthenticateAsServer setting the enabledSslProtocols to all values of the SslProtcols enumeration (e.g. bitwise OR of Ssl2, Default, Tls11, Tls12) then the KeyExchangeAlgorithm is negotiated to ECDHE as expected (an algorithm providing forward secrecy).

When running on the application on a Windows operating system, usage of SslProtocols.None (or the overload without the enabledSslProtocols parameter) correctly negotiates ECDHE as the key exchange algorithm.

Example code attached (a small client and server) that replicates the issue. 
[SSL Stream Negotiation.zip](https://github.com/dotnet/corefx/files/2235790/SSL.Stream.Negotiation.zip)

**Comment by davidsh** [comment]
Using 'SslProtocols.None` implies the use of the OS's "default" set of TLS protocols, ciphers, etc.  It is possible that on some Linux OS's, the default set doesn't include cipher suites that use Key Exchange algorithms with forward secrecy.

`SslProtocols.None` doesn't mean use the "strongest".  It simply means use the OS default set.

**Comment by davidsh** [comment]
cc: @bartonjs @wfurt - please comment on this.  Not sure if this is really a bug in .NET Core code or just how OpenSsl works.

**Comment by bartonjs** [comment]
Looks like a bug.

https://github.com/dotnet/corefx/blob/30148bf4a56ea5dc934893f8b87367ff221014a6/src/Native/Unix/System.Security.Cryptography.Native/pal_ssl.c#L70-L110

The early return means it doesn't call `TrySetECDHNamedCurve`.

I'd just move the ECDH init code to above the protocols part (and early-return-if), instead of having it at the end.  And, of course, check that the managed code doesn't skip the call when it's None.

Since we serviced ECDH init into 2.0, we should probably service this into 2.1 (but not 2.0, since it's near End of Life).

**Comment by davidsh** [comment]
cc: @danmosemsft - possible 2.1.x servicing

**Comment by karelz** [comment]
@samdearden is it a regression against .NET Core 2.0 or earlier verion?

**Comment by samdearden** [comment]
@karelz same issue on .NET Core 2.0

**Comment by bartonjs** [comment]
@karelz this issue is that the servicing fix for 2.0 was bad.  If the users follow our guidance and have no preference on the TLS protocol (SystemDefault) they don't get perfect forward secrecy ciphersuites (ECDHE).  If they restrict the TLS protocol versions in any way then they get it, as an artifact of the enabler being on the wrong side of an early return.

**Comment by karelz** [comment]
> @bartonjs the servicing fix for 2.0 was bad

Is there bug/PR associated with the "bad servicing fix in 2.0"? (Just to track what introduced the regression - assuming I understand it correctly and it is a regression against 1.x)

**Comment by bartonjs** [comment]
The regression is just "from Windows" / "from NetFX" / "we have bad security".

https://github.com/dotnet/corefx/pull/26147 / https://github.com/dotnet/corefx/issues/24648

**Comment by karelz** [comment]
Fixed in release/2.1 branch in PR #32034. Will be part of 2.1.5 release.
