### ISSUE TITLE
Cannot build System.Collections.Concurrent.Tests in Visual Studio 2015

### ISSUE THREAD

**Issue by DixonDs** [dotnet/corefx#3150]
I get the following error:

    xunit.abstractions 2.0.0 is not compatible with DNXCore,Version=v5.0.

Any suggestions or work-around?

**Comment by stephentoub** [comment]
@DixonD-git, are you still hitting this?  I just tried, and it's working fine for me.  I sync'd to the latest source in the repo, opened the System.Collections.Concurrent.sln solution, did a full build, and both projects build successfully for me.  If you're still having trouble, what steps are you following?

**Comment by DixonD-git** [comment]
Yes, I'm still experiencing it. But now I see my mistake in the issue description: build succeeded even though I still see the mentioned error in Error List. I'm using Visual Studio 2015 Community if that matters. I've raised this issue to xUnit guys at https://github.com/xunit/xunit/issues/587, they say that it should be some issue with Visual Studio 2015 itself.

**Comment by mellinoe** [comment]
Yeah, this seems to be some issue with VS, or maybe just its error list. The errors show up, but the build should still succeed.

**Comment by Clockwork-Muse** [comment]
@DixonD-git - Perhaps you should update the issue title?  Since this appears to be affecting just about everything, and doesn't block builds.

**Comment by ericstj** [comment]
This is the same issue as https://github.com/dotnet/corefx/issues/4448.  The problem is that Xunit doesn't explicitly support DNXCore50.  Instead it relies on some logic in DNX that considers portable-net45+win8 as compatible.  This is why our commandline build works.

When you open the project in VS 2015 the inbox NuGet extension uses the NuGet restore code to restore the project prior to build.  The NuGet codebase is missing the logic I mentioned above.  The workaround is to explicitly declare that you want the DNXCore50 project to permit installation of portable-net45+win8 packages, as I mentioned in the linked issue.

Long term I want us to move away from pretending to be DNXCore50 libraries as I mention in this issue: https://github.com/dotnet/corefx/issues/2427

I'm seeing more and more reasons to do this recently so I might just pull the trigger and do the rename/refactor.

**Comment by mellinoe** [comment]
I'm not even seeing the "fake error" at this point, anymore. Lots of things have changed since this was filed, and the project should build completely cleanly at this point. Make sure you have the [corefx build prereqs](https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md#required-software) installed, and you shouldn't have any issues.
