### ISSUE TITLE
Using Microsoft.Win32.Registry on a .NET Standard extension

### ISSUE THREAD

**Issue by jp2masa** [dotnet/corefx#31516]
Related to #24483, but I think it isn't clear enough.

## Scenario
There are both a .NET Framework and .NET Core applications which are extensible, and provide the extensibility APIs as one or more .NET Standard assemblies. One of the extensions, which targets .NET Standard, uses `Microsoft.Win32.Registry`, which is expected to work, but it fails on the .NET Framework application with `PlatformNotSupportedException`, as the facade didn't ship with the extension.

Is this scenario unsupported? If so, is there a workaround? I think that this totally breaks the purpose of .NET Standard, by forcing the extension to know the target runtimes when building.

**Comment by danmosemsft** [comment]
Maybe @safern has an idea

**Comment by safern** [comment]
> s this scenario unsupported? If so, is there a workaround? I think that this totally breaks the purpose of .NET Standard, by forcing the extension to know the target runtimes when building.

@jp2masa I need to know more detail about your scenario. How are you distributing your libraries? Are you producing NuGet packages or just sharing the published library output and referencing the assembly directly? How are you building them? Are them in a public repo I could take a look? 

The more information you share the better I can understand the scenario and that way I can guide you to the right path or fix it if it was a bug in our side.

**Comment by safern** [comment]
> .NET Core understands the dependency graph, so it loads the correct assembly.

I was able to repro and by looking at your case I think you're skipping one layer of letting the runtime/nuget do the dependency graph resolution. 

> .NET Framework doesn't, so it uses the assembly shipped with the library, which causes it to fail. This means that Microsoft.Win32.Registry doesn't really support .NET Standard.

`Microsoft.Win32.Registry` do support .NET Standard, however it is a runtime/target framework specific package, and here you're producing a .NET Standard layout by publishing it (non-target, non-runtime specific) and loading the assembly manually, this is not the way the standard works. Since .NET Framework has all this types defined already mscorlib we can't use the .NET Standard implementation as it will conflict when doing type resolution, so we need to include a framework and runtime specific implementation for net461-windows that only has typeforwards of the defined types in the .NET Standard reference assembly to mscorlib, so that our type resolver can find the implementation when running in .NET Framework. 

The main problem here is that you're bypassing all this resolution by publishing the Library for netstandard2.0 and trying to load the assembly and calling APIs via reflection. 

The way you should use a netstandard2.0 application to be able to correctly run in multiple frameworks (mono, netcoreapp, full framework, uap) would be by adding a ProjectReference to your .NET Standard application OR by creating a nuget package that depends on `Microsoft.Win32.Registry` and then referencing that Library NuGet package in the applications that want to use it and the dotnet sdk with nuget will resolve the right dependencies for you depending on the target framework and the runtime you're on. 

I just tried the ProjectReference approach and doing dotnet publish, and consuming the .dll from the net471\publish\ folder and it works as expected.

Also, your library would be easier to consume, no need of doing Assembly.Load and calling API through reflection. 

I also noticed you're using 4.4.0 package, I suggest using the 4.5.0 package which is the latest.

**Comment by jp2masa** [comment]
I didn't notice that the implementation was being published for the `win` runtime. So it's correct that `Microsoft.Win32.Registry` supports .NET Standard, but it's runtime specific. .NET Core knows how to find runtime specific assets, while .NET Framework doesn't, and that's the real issue here. That was always a problem, which I hit many times, but it's understandable. Thanks for the help!
