### ISSUE TITLE
Could CurlHandler support UNIX sockets?

### ISSUE THREAD

**Issue by markrendle** [dotnet/corefx#3153]
There is support in `libcurl` for using UNIX sockets instead of TCP (http://curl.haxx.se/libcurl/c/CURLOPT_UNIX_SOCKET_PATH.html).

In a microservice world, this capability is very useful for communication between discrete services on a single server, reducing the overhead of TCP sockets and improving performance.

As a precedent, the Kestrel HTTP server now supports UNIX sockets, which Nginx can consume when reverse-proxying (see https://github.com/aspnet/KestrelHttpServer/pull/157).

I took a quick look to see if I could implement this, but there doesn't seem to be a point where a socket file path could be added in, so I opted for starting a discussion instead. :open_mouth:

**Comment by davidsh** [comment]
cc: @vijaykota @pgavlin @stephentoub

**Comment by stephentoub** [comment]
Thanks, @markrendle.  I think this would be a nice addition, at some point.

As of right now, CurlHandler is internal, backing the concrete and public HttpClientHandler.  Our initial plans for release were to not expose CurlHandler as a type publically, which means there's little opportunity to expose additional knobs.  However, the implementation has tried to maintain an implementation separation between HttpClientHandler and CulHandler, with an instance of the former wrapping an instance of the latter, because we have been considering the future option of exposing CurlHandler if/when we want to expose such additional settings.  WinHttpHandler does this same thing: HttpClientHandler wraps one internally, but WinHttpHandler is also available as a public type in order to let one configure additional knobs not exposed on the default.

We should maintain a list of the additional functionality that should be exposed, and once we're to the point of being happy with the core implementation, consider exposing the type publically to add additional configuration.  At that point, such support for UNIX domain sockets would make a lot of sense, and be easy both to expose (a property or method on CurlHandler) and implement (calling the underlying libcurl function based on the data set).

**Comment by markrendle** [comment]
@stephentoub Thanks for the detailed response!

**Comment by stephentoub** [comment]
Thanks for starting the discussion, @markrendle.  I'm going to close this issue and let #3185 track it, as it'd be a prerequisite to this and this would be one of the inspirations for doing it.
