### ISSUE TITLE
Can we determine if a FileSystem is case sensitive or not through an API?

### ISSUE THREAD

**Issue by troydai** [dotnet/corefx#3156]
I'm exploring the possibility of making our cross-platform file globbing to determine if it acts as case sensitive or not based on current file system. It can't be determined just by the current operating system since case insensitive file system can still be mounted on Linux/Unix/Darwin. Is there an API can help to determine if a file system at given path is case sensitive.

**Comment by stephentoub** [comment]
Unfortunately, no: https://github.com/dotnet/corefx/issues/1086

**Comment by stephentoub** [comment]
(Hmm, upon rereading the issue I linked to, it's about getting the actual casing of a path.  I was sure we had an issue about an API for getting the case sensitivity of the current file system... not sure what happened to that one, but I guess we can use this issue in its place.) cc: @sokket, @ellismg

**Comment by sokket** [comment]
@stephentoub I thought we had an issue too but I couldn't find it either. I know we discussed this when dealing with the FileSystemWatcher but pushed it out later due to complexities around mount points with different underlying File Systems mounted anywhere. This seems like it might be a fit for an API discussion to figure out if we want to provide an API to determine if the given path is case sensitive.

**Comment by nguerrera** [comment]
cc @JeremyKuhne

**Comment by yishaigalatzer** [comment]
This will be very useful for us as well. I'd like to see an API that take a folder, because the cases where have heard about are:

1. Windows machine with a samba share
2, Linux machine with a folder mounted to a window share
3. Mac + mount points to either case sensitive or case insensitive drive.

I would expect such an API to be reasonably fast with some sort of caching if needed so it can be called multiple times without a major penalty, and if not properly document it on the API so it is clear if the consumer is required to cache.

**Comment by karelz** [comment]
Related to #1086.

**Comment by JeremyKuhne** [comment]
#1086 should handle most people's needs.

In this case we need something similar to `DriveInfo` but available for any path. Perhaps `VolumeInfo`.  In Win32 you need to use Volume Management APIs such as [GetVolumeInformation](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364993) to find the relevant file system info (which `DriveInfo` already utilizes for some of it's functionality, but doesn't give you the ability to use anything other than a root path- you would have to figure out where mounted folders actually point to).

If someone can pull together the necessary APIs on the Unix/MacOS side then we can move forward with this. For now I'll close in favor of #1086. Please feel free to reopen if you can drive this issue forward.
