### ISSUE TITLE
Consider exposing the underlying byte array for the DebugDirectoryBuilder

### ISSUE THREAD

**Issue by cshung** [dotnet/corefx#31622]
It will be useful for generating portable pdb using Cci.

**Comment by tmat** [comment]
Looking at your code again, it seems that you couldn't use the raw debug directory blob since you need to return PeDebugDirectory instance.

You could use the raw bytes of code view entry. I'm not sure that's worth a public API though - it would only save you this line: `byte[] data = signature.Concat(guid).Concat(age).Concat(path).Concat(nullterminated).ToArray();`.

**Comment by cshung** [comment]
I agree, the value is too low to worth a public api, closing this issue.
