### ISSUE TITLE
Distributed tracing and the new Activity class - How to make it Just Work

### ISSUE THREAD

**Issue by lukepuplett** [dotnet/corefx#31692]
I've been reading source code on GitHub for hours and it seems there's a whole load of stuff hiding away for making request tracing through .NET Core apps/microservices, and I'm guessing Azure PaaS, "Just Work".

The new `Activity` class is created and started and the request is added, parent-child is chained, hierarchical correlation IDs are generated and flowed to subsequent requests via `Request-Id` and baggage is flowed automatically via `Correlation-Context`, or so it seems, by handlers in the HTTP client and in SQL bits, I see.

(Assumes the code I'm looking at is RTM. Maybe it isn't.)

Examples are given in the Activity User Guide, but actually seems to be implemented in .NET Core code, so the guide seems more for other framework authors..?

However what I can't find is the part where those headers are picked-up off the request and flowed into a new `Activity`, how it relates to the `httpContext.TraceIdentifier` and well, why our .Net Core 2.1 services don't seem to just work.

We have a dozen Core services on Service Fabric, do we need to do anything to hook all this up? Is this just gonna work in 2.2? And if so, can we do anything in _anticipation_ of this good work?

Thanks.

**Comment by karelz** [comment]
cc @vancem @brianrob @valenis

**Comment by lukepuplett** [comment]
cc @lmolkova

**Comment by lmolkova** [comment]
@lukepuplett 

This code is RTM since .NET Core 2.0. 

Two pieces of code that actually read incoming headers and create an Activity to track incoming requests are implemented in 
- ASP.NET Core https://github.com/aspnet/Hosting/blob/master/src/Microsoft.AspNetCore.Hosting/Internal/HostingApplicationDiagnostics.cs (from 2.0)
- ASP.NET Classic https://github.com/aspnet/Microsoft.AspNet.TelemetryCorrelation
 there are two more for EventHubs and ServiceBus .NET SDKs

Activity is not related to the TraceIdentifier, tracing identifier is created before Activity tracing starts and we are still thinking about how to accommodate it better.

Tracing lights up in presence of listeners for the DiagnosticSources and without listeners is noop. The easiest way to enable it is to install ApplicationInsighs. It also supports ServiceFabric (you might need to do some extra config as described here https://github.com/Microsoft/ApplicationInsights-ServiceFabric) 

You may use another tracing system/lib or implement your own diagnostics listeners for particular sources. You may use ApplicationInsights code as an example ([HttpClient Core](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/HttpCoreDiagnosticSourceListener.cs) [ASP.NET Core](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs)). LEt me know if you have any questions

**Comment by lukepuplett** [comment]
Thank you for this, and thank you for your answer on SO.

https://stackoverflow.com/questions/51749071/diagnosticsource-diagnosticlistener-for-frameworks-only

Your answer implies that an SF application comprising all .NET 2.1 Reliable Services should automatically add a `Request-Id` header to outbound requests, as per code in:

corefx/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs 

It should also read and flow this header at the receiving end, using the hierarchical format - unless possibly the SF host means that `HostingApplicationDiagnostics` isn't used.

And that this will only happen when something is subscribed to the listener, source, thing. So as soon as we add AI, it'll light-up.

We'll do a spike :)

**Comment by noahfalk** [comment]
This issue has been quiet for a long time, so I'm making the optimistic assumption it has been resolved : ) If that is not the case please re-open it or file a new issue. Thanks!

**Comment by davidfowl** [comment]
It’s not but we’re investing in this very issue in 3.0
