### ISSUE TITLE
Relative Uri can not get Query

### ISSUE THREAD

**Issue by MJEdwin** [dotnet/corefx#31757]
Uri uri=new Uri("/cgi-bin/customer?abc=1",UriKind.Relative);
string query=uri.Query; //throw InvalidOperationException:This operation is not supported for a relative URI.

**Comment by davidsh** [comment]
What version of .NET Core are you using?

**Comment by davidsh** [comment]
cc: @rmkerr

**Comment by davidsh** [comment]
.NET Framework behaves the same way.  There are many properties of Uri that throw that exception if the Uri is `UriKind.Relative`.  The reason is that different parsing rules can apply to various Uri schemes and 'Query' is not something that applies to all schemes.

As you can below, many properties will have that exception if the Uri is relative:

![image](https://user-images.githubusercontent.com/7684835/44103165-5ade2626-9fa0-11e8-9ddc-92b37697b3ca.png)

**Comment by davidsh** [comment]
Since the behavior is by-design, we'll close the issue.
