### ISSUE TITLE
Exposing internal virtuals involving searching a key in DataView

### ISSUE THREAD

**Issue by Anipik** [dotnet/corefx#31764]
# Rationale 
Winforms require DataTable.AsDataView extension methods. They uses ``` LinqViewData ``` datatype which override some internal virtuals like 
```c#
internal virtual int FindByKey(object key);
internal virtual int FindByKey(object[] key);
internal virtual DataRowView[] FindRowsByKey(object[] key);
internal virtual void SetIndex(string newSort, DataViewRowState newRowStates, IFilter newRowFilter);
```

So we need to expose these apis and constructor.

# Api Proposal
ctor
```c#
protected DataView(DataTable table, System.Predicate<DataRow> predicate, System.Comparison<DataRow> comparison, DataViewRowState RowState);
```

Methods
```C#
protected virtual int FindByKey(object key);
protected virtual int FindByKey(object[] key);
public virtual DataRowView[] FindRowsByKey(object[] key);
public virtual void SetIndex(string newSort, DataViewRowState newRowStates, IFilter newRowFilter);
public Range FindRecords<TKey, TRow>(Index.ComparisonBySelector<TKey, TRow> comparison, TKey key) where TRow : DataRow { throw null; }
public Predicate<DataRow> RowPredicate { get { throw null; } set { } }
public DataRowView[] GetDataRowViewFromRange(System.Data.Range range) { throw null; }
public ComponentModel.PropertyDescriptor GetSortProperty() { throw null; }
public ComponentModel.ListSortDescriptionCollection GetSortDescriptions() { throw null; }
public System.Comparison<DataRow> SortComparison { get { throw null; } set { } }
```
```C#
public interface IFilter {}

public sealed class Index
{
    public delegate int ComparisonBySelector<TKey, TRow>(TKey key, TRow row) where TRow : DataRow;
}
public struct Range
{
    public Range(int min, int max) { }
    public int Count { get { throw null; } }
    public bool IsNull { get { throw null; } }
    public int Max { get { throw null; } }
    public int Min { get { throw null; } }
}
```

# Behavior

https://referencesource.microsoft.com/#System.Data.DataSetExtensions/System/Data/LinqDataView.cs,18

# implementation
https://github.com/Anipik/corefx/tree/debugAssert

Related Issue:- https://github.com/dotnet/corefx/issues/27610

cc  @danmosemsft @ericstj  @JeremyKuhne @divega @keeratsingh 

# Note Explaining Why

https://github.com/dotnet/corefx/issues/27610#issuecomment-410090277

**Comment by danmosemsft** [comment]
@Anipik can you briefly add a note explaining why you have concluded we have to make these public? The thread with @ericstj

**Comment by Anipik** [comment]
I added the eric comment in the description

**Comment by JeremyKuhne** [comment]
> I added the eric comment in the description

Please link to the comment directly.

**Comment by ericstj** [comment]
I take it that this is just a precursor to exposing these in netstandard?  Technically you could do it without new public api if you push the types down on netcoreapp.

**Comment by Anipik** [comment]
> Technically you could do it without new public api if you push the types down on netcoreapp. 

i didnt understand that. can you please  explain a little bit more ?


> I take it that this is just a precursor to exposing these in netstandard?

yep

**Comment by ericstj** [comment]
Imagine the implementation of DataTableExtensions (and its closure) was typeforwarded to the same assembly as DataView. It wouldn’t need those virtuals to be public since it could override them from the same assembly.  Granted you still wouldn’t be able to do this in a netstandard implementation, only for netcoreapp.  That’s the same as this in a way, since you can only add this API to netcoreapp.  I bet pushing the types down is a much larger change than this but it’s possible if you really don’t want to make that API public.

**Comment by Anipik** [comment]
Thanks for the info.
So  whts the final decision here ?
should we made them public or add typeForwards to DataTableExtensions ?

**Comment by ericstj** [comment]
I think making public (actually protected unless there's a good reason for public) is better since it preserves the type factoring/architecture.  I think you'll need to examine if making that change is the correct thing for the API and doesn't cause any harm or confusion for its existing use cases.  Typically we try to go over that sort of thing in the API review process.  If it passes that test then we go with it.  If not then you fall-back to the moving-types approach.

**Comment by danmosemsft** [comment]
@Anipik can these be protected rather than public?

@keeratsingh do you have any concerns about exposing these? It does seem less ugly and more correct than internalsvisibleto, but it's not our type.

**Comment by Anipik** [comment]
we can make both the properties and ctor protected. There shouldnt be any issue with that. i will test the changes in the local branch and let you know, if i face any other problems.

**Comment by keeratsingh** [comment]
@danmosemsft I believe @divega would be the better person to answer this question since he has more API related insight than I do.

**Comment by Anipik** [comment]
@danmosemsft we can make everything protected except ```setIndex```. It is being used in other classes which doesnot inherit the dataview. 
https://github.com/Anipik/corefx/commit/1a1b4ef3eb050a695a8f95c6eff68bf8985a18dc
and we have to make ```Ifilter``` interface public

**Comment by danmosemsft** [comment]
I suggest renaming `IFilter` to `IDataRowFilter` in the proposal. `IFilter` is much to generic a name to make public. We try to make type names unique in System.* (at least we try)

**Comment by Anipik** [comment]
@danmosemsft I have updated the issue with all the classes and methods. I also linked to the implementation branch.

**Comment by danmosemsft** [comment]
I think this is going to be too much new API to expose just for this purpose.

What I suggest is 
1) we just implement `AsDataView` directly onto `DataTable`. That helps new compilations. Even if the extension method is visible, the compiler will prefer it on the type. We don't need a new configuration -- it builds for netcoreapp already.
2) we add a netcoreapp configuration of System.Data.DatasetExtensions.dll, and on that, we add AsDataView implemented as a call to the method we added in (1). That helps existing built binaries that expect to find it on DataSetExtensions. We need a new configuration because when building a net standard library, the library will be consuming DataTable in its net standard state, and the implementation won't be there.

This implies that it will probably become part of .NET Standard in due course, which seems fine.

@weshaggard does this seem right.

**Comment by weshaggard** [comment]
@danmosemsft that sounds reasonable and should work if we feel this one method is work the hassle.

**Comment by Anipik** [comment]
@danmosemsft did you mean that we expose 
AsDataView method in System.Data.Common as well as in system.Data.DatasetExtensions ?

**Comment by Anipik** [comment]
@weshaggard @danmosemsft @ericstj  
there is a AsDataview extension function on EnumerableRowCollection<T>. This class is present in System.Data.DatasetExtensions. what should we do about that ?

**Comment by Anipik** [comment]
There are 2 options left here 

- We can proceed with @danmosemsft  suggestion plus moving EnumerableRowCollection to S.D.C and adding typeforwards for this class in S.D.DSE.
- Moving both the EnumerableRowCollection and DataTableExtension methods to S.D.C and adding typeforwards for both the classes in S.D.DSE. In this case we will only need to expose the AsDataView as an extension method.
LMK in which direction should i proceed

cc @weshaggard @ericstj

**Comment by weshaggard** [comment]
@Anipik do you have any any sense of what all would need to be pulled into S.D.C in both of those options? Would it be all of S.D.DSE? If so do we know how much of a binary size increase that causes?

If both options end up with close to the same moved into S.D.C then I would go with option 2 so we remain essentially the same from the public surface area standpoint and we don't need to add any new instance members on DataTable.

**Comment by Anipik** [comment]
> Would it be all of S.D.DSE? If so do we know how much of a binary size increase that causes?

I will try it and let you know how much stuff we need to pull into S.D.C

**Comment by Anipik** [comment]
@weshaggard we need to move 
System\Data\DataTableExtensions.cs
System\Data\EnumerableRowCollection.cs
System\Data\SortExpressionBuilder.cs
System\Data\DataSetUtil.cs

for exposing both the overloads of AsDataView function

**Comment by weshaggard** [comment]
Does it add any more dependencies? If not I suspect it is probably fine to proceed with moving them.

**Comment by Anipik** [comment]
No It didn't require to add any more dependencies

**Comment by weshaggard** [comment]
To add a little more detail the approach of moving those types into System.Data.Common would only work for .NET Core and would still block us from supporting them in .NET Standard. We would end up having to duplicate those types in both libraries and condition them appropriately for the different configurations. So the value add verse the complexity doesn't seem to be worth the cost of adding these at this point. We can consider adding them in some way to .NET Core only in the future if there is enough need.
