### ISSUE TITLE
.Net regex parser incorrect on patterns like `[b-\-a]`

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/corefx#31786]
Full conversation here: https://github.com/dotnet/roslyn/pull/23984/files/13563a78d575941cffc35d659b0ad17da414426b#diff-5bf37f67cacf636edb343fc847ae96e3

Based on the .net regex specificaiton, this should be a character class with two sections.  The first is the range "`b` through `\-`".  The second is `a`.   However, the .net regex parser treats this as equivalent to the range `[b-a]` (which it incorrectly reports as an errors since 'a' is less than 'b').

You can see the full analysis of why this happens in the conversation i linked above.  From talking to @ViktorHofer it is believed to be a bug, and it is highly likely it is safe to fix without breaking any existing clients.

**Comment by ViktorHofer** [comment]
Thanks for opening an issue for that. It must have slipped under my radar and I forgot to open one. I won't have time to fix it in the near future because of resources but the issue will remind me to look into it. If you want to, you could also take a look and try to fix it.

**Comment by pgovind** [comment]
Just adding a note here that `ParseRegexNode`(which is where the exception is thrown) uses a `SingleRange` internally and has some functions to collapse ranges. This makes it a good candidate for https://github.com/dotnet/corefx/issues/40988

**Comment by CyrusNajmabadi** [comment]
@pgovind I'm not sure what that has to do with this particular incorrect-parsing bug.  Thanks!

**Comment by pgovind** [comment]
It doesn't have anything to do with this bug. The note was for me to track real use cases for an IndexSet type. 
I spent about an hour or so debugging this and understand what, why and where the bug is. When I have some time later this/next week, I'll look into fixing this. On the face of it, it looks like `ParseRegexNode` might need a local fix. Assigning myself to it :)

**Comment by pgovind** [comment]
Just for my edification, are we certain that this is a valid pattern? I can see that we're treating it as the range `[b-a]` instead of `[b-\-]` and `[a]`, but isn't `[b-\-]` also invalid? In ASCII, that seems to be range [98 - 45]. Trying it on regex101 with PCRE set, I get this error:

_Character range is out of order_

**Comment by CyrusNajmabadi** [comment]
> also invalid?

Not from a parsing perspective.  Regardless, you'll see the same problem if you try with characters that are numerically in order.  The root of the issue is about the parser getting confused about the escaped `-`.

**Comment by pgovind** [comment]
Ah, I should've clarified my question. Never mind now. I put up a fix for it here: https://github.com/dotnet/runtime/pull/1075.
