### ISSUE TITLE
UriBuilder from local path fails on Mac

### ISSUE THREAD

**Issue by odhanson** [dotnet/corefx#31796]
Hi. 
When I call the following UriBuilder constructor on windows:

UriBuilder b = new UriBuilder("c:\\test\\test.bin");

I get the correct result of: b={file://c:/test/test.bin}

However on Mac, if I call
UriBuilder b = new UriBuilder("/test/test.bin");

It throws the following exception:
System.UriFormatException: "Invalid URI: The hostname could not be parsed."
  at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)\n   at System.Uri..ctor(String uriString)\n   at System.UriBuilder..ctor(String uri)\n   at Uri.Program.Main(String[] args) in 

I would have expected: b={file:///test/test.bin}

**Comment by davidsh** [comment]
cc: @rmkerr

**Comment by odhanson** [comment]
Thanks. The problem is actually in Uri. It seems like it doesn't detect it as an AbsoluteUri.

**Comment by rmkerr** [comment]
The problem stems from the fact that URIs aren’t really designed to support Unix native file paths. In this case, it is ambiguous whether you are trying to create an absolute Unix-style file path, or a relative path that will later be combined with an absolute path. Historically this wasn’t an issue because Windows absolute file paths always start with a drive name – eg ‘c:\’ and so the established behavior is to interpret a URI that starts with a ‘/’ as a relative path. Relative paths don’t make sense in the context of UriBuilder, and so an exception is thrown. Changing this behavior would have _huge_ potential to break existing apps.
 
The most effective workaround will probably be to prefix your file paths with the ‘file:/// ‘ scheme. This makes it clear that you want an absolute file path rather than a relative path. If that doesn’t help just let me know, and I’m sure we can find something workable.

Since there is no plan to change this behavior and we have a workaround, I am going to close this issue.

**Comment by rmkerr** [comment]
@jkotas Yes, that suggestions does consistently work. It is also possible to simply add the scheme on to the beginning of a string you know contains an implicit file path:
```csharp
new Uri("file://" + localPath);
```
We could probably improve the experience with a new API, but there is still inherent ambiguity with implicit file paths on Unix. It just isn't clear whether "/home/foo/README.md" is a relative or an absolute path. The developer has to know in advance what they want, because there is not enough info for us to make a decision.

I think that the best we could do is add support for choosing whether we default to interpreting a path like that as a relative path or an absolute path. I could always be missing something though -- any suggestions on how to improve would be welcome 😄

**Comment by jkotas** [comment]
> It just isn't clear whether "/home/foo/README.md" is a relative or an absolute path

This is always absolute path on Unix. Why is there an ambiguity?

**Comment by danmosemsft** [comment]
Is the `new Uri(string uriString, UriKind uriKind);` constructor also an option? UriKind indicates relative or not.

**Comment by rmkerr** [comment]
@jkotas Only if we know that it is a file path, which in this case we don't. The URI spec allows relative paths that start with a '/'. That specific path might be an absolute reference to a file, or it might be a relative path that will later be appended to an absolute path to become, for example, `http://contoso.com/home/foo/README.md`

@danmosemsft I expect that would also work, and if it does it's a much cleaner solution than I suggested.
