### ISSUE TITLE
DateTime Format 

### ISSUE THREAD

**Issue by wtf-boy** [dotnet/corefx#31793]
.netCore Version :2.1.4
CentOS Version: CentOS Linux release 7.4.1708 (Core)

when i use：
  DateTime.Now.ToString("yyyyMM/dd/")
console result:  201808-16-
escape /  to -

remark:Other project output is normal on the same machine

**Comment by Clockwork-Muse** [comment]
The `/` is getting turned into a `-`, because the forward-slash (`/`) is really the [date-separator character](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#dateSeparator), which is being _localized_.  This is by design, since in most cases if this is a user-facing program you want date formatting to use a localized format that will look correct to the user.

If you want the forward-slash (`/`) to be printed, you [need to escape it](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#escape).  Try using this instead:
```
DateTime.Now.ToString(@"yyyyMM\/dd\/")
```

<hr />
Some other notes.

If you want a non-localized format, you should probably also be using the explicit invariant culture:
```
DateTime.Now.ToString(@"yyyyMM\/dd\/", CultureInfo.InvariantCulture)
```

...additionally, the use of a non-localized format implies that the local timezone may not be important, and you should probably be either in UTC, or some explicit other timezone (ie, if for a business, probably the timezone of your headquarters):

```
DateTime.UtcNow.ToString(@"yyyyMM\/dd\/", CultureInfo.InvariantCulture)
// Or
TimeZoneInfo.ConvertTimeBySystemTimeZoneId(DateTimeOffset.UtcNow, "SomeTimeZone").ToString(@"yyyyMM\/dd\/", CultureInfo.InvariantCulture)
```

**Comment by danmosemsft** [comment]
@wtf-boy as above - please close if this resolves the issue.

**Comment by tarekgh** [comment]
@wtf-boy ```/``` means date separator and not literal slash character. if you want to produce the literal slash in your format, please surround the slash with a single quote. something like the following:

```
DateTime.Now.ToString("yyyyMM'/'dd'/'")
```
