### ISSUE TITLE
Investigate perf difference between multiple `SetAllVector128` and a `Load + Permute` sequence

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#31825]
As per the comment here: https://github.com/dotnet/corefx/pull/31779#discussion_r210330631

I would expect that an explicit `Load + four Permute` operations (for four sequential memory addresses) would be faster than (or at least as fast as) four `SetAllVector128` (which should be equivalent to four loads and four permutes).

Investigate the codegen between the two to see if there is some bug blocking this optimization.

**Comment by tannergooding** [comment]
CC. @fiigii, @eerhardt, @CarolEidt 

Also CC. @EgorBo

**Comment by tannergooding** [comment]
I've self assigned and should get to this on Monday.

**Comment by EgorBo** [comment]
@tannergooding turns out I was benchmarking that test on some old 2.1 runtime, with the latest 3.0 Shuffle is 20% faster. 
JIT output:
`Multiply-SetAllVector.cs`: https://gist.github.com/EgorBo/84ae4be8f4a8024548615e486e603962
`Multiply-Shuffle.cs`: https://gist.github.com/EgorBo/c44417038ad56e8ec145ea1945257a36
C#: https://gist.github.com/EgorBo/e2717606fdc4c3a14a7fa16617f87ad8

**Comment by tannergooding** [comment]
Thanks for the update @EgorBo!
