### ISSUE TITLE
latest clrcompression PDB is stripped, and the library itself is built with an outdated toolset

### ISSUE THREAD

**Issue by mababey** [dotnet/corefx#31884]
BinSkim cannot properly analyze clrcompression.dll, because the public symbols are stripped.

Aside from the missing symbol info, it also appears the latest clrcompression.dll was built with an outdated toolset, meaning it is missing any security fixes and performance improvements in the current toolset.

This results in BinSkim errors reported for a UWP app.

Repro:

1. Download latest (4.0.1) runtime.win10-x64-aot.runtime.native.System.IO.Compression (https://www.nuget.org/api/v2/package/runtime.win10-x64-aot.runtime.native.System.IO.Compression/4.0.1), and extract.
2. Download latest (1.5.0) BinSkim (https://www.nuget.org/api/v2/package/Microsoft.CodeAnalysis.BinSkim/1.5.0), and extract.
3. Run: Microsoft.CodeAnalysis.BinSkim\tools\netcoreapp2.0\win-x64\BinSkim.exe analyze runtime.win10-x64-aot.runtime.native.system.io.compression\runtimes\win10-x64-aot\lib\netcore50\clrcompression.dll --sympath "Srv*http://msdl.microsoft.com/download/symbols" --config default --verbose --hashes --output BinSkim.sarif

Output (trimmed to errors):

```
clrcompression.dll: info BA2008: 'clrcompression.dll' was not evaluated for check 'EnableControlFlowGuard' as the analysis is not relevant based on observed metadata: image was compiled with a toolset version (12.10) that is not sufficiently recent (14.0 or newer) to provide relevant settings.
error ERR997.ExceptionLoadingPdb : BA2002 : 'clrcompression.dll' was not evaluated for check 'DoNotIncorporateVulnerableDependencies' because its PDB could not be loaded. (Pdb is stripped of cv (CodeView) info)
error ERR997.ExceptionLoadingPdb : BA2006 : 'clrcompression.dll' was not evaluated for check 'BuildWithSecureTools' because its PDB could not be loaded. (Pdb is stripped of cv (CodeView) info)
error ERR997.ExceptionLoadingPdb : BA2007 : 'clrcompression.dll' was not evaluated for check 'EnableCriticalCompilerWarnings' because its PDB could not be loaded. (Pdb is stripped of cv (CodeView) info)
error ERR997.ExceptionLoadingPdb : BA2011 : 'clrcompression.dll' was not evaluated for check 'EnableStackProtection' because its PDB could not be loaded. (Pdb is stripped of cv (CodeView) info)
error ERR997.ExceptionLoadingPdb : BA2013 : 'clrcompression.dll' was not evaluated for check 'InitializeStackProtection' because its PDB could not be loaded. (Pdb is stripped of cv (CodeView) info)
error ERR997.ExceptionLoadingPdb : BA2014 : 'clrcompression.dll' was not evaluated for check 'DoNotDisableStackProtectionForFunctions' because its PDB could not be loaded. (Pdb is stripped of cv (CodeView) info)
error ERR997.ExceptionLoadingPdb : BA2024 : 'clrcompression.dll' was not evaluated for check 'EnableSpectreMitigations' because its PDB could not be loaded. (Pdb is stripped of cv (CodeView) info)
```

Analysis did not complete due to one or more unrecoverable execution conditions.
Unexpected fatal runtime condition(s) observed: ExceptionLoadingPdb

**Comment by karelz** [comment]
@weshaggard @wtgodbe is it a known problem?
cc @ViktorHofer @ianhays

**Comment by wtgodbe** [comment]
I wasn't aware of this. I actually don't know where we publish this package to in myget, I'm not seeing it in dotnet-core. Also looks like the version in Nuget (4.0.1) was published in 2016, so I'm not surprised that it's out of date... I think it's likely that we no longer support this package with that RID

**Comment by weshaggard** [comment]
Correct we no longer publish this package as we only ship this assembly in the various Microsoft.NETCore.App runtime packages. It might be worth verifying that the clrcompression.dll contained in the latest https://www.nuget.org/packages/runtime.win-x64.Microsoft.NETCore.App package is correct.

**Comment by mababey** [comment]
This is the default version chosen for current UWP projects.

1. Install latest Visual Studio 2107 (15.8.1).
2. New -> Project -> Visual C# -> Windows Universal -> Blank App (Universal Windows)
3. Project -> Manage NuGet Packages..., verify Microsoft.NETCore.UniversalWindowsPlatform is v6.1.7.
4. Build Release|x64.
5. clrcompression.dll in .\bin\x64\Release is 4.0.1.

**Comment by weshaggard** [comment]
Even for UWP it should be coming from https://www.nuget.org/packages/runtime.win10-x86.Microsoft.NETCore.UniversalWindowsPlatform/6.1.7 and not that older package. The version number might be the same but the binary shouldn't be coming from that package.

**Comment by mababey** [comment]
Note that we have been shipping this app for a couple years, over multiple versions of Microsoft.NETCore.UniversalWindowsPlatform, and we have always ended up with the same clrcompression.dll.  So, whatever is broken, has always been broken.

**Comment by joshfree** [comment]
@wtgodbe this sounds like it may be a build infra issue perhaps?  is this something that you could help investigate?

**Comment by wtgodbe** [comment]
I believe we've already identified the issue, UWP should be targeting the latest version of https://www.nuget.org/packages/runtime.win10-x86.Microsoft.NETCore.UniversalWindowsPlatform/6.1.9, rather than the outdated https://www.nuget.org/packages/runtime.win10-x64-aot.runtime.native.System.IO.Compression/4.0.1 from 2016

**Comment by ViktorHofer** [comment]
@wtgodbe what's with this one? any remaining work necessary to do?

**Comment by wtgodbe** [comment]
Looks to be the same as https://github.com/dotnet/corefx/issues/38545, which was closed as no-repro. CC @tommcdon @vonders in case there is anything more there, but I believe we can close this as well.

**Comment by mababey** [comment]
@wtgodbe that other issue sounds like it was not repro on the latest builds due to lack of specific file information, whereas _this_ issue has very specific file info and still-valid error information.  In addition, part of the problem here stems from the fact that the shipping UWP configuration does _not_ get the latest library version.  I was just able to repro again today with the same basic steps:

Windows 10 Enterprise x64 1903 latest (18363.239)
Visual Studio 2019 Enterprise 16.1.6

1. In VS:
    a. File -> New -> Project… -> (C#) Blank App (Universal Windows)
    b. Target version 17763, min version 14393
    c. Set Platform/Config to x64/Release, and build.  (The project defaulted to targeting Microsoft.NETCore.UniversalWindowsPlatform 6.2.8.)
2. Install latest BinSkim, https://www.nuget.org/packages/Microsoft.CodeAnalysis.BinSkim/1.5.1.
3. Run:
$(BinSkimPkgDir)\tools\netcoreapp2.0\win-x64\BinSkim.exe analyze $(MSBuildProjectDirectory)\bin\x64\Release\ilc\clrcompression.dll --sympath "Srv*http://msdl.microsoft.com/download/symbols" --config default --verbose --hashes --output BinSkim.sarif

Result:

Analyzing...
Analyzing 'clrcompression.dll'...
C:\Temp\App1\App1\bin\x64\Release\ilc\clrcompression.dll: info BA3001: 'clrcompression.dll' was not evaluated for check 'EnablePieOnExecutables' as the analysis is not relevant based on observed metadata: image is not an ELF binary.
C:\Temp\App1\App1\bin\x64\Release\ilc\clrcompression.dll: info BA3002: 'clrcompression.dll' was not evaluated for check 'DoNotMarkStackAsExecutable' as the analysis is not relevant based on observed metadata: image is not an ELF binary.
C:\Temp\App1\App1\bin\x64\Release\ilc\clrcompression.dll: info BA3003: 'clrcompression.dll' was not evaluated for check 'EnableStackProtector' as the analysis is not relevant based on observed metadata: image is not an ELF binary.
C:\Temp\App1\App1\bin\x64\Release\ilc\clrcompression.dll: info BA3010: 'clrcompression.dll' was not evaluated for check 'EnableReadOnlyRelocations' as the analysis is not relevant based on observed metadata: image is not an ELF binary.
C:\Temp\App1\App1\bin\x64\Release\ilc\clrcompression.dll: info BA3030: 'clrcompression.dll' was not evaluated for check 'UseCheckedFunctionsWithGcc' as the analysis is not relevant based on observed metadata: image is not an ELF binary.
C:\Temp\App1\App1\bin\x64\Release\ilc\clrcompression.dll: info BA2008: 'clrcompression.dll' was not evaluated for check 'EnableControlFlowGuard' as the analysis is not relevant based on observed metadata: image was compiled with a toolset version (12.10) that is not sufficiently recent (14.0 or newer) to provide relevant settings.
C:\Temp\App1\App1\bin\x64\Release\ilc\clrcompression.dll: info BA2015: 'clrcompression.dll' was not evaluated for check 'EnableHighEntropyVirtualAddresses' as the analysis is not relevant based on observed metadata: image is not an executable program.
C:\Temp\App1\App1\bin\x64\Release\ilc\clrcompression.dll: info BA2016: 'clrcompression.dll' was not evaluated for check 'MarkImageAsNXCompatible' as the analysis is not relevant based on observed metadata: image is a 64-bit binary.
C:\Temp\App1\App1\bin\x64\Release\ilc\clrcompression.dll: info BA2018: 'clrcompression.dll' was not evaluated for check 'EnableSafeSEH' as the analysis is not relevant based on observed metadata: image is not a 32-bit binary.
C:\Temp\App1\App1\bin\x64\Release\ilc\clrcompression.dll: pass BA2001: 'clrcompression.dll' is a 64-bit image with a base address that is >= 4 gigabytes, increasing the effectiveness of Address Space Layout Randomization (which helps prevent attackers from executing security-sensitive code in well-known locations).
error ERR997.ExceptionLoadingPdb : BA2002 : 'clrcompression.dll' was not evaluated for check 'DoNotIncorporateVulnerableDependencies' because its PDB could not be loaded. (Pdb is stripped of cv (CodeView) info)
C:\Temp\App1\App1\bin\x64\Release\ilc\clrcompression.dll: pass BA2005: 'clrcompression.dll' is not known to be an obsolete binary that is vulnerable to one or more security problems.
error ERR997.ExceptionLoadingPdb : BA2006 : 'clrcompression.dll' was not evaluated for check 'BuildWithSecureTools' because its PDB could not be loaded. (Pdb is stripped of cv (CodeView) info)
error ERR997.ExceptionLoadingPdb : BA2007 : 'clrcompression.dll' was not evaluated for check 'EnableCriticalCompilerWarnings' because its PDB could not be loaded. (Pdb is stripped of cv (CodeView) info)
C:\Temp\App1\App1\bin\x64\Release\ilc\clrcompression.dll: pass BA2009: 'clrcompression.dll' is properly compiled to enable Address Space Layout Randomization, reducing an attacker's ability to exploit code in well-known locations.
C:\Temp\App1\App1\bin\x64\Release\ilc\clrcompression.dll: pass BA2010: 'clrcompression.dll' does not have an imports section that is marked as executable, helping to prevent the exploitation of code vulnerabilities.
error ERR997.ExceptionLoadingPdb : BA2011 : 'clrcompression.dll' was not evaluated for check 'EnableStackProtection' because its PDB could not be loaded. (Pdb is stripped of cv (CodeView) info)
C:\Temp\App1\App1\bin\x64\Release\ilc\clrcompression.dll: pass BA2012: 'clrcompression.dll' is  C or C++binary that does not contain a load config table, which indicates either that it was compiled and linked with a version of the compiler that precedes stack protection features or is a binary (such as an ngen'ed assembly) that is not subject to relevant security issues.
error ERR997.ExceptionLoadingPdb : BA2013 : 'clrcompression.dll' was not evaluated for check 'InitializeStackProtection' because its PDB could not be loaded. (Pdb is stripped of cv (CodeView) info)
error ERR997.ExceptionLoadingPdb : BA2014 : 'clrcompression.dll' was not evaluated for check 'DoNotDisableStackProtectionForFunctions' because its PDB could not be loaded. (Pdb is stripped of cv (CodeView) info)
C:\Temp\App1\App1\bin\x64\Release\ilc\clrcompression.dll: pass BA2019: 'clrcompression.dll' contains no data or code sections marked as both shared and writable, helping to prevent the exploitation of code vulnerabilities.
C:\Temp\App1\App1\bin\x64\Release\ilc\clrcompression.dll: pass BA2021: 'clrcompression.dll' contains no data or code sections marked as both shared and executable, helping to prevent the exploitation of code vulnerabilities.
C:\Temp\App1\App1\bin\x64\Release\ilc\clrcompression.dll: pass BA2022: 'clrcompression.dll' appears to be signed with secure cryptographic algorithms. WinTrustVerify successfully validated the binary but did not attempt to validate certificate chaining or that the root certificate is trusted. The following digitial signature algorithms were detected: Cryptographically weak signatures: [digest algorithm: 'sha1NoSign' + digest encryption algorithm: 'RSA'] Cryptographically strong signatures: [digest algorithm: 'sha256NoSign' + digest encryption algorithm: 'RSA']
error ERR997.ExceptionLoadingPdb : BA2024 : 'clrcompression.dll' was not evaluated for check 'EnableSpectreMitigations' because its PDB could not be loaded. (Pdb is stripped of cv (CodeView) info)

One or more rules was disabled for an analysis target, as it was determined not to be applicable to it (this is a common condition). Pass --verbose on the command-line for more information.

Analysis did not complete due to one or more unrecoverable execution conditions.
Unexpected fatal runtime condition(s) observed: ExceptionLoadingPdb

**Comment by mababey** [comment]
@wtgodbe , please re-open this issue.

**Comment by WackPenguin** [comment]
Any update on this issue? I have similar issue with System.Data.SqlClient package. 

`
Analyzing...
error ERR997.ExceptionLoadingPdb : BA2002 : 'sni.dll' was not evaluated for check 'DoNotIncorporateVulnerableDependencies' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2006 : 'sni.dll' was not evaluated for check 'BuildWithSecureTools' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2007 : 'sni.dll' was not evaluated for check 'EnableCriticalCompilerWarnings' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2011 : 'sni.dll' was not evaluated for check 'EnableStackProtection' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2013 : 'sni.dll' was not evaluated for check 'InitializeStackProtection' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2014 : 'sni.dll' was not evaluated for check 'DoNotDisableStackProtectionForFunctions' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2024 : 'sni.dll' was not evaluated for check 'EnableSpectreMitigations' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2002 : 'sni.dll' was not evaluated for check 'DoNotIncorporateVulnerableDependencies' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2006 : 'sni.dll' was not evaluated for check 'BuildWithSecureTools' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2007 : 'sni.dll' was not evaluated for check 'EnableCriticalCompilerWarnings' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2011 : 'sni.dll' was not evaluated for check 'EnableStackProtection' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2013 : 'sni.dll' was not evaluated for check 'InitializeStackProtection' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2014 : 'sni.dll' was not evaluated for check 'DoNotDisableStackProtectionForFunctions' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2024 : 'sni.dll' was not evaluated for check 'EnableSpectreMitigations' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2002 : 'sni.dll' was not evaluated for check 'DoNotIncorporateVulnerableDependencies' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2006 : 'sni.dll' was not evaluated for check 'BuildWithSecureTools' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2007 : 'sni.dll' was not evaluated for check 'EnableCriticalCompilerWarnings' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2011 : 'sni.dll' was not evaluated for check 'EnableStackProtection' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2013 : 'sni.dll' was not evaluated for check 'InitializeStackProtection' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2014 : 'sni.dll' was not evaluated for check 'DoNotDisableStackProtectionForFunctions' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2024 : 'sni.dll' was not evaluated for check 'EnableSpectreMitigations' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
`

**Comment by carlossanlop** [comment]
Triage:
UWP is going to be replaced by .NET Core, that should solve it.
