### ISSUE TITLE
Why RSACng use SignHash with RSASignaturePadding.Pkcs1 need input hash length equal to HashAlgorithmName's hash's length?

### ISSUE THREAD

**Issue by avalon1610** [dotnet/corefx#31933]
I'm use .NET Framework 4.6.1 on Windows.

And I found when use RSACng SignHash, which is 
```c#
byte[] SignHash(byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding);
```
when the parameter hash, the byte array 's length is not equal to hashAlgorithm's hash length, it will throw exception: wrong parameter.
For example:
when use hashAlgorithm Sha256, whose result length is 32 , the length of hash must also be 32.

PSS padding has no such restrictions.
I think native library like Openssl also has no such restrictions.

**Comment by bartonjs** [comment]
If you're using `SignHash` (the hash is already computed) then the hash needs to be correct for it's size.  If PSS isn't requiring that then that sounds like a bug with the PSS handler (though I'd have to dig in and double check).

If you are signing data (which needs to be hashed first) then you should use `SignData` instead.  It has no size restrictions.

**Comment by avalon1610** [comment]
OK, I made a mistake. 
I found openssl's `EVP_DigestSignUpdate` will auto hash for the data, equals to `SignData` here. 
But signing with PSS padding has different behavior here as I tested.

**Comment by bartonjs** [comment]
The PSS format allows the hash to mismatch because PSS technically doesn't have a requirement that the PSS hash and the data hash match, and that functionality is the escape valve for implementing custom logic (e.g. hash the data using SHA384 then verify the signature with PSS/SHA256... for... reasons.... :smile:).

There doesn't seem to be any other action required here, so closing.
