### ISSUE TITLE
System.Tests.StringTests/Replace_StringComparison_TurkishI failing randomly on UAP

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#31978]
This one seems to be flaky, I will disable it for now (https://github.com/dotnet/corefx/pull/31974/commits/4fc6e4c95426b6acb69ab4b79ca6ef5d24052a06). Failing on uap.

```
System.Tests.StringTests/Replace_StringComparison_TurkishI

System.Diagnostics.RemoteExecutorTestBase+RemoteInvokeHandle+RemoteExecutionException : Remote process failed with an unhandled exception.

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
           ↓ (pos 1)
Expected: aİ
Actual:   aa
           ↑ (pos 1)
   at System.Tests.StringTests.<>c.<Replace_StringComparison_TurkishI>b__327_0(String source) in D:\j\workspace\windows-TGrou---33cbf18b\src\System.Runtime\tests\System\StringTests.netcoreapp.cs:line 478

Child process:
  System.Runtime.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb System.Tests.StringTests+<>c Int32 <Replace_StringComparison_TurkishI>b__327_0(System.String)

Child arguments:
  iİ
```

cc @tarekgh

**Comment by danmosemsft** [comment]
Inconsistent currentculture? I can't see how else it could be flaky

**Comment by krwq** [comment]
I suspect this is because we change current culture more than once. I remember there was some issue with that on uap that only 1 change can be done reliably and anything after that is "hey Windows, we would like to change the culture please" and then it was up to Windows if it will change it immediately or later... Try splitting into 2 remote invokes or leave open if it is still flaky after that
