### ISSUE TITLE
RegEx.IsMatch appear to fall into infinite loop

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#32055]
@ie-zero commented on [Wed Aug 29 2018](https://github.com/dotnet/core/issues/1901)

# Issue Title
Regex.IsMatch appears to fall into an infinite loop when attempting to match 

string ```"BEGIN:VCOMPONENT\r\nBEGIN:VCOMPONENT\r\n"``` 
against ```@"^(BEGIN\:VCOMPONENT\r\n)(.*\n*)*(END:VCOMPONENT\r\n)$"``` regular expression.

# General
I have experienced this behaviour on Windows 7 under .NET Core 2.1.401 using the following tests

```C#
[Fact]
public void PassingTest()
{
	const string regEx = @"^(BEGIN\:VCOMPONENT\r\n)(.*\n*)*(END:VCOMPONENT\r\n)$";
	var actual = Regex.IsMatch("BEGIN:VCOMPONENT\r\nBEGIN:VCOMPONENT\r\n", regEx);

	Assert.False(actual);
}
```
```C#
[Fact]
public void InfiniteLoopTest()
{
	const string regEx = @"^(BEGIN\:VCOMPONENT\r\n)(.*\n*)*(END:VCOMPONENT\r\n)$";
	var actual = Regex.IsMatch("BEGIN:VCOMPONENT\r\nDummyName:DummyValue\r\nBEGIN:VCOMPONENT\r\n", regEx);

	Assert.False(actual);
}
```

# System Information 

.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.401\

Host (useful for support):
  Version: 2.1.3-servicing-26724-03
  Commit:  124038c13e

.NET Core SDKs installed:
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by danmosemsft** [comment]
@ie-zero hello, this regular expression is going to be slower than necessary in any engine because it involves heavy back tracking.

Your regex and pattern can be simplified and still demonstrate the problem eg to `(.*)*(Z)` and `abcdefghijklmnopqrstuvwxyz`. The engine matches zero or more characters zero or more times then takes zero or more of whatever that matched and then looks for the end of the pattern. It fails, so then it tries again until it has exhausted every other permutation.

Definitely the engine could be more efficient here (I measured Javascript is faster) but it is a bad pattern that gets worse quickly as the text gets longer.

Note you can set a timeout to break out of this kind of backtracking, for example: `var actual = Regex.IsMatch("BEGIN:VCOMPONENT\r\nDummyName:DummyValue\r\nBEGIN:VCOMPONENT\r\n", regEx, RegexOptions.None, new TimeSpan(0, 0, 5));` limits the regex to 5 seconds.

A better plan is to improve the regex. I suspect you want `RegexOptions.SingleLine` which allows `.` to match `\n`. Then you can drop the `\n*` in your pattern and you have `"^(BEGIN\:VCOMPONENT\r\n)(.*)(END:VCOMPONENT\r\n)$"` which can match or fail very fast.

**Comment by ie-zero** [comment]
Thank you very much for taking the time to look into this @danmosemsft

**Comment by danmosemsft** [comment]
You're welcome @ie-zero. By the way if you are interested in contributing to.NET Core, there are plenty of issues marked up for grabs...
