### ISSUE TITLE
Two TimeZoneInfo tests are failing on OS X

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3211]
```
09:23:54    TimeZoneInfoTests.NearMinMaxDateTimeOffsetConvertTest [FAIL]
09:23:54       Error: Expected value '12/31/9999 23:59:59' but got '12/31/9999 22:59:59', input value is '12/31/9999 04:59:59', Source TimeZone: America/Los_Angeles, Dest. Time Zone: Australia/Sydney
09:23:54       Expected: True
09:23:54       Actual:   False
09:23:54    System.Runtime.Extensions.Tests  Total: 495, Errors: 0, Failed: 1, Skipped: 0, Time: 1.096s
09:23:54       Stack Trace:
09:23:54             at TimeZoneInfoTests.VerifyConvert(DateTime inputTime, String sourceTimeZoneId, String destinationTimeZoneId, DateTime expectedTime)
09:23:54             at TimeZoneInfoTests.NearMinMaxDateTimeOffsetConvertTest()
09:23:54    TimeZoneInfoTests.NearMinMaxDateTimeConvertTest [FAIL]
09:23:54       Error: Expected value '12/31/9999 23:59:59' but got '12/31/9999 22:59:59', input value is '12/31/9999 12:59:59', TimeZone: Australia/Sydney
09:23:54       Expected: True
09:23:54       Actual:   False
09:23:54       Stack Trace:
09:23:54             at TimeZoneInfoTests.VerifyConvert(DateTime inputTime, String destinationTimeZoneId, DateTime expectedTime)
09:23:54             at TimeZoneInfoTests.NearMinMaxDateTimeConvertTest()
```
cc: @eerhardt, @ellismg, @tarekgh

**Comment by eerhardt** [comment]
This issue is that OS X has older/v1 tzfiles, which do not contain the ["POSIX-TZ-environment-variable-style string for use in handling instants after the last transition time stored in the file"](http://linux.die.net/man/5/tzfile).  This means that there isn't a way to tell when daylight savings starts and ends for dates in the future (in the case of the test, year 9999).  You can only tell when DST starts and ends for dates that are stored in the file, which the max year for v1 tzfiles is 2038.  So TimeZoneInfo doesn't know that Los Angeles should not be in DST on 12/31/1999, and that Sydney should be in DST.  Thus, TimeZoneInfo is an hour off.

If/when OS X updates to the newer v2 tzfile format, then these tests will pass on OS X.  But in the meantime, we should change the test to use these expected times on OS X.
