### ISSUE TITLE
Add MemoryMappedFile.CreateNew without map name

### ISSUE THREAD

**Issue by odhanson** [dotnet/corefx#32130]
The following factory method:
```c#
public static MemoryMappedFile CreateNew(string mapName, long capacity)
```
is not supported on OS other than windows when mapName is not null. This produces a warning in the system build when we use application compatibility checks, and relies on code reviews to make sure this API is always used with null.

I propose adding another overload:

```c#
public static MemoryMappedFile CreateNew(long capacity)
```
to make is explicit about using the anonymous version.

I will add a PR shortly with the actual implementation

**Comment by karelz** [comment]
@odhanson the API addition has to be approved first. Please do not put up PR, until it is approved.
See API approval details: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md

**Comment by odhanson** [comment]
@karelz sorry, I meant a link to a PR on my own fork, just for reference.

**Comment by karelz** [comment]
@odhanson just be aware that it may be wasted time if the API eventually gets rejected or significantly changed. That's why we encourage contributors to wait for the approval first.
Feel free to go ahead with PR in your fork if you are ok with the risk.

**Comment by stephentoub** [comment]
You're just proposing this?
```C#
public static MemoryMappedFile CreateNew(long capacity) =>
    CreateNew(null, capacity);
```
?

**Comment by odhanson** [comment]
Yep.  Its small but it can enable us to be explicit about the use of platform supported APIs



Sent from my Samsung Galaxy smartphone.

**Comment by stephentoub** [comment]
Thanks. I understand the motivation, but I'm not convinced it's worthwhile (though my care level is fairly low).

If the goal is to improve code reviews, well, code reviewers will already need to be on the lookout for usage of the existing overload.  If the goal is to help an analyzer, I expect if an analyzer just checked whether the first argument was a `null` const, that would address 99.9% of false positives.  There would still be the case of someone who did:
```C#
string mapName = null;
MemoryMappedFile.CreateNew(mapName, capacity);
```
but that's unlikely, especially if it's a case that would be addressed by the proposed overload, since if you're using that proposed overload, you're already in a situation where you couldn't be forwarded some name that was passed along to you.

That's all to say, I'm not convinced it actually moves the needle significantly. It also doesn't address the other APIs that also take a mapName and also work fine on Unix when mapName is null, e.g. CreateFromFile, CreateOrOpen.  And adding additional overloads there just makes it even less likely.  Plus, the failure mode here is deterministic: if you pass non-null on Unix, you get an exception.  So the majority case is analyzable, and if something slips through, any testing should highlight it instantly.

**Comment by JeremyKuhne** [comment]
I agree with @stephentoub's assessment above. As there has been no further discussion/feedback here I'm closing this for now. We can resurrect if we get more input/data.
