### ISSUE TITLE
Branching (or not)

### ISSUE THREAD

**Issue by eatdrinksleepcode** [dotnet/corefx#322]
While commenting on [an outstanding pull request](https://github.com/dotnet/corefx/pull/110#issuecomment-65910391), David Kean mentioned:
> We're trying to figure out our branching structure at the moment. Currently we have only a single branch that represents what we're shipping for the next update of .NET Core. Clearly this isn't scalable for the product, and we're going to creating branches for future work so PR's that have API changes and destablizing changes get a little more bake time. @joshfree is looking into that.

I would like to get the conversation about branching structure out into the open. And to do that, I would like to start by asking: _why_ is a single branch not scalable for the product?

I have worked in code bases of various sizes, release schedules, and branching schemes, and my experience is that NOT branching is nearly always preferable to branching. In fact, the most common reasons given for wanting to branch (e.g. disruptive or long-running changes) are exactly the times when branching hurts the most, because it encourages divergence between different works-in-progress, pushing difficult integration decisions farther out and requiring more rework later.

Rather than a policy that handles change by branching, I would rather see a policy of trunk-based development that encourages all changes - even incomplete changes - to be merged into master on a frequent basis. This shortens and simplifies the merging process and encourages small refactorings and improvements by reducing the amount of work needed to merge them.

Obviously allowing unfinished work to be committed to master requires mechanisms in place to ensure that such work does not affect the releasability of the framework. Mechanisms such as feature flags and branch by abstraction are slightly more complicated to implement in a framework (especially one that is highly tuned for performance) than in a typical application, but not excessively so. And the advantage of keeping all of the ongoing work together is well worth the effort.

What are the community's thoughts on trunk-based development?

**Comment by joshfree** [comment]
Hi All,
 Later this week we will be creating a v1.0 release branch on GitHub.  At that point the master branch will become 'forward looking' and will be open to riskier community PRs - such as new APIs - that up until now we've been postponing.

**What this means for everyone working on dotnet/corefx (rules of the road) :**

* dotnet/corefx **master**
  * The **master** branch will be open for 'forward looking' changes that ship in a future release (let's call it 1.1 for now).
  * The backlog of PRs for new APIs can now be reviewed and either accepted or closed against **master**.
  * All API and general product improvement PRs should continue to be submitted to **master** going forward
* dotnet/corefx **v1.0**
  * The **v1.0** branch will coincide with our eventual 1.0 release and servicing branch
  * **v1.0** will contain all community PRs from master up until the date of the fork.
  * build changes as well as initial library commits from the product team should happen in **v1.0** and then flow upstream to master.

I'd also like to mention that since the dotnet/corefx GitHub project is just getting started we're trying hard to keep everything as simple as possible while still meeting the needs of the community and close partners.  We are going to be flexible with the plan and open to adjustments as needed going forward.

Please let me know if you have any questions or concerns.

Cheers,
Josh

**Comment by eatdrinksleepcode** [comment]
Thanks for the update Josh, that sounds sensible.

**Comment by joshfree** [comment]
I've gone ahead and created the v1.0 branch.

* https://github.com/dotnet/corefx/commits/master
* https://github.com/dotnet/corefx/commits/v1.0

At this point I'll close out the issue.  Feel free to reactivate if needed.

**Comment by eatdrinksleepcode** [comment]
The original reason for this issue (which was not actually related to release branching) has not been resolved, or even really discussed. I apologize for the delay in my response; sadly I do not get to work on .NET Core at my day job :) I will respond to the questions raised by the weekend.

(GitHub does not allow me to re-open my own issue if I didn't close it. Please re-open.)

**Comment by terrajobst** [comment]
Before we re-open, can you clarify what issue is that you're after? I'm not pushing back, by the way, I just feel that @AArnott, @joshfree and myself provided the answers to your question.

**Comment by eatdrinksleepcode** [comment]
In a nutshell (I'm on my phone on a plane):

In Dave Kean's post that I originally linked to, he implied that there was an intent to employ some kind of branching scheme, over and above the typical GitHub fork-and-PR or release branching. It is that possible branching scheme that I most want to discuss.

I am in no way opposed to release branching as a vehicle for service releases. There ARE alternatives, but it was not my intent to argue that any of those are more appropriate for this project than release branching; I was merely trying to surface the apparent assumption that branches are the only way, because I believed that assumption would also be relevant to the rest of the conversation.

Fork-and-PR as feature branching, and possible alternatives to that model, is also a subject I am interested in, but that can wait for another time.

**Comment by terrajobst** [comment]
I see. My understanding is that there are currently no plans to formerly introduce feature or development branches into the `corefx` repository. We plan on using the GitHub fork + local feature branch + PR against master approach. If we ever want to change that, we'll certainly start a discussion on GitHub.

Does this help?

**Comment by eatdrinksleepcode** [comment]
Yes it does. Thank you.

**Comment by terrajobst** [comment]
Excellent. And thanks for the feedback!
