### ISSUE TITLE
Unnecessary extra div in BigIntegerCalculator.DivRem

### ISSUE THREAD

**Issue by artelk** [dotnet/corefx#3220]
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Numerics/src/System/Numerics/BigIntegerCalculator.DivRem.cs#L28
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Numerics/src/System/Numerics/BigIntegerCalculator.DivRem.cs#L49

Current code:

ulong value = (carry << 32) | left[i];
quotient[i] = (uint)(value / right);
carry = value % right;

I suspect that won't be optimized by JIT and this would work a bit faster:

ulong value = (carry << 32) | left[i];
ulong d = value / right
quotient[i] = (uint)d;
carry = value - d*right;

**Comment by stephentoub** [comment]
cc: @axelheer

**Comment by axelheer** [comment]
Makes sense, thanks! :+1:

But someone should measure the speed gain, if any. (I can, of course...)

**Comment by artelk** [comment]
Found discussion about that:
http://stackoverflow.com/questions/447282/why-is-math-divrem-so-inefficient

**Comment by CodesInChaos** [comment]
The alternative version looks more difficult to optimize in the JITter to me. Since the same CPU instruction outputs both quotient and remainder on x86, optimizing the naive form should be straight forward. So even if the new version is faster with the current version of the JITter it might become the slower version if the JITter improves.

I'd prefer asking the JIT team to implement this optimization (if the JITter doesn't optimize this already). As an alternative it'd also be possible to extend `Math.DivRem` to unsigned values and add a JITter intrinsic for it.

**Comment by stephentoub** [comment]
https://github.com/dotnet/coreclr/issues/757

**Comment by axelheer** [comment]
Okay, I did the benchmark: dividing 1024 bit integers by 16 bit integers a million times leads to 542 ms before this tweak / 446 ms after this tweak, which I find quite significant.

A agree that an JITer optimization (as pointed out by @CodesInChaos) would be great, but since that isn't on the roadmap yet (as by @stephentoub's linked issue), I'd speak for @artelk's optimization. I'll prepare a PR accordingly, since I've already done the "work".

**Comment by mellinoe** [comment]
Thanks a lot for the contribution, @axelheer !
