### ISSUE TITLE
[bug] TimeSpan constructors kill microseconds

### ISSUE THREAD

**Issue by astrowalker** [dotnet/corefx#32430]
`TimeSpan` (https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/TimeSpan.cs) constructors go through `Interval` method which has such line:

    return new TimeSpan((long)millis * TicksPerMillisecond);

This is incorrect -- here the milliseconds are (prematurely) rounded, and the scale is changed. It should be:

    return new TimeSpan((long)(millis * TicksPerMillisecond));

First -- changing the scale, then rounding.

With this change values smaller than milliseconds can be passed and stored in `TimeSpan`.

**Comment by Clockwork-Muse** [comment]
....I don't know if the precision of floating point would play havoc at the size, but possibly a better solution is to transition calls from `return Interval(value, MillisPerHour)` to `return Interval(value, TicksPerHour)`

From the look of things, the method was only ever intended to handle millisecond precision (given the [adjustment it performs](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/TimeSpan.cs#L246)), probably due to the way that computer clocks originally couldn't do any better than ~10-15ms accuracy anyways.

**Comment by astrowalker** [comment]
@Clockwork-Muse , Since there is one constructor that's directly stores ticks (`FromTicks`) I wrote helper method mimicking the pointed out method -- but I changed the order of computation. First compute ticks as `double`, then check the range, and then cast it it `long`. Of course there will be a bit of rounding (it has to be), but microseconds are stored without a sweat. 

It is not floating precision that is the problem, but the casting priority (or here more generally, the order of computation).

**Comment by danmosemsft** [comment]
@astrowalker I'm going through old issues. Any interest in offering a PR here?

**Comment by astrowalker** [comment]
@danmosemsft , I am not sure what PR means in this context :-). What do you have in mind I should do?

**Comment by danmosemsft** [comment]
My understanding based on your description above (I did not investigate) is that we are unnecessarily losing precision and that this could be fixed. So a PR (pull request) would be a submission of a code change that fixed it, which would usually come with test(s) also. 

There's no obligation to offer one of course - I only suggested it because often people that report an issue like this are interested in trying to fix it. It might otherwise not get attention from us for some time.

Information about contributing, should you want to, is in the Documentation folder in this repo.

**Comment by astrowalker** [comment]
Thank you, out of context I thought about Public Relations :-) I will try to learn how to make one, but it will take some time because of my heated time currently and the fact I need to learn how things are organized, why VS2017 complains right at the start, and so on.

In other words, I am willing but please don't count on me (at least not in reasonable timely fashion), as for providing potential code to fix this issue via this thread -- sure thing.

**Comment by danmosemsft** [comment]
@astrowalker that is totally fine as there is no rush on this one. It takes some time to learn how to build and test and make a PR but then of course the second time will be easy. Ping me if you get stuck.
