### ISSUE TITLE
GetGenericArguments for open generic type returns empty array

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#3247]
The following test fails in CoreCLR:

[Fact]
public static void GenDefArgs()
{
    Assert.Equal(1, typeof(Func<>).GetGenericArguments().Length);
}

On desktop CLR, the following prints 1:

Console.WriteLine(typeof(Func<>).GetGenericArguments().Length);

For closed generic types, things seem fine.

**Comment by nguerrera** [comment]
@bartdesmet Are you working in System.Linq.Queryable by chance? I believe the public GetGenericArguments compatibility extension in System.Reflection.TypeExtensions is fine, but I just found an error in the internal implementation in System.Linux.Queryable's TypeHelper. Fixing it.

The issue is that in the move to TypeInfo (before my time), it was decided to distinguish between the type parameters of open types and the type arguments of closed types. The Queryabe helper is using TypeInfo.GenericTypeArguments always, but it should use GenericTypeParameters for open types.

**Comment by bartdesmet** [comment]
@nguerrera Could well be the case I hit that one; this was discovered in the context of writing a test for System.Linq.Expressions.

**Comment by nguerrera** [comment]
There's a bad helper in System.Linq.Expressions.Tests too!

**Comment by bartdesmet** [comment]
Aha, that’d explain it. My F12 “Go to Definition” is still upset in some CoreCLR projects; it made me believe it came from System.Reflection.TypeExtensions IIRC.

Will you address those?

**Comment by nguerrera** [comment]
Yep. PR coming shortly.
