### ISSUE TITLE
API Proposal: System.IO.File.WaitForAvailable

### ISSUE THREAD

**Issue by hez2010** [dotnet/corefx#32550]
Sometimes when a file is occupied by other process, we can not open it until the process close the file. So we have to write a loop to try opening the file many times.
I suggest the System.IO can provide a method: 
```c#
bool File.WaitForAvailable(string fileName, uint maxiumWaitingTime = uint.Infinity);
```
which will automatically wait the file to be closed and becomes available.
The method will fail if the waiting time exceeds maxiumWaitingTime or does not have proper privilege.

In *inx system, a file can be accessed even when it has been occupied, so the method can directly return true in this case.

**Comment by Clockwork-Muse** [comment]
>In *inx system, a file can be accessed even when it has been occupied, so the method can directly return true in this case.

That's not necessarily true - some types of locks are only _advisory_ - they require all interested processes to opt-in by checking for the existence of the relevant lock.  Some lock types are mandatory.  I'm going to assume that .NET Core checks for the advisory locks, so returning true wouldn't be correct behavior anyways.

There's a few problems with this API, though - 
 1. `File` is a static class, which means a method called on it would have global (or at least thread-local) effects.  It also means the return value should be `void` (since it's not being called on a specific file)
 1. It turns all calls to `Open` into a blocking wait, when the general trend, especially in IO, is async/non-blocking
 2. If it _was_ per-file, the method returning true doesn't mean `Open` would succeed - there's an inherent race condition possible.

... so it might be better to do something like: 
```charp
public static Task<System.IO.FileStream> OpenAsync (string path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, CancellationToken token)
```
...although I have no idea if Windows, or any other OS, natively supports this (as opposed to doing something with `SpinWait`s or similar).

**Comment by hez2010** [comment]
@Clockwork-Muse I forgot the filename parameter. 
I have edited the description.

**Comment by Clockwork-Muse** [comment]
@hez2010 - Fair, enough, I was wondering.
I've updated the issues I mentioned to reflect that change.

**Comment by stephentoub** [comment]
I agree with @Clockwork-Muse's concerns. Plus, as defined, I don't know why this would be specific to File; several libraries (e.g. Polly) provide "retry" helpers, with various policies and back-off schemes, working with arbitrary delegates, and that's all this really is. I don't think we should add this, at least not as proposed.

And while async file opening support would be nice, I'm not aware of efficient ways to support that on all OSes we care about. If such mechanisms did exist, I'd want to expose that separately, and then such a retry helper could be used with it.

**Comment by MarcoRossignoli** [comment]
FYI @hez2010 https://github.com/dotnet/corefx/issues/31917 , maybe something like this with retry(e.g. Polly).

**Comment by JeremyKuhne** [comment]
Closing. If more data comes up that addresses @stephentoub's comments we can reopen and re-evaluate.
