### ISSUE TITLE
corefx wiki page is malformed

### ISSUE THREAD

**Issue by AdamYoblick** [dotnet/corefx#32560]
See https://github.com/dotnet/corefx/wiki

**Comment by stephentoub** [comment]
@karelz, for some reason I don't appear to have permissions to revert changes made to the wiki, but a change was recently made that should be undone.

**Comment by karelz** [comment]
Turns out the type of the page was changed to MediaWiki instead of Markdown + wrong link was added in this change: https://github.com/dotnet/corefx/wiki/Home/_compare/56247a4dc4a4ca8376957e55acad2b25c80bdaa6...01d730d95162c6bb6de42481baea1e6090852001 by @Xray1983. The different type of the page made it not show history even for me (hiding the ability to revert the changes).
@Xray1983 was that intentional change or by accident?

Thanks @AdamYoblick for letting us know. It is fixed now.

**Comment by AdamYoblick** [comment]
Not a problem 👍
