### ISSUE TITLE
System.IO.Path.Combine used in netstandard2.0 project not producing the same result when called from .NET Core and .NET Framework

### ISSUE THREAD

**Issue by jordanovski** [dotnet/corefx#32612]
In a netstandard2.0 project, we have a method that creates a path from a string array using the **System.IO.Path.Combine** method.
``` csharp
string[] array = new string[] { "C:", "Temp" };
var res = Path.Combine(array);
```

This is the output we are getting from the method when we call it from a .NET Core 2.1 and .NET Framework 4.6.1 projects:

**.NET Core 2.1** 
``` csharp
res = "C:\\Temp"
```

**.NET Framework 4.6.1** 
``` csharp
res = "C:Temp"
```

Is this the expected behaviour of Path.Combine?

**Comment by jordanovski** [comment]
I don't know if this is the correct place of the **Path.Combine** implementation for .NET Core and .NET Framework but I found that in the .NET Framework implementation there is one comparison (`ch != VolumeSeparatorChar`) more for determining if **DirectorySeparatorChar** needs to be appended to the file path

**.NET Framework**
https://referencesource.microsoft.com/#mscorlib/system/io/path.cs,1276
``` csharp
char ch = finalPath[finalPath.Length - 1];
if (ch != DirectorySeparatorChar && ch != AltDirectorySeparatorChar && ch != VolumeSeparatorChar) {
    finalPath.Append(DirectorySeparatorChar);
}
```


.NET Core
https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/IO/Path.cs#L380
``` csharp
if (!PathInternal.IsDirectorySeparator(ch))
{
    finalPath.Append(PathInternal.DirectorySeparatorChar);
}
```
https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/IO/PathInternal.Windows.cs#L317
``` csharp
c == DirectorySeparatorChar || c == AltDirectorySeparatorChar;
```

**Comment by sixlettervariables** [comment]
On Windows, `C:` and `C:\` mean two different things, oddly enough. Specifying a drive (i.e. `C:`) without a trailing directory separator character means, "relative to the current working directory of the drive," rather than the root of that drive (compare in a DOS/command prompt using `C:` vs `C:\`). For example:
```
> Path.GetFullPath(@"C:TEMP")
"C:\\Windows\\TEMP"
> Path.GetFullPath(@"C:\TEMP")
"C:\\TEMP"
```

**Comment by jkotas** [comment]
> I found that in the .NET Framework implementation there is one comparison more

This change was intentionally introduce by https://github.com/dotnet/coreclr/pull/16447

> My expectations where that when I start referencing it in .NET Framework project the functionality will be the same

.NET Framework and .NET Core are not guaranteed to have same bugs. System.IO namespace in particular has a lot of bugs and limitations fixed compared to .NET Framework.

**Comment by JeremyKuhne** [comment]
@jordanovski Thanks for the report. As @jkotas mentioned this was intentional.

Primarily this was done to fix issues with cross platform scenarios. Having volumes mounted that support other characters is slowly becoming more common.

From a best practices perspective, you should never use drive relative paths. You should never use any partially qualified paths as a base path either. This typically means no drive or UNC prefix, with the one odd case of drive relative. The reason is that these paths get resolved against the current working directory, which is a process-wide setting. Not fully resolving can lead to tricky bugs where your paths change out from under you. (The Windows [documentation](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-getfullpathnamew) that GetFullPath is based on specifically goes into this and actually discourages using the API.)

In order to mitigate the current working directory issue the best choice is to make sure you have a fully qualified path as a base path. `Path.GetFullPath()` will do this. It still is obviously subject to the current working directory- but at least you get the path fixed at a specific point in time. We've added a new overload in .NET Core that allows specifying a "virtual" working directory (`basePath`) which avoids the problem altogether.

If you really want to make a drive relative path (not recommended, of course) and have it be consistent between desktop and Core, you should just concat the strings.

**Comment by jordanovski** [comment]
Thanks for the clarification @JeremyKuhne @jkotas
