### ISSUE TITLE
decimal.ToString("N") behaving different on Ubuntu 18

### ISSUE THREAD

**Issue by Tratcher** [dotnet/corefx#32644]
_From @JoshClose on October 5, 2018 17:46_

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

code: `(12345.67890).ToString("N")`
expected output: `"12,345.679"`
actual output:  `"12345.678900"`

_Copied from original issue: aspnet/Home#3589_

**Comment by JoshClose** [comment]
If just found the reason is because `CultureInfo.CurrentCulture` is `en-US-POSIX` on Ubuntu 18 and id `en-US` on Ubuntu 16.

What is the correct/recommended way to handle this?

**Comment by Clockwork-Muse** [comment]
The correct way to do **ANY** formatting is to always explicitly specify the target culture:
```csharp
var culture = CultureInfo.GetCultureInfo("en-US");
(12345.67890).ToString("N", culture);
```
(or whatever)

**Comment by JoshClose** [comment]
All apps would have to have a config with the culture or a way for the user to pick their culture then.

Wouldn't you want to use whatever culture the OS is set to so it formats correctly when in another country?

**Comment by Clockwork-Muse** [comment]
...you're working with ASP.NET, which is (usually) deployed as a server-running web application.  The culture of the machine is almost never relevant (as opposed to the culture of the viewer, or maybe some explicitly configured option).

For end-user applications, I don't tend to like automagically picking up the context on each call, specifically because it tends to make programmers act as if their culture is the only one that exists (usually English), which leads to things like thinking `Substring` is universally usable.  Normally what I'd do is pick it up during application start and inject it where required, overridable via a .conf or similar.  In many cases, too, you're going to be wanting to make any formatting explicit (which may have legal requirements).

**Comment by Clockwork-Muse** [comment]
So I guess the real question/issue here is, why did the reported/used culture of the machine change.  Is this a .NET core thing only, or did it actually change on the machine itself?

**Comment by JoshClose** [comment]
Yeah, I see your point. My app has no way for the user to change their culture, so I'd have to set it via config. Do you see a reason why using `CultureInfo.DefaultThreadCurrentCulture` and `CultureInfo.DefaultThreadCurrentUICulture` would be bad instead of explicitly using it in every place that can take a culture?

I'm using a fresh Ubuntu 18 install on Digital Ocean. The locale was set to `C.UTF-8` instead of `en_US.utf8`. I don't know if that's a Ubuntu 18 thing, or the way Digital Ocean has their default config for the droplets set up. I changed it to `en_US.utf8` and everything works as expected.

**Comment by stephentoub** [comment]
> Looks like it's recommended to use C.UTF-8 instead of en_US.utf8 now. If this is the case, it probably needs to be handled in .NET Core because it shows up as en_US-POSIX for the culture.

cc: @tarekgh, @krwq

**Comment by tarekgh** [comment]
@JoshClose 

> Looks like it's recommended to use C.UTF-8 instead of en_US.utf8 now. If this is the case, it probably needs to be handled in .NET Core because it shows up as en_US-POSIX for the culture.

from where you are getting this recommendation? It is not recommended to use the POSIX or C as its collation behavior is not what most people expect. you may use Invariant culture or en-US is good.

**Comment by tarekgh** [comment]
> Yeah, I see your point. My app has no way for the user to change their culture, so I'd have to set it via config. Do you see a reason why using CultureInfo.DefaultThreadCurrentCulture and CultureInfo.DefaultThreadCurrentUICulture would be bad instead of explicitly using it in every place that can take a culture?

I am not seeing any reason why not using CultureInfo.DefaultThreadCurrentCulture and CultureInfo.DefaultThreadCurrentUICulture as these APIs introduced originally for the purpose you are specifying. Just ensure the user of your app not worried about overriding the default cultures.
One small note, UWP apps working differently though. I can  give more info about that if you are interested in that.

**Comment by tarekgh** [comment]
I am closing this issue but feel free to send any question if you still want some follow up. Thanks.

**Comment by JoshClose** [comment]
`C.UTF-8` is the default for Ubuntu 18 (at least on the Digital Ocean images). I was looking around for what that was the other day and found several places stating that should be used instead of `en_US.utf8`.

If this is the case or even if it's an option, .NET should probably handle it better than `Unknown Locale (en-US-posix)`
