### ISSUE TITLE
Why doesn't System.Security.Claim have a parameterless constructor?

### ISSUE THREAD

**Issue by yetanotherchris** [dotnet/corefx#32658]
I'm trying to deserialize `Claim` objects as part of an Aspnet.Identity project, and running into problems with System.Security.Claim as it doesn't have a parameterless constructor.

I was wondering what the design decision is for the object requiring a type and value? It's a POCO after all isn't it? All logic for it happens in the store responsible for storing and checking it.

Chris

**Comment by yetanotherchris** [comment]
It looks like the class's responsibility is to serialize as well, so I'm assuming `Claim` is not intended to be JSONified (or any other text based serialization). Is this right?

**Comment by bartonjs** [comment]
I presume that it doesn't have a default ctor because none of the properties are assignable (or at least most aren't).  I assume that none of the properties are assignable because readonly objects are easier to work with (they can be used as dictionary keys safely, et cetera).

Maybe @brentschmaltz would have more insight than that, though.

The workaround is probably to make a `SerializableClaim` which is just a property bag that has a method to build a System.Security.Claims.Claim object via the long ctor.

**Comment by brentschmaltz** [comment]
@yetanotherchris @bartonjs 	
Some history
in designing the Claim model in 2006, we assumed a claim needed at least two items: type and value. We landed on value being a 'string' rather than object, to avoid the issue of serialization and the observation most values were string. The property ClaimValueType is a hint for dealing with JSON.

@bartonjs yes, we didn't want to be checking for null all over the place. 

We introduce a new serialization model a couple of years ago, although there is a bug we need to fix before we can use the model.

**Comment by yetanotherchris** [comment]
Not having to null check makes perfect sense, and something that should be used more often. The problem is probably at the Microsoft.AspnetIdentity side, as their `IUserClaimStore<T>` has a dependency on the `Claim` object, which makes it very hard to write a custom NoSQL/DocumentDB implementation without writing lots of custom serialization using Jil or another serializer.

I'll close the issue though and raise it with the identity team, but given the contract is already there for `IUserClaimStore` I can't see it changing.
