### ISSUE TITLE
Unexpected assembly version in assembly manifest

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/corefx#32767]
_From @JeremyTCD on October 10, 2018 7:51_

## Summary
MSBuild is generating assemblies with unexpected assembly versions in their manifests.

### Steps to reproduce
I've created a [minimal reproduction repository](https://github.com/JeremyTCD/IssueReproduction.AssemblyManifestTest) for this issue. The following are its contents:

- AssemblyManifestTest.csproj:
  ```xml
  <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
          <TargetFramework>netstandard2.0</TargetFramework>
      </PropertyGroup>
      <ItemGroup>
        <PackageReference Include="System.Buffers" Version="4.5.0" />
      </ItemGroup>
  </Project>
  ```

- Test.cs:
```c#
  using System.Buffers;

  namespace AssemblyManifestTest
  {
      class Test
      {
          public void DoSomething()
         {
              byte[] test = ArrayPool<byte>.Shared.Rent(10);
          }
      }
  }
```
  Simple class that utilizes types from the `System.Buffers` assembly.

I build the project using:
```
dotnet msbuild
```
where `dotnet msbuild -version` prints:
```
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

15.7.179.6572
```

### Expected  behavior
The `System.Buffers` Nuget package (v4.5.0) multi-targets `netstandard2.0` and `netstandard1.0`. Its `netstandard2.0` folder contains the version `4.0.3` assembly whilst its `netstandard1.0` folder contains the `4.0.2` assembly.  

Therefore, the generated assembly, "bin/release/**netstandard2.0**/AssemblyManifestTest.dll", should have the following dependency in its manifest:
```
.assembly extern System.Buffers
{
  .publickeytoken = (CC 7B 13 FF CD 2D DD 51 )
  .ver 4:0:3:0
}
```
Note the expected assembly version, `4:0:3:0`.

### Actual behavior
The generated assembly, "bin/release/**netstandard2.0**/AssemblyManifestTest.dll", has the following dependency in its manifest:
```
.assembly extern System.Buffers
{
  .publickeytoken = (CC 7B 13 FF CD 2D DD 51 )
  .ver 4:0:2:0
}
```
Note the actual assembly version, `4:0:2:0`.

### Why this is a problem
When I reference the `AssemblyManifestTest` library from a `net462` console application, the following happens:
- MSBuild grabs the version `4.0.3` assembly from the `netstandard2.0` folder.
- The runtime throws a ` System.IO.FileLoadException` exception:
  ```
  System.IO.FileLoadException: Could not load file or assembly 'System.Buffers, Version=4.0.2.0, 
  Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located 
  assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 
  0x80131040)
  ```
The exception is thrown because the `System.Buffers` assembly version in `AssemblyManifestTest.dll` is unexpectedly `4.0.2` (and `System.Buffers` is strongly named).  

### Notes 
The generated `.deps` file, "bin/release/**netstandard2.0**/AssemblyManifestTest.deps.json", has the following depedency:
```json
"System.Buffers/4.5.0": {
        "runtime": {
          "lib/netstandard2.0/System.Buffers.dll": {
            "assemblyVersion": "4.0.3.0",
            "fileVersion": "4.6.26515.6"
        }
    }
}
```
It correctly lists the "assemblyVersion" as "4.0.3.0", so it seems like just the assembly manifest that is off.

Edit: Simplified example

_Copied from original issue: Microsoft/msbuild#3846_

**Comment by safern** [comment]
From looking deeper into this and talking to @ericstj this is by design and the package doesn't actually have a bug in it. This are the reasons:

- The netstandard2.0 reference assembly is pinned to 4.0.2.0 version because the netcoreapp implementation became part of the .NET Core shared framework and we need to match our inbox implementation in order to not fail.
- Because we're stuck with the netstandard2.0 reference assembly being pinned, for the System.Buffers 4.5.0 package we added a net45 reference assembly with 4.0.3.0 version so that we don't hit the issue described here. 
- Msbuild should be creating the assembly redirect automatically when a desktop app references a netstandard library that contains a package reference where the netstandard reference and the desktop reference assembly within that package reference have different assembly versions, however this automatic generation is only enabled when the full framework (net4*/desktop) project has a PackageReference within it, then msbuild will look at transitive references and generate the necessary binding redirects.

@JeremyTCD I've forked your repro app and added a desktop ConsoleApp that references your test library and added a msbuild property to get transitive references when there are not PackageReference in the project.

https://github.com/safern/IssueReproduction.AssemblyManifestTest/blob/master/ConsoleApp1/ConsoleApp1.csproj#L15-L17

If you restore and build the console app in the bin folder you will find `ConsoleApp1.exe.config` file containing this binding redirect: 
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

You can look at App.config file that I didn't add that redirect manually: 
https://github.com/safern/IssueReproduction.AssemblyManifestTest/blob/bcc847b551f9837577426604126bb555a19a3f3e/ConsoleApp1/App.config#L1-L6

So if you don't plan on having package references I suggest adding the property to your project or switching out from packages.config into `<PackageReference>` items in your .csproj.
```xml
<RestoreProjectStyle>PackageReference</RestoreProjectStyle>
```
There are a bunch of related issues that help understand this problem: 
https://github.com/dotnet/corefx/issues/32511
https://github.com/dotnet/corefx/issues/32457
https://github.com/aspnet/AspNetCore/issues/3544
