### ISSUE TITLE
Expose current capacity on more collection classes

### ISSUE THREAD

**Issue by drieseng** [dotnet/corefx#32785]
The following collection classes allow the initial capacity to be set:

* ConcurrentDictionary\<TKey, TValue>
* Dictionary\<TKey, TValue>
* HashSet\<T>
* **List\<T>**
* Queue\<T>
* **SortedList\<TKey, TValue>**
* Stack\<T>

However, only those collections marked in bold actually allow one to obtain the current capacity.
I sometimes use the **Capacity** property in unit tests to ensure collections were created with the correct initial capacity (to avoid resizing).

Would such a PR be accepted (after API review)?

**Comment by Wraith2** [comment]
Dictionary doesn't directly honour that capacity because it requires that the bucket array be prime number sized so what it will do it take that number and work out the next prime for the starting capacity. So in this case at least the starting capacity is a hint not an absolute. If you wanted to get back the real capacity it would have to be stored which would cause the in memory size of every dictionary compilation and instance to increase, not good.

I'm not very familiar with the ConcurrentDictionary internals but since it's concurrent it will do complex operations that boggle the mind of mere mortals. It seems unlikely that getting a capacity count would be non-blocking.

IF a collection exposes a capacity argument allowing construction is it not part of the contract that it attempt to honour that request? Dictionary for example will do so even though it doesn't use the absolute. Does this really need testing outside corefx where the types are implemented?

**Comment by svick** [comment]
[`List<T>.Capacity`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.capacity) also has a setter, which lets you adjust its capacity even after construction. Are you asking for that in the newly introduced `Capacity` properties too?

**Comment by drieseng** [comment]
Personally, I'm only interested in the getter.
However, for consistency it may be a good idea to add a setter too.
Apparently, I'm not the first to have a need for [this](https://stackoverflow.com/questions/17338428/why-dont-stackt-and-queuet-have-capacity-property-while-listt-does).

**Comment by MaxShoshin** [comment]
I'm intresting in setters.

If collection is used to store a lot of items (1 mln of capacity for example) if we add one more element it will reallocate inner storage to store at least 2mln of items. What if I never use 99% of extra space?

Currently with `List` before `Add` I can check capacity and set it to appropriate number to change strategy of growth. But it is not possible with for example `Dictionary`.

[More details](https://stackoverflow.com/questions/46068944/how-to-avoid-extra-space-allocation-when-using-standard-collections-and-storing)

**Comment by danmosemsft** [comment]
This wasn't what was asked, but related - note that `Dictionary<K,V>` now has `int EnsureCapacity(int capacity)` and `public void TrimExcess(int capacity)` / `public void TrimExcess() `. That addresses the more common feedback that there is no way to pre-size dictionaries nor indicate that you no longer need a potentially large backing capacity.

@Wraith2 is correct that `Dictionary<K,V>` does not need to store the originally specified capacity and we would not want to grow all dictionaries by 4 bytes to store it. We could expose the size of the `_entries` / `_buckets` but that seems of marginal value if iti s to just to enable a unit test to verify that they are "at least as large" as what was originally requested.

Let me know if I misundestand the need.

**Comment by drieseng** [comment]
@danmosemsft We could indeed limit this to **Stack\<T>** and **Queue\<T>**. Should we add both a getter and setter for **Capacity** (like we have on **List<T>** and **SortedList\<T>**), or only a getter but add `int EnsureCapacity(int capacity)` and `void TrimExcess(int capacity) / public void TrimExcess()`?

**Comment by danmosemsft** [comment]
The changes to dictionary were motivated by performance issues in real world apps. I think is should be the same here, certainly for those methods, but I do not have strong objection to aCapacity getter, as it is so trivial, even though it seems only marginally useful.

**Comment by danmosemsft** [comment]
@safern owns collections

**Comment by safern** [comment]
I don't feel a strong motivation to expose those members in collections specially because Capacity doesn't really tell much to developers as they grow different from collection to collection and I don't think it has any interesting useful scenarios in real world apps. It is somehow compared to StringBuilder's capacity property: https://github.com/dotnet/corefx/issues/32932#issuecomment-431888223

If you're only interested in this getter for testing purposes wouldn't you be able to access the array through reflection and get the length? 

I'm not even sure this would make the review round because of what I just mentioned above.

**Comment by drieseng** [comment]
I understand, and I agree it's not an important addition.
I do wonder why it was considered ok for **List\<T>** and **SortedList\<TKey, TValue>**, and why that motivation would not apply to **Stack\<T>** and **Queue\<T>**?

**Comment by danmosemsft** [comment]
Probably unintentional inconsistency from long ago...

I'm going to close this as it seems answered and resolved.

**Comment by Grauenwolf** [comment]
The string builder comment made me think of something. In some object pooling scenarios, you may want to know the capacity so that you can hand over an appropriately sized collection from the pool. You may also want to avoid returning an overly large collection to the pool.

How often this actually occurs in real life is unknown to me.
