### ISSUE TITLE
Proposal: add implicit conversation from Memory to Span, ReadOnlySpan and from ReadOnlyMemory to ReadOnlySpan

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#32782]
Proposal:
1. Add implicit conversation from Memory to Span and ReadOnlySpan.
2. Add implicit conversation from ReadOnlyMemory to ReadOnlySpan.

**Comment by stephentoub** [comment]
IIRC, we previously explicitly decided against having those because there's measurable cost involved in getting a span from a memory, and we want developers to be explicit then about when they do it, preferring to do it once and then repeatedly operate on the resulting span, rather than accidentally repeatedly operating on the memory via passing it to things that accept structs and paying the implicit cast cost each time.  @ahsonkhan?

**Comment by ahsonkhan** [comment]
Given this could result in an unexpected performance trap, I am closing this issue.
