### ISSUE TITLE
ZipFileExtensions.ExtractToDirectory do not respect OS specific directory separator for subfolders

### ISSUE THREAD

**Issue by hopix** [dotnet/corefx#32788]
When ZIP file (which has files in subfolders) is created on Windows and then extracted on Linux it creates wrong files names for files which are in subfolders.

Example:
Windows relative file in ZIP file: `subFolderA\file1` will be on Linux extracted to file name: `subFolderA\file1` (but the whole string `subFolderA\file1` is filename! `file1` is not placed to subfolder `subFolderA`. Correctly it should be `subFolderA/file1`.

ZipFileExtensions.ExtractToDirectory needs to correctly handle directory separator for subfolders.

Tested on .net core 2.1.4.

**Comment by Wraith2** [comment]
The simple case fix for this is to check if `Path.AltDirectorySeparatorChar` is present and `Path.DirectorySeparatorChar` isn't and assume that they're transposable. 

What should happen in the case where a path contains both characters? As you point out it's legal to have a \ in a filenames on at least some non-ntfs filesystems so mixed cases can be created but there is no way to identify the source platform and even if it were possible that wouldn't indicate intent, it would only allow further possibly invalid heuristic choices to be made. I think this may be a case where throwing an `InvalidOperationException` may be the cleanest way out.

**Comment by MarcoRossignoli** [comment]
Or using `Path.GetDirectoryName` and create folders
```
Console.WriteLine(Path.GetDirectoryName(@"file1"));
Console.WriteLine(Path.GetDirectoryName(@"subFolderA\file1"));
Console.WriteLine(Path.GetDirectoryName(@"subFolderA/file1"));
Console.WriteLine(Path.GetDirectoryName(@"subFolderA/subfolderB\file1"));
```
results
```

subFolderA
subFolderA
subFolderA\subfolderB
```

**Comment by Wraith2** [comment]
That's a choice to map all directory separators to local. If that's what gets implemented and documented it's fine but it isn't the only option.

**Comment by carlossanlop** [comment]
@hopix thank you for reporting the bug.

I have a few questions that will help me narrow down the problem, because I am unable to reproduce it:

1. What did you use to generate your zip file? You mentioned it was created in Windows, but I wonder what was the tool you used: .NET Core, Windows Explorer, 7-zip, WinZip?
2. What Windows version were you using?
3. What Linux version/flavor did you use to extract the file?
4. Do you have a chance to extract the zip file using a .NET Core version higher than 2.1.4?


These are the tests I ran:

- I generated 4 zip files. All of them zipped a folder with a subfolder inside, and a txt file inside the subfolder.
     - The first file was generated with a small .NET Core app that used ZipFile.CreateFromDirectory. I ran the program from an NTFS drive in Windows 10.
     - The second file was generated with the same app, but in FAT32 in Windows 10.
     - The third file was generated using Windows Explorer (right click - Send To - Compressed (zip) folder) in an NTFS drive in Windows 10.
     - The fourth file was generated with Windows Explorer too, but from a FAT32 drive.

Then I copied all the files both to Ubuntu and to Mac, and using a .NET Core app that consumes ZipFileExtensions.ExtractToDirectory, I extracted the 4 zip files. They were all extracted without problems.

The .NET Core app that extracted the files was compiled with versions 2.1.302, 2.1.505 and 2.1.602, and none of them reproduced the issue. All the zip files were extracted correctly, with the file tree intact.

It might be worth mentioning that Windows forbids the usage of both \ and /, according to the [official docs](https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file), and when the user attempts to create a file in Linux/Unix using the \ character in the filename, that character is ignored and not included in the final filename after pressing enter.

**Comment by hopix** [comment]
Answers to you questions:
1. PowerShell CmdLet Compress-Archive
2. Windows 10 64-bit.
3. Using self contained deployment of .net core for runtime `debian.9-arm` running on Raspberry Pi HW with lastest raspbian_lite OS image - https://downloads.raspberrypi.org/raspbian_lite_latest
4. Will get back to you if it will be possible. - May be could you share your source of your .net core test app to extract zip? It might be easier for me to try.

**Comment by carlossanlop** [comment]
Hi @hopix,

Thanks for your reply and your patience. I found the root cause and I have a potential fix for this.

### Summary

During extraction, when iterating through the ZipArchiveEntry instances, my proposed fix is to check if the fullName string contains "\" characters and convert them to "/" before attempting to create the subfolder.


### Details

I generated a bunch of zip files using different tools:

- .NET Core (Windows)
- .NET Core (Ubuntu)
- 7-Zip (Windows)
- Windows File Explorer: Right click -> Send to -> Compressed (zip) folder
- PowerShell Compress-Archive command
- Ubuntu bash shell zip command

All the zip files had this structure:

```
file.zip
  Folder/
    SubFolder/
      SubSubFolder/
        file.txt
```

I ran the program in Windows and in Ubuntu.

The program was fed each one of the generated zip files, printed all the ZipArchiveEntry fullNames, and then attempted to extract the zip file. Here are the results:


#### When running the program in Windows:

-------- Created with .NET Core (Windows) --------
Entries:
- Folder/SubFolder/SubSubFolder/text.txt

**RESULT**: Zip file extracted successfully

-------- Created with .NET Core (Ubuntu) --------
Entries:
- Folder/SubFolder/SubSubFolder/text.txt

**RESULT**: Zip file extracted successfully

-------- Created with 7-Zip (Windows) --------
Entries:
- Folder/
- Folder/SubFolder/
- Folder/SubFolder/SubSubFolder/
- Folder/SubFolder/SubSubFolder/text.txt

**RESULT**: Zip file extracted successfully

-------- Created with Windows File Explorer --------
Entries:
- Folder/SubFolder/
- Folder/SubFolder/SubSubFolder/
- Folder/SubFolder/SubSubFolder/text.txt

**RESULT**: Zip file extracted successfully


-------- Created with zip command (Ubuntu) --------
Entries:
- Folder/
- Folder/SubFolder/
- Folder/SubFolder/SubSubFolder/
- Folder/SubFolder/SubSubFolder/text.txt

**RESULT**: Zip file extracted successfully


-------- Created with PowerShell --------
Entries:
- Folder\SubFolder\
- Folder\SubFolder\SubSubFolder\text.txt

**RESULT**: Zip file extracted successfully



#### When running the program in Ubuntu:

-------- Created with .NET Core (Windows) --------
Entries:
- Folder/SubFolder/SubSubFolder/text.txt

**RESULT**: Zip file extracted successfully


-------- Created with .NET Core (Ubuntu) --------
Entries:
- Folder/SubFolder/SubSubFolder/text.txt

**RESULT**: Zip file extracted successfully


-------- Created with 7-Zip (Windows) --------
Entries:
- Folder/
- Folder/SubFolder/
- Folder/SubFolder/SubSubFolder/
- Folder/SubFolder/SubSubFolder/text.txt

**RESULT**: Zip file extracted successfully


-------- Created with Windows File Explorer --------
Entries:
- Folder/SubFolder/
- Folder/SubFolder/SubSubFolder/
- Folder/SubFolder/SubSubFolder/text.txt

**RESULT**: Zip file extracted successfully


-------- Created with zip command (Ubuntu) --------
Entries:
- Folder/
- Folder/SubFolder/
- Folder/SubFolder/SubSubFolder/
- Folder/SubFolder/SubSubFolder/text.txt

**RESULT**: Zip file extracted successfully


-------- Created with PowerShell --------
Entries:
- Folder\SubFolder\
- Folder\SubFolder\SubSubFolder\text.txt

**RESULT**: EXCEPTION: Invalid argument

```
at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName, Boolean overwrite)
at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding, Boolean overwrite)
at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName)
at CompressionExamples.Program.ExtractZipFile(String fileName, String filePath) in /home/usr/repos/carlossanlopTools/CompressionExamples/CompressionExamples/Program.cs:line 177
```


#### Proposed fix

This is the function I will modify:

corefx\src\System.IO.Compression.ZipFile\src\System\IO\Compression\ZipFileExtensions.ZipArchive.Extract.cs:
```
        internal static void ExtractRelativeToDirectory(this ZipArchiveEntry source, string destinationDirectoryName, bool overwrite)
        {
		...
            string fileDestinationPath = Path.GetFullPath(Path.Combine(destinationDirectoryFullPath, source.FullName)); 
           ^--- Replace "\" with "/" in FullName before combining
```

**Comment by carlossanlop** [comment]
Hi again @hopix,

The change I proposed would be a breaking change so we won't check it in: .NET Core is doing the right thing (more details below), while PowerShell (and potentially other tools that create zip files) is not.

Powershell creates its zip file by adding each individual entry manually using Windows paths with "\" instead of "/" as directory separator (more details below). We will report the bug to PowerShell.

I have some workarounds for you:

1. You can write a function that takes the zip file and substitutes the files inside it with the proper name. This is not an optimal approach because if the zip file contains too many entries, or some entries are too large, the function could use a lot of resources, so use it with caution.

```cs
	void SubstituteZipArchiveEntryPaths()
	{
		string nameFileZip = "CreatedWithPowerShellCompress-Archive.zip";
		
		// Open your zip file generated with PowerShell
		using (var zip = ZipFile.Open(nameFileZip, ZipArchiveMode.Update))
		{
			var toChange = new List<string>();
			foreach(var entry in zip.Entries)
			{
				Console.WriteLine(entry.FullName);
				if (entry.FullName.Contains('\\'))
				{
					toChange.Add(entry.FullName);
				}
			}
			
			// Substitute the original entry with a new entry that contains a name using the correct separator
			foreach(var oldName in toChange)
			{
				var entry = zip.GetEntry(oldName);
				
				var newName = entry.FullName.Replace('\\', '/');
				var newEntry = zip.CreateEntry(newName);

				using (Stream oldStream = entry.Open())
				using (Stream newStream = newEntry.Open())
				{
					oldStream.CopyTo(newStream);
				}
				
				entry.Delete();
			}
		}
	}
```

2. You can write a function that iterates throught the zip file entries and before creating their subfolders, you make sure the "\" character is substituted with a "/", you create the folder, then you extract the entry into that subfolder.

```cs
	void ExtractPowerShellCompressArchiveFile()
	{
		string pathRoot = Directory.GetCurrentDirectory();
		string nameDirectory = "extracted";
		string pathDirectory = Path.Combine(pathRoot, nameDirectory);
		string nameFileZip = "CreatedWithPowerShellCompress-Archive.zip";
		string pathFileZip = Path.Combine(pathRoot, nameFileZip);

		if (Directory.Exists(pathDirectory))
		{
			Directory.Delete(pathDirectory, true);
			Directory.CreateDirectory(pathDirectory);
		}

		using (var zip = ZipFile.Open(pathFileZip, ZipArchiveMode.Read))
		{
			foreach(var entry in zip.Entries)
			{
				Console.WriteLine("Entry wrong path: {0}", entry.FullName);
				string correctPath = entry.FullName.Replace("\\", "/");
				Console.WriteLine("Entry right path: {0}", correctPath);
				FileInfo extractedFileInfo = new FileInfo(Path.Combine(pathDirectory, correctPath));
				string entryDirectory = extractedFileInfo.Directory.FullName;
				if (!Directory.Exists(entryDirectory))

				{
					Console.WriteLine("Creating entry directory: {0}", entryDirectory);
					Directory.CreateDirectory(entryDirectory); 
				}
				// Find out if the entry is a directory or not
				if (Path.GetFileName(extractedFileInfo.FullName).Length == 0)
				{
					if (!Directory.Exists(extractedFileInfo.FullName))
					{
						Console.WriteLine("Creating directory entry: {0}", extractedFileInfo.FullName);
						Directory.CreateDirectory(extractedFileInfo.FullName);
					}
				}
				else
				{
					Directory.CreateDirectory(Path.GetDirectoryName(extractedFileInfo.FullName));
					Console.WriteLine("Extracting entry: {0}", extractedFileInfo.FullName);
					entry.ExtractToFile(extractedFileInfo.FullName);
				}
			}
		}
	}
```

3. .NET Framework (>=4.6.1) and .NET Core offer an [AppContext Switch](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/mitigation-ziparchiveentry-fullname-path-separator) to mitigate this issue, by allowing the user to turn off the use of backslash as separator in a specific app consuming ZipArchiveEntry, although the instructions to use this with PowerShell are not entirely clear to me. If you decide to follow this approach, let me know if you find a way to apply it to PowerShell.


### Details

This is not a bug on the .NET Core side because:

1. We make sure our code generates the zip file entries always using the "/" character as a directory separator. This issue was [fixed back in Jan 2015](https://github.com/dotnet/corefx/commit/7b9331e89a795c72709aef38898929e74c343dfb) and apparently it was backported to .NET Framework.

2. When extracting files, we don't make assumptions about the character used as a directory separator, because:
	a) Sometimes zip is used to pack/compress other kind of data besides files (database keys for example). In that case, we need to make sure not to assume there's a "directory separator", and simply append the destination directory absolute path with each entry's path (which happens to be the fullName).
	b) In Linux/Unix, it is possible (although rare) to create files/folders with the "\" character. It might not be the best practice due to cross-platform incompatibility issues, but .NET Core tries to be flexible about this.

3. The PowerShell cmdlet Compress-Archive is creating each entry individually using ZipArchive.CreateEntry by passing a path with Windows paths ([here](https://github.com/PowerShell/Microsoft.PowerShell.Archive/blob/master/Microsoft.PowerShell.Archive/Microsoft.PowerShell.Archive.psm1#L828) and [here](https://github.com/PowerShell/Microsoft.PowerShell.Archive/blob/master/Microsoft.PowerShell.Archive/Microsoft.PowerShell.Archive.psm1#L872)). Note: This open source code is part of the latest PowerShell version. Windows includes an older version (not open source) which seems to also have this bug.

**Comment by carlossanlop** [comment]
I reported the bug in the PowerShell repo and will close this issue now.
