### ISSUE TITLE
CtorTests.InvalidCertificateBlob failed on OS X in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3282]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_mac_debug_tst/31/console
```
21:55:11    System.Security.Cryptography.X509Certificates.Tests.CtorTests.InvalidCertificateBlob [FAIL]
21:55:11       Assert.Equal() Failure
21:55:11       Expected: 218595386
21:55:11       Actual:   -2146233088
21:55:11       Stack Trace:
21:55:11             at System.Security.Cryptography.X509Certificates.Tests.CtorTests.InvalidCertificateBlob()
```

**Comment by bartonjs** [comment]
`-2146233088` is `COR_E_EXCEPTION`, so something was definitely off at the time.

Since this was reported in September, the test isn't disabled or platform specific, we've changed our minimum OpenSSL version since then, and no one seems to be complaining that this is still happening (however infrequently); I'm going to call this closed.
