### ISSUE TITLE
Add an API to retrieve number of physical CPUs

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/corefx#3284]
`Environment.ProcessorCount` returns the number of logical processors, i.e. number of logical cores available after things like Hyper-threading are taken into account. In some cases however it is important to know the number of actual physical cores rather than logical cores. E.g. in the ASP.NET 5 Kestrel web server, we need to create a number of threads for IO work and our testing has shown that performance is better when there is a thread per physical core rather than logical, in the case that Hyper-threading is enabled.

**Comment by stephentoub** [comment]
Thanks, @DamianEdwards.

Can you elaborate more on the tests you ran and the perf results? Presumably in a real environment the web server would be the primary thing running on the box? Why wouldn't hyperthreading just be disabled on the machine if that led to increased performance? I'd expect there would be a variety of machine-wide configuration that would be done to get utmost throughout, no?

As for the specific API, what do you propose?

**Comment by jasonwilliams200OK** [comment]
:+1: 
Some useful refs for implementation details:

Win32/WMI based solution: http://stackoverflow.com/a/188526 by @stephbu
Pure C# solution: http://stackoverflow.com/a/189371 by @jslicer
/cc @JonHanna :)

**Comment by JonHanna** [comment]
Hmm. I perhaps shouldn't have +1'd that answer since it didn't actually give the number of processors.

What it did give, the number of logical cores currently available to the process when processor affinity is considered, is certainly a useful thing to get too, though.

**Comment by stephentoub** [comment]
> Some useful refs for implementation details

Assuming we went ahead with the API, my guess is that on Windows we'd probably want to use GetLogicalProcessorInformationEx with RelationProcessorCore, on Linux we'd probably want to get the info from /procfs/cpuinfo, and on OS X we'd probably want to use sysctl or sysctlbyname.  But it's possible there are better options.

**Comment by jasonwilliams200OK** [comment]
Some more resources:

* C++11 approach: http://stackoverflow.com/a/2921632 (but it will not distinguish between physical CPUs form hyper-threads).
* http://stackoverflow.com/a/3082553 (one comment suggested that it won't work on latest Intel processor, and hence the answer is obsolete).
* These seem like the perfect solutions: http://stackoverflow.com/a/24824554 & http://stackoverflow.com/a/29761237
* Based on http://stackoverflow.com/a/29414957 answer, `Open MPI logo 	
Portable Hardware Locality (hwloc)` (http://www.open-mpi.org/projects/hwloc/) library provides all kinds of information and is buildable on Windows as well, as you can find here: https://github.com/open-mpi/hwloc. My vote is for using this library as a submodule, to emit all the salient parts of this API in .NET. :) Not sure about the BSD & MIT licenses compatibility though.
* Finally the pure POSIX approach: http://stackoverflow.com/a/2693994.

**Comment by DamianEdwards** [comment]
@stephentoub I need to do a more thorough investigation, but as it is now, configuring Kestrel to use as may threads for IO as there are CPUs results in worse performance in simple benchmarks than current CPUs / 2. Like I said, I need to investigate further as to whether this is an artifact of Hyper-Threading or just creating too many IO threads in general (and leaving less CPU time for no IO work).

Ultimately, we're trying to settle on a good default for Kestrel. The setting is configurable within the app and of course all apps should always measure and change settings for their specific work profile but we'd like to try and at least have a decent performing default based on what we can easily test and determine from the runtime APIs.

**Comment by stephentoub** [comment]
Thanks, @DamianEdwards.  I completely agree having a good default is important, and we should ensure the right APIs are exposed to enable your picking such a good level.  I just want to make sure we're setting that default based on the right information.

In your benchmarks, the optimal level for your I/O thread count was exactly at the number of physical cores, or was it higher or lower than that?  

If you disable hyper-threading on the machine, the optimal number is then equal to Environment.ProcessorCount and not higher or lower?

Have you tried changing the power settings on the machine?  Some configurations will put cores to sleep and only turn them back on over time based on heuristics, so it's possible you could also be running up against that rather than simultaneous multithreading.

Also, how close is your simple benchmark to the real kinds of workloads we expect folks to develop?  That could potentially have a significant impact on what level you'd want to set this to.

Finally, assuming we did add the API, what would you want it to look like?  Environment.PhysicalProcessorCount?  Something else?  I believe @terrajobst has this on the agenda for an upcoming design meeting, so it'd be good to have the relevant info gathered by then.

**Comment by stephentoub** [comment]
@DamianEdwards, just wanted to check in on this.  Still investigating?

**Comment by stephentoub** [comment]
@DamianEdwards, any updates here? Thanks.

**Comment by DamianEdwards** [comment]
Sorry for the delay. I think we can live without this for now. We'll revisit this later if further testing determines it's useful.

**Comment by stephentoub** [comment]
Ok, sounds good.  Thanks.
