### ISSUE TITLE
Decoder.Convert overloads that take pointers should accept null if count is 0

### ISSUE THREAD

**Issue by jazzdelightsme** [dotnet/corefx#32861]
I tried to use the `fixed` keyword to get a pointer to a `char[]`, and then I passed that pointer to `Decoder.Convert`. I found that sometimes I'd get an `ArgumentNullException`, which baffled me, because I had just barely allocated the `char[]`.

It turns out that `fixed` will give you a `null` pointer for a 0-length array, so that's where the null came from. I complained about that (the different behavior depending on length of the array), and one response I got was "Seems the bug comes from whatever underlying API decided to give special meaning to nullptr even in a counted range".

Ideally I'd be able to pass a null pointer to `Decoder.Convert`, and as long as `charCount` is also zero, it should be treated the same as a 0-length buffer.

C.f.: https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/Common/src/CoreLib/System/Text/Decoder.cs#L306

**Comment by danmosemsft** [comment]
@JeremyKuhne was the conclusion that it is correct for fixed to produce null pointer to 0 length array?

**Comment by GrabYourPitchforks** [comment]
FYI, here's a workaround for any method (such as p/invoke) that requires a non-null pointer, even if the input array is zero.length.

```cs
using System.Runtime.InteropServices;

public static class ArrayExtensions {
  public static ArrayWrapper<T> NotNullFixed<T>(this T[] array) {
    return new ArrayWrapper<T>(array);
  }

  public readonly struct ArrayWrapper<T> {
    private readonly T[] _wrapped;
    internal ArrayWrapper(T[] wrapped) {
      _wrapped = wrapped;
    }

    public ref T GetPinnableReference() {
      return ref MemoryMarshal.GetReference(_wrapped.AsSpan());
    }
  }
}

public unsafe class Program
{
  public static void Main()
  {
    char[] chars = new char[0];
    fixed (char* ptr = chars.NotNullFixed()) {
      Console.WriteLine((IntPtr)ptr);
    }
  }
}
```

**Comment by stephentoub** [comment]
IIRC, the underlying Win32 APIs fail if you give them a null pointer (I may be misremembering), so these .NET wrappers preemptively throw ArgumentNullException in that case. But it seems we could just add a `if (count == 0) return;`-like check before throwing... would help this case and would only add a check on a path that's already exceptional. @tarekgh? Or if I'm misremembering, maybe the null check could be removed entirely.

**Comment by jkotas** [comment]
If you use the Span overloads, you will be fine because of they do not suffer from this problem.

As for the pointer overloads, I think it should be ok to skip the check for null if the buffer is empty for all Encoding/Encoder/Decoder APIs that takes pointers and adjust the implementation for the few cases where it is implemented by calling the underlying OS API. The easy way to do that is to just make the pointer non-null. It is what the [Span overloads do](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Runtime/InteropServices/MemoryMarshal.Fast.cs#L91).  However, it is not going to be 100% fix to the problem because of Encoding types are extensible and any implementations out there that implements the current [documented contract](https://docs.microsoft.com/en-us/dotnet/api/system.text.decoder.convert?view=netcore-2.1#System_Text_Decoder_Convert_System_Byte__System_Int32_System_Char__System_Int32_System_Boolean_System_Int32__System_Int32__System_Boolean__) is still going to be broken.

**Comment by tarekgh** [comment]
I think it make sense to skip null checking when having 0 length buffer. I'll try to fix that. as  @jkotas mentioned this will not help for anyone implemented custom decoders.

**Comment by JeremyKuhne** [comment]
> was the conclusion that it is correct for fixed to produce null pointer to 0 length array?

It is correct as it has always done it- changing that behavior would be catastrophic. The thing we were looking at is that we now have the ability to pin spans directly in C#. We used to have to use `MemoryMarshal`, which does differ in how it treats empty arrays (as pointed out here). This difference was often overlooked or simply not understood.

``` C#
byte[] nullArray = null;
byte[] emptyArray = new byte[0];
fixed (byte* n = nullArray)
fixed (byte* e = emptyArray)
{
    Debug.Assert(n == null && e == null);
}

Span<byte> nullSpan = nullArray;
Span<byte> emptySpan = emptyArray;

fixed (byte* n = nullSpan)
fixed (byte* e = emptySpan)
{
    Debug.Assert(n == null && e == null);
}

fixed (byte* n = &MemoryMarshal.GetReference(nullSpan))
fixed (byte* e = &MemoryMarshal.GetReference(emptySpan))
{
    Debug.Assert(n == null && e != null);
}
```

**Comment by GSPP** [comment]
As a matter of API cleanliness a null pointer should never be accepted. All other .NET APIs do it the same way. It should not be conditionally accepted based on other data.

Callers need to work around the behavior of `fixed` which can produce a null pointer. Often, inserting a length check at the level of the caller is a good thing to do anyway to optimize for the zero length case which tends to be common.

**Comment by jkotas** [comment]
> As a matter of API cleanliness a null pointer should never be accepted. All other .NET APIs do it the same way.

Do you mean unmanaged null pointers? The .NET APIs are pretty inconsistent in handling unmanaged null pointers.

**Comment by GSPP** [comment]
I was not aware that the APIs are inconsistent about unmanaged null pointers. In that case my point becomes weaker. But I would argue the existing cases where null is accepted are dubious. This should not be repeated without a good reason. Performance could be a good reason but that single null check would not matter much in this case.

**Comment by tarekgh** [comment]
I have looked at the code and I am seeing it is not difficult to handle the 0 length with null pointer but in same time the change wouldn't be that trivial either for the following reasons:

- If we need to go with this change  we'll have to fix all APIs in all our Encoders and Decoders that accept a native pointers and length. We'll have to do it in GetChars, GetBytes, GetCharCount, GetByteCount and convert in all encoders/decoders we have.
-  Also Encoders and Decoders has states and   the APIs has multiples out parameters reporting the state. if we need to go with the change we'll have to ensure the state is correct as we used to work before and also we have to initialize the out parameters and ensure those initialize match the expectation. 

Considering that, I am inclining to say this is not worth to do it. just to handle this corner case which the callers should be able easily to do it. 

@jkotas what you think?

**Comment by jkotas** [comment]
> I would argue the existing cases where null is accepted are dubious.

It is fine to use `nullptr` as pointer for zero-length buffer in most of the unmanaged C/C++ code out there. Rejecting `null` for zero-length unmanaged buffers in C# conflicts with it. It is where I see the key problem in this issue.

> If we need to go with this change we'll have to fix all APIs in all our Encoders and Decoders that accept a native pointers and length.

Right, there are many places in System.Text namespace where this issue is replicated.

>  if we need to go with the change we'll have to ensure the state is correct as we used to work before and also we have to initialize the out parameters and ensure those initialize match the expectation.

Depends on the fix. If the fix was done by simply relaxing the argument validation like `bytes == null` -> `bytes == null && byteCount != 0`, you would not have this problem.

> Considering that, I am inclining to say this is not worth to do

Fine with me. Another argument for not doing this that the fix would be incomplete. It would not apply to custom Encoding/Decoding implementations out there that copied the existing validation.

As I have said, this can be also worked around by using `Span<T>` overloads that do not suffer from this issue and generally safer.
