### ISSUE TITLE
Could not find special directory 'My Documents'.

### ISSUE THREAD

**Issue by paul1956** [dotnet/corefx#32862]
Environment.GetFolderPath(SpecialFolder.Personal) returns empty string on test machine Windows.10.Nano.Amd64.Open-x64-Debug

**Comment by JeremyKuhne** [comment]
This is by design, Windows doesn't provide all of the special folder values on Nano. When/if Windows actually provides this data we'll "light up".

https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/tests/System/EnvironmentTests.cs#L441

https://github.com/dotnet/corefx/issues/19110

**Comment by paul1956** [comment]
Thanks I somehow missed that this was Nano again.
