### ISSUE TITLE
DateTime overflow in .NET

### ISSUE THREAD

**Issue by DavidKiff** [dotnet/corefx#32907]
Is this a bug?

DateTime.TryParse("9999-12-31T23:59:59.99999999Z", out var dateTime);

Throws an ArgumentOutOfRangeException (The added or subtracted value results in an un-representable DateTime.Parameter name: value).

I wouldn't expect **Try**Parse to throw, nor for my DateTime to be incremented by a day?  Perhaps loosing precision is better than overflowing the date?  Not sure.

https://stackoverflow.com/questions/52890501/datetime-overflow-in-net?noredirect=1#comment92693767_52890501

**Comment by stephentoub** [comment]
> Is this a bug?

Certainly looks like one, at least the throwing part in TryParse.

cc: @tarekgh

**Comment by tarekgh** [comment]
I agree in general we shouldn't throw if we couldn't parse.  but I am not agreeing with the statement "Perhaps loosing precision is better than overflowing the date". this looks like rounding problem with floating points and it depends on the general approach of we are handling that in general and we should be consistent. if we round to next day  with other dates, then we should be doing that with the edge cases too. anyway, I'll try to take a look.

**Comment by Clockwork-Muse** [comment]
Relevant methods:
[ParseFraction](https://github.com/dotnet/coreclr/blob/44fd2693a85a35d2f4e532bb5a12f145224ee5bf/src/System.Private.CoreLib/shared/System/Globalization/DateTimeParse.cs#L467)
[ParseFractionExact](https://github.com/dotnet/coreclr/blob/44fd2693a85a35d2f4e532bb5a12f145224ee5bf/src/System.Private.CoreLib/shared/System/Globalization/DateTimeParse.cs#L3168)

The non-exact version is multiply-adding each successive digit by .1 (with the result hopefully never going above 1), whereas the exact version is multiplying the result by 10 for each successive digit, then dividing by `Pow10(length)` at the end.  Presumably this difference is to allow the non-exact version to parse an arbitrary number of digits safely.

Personally, I disagree with labeling this "fraction", or using `double`s.  While it's true that this represents a fraction-of-a-second, in the context of a `DateTime` this will almost always be understood to be some exact sub-second discrete tock; that is, an integer count of some smaller unit (even if `DateTime` itself is limited to 100-ns ticks).
Generally speaking, this also mandates _truncating_ any extra digits, because under that definition any sub-stored amount simply "hasn't moved to the next tock yet".  Note that truncation is effectively how time is recorded for logging: If we capture the instant before and after an event happens (assuming our clock will tock at least once between each read), then the best we can say is that the even happened on-or-after the earlier tock, and before the later tock.
Given the previous, it should become obvious why it's good practice to query date-time objects as lower-bound inclusive, upper-bound exclusive: It allows the queryier to specify only the precision they're interested in, rather than the full precision of the type (querying for the year 2018, for example, can be done by querying `2018 <= x < 2019`, rather than needing to specify month, day, hour...).  Rounding throws that completely out the window - you're changing the lower-bound bucket.  Calling `someDateTime.Date` is untrustworthy, now.

Note that Java and NodaTime both store/report a full nanosecond-precise instant (even if they're bound by the same limitations in hardware we are for getting accurate values).  I'm assuming somebody's data has been silently re-bucketed by this.
