### ISSUE TITLE
[QUESTION]Out-of-band/Inbox documentation

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/corefx#32926]
After this explanation https://github.com/dotnet/corefx/issues/32745#issuecomment-429113640 
Is there documentation to know if an assembly is OOB or Inbox, for instance Runtime->Assembly->OOB or Inbox?

**Comment by karelz** [comment]
I believe that each package that has pkg subdir is OOB (i.e. not inbox).
@ericstj can likely confirm

cc @danmosemsft @weshaggard @wtgodbe

**Comment by ericstj** [comment]
PKG subdirectory is necessary for something to be OOB (in the current release) but not sufficient.  The package is just a means for oobing.  The package may explicitly list a framework as [inbox](https://github.com/dotnet/corefx/blob/ac8fb6965658e32b7154ca8c8cc1c93652635892/src/System.Reflection.Emit.ILGeneration/pkg/System.Reflection.Emit.ILGeneration.pkgproj#L15).  In this example the package exists so that it can expose a reference assembly for netstandard, however it's implementation is inbox on netcoreapp (and thus the reference is frozen).

The Directory.Build.props will tell you if the library is inbox.  (EG: IsNetCoreApp means its inbox for netcoreapp, IsNetCoreAppRef=false means that only the implementation is inbox and the reference is not exposed by the framework).

For some packages, like System.Collections.Immutable they are both inbox and OOB, permitting folks to update them on top of the framework.

**Comment by MarcoRossignoli** [comment]
Thank's for explanation guys!
I close issue.
