### ISSUE TITLE
System.Collections.Immutable assembly considered Security Critical

### ISSUE THREAD

**Issue by NArnott** [dotnet/corefx#3293]
I'm writing a program where some untrusted code is running in a separate app domain.  I want this untrusted code to use various Immutables, but I get the following error:

`Attempt by security transparent method 'MyMethod' to access security critical method 'System.Collections.Immutable.ImmutableList.CreateBuilder<MyObject>()' failed.`

`Assembly 'MyAssembly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=**** is partially trusted, which causes the CLR to make it entirely security transparent regardless of any transparency annotations in the assembly itself.  In order to access security critical code, this assembly must be fully trusted.`

Why is the Immutable assembly considered security critical?  I would imaging this is an oversight and it should be Security Transparent.

**Comment by stephentoub** [comment]
cc: @weshaggard, @aarnott

**Comment by AArnott** [comment]
I'm in favor of such a change. I thought all the assemblies we distribute on NuGet such as this were security transparent anyway.

**Comment by morganbr** [comment]
Marking it transparent sounds reasonable to me. I'd be pretty surprised if it ever calls into critical code.

@NArnott , per the caution at https://msdn.microsoft.com/en-us/library/c5tk9z76(v=vs.110).aspx , we advise against using that to run untrusted code. (We're working on putting that somewhere more obvious since it's easy to miss right now).

**Comment by AArnott** [comment]
I have sent a private build to @NArnott asking for verification of the fix.
