### ISSUE TITLE
Enabling System.Console.WindowWidth and System.Console.CursorVisible properties in CoreFx

### ISSUE THREAD

**Issue by anuchandy** [dotnet/corefx#3294]
We are building a cross-platform command line tool which has support for displaying tables (using ascii chars) and showing progress. To render the table correctly we use WindowWidth and want to hide the cursor when we show progress.

**Comment by stephentoub** [comment]
@anuchandy, for these issues, we're generally aware that such members aren't available in the contracts.  If you're asking for them to be added, providing more details on the scenarios would be helpful.  Thanks for your interest.

**Comment by anuchandy** [comment]
@stephentoub thank you. The scenarios are:

We are building a cross-platform command line tool which has support for displaying tables (using ascii chars) and showing progress. To render the table correctly we use WindowWidth and we want to hide the cursor when we show progress.

**Comment by mellinoe** [comment]
We used WindowWidth in our command line helper class:

https://github.com/dotnet/buildtools/blob/master/src/common/CommandLine.cs#L1705

It was used to print out the "help/usage" message in a nicely-formatted table. It's much messier-looking now since I just hard-coded the width/height on .NET Core.

**Comment by pallavit** [comment]
This should be fixed as part of #3683
