### ISSUE TITLE
ValueTask.Exception property question/feature request

### ISSUE THREAD

**Issue by akarnokd** [dotnet/corefx#32977]
While working with the proposed C# 8 [`IAsyncEnumerable`](https://github.com/dotnet/corefx/issues/32640) design, I need to extract any potential `Exception` from `ValueTask` and `ValueTask<T>`. Both feature the `IsFaulted` property, just like `Task`, but unlike `Task`, there is no `Exception` property, thus I may have to go extra length (such as `AsTask().Exception`) to get hold of such exceptions.

I know `ValueTask<T>.Result` will throw, but `ValueTask` doesn't have a `Result` obviously.

Is there a way to get the known to exist `Exception` from both `ValueTask` types without much hassle (and without potential allocation)? Would it make sense to add the `Exception` property and implement it in a delegating fashion just like the other properties?

(I did search for mention of this property in hopes some design document dismissed it as unnecessary, but haven't found it.)

**Comment by Wraith2** [comment]
The design discussion is [here](https://github.com/dotnet/corefx/issues/27445) and mention of the exception property is made, judging from the conversation I think that using AsTask() is probably the way to do it since if you're in an exceptional path and haven't completed successfully synchronously you're already out of the cost savings scope for ValueTask. I'm sure @stephentoub will be able to clarify.

**Comment by stephentoub** [comment]
Right. Just use AsTask. ValueTask is not as full featured as Task, by design, meant to be a lightweight/extensible alternative for the common path of awaiting an async operation. For anything more than that, you'll often need to use AsTask and then party on the resulting Task. At this point, adding a property like that would be difficult/expensive, as it's not part of the IValueTaskSource interface.

**Comment by akarnokd** [comment]
Understood. Thanks @stephentoub & @Wraith2 !
