### ISSUE TITLE
System.ComponentModel.Annotations packaging issue with Xamarin.Forms

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#32988]
Filing an issue on behalf of a user who emailed 'Contact Owners' on https://www.nuget.org/packages/System.ComponentModel.Annotations/

> This nuget package is marked as compatible with .Net Standard 1.1, but no .dll is downloaded for that target. This breaks compatibility with Xamarin.Forms PCL projects (Profile111) since libraries with this dependency will never be resolved.

cc: @lajones, @divega, @ajcvickers

**Comment by ajcvickers** [comment]
Possibly related to https://github.com/dotnet/standard/issues/450 and https://github.com/aspnet/EntityFrameworkCore/issues/13268 for which customers are still waiting for answers.

**Comment by ericstj** [comment]
Just chiming in here, Profile111 = portable-net45+win8+wpa81.  I believe this didn't include ComponenetModel.Annotations inbox because it wasn't supported on Windows Phone.  Contrast to Profile7 = portable-net45+win8 will have this reference.

Xamarin frameworks do include this assembly inbox, so when using a Xamarin project and this package I'd expect the Xamarin SDK to bring in the dll (not the package).  The problem is unique to the Profile111 project using packages.config.

I believe if you used PackageReference (instead of packages.config) in this project it would do the right thing: get a reference (ref\nestandard1.1) for the PCL project to build and then provide no implementation in the Xamarin project where the implementation comes from the framework itself.

If the library owners wanted to make this work: packages.config consumption in a Profile111 project, they'd need to add a netstandard1.1 implementation: either real or throwing a not-supported-exception.
