### ISSUE TITLE
System.Net.Http 4.0 is loaded instead of 4.2

### ISSUE THREAD

**Issue by Mogikan** [dotnet/corefx#33034]
I created new blank Console app (targeting .net 4.7.2) in VS 15.8.8
Added reference to System.Net.Http (v. 4.2), specified specific version to true, copylocal to true.
When I run the app it prints that v.4.0 was loaded.
Code:
```c#
            var assembly = typeof(HttpClient).Assembly;
            Console.WriteLine("Path: " + assembly.Location);
            Console.WriteLine("Version: " + assembly.GetName().Version);
            Console.ReadKey();
```
Output:
> Path: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll
> Version: 4.0.0.0

Expected output:
Version 4.2

Sample to reproduce the problem:

[ConsoleApp14.zip](https://github.com/dotnet/corefx/files/2513243/ConsoleApp14.zip)

**Comment by 0xd4d** [comment]
https://github.com/dotnet/corefx/issues/25050#issuecomment-341803990

**Comment by davidsh** [comment]
@joperezr

**Comment by joperezr** [comment]
This is by design. Due to a Windows requirement, all of the framework assemblies installed in the GAC need to be versioned 4.0.0.0. The actual implementation contained in that assembly is not the 4.0.0.0 implementation but the 4.2.0.0 instead. There are a bunch of complicated reasons of why Windows has this requirement on our assemblies installed on the GAC, like servicing, bugfixing, and just having one GAC for all .NET 4+ frameworks, but essentially this is expected.
