### ISSUE TITLE
Need a standard convention to refer to bugs from corresponding regression tests.

### ISSUE THREAD

**Issue by VSadov** [dotnet/corefx#3311]
Roslyn uses WorkItemAttribute as a standardized way for regression tests to refer to bugs. It has been found very useful in the past, since bug descriptions and discussions can contain a lot of relevant information, that would be hard to make a part of a test. 
Being an attribute makes it easy to find in an automated way if so needed (bugs migrated to alternative store or something)

Turns out Linq.Expression does not have any convention for regression tests. I suggested commented out attribute as a temporary measure to not lose the information about corresponding bug, but there seem to be a need for a better, more standard convention for this.

**Comment by VSadov** [comment]
I would prefer to use an attribute, since natural text comments seem to be not as friendly to tooling. There could be other ways though. Including "let's not do this".

**Comment by VSadov** [comment]
@stephentoub @bartonjs @mmitche   -  any suggestions here?

**Comment by bartonjs** [comment]
My personal opinion is that this is unproductive, so I'd call it a "Won't Fix".

* Anything that existed pre-us-being-on-github has no such things, because they are now considered to have been around since time immemorial.
* Maybe now we'll stick to one issues database for longer than 2 years, but historically around the time you write down an issue number you regret it because the bug database just got migrated.
    * Usually only active issues get migrated, so while programmatic findability is good, it isn't usually productive.
* As the product evolves, so do the tests.  If issue 9876 introduced this concept, but had an exception in this case, and now that case has a legitimate usage due to issue 9912... which attribute do you use?  The first? last? both?

You say that it "has been found very useful in the past".  Can you give some examples?  Right now I don't see a concrete benefit; so to me this is a cost-only proposal.

**Comment by mmitche** [comment]
I want to say that we already have something close to this?

We have: [ActiveIssue(846, PlatformID.AnyUnix)] where 846 is the GH id.  This attribute will implicitly disable the test.  If we need an attribute that won't disable the test we should add one.

**Comment by mmitche** [comment]
We could augment this to something like:

Issue(State.Active, 846, PlatformID.AnyUnix)

Where the state enum is something like:

State {
  WontFix
  Fixed
  Active
}

**Comment by VSadov** [comment]
@bartonjs - I find me using references from tests to bugs relatively regularly. Perhaps once a month a situation arise where a change breaks some strange-looking test and I am curious about the history of the scenario - whether that was a compatibility or perf related thing, whether there the issue was theoretical or reported by multiple customers etc. Typically this is not blocking, but very useful so to not repeat investigations that were already done.

I do not agree that bug databases routinely disappear. I had to lookup bugs from around C# V1.0. It is often not easy to find old bugs, but often there is some sort of backup or an index. Now that our bugs are "on the web" they will likely stay around reasonably forever.

**Comment by VSadov** [comment]
A concrete and recent example -
The first attempt to fix https://github.com/dotnet/roslyn/issues/4471 resulted in a unit test break. The unit test had a reference to a bug (internal in this case) that contained a fairly thorough investigation/discussion about whether the new behavior is matching the spec and how that impacts backwards compatibility. That was definitely a time saver to have that info already.

**Comment by Priya91** [comment]
@VSadov As @mmitche suggested, have you checked out if ActiveIssue attribute works for this?

**Comment by VSadov** [comment]
As I understand ActiveIssue is used to indicate a currently open bug that affects the test. Correct me if I am wrong.

What we'd like here is a way to refer to bugs/workitems that had effect on a given testcase in the past.

That way you do not need to put a lot of explanation in the testcase - the bug typically already has all the context on what breaks, how and what justifies fixing it and so on.

Look for example at the last testcase in 
https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOperators.cs#L4959

The testcase refers to the corresponding closed bug that has a thorough explanation of the scenario involved.
https://github.com/dotnet/roslyn/issues/7262

It is very valuable to be able to have such information.

**Comment by Priya91** [comment]
@VSadov Yeah, that's correct, ActiveIssue applies only for disabling tests linked to an open issue. But how common is the scenario you mention? This will be valid only till the bug is kept in the database. If it was indeed important to preserve some information in code, that will be useful forever, then i think it is best to comment it near the code, instead of having a dependency over an external database which will evolve independent of this source code reference. As this never been an issue so far (i.e, the external reference getting lost)?

**Comment by VSadov** [comment]
Losing bug databases would be unfortunate, but it is, hopefully, not a very common occurrence nowdays.

In the past when switching databases, some readonly/cached version of old database would be kept  around. It is often possible with some digging find bugs as old as year 2000 even though we did switch bug databases several times.

The possibility of losing bug databases does not in my view negates the value of associating tests with bugs. And the cost of tracking that association is pretty cheap.

**Comment by Priya91** [comment]
This feature is not specific to corefx, if required this should be implemented on [dotnet/buildtools](https://github.com/dotnet/buildtools) so it's reusable everywhere. @VSadov You could port the roslyn WorkItem attribute over to buildtools for reusing in corefx. Closing this issue.
