### ISSUE TITLE
Add NetDataContractSerializer to Windows Compat Pack

### ISSUE THREAD

**Issue by gallivantor** [dotnet/corefx#33120]
Currently the Windows Compatibility Pack provides good coverage of the WCF client APIs for calling into existing WCF services.

However one thing that is missing is the NetDataContractSerializer; this means that from a .NET Core app it is not possible to call into an existing WCF service which returns data serialized in this format.

This request is to add this API to the Windows Compatibility Pack so that .NET Core apps can call into existing WCF services that return data serialized in this manner.

**Comment by Lxiamail** [comment]
@gallivantor It is not currently planned to enable NetDataContractSerialize in .Net Core. Thank you for your feedback, we will prioritize features based on customer feedbacks.

**Comment by gallivantor** [comment]
I believe that the NetDataContractSerializer is the standard approach to serializing exceptions across tiers with WCF services.

Without it, in general that will mean that .NET Core clients can call into existing services correctly, but will be unable to parse any exceptions that come back from the service. This seems like a shame as the WCF interop functionality is almost there but with this missing piece it's not possible to correctly handle exceptions coming from the service

**Comment by mconnew** [comment]
@gallivantor, I'm very strongly against porting over NetDataContractSerialzier for the simple reason that the concrete type to be deserialized is written into the payload and is then used on deserialization to instantiate objects. NetDataContractSerialzier was created in more innocent times when it wasn't yet realized how bad an idea this is.  
Serializing an exception into the response and then having that deserialized to the exact same exception type based on the XML is an anti-pattern in WCF. It makes your WCF service only usable from a .NET client, and it also aborts the channel if it's session based (WSHttpBinding, NetTcpBinding etc). The correct way is to use [FaultException\<TDetail\>](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.faultexception-1?view=netframework-4.8). You can even use the exceptions that you currently throw as the fault detail. The only caveat is that you need to attribute your operations with multiple instances of `FaultContractAttribute`, one for each fault type you expect to throw. There's a very good example in the documentation I linked to showing how everything works together.  
If you really want to stick with NetDataContractSerializer, you can copy the code from ReferenceSource (I would suggest using https://github.com/Microsoft/ReferenceSource as the easiest way to get the code). Any internal classes from System.Runtime.Serialization you should be able to copy into your own code too so that shouldn't be blocking you. But as I said, I recommend moving to using FaultException\<TDetail\> as a better usage pattern as it's also cross framework compatible (java, php etc) as it's part of the SOAP spec.

**Comment by cbenard** [comment]
@mconnew how about letting developers make the decision on which code to use? Not having `NetDataContractSerializer` means being unable to deserialize objects that have been persisted in the past by Framework code.

It's not only used by WCF. We have data that's been persisted using NDCS and without NDCS we are unable to deserialize it, and unable to move to .NET Core/5. Yes, I know we could write some kind of process that runs in Framework to loop over the rows/convert/hope for the best/etc.

However, NDCS belongs in a compat NuGet. I don't care if you don't want to use it or if you think it's a code smell or if you assume it is only ever used in WCF. Having the types serialized along with the data is actually **fantastic** when you control both sides of the input/output of the serialization (not using user-input).

I have looked at the reference code and it's not as simple as porting one class. It has many dependencies and didn't end up being an hour task. I gave up on it until I have more time to look at it.

**Comment by mconnew** [comment]
@cbenard, I know it's not what you meant, but you do have the freedom to make the decision on which code to use. The entire code required is available on reference source and there's no impediment to you using that code. I also believe that you should be able to use XmlSerializer to deserialize XML created with NetDataContractSerializer. XmlSerializer was designed to be able to deserialize arbitrary XML so if you approach it from the point of view of the output from NETDCS as being some esoteric XML mapping, you should be able to read all your data using XmlSerializer.  

It's a lot more work that needs to happen to bring it over as part of the whole .NET eco system compared with someone bringing it over for their own use. One example is the issue with UWP native apps. The existing code to dynamically generate IL code at runtime doesn't work for UWP native apps. We have a tool which pre-generates serializers for XmlSerializer, DataContractSerializer and DataContractJsonSerializer as part of the UWP tool chain. We would need to write that for NetDataContractSerializer. We also have a reflection based serializer which doesn't use IL but dynamically executes code based on reflected info about your data contract. This is slower, but allows a smaller binary size for UWP. This was a significant amount of work to do for the existing serializers and we're still finding bugs in the implementation (a fix was just committed in the last 24 hours). As far as I'm aware there's been no announced plans for UWP to support netstandard3.0, but by porting NetDataContractSerializer we are creating a corner we can get boxed into where we are implicitly signing up for all this work if UWP support for netstandard3.0 is announced. It's a potential ice berg.  

In the future, I would like to add support for async serialization (XmlSerialzier etc only serialize synchronously) to the XML serializers. This could only conceivably be done using the reflection based serializer as a starting point otherwise it's not a one-man job. It would take a full team many months, maybe a full year, to enable async with the Ref.Emit based serializer. Which means you either need to do the reflection based serializer for NetDataContractSerializer at the same time as porting or that becomes an extra cost before implementing async serialization for the other serializers. Again, another ice berg.  

There's also the ongoing support cost to porting NetDataContractSerializer. It's not just a case of bring the code over and we're done. As I mentioned, including the CLR type info in the XML is a bad idea. There's a whole class of security bugs which exist when you do that. Any security fixes could need to be fixed and validated in up to 3 new implementations. These aren't 3 copies, but three distinct different code bases.  

What it comes down to is simply that this is a lot bigger task than you realize, with a lot more ongoing costs and knock on cost effects for future improvements and the team which owns serialization isn't sized to do the up-front work or make an ongoing commitment to support it. I understand the frustration of not having all your dependencies available, I primarily work on WCF and I've had to do a lot of work and get very creative with finding alternative solutions because with the exception of the UI libraries, WCF basically uses everything there is in .NET Framework and there's big pieces absent in .NET Core. So you do have my sympathy, and I hope you understand now that it's more involved than you initially thought and why we can't port it.

**Comment by StephenBonikowsky** [comment]
Closing as won't fix.
