### ISSUE TITLE
HttpWebResponse.Cookies different behavior in .net framework and .net core

### ISSUE THREAD

**Issue by Avemey** [dotnet/corefx#33122]
Environment:
OS: Windows 10 pro
.NET Core: 2.1
.NET Framework: 4.5.1

HttpWebResponse.Cookies should contains cookies that are associated with response but for .net core this property contains cookies from request and response both.

Example:
```c#
CookieContainer cookieContainer = new CookieContainer();
Uri uri = new Uri("https://google.com");
cookieContainer.SetCookies(uri, "k1=1111,k2=2222,k3=3333,1P_JAR=zzz");

HttpWebRequest request = (HttpWebRequest)WebRequest.Create(uri);
request.CookieContainer = cookieContainer;
request.Method = "GET";

HttpWebResponse response = (HttpWebResponse)request.GetResponse();

Console.WriteLine("Cookies from response: ");
foreach (Cookie cookie in response.Cookies)
{
    Console.WriteLine("    " + cookie.Name + ": " + cookie.Value);
}

Console.WriteLine("Get cookie by name: " + response.Cookies["1P_JAR"]);
```

Result for .net framework 4.5.1 (as expected):
```
Cookies from response:
    1P_JAR: 2018-10-26-13
    NID: bla-bla-bla
Get cookie by name: 1P_JAR=2018-10-26-13
```

Result for .net core 2.1 (wrong):
```
Cookies from response:
    k1: 1111
    k2: 2222
    k3: 3333
    1P_JAR: zzz
    1P_JAR: 2018-10-26-13
    NID: bla-bla-bla
Get cookie by name: 1P_JAR=zzz
```

**Comment by rmkerr** [comment]
Thanks for the report.

This looks like a consequence of HttpWebRequest being built on top of HttpClient in .NET Core. HttpClient maintains a CookieContainer that it uses to track all cookies that are sent and received.

So the following sequence of events is causing this issue:

(1) The request cookie container is copied into HttpClientHandler:
https://github.com/dotnet/corefx/blob/0bfc4f3cf62f6fc29162ad5b1b89acc14124a375/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L1124-L1128
(2) The request is sent, and any response cookies are automatically copied into the cookie container:
https://github.com/dotnet/corefx/blob/0bfc4f3cf62f6fc29162ad5b1b89acc14124a375/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L1211-L1215
(3) The response is constructed with the cookie container that now contains both sets of cookies:
https://github.com/dotnet/corefx/blob/0bfc4f3cf62f6fc29162ad5b1b89acc14124a375/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L1217

We don't expose many options to control cookie behavior on HttpClient, so the only fix I can think of here is to re-parse the response Set-Cookie header in order to construct a cookie container ourselves.

**Comment by karelz** [comment]
@Avemey how badly is it impacting your scenarios?
While there is a difference from .NET Framework, it is likely not too bad that we return all cookies merged. Or is it?

**Comment by Avemey** [comment]
The main problem that we use one code for .net core and .net framework version of our lib. And this problem was discovered via integration tests. So it is not very good for us.
For now temporary salvation is using conditional compiling but there is not only one problem place in code so it will be good to avoid conditional compiling.

**Comment by karelz** [comment]
@Avemey you can replace conditional compilation with runtime check to avoid conditional compilation.

**Comment by Avemey** [comment]
@karelz what do you mean about checking runtime?
For now code looks like this:

```
        // ...
	void SomeMethod()
	{
		// ...
		var cookies = response.GetResponseCookies();
		// ...
	}

        public static class HttpWebResponseGetCookiesExtension
	{
		public static CookieCollection GetResponseCookies(this HttpWebResponse response)
		{
#if NETCOREAPP
			var cookieContainer = new CookieContainer();
			string cookieHeader = response.Headers[HttpResponseHeader.SetCookie] ?? string.Empty;
			cookieContainer.SetCookies(response.ResponseUri, cookieHeader);
			return cookieContainer.GetCookies(response.ResponseUri);
#else
			return response.Cookies;
#endif
		}
	}
```
Is it more simple way? (I do not like use ConditionalAttribute)

**Comment by karelz** [comment]
Quick search on the internet shows that:
1. There is API proposal to check version: https://github.com/dotnet/corefx/issues/17452
2. Current workarounds / hacks are available: https://techblog.dorogin.com/how-to-detect-net-core-version-in-runtime-ecd65ad695be

**Comment by Avemey** [comment]
@karelz I am sorry, but this is worse than conditional compiling! It take extra operations for detecting version on each call! Maybe in some cases it can be acceptable, but not for this.

**Comment by karelz** [comment]
If the overhead is large, then cache it into static boolean, initialized just once.

**Comment by karelz** [comment]
Triage: Looks like rare scenario (only 1 customer hitting it).
Given that it is fairly complicated to fix and given that `HtpWebRequest` is being phased out and replaced by `HttpClient`, we don't plan to fix it. Closing.
If there are more customers hitting this when migrating from .NET Framework, we can reconsider in future and reopen the issue.
