### ISSUE TITLE
Installing System.Threading.Tasks.Extensions to project changes what StreamContent.CopyToAsync does

### ISSUE THREAD

**Issue by christophertrml** [dotnet/corefx#33144]
I'm not entirely sure if this makes any sense at all or if this is actually expected, but here it goes:

I have a project that utilizes `ByteRangeStreamContent` and thus uses a `ByteRangeStream`. 

See this sample code:
```
            var buffer = new byte[70];
            for (var i = 0; i < 70; i++)
            {
                buffer[i] = (byte)i;
            }
            var buffer2 = new byte[42];
            var stream = new MemoryStream(buffer);
            var byteRangeStreamContent =
                new ByteRangeStreamContent(stream, new RangeHeaderValue(20, 60), "text/plain", 30);
            var stream2 = new MemoryStream(buffer2);
            var o = byteRangeStreamContent.CopyToAsync(stream2);
            o.Wait();
```

The `CopyToAsync` call turns around and calls `ByteRangeStreamContent.SerializeToStreamAsync`. The `ByteRangeStreamContent` runs this code: `return _byteRangeContent.CopyToAsync(stream);`, which before installing `System.Threading.Tasks.Extensions` then turns around and utilizes this function:

```
        public override IAsyncResult BeginRead(byte[] buffer, int offset, int count, AsyncCallback callback, object state)
        {
            return base.BeginRead(buffer, offset, PrepareStreamForRangeRead(count), callback, state);
        }
```

However, after installing `System.Threading.Tasks.Extensions` into my project, the `return _byteRangeContent.CopyToAsync(stream);` call goes somewhere else and does not ever end up in `BeginRead`.

Questions:
1. Is this an intentional consequence of this library?
2. Is there another override `ByteRangeStream` needs to implement that it's not currently?

**Comment by stephentoub** [comment]
> Is this an intentional consequence of this library?

I assume this is a desktop project rather than a core project? And are you sure this is related to System.Threading.Tasks.Extensions rather than to System.Net.Http?

> Is there another override ByteRangeStream needs to implement that it's not currently?

We've seen this issue in relation to using System.Net.Http from a NuGet package on desktop, because HttpContent's CopyToAsync implementation changed in core and the NuGet package contains that core code.  There's a known bug in System.Net.Http.Formatting, where DelegatingStream overrides CopyToAsync but ByteRangeStream does not, and thus ByteRangeStream's position code doesn't get executed.  @dougbu is working on a fix for that in System.Net.Http.Formatting.

**Comment by christophertrml** [comment]
And yeah, your comment has lead me down a path to show me that it's just the update of `System.Net.Http` that lead to this. I'm a bit unsure of why installing `System.Threading.Tasks.Extensions` forced the application to use an updated version of `System.Net.Http` though; could you shed a little light on that so I can have more understanding?

**Comment by christophertrml** [comment]
With your help I was able to create a new `ByteRangeStream` that overloads `ReadAsync` correctly and then implements `CopyToAsync`:

```

        public override async Task CopyToAsync(Stream destination, int bufferSize, CancellationToken cancellationToken)
        {
            for (; ; )
            {
                var tempBuffer = new byte[bufferSize];
                int bytesRead = await ReadAsync(tempBuffer, 0, bufferSize, cancellationToken).ConfigureAwait(false);
                if (bytesRead == 0)
                {
                    break;
                }

                await destination.WriteAsync(tempBuffer, 0, bytesRead, cancellationToken).ConfigureAwait(false);
            }
        }
```

Probably not what you'll do exactly but it works until an updated version comes out. Thanks for your help! I'd still love an explanation about `System.Net.Http` though :)

**Comment by stephentoub** [comment]
> I'm a bit unsure of why installing System.Threading.Tasks.Extensions forced the application to use an updated version of System.Net.Http though; could you shed a little light on that so I can have more understanding?

I wouldn't have expected that, and I'm not able to repro it.  Are you sure it wasn't just coincidence?  I created a new .NET Framework Console app, I added a NuGet reference to System.Threading.Tasks.Extensions, I built, and then I Console.WriteLine'd `typeof(HttpContent).Assembly.Location`, and got:
```
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll
```
which is the .NET Framework implementation from .NET Framework 4.7.2.

When you do those same steps, you see otherwise?
