### ISSUE TITLE
CurlHandler throwing "HTTP stack not implemented" from MaxRequestContentBufferSize

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3321]
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClientHandler.Unix.cs#L129-L133

**Comment by davidsh** [comment]
`MaxRequestContentBufferSize` is considered a "deprecated" property in HttpClientHandler.  Even on .NET Desktop, it was only used in rare case where the HttpClientHandler would buffer in the request body if it didn't know the length (no Content-Length header) and Transfer-Encoding: chunked was not specified.  This behavior was changed in CoreFx so that in cases where it is ambiguous, chunked is used.  This only streamlines the design of HttpClient so that the developer is always in charge of when request body content is buffered.

**Comment by stephentoub** [comment]
Thanks.  I'm fine if we decide to still throw, but we should throw NotSupportedException rather than NotImplementedException.
