### ISSUE TITLE
Could not install System.Data.Odbc 4.5.0 on .NET Framework 4.5

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#33252]
Creating issue on behalf of a user who emailed the support link on https://www.nuget.org/packages/System.Data.Odbc/ : 

> Hi, I am using Visual Studio Community 2017 Version 15.6.6 and NuGet Package Manager 4.6.0. I am trying to install System.Data.Odbc 4.5.0, but I keep getting the following error. My project is a .net 4.5 project. Thanks for any help.

 ```
Severity Code Description Project File Line Suppression State Error
Could not install package 'System.Data.Odbc 4.5.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author. 0
```

cc: @divega, @ajcvickers, @keeratsingh, @afsanehr, @david-engel

**Comment by ajcvickers** [comment]
@divega Do you remember if it is intended to target net45? (Seems unlikely, but maybe there was a reason to go this far back.)

**Comment by divega** [comment]
It seems that the confusion stems from the fact that the package version is 4.5.0. That is completey unrelated to any .NET Framework version. The package only targets .NETCoreApp 2.0, .NETFramework 4.6.1 and .NETStandard 2.0. 

FWIW, I suspect that none of the packages we build from this repo target .NET Framework 4.5. 

A project that targets .NET Framework 4.5 can use System.Data.Odbc types by referencing the System.Data.dll assembly directly from the framework.  

@joshfree I will assign the issue to you so that you can answer the email from the customer and close it, but feel free to forward it to me and I will answer.
