### ISSUE TITLE
Could not load file or assembly 'System.Net.Http, Version=4.2.0.0

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#33251]
Opening on behalf of a user who emailed the support link on https://www.nuget.org/packages/System.Net.Http : 

> ASP net Core is asking for version 4.2.0.0. This latest NuGet 4.3.4 only has 4.1.1.3. I am seeing failure: 
```
System.IO.FileLoadException HResult=0x80131040 Message=Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) Source=Microsoft.AspNetCore.Http.Connections.Client StackTrace:
 at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection..ctor(HttpConnectionOptions httpConnectionOptions, ILoggerFactory loggerFactory)
 at Microsoft.Azure.SignalR.AspNet.ConnectionFactory.<ConnectAsync>d__12.MoveNext()
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

Inner Exception 1: FileLoadException: Could not load file or assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 
The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

cc: @davidsh @rmkerr

**Comment by joperezr** [comment]
> @joperezr - packaging issue?

No. 4.2.0.0 version of System.Net.Http doesn't ship in a single package anymore, as it is not inbox for all frameworks. New packages (like 4.3.4) are only servicing older frameworks (netcoreapp 1.1, netstandard 1.6 and below). This means that if you are targeting .NET Core, then 4.2.0.0 should be part of the shared framework being used to run the app. @joshfree is there a way to contact the user in order to get more details about how is he running the app? Or perhaps maybe even get a simple repro from him so that we can investigate.

**Comment by karelz** [comment]
Not actionable, closing.
