### ISSUE TITLE
IdnMapping.GetAsciiInvariant test can never be true

### ISSUE THREAD

**Issue by Zenexer** [dotnet/corefx#33269]
https://github.com/dotnet/corefx/blob/d7991c184d59bf0a62799e777b916ac35a4a0bd0/src/Common/src/CoreLib/System/Globalization/IdnMapping.cs#L214

I'm fairly certain this test can never be true.

On line 211:

```csharp
bool bHasLastDot = (unicode.Length > 0) && IsDot(unicode[unicode.Length - 1]);
```

On line 214:

```csharp
if ((!bHasLastDot) && unicode.Length > 0 && IsDot(unicode[unicode.Length - 1]))
```

Under sane circumstances, I'm pretty sure `!bHasLastDot` and `unicode.Length > 0 && IsDot(unicode[unicode.Length - 1])` can never be true simultaneously.  It could alternatively be written as:

```csharp
if (!bHasLastDot && bHasLastDot)
```

**Comment by stephentoub** [comment]
Yeah, that looks dead.

@tarekgh, this was introduced in https://github.com/dotnet/coreclr/pull/10264. In the non-invariant code before this, there's a potential normalization between those checks, but there's not in invariant. Should this all just be deleted?

**Comment by tarekgh** [comment]
Yes, what you have said is true. as we don't do the normalization in the invariant mode. in the normal implementation after we initialize bHasLastDot we do the normalization which can change the dot at the end of the string. but for invariant we don't do this normalization. we can just remove this condition.

@Zenexer thanks for reporting it. feel free to submit a PR for removing this condition. otherwise, I'll do it.

**Comment by Zenexer** [comment]
@tarekgh Thanks; looks like @stephentoub beat me to it!

**Comment by stephentoub** [comment]
The nice thing about GitHub's in-browser editor is you can submit PRs like that really quickly :smile:
