### ISSUE TITLE
Unescape the JSON string token before returning in TryGetValueAsString

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#33292]
It is possible that the JSON input contains strings containing escaped characters. Before returning a `System.String` to the caller via `TryGetValueAsString`, unescape them first, where necessary.

cc @GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
We have JSON escaping APIs already built in to the framework (https://apisof.net/catalog/System.Text.Encodings.Web.JavaScriptEncoder), but there's no unescape equivalent. I wonder if this scenario is common enough for us to make an all-purpose one rather than make it internal to the `JsonUtf8Reader` class.

**Comment by davidkaya** [comment]
@GrabYourPitchforks There is also a JS encoder in https://github.com/dotnet/corefx/blob/e23f83e6172ef2d879342e1c4883012749b91ef1/src/System.Web.HttpUtility/src/System/Web/Util/HttpEncoder.cs#L170 available through `HttpUtility`.

**Comment by GrabYourPitchforks** [comment]
@davidkaya The encoding routines in `System.Text.Encodings.Web` are preferred over the routines on `HttpUtility`. I'd like to obsolete the latter.
