### ISSUE TITLE
[CI] System.Security.Cryptography.Cng.Tests.DSACngPkcs8Tests.NoPlaintextExportAllowsEncryptedPkcs8(algorithm: TripleDes3KeyPkcs12)

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#33313]
x64_checked_windows_nt_corefx_innerloop_prtest on coreclr

System.Security.Cryptography.Cng.Tests.DSACngPkcs8Tests.NoPlaintextExportAllowsEncryptedPkcs8(algorithm: TripleDes3KeyPkcs12)
```
MESSAGE:
Assert.True() Failure\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at System.Security.Cryptography.Cng.Tests.DSACngPkcs8Tests.VerifyMatch(DSACng exported, DSACng imported) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Security.Cryptography.Cng\tests\DSACngPkcs8Tests.cs:line 24 
at System.Security.Cryptography.Cng.Tests.CngPkcs8Tests`1.NoPlaintextExportAllowsEncryptedPkcs8(PbeEncryptionAlgorithm algorithm) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Security.Cryptography.Cng\tests\CngPkcs8Tests.cs:line 74
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_corefx_innerloop_prtest/4190/

**Comment by bartonjs** [comment]
Thanks to the legwork by @sandreenko (and many, many keygens on my computer) I was able to figure out the cause, then reject it, then figure out what might be the real one.

When this error happens calling `ExportParameters(false)` shows that the `Y` values (the public key) are different.

Many, many more keygens later (this time in a context where `ExportParameters(true)` has permissions to succeed) the triggering condition became visible: when `log2(key.X) < log2(key.Q) - 8` (when X's encoding needed fewer bytes than Q's), which is a (roughly) 1/256 occurrence.

Heroics abound on rewriting the exported PKCS8, then _voila_... the tests still fail.

Take one of the exported PKCS8 blobs, try to fix it by hand, be upset that I copied a post-fix value... no, it's pre-fix.  Yep, the PKCS8 is correct.

Looks like CNG has a hiccup when reading small X values from PKCS8, but it's fine when reading it from the CNG-specific blob format; so I'll just convert it manually instead of passing the PKCS8 to CNG.  (Since the PKCS8 for DSA doesn't contain the public key to verify, it's not really possible to ask "did you import correctly" outside of a scoped test like this.  Lesson to future crypto key file format designers: the public key helps verify the private import!  It's not pointless!)

**Comment by bartonjs** [comment]
@benaadams Oh, that failure was in coreclr, not corefx?  Weird, I don't know why we've never seen it from our CI runs.

Still, debugging saga story applies, and I was debating copying the coreclr issue to here so I had something to mark "fixed" when I opened the PR.

**Comment by bartonjs** [comment]
>    System.Security.Cryptography.Cng.Tests: [Long Running Test] 'System.Security.Cryptography.Cng.Tests.DSACngPkcs8Tests.Thingy3', Elapsed: 00:38:00

Between 38 and 40 solid minutes of generating random DSA keys looking for more aberrant behavior's good enough for me.

**Comment by benaadams** [comment]
>  Oh, that failure was in coreclr, not corefx?

Yeah, checked coreclr with corefx. Reran and it didn't reoccur

**Comment by benaadams** [comment]
Ah, looks same configuration as the other issue
