### ISSUE TITLE
Why const is used in stackalloc char[255] ?

### ISSUE THREAD

**Issue by iSazonov** [dotnet/corefx#33331]
Was there any special thoughts that there is `stackalloc char[255]` instead of `stackalloc char[source.Length]`?
https://source.dot.net/#System.Private.CoreLib/shared/System/Globalization/CompareInfo.cs,1295

**Comment by iSazonov** [comment]
Another sample https://source.dot.net/#System.Private.CoreLib/shared/System/Globalization/CompareInfo.Windows.cs,142

**Comment by stephentoub** [comment]
The JIT can better optimize the stackalloc when it's a const, and the extra space difference between the actual length and the max of 255 doesn't have an impactful difference.  So it's better to let the JIT do its const-based optimizations.

**Comment by iSazonov** [comment]
Thanks! Clear!

**Comment by benaadams** [comment]
Also if you use `source.Length` without any limit to the length (which there are in the examples); then a user providing a string that is too long will cause a stack overflow; which is why > 255 it falls back to a regular array.

Also CoreLib clears the `.initlocals` flag with illink for these methods; so it doesn't initialise the stackalloc'd memory to 0; so the cost of stackallocing 10 chars or 255 chars is the same.
