### ISSUE TITLE
BlockingCollection<T> isn't Serializable

### ISSUE THREAD

**Issue by simendsjo** [dotnet/corefx#33483]
https://referencesource.microsoft.com/#System/sys/system/collections/concurrent/BlockingCollection.cs,3fc8b6e4e28ee36c

**Comment by Wraith2** [comment]
No. It isn't.

Did you think it should be? It doesn't seem to make sense that it would be when the purpose is to provide thread safe producer consumer mechanisms which only make sense at runtime. I would expect serialization to be handled in another place which then dumps the information into this collection for processing.

**Comment by simendsjo** [comment]
> Did you think it should be?

Maybe..? It's in System.Collection. I just came across a third-party class which couldn't be serialized as it used this class. Is it the only collection in System.Collection which isn't Serializable?

**Comment by Wraith2** [comment]
The classes in the same namespace, Concurrent- Bag Stack, Queue etc aren't serializable either. As I said I don't think it makes a lot of sense for them to be serializable given that their specific behaviour is about runtime. I would expect them to be in the middle of a processing pipeline and not a terminal/serialization stage.

**Comment by simendsjo** [comment]
- ConcurrentBag is Serializable: https://referencesource.microsoft.com/#System/sys/system/collections/concurrent/ConcurrentBag.cs,50
- ConcurrentStack is Serializable: https://referencesource.microsoft.com/#mscorlib/system/Collections/Concurrent/ConcurrentStack.cs,53
- ConcurrentQueue is Serializable: https://referencesource.microsoft.com/#mscorlib/system/Collections/Concurrent/ConcurrentQueue.cs,45

**Comment by stephentoub** [comment]
> ConcurrentBag/Stack/Queue is Serializable

Not in .NET Core.

> Maybe..?

We are not making additional types [Serializable].  In fact, we're going in the opposite direction, with fewer types being [Serializable] in .NET Core.  Making types [Serializable] is too restrictive, in that it often makes implementation details part of the contract, restricting the ability to evolve/improve implementation as we'd otherwise like.  It's also not the most efficient mechanism.  In general we recommend other serialization mechanisms.

**Comment by simendsjo** [comment]
> > ConcurrentBag/Stack/Queue is Serializable
> 
> Not in .NET Core. Those referencesource links point to .NET Framework code, rather than .NET Core, which this repo is about. You can use source.dot.net as an index for .NET Core source.

Sorry, I'm talking about .NET Framework, not .NET Core.

**Comment by stephentoub** [comment]
Ok.  I don't think it should be made [Serializable] in .NET Framework, either :smile:  First, it's not clear what serializing it would actually mean, if for example there are three threads all waiting to take out an item... what aspects of those threads is serialized?  Second, even if it were [Serializable] and T was [Serializable], `BlockingCollection<T>` is just a wrapper for an `IProducerConsumerCollection<T>`, and so it would need to be serializable as well.  Third, I agree with @Wraith2 that serializing a type intended to be used as a synchronization mechanism between a producer and consumer is a strange operation.  Fourth, in general runtime serialization isn't a technology that's being advanced or promoted, with other mechanisms instead preferred, so we're generally not making new or existing types [Serializable], and as noted, many types that were [Serializable] in .NET Framework are no longer in .NET Core. And finally, if you need to serialize its data, you call ToArray() on it to get its elements, and then "deserialize" it by passing that array to something like `new BlockingCollection<T>(new ConcurrentQueue<T>(array))`.

As this repo is about .NET Core, I'm going to close the issue.  Thanks.

**Comment by simendsjo** [comment]
I see. This is a third-party library which is, wrongly, being used remotely (through AppDomain) in another third-party library. They don't want to add MarshalByRefObject, and adding Serializable is impossible because of this.

I get the feeling of being stuck in the middle all the time. People only want to advance Core, but a lot of stuff is still impossible with Core, which means existing projects cannot upgrade. We often get the worst of both worlds.

**Comment by stephentoub** [comment]
> and adding Serializable is impossible because of this.

You're saying they have an object that contains a `BlockingCollection<T>` that they want to make serializable, but can't because of the contained `BlockingCollection<T>`?  That should not stop them: they can just implement `ISerializable`, and do what I said above: when `GetObjectData` is called, call `ToArray` on the `BlockingCollection<T>` and store the resulting `T[]` into the `SerializationInfo` rather than storing the `BlockingCollection<T>` itself, and then when the deserialization ctor is called, extra that `T[]` and use it to create a new `BlockingCollection<T>`.  It's no different than any other type that wraps non-serializable objects (of which there are many); it's one of the reasons `ISerializable` exists.
