### ISSUE TITLE
Missing support for sockaddr_un scheme in System.Uri

### ISSUE THREAD

**Issue by tdaniely** [dotnet/corefx#33604]
The afunix driver is now included with windows.
Common sense is that the framework should eventually support unix sockets at all layers.

See related [dotnet/corefx #27643](https://github.com/dotnet/corefx/issues/27643) framework should start acknowledging this functionality.
See example downstream use case [PowerShell/PowerShell #8314](https://github.com/PowerShell/PowerShell/issues/8314).

**Comment by davidsh** [comment]
@stephentoub @rmkerr

**Comment by stephentoub** [comment]
Where is sockaddr_un documented as an official scheme for use in Uri's?

**Comment by stephentoub** [comment]
> See related dotnet/corefx #27643 framework should start acknowledging this functionality.

It's already supported by Sockets, but that's different from Uris.  There's a POSIX address family for Unix domain sockets.

**Comment by rmkerr** [comment]
sockaddr_un is not registered with the [IANA](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml), nor is it even a legal URI scheme.

For reference, here's the set of characters that are allowed in a scheme:
```
scheme        = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )
```
System.Uri correctly throws an exception with sockaddr_un because it contains an illegal underscore.

**Comment by stephentoub** [comment]
Given the above, I'm going to close this.  Thanks.
