### ISSUE TITLE
FileInfo.CreationTimeUtc setter seems not working (do nothing without exception) on Linux

### ISSUE THREAD

**Issue by WernerMairl** [dotnet/corefx#33601]
Hi
Using Dotnet Core 2.1 

The following test is working on my Windows machine

BUT it is failing on the assert in the last line if i execute the code using 
(linux) docker image "microsoft/dotnet:sdk" (on Bitbucket Pipeline)

```c#
        [Fact]
        public void CreationTimeUtc_Bug()
        {

            string proposedFileName = Path.GetTempFileName();

            File.Delete(proposedFileName);
            File.WriteAllText(proposedFileName, "dummy file content as text");

            FileInfo localFile = new System.IO.FileInfo(proposedFileName);
            DateTime newCreationTimeUTC = System.DateTime.UtcNow.Subtract(TimeSpan.FromDays(365));

            localFile.CreationTimeUtc = newCreationTimeUTC;
            Assert.True(localFile.CreationTimeUtc == newCreationTimeUTC, "thats a BUG!!");

        }
```

may be something like  #16782 ?

Expected Behavior: value should be assigned or Exception (PlatformNotSupported....)

regards
Werner

**Comment by danmosemsft** [comment]
@WernerMairl 	can you please try it on master? You can get that in various ways such as from https://github.com/dotnet/core-sdk

**Comment by WernerMairl** [comment]
@danmosemsft all my linux environments are docker based, so a image could be helpful....

at the moment i can find only 2.2 preview 
(looking at docker-hub and https://github.com/dotnet/dotnet-docker/blob/master/TAGS.md)

assuming master is 3.0 ?
any other source for docker images ?

**Comment by WernerMairl** [comment]
found: probably here: https://hub.docker.com/r/microsoft/dotnet-nightly/tags/

**Comment by WernerMairl** [comment]
docker image: microsoft/dotnet-nightly:3.0-sdk
dotnet --info
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-009734
 Commit:    841b50c4df

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100-preview-009734/

Host (useful for support):
  Version: 3.0.0-preview-27106-02
  Commit:  410cba8501

.NET Core SDKs installed:
  3.0.100-preview-009734 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 3.0.0-alpha1-10663 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 3.0.0-alpha1-10663 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27106-02 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

```


Test: failed!

**Comment by tmds** [comment]
Linux doesn't have a creation time. 3 timestamps are tracked:
```
    time_t    st_atime;   /* time of last access */
    time_t    st_mtime;   /* time of last modification */
    time_t    st_ctime;   /* time of last status change */
```
The `atime` and `mtime` can be set by the user.

in https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/FileStatus.Unix.cs:
set of CreationTime is implemented as updating `atime`.
get of CreationTime returns the oldest of `ctime` and `mtime`.

[mono](https://github.com/mono/mono/blob/master/mono/metadata/w32file-unix.c) has the same logic for the getter, the setter is a no-op.

The corefx setter has a comment:
https://github.com/dotnet/corefx/blob/ed05109d18912262db4d2a9f5bbc6327073beb79/src/System.IO.FileSystem/src/System/IO/FileStatus.Unix.cs#L166-L169

If we update the `mtime` instead of the `atime`, that will make the getter return the same value (as long as creation time isn't set in the future).

Looking at `FileSystemWatcher` implementation, this should still cause the event to be triggered.

**Comment by danmosemsft** [comment]
@wernermairl please try in master now.

**Comment by WernerMairl** [comment]
tested with:
3.0.100-preview-009756

test failed, old behavior, setter not working.....

waiting another day .. not sure about how often "microsoft/dotnet-nightly:3.0-sdk" is rebuilded!

**Comment by danmosemsft** [comment]
Ah if you consume via SDK it can take a week or two.
