### ISSUE TITLE
System.Net.Security related Pending PR coments/TODO

### ISSUE THREAD

**Issue by rajansingh10** [dotnet/corefx#3362]
1. Interop.OpenSsl TODO - See if SSL_CTX_Set_quite_shutdown can be used

**Comment by vijaykota** [comment]
@rajansingh10, seems like a copy-paste error. There should be more unaddressed comments here

**Comment by rajansingh10** [comment]
2. Trailer size requirement changes based on Protocol. Currently it's hard coded. (Interop.libssl_types.cs)
3. SSL3_RT_MAX_COMPRESSED_LENGTH will depend on whether compression is allowed or not. (Interop.libssl_types.cs)
4. AllocateSslContext - Set remote certificate options (Interop.OpenSsl.cs)
5. Disconnect -  check the SSL_shutdown error (Interop.OpenSsl.cs)
6. BioRead/BioWrite - Should bio retry, investigate & fix? (Interop.OpenSsl.cs)
7. SslCredKey - used a prime number here as it's a XOR. Figure out appropriate value. (_SslSessionsCache.cs)
8. GetRemoteCertificate - Fetch remoteCertificateStore, if applicable for unix. (CertModule.cs)
9. GetRequestCertificateAuthorities - populate issuers. (CertModule.cs)
10. EnsureStoreOpened - Implement the method. (CertModule.cs)
11. SafeFreeContextBufferChannelBinding - Implement the class (SecuritySafeHandles.cs)
12.  SslConnectionInfo -  map key sizes (SslConnectionInfo.cs)
13.  MapProtocol - Figure out correct value for default - (SslConnectionInfo.cs)
14. MapCipherAlgorithmType/MapExchangeAlgorithmType/MapHashAlgorithmType - Handle other values - (SslConnectionInfo.cs)
15. GetException - Implement the method. (SSPISecureChannelType.cs)
16. AcquireCredentialsHandle -  retVal is not getting released now, need to be fixed.  (SSPISecureChannelType.cs)
17. QueryContextChannelBinding & QueryContextIssuerList - Implement the method. (SSPISecureChannelType.cs)

**Comment by rajansingh10** [comment]
17. Add error messages to *.resx files for localization.

**Comment by rajansingh10** [comment]
18. Use SslContext as a class rather than struct & use a GCHandle rather than allocating native memory every time.

**Comment by rajansingh10** [comment]
Evaluate if various SSL methods in GetSslMethod of Openssl.cs, can be cached one time & use always.

**Comment by rajansingh10** [comment]
use safehandles inplace of intptr wherever applicable.

**Comment by CIPop** [comment]
@rajansingh10 Instead of adding new posts, please move all items to the first one by editing it (the pencil icon near the top right).
Also, it's nice if you use the format to track what's already done:
- [ ] Item1
- [X] Item2
- [ ] Item3

**Comment by shrutigarg** [comment]
updated the partial issues fixed..

**Comment by vijaykota** [comment]
Using https://github.com/dotnet/corefx/issues/3954 to track the remaining

**Comment by stephentoub** [comment]
@vijaykota, this issue was closed, but there are still TODO references to this issue in the code, and for things that don't appear to be covered by 3954.

**Comment by eerhardt** [comment]
I will open a new issue for SSL error handling in general.  Along with the `TODO check this error` comment, I found another problem with the error handling - 

There are 2 sets of error codes
1. Those defined in err.h
2. Those defined in ssl.h
These two sets overlap, for example ERR_R_SYS_LIB = 2 and SSL_ERROR_WANT_READ = 2.

In Interop.OpenSsl.GetSslError, if the SslErrorCode returned from SSL_get_error (defined in ssl.h) is SSL_ERROR_SYSCALL, it calls ERR_get_error (defined in err.h), and casts that result to an SslErrorCode, which is incorrect since it will return a separate set of error codes.

**Comment by vijaykota** [comment]
> there are still TODO references to this issue in the code

There is no active coding/investigate work pending for these. So the comments need to be removed from the code. Created https://github.com/dotnet/corefx/issues/4128 to track this.

cc: @shrutigarg

**Comment by eerhardt** [comment]
Even this one?  https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/Unix/libssl/SecuritySafeHandles.cs#L280-L283

```C#
internal abstract class SafeFreeContextBufferChannelBinding : ChannelBinding
{
    // TODO (Issue #3362) To be implemented
}
```

**Comment by CIPop** [comment]
@bartonjs PTAL at the second issue (prime number in XOR).

**Comment by CIPop** [comment]
+1 on @eerhardt's comment: the issues should be closed after all code references have been resolved.

**Comment by bartonjs** [comment]
@CIPop I'm not sure what you're asking me to look at?

**Comment by eerhardt** [comment]
> @CIPop I'm not sure what you're asking me to look at?

I think it is this:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/src/System/Net/_SslSessionsCache.cs#L56
```C#
    _HashCode ^= serverMode ? 5 : 7; //TODO (Issue #3362) used a prime number here as it's a XOR. Figure out appropriate value.
```
Is that code correct?

**Comment by CIPop** [comment]
Thanks @eerhardt. @bartonjs: That's the code that I'm referring to. If the code is correct as it is, then we can remove the comment.

**Comment by vijaykota** [comment]
Please see 4128 for removing all these occurences.

**Comment by bartonjs** [comment]
@CIPop It's not necessarily my area of expertise, but I can offer advice.

* The hash code starts off using the first 4 bytes of the thumbprint.  Since that has a full-spectrum range and is itself a very chaotic input, the first couple of lines are good.
* It then XORs in allowedProtocols, which is a value that is (for the most part) `0x0000` to `0x0800`, that interacts only with thumbprint[1] and thumbprint[0].
    * At this point nothing's really bad, since it isn't undoing itself.
* It then XORs in encryptionPolicy, which is 0, 1, or 2.  This definitely only interacts with thumbprint[0].
    * Certain combinations of encryptionPolicy and allowedProtocols are indistinguishable, meaning they'll guaranteed share a bucket.
* Then it XORs in either 5 or 7.  This, again, only interacts with thumbprint[0].
    * Again, certain combinations of allowedProtocols and isServer are indistinguishable from each other, meaning they'll always share buckets (for the same cert).

If you want really good spread you'd steal some bytes out of a hash of thumbprint.Concat(allowedProtocols).Concat(encryptionPolicy).Concat(isServer)).  But if you're really only ever having one set of options per certificate you've pretty much already done that, so it's possibly not worth changing.
