### ISSUE TITLE
EmailAddressAttribute is sealed class

### ISSUE THREAD

**Issue by cycbluesky** [dotnet/corefx#33724]
EmailAddressAttribute is sealed class but others such as StringLengthAttribute, RequiredAttribute are not.
Why?

I want to use a new class which inherit EmailAddressAttribute to set the ErrorMessage globally.

**Comment by ajcvickers** [comment]
@cycbluesky Because guidance is to seal all attributes, since this can greatly improve perf when looking for them. However, some of the "newer" annotations were not sealed because the advantage of being able to derive from them was considered to be more valuable. That being said, we do not plan to go back and change any attributes to unseal them since they were original designed with this perf in mind and we don't want to change that.

**Comment by cycbluesky** [comment]
@karelz , I found you added this to the 3.0 milestone? Does that means you'll unseal all validation attribute class?  I've met another problem of EmailAddressAttribute. It will treat the empty string as invalid email address even the model field is not required. I could have solved the problem by inherit EmailAddressAttribute but unfortunately it's a sealed class.

**Comment by karelz** [comment]
Milestone set = when was it closed. Does not say it was fixes. For resolution type, please read comments above.

**Comment by andre-ss6** [comment]
@ajcvickers How big is the performance impact? Do you have any data on how much is that difference, especially taking into consideration how frequently are the sealed and unsealed attributes used?

**Comment by ajcvickers** [comment]
@andre-ss6 No, I don't have specific numbers. If you do some tests and show that the performance difference is negligible, then that would be something we could consider. However, this will be an up-hill battle. The accepted wisdom for attributes is that they should be sealed, so changing that will require strong evidence that this wisdom is wrong.
