### ISSUE TITLE
Limit binplacing for tests projects

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#33743]
We currently binplace all our test project assets to a separate directory which is placed under `artifacts/bin/tests/$(MSBuildProjectName)/`. We should investigate if we really need that and if not just remove the binplacing and change our helix upload test directory list (currently all directories under tests are compressed and uploaded).

cc @ericstj @safern

**Comment by ericstj** [comment]
@safern added this with https://github.com/dotnet/corefx/commit/664ca9508a03483a7fb2714b55b9cba885593d90

I believe the purpose was to give the test a unique location per runtime/test configuration, even for tests which may have a single shared build configuration (eg: netstandard).

**Comment by safern** [comment]
> I believe the purpose was to give the test a unique location per runtime/test configuration, even for tests which may have a single shared build configuration (eg: netstandard).

Correct, the purpose of this is so that people that run the same test project for multiple configurations, don't get binaries clash. It was causing issues, because before the test working dir was not runtime specific, so if you ran the test project for netcoreapp first and then for netfx you would be executing in the same directory, containing assets that are not specific for that runtime, and people where hitting issues.

I think this is by design, unless we can come up with a better solution.

**Comment by ViktorHofer** [comment]
>  It was causing issues, because before the test working dir was not runtime specific

But it is now, right? i.e. `C:\git\corefx\artifacts\bin\System.Text.RegularExpressions.Tests\netcoreapp-Debug`.

**Comment by ericstj** [comment]
That particular test has a `netcoreapp` configuration: https://github.com/dotnet/corefx/blob/8fb32123a5894e79031e6e4c58cec337f63502ad/src/System.Text.RegularExpressions/tests/Configurations.props#L5.  You would need to examine a test that only has a `netstandard` configuration.

**Comment by ViktorHofer** [comment]
Forgot to respond. Thanks for the clarification. Now I understand why we need the binplacing here.
