### ISSUE TITLE
Environment.GetEnvironmentVariable Support Machine/User on Unix

### ISSUE THREAD

**Issue by xav-stargate** [dotnet/corefx#33745]
Hey,
I would like to know if the support of Environment.GetEnvironmentVariable Machine and User on Unix is planified ? Or will be ?

Thanks everyone

**Comment by danmosemsft** [comment]
@xav-stargate I am not sure that Unix has such concepts. The closest thing to machine scope perhaps would be the environment of the `init` process? And what would `SetEnvironmentVariable` do ? @tmds can you advise?

@xav-stargate what is your goal?

**Comment by gfoidl** [comment]
> Environment.GetEnvironmentVariable Machine and User

`Environment.MachineName` is supported, see https://github.com/dotnet/corefx/blob/fe9fd2cd1d40a97ecdbf1ef80fc9ace973a32560/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L302
Same for `Environemt.UserName` (https://github.com/dotnet/corefx/blob/fe9fd2cd1d40a97ecdbf1ef80fc9ace973a32560/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L377)
Will do these the job, otherwise `$HOSTNAME` and `$USER` (so for `GetEnvironmentVariable` without the `$`, just the name).

Or did I miss your question?

**Comment by danmosemsft** [comment]
@gfoidl for Unix they return null. It happens here
https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/Environment.cs#L484
FEATURE_WIN32_REGISTRY is only defined for Windows.

**Comment by danmosemsft** [comment]
Same for Set.

**Comment by jkotas** [comment]
`Environment.GetEnvironmentVariable` for Machine or User on Unix is not planned nor reasonably possible. This problem space was discussed in length in https://github.com/dotnet/corefx/issues/32685 https://github.com/dotnet/corefx/issues/20147 and related issues.

**Comment by gfoidl** [comment]
@danmosemsft at least on the linux-system I've tested `Environment.MachineName` and `Environment.UserName` return non-null correct results. For `Environment.GetEnvironmentVariable` _USER_ works, for _HOSTNAME_ it depends on the shell if it sets this variable.
In general, alls env-variables, that `env` lists, can be obtained.

Did I miss something?
