### ISSUE TITLE
CreateInstanceAndUnwrap API in AppDomain

### ISSUE THREAD

**Issue by ritchxu** [dotnet/corefx#33750]
This could be a silly question, but when targeting my class library to netstandard 2.0, I was expecting APIs like `CreateInstanceAndUnwrap` available [as they seem to be](https://github.com/dotnet/corefx/blob/51e1541da82253ab7d10a7c00a2fd93b8e41c341/src/System.Runtime.Extensions/src/System/AppDomain.cs). But I could not find those APIs, could I be pointed out where I made the silly mistake?

<img width="511" alt="capture" src="https://user-images.githubusercontent.com/10766168/49249783-28ab9e00-f3eb-11e8-809e-267f74f6144b.PNG">

**Comment by svick** [comment]
That method will be in .Net Core 3.0 (see https://github.com/dotnet/corefx/issues/30190 and especially notice that it's in the 3.0 milestone), which is why you can see it in the current version of the code in this repo. But that means it couldn't possibly be part of .Net Standard 2.0, which only includes APIs that are available in .Net Core 2.0.

As far as I can tell, that method won't be added in the upcoming .Net Standard 2.1 (which could in theory add it). I don't know if there are any plans for it in a version of .Net Standard after that.

Also note that even though the method has been added, .Net Core 3.0 still doesn't support having more than one `AppDomain`. So, if you have existing code that uses something like `AppDomain.CurrentDomain.CreateInstanceAndUnwrap(…)`, it will work, but the method won't be useful beyond that.

**Comment by ritchxu** [comment]
Thanks for the clarification! I think then I'm out of luck isolating assembly into a separate context using `AppDomain` with .NET Core moving forward. I'm exploring `AssemblyLoadContext` for that purpose.

In the meantime, I thought the compatibility pack would expose that API and I can live with `PlatformNotSupportedException` on the wrong platform. I planed to guard it with check of `RuntimeInformation.IsOSPlatform(OSPlatform.Windows)`. Any thought of why it's not exposed with the compatibility pack?

**Comment by karelz** [comment]
The type is part of .NET Strandard, so we cannot expose its members from elsewhere (compatibility pack). Types cannot be just partial in assemblies (only C# source code can).

**Comment by vitek-karas** [comment]
`AppDomain` is not really useful for isolation in .NET Core - mainly because the runtime only ever allows one `AppDomain` to exist - the default one. There's no way to create a new one. `AssemblyLoadContext` is the correct way to do load isolation on .NET Core.

We are aware that this makes it a bit difficult to have code which runs on both .NET Core and .NET Framework since it has to use ifdefs and have two different code paths.

**Comment by danmosemsft** [comment]
I think all questions are resolved and there is no work possible here.
