### ISSUE TITLE
ValidationAttribute and implicit conversion

### ISSUE THREAD

**Issue by ZBAGI** [dotnet/corefx#33831]
Some of the `ValidationAttributes` do not take into account implicit conversion. By defining implicit conversion into type we are essentially telling that this type is usable as other type. Is there a reason why some of `ValidationAttributes` greeting us with `InvalidCastException` in those situations ?

## Example
[MaxLengthAttribute ](https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/MaxLengthAttribute.cs) will complain when working on `Nullable<string>`  or other type that have user defined implicit conversion. On top of that it never actually tries to cast `object` into expected type, instead of it just checks type, so... exception `InvalidCastException` is a bit misleading?
## Proposal
Instead of directly throwing `InvalidCastException` validator should try to cast `value` into expected type before throwing corresponding exception.

**Comment by Wraith2** [comment]
Where would the expected type come from?

**Comment by ZBAGI** [comment]
Each validator knows what type it expecting. As in example [MaxLenghtAttribute](https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/MaxLengthAttribute.cs) expecting either string or collection.

There is already type check implemented in each validator:
https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/MaxLengthAttribute.cs#L74
https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/MaxLengthAttribute.cs#L78

I propose to replace that check or add additional cast try.

**Comment by mikernet** [comment]
I'm confused by your issue. `Nullable<string>` isn't a valid type. Nullable types should generally work because they get passed in as an `object` which will either convert the nullable to a null object value or a boxed value type without the nullable wrapper. Can you give me an example where this actually happens?

**Comment by ZBAGI** [comment]
Here is `struct` i using as a wrapper for the `string`:
```csharp
 public struct Change<T>
    {
        public Change(T value)
        {
            IsUsed = true;
            Value = value;
        }

        public bool IsUsed { get; private set; }
        private T Value;

        public static bool operator ==(Change<T> c1, Change<T> c2)
        {
            // both are false, its a match
            if (!c1.IsUsed && !c2.IsUsed)
                return true;

            // One of them is false but other is true
            if (!c1.IsUsed ^ !c2.IsUsed)
                return false;

            if (c1.Value == null && c2.Value == null)
                return true;

            if (c1.Value == null ^ c2.Value == null)
                return false;

            return c1.Value.Equals(c2.Value);
        }

        public override int GetHashCode()
        {
            if (!IsUsed)
                return 0;
            return Value.GetHashCode();
        }

        public static bool operator !=(Change<T> c1, Change<T> c2)
            => !(c1 == c2);

        public static implicit operator T(Change<T> change)
            => change.Value;

        public static implicit operator Change<T>(T value)
            => new Change<T>(value);

        public override string ToString()
        {
            return IsUsed ? (Value == null ? "null" : Value.ToString()) : "Not defined";
        }

        public override bool Equals(object other)
        {
            if (!IsUsed)
                return other == null;
            if (other == null && Value == null)
                return true;
            if (other == null ^ Value == null)
                return false;
            return Value.Equals(other);
        }

        public bool Equals(object other, Func<T, T> valueModifier)
        {
            if (!IsUsed)
                return other == null;
            if (other == null && Value == null)
                return true;
            if (other == null ^ Value == null)
                return false;
            return valueModifier(Value).Equals(other);
        }
    }
```
I expected `Change<string>` to work with `MaxLenghtAttribute` but instead i got:
`InvalidCastException: The field of type XXX.Change`1[System.String] must be a string, array or ICollection type.`

**Comment by mikernet** [comment]
I don't think what you're trying to do is really possible without writing `dynamic` based code but then you're opening up a whole can of worms. The attribute can't just try casting, because this doesn't work:

```c#
object x = new Change<string>("value");
string y = (string)x;
```

The above code will fail because there is no conversion from `object` to `string` unless the `object` is a `string` (but it's not, it's a `Change<string>`). Your implicit conversion doesn't come into play here so I'm not sure what solution you are suggesting.

If you need something like this then I would suggest writing a `StringLengthAttribute` or something similar that just does ToString() on the value and checks it's length if that's what you need. I think it would be too quirky to support a scenario like this in the BCL attribute.

**Comment by mikernet** [comment]
If you want to write something like an `ImplicitMaxLengthAttribute` then you would have to do something like this:
```c#
try {
    string stringValue = (dynamic)value;
}
catch (InvalidCastException) { }
```

I don't know if introducing dynamic code like that into the standard attributes is something that would happen but perhaps someone else can chime in on that. Part if the issue here is that the attribute would be creating and catching exceptions for any values that aren't strings which isn't really desirable from a performance perspective.

**Comment by ajcvickers** [comment]
This is not something we are planning to implement.
