### ISSUE TITLE
Equality of Claim

### ISSUE THREAD

**Issue by HailOdin** [dotnet/corefx#33861]
https://github.com/dotnet/corefx/blob/master/src/System.Security.Claims/src/System/Security/Claims/Claim.cs

```
var claim1 = new Claim("Role", "Admin");
var claim2 = new Claim("Role", "Admin");

Console.WriteLine(claim1 == claim2); // False

//----------

var claims = new[]
{
    new Claim("Role", "Admin"),
    new Claim("Role", "Admin")
};

Console.WriteLine(string.Join(',', claims.Distinct().Select(c => c.Value))); // Admin,Admin
```

Shouldn't `Equals` be implemented for claims? I think those two claims should be equal, they have the same type and the same value.

If I wanted to remove duplicates from some list of claims, using something like `Except`/`Distinct` is not possible, and I have to use `Where` and compare both type and value myself.

**Comment by khellang** [comment]
What about `ValueType` and `Issuer`? I'm not sure an `Equals` method is as straight forward as it seems. It's probably best to just use something like https://github.com/IdentityModel/IdentityModel2/blob/master/src/ClaimComparer.cs

**Comment by bartonjs** [comment]
As @khellang pointed out, Claim has multiple "obvious" definitions of Equals:

* Just Type and Value (`return ToString().Equals(other.ToString())`)
  * Case/culture sensitive/not.
* Type/Value/ValueType/Issuer
  * Maybe `null` ValueType and/or Issuer means "match anything", maybe it means only-matches-null
  * Case/culture sensitivity again
* There's also OriginalIssuer, Subject, CustomSerializationData, and Properties.
  * More "what does null mean" and "what sort of case/culture sensitivity" problems.

Since `CustomSerializationData` and `Properties` aren't guarded from modification they'd either need to be excluded or would cause the Claim to violate the guideline that GetHashCode and Equals should not depend on mutable data.  (Excluding them would, of course, create weird corner cases when using Claim as a dictionary key)

In the end, the type is just too flexible to define intrinsic equality; and is better served by external comparers.
