### ISSUE TITLE
[arm32/Windows] System.IO.Ports.Tests failures on arm32 windows

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#34029]
Running the arm32 tests on windows for System.IO.Ports.Tests produced the following results: passed 966/967 tests.

The failing test is System.IO.Ports.Tests.GetPortNames.AllGetPortNamesAreInHelperPorts and it failed with the following message:
```
脉\0\0\xffff\xffff窐螏⁔裲\0\0\0\0\0\0\0蕀\x18\0稸螏ꍍ能稔螏빩能\0\0\0\0\0\0\x02\0က蒀࿰\0윂裱\0\0쀀脉\x01\0윂裱\0\0穈螏녥胶媗㼡媗㼡穨螏늯胶\0\0\0\0\0\0\x03槼쀢\x01\0竀螏ꃧ胴\0\0窐螏脉倀㼡\0\0\0\0\x01\0\0\0 裲樀쀢ৈজজঀজঀ\0\0耀觐\x04\0\0\0\"\0뀴詆■&笘螏疃詆耀觐\x04 is not present in PortHelper.GetPorts result\r\nPortHelper Ports: \r\nSerialPort Ports: 脉\0\0\xffff\xffff窐螏⁔裲\0\0\0\0\0\0\0蕀\x18\0稸螏ꍍ能稔螏빩能\0\0\0\0\0\0\x02\0က蒀࿰\0윂裱\0\0쀀脉\x01\0윂裱\0\0穈螏녥胶媗㼡媗㼡穨螏늯胶\0\0\0\0\0\0\x03槼쀢\x01\0竀螏ꃧ胴\0\0窐螏脉倀㼡\0\0\0\0\x01\0\0\0 裲樀쀢ৈজজঀজঀ\0\0耀觐\x04\0\0\0\"\0뀴詆■&笘螏疃詆耀觐\x04\r\n\r\nExpected: True\r\nActual:   False
   at System.IO.Ports.Tests.GetPortNames.AllGetPortNamesAreInHelperPorts() in F:\git\corefx\src\System.IO.Ports\tests\SerialPort\GetPortNames.cs:line 64
```

**Comment by danmosemsft** [comment]
GetCommPortsViaQueryDosDevice() (which uses ::QueryDosDevice) returned nothing while GetPortNames() (which uses HARDWARE\DEVICEMAP\SERIALCOMM) returned something (although to my eye it looks like a lot of garbage)

If serial ports work fine on this SKU, then we should just simply disable this one single test for Windows IoT, because it just means that they disabled ::QueryDosDevice on this SKU.

I am curious why the result looks like garbage.

@krwq apparently you're famliar?

**Comment by krwq** [comment]
closing as dup of https://github.com/dotnet/corefx/issues/32847
I haven't had a chance to look at this yet
