### ISSUE TITLE
How to use Microsoft.Bcl.Async with Managed C++ projects

### ISSUE THREAD

**Issue by rayncc** [dotnet/corefx#34093]
We are working on a solution with .Net 4.0 (for some reason), and we have two projects here:
1. Project A is a C# project, which imports Microsoft.Bcl.Asyc
2. Project B is a VC++ Project (CLR dll), which adds Project A as a reference.

Now project B can not work, because Microsoft.Bcl requires project B to install nuget package Microsoft.Bcl, But we cannot install it on a VC++ project. Also, we got warnings like 

> Warning	MSB3268	The primary reference "Microsoft.Threading.Tasks" could not be resolved because it has an indirect dependency on the framework assembly "System.Runtime, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". 

And meanwhile, the types in Project A cannot be recognized in Project B.
We have tried manifest file or configuration  file to redirect the upper assemblies to the lasted version, but they didn't work.

Any solutions for this?

I have put a sample project for this situation

[BCLWithManagedCpp.zip](https://github.com/dotnet/corefx/files/2678994/BCLWithManagedCpp.zip)

**Comment by lextm** [comment]
First, this is a repo for .NET Core, so discussing your .NET Framework 4.0 issues is not quite appropriate.

Second, .NET Framework 4.0 lifecycle has ended a long while ago (since January 2016), so for whatever reasons you shouldn't use it any more. Microsoft FAQ can be found at https://support.microsoft.com/en-ca/help/17455/lifecycle-faq-net-framework

Third, if you really want o get it resolved, use the old versions of relevant NuGet packages. Their latest versions should match the policies to only support 4.5.2 and above, but their old versions might support 4.0.

**Comment by karelz** [comment]
Does not seem to be related to .NET Core, closing.
If there is repro on .NET Core, let us know and we can reopen.

As @lextm said above, it looks like you are using [unsupported .NET version](https://en.wikipedia.org/wiki/.NET_Framework_version_history#Overview). The nuget packages you're using likely do not support that targeted framework. Either use older *unsupported) nuget versions, or upgrade to newer .NET Framework.
