### ISSUE TITLE
Discussion: DispatchProxy and default interface methods

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/corefx#34182]
This is meant to be a discussion of how to treat [default interface methods](https://github.com/dotnet/csharplang/blob/21dc9561aeffc87a31da44588ce7ed6930ee3333/proposals/default-interface-methods.md) in the [DispatchProxy](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.dispatchproxy) class.

Since DispatchProxy is [pretty much not used](https://apisof.net/catalog/System.Reflection.DispatchProxy) by anyone (but we consider it important enough for inclusion in NetStandard 2.1), here's a recap of what it does:

```csharp
interface IFoo
{
    int Frob();
}

class Program : DispatchProxy
{
    static void Main(string[] args)
    {
        IFoo myProxy = DispatchProxy.Create<IFoo, Program>();
        int result = myProxy.Frob();
        Console.WriteLine($"myProxy.Frob returned {result}");
    }

    protected override object Invoke(MethodInfo targetMethod, object[] args)
    {
        Console.WriteLine($"Invoked method {targetMethod.Name} with {args.Length} arguments");
        return 42;
    }
}
```

Above program will print `Invoked method Frob with 0 arguments` followed by `myProxy.Frob returned 42`.

`DispatchProxy` can be used to mock/implement an interface at runtime without requiring the underlying platform to support `Reflection.Emit` (i.e. this _works_ on UWP).

## The Problem

One of the points of default interface methods is to allow API authors to add new methods to their interfaces without breaking the consumer. If we look at the problem this way, it would mean that for this interface:

```csharp
interface IFoo
{
    // NOTE: here's a default implementation that is used when nobody else provides an impl
    int Frob() => 42;
}
```

we would need to make sure that if someone uses `DispatchProxy` to implement the interface and a new default interface implementation is added, the `DispatchProxy`s `Invoke` method doesn't see `MethodInfo`s it's not prepared to handle.

On the other hand, the default interface method resolution rules are defined in a way that adding a default interface method implementation to an existing abstract interface method is a non-breaking change.

These two rules are in conflict.

What use cases do people have for `DispatchProxy`? If we were to keep calling the `Invoke` method even if there's a default interface method implementation available, would that be a problem?

**Comment by MichalStrehovsky** [comment]
Tagging a couple people who commented on/filed `DispatchProxy` related issues: @Mutuduxf, @ggeurts, @ElderJames, @Semyntax, @baron-zhang-avepoint, @shcemApp, @yfakariya, @peter-f-s, @roncain

**Comment by nguerrera** [comment]
I see, I missed the case of adding a default implementation to existing method. I see now that you called it out from the beginning. Nevermind, then.

**Comment by morganbr** [comment]
Adding @mconnew for WCF thoughts since I think that's the primary usage. In WCF, or anything else that just proxies to another implementation, I'd think that the preferred choice would just be to send the call along to Invoke since it's general-purpose code that can find the target via reflection (and would correctly choose whether to use the default interface implementation).

**Comment by mconnew** [comment]
I agree with @morganbr. DispatchProxy was created as a replacement for the .NET remoting transparent proxy feature that WCF uses on .NET Framework in order to create an object at runtime which can be cast to an interface and send the method call to a remote service. With the concrete usage that WCF has for DispatchProxy (service contract interfaces), default interface methods make zero sense to use as there is no concrete implementation in process. If you add a new method to the service contract interface, it's because a new method has been added on the service side. The issue of having the interface on the client and server side mismatched is resolved using other techniques in WCF.  
Having said that, a customer might still provide an interface to WCF that has a default interface method and we have to do something reasonable and intuitive in that case. Conceptually all interface methods have been implemented on the service side so a default interface method should be dispatched to the Invoke method like all other methods.
Taking a step back from the WCF specific usage and looking at the broader picture, I think it would make sense to have a method in DispatchProxy that a derived implementation could call in the case that an interface method isn't expected. In the Invoke method override, an implementation could call that method if it doesn't recognize the method that was passed to it. So something like this:

```csharp
interface IFoo
{
    int Fizz();
    int Buzz() => 0xFEEFEE;
}

class Program : DispatchProxy
{
    static void Main(string[] args)
    {
        IFoo myProxy = DispatchProxy.Create<IFoo, Program>();
        int result = myProxy.Fizz();
        Console.WriteLine($"myProxy.Fizz returned {result}");
        result = myProxy.Buzz();
        Console.WriteLine($"myProxy.Buzz returned {result}");
     }

    protected override object Invoke(MethodInfo targetMethod, object[] args)
    {
        Console.WriteLine($"Invoked method {targetMethod.Name} with {args.Length} arguments");
        if (targetMethod.Name == "Fizz")
            return 42;
        if (base.TryInvokeDefault(method, object[] args, out object result))
            return result;
        throw new Exception($"Unknown method {targetMethod.Name}");
    }
}
```

WCF reflects over an interface and creates a contract description based on the methods and attributes on those methods. Will default interface methods look the same as regular interface methods when reflecting? I want to make sure that we see these methods when constructing our internal description for making a remote call.

**Comment by ElderJames** [comment]
Hello everyone,
I developed a simple AOP class library with dispatchproxy, https://github.com/ElderJames/CoreProxy.

```csharp
    class Program
    {
        static void Main(string[] args)
        {
            var poxy1 = (targetInterface)ProxyGenerator.Create(typeof(targetInterface), new SampleProxy("coreproxy1"));
            poxy1.Write("here was invoked"); //---> "here was invoked by coreproxy1"

            var poxy2 = (targetInterface)ProxyGenerator.Create(typeof(targetInterface), typeof(SampleProxy), "coreproxy2");
            poxy2.Write("here was invoked"); //---> "here was invoked by coreproxy2"

            var poxy3 = ProxyGenerator.Create<targetInterface, SampleProxy>("coreproxy3");
            poxy3.Write("here was invoked"); //---> "here was invoked by coreproxy3"
        }
    }


    public class SampleProxy : IInterceptor
    {
        private string proxyName { get; }

        public SampleProxy(string name)
        {
            this.proxyName = name;
        }

        public object Intercept(MethodInfo method, object[] parameters)
        {
            Console.WriteLine(parameters[0] + " by " + proxyName);
            return null;
        }
    }

    public interface targetInterface
    {
        void Write(string writesome);
    }
```

**Comment by MichalStrehovsky** [comment]
Thanks @mconnew! To your question: default interface methods are going to show up in reflection the same way as any other interface methods, except they won't be abstract.

Seems like the consensus is to keep calling the `Invoke` method as usual, even if there's a default implementation available. The `TryInvokeDefault` method is something we can implement if there ends up being demand for such feature. It's pretty non-trivial to implement that.

I'm tracking some bugfix level work we'll need to do for `DispatchProxy` in dotnet/coreclr#15646 (the issue is there because I need to be able to reference it from the CoreCLR project for tracking, but the fix will be in CoreFX).
