### ISSUE TITLE
Coding style consistency

### ISSUE THREAD

**Issue by ghost** [dotnet/corefx#34243]
.NET has a long history. Its naming conventions vary from time to time, so there are different styles in the class libraries. Since we have determined a new style, why not convert those old ones for consistency? It would not be a breaking change.

For example, the private fields which are named `m_member`. :-)

```
We use _camelCase for internal and private fields and use readonly where possible. Prefix internal and private instance fields with _, static fields with s_ and thread static fields with t_. When used on static fields, readonly should come after static (e.g. static readonly not readonly static). Public fields should be used sparingly and should use PascalCasing with no prefix when used.
```

**Comment by karelz** [comment]
I believe some types are sensitive on private field names due to serialization - @ViktorHofer can you confirm?

Beside that, changing code style or reformatting code is done usually when someone needs to modify the old code and wants to modernize it along the way. We do not have plans to do it more proactively. I think we might be open to contributions though - @danmosemsft @stephentoub thoughts?

**Comment by lchhh1** [comment]
Thanks for the quick replies! Almost forgot the serializable classes. I thought that private members would only be accessed by reflection.

**Comment by joperezr** [comment]
Given the above explanation from @danmosemsft I'll go ahead and close this for now as most of the inconsistencies with our formatting are due to Serialization. Feel free to go ahead and reopen if you find concrete cases where we don't follow conventions and classes aren't serializable.
