### ISSUE TITLE
Microsoft.VisualBasic.Asc/Chr use the Default Encoding, witch is different between .Net Core 3.0 Preview 1 and .Net Framework

### ISSUE THREAD

**Issue by Lohnegrim** [dotnet/corefx#34256]
Version:   3.0.100-preview-009812
 Commit:    e3abf6e935

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-009812\

Host (useful for support):
  Version: 3.0.0-preview-27122-01
  Commit:  00c5c8bc40

Hi,
I noticed that the Microsoft.VisualBasic.Asc and Microsoft.VisualBasic.Chr are relaying on System.Text.Encoding.Default, but since this Returns Different Results in the .Net Framework(CodePage: 1252 on my System) and in .Net Core(CodePage: 65001 on my System), are these not directly compatible.
Even if I add a NuGet Reference to 'System.Text.Encoding.CodePages' and Call 'Encoding.RegisterProvider(CodePagesEncodingProvider.Instance)' there are still differences.
For Excample: 
Console.Writeline(Asc(Chrw(172)))
Returns on Net Core: -15700
Returns on Net Framework: 172

This may/does lead to unexpected results when a Application that relays on Asc/Chr gets converted from .Net Framework to .Net Core 3.0

**Comment by cston** [comment]
@Lohnegrim, should your example be `Asc(Chr(172))` instead (using `Chr()` rather than `ChrW()`)?

It looks like `Asc()` relies on `System.Text.Encoding.Default.CodePage` (which is different between .NET Core and .NET Framework, as you mentioned) while `Chr()` relies on `System.Threading.Thread.CurrentThread.CurrentCulture.TextInfo.ANSICodePage`.

**Comment by cston** [comment]
@Lohnegrim, thanks for reporting this issue.
