### ISSUE TITLE
dotnet restore on failing on Ubuntu 18.04.1

### ISSUE THREAD

**Issue by jeroenlandheer** [dotnet/corefx#34293]
When running `dotnet restore` on a Linux build agent (Ubuntu 18.04.1), I'm getting the following error:

```
GSSAPI operation failed with error - An invalid status code was supplied (Configuration file does not specify default realm).
```

This happens when it is trying to download a package from a TFS 2018 feed. 
When I use NuGet (based on mono) for restoring packages everything works fine.

dotnet sdk version: 2.2.101
Build agent version: 2.136.1

**Comment by am11** [comment]
Based on the commentary in https://github.com/NuGet/Home/issues/6902 and this documentation: https://github.com/Microsoft/artifacts-credprovider/blob/c188c4e2/README.md, you could try SSH'ing into your build agent and install credential provider as follow:

```sh
mkdir -p ~/.nuget/plugins/netcore

curl -LO https://github.com/Microsoft/artifacts-credprovider/releases/download/0.1.8/Microsoft.NuGet.CredentialProvider.tar.gz

tar -xzf ./Microsoft.NuGet.CredentialProvider.tar.gz -C ~/.nuget/plugins/netcore

dotnet restore --interactive
# this will interactively read username and password and will store auth token
# at ~/.local/share/MicrosoftCredentialProvider

# subsequently use `dotnet restore` without --interactive until the token expires
```

**Comment by joshfree** [comment]
@bartonjs

**Comment by bartonjs** [comment]
I agree with @am11's assessment: This is a problem that the Linux build agents require manual setup work to get the credential provider (and perhaps register it); because the TFS feed requires authentication.

I won't disagree that there's room for improvement in the experience, but that belongs to the VSTS team and/or the NuGet/dotnet.exe team.

Closing as external/duplicate to https://github.com/NuGet/Home/issues/6902.
