### ISSUE TITLE
MissingMethodException for System.Security.Permissions.SecurityPermission..ctor(System.Security.Permissions.PermissionState)

### ISSUE THREAD

**Issue by mjsabby** [dotnet/corefx#34308]
Looks like the issue I opened in https://github.com/dotnet/coreclr/issues/21742 probably belongs here.

New in .NET Core 3.0 Preview 1 compared to 2.2 is a `MissingMethodException` for `Void System.Security.Permissions.SecurityPermission..ctor(System.Security.Permissions.PermissionState)` triggered by the following line of code:

```csharp
            new SecurityPermission(PermissionState.Unrestricted).Demand();
```

I know we gutted CAS in this release, and so it's probably related to that change in some way, but I did not expect this to break so it does seem like a bug, but I've not root caused it yet.

Looks like the following types were introduced in System.Runtime.Extensions ... but it is not from @jkotas's change, so maybe this isn't related to that.

`System.Security.Permissions.PermissionState`
`System.Security.PermissionSet`
`System.Security.IStackWalk`

**Comment by mjsabby** [comment]
Related. https://github.com/dotnet/corefx/issues/32745 https://github.com/dotnet/corefx/issues/33874

**Comment by jkotas** [comment]
You need to pickup new netcoreapp3.0 compatible version of the `System.Security.Permissions.SecurityPermission` package.

https://github.com/dotnet/corefx/issues/32745#issuecomment-429057133 talks about it.

cc @ericstj @danmosemsft

**Comment by mjsabby** [comment]
PR https://github.com/dotnet/corefx/pull/33379 introduced the issue.

And the issue is that if you're using the System.Security.Permissions nuget package some of the type forwards are going to System.Runtime.Extensions and some of them are going to System.Security.Permissions.

This is a breaking change because System.Security.Permissions is targetting NS2.0, so I'm assuming one will have to pick up a new package, but do we do breaking changes like these?

**Comment by mjsabby** [comment]
@jkotas, alright I read your comment, so it looks like we've done this before.

**Comment by mjsabby** [comment]
Ok. I'd just like to point out that some Newtonsoft.Json packages (depends on the different target flavors) they are are doing this SecurityPermission stuff to see if dynamic code gen is available or not. And so that's how I ran into it.

https://github.com/JamesNK/Newtonsoft.Json/blob/d48558b53b0a516bfa15c1af50231ea1ba7c2454/Src/Newtonsoft.Json/Serialization/JsonTypeReflector.cs#L469

I wonder how many people will run into this ...

In any case @maryamariyan @ericstj @danmosemsft do we have an ETA on when we'll have the System.Security.Permissions package fixed up? We've potentially broken .NET Core 3.0 preview builds that are using 
Microsoft.Windows.Compatibility and directly or indirectly relying on code that is calling this stuff.

**Comment by danmosemsft** [comment]
I think I need guidance from @ericstj in this case.

**Comment by mjsabby** [comment]
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Permissions" Version="4.5.0" /> <!-- What is our response to someone who does this? -->
    <PackageReference Include="System.Security.Permissions" Version="4.6.0-preview.19054.1" /> <!-- Maybe it's just do this, and it seems according to @jkotas that's what we've done before. -->
  </ItemGroup>

</Project>

```

While I find it unsatisfying, the above snippet is what I've done to unblock myself.

**Comment by danmosemsft** [comment]
@ericstj can you advise what is required here?

**Comment by ericstj** [comment]
With https://github.com/dotnet/corefx/commit/51e1541da82253ab7d10a7c00a2fd93b8e41c341 we pushed types down from System.Security.Permissions to System.Runtime.Extensions.  TypeForwards were added to System.Security.Permissions that permit code compiled against the old location of the types to continue to work.

I don't reproduce a run-time failure.  On preview1 bits (prior to change) I see that the app still runs correctly.  On preview2 I see the following compiler error:
```
 error CS0433: The type 'PermissionState' exists in both 'System.Runtime.Extensions, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Security.Permissions, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
```
I tried both directly referencing S.S.P as well as indirect via project reference.  Compiling against the old location and running on new should work due to typeforwards.  I couldn't force the runtime exception.

The only time I'd imagine you'd get the missing-method exception would be if you compiled against the *new* location of PermissionState (S.R.E) but ran against the old S.S.P (which thinks it defines PremissionState).  Let me know if you're still producing the runtime error and share a full repro with SDK version and shared framework version and I can take a look.

The fix is as @jkotas mentioned: upgrade your System.Security.Permissions to the latest out of the 3.0 branch.  In general, it's probably a good idea to use the latest packages that are being co-developed with netcoreapp3.0 rather than using the old 2.1 packages on the 3.0 framework.

It's unfortunate that this sort of upgrade is "forced" by the compiler error but we have done the same in the past (in fact we did it a ton between 1.0 and 2.0).  Unfortunately there isn't a great way to communicate that a lower stack component requires an update to the higher stack component.  We could absorb System.Security.Permissions into the shared framework to force the update it but that has even worse *legacy garbage* characteristics (to quote @jkotas).  Right now we made this call based on ref-counts from multiple customers hitting this including many hitting it in desktop binaries they wish to reuse.

At the very least we should relnote the compiler error, but I want to close the loop on the runtime exception.  Can you please let me know if you still reproduce this?

**Comment by ericstj** [comment]
I tried again on the latest and couldn't reproduce a runtime issue.

Here's the error I see:
```
error CS0433: The type 'PermissionState' exists in both 'System.Runtime.Extensions, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Security.Permissions, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
``

The fix is to upgrade the PackageReference of System.Security.Permissions to latest.

Please reactivate if you have a repro of a runtime issue.
