### ISSUE TITLE
ValidateToStringUsingWhoami/ValidateToString tests are buggy

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#34395]
ValidateToStringUsingWhoami initializes `endSid` to 0 and then never sets it to anything other than its initial value:
https://github.com/dotnet/corefx/blob/b04b5f22e933b0dae74af3e8b4d1bd5c12cbed01/src/System.Security.Principal.Windows/tests/SecurityIdentifierTests.cs#L68
We then check if `endSid > startSid`, which can only happen if `startSid` is `-1` due to the `int startSid = output.IndexOf("S-1-5-")` not finding the target string, in which case `output.Substring(startSid, (endSid - startSid))` will throw an exception due to passing `-1` as the offset to `Substring`:
https://github.com/dotnet/corefx/blob/b04b5f22e933b0dae74af3e8b4d1bd5c12cbed01/src/System.Security.Principal.Windows/tests/SecurityIdentifierTests.cs#L81

Additionally, the test seems to assume that the user's SID begins with `S-1-5-`, which mine doesn't, which is how I found the above.  The ValidateToString test has this same issue.

cc: @bartonjs, @Wraith2

**Comment by Wraith2** [comment]
Interesting, I assume it's the 5 that's different in yours, what do you have there out curiosity?

**Comment by stephentoub** [comment]
12

**Comment by Wraith2** [comment]
I'm not sure if that's a value that should be handled or not. The first number is sid version, if it isn't 1 then this test should fail until rewritten to understand version 2. The second number is the [IdentifierAuthority](https://github.com/dotnet/corefx/blob/b04b5f22e933b0dae74af3e8b4d1bd5c12cbed01/src/System.Security.Principal.Windows/src/System/Security/Principal/SID.cs#L18) which doesn't have 12 as a defined value. It's functioning because the interop code translating it is casting and not checking if it's defined. I don't know what 12 means so while I can validate that it's a number that's about all I can do.

**Comment by bartonjs** [comment]
FWIW https://en.wikipedia.org/wiki/Security_Identifier says 12 is AzureAD.

**Comment by Wraith2** [comment]
Ah, my mistake was checking the [msdn docs](https://docs.microsoft.com/en-gb/windows/desktop/api/winnt/ns-winnt-_sid_identifier_authority) then... 😉
