### ISSUE TITLE
SetAllZeroVector256, SerAllVector256 Moved to Vector256 from Avx

### ISSUE THREAD

**Issue by Anipik** [dotnet/corefx#34444]
There is inconsistency between the coreclr and corefx. we moved some of the functions like 

SetAllZeroVector256
SetAllVector256

to vector 256 class from Avx but they are still present in the ref assembly
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Intrinsics/ref/System.Runtime.Intrinsics.cs#L626

Due to this when we try to use any of these method we get
```
System.MissingMethodException: 'Method not found: 'System.Runtime.Intrinsics.Vector256`1<!!0> System.Runtime.Intrinsics.X86.Avx.SetAllVector256(!!0)'.'
```
Repro Program 
``` C#
using System;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;


namespace ConsoleApp14
{
    class Program
    {
        static void Main(string[] args)
        {
            Vector256<int> scaleVector256 = Avx.SetAllVector256(1);
        }
    }
}
```

This bug is present in .netcore preview 1 also. I am not sure why it was not caught by ApiCompat as there is no suppression for this function

cc @danmosemsft @eerhardt @tannergooding

**Comment by danmosemsft** [comment]
Good find, I'm curious how this got past APIcompat as well.

**Comment by tannergooding** [comment]
Got a fixup here: https://github.com/dotnet/corefx/pull/34449

I got @ericstj to stop by and take a look and it appears that there were (still are) multiple issues with GenAPI, including:
* The reference assembly was listed as one of the implementations in ApiCompat
* ApiCompat wasn't able to resolve the location of S.P.Corelib
* ApiCompat, when it could resolve S.P.Corelib didn't fail due to the APIs that were removed

**Comment by ericstj** [comment]
> The reference assembly was listed as one of the implementations in ApiCompat

Reference path was being passed as an implementation candidate.  Even though this is last it seems dangerous since it could mean API compat is potentially diffing the same files.  Looking at https://github.com/dotnet/arcade/blob/3220be53ac764d9ee160b0bc64baa492af219aa7/src/Microsoft.DotNet.ApiCompat/build/Microsoft.DotNet.ApiCompat.targets#L46 this appears to be expected, but a better alternative might be do pass specific files rather than directories.  Probably a feature rather than the actual problem we're hitting here.

Ultimately there is something *fishy* here that's resulting in API compat missing these changes.  We should debug to find out what's going on.  /cc @ViktorHofer @wtgodbe

**Comment by danmosemsft** [comment]
Can we please have an active issue for the genapis?

**Comment by ericstj** [comment]
I think you mean API Compat, right?

**Comment by tannergooding** [comment]
I created https://github.com/dotnet/arcade/issues/1730 to track the overall issue that still remains

**Comment by danmosemsft** [comment]
Uh, yes.
