### ISSUE TITLE
HTTP2: Make HTTP2 tests run against platform handlers

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#34462]
We have some HTTP2-specific tests in SocketsHttpHandler.Http2.cs.

These are currently only running against SocketsHttpHandler. To ensure consistent behavior, we should make these run against platform handlers as well, at least to the extent reasonably possible.

**Comment by davidsh** [comment]
>These are currently only running against SocketsHttpHandler. To ensure consistent behavior, we should make these run against platform handlers as well, at least to the extent reasonably possible.

I am concerned about the value in this.  The specifics of other HTTP/2 implementations are not necessarily something we should be testing against.  We have no ability fix other implementations such as WinHTTP, WinInet (UWP) etc.  So, why have protocol specific tests against them?

We would probably end up skipping many of those tests due to specific differences in those implementations.

**Comment by karelz** [comment]
I agree with @geoffkizer. If we find that some tests are flaky or problematic on other implementations, we can change our position.
Running them at least once on platform handlers is IMO valuable. Given the churn and new tests being brought up in the upcomming months, it would be valuable to run them on regular basis to avoid accidental regressions and mistakes + get cross-implementation coverage right away.

**Comment by davidsh** [comment]
>I agree with @geoffkizer. If we find that some tests are flaky or problematic on other implementations, we can change our position.

FYI.  The team discussed this issue in the Wed. team meeting.  And we agreed on a slightly different conclusion.

**Comment by geoffkizer** [comment]
Fixed by #34630
