### ISSUE TITLE
Continuous Hang on XmlSerializer

### ISSUE THREAD

**Issue by meehanman** [dotnet/corefx#34620]
When running the following code. The Class `CommunicationRecordList` causes the XmlSerializer to freeze on this point indefinatly. 

    XmlSerializer x = new XmlSerializer(typeof(CommunicationRecordList));

    public class CommunicationRecordList : List<CommunicationRecord>
    {
    }

    public class CommunicationRecord
    {
        public string RecordNumber;
        public Plan Plan;
    }
    public class Plan : List<Plan>
    {
        public string PlanName
    }

**Comment by stephentoub** [comment]
This stack overflows, on both .NET Framework and .NET Core, due to unbounded recursion in https://github.com/dotnet/corefx/blob/4febb444f82cabed2b3df186bcc8e9ad0b31dbf9/src/System.Private.Xml/src/System/Xml/Serialization/Models.cs#L187.

**Comment by Lxiamail** [comment]
@meehanman looks like "public class Plan : List<Plan>" triggered stack overflow. Is this real world scenario using this code?

**Comment by meehanman** [comment]
It was part of a real world scenario of business logic @Lxiamail.

I've refactored the code to take out the culpret but I still feel as though .Net could handle the stackoverflow better.

**Comment by Lxiamail** [comment]
@meehanman Yes, I agree that .NET could handle the stackoverflow better. However, due to the compat risk of making the fix and this is relatively corner case issue, we would recommend work around instead of changing the product. Thank you for being flexible.

**Comment by GSPP** [comment]
Should we not at least throw a better exception? Stack overflow exceptions tend to kill the process. They are very inconvenient to debug. Killing a web app process is particularly bad because it crashes all requests, not just the current one.

**Comment by Lxiamail** [comment]
@GSPP I agree with you for general best practice of exception and diagnostic perspectives. However, since this has been the behavior on .NET Framework for over 15 years and on .NET Core as well, I worry about changing exception could also break existing customers' program.  I know sound obscure, but it happens from time to time with millions customers using .NET Framework.  In this case, since the work around is relatively straight forward, our best practice is not changing .NET Framework code even though the code is not ideal.

**Comment by GSPP** [comment]
What customer would depend on unbounded recursion causing a stack overflow? :rofl:
