### ISSUE TITLE
Hide the S.T.Json sources within the consuming project or move to a custom subdirectory

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#34793]
Currently, when the user consumed the source package, the S.T.Json source files show up at the root of their project (for example within VS). Ideally, the source package would behave like other NuGet packages and the sources wouldn't bloat the consumers solution view and hide their own source files.

If that is not feasible, then we should consider moving the source files to a custom named subdirectory to keep the root directory cleaner.

Feedback from https://github.com/Azure/azure-sdk-for-net-lab/pull/71#discussion_r250378908

cc @KrzysztofCwalina, @ericstj, @joperezr

**Comment by joperezr** [comment]
Chatted offline with @ericstj and we believe that it wouldn't be good to completely hide the sources from the .csproj since that would give the feel that this is a regular NuGet package and hide the fact that we are actually compiling the source. PR #34812 is addressing this by moving the contents into a subfolder instead.

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/corefx/pull/34812. Tyvm @joperezr
