### ISSUE TITLE
Request for Double.HasExponent()

### ISSUE THREAD

**Issue by Symbai** [dotnet/corefx#34847]
I have a code where I'm iterating through more than a million of double values and have to check if each value contains an exponent. Currently I'm using code like this:

```
var doubles = new double[12000000];
for (int i = 0; i < doubles.Length; i++)
{
	if (doubles[i].ToString(CultureInfo.InvariantCulture).IndexOf("e", StringComparison.OrdinalIgnoreCase) == -1)
		//...
}
```

But instead of creating a string for more than a million of times I'm wondering if there is a faster approach. Somehow .NET has to know if there is an exponent like it does on ToString() when inserting an 'e' so there could also be a method doing the same but just return true / false instead of creating a string.

**Comment by danmosemsft** [comment]
@tannergooding

**Comment by tannergooding** [comment]
A double-precision floating-point value is a 64-bit value constructed from 3 parts:
* A 1-bit sign
* An 11-bit exponent
* A 52-bit signifiand

So in all cases, floating-point values have exponents.

It seems like what you are asking for, however, is whether a resulting call to `ToString()` will cause the value to be output in "scientific" notation. This is difficult because it not only depends on the format specifier passed in (some will never trigger it, some will always trigger it, some depend on the number of digits you request, etc), but it can't readily be computed without doing a good majority of the work that `ToString()` would be doing anyways.

Could you provide some further details on why you are needing to determine if a `ToString()` call will be outputting the value in "scientific" notation?

**Comment by Symbai** [comment]
> It seems like what you are asking for, however, is whether a resulting call to `ToString()` will cause the value to be output in "scientific" notation. 

I'm sorry, yes this is what I meant. I'm reading a large array of bytes where I know all of them are numbers and I know all of these numbers are stored in a human readable format but I don't know which type (i.e. integer, float, double). So I have to guess. Could it be type integer, long, double etc. My approach is that if you for example convert a long number (8 bytes) to byte array and then to double most of the time this number has a scientific notation. But it's very rare that a double number is supposed to have a scientific notation when it's supposed to be human readable. For example a progress bar value might be 120d, but a programmer wouldn't set it to 1.352352e-234, that doesn't make sense. 

Currently the only way I know how to see if a double value would contain this scientific notation is to call it to a string and then check for the 'e'. But I wish there would be a faster approach without calling it to a string first. How does .NET knows when it has to append an 'e' or scientific notation from a double value? This is what I'm looking for to do the same just without creating a string.

There are some existing functions to see if a double value is nan or infinite. So I thought I might request to have another for checking if a double value has a scientific notation. I've seen there were similar requests around the internet before and in all the answer was to check for 'e'. But in my case when you do this a million time it's a bottleneck I would like to avoid especially since I don't really need this string at all.

In case you might not want to have such a method, could you please at least point me to the code showing how .NET knows whether it needs a scientific notation or not?

**Comment by tannergooding** [comment]
> In case you might not want to have such a method, could you please at least point me to the code showing how .NET knows whether it needs a scientific notation or not?

There are a bunch of code-paths, each with their own logic. For the default format specifier (which is `G`), the logic is here: <https://source.dot.net/#System.Runtime.Numerics/System/Globalization/FormatProvider.Number.cs,3983315d94b55804>

Basically, it depends on the number of "significant" digits the user wants included in the string and the actual resulting number. Basically, for `G`, if the scale of the number is greater than the number of digits requested or if the scale is less than -3, we switch to scientific notation. Otherwise, we just print the number of significant digits requested.

For example, `Math.PI` will never use scientific notation as it has an integral part with only 1 digit and a scale greater than -3:
```
     3.14159265358979
G    3.14159265358979
G0   3.14159265358979
G1   3
G2   3.1
G3   3.14
G4   3.142
G5   3.1416
G6   3.14159
G7   3.141593
G8   3.1415927
G9   3.14159265
G10  3.141592654
G11  3.1415926536
G12  3.14159265359
G13  3.14159265359
G14  3.1415926535898
G15  3.14159265358979
G16  3.141592653589793
G17  3.1415926535897931
G18  3.1415926535897931
G19  3.1415926535897931
```

`-60` will switch to scientific notation for `G1` because there are two significant integral digits:
```
     -60
G    -60
G0   -60
G1   -6E+01
G2   -60
G3   -60
G4   -60
G5   -60
G6   -60
G7   -60
G8   -60
G9   -60
G10  -60
G11  -60
G12  -60
G13  -60
G14  -60
G15  -60
G16  -60
G17  -60
G18  -60
G19  -60
```

`double.Epsilon` will always use scientific notation as its scale is less than -3:
```
     4.94065645841247E-324
G    4.94065645841247E-324
G0   4.94065645841247E-324
G1   5E-324
G2   4.9E-324
G3   4.94E-324
G4   4.941E-324
G5   4.9407E-324
G6   4.94066E-324
G7   4.940656E-324
G8   4.9406565E-324
G9   4.94065646E-324
G10  4.940656458E-324
G11  4.9406564584E-324
G12  4.94065645841E-324
G13  4.940656458412E-324
G14  4.9406564584125E-324
G15  4.94065645841247E-324
G16  4.940656458412465E-324
G17  4.9406564584124654E-324
G18  4.9406564584124654E-324
G19  4.9406564584124654E-324
```

`double.MaxValue` will also always use scientific notation as its scale is greater than any number of digits you can request:
```
     1.79769313486232E+30
G    1.79769313486232E+308
G0   1.79769313486232E+308
G1   2E+308
G2   1.8E+308
G3   1.8E+308
G4   1.798E+308
G5   1.7977E+308
G6   1.79769E+308
G7   1.797693E+308
G8   1.7976931E+308
G9   1.79769313E+308
G10  1.797693135E+308
G11  1.7976931349E+308
G12  1.79769313486E+308
G13  1.797693134862E+308
G14  1.7976931348623E+308
G15  1.79769313486232E+308
G16  1.797693134862316E+308
G17  1.7976931348623157E+308
G18  1.7976931348623157E+308
G19  1.7976931348623157E+308
```

**Comment by tannergooding** [comment]
Other format specifiers each have their own behavior. `E`, for example, always uses scientific notation. `C`, `F`, `N`, and `P` never do.

**Comment by Symbai** [comment]
I'm interested in the default format specifier like in my example above. Thanks for the link, I believe it's exactly what I was looking for.
