### ISSUE TITLE
Why SpinLock is not re-entrant?

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/corefx#34919]
if spin lock has enough information to detect deadlock (via thread owner tracking) and throw exception, why is it not re-entrant? (or why there is no option to make it re-entrant).

**Comment by Clockwork-Muse** [comment]
Because it's supposed to be low-level, and by default there's **no** tracking - [deadlock detection is for debug behavior, not normal behavior](https://docs.microsoft.com/en-us/dotnet/standard/threading/how-to-enable-thread-tracking-mode-in-spinlock).

Note that the "Deadlock detection" present here guards you from **ONE** specific type of deadlock - not properly releasing the lock before trying to acquire it again _from the same thread_.  It won't detect deadlocks due to the original owning thread dying (and thus never calling `Exit` - which would be the halting problem, anyways).  It's not going to notice if you have two spinlocks and interleave them poorly.  It's not going to detect you doing something silly, like calling `Exit` from the wrong thread.

There literally wasn't enough information stored to maintain a reentrancy count.  Then, too, I suspect that the cases where reentrancy would make a big showing would be heavier cases that should normally use an actual blocking call (which should be avoided with `SpinLock`).

**Comment by MkazemAkhgary** [comment]
I see. I worded my sentence badly, what I meant by detecting deadlock was just the case for reentrancy (same thread entering the same lock again). I wont use that word again :)

So in other words for SpinLock to have any kind of performamce benefits is to be as simple as possible and overhead of thread owner tracking most likely defeats the purpose of having SpinLock. Except it only makes sense to have that feature for easier debugging.

**Comment by Clockwork-Muse** [comment]
Right.

Essentially, `SpinLock` is for the situation where your operations are going to be short.  For instance, in a linked list, inserting an item requires updating two memory addresses - one on the existing list, and one on the new node.  These are fast, but the entire operation can't be made atomic with anything short of a lock (or not simply, anyways).  So, `SpinLock`, since the updates are a _very_ few instructions.
