### ISSUE TITLE
Decide if UAP should include System.Reflection.Emit

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/corefx#34937]
CoreFx will soon be moving to target `netstandard2.1`, so we need to decide whether or not UAP will include RefEmit. The other option would be to not move UAP from `netstandard2.0` to `netstandard2.1`

CC @terrajobst @ericstj @karelz

**Comment by MichalStrehovsky** [comment]
UAP has a [throwing implementation](https://github.com/dotnet/corert/tree/master/src/System.Private.CoreLib/src/System/Reflection/Emit) for the whole Ref.Emit surface area and apps can use [RuntimeFeature.IsDynamicCodeSupported/IsDynamicCodeCompiled](https://github.com/dotnet/corert/blob/aa4f9db019c6754d638a238d12af243df6fbb5d3/src/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeFeature.CoreRT.cs#L9-L10) to probe for this.

What is this issue tracking?

**Comment by ericstj** [comment]
Correct, but that's currently not exposed as a default reference in the UAP framework package.  For an application to get it you need to use the package.  In the past that was because the implementation only existed on coreclr and folks didn't want to lead developers on by having it work in debug and not release.

This issue is tracking making it a default reference in UAP.  That will have to be done for UAP to support netstandard2.1.  @wtgodbe and I looked at just making that change but it had implications for the current set of packages we're shipping in the 3.0 release: https://github.com/dotnet/corefx/issues/29365.  We were reluctant to have those packages refer to some future version of UAP where this was inbox when we don't even know what that [version will be](https://github.com/dotnet/corefx/blob/5197c8dc78adcb130a08944724f1b49c3765a4b1/Directory.Build.props#L21-L27).

Probably the right thing to do here is turn off UAPVNext from the packages, then make the changes which set up UAPVNext to support netstandard2.1.   That's what we've done for past releases where .netcore and uap release schedules didn't sync up.  I've opened https://github.com/dotnet/corefx/issues/34959 to track excluding UAPVNext from packages.

**Comment by ViktorHofer** [comment]
This is already done in master and release/3.0.
