### ISSUE TITLE
Marshal.GetObjectForNativeVariant is obsoleted with no workaround provided

### ISSUE THREAD

**Issue by jbartlau** [dotnet/corefx#34949]
When using Marshal.GetObjectForNativeVariant, this gives a warning:

>warning CS0618: 'Marshal.GetObjectForNativeVariant(IntPtr)' is obsolete: 'GetObjectForNativeVariant(IntPtr) may be unavailable in future releases.' 

We heavily rely on being able to interop with variants (which actually works just fine in Core 3 Preview 2). Would be happy to move to a different technique, however the warning doesn't contain a suggested way to do things right. Does the obsoletion make sense? What's the future proof way to marshal variants then?

**Comment by vcsjones** [comment]
@AaronRobinsonMSFT may know?

**Comment by AaronRobinsonMSFT** [comment]
Thanks @vcsjones.

@jbartlau The obsolete statement is a nuanced indication about the intent of certain APIs and scenarios involving CoreCLR. As you probably know `VARIANT` is related to the COM and OLE technologies on the Windows platform. This fact makes it somewhat hard to reconcile with CoreCLR's goal of being an environment where one can build enterprise level cross-platform applications. The API doesn't really make sense in that environment and as such is "obsolete". The ugly truth of the matter is that the statement "may be unavailable in future releases", although technically possible, is highly unlikely. As long as there are still developers writing applications for .NET Core to run on Windows or porting .NET Framework applications to .NET Core, this API isn't going anywhere.

>What's the future proof way to marshal variants then?

If your application is targeting Windows and only Windows, this API is fine to use and will be around for years to come. If there are plans for your application to run on non-Windows platforms, I would suggest avoiding any API that relates to `VARIANT` for the time being since support on non-Windows platform is still in question.

cc @jeffschwMSFT

**Comment by jkotas** [comment]
> could this be one of those APIs that got marked obsolete by accident?

I think so.

**Comment by AaronRobinsonMSFT** [comment]
@stephentoub, @jkotas, @jeffschwMSFT,

Are there any concerns about removing the `System.ObsoleteAttribute` attribute from the `VARIANT` family of functions? As pointed out the messaging is a bit misleading because I can't see anyway we would ever remove these functions, however I can see the attribute as a way to prompt users to seriously reconsider designs if possible. Thoughts?

https://github.com/dotnet/corefx/blob/bcb76015585c91a1dfa63df68ef392bed317e8dd/src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs#L561-L572

**Comment by stephentoub** [comment]
When were they marked as obsolete?  Seems like they're marked in both .NET Core and .NET Framework.  Any idea when it happened in netfx?

**Comment by jkotas** [comment]
Where do you see them marked as obsolete for .NET Framework?

It happened during .NET Native when folks tried to make interop APIs to either AOT-friendly (it is where all the generic overloads for `Marshal.SizeOf`, etc. came from) or obsolete them (when the API does not have a clear bound on the interop code it needs). These changes were done on a dogfood TFS server that was retired since then. I do not know where the soruce code history for that period lives to get you more details.

**Comment by stephentoub** [comment]
> Where do you see them marked as obsolete for .NET Framework?

In the docs:
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getobjectfornativevariant?view=netframework-4.7.2

**Comment by stephentoub** [comment]
Sounds fine to me.

**Comment by jkotas** [comment]
The docs are not showing the right obsolete attributes in many cases https://github.com/dotnet/dotnet-api-docs/issues/1184

**Comment by danmosemsft** [comment]
@ahsonkhan and @safern are working on a plan for updating the corefx API docs for 3.0. I think they were mainly focused on API that wasn't documented at all, but we should think about this case also.

**Comment by AaronRobinsonMSFT** [comment]
@safern Do you have any concerns with me putting up a PR with the attribute removed?

**Comment by safern** [comment]
From the docs perspective sounds fine to me. We should be handing the new reference assemblies every release. So as long as reflection is done correctly, it should be reflected on the docs for next release. As long for .NET Core, because for netfx, I think the source of truth are not core ref assemblies, but still don't know enough to tell.

cc: @mairaw

**Comment by mairaw** [comment]
There's a bug in docs where the attribute is not version aware at the moment.
When you look at the docs source, you can see exactly which versions have that attribute:
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Runtime.InteropServices/Marshal.xml#L4462

Tagging @dendeli-msft to comment on when this bug should be fixed. I think it's still months away because it was dependent on some other work they need to do first to enable this.

Yes, for netfx, Vivek gives me a pointer to the targeting pack for me to reflect on.

**Comment by crowo** [comment]
also dont forget removing obselete from  UnmanagedType.SafeArray

**Comment by AaronRobinsonMSFT** [comment]
@crowo Please refer to https://github.com/dotnet/corefx/pull/35161 for the extent of the changes.
