### ISSUE TITLE
Build: individual release builds don't work

### ISSUE THREAD

**Issue by Wraith2** [dotnet/corefx#34972]
Started with `clean -all` synced to master. `build -allconfigurations` ran successfully.
`build src\System.Data.SqlClient -debug` works
`build src\system.Data.SqlClient -release` fails with:

```
E:\Programming\csharp7\corefx>build src\System.Data.SqlClient -release
  Restore completed in 31.8 ms for C:\Users\Wraith\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19078.1\tools\Tools.proj.
  Package Id                             Version      Commands
  -------------------------------------------------------------------
  coverlet.console                       1.4.0        coverlet
  dotnet-reportgenerator-globaltool      4.0.5        reportgenerator
E:\Programming\csharp7\corefx\Directory.Build.props(458,3): error MSB4019: The imported project "E:\Programming\csharp7\corefx\artifacts\bin\runtime\netcoreapp-Windows_NT-Release-x64\Microsoft.Net.Test.Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [E:\Programming\csharp7\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]

Build FAILED.
```

The same occurs with System.Data.Odbc and presumably any other library using the same approach. It's a bit inconvenient when I'm working on perf.

cc @safern, @ViktorHofer, @ericstj

**Comment by safern** [comment]
build -allConfigurations was built in debug mode and you're trying to build a project in release mode. So there are no assets for Release build in bin/obj folders, so we can't build. Try running build -release beforehand.

**Comment by Wraith2** [comment]
Ok, building. So what is allconfigurations if it isn't all confirations? I thought trying to use allconfigurations and debug/release together used to fail.

**Comment by Wraith2** [comment]
Sorted. Sorry for the noise, it's hard to keep up with the build system at times.

**Comment by safern** [comment]
Not a problem! Actually -allConfigurations means - All TargetFrameworks for all projects. So for example if a project has 

```
<BuildConfiguration>
    netcoreapp;
    netfx;
    uap;
</BuildConfiguration>
```

So all configurations will build that project for netcoreapp, netfx and uap in one build. But you still need to specify the ConfigurationGroup you want those frameworks to be built on, Debug or Release.

Naming might not be the best, and it should change in the future, but it will be like this for a while. I wouldn't recommend running allConfigurations for testing just one framework. Then I would just build for that framework, since allConfigurations is slower.
