### ISSUE TITLE
System.Runtime.Intrinsics.X86.Sse2 missing overloads

### ISSUE THREAD

**Issue by Symbai** [dotnet/corefx#34988]
The System.Runtime.Intrinsics.X86.Sse2 are missing overloads for certain types such as:

```
byte:
Sse2.CompareGreaterThan(Vector128<byte>, Vector128<byte>)
Sse2.CompareLessThan(Vector128<byte>, Vector128<byte>)

int:
Sse2.CompareNotEqual(Vector128<int>, Vector128<int>)
Sse2.CompareGreaterThanOrEqual(Vector<int>, Vector128<int>)

long:
Sse2.CompareEqual(Vector128<long>, Vector128<long>)
Sse2.CompareGreaterThan(Vector128<long>, Vector128<long>)
Sse2.CompareLessThan(Vector128<long>, Vector128<long)
```

There are many more. Is there a reason why they are missing? Is there a chance they will be added? I'm asking because there is no contiguity, it rather feels just incomplete. I'm sorry if there has been an explanation to this before, I couldn't find it.

**Comment by tannergooding** [comment]
@Symbai, these intrinsics map directly to the underlying CPU instructions of a given ISA so they can only expose what the underlying hardware exposes.

For example, with `CompareGreaterThan` the corresponding instruction (`PCMPGTB/PCMPGTW/PCMPGTD`) is explicitly documented as comparing packed signed integers.

The same applies to the other missing functions listed above, either only signed vs unsigned is exposed because the underlying instruction explicitly supports one (and the sign is semantically meaningful in this case) or the CPU doesn't expose any such instruction that supports the desired operation.
