### ISSUE TITLE
Contributing experience: `dotnet test` should work in the same way as `dotnet msbuild /T:BuildAndTest`

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#35011]
Any way to make this work?

**Comment by ViktorHofer** [comment]
I'll take a look.

**Comment by ViktorHofer** [comment]
For this to work we would need to enable project restore for test projects and package reference Microsoft.Net.Test.Sdk instead of our current solution to restore everything upfront and manually reference the test sdk assemblies. This is something I really would like to see but I don't think it's feasible in the short-term.

**Comment by ericstj** [comment]
I think restore should be a noop for our tests.  It looks like `dotnet test` just [runs the VSTest target](https://github.com/dotnet/cli/blob/7b2d1b1c154505918ce2f509ba791082967f1fb9/src/dotnet/commands/dotnet-test/Program.cs#L40-L46).  Couldn't we just hook that and make it do what we need?
