### ISSUE TITLE
Incorrect socket exception on Linux

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#35127]
I get 
```
Hello World!
Failed to create socket!
System.Net.Sockets.SocketException (0xFFFFFFFF): Unknown error -1
   at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   at dd.Program.Main(String[] args) in /tmp/dd/Program.cs:line 15
```

when running following app on Linux (2.1 & 3.0)
```c#
using System;
using System.Net;
using System.Net.Sockets;

namespace dd
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Socket socket;

            try {
                socket = new Socket(AddressFamily.InterNetwork, SocketType.Raw, ProtocolType.Tcp);
           } catch (Exception e) {
                Console.WriteLine("Failed to create socket!");
                Console.WriteLine(e);
                return ;
           }
    }
}
```

when running under strace the (`strace -f -e trace=network /tmp/dd/bin/Debug/netcoreapp3.0/linux-x64/publish/dd`)
the error is clearly permission issue:
> [pid  9053] socket(PF_INET, SOCK_RAW|SOCK_CLOEXEC, IPPROTO_TCP) = -1 EPERM (Operation not permitted)

may be related to #30790 as we clearly do not propagate correct OS errors back.

**Comment by stephentoub** [comment]
I get this on 3.0:
```
Hello World!
Failed to create socket!
System.Net.Sockets.SocketException (0xFFFFFFFF): Bad value for ai_flags
   at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType) in /mnt/d/repos/corefx_wsl/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 100
   at dd.Program.Main(String[] args) in /home/stoub/repros/Program.cs:line 15
```

**Comment by stephentoub** [comment]
I suspect part of the problem is the way the SocketPal is set up, it's expecting a SocketError to come back from various calls, and there's no mapping in the table at https://github.com/dotnet/corefx/blob/ef4c7fa0671ddb1874425ebf7a695ef28964792c/src/Common/src/System/Net/Sockets/SocketErrorPal.Unix.cs#L35-L78 that maps EPERM to a SocketError.  As a result, we'll just end up using SocketError.SocketError, a generic socket error.  Looks like the fix would be to add a mapping for EPERM to SocketError.AccessDenied.
