### ISSUE TITLE
Design document for performance patterns

### ISSUE THREAD

**Issue by sharwell** [dotnet/corefx#352]
As noted in #351, some patterns which are commonly used in the .NET Framework for performance reasons are not obvious to users who are new to this project. Due to the number of projects which leverage the .NET library as part of their own applications, performance is a particularly sensitive area, especially in regards to [unnecessary] memory allocations. It would be very helpful to have a document explaining commonly used patterns intended to avoid unnecessary memory allocations, and perhaps other techniques which your prior work has indicated are high-value practices for some reason.

**Comment by stephentoub** [comment]
Thanks, @sharwell. It's a fair request, but at the same time this is just part of a general "write high-performing .NET code" category, and there's a good amount of information on such things already available, on blogs (e.g. http://blogs.msdn.com/b/pfxteam/archive/2012/02/03/10263921.aspx), on MSDN (e.g. http://msdn.microsoft.com/en-us/library/ff647790.aspx), in many C# books (e.g. http://www.amazon.com/dp/1430244585), etc.  I wouldn't object to a wiki or something, but I'm not sure how much better (if any) such a thing would be than what's already out there.

**Comment by akoeplinger** [comment]
@stephentoub Yeah, the problem is that many people don't know about those random blog posts (and having a title of "Know Thine Implicit Allocations" doesn't exactly ensure it turns up high on Google :smile:). The MSDN article is from over a decade ago, so even if I'd arrived at that page I'd immediately wonder if those guidelines are still true today.

I think having a curated list of articles/blog posts/wiki entries that the corefx team thinks are good reads would be highly appreciated!

**Comment by stephentoub** [comment]
:smirk:

**Comment by stephentoub** [comment]
I've started a wiki page at https://github.com/dotnet/corefx/wiki/Performance.  We can populate this over time as appropriate content is found.

**Comment by stephentoub** [comment]
Thanks for the suggestion.

**Comment by weshaggard** [comment]
Thanks @stephentoub
