### ISSUE TITLE
ManagedWebSocket: Inconsistent check in EnsureBufferContainsAsync?

### ISSUE THREAD

**Issue by fillmore** [dotnet/corefx#35268]
In [ManagedWebSocket.cs](https://github.com/dotnet/corefx/blob/release/3.0/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs), [Line 1194](https://github.com/dotnet/corefx/blob/release/3.0/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L1194) has assertion that _numRead_ should be non-negative. But in following [Line 1195](https://github.com/dotnet/corefx/blob/release/3.0/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L1195), it would throw expcetion when _numRead_ is ZERO. 
```
	Debug.Assert(**numRead >= 0**, $"Expected non-negative bytes read, got {numRead}");
	if (**numRead <= 0**)
	{
		ThrowIfEOFUnexpected(throwOnPrematureClosure);
		break;
	}
```

**Comment by stephentoub** [comment]
It's saying that a valid stream should never return a negative value from ReadAsync, and it's asserting if that condition occurs to alert us to a bug somewhere in the implementation.  But since such an assert is compiled away in release and we want to do something reasonable in the face of such a buggy stream provided, we throw in release builds.

**Comment by davidsh** [comment]
I think there is an inconsistency here though.

We validate with an Assert if the value is 0 or greater.  So, negative numbers would cause an assert.  But 0 is ok.

And yet the next line will throw an exception for negative numbers and if 0.  That seems inconsistent.  If the Assert is valid, then the 'if' check below should just check for "less than zero" and *not* "less than or equal to 0".

**Comment by stephentoub** [comment]
The assert is validating a properly functioning stream, i.e. no negative values.  The exception is validating that we got the data we were supposed to get, only positive values.  If the stream returns 0, that could be a properly functioning stream, but we got invalid data from whomever was sending it, because we hit EOF earlier than expected.

**Comment by davidsh** [comment]
Thanks for clarifying.  Sounds like the current code is correct and by-design.
