### ISSUE TITLE
Investigate System.Text.Encodings.Web.Tests encoding failure using XUnit Theory

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#3537]
We currently have this TODO in our UnicodeHelpersTests:
```C#
// This loop should instead be implemented as a [Theory] with multiple [InlineData]s.
// However, until globalization support is implemented on Unix, this causes failures when
// the xunit runner is configured with -xml to trace out results.  When it does so with 
// [InlineData], the parameters get written out to the results xml file, and with our
// current temporary globalization implementation on Unix, this causes exceptions like
// "The surrogate pair (0xD800, 0x22) is invalid. A high surrogate character 
// (0xD800 - 0xDBFF) must always be paired with a low surrogate character (0xDC00 - 0xDFFF)."
```

However, after implementing the Encoding table on Unix, and converting this test back to a Theory, we still get a similar error running the test:

`error: Invalid high surrogate character (0xDFFF). A high surrogate character must have a value from range (0xD800 - 0xDBFF).`

We should investigate why this error is happening and fix it.

**Comment by stephentoub** [comment]
I debugged this to libcoreclr's UTF8ToUnicode implementation:
https://github.com/dotnet/coreclr/issues/2037

The attribute string is persisted in metadata as a UTF8 blob.  When that string (which contains invalid code points) is decoded on Linux, UTF8ToUnicode isn't using appropriate fallback replacements, and the string is coming into the test as written.  That's then causing the XmlWriter employed by xunit to throw an exception when it detects the malformed text.

In contrast, on Windows the call to MultiByteToWideChar used when loading the attribute data is dutifully noticing the invalid text and substituting the replacement character; by the time the text gets to managed code, it's already been changed.  That means that it's not failing in the XmlWriter because the text has already been sanitized.  However, it also means that the test is bogus when written using a [Theory], as the input isn't what was actually expected to be passed into the test.

On the corefx side, the fix is simply to not use a [Theory], as doing so won't be valid in any case; I'll submit a PR to remove the TODO.  On the coreclr side, the MultiByteToWideChar implementation should be fixed appropriately, and https://github.com/dotnet/coreclr/issues/2037 tracks that.
