### ISSUE TITLE
Please add this overload to BinarySearch

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/corefx#35435]
This overload would be helpful to binary search based on property

```c#
BinarySearch<K>(Func<T, K> itemSelector, K item, ...)
```
both for List and Array. 

currently I have to create dummy object to do the search. but this simple overload solves that problem.

**Comment by MarcoRossignoli** [comment]
Hi @MkazemAkhgary you could write a complete proposal following proposal guide https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md

**Comment by safern** [comment]
@MkazemAkhgary in order to proceed with a new API we need a formal proposal as @MarcoRossignoli stated above. Since there has been no response for that in the past 3 months I will close. Please feel free to reopen if you're still interested in this API and if you get a change to write a formal proposal. Thanks 😄
