### ISSUE TITLE
Exception Type Naming Inconsistencies

### ISSUE THREAD

**Issue by surfsquid** [dotnet/corefx#35447]
why do we have:
NullReferenceException and ArgumentNullException
and not:
ReferenceNullException and ArgumentNullException
or even:
NullReferenceException and NullArgumentException?

**Comment by jeroen-mostert** [comment]
`NullReferenceException` predates `ArgumentNullException` if the docs are to be believed (.NET 1.0 vs. .NET 1.1), so the question is really "why is it `ArgumentNullException` and not `NullArgumentException`" -- and the answer to *that* is likely "because it seemed sensible to name a class derived from `ArgumentException` as `Argument[Is]NullException`" and because nobody felt a need to mirror `NullReferenceException`".

As to why it's `NullReferenceException` and not `ReferenceNullException` (keeping in mind that `ArgumentNullException` wasn't a thing yet): Java has `NullPointerException`, and it's no secret that .NET was, shall we say, heavily inspired. The concept of a "null pointer" predates both Java and .NET (the same is not true for a "null argument", which isn't really a separate thing). It would have made less sense to name the class `Reference[Is]NullException`.

With all that said, I hope you're not seriously proposing we rename either class -- from a compatibility standpoint, that's a non-starter. 😄

**Comment by ViktorHofer** [comment]
As in the early days of .NET Framework someone decided to name it as it is. We can't go back and change such fundamental types as that would be a breaking change.

![image](https://user-images.githubusercontent.com/7412651/53104835-60306f00-3530-11e9-8a16-df8bc6bd8582.png)

**Comment by surfsquid** [comment]
Yeah I wasn't really holding too much hope for a rename 😅

Thanks for the explanation of how we got here though, it's all very interesting!
