### ISSUE TITLE
.Net Core 2.1 : Google Recaptcha fails on server because of Socket Exception when HttpClient makes call on POST

### ISSUE THREAD

**Issue by 007LP** [dotnet/corefx#35451]
Below is the server side implementation
```c#
var httpClient = _httpClientFactory.CreateClient();
var res = await httpClient.GetAsync($"https://www.google.com/recaptcha/api/siteverify?secret={secret}&response={gRecaptchaResponse}");
```

Tried to use WebProxy as the server uses a proxy, but returns 407 proxy authentication error.

Any suggestions on workarounds/solutions ?

**Comment by davidsh** [comment]
You need to pass proxy credentials via the HttpClientHandler.Proxy or HttpClientHandler.DefaultProxyCredentials property.  You can create the HttpClientHandler and pass it to the constructor of HttpClient.

However, since you are using the HttpClientFactory API (and not creating the HttpClient yourself) you will need to talk with them about how to do proxy credentials.

**Comment by davidsh** [comment]
@Tratcher Can you please help route to HttpClientFactory?

**Comment by Tratcher** [comment]
HttpClientFactory shouldn't meaningfully affect this behavior. Can you reproduce it with `new HttpClient()`?

**Comment by Tratcher** [comment]
@rynowak I don't see HttpClientFactory docs for configuring the HttpClientHandler.

**Comment by rynowak** [comment]
Here's the docs for this: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2#configure-the-httpmessagehandler

**Comment by karelz** [comment]
Seems to be answered above.
