### ISSUE TITLE
Feature request: Add Environment.LongTickCount

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#35499]
Environment.TickCount rolls over, which makes it inconvenient to use. See e.g. https://github.com/dotnet/corefx/pull/35401

To remedy this, we should add Environment.LongTickCount. This is trivial to implement on Windows using GetTickCount64. 

```C#
public static class Environment
{
    public static long LongTickCount { get; } // or TickCount64
}
```

**Comment by stephentoub** [comment]
Related https://github.com/dotnet/corefx/issues/3249

**Comment by danmosemsft** [comment]
There is precedent for adding `64` on properties on Process eg
```c#
        public int PeakWorkingSet { get { throw null; } }
        public long PeakWorkingSet64 { get { throw null; } }
```
So I would vote for 
Not sure whether there's precedent for prefixing `Long`.

**Comment by stephentoub** [comment]
> Conversely the only example of the Long prefix is

There's also Enumerable.LongCount.

But I'd be fine with either the Long prefix or the 64 suffix.

**Comment by danmosemsft** [comment]
> There's also Enumerable.LongCount.

Right I only looked at properties

**Comment by tannergooding** [comment]
I think `64` or `Int64` makes much more sense.

The framework guidelines also recommend not using language specific names (like `Long`), given that they can mean different things in different languages: https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/general-naming-conventions#avoiding-language-specific-names

**Comment by jeroen-mostert** [comment]
Re: language-specific names, my favorite bug/gotcha in this regard is `IDataReader.GetFloat()` (which should have been `IDataReader.GetSingle()`). This has bitten numerous folks who thought to use `.GetFloat()` to read a T-SQL `FLOAT`, which is actually a double-precision type and has to be read with `.GetDouble()`. This is practically an unavoidable mistake if your language doesn't have a `float` type in the first place (e.g. VB.NET).

The only reason "long" is halfway acceptable in this regard is because it can be interpreted as a modifier rather than a type name (e.g. `LongLength` is `Length`, but "longer") and so is unlikely to be as harmful as the above.

**Comment by terrajobst** [comment]
The most logical API proposal would be, which looks fine to me.

```C#
public static class Environment
{
    public static long TickCount64 { get; }
}
```

I'll bring it up in the next API review.

**Comment by terrajobst** [comment]
And we landed on:

```C#
public static class Environment
{
    public static long TickCount64 { get; }
}
```

**Comment by danmosemsft** [comment]
Should we mark up for grabs or is someone planning to take this?
