### ISSUE TITLE
Queue<T>: why set GrowFactor to 200 and divide by 100?

### ISSUE THREAD

**Issue by chukunx** [dotnet/corefx#35515]
hi guys, this isn't an issue, but just me being curious about a configuration setup in `Queue<T>` class. may i ask why do we want to double the size of array by initiating the GrowFactor as 200 and multiplying the original size by `GrowFactor / 100` here? what's the downside of using `2` directly? thanks.
https://github.com/dotnet/corefx/blob/bca44089343cf14cffd3cb0982b7e209692f6731/src/System.Collections/src/System/Collections/Generic/Queue.cs#L188

**Comment by Wraith2** [comment]
Guessing here, if you use 100 as the base you avoid using a float to store fractional growth factors and end up with an integer division which is easier/faster than float division. If that's the case then it feels like a development setup so someone can test various growth factors and perhaps not something that is needed in release builds since GrowthFactor is constant.

**Comment by chukunx** [comment]
ah i see, it make sense. i evaluated the statement in a wrong order as `_array.Length * (GrowFactor / 100)`, with which the fractional growth wouldn't work. but yes as you mentioned, the GrowthFactor can be directly set to a desired constant value here.
