### ISSUE TITLE
Should GenAPI be removing the XML Serialization attributes?

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#35561]
Currently the automatic generation of reference assemblies excludes some of the XML Serialization attributes

https://github.com/dotnet/corefx/blob/26b932e3c56702382d13ece010b300d3181d2891/eng/DefaultGenApiDocIds.txt#L44-L47

This feels like (but is currently unverified) it would create a problem for `sgen.exe`; in that the `sgen`-generated serializer/deserializer would behave differently than the runtime-generated serialization assembly; so it seems like they should be left as part of the ref.cs

Alternatively, it seems like all of the attributes in https://docs.microsoft.com/en-us/dotnet/standard/serialization/attributes-that-control-xml-serialization?view=netframework-4.7.2 would be removed.

No matter what, the inconsistency seems weird.

cc: @ericstj

**Comment by ericstj** [comment]
Agreed.  I don't think we should be omitting those.  @huanwu @mconnew can one of you comment on this?

**Comment by mconnew** [comment]
For the .NET Framework sgen.exe tool, it don't think it matters either way as it can't work with an assembly targeting netstandard. The problem is a data assembly will be compiled against the reference assembly netstandard.dll but sgen has no capability to find reference assemblies so it ends up using runtime assemblies. The runtime assembly netstandard.dll for the .NET Framework is just a façade and the C# compiler can't use façade assemblies. Basically pre-generated serializer creation on .NET Framework are incompatible with a data assembly targeting netstandard. We have the same problem with runtime serializer creation with XmlSerializer when soap encoding is required from XmlSerializer as we only have a code gen code path which invokes csc and fails for the same reason.  
But our .NET Core pre-generated serializer code will need those attributes to be in the reference assembly as we do use the reference assemblies there.

**Comment by joperezr** [comment]
@mconnew Next steps would be to remove those attributes from the list and the rebuild corefx, which might throw some errors in ApiCompat due to the removal of this attributes. Do you mind taking a look at this given that you are the area expert?

**Comment by Lxiamail** [comment]
@joperezr we have review the suggestion of removing the 4 attributes from [corefx/eng/DefaultGenApiDocIds.txt ](https://github.com/dotnet/corefx/blob/26b932e3c56702382d13ece010b300d3181d2891/eng/DefaultGenApiDocIds.txt#L44-L47)to make them available in reference assembly. It looks right, please go for it. Please also remove 
T:System.Runtime.Serialization.KnownTypeAttribute from the list as well.

**Comment by joperezr** [comment]
I can help fixing this issue, but I believe that in the future changes like these should be handled by domain experts because of potential impact on reference assemblies, which in this case is the serialization team.
