### ISSUE TITLE
how to make System.Net.HttpListener to support for long url ?

### ISSUE THREAD

**Issue by maxzhou0** [dotnet/corefx#35622]
I use System.Net.HttpListener to make a simple http server.(NOT through IIS)
when my url content become longer , i recieved the web page like these

> Request URL Too Long
> HTTP Error 414. The request URL is too long.

is there some options i can configure to make max allowed content length larger?

**Comment by vcsjones** [comment]
If I am not mistaken, `HttpListener` uses Win32's http.sys on Windows, which is where this limitation is likely coming from. Therefore, I think the correct way to "fix" this for `HttpListener` then is to make appropriate [registry changes][1] and setting `UrlSegmentMaxLength`.

It is my understanding that using Kestrel will give you a lot more flexibility here and can be configured via `MaxRequestLineSize`.

/cc @davidsh

[1]: https://support.microsoft.com/en-us/help/820129/http-sys-registry-settings-for-windows

**Comment by davidsh** [comment]
>It is my understanding that using Kestrel will give you a lot more flexibility here and can be configured via `MaxRequestLineSize` without having to make registry changes.

@Tratcher Can you comment about Kestrel's behavior here?

**Comment by Tratcher** [comment]
Because kestrel is hosted in process you get a lot more programmatic control over its processing.
https://github.com/aspnet/AspNetCore/blob/0d570a2d429ada2f2b37fdf5bafead3bf92c16eb/src/Servers/Kestrel/Core/src/KestrelServerLimits.cs#L86-L94

Part of the reason HttpListener/HttpSys is less flexible here is that it can share ports across applications. I needs to be able to parse the request before routing it to the correct app so it can't have app specific parsing controls. It could have endpoint specific settings configured via netsh.

**Comment by davidsh** [comment]
@maxzhou0 

>is there some options i can configure to make max allowed content length larger?

The summary of the discussion is that there are no HttpListener APIs that control URL length.  And none can be implemented.   URL length is controlled via registry key.

If you need to control URL length, then using ASP.NET Core middleware (like Kestrel) is the best option.
