### ISSUE TITLE
System.Net.Http (Linux) doesn't support ChannelBinding

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#3565]
Test (HttpClientHandlerTest.cs)
PostAsync_Post_ChannelBindingHasExpectedValue() fails because it returns a NULL value for ChannelBinding.

**Comment by davidsh** [comment]
cc: @CIPop @stephentoub @vijaykota @SidharthNabar

**Comment by davidsh** [comment]
Discovered during PR #3554

**Comment by vijaykota** [comment]
@kapilash, can you take a look? I didn't quite get how the binding is exposed to the user of HttpClientHandler.

**Comment by davidsh** [comment]
@vijaykota The binding is exposed via the protected SerializeToStreamAsync() method of HttpContent.  Developers can subclass the HttpContent class, override this method and get access to the TransportContext object.  This is what WCF does today to get access to the "blob" containing the ChannelBinding token (available on SSL/TLS connections).

**Comment by vijaykota** [comment]
Thanks @davidsh We missed this out when looking at xplat work for HttpClientHandler

**Comment by vijaykota** [comment]
No immediate consumers for this so changing the milestone to RTM

**Comment by kapilash** [comment]
The test works now when the underlying libcurl uses libssl compatible ssl backend.

**Comment by vijaykota** [comment]
Pending work here is to re-enable the test for Linux

**Comment by vijaykota** [comment]
@kapilash, I am assuming that supporting this for libcurl with gnutls is not possible.

**Comment by kapilash** [comment]
>  I am assuming that supporting this for libcurl with gnutls is not possible.

@vijaykota yes, the the ssl callbacks that we are relying on are available only for libssl compatible backends. 

But it is possible if we can pinvoke into gnutls.   I  had to do the following steps, in order to  get it working with gnutls

Identify that the backend is gnutls
-----------------------------------------------
Once easy pointer has been created, ```curl_easy_getinfo```  with ```CURLINFO_TLS_SESSION``` gives us info about the ssl backend. This function does not return valid values for all ssl backends but it does work for gnutls.

register callback
-------------------------------
gnutls allows us to register call back for certificate validation via ```gnutls_certificate_set_verify_function```.  (Before we can call this function,  we need to create the ```gnutls_certificate_credentials_t``` function via ```gnutls_certificate_allocate_credentials``` and link it to the session object via ```gnutls_credentials_set``` ).

callback 
------------
In the callback, we need to use ```gnutls_certificate_type_get ``` to get the certificate object which can be used for creating the token.
 

shims
-----------
All the shims for above are to be conditionally compiled. (That is, compilation should not fail if the above functions aren't available at the compilation/link time of System.Net.Http.Native library).

**Comment by stephentoub** [comment]
Works as expected with a libssl-compatible backend.
