### ISSUE TITLE
System.Runtime.Loader.Tests.AssemblyLoadContextTest.InitializeDefaultContextTest failing on Linux in CI

### ISSUE THREAD

**Issue by pgavlin** [dotnet/corefx#3569]
For example:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/2896/

**Comment by pgavlin** [comment]
@stephentoub: who should take a look at this one?

**Comment by stephentoub** [comment]
@kouvel, I think you recently made some changes here.  Could you please take a look?  This is causing a bunch of corefx runs to fail, e.g. http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst/1052/testReport/junit/System.Runtime.Loader.Tests/AssemblyLoadContextTest/InitializeDefaultContextTest/

**Comment by kouvel** [comment]
It looks like this was caused by my change e780495d6e7575812fd5c42d4125c35b6054fa95. I had a clean test run on the PR though, so maybe in combination with another change. I'll investigate.

**Comment by kouvel** [comment]
It certainly was my change. The issue is that removing the PKT check in the binder when binding to assemblies on the TPA list means when the app executable is unsigned and alongside corerun, it's treated as a platform assembly and the assembly load context doesn't get locked.

This seems to be by design as far as the binder is concerned. If the app executable were signed or in a different directory, the behavior would differ. @jkotas suggested a way to make the behavior more consistent would be to add assemblies in the app executable's directory to the TPA list.

I'm going to try that, meanwhile I'll disable the test to unblock the CI.

**Comment by stephentoub** [comment]
Thanks, @kouvel. I already disabled the test this morning.

**Comment by kouvel** [comment]
Oh that's great, thanks!

**Comment by kouvel** [comment]
Fixed
