### ISSUE TITLE
Linq sort .AsParallel is not stable when .AsP

### ISSUE THREAD

**Issue by DragonSpit** [dotnet/corefx#35710]
Under the following usage Linq sorting is stable and parallel:

uint[] ArrayOne = { 21, 43, 16, 5, 54, 3 };
uint[] sortedArrayOne;

sortedArrayOne = ArrayOne.AsParallel().OrderBy(i => i).ToArray();

However, placing .AsParallel() as follows is still parallel, but becomes unstable:

sortedArrayOne = ArrayOne.OrderBy(i => i).AsParallel().ToArray();

Both versions should be parallel and stable.

**Comment by stephentoub** [comment]
PLINQ's OrderBy is explicitly documented to not be stable:
https://docs.microsoft.com/en-us/dotnet/api/system.linq.parallelenumerable.orderby?view=netframework-4.7.2
"In contrast to the sequential implementation, this is not a stable sort."

**Comment by DragonSpit** [comment]
Thank you Stephen!

**Comment by Clockwork-Muse** [comment]
...Although what we're looking at here isn't the stability of `OrderBy()`, but the stability of `ToArray()` - PLINQ only provides parallel operations to the right of the `AsParallel()` call, not the left.  
PLINQ doesn't actually know that the enumerable you've handed it in the second case is ordered - it doesn't check for the type returned by the sequential `OrderBy()`, and thinks it's a regular `IEnumerable<T>`.  
You could tell PLINQ to treat the enumerable as origin-ordered, via `AsOrdered()` (which should make the enumeration into the array stable), but unless you're doing _something else_ with the parallel part, you'd be better off removing the parallel part altogether.

**Comment by DragonSpit** [comment]
Is there a way to keep the whole process still stable overall? Otherwise, this still seems like a bug and making .ToArray() stable should be much simpler than making parallel sorting stable, since it already seems to be stable.
My stability tests show that the first usage seems to be stable, whereas the second usage fails stability tests. This is not necessarily a fully conclusive result, and Stephen Toub's find of the documentation shows that PLINQ.AsParallel.OrderBy() states that the parallel version is not stable. Maybe that's the reason it is not stable - the .ToArray() is not stable. But, it sure seems like that one would be simpler to make stable.

**Comment by Clockwork-Muse** [comment]
...`ToArray()` isn't stable here because PLINQ doesn't know it "needs" to be kept stable.  It knows you gave it an `IEnumerable<T>`.... and that's it.  It doesn't know you cared about the order of the elements.  If you want the same ordering in your output, you have to explicitly tell PLINQ that. 

It's like you told a couple of kids to put away a set of markers you previously neatly sorted by name - they both grab a handful, but the kid who picked some up first is slower, and gets to the box second.  If you want the markers to go into the box in that order, you either have to tell the kids that you want the markers to go in the box in the same order they were in on the table, or you have to tell the kids to sort the markers themselves (in which case they grab _all_ the markers on the table at once, and never notice you previously sorted them).  

I mentioned earlier, you could retain the source ordering with `AsOrdered()`:
```csharp
// Keeps original pre-parallel ordering, but this has a performance cost
var n = ArrayOne.AsParallel().OrderBy(i => i).AsParallel().AsOrdered().ToArray();
```
...but if that's actually what your code looks like, you're better off removing the entire parallel portion, because the majority of the work is still being done sequentially.  (Additionally, the switch to PLINQ is going to remove fun optimizations, like being able to pre-allocate the array at the proper size)

<hr />

 Note that chaining anything else after an `OrderBy()` call would (mostly) remove the ability to tell that the source was ordered anyways:
```csharp
// "Wot?  This is ordered?  I can't tell!"
var n = ArrayOne.AsParallel().OrderBy(i => i).Select(x => x.Property).AsParallel().ToArray();
```

Note too that ["stable sorting"](https://stackoverflow.com/questions/1517793/what-is-stability-in-sorting-algorithms-and-why-is-it-important)  (which is what Stephen refers to) is something quite different than "stable access ordering" (which is what's happening here).

 1. Vanilla LINQ has the latter because it deals with things sequentially, so is able to guarantee the former without too much work.
 1. PLINQ doesn't really have the latter (because of multiple threads), so it can't guarantee the former.
