### ISSUE TITLE
TypeConverter.CanConvertFrom method has been changed

### ISSUE THREAD

**Issue by pavelovcharov** [dotnet/corefx#35753]
While porting our app to NetCore3, we've noticed that the TypeConverter's CanConvertFrom and ConvertFrom methods work diffrently in Net Core 3 and Net Framework 4.7.2

https://referencesource.microsoft.com/#System/compmod/system/componentmodel/TypeConverter.cs
```
        public virtual bool CanConvertFrom(ITypeDescriptorContext context, Type sourceType) {
            if (sourceType == typeof(InstanceDescriptor)) {
                return true;
            }
            return false;
        }
public virtual object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value) {
            InstanceDescriptor id = value as InstanceDescriptor;
            if (id != null) {
                return id.Invoke();
            }
            throw GetConvertFromException(value);
        }
```

https://github.com/dotnet/corefx/blob/release/3.0/src/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeConverter.cs
```
       public virtual bool CanConvertFrom(ITypeDescriptorContext context, Type sourceType) => false;
       public virtual object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)
        {
            throw GetConvertFromException(value);
        }
```

Is this an intentional change?

**Comment by am11** [comment]
Seems like `CanConvertFrom` is returning `false` since it was ported to .NET Core v1.0.0-rc1 in Feb 2015: https://github.com/dotnet/corefx/pull/739/files#diff-12e5d00657bd456dff4cfb2149a3e3beR29

`InstanceDescriptor` was not part of the initial port, it was added later (2016) in https://github.com/dotnet/corefx/pull/12081. Recently, the derived `TypeConverter` types were adapted to support `InstanceDescriptor` matching desktop implementation in https://github.com/dotnet/corefx/pull/32621, but the base class is missing the support. Maybe it was an oversight?
