### ISSUE TITLE
System.Security.Cryptography KeyedHashAlgorithm add support for ReadOnlySpan<byte> as Key

### ISSUE THREAD

**Issue by juho-hanhimaki** [dotnet/corefx#35815]
At the moment the `Key` must be `byte[]`.

In our scenario we have a key that is stored as `ImmutableArray<byte>`. In future `ImmutableArray<byte>` might be compatible with `ReadOnlySpan<byte>`.  https://github.com/dotnet/corefx/issues/34126

It would be neat if the `ReadOnlySpan<byte>` could then be used as a key for the hash algorithms.

**Comment by jkotas** [comment]
If you need to interop with existing APIs that take `byte[]` and do not modify it, you can get `byte[]` from `ImmutableArray<byte>` by doing:

```
ImmutableArray<byte> ia;
byte[] a = Unsafe.As<ImmutableArray<byte>, byte[]>(ref ia);
```

**Comment by vcsjones** [comment]
I think this would have to be an entirely new API. The issue with `KeyedHashAlgorithm` and `HashAlgorithm` end up being that the key is stored as a field on the instance which you cannot do with a `ROS<T>`.

This feels similar to #31722.

**Comment by GrabYourPitchforks** [comment]
It's not possible to change the type of the `KeyedHashAlgorithm.Key` property. As @vcsjones said, it would likely need to be an entirely new API with a different type hierarchy than `KeyedHashAlgorithm`. Too much of the type as it exists today is dependent on everything being in the form of a `byte[]`.

The scenario can be accomplished safely with a single line of code. It makes a copy of the inner array, but it should still be perfectly fine for the majority of use cases.

```cs
myKeyedHashAlgorithm.Key = myImmutableArray.AsSpan().ToArray();
```

I'm closing this for now since it seems that the scenario is adequately achievable. If you feel that this issue has been closed in error, please reopen.
