### ISSUE TITLE
CI builds are failing due to a bad package for Xunit.netcore.extensions

### ISSUE THREAD

**Issue by pgavlin** [dotnet/corefx#3596]
The version of xunit,netcore.extensions.dll shipped in the latest xunit.netcore.extensions package references 'xunit.core, Version=2.1.0.3168', but the latest version of xunit.core that is available seems to be 'xunit.core, Version=2.1.0.3029'.

**Comment by pgavlin** [comment]
e.g. http://dotnet-ci.cloudapp.net/job/dotnet_corefx_mac_release_prtest/3867/consoleFull#-287117688a82fefab-f698-416f-8fca-58544c94cd4e, http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/4717/

**Comment by pgavlin** [comment]
@stephentoub @joshfree: any idea who should take a look at this?

**Comment by stephentoub** [comment]
It appears to have something to do, at least in part, with @vancem's recent change. I reverted it here https://github.com/dotnet/corefx/pull/3593 and it's green.

**Comment by pgavlin** [comment]
FWIW, I hit this a few times in local builds when working on Sockets. Locking my version of xunit.netcore.extensions to 1.0.0-prerelease-00085 seemed to fix things. Seems like the newer package versions are busted, though.

**Comment by bartonjs** [comment]
I ran into similar failures when doing #3513, which is why I rolled back all the project.lock.json parts having to do with xunit.

@stephentoub if you just edit  src/System.Diagnostics.DiagnosticSource/tests/project.json
to use 00085 for the xunit package (instead of *), build, then edit project.json and project.lock.json to turn it back into *, and rebuild, everything'll probably be ok.

**Comment by stephentoub** [comment]
Thanks, @bartonjs.  I'd tried something similar at https://github.com/dotnet/corefx/pull/3597, but it didn't work... I likely just got it wrong.  @ellismg said he's trying out a fix he and @ericstj discussed.

**Comment by ellismg** [comment]
Fixed in master now.
