### ISSUE TITLE
Strange choise of TaskScheduler

### ISSUE THREAD

**Issue by IvaYan** [dotnet/corefx#35981]
Hello!
I was looking through the sources and have noticed that inside the FileStream's native Windows implementation we have the following [code](https://github.com/dotnet/corefx/blob/f649e1bbb5149519d391805fd532df7216778f5a/src/Common/src/CoreLib/System/IO/FileStream.Windows.cs#L1592):

```csharp
return Task.Factory.StartNew(
                    state => ((FileStream)state).FlushOSBuffer(),
                    this,
                    cancellationToken,
                    TaskCreationOptions.DenyChildAttach,
                    TaskScheduler.Default);
```

The same is for [Unix](https://github.com/dotnet/corefx/blob/ff2d86994bbe8c42ea2f9e35a9452f7a66ed5af7/src/Common/src/CoreLib/System/IO/FileStream.Unix.cs#L371).

This looks strange to me, because if the caller uses their own scheduler, then this call will jump from it to the Default one. Is it ok? Or should we've been using TaskScheduler.Current instead?

**Comment by MarcoRossignoli** [comment]
I think because `TaskScheduler.Current` return `Returns the TaskScheduler associated with the currently executing task.` that could be different from `TaskScheduler.Default` https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskscheduler?view=netcore-3.0#remarks that run Tasks(and underneath threads) on .NET Core Thread Pool implementation(with a lot of features work stealing etc...).
`TaskScheduler.Current` could be a special scheduler with special synchronization context features(i.e. WindowsForm/WPF where UI handling are queued to only one thread, the famous message pump) i.e. https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskscheduler?view=netcore-3.0#specifying-a-synchronization-context

BTW @stephentoub will enlight us.

**Comment by IvaYan** [comment]
Yes, the current scheduler may differ from the default one. And this is the essence of the question: why do we use the default one if we might have been started using a custom one?

> TaskScheduler.Current could be a special scheduler with special synchronization context features

Yes, but maybe the current task have been started with such a specific scheduler for purpose? In my opinion, we'd better continue using the current scheduler instead of changing to another one silently.

**Comment by stephentoub** [comment]
This isn't user code; this is library code that's opaque to the user.  It's an implementation detail of the implementation that work is being scheduled, and thus it can choose to schedule it wherever it likes.  In fact, it could be very problematic to schedule it to the user's scheduler, in particular if the consuming code wasn't expecting it. Imagine if the calling code blocked waiting for the operation to complete, and that the current scheduler was for a context with limited scheduling resources, say a context that represented the UI thread: if the caller was on the UI thread and blocked waiting for this task to complete, and this task was scheduled to run back on the UI thread, it would likely deadlock.  This is similar to why library code should 99.9% of the time use .ConfigureAwait(false) when awaiting tasks.
