### ISSUE TITLE
ConcurrentQueueSegment<T> prevents GC of items.

### ISSUE THREAD

**Issue by fen** [dotnet/corefx#36010]
```C#
        static void Main(string[] args)
        {
            var queue = new ConcurrentQueue<object>();
            queue.Enqueue(new object());
            queue.Enqueue(new object());

            queue.TryPeek(out _);
            
            queue.TryDequeue(out _);
            queue.TryDequeue(out _);
        }
```

When I use `TryPeek` `ConcurrentQueueSegment<T>._preservedForObservation` is set to true, this will prevent the `TryDequeue` method from doing a `slots[slotsIndex].Item = default(T);`, keeping my items alive.

Is this expected behaviour when using `TryPeek`?

**Comment by stephentoub** [comment]
> Is this expected behaviour when using TryPeek?

Yes.  It's a tradeoff for making enqueue/dequeue as efficient as possible.  Because peeking isn't actually removing the item, we need to handle the race condition where another thread tries to dequeue (and zero out) the same item concurrently with us reading it.  If we then tried to reset this flag after, that would require additional synchronization because we'd need to account for the fact that other threads could be concurrently peeking.

Once the segment is marked in that fashion, no further enqueues will go to the segment, and once everything has been dequeued from the segment, the segment itself will be dropped.

**Comment by fen** [comment]
Thank you for clarifying, so after the 32 slots been filled and dequeued the entire segment is collected?

**Comment by stephentoub** [comment]
> Thank you for clarifying, so after the 32 slots been filled and dequeued the entire segment is collected?

Sorry, I mispoke.  We actually have two flags, and I was conflating them.  There's _preserveForObservation and _freezeForEnqueues.  _freezeForEnqueues is mostly what I was describing, and is set when you try to enumerate the queue; at that point, we route all future enqueues to a new segment, allow this segment to drain, and then drop this segment such that the whole thing can be collected.  _preserveForObservation is only set when peeking, and only affects whether we zero out the slot, due to the race condition I mentioned.  Once set for the segment, it'll remain set, and it'll just cause us to not zero out the slots.  But the slots will get overwritten by subsequent enqueues into that segment once it wraps around, so if the segment is 32 slots, after 32 enqueues the slot will get overwritten.
