### ISSUE TITLE
JsonSerializer does not support parsing DateTime values

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#36023]
**Runtime version:** 3.0.0-preview4-27513-05

Consider:

```C#
var content = $"\"{DateTime.UtcNow.ToString()}\"";
var result = JsonSerializer.Parse(content, typeof(DateTime));
```

This results in the following exception:

```
Unhandled Exception: System.Text.Json.JsonReaderException: The JSON value from [System.DateTime] could not be converted to System.DateTime.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException_DeserializeUnableToConvertValue(Type propertyType, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.Serialization.JsonPropertyInfo`2.Read(JsonTokenType tokenType, JsonSerializerOptions options, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.JsonSerializer.HandleValue(JsonTokenType tokenType, JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.Serialization.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.Serialization.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializer.Parse(String json, Type returnType, JsonSerializerOptions options)
```

**Comment by ahsonkhan** [comment]
This is because the Serializer is using `Utf8Parser` (with 'O' format specifier) which requires ISO 8061 compliant input (with precisely 7 fractional seconds). The more flexible GetDateTime API on the Utf8JsonReader should help partially:
https://github.com/dotnet/corefx/blob/20657b549ab4de422c3f7a9c50e22bf4d7f789a5/src/System.Text.Json/src/System/Text/Json/Serialization/Converters/JsonValueConverterDateTime.cs#L21-L22

```C#
var content = $"\"{DateTime.UtcNow.ToString()}\""; // "3/13/2019 8:36:08 PM"
Assert.True(Utf8Parser.TryParse(Encoding.UTF8.GetBytes(content), out DateTime value, out int _, 'O'), content);
```

After this change, the following format should work: https://github.com/dotnet/corefx/pull/35903
```C#
var content = $"\"{DateTime.UtcNow.ToString("O")}\""; // "2019-03-13T20:40:04.0922893Z"
```

However, the default converter will still not accept/parse arbitrarily formatted date time string. The DateTime within the payload needs to be ISO 8061 compliant. Otherwise, a custom `JsonValueConverter` needs to be provided (by the caller), once such an extensibility design is implemented (still WIP).

cc @layomia

**Comment by Clockwork-Muse** [comment]
@ahsonkan
> which requires ISO 8061 compliant input (with precisely 7 fractional seconds)

...which is going to cause interop problems with anything written in Java (and possibly other languages/frameworks), since the default formatters there are going to be giving you 9 fractional seconds digits.

**Comment by ahsonkhan** [comment]
> ...which is going to cause interop problems with anything written in Java (and possibly other languages/frameworks), since the default formatters there are going to be giving you 9 fractional seconds digits.

The change in #35903 supports 7+ fractional seconds, so that concern should be resolved. Thanks for bringing it up :)

I was merely pointing out what the current behavior is and what the `Utf8Parser` 'O' format requires, specifically.

**Comment by ahsonkhan** [comment]
@rynowak, @JamesNK - the default converter will not accept/parse arbitrarily formatted date time string. The DateTime within the payload needs to be ISO 8061 compliant. Otherwise, a custom `JsonValueConverter` needs to be provided (by the caller), once such an extensibility design is implemented (still WIP).

Is that an acceptable workaround? I don't know if the default converter should be guessing the date/time format (especially when it can become ambiguous).

**Comment by pranavkm** [comment]
The one place where we required this, we've changed to use `JsonElement` and doing our own deserialization. I think it's fine to do this rather than have the serializer do `TryParse` on strings all the time. I'll this up to you to decide if this needs to be closed.

**Comment by ahsonkhan** [comment]
> The one place where we required this, we've changed to use `JsonElement` and doing our own deserialization.

Can you share a link to the code where you changed to use `JsonElement`? I want to understand better why ISO supported DateTime parsing wasn't sufficient for your scenario.

**Comment by pranavkm** [comment]
The code in question is trying to deserialize a `IDictionary<string, object>` where `object` is a from fairly limited set of types: https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.ViewFeatures/src/Infrastructure/DefaultTempDataSerializer.cs#L48-L63

**Comment by ahsonkhan** [comment]
And why would `item.Value.TryGetDateTime` / `item.Value.TryGetGuid` not work for you?

```C#
case JsonValueType.String:
    if (item.Value.TryGetDateTime(out DateTime dateTime))
    {
        deserializedValue = dateTime;
    }
    else if (item.Value.TryGetGuid(out Guid guid))
    {
        deserializedValue = guid;
    }
    else
    {
        deserializedValue = item.Value.GetString();
    }
    break;
```

**Comment by pranavkm** [comment]
Ahh neat, I didn't know those were already there.

**Comment by layomia** [comment]
ISO 8601 support has been added to the serializer. Other formats can be supported when an extensibility design for adding custom `DateTime` converters is implemented.
