### ISSUE TITLE
do netcore3 can load com?(e.g.msscript.ocx)

### ISSUE THREAD

**Issue by drearyrainDeng** [dotnet/corefx#36039]
I try to load msscript.ocx to netcore3 ConsoleApp.  build ok. but run fail!  Interop.MSScriptControl.dll was inclueded same folder with ConsoleApp   but still get error  like it   System.IO.FileNotFoundException:“Could not load file or assembly 'Interop.MSScriptControl, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by joshfree** [comment]
@drearyrainDeng could you provide a link to a gist with the repro?

/cc @jeffschwMSFT

**Comment by jeffschwMSFT** [comment]
cc @AaronRobinsonMSFT

**Comment by drearyrainDeng** [comment]
![image](https://user-images.githubusercontent.com/35326823/56861618-1a32d400-69d5-11e9-9c04-7ffa8c9d3a98.png)
[ConsoleApp1.zip](https://github.com/dotnet/corefx/files/3124770/ConsoleApp1.zip)
sorry for big late !it not work,did I do something wrong?

**Comment by AaronRobinsonMSFT** [comment]
@drearyrainDeng Thank you for the project that shows the failure. This is failing because of how the assembly is being referenced. The issue here is related to missing entries in the `.deps.json` file for the project. I would try calling `dotnet restore` on your project or alternatively embedding the COM types using the `EmbedInteropTypes` property on the `COMReference` item - see below for an example.

``` xml
    <COMReference Include="MSScriptControl.dll">
      <Guid>0e59f1d2-1fbe-11d0-8ff2-00a0d10038bc</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
```

Once the type is embedded please change the code to use the interface `coclass` for activation.

The following line

``` csharp
MSScriptControl.ScriptControlClass sc = new MSScriptControl.ScriptControlClass();
```

should become

``` csharp
MSScriptControl.ScriptControl sc = new MSScriptControl.ScriptControl();
```

Activating the interface `coclass` will permit type embedding and allow the CLR to discover the interfaces within the assembly itself instead of relying on CLR  loader to discover the PIA from disk.

**Comment by AaronRobinsonMSFT** [comment]
@drearyrainDeng I am going to close this issue. If this problem persists please file an issue in https://github.com/dotnet/coreclr.
