### ISSUE TITLE
JsonSerializer serialization should use the passed in type

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#36166]
Consider the following sample:

```C#
object message = "Hello";
var serialized = JsonSerializer.ToString(message);
Console.WriteLine(serialized);
```

Json.NET uses the type of the value passed in, therefore the output you'd get here is the string `"Hello"`. System.Text.Json uses the declared type, in this case, `object` and consequently the output you get is `{}`.

This is particularly problematic when you have heterogeneous arrays. Consider:

```C#
var args = new object[] { 1, "Hello", false };
var serialized = JsonSerializer.ToString(args);
Console.WriteLine(serialized);
```

One would expect the output to be `[ 1, "Hello", false ]`, however the serializer uses the declared type (object) and you get `[ {}, {}, {} ]`.

### Background
Microsoft.JSInterop that ships as part of 3.0 ASP.NET Core shared fx, very routinely serializes opaque .NET types that are made available in JavaScript (interop \ RPC using JSON).  I've attempting to convert it's implementation of SimpleJson with the Microsoft.Bcl.Json.Sources package. It provides [APIs to serialize and deserialize JSON objects](https://github.com/aspnet/Extensions/blob/master/src/JSInterop/Microsoft.JSInterop/src/Json/Json.cs#L21). The framework serializes mixed type arrays - https://github.com/aspnet/Extensions/blob/3a884e2e1e6ae3f1fc4381fc8fbb428de5cff063/src/JSInterop/Microsoft.JSInterop/src/JSRuntimeBase.cs#L86-L90.

**Comment by pranavkm** [comment]
cc @SteveSandersonMS

**Comment by stephentoub** [comment]
> JsonSerializer serialization should use the passed in type 

It explicitly doesn't for security reasons.
cc: @bartonjs, @grabyourpitchforks

**Comment by rynowak** [comment]
Is there a suggestion or recipe for how we should handle heterogeneous arrays? That's really what we have a need for. This is an implementation detail of something, so we could consider alternatives as well.

**Comment by stephentoub** [comment]
Presumably for the first case it would just be:
```C#
JsonSerializer.ToString(message, message.GetType());
```

@steveharter or @bartonjs would need to comment on the array case.

**Comment by steveharter** [comment]
As @stephentoub mentioned for static-analysis security we will use the implicit generic type parameter which is `object` in your example.

If that is not desired, use an explicit generic type `ToString<string>()` or use the overload that has a type parameter `ToString(obj, obj.GetType())`

For serializing heterogeneous arrays ideally you would have them as `JsonDocument` or `JsonElement[]` since we plan on adding support to (de)serialize loosely-typed values that way. If that doesn't work then we need a different feature.

**Comment by rynowak** [comment]
I met last week with @steveharter @GrabYourPitchforks @bartonjs @ahsonkhan and @SteveSandersonMS to discuss these scenarios in more detail. Here are some rough notes:

------

We looked at three motivating cases for how users can think about polymorphism and heterogeneous collections. This looks to close scenario gaps in cases where users have existing scripts or consuming code from JavaScript.

In general these scenarios are not intended to round-trip to .NET in a strongly-typed way. This means that it's possible to **write** JSON - that when read will not produce an object graph of the same types. This is perfectly acceptable for Case 2 and Case 3 in these examples.


## Case 1: Person/Employee/Manager

This is the case where you have a class hierarchy with levels of additional properties and information. At the top level this is a solved problem – because you can specify the type. 

What about the case where you have (and want) to serialize a property (not top level) as its runtime type? We haven’t defined a way to do this yet. It’s somewhat common to do, even if it doesn’t round-trip to .NET. In JavaScript this would be easy to consume because the absence of certain properties is not a problem.

We propose to add a new attribute to opt-in to this behavior at a property level to address this case.


## Case 2: Property Bag

This is a case where a user wants to serialize a type like:

class Message
{
              string Id { get; set; }
              DateTime ReceivedUtc { get; set; }
              IDictionary<string, object> Properties { get; set; }
}

In this example the message type has a few defined properties as well as a “property bag” of weakly-typed, arbitrary, serializable data. This is data that might be sent to a monitoring system or some other kind of system that can interpret arbitrary key-value-pairs. The property data is not limited to primitives. (ASP.NET Core health checks has a usage like this).

It’s also desirable for .NET to be able to deserialize this type in *some way* and produce weakly-typed data (JObject equivalent). It’s not required or expected to round-trip the original types used to initialize Properties.

*This is similar to, but not exactly the same as the overflow case.*

We propose to make collections like `List<object>` `object[]` and `IDictionary<string, object>` able to serialize values using their runtime type. The justification is that the property declaration clearly specifies the user’s intent for weakly-typed data.


## Case 3: Arbitrary Prescriptive JSON

This is case where a user wants to serialize something like the following in order to satisfy expectations of existing JavaScript code..NET.

object[] values = new object[] { “hello”, 3, new { isSunny: true } }; 

In this case the structure of the JSON that needs to be returned is prescriptive – it may be a library the developer didn’t write. We need a way to express in .NET how to send data in this format, and it’s already easy to do with JSON. The team says that this works ok today when the object[] only contains primitives – expanding this to include arbitrary values and types would be very valuable. It is not important that .NET is able to deserialize this data in a strongly-typed way.

This is also resolved by the proposal from case 2.


## Proposals:

Values are serialized using their runtime type if:
-	The declared type is System.Object
-	The user places [PolymorphismPlease] (a new attribute) on that property

Otherwise objects are serialized using their declared type.

Declared type is defined as:
-	The type passed into the serializer for top level objects
-	The type of the property for properties
-	The type of the type parameter for an IList<> (includes arrays)
-	The type of the second type parameter for an IDictionary<,> 

Additionally we want to look into:
-	Do we want a global switch to opt-in to polymorphic behavior?
-	What data type is returned from Properties in case 2?
-	Should the serializer try to honor JSON.NET’s attributes for suppressing serialization of properties?

**Comment by NinoFloris** [comment]
Could case 1 be done with the Aspnetcore mantra in mind "Attributes only inform the metadata"? 
I'd like if you could configure allowed polymorphic props/fields on JsonSerializerOptions (via say a list of MemberInfos) vs having to add an attribute...

**Comment by steveharter** [comment]
Closing this as https://github.com/dotnet/corefx/pull/36486 address the serialization case.

**Comment by DynConcepts** [comment]
Was looking into using this for persisting polymorphic object graphs, but 100% round tripping is a requirement.  Any suggestions on a way forward that will align with the direction of .Net Core??

[As a side note: So frustrating that a problem which was basically solved in the early WCF days [nearly 15 years ago] is still even a bump in the road]
