### ISSUE TITLE
Add Async Overrides to SslOverTdsStream

### ISSUE THREAD

**Issue by corivera** [dotnet/corefx#3622]

**Comment by corivera** [comment]
Unnecessary since Stream's Async methods can't be overridden, and just end up using Read/Write anyway.

**Comment by stephentoub** [comment]
> Unnecessary since Stream's Async methods can't be overridden

@corivera, I didn't understand this.  ReadAsync (https://msdn.microsoft.com/en-us/library/hh193669(v=vs.110).aspx), WriteAsync, and FlushAsync all have virtual overloads.  Can you clarify?

It's certainly possible that the base implementation is sufficient.  I just want to make sure we're choosing to not override them for the right reasons.

**Comment by corivera** [comment]
The specific method signature I looked at wasn't virtual. Didn't notice the other one. 

ReadAsync internally just creates async tasks that call Read(), so adding Async overloads to this class is unnecessary.

**Comment by stephentoub** [comment]
> ReadAsync internally just creates async tasks that call Read(), so adding Async overloads to this class is unnecessary.

I think there's a disconnect here.

There's a reason these methods are virtual.  Yes, the base implementation queues a work item to call the corresponding synchronous method; that's the best it can do without knowing more about the concrete implementation.  But the whole point of these methods is to be able to avoid blocking worker threads like that.  If you're a stream that reads and writes over the network, then most of the time spent in a blocking call to Read or Write is going to be waiting for I/O... if you can instead implement the operation with asynchronous I/O, then you can provide a better implementation of ReadAsync and WriteAsync that doesn't just block a worker thread.

SslOverTdsStream wraps another Stream.  If that wrapped Stream tries to do the right thing and implements ReadAsync/WriteAsync to be really efficient, but then the wrapper SslOverTdsStream ignores those methods and just has its ReadAsync/WriteAsync effectively call Read/Write, it'll be doing extra blocking when blocking isn't necessary.

From what I can see, SslOverTdsStream is in fact wrapping a NetworkStream, so there's scalability being left on the table here.

**Comment by kkurni** [comment]
At this moment, only Read(...) is currently called by SSLStream.ForceAuthentication.
SSLStream will wrap this SSLOverTDSStream.
https://github.com/dotnet/corefx/blob/a3050bacc9b716f52f086751bfb4bf0384019f53/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNITcpHandle.cs#L149-L150

This ForceAuthentication, will call Stream.Read by using StreamAsyncHelper.
https://github.com/dotnet/corefx/blob/a3050bacc9b716f52f086751bfb4bf0384019f53/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNITcpHandle.cs#L176

https://github.com/dotnet/corefx/blob/772e42b5d6f3ed46cfb455a94b1ea6891d3271f4/src/System.Net.Security/src/System/Net/SecureProtocols/_SslState.cs#L586

StreamAsyncHelper wrapped Read(...) with TPM to do async call.
https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/src/Common/src/System/IO/StreamAsyncHelper.cs#L63-L84

We need to modify StreamAsyncHelper to call ReadAsync instead so that our ReadAsync will be called.

There are couple option for this issue : 
1. We can implement ReadAsync first.
+ Once StreamAsyncHelper changed to use TPM, It will start get the async benefit.
- But before StreamAsyncHelper is changed, we won't be able to test end to end.
- It will end up adding additional  code means more maintenance.

2. Wait until StreamAsyncHelper change.
+ We will be able to verify whether we get performance benefit of this async + easier to tweak.
+ Less code means less maintenance.

I prefer to choose option 2 for this case as at this moment, It won't give us performance benefit without changing StreamAsyncHelper.

@stephentoub , Let me know what you think ?

**Comment by stephentoub** [comment]
Honestly, StreamAsyncHelper should really go away.  It existed to help code written in terms of the APM pattern migrate to .NET Core, where the base Stream class no longer exposed Begin/EndRead/Write methods, but it really just represents overhead that should eventually be removed.  In fact, I believe it's been removed from everywhere else in corefx, except for System.Net.Security.  Ideally the code that's currently using it would instead be written in terms of ReadAsync/WriteAsync and StreamAsyncHelper could be deleted entirely.

Since no one else in corefx is using StreamAsyncHelper, you could certainly reimplement it to use ReadAsync/WriteAsync instead of queueing a Task.  That might be a good way to get started with this.  Longer term, though, rather than having the consumer do all of this complicated APM logic wrapped around tasks, it'd be better to rewrite the consumer using Tasks/async/await directly.

**Comment by kkurni** [comment]
I agree that we can easily change StreamAsyncHelper to call ReadAsync / WriteAsync.

But Unfortunately we will never call this Async method, there was no async call in our method.

SNITcpHandle call Enable SSL which will call AuthenticateAsClient instead of AuthenticateAsClientAsync.
https://github.com/dotnet/corefx/blob/a3050bacc9b716f52f086751bfb4bf0384019f53/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNITcpHandle.cs#L176

Without calling AuthenticateAsClientAsync this Asycn method will not be called.
https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/src/System.Net.Security/src/System/Net/SecureProtocols/SslStream.cs#L114

https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/src/System.Net.Security/src/System/Net/SecureProtocols/SslStream.cs#L194


I can change this to call AuthenticateAsClientAsync intead in EnableSSL, but this means that I need to create EnableSSLAsync and all other call stack above to start using Async.

Except that I can directly call AuthenticateAsClientAsync.Results which will cause to wait.
But I don't think if this will be a good practice ?

**Comment by kkurni** [comment]
As we don't support true async for open connection at this moment. We will close this issue.
And working on it when we write async all the way up for Open Connection.

**Comment by kkurni** [comment]
As we don't support true async for open connection at this moment. We will close this issue.
And working on it when we write async all the way up for Open Connection.
