### ISSUE TITLE
Consider making FileInfo.Length Property UInt64

### ISSUE THREAD

**Issue by jpfreyen** [dotnet/corefx#36238]
.NETCore documentation states the FileInfo.Length property, i.e. the size of a file in bytes, is a **signed** int

https://docs.microsoft.com/en-us/dotnet/api/system.io.fileinfo.length?view=netcore-2.1

Why?  file size has no meaning as a negative number.   Why make it signed and introduce a theoretical possibly of an overflow, underflow, or wraparound error?  Values/properties like this should be unsigned to 100% eliminate the chance of a bug, even if it's theoretical.

**Comment by Joe4evr** [comment]
> Why?

Same reason `Array.Length`/collection counts are signed ints. For one thing, unsigned integers are not CLS compliant, meaning that other .NET languages might not support them. And for another, changing the return type now is a *massive* binary breaking change.

**Comment by danmosemsft** [comment]
I believe this is the correct answer. (I am curious why the unsigned types were not CLI compliant, perhaps someone knows.)

BTW, it's a long, not an int, so there are still `64 - 1` bits.

**Comment by vcsjones** [comment]
>(I am curious why the unsigned types were not CLI compliant, perhaps someone knows.)

I think largely because VB6 any many portions of COM do not like unsigned integers. Visual Basic .NET  in its first release didn't support unsigned integers, either, so [says wikipedia](https://en.wikipedia.org/wiki/Visual_Basic_.NET#2005_(VB_8.0)). The release notes for Visual Basic 8 (paired with Visual Studio 2005) indicate "support for unsigned integers".

>I believe this is the correct answer.

I think in addition, I also think people tend to do arithmetic on these numbers as well. Having an unsigned operand forces most expressions to also be unsigned, (`4 * 2UL = 8UL`), and I think some people naturally expect negative numbers to work, eg `bool hasEnoughDiskSpaceToCopy = TotalDiskSpaceOfOtherDrive - fileToBeCopied.Length > 0` (a contrived answer, but you get the idea)
