### ISSUE TITLE
Consider "relocating" extension methods defined on System.Data.Common to System.Data

### ISSUE THREAD

**Issue by divega** [dotnet/corefx#36244]
By "relocating", I actually mean copying the extension methods (with new names?) and deprecating the existing ones. 

There are specifically two extension methods defined in System.Data.Common.DbDataReaderExtensions:
``` csharp
public static System.Collections.ObjectModel.ReadOnlyCollection<DbColumn> GetColumnSchema(
    this DbDataReader reader);

public static bool CanGetColumnSchema(this DbDataReader reader);
```
But in https://github.com/dotnet/corefx/pull/36123/files we decided that similar extension methods belong in the System.Data namespace instead. 

Normally, you import System.Data.Common only if you:

- Building an ADO.NET provider
- Consuming ADO.NET APIs in a provider-agnostic way

For consuming extension methods applicable to all ADO.NET providers, System.Data is a better choice.

**Comment by divega** [comment]
The change at https://github.com/dotnet/corefx/pull/36478 means that CanGetColumnSchema is now irrelevant (it will always return true). We only need to _move_ GetColumnSchema.

**Comment by ajcvickers** [comment]
@divega Is the motivation for this only to avoid people needing to use the "System.Data.Common" namespace, or is there more to it?

**Comment by divega** [comment]
it is basically that, to restore consistency (extension methods for DbDataReader should all go in System.Data by default, like the GetXyz(string) methods), and the opportunity to clean up (one of the methods isn’t needed anymore so it can stay where it is and maybe become obsolete).

**Comment by divega** [comment]
@roji @ajcvickers just noticed this doesn’t have a milestone. I don’t think it is super important but on the other hand it should be easy.

**Comment by roji** [comment]
@divega we can definitely push this for 3.0, why not.

However, thinking about this again, if we simply define the same extension methods under System.Data, we're making life complicated for anyone using both System.Data and System.Data.Common (which probably means anyone System.Data.Common) - the invocation would be ambiguous and they would have to specify which version they want.

Creating them under different names seems like it would introduce confusion, with users asking themselves what each one means/does.

With the above two issues I'm not sure that this is an actual win in terms of consistency/ease of use - it may be better to leave things as they are...

One last extreme idea is to really move it, deleting it from System.Data.Common. Since anyone using these methods is almost surely importing System.Data, this *may* be acceptable, but I'm not sure what the corefx policy on such a breaking change is (for 3.0).

What do you think?

**Comment by ajcvickers** [comment]
@roji The reason I didn't put it in a milestone 10 days ago was because I am not convinced we should do this. Unfortunately it then fell off my radar.

My 2¢: it's not worth the break.

**Comment by divega** [comment]
I am fine with closing this. Especially because it is not a that commonly needed API.

**Comment by roji** [comment]
OK, thanks for the feedback - closing.
