### ISSUE TITLE
Proposal - Change the way Marshal allocates / frees unmanaged memory

### ISSUE THREAD

**Issue by Akaion** [dotnet/corefx#36250]
From what I understand, Marshal currently uses LocalAlloc when `Marshal.AllocHGlobal` is used and LocalFree when `Marshal.FreeHGlobal` is used.

The [documentation](https://docs.microsoft.com/en-nz/windows/desktop/Memory/global-and-local-functions) for Local functions states that Heap functions should be used over Local functions where possible (it states in another documentation that local functions have more overhead and, thus, are less efficient.)

Obviously some benchmarks would need to be done but using HeapAlloc and HeapFree over LocalAlloc and LocalFree seems like a logical thing to use unless there is some reason why these functions can't be used with Marshal.

**Comment by jkotas** [comment]
Discussed in https://github.com/dotnet/coreclr/issues/1846

**Comment by GrabYourPitchforks** [comment]
One of the things mentioned in the other thread is that it would be an unaccepable breaking change to redirect these functions to a different allocator. I agree with this assessment - I've written production service code that would fall over dead if we changed this because it allocated memory from `Marshal.AllocHGlobal` (on the managed side), p/invoked into native code, then called `LocalFree` from the native side. We don't want to be in a world where you take your existing Full Framework code, recompile it against Core, see that the build succeeds just fine, then non-deterministically fall over in production due to native heap corruption.

If we do want to use a different allocator we really should have different methods. We could even go so far as to not document what allocators are being used under the covers; instead simply say that `Marshal.AllocSpecial` must always be paired with `Marshal.FreeSpecial`.

**Comment by Akaion** [comment]
Makes sense I guess. Thanks for the insight

**Comment by tannergooding** [comment]
@jkotas, @GrabYourPitchforks Isn't this entirely dependent on what flags are passed to the alloc/free/realloc calls? The local/global functions are publicly documented to just forward down to the newer heap functions for the simple cases.

And running some local tests shows that, you can (for various but not all flag cases) call `HeapAlloc` and a corresponding call to `LocalFree` or `GlobalFree` will succeed (provided it is done with the default process heap). We don't appear to be passing any of the unsupported flags, so it should "just work".

**Comment by jkotas** [comment]
> publicly documented to just forward down to the newer heap functions for the simple cases.

Where is this documented?

**Comment by tannergooding** [comment]
https://docs.microsoft.com/en-us/windows/desktop/Memory/global-and-local-functions

> The global and local functions are supported for porting from 16-bit code, or for maintaining source code compatibility with 16-bit Windows. Starting with 32-bit Windows, the global and local functions are implemented as wrapper functions that call the corresponding heap functions using a handle to the process's default heap. Therefore, the global and local functions have greater overhead.

We might be able to talk to the Windows team and see if they would officially put exactly when they are identical and when they are different.

**Comment by mikedn** [comment]
> Isn't this entirely dependent on what flags are passed to the alloc/free/realloc calls?

No flags are passed to any local free calls. So the free function somehow needs to recognize movable memory handles and do the right thing. That makes it impossible to change `FreeHGlobal` to call `HeapFree` instead of `LocalFree` because it would break people passing movable memory handles to it.
