### ISSUE TITLE
Package.GetPart no longer calls Package.GetPartCore

### ISSUE THREAD

**Issue by stevenbrix** [dotnet/corefx#36388]
This breaks any derived package types that use Package.GetPart to incrementally build the underlying cache of package parts

**Comment by ericstj** [comment]
@stevenbrix and I had a look at this and found the following:
1. Earlier refactoring of Package when initially ported removed all calls to GetPartCore.
2. Instead of calling GetPartCore, the Package.Open methods would call GetParts which would initialize Package's internal part collection with any existing parts.
3. This scenario doesn't work for WPF's [ResourceContainer](https://referencesource.microsoft.com/#PresentationFramework/src/Framework/MS/Internal/AppModel/ResourceContainer.cs,47) type.  This type is an open-ended package that acts as a lookup so it cannot enumerate parts, it can only probe for them.
