### ISSUE TITLE
.NET Core Custom Cultures and IStringLocalizer

### ISSUE THREAD

**Issue by amagrath** [dotnet/corefx#36397]
In a multi-tenant application, different tenants may demand different translations for the same thing, reflecting particular in-house language for example.

The `IStringLocalizer` interface has a `IStringLocalizer WithCulture(CultureInfo culture);` method which returns a culture-specific localizer. Therefore, in a multi-tenant system, the tenant ID somehow needs to be encapsulated into the culture.

Issue https://github.com/dotnet/corefx/issues/24559 discussed how culture variants may be registered with the operating system. However, this approach is impractical in a multi-tenant application where there may be multiple servers, and therefore a `CultureAndRegionInfoBuilder` is needed in .NET Core.

**Comment by tarekgh** [comment]
Sorry, it has been decided CultureAndRegionInfoBuilder is deprecated because it cannot keep in sync with the changes in the underlying OS. It is recommended to use the locale builder as this is updated tools to create the custom cultures. I am not sure which this is impracticable as you can create your custom cultures in advance and deploy it to whatever server. it can be done by simple script. The benefit doing that, you'll be using the tool that ensure updated to match the latest versions of the OS changes.

**Comment by chriswelles** [comment]
I think the issue is that it's natural to want to vary strings/content/html/etc. based upon parameters other than just the "culture" as defined by the OS.  You could say that this is beyond the scope of IStringLocalizer, but then you're stuck building a similar facility above and beyond the built in string localization support, and it's not nearly as elegant.

I've just put some code together where I'm injecting a custom string localizer factory to use a variation that takes some other contextual information into account.  I'm passing through other context through using AsyncLocal<T> data (Yuck!).  It'd be more natural to extend CultureInfo if I could find a clean way to do it, but that doesn't seem to be the case today.

I appreciate the design and flexibility of the current system, but it kind of feels like things should eventually evolve in a direction where IStringLocalizer has a role above and beyond just cultural variations.  (Then again, maybe that would end up being more confusing.)  Maybe .NET 6.0.  :-)

**Comment by amagrath** [comment]
I notice that in version 3 of .NET Core, the WithCulture method has been
deprecated:

``
[System.Obsolete("This method is obsolete. Use `CurrentCulture` and
`CurrentUICulture` instead.")] public
Microsoft.Extensions.Localization.IStringLocalizer
WithCulture (System.Globalization.CultureInfo culture);

``

Since CurrentCulture and CurrentUICulture are both "magic" AsyncLocal
variables, it suggests that your approach of using other AsyncLocal data is
not wrong. However, it does seem to go against the .NET Core grain of
injecting all data as parameters rather than presenting them as AsyncLocal
or ThreadStatic variables.

**Comment by chriswelles** [comment]
Magic contextual variables tend to be problematic.  However, in this particular case, it removed a lot of prior complexity.  My biggest concern is some later developers looking at the technique and going (ooh.  This is cool.  I'll just extend this . . . . )  For that very reason, I was quite hesitant before putting it in.  Dangerous coding practices have a nasty tendency to propagate.
