### ISSUE TITLE
Managing SQL Azure Max Connections

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/corefx#36453]
Originally filed as: https://github.com/aspnet/EntityFrameworkCore/issues/15191 by @tuath

-----

Azure SQL has relatively low maximum connection counts (60 for base database I believe).

In order to protect myself against too many simulataneous connections during a usage peak, I would like to:
1- better understand the behavior of DotNetCore and EFCore when the servers returns a NoMoreConnectionsAvailable type error
2 - a mecanism where i could intercept this so i can fli the health status of my app to degraded, so I can act...

Any ideas, didn't find anything specifc while looking at the code...

**Comment by AfsanehR** [comment]
@tuath You should be able to have a max of 32767 connection by default,although I think it is dependent on your SQL Server Tier.  check the following query to view your setting:
```
select * from sys.configurations
where name ='user connections'
```

It is also best practice to close or dispose your connections properly and not rely on finalizers. Try putting using statements whenever creating a new connection. 
```
using (SqlConnection Conn = new SqlConnection(connectionString))
{
     //Your code 
}
```
Also make sure connection pooling is not disabled and try increasing the Max Pool Size. This can help reuse the connections rather than creating ones every time.

I also saw some good recommendation [here ](https://github.com/Azure/elastic-db-tools/issues/154)about using load balancers to partition requests between app servers. I would recommend going through them.

I hope that helps.

**Comment by tuath** [comment]
Hi @AfsanehR , I double checked and I can't seem to find this information on Microsoft pages (Maximum connection limits per tier for Azure SQL Service). Maybe it's not somethign that matters anymore...

This said, I will close this issue because all i can find right now on the MS website is https://docs.microsoft.com/en-ca/azure/sql-database/sql-database-resource-limits-database-server :

> Sessions and workers (requests)
> The maximum number of sessions and workers are determined by the service tier and compute size (DTUs and eDTUs). New requests are rejected when session or worker limits are reached, and clients receive an error message. While the number of connections available can be controlled by the application, the number of concurrent workers is often harder to estimate and control. This is especially true during peak load periods when database resource limits are reached and workers pile up due to longer running queries.
> When encountering high session or worker utilization, mitigation options include:
> Increasing the service tier or compute size of the database or elastic pool. See Scale single database resources and Scale elastic pool resources.
> Optimizing queries to reduce the resource utilization of each query if the cause of increased worker utilization is due to contention for compute resources. For more information, see Query Tuning/Hinting.
> 

I can swear there was a number here like 80 or 90 for a small 10dtu instance 2-3 years ago… 

Thanks, Erik.
