### ISSUE TITLE
Add generic overloads with unmanaged constraint to BinaryReader/Writer

### ISSUE THREAD

**Issue by bitapparat** [dotnet/corefx#36508]
I suggest adding generic overloads to BinaryReader/Writer now that we have the unmanaged constraint to represent blittable types. 

```cs
void ReadStruct<T>(out T result) where T: unmanaged { ... }
void Write<T>(T value) where T: unmanaged { ... }
```

Difficultly: This requires the ability to convert the endianness of unmanaged types, maybe as a BinaryPrimitives.ReverseEndianness overload. This would be possible in theory, because each unmanaged type ultimately breaks down to primitives at known offsets, but would be a rather involved process.

A great benefit, aside from the ease of use, would especially be the correct treatment of endianness. Currently, a lot of developers just read/write bytes and use Marshal.PtrToStructure/StructureToPtr without respect to endianness.

**Comment by GrabYourPitchforks** [comment]
These APIs already exist on the `MemoryMarshal` class. They're there instead of on `BinaryReader` / `BinaryWriter` / `BinaryPrimitives` because they allow skipping visibility checks and bypassing normal constructor logic, so they are inherently unsafe. See https://github.com/dotnet/corefx/issues/27094 for more information.

**Comment by Lxiamail** [comment]
It's not Serialization related.

**Comment by karelz** [comment]
@Lxiamail please do not remove area lables without setting new ones. Replacing is fine, but each issue should have exactly 1 area label. Thanks!

**Comment by karelz** [comment]
@GrabYourPitchforks if the APIs exist, what is this issue tracking?

**Comment by GrabYourPitchforks** [comment]
I think this issue is tracking the ability to perform endianness-aware serialization of the member fields of unmanaged structs. This isn't something we'd add to the framework, especially given the safety / reliability concerns mentioned previously in this thread. If a struct is being shuttled around within the same process, a simple bitblt (without regard to endianness) would suffice. And if a struct is being shuttled cross-proc or cross-machine, a proper serializer should be used.

I'll close the issue now. If somebody thinks this issue was closed improperly, please reopen and leave comments.
