### ISSUE TITLE
Unintended interactions of SerializationGuard and other features

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#36723]
The SerializationGuard feature is trying to prohibit certain types of operations during deserialization. However, these prohibited operations can happen and are valid for as features indirectly involved by deserialization. Example of such features include tracing or on-demand assembly loading:

- The tracing often create a new file as side-effect of tracing operations done while the deserialization is in progress.
- On-demand assembly loading systems sometimes that materialize the files on disk or even start a compiler in separate process to create the file.

There are likely unintended interations like this that we cannot think about yet. The SerializationGuard feature violates encapsulation that is one of the key principles of good software design.

**Comment by MichalStrehovsky** [comment]
The more attack vectors we try to guard against in the future, the more unintended interactions this feature is going to have (e.g. writing to registry can be equally dangerous as Process.Start and WriteFile...).

Doesn't leaving things trivially exploitable (so that anyone can write their own POC in a matter of minutes) send a better message about how incredibly dangerous arbitrary deserialization is than introducing a feature that makes it look like we're making arbitrary deserialization safe?

**Comment by bartonjs** [comment]
> Doesn't leaving things trivially exploitable ... send a better message ...?

For years docs have said to not deserialize untrusted input.  And for years we've mopped up onesey twosey places with security bugs.  The conclusion was we need to be more proactive.

**Comment by jkotas** [comment]
> The conclusion was we need to be more proactive.

I agree with that. However, it still need to work properly. This feature does not work properly and it is a dead-end design as @MichalStrehovsky pointed out.

**Comment by GrabYourPitchforks** [comment]
Re: assembly load, I don't think the Serialization Guard feature blocks all assembly loads. I think it's just the `Assembly.Load(byte[])`-related overloads that are blocked. Is this impacting a mainline scenario?

**Comment by MichalStrehovsky** [comment]
> I think it's just the `Assembly.Load(byte[])`-related overloads that are blocked. Is this impacting a mainline scenario?

Load from byte array is how people do "single-file" deployments right now. E.g. the NuGet credential provider for Azure embeds its dependent assemblies as resources, hooks up `AppDomain.AssemblyResolve`, and satisfies assembly resolution requests from the embedded assemblies. The embedded assemblies are loaded from a byte array.

**Comment by GrabYourPitchforks** [comment]
I bet we could make that scenario work. Should we use this issue to track it?

**Comment by MichalStrehovsky** [comment]
> I bet we could make that scenario work. Should we use this issue to track it?

I think the point that Jan is making is that every single blocking we add is going to have unintended interactions (including the blocking of file writes, and whatever else we decide to block later - it's not just about `Assembly.Load`). This issue tracks the whole category.

It will be especially problematic if this blocking is looked at as a security feature. E.g. we didn't block registry writes now, but an attacker can use that to do indirect file writes, including a (delayed) process start. Let's say we find this "exploit" later and decide to do a "security fix" to block it. Now the security fix is going to have unintended impacts on scenarios we can't estimate risks on because it impacts arbitrary code paths in user code that might be executing while a deserialization is in progress. The result is that a security fix is going to break customers in code paths unrelated to the fixed area.

**Comment by GrabYourPitchforks** [comment]
We're not interested in closing every possible exploit vector. We're just interested in closing the ones that keep coming up over and over and over again in the security cases reported to us. File writes, assembly loading, and process start tend to be the ones we see in practice since for better or worse developers love writing deserialization ctors that directly or indirectly kick off one of those operations.

You're right in that nothing stops somebody from writing a deserialization ctor that performs an arbitrary registry write. At the same time nothing stops somebody from writing a deserialization ctor that performs an arbitrary write to memory. But we don't have evidence that such types exist in quantities that pose a threat to our ecosystem. And until that evidence appears I don't see us doing anything about it.

**Comment by MichalStrehovsky** [comment]
> But we don't have evidence that such types exist in quantities that pose a threat to our ecosystem. And until that evidence appears I don't see us doing anything about it.

People use Process.Start and file writes because it's the most straightforward thing. Take that away, and people will just find the next straightforward thing (registry, WMI, whatever). It's easy to anticipate the next step here.

If we go and block the next straighforward thing too, it adds to the argument of getting unintended interactions in many places. If we don't block it, this feature becomes pretty much useless (a speed bump that everyone knows how to drive around). Neither of those options make me feel like this is a sustainable design.

**Comment by danmosemsft** [comment]
We need to resolve this before shipping.

**Comment by danmosemsft** [comment]
I spoke to @GrabYourPitchforks. He is going to remove the public surface area and reach consensus on the rest for 3.0 (ie this month I hope).

**Comment by joperezr** [comment]
@GrabYourPitchforks given that you merged #38739, can this be closed now?

**Comment by ViktorHofer** [comment]
Serialization guard is still on by default in 3.0 and master: https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/LocalAppContextSwitches.Common.cs#L48

Did we agree on keep it enabled?

**Comment by bartonjs** [comment]
Yes.
