### ISSUE TITLE
Audit that System.Drawing native structs are marshaled with correct Charset

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#36722]
Auto changed to mean UTF-8 on Unix, we've hit one place were the native code was writing past the buffer because of this. Let's make sure that our Unix native structs in Unix are set to the correct `Charset`.

cc: @stephentoub @jkoritzinsky 

Related: https://github.com/dotnet/corefx/pull/36718 and #36683

**Comment by danmosemsft** [comment]
`c:\git\corefx\src>\t\grep \[.*CharSet.*Auto -R --include=*.cs . | \t\grep Unix` gives no hits.

There are a couple of uses of `Unicode` that aren't relating to `Libraries.GlobalizationNative` (where I"m assuming they're intentional? Are we building that for UTF16?):

```
./System.Drawing.Common/src/System/Drawing/NativeStructs.Unix.cs:    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
./System.Drawing.Common/src/System/Drawing/NativeStructs.Unix.cs:    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
```

One of these seems unnecessary as there's apparently no string. The other has
```
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 32)]
        internal string lfFaceName;
```
@jkoritzinsky is the above all correct?

**Comment by jkoritzinsky** [comment]
The `[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]` on `GdipImageCodecInfo` is unnecessary. The other one is correct and should stay as is.
