### ISSUE TITLE
CodeDom: GenerateMethod & partial method declaration

### ISSUE THREAD

**Issue by gh0stwizard** [dotnet/corefx#36732]
Hi,
I want to generate a method like this with System.CodeDom:
```c#
public partial class MyClass
{
    partial void MyMethod(int value); // note that this is a declaration
}
```
But it is impossible due the test here https://github.com/dotnet/corefx/blob/3f7071d66f563cc2f0d49d4c9be7dd538c0e24ae/src/System.CodeDom/src/Microsoft/CSharp/CSharpCodeGenerator.cs#L1482-L1483

The definition of MemberAttributes is here https://github.com/dotnet/corefx/blob/3f7071d66f563cc2f0d49d4c9be7dd538c0e24ae/src/System.CodeDom/src/System/CodeDom/MemberAttributes.cs#L8-L26

As you may see either I will get `abstract partial void MyMethod(int value);` either `partial void MyMethod(int value) { }` (note the braces). In details, ScopeMask = 0x000F always covers Abstract = 0x0001.

Is it possible to change `MemberAttributes.ScopeMask` value or `MemberAttributes.Abstract` to something different? Or may be fix the check above in the `GenerateMethod()`?

Sample code:
```c#
var @class = new CodeTypeDeclaration(model.Name);
@class.IsClass = true;
@class.IsPartial = true;

var m = new CodeMemberMethod();
m.ReturnType = new CodeTypeReference("partial void");
m.Name = "MyMethod";
m.Parameters.Add(new CodeParameterDeclarationExpression(new CodeTypeReference(typeof(int)), "value"));
m.Attributes = MemberAttributes.Abstract | MemberAttributes.ScopeMask;
@class.Members.Add(m);
```

Thank you!

**Comment by krwq** [comment]
@gh0stwizard, I don't believe this is currently supported. Note that `partial void` is not the type (although it does allow working around adding partial keyword). The proposed fix might allow you to workaround the limitation but is not correct. The proper fix would be probably to add something representing partial method, i.e. `CodeMemberPartialMethod`.

My recommendation would be to instead of CodeDom use Roslyn - it supports all syntax nodes which should always be up to date with the latest features.

**Comment by gh0stwizard** [comment]
@krwq,
>The proper fix would be probably to add IsPartial to CodeMemberMethod.

Yes, you are correct.

>My recommendation would be to instead of CodeDom use Roslyn [snip]

I am able to do this in the current project, I would try Roslyn then. Thank you for quick response. You may close this issue if you wish.

**Comment by krwq** [comment]
Thanks @gh0stwizard!
