### ISSUE TITLE
Package.Open(string, ...) is more restrictive than Package.Open(stream, ...)

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#36794]
We unnecessarily throw on many combinations of FileAccess for Package.Open(string, …).

See https://github.com/dotnet/corefx/blob/5023c2420a4145bcb560c4b8c57f4bb60cd6973f/src/System.IO.Packaging/src/System/IO/Packaging/Package.cs#L838-L849

The .NETCore implementation of System.IO.Packaging permits the write-only case due to the way that System.IO.Compression maintains the ZIP data in memory before writing out.  We should unblock more of these cases.

In the meantime, the workaround is to open the file one-self and call Package.Open(stream, …)
https://github.com/dotnet/corefx/blob/5023c2420a4145bcb560c4b8c57f4bb60cd6973f/src/System.IO.Packaging/src/System/IO/Packaging/ZipPackage.cs#L270

/cc @stevenbrix @miguep

**Comment by ericstj** [comment]
@karelz can you create a label for System.IO.Packaging?

**Comment by stephentoub** [comment]
Done

**Comment by karelz** [comment]
In general, I discourage creating areas for less than 10-20 issues. The overhead does not pay off. There are alternative ways to mark things.
Also, we need to update the internal attribution tooling (I can help), and set up [area owner](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#areas) - who will that be?

I see only 7 issues in the label at the moment. Do we have more? Happy to chat about it tomorrow ...

**Comment by stephentoub** [comment]
> The overhead does not pay off.

What is the overhead? What area label should be used instead? Do the same developers own Packaging that own those areas?

**Comment by karelz** [comment]
Overhead:
* Querying across multiple labels, because GH does not do OR semantics :(
* Maintaining yet another area

> Do the same developers own Packaging that own those areas?

Yes. Unless we have different devs in mind, it does not make sense to break it out IMO (unless it hits critical mass). And even if different devs care about it, that may not be forever and it is still a bit questionable. See for example System.Uri - packed with loagical area System.Net, using "[Uri]" prefix to mark. Not ideal, but it works.
If there are different circumstances for System.IO.Packaging (at least different owner), then I am in ...

**Comment by ericstj** [comment]
System.IO.Packaging is owned by different devs than the rest of Corefx.  WPF owns this

**Comment by karelz** [comment]
Are they aware of that? We need to clarify the ownership on Monday. We need to explain to them requirements and rules of the repo, etc.

**Comment by ericstj** [comment]
@stevenbrix did you still need a fix for this for WPF for 3.0 or did you use the workaround I suggested?

**Comment by stevenbrix** [comment]
@ericstj i'm investigating this now. Is this related to https://github.com/dotnet/corefx/issues/34219? Are you suggesting that the API throws exceptions when it doesn't need to, or are there certain combinations here that don't work due to the seekability of the streams?

If there is a workaround, we are most likely willing to make the necessary changes to use them. With that being said, I'm still in the process of validating that claim.

I'm mostly interested in making sure that WPF customers aren't broken without any possible workaround.

Another possible related issue: https://github.com/dotnet/corefx/issues/25273

**Comment by ericstj** [comment]
This is not related to either of those issues.  I opened this issue as a result of the internal discussion here:  https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int/pullrequest/662?discussionId=5856&_a=files&path=%2Fsrc%2FMicrosoft.DotNet.Wpf%2Fsrc%2FWindowsBase%2FMS%2FInternal%2FIO%2FPackaging%2FPackagingExtensions.cs. 

Here's the current code that's calling this:
https://github.com/dotnet/wpf/blob/9c5dd1acfe9037f92f6c91b05ab2f7e18edf55b7/src/Microsoft.DotNet.Wpf/src/ReachFramework/Packaging/XpsManager.cs#L140-L155

**Comment by stevenbrix** [comment]
@ericstj gotcha, now i understand. yeah i'm hitting this now investigating a different test failure. is there any history as to why these restrictions were put in place for the variation of `Package.Open` that takes a `string` vs. the one that takes a `Stream`?

**Comment by ericstj** [comment]
So the two we can remove here are https://github.com/dotnet/corefx/blob/5023c2420a4145bcb560c4b8c57f4bb60cd6973f/src/System.IO.Packaging/src/System/IO/Packaging/Package.cs#L840-L843

**Comment by stevenbrix** [comment]
@ericst should they be removed, or be changed to allow `FileAccess.Write`?

**Comment by ericstj** [comment]
We can remove completely since FileStream itself will check for FileAccess.Write whenever Create is specified.
