### ISSUE TITLE
Enable HttpClient activity propagation by default

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#36954]
In order to enable end to end distributed tracing in ASP.NET Core applications without a DiagnosticListener being enabled. Today the logic in the HttpClientHandler only enables activity propagation if there's a DiagnosticListener (e.g. https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.Net.Http/src/System/Net/Http/HttpClientHandler.Unix.cs#L405), to make this more seamless, we'd like to do this if `Activity.Current` is non-null or if there's a listener. This would allow ASP.NET Core applications that are Activity enabled to automatically "activate" outgoing HttpClient calls for activity propagation.

As part of this change, it's also desirable to allow disabling this feature at various levels:
- Exposing DiagnosticHandler as a public API users can choose to use:
  - Exposing an instance property `DiagnosticHandler.SuppressActivityPropagation` (per DiagnosticHandler instance)
  - Exposing a static property `DiagnosticHandler.SuppressAutomaticActivityPropagation` (per app domain)
  - via HttpRequestMessage.Properties["disableHeaderPropogation"] (per request)
  - via Activity.Current.Tags["disableHeaderPropogation"] (per async execution)

The above ways to disable the flow don't all need to be considered but they cover all of the cases. We can choose the most valuable ones to do.

cc @lmolkova @noahfalk

**Comment by karelz** [comment]
@davidfowl do oyu plan to fix it? (if yes, I will assign it to you)

**Comment by davidfowl** [comment]
Yes assign me

**Comment by karelz** [comment]
@davidfowl time is running short ... any ETA?

**Comment by lmolkova** [comment]
Looking into this.

Making `DiagnosticsHandler` public creates a whole new level of complexity:
- it will be possible to add it to the pipeline in addition to the one added automatically in `HttpClientHandler`
- need to pass instance `SuppressActivityPropagation` to the instance created by `HttpClientHandler`.

I suggest to expose `SuppressActivityPropagation` properties on `HttpClientHandler` instead.
Also, they should disable instrumentation in the presence of the listener - this is helpful in some scenarios when remote endpoint does not allow correlation headers (because of CORS or something else) or when there is a specialized listener and auto-instrumentation is not needed.

Will try to send PR and API review tomorrow.
