### ISSUE TITLE
ToString() extension method for IEnumerables

### ISSUE THREAD

**Issue by fiddyschmitt** [dotnet/corefx#36955]
Request to add the following extension method:

```c#
public static string ToString(this IEnumerable<string> list, string separator)
{
    string result = string.Join(separator, list);
    return result;
}
```

This means that instead of this:

```c#
var guestList = string.Join(Environment.NewLine, people
                    .OrderBy(p => p.Firstname)
                    .ThenBy(p => p.Surname)
                    .Select(p => $"{p.Firstname} {p.Surname}"));
```

We can do this:

```c#
var guestList = people
                    .OrderBy(p => p.Firstname)
                    .ThenBy(p => p.Surname)
                    .Select(p => $"{p.Firstname} {p.Surname}")
                    .ToString(Environment.NewLine);
```

**Comment by Happi-cat** [comment]
would be better to use different name, as in that case its not obvious
and there is a chance that someone can decide to use object.ToString() by mistake

**Comment by fiddyschmitt** [comment]
Hi Happi, I think ToString() is suitable because it's reasonable to expect that calling ToString() on a list would result in a flattened string.

**Comment by huoyaoyuan** [comment]
Because 'object.ToString()' always exists, an extension method seems would never be chosen.
Technically, you want an extensive use for 'string.Join'. Permitting extension methods everywhere may help.

**Comment by Clockwork-Muse** [comment]
What you're really looking for is a `FormatJoin` method on `string`, more than anything on `IEnumerable` itself, I think.  That could just be me, though, since I tend to be wary of outputting things as string (for anything other than console debugging, anyways).

<hr />
In your original example code, this:
```csharp
.Select(p => $"{p.Firstname} {p.Surname}")
```
... will allocate a new string for each item (plus the one for the final concatenation, but that's required regardless).  Which would be nice to avoid, if possible.

So if we did put something on `IEnumerable`, I'd want something like this instead:

```csharp
var guestList = people
                    .OrderBy(p => p.Firstname)
                    .ThenBy(p => p.Surname)
                    .Select(p => (p.Firstname, p.Surname))
                    .FormatAsString(Environment.NewLine, "{0} {1}");
```
(which still allocates a tuple, but at least it's a value type).

Note that you can do something similar now, too:

```csharp
var guestlist = people
	.OrderBy(p => p.Firstname)
	.ThenBy(p => p.Surname)
	.Aggregate(
		new StringBuilder(), 
		(sb, p) =>
		{
			sb.AppendFormat("{0} {1}", p.Firstname, p.Surname);
			sb.AppendLine();
			return sb;
		},
		sb => sb.ToString());
```
<kbd>[Example fiddle](https://dotnetfiddle.net/fsa6Yo)</kbd>

<hr />

Side note: surname and _firstname_?  Shouldn't it normally be surname and _given name_?

**Comment by karelz** [comment]
Given that it is just different syntax for using `string.Join(char, IEnumerable<T>)`, I don't think we should add it.
In general, we do not want to add duplicate APIs in BCL, which are only for convenience, unless significant portion of all C# developers need them.
In this case, it is easy to do custom extension and I think we should leave it at that.
I recommend closing the issue.

**Comment by Clockwork-Muse** [comment]
@karelz - what about the ability to pass in a format string?  I feel that's possibly the more important/interesting part of the proposal, than adding anything to LINQ.

**Comment by svick** [comment]
If you're talking about the `FormatAsString` method you proposed, how would you implement it efficiently, considering that it seems to work on `IEnumerable<any-tuple>`? Especially if you're trying to avoid allocations, you should make sure the new method does not allocate too much, and I'm not sure how would that work here.

**Comment by karelz** [comment]
@Clockwork-Muse I don't see that in the top post. Was it mentioned in your reply? I don't fully understand that proposal to have a strong opinion.
Maybe it deserves separate issue / discussion?

**Comment by Clockwork-Muse** [comment]
@svick - 
That looks to have been overly-wishful thinking on my part; having the ability to dereference the elements in a tuple during formatting.  I wouldn't want it to work on tuples specifically, anyways.

I'd have to read a bit more through the code, but I'd imagine something along the lines of what `StringBuilder.AppendFormat` is currently doing is what we'd need.  (We might have a better result if `ISpanFormattable` was public, and more widely used, but even just the primitives is a good start)

**Comment by Clockwork-Muse** [comment]
@karelz - 
Yeah, I mentioned an alternative there.  Opened new issue #37170

**Comment by MgSam** [comment]
@karelz Joining the elements of an enumerable into a string is an extremely common operation. It is so common that it's on `Array` in [JavaScript](https://www.w3schools.com/jsref/jsref_join.asp) (which is notoriously light on built-in operations). 

I really don't understand Microsoft's position of not having touched LINQ in 10 years and instead defaulting to "make your own extension method" for every single LINQ request. The whole point of a framework is to provide standard ways to accomplish common tasks. 

And there are tons of duplicate ways to accomplish the same operations in .NET. Moving an API from where it's hard to find (a static method on `String`) to an instance method (via extensions) on `IEnumerable` (where it's trivial to find because LINQ is so commonly used) seems like a no-brainer to me.

Though I definitely think it should not be called `ToString()`. And since `Join` is already taken, I personally use `JoinString` in the extension method that I have to write in nearly every one of my projects :)

**Comment by stephentoub** [comment]
> I really don't understand Microsoft's position of not having touched LINQ in 10 years

I'm not sure what you mean.  LINQ has been almost entirely rewritten in .NET Core over the last few years, and has received attention and optimizations in almost if not every .NET Core release.  There also have been new APIs added, such as TakeLast, SkipLast, Append, and Prepend.

> instead defaulting to "make your own extension method" for every single LINQ request

The vast majority of such requests are incredibly specialized.  There is cost to both the implementers and consumers of Enumerable to having additional API surface area there.  There are multiple popular 3rd party libraries containing a plethora of `IEnumerable<T>` extension methods, which anyone can use, and of course anyone can write their own. And except in the most extremely useful/general scenarios, we also do not provide methods just to provide a different name for something, so we wouldn't add an extension on `Enumerable` in order to let someone write `list.ToString(separator)` instead of `string.Join(separator, list)`.

Regardless, thank you for the suggestion.
