### ISSUE TITLE
GenerateReferenceSource Baseline is out of date

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#36966]
The current baseline for `/t:GenerateReferenceSource` appears to be fairly out of date.

Currently running it over the entire repo produces a number of diffs:
[Baseline.patch.txt](https://github.com/dotnet/corefx/files/3090216/Baseline.patch.txt)

Some of this is simple "ordering" issues and many of it is attributes that we say can be stripped. However, there are also a few APIs that are reported as not being exposed.

These should likely be reviewed and fixed-up as applicable.

**Comment by tannergooding** [comment]
CC. @ericstj, @ahsonkhan

**Comment by ericstj** [comment]
FYI patch files can be visualized in a gist (or you can always push the commit somehwere and link that).

EditorBrowsable should not be removed, it's only relevant in the reference aseembly, so if anything it can be omitted from the implementation, not the reference.
Same is true for Obsolete.
I suspect that both of these are stripped because we are using the same exclusion list for API-compat and GenAPI.
I can't remember all the decisions made for XML attribute but those could be cleaned up.

CoreFx.Private.TestUtilities -> don't care but it can be cleaned up.  Alternatively if folks were intending for that to be implementation only, they can configure GenAPI to omit it. 

This removes ifdefs -> we shouldn't do that.  The way to fix that to make it stable is to use partial files  and then configure GenAPI to split the API between the partial files.
This is merging API that was in partial files into the main file -> we shouldn't do that.  The way to fix that to make it stable is to configure GenAPI to split the API between the partial files.

>  there are also a few APIs that are reported as not being exposed.

This is possible, but not likely given we run reverse API-compat on most libraries.  We don't do that on facades, so those might be problems.  Most cases I looked at seemed like the manual file merging I mentioned above.  Did you see any case where a library was actually missing API?

**Comment by tannergooding** [comment]
> I suspect that both of these are stripped because we are using the same exclusion list for API-compat and GenAPI.

Yes, that looks to be the case. Probably something we should split out...

> Did you see any case where a library was actually missing API?

I'm not familiar enough with the surface area to say for sure on any given API. But, ideally we should be able to run `/t:GenerateReferenceSource` across the entire repo and there would be zero diffs. There are likely places today where the tooling is insufficient and we should identify those individual cases and log issues for them so they are explicitly tracked.

**Comment by joperezr** [comment]
Is this a dupe of #29737?

**Comment by tannergooding** [comment]
Possibly. I don't think the other has a baseline patch that can be reviewed though...

I'll close this one and copy the patch over to it.

**Comment by ahsonkhan** [comment]
> FYI patch files can be visualized in a gist (or you can always push the commit somehwere and link that).

**This commit** from a while back has a more readable "diff", though I am sure its out-dated by now:
https://github.com/dotnet/corefx/pull/35474/commits/1534ca918cb69fda62039663b2c5282785c3b03f 

(from https://github.com/dotnet/corefx/pull/35474/commits - "Update reference assemblies based on source changes")
