### ISSUE TITLE
Running GenerateReferenceSource fails against certain source projects.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#36967]
Currently running `/t:GenerateReferenceSource` against the certain `src` projects in the repo causes the following failure:

```
Unable to resolve assembly 'Assembly(Name=System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)' referenced by '...'.
```

Is this expected? I see no such errors when running against the `ref` projects

**Comment by tannergooding** [comment]
CC. @ahsonkhan, @ericstj

**Comment by tannergooding** [comment]
It also looks like `GenerateReferenceSource` against a ref and against the src generate very different outputs in some cases.

Ideally this would be effectively the same and people could reliably run a single command to ensure that everything was up to date and correct (https://github.com/dotnet/arcade/issues/2540 is probably partially related).

**Comment by ericstj** [comment]
Running GenerateReferenceSource isn't really a valid scenario, other than maybe as a hack to see how it round-trips the source (and it washes away and ifdefs/source file factoring).

Running against implementation fails to find the corelib because of the hack that the target uses for passing references: https://github.com/dotnet/corefx/pull/34379#discussion_r246085065

It should instead be using the same set of references that are passed to the compiler, as is done here: https://github.com/dotnet/arcade/blob/5c40ffc8d160681c1ff39f69ec8fd893795bd520/src/Microsoft.DotNet.GenAPI/build/Microsoft.DotNet.GenAPI.targets#L89

This should be addressed by https://github.com/dotnet/corefx/issues/33981
