### ISSUE TITLE
PostRewindableContentUsingAuth_NoPreAuthenticate_Success is failing with a NotImplementedException on Linux

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#3699]
System.Net.Http.Functional.Tests:
Reference PR: #3680
Reference build: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/4926/

PostRewindableContentUsingAuth_NoPreAuthenticate_Success is failing with a NotImplementedException.

See original discuss on PR #3680.  But CurlHandler should not be using `Seek` to rewind the HttpContent request body.  Instead, it should use the HttpContent.CopyToAsync() API to have the content serialize itself.

@stephentoub (GitHub seems to hiding your comment so I'm re-quoting it here)

>Thanks for the explanation, David.
Yes, libcurl provides a CURLOPT_SEEKFUNC callback. According to the docs, "this function gets called by libcurl to seek to a certain position in the input stream and can be used to fast forward a file in a resumed upload (instead of reading all uploaded bytes with the normal read function/callback). It is also called to rewind a stream when data has already been sent to the server and needs to be sent again. This may happen when doing a HTTP PUT or POST with a multi-pass authentication method, or when an existing HTTP connection is reused too late and the server closes the connection." We implement that callback by checking if the Stream's CanSeek is true, and if it is, calling Seek, otherwise we inform libcurl that the Stream isn't seekable:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.MultiAgent.cs#L851-L859
What would you recommend we do here instead?

The CurlHandler is not supposed to be rewinding the HttpRequestMessage.Content streams.  It should be simply using the HttpContent contract APIs to tell the HttpContent to "serialize" itself.  The HttpContent object is responsible for determining how to do that.  The CurlHandler should not be directly retrieving a stream from the HttpContent. Instead the HttpContent is told to serialize itself to a some "Http Request Stream".  And it does that via the its `CopyToAsync` method.

See code in WinHttpHandler for example:

```c#
                    // Send request body if present.
                    if (state.RequestMessage.Content != null)
                    {
                        using (var requestStream = new WinHttpRequestStream(requestHandle, chunkedModeForSend))
                        {
                            await state.RequestMessage.Content.CopyToAsync(
                                requestStream,
                                state.TransportContext).ConfigureAwait(false);
                            requestStream.EndUpload();
                        }
                    }
```

**Comment by davidsh** [comment]
cc: @stephentoub @kapilash

**Comment by davidsh** [comment]
Updated stack trace:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/4948/

MESSAGE:
System.Net.Http.HttpRequestException : An error occurred while sending the request. ---- System.NotImplementedException : CustomStream.Seek
+++++++++++++++++++
STACK TRACE:
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() at System.Net.Http.CurlHandler.<QueueOperationWithRequestContentAsync>d__1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Net.Http.Functional.Tests.PostScenarioTest.<PostUsingAuthHelper>d__26.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at System.Net.Http.Functional.Tests.PostScenarioTest.<PostRewindableContentUsingAuth_NoPreAuthenticate_Success>d__f.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) ----- Inner Stack Trace ----- at System.Net.Http.Functional.Tests.CustomContent.CustomStream.Seek(Int64 offset, SeekOrigin origin) at System.Net.Http.DelegatingStream.Seek(Int64 offset, SeekOrigin origin) at System.Net.Http.CurlHandler.MultiAgent.CurlSeekCallback(IntPtr context, Int64 offset, Int32 origin)

**Comment by stephentoub** [comment]
@davidsh, I appreciate the additional info, but I'm not following how your comment applies.

Is there any situation in which winhttp asks to start over such that you reinitiate the CopyToAsync?  If so, can you point us to where?  If not, how do you propose that happen for other implementations (like CurlHandler) that need to?  Presumably you're not encouraging buffering the entire request stream in memory, in which case if the handler needs to be able to start over _during_ the CopyToAsync operation, how do you propose that work?

I'm also not clear on why it's such a problem to support seeking.   You talk about the HttpClient API contract, but it's exposing a Stream, and so if that Stream returns true from CanSeek, certainly seems like it's part of the contract that you should be able to seek on it.  Why is that such a problem?  If it really is one, that seems like a fundamental problem with HttpClient APIs.

Note that libcurl has a pull-based model: you don't write data to it whenever you want, but rather it asks for the next chunk of data when it needs it.  So CopyToAsync is far from an ideal API to use.  That's why the current CurlHandler implementation uses HttpContent.ReadAsStreamAsync, and then Reads from the Stream on-demand when libcurl asks it for more data.  Why do we expose a ReadAsStreamAsync method if it's not supposed to be used?

Thanks for any additional insights.  I think we really need to find a solution here that doesn't involve bending over backwards to try to force a push-model onto a handler that's fundamentally based on a pull-model.

**Comment by davidsh** [comment]
The ReadAs* methods are similar but not the same.  I'll need to pull out the old design document.  But the ReadAs* methods were meant to consume the content and used mostly by endpoints wanting to read the transmitted data.

The CopyToAsync() API calls the protected SeralizeToStreamAsync() method which subclasses of HttpContent can override to provide custom streaming behavior from constructing the content-read-stream.  Having the curl implementation use the ReadAs* APIs to get a stream to read to pull from is not the way the HttpClient APi was originally designed to work well from.  Using a pull-based model like that will mean that the SeralizeToStreamAsync() protected method won't get used at all which will break all subclasses of HttpContent that developers might use.

WCF may have some guidance here because they extensively create subclasses of HttpContent where they are providing a custom stream implementation since they can control how they serialize the data to the HTTP request stream.  The design principle of HttpClient has always been a push model to push content to the HTTP request stream.  It was that way with the original HttpWebRequest.

You can call it a "problem" with the API since it works that way.  But it's the way the API was fundamentally designed at the time.  If the CurlHandler continues to use the ReadAsStreamAsync() API to get a pull-model for content upload, then we will have scenarios in WCF that just won't work.  

@mconnew (WCF team) might be able to shed more light on this.

**Comment by davidsh** [comment]
And regarding this question:

>Is there any situation in which winhttp asks to start over such that you reinitiate the CopyToAsync?

Yes, that happens all the time.  If you look at the code which calls `CopyToAsync` you will see it is in a loop (retry loop).  It loops when the request needs to be resent due to redirection and/or auth challenges.

**Comment by stephentoub** [comment]
> The ReadAs* methods are similar but not the same.

Ugh, that's unfortunate.  This is going to lead to less efficient implementation for any system that is pull-based, as with libcurl.  We're going to need an adapter where we effectively stall the CopyToAsync until we're asked for the next piece, and to support restarts the logic is going to get convoluted due to the request coming from a callback rather than from a loop around the operation.

**Comment by davidsh** [comment]
@stephentoub Before we start re-working the CurlHandler, it would be good to 1) get input from @mconnew  and 2) run more WCF tests using the Linux CurlHandler and see what scenarios might be broken (or less performant) in WCF.

**Comment by stephentoub** [comment]
Thanks, @davidsh.  Sounds good.  @mconnew, any insights you can provide would be helpful.  I searched around wcf a bit, and from brief inspection it looks the HttpContent-derived types there would always have the same data surfaced through ReadAsStringAsync (via CreateContentReadStreamAsync) and through SerializeToStreamAsync, but maybe I misread the ones I saw or maybe I missed some others that are behaving differently.

**Comment by davidsh** [comment]
And FWIW, I could implement the Seek() method in this test class to prevent this exception from occurring in the test.  Or CurlHandler could use ".Positiion=0" instead of Seek(0, ...) to rewind it's stream.  

But we would only be covering up this nuanced issue about push vs. pull model for uploading request body and how if might impact Xplat compat.

**Comment by mconnew** [comment]
We've already needed to implement two different code paths to achieve the same end for the WinHTTP based handler and the UWP WinRT based handler. [WinHttpHandler uses HttpContent.CopyToAsync](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L1179) which can't be overridden. This [then calls SerializeToStreamAsync](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpContent.cs#L323) which can be overridden which we do [here](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MessageContent.cs#L187). For UWP, HttpHandlerToFilter uses HttpContent.ReadAsStreamAsync which also can't be overridden. This then calls [CreateContentReadStreamAsync](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpContent.cs#L288) which we've needed to [override](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MessageContent.cs#L177). So today if you want to create an HttpContent class which works with core clr and with UWP, you have two separate methods that need to be overridden anyway. As ReadAsStreamAsync presumes a pull model (we're supposed to provide a stream that can be read from which can happen before we have data ready) and WCF is a push model (we write to the stream as we're serializing the payload as it could be very big) we had to create a stream to accommodate this. This is our [ProducerConsumerStream](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ProducerConsumerStream.cs) and might be useful in brokering between the two models in this scenario too.

**Comment by stephentoub** [comment]
Thanks, @mconnew.  So if I'm understanding correctly, handlers that consume content via ReadAsStreamAsync will work correctly with WCF, both the one used in UWP and CurlHandler.  If that's the case, is there a good reason for CurlHandler to change in this regard?  It sounds like your implementation already handles the pull/push difference, so the only thing we'd be doing by changing the CurlHandler model is changing in which codebase the pull/push adaptation happens.

**Comment by stephentoub** [comment]
Also, I noticed that the ProducerConsumerStream isn't seekable: https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ProducerConsumerStream.cs#L27.  What does UWP do in the case where it needs to retry/resend, ask for a new stream?

**Comment by davidsh** [comment]
@mconnew This is good information.

@stephentoub Based on this discussion, I think we can 1) leave CurlHandler as-is using the 'putll' model, 2) Implement the "Seek()" method in the test class esp. since the Position property is implemented, and 3) re-activate the test.

**Comment by mconnew** [comment]
@stephentoub, if you have all the data buffered (e.g. MemoryStream) or already available in a seekable stream (e.g. FileStream), you don't need a ProducerConsumerStream as CurlHandler will be able to pull data whenever it's needed. This is only needed when you are producing the data as you are sending and the data production isn't an on-demand mechanism. In our case we need a stream that we can pass to a producer which could be almost any type of code (usually a message encoder but could be user code writing to the stream behind the curtain which we have no control over), and we need to make the producer wait if the http request can't keep up, and we need to make HttpClient wait if the client can't keep up.

**Comment by stephentoub** [comment]
> if you have all the data buffered (e.g. MemoryStream) or already available in a seekable stream (e.g. FileStream), you don't need a ProducerConsumerStream as CurlHandler will be able to pull data whenever it's needed

This is what we're already doing: we get a Stream via ReadAsStreamAsync and read from it, and if it's a MemoryStream, we do additional optimizations.  This thread started because David initially suggested we shouldn't be using ReadAsStreamAsync, but should instead be using CopyToAsync, which means we'd always need such a ProducerConsumerStream to serve as the middle-man between CopyToAsync and our pull-based consumer.

**Comment by stephentoub** [comment]
@davidsh, I've spent some more time understanding the HttpContent implementation, and it seems we're stuck between a rock and a hard place.

With ReadAsStreamAsync and seeking, we get the best performance.  It's extremely common for the stream that comes back to be a MemoryStream, which leads to an optimal implementation.  It's also common for it to be a FileStream or something else that's seekable and that does caching to make asynchronous reads typically very fast. However, ReadAsStreamAsync has some deficiencies.  For example, some of the WCF HttpContent-derived types return non-seekable streams from CreateContentReadStreamAsync and thus from ReadAsStreamAsync.  This means that, using ReadAsStreamAsync, if we need to resend a request, we need to call ReadAsStreamAsync again.  But for whatever reason ReadAsStreamAsync doesn’t do the same _contentConsumed check that SerializeToStreamAsync does.  That means if the content is actually a StreamContent, whose CreateContentReadStreamAsync just does ```return Task.FromResult(new ReadOnlyStream(this._content));```, and if the stream is non-seekable, then we’ll end up getting back the “new” stream but that’s already had its content consumed, and we won’t know.  We can’t even try to do an object reference comparison, because StreamContent is wrapping the returned stream in a new ReadOnlyStream instance each time.

With HttpContent.CopyToAsync, it seems we get the best integration with any HttpContent that might exist, or at least remain consistent with WinHttpHandler as to the HttpContents we support.  However, this forces us to *always* have an intermediate pull/push-adapter stream, even for the very common case of the input being a MemoryStream.  This has non-trivial overheads that we’ll always pay even though they’re typically not necessary.

From a correctness perspective, it seems we may need to go the HttpContent.CopyToAsync route, but as a result we’ll end up leaving perf on the table.

**Comment by davidsh** [comment]
>But for whatever reason ReadAsStreamAsync doesn’t do the same _contentConsumed check that SerializeToStreamAsync does. That means if the content is actually a StreamContent, whose CreateContentReadStreamAsync just does return Task.FromResult(new ReadOnlyStream(this._content));, and if the stream is non-seekable, then we’ll end up getting back the “new” stream but that’s already had its content consumed, and we won’t know.

This is actually a known issue with ReadAsStreamAsync().  Will send offline email with link.
