### ISSUE TITLE
Why .NET Framework is localized?

### ISSUE THREAD

**Issue by epeshk** [dotnet/corefx#37031]
Sorry for offtop, i don't know a better place for this question.

Why .NET Framework exception messages and compiler errors are localized? Are there any reasons for this? IMHO developers can understand english errors better than machine translated trash. Is it legacy? Why there is no opt-out for localized errors (Or I'm wrong)?

Found [this issue](https://github.com/Microsoft/dotnet/issues/474). It describes pain and possible solutions, but doesn't describe historical reasons which localization was added.

Most likely .NET FW is localized to be consistent with Windows. Other question: why windows developer-related stuff are localized? (e.g. FormatMessage winapi, Performance Counter categories and counter names). Can somebody explain why?

**Comment by danmosemsft** [comment]
@epeshk I don't know why exceptions were historically localized - this decision would be nearly 20 years ago. 

At a guess, the reason was because some apps show the messages to their users. For example, if there is an IOException like "Path c:\foo\bar is not found" it is not easy to make such a good message in your own app, even if you want to. You cannot tell the issue is "path not found" and the actual path, without fragile parsing of the text (although [this may help](https://github.com/dotnet/corefx/issues/34221)). If you show the messages, you may want them to appear in the user's own locale. If you want them in en-US, you should be able to simply set the thread culture before the exception is thrown.

Currently, .NET Core libraries do not localize their exceptions, but I believe the CLI does localize its errors. We may localize our exceptions in future, but there is no current plan to do so and we'd be interested in community input at that point.

I think this question is answered, as far as we can answer, so I'll close. Please reopen if not.

**Comment by uhfath** [comment]
> Currently, .NET Core libraries do not localize their exceptions, but I believe the CLI does localize its errors. We may localize our exceptions in future, but there is no current plan to do so and we'd be interested in community input at that point.

Is there any way to, for example, replace some .resx with custom localized version at least?
