### ISSUE TITLE
Get Kerberos ticket from Linux kdc server

### ISSUE THREAD

**Issue by westfin** [dotnet/corefx#37060]
I use Linux Debian 9 with kdc server for Kerberos authentification.
Is it possible on windows machine get ticket from linux kdc server?
Simply I need create service like `kinit`.

I see a lot of issues about Kerberos and Ntlm and I think class `NegotiateStream` can help me.
But to be sure I create this issue.

**Comment by davidsh** [comment]
The short answer is yes this is possible.  However, it requires a lot of configuration on the machines so that the Windows machine is joined to the Linux Kerberos realm.

.NET Core supports kerberos in general for HTTP and NegotiateStream scenarios.

This question is really, though, outside the scope of this repo.  There are lots of resources on the Internet that can assist you in configuring Windows and Linux Kerberos interop scenarios.

@karelz

**Comment by davidsh** [comment]
Here are some links that can help.  I've used these to help set up our Enterprise testing lab to verify that .NET Core works in these scenarios.

Setting up cross realm trust between Active Directory and Kerberos KDC
https://blog.godatadriven.com/cross-realm-trust-kerberos.html

Kerberos Cross Authentication
https://zeroshell.org/kerberos/Kerberos-cross-authentication/

MANAGING AND CONFIGURING A CROSS-FOREST TRUST ENVIRONMENT
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/windows_integration_guide/trust-managing#posix-attributes-from-ad

**Comment by davidsh** [comment]
If you are looking for .NET cross-platform low-level Kerberos protocol library then that is issue #32291.

**Comment by westfin** [comment]
@davidsh Thank you.

Today I read your links and now I understand where problem. I did not think that add windows client to kdc realm so difficult and need a lot of configuration work.

**Comment by davidsh** [comment]
Glad you figured out the problem with your configuration.

As I mentioned earlier .NET Core doesn't support a low-level Kerberos API but this is tracked by #32291
