### ISSUE TITLE
Add non-primitive value support for dictionaries in JsonSerializer

### ISSUE THREAD

**Issue by layomia** [dotnet/corefx#37077]
Currently, the serializer only supports primitives (`int32`, `string`, `float` etc.) as dictionary values.

Support for non-primitive types should also be added:

- [ ] `Dictionary<string, MyConcreteClass>`
- [ ] `Dictionary<string, List<T>>`
- [ ] `List<Dictionary<string, T>`
- [ ] `Dictionary<string, Dictionary<string, T>>`
- [ ] Polymorphic support (serialize only): `Dictionary<string, object>`

cc @steveharter

**Comment by Joelius300** [comment]
Will there ever be serialization-support for `Dictionary<object, object>`? Other json-libraries simply call `.ToString()` on the key in order to get the json-`string`-key. Currently there is no support for this even if you fully implement and override `.ToString()` for the object you want to use as key.  
If it's not a possibility to make this the default behaviour, it would be nice to at least have the option for this maybe through an attribute or the serialization options.  

What do you think?  

Ps. if this is the wrong place for this kind of question I can also open an issue but I thought since this is very closely related to this issue I'll just comment on here.

**Comment by adrianm64** [comment]
polymorphic `IReadOnlyDictionary` doesn't work for me.
Primitive works fine
Works in `Json.net`
```
internal sealed class ValueCollection : IReadOnlyDictionary<string, object>
{
    private readonly List<KeyValuePair<string, object>> _values = new List<KeyValuePair<string, object>>();

    public void AddValue(string key, object value) => this._values.Add(new KeyValuePair<string, object>(key, value));

    IEnumerator<KeyValuePair<string, object>> IEnumerable<KeyValuePair<string, object>>.GetEnumerator() => this._values.GetEnumerator();
    IEnumerator IEnumerable.GetEnumerator() => this._values.GetEnumerator();

    int IReadOnlyCollection<KeyValuePair<string, object>>.Count { get => this._values.Count; }
    bool IReadOnlyDictionary<string, object>.ContainsKey(string key) => throw new System.NotImplementedException();
    bool IReadOnlyDictionary<string, object>.TryGetValue(string key, out object value) => throw new System.NotImplementedException();
    object IReadOnlyDictionary<string, object>.this[string key] { get => throw new System.NotImplementedException(); }
    IEnumerable<string> IReadOnlyDictionary<string, object>.Keys { get => throw new System.NotImplementedException(); }
    IEnumerable<object> IReadOnlyDictionary<string, object>.Values { get => throw new System.NotImplementedException(); }
}
```

```
    var vc = new ValueCollection();
    vc.AddValue("x", 1);
    
    JsonSerializer.Serialize<IReadOnlyDictionary<string, object>>(vc).Dump();
```

Error message is 
>Unable to cast object of type 'Enumerator[System.Collections.Generic.KeyValuePair`2[System.String,System.Object]]' to type 'System.Collections.IDictionaryEnumerator'.

Seems to be multiple problems:
* Not detecting the object as a generic dictionary and calls non-generic `IEnumerable.GetEnumerator`
* Assuming `IEnumerable.GetEnumerator` returns an `IDictionaryEnumerator`  
(might be a BCL convention)
