### ISSUE TITLE
.NET Core fails XML validation while .NET Framework succeeds

### ISSUE THREAD

**Issue by DSBRBrasil** [dotnet/corefx#37104]
Hi,
Why, I don't  validate a document using .net standard 2.0? I get that's message: Type not declared
That's my code:
```
 var xDoc = XDocument.Parse("<consStatServ versao=\"4.00\" xmlns=\"http://www.portalfiscal.inf.br/nfe\"><tpAmb>2</tpAmb><cUF>29</cUF><xServ>STATUS</xServ></consStatServ>");
   var xss = new XmlSchemaSet();
   xss.Add("http://www.portalfiscal.inf.br/nfe", @"D:\Schemas\consStatServ_v4.00.xsd");
   //Validar Xml
   xDoc.Validate(xss, (sender, args) =>
            {
                throw new FalhaValidacaoSchemaException(args.Message);

            });
```

**Comment by terrajobst** [comment]
I can reproduce this issue. On .NET Framework the code works, but on .NET Core it fails. A full repro is [here](https://github.com/terrajobst/corefx-issue37104). You can change the target framework in the project file to see the difference in behavior.

@buyaa-n, @krwq could one of you take a look and check this isn't a regression?

**Comment by krwq** [comment]
I suspect the issue is that https://source.dot.net/#System.Private.Xml/System/Xml/Core/XmlReaderSettings.cs,654 is not respecting resolver setting set previously - it should be using XmlUrlResolver or at minimum respect setting from XmlReaderSettings (which I have just validated it isn't) but not 100% sure without debugging.

**Comment by vcsjones** [comment]
This can be fixed one of two ways. You can either allow the default resolver by default using the `AppContext` switch:

```csharp
AppContext.SetSwitch("Switch.System.Xml.AllowDefaultResolver", true);
```

or explicitly configure the `XmlSchemaSet` to use the `XmlUrlResolver`:

```csharp
cfg.Schemas.XmlResolver = new XmlUrlResolver();
```

This appears to be related to this [known behavior](https://github.com/dotnet/corefx/wiki/ApiCompat#systemxmlschema).

> at minimum respect setting from XmlReaderSettings (which I have just validated it isn't)

I observed that behavior as well. Setting the `XmlUrlResolver` on `XmlReaderSettings` instead of `XmlSchemaSet` does not address the behavior.

Aside:

I suspect the change in behavior regarding the `XmlUrlResolver` is related to security since a number of documented security issues exist around `XInclude`; it would be nice if there was more documentation on this change (If there is I couldn't find it). At the very least a clear exception should be thrown, such as was observed in #31390.

**Comment by krwq** [comment]
yes, I believe we should throw an exception or at least report it to validator callback, so will leave the issue open.

I initially set resolver only on settings but not on the .Schemas, since this is not unusual scenario and this or similar issue is coming back every couple of months I think we should fix it for 3.0 (validation error + docs update) but if we don't have enough time for the fix it's ok move it to the next release.

**Comment by buyaa-n** [comment]
There is 2 steps before schema validation:

1. Adding schema to schema set: `cfg.Schemas.Add(null, schema);` where the schea is loaded and parsed, also included schemas loaded and parsed on this step. The error we want to show could be thrown here, but seems we should ignore unsuccessfully loaded schemas included, from ShemaSet.Add() method documenation:
![image](https://user-images.githubusercontent.com/45579687/57092310-fb2b8f00-6cbf-11e9-84f7-c8e104990628.png)

2. Create reader step where the xml will be read and loaded schemas will be applied: `XmlReader.Create(new StringReader(stringXml), cfg);` where the exception in question is thrown: `Type 'http://www.portalfiscal.inf.br/nfe:TConsStatServ' is not declared.` For me this message is not that wrong as the type was not exist within shema set, becasue it was not loaded in step 1. But we cannot change this error message with `Resolving of external URIs was prohibited` directly because the type might haven't declared even if all included shemas loaded successfully.

So the question is how we want to solve this:

1. Throw on step 1 with `Resolving of external URIs was prohibited` 
2. Or keep exception messages thrown in step 1 and show them as possible issue: `Type 'http://www.portalfiscal.inf.br/nfe:TConsStatServ' is not declared. Possible cause: Cannot resolve the 'schemaLocation' attribute. Resolving of external URIs was prohibited.` 
3. Or keep track of all errors for all types/elements from step 1 to show more meaningful error message on step 2 (this will be more costly) 
4. Or just leave it as is

**Comment by DSBRBrasil** [comment]
Hi,
I did can do works it, this way: 
```
private void ValidateSchema(NFe entity)
        {
            var cfg = new XmlReaderSettings {ValidationType = ValidationType.Schema};
            //List XSD files
            var list = GetListXsdFiles();
            list.ForEach(n => { cfg.Schemas.Add(null, Path.Combine(pathSchema, n)); });
            cfg.ValidationEventHandler += ValidationEventHandler;
            var xml = Utils.ClassToXmlString(entity);
            var reader = XmlReader.Create(new StringReader(xml), cfg);
            var document = new XmlDocument();
            document.Load(reader);
            document.Validate(ValidationEventHandler);
        }
private List<string>GetListXsdFiles() {
 var list = new List<string>();
            list.Add("enviNFe_v4.00.xsd");
            list.Add("leiauteNFe_v4.00.xsd");
            list.Add("tiposBasico_v4.00.xsd");
            list.Add("nfe_v4.00.xsd");
            list.Add("xmldsig-core-schema_v1.01.xsd");
            return list;
}
```
 I listed all files schemas names, thats  worked it for me.

Thank you guys !
