### ISSUE TITLE
Sporadic crash in System.Linq.Expressions on OSX

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3712]
While @janvorli and @ellismg investigate, we'll disable System.Linq.Expressions.Tests in the lab in order to hopefully get a clean run.

**Comment by janvorli** [comment]
@ellismg, after my change #1715 goes in, the test should no longer crash with `terminating with uncaught exception of type PAL_SEHException` message, but rather dump the specific unhandled exception.

**Comment by janvorli** [comment]
So the change  #1715 didn't fix the problem. I am able to repro it. I am looking into it.

**Comment by janvorli** [comment]
I will send a PR for a fix soon. This issue was a collision between hardware exception handling and activation injection on OSX where both were trying to create a helper frame and modify a thread context of the same thread at the same time.
@joshfree, since this issue came in on Sep 23 with my OSX activation changes, we will need to put the fix to beta 8.

**Comment by joshfree** [comment]
Thanks @janvorli.  To confirm, https://github.com/janvorli/coreclr/commit/278285afb2934d14ba12e68052b387fc29ef2158 is the fix for this active issue?

**Comment by janvorli** [comment]
@joshfree right, that's the fix.

**Comment by janvorli** [comment]
@ellismg, @stephentoub - the issue was fixed in the coreclr repo by https://github.com/dotnet/coreclr/pull/1720. I have verified that the System.Linq.Expressions tests now pass (I was able to repro the issue in about 9 out of 10 runs before).
