### ISSUE TITLE
Inconsistent versioning

### ISSUE THREAD

**Issue by manu-silicon** [dotnet/corefx#3716]
When you build the CoreFX assemblies and you put them altogether, you realize that there are some inconsistent version number. For example System.Console.dll requires System.Runtime version 4.0.20 but System.Runtime is version 4.0.21.

Ideally it would be nice if all the generated assemblies were consistent with respect to the version.

**Comment by weshaggard** [comment]
@manu-silicon this is intentional because we want our libraries to reference the lowest version they can work with in their dependencies. At runtime as long as you have a version of the library that is at or higher then the one requested things will unify up and work as expected. 

I'm going to close this issue because I don't think there is any action to take but please feel free to ask follow-up questions.

**Comment by manu-silicon** [comment]
It does make sense, but I'm having an issue where I compiled assemblies against CoreCLR assemblies and then try to run them it doesn't do that, it still looks for the lower version even if I provided the high version. I'll look for a reproducible sample.
