### ISSUE TITLE
Is TimeZoneInfo.FindSystemTimeZoneById special-casing for UTC correct on Win32?

### ISSUE THREAD

**Issue by IanKemp** [dotnet/corefx#37173]
[This Stack Overflow question](https://stackoverflow.com/questions/55845466/why-do-timezoneinfo-findsystemtimezonebyidutc-and-timezoneinfo-getsystemtime) asks why `FindSystemTimeZoneById` returns a different result to `GetSystemTimeZones()` for UTC specifically.

After digging a bit, I found that the culprit [is these lines](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/TimeZoneInfo.Win32.cs#L327):

```csharp
// Special case for Utc as it will not exist in the dictionary with the rest
// of the system time zones.  There is no need to do this check for Local.Id
// since Local is a real time zone that exists in the dictionary cache
if (string.Equals(id, UtcId, StringComparison.OrdinalIgnoreCase))
{
    return Utc;
}
```

But on my Windows 10 build 1803 computer (and presumably the question asker's), the above comment is false - there is indeed a "UTC" time zone defined under `HKCU\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Time Zones`.

The end result is that there are effectively **two** UTC time zones: [a constant one created by `TimeZoneInfo` itself](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/TimeZoneInfo.cs#L55), and the one in the Windows registry. This seems at best confusing and at worst incorrect - what should the behaviour be here?

Note: this occurs in both Core and Framework.

**Comment by bartonjs** [comment]
cc @tarekgh

**Comment by tarekgh** [comment]
@IanKemp this code was written long ago and during that time the assumption is Utc was not enumerated on the machine and will not be stored in the local dictionary. I agree this is not the case now. Although I am not seeing this can cause a real problem here as both Utc created object will behave correctly, but I think it would be better to fix that and ensure we use one Utc object. We'll still need to keep the check you pointed at in the code snippet for the perf sake. We should fix the issue when trying to store the Utc to the dictionary.

**Comment by tarekgh** [comment]
@bartonjs I marked this issue for 3.0 but it can be moved to the future milestone too.

**Comment by maryamariyan** [comment]
@IanKemp are you interested in creating a PR for this?

**Comment by tarekgh** [comment]
@maryamariyan I am going to have a PR soon for this.
