### ISSUE TITLE
Change how the Arm intrinsics are exposed

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#37199]
## Overview

Based on prior review, it was determined that the ARM64 and ARM32 intrinsics should be exposed independently due to the architectural differences that exist. However, after more discussion, it is believed we can simplify this split to allow more code to be shared, where applicable.

We should also take into consideration that ARM exposes their CPU feature detection in a drastically different way from x86. For example, it can only be accessed from Kernel mode; and so most OS expose a call through which you can determine which features are available. Additionally, they tend to use multiple bits for various features, rather than a single bit per ISA.

### Initial Design

The initial design was such that we would have two namespaces each with their respective ISAs exposed. Intrinsics that supported all 10 initial primitive types would be exposed as generic.

```csharp
namespace System.Runtime.Intrinsics.Arm.Arm32
{
    public static class Base
    {
        public static bool IsSupported { get; }

        // Intrinsics that exist on all ARM32 chips
    }

    public static class <Isa>
    {
        public static bool IsSupported { get; }

        // Intrinsics that exist on ARM32 chips with <Isa>
    }
}

namespace System.Runtime.Intrinsics.Arm.Arm64
{
    public static class Base
    {
        public static bool IsSupported { get; }

        // Intrinsics that exist on all ARM64 chips
    }

    public static class Simd
    {
        public static bool IsSupported { get; }

        // Intrinsics that exist on ARM64 chips with AdvSimd == 0b0000
    }
}
```

### Update after x86 Work

While working on the x86 intrinsics, we made several design decisions that were later weighed and decided to be taken for Arm as well. We also decided to make a few changes to try and improve general usage.

The primary changes included moving the classes into single namespace (differentiating with a prefix), exploding the types to no longer be generic, and following a class hierarchy for hierarchical ISAs.

This was done with consideration for future expansion, that multiple architectures would be simultaneously imported, and to make a clear distinction of the ISA to underlying CPU checks for consistency.

```csharp
namespace System.Runtime.Intrinsics.Arm
{
    public abstract class A32Base
    {
        public static bool IsSupported { get; }

        // Intrinsics that exist on all ARM32 chips
    }

    public abstract class A32<Isa>
    {
        public static bool IsSupported { get; }

        // Intrinsics that exist on ARM32 chips with <Isa>
    }

    public abstract class A64Base
    {
        public static bool IsSupported { get; }

        // Intrinsics that exist on all ARM64 chips
    }

    public abstract class A64AdvSimd0
    {
        public static bool IsSupported { get; }

        // Intrinsics that exist on ARM64 chips with AdvSimd == 0b0000
    }
}
```

### Proposed Changes

However, after further discussion with developer's from ARM, it is believed we can improve this still.
We would again be building off changes that were made for x86 but also trying to make the APIs more user friendly and taking into account how they are commonly used today (such as in C/C++).

Namely, this is taking advantage of the fact that, even though ARM64 is a redesign and distinct architecture (rather than an architectural extension like `x64` vs `x86`), it is still a logical extension in a lot of ways.

For example, ARM32 and ARM64 both support essentially the same `AdvSimd` instructions (`NEON on ARM32` and `AdvSIMD on ARM64`) and even though Arm64 may support some additional types it still supports much of the same baseline from a higher level perspective (the operations, the parameters, the return types, and the behaviors).

The ISA names could then likely be based on the "feature names" that ARM has given them in the C/C++ headers as they are what most users would be familiar with them as and should be largely stable for back-compat reasons: https://developer.arm.com/docs/101028/latest/5-feature-test-macros

```csharp
namespace System.Runtime.Intrinsics.Arm
{
    public static class ArmBase
    {
        public static bool IsSupported { get; }

        // Intrinsics that exist on all ARM chips

        public abstract class Arm32
        {
            public static bool IsSupported { get; }

            // Intrinsics that exist only on ARM32 chips
        }


        public abstract class Arm64
        {
            public static bool IsSupported { get; }

            // Intrinsics that exist only on ARM64 chips
        }
    }

    public static class Neon
    {
        public static bool IsSupported { get; }

        // Intrinsics that exist on ARM chips with AdvSimd baseline support

        public abstract class Arm32
        {
            public static bool IsSupported { get; }

            // Intrinsics that exist only on ARM32 chips with AdvSimd baseline support
        }


        public abstract class Arm64
        {
            public static bool IsSupported { get; }

            // Intrinsics that exist only on ARM64 chips with AdvSimd baseline support
        }
    }
}
```

**Comment by tannergooding** [comment]
CC. @CarolEidt, @terrajobst, @TamarChristinaArm

**Comment by tannergooding** [comment]
Before marking this `ready-for-review`, I would like to try and get a more exact definition of what ISAs would be exposed (including their names), what the split between A32/A64 is, and to try and get some numbers on how much duplication vs non-duplication there is...

**Comment by TamarChristinaArm** [comment]
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿The following is a list based on the intrinsics we defined for C/C++ which I can see being useful for inclusion in the coreclr. It's excluding certain intrinsics that we need in C but not so much here such as the type conversion ones (`vreinterpret`) ones. It does however include loads since I did not split out the complex structural loads (for which we would require intrinsics) and the simple loads (which are handled by `Unsafe.Create`).

That is to say, take the numbers as mostly a rough guide.

The breakdown looks as follows

| Feature group         	| A32/A64 	| A64  	| Grand Total 	|
|-----------------------	|---------	|------	|-------------	|
| AES                   	| 5       	| 1    	| 6           	|
| Armv8.2-A & FP & FP16 	| 24      	|      	| 24          	|
| Base                  	| 219     	| 25   	| 244         	|
| ComplexNumber         	| 24      	| 6    	| 30          	|
| ComplexNumber & FP16  	| 28      	|      	| 28          	|
| CRC                   	| 8       	|      	| 8           	|
| DotProduct            	| 8       	| 4    	| 12          	|
| FP                    	| 4       	| 6    	| 10          	|
| FP & FP16             	| 157     	| 148  	| 305         	|
| RDMA                  	|         	| 36   	| 36          	|
| SHA2                  	| 10      	| 4    	| 14          	|
| SHA3                  	|         	| 18   	| 18          	|
| SIMD                  	| 1611    	| 1025 	| 2636        	|
| SIMD & FP16           	| 174     	| 237  	| 411         	|
| SM4                   	|         	| 9    	| 9           	|
| Grand Total           	| 2272    	| 1519 	| 3791        	|

So there are currently `0` `A32` only intrinsics we found useful to include, `2272` shared `A32 & A64` intrinsics and `1519` `A64` only intrinsics. Plenty of these are just overloads! But I expect the same number of overloads in CoreCLR if all the intrinsics are defined.

So the duplication amount if we were to have feature parity with the neon intrinsics defined by [Arm compilers](https://developer.arm.com/architectures/instruction-sets/simd-isas/neon/intrinsics) is about `2000` intrinsics. or roughly `60%`.

As for which `ISA`s, one thing that is a bit different on Arm architectures is that our architecture revisions aren't fixed. We routinely backport new instructions as optional extensions to older architecture revisions. 

Which is why I suggest the ISA's here to be something like a feature group instead of actual ISAs or architecture revisions.

Now for the actual namespace, there are a few things to consider. On `Armv8` the `SIMD` and `FP` units are optional (See section A1.5 of the [ArmARM](https://developer.arm.com/docs/ddi0487/latest/arm-architecture-reference-manual-armv8-for-armv8-a-architecture-profile)).  On AArch64 we strongly encourage the inclusion of both `SIMD` and `FP`, to the point that we didn't define a `soft-float` ABI for AArch64 and general advice is not to expect Linux to work without them. In all likelihood the implementations that the CoreClr will be running on will all have it, but that's something I'll defer to you guys.

Aside from this, you also have `FP16` which is again optional, but requires `FP`. There is one inaccuracy in the numbers above where the `SIMD + FP` cases have been merged in the `SIMD + FP16` one. Or rather, my query wasn't specific enough to be able to distinguish between the two.  But they are there!

So it seems to me that a good way to organize these would be the following scheme

| Namespace mappings    	| Sub-namespace    	|
|-----------------------	|------------------	|
| AES                   	|               	|
| Armv8_2A              	| FP16             	|
| Base                  	|               	|
| Base                  	| FP         	|
| Base                  	| FP16         	|
| ComplexNumber         	|               	|
| ComplexNumber         	| FP16          	|
| CRC                   	|               	|
| DotProduct            	|               	|
| RDMA                  	|               	|
| SHA2                  	|               	|
| SHA3                  	|               	|
| SIMD                  	|               	|
| SIMD                  	| FP             	|
| SIMD                  	| FP16          	|
| SM4                   	|               	|

where each of these have `A64 & A32` sub-namespaces if required. I'll defer the exact naming of these to you guys but these are roughly the split-up I foresee.

The `Armv8_XX` ones are ones for which we have no name as they are mandatory at the architecture revision.

**Comment by tannergooding** [comment]
> We routinely backport new instructions as optional extensions to older architecture revisions.

I think this should be fine as long as there is a single and consistent way to check for a given extension. It might be something that needs further thought if the instructions that are backported aren't consistent with what were exposed upstream...

> In all likelihood the implementations that the CoreClr will be running on will all have it, but that's something I'll defer to you guys.

I believe we require the FP extension, but I don't think we require the SIMD extension. Someone on the JIT team would know better.

**Comment by tannergooding** [comment]
The key points for the classes and methods we expose are:
* Each class has a single `IsSupported` check so if that check returns `true`, all methods in that class must work (otherwise, we need to split them into groups where that condition holds).
  * That is, we should never end up in a situation where a user can do `if (Isa.IsSupported) { Isa.Method(); }` and then have that fail because the emitted instruction was not actually supported.
* We can't make breaking changes to the already exposed surface area, so we should try to make this logical the first time around if possible.
  * That is, if we ship `Isa` and then later only part of that is backported to be available on an older architecture, we can't move some of the methods out. We would need to make a new class with a separate `IsSupported` check.

This ultimately requires that the hardware have separate hardware checks for each logical "set" of instructions (or ISA).
Those checks can be hierarchical in nature (e.g. on x86 `Sse3` requires `Sse2` which requires `Sse`) or they can be standalone (e.g. on x86 `Bmi1` does not techically require any other ISA; even if all current chips will also provide `Avx`; so we expose it without a dependency on `Avx`).

**Comment by TamarChristinaArm** [comment]
> This ultimately requires that the hardware have separate hardware checks for each logical "set" of instructions (or ISA).

Agreed, each of the `Feature group` above have a unique set of hardware bits that would identify them.

**Comment by tannergooding** [comment]
That makes sense to me.

We would then need to decide if one were to do (as a minimal example):
```csharp
public abstract class Armv8_2
{
}

public abstract class Armv8_2Fp16 // Could inherit from Armv8_2
{
}

public abstract class AdvSimd
{
}

public abstract class AdvSimdFp16 : Armv8_2Fp16 // Could also inherit from AdvSimd, but not both
{
}

public abstract class CompNum
{
}

public abstract class CompNumFp16 : Armv8_2Fp16 // Could also inherit from CompNum, but not both
{
}
```

or if you were to do:
```csharp
public abstract class Armv8_2
{
    public abstract class Fp16
    {
    }
}

public abstract class AdvSimd
{
    public abstract class Fp16 : Armv8_2.Fp16
    {
    }
}

public abstract class CompNum
{
    public abstract class Fp16 : Armv8_2.Fp16
    {
    }
}
```

I think I currently have a preference towards the latter as it looks nicer to me. I think it also more clearly conveys that the nested `Fp16` class is an optional part of the parent class, but that it is an extension of the inherited class.

**Comment by TamarChristinaArm** [comment]
I have a preference towards the latter case as well,
`CompNum.Fp16.Arm64.Method()` is indeed a bit of a downside, but I do think it's a bit clearer than the option 1 which would rely on CamelCase to indicate what the extension is.

It's too bad you can't have overlapping `namespace` and `class` names.

**Comment by tannergooding** [comment]
This was reviewed and approved over e-mail. I've started the work on changing the surface area to match this here: https://github.com/dotnet/coreclr/pull/25508, but it won't get merged until after dotnet/master begins targeting .NET 5.

**Comment by tannergooding** [comment]
This was resolved in https://github.com/dotnet/coreclr/pull/25508
