### ISSUE TITLE
AzDO test runs should publish testResults as a test artifact

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#37205]
Looking at other repositories, i.e. CoreClr, I can see test analytics. I quickly looked at their publish proj and I believe these properties tell helix to upload the test results: https://github.com/dotnet/coreclr/blob/master/tests/helixpublishwitharcade.proj#L158-L159.

Analytics for coreclr tests: https://dnceng.visualstudio.com/public/_test/analytics?buildDefinitionId=228

cc @safern @danmosemsft @MattGal

**Comment by safern** [comment]
Yes, in fact we started publishing tests results like that when we moved to AzDevOps, however they don't yet have the "flaky" tests "retry" feature, so it was impossible to get a green build and we were getting false positives. So we have 2 options here:
 
1. wait until that feature is finished. 
2. enable publishing test results to azure devops and fail the build based on Mission Control test results which considers pass on retry. 

I would go for option 1 because having test results on the test tab could confuse people on why the build is green but the test tab and `Github Checks` tab show a test failure. If we need to wait for that feature, I think we will probably have no time to do this for 3.0 because the feature is not yet ready.

@alexperovich do you have an ETA when that will be ready?

**Comment by ViktorHofer** [comment]
Thanks for the info. Sounds like both helix and AzDO are involved in adding the test retry feature. Is @alexperovich responsible for implementing that feature on the helix side and also the point of contact for the AzDO team?

**Comment by safern** [comment]
> Is @alexperovich responsible for implementing that feature on the helix side and also the point of contact for the AzDO team?

Helix is ready from last time I spoke with @alexperovich however we're still waiting on AzDO feature.

**Comment by alexperovich** [comment]
The AzDO feature is available now. There is a "Flaky" button you can click on the test results page to mark a test as flaky.
![Capture_LI](https://user-images.githubusercontent.com/10565410/56922641-8b2dc680-6a7d-11e9-8fb6-8d9e7ec1e0dd.jpg)

**Comment by ViktorHofer** [comment]
Does that mean we can start publishing test results again to AzDO and need to mark flaky tests manually so that they are retried?

**Comment by alexperovich** [comment]
Yea, they won't be retried though. The azure devops thing will just flag them as "failed but unimportant". I haven't had a chance to mess with it though, so I don't know how they will look.

**Comment by ViktorHofer** [comment]
@danmosemsft is that sufficient for our runs or do we need them to be retried?

**Comment by ViktorHofer** [comment]
I don't think we have any alternatives at the moment. Changing to the Test Explorer would also guard us against MC outages, like the one that we just had over the weekend.
