### ISSUE TITLE
Stopwatch is off by a factor of 100

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/corefx#37231]
I'm seeing Stopwatch.Start/Stopwatch.Stop/Stopwatch.Elapsed.TotalMilliseconds being off by a factor of 100 on WSL with the 3.0.0-preview6-27626-01 version of Microsoft.NETCore.App.

Things that should take 225 ms (and diffing DateTime.Now reports them as such) get measured as 2.28 ms with Stopwatch.

**Comment by MichalStrehovsky** [comment]
Cc @tannergooding since there were p/invoke changes around this recently

**Comment by tannergooding** [comment]
Is this only on Linux?

**Comment by tannergooding** [comment]
Ok, I see where the problem is, but I'm concerned there might be a bug on OSX as well....

On Windows, we always call `QueryPerformanceFrequency` which gives us back a `ulong` that contains the `counts per second`. We have defined that a .NET tick is `100 nanoseconds` so we compute the tick frequency as `(double)TicksPerSecond / Frequency` (effectively `.NET Ticks Per Second` / `System Ticks Per Second`).

On newer MacOS we call `mach_timebase_info` which gives you back a numerator and denominator that can be used to scale something to nanoseconds. However, rather than scaling out the result and then dividing, we are first dividing the numerator by the denominator and then multiplying that by `SecondsToNanoSeconds` (which is effectively `NanosecondsPerSecond`).
* The correct thing to do here would be do `return (SecondsToNanoSeconds * (uint64_t)(mtid.denom)) / (uint64_t)(mtid.numer)`. This helps prevent issues where `denom` and `numer` are sufficiently close to eachother and would round to the nearest integral value.

On older MacOS and on Unix, we were previously just returning `SecondsToNanoSeconds`. However, that was incorrect given that nothing guarantees the result of `clock_getres(CLOCK_MONOTONIC)`. So, I updated the code to call it `clock_getres` which gives you a `sec` and `nsec` field that you can use to compute the nanoseconds per tick. The issue is that we are then scaling `nanosecondsPerTick` by `SecondsPerNanoSecond`.
* The correct thing to do here would be to do `return SecondsPerNanoSecond / (((uint64_t)(ts.tv_sec) * SecondsToNanoSeconds) + (uint64_t)(ts.tv_nsec))` (effectively `Nanoseconds per Second` / `Nanoseconds per Tick`), which gives us the number of `Ticks Per Second`.
