### ISSUE TITLE
System.Net.Sockets tests will behave differently when running in an elevated (admin) context

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#3726]
```
  Discovering: System.Net.Sockets.Tests (TaskId:239)
  Discovered:  System.Net.Sockets.Tests (TaskId:239)
  Starting:    System.Net.Sockets.Tests (TaskId:239)
     System.Net.Sockets.Tests.CreateSocket.Ctor_Failure(addressFamily: InterNetwork, socketType: Raw, protocolType: Tcp) [FAIL] (TaskId:239)
        Assert.Throws() Failure (TaskId:239)
        Expected: typeof(System.Net.Sockets.SocketException) (TaskId:239)
        Actual:   (No exception was thrown) (TaskId:239)
        Stack Trace: (TaskId:239)
D:\git\corefx\packages\Microsoft.DotNet
```

I'm hitting this failure consistently on my local machine any ideas of what is happening?

**Comment by davidsh** [comment]
cc: @CIPop @pgavlin

**Comment by CIPop** [comment]
@weshaggard Are you running them in an elevated prompt?

The following combination is expected to fail if you don't have full permissions but it'll probably work if you are an Admin:
`       new object[] { AddressFamily.InterNetwork, SocketType.Raw, ProtocolType.Tcp },`

**Comment by davidsh** [comment]
>Are you running them in an elevated prompt?

Is this a new requirement for our MSBuild window for CoreFx?

Do the CI machines always run in elevated mode?

**Comment by CIPop** [comment]
> Is this a new requirement for our MSBuild window for CoreFx?
@davidsh No, actually the opposite although I didn't try to repro yet.

**Comment by weshaggard** [comment]
I am running from an elevated prompt. We should split these tests up correctly so we don't fail in different environments like this.

**Comment by CIPop** [comment]
/cc @pgavlin 

I disagree with splitting the tests: having all combinations for complicated stacks such as networking is out of scope for these tests. I think that tests should be executed the same way as the CI system does.

My proposal is to add a new Capability check within `Capability.Sockets.cs`. This should ensure that the test is not running in an elevated prompt. If it does, it should fail with a clear message instead of the assert. Note that adding these complicated Capability tests will complicate sharing test code across other platforms such as NetNative.

**Comment by davidsh** [comment]
+1
>I disagree with splitting the tests: having all combinations for complicated stacks such as networking is out of scope for these tests. I think that tests should be executed the same way as the CI system does.

My proposal is to add a new Capability check within  Capability.Sockets.cs . This should ensure that the test is not running in an elevated prompt. If it does, it should fail with a clear message instead of the assert. Note that adding these complicated Capability tests will complicate sharing test code across other platforms such as NetNative.

**Comment by weshaggard** [comment]
This is interesting as it is the opposite issue of other cases like https://github.com/dotnet/corefx/issues/3134 which require admin access to work. At a high level I agree that we should figure out a way to make the dev flow and the CI/official build flow be consistent but that to me doesn't mean this test should fail when run in a different context. 

I do not believe we should make this test fail differently when run as admin, it should either be filtered out at the test harness level via some capabilities or via runtime and either skipped or the expected behavior updated. Regardless of how our CI or dev workflow handles this customers can run this code in either context and we should have the appropriate test coverage for both scenarios.

**Comment by weshaggard** [comment]
I keep hitting these failing tests so I'm disabling these cases until they can correctly be addressed. 

I had to disable some test cases for RAW/TCP/UDP in both test methods DualMode_Failure and Ctor_Failure as they actually don't fail in creation when running elevated.

In fact the DualMode_Failure tests fail by hitting this assert (
https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L108) in elevated mode which I think is an actual bug that needs to be fixed.
