### ISSUE TITLE
HttpClient header date parsing fixes should be backported to Core 2.x

### ISSUE THREAD

**Issue by IanKemp** [dotnet/corefx#37293]
Initial issue: #36992
PR containing the fixes: #28843

I have tested against .NET Core SDK 2.2.106 and these fixes are not present - I believe they should be backported. Is it intentional that they are not, or will this work only be done after 3.0.0 has shipped, or...?

**Comment by davidsh** [comment]
@karelz

**Comment by karelz** [comment]
We backport only changes that are highly impactful on existing customers. Otherwise we would turn servicing branches into another master branch with less stability.
If there is need for the changes in 2.1/2.2 servicing, please tell us more details - what is the situation? How impactful is it? Did you consider any workarounds?

**Comment by karelz** [comment]
Ah, I lost context for this one, reopening (sorry for the closing).

Either way, the question should not be "Why is this not ported", but rather should be "Why this should be ported"?

**Comment by karelz** [comment]
@IanKemp any update on why this is important and how it is impacting serious number of customers?

**Comment by karelz** [comment]
Looks like there is no data for porting it to 2.2.x, closing. We can reconsider when more data appears.
