### ISSUE TITLE
Change System.Numerics.Vector<T>'s unsafe constructors' access level to public.

### ISSUE THREAD

**Issue by ReverseBlade** [dotnet/corefx#3741]
Currently Vector<T>'s constructors that accept a pointer are marked as private, e.g:
private unsafe Vector(void* dataPointer, int offset)

Please consider making them public. Because at some point we might have only the pointers themselves in our own code but rather than arrays. Recreating an array from these pointers is costly. So allow us to use this constructor directly as it is.

**Comment by redknightlois** [comment]
Agree!! Pretty common issue when dealing with numerical methods.

**Comment by mellinoe** [comment]
This is definitely something we've wanted to do, along with increasing usability with unsafe code in general. We will still need to put this through our regular design process, but I can take care of creating a proposal and walking it through that process.

**Comment by aL3891** [comment]
Any progress on this? i'd really like to be able to do this also :) 
Maybe it doesnt have to be a void pointer but a T pointer instead? (if void* is a problem for cls compliance)

**Comment by ReverseBlade** [comment]
T* is not supported by C# unfortunately. So it has to be void* .

**Comment by aL3891** [comment]
ah.. how about a byte* and size perhaps?

**Comment by mellinoe** [comment]
Unfortunately I've been busy with other work and we have slowed down over the holiday season, so I don't think we will be able to get this through our review process until January. I'll post an update when that moves forward.

As for the signature, it will most likely remain void* just due to the nature of the type. Generic pointers aren't supported, and a byte* would be a bit awkward if you had some other type of pointer. The signature will most likely just be as it is in the original post:

```
private unsafe Vector(void* dataPointer, int offset)
```

The "size" of the vector is implicit from the type of vector you are creating.

**Comment by aL3891** [comment]
sure, i was just thinking if the cls compliance was a problem, perhaps it isnt :)

**Comment by mellinoe** [comment]
We decided to go a different route with this. You should be able to use the `Unsafe.Read(void*)` method in the System.Runtime.CompilerServices.Unsafe package for this purpose. That package is also useful for a variety of other low-level pointer-based Vector manipulations. I'm going to close this issue now; please re-open or file a new issue if you think there is something that is not addressed by the current state of things.

**Comment by benaadams** [comment]
@mellinoe working like a charm https://github.com/aspnet/KestrelHttpServer/pull/811 and https://github.com/aspnet/KestrelHttpServer/pull/812

**Comment by aL3891** [comment]
New approach looks great imo!
