### ISSUE TITLE
[OnSerializing] attribute callback not triggering when using System.Text.Json

### ISSUE THREAD

**Issue by Eilon** [dotnet/corefx#37503]
_From @alextech on Tuesday, 07 May 2019 17:52:35_

`[OnSerializing]` Attribute is not triggered when using System.Text.Json . The .Net Core Preview 5 blog post suggests moving from NewtonSoft serializer to builtin one, but does not mention any migration paths, so I assume they should work the same way. Is this the case?

### To Reproduce
In object to be serialized, such as output of a REST API controller, mark a method with `[OnSerializing]` attribute.

### Expected behavior
Marked method executes before output to page

### Additional context
dotnet --info
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

_Copied from original issue: aspnet/AspNetCore#10047_

**Comment by ahsonkhan** [comment]
cc @steveharter

**Comment by ahsonkhan** [comment]
Related to and depends on https://github.com/dotnet/corefx/issues/36639.

**Comment by jkotas** [comment]
`OnSerializing` attribute is part of the binary serialization contract. We are trying hard to deprecate binary serialization for security and maintainability reasons.

We should not be breathing a new life into binary serialization by supporting it in System.Text.Json.

This issue should be won't fixed.

cc @GrabYourPitchforks

**Comment by joshfree** [comment]
Closing issue as this is tracked by https://github.com/dotnet/corefx/issues/36639

**Comment by GrabYourPitchforks** [comment]
My understanding is that the `System.Runtime.Serialization` namespace contains members related both specifically to dangerous serialization (`BinaryFormatter`, `ObjectManager`, etc.) and to serialization in general (`DataMemberAttribute`, `IgnoreDataMemberAttribute`, etc.).

If we deprecate the existing serialization namespace all-up we may want to consider moving the more general-purpose attributes and types into a separate namespace so that XML, JSON, and friends can take advantage of them.
