### ISSUE TITLE
double.ToString fixed-point formatting does unexpected rounding

### ISSUE THREAD

**Issue by slozier** [dotnet/corefx#37524]
`(0.0046).ToString("F2")` returns `0.01` instead of the expected `0.00`. @tannergooding

**Comment by tannergooding** [comment]
Taking a look.

**Comment by tannergooding** [comment]
The root issue is double-rounding. Both Dragon4/Grisu3 will take rounding into account when generating the digit stream. `NumberToString` will then try to round that number again according to the requested number of digits.

In a case where the first significant is directly after the requested number of digits, if it is a 4 and the following digit would cause that to round, we will cause the displayed digit to be 1 rather than 0.

The simplest fix is to just exhaust the digit stream in this case, which avoids the rounding done by Dragon4. It may also be possible to elide the rounding done by `NumberToString` for floating-point buffers, but that requires more thought/testing...

**Comment by danmosemsft** [comment]
@slozier thank you for the report, this meant we were able to fix this before it got to customers in release. We would welcome reports of any other similar defects you might find, with this fix in place. You can either try it in daily builds, or wait for Preview 6.
