### ISSUE TITLE
Task.ContinueWith not called when using Task.Run on an async action

### ISSUE THREAD

**Issue by SixFive7** [dotnet/corefx#37602]
We've reduced the problem to the following few lines. Fails both in .net core 2.2 and .Net Framework 4.7.2 (using C# language level 7.3). On Windows 10 Pro 64bit (1809).

**Code:**
```
static async Task Main(string[] args)
{
    Console.WriteLine("Hello World!");
    Foo(async () => throw new Exception("Oops"));
    Console.ReadLine();
}

static void Foo(Action action)
{
    Task.Run(action).ContinueWith(t =>
    {
       Console.WriteLine(t.Exception);
    }, TaskContinuationOptions.OnlyOnFaulted);
}
```
**Expected behavior:**
The task fails, and continues by writing the exception to the console. Then the application resumes normally.

**Actual behavior:**
The task fails and immediately crashes with an Unhandled Exception:

```
Unhandled Exception: System.Exception: Oops
   at ConsoleApp1.Program.<>c.<<Main>b__0_0>d.MoveNext() in D:\Projects\C#\ConsoleApp1\ConsoleApp1\Program.cs:line 12
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
If we remove the ```async``` modifier on line 4 everything works as expected. If we change ```Action``` on line 8 to ```Func<Task>``` again everything works as expected.

**Comment by kevingosse** [comment]
I don't know if this behavior is documented somewhere, but this is by design. 

Since `Foo` expects an `Action`, your anonymous function is compiled as an async void method. Because there is no way to observe an unhandled exception thrown in an async void method, that exception is propagated to the synchronization context if any, and to the threadpool if none. Throwing an unhandled exception in the threadpool crashes the application, so the `ContinueWith` (or anything else) cannot run.

https://github.com/dotnet/coreclr/blob/9773db1e7b1acb3ec75c9cc0e36bd62dcbacd6d5/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs#L128-L147

**Comment by stephentoub** [comment]
Kevin is correct, this is by design.

https://devblogs.microsoft.com/pfxteam/potential-pitfalls-to-avoid-when-passing-around-async-lambdas/
