### ISSUE TITLE
Question : Why there is no System. Memory constructor with void* parameter? 

### ISSUE THREAD

**Issue by dotChris90** [dotnet/corefx#37618]
Just for curiosity. is there any special reason that System.Memory does not have a constructor which accepts pointer? the System.Span does with 2nd parameter (length of memory).

or is there a possibility to convert span to memory? not copy really reference.

**Comment by svick** [comment]
> Just for curiosity. is there any special reason that System.Memory does not have a constructor which accepts pointer?

You can create `Memory<T>` from a pointer, it's just a little more complicated. You do it by creating a class that inherits from [`MemoryManager<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.memorymanager-1?view=netcore-2.1). A trivial implementation looks like this: [`PointerMemoryManager<T>`](https://github.com/dotnet/corefx/blob/0d3caeb/src/Common/src/System/Memory/PointerMemoryManager.cs).

> or is there a possibility to convert span to memory?

That's not possible, because it might not be safe: that `Span<T>` could point to stack-allocated memory and `Memory<T>` can't work with that.

**Comment by dotChris90** [comment]
@svick thanks for this hint! I was long time searching for sth like this (even the trivial one is enough for me). ;) I will close this issue because solved my problem.
