### ISSUE TITLE
System.Data.Odbc namespace : "error CS0246: The type or namespace name..."

### ISSUE THREAD

**Issue by deokershesh** [dotnet/corefx#37626]
I need to change System.Data.Odbc namespace to MyDB.Net.Core and make appropriate MyDB related code changes. I have made changes to src/odbc folder files, Iterop.Odbc.cs, System.Data.Odbc.csproj and MatchingRefApiCompatBaseline.txt file, to change the name from System.Data.Odbc to  MyDB.Net.Core and building the entire corefx project reports 194 errors!! All of them similar to below across files.

System\Data\Odbc\Odbc32.cs(14,25): error CS0246: The type or namespace name 'Exception' could not be found (are you missing a using directive or an assembly reference?) [D:\shesh\corefx\src\System.Data.Odbc\src\System.Data.Odbc.csproj]

Any help in this regard to change the namespace would be greatly appreciated.

**Comment by deokershesh** [comment]
Any help please?

**Comment by David-Engel** [comment]
This is something we don't support. You are welcome to try making changes to the code on your own (as you are doing), but you might be hard-pressed to find someone who has gone down that road and has specific help for you.

**Comment by ajcvickers** [comment]
@David-Engel @divega Can we close this?

**Comment by divega** [comment]
I agree with what @David-Engel said above. I believe there is guidance on how to build projects from CoreFx in https://github.com/dotnet/corefx/tree/master/Documentation, but if that isn't enough, maybe the best option would be to make a copy of the System.Data.Odbc codebase into a completely independent project and do the work there so that you don't need to satisfy any build requirements from this repo.
