### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by zhongzepeng** [dotnet/corefx#37662]
Environment: docker
Version: netcore 2.2
Dmesg log:
Dotnet [20498]: segfault at 80300e05 IP 00007fc0a8513863 sp 00007fc014e2e560 error 4 in libgdiplus.so.0.0.0[7fc0a84d3000+64000]

How to catch this Exception

**Comment by zhongzepeng** [comment]
```
public static Image MakeRoundedCorners(this Image image, int radius)
{
    Bitmap Bmp = new Bitmap(image, image.Width, image.Height);
    Graphics G = Graphics.FromImage(Bmp);
    Brush brush = new System.Drawing.SolidBrush(Color.Red);
    for (int i = 0; i < 4; i++)
    {
        Point[] CornerUpLeft = new Point[3];

        CornerUpLeft[0].X = 0;
        CornerUpLeft[0].Y = 0;

        CornerUpLeft[1].X = radius;
        CornerUpLeft[1].Y = 0;

        CornerUpLeft[2].X = 0;
        CornerUpLeft[2].Y = radius;

        System.Drawing.Drawing2D.GraphicsPath pathCornerUpLeft =
            new System.Drawing.Drawing2D.GraphicsPath();

        pathCornerUpLeft.AddArc(CornerUpLeft[0].X, CornerUpLeft[0].Y,
            radius, radius, 180, 90);
        pathCornerUpLeft.AddLine(CornerUpLeft[0].X, CornerUpLeft[0].Y,
            CornerUpLeft[1].X, CornerUpLeft[1].Y);
        pathCornerUpLeft.AddLine(CornerUpLeft[0].X, CornerUpLeft[0].Y,
            CornerUpLeft[2].X, CornerUpLeft[2].Y);

        G.FillPath(brush, pathCornerUpLeft);
        pathCornerUpLeft.Dispose();

        Bmp.RotateFlip(RotateFlipType.Rotate90FlipNone);
    }
    brush.Dispose();
    G.Dispose();
    Color backColor = Bmp.GetPixel(0, 0);
    Bmp.MakeTransparent(backColor);
    return Bmp;
}
```

this code will crash the app，but i can't find other code in my project，so how to Catch Execption .It is very important .

**Comment by Clockwork-Muse** [comment]
[Seg(mentation) faults](https://en.wikipedia.org/wiki/Segmentation_fault) aren't exceptions, they're signaled from the OS, and are generally **not** something you catch (you let the OS kill your process).  If the action somehow succeeded (ie, successfully wrote to readonly memory), you've generally just corrupted state you shouldn't be touching.  If you're attempting to continue _despite_ the error, some part of your program data isn't in the state it should be, and the rest of your program behavior is unknown (could be drawing with a blue brush instead of a red one, for example).

It would be helpful if you could reduce the lines of code here, and get a minimum reproduction of the problem.  We would at least like to know what line the program crashes on.
Furthermore, just saying "Environment: Docker" is insufficient.  We need at least the OS version and runtime build number.  If you're using a published docker image, please tell us what it is.  The host environment may also be helpful.

**Comment by safern** [comment]
Thanks @zhongzepeng for opening the issue, however this is a libgdiplus issue as you can see in the error, it happened there. 

Could you please open the issue there? or please provide us with more information and I can open the issue for you.

Version of libgdiplus used.
Dockerfile or docker image information, mostly which OS version it was running on.
