### ISSUE TITLE
JsonElement.TryGetInt32 throws System.InvalidOperationException on nulls

### ISSUE THREAD

**Issue by fitdev** [dotnet/corefx#37720]
Presumably all the `JsonElement.TryGet...`s throw `System.InvalidOperationException` when encountering nulls, i.e. `{"year":null}` (and possibly in other cases as well). This is somewhat misleading, as Try APIs should not throw, but instead return false with the out variable initialized to its default value (0 for int) whenever error is encountered.

**Comment by fitdev** [comment]
Related issue is that it throws for `JsonElement.TryGetProperty` as well when the JsonElement itself is `null`. Thus, the current approach requires much more boiler plate code like `if(jsonElement.Type == JsonValueType.Object) jsonElement.TryGetProperty("foo")...`.

**Comment by ahsonkhan** [comment]
> This is somewhat misleading, as Try APIs should not throw, but instead return false with the out variable initialized to its default value (0 for int) whenever error is encountered.

I believe our guidelines for Try APIs is that true/false is only used to reflect **one** condition. Currently, the true/false is tied to whether or not the token was actually an int32 (rather than double/long/etc.). We throw for TokenType != Number. Returning false for that case would overload what true/false means. Null would fall into a similar category.

cc @bartonjs to chime in

**Comment by bartonjs** [comment]
> I believe our guidelines for Try APIs is that true/false is only used to reflect one condition.

We're working on improving the guidance around that.  Mainly it's "one recovery path".  Recovering an Int32 from the payload would fail if it's not a Number, has a decimal point (or a scientific notation `e`), or is larger than Int32.MaxValue (or smaller than MinValue), which we classified down to "not a Number, doesn't fit".

"Doesn't fit" returns false, and you can try Int64 or Double. "Not a Number" throws, because it was easily detected by looking at the TokenType value before calling the method.  So "false" only means "this is a number, but it doesn't fit in an Int32 container":

The complexity in understanding the rule comes from the majority of the Try- methods being static, so there's no state to be invalid.

Framework Design Guidelines (Cwalina, Abrams), 2nd edition, 7.5.2 (Try-Parse Pattern), p243:

> When using this pattern, it is important to define the try functionality in strict terms.  If the member fails for any reason other than the well-defined try, the member must still throw a corresponding exception.

**Comment by ahsonkhan** [comment]
This is by-design and follows the try-pattern.
