### ISSUE TITLE
Culture sv-SE sort order for strings does not handle the order of v and w correctly

### ISSUE THREAD

**Issue by osjoberg** [dotnet/corefx#37753]
I am having a problem sorting Swedish strings, characters: v and w not sorting in the correct order.

Repro:
`new[] { "wa", "va", "wb", "vb"  }.OrderBy(x => x, new CultureInfo("sv-SE").CompareInfo.GetStringComparer(CompareOptions.None))
`

Expected: va, vb, wa, wb
Actual: va, wa, vb, wb

I believe that the current order have been correct historically, however in 2006 the "Svenska Akademiens Ordlista" "officially" changed this.

As a work around I have switched to the "se-SE" culture (Sami) to work-around this.

**Comment by danmosemsft** [comment]
Is this on Windows, Linux, or macOS? 

On Unix we use libicu which uses [CLDR ](http://cldr.unicode.org/) data. On Windows I believe newer versions use CLDR data. So very likely this is an issue with the OS having not up to date CLDR data. You can verify if you try this in native code.

@tarekgh

**Comment by tarekgh** [comment]
I am seeing the problem happen on Windows. On Linux it works as expected. 

@osjoberg we'll forward the issue to Windows team but I suggest you report it to through "Feedback Hub" using Windows 10 so you can track the issue and the response. CC'ing @shawnsteele from Windows team too. 

As this is the OS issue I am closing this issue here. Feel free to reply back with any more questions. Thanks for reporting this issue.
