### ISSUE TITLE
[System.Text.Json] JsonException Path should be a JsonPath

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#37768]
This wasn't correctly captured as part of #36025, but it would be way more useful for `JsonException.Path` to be [Json Path](https://goessner.net/articles/JsonPath). This is similar to the way Newtonsoft.Json reports it's deserialization errors and is a bit more useful to identity what is problematic. Consider:

```C#
var badData = "{ \"SubModel\": [{ \"Id\": false }] }";
try
{
    // JsonConvert.DeserializeObject<TestModel>(badData);
    System.Text.Json.Serialization.JsonSerializer.Parse<TestModel>(badData);
}
catch (JsonException ex)
{
    System.Console.WriteLine(ex.Path);
}

public class TestModel
{
    public List<TestSubModel> SubModel { get; set; }
}

public class TestSubModel
{
    public int Id { get; set; }
}

Output: [console1.TestModel].SubModel.Id
```
 
The same data through Json.NET produces `SubModel[0].Id` which tells which segment of the Json payload is problematic.

**Comment by ahsonkhan** [comment]
> Output: [console1.TestModel].SubModel.Id
> Json.NET produces SubModel[0].Id

From the example, it is difficult to see why one is more useful than the other (especially since there is an indexer within the Json.NET output when we don't have an array within the payload). Can you provide additional context/example to help motivate this change (other than just precedence)?

Also, where did SubModel come from within the "json path"? The payload doesn't contain it.

**Comment by pranavkm** [comment]
> Also, where did SubModel come from within the "json path"? The payload doesn't contain it.

Updated my scenario which explains the scenario a bit better

**Comment by JamesNK** [comment]
Exception messages from the serializer can contain the type name if you want, but the path property on the JsonException should not.

Message:
`The JSON value from [console1.TestModel].SubModel.Id could not be converted to System.String.`
Path:
`SubModel.Id`

**Comment by JamesNK** [comment]
Does JsonSerializer encode path following the logic here https://goessner.net/articles/JsonPath? That is why the property is called path in Newtonsoft.Json.

For example, if there is non-alpha numeric content in a segment does the path encode that segment?
e.g. `Root.Data['Dictionary key with spaces in it'].Name`

**Comment by steveharter** [comment]
Having an indexer in the message is a different ask than a json path - the json path will contain the json property names and not the CLR\object property names which can vary due to a naming policy or use of [JsonName].

In other words, we can add indexer support with either json or object path.

**Comment by JamesNK** [comment]
I mention dictionary key because it is a common case for mapping properties with spaces to a .NET object.

You can't write out property names separate them with `.` without any through to the content. For example, a JSON property that contains `.` will break anyone who wants to parse the path.

`Root.Data.This.Json.Has.Periods.Name`
vs
`Root.Data['This.Json.Has.Periods'].Name`

**Comment by steveharter** [comment]
Capturing some design decisions:
•	Use valid JSONPath – basically the same as Json.NET except start with “$” or "$." (e.g. “$.customer.phone[0]”).
•	Use dot-notation and bracket-notation the same as Json.NET (if special characters encountered, switch to bracket for that given property name).
•	Escape the property name to avoid injection.
•	If an error is encountered on the nth element (whether or not it is first) then n is shown. So `[tru]` returns `$[0]` as the path. (this is still under discussion).
