### ISSUE TITLE
JSON (de)serializer - add support for object references

### ISSUE THREAD

**Issue by Andrzej-W** [dotnet/corefx#37786]
To correctly serialize and deserialize object graphs from Entity Framework we need object references (something like this: https://www.newtonsoft.com/json/help/html/PreserveObjectReferences.htm).

Simple example: we want to serialize orders. Orders have references to customers. Two different orders have a reference to exactly the same customer. After deserialization we have to have one customer object and not two different objects with exactly the same property values.

Without this functionality new JSON (de)serializer is in my opinion almost useless in real world business application. Think about Blazor.

To correctly serialize object graphs from Entity Framework we also need support for graph cycles, see here: #36510

**Comment by ahsonkhan** [comment]
This is a known limitation of the JsonSerializer for v1, which is intended to be an MVP for the most critical scenarios, given the runway we have. Since `S.T.Json` is brand new, it is expected that there will be several features within Json.NET that will not be supported for the initial release.

Regardless, I have marked this as a 3.0 milestone for now rather than deferring to future, for discussion.

cc @steveharter, @rynowak, @JamesNK

**Comment by WinCPP** [comment]
@ahsonkhan once the decision is through, may I work on this?

**Comment by ahsonkhan** [comment]
> once the decision is through, may I work on this?

This issue is marked for future and likely requires some design and/or api work (which would need to go through approval). I don't think we will have a decision any time soon, so I don't think it can easily be picked up yet.

If you prefer to prototype an implementation and propose an API for review, then feel free to take this on. However, we have quite a few 3.0. milestone issues that we are prioritizing atm, and I would recommend try picking one of those up first:
https://github.com/dotnet/corefx/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.0

**Comment by WinCPP** [comment]
Got it @ahson. I haven't left a comment in #36125. Please check there.

Thanks!


Sent via mobile. Please excuse typos.]

**Comment by WinCPP** [comment]
Got it @ahsonkhan. I haven't left a comment in #36125. Please check there.

Thanks!

**Comment by Jozkee** [comment]
Preview is here.

* download the `System.Text.Json` preview package version 5.0.0-alpha.1.20071.1 from dotnet5 gallery (through Visual Studio's NuGet client):
https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json

If you want to add feedback, feel free to leave a comment in https://github.com/dotnet/corefx/issues/41002.
