### ISSUE TITLE
JsonSerializer.Parse throws unexpected exception parsing invalid DateTime(Offset) and Guid's

### ISSUE THREAD

**Issue by watfordgnf** [dotnet/corefx#37807]
While writing tests to cover #36901, the following additional test cases were found to fail:
```csharp
Assert.Throws<JsonException>(() => JsonSerializer.Parse<DateTime>(@"[]"));
Assert.Throws<JsonException>(() => JsonSerializer.Parse<DateTimeOffset>(@"[]"));
Assert.Throws<JsonException>(() => JsonSerializer.Parse<Guid>(@"[]"));
Assert.Throws<JsonException>(() => JsonSerializer.Parse<DateTime>(@"{}"));
Assert.Throws<JsonException>(() => JsonSerializer.Parse<DateTimeOffset>(@"{}"));
Assert.Throws<JsonException>(() => JsonSerializer.Parse<Guid>(@"{}"));
```
The exception received is:
```
    System.Text.Json.Serialization.Tests.ValueTests.ReadPrimitivesFail [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Text.Json.JsonException)
      Actual:   typeof(System.InvalidOperationException): Cannot get the value of a token type 'StartArray' as a string.
      ---- System.InvalidOperationException : Cannot get the value of a token type 'StartArray' as a string.
```
This should be JsonException as with the other parsing failures.

**Comment by ahsonkhan** [comment]
> This should be JsonException as with the other parsing failures.

I am not sure about that one. A case can be made for `InvalidOperationException` as well if you view it from the perspective that the caller can change the .NET API call rather than the payload being fed in.

Why is the caller parsing a `[]` into a DataTime? They should be parsing it to an array of some sort. Change the `Parse<T>` API call.

It could be `JsonException`, IF, the caller is adamant on it being a `DateTime` and the payload needs to be changed to a single value json string that contains a date time, but I don't see this as the most obvious choice.

@watfordgnf, why do you think `JsonException` fits better here? Is it more consistent with other scenarios?

@steveharter, @rynowak, @JamesNK - thoughts?

**Comment by watfordgnf** [comment]
It was odd to see this discontinuity from the perspective of exception handling:
```
JsonSerializer.Parse<int>("[]"); // throws JsonException
JsonSerializer.Parse<string>("[]"); // throws JsonException
JsonSerializer.Parse<DateTime>("[]"); // throws InvalidOperationException
JsonSerializer.Parse<SomeEnum>("[]"); // throws JsonException
```
Makes consuming the library a bit more difficult.

**Comment by ahsonkhan** [comment]
> It was odd to see this discontinuity from the perspective of exception handling

Agreed. Good catch :)

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/corefx/pull/37809.
