### ISSUE TITLE
System.Reflection.MetadataLoadContext has dependency on newer System.Memory package than it was built against

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/corefx#37943]
`System.Reflection.MetadataLoadContext` (for e.g., `4.6.0-preview6.19273.5`) …. 
- ... depends on `System.Memory/4.5.3`  (`AssemblyVersion=4.0.1.1`)
- ... requires `System.Memory` with `AssemblyVersion=4.0.1.0` (=> this is NOT `4.5.3` – this is `4.5.2)`. 

This incoherence breaks the build for PresentationBuildTasks in [dotnet/wpf](https://github.com/dotnet/wpf). 

We are temporarily working around the problem by explicitly referencing `System.Memory/4.5.2` and suppressing `NU1605`, but we'd like to stop doing this - and prefer that whatever version of `System.Memory` is pulled in by `System.Reflection.MetadataLoadContext` _just works_.

/cc @nguerrera, @ericstj, @ryalanms, @rladuca 
/cc @dotnet/wpf-developers

**Comment by nguerrera** [comment]
cc @steveharter

**Comment by ericstj** [comment]
@joperezr looks like this is fallout from https://github.com/dotnet/corefx/pull/37600

We should also update https://github.com/dotnet/corefx/blob/e8990ae04e4ef62f5ccb143352472c9b4d5d5968/external/binplacePackages/binplacePackages.depproj#L31-L41 to be consistent with whatever we are baselining to.  Otherwise we end up compiling against a different assembly than what we'll depend on.  This is OK in general, but is causing a problem for PBT which is an MSBuild task and is unable to easily specify bindingRedirects.

**Comment by ericstj** [comment]
To be clear this is a not a coherency issue, it's just a case were we are lifting the dependency up to a newer version that what we built against.  This sort of thing is normal and acceptable in most cases but in the case of a build task which wishes to avoid hooking AssemblyResolve and cannot specify bindingRedirects it makes it hard to deal with.  https://github.com/dotnet/corefx/issues/34816 tracks tooling this sort of requirement.
