### ISSUE TITLE
Perf: MemoryMappedFile.CreateFromFile ~20x slower on Linux

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#3813]
| test name                                                                                  |  date ran  |  Windows time |  Linux time |  linux/windows | 
|--------------------------------------------------------------------------------------------|------------|---------------|-------------|----------------| 
| System.IO.MemoryMappedFiles.Tests.Perf_MemoryMappedFile.CreateFromFile(capacity: 10000)    | 10/13/2015 | 0.433927546   | 73.4239     | 169.2077414    | 
| System.IO.MemoryMappedFiles.Tests.Perf_MemoryMappedFile.CreateFromFile(capacity: 100000)   | 10/13/2015 | 0.626372417   | 51.90790001 | 82.87066702    | 
| System.IO.MemoryMappedFiles.Tests.Perf_MemoryMappedFile.CreateFromFile(capacity: 1000000)  | 10/13/2015 | 1.818675306   | 57.4766     | 31.60355221    | 
| System.IO.MemoryMappedFiles.Tests.Perf_MemoryMappedFile.CreateFromFile(capacity: 10000000) | 10/13/2015 | 12.5975838    | 211.0644    | 16.7543557     | 

Perf test:
```
[Benchmark]
[InlineData(10000)]
[InlineData(100000)]
[InlineData(1000000)]
[InlineData(10000000)]
public void CreateFromFile(int capacity)
{
    // Note that the test results will include the disposal overhead of both the MemoryMappedFile
    // as well as the Accessor for it
    foreach (var iteration in Benchmark.Iterations)
        using (TempFile file = new TempFile(GetTestFilePath(), capacity))
        using (iteration.StartMeasurement())
        using (MemoryMappedFile mmfile = MemoryMappedFile.CreateFromFile(file.Path))
        using (mmfile.CreateViewAccessor(capacity / 4, capacity / 2))
        { }
}
```

**Comment by stephentoub** [comment]
I spent some time looking into this.

First, on my machines, I'm not seeing anywhere near a 20x difference.  Closer to 2-3x, regardless of the size of the file being used.

Second, the cost is coming almost entirely from the CreateViewAccessor call; if I just compare the cost of MemoryMappedFile.CreateFromFile on Windows and Linux, it's ~3x faster on Linux (which makes sense, as on Linux we defer much of the cost to CreateViewAccessor due to a mismatch between the .NET APIs and the underlying syscalls available on Unix, whereas on Windows there's more of a 1:1 mapping between the .NET APIs and the Win32 APIs). Within CreateViewAccessor, the cost is almost entirely in the syscall to mmap.  I don't think there's much we can do about that: it's just a difference in platforms.

As such, I'm closing this issue out.
