### ISSUE TITLE
Perf: MemoryMappedFiles.CreateNew ~5x slower on Linux

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#3814]
Probably related to #3813; possible duplicate

| test name                                                                             |  date ran  |  Windows time |  Linux time |  linux/windows | 
|---------------------------------------------------------------------------------------|------------|---------------|-------------|----------------| 
| System.IO.MemoryMappedFiles.Tests.Perf_MemoryMappedFile.CreateNew(capacity: 10000)    | 10/13/2015 | 1.420100596   | 25.587      | 18.01773767    | 
| System.IO.MemoryMappedFiles.Tests.Perf_MemoryMappedFile.CreateNew(capacity: 100000)   | 10/13/2015 | 1.437777014   | 24.3962     | 16.96799974    | 
| System.IO.MemoryMappedFiles.Tests.Perf_MemoryMappedFile.CreateNew(capacity: 1000000)  | 10/13/2015 | 1.6233794     | 24.3918     | 15.0253231     | 
| System.IO.MemoryMappedFiles.Tests.Perf_MemoryMappedFile.CreateNew(capacity: 10000000) | 10/13/2015 | 5.915327678   | 24.5068     | 4.142931944    | 

Perf Test:
```
[Benchmark]
[InlineData(10000)]
[InlineData(100000)]
[InlineData(1000000)]
[InlineData(10000000)]
public void CreateNew(int capacity)
{
    const int innerIterations = 1000;
    MemoryMappedFile[] files = new MemoryMappedFile[innerIterations];
    foreach (var iteration in Benchmark.Iterations)
    {
        using (iteration.StartMeasurement())
            for (int i = 0; i < innerIterations; i++)
                files[i] = MemoryMappedFile.CreateNew(null, capacity);
        for (int i = 0; i < innerIterations; i++)
            files[i].Dispose();
    }
}
```

Note that unlike CreateFromFile, the CreateNew tests only construct the files - they do not create an accessor. Therefore, any comparison of the results between the two tests probably won't be valid. If desired, I can add a test (or modify this test) that enables a better comparison between the two.

**Comment by stephentoub** [comment]
This is similar to #3813.

On my machine, the difference is around ~2.3x rather than ~5x, but that's still a measurable difference.

~50% of the time is being spent in a syscall to shmopen to create the backing object for the map.
~25% of the time is being spent in a syscall to ftruncate to size the backing object to the right size.
~10% is being spent in a syscall to shmunlink to remove the backing object.

And those account for the gap, with pretty much everything else being shared code with Windows.

This is another case where it's simply a matter of the platforms having different performance characteristics.  I'm also not particularly worried about it, given that typical use case for MMFs isn't to create and destroy them furiously.

Closing.
