### ISSUE TITLE
Perf: Stringbuilder ctor 5x slower on Linux

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#3819]
The constructor that takes a string is fine, but the default constructor is slow.

| test name                                                         |  date ran  |  Windows time |  Linux time |  linux/windows | 
|-------------------------------------------------------------------|------------|---------------|-------------|----------------| 
| System.Runtime.Tests.Perf_StringBuilder.ctor                      | 10/13/2015 | 1.690948933   | 9.650000006 | 5.706854783    | 
| System.Runtime.Tests.Perf_StringBuilder.ctor_string(length: 100)  | 10/13/2015 | 5.608841402   | 11.93529999 | 2.127943926    | 
| System.Runtime.Tests.Perf_StringBuilder.ctor_string(length: 1000) | 10/13/2015 | 32.82909926   | 36.8228     | 1.121651243    | 

Perf test:
```
[Benchmark]
public void ctor()
{
    StringBuilder builder;
    foreach (var iteration in Benchmark.Iterations)
        using (iteration.StartMeasurement())
            for (int i = 0; i < 10000; i++)
            {
                builder = new StringBuilder(); builder = new StringBuilder(); builder = new StringBuilder();
                builder = new StringBuilder(); builder = new StringBuilder(); builder = new StringBuilder();
                builder = new StringBuilder(); builder = new StringBuilder(); builder = new StringBuilder();
            }
}

[Benchmark]
[InlineData(100)]
[InlineData(1000)]
public void ctor_string(int length)
{
    PerfUtils utils = new PerfUtils();
    string input = utils.CreateString(length);
    StringBuilder builder;
    foreach (var iteration in Benchmark.Iterations)
        using (iteration.StartMeasurement())
            for (int i = 0; i < 10000; i++)
            {
                builder = new StringBuilder(input); builder = new StringBuilder(input); builder = new StringBuilder(input);
                builder = new StringBuilder(input); builder = new StringBuilder(input); builder = new StringBuilder(input);
                builder = new StringBuilder(input); builder = new StringBuilder(input); builder = new StringBuilder(input);
            }
}
```

possibly related to #3588?

@stephentoub @JeremyKuhne I think you have mentioned something like this?

**Comment by stephentoub** [comment]
> possibly related to #3588?

Yes.  Constructing a StringBuilder() with the default constructor is essentially just a couple of object allocations, one for the StringBuilder itself and one for the underlying char[] array.  Having a different issue open for each different kind of object that's slower to construct probably isn't that worthwhile, since they all essentially boil down to the same set of issues, e.g. https://github.com/dotnet/coreclr/issues/1708.

> I think you have mentioned something like this?

No, what Jeremy and I have been talking about are inefficiencies in how StringBuilders are marshaled in P/Invoke signatures.  That's not specific to Unix; that's just a general issue with regards to copying and allocations done in the marshaler, regardless of platform.

**Comment by ianhays** [comment]
Thanks @stephentoub, closing this then :)
