### ISSUE TITLE
Review and update THIRD-PARTY-NOTICES.TXT for 3.0

### ISSUE THREAD

**Issue by leecow** [dotnet/corefx#38206]
Review and update repo THIRD-PARTY-NOTICES.TXT as appropriate. Work should be completed for Preview 7.

**Comment by danmosemsft** [comment]
@tannergooding could you have a quick check then resolve this?

**Comment by tannergooding** [comment]
@leecow, @danmosemsft could you clarify what is required here? The third party notices file (to my knowledge) has already been updated, as appropriate, with any PRs that were using some new external code.

I'm not sure what would be actionable here outside reviewing all PRs that have happened since the last time it was reviewed and confirming that any 3rd party code pulled in also included a relevant notice addition to `THIRD-PARTY-NOTICES.TXT`.

**Comment by leecow** [comment]
This is an exercise to ensure the TPN is correct and up to date. If processes in place which ensure that then we're good go.

**Comment by danmosemsft** [comment]
I don't think you need do anything elaborate @tannergooding just 5 minutes thought whether we missed anything.

**Comment by tannergooding** [comment]
As far as I can tell, we have followed the existing guidelines which is to update the third-party notices files in the same PR that takes on a new third-party dependency.

I checked both the history of the TPN file and did some grepping over the codebase to see if there were any comments about code being ported from third-party sources.

**Comment by danmosemsft** [comment]
thanks @tannergooding
