### ISSUE TITLE
Socket.SetSocketOption throws invalid argument exception on Mac OS but works fine on Linux

### ISSUE THREAD

**Issue by ramsubbaraoc** [dotnet/corefx#38440]
socket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReceiveTimeout, timeout);

Using the above method throws the following exception 

System.Net.Sockets.SocketException (22): Invalid argument
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)

But the same works on Windows/Linux

**Comment by stephentoub** [comment]
What is the type and value of `timeout` in your example? This error is coming from the OS; it may be that Windows and Linux are more forgiving about invalid inputs.

**Comment by ramsubbaraoc** [comment]
Timeout is an int and value is -1

**Comment by stephentoub** [comment]
Negative receive timeout values are invalid with setsockopt; that's why the OS is giving you back an error. But POSIX didn't specify these failure modes, so they can be different across OSes.

Socket.SetSocketOption is meant to just pass the inputs through to the OS. If you want .NET to express is in opinion, you can use Socket.ReceiveTimeout... You'll see that it throws for < -1 but translates -1 into 0 to mean infinite because -1 is a standard convention for that in .NET.

Based on your description, everything here is behaving correctly, and you're just seeing OS differences in failure cases.

**Comment by ramsubbaraoc** [comment]
Thank you.That worked

**Comment by ramsubbaraoc** [comment]
Hi @stephentoub 

Can we have -1 for Windows and 0 for Linux. Will the behavior be same? 

-1 is used for infinite poll. Setting it to 0 on Mac and Linux will do a infinite poll

**Comment by stephentoub** [comment]
> Can we have -1 for Windows and 0 for Linux. Will the behavior be same?

For ReceiveTimeout it should be the same. You're seeing otherwise?

**Comment by ramsubbaraoc** [comment]
Yes, i see a difference in behavior when i use 0.
Mine is a multi threaded application and when i use 0,my application intermittently fails with an error.

"Cannot Read & Write to a socket at the same time " exception with the sslstream class.

When i use -1 i never see this exception.

**Comment by stephentoub** [comment]
> When i use -1 i never see this exception

-1 and 0 are 100% identical with ReceiveTimeout because the former is just converted to the latter:
https://github.com/dotnet/corefx/blob/c3f4524c785a226bae79cc82a96f7525460e2b5e/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L469-L472
