### ISSUE TITLE
Path of ModelState is not informative in certain cases

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/corefx#38494]
Take the following example:

```c#
[Fact]
public virtual async Task ReadAsync_InformativePath()
{
    var byteArray = Encoding.ASCII.GetBytes("[0, 23, 300]");
    var inputStream = new MemoryStream(byteArray);

    var modelType = typeof(byte[]);
    var serializerOptions = new JsonSerializerOptions();

    var ex = await Assert.ThrowsAsync<System.Text.Json.JsonException>(async () => {
        await System.Text.Json.JsonSerializer.ReadAsync(inputStream, modelType, serializerOptions);
    });

    Assert.Equal("[2]", ex.Path);
}
```

This will produce an `ex.Path` of `$` and an `ex.Message` of `The JSON value could not be converted to System.Byte[]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.`, neither of which is particularly informative about what went wrong. The particular information I think would be helpful is the Path of the specific element that failed to convert and the BytePosition of the element that failed to convert. Without those you're essentially left to manually verify your elements one by one.

Compare this to:
```c#
[Fact]
public virtual async Task ReadAsync_InformativePath()
{
    var byteArray = Encoding.ASCII.GetBytes("[{ \"Name\": \"Name Two\", \"Small\": 300}]");
    var inputStream = new MemoryStream(byteArray);

    var modelType = typeof(ComplexModel[]);
    var serializerOptions = new JsonSerializerOptions();

    var ex = await Assert.ThrowsAsync<System.Text.Json.JsonException>(async () => {
        await System.Text.Json.JsonSerializer.ReadAsync(inputStream, modelType, serializerOptions);
    });

    Assert.Equal("[2]", ex.Path);
}

protected sealed class ComplexModel
{
    public string Name { get; set; }

    public decimal Age { get; set; }

    public byte Small { get; set; }
}
```

Which produces something like `ex.Path` of `$[0].Small` and `ex.Message` of `The JSON value could not be converted to System.Byte. Path: $[1].Small | LineNumber: 0 | BytePositionInLine: 69.`. That's much more useful, it breaks down the exact array elements, parameter names and BytePositions that you should check out, and gives you the type it failed to convert to. This could only be more useful if it also told you the actual value that failed to convert.

### Expected result:
|Property|Value|
|---------|------|
|ex.Path  |$[2]|
|ex.Message|The JSON value could not be converted to System.Byte. Path: $[2] \| LineNumber: 0 \| BytePositionInLine: 4|

Hopefully that all makes sense, let me know if it needs clarifying.

**Comment by ahsonkhan** [comment]
The reason for this issue is that we only deserialize Base-64 encoded strings as byte[] (and also serialize byte[] as Base-64 encoded JSON strings). In this case, the deserializer expected a JSON string (since when it sees a byte[] in the model, it maps to the byte-array converter which expects base64). See https://github.com/dotnet/corefx/issues/36974. 

So, looking at the payload as a whole, and expecting base-64 json, **the error message makes sense**. It isn't failing because `300 > byte.MaxValue`. Even if you had a valid json array of numbers, the deserialization to a byte[] would fail with the same error.

We currently don't have the flexibility to deserialize a json array of numbers into a byte[] (along with a base-64 string) and the recommendation for that case would be to use a non-byte numeric type for an array of numbers.

**Do you have a scenario that requires such a flexibility in deserializing?**

https://github.com/dotnet/corefx/blob/b506d4a4ff6ffe1a1877016811e2266eacc2ebbc/src/System.Text.Json/src/System/Text/Json/Serialization/Converters/JsonValueConverterByteArray.cs#L11

cc @steveharter

**Comment by ryanbrandenburg** [comment]
Given that context this seems reasonable to me. I don't have a "real" scenario to need this behavior, it's just something I noticed while writing tests for one of our components that uses System.Text.Json. Feel free to close this out.

**Comment by ahsonkhan** [comment]
Sounds good. Thanks @ryanbrandenburg. Please do file and share issues like these as we want to make sure the exception messages are meaningful and help users understand what went wrong.
