### ISSUE TITLE
Investigate removing Homebrew dependency for ICU

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#3849]
The experience when you don't have an ICU or have a mismatched ICU (anything other than version 55) today is not great.  Let's improve this experience for rc1

http://userguide.icu-project.org/design#TOC-ICU-Data-Compatibility

Starting in ICU 3.8 and later, the data library that comes with ICU is binary compatible and structurally compatible with versions of ICU with the same major and minor version, or a maintenance release. This allows multiple maintenance releases of ICU to share the same data, but generally the latest maintenance release of the data should be used.

**Comment by ellismg** [comment]
@danroth27, I would like to better understand what pain points this is causing.  I understand that right now ICU is the only dependency we have on OSX that doesn't ship inbox, and it has to be acquired via homebrew.  If we solved this for OSX (by dynamically linking against a system provided ICU) is that sufficient?  This would remove the need for users to acquire ICU themselves on OSX.

I don't see how the data stability provided by ICU would allow us to create a Linux version of System.Globalization.Native that was portable across distributions.  However on Linux we already have many dependencies that have to be apt-get or yum'd before CoreCLR boot, so I don't understand why ICU is any worse than any of our other native dependencies.

**Comment by jasonwilliams200OK** [comment]
Static linking for cross-platform might be a challenge too. We will need to check the dependencies `readelf -d /path/to/libicui18n.a`. Secondly, for cross-platform, it will require us to take their repo as submodule and build the lib as part of CoreFX build process, otherwise something linked with glibc (libc.so.x), ld-linux-x86-64 and/or libc++ will not work with other Unix-like OSes. The additional overhead in case of libicu is that it [uses SVN](http://site.icu-project.org/repository), so we will need to create a mirror repo on GitHub and then consume it as a submodule.

Therefore, I agree with @ellismg to keep libicu marked as a `Needed` dependency.

**Comment by ellismg** [comment]
I have changed the title of this bug to reflect the work we actually think we might be able to do for RC (which is to remove the need to use Homebrew to install ICU on OSX, in favor of something that does ship inbox).
