### ISSUE TITLE
Support all CompareOptions values

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#3858]
For cross plat we don't currently support CompareOptions other than Ordinal, IgnoreCase, OrdinalIgnoreCase and None.

We need to understand how to support the other options on top of ICU, which has a different collation model than Win32.

**Comment by eerhardt** [comment]
CompareOptions IgnoreCase, IgnoreNonSpace, IgnoreSymbols, IgnoreKanaType and IgnoreWidth are all supported now on all platforms.

The only option that isn't fully supported is StringSort, which is defined as
> Indicates that the string comparison must use the string sort algorithm. In a string sort, the hyphen and the apostrophe, as well as other nonalphanumeric symbols, come before alphanumeric characters.

This is the default behavior in ICU. So the only thing that is left undone is that when StringSort is not specified (.NET's default), the sort order will be different between Windows and Unix platforms. The nonalphanumeric symbols will come after alphanumeric characters on Windows, but before on Unix.

Since locale-specific string sort order can change from one version of Windows to the next, there is no reason to guarantee string sort order between Windows and ICU. Thus trying to change ICU's default behavior here isn't really justified unless someone has a strong reason for !StringSort to behave differently.

Closing this issue as this feature is now considered complete.
