### ISSUE TITLE
Version Compatibility: netcoreapp2.0 Rounds Differently than netcoreapp3.0

### ISSUE THREAD

**Issue by MarkMichaelis** [dotnet/corefx#38588]
`System.Console.WriteLine(1.618033988749895)` with `netcoreapp2.0` and SDK `2.1.700` will result in the output:
```
1.61803398874989
```
However, changing to `netcoreapp3.0` with SDK `3.0.100-preview5-011568` will result in the output 
```
1.618033988749895
```

This would seem to be a version breaking change in behavior. While I don't particularly mind, I don't understand why the behavior is different and I want to be sure that it is intentional.  (In my case, it broke a unit test. :)

**Comment by stephentoub** [comment]
cc:@tannergooding

**Comment by tannergooding** [comment]
This change and its reasoning is covered here: https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/

As a summary, the old behavior was non-IEEE compliant and does not produce a round-trippable result by default. The new behavior is both IEEE compliant and produces a round-trippable result by default.

In your case, `1.618033988749895` has an underlying bit representation of `0x3FF9E3779B97F4A8`. Its exact value is `1.6180339887498949025257388711906969547271728515625`. Its shortest round-trippable string is `1.618033988749895`

However, `1.61803398874989` has an underlying bit representation of `0x3FF9E3779B97F492` (delta of 16 from the correct bit representation).  Its exact value is `1.618033988749890017544430520501919090747833251953125`. Its shortest round-trippable string is `1.61803398874989`.

So, the older framework versions result was causing a loss of information and that has been fixed for .NET Core 3.0.

**Comment by MarkMichaelis** [comment]
Similarly, note the discrepancy in the following code:
```
            const double number = 1.618033988749895;
            double result;
            string text;

            text = $"{number}";
            result = double.Parse(text);
            System.Console.WriteLine($"{result == number}: {result} == {number}");
```
### `netcoreapp2.0` SDK `2.1.200` Outputs:
```
False: 1.61803398874989 == 1.61803398874989
```
### `netcoreapp3.0`, SDK `3.0.100-preview5-011568` Output:
```
True: 1.618033988749895 == 1.618033988749895
```

**Comment by MarkMichaelis** [comment]
Here are some more differences that I assume are related but they seem slightly different.  See examples 2 & 4.
Given:
```
            // 1. Displays: 4.2 != 4.200000286102295
            System.Console.WriteLine(
                $"{(double)decimalNumber} != {doubleNumber1}");

            // 2. Displays: (float)4.2M != 4.2000003F
            System.Console.WriteLine(
                $"(float){(float)decimalNumber}M != {floatNumber}F");

            // 3. Displays: 4.200000286102295 != 4.2
            System.Console.WriteLine(
                $"{doubleNumber1} != {doubleNumber2}");

            // 4. Displays: 4.2000003F != 4.2D
            System.Console.WriteLine(
                $"{floatNumber}F != {doubleNumber2}D");

            // 5. Displays: 4.199999809265137 != 4.2
            System.Console.WriteLine(
                $"{(double)4.2F} != {4.2D}");
```

### `netcoreapp2.0` SDK `2.1.200` Outputs:
```
4.2 != 4.20000028610229
(float)4.2M != 4.2F
4.20000028610229 != 4.2
4.2F != 4.2D
4.19999980926514 != 4.2
```
### `netcoreapp3.0`, SDK `3.0.100-preview5-011568` Output:
```
4.2 != 4.200000286102295
(float)4.2M != 4.2000003F
4.200000286102295 != 4.2
4.2000003F != 4.2D
4.199999809265137 != 4.2
```

**Comment by tannergooding** [comment]
Those, modulo `(float)4.2M`, all look to be expected.

For #4, it's important to keep in mind that the `shortest round-trippable string` and the `exact underlying value` generally differ. In the case of `4.2` as a double, `4.2` is the shortest round-trippable string, but the exact underlying value is `4.20000000000000017763568394002504646778106689453125`.

The two representable `single-precision floating-point` values surrounding that are `4.19999980926513671875` and `4.200000286102294921875`. The `double-precision` floating-point value is slightly closer to the later, while `4.2f` is slightly closer to the former.

For `(float)4.2M`, it looks like `decimal.ToSingle()` is routing through `VarR4FromDec`, which in turn is just downcasting the result from `VarR8FromDec`. This is incorrect due to scenarios like the above: https://source.dot.net/#System.Private.CoreLib/shared/System/Decimal.DecCalc.cs,f7d192c86ca10cd4,references.
-- I will open an issue for this one and track getting it fixed.

**Comment by tannergooding** [comment]
Those, modulo `(float)4.2M`, all look to be expected.

For #4, it's important to keep in mind that the `shortest round-trippable string` and the `exact underlying value` generally differ. In the case of `4.2` as a double, `4.2` is the shortest round-trippable string, but the exact underlying value is `4.20000000000000017763568394002504646778106689453125`.

The two representable `single-precision floating-point` values surrounding that are `4.19999980926513671875` and `4.200000286102294921875`. The `double-precision` floating-point value is slightly closer to the later, while `4.2f` is slightly closer to the former.

For `(float)4.2M`, it looks like `decimal.ToSingle()` is routing through `VarR4FromDec`, which in turn is just downcasting the result from `VarR8FromDec`. This is incorrect due to scenarios like the above: https://source.dot.net/#System.Private.CoreLib/shared/System/Decimal.DecCalc.cs,f7d192c86ca10cd4,references.
-- I will open an issue for this one and track getting it fixed.

**Comment by tannergooding** [comment]
Logged https://github.com/dotnet/corefx/issues/38602

**Comment by MarkMichaelis** [comment]
Thanks for all the insight and help with this @tannergooding! (While no bugs would be better, I'm glad at least we were able to find at least one issue. :)
