### ISSUE TITLE
`Utf8JsonReader` does not correctly resume with only a `JsonReaderState`

### ISSUE THREAD

**Issue by mqudsi** [dotnet/corefx#38591]
~~The way the API is currently designed and going off of the inline-documentation and online blog posts, it seems that `JsonReaderState` exists to work around the limitations of its `ref struct` type, namely, notably the inability to use it in an `async` context.~~ 

Based off of writing a non-blocking, user-buffered, `async` wrapper for `JsonSerializer.ParseAsync<T>()` and a STJ-based alternative to the `JsonTextReader`, working with the currently released version of the `System.Text.Json` library:

The problem is that `Utf8JsonReader` retains stateful information that is not contained in `JsonReaderState`, meaning that despite all appearances, you have to either find a way to re-use `Utf8JsonReader` objects (impossible in an `async` context) or else retrieve additional state information that must then be relayed to a new `Utf8JsonReader` instance in order to continue a previous partial read operation (impossible outside of SWT, as the properties are accessors only).

**I have a contained reproduction of the problem here as a single-file MSTest: https://github.com/mqudsi/StjTest**

**Both tests should pass, currently only the one that explicitly clones the existing `Utf8JsonReader` object (which isn't possible across async boundaries) does.**

I see there's a proposal in https://github.com/dotnet/corefx/issues/35252 to rather reduce the amount of state stored in a `JsonReaderState` to reduce heap allocations, which is definitely a laudable goal. But as long as `Utf8JsonReader` is publicly usable, then the first priority should be to make it possible to re-initialize `Utf8JsonReader` to resume from a previous partial run without resorting to hacks that involve client-side state retention and manipulating the stream the reader is initialized atop of.

The `JsonReaderState` object contains all the information needed to correctly resume a new `Utf8JsonReader` instance from a previous `Utf8JsonReader.CurrentState` snapshot, but only some of that information is restored when the `Utf8JsonReader(..., JsonReaderState state)` overload is used to construct a new `Utf8JsonReader` instance.

#35252 details a workaround that can be used by changing the position of the underlying `ReadOnlySequence<byte>` that the reader is reading from, based off the value retained in the previous state. That only works if you're reading from a `ReadOnlySequence<byte>` and not a `Span<byte>` (although in the latter case you *should* be able to re-use the same `Utf8JsonReader` as both require stack-only allocation, but it certainly is imaginable that one is able to derive a partial `Span` from a heap-allocated read source (even just the contrived `Memory<byte>.Span`) and pass that in to a newly-constructed/restore `Utf8JsonReader`).

It is extremely confusing for the constructor to take a "complete" `JsonReaderState` object but only restore some of the values. Would you consider splitting the state into two (i.e. the equivalent of a `PartialState` and `FullState`, where `PartialState` is the information currently restored to a `Utf8JsonReader` when passed in a state and `FullState` would be the current `JsonReaderState`) and restoring the *entirety* of whatever state is passed in?

(This includes restoring values like `BytesConsumed`, which I use as part of my workaround for the lack of `SequencePosition` information when reading from a `Span<byte>`, but I must manually calculate that based off the previous state and current state rather than the current state alone as it is not restored.)

**Comment by mqudsi** [comment]
Oh, and of course the only externally usable API for setting the state of a `Utf8JsonTextReader` is the `state` parameter in the constructor. Users of the API cannot set `position` manually.

**Comment by mqudsi** [comment]
Additionally, for proper re-entrance/re-initialization support the `position` value is useless in all cases when reading from a `Span<byte>` rather than a `ReadOnlySequence<byte>`. I've had to work around this by separately keeping track of `BytesConsumed` (because it is not restored from the passed-in `JsonReaderState` object), manually bumping the cursor when saving `CurrentState`, and internally calling `Span<byte>.Slice(MyState.CumulativeBytesConsumed)` before passing in the previous `CurrentState` snapshot to properly resume across `async` boundaries.

**Comment by mqudsi** [comment]
*Revised and clarified*

**Comment by ahsonkhan** [comment]
> **Both tests should pass, currently only the one that explicitly clones the existing `Utf8JsonReader` object (which isn't possible across async boundaries) does.**

Do you mean `ResumeWithReader` succeeds and `ResumeWithState` fails?

This is expected given the current design since you need to slice the input data (if, for instance, it is contained within a `ReadOnlySpan<byte>`) by `BytesConsumed`, before passing it back to a new reader.

> (This includes restoring values like `BytesConsumed`, which I use as part of my workaround for the lack 

Slicing using `BytesConsumed` is the expected pattern (given its a span, that's quite cheap). Re-creating a reader instance from the state is generally only relevant for the async case where you want to go and read more data from an input source (like stream). In that case, you generally have a new `ReadOnlySpan<byte>` with the json data (rather than an existing one), and so it doesn't make sense to retain the previous `BytesConsumed`. Otherwise, we end up with BytesConsumed that is larger than the current json payload that was passed in. Both approaches have trade-offs here (whether `BytesConsumed` is the aggregate of all the data seen so far, or only related to the current input).

I don't see your sample requiring a need for re-entrancy (or re-creating a new `Utf8JsonReader` instance), so it is difficult to use it to justify changing the current design. I would expect you to keep using `ResumeWithReader` for that. The state passing is only relevant for async calls on the input source like stream/pipereader.

See tests like these for examples of expected usage:
https://github.com/dotnet/corefx/blob/85a2e0c1a3eebf0c937d26de1aafe4e4687b2d4f/src/System.Text.Json/tests/Utf8JsonReaderTests.cs#L766-L767

> but I must manually calculate that based off the previous state and current state rather than the current state alone as it is not restored

What calculation do you end up having to do? As long as your input starts where you had previously left off, the `BytesConsumed` on the state should just work.

> It is extremely confusing for the constructor to take a "complete" `JsonReaderState` object but only restore some of the values.


That's fair, which is partially why I wanted to remove the ones causing confusion (see https://github.com/dotnet/corefx/issues/35252), but that has the drawbacks I had mentioned there.

> Would you consider splitting the state into two (i.e. the equivalent of a `PartialState` and `FullState`, where `PartialState` is the information currently restored to a `Utf8JsonReader` when passed in a state and `FullState` would be the current `JsonReaderState`) and restoring the *entirety* of whatever state is passed in?

I am not sure if that would actually help or add complexity without much benefit. The `JsonReaderState` does not (and cannot) hold the original input span, so we will never have "full state" recovery anyway and that is the only reason some of the state is not being recovered (because the input span is changing).

**Comment by BreyerW** [comment]
If what @ahsonkhan said still doesnt work then i think team should reevaluate the possibility to convert reader to plain class instead of ref struct. Plain classes dont have issues with async context right? (and when converting writer to class it was found out that perf loss was acceptable).

**Comment by mqudsi** [comment]
Thank you for taking the time to reply, @ahsonkhan. I purposely kept the test code as minimal as possible, it was definitely not the same way I was using the reader in practice. My asynchronous code looks more like this:

```cs

/// Load the contents of property <c>property</c> at depth <c>depth</c> as a
/// <c>T</c>.
public async Task<T> ParseAsync<T>(Stream stream, string property, int depth)
{
	// Create a ReadOnlySequence<byte> adapter around the Stream
	var source = new StreamSequence(stream); 

	var state = new ParseState
	{
		InnerState = new JsonReaderState(),
		BytesConsumed = 0,
	};

	var utf8Property = DefaultEncoding.GetBytes(property);

	T partial = default;
	while (true)
	{
		switch (TryParse<T>(source.Sequence, utf8Property, depth, 
					ref state, ref partial)))
		{
			case ParseResult.ReadMore:
				await source.ReadMoreAsync();
				continue;
			case ParseResult.Complete:
				// no longer partially completed
				return partial;
			default:
				// Handle errors
		}
	}
}
```

From your explanation, I understand now how you're using the individual state values and why some are restored and others aren't. I had taken a different approach.

I'm not permanently advancing the `ReadOnlySequence<byte>` each time an attempted deserialization stalls by the value of `JsonReaderState.BytesConsumed`, rather I slice the passed-in source to the cumulative `BytesConsumed` offset; the `ReadOnlySequence<byte>` going in to the internal non-async parse function always starts at zero relative to the source:

```csharp
struct ParseState
{
	public JsonReaderState InnerState;
	public long BytesConsumed;
}

readonly ref struct JsonNode
{
	public readonly JsonTokenType TokenType;
	public readonly ReadOnlySpan<byte> Value;

	public JsonNode(JsonTokenType tokenType, ReadOnlySpan<byte> value)
	{
		TokenType = tokenType;
		Value = value;
	}
}

private TryParse<T>(ReadOnlySequence<T> source, Span<byte> property, int depth,
		ref ParseState state, ref result)
{
	// Note that this isn't the JsonReaderState's `BytesConsumed` field!
	// JsonReaderState.BytesConsumed always starts off from zero again
	var consumed = state.BytesConsumed;
	source = source.Slice(state.BytesConsumed); 

	var reader = new Utf8JsonReader(source, false, state.InnerState);

	// Try to skip to the node that contains the content we care about
	switch (GetProperty(property, depth, out var node) == ParseResult.ReadMore)
	{
		case ParseResult.ReadMore:
			return ParseResult.ReadMore;
		case ParseResult.Complete:
			break;
		default:
			// Handle errors
	}

	// Make sure the entirety of the value of this node is loaded
	// Use a new Utf8JsonReader so as to preserve our own state in case we
	// *do* have sufficient data to decode.
	var skipper = reader;
	if (!skipper.TrySkip())
	{
		return ReadResult.ReadMore;
	}

	result = JsonSerializer.ReadValue<T>(ref reader);
	return ReadResult.Complete;
}
```

From the API, I understood that the state would be saved so it made sense to me that I need to pass in a source that starts at the same place the last source did. Then each time that inner function is called, it must add up the previous value and the new read amount because the source isn't destructively sliced by the caller but rather temporarily by the callee.

I can easily change the code to slice externally prior to calling, in which case the `BytesConsumed` property zeroing out each time makes sense. The difference is that right now I have abstracted away when the value changes by including that in `GetProperty(..)` but that would necessitate managing state at the topmost caller level rather than internally at each location that temporarily modifies the state and may choose to save its location or reset it.

---

The problem is that the word "state" has a very specific meaning, and saving and restoring state has well understood semantics in most libraries and languages. As an example, when you call `Stream.Read(...)` it returns the number of bytes read *in this go*. That's not part of the stream state -- the stream state is the position the read pointer is located at in the read stream. The API should be designed in a way that makes it hard to write bad code, but with the STJ API it seems you really have to know exactly how it was intended to be used to get anywhere with it.. which is fine if the team had no intention of making it publicly accessible but definitely not ok otherwise.

All of which is to say I think you're absolutely correct with #35252 and I really hope that gets changed. 

As a final note, I think more of the confusion comes from the completely different ways of using the API depending on whether you are using `ReadOnlySequence<byte>` or `Span<byte>`:

> I am not sure if that would actually help or add complexity without much benefit. The JsonReaderState does not (and cannot) hold the original input span, so we will never have "full state" recovery anyway and that is the only reason some of the state is not being recovered (because the input span is changing).

For `Span<byte>`, yes. There's no other way more data could be loaded since it guarantees contiguity. But for `ReadOnlySequence<byte>` it certainly is sufficient.

**Comment by ahsonkhan** [comment]
> As a final note, I think more of the confusion comes from the completely different ways of using the API depending on whether you are using `ReadOnlySequence<byte>` or `Span<byte>`:

> For `Span<byte>`, yes. There's no other way more data could be loaded since it guarantees contiguity. But for `ReadOnlySequence<byte>` it certainly is sufficient.

How is it different for `ReadOnlySequence<byte>`? Just like we have span slice with `BytesConsumed`, the user is expected to slice the `ReadOnlySequence` by the `SequencePosition`. How do you load more data to a `ReadOnlySequence` without going back to a similar input source (like Stream/PipeReader)?
`Stream` -> Get more byte[] as `ReadOnlySpan<byte>`
`PipeReader` -> Get more `ReadOnlySeqeunce<byte>`

For example (from https://github.com/dotnet/corefx/issues/35252), we use the `SequencePosition` property to advance the pipe reader from which you get the next `ReadOnlySequence<byte>`:
```C#
_pipe.Reader.AdvanceTo(state.Position);
```

> I'm not permanently advancing the `ReadOnlySequence<byte>` each time an attempted deserialization stalls by the value of `JsonReaderState.BytesConsumed`, rather I slice the passed-in source to the cumulative `BytesConsumed` offset; the `ReadOnlySequence<byte>` going in to the internal non-async parse function always starts at zero relative to the source

> var consumed = state.BytesConsumed;
	source = source.Slice(state.BytesConsumed); 

Slicing the `ReadOnlySequence` from the start by an always growing int64 is probably not as efficient since it would force walking each segment every time. So, if you happen to have several segments, now you walk the linked list of segments within each iteration of `TryParse` (in your case). That is primarily why you would use the `SequencePosition` property.

> The problem is that the word "state" has a very specific meaning, and saving and restoring state has well understood semantics in most libraries and languages.

> The API should be designed in a way that makes it hard to write bad code, but with the STJ API it seems you really have to know exactly how it was intended to be used to get anywhere with it.. which is fine if the team had no intention of making it publicly accessible but definitely not ok otherwise.

That's definitely fair feedback. We had designed the type primarily targeting advanced developers, especially when it comes to some of the complex usage scenarios that you are trying to build up (for instance support for async). The fact that the type is a ref struct, alone, increases that barrier to entry. One thing we have considered for the future, is to build "StreamReader" support on top which does the state shuffling for you, under the covers, but I believe that publicly exposing the underlying low-level type (i.e. Utf8JsonReader), is useful for those who want to opt-in to the complexity. Similarly, one of the goals of the JSON stack was exposing each layer, so that any interested/motivated user could build their own custom higher layers on top of it.

> All of which is to say I think you're absolutely correct with #35252 and I really hope that gets changed.

Thanks. I am still not fully convinced if that change is worth the trade-off since we do end up hurting the intended use case of reading from a stream/pipe asynchronously and pass the state back and forth. Sure, we get some clarity for a scenario like yours, but does it buy us much. In one case, it requires reading docs/ramping up a bit (maybe even by looking at a sample to realize you should use BytesConsumed/Position for slicing), but in the other case, the user has to now return additional state themselves from the synchronous method to the async one (and that pattern becomes intrinsic to the design, and no "ramp up" will fix that wart).

**Comment by ahsonkhan** [comment]
@mqudsi, is there anything else left about this issue?

**Comment by mqudsi** [comment]
@ahsonkhan thanks for the ping.

> How is it different for ReadOnlySequence<byte>? Just like we have span slice with BytesConsumed, the user is expected to slice the ReadOnlySequence by the SequencePosition. How do you load more data to a ReadOnlySequence without going back to a similar input source (like Stream/PipeReader)?

The difference is that as a developer implementing some functionality, if you are reading from a pipe or stream or anything other than a guaranteed-contiguous byte-level memory-mapped source and need to load more data, you can cheaply append to an existing `ReadOnlySequence` whereas if you were using the span version of the api instead, you can only (realistically) supply a totally new `Span` (otherwise there's no reason you wouldn't have supplied the original `Span` in its entirety, unless you are copying from a non-contiguous source to a full-length buffer in memory but only want to read a chunk at a time, which we thankfully no longer have to do with modern .net core concepts).

> is there anything else left about this issue?

What about passing in separate ref fields for the bits that are not restored on initialization? e.g. 

`Utf8JsonReader(JsonReaderState state, ref int bytesConsumed, ...)`


> At a higher level, what is the scenario you are trying to resolve with your async code? Where is your JSON coming from? Maybe a JsonStreamReader would help here (which we are considering adding in the future):

That's what I have implemented on my end. I have no problem with the bare bones functionality of the current API. My only issue is that the API is misleading. I'm willing to jump through hoops to implement features on my end (it's my job, after all!) but an API whose design says upfront that I'll have to is preferable to an API that makes it seem like it'll resume where it left off when it doesn't.

**Comment by terrajobst** [comment]
Closing in favor of #35252.
