### ISSUE TITLE
Info Request - Where is this file

### ISSUE THREAD

**Issue by leecow** [dotnet/corefx#38726]
@sujayvsarma commented on [Sun Jun 16 2019](https://github.com/dotnet/core/issues/2891)

Hello,
Where is the actual source file where these changes have been done? 

API DIFF: 
https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/api-diff/preview6/3.0-preview6_System.Collections.Generic.md

---

@leecow commented on [Wed Jun 19 2019](https://github.com/dotnet/core/issues/2891#issuecomment-503875559)

Most of the APIs will be found in the corefx repo. This particular library can be found at https://github.com/dotnet/corefx/tree/master/src/System.Collections/src/System/Collections/Generic.

---

@sujayvsarma commented on [Wed Jun 19 2019](https://github.com/dotnet/core/issues/2891#issuecomment-503882204)

The API DIFF talks about changing the interface specs of `IDictionary` and `IReadonlyDictionary`. I don't see those objects at the [location](https://github.com/dotnet/corefx/tree/master/src/System.Collections/src/System/Collections/Generic) you mentioned.

---

@sujayvsarma commented on [Wed Jun 19 2019](https://github.com/dotnet/core/issues/2891#issuecomment-503882437)

@leecow Hopefully you will check if the response you provide is **actually** helpful before closing out the requests.

---

@leecow commented on [Thu Jun 20 2019](https://github.com/dotnet/core/issues/2891#issuecomment-504061115)

Sorry about that. Again, all of that code should be in the corefx repo so let's move this question over there.

**Comment by Gnbrkm41** [comment]
https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Collections/Generic/IDictionary.cs
https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Collections/Generic/IReadOnlyDictionary.cs

**Comment by sujayvsarma** [comment]
Why are these classes private? Doesn't make sense.

**Comment by Gnbrkm41** [comment]
They are not private, per se; IIRC, the interface shared across different repos (corert, coreclr, mono etc) and these shared source files go in `System.Private.CoreLib` project.

**Comment by Gnbrkm41** [comment]
One easy way to look up source code is to use https://source.dot.net Source browser website. Not only they provide easy search / browse feature they also let you see where the source code is located at (click bottom right `Web Access`).

**Comment by sujayvsarma** [comment]
`Private` in the namespace, hard to locate.. Well hidden. Didn't this interface used to be in the `System.Collections.Generics` project/source tree in the framework ?? 

You guys have become weird with code organization IMHO.

**Comment by Gnbrkm41** [comment]
`System.Private.CoreLib` as in project, not as in namespace. If you see the files, they indeed are under System.Collections.Generic namespace:  `namespace System.Collections.Generic`

And yes, not disagreeing that it's somewhat weird... but I guess that's what you need for sharing codes across many different repos. 😋

**Comment by filipnavara** [comment]
Many of the external assemblies (eg. `System.Collections`) are facades or partial facades. The actual implementation is in different assembly and it is type-forwarded. In this particular case the classes were needed by the transitive dependency closure of other classes in `System.Private.CoreLib`, the lowest-level runtime library (a lightweight version of what used to be `mscorlib.dll` back in the day).

**Comment by sujayvsarma** [comment]
That explains the organization. 

Probably a whole another question, but doesn't type-forwarding (and heavily as in the case of internal .net) kind of slam on some brakes in terms of performance? Am thinking about context changes across assemblies etc.

**Comment by danmosemsft** [comment]
Do you have evidence that Typeforwarding is impacting the perf of your app? We generally work on the assumption that it is not significant.

**Comment by sujayvsarma** [comment]
Impact depends on what you call "significant" and what type of app you're writing. With TF, there is a [whole lot of messing](https://blogs.msdn.microsoft.com/davbr/2009/09/30/type-forwarding/) going around. Think of a scenario where like in SharePoint, you have types cached up in a database table and they are loaded at run time. How .NET works impacts all of those applications. Given that you guys have announced there will be no more Framework from v5.0 on, this is not a joke.

From the docs available out there it seems that moving code out of mscorlib was the only priority that led to the current state of heavy TFing in .NET Core. 

In the end, instead of one heavy mscorlib, you now need a 10 packages with a 100 dlls (never to be used cross plat stuff included when you download the nuget) to do the same thing.

**Comment by joperezr** [comment]
@sujayvsarma As explained above, the source for the **implementation** of the interface is located in the coreclr repo as part of System.Private.CoreLib, and also as it is explained above, the reason is that this interface is part of the closure of System.Private.CoreLib which is the lowest part of the stack of .NET Core so we needed to move it down there in order to avoid circular references. The **reference** definition of this interface does live in this repo, particularly it lives here(this is the IDictionary one, IReadOnlyDictionary is also in that file): 

https://github.com/dotnet/corefx/blob/816cd5d4a72780eafd58aa585ffd552da4b5a994/src/System.Runtime/ref/System.Runtime.cs#L3949-L3958

Finally, the specific change on the interface that you are seeing, was introduced by this PR: https://github.com/dotnet/corefx/pull/38474/files#diff-b3d39e42f75b9efe89d21eb385ed61f6L3983

Given that this issue was created as a question which I believe I just answered I'll go ahead and close the issue. That said, @sujayvsarma please feel free to reopen if you have any follow up comments 😄
