### ISSUE TITLE
What is roadmap for HttpListener

### ISSUE THREAD

**Issue by comdiv** [dotnet/corefx#3872]
It's not regular issue - it's design and road map question about HTTP stack.

Our company focused on multi-agent solutions that are installed into multi-node trusted environment. So for recent years we use HttpListener and develop some set of lightweight http-servers, tightly bound to our task. If we need some features as Internet access, SSL, advaced static file support we use NGINX as frontend. So we not require to use some of prepared ASP.NET Servers or IIS while they are not so close to our task.

But HttpListener has http.sys implementation in .NET so we require use netsh in Windows, if we use Mono - on Windows we got troubles and bugs and on Linux - all works well.

So from netcore(dnx)/corefx we expected that HttpListener class will be kept but rewritten on Mono-like style with own socket wrapping and managed HTTP protocol support. So it would be good base for lightweight HTTP-based solutions.

Instead of this we see that (or it seems) that roadmap of netcore is focused on aspnet-related HOSTS and we lost valid HttpListener support, but we are turned to use ASP.NET+MS MVC or Kestrels model.

It's not what we expected - all other modules (as Reflection, Xml and so on) moved to more atomic and know-what-you-exactly-want style and design. But in NET stack we still see tendention to using monstrous-like complex "hosts".  In System.Net.Http we see some improvements for client HTTP but not for Server.

May we are not right but we not see activity on HttpListener or it's analog so it's limitation that force as to keep using not unified .NET 4.5 + Mono 4.0.4 stack.

What exactly planned in HTTP stack for netcore/dnx?

**Comment by davidfowl** [comment]
I can speak to a few of these things. On the ASP.NET team, we built 2 servers, kestrel and WebListener. WebListerer is http.sys specific and won't ever work xplat but is the logical successor to HttpListener on Windows. Kestrel is cross platform but it's pretty much tied to ASP.NET's object model.

 I do have some probing questions though (but don't read too much into them, I'm just trying to get information).

You can use WebListener directly instead of using the Microsoft.AspNet.Server.WebListener package. This will give you a Windows specific asp.net agnostic API for handling http requests. Why not just use ASP.NET 5? The layering is much thinner than what previous versions of asp.net looked like so maybe it's time to reevaluate and see if it could work for you? 

I see the term monolithic being used but I'm guessing that's based on past experience instead of what we have now. You can even use individual pieces independently of each other if you want to build your own web framework.

HttpListener is just the wrong abstraction to take cross platform. I applaud mono's efforts but there are much better ways of achieving the same goals. Maybe for application portability somebody can port the mono HttpListener to .NET core but It's not something we'd recommend to people, just s bridge.

**Comment by comdiv** [comment]
WebListener is "windows specific" - it still require netsh to setup and is not working on linux (or I'm mistaken) - if it can work on Linux i think it's not hard to migrate on.

Why not ASP.NET. If it's interesting.
I used ASP.NET for a long time since .NET 1.1 and have some notions about it (that could be some kind of holywar). Today ASP.NET is much pretty than it's ancestors, but we have large amount of existed code that works over HttpListener without ASP.NET pattern (we use self writen REST framework) - it's not very simple to turn it into ASPNET5 WebAPI model. Anyway we prefer "fresh webserver" that we could use any way we want. For example we have Trust/IP based filter and redirection module that works for security and dispatching in farm and it use special Identity. It's possible, of couse express it as modules/services for aspnet but it's not very simple.  While development time for our command is more than 8 years we have almost all things written ourselfs for our certain problemtatic - DI and so on. It based on System classes of .NET/MONO without any extra dependencies except of NUNIT or some algorithmic libraries.  So NUGET ideology is not so close for us - it's like a Package ZOO that usually seen in Java projects... We prefer oldscool working with src with git-tag to mark well tested dependency. So may be we are some kind of dinosaurus, but we like situation where we checkout code, call . build run and that all we need to deploy.

So we want to move to netcore when it will be released - it's much pretty and clear than .NET/MONO but got some breaking differences... another one is that we already has dnx-like console host that controls shadow copying, dll/code/resource allocation and setup application from config as DI container with entry point. It's very close by ideology but not simple to migrate... And we use gitbased components (host fetchs and recompile) at production - it's close but not simple to migrate with NUGETS.

**Comment by joshfree** [comment]
@SidharthNabar @davidsh @vijaykota

**Comment by davidfowl** [comment]
@comdiv Like I said, you should take another look, your assumptions aren't well founded (fair based on previous ASP.NET). I won't try to convince you as it distracts from your original question but I'll leave you with this, ASP.NET != MVC or WebAPI, that's just a framework on top of ASP.NET 5. You can learn more about it here if you're interested https://docs.asp.net/en/latest/

**Comment by comdiv** [comment]
Is it true that following code is code for multithread server that works with "raw" request?
```
 public async void Configure(IApplicationBuilder app)
        {
            app.Run(async context =>
            {
                context.Response.ContentType = "text/plain";
                await context.Response.WriteAsync("Staging environment.");
            });
        }
```
If it's true - it's similar to what we used to deal with when working with HttpListener - so this sample could be clue to

**Comment by davidfowl** [comment]
@comdiv yes, it's also server agnostic
