### ISSUE TITLE
SocketAsyncContext memory leak

### ISSUE THREAD

**Issue by xinyanmsft** [dotnet/corefx#38827]
we are seeing memory leak around SocketAsyncContext.
- Our app runs inside Linux Docker (Azure Kubernetes Service). Compilation is done with mcr.microsoft.com/dotnet/core/sdk:2.2 base image. The app runs with mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine3.9 base image. We are seeing SocketAsyncContext objects are leaking 41721 instances:

00007F9F0F7096F8        126260  3030240 System.Object
00007F9F154A4D20        41721   1668840 System.Net.Sockets.SafeCloseSocket+InnerSafeCloseSocket
00007F9F154A6A90        41721   3003912 System.Net.Sockets.SafeCloseSocket
00007F9F16B51C30        41721   6007824 System.Nmempeeet.Sockets.SocketAsyncContext
00007F9F16BAAD38        41719   3671272 System.Net.Sockets.SocketAsyncContext+BufferMemoryReceiveOperation
0000563A0F639080        16329   3928436 Free
00007F9F0F708AA8        10788   1073552 System.String
00007F9F0F70EFB0        6722    699088  System.Reflection.RuntimeMethodInfo
00007F9F0F6F8CF8        5309    1004193 System.Byte[]
......

(to reduce noise, the app calls GC.Collect every few seconds)

GC root gives this call graph:

GCRoot 7F9F88331068->7F9EF6E65248 Strong handle -> 7f9ef6e65248 System.Object[]  ->
7f9ef6e65140 System.Threading.Tasks.Task  ->
7f9ef6e65018 System.Net.Sockets.SocketAsyncEngine  ->
7f9ef6e65058 System.Collections.Generic.Dictionary<System.IntPtr,System.Net.Sockets.SocketAsyncContext>  ->
7f9f06e55750 System.Collections.Generic.Dictionary+Entry<System.IntPtr,System.Net.Sockets.SocketAsyncContext>[]  ->
7f9ef830efe0 System.Net.Sockets.SocketAsyncContext  ->
7f9ef830f128 System.Net.Sockets.SocketAsyncContext+BufferMemoryReceiveOperation

It seems Socket.cs is not disposing properly, and didn't invoke _handle.Dispose() somehow.

I find a related PR https://github.com/dotnet/corefx/pull/38499 but not sure if this is related.

**Comment by davidsh** [comment]
@wfurt @stephentoub Wasn't this fixed in .NET Core 3.0?

**Comment by stephentoub** [comment]
> Wasn't this fixed in .NET Core 3.0?

Yes:
https://github.com/dotnet/corefx/pull/38499
https://github.com/dotnet/corefx/issues/37044#issuecomment-500660152

**Comment by stephentoub** [comment]
> I find a related PR #38499 but not sure if this is related.

It is.  That is the fix for this in .NET Core 3.0.

However, that you are seeing this @xinyanmsft means that you're not disposing of something; this issue only prevents these objects from being finalized, but properly disposing of them in your code will prevent the issue.  For example, if you're creating HttpClient instances, make sure you're disposing of them when you're done with them (it's fine to keep one around for a long time in order to make lots of requests on the same instance, in fact that's encouraged, but if/when you choose to drop it and, say, replace it with another instance, Dispose of it first).
