### ISSUE TITLE
System.Text.Json.Serialization.JsonSerializer should respect DataMemberAttribute.Name

### ISSUE THREAD

**Issue by abelykh0** [dotnet/corefx#38841]
The following code outputs `{"MyDataMember":"dataMember"}`, should be `{"RENAMED":"dataMember"}`

```csharp
using System;
using System.Diagnostics;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace JsonSerializerIssue
{
    [DataContract]
    internal class MyData
    {
        [DataMember(Name = "RENAMED")]
        public string MyDataMember { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            MyData myData = new MyData() { MyDataMember = "dataMember" };
            Debug.WriteLine(JsonSerializer.ToString(myData));
        }
    }
}
```

**Comment by ahsonkhan** [comment]
Is there a particular reason why the new `JsonPropertyName` attribute won't work for your scenario?

**Comment by abelykh0** [comment]
We have tens of thousand lines of code and would like to replace Newtonsoft.Json with the new functionality.

**Comment by jjrdk** [comment]
+1 for sticking with an existing API.

**Comment by hmqgg** [comment]
> Is there a particular reason why the new `JsonPropertyName` attribute won't work for your scenario?

For example, if we build a Blazor app, and ofc we'd like to make JSON models shared between our server and client to keep them consistent, but on the client side (i.e. Blazor project), we can't use `System.Text.Json` due to the runtime restrictions so we can't use `JsonPropertyName`.

What's more, many existing projects now use `DataContract`/`DataMember` attributes because it's common and most of JSON libs respect it.

I knew that now it's life after WCF, and we'd better not use these attributes introduced by WCF since it's nearly EoS. But we need attributes that could describe JSON models across so many JSON libs and runtime.

**Comment by kucint** [comment]
there is currently no replacement for [DataMember(EmitDefaultValue)] in System.Text.Json.

**Comment by jjrdk** [comment]
@ahsonkhan Can you explain why it is necessary to create a new attribute only for json serialization? What if I also need to serialize to other formats? Should I now decorate my type with additional attributes?

Why not use the existing common attribute?

**Comment by Aernor** [comment]
@jjrdk, I agree. It seems logical to abstract the serialization decorations to allow for the serializing and deserializing in multiple formats (based on request Accept headers for example).

**Comment by layomia** [comment]
Closing as duplicate - this falls under the ask to support types from System.Runtime.Serialization: https://github.com/dotnet/corefx/issues/38758.
