### ISSUE TITLE
Failing unit test locally on mac: ProcessWaitingTests.WaitForSignal

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#38916]
```
      System.Diagnostics.Tests.ProcessWaitingTests.WaitForSignal [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
          /Users/hugh/Documents/GitHub/corefx/src/System.Diagnostics.Process/tests/ProcessWaitingTests.cs(208,0): at System.Diagnostics.Tests.ProcessWaitingTests.WaitForSignal()
    Finished:    System.Diagnostics.Process.Tests

```

**Comment by stephentoub** [comment]
What OS distro and version? What command did you run (e.g. just this test project? All tests?)? Etc

**Comment by hughbe** [comment]
![Screenshot 2019-06-26 at 14 00 44](https://user-images.githubusercontent.com/1275900/60181765-d7497d00-981a-11e9-9a4c-73241c40d6fb.png)

Ran `./build.sh -test` from root

**Comment by hughbe** [comment]
Can't repro when running individual tests, but can during the full test run

**Comment by stephentoub** [comment]
> Can't repro when running individual tests, but can during the full test run

Consistently?  If you increase this value:
https://github.com/dotnet/corefx/blob/30ca4113ed07fc78060a0c9d3f95eee4fe8f8ee3/src/System.Diagnostics.Process/tests/ProcessWaitingTests.cs#L184
to, say, 60_000 or higher, does it still happen?  Trying to determine if this is simply due to the machine getting bogged down with lots of things contending for resources (though 30 seconds would be a long time).

**Comment by hughbe** [comment]
Boff, can't seem to repro! Thanks for your help
