### ISSUE TITLE
JsonElement - Support returning values as ReadOnlyMemory<byte>

### ISSUE THREAD

**Issue by stevejgordon** [dotnet/corefx#38922]
I've very recently begun using JsonDocument and in my scenario, it would feel really useful if I could get the value of a property via JsonElement I am returned from GetProperty() without allocating. Today it seems that I need to allocate a string to access a string value. 

The scenario I'm working on is an optimised ASP.NET Core service which has a single endpoint mapped. I'm then using the BodyReader (PipeReader) of the request to read the JSON data. Later I form a simple response which uses incoming data to form a URL response, which I write to the BodyWriter (PipeWriter) 

Right now, I'm deserialising to an object which includes the properties I need as strings. See this sample - https://github.com/stevejgordon/AspNetCorePipeSample. I feel I could optimise this by avoiding the object and string allocations.

If I could use the JsonDocument to access the properties (JsonElement) and then get a ReadOnlyMemory<byte> I could then form my response, copying the bytes I need from various properties, directly into the BodyWriter.

Maybe something like this is possible to expose?

```csharp
public ReadOnlyMemory<byte> GetValueMemory();
```

I've not explored the whole codebase yet but it seems that as long as this is accessed during the lifetime of JsonDocument (before disposal), reading that memory would be fine. I guess it risks references leaking and preventing the return of the array memory to the pool.

cc\ @steveharter

**Comment by ahsonkhan** [comment]
cc @bartonjs

**Comment by GrabYourPitchforks** [comment]
I feel strongly that such an API would encourage misuse. The raw bytes coming from a JSON payload are in a JSON-specific format (using JSON-specific escaping, for instance) and aren't in a format that's immediately usable by any other consumer. In the example linked to here, the application should already be further processing the data by escaping it in a manner appropriate for inclusion in a URL. This involves converting the data to a `string` for manipulation, so this particular example wouldn't benefit from `ROM<byte>` APIs anyway.

**Comment by bartonjs** [comment]
The design of JsonDocument/JsonElement is such that the underlying data encoding is never exposed to the caller.  Should future needs warrant adding a UTF-16-based JSON reader or a UTF-32-based JSON reader these could be used as internal implementation details by JsonDocument.  Once JsonElement exposes an encoding, this stops being practical.

Exposing the bytes is also difficult with plans, post-3.0 to make a mutable DOM which is/interacts-with JsonElement, since there might not actually be any underlying bytes to expose.

If demand stays high and these future plans/capabilities turn out to be not needed, we can always change our mind... but right now this is not something that we want to do.

**Comment by stevejgordon** [comment]
Thanks, @GrabYourPitchforks and @bartonjs for the quick replies. You've both raised great points and I hadn't got far enough along to consider the JSON escaping issue. 

I'll close this now as the question has been fully addressed.
