### ISSUE TITLE
Documentation for HttpClient methods should state which exceptions can be thrown by the returned task

### ISSUE THREAD

**Issue by lawrencejohnston** [dotnet/corefx#3894]
Not 100% sure this is the right place for it, but it looks like HttpClient is in this repository so I'm reporting this here.

The documentation for HttpClient methods (and async methods in general) should state which exceptions can be thrown by the returned task instead of just the exceptions that can be thrown by the method that returns the task.

As example of this is the documentation for [HttpClient.GetStringAsync](https://msdn.microsoft.com/en-us/library/hh551746%28v=vs.118%29.aspx).

Without this documentation you either have to catch everything ([well-documented as a bad practice](https://msdn.microsoft.com/en-us/library/ms182137.aspx?f=255&MSPPError=-2147217396)) or make educated guesses based on experimentation and [digging](https://stackoverflow.com/questions/24689263/exception-handling-for-httpclient-getstringasyncurl-async-api-call) through [various](https://social.msdn.microsoft.com/Forums/en-US/d8d87789-0ac9-4294-84a0-91c9fa27e353/bug-in-httpclientgetasync-should-throw-webexception-not-taskcanceledexception?forum=netfxnetcom) posts online, and if you go that route it's easy to miss that it throws, e.g., InvalidOperationException if the charset of the content type of the requested page can't be parsed into an encoding.

**Comment by davidsh** [comment]
cc: @SidharthNabar @stephentoub

**Comment by lawrencejohnston** [comment]
Here's another one we just discovered in the field:
System.IO.InvalidDataException: The magic number in GZip header is not correct. Make sure you are passing in a GZip stream.

**Comment by CIPop** [comment]
/cc @mairaw @karelz 

Marking this up-for-grabs. The initial work required is to dig through the code and find all failure modes. 
The best way to start is probably with the assertions within our tests. If we find scenarios that are not verified, it would be good if we add tests for those as well.

**Comment by DelfCo** [comment]
This is intentional. Asking us to do the work for you just means that you're trading doing your own research, testing, and/or digging through the source and finding the exceptions you care about, for having someone else (me) dig through the source and guess which exceptions you might care about. Even if that were possible, I'm responsible for too many other things to be able to do that job adequately. The doc team has no special insight into what's significant, nor do we watch the code for changes that might affect the documentation. And neither the doc team nor the dev team will necessarily know that a change to a utility component deep in the stack needs to be reflected in docs for all of the API that use it. In short, we can't keep such a list accurate and up to date, so we avoid giving you anything that might be interpreted that way. I did Windows development for twenty years before I started working as a writer -- those docs that tried to list the exceptions were never complete and up to date.

Your link for "well documented as a bad practice" isn't working for me, but I believe someone's misinterpreting recommended best practice. What's a bad idea is to catch and swallow all exceptions, because that keeps other components from getting an exception they might know how to handle. It's a good idea to catch the exceptions you can handle productively in your code, and ignore or log and rethrow those you can't handle. You need to determine which those are by testing, or with .NET Core, by inspecting the code that's relevant to your use case.

**Comment by karelz** [comment]
@DelfCo there is likely misunderstanding. No one is pushing work on your plate ;-).
For context please read our [issue guide](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md), esp. about "up for grabs".

@CIPop you might want to update your text to clarify those are the next steps you expect from whomever picks up the issue -- it is not clear even for me.
Also we should refrain from looping in docs folks until there is something actionable for them (or nearly actionable).

**Comment by CIPop** [comment]
> Also we should refrain from looping in docs folks until there is something actionable for them (or nearly actionable).

Sorry about that @mariaw, @DelfCo. /cc is used to add you to the notification list of an issue and isn't considered an assignment.
Exceptions were documented in the past. For example, see the [Exceptions list for ConnectAsync](https://msdn.microsoft.com/en-us/library/bb538102(v=vs.110).aspx#Anchor_1). We are missing this paragraph entirely for [HttpClient.GetAsync ](https://msdn.microsoft.com/en-us/library/hh551747(v=vs.118).aspx).

> @CIPop you might want to update your text to clarify those are the next steps you expect from whomever picks up the issue

In more details, whomever picks this issue will need to:
1. Dig through the code and find all failure modes for HttpClient methods. One idea is to start with the test code which is already verifying that in certain cases, certain exceptions will be thrown.
2. Build a list of all the exceptions and the failure-mode that caused them. (e.g. TimeoutException is thrown when the server is not responding) Attach the list to this issue.
3. (Nice to have:) For failure modes that are not tested, add new tests to pin down the behavior. This way we can ensure that the behavior is pinned and verified cross-plat.

After the completion of the above 3 steps, the documentation team (@mariaw, @DelfCo) should have enough information to derive exception documentation for HttpClient. At that point only the item will be routed to their team.

**Comment by davidsh** [comment]
Please refer to the new place for documentation (docs.microsoft.com).

The common exceptions are documented.  For example: [HttpClient.GetStringAsync](
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.getstringasync?view=netcore-2.0#System_Net_Http_HttpClient_GetStringAsync_System_Uri_)

If there are other classes/methods that need documentation updates, please feel free to Edit link on the top-right corner of each documentation page. 
![image](https://user-images.githubusercontent.com/7684835/39962504-483c3100-5605-11e8-8109-89c017b1ab28.png)


That will redirect you to the GitHub repo for the documentation. From there, you can open a new issue or even submit a PR with suggested fixes to the documentation.
