### ISSUE TITLE
chmod: cannot access '/home/s0dy/source-build/bin/src/corefx.a28176b5ec68b6da1472934fe9493790d1665cae/artifacts/bin/testhost/netcoreapp-Linux-Release-x64/': No such file or directory

### ISSUE THREAD

**Issue by s0dy** [dotnet/corefx#38988]
```
Restore completed in 1.18 ms for /home/s0dy/source-build/bin/src/corefx.a28176b5ec68b6da1472934fe9493790d1665cae/external/runtime/runtime.depproj.
    chmod: cannot access '/home/s0dy/source-build/bin/src/corefx.a28176b5ec68b6da1472934fe9493790d1665cae/artifacts/bin/testhost/netcoreapp-Linux-Release-x64/': No such file or directory
  /home/s0dy/source-build/bin/src/corefx.a28176b5ec68b6da1472934fe9493790d1665cae/external/runtime/runtime.depproj(77,5): error MSB3073: The command "chmod +x /home/s0dy/source-build/bin/src/corefx.a28176b5ec68b6da1472934fe9493790d1665cae/artifacts/bin/testhost/netcoreapp-Linux-Release-x64/" exited with code 1.

  Build FAILED.

  /home/s0dy/source-build/bin/src/corefx.a28176b5ec68b6da1472934fe9493790d1665cae/external/runtime/runtime.depproj(77,5): error MSB3073: The command "chmod +x /home/s0dy/source-build/bin/src/corefx.a28176b5ec68b6da1472934fe9493790d1665cae/artifacts/bin/testhost/netcoreapp-Linux-Release-x64/" exited with code 1.
      0 Warning(s)
      1 Error(s)

  Time Elapsed 00:01:41.74
  Build failed (exit code '1').

  'corefx' failed during build.
  See '/home/s0dy/source-build/bin/logs/corefx.log' for more information.
  'known-good' failed during build.
```

I have seen similar issues but I have not been able to fix my problem, i started the compilation from the build.sh script (dotnet/source-build)

Operating system: Exherbo linux

**Comment by ericstj** [comment]
Exherbo linux isn't in the supported set of platforms, so restore is failing to find the host dotnet since no compatible package exists, and then failing to chmod it (since it couldn't restore/copy it).
https://github.com/dotnet/corefx/blob/1b16f0f02f423e38b04a895677fcc46f0b91bdcf/external/runtime/runtime.depproj#L52-L57

It looks like you're trying to build on a new runtime, you won't be able to test until after you've built once, so you can probably disable this target entirely by specifying /p:BinPlaceTestSharedFramework=false.  Tests won't work until you've built enough of the stack to produce a host package for this distro.  Alternatively if you just want to build for this distro as if it were some other linux you could specify /p:PackageRid=linux-x64.

**Comment by ViktorHofer** [comment]
Closing as currently not supported and we haven't heard back for a month now.
