### ISSUE TITLE
WinHttpHandler null refs if IWebProxy.GetProxy returns null

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#38990]
```
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
          d:\repos\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(1048,0): at System.Net.Http.WinHttpHandler.SetRequestHandleProxyOptions(WinHttpRequestState state)
          d:\repos\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(1011,0): at System.Net.Http.WinHttpHandler.SetRequestHandleOptions(WinHttpRequestState state)
          d:\repos\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(852,0): at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state)
          d:\repos\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(528,0): at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
          d:\repos\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(156,0): at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
```

https://github.com/dotnet/corefx/blob/612a9fd54ae10bd7f470d64a236341e5f96fea3c/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L1047-L1048

cc: @davidsh

**Comment by davidsh** [comment]
>WinHttpHandler null refs if IWebProxy.GetProxy returns null

Officially `IWebProxy.GetProxy` is not [defined](https://docs.microsoft.com/en-us/dotnet/api/system.net.iwebproxy.getproxy?view=netcore-2.2#System_Net_IWebProxy_GetProxy_System_Uri_) to return null. It is only defined to return a proxy for the given uri assuming there is a proxy for it. Otherwise, it is assumed that `IWebProxy.IsBypassed` is called first and would return `true`. Thus a caller shouldn't call GetProxy().

This has been a source of problems over the years. The implementation of WebProxy.GetProxy() actually returns the uri passed in when there is no proxy. And other implementation we've done have returned null to indicate no proxy. So, we have tended to allow either to indicate no proxy and unofficially require callers to handle it. The assumption was always callers won't call GetProxy() because they are supposed to call IsBypassed() first.

**Comment by davidsh** [comment]
@stephentoub 

Looking at the WinHttpHandler code, the code is written to use the correct pattern.  It checks IsBypassed() first.  If IsBypassed() returns false, then it is expected that the proxy will return a valid uri to use for a given destination uri passed into GetProxy(). The fact that in this case GetProxy() returns null is an error in the implementation of the proxy. So, it's fine for it to throw an exception here.

https://github.com/dotnet/corefx/blob/612a9fd54ae10bd7f470d64a236341e5f96fea3c/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L1040-L1050

So, I don't think there is a bug to fix here.
