### ISSUE TITLE
HTTP2: How should cancellation work with duplex?

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#39049]
With duplex communication, we can still be sending the request body after SendAsync returns. If the CancellationToken passed to SendAsync fires after SendAsync returns, what should happen?

Looking at the code, I believe this will cause the request body send to be cancelled. However, this seems arguably wrong. It seems like the CancellationToken should not apply anymore once SendAsync has completed.

Thoughts?

@stephentoub @wfurt

**Comment by stephentoub** [comment]
Out of the various options, the current policy makes the most sense to me. Otherwise whether cancellation applies to some of the sending depends on a race condition, and there's no better way to signal the sender. It makes sense to me from an explainable perspective that SendAsync starts the content copy and this is token applied to the copy.

**Comment by geoffkizer** [comment]
Should the same apply to the response body, then? At least for HTTP/1.1 and SocketsHttpHandler, we haven't allowed the cancellationToken to cancel the response body receive once SendAsync has returned (assuming you use ResponseHeadersRead).

**Comment by geoffkizer** [comment]
> Otherwise whether cancellation applies to some of the sending depends on a race condition

I'm not sure that's the right way to look at it.

With duplex, we return as soon as we've sent the request headers and received the response headers. Cancellation applies to these actions. If either of these operations fail (including due to cancellation), then the whole operation is failed and any remaining work -- including both sending request body and receiving response body -- is cancelled.

After SendAsync returns, if there's a failure in either sending the request body or receiving the response body, then both sides are failed and remaining work cancelled.

At least, that seems like a reasonable way to look at it to me. Thoughts?

**Comment by stephentoub** [comment]
> After SendAsync returns, if there's a failure in either sending the request body or receiving the response body, then both sides are failed and remaining work cancelled.

An error in the response won't aggressively cancel the request body send; doing that would require a cancellation token to be passed into all aspects of the send (since a failure in receiving a response body isn't going to tear down the connection).

> I'm not sure that's the right way to look at it.

Why not?

SendAsync accepts a CancellationToken and initiates several operations, providing that CancellationToken to each.  That operation is transferring the request content and receiving the response headers; the cancellation token applies to both.  Once the response headers are received, the caller has access to the response stream and can provide a CancellationToken to the individual read operations performed on that stream, but there's no equivalent place to pass a CancellationToken to individual operations performed on the request stream.

If we say that the CancellationToken passed to SendAsync only applies to the sending of the request content until the response headers are received, then there absolutely is an inherent race condition here; the token would be applying to the sending of the request body, and then all of a sudden at some point it wouldn't.

**Comment by davidsh** [comment]
>From: @geoffkizer 
Looking at the code, I believe this will cause the request body send to be cancelled. However, this seems arguably wrong. It seems like the CancellationToken should not apply anymore once SendAsync has completed.

>From: @stephentoub 
If we say that the CancellationToken passed to SendAsync only applies to the sending of the request content until the response headers are received, then there absolutely is an inherent race condition here; the token would be applying to the sending of the request body, and then all of a sudden at some point it wouldn't.

I tend to agree with @stephentoub on this.  The intent of the HttpClient API and the cancellation token passed in is that is applies to the entire operation of sending request headers/body and receiving response header (and optionally body if HttpCompletionOption.ResponseContentRead is set or implied).

**Comment by geoffkizer** [comment]
> An error in the response won't aggressively cancel the request body send; doing that would require a cancellation token to be passed into all aspects of the send (since a failure in receiving a response body isn't going to tear down the connection).

An error in the response means RST_STREAM. That will abort the stream, and on the next attempt to write the request body, we will fail because the stream is aborted.

**Comment by stephentoub** [comment]
> on the next attempt to write the request body, we will fail because the stream is aborted.

Yes, but it won't interrupt any read currently happening. If we're talking about duplex, then the request body content is likely some producer/consumer, and SerializeToStreamAsync is going to be waiting for data to arrive that it can then send; that waiting won't be canceled.

**Comment by stephentoub** [comment]
@geoffkizer, are you ok with the status quo / closing this?

**Comment by stephentoub** [comment]
It occurred to me today that in the 95% case we're actually already in a state where the request body sending will ignore the cancellation token after SendAsync completes.  The 95% case is code using SocketsHttpHandler via HttpClient (rather than via, say, HttpMessageInvoker) and without changing Timeout.  In that case, HttpClient always manufactures a new token source / token specific to that request:
https://github.com/dotnet/corefx/blob/b6edaf0ac1ca42b48fd6c836f9bb472090d832a8/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L482-L490
and that token source gets disposed once SendAsync completes (in the case of ResponseHeadersRead, which is the only mode relevant to duplex):
https://github.com/dotnet/corefx/blob/b6edaf0ac1ca42b48fd6c836f9bb472090d832a8/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L586-L593
That means that even if the request body is polling or registering with the token after SendAsync has completed, it won't receive any further cancellation notifications, with the token remaining in the same uncanceled state it had been in prior to SendAsync completing.

Given this, plus the fact that we're not actually passing the cancellation token through to the CopyToAsync operation for any content types where this really matters (https://github.com/dotnet/corefx/issues/9071), seems like the best course of action for 3.0 is to just not pass the token to the request body sending.

**Comment by geoffkizer** [comment]
> @geoffkizer, you ok with that?

Yes

**Comment by scalablecory** [comment]
@geoffkizer I believe we landed on a behavior for 3.0, are we comfortable closing this issue or does this need further consideration?

**Comment by karelz** [comment]
Triage: We're ok to close it (incl. @geoffkizer).
