### ISSUE TITLE
Error while checking for terminated children

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#39060]
Hit in https://github.com/dotnet/coreclr/pull/25497 on Linux arm checked

```
  Discovering: JIT.jit64.XUnitWrapper
  Discovered:  JIT.jit64.XUnitWrapper
  Starting:    JIT.jit64.XUnitWrapper
Process terminated. Error while checking for terminated children. errno = 0
   at System.Environment.FailFast(System.String)
   at System.Diagnostics.ProcessWaitState.CheckChildren(Boolean)
   at System.Diagnostics.Process.OnSigChild(Boolean)
Aborted (core dumped)
```

**Comment by stephentoub** [comment]
cc: @tmds

**Comment by tmds** [comment]
This happens when this code returns < 0:

https://github.com/dotnet/corefx/blob/b10e8d67b260e26f2e47750cf96669e6f48e774d/src/Native/Unix/System.Native/pal_process.c#L639-L654

The man page says:

> If WNOHANG was specified in options and there were no children in a waitable state, then waitid() returns 0 immediately and the state of the siginfo_t structure pointed to by infop is unspecified. To distinguish this case from that where a child was in a waitable state, zero out the si_pid field before the call and check for a nonzero value in this field after the call returns. 

Maybe this is what is happening here, and `siginfo.si_pid` contains a `< 0` value.
When I try to reproduce this on x64, I get return `-1` with errno ECHILD.
The error occurred on Ubuntu.1604.Arm32.

I'll update the code to handle this case.
