### ISSUE TITLE
Symbols missing for sni.dll in dotnet sdk 2.1.505

### ISSUE THREAD

**Issue by IlyaBiryukov** [dotnet/corefx#39169]
Our binskim run couldn't find symbols for sni.dll. We use dotnet sdk 2.1.505.

Component :
bin\Debug\Cascade.Services.Core\publish\runtimes\win-arm64\native\sni.dll

Bug:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/939989

**Comment by ericstj** [comment]
SNI is built outside corefx by the SQL team.  @saurabh500 can you follow up and make sure you're publishing symbols for this where tools expect to find them?

**Comment by divega** [comment]
Pinging SqlClient owners @david-engel, @AfsanehR @Gary-Zh.

**Comment by danmosemsft** [comment]
@markwilkie I believe we now have an automated check that our managed binaries have uploaded symbols. We may be missing such a step for our native binaries?

**Comment by cheenamalhotra** [comment]
@corivera @geleems

Do you know anything related to SNI Symbols since @saurabh500 is OOF.

**Comment by ericstj** [comment]
Please try to get symbols published matching the build of SNI that ships in the next release.

**Comment by danmosemsft** [comment]
@cheenamalhotra is this on your radar for 3.1 timeframe?

**Comment by danmosemsft** [comment]
This is definitely owned by the Data team 😄

**Comment by ericstj** [comment]
This is built out of an internal repository set up by @saurabh500.  I found it here: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/b2175e18-4168-41d2-966f-d886ad052cb5?_a=history

I believe the 2.0 release build is here: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=857588

The files appear to be here: \\cpvsbuild\drops\SNI\DotNet-CoreFx-SNI\20170712.01

I believe you can fix this issue by manually submitting symbols for this post-hoc.  It might be interesting for you to enable that in your build pipeline if you plan to build this component regularly.  Given you haven't done that since July 2017, maybe not a priority.

**Comment by ericstj** [comment]
So I was going to help out here by indexing this, but first thought I'd double check the original issue (so I could see failure first, then fix the failure).  Turns out this is no-repro.

The following all work for me:
```
C:\Users\ericstj\.nuget\packages>\Debuggers\symchk /s https://msdl.microsoft.com/download/symbols /ob /op /r sni.dll
SYMCHK: C:\Users\ericstj\.nuget\packages\runtime.win-arm64.runtime.native.system.data.sqlclient.sni\4.4.0\runtimes\win-arm64\native\sni.dll PASSED  - PDB: sni.pdb DBG: <N/A>
SYMCHK: C:\Users\ericstj\.nuget\packages\runtime.win-x64.runtime.native.system.data.sqlclient.sni\4.4.0\runtimes\win-x64\native\sni.dll PASSED  - PDB: sni.pdb DBG: <N/A>
SYMCHK: C:\Users\ericstj\.nuget\packages\runtime.win-x86.runtime.native.system.data.sqlclient.sni\4.4.0\runtimes\win-x86\native\sni.dll PASSED  - PDB: sni.pdb DBG: <N/A>
SYMCHK: C:\Users\ericstj\.nuget\packages\runtime.win7-x64.runtime.native.system.data.sqlclient.sni\4.3.0\runtimes\win7-x64\native\sni.dll PASSED  - PDB: sni.pdb DBG: <N/A>
SYMCHK: C:\Users\ericstj\.nuget\packages\runtime.win7-x86.runtime.native.system.data.sqlclient.sni\4.3.0\runtimes\win7-x86\native\sni.dll PASSED  - PDB: sni.pdb DBG: <N/A>

SYMCHK: FAILED files = 0
SYMCHK: PASSED + IGNORED files = 5
```

I was able to locate symbols for all stable versions of sni.dll on both http://symweb and https://msdl.microsoft.com/download/symbols

Closing this as no-repro.
