### ISSUE TITLE
Provide the way to ensure the required length before formatting from ISpanFormattable

### ISSUE THREAD

**Issue by aobatact** [dotnet/corefx#39198]
# Provide the way to ensure the required length before formatting from ISpanFormattable

## Issue
Current design of ISpanFormattable doesn't tell the required length, and the current usage like `StringBuilder.AppendSpanFormattable` retry to format by using `ToString`  when we fail to format in `TryFormat`. This makes a performance issue.
Since the `ISpanFormattable` is not  public yet, there is a chance to change it.

## Proposed Api

```csharp
    internal interface ISpanFormattable
    {
        bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider provider);

        int RequiredCharsLength(ReadOnlySpan<char> format, IFormatProvider provider);
    }
```

## Benchmark
``` ini

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17134.829 (1803/April2018Update/Redstone4)
Intel Core i7-7700K CPU 4.20GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.0.100-preview4-011223
  [Host]     : .NET Core 3.0.0-preview4-27615-11 (CoreCLR 4.6.27615.73, CoreFX 4.700.19.21213), 64bit RyuJIT
  DefaultJob : .NET Core 3.0.0-preview4-27615-11 (CoreCLR 4.6.27615.73, CoreFX 4.700.19.21213), 64bit RyuJIT


```
|                   Method |     Mean |     Error |    StdDev |
|------------------------- |---------:|----------:|----------:|
|           EnoughCapacity | 31.52 ns | 0.1802 ns | 0.1686 ns |
|        NotEnoughCapacity | 88.07 ns | 0.9511 ns | 0.8896 ns |
|    Enough_EnsureCapacity | 35.96 ns | 0.2609 ns | 0.2312 ns |
| NotEnough_EnsureCapacity | 50.22 ns | 0.2931 ns | 0.2742 ns |

```csharp
public class AppendCapacity
{
    private int value;

    [GlobalSetup]
    public void SetUp()
    {
        value = (new Random()).Next();
    }

    [Benchmark]
    public void EnoughCapacity()
    {
        var sb = new StringBuilder();
        sb.Append(value);
    }
    
    [Benchmark]
    public void NotEnoughCapacity()
    {
        var sb = new StringBuilder(1);
        sb.Append(value);
    }
    [Benchmark]
    public void Enough_EnsureCapacity()
    {
        var sb = new StringBuilder();
        var c = CountDigits((uint)value);
        sb.EnsureCapacity(c);
        sb.Append(value);
    }

    [Benchmark]
    public void NotEnough_EnsureCapacity()
    {
        var sb = new StringBuilder(1);
        var c = CountDigits((uint)value);
        sb.EnsureCapacity(c);
        sb.Append(value);
    }

    //from System.Buffers.Text.FormattingHelpers.CountDigits
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int CountDigits(uint value)
    {
        int digits = 1;
        if (value >= 100000)
        {
            value = value / 100000;
            digits += 5;
        }

        if (value < 10)
        {
            // no-op
        }
        else if (value < 100)
        {
            digits += 1;
        }
        else if (value < 1000)
        {
            digits += 2;
        }
        else if (value < 10000)
        {
            digits += 3;
        }
        else
        {
            Debug.Assert(value < 100000);
            digits += 4;
        }

        return digits;
    }
    
}
```
## Related
#30114

**Comment by EgorBo** [comment]
`RequiredCharsLength` should have `ReadOnlySpan<char> format, IFormatProvider provider` parameters then I guess.

**Comment by aobatact** [comment]
> RequiredCharsLength should have ReadOnlySpan<char> format, IFormatProvider provider parameters then I guess.

That's right, I'll fix it.

**Comment by stephentoub** [comment]
I'm not seeing the benefit here.

First, it's not cheap for some implementations to determine how many characters are needed; they essentially need to actually do the whole formatting routine to determine it. For those where it is cheap, TryFormat already does that up front and bails out early.

Second, StringBuilder currently falls back to ToString because the case where a) there isn't enough room and b) perf matters is rare: in general in such cases your formatting into a cached builder that already has a lot of space... paying to computer the length a second time is unnecessary overhead door the common case.

Third, the ToString fallback is currently done out of convenience / code minimization for the less common case, but there's nothing preventing the implementation from instead growing the buffer and trying again. Yes, it might need to repeat until the buffer grew big enough, but we're already in the less common case, and in that less common case one grow would generally be big enough for almost all kinds of values.

Finally, this interface isn't public. If we were to make it public, it would require a full design / review process, for which the existing issue is sufficient. You're welcome to comment on that issue, but I don't think a second issue is needed here.

**Comment by stephentoub** [comment]
Closing as dup of #30114. Suggestions on shape for if/when the API is exposed can be made there. Thanks.
