### ISSUE TITLE
System.Security.Cryptography.Native fails to build on OSX El Capitan (10.11)

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#3924]
It looks like that El Capitan may have removed the OpenSSL headers we depend on.  @gkhanna79 is hitting some issues locally because `openssl/asn1.h` is not found.

It would appear that the libraries we link against are still present in El Captian (so the .dylib we build should still run there) we just can't seem to build it out of the box.

We need to figure out what the correct work around is (does installing the previous version of XCode or the command line compiler tools work, or maybe we need to get the headers via homebrew or something else)?

The fact that Apple is on a 0.9.8 version of OpenSSL seems like it will also hurt us in obtaining the correct headers from a reasonably up to date package manager.

**Comment by ellismg** [comment]
/cc @bartonjs 

I am going to play around with upgrading to El Capitan once I have figured out a way to ensure I can roll back to 10.10 if needed.

**Comment by akoeplinger** [comment]
Apple deprecated their OpenSSL and removed the headers in El Capitan: http://lists.apple.com/archives/macnetworkprog/2015/Jun/msg00025.html

**Comment by gkhanna79** [comment]
I uninstalled XCode 7 and reinstalled XCode 6.4 with its command line tools - corefx repo builds cleanly now. Our guidance for folks on El Capitan should be to stick with Xcode 6.4 toolset until we figure out the story with XCode 7.

**Comment by jasonwilliams200OK** [comment]
I am able to build with latest XCode 7 (yesterday's update applied) on El Capitan. Echoing my own comment (from https://github.com/dotnet/corefx/pull/4026#discussion_r42769369):

> I upgraded a new mac as is to El Capitan (v10.11.1) and it wasn't succeeding `git clean -xdf; ./build.sh native` with latest AppleClang / Xcode (yesterday's updates) applied. I had to run `brew link --force openssl` (yeah i had to install brew first). Now it compiles 100% there as well.

**Comment by jasonwilliams200OK** [comment]
Oh, I also ran `brew install openssl` before, while i was at it :smile:

**Comment by bartonjs** [comment]
The best situation that I'm seeing is:
```
brew install openssl
brew link --force openssl
./build.sh native clean
```

This happens to upgrade the mac to OpenSSL 1.0.2d.  Aside from one small error in our detection for `HAVE_SSL_CIPHER_SPLIT_ALGORITHMS` (LocalFixed) this seems to work fine.

Since I'm not a mac person I don't know if this is onerous, acceptable, or preferred (getting an OpenSSL that wasn't built from the stone-ages).  @ellismg or @stephentoub do you have particular thoughts?

There's also a possibility we actually want to stop trying to support 0.9.8 and force all mac users to switch to the brew version.  According to https://www.openssl.org/blog/blog/2014/12/23/the-new-release-strategy/:

> Back in October we announced the End Of Life of version 0.9.8. This version is currently only receiving security updates, and support will cease completely on 31st December 2015.

I verified using `dtruss` that the correct OpenSSL was being found at runtime.  I think that cmake's find_package did wonderful things for us here, since I read horror stories about the possibility of getting the 1.0.x headers from brew, but the loader preferring /usr/lib/libcrypto.dylib.

**Comment by stephentoub** [comment]
> There's also a possibility we actually want to stop trying to support 0.9.8 and force all mac users to switch to the brew version.

That sounds like the right approach to me.  We can't deliver a solution that relies on something that's going to be completely out of support before we even ship.

**Comment by ellismg** [comment]
Previously we had done work (at the request of ASP.NET) to remove the requirement of using homebrew to pull down dependencies for the runtime and framework, since the OSX deployment model was "download a binary distribution of DNX and expect things to work".  IIRC, the current DNX instructions no longer even use homebrew, so this might re-introduce friction.  @danroth27 @davidfowl What do you think about this?  Both options seem "bad" either running on a library that has been EOL'd or forcing folks to brew install packages to run non trivial programs.

**Comment by bartonjs** [comment]
We're pretty solidly on the plan of OpenSSL >= 1.0.0 for RTM (#4737), which solves the build problem on 10.11; so I'm closing this.
