### ISSUE TITLE
ConnectTest.ConnectAsync_AddHostHeader_Success test failing on all platforms

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39271]
```
      System.Net.WebSockets.Client.Tests.ConnectTest.ConnectAsync_AddHostHeader_Success [FAIL]
        System.Net.WebSockets.WebSocketException : The server returned status code '404' when status code '101' was expected.
        Stack Trace:
          D:\repos\corefx\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WebSocketHandle.Managed.cs(181,0): at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
          D:\repos\corefx\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\ClientWebSocket.cs(152,0): at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
          d:\repos\corefx\src\System.Net.WebSockets.Client\tests\ConnectTest.cs(118,0): at System.Net.WebSockets.Client.Tests.ConnectTest.ConnectAsync_AddHostHeader_Success()
          --- End of stack trace from previous location where exception was thrown ---
```
It's talking to the remote echo server, and it's getting back a 404.
https://github.com/dotnet/corefx/blob/b8a7f34e1b64e5c594f591aa8683f34506eb9736/src/System.Net.WebSockets.Client/tests/ConnectTest.cs#L96

cc: @davidsh

**Comment by davidsh** [comment]
>It's talking to the remote echo server, and it's getting back a 404.

I suspect this is a transient Azure networking issue and not directly related to the remote endpoint itself.  There are no 404 errors that have been returned in the last 24 hours.
![image](https://user-images.githubusercontent.com/7684835/60774137-b27bc200-a0c4-11e9-9d46-6d2413717a80.png)

**Comment by stephentoub** [comment]
I don't think it's transient.  I've been hitting this every time I run locally for the last hour, and I hit it every outerloop run I did in CI yesterday and the day before.

**Comment by davidsh** [comment]
Well, it still probably is an Azure infrastructure issue that we don't have any control over.

**Comment by davidsh** [comment]
Otherwise it an error with our client-side networking and perhaps the uri being used has been malformed in some way. We would need to get a network trace and see exactly what the test is sending on the network.

**Comment by stephentoub** [comment]
@davidsh, this is trivial to repro, on both .NET Framework and .NET Core:
```
using System;
using System.Net.Http;

class Program
{
    static void Main(string[] args)
    {
        var client = new HttpClient();
        client.DefaultRequestHeaders.Host = "subdomain.corefx-net-http11.azurewebsites.net";
        Console.WriteLine(client.GetStringAsync(@"http://corefx-net-http11.azurewebsites.net/").Result);
    }
}
```

**Comment by davidsh** [comment]
Is this a new test? If not, did it used to work and now is broken?

Why would we expect this test to work? It is setting the host header to a subdomain of the actual site. So, I would expect the endpoint to return a 404 actually.

I think the problem might be due to the fact that the Azure remote endpoint is running on Azure App Service.  Several months ago it used to run on a different endpoint http://corefx-net.cloudapp.net. But we've deprecated that endpoint, #36018.

And it might now be interpreting host headers to redirect the website to something else. So, I think we need to disable this test.

**Comment by stephentoub** [comment]
> Is this a new test?

No.

> If not, did it used to work and now is broken?

Yes.  It was added over two years ago.
https://github.com/dotnet/corefx/commit/17473cbb1a33c1851bbfdd5083ae0d25bd7e553f

**Comment by davidsh** [comment]
Website endpoints can be configured to use 'Host' headers to redirect to different websites. That is how a lot of ISPs work because it enables multiple websites to be hosted on a single IP address.

Azure App Service has a front-end to it and I think it has been changed to interpret 'Host' headers now. We didn't make any specific config changes lately to this remote endpoint.

**Comment by davidsh** [comment]
This is the current "Custom Domains" configuration for the endpoint. It doesn't  have any listing other than the main domain. So, I'm surprised this test ever worked once #36018 was merged.

![image](https://user-images.githubusercontent.com/7684835/60774383-22d81280-a0c8-11e9-89dd-5c884e7356fd.png)

Perhaps Azure has made some changes recently to enforce the proper 'Host' name mapping.

**Comment by davidsh** [comment]
>Yes. It was added over two years ago.

I recommend we move this test to a loopback server test where we verify things more easily. This test really only needs to verify that the 'Host' request header is properly sent to the server.
