### ISSUE TITLE
Dropped HTTP/2 response / response streams remain rooted

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39420]
SocketHttpHandler's Http2ReadStream doesn't have a finalizer to handle the case where the caller drops the stream without disposing of it.  But even if it did, it wouldn't be called today, because the response stream remains rooted: Http2Connection maintains a strong table of all active Http2Stream instances, each of which has a strong reference to its HttpResponseMessage, which has a strong reference to the Http2ReadStream.

**Comment by geoffkizer** [comment]
Yuck. Thanks for finding.

We need a reference from Http2Stream->HttpResponseMessage while we are processing response headers. This is fine, since as long as we're still waiting for headers to arrive, SendAsync hasn't completed yet.

Once we receive the response headers, I think we can drop the reference to the HttpResponseMessage. There may be some trickiness with trailing headers here, but I think we can make it work.

Thus, once SendAsync completes, we won't have a circular reference here anymore.

We will still need a finalizer on Http2ReadStream.

**Comment by stephentoub** [comment]
> I think we can drop the reference to the HttpResponseMessage. There may be some trickiness with trailing headers here, but I think we can make it work.

Yes, though my guess is we wouldn't drop it outright but would instead convert it to a weak reference.

**Comment by geoffkizer** [comment]
Why a weak reference?

**Comment by stephentoub** [comment]
Because you need to be able to access it to set trailers.

**Comment by geoffkizer** [comment]
I think we have other issues with trailing headers and HTTP2, unfortunately. See #39427.

If we change trailing header processing as I suggest in that issue, then I think we can avoid holding on to the HttpResponseMessage after SendAsync completes.

**Comment by stephentoub** [comment]
You still need to be able to get the headers into the TrailingHeaders collection at the end. Either we do that via the response message, in which case it needs to be a weak reference, or we do it by holding onto the collection itself and validate that that collection doesn't have a back reference.

**Comment by geoffkizer** [comment]
We can hold on to it on the response stream object. That's what we do for HTTP/1.1.

**Comment by stephentoub** [comment]
How do you get to the response stream object? Or you're saying the response stream would pull in the headers at the end? Seems reasonable.

**Comment by geoffkizer** [comment]
Yes, when the response stream gets EOF from an attempt to read, it should then populate any trailing headers on to the HttpResponseMessage object.

**Comment by stephentoub** [comment]
Will submit a PR.
