### ISSUE TITLE
Are there any reasons why the System.Web.HttpUtility is sealed class?

### ISSUE THREAD

**Issue by Marusyk** [dotnet/corefx#39514]
HttpUtility is sealed class and contains only static methods
https://github.com/dotnet/corefx/blob/b75421a0035bf3a44e1f68447255470d57074dbb/src/System.Web.HttpUtility/src/System/Web/HttpUtility.cs#L41

Can it be changed to static class?

**Comment by davidsh** [comment]
It is sealed because the type already existed in .NET Framework:
https://docs.microsoft.com/en-us/dotnet/api/system.web.httputility?view=netframework-4.8

Changing this would be an API change and could break existing app. What is the motivation for wanting to change it?

**Comment by Marusyk** [comment]
Ok, I see.
But it doesn't make any sense to create and use an instance of `HttpUtility `. So, I hope that this shouldn't  break existing apps. 

> What is the motivation for wanting to change it?
Just working on a similar task  https://github.com/dotnet/corefx/issues/39308

**Comment by bartonjs** [comment]
It doesn't look like `HttpUtility` declares a private ctor, so making it `static` would technically be a breaking change.

Since there are no instance methods, it shouldn't really be a thing people were doing; but there's not really an argument for making the change other than tidiness.  (It would prevent creating a new method as non-static, but testing should really catch that.)
