### ISSUE TITLE
[3.0 servicing] Determine what we do to improve package harvesting story for 3.0

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#39537]
See https://github.com/dotnet/arcade/issues/2929

We need to decide how much of this we tool for 3.0 servicing.

**Comment by joperezr** [comment]
My plan here would be to basically do two things:

- [ ] For 3.0, I would add a test on the all configurations leg that will go and ensure that for every package that has harvested assets, we will make sure that the package version we used to harvest is the latest of that era. For example, if we are harvesting package 4.5.1, the test will make sure that we haven't shipped a 4.5.x where x is greater than 1. This test should be added to release/3.0 branch.
- [ ] For Future, we can finish the spec for multi-package harvesting feature, and we can decide when would it be a good time to do that. After chatting offline with @ericstj we are not yet sure if this would be very useful, as in theory it should always be fine to harvest from the latest package of the previous era, since if there is a servicing that happens 2 eras away, eventually the previous era will have to re-service again with that fix.

**Comment by ericstj** [comment]
Indeed, maybe even to avoid having to specify the version of the package to harvest from we just change how we compute that version.  Instead of latest-stable we compute latest-stable of the last minor version.

Thinking more about the test: how will the test function when we are sim-shipping out of multiple internal branches and haven't yet published to nuget.org.  What do we do to keep ourselves correct in this case?

**Comment by ericstj** [comment]
After some discussion we're thinking to do the following:
1. Catch when a package is harvesting from a version that isn't latest for the era its harvesting.
2. By default, don't harvest from the last stable, but harvest from the last stable of the previous era.
3. Add a target to corefx that updates the packageIndex and harvest package references based on the data we find on nuget feeds, and direct folks to run that target when 1 fails.

**Comment by ViktorHofer** [comment]
@joperezr can you please provide a status update? Do you think this will be ready by Tuesday? thanks

**Comment by joperezr** [comment]
Yes, I'm done with all changes in arcade now. I'm working on the corefx master PR now and once that is in I will create the 3.0 PR
