### ISSUE TITLE
Question : ValueTask or warning because of not using await

### ISSUE THREAD

**Issue by christophedemey** [dotnet/corefx#39566]
Hi

I have an interface from an external library which i have to adhere by.
It looks like this :
```
public Task<RealestateObject> Handle(RealEstatePushRequestModel request, CancellationToken cancellationToken)
{
}
```
I only have synchronous code that is required in this block.
Is it better make the function async and just return the result : 
```
public async Task<RealestateObject> Handle(RealEstatePushRequestModel request, CancellationToken cancellationToken)
{
    //Much synchronous code here...
    return new RealestateObject();
}
```
Which warns me :
**This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do** 

**OR**

I await ValueTask and return that : 
```
public async Task<RealestateObject> Handle(RealEstatePushRequestModel request, CancellationToken cancellationToken)
{
    return await GetValue(request);
}

public ValueTask<RealestateObject> GetValue(RealEstatePushRequestModel request)
{
    //Much synchronous code here...
    return new ValueTask<RealestateObject>(new RealestateObject() { ObjectKey = "dummydata" });
}
```
Which has no warnings at all.

**OR** 

use **Task.FromResult**.
```
public Task<RealestateObject> Handle(RealEstatePushRequestModel request, CancellationToken cancellationToken)
{
    //Much synchronous code here...
    return Task.FromResult(new RealestateObject() { ObjectKey = "dummydata" });
}
```

Which one of the scenario's is the best to use ?

Thanks!

**Comment by Wraith2** [comment]
I would choose option 3. Your code isn't doing any async work so there is no benefit to using a compiler generated state machine. ValueTask is not relevant to this use case. You may want to check the cancellation token to throw an exception or return an appropriate value.

**Comment by stephentoub** [comment]
What @Wraith2 said.

Your second approach with `ValueTask` is just adding unnecessary cost and complexity, solely to confuse the compiler's analysis in order to avoid the warning, but it logically has the same condition the compiler is trying to flag: you've got an async method and you're always completing synchronously.

I'd recommend either just suppressing the warning, or not using `async` in the signature and just using Task.FromResult.  If you do the latter, you'll also want to consider adding a try/catch block, and in the catch block returning any exceptions via a Task.FromException (and potentially cancellation via Task.FromCanceled)... `async` does that for you.

**Comment by christophedemey** [comment]
Thanks for the info! :)
