### ISSUE TITLE
CI not running for PRs

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#39593]
CI is currently not running for PRs and don't show up in checks:

![image](https://user-images.githubusercontent.com/1142958/61467434-82a9a580-a973-11e9-8bca-e164baf793bc.png)

Examples https://github.com/dotnet/corefx/pull/39560 https://github.com/dotnet/corefx/pull/39574 https://github.com/dotnet/corefx/pull/39584 https://github.com/dotnet/corefx/pull/39585 https://github.com/dotnet/corefx/pull/39587 https://github.com/dotnet/corefx/pull/39588 https://github.com/dotnet/corefx/pull/39589 https://github.com/dotnet/corefx/pull/39590 https://github.com/dotnet/corefx/pull/39591 https://github.com/dotnet/corefx/pull/39455 https://github.com/dotnet/corefx/pull/39594

**Comment by stephentoub** [comment]
@dotnet/dncenghot, CI isn't running for coreclr or corefx.

**Comment by MattGal** [comment]
Self-assigned before realizing it was a corefx, not core-eng issue :)  I'm looking into it either way;  seems to be related to yesterday's massive outage.

**Comment by MattGal** [comment]
This should be unblocked (close / reopen your PRs to be certain).

Root cause : The GitHub app for AzDO pipelines seems to have been flipped to only work for the Nuget BuildTasks repo.  This might be related to the outage, or human error; we're following up to figure out why but please check and confirm you are unblocked.

**Comment by benaadams** [comment]
Seems to be working; thank you
