### ISSUE TITLE
HttpCompletionOption.ResponseHeadersRead is causing deadlock in .NET Framework

### ISSUE THREAD

**Issue by wrathofodin** [dotnet/corefx#39615]
This bug is not present in CoreFX (which is good news).

This is only present when using the full .NET Framework (as it's not using CoreFX)

Run this code using any .NET Framework version (I used 4.8) and then run it using .NET Core. 
```csharp
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    private static readonly Uri Address = new Uri("https://google.com/");

    public static HttpClient HttpClient = new HttpClient { BaseAddress = Address };
    private const int NumberOfTasks = 100;

    static void Main(string[] args)
    {
        var tasks = new List<Task>();
        for (var i = 0; i < NumberOfTasks; i++)
        {
            tasks.Add(SendRequest(i));
        }

        Task.WaitAll(tasks.ToArray());

        Console.ReadKey();
    }

    static async Task SendRequest(int i)
    {
        var response = await HttpClient.SendAsync(new HttpRequestMessage(HttpMethod.Get, "/"), HttpCompletionOption.ResponseHeadersRead, CancellationToken.None).ConfigureAwait(false);
        Console.WriteLine($"{i}:{response.StatusCode}");
    }
}
```

Related issue: https://github.com/reactiveui/refit/issues/449

Possible location:

https://github.com/microsoft/referencesource/blob/aaca53b025f41ab638466b1efe569df314f689ea/System/net/System/Net/Http/HttpClient.cs#L433-L441

**FIX**

Most probably `TaskCompletionSource.TrySetResult` is causing this https://github.com/microsoft/referencesource/blob/aaca53b025f41ab638466b1efe569df314f689ea/System/net/System/Net/Http/HttpClient.cs#L714 . See this issue for details: https://github.com/EventStore/EventStore/issues/1179

> Thankfully the fix is pretty simple - either you can wrap _source.SetResult in Task.Run OR every TaskCompletionSource can be constructed with TaskCreationOptions.RunContinuationsAsynchronously

The fix would be here: https://github.com/microsoft/referencesource/blob/aaca53b025f41ab638466b1efe569df314f689ea/System/net/System/Net/Http/HttpClient.cs#L387

replace with:

`TaskCompletionSource<HttpResponseMessage> tcs = new TaskCompletionSource<HttpResponseMessage>(TaskCreationOptions.RunContinuationsAsynchronously);`

Not a big issue for me as I'm using .NET Core anyway (except for WPF apps until 3.0 comes out) but it would be nice if you could release a patch for 4.8 that fixes this bug

**Comment by stephentoub** [comment]
This is a bug in your repro: you're not disposing of the HttpResponseMessage that's returned from SendAsync.

With ResponseHeadersRead, you're telling HttpClient not to read the response body, that you are taking on that responsibility.  As such, it's giving you back an HttpResponseMessage with a response Stream that still has data to be read and that references a still open connection.  You need to tell the system that you're done with it by disposing of the HttpResponseMessage and/or its response Stream.

This is still an issue on .NET Core, you just see the affects of it differently because on .NET Core, by default the system doesn't place a limit on the number of outstanding connections per endpoint, whereas in .NET Framework it defaults to 2.  If you add:
```C#
 ServicePointManager.DefaultConnectionLimit = int.MaxValue;
```
at the beginning of your Main method, you'll see the Task.WaitAll complete.

**Comment by wrathofodin** [comment]
Damn, you're right. It works with dispose. So that was the problem.

**Comment by wrathofodin** [comment]
But does it mean that ResponseContentRead automatically disposes the underlying stream used in HttpContent? Or is dispose also needed when using ResponseContentRead?
