### ISSUE TITLE
Generalized serialization surrogate support

### ISSUE THREAD

**Issue by zhenlan** [dotnet/corefx#3963]
Provide a solution for types that are serializable on desktop .NET but not on .NET Core

**Comment by shmao** [comment]
The issue actually implies two issues: 

   **Issue 1**. As ISerializable is not available on NetCore, we wanted to see whether it's possible for NetCore to serialize types that implement ISerializable interface on desktop .Net with the help of DataContract surrogate so that objects serialized on desktop can be deserialized on NetCore, and vice versa. Unfortunately, the answer is no.  Because on desktop DataContractSerializer has special methods handling the serialization of ISerializable types and generate special Xmls for ISerializable types, I didn't find a nice solution for us to generate ISerializable like Xml using DataContract serializer. 
   
   **Issue 2**. In scenarios where users do not control the creation of DataContractSerializer, we wanted to have a mechanism for users to set up DataContract surrogate for the DataContractSerializers of non-serializable types. We found that WCF already has an existing way to allow users to set surrogate for types, see [Data Contract Surrogates in WCF](https://msdn.microsoft.com/en-us/library/ms733064(v=vs.110).aspx#Anchor_2). We decided to let WCF to decide whether to support this feature on NetCore.  
   
   For now we don't take any actions on this issue.
