### ISSUE TITLE
No support for file extended attributes metadata

### ISSUE THREAD

**Issue by lastlink** [dotnet/corefx#39642]
## Problem
Should be an api for setting a files extended attributes such as created and author.

**Comment by Wraith2** [comment]
Why? What is the common use case? Which platforms support extended metadata and do they do so in similar ways?

**Comment by lastlink** [comment]
Well nodejs has an npm module that will let you do it. https://www.npmjs.com/package/ffmetadata
rust has a few libraries such as https://github.com/Stebalien/xattr as well as https://docs.rs/rexiv2/0.7.0/rexiv2/.
From what I could tell on windows you can do it with bat or powershell, but not on a mac or linux using c#.

**Comment by Wraith2** [comment]
Those three libraries do very different things. The only one that is filesystem extended attributes Is xattr, the other two use format specific metadata libraries/capabilities. Windows has extended attribute capability but they're almost never used, they may be used more on other platforms but I think it's still quite rare. 

There would need to be a compelling use case for them to be included in the BCL.

**Comment by Zenexer** [comment]
@Wraith2 xattrs are pretty important in the Linux world, although they’re not often used directly by end users. Some examples:

1. SELinux—this is pretty common, and interfacing with these attributes may be necessary for an application to install or run properly
2. Windows-compatible ACLs, particularly when dealing with network shares (SMB/CIFS)—they’re not just for Windows compatibility, but they work similarly, so they’re often used for that purpose.
3. Giving executables specific capabilities (somewhat comparable to UAC)
4. Storing metadata like checksum,author, or title—this is uncommon and probably less than ideal, but it is supported.

The xattr interface itself is pretty simple: it’s just a per-file key-value store. It might make sense to expose that functionality in BCL, but I don’t think it makes sense to implement specific attributes. The only exception might to allow ACLs to be managed the same way on both Linux and Windows, but I know nothing about how Windows ACLs are exposed by BCL; for all I know, they aren’t exposed at all.

@lastlink, it doesn’t sound like you’re asking for actual extended attributes, though. It sounds more like you’re interested in metadata stored within a file, rather than in its inode, or that you may be confusing the two. xattrs generally don’t travel with a file and shouldn’t contain a “creator” or “author” under normal circumstances. (If by “created” you mean “file creation timestamp,” Linux doesn’t offer that directly, but some filesystems choose to store it. It is not stored as an extended attribute and isn’t normally shown by filesystem tools without additional flags.)

**Comment by lastlink** [comment]
Ok this discussion was helpful, I guess meta is directly related to the file type such as an mp3, pdf, or epub.
