### ISSUE TITLE
Marshal.SizeOf<char>() is one byte, not two, by default

### ISSUE THREAD

**Issue by Turnerj** [dotnet/corefx#39641]
I couldn't find documentation on this whether it is actually intended though when you marshal a `char` (or a `struct` with a `char` in it), it is very easy to cause heap corruption when then allocating memory to it.

I believe the issue comes from the difference between the size of a `char` and the value that `Marshal.SizeOf<char>()` returns. According to [MSDN](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/char), a `char` is a 16-bit value though when you use `Marshal.SizeOf<char>()`, it only returns one (byte).

In some fairly basic tests, I could reproduce this issue.

```csharp
public struct CharStruct
{
	public char MyValue;

	public CharStruct(int myValue)
	{
		MyValue = (char)myValue;
	}
}
```

And the following test:
```csharp
var maxSize = 1000;
var individualSize = Marshal.SizeOf<CharStruct>();
var totalSize = individualSize * maxSize;
var operationsHandle = Marshal.AllocHGlobal(totalSize);
var operations = new Span<CharStruct>(operationsHandle.ToPointer(), maxSize);

for (int i2 = 0; i2 < maxSize; i2++)
{
	operations[i2] = new CharStruct(123);
}

var localSlice = operations.Slice(maxSize / 2);
var result = localSlice.ToArray();
Marshal.FreeHGlobal(operationsHandle);
```

Sometimes it works fine. Sometimes I will get a `StackOverflowException` and it will terminate. Sometimes I will get "Internal CLR Error". Sometimes Visual Studio will terminate the program because invalid memory access. Most of the time though, I get a heap corruption and the process will terminate. The higher you have `maxSize`, the more likely it will crash in my tests. 

After a few days of debugging, I did realise I can work around this issue with the `MarshalAs` attribute and specify a two-byte value but at that point it makes me wonder if there is actually a reason why `char` is considered one byte by `Marshal.SizeOf` anyway as it would seem like it always would be an issue.

Did I miss some super obvious documentation that states that a `char` should be one byte if marshaled? If this is intended, may I ask why a `char` is only represented as one byte?

If it isn't intended, could `Marshal.SizeOf` return 2 instead of one for `char` by default?

Version: .NET Core 3 Preview 5

**Comment by mikedn** [comment]
The big question is what you are trying to `Marshal.SizeOf` for, the sample code you show has nothing to do with marshaling. You may be looking for `sizeof(char)` or `Unsafe.SizeOf<char>()`.

As for why `Marshal.SizeOf` returns a certain value, that's basically because it tries to accommodate the OS the program runs on. On Linux/macOS that's normal because they use UTF-8 so their `char` is 1 byte. On Windows it's a bit of mess because it basically tries to accommodate Win9x, which used ANSI and it's long gone, but all recent versions of Windows use UTF-16 so it's a bit confusing that you get 1 byte. But then if you actually do marshaling you'd probably know that.

See https://docs.microsoft.com/en-us/dotnet/standard/native-interop/charset

**Comment by Turnerj** [comment]
I'm pretty new to dealing with unmanaged memory but I'm pretty sure `Marshal.AllocHGlobal(totalSize)` is literally doing marshaling - let me know if that is wrong though. I'll be honest, I don't know if this is the best way to work out the size of the allocation I want or not, just what I found for my own searching.

That sample code is based [this code](https://github.com/Turnerj/TextDifferenceBenchmarking/blob/e3a19624862dba0b34f68e2723b34c06c61d614c/TextDifferenceBenchmarking/DiffEngines/DmitryBestParallelResultArrayMarshal.cs#L118-L154) which is me attempting to optimise allocations (which it does, having about a 1/3rd of the allocations that a [non-marshaled version](https://github.com/Turnerj/TextDifferenceBenchmarking/blob/master/TextDifferenceBenchmarking/DiffEngines/DmitryBestParallelResultArray.cs#L118-L148) does).

Thanks for the explanation about why it might be giving 1 byte though - I didn't think about Linux/macOS. I am on Windows though so yeah, seems a little strange that is the case.

**Comment by Turnerj** [comment]
Oh, I think I get what you mean now and I think you're right - I'm actually wanting `Unsafe.SizeOf<char>()` and not `Marshal.SizeOf<char>()`.

**Comment by Turnerj** [comment]
Yep, entirely just my misunderstanding of how to get the `SizeOf` I am actually wanting.

**Comment by mikedn** [comment]
> I'm pretty new to dealing with unmanaged memory but I'm pretty sure Marshal.AllocHGlobal(totalSize) is literally doing marshaling - let me know if that is wrong though.

No, it just a native block of memory of the specified size. It ended up on the `Marshal` class probably because it was thought that if you're doing marshaling you may need to allocate native memory. But then the framework didn't offer any other to allocate native memory so `AllocHGlobal` is used for things other than marshaling.

>  'll be honest, I don't know if this (specifically using Marshal.SizeOf) is the best way to work out the size of the allocation I want or not, just what I found for my own searching.

Basically `Marshal.SizeOf` is intended to be used with certain other marshaling functions and only with those - you use it get the size of a structure to be marshaled, you allocate a block of memory of that size and then use `Marshal.StructureToPtr` to marshal the structure to that block of memory. Any other use of `Marshal.SizeOf` that doesn't actually involve marshaling is likely to be wrong.

> That sample code is based this code which is me attempting to optimise allocations (which it does, having about a 1/3rd of the allocations that a non-marshaled version does).

Yep, definitely a case for `sizeof`/`Unsafe.SizeOf` (they return the same value but sometimes `sizeof` cannot be used due to rather arbitrary language restrictions).

Though that use case seems a bit odd, since you allocate an array anyway. I guess that's because the number of diffs is usually relatively small so the result array is smaller than the temporary operations buffer.

**Comment by Turnerj** [comment]
Thanks for the detailed explanation!

> It ended up on the Marshal class probably because it was thought that if you're doing marshaling you may need to allocate native memory. But then the framework didn't offer any other to allocate native memory so AllocHGlobal is used for things other than marshaling.

That was going to be my next question! Kinda funny but makes sense at the same time.
