### ISSUE TITLE
Utf8JsonWriter throws `System.InvalidOperationException: Cannot advance past the end of the buffer, which has a size of 256.`

### ISSUE THREAD

**Issue by dodyg** [dotnet/corefx#39648]
### Describe the bug
Using `Utf8JsonWriter` in `3.0.100-preview6-012264` writing to `HttpResponse.Body` throws `System.InvalidOperationException: Cannot advance past the end of the buffer, which has a size of 256.` 

### To Reproduce
```
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.DependencyInjection;
using System.Text.Json.Serialization;
using Microsoft.Net.Http.Headers;
using System;
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.AspNetCore.Http.Features;
using System.Threading.Tasks;

namespace JsonSample
{
    public class Superpower
    {
        public string Name { get; set; }

        public short Rating { get; set; }

        public Superpower(string name, short rating)
        {
            Name = name;
            Rating = rating;
        }
    }

    public class Person
    {


        public string Name { get; set; }

        public int Age { get; set; }

        public bool IsMarried { get; set; }

        public DateTimeOffset CurrentTime { get; set; }

        public Dictionary<string, bool> Characters { get; set; }

        public List<Superpower> Superpowers { get; set; }
    }

    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
        }

        public void Configure(IApplicationBuilder app)
        {
            app.UseRouting();
            app.UseEndpoints(route =>
            {
                route.MapGet("/", async context =>
                {
                    var payload = new Person
                    {
                        Name = "Annie",
                        Age = 33,
                        IsMarried = false,
                        CurrentTime = DateTimeOffset.UtcNow,
                        Characters = new Dictionary<string, bool>
                        {
                            {"Funny" , true},
                            {"Feisty" , true},
                            {"Brilliant" , true},
                            {"FOMA", false}
                        },
                        Superpowers = new List<Superpower> {
                            new Superpower("Humor", 8),
                            new Superpower("Intelligence", 10),
                            new Superpower("Focus", 7)
                        }
                    };

                    var options = new JsonWriterOptions
                    {
                        Indented = true
                    };

                    context.Response.Headers.Add(HeaderNames.ContentType, "application/json");

                    await using (var writer = new Utf8JsonWriter(context.Response.Body, options))
                    {
                        writer.WriteStartObject();
                        writer.WriteString("name", payload.Name);
                        writer.WriteNumber("age", payload.Age);
                        writer.WriteBoolean("isMarried", payload.IsMarried);
                        writer.WriteString("currentTime", payload.CurrentTime);

                        writer.WriteStartObject("characters");
                        foreach (var kv in payload.Characters)
                            writer.WriteBoolean(kv.Key, kv.Value);
                        writer.WriteEndObject();

                        writer.WriteStartArray("superpowers");
                        foreach (var s in payload.Superpowers)
                        {
                            writer.WriteStartObject();
                            writer.WriteString("name", s.Name);
                            writer.WriteNumber("rating", s.Rating);
                            writer.WriteEndObject();
                        }
                        writer.WriteEndArray();

                        writer.WriteEndObject();

                        await writer.FlushAsync();
                    }
                });
            });
        }
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>().
                    UseEnvironment(Environments.Development);
                });
    }
}
```

### Screenshots
![flush-async3](https://user-images.githubusercontent.com/1761249/61588260-7b171600-ab98-11e9-8fcc-d1f16f3275b0.png)

**Comment by benaadams** [comment]
Is caused by Dispose calling Flush (regardless of whether you have already called FlushAsync)

You'd need to use the async Disposable (add await before the using in C#8/preview)

```diff
-    using (var writer = new Utf8JsonWriter(context.Response.Body, options))
+    await using (var writer = new Utf8JsonWriter(context.Response.Body, options))
```

Or be explicit and change using to try+finally for pre-C#8

```diff
    var writer = new Utf8JsonWriter(context.Response.Body, options))
+   try
    {
        // ...        
        writer.WriteEndObject();

-       await writer.FlushAsync();
    }
+   finally
+   {
+       await writer.DisposeAsync();
+   }
```

**Comment by dodyg** [comment]
Same result
> await using (var writer = new Utf8JsonWriter(context.Response.Body, options))

![flush-async-5](https://user-images.githubusercontent.com/1761249/61588445-e8787600-ab9b-11e9-8fc8-a2b556bf46af.png)

**Comment by benaadams** [comment]
Seems strange for a Stream with Utf8JsonWriter to max out at 256 bytes cc @ahsonkhan

**Comment by stephentoub** [comment]
I think what you're witnessing is actually a secondary error; there's an earlier exception occurring, leaving things in a bad state, and then the disposal is trying to flush, and incurring a second exception.

The first exception is because theUtf8JsonWriter is trying to synchronously write to the response stream, and by default ASP.NET Core doesn't allow that.  Try adding:
```C#
webBuilder.ConfigureServices(services => services.Configure<IISServerOptions>(options => options.AllowSynchronousIO = true));
```
to the body of your .ConfigureWebHostDefaults callback in your repro, and I expect you'll start to see things work (at least, I do).  You can also see the first error occurring if you break on first-chance exceptions... you should then see something like this:
![image](https://user-images.githubusercontent.com/2642209/61594916-e247c100-abbe-11e9-9732-5f51277820a8.png)

This highlights a few issues:
1. It's natural to want to pass context.Response.Body to Utf8JsonWriter in order to output JSON, but there's a natural mismatch between the implementations: constructing a Utf8JsonWriter with a Stream will cause it to perform synchronous I/O, and by default ASP.NET Core disallows synchronous I/O on the response stream.
2. An exception from the underlying _stream will leave the Utf8JsonWriter in a bad state, because we advance here:
https://github.com/dotnet/corefx/blob/347412c9a917c71a744d8e20b090da90aa558a79/src/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.cs#L1043
without setting BytesPending to 0, and if the _stream.Write here then throws:
https://github.com/dotnet/corefx/blob/347412c9a917c71a744d8e20b090da90aa558a79/src/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.cs#L1054
the Utf8JsonWriter won't know that BytesPending is wrong.  When it then goes to perform any subsequent operation, such as a flush as part of Dispose{Async}, it'll likely incur this error about trying to advance the writer by BytesPending when it didn't actually increase the storage by that much (and even if it did have a large enough buffer, this would then likely result in a corrupt output, flushing a buffer that hadn't actually been written to).
