### ISSUE TITLE
JsonSerializer.SerializeAsync(Stream) should have "Utf8" in its name

### ISSUE THREAD

**Issue by GSPP** [dotnet/corefx#39712]
The `SerializeToUtf8Bytes` method has "Utf8" in its name supposedly so that "Utf16" can be added later. It seems that this should be done for the `Stream` based APIs as well.

**Comment by ericstj** [comment]
This is a good suggestion but unfortunately we couldn't get the API changes in.  We could take a parameter name change in 5.0 since it isn't binary breaking.  We'd need to doc the source breaking change.

**Comment by ahsonkhan** [comment]
The primary reason `SerializeToUtf8Bytes` has "Utf8" in the name was to distinguish it from the one that returns string (since you can't have API overloads with the same name just based on the return type). If you notice, the Deserialize APIs do not have "Utf8" in the name, since we can overload them just fine based on the input parameter.

The stream-based ones will likely remain defaulted to UTF-8 (as indicated by the parameter name) so I don't think we need to rename it, but we may add support for UTF-16 directly (by inspecting a presence of a BOM), or alternatively, by adding an overload where the encoding is specified.

See related, somewhat duplicate, issues:
https://github.com/dotnet/corefx/issues/40482
https://github.com/dotnet/corefx/issues/39433

Hence, closing this one.

**Comment by GSPP** [comment]
When UTF16 support is added, it will be in the form of a method `void SerializeUtf16(Stream stream, object obj)`. I don't see an alternative design possibility (that has a chance to be chosen). Do you?

And then we have a method `Serialize` and a method `SerializeUtf16` which is inconsistent naming.
