### ISSUE TITLE
Hungarian double compression test failing on Linux

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3972]
```C#
CultureInfo.CurrentCulture = new CultureInfo("hu-HU");
Console.WriteLine("dzsdzs".IndexOf("ddzs"));
```
This prints out 0 on Windows but -1 on Linux.  If StringComparison.CurrentCultureIgnoreCase is used instead of the CurrentCulture default, both Windows and Linux print out 0.

**Comment by steveharter** [comment]
This appears to be by design for ICU based on the locale data for HU. When the IgnoreCase flag is used, we tell ICU to use "secondary" collation level which ignores the differences in the HU dzs collation differences which are defined as a "tertiary" rule. A "primary" or "secondary" collation level does include tertiary rules.

ICU follows the Unicode collation rules as specified here: http://www.unicode.org/reports/tr35/tr35-collation.html#CLDR_Collation_Algorithm and http://www.unicode.org/reports/tr35/tr35-collation.html#Setting_Options

For HU collation see http://unicode.org/repos/cldr/trunk/common/collation/hu.xml with syntax explained at http://userguide.icu-project.org/collation/customization. The dzs collation differences (to DZ and then to D) are defined as tertiary rules.

The corresponding test for this issue will be updated.

**Comment by steveharter** [comment]
Fixed test
