### ISSUE TITLE
SerializeToUtf8Bytes does not support non-english characters

### ISSUE THREAD

**Issue by goyzhang** [dotnet/corefx#39756]
System.Text.Json.JsonSerializer.SerializeToUtf8Bytes
Based on the [existing test](https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/tests/Serialization/Value.WriteTests.cs):
```
            [Theory]
            [InlineData("Hello")]
            [InlineData("你好")]
            [InlineData("مرحبا")]
            [InlineData("こんにちは")]
            public void WriteTest(string str)
            {
                Span<byte> json = JsonSerializer.SerializeToUtf8Bytes($"{str}");
                Assert.Equal(Encoding.UTF8.GetBytes($@"""{str}"""), json.ToArray());
            }
```
Only the first test can pass. The output byte array is not identical to what we would get from `Encoding.UTF8.GetBytes`

**Comment by Tornhoof** [comment]
It just encodes non-ascii symbols explicitly, like \u1234. Your test case just works for ascii cases.

**Comment by ericstj** [comment]
I believe it is by-design that SerializeToUtf8Bytes will do escaping that's more than just plain encoding.
@ahsonkhan is that correct?

**Comment by goyzhang** [comment]
@Tornhoof  Actually that's what I am asking about. The output is not expected and unusable. The method name `SerializeToUtf8Bytes` gives me the feeling that it would have the same output as `Encoding.UTF8.GetBytes(Newtonsoft.Json.JsonConvert.SerializeObject($"{str}"))`, not something like \u1234

**Comment by scalablecory** [comment]
The output is definitely usable; it should be read correctly by other json libraries identically as if it were unescaped.

It defaults to escaping these characters to avoid common security issues in application code or 3rd party libraries that might implement Unicode incorrectly.

That said, we're aware it affects readability/size, and are discussing this in #38354, which also explains ways you can ultimately get the output you're looking for if you're okay with the associated risks.

**Comment by ahsonkhan** [comment]
As mentioned, this is by-design, and this issue is a duplicate of others.

There are ways to workaround this issue by passing in your own `JavascriptEncoder` to the `JsonSerializerOptions` that lets you skip escaping characters that you consider over-escaped.

We have similar capability in the `Utf8JsonWriter` (via `JsonWriterOptions`).

So something like this should work:
```C#
[Theory]
[InlineData("Hello")]
[InlineData("你好")]
[InlineData("مرحبا")]
[InlineData("こんにちは")]
public void WriteTest(string str)
{
    var options = new JsonSerializerOptions() { Encoder = JavaScriptEncoder.Create(UnicodeRanges.All) };
    Span<byte> json = JsonSerializer.SerializeToUtf8Bytes($"{str}", options);
    Assert.Equal(Encoding.UTF8.GetBytes($@"""{str}"""), json.ToArray());
}
```

Since `SerializeToUtf8Bytes` is returning bytes containing utf-8 text, we do not want to change the default behavior and see value in escaping more aggressively to be secure by default. We even escape certain characters within the ascii range (that are not absolutely necessary according to the JSON spec), which includes `+` and characters that are special within an HTML context (for example, `&`, `<`, etc.).

By default, the serializer/writer uses `JavascriptEncoder.Default`.

Hence, closing. Please feel free to re-open if you have other concerns. Thanks for the feedback.
