### ISSUE TITLE
Color.NonRedirectedOutputDoesUseAnsiSequences failing locally on Ubuntu 18.04 (WSL2)

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#39760]
This test is failing locally on Ubuntu 18.04 with WSL2:

```
<test name="Color.NonRedirectedOutputDoesUseAnsiSequences" type="Color" method="NonRedirectedOutputDoesUseAnsiSequences" time="0.010154" result="Fail">
        <traits>
          <trait name="category" value="nonwindowstests" />
          <trait name="category" value="ignoreforci" />
        </traits>
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\nExpected: 3\nActual:   0]]></message>
          <stack-trace><![CDATA[   at Color.<>c.<NonRedirectedOutputDoesUseAnsiSequences>b__3_0(MemoryStream data) in /home/vihofer/corefx/src/System.Console/tests/Color.cs:line 68
   at Helpers.RunInNonRedirectedOutput(Action`1 command) in /home/vihofer/corefx/src/System.Console/tests/Helpers.cs:line 81
   at Color.NonRedirectedOutputDoesUseAnsiSequences() in /home/vihofer/corefx/src/System.Console/tests/Color.cs:line 62]]></stack-trace>
        </failure>
      </test>
```

cc @tmds @stephentoub

**Comment by danmosemsft** [comment]
Debian 9 also 
https://github.com/dotnet/corefx/issues/39721

**Comment by adlich** [comment]
I stumbled upon this issue while setting up an OS X 10.14.5 dev environment. I'm new to this codebase and toolset, but looked into w/ the goal of ruling out issues w/ my setup.

Here are my observations:
a) ConsolePal.IsOutputRedirectedCore reports true during test [1], rendering ConsolePal.WriteSetColorString a no-op
b) Notwithstanding (a), I'm afraid InterceptStreamWriter does not see these writes since 98552707c585bc0f0c138fdeed991c28f00a0ac5, which writes directly to fd

I did **not** investigate:
c) If (a) is a behavior of test harness or redirection detection, or when it regressed
d) If anything else kept it working after (b) but regressed more recently

I hope this is useful. If not, I'd love to learn what I missed and what I could have done better. 

[1] dotnet msbuild /t:rebuildandtest /p:XunitMethodName=Color.NonRedirectedOutputDoesUseAnsiSequences

**Comment by tmds** [comment]
Some more observations:

This test wasn't running until: https://github.com/dotnet/corefx/pull/38676/files#diff-66bcacbeced67c50d82d7f4fa1a7e7b1L54 which has a comment:
```
// the CI system redirects stdout, so we can't easily test non-redirected behavior
```
Also, I'm not sure what makes the `Console.SetOut` thread-safe between tests:
https://github.com/dotnet/corefx/blob/57df8b38e4e70fc25aabe3d061cd1745cff0b26b/src/System.Console/tests/Helpers.cs#L67-L87

**Comment by tmds** [comment]
> b) Notwithstanding (a), I'm afraid InterceptStreamWriter does not see these writes since 9855270, which writes directly to fd

This is the root cause. Removing these tests in https://github.com/dotnet/corefx/pull/40495.

> Also, I'm not sure what makes the Console.SetOut thread-safe between tests:

This is handled at xunit level:

https://github.com/dotnet/corefx/blob/41cd99d051102be4ed83f4f9105ae9e73aa48b7c/src/System.Console/tests/XunitAssemblyAttributes.cs#L7-L8

**Comment by stephentoub** [comment]
> failing locally on Ubuntu 18.04 (WSL2)

@tmds, I assume this is a red herring and it's actually failing everywhere, not just on Ubuntu 18.04 on WSL?

**Comment by tmds** [comment]
Yes, it fails everywhere (including my Fedora 30 system).
The test wasn't running until https://github.com/dotnet/corefx/pull/38676/files#diff-66bcacbeced67c50d82d7f4fa1a7e7b1L54.
