### ISSUE TITLE
Difference in System.drawing.common.dll  in the Bin\Debug\netcoreapp2.1  vs Publish folder

### ISSUE THREAD

**Issue by sdg002** [dotnet/corefx#39776]
### Environment
VS2017
.NET Core console application
Windows 10, 64 bit

### Steps to reproduce - .NET Core EXE

1. Create a .NET Core Console project  (v2.1)
2. Add reference to System.drawing.dll nuget package
3. Edit the CSPROJ and add 

`<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies> `

4. Do a Build
5. Do a Publish, target runtime **win-x64**
6. Note down the size of System.drawing.common.dll under bin\Debug\netcorapp2.1 folder (around 141 KB)
7. Note down the size of System.drawing.common.dll under bin\Release\netcoreapp2.1\publish\ folder. (659 KB)

### Expected
The 2 files should have been the same

**Actual**
They are different. 141 KB and 659 KB

### Further challenges - NET Standard 20 Class library
I believe the above scenario is indirectly hampering our development work. We have  a .NET Standard 20 class library package which references the System.Drawing.Common.dll package and uses the **CopyLocalLockFileAssemblies** to copy over all the referenced assemblies to the output folder. We need the referenced assemblies because our application follows a Plugin architecture (MEF) and each Plugin class library is made responsible for its own dependencies.  In this case, the Plugin Class library ends up with the wrong version of System.Drawing.Common.dll and which in turn throws exception **PlatformNotSupported** in one of the Font constructurs.  Things works fine if we copy over the larger **System.Drawing.Common.dll** directly from the Nuget folder to the Bin. But this defeats the Plugin nature of our application.

```
EXE   
-----
    (Loads Plugin class library using MEF)

Plugin Class library , NET Standard 20
-----------------------------------------
    (CopyLocalLockFileAssemblies) 
    System.Drawing.Common.dll (141KB)


```

Any suggestions?

Thanks,
Sau

**Comment by ViktorHofer** [comment]
cc @safern

**Comment by safern** [comment]
Hello @sdg002 -- thanks for reporting the issue.

This is completely by design. The reason why this is by design is because `System.Drawing.Common` is runtime dependent, what this means is that we have 2 different implementations for Windows and for Unix, the reason for that is because `Graphics`, `Imaging` and other stuff are dependent to the standards of the different OS specifications, however we try to make them behave as closer as possible. Also another difference is that, we use different native libraries, in Windows we use the built-in `GDI+` library and in Unix we use `libgdiplus` which is a library maintained by the mono folks and try to be as similar as possible to `GDI+`. We're trying to make our implementations as similar as possible but there are bottle necks where we have no other option but to have specific implementation for each runtime.

Hence, this is the reason why we have an assembly (dll) that throws `PlatformNotSupportedException` and is specifically designed to catch this sort of issues where developers reference the package and try to use it in a OS/Runtime agnostic world. When you're publishing the app and targeting win-x64 as a runtime, then `NuGet` knows, it should use the implementation under the `runtimes/win/*` directory, therefore you get the real implementation assembly. 

Since netstandard is not a runtime, it is just meant for libraries and to provide compile assets, then what you guys are doing defeats the purpose of `netstandard`'s design. Basically a netstandard library should be consume by the following 2 ways:

- Direct project reference by the consuming application
- `PackageReference` in the consuming application

Then the consuming application knows what runtime is targeting (e.g `netcoreapp2.1-win-x64`) then when you run/publish that application, the build system will identify that you're publishing for `netcoreapp2.1-win-x64` and will resolve the right assets (in this case the large dll) and will put it in the `publish` directory by your application.

> Any suggestions?

Given what I said above, I suggest that your Plugin class libraries have the right `PackageReference`'s in this case `System.Drawing.Common` (which means they're still responsible for their own dependencies) and then your application, consumes this libraries, via a `PackageReference` or a `ProjectReference`, that way, the build system will bring over the transitive dependencies (dependencies defined in your class libraries) into the closure and put them side by side to your application. Does that make sense?

I will be closing the issue because this is by design, but feel free to continue asking questions and I'll be happy to assist you.

cc: @ericstj

**Comment by sdg002** [comment]
Hi @safern ,
Thank you for taking the time to look into this and patiently replying to my queries. From your response, I understand that the main application should be responsible for providing the final package references.  

As per your suggestions we have to modify the main application by providing the **PackageReference**.   
i.e. Potentially, for every new Plugin class library we will have to go back and re-compile and re-deploy the main EXE.

We are using **Managed Extensibility Framework**  so that we do not build up a monolith. MEF is a proven architecture that has worked well for good number of years. Visual Studio itself is built on MEF.     Your suggestion is tantamount to re-deploying Visual Studio EXE just because some 3rd party packages require some additional functionality.


### What would have been desirable?
The Plugin library should have been able to pull in all the required assets - managed and unmanaged into the Bin\Release folder. The element CopyLocalLockFileAssemblies or something of that nature should have done that work for the Plugin class library.
**Example** - I am using CopyToOutputDirector to copy over the unmanaged TensorFlow libraries for Windows runtime in our .NET 20 class library. This has worked very well. We know our environment is designed for Windows and we have been able to selectively pull the native libraries out into the Bin\Release of the Plugin Class library as opposed to modifying the main executable.

```
  <ItemGroup>
    <None Include="$(NugetPackageRoot)\tensorflowsharp\1.13.0\runtimes\win7-x64\native\libtensorflow.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>


```

I tried the above approach with System.Drawing.Common and it did copy over the assembly (640KB) but the main EXE complained about AssemblyLoading failures  while loading from the Plugin folder, possibly due to manifest mismatch. We compiled against something and running against some other version. 

### Conclusion
As I suspected,  .NET Core and/or the PackageReferenc system the way it is designed now , prevents us from exploiting the benefits of MEF and building Plugin style applications - a concept that was so tried and tested with .NET Framework.

**Comment by ericstj** [comment]
You can still publish a library same as you would on desktop.  Just make sure the library targets .NETCoreApp and make sure you use the deps file when loading dependencies (similar to how desktop required .dll.config in order to deal with dependencies).  Did you try publishing your library for .NETCoreApp? /cc @vitek-karas.

**Comment by vitek-karas** [comment]
I completely agree with what @ericstj says. I'm just going to extend on it:

### Creating the plugin
The right way to build the plugin is to make it a classlib, target a real runtime TFM (so not netstandard) - in your case it seems `netcoreapp2.1`, and then publish it for the platform it's going to run on.

This should give you the plugin and all of its dependencies including native ones in one flat folder.

### Consuming the plugin
In .NET Core 2.2 and below we don't have a good story for loading plugins with dependencies. So you will probably have to make something up. Assuming the above plugin layout (everything in one folder), you should be able to load it either via `Assembly.LoadFile` or by handling `AssemblyLoadContext.Default.Resolving` and resolving from the plugins folder. This approach should mostly work, but it has lot of rough edges. Mainly all plugins should agree on dependency versions (so if two plugins use the same library, they better use the same version) - note that VS today suffers from exactly this problem as well.

### .NET Core 3.0
In 3.0 we've improved this quite a bit:
* There's now official support for building "plugins" - make a classlib and add `<EnableDynamicLoading>true</EnableDynamicLoading>` to the project. That will make sure all the dependencies are copied into the output. This will actually be able to build portable plugins - that is plugins which carry multiple versions of dependencies for each runtime (so in the above case you would get two `System.Drawing.Common` copies (one for Windows and one for Linux).
* We've introduces `AssemblyDependencyResolver` which is a class which reads the `.deps.json` produced by the build of the plugin and will resolve all the plugin dependencies. This in combination with a custom `AssemblyLoadContext` for isolation pretty much guarantees that plugins will work in almost all cases (for one it solves the dependency versioning problem mentioned above). If you're interested there's a sample how to do this here: https://github.com/dotnet/samples/tree/master/core/extensions/AppWithPlugin
* There are several fixes in both the SDK and the hosting layer to make plugin scenarios work better
* There are also fixes in the runtime to overcome potential issues with reflection and such when plugins are loaded in isolation.
