### ISSUE TITLE
Change to source code in CoreLib has no effect

### ISSUE THREAD

**Issue by JeffreyZhao** [dotnet/corefx#39897]
I'm trying to contribute to corefx since I've found a bug in System.dll. 

1. I forked the project and build as documented with `build & build -buildtests -test`, which looks good as expected.
2. I searched for the test file for the class I'm going to change and find it in `System.Runtime\tests`, although the source code is in `src\Common\src\CoreLib\System`. I added some unit tests to the test file, rebuild the tests and execute them by `build -buildtests -test`, and those new test cases failed as expected.
3. I fix the code in `src\Common\src\CoreLib\System`, rebuild by `build`, and then `build -buildtests -test` again, those tests still fails as no change has been made.
4. I went back the source code and write some code that cannot be compiled, and then `build` again. The build succeeded. It seems it hasn't picked up the change I've make.
5. I did a clean by `build -clean` and repeated the whole build process, and it's all the same.

So I have some questions:

1. Why my changes to the CoreLib cannot be picked by the build process. Is that the correct place to change?
2. Why the tests are in `src\System.Runtime` but the source code is in `src\Common\src\CoreLib`?
3. When I exam the build results, I found the dlls like `mscorlib.dll` or `System.dll` are all "reference dll" with metadata only. Where's the real dll with implementation in it?

Thanks
Jeff

**Comment by stephentoub** [comment]
> Why my changes to the CoreLib cannot be picked by the build process. Is that the correct place to change?

Most of the source code for System.Private.CoreLib is mirrored to several repos.  It's for example mirrored into dotnet/corert and mono/mono so that the System.Private.CoreLibs there can share most of the implementation.  And it's mirrored into dotnet/corefx so that various corefx libraries can build this or that source file into different libraries.  However, System.Private.CoreLib itself is built in the dotnet/coreclr repo, not in dotnet/corefx.  Changes to src\Common\src\CoreLib need to be made in dotnet/coreclr.

> Why the tests are in src\System.Runtime but the source code is in src\Common\src\CoreLib?

All tests for public surface area in .NET Core are located with the respective libraries.  Some of the implementation for those libraries may be in dotnet/coreclr, some may be in dotnet/corefx, but the tests (and the reference assemblies) are all in corefx.  We're fairly fluid about where the implementation lives, and in fact frequently find ourselves moving implementation back and forth across that boundary as need dictates.

> Where's the real dll with implementation in it?

mscorlib.dll and System.dll exist only for compatibility with .NET Framework.  The implementations for these just contain type forwards into other assemblies in .NET Core.  For example, System.Diagnostics.Process lives in System.dll in .NET Framework, but lives in System.Diagnostics.Process.dll in .NET Core.  The System.dll produced in .NET Core just type forwards the Process type to System.Diagnostics.Process.dll.

**Comment by JeffreyZhao** [comment]
> All tests for public surface area in .NET Core are located with the respective libraries. Some of the implementation for those libraries may be in dotnet/coreclr, some may be in dotnet/corefx, but the tests (and the reference assemblies) are all in corefx. 

It sounds to me that the source code and unit tests have to be committed separately into different projects. Does it mean that we cannot do it with a TDD approach since all tests are in dotnet/corefx only? Could you please suggest what to do in this case? Should I create a pull request to dotnet/coreclr for the source code only, and create another one to dotnet/corefx for the test when/if it's been accepted?

**Comment by stephentoub** [comment]
> It sounds to me that the source code and unit tests have to be committed separately into different projects.

If the relevant code being modified is in System.Private.CoreLib, that is the case today.

> Does it mean that we cannot do it with a TDD approach since all tests are in dotnet/corefx only?

No, it doesn't mean that.  You just need to build corefx with the /p:CoreCLROverridePath argument, specifying the path to your locally built coreclr; when you run the tests in corefx, you'll then be testing your local corelib.  See https://github.com/dotnet/corefx/blob/ab58ff6e649852b85fdb99b15992a2fa3a7d8834/Documentation/project-docs/developer-guide.md#testing-with-private-coreclr-bits.

> Should I create a pull request to dotnet/coreclr for the source code only, and create another one to dotnet/corefx for the test when/if it's been accepted?

If you need to add new tests, yes.  Note that all of the corefx tests run against coreclr PRs.

**Comment by stephentoub** [comment]
However, @JeffreyZhao, if you believe you've found a bug in corefx, it's probably best to first open an issue describing the problem, including a repro, etc.  Thanks again for your interest.

**Comment by JeffreyZhao** [comment]
Thanks @stephentoub, I've report the bug in issue #39919.
