### ISSUE TITLE
Problem with FTDI driver

### ISSUE THREAD

**Issue by MichaelL79** [dotnet/corefx#39944]
I'm not quite sure if this is related to .Net Core 3 but from my perspective it seems to.

# Setup
I have a legacy project migrated to .NetStandard 2. The project is used to communicate to our USB devices via FTDI driver (FTD2XX.dll). To open the connection to a device, we use the FT_OpenEx() method.

# Problem
When used in a classic WPF application (4.7.2) everything works fine. The method returns 0 and the connection is opened.
When the very same DLL is used in a .NET Core 3 WPF or console application, the method returns 3 and the connection is not opened.

Example:
```
[DllImport("FTD2XX.dll")]
static extern uint FT_OpenEx([MarshalAs(UnmanagedType.LPArray)] byte[] p_Arg1, uint uiFlags, ref uint uiHandle);

public const uint FT_OPEN_BY_DESCRIPTION = 2;

public bool Open(){
  byte[] descriptionBytes = new byte[]{ 0x01, 0x02, 0x03, ... };
  uint deviceHandle = 0;
  var status = FT_OpenEx(descriptionBytes, FT_OPEN_BY_DESCRIPTION, ref deviceHandle);
  // status when used from a classic WPF application is 0
  // status when used from a .NET Core WPF application is 3
}
```

**Comment by vcsjones** [comment]
In your .NET Framework application, are you running your application as 32-bit by either explicitly targeting x86 or have the "Prefer 32-bit" checkbox set by default?

Looking at your function declaration and some Random Googling, it looks like your last parameter should be marshalled as `IntPtr`, not `uint`, since `FT_HANDLE` is [defined][2] as:

```c
typedef PVOID FT_HANDLE; 
```

[2]: https://www.ftdichip.com/Support/Knowledgebase/index.html?ftd2xx_h.htm

**Comment by MichaelL79** [comment]
Thanks for your quick reply. Sorry, it actually was a mistake in my setup.
