### ISSUE TITLE
 System.Text.Json.JsonSerializer.Deserialize<Dictionary<string, object>> Treats 'object' Incorrectly

### ISSUE THREAD

**Issue by nick2893** [dotnet/corefx#39953]
In the following example: 

            string sJsonFromDB = 
@"{ 
  ""command73"": { 
    ""type"": ""string"", 
    ""value"": ""2@RUN"" 
  }, 
  ""Data_73_1"": { 
    ""type"": ""hash"", 
    ""value"": { 
      ""73_var1"": ""2.0"", 
      ""73_var2"": ""1.0"" 
    } 
  } 
}"; 
            Dictionary<string, object> dobjDBtxt = System.Text.Json.JsonSerializer.Deserialize<Dictionary<string, object>>(sJsonFromDB); 
            System.Web.Script.Serialization.JavaScriptSerializer webSerializer = new System.Web.Script.Serialization.JavaScriptSerializer(); 
            Dictionary<string, object> dobjDBweb = webSerializer.Deserialize<Dictionary<string, object>>(sJsonFromDB); 

JavaScriptSerializer correctly creates the following structure as I would expect: a Dictionary<string, object> where the object is either a string, or another Dictionary<string, object>. 

JsonSerializer incorrectly generates a Dictionary<string, System.Text.Json.JsonElement>

**Comment by steveharter** [comment]
This is by design. When the deserializer sees `System.Object` it uses `System.Text.Json.JsonElement` because the deserializer doesn't want to "guess" what the primitive values are (should a number be a double or decimal?) or even other strings (which could be a datetime, etc).

Here's a [similar issue](https://github.com/dotnet/corefx/issues/38713) with an explanation and example of a work-around if you need that behavior.
