### ISSUE TITLE
Why PipeWriter doesn't have synchronous Flush?

### ISSUE THREAD

**Issue by aliveli186** [dotnet/corefx#39999]
System.IO.Pipelines

**Comment by carlossanlop** [comment]
Hello @aliveli186 , thank you for your contribution.

This was probably an oversight when the classes were added in this PR to corefx: https://github.com/dotnet/corefx/pull/27007 . I did not find any comments asking about adding a `Flush()` method.

Would you mind sharing your use case? Why would you prefer to use Flush instead of FlushAsync?

cc @JeremyKuhne

**Comment by stephentoub** [comment]
> This was probably an oversight

I don't think so :wink:
cc: @davidfowl

**Comment by carlossanlop** [comment]
@stephentoub @davidfowl so what would be the reason behind [not including Flush in the PR I mentioned above](https://github.com/dotnet/corefx/pull/27007/files#diff-3e3d4d1815dfb473d42636ce0603aaa6R83)? I can't find an explanation in that PR, and there's no mention of the API approval issue for that PR, where I was hoping this would be explained. If it wasn't an oversight, then it would be great to provide an answer in this thread so we can close the issue.

**Comment by stephentoub** [comment]
System.IO.Pipelines is intended for high-throughput and scalable processing of data.  In a producer/consumer scenario, a writer that flushes may need to wait for the reader to read before the flush can complete, and with a synchronous flush, that would mean blocking a thread (probably a thread pool thread) waiting for some other thread (probably also a thread pool thread) to do the necessary work.  That's a recipe for being non-scalable.

**Comment by carlossanlop** [comment]
Clear as water, thanks @stephentoub . I'll close the issue.
