### ISSUE TITLE
OS X does not provide IPv4 packet info for dual-stack sockets.

### ISSUE THREAD

**Issue by pgavlin** [dotnet/corefx#4004]
There is not likely to be a mitigation, so this will probably just need to be documented.

**Comment by stephentoub** [comment]
If it can't be done, it can't be done.  Is this something we can throw a PlatformNotSupportedException for in the code?  What code does one write to experience this, and what's the experience in the code-as is with the information not being provided?

**Comment by pgavlin** [comment]
> Is this something we can throw a PlatformNotSupportedException for in the code?

Yes, with some minor refactoring in the shim and the native code: we'd need some way to indicate that the platform does not support IPv4 packet info for dual-stack sockets and a place to check that information.

> What code does one write to experience this, and what's the experience in the code-as is with the information not being provided?

Any usage of the various `ReceiveMessageFrom` APIs will expose this. These APIs typically fill in an `IPPacketInformation` value with origin information for the received packet. On Windows and Linux, a dual-stack socket (i.e. an IPv6 socket that can also communicate over IPv4) can provide origin information for IPv4 packets; on OS X, this information is not available. AFAICT from the implementation, however, there is no guarantee that origin information will be available (if the information is not provided by native code, the routines that attempt to find it simply return `default(IPPacketInformation)`). The guaranteed receipt of origin information is, however, implied by the tests.

**Comment by stephentoub** [comment]
> however, there is no guarantee that origin information will be available

Interesting.  If there are cases where we won't provide this information on Windows or Linux, I'm fine saying that we provide it if it's provided by the OS or return default(IPPacketInformation) otherwise, and since it's never provided on OS X, we just always return the default.

It's more complicated if on Windows and Linux the information is always available, in which case we need to decide whether the right behavior for OS X is returning default(IPPacketInformation) or throwing.  Is there any way a consumer of this information could be led astray if we return default(IPPacketInformation)?  If not, seems like it'd be better to just return the default rather than throwing.  If we could end up misleading someone in some way, though, we should consider the exception.

**Comment by pgavlin** [comment]
> Is there any way a consumer of this information could be led astray if we return default(IPPacketInformation)?

If the consumer assumes that the information in the returned `IPPacketInformation` always contains a  non-null `IPAddress` instance, then returning `default(IPPacketInformation)` would cause the consumer to AV. As long as there is a null check--which there should be--then the consumer should be unaffected from a correctness point of view. At a higher level, I'm not sure what the lack of the packet information would imply for consuming code (i.e. it's not clear to me whether a consumer would have a hard dependency on this information being available).

**Comment by stephentoub** [comment]
@cipop, are you aware of any situations on Windows where we'd end up giving back a default IPPacketInformation, or otherwise with a null IPAddress field?

**Comment by CIPop** [comment]
It's best if we could have a few simple tests to pin behavior and ensure all of this works the same across platforms.

The `IPPacketInformation` is just a wrapper over winsock's `WSAMSG`. According to MSDN a valid pointer to a `SOCKET_ADDRESS` is going to be populated for any unconnected socket. (https://msdn.microsoft.com/en-us/library/windows/desktop/ms741687(v=vs.85).aspx)

Within managed code, the value is never null for IPv4 or IPv6 in Windows: 
https://github.com/CIPop/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/_ReceiveMessageOverlappedAsyncResult.Windows.cs#L106
https://github.com/CIPop/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Windows.cs#L1151

It could be null for other types of sockets (other IP versions or non-IP?). Not sure when this `else` statement would apply given that the struct contains the acronym 'IP'.

**Comment by pgavlin** [comment]
I see: even if the checks at https://github.com/CIPop/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Windows.cs#L1155, https://github.com/CIPop/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Windows.cs#L1165, https://github.com/CIPop/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/_ReceiveMessageOverlappedAsyncResult.Windows.cs#L108, and https://github.com/CIPop/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/_ReceiveMessageOverlappedAsyncResult.Windows.cs#L119 fail, the code at least sets the returned `IPPacketInformations`'s address to `IPAddress.None`. @stephentoub I think that doing the same would probably be fine for OS X.

**Comment by stephentoub** [comment]
>  I think that doing the same would probably be fine for OS X.

Sounds good.

**Comment by ericeil** [comment]
So after some experimentation and research, I agree with @pgavlin that there's probably nothing we can do to make this work on OSX.

I'm concerned about the proposal to simply return IPAddress.None here.  Presumably users of these APIs care about getting the actual address back; otherwise, they'd likely use a simpler API.  And this is the kind of thing that might be missed in testing, if, for example, a user only tested with an IPv6 client.

My preference is to simply throw `PlatformNotSupportedException` from `ReceiveFrom` and `ReceiveMessage` (and the async versions) if they're called on a dual-stack socket on OSX.  The message can suggest the workaround of using separate IPv4 and IPv6 sockets (if source address information is really needed) or using `Receive` (if the extra info isn't actually required).

@CIPop, @pgavlin, @stephentoub, does this seem reasonable?

**Comment by stephentoub** [comment]
Let's go with PlatformNotSupportedException then.  It at least gives us the flexibility to provide a better implementation later should we find a better option.
