### ISSUE TITLE
System.Xml.Serialization needs a dynamic element name for interop

### ISSUE THREAD

**Issue by KubaO** [dotnet/corefx#40041]
There's some awful XML out there that uses such a multitude of element names that it's infeasible to map them all out in explicit `XMLElement` attributes. Heck, such XML is usually produced with  dynamically generated names. It's a horrible practice - not to be encouraged, but we should be able to simplify the life of people who need to interoperate with such XML.

It'd be nice if we could do this:

```
class AwfulElement {
  [XmlDynamicElementName]
  string name;
  [XmlText(typeOf(int))]
  int aNumber;
  ...
}
```

Other names for the proposed attribute may be `XmlInteropDynamicElementName` to signify that this is for interop purposes only, or `XmlAwfulDynamicElementName` to make it abundantly clear what it is :/

### Rationale

As it stands, `XmlSerializer` infrastructure does a very poor job of supporting this - it requires quite a bit of semi-efficient code. Imagine you wanted a bunch of such elements in a collection with the following spec (note that currently it requires having an `INamedElement`, but with the support for the proposed attribute there'd be no need for it):

```
partial class AwfulCollection<T> : IXmlSerializable, IEnumerable<T> where T : INamedElement, new();

class AwfulParent {
  public AwfulCollection<AwfulElement> Elements;
}

<?xml>
<AwfulParemt>
  <Awful1\>
  <Awful2\>
</AwfulParent>
```

I'll spare the details, but implementing this generic `AwfulCollection` is a pain. With the support for the proposed attribute, the usual array could be used:

```
class LessAwfulParent {
  public AwfulElement[] Element;
}
```

### Spec

The attribute definition would be rather basic. A `DefaultElementName` property is a fallback if the name the attribute applies to is null. An exception would be thrown on serialization if both the name-attributed field as well as the default name were empty. On deserialization, the `name` is filled in with the name of the element.

```
[System.AttributeUsageAttribute(System.AttributeTargets.Field | System.AttributeTargets.Property, AllowMultiple=false)]
    public partial class XmlDynamicElementNameAttribute: System.Attribute
    {
        public XmlDynamicElementNameAttribute() { }
        public XmlDynamicElementNameAttribute(string defaultElementName) { }
        public string DefaultElementName { get { throw null; } set { } }
        public System.Xml.Schema.XmlSchemaForm Form { get { throw null; } set { } }
        public string Namespace { get { throw null; } set { } }
    }
```

**Comment by terrajobst** [comment]
This is a request for a new API, which means it belongs into CoreFX.

**Comment by StephenBonikowsky** [comment]
Per a conversation with Matt and Daniel there is an alternative coding pattern that solves this issue without needing to add a new API.


@mconnew and @dasetser can you guys provide details?

**Comment by dasetser** [comment]
@KubaO The simplest way to do this with XmlSerializer would be to add an extra property to the type that will hold any additional elements that the serializer can’t handle normally. It would look like this:
```csharp
[XmlAnyElement]
public XmlElement[] Unsupported { get; set; }
```

Once you have that add a method and mark it with the `OnDeserialized` attribute, and have it iterate through your Unsupported array and handle each element individually. To handle them you would want to read the element name, and create an instance of XmlSerializer for that name that can be used to deserialize the object. Doing this for every element in the Unsupported array should let you handle everything.

The reason why this is awkward to handle is because XmlSerializer is supposed to be used with XML which has a defined schema, but having random names for an element means there's no schema for it. For the same reason this isn't the kind of feature we want to add to XmlSerializer. You can use the above suggestion as a workaround, but in reality XmlSerializer isn't designed to handle schema-less XML, and if you need to read and handle arbitrary XML you would generally want to use a solution like XmlReader instead.
