### ISSUE TITLE
macOS FileSystemWatcher sometimes throws ArgumentOutOfRangeException while processing events

### ISSUE THREAD

**Issue by alexischr** [dotnet/corefx#40054]
See https://github.com/mono/mono/issues/15575 for some more details and a stacktrace (note that the class namespace is renamed to `System.IO.CoreFX` under Mono)

It seems (we have not yet confirmed, but nothing else shows from the code) that in some events, `_fullDirectory` is longer than some of the paths returned in the event list used by `ProcessEvents()`, signifying a completely different root. We have a candidate fix of sorts at https://github.com/mono/corefx/pull/317 , where we just don't try to slice if the lengths are out of range, but a more proper solution is probably to always ensure `_fullDirectory` is the first part of any path before we try to just slice it out.

The issue seems to happen more often in macOS Catalina according to crash reports, but we don't yet have a reliable reproduction.

**Comment by danmosemsft** [comment]
@buyaa-n since yo'ure looking at FSW on Mac already please take a look at this as well and ideally a fix if needed.

**Comment by buyaa-n** [comment]
Sure @danmosemsft will see what can I do

**Comment by buyaa-n** [comment]
Seems its not directly related to the issue I was looking #40034 where OS is not triggering Create event on File.Move(source, target) action, instead producing another event (kFSEventStreamEventFlagRootChanged). For this bug seems the event is occurred but the path where event occured was not set or not valid. My first guess is it might related to security restrictions OSX 10.15 version have got https://github.com/dotnet/corefx/issues/40037#issuecomment-518409452. @alexischr could you try or ask them to disable `csrutil` in their system?

**Comment by buyaa-n** [comment]
@alexischr seems original issue mono/mono#15575 resolved and closed, can we close it now?

**Comment by alexischr** [comment]
@buyaa-n The issue on Mono was fixed because some patches were made to fix the issue. I am upstreaming these changes on a PR for this repo now.
