### ISSUE TITLE
Building X509Chain should propagate error to X509Chain.ChainStatus

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/corefx#40116]
In https://github.com/dotnet/corefx/issues/39988 we have started handling `UnparseableExtension` status code on OSX but we have noticed that error on Windows (and possibly Linux) is not being propagated to X509Chain.ChainStatus.

Here is an example test case modification which will show the issue.

In src/System.Security.Cryptography.X509Certificates/tests/DynamicChainTests.cs, test case `TestInvalidAia`

following assert should be added

```csharp
 Assert.Contains(chain.ChainStatus, (status) => status.Status.HasFlag(X509ChainStatusFlags.InvalidExtension));
```

currently this will fail on Windows.

We should investigate how can the error messages be improved.

cc: @bartonjs @krwq

**Comment by bartonjs** [comment]
Since Windows is the authority on what we do and don't provide via the error codes (in Windows we don't touch the chain at all, they build it and tell us what happened), if Windows doesn't set the code then not setting the code is correct.

Based on other activity on the related issues/PRs, I don't think this is actionable anymore.
