### ISSUE TITLE
Consider exposing crv values for ECDSA keys

### ISSUE THREAD

**Issue by scottbrady91** [dotnet/corefx#40192]
When handling ECDSA keys, it can be useful to know the corresponding crv value defined in [rfc7518](https://tools.ietf.org/html/rfc7518#section-6.2.1.1).

Currently, only the oidc and friendly name are exposed.

There are some mappings in IdentityModel's `ECDsaAdapter`, but these methods are private.

**Comment by bartonjs** [comment]
Mostly the corefx cyptography only works at the bottom layer, which is defined in terms of the OID.

Exposing the JWE identifiers feels like it belongs more wiht the JWE/JWT layer, which is (I believe) https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/

**Comment by scottbrady91** [comment]
I was going to open it there but @brentschmaltz told me to open it here :p

**Comment by bartonjs** [comment]
I can't think of a reason why it would belong here... it'd either be out of date or would slow down the JWE/JWT layer by waiting on us to add something to a mapping table (since we don't have any reason to pay attention to JWE evolution... and only ship new public members about once a year).

I think the easy answer is that in the corefx layer we usually only host information that we need ourselves, and we don't need the JWE identifiers.  If we needed them because of a new mode in PKCS#7, or something like that, then we'd have a different story.

**Comment by scottbrady91** [comment]
@bartonjs thanks :) I'll move this to the Identity Model repo
