### ISSUE TITLE
Is there any way to change Transaction's MaxTimeout or any plan to make possible it?

### ISSUE THREAD

**Issue by JP3BGY** [dotnet/corefx#40266]
https://github.com/dotnet/corefx/blob/a4f5f13ec1fa0d51ce0964c126e35ef0046ea7be/src/System.Transactions.Local/src/System/Transactions/Configuration/MachineSettingsSection.cs#L7-L26

It seems there is no way to change Transaction's MaxTimeout in .NET Core.
Is there any way to change it or any plan to make it possible?

**Comment by dasetser** [comment]
@JP3BGY You're correct that there is no way to change the Transaction's MaxTimeout in .NET Core. In .NET Framework the only way was through machine config, which does not exist on .NET Core, so this is always the default value of 10 minutes.

We don't have any plans to add a new way to configure this. You generally want to design your transactions so they are short-lived to avoid locking resources for extended periods of time.

**Comment by GSPP** [comment]
@dasetser I work on two major applications that require long-running transactions. These are transactions for background jobs. The blocking that this causes has no end user impact. We need the atomicity so that failed jobs are rolled back. The transaction duration for such jobs ranges from milliseconds to a few hours.

There is nothing inherently bad about long-running transactions. They do require more careful design but it's a useful feature to have.

We could manually manage the transactions but we currently (and for good reasons) depend on System.Transactions for our transaction management.

This would be a migration issue for us. Any chance you can add a setting for this?

I'd prefer setting the timeout in code to the machine.config anyway.
