### ISSUE TITLE
Support for seeking on CryptoStream depending on mode

### ISSUE THREAD

**Issue by Genbox** [dotnet/corefx#40400]
CryptoStream currently returns a hardcoded false on CanSeek. [See source here](https://source.dot.net/#System.Security.Cryptography.Primitives/System/Security/Cryptography/CryptoStream.cs,64).

However, it is entirely possible to seek with some encryption/decryption modes. Take AES in ECB mode for example - there is no dependency from block to block, which makes it possible to seek to a block and encrypt/decrypt it accordingly.

According to the comment (see link above), the author also seems to agree that it is too strict to just return false. Could we extend CryptoStream to have seek support?

**Comment by bartonjs** [comment]
What's your scenario? There may be better ways of solving the problem than with CryptoStream.

Since ICryptoTransform has no way of reporting if it can support skipping, what behavior would you propose for CBC, or any other stateful mode?  Seeking forward could be implemented as repeated reads (discarding the result), but that would mean doing potentially a lot of synchronous I/O when Seek is usually an O(1) ok-in-an-async-context operation.  Seeking backwards seems hard.  Seeking at all during encryption seems dangerous, and the ICryptoTransform doesn't report which direction it's processing.

I'm not really seeing a way where it could ever do it safely.  ECB is the only time it seems reasonable, and an easier solution seems to be just to feed the CryptoStream less data (e.g. pre-seek a FileStream to where you want to resume before passing it to the CryptoStream), and/or to use ICryptoTransform directly to control what pieces of data it's seeing.

**Comment by Genbox** [comment]
I'm currently building a network-based API with retrying capability. With a normal FileStream/MemoryStream it is possible to seek back to the last checkpoint (think chunking) in the stream and go from there. However, as soon as you wrap the stream in a CryptoStream, you no longer can get the length of the stream, or seek in it.

Some ciphers are designed to transform a block without depending on the previous ciphertext block. ECB and some counter modes come to mind, and in that case, it should be trivial (and safe) to support seeking. For CBC mode it is much more difficult, and I think it would add too much complexity to attempt to support it.

Some ciphers are are also designed without padding, which means the ciphertext is as long as the plaintext, and others are not. Even in cases with padding, it should be possible to calculate the final size from the blocksize and original data length. Amazon's API for .NET is a good example of where this limitation is worked around when using AES in CBC mode.

I'm thinking CipherStream could check if the underlying implementation supports seeking (if (impl is ISeekable)) and return true/false accordingly. The same could be done for the length of the stream.

**Comment by bartonjs** [comment]
ECB is the only truly independent mode. CTR (which we don't support) is sort of independent, in that it only needs the position and IV.

But that doesn't really matter... because there's no way for the ICryptoTransform to report that it would supports seeking.  Decryption would need to back-seek to understand the previous block (CBC, CFB, CTS), or perform keystream generation (OFB).   Encryption (since you can encrypt via Read mode) would have a similar need to rehydrate state, but more difficultly.  The ICryptoTransform might not support restarting with the IV (Seek(0, Begin)).

We don't know if we're encrypting or decrypting.  We don't know if padding is required (ECB, CBC) or not (CFB, OFB, CTR, CTS).  So we can't give a meaningful answer for Length.


So long as you hold on to the underlying stream, you could seek it back, snap off a new encryptor/decryptor, and wrap it in a CryptoStream again.  Or just ignore CryptoStream and jump straight to cryptoTransform.TransformFinalBlock with the payload (all of the inbox implementations from SymmetricAlgorithm instances are CanTransformMultipleBlocks=true, so they can all just dump 100% of the payload into TransformFinalBlock for a one-shot call).  But the interface doesn't give CryptoStream enough data to do seeking safely, and it can't report the Length in a sensible manner.

**Comment by Genbox** [comment]
GCM has been added to .NET Core 3.0, so I guess that can be added to the set of semi-independent encryption ciphers, as only the encrypted counter is needed like CTR.

I don't think anything should change for ICryptoTransform regarding seeking or length as my understanding is that it provides the API necessary for transforming blocks and nothing more. Any changes to ICryptoTransform, besides being breaking, is a change in design and therefore put extra requirements on past/current/future implementations - that's not something I think should be done.

However, instead of using the UniversalCryptoTransform class, would it be possible to create specific implementations that support seeking/length (like, for ECB), and then extend it with an interface (say IHasSeek), which CryptoStream would check for and use the specific implementation instead of simply returning false for CanSeek or giving an exception for Length.

**Comment by bartonjs** [comment]
When Decrypting it can't know the answer for Length until it gets the last block and computes the padding removal (unless it's PaddingMode.None).  GCM and CCM are not ICryptoTransform implementations, and cannot be used with CryptoStream (they're both all-or-nothing encrypt-and-produce-tag, and all-or-nothing decrypt-and-verify-tag).

Currently .NET Core only supports ECB and CBC (and GCM/CCM, but not as ICryptoTransform). CBC can't sensibly seek backwards, because it's stateful.  ECB decryption can't predict length (except in degenerate None-padding). ECB encryption can produce sensible values for Length `(16 * ((n+16)/16))`, but can only sensibly support Seek to a block-aligned position (assuming Read mode... and "block aligned" would have to be determined by the underlying stream's position when the wrapping ctor was invoked).

Decrypting via Read mode can seek forwards easily (just call Read into a throwaway buffer).  Write mode could arguably be made to seek backwards to overwrite previous data, but I don't know if that's useful to anyone (and doesn't sound like your scenario).

I feel like "seekable" will be hard to explain, hard to use, and full of too much nuance.  The type isn't sealed, though, so you could derive from it and try to make seeking make sense for your use case.

**Comment by Genbox** [comment]
@bartonjs I agree that it is hard for most ciphers, but also pretty easy for a few of them. It seems the complexity is not worth it from our discussion, so I consider this issue closed.
