### ISSUE TITLE
Properties of System.Diagnostics.Process should be null rather than throwing exceptions

### ISSUE THREAD

**Issue by Symbai** [dotnet/corefx#40444]
The following code throws `System.InvalidOperationException: No process is associated with this object.` when trying to access the ProcessName property although it has a null check. I mean for some reason accessing all properties of the Process object throws an InvalidOperationException. Wouldn't it make more sense that they are just null if the underlying process is disposed? Otherwise something like this:

`public string ProcessName => proc?.ProcessName ?? "<empty>";`

is not possible and always requires a try catch method body like this:

```
public string ProcessName
{
    get
    {
        try
        {
            return proc.ProcessName;
        }
        catch (InvalidOperationException)
        {
            return "<empty>";
        }
    }
}
```

Repro:
```
public MainWindow()
{
    InitializeComponent();
    proc = Process.GetCurrentProcess();
}
private Process proc;
public string ProcessName => proc?.ProcessName ?? "<empty>";

private void Button_Click(object sender, RoutedEventArgs e)
{
    MessageBox.Show(ProcessName);
    proc?.Close();
    proc?.Dispose();
    MessageBox.Show(ProcessName); //Throws System.InvalidOperationException: No process is associated with this object.
}
```

**Comment by Gnbrkm41** [comment]
I think there isn't much to be done since this would be a breaking change as the behaviour is clearly defined in the documentations.

Maybe there could be a boolean property named `IsAssociated` or whatever to enable checking though.

**Comment by Symbai** [comment]
With 5.0 a breaking change is not a big deal (I expect this, if ever be done, not be part of 3.x anyway). 

Why does it throw anyway instead of returning null? Is there a clearly specific reason WHY it has to throw rather than "it's just like it is now"? I'm asking because I don't know any and so I find the current behavior odd. It makes the life of developers just more complicated by forcing to add more code and checks.

**Comment by Gnbrkm41** [comment]
> With 5.0 a breaking change is not a big deal

Why so? it has potential to break every existing code that use Process since they wouldn't expect it to not throw and suddenly return null. Suddenly, NullReferenceExceptions everywhere!

I can't really comment on the decisions behind it given that it's probably made when it was first introduced into .NET Framework 1.1 (at least 16 years ago).

**Comment by stephentoub** [comment]
> With 5.0 a breaking change is not a big deal

Breaking changes in any version are a big deal.  Some things are more breaking than others, and in some cases we may choose to accept the break because the reward is greater than the risk, but I agree with @Gnbrkm41 that in this case that's unlikely to be the case, and we would very likely start seeing a non-trivial amount of code that was correctly written to handle InvalidOperationExceptions now start null ref'ing.  I highly doubt it's a change we'd want to make.

**Comment by Gnbrkm41** [comment]
Also, looking at the code it seems that you're trying to aceess members of a disposed object, which usually has a range of behaviours from NRE, ObjectDisposedException or simply undefined etc. Throwing exception for that particular case seems fine to me.

I'm not too sure about other cases where the instance is not associated with a process, and if it's common for that to happen (I genuinely don't know); Apart from disposal of the object, what Constructing a new instance by doing `new Process()`.

**Comment by Symbai** [comment]
> Why so? 
 breaking changes are not a big deal on 5.0 because its a new major release and yes, developers have to expect that there might be breaking changes. I dont know any developer which blindly updates to a major release without checking out whats new and what has changed etc. I'm not saying that breaking changes don't matter at all so we can greatly introduce them.  I'm saying that if there is a next major release, then it's the best chance to introduce a breaking change. And unlike stephentoub I see this change more useful than to keep an existing state, where nobody can clearly say WHY it has to be like that which has more negative aspects than positive.

> Also, looking at the code it seems that you're trying to aceess members of a disposed object, which usually results in a range of behaviours from NRE, ObjectDisposedException or simply undefined etc. Throwing exception for that particular case seems fine to me.

This is a repro code, not a productive code. When a process property is shared along multiple classes and perhaps even WPF/UWP binds to it and it's getting disposed it throws everywhere. To avoid this, we would have to try-catch at multiple places literally everywhere it's going to get accessed. This is a lot of try-catch. Something that is only necessary on System.Diagnostics.Process, for a reason nobody can tell.

**Comment by stephentoub** [comment]
> for a reason nobody can tell

Because it was designed, implemented, tested, and documented to use exceptions rather than null/false/sentinel values to communicate failure. That is a reasonable choice, even if you don't like it. Code has been written to rely on those semantics for almost two decades. It would require a very strong reason to break such code, and I'm not seeing that reason.

**Comment by Symbai** [comment]
> 
> 
> > for a reason nobody can tell
> 
> Because it was designed, implemented, tested, and documented 

16 years ago. Which is a good reason for me to take a look at it and consider whether things like that also makes sense nowadays. Whether they fit to the overall .NET experience/behavior. But if you don't see it this way, fine.
