### ISSUE TITLE
ConcurrentDictionary.GetOrAdd Func<TKey, TValue> executing multiple times with incorrect semantics?

### ISSUE THREAD

**Issue by sblackler** [dotnet/corefx#4068]
I have an issue with some internal code that uses `ConcurrentDictionary`'s `GetOrAdd(TKey, Func<TKey, TValue>)`.

I initially, incorrectly, assumed that being a thread safe class that the `Func<TKey, TValue>` would be invoked once. After reading the [MSDN Documentation](https://msdn.microsoft.com/en-us/library/ee378677(v=vs.110).aspx) it does indeed state that:
> If you call GetOrAdd simultaneously on different threads, addValueFactory may be called multiple times, but its key/value pair might not be added to the dictionary for every call.

This raises a few issues:

- What if `TValue` is something like a `QueueClient` that can cause conflicts with each other or consumes vast resources?
- Shouldn't the invocation of `addValueFactory` be thread safe given that it is a concurrent class? As in guaranteed to be executed once.
- If `TValue` implements `IDisposable` and the `addValueFactory` gets invoked twice then don't we have a framework induced memory leak? (Can't rely on devs implementing finalizers, also a finalizer has no guarantees on when its being called if at all)

cc/ @MattRidgway @Smudge202 @HerecyDev

**Comment by herecydev** [comment]
Agree with everything here.

* It's not implied this would happen
* Created objects can and will run forever (GC collection isn't guaranteed).

**Comment by JonHanna** [comment]
> What if TValue is something like a QueueClient that can cause conflicts with each other or consumes vast resources?

Then it shouldn't be used with that method. As well as it being called out explicitly in the documentation, it's also called out implicitly in the name `Func` implying a pure function.

> Shouldn't the invocation of addValueFactory be thread safe given that it is a concurrent class?

It is thread safe:

* It will not corrupt the state of the dictionary.
* It will never write an incorrect value due to a key being changed by another thread.
* Any simultaneous call to `AddOrUpdate` will either act before it does (causing its function to be repeated), or act after it, upon the value it wrote (perhaps causing that call's function to be repeated).

The possibility of repeats is required by this method being thread-safe, unless it was to completely lock on at least that key.

> As in guaranteed to be executed once.

That is not entailed or even suggested by it being thread-safe.

> If TValue implements IDisposable and the addValueFactory gets invoked twice then don't we have a framework induced memory leak?

No, the leak (of whatever resource) wasn't induced by the framework. In order to provide a thread-safe get-or-add operation, that doesn't block in the face of heavy concurrency, it is necessary to have the possibility of the factory being called more than once, for the same reason why compare-and-swap-based updates may repeat the CAS (think of a classic Michael & Scott lock-free queue).

Developers will very often have synchronisation requirements beyond those provided by a given structure, and it is then up to them to provide them.

Calling `GetOrAdd` with a non-pure function, and not dealing with the potential consequences, is a bug in the calling code, not the fact that there could be consequences. It's no different to the bug of doing `if (concurrentStructure.Count != 0) doSomethingWith(concurrentStructure.First());`

Either lock on the concurrent dictionary (use an inclusive-exclusive lock like `ReaderWriterLockSlim` with the usual operations having inclusive ("read") locks so they remain concurrent with each other, and the operations which need greater isolation having the exclusive ("write") lock), or clean up the repeats (if the type of the values is a reference-type, then any values created that are not identity-equal to the result of the get-or-add didn't make it and should be disposed).

**Comment by herecydev** [comment]
"Calling GetOrAdd with a non-pure function, and not dealing with the potential consequences, is a bug in the calling code, not the fact that there could be consequences."

Thanks for the detailed reply. I understand the consequences can be mitigated on the calling code and can obviously adjust for that in the future. Was there a specific design decision that led you to the implementation we have at the moment? Would you always expect a pure func passed to the dictionary? Perfomance? etc?

**Comment by JonHanna** [comment]
I can't speak of the design process, as I'm not from Microsoft, just an enthusiast who started of with a plan of getting a simple website running on a Linux server, and in looking up details of .NET Core, ended up spending time contributing to corefx instead. (Well, it **is** a cool project).

I can speak a bit as to why I would (and have, in a very differently implemented concurrent dictionary) have done precisely the same thing, though.

The over-all goal of a concurrent structure is of course to ensure that all uses of the structure are in and of themselves thread-safe, while ideally allowing each call to return as quickly as possible, with as little interference from other threads as possible.

By "in and of themselves" I mean that each operation will either succeed, or fail due to a well-defined reason with a well-defined error, with the expected result upon the structure, leaving the structure in a valid state. A further quality that isn't always needed but is certainly very useful (and provided by `ConcurrentDictionary`) is that of serialisability: That it be possible to take the history of concurrent operations, and produce a single-thread series of operations where all of them take place in the same relative order to each other as observed by any of the participating threads (e.g. if thread B read a value set by thread A then this read would always be after that write) which would have the same result. Or to put it another way, while there might not be a single true "state of the object" as seen by all cores, it always acts as if there is, and that state is a sensible one.

Given this, we have a building-block for concurrent code, but it's one that can still be used in a non–thread-safe manner. A classic case would be reading a value, deciding to do something on the basis of that value, and then acting after the value has in fact been changed by another thread.

In a way this is comparable to how `int` is thread-safe in and of itself (read and write of `int` is atomic) but of course `int` can be used in non-thread-safe ways if we combine reads and writes based on the value read, with `++x` sometimes not being an acceptable piece of code, as it doesn't play well with other code, if `x` is 3 and one thread does `++x` while another does `--x` then the only possible value for `x` if those operations where both atomic would be `3` (either inc, then dec or dec, then inc) we could in fact end up with 4 (inc after dec, but based on the value before dec) or 2 (dec after inc, but based on the value before inc).

If we need an atomic increment, we use `Interlocked.Increment()` to guarantee atomicity. Likewise `Interlocked.CompareExchange()` allows us to write to `x` but only if it still has the value it had when we decided what to write, which doesn't remove all related problems (the ABA problem comes to mind), but it does allow us to build larger pieces of concurrent code based only on this very small piece of atomicity (it's enough in fact, to build a concurrent dictionary, though `ConcurrentDictionary` does not take this CompareExchange-only approach).

A typical use of `CompareExchange()` will read a value, attempt to replace that value, and then on the basis of whether it succeeded or not either:

1. Happily deal with successful operation.
2. Give up unhappily (failure reported or exception thrown).
3. Give up happily (we didn't change the state, but we're happy with what the state now is)
4. Loop around and try again. Perhaps re-computing the value to set, perhaps not.

(Think of a Michael & Scott lock-free queue, or if you aren't familiar with them, check them out as they're a reasonably simple but still practical demonstration of the point).

Now, the minimum a concurrent dictionary can provide is that the value associated with each key is analogous to an `int` in that reads and writes to that value is in itself atomic. Hence `dict[key] = val;` and `var val = dict[key];` are each guaranteed to be atomic in the same way that `x = 1` and `y = x` are for integers.

Just as the atomicity of `int` is not enough for a lot of thread-safe use without locking, so that atomicity to `ConcurrentDictionary` is not enough for a lot of thread-safe use of it, so it needs some methods comparable to the `Interlocked` methods.

The most basic is perhaps `TryUpdate`. It acts pretty much exactly the same way as `CompareExchange`; if the value is currently the same as `comparisonValue` it is over-written, other wise it is not.

There are two other things that `ConcurrentDictionary` needs to deal with. One of them is that unlike an `int`, keys can not just have a variety of values, but also be absent or present. It therefore needs methods that conditionally add or remove. `GetOrAdd(TKey, TValue)` obviously fits in there, as does `TryRemove(TKey, TValue)`.

Now, at this point we've pretty much a full set of complements to `int` in terms of atomic methods available, as well as comparable methods that deal with presence and absence of keys.

But we've the disadvantage of dealing with a heavier object than `int` is.

Let's consider wanting to multiply-assign an arbitrary `int` to another `int`. We have two options. We could use a lock:

```C#
private static object atomicAddLockObject = new object();
public static void AtomicMult(ref int value, int multiplier)
{
	if (multiplier != 1)
	{
		lock(atomicAddLockObject)
			value *= multiplier;
	}
}
```

Or we could use `CompareExchange()`:

```C#
public static void AtomicMult(ref int value, int multiplier)
{
	if (multiplier != 1)
	{
		int current;
		int found;
		do
		{
			current = value;
			found = Interlocked.CompareExchange(ref value, current * multiplier, current);
		} while (current != found);
	}
}
```

Both basic approaches have their place. In the case of heavy concurrent access the first ends up with lock-queues, while the second ends up with loops.

Now let's consider the analogous case with a `ConcurrentDictionary<int, int>` if there were only the methods we've so far described.

We could obtain a lock, and that's not necessarily a bad idea - higher level locks can have their place along side concurrent structures. There really isn't anything the implementer of `ConcurrentDictionary` can do to help here, as it's all really in the hands of the developer using it.

We could also spin similar to the `Interlocked` approach:

```C#
public static void AtomicMult(ConcurrentDictionary<int, int> dict, int key, int multiplier)
{
	if (multiplier != 1)
	{
		int current = dict[key];
		while (!dict.TryUpdate(key, current * multiplier, current))
		{
			current = dict[key];
		}
	}
}
```

This sort of looping that is common with `Interlocked` will be common with `ConcurrentDictionary` too (and still is considering there's no `TryUpdate(TKey key, Func<TValue, TValue> updateFactory)`).

As:

1. The approach will be common.
2. `Func`s are convenient.
3. The implementer of `ConcurrentDictionary` has the opportunity to do some of the looping in a tighter spot than developers using the class do.

It therefore makes sense to provide methods that do that looping for you, and do it more efficiently (which among other things makes the looping happen less often) than you can from the outside.

Methods that take the approach of locking, which is necessary if you need to ensure that factory methods are only ever called once, are less of a gain:

1. The details of just what needs to be locked upon will vary, with the calling-code's developer being best placed to judge.
2. The implementer of the dictionary has little advantage over the calling-code's developer in terms of efficiencies, indeed the calling-code's developer may have opportunities to scope locks to particular details that the dictionary implementer cannot.
3. If you're only going to call once, and if you lock on the outside rather than internally, you don't necessarily need a `Func` which have their own inefficiencies, so we might as well not insist on their being the approach used.

In all therefore, the methods that take `Func` and loop add value that methods that that take a `Func` and guarantee never to loop would not.

**Comment by herecydev** [comment]
> The details of just what needs to be locked upon will vary, with the calling-code's developer being best placed to judge.

Definitely agree with that one, and I do feel that it's probably a better idea to have a pure function. Some very good insights there, thanks for taking the time to explain them.

**Comment by JonHanna** [comment]
It's good to be as pure as one can as often as one can, in programming at least. If it really is unavoidable, there are ways around it. Say for example with a `DisposableType` that must be disposed:

```C#
DisposableType value = dict.GetOrAdd(key, k => { var created = new DisposableType(k); toRemove = created; return created; });
if (toRemove.Count != 0 && ReferenceEquals(toRemove.Last(), value))
    toRemove.RemoveAt(toRemove.Count - 1);
foreach(DisposableType unused in toRemove)
    unused.Dispose();
```

Which can be generalised:

```C#
public static TValue GetOrAddDisposeUnused<TKey, TValue>(this ConcurrentDictionary<TKey, TValue> dict, TKey key, Func<TKey, TValue> valueFactory) where TValue : class, IDisposable
{
    List<TValue> produced = new List<TValue>();
    TValue result = dict.GetOrAdd(key, k => { TValue val = valueFactory(k); produced.Add(val); return val});
    int prodCount = produced.Count;
    if (prodCount != 0)
    {
        if (ReferenceEquals(produced[prodCount - 1], result))
            --prodCount;
        for (int idx = 0; idx != prodCount; ++idx)
            produced[idx].Dispose();
    }
    return result;
}
```

Or even:

```C#
public static TValue GetOrAddCleanUpUnused<TKey, TValue>(this ConcurrentDictionary<TKey, TValue> dict, TKey key, Func<TKey, TValue> valueFactory, Action<TValue> cleaner) where TValue : class
{
    List<TValue> produced = new List<TValue>();
    TValue result = dict.GetOrAdd(key, k => { TValue val = valueFactory(k); produced.Add(val); return val});
    int prodCount = produced.Count;
    if (prodCount != 0)
    {
        if (ReferenceEquals(produced[prodCount - 1], result))
            --prodCount;
        for (int idx = 0; idx != prodCount; ++idx)
            cleaner(produced[idx]);
    }
    return result;
}
```

**Comment by sblackler** [comment]
Firstly, let me thank you for your thorough reply - I'm sure others will stumble across and it will help them in the future also.

I do agree that it is up to the consumer to manage the life cycle of the objects where possible. This is not where I am saying the change should happen. Granted I probably didn't explain myself clearly enough and I will try a few examples to illustrate my point using CAS.

This is what I expect to observe using the `GetOrAdd` method:

    T value = factory(key);
    while(!Interlocked.CompareExchange(ref somethingInternal, value, null) == null)
         Thread.SpinWait(20);

But this is what we are actually seeing:

    while(!Interlocked.CompareExchange(ref somethingInternal, factory(key), null) == null)
         Thread.SpinWait(20);

If the factory method was pure, then the worst that we should see is an additional method invocation + memory allocations and method calls that the factory has. That said, all because the function is intended to be pure then it doesn't mean that the object doesn't need cleaning up (as per your suggested workaround, which is what I was sort of thinking needs to happen). I didn't mean earlier to suggest that the framework should be cleaning this up for me. Instead, I was aiming at the point that the factory should only ever be invoked once (so also consider the case where the factory takes a considerable amount of time to create the object but is not disposable and has no observable side effects).

**Comment by stephentoub** [comment]
> This is what I expect to observe using the GetOrAdd method

If that's the behavior you want, then you can use ```GetOrAdd(key, factory(key));``` rather than the overload that takes a delegate.

> Firstly, let me thank you for your thorough reply

Yes, nice response, @JonHanna.  In addition to everything Jon said, we explicitly chose not to invoke the delegate while holding a lock in part because it's a great recipe for deadlock.  If GetOrAdd did something in its delegate that tried to write to the dictionary, for example, that could deadlock, due to the use of fine-grained locks in the dictionary (multiple threads could end up taking the locks in different orders).  We could work around that by taking all of the locks, but that defeats the optimizations provided by ConcurrentDictionary, actually making it slower than just taking a single lock around a regular Dictionary, and it doesn't solve other deadlocks, like the delegate running some code which takes a lock, and having another thread holding that lock trying to write to the dictionary).

**Comment by herecydev** [comment]
> it's a great recipe for deadlock.

That's perfect. That's a great use case for not locking the factory. Thanks again to you both for a good write up.

**Comment by JonHanna** [comment]
Oh, I forgot about the deadlock risk because while the general principles are the same, the only such class I ever attempted didn't use locks.

If you did take all the locks, then as well as the hit of that in itself, it would then depend on re-entering locks, which it's good to develop a sense of queasiness about, IMO.

**Comment by JonHanna** [comment]
> so also consider the case where the factory takes a considerable amount of time to create the object but is not disposable and has no observable side effects

If:

1. The factory takes a considerable length of time.
2. The factory has to be called in the method, because it depends on some feature of the key that isn't already entailed by the key's equality (e.g. if the dictionary was case-insensitive and the factory case-sensitive).
3. You cannot tolerate repeats (already implied by the considerable length of time).
4. It's at all likely that the key could be changed or removed

Then you really do want to take a lock on the whole collection, or obtained from a separate collection of locks.

If point 2 doesn't hold, then I'd suggest considering:

```C#
TValue value;
if (!dict.TryGetValue(key, out value))
{
    TValue produced = valueFactory(key);
    value = dict.GetOrAdd(key, produced);
    if (!ReferenceEquals(value, produced))
    {
        // we lost the race, clean-up
        produced.Dispose();
    }
}
```

As then you can only have at most one extraneous factory call per thread, and clean-up is simple.

Alternatively, if you really must call it only once:

```C#
if (!dict.TryGetValue(key, out value))
{
    lock(factoryLock)
    {
        if (!dict.TryGetValue(key, out value))
        {
            dict[key] = valueFactory(key);
        }
    }
}
```

So locking is purely on the factory calls alone, not affecting any other code. Striped locks, indexed on the hash of the key, could be used to further reduce the impact of locking.

**Comment by JonHanna** [comment]
> This is what I expect to observe using the GetOrAdd method:

Your code here makes sense if the value you try to add does not depend upon the exact details of the key, but `GetOrAdd` has to assume that it does, perhaps in ways not reflected by what keys the dictionary considers equivalent.. For that reason it is more like my `AtomicMult` in that it updates the value, based on the current value, in a manner that is atomic to an outside observer (a `Func` passed to `GetOrAdd` is not an outside observer), and may therefore have to loop to do so.

**Comment by sblackler** [comment]
From reading everything here today it appears that you've done all that you can do - the deadlocks is a very good point (though that would seem nuts to lock inside there, but I guess there are cases where you might want to).

Thanks all for your time and clarification :)

**Comment by stephentoub** [comment]
Thanks for the discussion.

**Comment by JonHanna** [comment]
> (though that would seem nuts to lock inside there, but I guess there are cases where you might want to)

The main possibility would probably be if you did something (potentially quite far down a chain of calls) that altered the dictionary, leading to it acquiring a lock. In particular its relatively easy for it to ensure it doesn't have deadlocks by managing lock acquisition order, but if the call was via a delegate called within a lock then it doesn't know which locks it holds.
