### ISSUE TITLE
`JsonEncodedText` has a different behaviour in netcoreapp2.2 than netcoreapp3.0

### ISSUE THREAD

**Issue by ycrumeyrolle** [dotnet/corefx#40702]
Given the following code:
```
        [Fact]
        public void JsonWriterTest()
        {
            var jsonEncodedText = "{\"test\":\"" + JsonEncodedText.Encode("value+1") + "\"}";
            var bufferWriter = new FixedSizedBufferWriter(4096);
            Utf8JsonWriter writer = new Utf8JsonWriter(bufferWriter);
            writer.WriteStartObject();
            writer.WriteString("test", "value+1");
            writer.WriteEndObject();
            writer.Flush();
            var expected = Encoding.UTF8.GetString(bufferWriter.Formatted);
            Assert.Equal(expected, jsonEncodedText);
        }
```

When running the test in netcoreapp3.0, this is fine.
When running in netcoreapp2.2, I have the following error:
```
    Assert.Equal() Failure
                                 ↓ (pos 19)
    Expected: {"test":"value\u002b1"}
    Actual:   {"test":"value\u002B1"}
                                 ↑ (pos 19)
```
`JsonEncodedText` escapes in lowercase, since `Utf8JsonWriter` escapes in uppercase.
@ahsonkhan

**Comment by ycrumeyrolle** [comment]
According to https://tools.ietf.org/html/rfc7159#section-7:

>    Any character may be escaped.  If the character is in the Basic
   Multilingual Plane (U+0000 through U+FFFF), then it may be
   represented as a six-character sequence: a reverse solidus, followed
   by the lowercase letter u, followed by four hexadecimal digits that
   encode the character's code point.  **The hexadecimal letters A though
   F can be upper or lower case.**

Uppercase & lowercase are valid, but the different behaviours are disturbing.

**Comment by ahsonkhan** [comment]
What version of the S.T.Json package are you referencing when targeting platforms older than .NET Core 3.0? Presumably you are referencing preview 8 from nuget: https://www.nuget.org/packages/System.Text.Json/4.6.0-preview8.19405.3

This issue has been fixed in preview9 and in master. So, if you grab the latest nightly or wait for preview9 to ship, you should see that we consistently use upper-case when writing.

Try using a newer version, say:
```csproj
<PackageReference Include="System.Text.Json" Version="4.6.0-preview9.19421.4" />
```

We previously were writing as lower-case within the Utf8JsonWriter, but changed it to use the JavascriptEncoder which writes upper-case (and that matches JsonEncodedText as well).

Note the lower-case 'a' changing to 'A'

Before (preview8):
https://github.com/dotnet/corefx/blob/bc10b53838bc84ac2b626e16eee1338183ee55c8/src/System.Text.Json/src/System/Text/Json/Writer/JsonWriterHelper.Escaping.cs#L614-L633

Now (preview9+):
https://github.com/dotnet/corefx/blob/2d2abb32db879c877e14310c892faeeef756e27d/src/System.Text.Json/src/System/Text/Json/Writer/JsonWriterHelper.Escaping.cs#L336-L355


I'll add this test case to the `Utf8JsonWriter` as a test enhancement, but as far as I can this issue around casing inconsistency between .NET Core 3.0 and older platforms (like 2.2) cannot be reproduced.

@ycrumeyrolle, please feel free to re-open if you find otherwise, once you try it on preview9.
