### ISSUE TITLE
System.Text.json issue with comments

### ISSUE THREAD

**Issue by JulienM28** [dotnet/corefx#40745]
.Net core 3 preview8

It's impossible to add 
// Comments in json files 

Deserialization throw an exception

Newtonsoft Json worked perfectly in ths case.

**Comment by Gnbrkm41** [comment]
[JsonSerializer.ReadCommentHandling](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.readcommenthandling?view=netcore-3.0#System_Text_Json_JsonSerializerOptions_ReadCommentHandling)?

**Comment by ahsonkhan** [comment]
@JulienM28 - If your concern is with reading/deserializing JSON containing comments (either //comment\r\n or /* comment */), you can pass in [JsonCommentHandling.Skip](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsoncommenthandling?view=netcore-3.0) to [JsonReaderOptions.CommentHandling](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonreaderoptions?view=netcore-3.0) or [JsonSerializerOptions.ReadCommentHandling](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions?view=netcore-3.0) to ignore the comments as, @Gnbrkm41 mentioned.

For writing comments using the `Utf8JsonWriter`, you can call [WriteCommentValue](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writecommentvalue?view=netcore-3.0), which will emit comments using /*...*/ format.

Presumably, you just want to ignore the comments and not actually read them to see the values (which is why `Skip` will work for you). By default, we detect comments and throw since that is invalid JSON.

If that doesn't work for you, please provide more details about your scenario and what exactly is failing, and feel free to re-open the issue. A sample repro including the payload that's causing the issue would be great.
