### ISSUE TITLE
Interpreting Expression results in InvalidCastException on 3.0 but not 2.2

### ISSUE THREAD

**Issue by chrarnoldus** [dotnet/corefx#40968]
Consider the following code:

```c#
using System;
using System.Linq.Expressions;
using System.Runtime.InteropServices;

namespace ConsoleApp1
{
    class Program
    {
        static DayOfWeek Cast(int i) => (DayOfWeek) i;

        static void Main(string[] args)
        {
            Expression<Func<DayOfWeek[]>> expr = () => new[] {Cast(1)};

            Console.WriteLine(RuntimeInformation.FrameworkDescription);
            Console.WriteLine("preferInterpretation=false:" + expr.Compile(false)()[0]);
            Console.WriteLine("preferInterpretation=true:" + expr.Compile(true)()[0]);
        }
    }
}
```

On 2.2, the output is as follows:

```
.NET Core 4.6.27817.03
preferInterpretation=false:Monday
preferInterpretation=true:Monday
```

On 3.0 however, the second evaluation of the Expression (with preferInterpretation=true) results in an exception being thrown:

```
.NET Core 3.0.0-preview9-19423-09
preferInterpretation=false:Monday
Unhandled exception. System.InvalidCastException: Object cannot be stored in an array of this type.
   at System.Array.InternalSetValue(Void* target, Object value)
   at System.Array.SetValue(Object value, Int32 index)
   at System.Linq.Expressions.Interpreter.NewArrayInitInstruction.Run(InterpretedFrame frame)
   at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Linq.Expressions.Interpreter.LightLambda.Run(Object[] arguments)
   at Thunk(Func`2 )
   at ConsoleApp1.Program.Main(String[] args) in C:\git\ConsoleApp1\ConsoleApp1\Program.cs:line 17
```

Can this regression be resolved in the final version of 3.0?

**Comment by danmosemsft** [comment]
Please leave issue active for 3.0.x consideration after merging to master

**Comment by stephentoub** [comment]
Re-opening to track port to 3.0.x

**Comment by danmosemsft** [comment]
@cton per my mail earlier in the week, you can prep a 3.0 PR for this per the usual process, if you believe it merits it. 3.1 is another option.

If neither, you can close this issue.

**Comment by cston** [comment]
@danmosemsft, I've created #41261 targeting 3.0.x.

**Comment by EamonNerbonne** [comment]
I'm also running into cases where the expression tree interpretation now results in incorrect output when the expression boxes enums.  That's a little nastier, because I only thought to look for that because of crashes as above (which are easy to find).

An example would be the following:

```C#
static DayOfWeek Monday() => DayOfWeek.Monday;
static string GetTypeName(object o) => o.GetType().Name;
static void Main(string[] args)
{
   Expression<Func<string>> expr2 = () => GetTypeName(Monday());
   Console.WriteLine("preferInterpretation=false:" + expr2.Compile(false)());
   Console.WriteLine("preferInterpretation=true:" + expr2.Compile(true)());
}
```

Which returns

```
preferInterpretation=false:DayOfWeek
preferInterpretation=true:Int32
```

The actual scenario involved `someEnumConstant.Equals(computedEnumValue)`, but clearly this affects any boxed enum value from a return expression.  An incorrect equals computation could lead to pretty nasty bugs, potentionally.

Additionally, the linked PRs include test cases that have NewArrayInit expressions, but that's actually not the real issue here; we're just lucky that Array.SetValue happens to assert that the type is exactly correct (even though the arrays don't actually require that when accessed directly).   So in any case it's probably wise to have a test case without an array.

**Comment by EamonNerbonne** [comment]
Even shorter case:

```C#
static DayOfWeek Monday() => DayOfWeek.Monday;
static void Main(string[] args)
{
   Expression<Func<string>> expr2 = () => Monday().ToString();
   Console.WriteLine("preferInterpretation=false:" + expr2.Compile(false)());
   Console.WriteLine("preferInterpretation=true:" + expr2.Compile(true)());
}
```

**Comment by danmosemsft** [comment]
@cston should this be closed now https://github.com/dotnet/corefx/pull/41261 is merged?

**Comment by danmosemsft** [comment]
ping @cston

**Comment by cston** [comment]
@EamonNerbonne, thanks for reporting the latest repro. It looks like that case is fixed with this change.
