### ISSUE TITLE
Implement support for getting Base64 bytes from JsonElement that's backed by a JsonNode

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#41132]
Along with implementing support for Base64, add tests as well.

```C#
string base64String = "ABA=";
using (JsonDocument doc = JsonDocument.Parse($"{{\"data\":\"{base64String}\"}}"))
{
    JsonElement root = doc.RootElement;
    JsonElement data = root.GetProperty("data");
    byte[] base64Bytes = data.GetBytesFromBase64(); // {0, 16}
    Console.WriteLine(base64Bytes.Length); // Returns 2
    Console.WriteLine(base64String == Convert.ToBase64String(base64Bytes)); // Returns true

    JsonElement roundtripViaNode = JsonNode.DeepCopy(root).AsJsonElement();
    data = roundtripViaNode.GetProperty("data");
    // Throws System.NotSupportedException: 'Specified method is not supported.'
    base64Bytes = data.GetBytesFromBase64();
    Console.WriteLine(base64Bytes.Length);
    Console.WriteLine(base64String == Convert.ToBase64String(base64Bytes));
}
```

https://github.com/dotnet/corefx/blob/e8efb815275c8323fedc950ca3596474fa5e23c3/src/System.Text.Json/src/System/Text/Json/Document/JsonElement.cs#L487-L504

![image](https://user-images.githubusercontent.com/6527137/64934371-35c13e80-d7ff-11e9-9acd-a32c027bc4a8.png)

cc @kasiabulat

**Comment by ahsonkhan** [comment]
@danmosemsft - adding tests alone won't be sufficient, since the implementation currently throws `NotSupportedException`. My intent with this issue was to fill in the implementation as well along with adding tests (hence the issue title stating "Add support...").

**Comment by danmosemsft** [comment]
Ah I see...feel free to fix it back!

**Comment by danmosemsft** [comment]
Thanks - assigned!

**Comment by AntonLandor** [comment]
Alright, I've made an implementation that should be tested now. However, I haven't been able to since this solution adds a public method to the JsonString class. In JsonElement.cs I wrote [this](https://github.com/AntonLandor/corefx/blob/3ab1753549c1092a3894c2bd6b51135e4f0b2cc5/src/System.Text.Json/src/System/Text/Json/Document/JsonElement.cs#L498-L501). Which meant I had to make the implementation for getting the base-64 bytes in [JsonString.cs](https://github.com/AntonLandor/corefx/blob/3ab1753549c1092a3894c2bd6b51135e4f0b2cc5/src/System.Text.Json/src/System/Text/Json/Node/JsonString.cs#L117-L135). And I also made the [following](https://github.com/AntonLandor/corefx/blob/3ab1753549c1092a3894c2bd6b51135e4f0b2cc5/src/System.Text.Json/src/System/Text/Json/Node/JsonString.cs#L78-L88). Note that these are not tested yet.

This solution however gives the following errors:

> Build FAILED.
> 
> /home/anton/.nuget/packages/microsoft.dotnet.apicompat/5.0.0-beta.19476.6/build/Microsoft.DotNet.ApiCompat.targets(143,5): error : MembersMustExist : Member 'System.Text.Json.JsonString.GetBytesFromBase64()' does not exist in the reference but it does exist in the implementation. [/home/anton/Documents/Studies/corefx/src/System.Text.Json/src/System.Text.Json.csproj]
> /home/anton/.nuget/packages/microsoft.dotnet.apicompat/5.0.0-beta.19476.6/build/Microsoft.DotNet.ApiCompat.targets(143,5): error : MembersMustExist : Member 'System.Text.Json.JsonString.TryGetBytesFromBase64(System.Byte[])' does not exist in the reference but it does exist in the implementation. [/home/anton/Documents/Studies/corefx/src/System.Text.Json/src/System.Text.Json.csproj]
> /home/anton/.nuget/packages/microsoft.dotnet.apicompat/5.0.0-beta.19476.6/build/Microsoft.DotNet.ApiCompat.targets(157,5): error : MatchingRefApiCompat failed - The reference assembly doesn't match all the APIs in the implementation for '/home/anton/Documents/Studies/corefx/artifacts/bin/System.Text.Json/netcoreapp-Debug/System.Text.Json.dll'. To address either fix errors in the reference assembly (referenced as implementation in compat errors for this reverse compat check), add the issues to the baseline file '/home/anton/Documents/Studies/corefx/src/System.Text.Json/src/MatchingRefApiCompatBaseline.txt' or disable this check by setting RunMatchingRefApiCompat=false in this project. [/home/anton/Documents/Studies/corefx/src/System.Text.Json/src/System.Text.Json.csproj]
> 
This is ofcourse since I'm changing the API of JsonString which is what I should do, right? If this is correct, how do I build this? I tried looking around the documentation but did not find anything relevant. Since this solution also changes the API, we have to make the [API Review Process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md), right?

**Comment by ahsonkhan** [comment]
> This is ofcourse since I'm changing the API of JsonString which is what I should do, right? If this is correct, how do I build this? I tried looking around the documentation but did not find anything relevant. Since this solution also changes the API, we have to make the API Review Process, right?

You shouldn't need to make any public API changes for this issue (but yes, in that case, it would have to go through API review). **The `TryGetBytesFromBase64` method on `JsonString` can be internal.**

As an FYI, for the error you are seeing, you have to expose the public API you are adding from the ref project, build that first, and then build the source/tests project. To re-iterate though, you shouldn't try adding new public APIs here. This issue is primarily an implementation detail of `JsonElement` that needs to be fixed. We can re-consider making the API public on `JsonString`, separately.
See 
https://github.com/dotnet/corefx/blob/969ce665afee70b2d591e5c271525c927a8834d0/src/System.Text.Json/ref/System.Text.Json.cs#L16

**Comment by ericstj** [comment]
Fixed by https://github.com/dotnet/corefx/pull/41467?

**Comment by ahsonkhan** [comment]
Yep.
