### ISSUE TITLE
Encoding.Convert with IBM285 incorrect

### ISSUE THREAD

**Issue by worksofliam** [dotnet/corefx#41145]
Hello

It looks like `Encoding#Convert` is returning the incorrect ASCII when using `IBM285`.

```csharp
string myvar = "C88593939640A6969993845B";
byte[] raw = new byte[myvar.Length / 2];
for (int x = 0; x < raw.Length; x++)
  raw[x] = Convert.ToByte(myvar.Substring(x * 2, 2), 16);

string output = Encoding.ASCII.GetString(Encoding.Convert(Encoding.GetEncoding("IBM285"), Encoding.ASCII, raw)));
```

if I decode EBCDIC `C88593939640A6969993845B`

* Using `IBM037`: `Hello world$` - correct
* Using `IBM285`: `Hello world?` - incorrect, result should be `Hello world£`

@NattyNarwhal can confirm this issue and may have more to say on the issue.

Liam

**Comment by worksofliam** [comment]
Original bug found in issue https://github.com/worksofbarry/NetRPG/issues/27

**Comment by NattyNarwhal** [comment]
I can reproduce it at least as far back as .NET 4; in that case, it gets swapped with a replacement character.

Interestingly, it's also reproducible with Mono, and that is AFAIK still using its own from-scratch implementation.

**Comment by worksofliam** [comment]
Here's the test for each CCSID: 37 and 285.

![image](https://user-images.githubusercontent.com/3708366/64991070-272a6400-d89f-11e9-87ca-6c3995369a90.png)

**Comment by tarekgh** [comment]
@worksofliam I believe you have a problem in your code that you convert the result to ASCII encoding. Here is some more details may simplify. 

If you execute the following code:
```C#
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

            Encoding encoding = Encoding.GetEncoding("IBM285");
            byte [] bytes = new byte[] { 0x5B };
            string s = encoding.GetString(bytes);
            Console.WriteLine($"{(int)s[0]:x}");
```

This convert the the code point 0x5B in the IBM285 code page to string and print the character ordinal value. The 0x5B in IBM285 is ```£```. the result of the code is 0x00A3 which is the Unicode character ```£``` which is perfectly correct.
Now, the problem in your code is you are using the ASCII encoding to convert 0x5B from IBM285. 

```C#
string output = Encoding.ASCII.GetString(Encoding.Convert(Encoding.GetEncoding("IBM285"), Encoding.ASCII, raw)));
```

This means this code will first convert 0x5B from IBM285 to Unicode which will produce the value 0x00A3 correctly. Then it will convert the Unicode 0x00A3 to ASCII encoding. ASCII encoding only support character up to 0x7F which means 0x00A3 is invalid character in the ASCII encoding and will produce ```?``` as default invalid character. 

This problem doesn't happen when using IBM037 because the code point 0x5B in that code page is ```$``` and this will get converted to the Unicode character 0x0024. When you convert 0x0024 using the ASCII encoding will be converted correctly because it is in the encoding range.

I am not sure why you use ASCII encoding at all in your conversion and why you don't just convert  directly using the encoding class as I showed in my sample code here?

Let me know if you have any question.

**Comment by NattyNarwhal** [comment]
I converted from UTF-8 and had the same problem; I guess that's why I got the replacement character reproducing on v4.0 instead of a `?`.
