### ISSUE TITLE
CMS should support attributes for counter-signers

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#41158]
https://github.com/dotnet/corefx/issues/25449 has added support for adding unsigned attributes to signers. It has been noted though this feature should also work for counter-signers as user might want to add a timestamp to the counter signature. There are some questions which need to be investigated first:
- unsigned attributes are also used for storing counter-signatures - currently counter signing counter signature is not supported - is this something we also need to directly support? (yes?)
  - should counter-counter signature sign original content or content stored by the SignerInfo? (original?)
- signed attributes are technically speaking allowed in the counter SignerInfo - I cannot think on how this would reasonably work at the moment though so presumably not support it?

cc: @bartonjs @heng-liu

**Comment by vcsjones** [comment]
> currently counter signing counter signature is not supported

My 2c, I've rarely support for counter-signing a counter signature. The only time I've needed counter signatures from an unsigned-attribute signature is szOID_NESTED_SIGNATURE nested signatures for Authenticode, but I think that is out of scope here. I don't see any reason to go out of the way to make sure it doesn't work.

**Comment by heng-liu** [comment]
In our case, we need timestamp to be added as unsigned attributes for both signatures and countersignatures, to provide long-term validity even after the signing certificate's validity period has expired.
https://github.com/NuGet/Home/wiki/Package-Signatures-Technical-Details#-timestamps

**Comment by heng-liu** [comment]
We don't have counter-counter signature in our scenarios. SignerInfo.CounterSignerInfos, one level up is enough in our case.

**Comment by heng-liu** [comment]
THis is @rrelyea typing on @heng-liu's laptop now...
How soon could we have a daily build of 3.1 with this fixed? 
We'd love to not have to work around it...as we would rather be as efficient as possible with our work.

**Comment by krwq** [comment]
@heng-liu @rrelyea I've sent you an offline e-mail with the answers

**Comment by bartonjs** [comment]
I think the API already refuses to (in one way or another) deal with counter-counter-signers (other than you can see that a counter-signer has a counter-signer attribute; and there's no reason for this issue to change that.

Other unsigned attributes (RFC3161 timestamping is probably the target scenario) should be able to be added to a counter-signer (or removed from the counter-signer, I suppose) as freely as they are on regular signers.

Adding or removing signed attributes after signing isn't (sensibly) possible, it would invalidate the signature.  The entire (counter-)signer needs to be removed and simply re-sign.  (Existing signed attributes work, because... well, they do :smile:).

**Comment by danmosemsft** [comment]
Asking for confirmation whether they need backport.

**Comment by bartonjs** [comment]
Closing the issue again since it was decided v5 is good enough.
