### ISSUE TITLE
Remove WinHttpHandler fallback from HttpClientHandler

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#41182]
A developer can explicitly use WinHttpHandler by referencing the nuget package and constructing one.  The meant-to-be-temporary environment-variable-controlled fallback is not only additional code to be maintained and additional complexity on how the code is structured, it forces every consumer of System.Net.Http.dll on Windows to carry the WinHttpHandler code internal to System.Net.Http.dll, which increases the size of the binary by ~70K.

**Comment by davidsh** [comment]
Unlike #41183 which will remove CurlHandler completely including the implementation and specific tests, removing the fallback to WinHttpHandler will result in almost no test coverage for WinHttpHandler except those tests in the System.Net.Http.WinHttpHandler/tests/* folders.

Do you think as part of implementing this issue, we should leave some WinHttpHandler testing in the main System.Net.Http/tests/FunctionalTests/* folder? And to do means that we would use the currently PlatformHandler* abstract test class. But instead of toggling the AppContext / EnvironmentVariable, we would simply create the WinHttpHandler() class directly.

**Comment by stephentoub** [comment]
> will result in almost no test coverage for WinHttpHandler except those tests in the System.Net.Http.WinHttpHandler/tests/* folders.

That's a good point.

> we would use the currently PlatformHandler* abstract test class. But instead of toggling the AppContext / EnvironmentVariable, we would simply create the WinHttpHandler() class directly.

Sounds like a good solution.

**Comment by stephentoub** [comment]
@eiriktsarpalis, since you assigned https://github.com/dotnet/corefx/issues/41183 to yourself, mind taking this one, too?  They're probably best done together.

**Comment by karelz** [comment]
Triage: Should be AFTER #41183. Testing -- we will need thoughts on how to test WinHttpHandler without it being a fallback.

**Comment by ManickaP** [comment]
Functional tests of WinHttpHandler will be brought back in [339](https://github.com/dotnet/runtime/issues/339); otherwise, this is fixed.
