### ISSUE TITLE
Diagnostic Activity Async issue

### ISSUE THREAD

**Issue by carl-berg** [dotnet/corefx#41228]
Not sure if this is the right repo to report this but i'm experiencing an issue with `Activity`. This code works as i expect, in the child "scope" `Activity.Current` has a new `Id`:
```csharp
public async Task Execute()
{
    var activity = new Activity("Executing root").Start();
    Console.WriteLine($"Executing in root scope \t{Activity.Current.Id}");
    await Task.Delay(50);
    var childActivity = new Activity("Child scope");
    Console.WriteLine($"Executing in child scope \t{Activity.Current.Id}");
    await Task.Delay(50);
    childActivity.Stop();
    activity.Stop();
}
```
but when i move creation of child scope activity into another async method:
```csharp
public async Task Execute()
{
    var activity = new Activity("Executing root").Start();
    Console.WriteLine($"Executing in root scope \t{Activity.Current.Id}");
    await Task.Delay(50);
    var childActivity = await StartActivity("Child scope");
    Console.WriteLine($"Executing in child scope \t{Activity.Current.Id}");
    await Task.Delay(50);
    childActivity.Stop();
    activity.Stop();
}

private async Task<Activity> StartActivity(string activityName)
{
    await Task.Delay(50);
    return new Activity(activityName).Start();
}
```
..then both these console logs have the same `Activity.Current.Id`. 
Reading this [documentation](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md), i would assume that it would work in async contexts aswell?:
>The current activity is exposed as static variable, Activity.Current, and flows with call context, including async calls, so that it is available in every Start/Stop event callback.

I experience the same behavior of package `System.Diagnostics.DiagnosticSource` both in version `4.5.1` and the latest pre-release `4.6.0-rc1.19456.4`.

**Comment by tommcdon** [comment]
@sywhang

**Comment by sywhang** [comment]
@carl-berg This is an expected behavior of Activity. 

Simply put, `Activity.Current` flows into async calls, but not back out into the caller. The reason for this is that `Activity.Current` is a static variable that uses `AsyncLocal` internally. From your example, inside `StartActivity` at the beginning, `Activity.Current.Id` would be equal to the ID of `Activity` created in `Execute` before `StartActivity` was called. When you created and started the new activity inside `StartActivity`, that switched `Activity.Current` to the newly created Activity's ID, but only for the scope of that `StartActivity` (and note that from `Execute`'s context, `Activity.Current` hasn't been updated). So in `Execute`, when it's done `await`ing for `StartActivity`, it receives a new `Activity` that was created inside `StartActivity`, but `Activity.Current` is not updated in this context, so it still prints the same ID as the one printed above.

**Comment by carl-berg** [comment]
Thanks @sywhang for the explanation. It seems a bit confusing to me why one would want this behavior, but i'm sure there's a good reason for it. Now that i'm aware of it, I can work around it. Thanks!
