### ISSUE TITLE
Use PooledByteBufferWriter in Utf8JsonWriter

### ISSUE THREAD

**Issue by Martin1994** [dotnet/corefx#41225]
Currently `Utf8JsonWriter` uses `ArrayBufferWriter<byte>` instead of `PooledByteBufferWriter`:
https://github.com/dotnet/corefx/blob/5bc2806f33090e78b38fafe4d5b46d5a0a4c1f08/src/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.cs#L46
Is there any reason behind it? 

Recently I did a benchmark on `System.Text.Json`, and I found that the async serialization method (writes to `Stream`) uses less memory than the synchronized method (writes to `Utf8JsonWriter` which writes to `Stream`). I believe the use of `ArrayBufferWriter<byte>` in `Utf8JsonWriter` is the reason why synchronized consumes more memory.

|                     Method |     Mean |     Error |    StdDev |   Median |      Min |      Max | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|--------------------------- |---------:|----------:|----------:|---------:|---------:|---------:|------------:|------------:|------------:|--------------------:|
|           System.Text.Json | 578.6 ns | 1.7358 ns | 1.6236 ns | 578.4 ns | 576.3 ns | 582.2 ns |      0.0975 |           - |           - |               616 B |
|     System.Text.Json_Async | 592.6 ns | 1.3711 ns | 1.2825 ns | 592.6 ns | 590.9 ns | 594.8 ns |      0.0471 |           - |           - |               304 B |

_Reference: [https://github.com/Martin1994/JsonJitSerializer/blob/7ad4ba036b8becc53d7beed8abaeb399a88437d7/README.md#json_tostream_loginviewmodel_](https://github.com/Martin1994/JsonJitSerializer/blob/7ad4ba036b8becc53d7beed8abaeb399a88437d7/README.md#json_tostream_loginviewmodel_)_

Since I build a serialization library on top of `Utf8JsonWriter`, my library, as well as all the third party libraries who make use of `Utf8JsonWriter`, will see the same thing that the async serialization method consumes less memory.

**Comment by bartonjs** [comment]
While `Utf8JsonWriter` isn't documented as thread-safe, there are still some minimal thread-safety guarantees that we take in the platform. The easiest way of describing it for this issue is "using a non-thread-safe object on multiple threads can only corrupt that object".

With `Utf8JsonWriter` the problem would manifest as something like

```
ThreadA: writer.WriteString(TheLittleBookOfCalm);
ThreadA:     writer._bufferWriter.GetMemory(someAmount);
ThreadA:        pool-return array0, rent array1, return array1.AsMemory(0, someAmount)
<context switch>
ThreadB: writer.WriteString(WarAndPeace);
ThreadB:     writer._bufferWriter.GetMemory(someBiggerAmount);
ThreadB:        pool-return array1, rent array2, return array2.AsMemory(0, someAmount)
ThreadB:     writer._savedMemory = (array2.AsMemory)
ThreadB:     finish
ThreadB: ArrayPool.Rent (get array1)
<context switch>
ThreadA:    writer._savedMemory = (array1.AsMemory)
<finish>
```

The `Utf8JsonWriter` instance ends up talking about `array1` after it has been returned to the pool, and in this degenerate example after it has already been rented by another call.  The writer then keeps writing to `array1` (until it next grows again), which is an ArrayPool-based use-after-free bug.  (If this race condition happens with `ArrayBufferWriter` it simply means `array1` doesn't get garbage collected... no other part of the process is using `array1`.)

So that's why `Utf8JsonWriter` can't use `PooledByteBufferWriter` by default.

Why can `JsonSerializer` do it?  Because the `JsonSerializer.Serialize` method is the only owner of the `Utf8JsonWriter` instance it can prove the instance never gets (ab)used cross-threads, and it can pass it an `IBufferWriter` instance that doesn't work so hot multithreaded.

If using pooled arrays is important to your throughput goals, one answer is to copy `PooledByteBufferWriter` locally and provide it to `Utf8JsonWriter` (like the serializer does).  We won't be making that type public, because it's way too easy to set yourself up for use-after-free bugs.
