### ISSUE TITLE
Where's the TransformBlock functionality on SHA256?

### ISSUE THREAD

**Issue by DaBackman** [dotnet/corefx#4123]
Hi, I have this working code in good old .NET 4.5 console application:

```c#
var sha256 = System.Security.Cryptography.SHA256.Create();
var message = new byte[] {1, 2, 3};
var s = new byte[32];
var m = sha256.ComputeHash(message);
sha256.TransformBlock(m, 0, m.Length, m, 0);
sha256.TransformFinalBlock(s, 0, s.Length);
var x = sha256.Hash;  // x = {236, 196, 174, 128, 243....}
```

How do I achieve the same thing when targetting dnxcore50 or a Universal Windows 10 App?
I get errormessages saying TransformBlock() / TransformFinalBlock() / Hash does not exist, but ComputeHash() seem to exist and work as before.
I have added dependency to "System.Security.Cryptography.Algorithms": "4.0.0-beta-23409"

**Comment by bartonjs** [comment]
@DaBackman In the API scrubbing phase of setting up CoreFX we wanted to separate the stateful (`TransformBlock` and `TransformFinalBlock`) and "stateless" (`ComputeHash`) parts of HashAlgorithm, because they didn't have good isolation.

https://github.com/dotnet/corefx/commit/49cdb6f1e82d867d98f1d888bb369a1f2711497d introduced a new type, `IncrementalHash` to handle the multiple-call stateful hash provider.  The tests added in that commit show some usage, but the equivalent to your sample would be:
```C#
var message = new byte[] { 1, 2, 3 };
var s = new byte[32];
byte[] m;
byte[] x;

using (HashAlgorithm sha256 = SHA256.Create())
{
    m = sha256.ComputeHash(message);
}

using (IncrementalHash sha256 = IncrementalHash.CreateHash(HashAlgorithmName.SHA256))
{
    sha256.AppendData(m);
    sha256.AppendData(s);
    x = sha256.GetHashAndReset();
}
```

`IncrementalHash` is in that same package, so you should hopefully be good to go.  I'd like to know if not :).

**Comment by DaBackman** [comment]
@bartonjs I tried it, verified the output and it works like a charm!
Thank you for the swift assistance!
