### ISSUE TITLE
API Proposal: Add Encoder/Decoder for new System.Buffer types

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#41326]
#41166 Discusses APIs for the Encoding classes in while this issue is about the stateful **Encoder** and **Decoder** types:

```C#
#nullable enable
namespace System.Text
{
    public static class EncodingExtensions
    {
            public static void Convert(this Encoder encoder,
                ReadOnlySpan<char> chars,
                IBufferWriter<byte> writer,
                bool flush,
                out long bytesUsed,
                out bool completed);

            public static void Convert(
                this Encoder encoder,
                in ReadOnlySequence<char> chars,
                IBufferWriter<byte> writer,
                bool flush,
                out long bytesUsed,
                out bool completed);

            public static void Convert(
                this Decoder decoder,
                in ReadOnlySequence<byte> bytes,
                Span<char> chars,
                bool flush,
                out SequencePosition bytesUsedPosition,
                out int charsUsed,
                out bool completed);

            public static void Convert(
                this Decoder decoder,
                in ReadOnlySequence<byte> bytes,
                IBufferWriter<char> writer,
                bool flush,
                out long charsUsed,
                out bool completed);
    }
}
```

These extensions would likely live in the same assembly as these abstractions since encoding couldn't directly take a dependency on those types (unless we push them lower in the stack).

cc @GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
Suggestions:

```C#
public static class EncodingExtensions
{
        public static void Convert(this Encoder encoder,
            ReadOnlySpan<char> chars,
            IBufferWriter<byte> writer,
            bool flush,
            /* int maxBytesPerChar, - REMOVE */ 
            /* int out charsUsed, - REMOVE */
            /* out SequencePosition charsUsedPosition, - REMOVE */
            out long /* was int */ bytesUsed,
            out bool completed);

        public static void Convert(
            this Encoder encoder,
            in ReadOnlySequence<char> chars,
            IBufferWriter<byte> writer,
            bool flush,
            /* int maxBytesPerChar, - REMOVE */
            out SequencePosition charsUsedPosition,
            out long bytesUsed,
            out bool completed);

        public static void Convert(
            this Decoder decoder,
            in ReadOnlySequence<byte> bytes,
            Span<char> chars,
            bool flush,
            out SequencePosition bytesUsedPosition,
            out int charsUsed,
            out bool completed);

        public static void Convert(
            this Decoder decoder,
            in ReadOnlySequence<byte> bytes,
            IBufferWriter<char> writer,
            bool flush,
            /* int maxCharsPerByte, - REMOVE */
            /* out SequencePosition bytesUsedPosition, - REMOVE */
            out long charsUsed,
            out bool completed);
}
```

`Convert` methods which have an "infinite" destination sink (such as `IBufferWriter<T>`) will always consume the entire source buffer, so there's no need to out a position which always points to the end of the sequence. Additionally, _maxBytesPerChar_ and _maxCharsPerByte_ wouldn't be needed by this API, so we can drop them as parameters.

**Comment by davidfowl** [comment]
Thanks! 

> Additionally, maxBytesPerChar and maxCharsPerByte wouldn't be needed by this API, so we can drop them as parameters.

Those came from my scratch implementation. I needed those in order to allocate a minimum buffer size from the `IBufferWriter<char/byte>`, otherwise you may end up getting a Span back that doesn't have enough to make progress on the input.

**Comment by GrabYourPitchforks** [comment]
> I needed those in order to allocate a minimum buffer size from the `IBufferWriter<char/byte>`, otherwise you may end up getting a Span back that doesn't have enough to make progress on the input.

The issue is that the caller almost certainly doesn't have that information, which is going to lead to callers guessing a value, which means the implementation will need to be resilient against bad guesses, which means the implementation needs to "do the right thing" regardless. So it's just noise in the API sruface.

**Comment by davidfowl** [comment]
So the implementation would still need that information and we would expose it in another way?

**Comment by GrabYourPitchforks** [comment]
If the implementation needs the information, it can get it from `Encoder.GetByteCount` / `Decoder.GetCharCount`. But the implementation shouldn't require such information, since there are other viable strategies. One such strategy is "Optimistically assume a 1:1 mapping of bytes to chars, but don't ask for more than 4 KB at a time. If at any point we can't make forward progress, fall back to `GetByteCount` / `GetCharCount` to query the exact count required so that we don't end up in an infinite loop."

**Comment by davidfowl** [comment]
I've removed it from the API surface but it's absolutely needed. Maybe we can guess a number like 32 😄.

> One such strategy is "Optimistically assume a 1:1 mapping of bytes to chars, but don't ask for more than 4 KB at a time. If at any point we can't make forward progress, fall back to GetByteCount / GetCharCount to query the exact count required so that we don't end up in an infinite loop."

Sure, as long as it's efficient. Its something that may only need to happen once.

**Comment by GrabYourPitchforks** [comment]
> I've removed it from the API surface but it's absolutely needed.

I absolutely 100% guarantee it's not. The current `Encoder` and `Decoder` APIs work just fine today (and have worked for nearly 20 years) without ever exposing such a concept and without requiring their caller to be aware of such. :)

**Comment by davidfowl** [comment]
> I absolutely 100% guarantee it's not. The current Encoder and Decoder APIs work just fine today (and have worked for nearly 20 years) without ever exposing such a concept and without requiring their caller to be aware of such. :)

Those APIs always take in a fixed target buffer, the new APIs allocate so this isn't like the past 20 years. In the past, if you ended up needing more space, the loop would exit and completed would be false. This would require the caller to pass in a bigger buffer. Now that the method is taking an IBufferWriter<T>, it has to allocate. that argument was about reducing the waste but it can be done in other ways (though not as efficiently).

**Comment by GrabYourPitchforks** [comment]
The reason the _maxCharsPerByte_ argument doesn't make sense is that it's sometimes impossible to know. For example, say that I perform a "final flush" on an `Decoder` instance, passing in an empty input:

```cs
decoder.Convert(ReadOnlySequence<byte>.Empty, destCharSpan, flush: true, ...);
```

If the current `Decoder` instance has internal stored state, it's possible that it could write a non-zero number of characters to the destination span, even with a zero-length input. What should the caller pass for _maxCharsPerByte_ in this situation? No number when multiplied by zero will produce an answer that's large enough to hold the output. It's the same problem as division by zero.

If you wanted to suggest a new API `Decoder.GetMaxCharCount(int byteCount, bool flush)` that would serve as an _O(1)_ "worst case" equivalent to the existing `Decoder.GetCharCount` APIs, feel free to open a new tracking issue. It'd probably need to follow a try-pattern instead since otherwise we'd be adding a new abstract method onto an abstract base type, but you get the gist. :)

**Comment by davidfowl** [comment]
I’m not too worried about it. As long as it can be reasonably implemented without wasting too much space then it’s all good. We can take he current API to review and see what else is needed

**Comment by terrajobst** [comment]
* Should these be `OperationStatus` APIs? We decided not to, because we modeled these overloads after the existing APIs.
* We considered replacing the outed sequence position with an `int`, but slicing with a position is simpler and more performant (because O(1)).
* We should rename `bytesUsedPosition` to just `position`
* Same as #41166: if we move `ReadOnlySequence<T>` and `IBufferWriter<T>` to corlib, we should make those instance methods.

**Comment by GrabYourPitchforks** [comment]
I do not believe it is feasible to write a reliable, high-performance implementation of the particular `Convert` method called out below. So I propose modifying the signature slightly to allow for improved reliability.

```cs
#nullable enable
namespace System.Text
{
    public static class EncodingExtensions
    {
            // REMOVE this overload
            public static void Convert(
                this Decoder decoder,
                in ReadOnlySequence<byte> bytes,
                Span<char> chars,
                bool flush,
                out SequencePosition bytesUsedPosition,
                out int charsUsed,
                out bool completed);

            // SUBSTITUTE this signature instead
            // (it matches the pattern used in the other Convert methods approved by this issue)
            public static void Convert(
                this Decoder decoder,
                ReadOnlySpan<byte> bytes,
                IBufferWriter<char> writer,
                bool flush,
                out long charsUsed,
                out bool completed);
    }
}
```
