### ISSUE TITLE
Make S.Runtime.Serialization.Xml 4.1 be legal for WCF to reference

### ISSUE THREAD

**Issue by roncain** [dotnet/corefx#4132]
Currently, if WCF attempts to take a dependency on S.R.Serialization.Xml 4.1.0, it causes CrossGen to fail because the new contract does not exist in TestNet, Desktop, etc.  This became a P0 blocker during RC1, and it forced WCF to revert to referencing 4.0.10.

We need WCF to be able to refer to 4.1 (or later) versions of S.R.S.Xml without breaking TFS lab builds.

To verify the fix, increase the dependency to 4.1.0 in WcfOpen\src\System.Private.ServiceModel\src\project.json, update the lock file and then do a full build of NDP.  You need to run CrossGen manually.  I did it like this from a Razzle window:
msbuild /m /nologo %_NTROOT%\Binaries.niproj /p:TargetPlatform=x86 /p:TargetClrAssembly=core /p:ProductGroupsToBuild="PK" /l:%VsSDKToolsPath%\StatusLogger.exe;context="Process Ship Binaries/Generate Native Images" /flp:append;logfile=e:\_scr\CrossGen-2015-10-23-05-07-08.log /flp1:append;errorsonly;logfile=e:\_scr\CrossGen-2015-10-23-05-07-08.err"

**Comment by zhenlan** [comment]
The reason WCF cannot reference the 4.1.0 version of S.R.Serialization.Xml is because the CrossGen for TestNet is using desktop binaries. According to @weshaggard, this will not be an issue when TestNet is updated to use .NET Core binaries. S.R.Serialization.Xml has been updated to support desktop as OOB and has no plan to do the same for TestNet. Assigning to @weshaggard to fix TestNet.

**Comment by weshaggard** [comment]
@khdang I believe you have the information you need from our offline email to address this issue.

**Comment by khdang** [comment]
As far as I know Wes has removed TestNet, so we shouldn't have this issue anymore.

**Comment by weshaggard** [comment]
Correct this should no longer be an issue.
