### ISSUE TITLE
System.Net.Sockets.Tests.IPPacketInformationTest.Equals_NonDefaultValue_Success failing in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#41361]
https://dnceng.visualstudio.com/public/_build/results?buildId=366911&view=ms.vss-test-web.build-test-results-tab&runId=11102506&paneView=debug

Configuration: `netcoreapp-Linux-Release-x64-Debian.9.Amd64.Open`

```
System.Net.Sockets.Tests.IPPacketInformationTest.Equals_NonDefaultValue_Success

Assert.True() Failure\nExpected: True\nActual: False

 at System.Net.Sockets.Tests.IPPacketInformationTest.GetNonDefaultIPPacketInformation() in /_/src/System.Net.Sockets/tests/FunctionalTests/IPPacketInformationTest.cs:line 74
   at System.Net.Sockets.Tests.IPPacketInformationTest.Equals_NonDefaultValue_Success() in /_/src/System.Net.Sockets/tests/FunctionalTests/IPPacketInformationTest.cs:line 30
```

@davidsh, @wfurt, @scalablecory, @eiriktsarpalis, @karelz

**Comment by eiriktsarpalis** [comment]
It's not clear from the stacktrace which assertion is failing, but I'm assuming it's [this one](https://github.com/dotnet/corefx/blob/e667c29636a622eb4f9493f75232b44e0ae90b29/src/System.Net.Sockets/tests/FunctionalTests/IPPacketInformationTest.cs#L79). It could be failing either because it's timing out (current timeout is 5 seconds) or because of a lost packet (the `UDPRedundancy` property is set to 1). I could try doubling the timeout for now.
