### ISSUE TITLE
TimeSpan precision was affected by core 3.0 release

### ISSUE THREAD

**Issue by idlerboris** [dotnet/corefx#41380]
Hi, there is a pull request https://github.com/dotnet/coreclr/pull/24279 which was merged to core 3.0. 

It removes an additional sum in TimeSpan.Interval method (`value >= 0 ? 0.5 : -0.5`) with comment in the description 
>This line was added because casting double to long was dropping the decimal part and we expect it to rounded off. This wont be the case anymore.

But, actually, it's still the case, because in the next line we have casting to long (`new TimeSpan((long)ticks)`). So, after upgrading to dotnet core 3.0, some TimeSpan conversions became slightly incorrect (i.e. the precision was actually decreased). For instance, you can use the following simple example and check it before and after that pull request:

```
var ts = TimeSpan.FromMilliseconds(34967800);
var ts2 = TimeSpan.FromSeconds(ts.TotalSeconds);
Assert.Equal(ts, ts2);
```

**Comment by stephentoub** [comment]
cc: @anipik

**Comment by Anipik** [comment]
Will take a look today

**Comment by Anipik** [comment]
I don't think so the removing the cast is the problem here because 
```
var ts = TimeSpan.FromMilliseconds(34967800);
```
results in 
```
{09:42:47.8000000}
    Days: 0
    Hours: 9
    Milliseconds: 800
    Minutes: 42
    Seconds: 47
    Ticks: 349678000000
    TotalDays: 0.40471990740740738
    TotalHours: 9.7132777777777779
    TotalMilliseconds: 34967800
    TotalMinutes: 582.79666666666662
    TotalSeconds: 34967.799999999996
    _ticks: 349678000000
```
This has the correct ticks value (which we get from the interval problem)

The problem is here
https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/TimeSpan.cs#L118

```
349678000000 * 1E-07 = 34967.799999999996
```
@tannergooding is this expected with floating point math ? can we correct it ?

**Comment by tannergooding** [comment]
Yes, it is expected. `1E-07` is not exactly representable and so it will introduce additional inaccuracies.

You should be dividing by `10000000.0` (which is exactly representable) if you want a more exact result.

This won't necessarily fix everything, as if the result is not exactly an integer or if the ticks is greater than 2^53, you also won't get an "exact" result.

**Comment by idlerboris** [comment]
@Anipik @tannergooding thank you for so fast reply here!

I've checked the fix with changing SecondsPerTick to `1 / 1000000.0`, it really works. Btw, I certainly understand that this won't help in every case, but as far as I understand, it should help for integer milliseconds cases (it is exactly what I wanted from the original question here).

P.S. @tannergooding excuse me for a silly question, but could you explain why 1e-07 is not exactly representable but `1000000.0` is? A link to some doc would be enough, thank you.

**Comment by tannergooding** [comment]
> @tannergooding excuse me for a silly question, but could you explain why 1e-07 is not exactly representable but 1000000.0 is? A link to some doc would be enough, thank you.

I'll try to explain it here and will link to some other articles at the bottom :)

A `float`/`double` is a number built from three parts: a sign, exponent, and significand. The "true" value of a them is then built by multiplying together the exponent and significand and taking the sign as is. The exponent for `float` and `double` is a power of 2, so all representable values are multiples of that power of 2..

Since `1` is a power of `2` (`2^0`), it means all integral values up to the size of the significand can be exactly represented (`1000000.0` hits this scenario). For `float` this is `2^24` and for `double` it is `2^53`. There is not, however, another power of `2` that is also a power of `10` in the exponent range (either positive or negative exponents), which means that most values that aren't powers of two can't be exactly represented and instead get rounded to the nearest representable value (`1 / 1000000.0` hits this scenario). 

Some more blog posts:
* http://fabiensanglard.net/floating_point_visually_explained/
  * This is a good summary of how binary floating-point works
* https://www.exploringbinary.com/
  * This is a series of blog posts over almost 10 years, each going into a particular area on floating-point

**Comment by idlerboris** [comment]
> Since `1` is a power of `2` (`2^0`), it means all integral values up to the size of the significand can be exactly represented (`1000000.0` hits this scenario). For `float` this is `2^24` and for `double` it is `2^53`. There is not, however, another power of `2` that is also a power of `10` in the exponent range (either positive or negative exponents), which means that most values that aren't powers of two can't be exactly represented and instead get rounded to the nearest representable value (`1 / 1000000.0` hits this scenario).

Thank you for your detailed answer! But, I know about representations of float/double, I just don't understand what is the difference between `ticks / 10000000.0` and `ticks * (1.0 / 10000000)` and why it helps here. I suppose it's because there are 1 vs 2 operations with doubles but don't have any knowledge of how the error is increasing by the number of operations.

**Comment by idlerboris** [comment]
Thank you!

So, what about the original problem? Does it make sense to change multiplying by `(1.0 / TicksPerSecond)` on dividing by `TicksPerSecond` to improve precision for integer milliseconds cases? For me, it looks like a very tiny change that will restore the same behavior (as it was before core 3.0). I'm not sure, should I create a pull request or it's enough to have this issue and you guys will do it when you have time?

**Comment by tannergooding** [comment]
I believe it makes sense. In general, ensuring accurate results should probably be the goal. @Anipik, any thoughts?

**Comment by Anipik** [comment]
yeah i agree with tanner that ensuring accurate results should be the first goal.

@idlerboris  feel free to throw up the PR  to fix this. you will have to make the change in Coreclr repo. You should also add the tests in the corefx repo.

The change is good for master,  i dont think it meets the criteria for 3.0.1 or 3.1. @tannergooding should we keep the change restricted to the master branch ?

**Comment by tannergooding** [comment]
I think just master is likely fine for now and we can discuss tomorrow if this should go for an initial bar check on 3.1 or if it should wait for additional feedback.

**Comment by idlerboris** [comment]
@Anipik 
Looks like I don't have the rights to add reviewers (as this section is not editable for me in new PRs). Perhaps, it would be available after tests, or I did something wrong (I tried to follow this one https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/contributing-workflow.md but it doesn't have any info about adding reviewers).

**Comment by Anipik** [comment]
@idlerboris the adding of reviewers is restricted to people with write access.
One way to go around is to just cc the reviewers in the comment.

**Comment by danmosemsft** [comment]
Was a conclusion reached about servicing? One option is to wait to see whether we get more reports.

**Comment by jkotas** [comment]
I think we should port this into 3.1. The fix is simple and it is a clear regression.

> whether we get more reports.

The reports we get shortly after release (ie this month) are for bugs that are very likely going to be hit by multiple customer. I do not think we need to wait for more reports to justify the back-port.

**Comment by jkotas** [comment]
PR with 3.1 port: https://github.com/dotnet/coreclr/pull/27010

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/issues/42280
