### ISSUE TITLE
Updating Microsoft.Windows.Compatibility to v3.0.0 Results in Build Errors

### ISSUE THREAD

**Issue by nick-beer** [dotnet/corefx#41403]
I recently update my Microsoft.Windows.Compatibility nuget from v3.0.0-preview5.19224.8 to v3.0.0.  After updating, I'm not longer able to build.  The build generates many errors similar to:

```
File.cs(1814,20): error CS0012: The type 'IAsyncAction' is defined in an assembly that is not referenced. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'. [G:\Project.NetCore_015px2u3_wpftmp.csproj]
```

This error is repeated for `IAsyncAction`, `IAsyncActionWithProgress<>`, `IAsyncOperation<>`, and `IAsyncOperationWithProgress<>`.

The lines that are generating these errors are places that we are awaiting a custom object that contains a Task<bool>.  That object has a `GetAwaiter` extension method that returns a TaskAwaiter<bool> - obtained from the contained Task<bool>.

The project's in question have Sdk="Microsoft.NET.Sdk.WindowsDesktop", and UseWpf and UseWindowsForms set to 'true'.

I've tried reproducing these build errors in a smaller application, but I haven't had any luck yet.  I'll keep trying to reproduce, but in the meantime, does anyone have any ideas?

**Comment by nick-beer** [comment]
When the `GetAwaiter` method is invoked as an extension method, I get the errors.  If I call it directly as a static method, there' is no error:
![image](https://user-images.githubusercontent.com/1509215/65797002-bbb08400-e133-11e9-84e5-cd99c288bc68.png)

**Comment by nick-beer** [comment]
Finally figured out how to reproduce the error.  See here: [https://github.com/nick-beer/GetAwaiterBug](https://github.com/nick-beer/GetAwaiterBug).  Adding a using statement for 'System' was the step I had previously been missing.  I suspect it has something to do with [these extension methods](https://apisof.net/catalog/System.WindowsRuntimeSystemExtensions.GetAwaiter(IAsyncAction))?

**Comment by safern** [comment]
The real problem is the `System.Runtime.WindowsRuntime` package, which is included in the new Compatibility package, which was actually included post preview5, that is why you didn't hit the issue in preview5. https://github.com/dotnet/corefx/commit/687ec698a4120a818dc8860bebfcd7a91df9a572

I'll dig a little bit more to see why this is happening, it seems like a facade might be broken, but still not sure.

**Comment by safern** [comment]
Ok, so I think the way to go here is to remove the `System.Runtime.WindowsRuntime` reference from the compat pack as it really not needed by our main customers when including the compat pack into their projects.

However, this seems like a compiler bug because no-one is using those extension methods at all, if you compile it by including `Windows.md` using the WinRT meta-package, it will succeed, but looking at the producing assembly, it doesn't even have a reference to `System.Runtime.WindowsRuntime`, so the fact that is being passed as a reference to the compiler is what is causing this to fail. /cc: @jaredpar 

As a workaround add this package reference to your project:
```xml
<PackageReference Include="System.Runtime.WindowsRuntime" Version="4.6.0" ExcludeAssets="all" />
```

@danmosemsft we would need to remove the reference to `System.Runtime.WindowsRuntime` from the compat pack, so I will mark this as 3.0 to service it. 
```

**Comment by danmosemsft** [comment]
@safern does this need a 3.0 PR?

**Comment by safern** [comment]
> @safern does this need a 3.0 PR?

Yes, I will port https://github.com/dotnet/corefx/pull/41419 now

**Comment by Tragetaschen** [comment]
@safern 
With regards to the compiler, this looks similar to https://github.com/dotnet/roslyn/issues/18673 (or https://github.com/dotnet/roslyn/issues/27107). The compiler considers the method for overload resolution even though it's not used. At least that's my understanding.

**Comment by safern** [comment]
Closing as we removed S.R.WindowsRuntime* from the compat pack. The roslyn question/issue I will follow up with their team to see if there needs to happen something on their side.
