### ISSUE TITLE
Console.OutputEncoding = Encoding.BigEndianUnicode; throw Exception.

### ISSUE THREAD

**Issue by newpost** [dotnet/corefx#41435]

**Comment by GrabYourPitchforks** [comment]
Per [the docs](https://docs.microsoft.com/en-us/dotnet/api/system.console.outputencoding), this property setter is contracted to throw if the caller attempts to set the output encoding to an unsupported encoding. So this behavior appears to be by design.

If you believe this issue was closed in error, please reactive and provide more information, including the exact exception message seen and the behavior you expect. Thanks!
