### ISSUE TITLE
Fix TFS integration for WebSockets.Client

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#4143]
In https://github.com/dotnet/corefx/blob/master/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.WinRT.cs:

```
// TODO: ** TFS BUILD IS BROKEN **  
                // This doesn't compile right now due to missing types 'WebErrorStatus' and 'RTWebSocketError' 
                 // Commenting out for now to allow the build to resume. 
                 //WebErrorStatus status = RTWebSocketError.GetStatus(ex.HResult); 
                 //var inner = new Exception(status.ToString(), ex); 
```

**Comment by pgavlin** [comment]
@mconnew do you have time to take a look at this?

**Comment by joshfree** [comment]
@davidsh you introduced this change.  What's the ramifications to shipping rc1 as-is?

**Comment by davidsh** [comment]
@joshfree I did not introduce the original change.  @mconnew did. So, he should comment on this.

The only thing I did was fix the build breaks on TFS due to the NETNative specific source files (living in GitHub) breaking the TFS build.  So, I commented out code in the TFS mirror files just to unblock the build.

**Comment by davidsh** [comment]
And by commenting out lines of code, we then suppressed the proper inner exception from showing up when errors are returned. So, this could impact developers in their error handling for RC1 (N developers with UWP apps) if we don't fix this up.
