### ISSUE TITLE
Installing System.Net.Http using Install-Package fails with "Dependency loop detected for package"

### ISSUE THREAD

**Issue by fqborges** [dotnet/corefx#41532]
I am installing packages to a folder using the following pwsh commands:

`Register-PackageSource -Location https://www.nuget.org/api/v2 -Name Nuget -ProviderName Nuget -Trusted -force`

`Install-Package -Name System.Net.Http  -ProviderName Nuget -Destination $somedir`

It fails with:
```
Install-Package : Dependency loop detected for package 'System.Net.Http'.
At C:\git\mobiltracker-ps-docker\Publish-PackageDll.ps1:81 char:1
+ Install-Package -Name $Name -ProviderName Nuget -Destination $Source  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : Deadlock detected: (System.Net.Http:String) [Install-Package], Exception
+ FullyQualifiedErrorId : DependencyLoopDetected,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```
It looks like the offending package is System.Diagnostics.DiagnosticSource v4.6.0

**Workaround:**

Installing in the current order works:

1. `Install-Package System.Diagnostics.DiagnosticSource -RequiredVersion 4.5.1 -Provider nuget`
2. `Install-Package System.Net.Http -Provider nuget`
3. `Install-Package System.Diagnostics.DiagnosticSource -Provider nuget`

**Comment by davidsh** [comment]
@joperezr

**Comment by ericstj** [comment]
There is no cycle in the package graph.  If you actually install the package on any target framework it will be successful.  There appears to be a problem with the cmdlet and how it chooses to download packages and it finds a false positive here. The cmdlet appears to evaluate all dependency groups and downloads a union of packages, and continues doing this down the stack.  Eventually it hits System.Diagnostics.DiagnosticsSource, which references System.Memory, which references System.Numerics.Vectors, which references NETStandard.Library, only on .NETStandard1.x.  NETStandard.Library references System.Net.Http, thus the cmdlet thinks there is cycle.  This cycle never exists in reality, since System.Numerics.Vectors only references NETStandard.Library for ns1.0-ns1.6, however System.Numerics.Vectors is never referenced for these TFMs (only on desktop and NS2.0)

This is a bug in the NuGet cmdlet belongs in https://github.com/nuget/home.

**Comment by fqborges** [comment]
Thanks for the info.

I will open an issue there.
