### ISSUE TITLE
System.Text.Json not working as expected (how Newtonsoft.json did) with [FromBody] WebApi parameter

### ISSUE THREAD

**Issue by giammin** [dotnet/corefx#41677]
before with Newtonsoft.json when calling a webapi like this

```
 [HttpPost]
public async Task<ActionResult> Post([FromBody]string someValue)
```

this worked:

`curl -H "Content-Type:application/json" https://localhost:5000/api/controller-X POST -d "'dsfdsafasf'" -v`

now with `System.Text.Json` there are no way to pass a simple string as a parameter.

I tried various combinatin like` {"someValue":"fsdfsdfsdf"}` or `{'someValue':'fsdfsdfsdf'}` or `someValue'=asdfsdfsdf` but without success

**Comment by ericstj** [comment]
@pranavkm @rynowak does this sound right?  I would have expected that MVC has a fast path for this.

FWIW, the following worked for me: `var str = JsonSerializer.Deserialize<string>("\"hello world\"");`
Perhaps you can try using double-quotes in your post command?

**Comment by pranavkm** [comment]
@ericstj MVC doesn't special case deserializing a string value, it pretty much passes the request Stream as-is to the input.

@giammin you want to pass a JSON string token to MVC.  JSON strings require that be double quoted - see http://www.json.org. Newtonsoft.Json was a bit more lax and allowed JSON (double quoted strings) and JavaScript strings (single quoted strings) which explains why `-d "'dsfdsafasf'"` works there. System.Text.Json is true to the spec which is why your binding's failing.

On my machine, I can get curl to work correctly if I author the call to curl like so:

```
curl -H "Content-Type:application/json" https://localhost:5000/api/controller-X POST -d "\"dsfdsafasf\"" -v
```

I used this https://stackoverflow.com/a/15828662 as my source to figure out how to author this correctly. You should use this to figure out what works best for your OS \ shell combination.

**Comment by giammin** [comment]
@pranavkm thanks for you reply. 
i already tried different quotes and escaping and I did some further tests but i always get this error: 

>  "'\\' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0."

and if I try something like:

`curl -H "Content-Type:application/json" https://localhost:5000/api/controller -X POST -d   "{\"someValue\":\"dsfjlsdajf\"}" -v`

i get:

>  "The JSON value could not be converted to System.String. Path: $ | LineNumber: 0 | BytePositionInLine: 1."

**Comment by giammin** [comment]
i resolved... 

the problem was powershell

adding` --%` resolved the issue  https://stackoverflow.com/a/24750582/921690
