### ISSUE TITLE
Could not load file or assembly 'System.IO.Ports, Version 4.0.1.0, Culture...' after upgrade to System.IO.Ports 4.6.0.

### ISSUE THREAD

**Issue by joseangelmt** [dotnet/corefx#41709]
After upgrade my .NETStandard v2.0 projects to System.IO.Ports Nuget package 4.6.0. I'm having the next error: 

> Could not load file or assembly 'System.IO.Ports, Version 4.0.1.0, Culture...'. The located assembly's manifest definition does not match the assembly reference.

The project's metadata shows references to `System.IO.Ports` version **4.0.1.0**, but the deployed version is **4.0.2.0**.

Analyzing the assemblies in the NuGet package, I can see the assembly in the `ref\netstandard2.0` folder has version **4.0.1.0** but the other assemblies (folder `lib\netstandard2.0, runtimes\osx\lib\netstandard2.0, runtimes\linux\lib\netstandard2.0, runtimes\win\lib\netstandard2.0`) has version **4.0.2.0**.

**Comment by safern** [comment]
Thanks @joseangelmt -- do you have a minimal repro or example on how to get this error?

**Comment by ericstj** [comment]
But when targeting desktop you get ref/net461 (4.0.2.0) lib/net461 (4.0.2.0).  The only framework that requires strict matching is .NETFramework, and for these (and most nuget packages) to work you need to enable automatic bindingRedirects.

In this case the package *could not* change the assembly version of ref/netstandard2.0 since it UAP16.0.16299 shipped that assembly inbox.  On .NETFramework we must version the assembly (to avoid an older copy from the GAC winning).  Thus the mismatch and the requirement for bindingRedirects.
