### ISSUE TITLE
Invalid file path generated from valid file path string

### ISSUE THREAD

**Issue by 0Keith** [dotnet/corefx#41757]
```
var expected = "C:\\PRN.json";
var path = Path.GetFullPath(expected);
Assert.AreEqual(expected, path);
```
```
Assert.AreEqual failed.
Expected:<C:\PRN.json>.
Actual:<\\.\PRN>.
```

**Comment by vcsjones** [comment]
I'm guessing this is because Windows handles files named PRN [specially][1], even if they have an extension.

If possible I would recommend not using files named PRN, NUL, etc.

[1]: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

**Comment by 0Keith** [comment]
I did change the the file name to "C:\db.PRN.json" and that correctly generates a valid path.

I believe an appropriate exception may be warranted rather than just generating an invalid path that then causes an ambiguous exception when attempting to open that file.

**Comment by vcsjones** [comment]
`\\.\PRN` seems correct to me since it is expanding PRN to the full Win32 device namespace. In that sense, `GetFullPath` has done the correct thing, and it is delegating to Windows' `GetFullPathNameW`, it appears. There is some history to this here https://github.com/dotnet/corefx/issues/11033#issuecomment-245145732.

As noted in the linked issue, you can use these file names if absolutely required by prefixing with `\\?\` so that any namespace expansion is disabled. However in doing so you are creating file names that other programs will probably not handle well. e.g. a file named `PRN.json`, Windows Explorer will be unable to delete.

/cc @JeremyKuhne

**Comment by stephentoub** [comment]
Yes. This is the Windows behavior, and there's little .NET can or should do to avoid it; as noted, any attempts to thwart Windows will result in other problems. In general, attempting to "undo" special-cases lower in a stack ends up being an uphill battle that causes other issues. Thanks for the report, though.
