### ISSUE TITLE
Add System.String constructors taking sbyte *

### ISSUE THREAD

**Issue by manu-silicon** [dotnet/corefx#4190]
If you have a lot of code that interops with C strings, chances are that you have used those constructors in the past. Not having them makes code a little bit more complicated to port to CoreCLR. So this would be a nice addition to have.

**Comment by mellinoe** [comment]
As anecdotal evidence, I've come across this constructor a lot when porting various things to the new surface area. I usually just replace it with the char* constructor, but I'm not really familiar with what could go wrong there (it usually seems to work, unless I'm just not paying enough attention).

**Comment by stephentoub** [comment]
> I usually just replace it with the char* constructor, but I'm not really familiar with what could go wrong there

I believe there's a fairly significant difference, at least in certain cases... sbyte* is treated as the platform's Ansi, whereas char* is treated as the platform's Unicode.  That means, for example, that on Unix, the sbyte* ctor will decode the data with UTF8, whereas the char* ctor will simply store the data into the string undecoded, i.e. assuming UTF16.  @ellismg can correct me if I got that wrong.

**Comment by mellinoe** [comment]
> whereas char* is treated as the platform's Unicode

That's probably the case... I think I have mostly tested Win32 functions this way, so perhaps they were fine with receiving a Unicode string.

**Comment by manu-silicon** [comment]
I would favor sbyte * to be treated as the platform's Ansi. Usually the char * is not an option on non-Windows platforms where we usually get either ASCII or UTF-8.

**Comment by ellismg** [comment]
Steve's understanding of the API is correct, modulo this statement:

> whereas char* is treated as the platform's Unicode

I think it would be more correct to say we always treat a char* as pointing to UTF-16 encoded data (since you could argue that UTF-8 is "the platform Unicode" on Linux and OSX)

> I would favor sbyte * to be treated as the platform's Ansi. Usually the char * is not an option on non-Windows platforms where we usually get either ASCII or UTF-8.

If we were to add this back, this is exactly the semantics we'd need to ensure.  This is the definition of the API today and we couldn't change this in .NET Core.

My guess for the reason they don't exist today is that we didn't want to expose APIs at this level of factoring that required us to pull encodings into the implementation.  I wasn't around when the decision was made, so that's just a hunch.  I think that you could easily convert uses of this API to `Encoding.Default.GetString(byte[])` (or just be explicit with `Encoding.UTF8.GetString(byte[])`).  That does require that you copy data from native memory to managed memory first, which is less than ideal, but at least there are options.

Regarding @mellinoe's question/statement

> I usually just replace it with the char* constructor, but I'm not really familiar with what could go wrong there (it usually seems to work, unless I'm just not paying enough attention).

If the underlying data is not actually a `byte*` but something like a `LPWSTR (or some other typedef that in Win32 means `wchar*`)` that is just manifesting itself as a `byte*`, you'll be fine (except you should update your signatures to actually say this thing is a `char*` so it's clear what's going on).  If it happens to point to data which is not encoding in UTF-16 at best you are going to corrupt text when you decode (for any character greater than 0x7F) and in the worst case you're going to walk pass the end of string (which is null terminated by a single byte instead of two bytes) and just start reading random garbage.  Unless you understand doing so is safe, you *should not* make this transformation.  At best you've introduced a globalization bug at worst, you have a buffer overflow.

**Comment by stephentoub** [comment]
> I think that you could easily convert uses of this API to Encoding.Default.GetString(byte[]) (or just be explicit with Encoding.UTF8.GetString(byte[])).

Marshal.PtrToStringAnsi also does the exact same thing, as it just calls that ctor after argument validation:
https://github.com/dotnet/coreclr/blob/bc146608854d1db9cdbcc0b08029a87754e12b49/src/mscorlib/src/System/Runtime/InteropServices/Marshal.cs#L140-L147

**Comment by AlexGhiondea** [comment]
It sounds like we are leaning **against** taking this API. 

@terrajobst, @stephentoub let me know if you think we should consider an API like this.

**Comment by manu-silicon** [comment]
@AlexGhiondea Do you have a rationale why this is leaning against this API?

**Comment by mellinoe** [comment]
>It sounds like we are leaning against taking this API.

We have already added it back:

https://github.com/dotnet/standard/blob/master/netstandard/ref/mscorlib.cs#L2964

**Comment by manu-silicon** [comment]
@mellinoe Missed this. Unless this is going to be withdrawn, I'm closing the issue.

**Comment by AlexGhiondea** [comment]
@manu-silicon it sounded like we did not want to add it back from the comments... but that was before netstandard 2.0 😄.

**Comment by terrajobst** [comment]
Yes, APIs like this will come back thanks to .NET Standard 2.0 :-)
