### ISSUE TITLE
Restructure our documentation

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/corefx#41954]
Followup for this issue: https://github.com/dotnet/corefx/issues/36057

As requested in [this comment](https://github.com/dotnet/corefx/issues/36057#issuecomment-541722131), we want to have our GitHub documentation recategorized before the corefx and coreclr repos get merged.

I modified the Documentation README.md to merge corefx and coreclr documentation, and include the wiki data I considered useful from my table above. But before I submit a PR with the new structure, I would like to get some feedback from the community.

Here is my proposed new structure:
https://github.com/carlossanlop/corefx/tree/NewReadme/Documentation

**Comment by ViktorHofer** [comment]
cc @danmosemsft @jkotas

**Comment by ViktorHofer** [comment]
It would be great to have a README.md file in the docs root that isn't too long but explains every sub-category so that developers can easily find the necessary information / create new docs in the best fitting category. At this point I would even do this as a cross-repo consolidation effort and already include coreclr's material and rename all the repository mentions to "runtime".

**Comment by jkotas** [comment]
The top level documentation for the merged repo is in https://github.com/dotnet/consolidation/tree/master/template already. Any additional edits to the top level README should be done on top of what is in that template, not against the corefx repo that your PR points to.

I am not sure why we need to be restructuring the documentation before the repo merge. I believe that the plan for the repo merge is to bring over everything almost intact, and then do further more significant restructuring (of all build scripts, sources, documentation, etc.) once the new repo is operational.

**Comment by ViktorHofer** [comment]
> Any additional edits to the top level README should be done on top of what is in that template, not against the corefx repo that your PR points to.

This is just an issue to discuss the categorization. The issue was placed here as it's a convenient place to discuss as the consolidation repo isn't visible for everyone. A PR would go in there of course as you correctly described. If I'm not mistaken, this issue is about discussing the categorization and a REAMDE.md file in the docs folder. This is not about the root README.md file.

> I am not sure why we need to be restructuring the documentation before the repo merge. I believe that the plan for the repo merge is to bring over everything almost intact, and then do further more significant restructuring (of all build scripts, sources, documentation, etc.) once the new repo is operational.

We can post-pone this effort to a later point of course. I just didn't see any reason to not already start with it.

**Comment by carlossanlop** [comment]
Thanks for your input, @jankotas.
From your last comment, it seems we should tackle this task at a later time, considering it would be confusing to have documentation on either repo (corefx vs consolidation) at this point.
@ViktorHofer and I can keep it in our radar, we can help restructure the documentation when the time comes.
