### ISSUE TITLE
The cultureInfo.EnglishName property returns different values for unknown cultures

### ISSUE THREAD

**Issue by 87Alex** [dotnet/corefx#42062]
In our code, we use the cultureInfo.EnglishName property to filter incorrect names as follows:

```c#
private string GetAspect(string cultureName) {
            CultureInfo cultureInfo;
            try {
                cultureInfo = CultureInfo.GetCultureInfo(cultureName);
            }
            catch {
                return "";
            }
            if(cultureInfo.EnglishName == string.Format("Unknown Locale ({0})", cultureName)) {
                return "";
            }
            return cultureInfo.Name;
        }
```

For the "xx-XX" cultureName value, the cultureInfo.EnglishName property returns "Unknown Locale (xx-XX)"
On a Linux machine, the cultureInfo.EnglishName returns "xx (XX)" that breaks our filter.

**Comment by scalablecory** [comment]
@tarekgh

**Comment by tarekgh** [comment]
@87Alex In general it is not guaranteed to have consistent globalization data between OS's and OS versions. so you can expect such discrepancies. The good news is we have a feature request which we are going provide in the next release https://github.com/dotnet/corefx/issues/32201 so I am going to close this issue here and you can follow the feature issue to use when it is out. 

side question, why you are filtering the cultures at all? even if you are requesting a culture that the OS try to fake it, it still valid to use. That is why OS's doing that.

**Comment by 87Alex** [comment]
Thank you, We will wait for the next release.
This method is just a part of a more complex project and check. We get the culture name from a file name and use it to load required culture values. Users can make a mistake in the file name. I got the difference in our tests and did not check how our application behaves with incorrect culture values.

**Comment by tarekgh** [comment]
> This method is just a part of a more complex project and check. We get the culture name from a file name and use it to load required culture values. Users can make a mistake in the file name. I got the difference in our tests and did not check how our application behaves with incorrect culture values.

I am not sure if this is right thing to validate. How the culture get included in the file name in the first place. You can run into scenarios having culture names in the file names that you assume it is not valid and can be valid. I suggest you go away from manually validating the culture this way or restrict the cultures to the current OS culture list. it is easy OS can add cultures in the future releases and if create file with such new culture names and use it in the previous OS version will fail.
