### ISSUE TITLE
Support in-memory X509Store

### ISSUE THREAD

**Issue by vcsjones** [dotnet/corefx#42096]
`X509Store` to my knowledge does not support an in-memory, ephemeral certificate store. This has at least one practical use, specifically on Windows where `StoreHandle` is passed to other Win32 functions I am platform invoking (`SignerSignEx3` via `SIGNER_CERT_STORE_INFO`). This is my primary use-case. Other potential uses include using it in .NET Core itself, as well as constructing a mock X509Store for testing scenarios.

In Windows, this would be implemented by calling `CertOpenStore` where the provider is `CERT_STORE_PROV_MEMORY`.

For macOS, I think implementing `IStorePal` with in-memory collection backing would work like `X509CertificateCollection(2)` - the underlying handle is not important there. I am not aware of a way to have an in-memory keychain.

For Unix, there is `X509StoreCtxCreate`, but OpenSSL tends to think of stores as chains. An in-memory store could be implemented with it, or it could just use the same mechanism as macOS.

Such functionality could also be used in places like https://github.com/dotnet/corefx/blob/a6159bb0929b5eb8b297a9a8ebba595d5f3a9bb0/src/System.Windows.Extensions/src/System/Security/Cryptography/X509Certificates/X509Certificate2UI.cs#L99

I have two questions.

1. Does it make sense for this to exist, or is this perhaps a too-out-there use case?

2. Assuming someone were to implement something like this, what would the API shape look like? Would it be public APIs, or is there something existing that can be use?

**Comment by bartonjs** [comment]
> X509Store to my knowledge does not support an in-memory, ephemeral certificate store.

If you call CertOpenStore manually, you can do `new X509Store(IntPtr)`.

Since an empty store doesn't really make sense on non-Windows systems I wouldn't really want to add it.  (Stores shouldn't be passed around as collections, that's what `store.Certificates` is for.)

**Comment by bartonjs** [comment]
> This has at least one practical use, specifically on Windows where StoreHandle is passed to other Win32 functions I am platform invoking (SignerSignEx3 via SIGNER_CERT_STORE_INFO).

If you're already doing the P/Invoke to call that, then this really just seems to be in the P/Invoke realm to me.  You can use the managed Add/Remove/CopyIntoACollection from the HCERTSTORE value as an IntPtr.

> Other potential uses include using it in .NET Core itself

Since it's already possible to do (with the SafeCertStoreHandle value) and no one does it, I don't think that we'd do that code "cleanup".  If we're using HCERTSTORE we're down in P/Invoke land already, and don't have much need for the indirection (unless it were to save a lot of code... but it's just "different" not "more legible").

> as well as constructing a mock X509Store for testing scenarios

On the one hand, that's possibly the most compelling argument.  On the other... it feels pretty slim.  The only thing that is really different in a method that takes the store vs the collection is the ability to add and remove... and those operations don't feel like they should be on a mainline path.

It wouldn't be a perfect analogue, since "Close() and re-open" would be different (the entire store vanishes)... so I'm really questioning the value.

**Comment by vcsjones** [comment]
>If you're already doing the P/Invoke to call that, then this really just seems to be in the P/Invoke realm to me

Yep. I use the constructor that takes the IntPtr handle, so I'm just making that p/invoke call, then using the existing X509Store to add some certificates to it (so I don't have to write that myself), etc. This would only save me two p/invoke calls (one to open and once to close since the ctor duplicates the handle, I have to close it myself again)

> so I'm really questioning the value.

Yeah, I was on the fence. Sometimes folks see something I don't, so I figured why not throw it out there. Since your initial reaction is similar to mine, I think it makes sense to close. Thanks for taking the time to write out your thoughts though!
