### ISSUE TITLE
Move non-Windows scripts over to Python

### ISSUE THREAD

**Issue by sokket** [dotnet/corefx#4213]
To help normalize our helper scripts cross-platform while removing environment dependencies (such as shells), we should switch our non-Windows scripts over from bash scripts to Python scripts. This will remove the Bash dependency (which is a heavy one) and add a Python dependency, which is installed by-default on our supported, non-Windows platforms to date (OS X and Ubuntu).

The scripts that need to be changed are:
- [ ] build.sh
- [ ] run-test.sh
- [ ] src/Native/format-code.sh
- [ ] src/Native/gen-buildsys-clang.sh

/cc @ellismg @mmitche
/fyi @janhenke @ghuntley @jasonwilliams200OK

**Comment by janhenke** [comment]
Sounds great!

**Comment by sokket** [comment]
Folks - let's use this as an area to chat about if we think this is the right direction to go or not :) I'm very open to feedback on this idea

**Comment by mmitche** [comment]
What are the default installed versions of python on osx and Ubuntu?

**Comment by janhenke** [comment]
Ubuntu is aiming for having only Python3 installed on the desktop. For the server image I am not sure, but Python 2 is clearly becoming legacy and should not be the target. Ubuntu 16.04 will Have python 3.5 as sole Python 3 version.

**Comment by sokket** [comment]
My OS X and Ubuntu versions are both on 2.7.6, but I have done ```apt-get update``` and ```brew update``` on my platforms.

It looks like (from the internet) that OS X Yosemite has 2.7.2 as default and Ubuntu has either 2.7.3 or 2.7.4

**Comment by janhenke** [comment]
@sokket Ubuntu 14.04 should have 2.7.5 (http://packages.ubuntu.com/trusty/python), but I do hope we are speaking about Python 3 here? Python 2 is outdated with no more feature development happening for quite some time now.

**Comment by mellinoe** [comment]
Why aren't we trying to target a solution that would just let us use the same scripts everywhere? Powershell or C# scripts seem like an obvious choice off the top of my head. Anything that moves us closer to a unified workflow is best, it's cumbersome having so many different environments to reason about and switch between.

Now, I'm aware that this probably isn't possible currently. I don't know how usable the above (ps/csx) are right now, maybe they don't work at all and won't for a while. But TBH, I'm actually not concerned about what sorts of scripts we are using in the meantime (python, bash, whatever) as long as we have a plan to migrate to a single script in the future.

**Comment by sokket** [comment]
Ah my mistake...good catch @janhenke! We are sticking with v2.* right now since that's whats default on the supported platforms; also, v3.* has had some issues (that I've hard of...nothing first-hand knowledge so let me know if this is incorrect) so I'd rather stick to the current-stable

@mellinoe If we want a unified script in PS then Powershell would need to be on Linux and stable; not to mention on any platform brought up by the community. Python fits this need already and in a stable state....plus it's hugely popular, which means (statistically speaking) that more people will be able to read / write the scripts as necessary

**Comment by mellinoe** [comment]
I think python 3 can be considered stable at this point... there have been releases for about 7 years it seems.

> If we want a unified script in PS then Powershell would need to be on Linux and stable; not to mention on any platform brought up by the community

Yeah, I did mention that I don't think it's possible currently. It would be nice to use those as they are .NET-based and would fit in here quite well (IMO). You bring up a good point that using something .NET-based would make it more difficult to port to new platforms.

**Comment by jasonwilliams200OK** [comment]
@sokket, Python2 and Python3 compatibility issues are already famous in build system world.
For example, like CMake, there is a Google counterpart for multi-platform build system called gyp written in Python v2. Node.js uses gyp when we build npm package wrapping some C lib. Google denied to upgrade gyp to Python 3 because unnecessary amount of hassle/work and now "the community" is deciding to upgrade it from their own. There are other examples which makes you believe that doing build stuff python is not much of a pleasant experience as it sounds. IMO, the best course of action would be to have scripts in `sh` instead of `bash` which is the default unix shell with widest availability (https://github.com/dotnet/home/issues/29).

**Comment by mmitche** [comment]
@jasonwilliams200OK Yeah, that kind of the track I was thinking on here.  LLVM uses 2.7 (which affects the LLILC project).  Given the compat issues, I think it's easier and more amenable to contributors to maintain two sets of 'simple' bash/sh and batch/powershell scripts that work out of the box 100% of the time rather than cause dependency pain.

**Comment by janhenke** [comment]
There are no compat issues. @mmitche @jasonwilliams200OK It is mostly either a big existing code base, where people have no time or motivation to port it to current standard or people not wanting to move ahead with new stuff.

Again *Python 2 is dead*. It is in deep maintenance mode, there will be no 2.8 release, just a 2.7 bugfix once in a while. As posted above, Linux distributions are actively trying to become *Python 3 only* in the default installation, which Ubuntu tries to archive in 16.04 LTS. So there should be no doubt that Python 2 is no option.

I also disagree with @jasonwilliams200OK about ```sh``` and ```bash```. Not only is Python easier to understand and to write for many people, it is also more powerful in it's default installation than ```sh```. And it is more likely to have Python by default then ```bash```.

**Comment by jasonwilliams200OK** [comment]
@janhenke, lately I am seeing loads of unnecessary disagreements. You are contradicting yourself BTW. Linux distributions are "trying" to become Python 3 only, but many distros are not going to have Python 3 out of the box in a foreseeable future. Consumers will have to install py3 as dependency to build corefx!

@saper, @akoeplinger, do you guys have any good/odd experiences with py3 which may bring some value to this discussion? Because what I know is sh is commonly used in install/build/start scripts in widely used software. One good example is npm, which uses `sh` in *every* package by default to execute the package and hence it is compatible with **all** Unix like operating systems.

**Comment by akoeplinger** [comment]
@jasonwilliams200OK I don't have python experience, but if we decide to use it, is there a way to write code compatible with py2+py3 at the same time without a lot of work?

I agree that python is a lot easier to understand than `sh`, on the other hand we're really not doing anything fancy in the existing scripts (looping over some variables, copying files around, invoking other programs), so I don't think moving to a higher-level language buys us much. 

If the plan is to have more complicated scripts (parsing/emiting JSON is a prime example that is just horrible to do in shell without a third-party program) then I'd favor moving away from shell, otherwise I think it's better to stick with it.

**Comment by saper** [comment]
On Fri, 30 Oct 2015, Peter Jas wrote:

> @janhenke, lately I am seeing loads of unnecessary disagreements. You
> are contradicting yourself BTW. Linux distributions are "trying" to
> become Python 3 only, but many distros are not going to have Python 3
> out of the box in a foreseeable future. Consumers will have to install
> py3 as dependency to build corefx!
> 
> @saper, @akoeplinger, do you guys have any good/odd experiences with
> py3 which may bring some value to this discussion? Because what I know
> is sh is commonly used in install/build/start scripts in widely used
> software. One good example is npm, which uses `sh` in *every* package
> by default to execute the package and hence it is compatible with
> **all** Unix like operating systems.

Regarding Python:

Python 2 is far from being dead. There is a significant push
towards Python 3 (also driven by the distributions). With
lots of effort one can try to keep scripts running on both
(I used to work on one such script, it's painful). 

People stuck with Python 3-as-default distributions
try to push for a change rather vocally, here's an example:

https://www.change.org/p/google-inc-upgrade-gyp-to-support-phyton-3

Somehow those people are less eager to address non-trivial
technical issues related to porting gyp to Python 3.

Regarding the issue at hand:

1. Is there any significant advantage for Windows if go full Python?
I don't see many .cmd scripts, and probably the infrastructure
used (msbuild) has nothing in command with non-Windows.

2. It would be good to collect all the dependencies
for the shell scripts and we need them. From a quick
glance I see "wget" or "curl" (could be also "fetch"
for FreeBSD), I saw "unzip" somewhere. 

3. The scripts could be made simpler, more robust
and shorter. I would aim at some Bourne shell baseline
(POSIX shell, maybe) and remove all bash-specific
things, because bash is an undefined language
(Korn Shell for example is). So using bash and
only bash should not be a dependency. For example,
the default FreeBSD /bin/sh should do as well.
I also see some typical signs of quick'n'dirty
shell coding like "pushd/popd" etc.

4. Let's keep in mind we have cmake already.

5. Unlike gyp which does some considerable
amount of processing the shell scripts here
are mostly used to call some external
programs. Python could give us advantage
of a built-in HTTP client for example,
but I do not like writing things
that are "aaa | bbb" in shell to
become "subprocess.this" and "subprocess.that".
Python is not the best tool to do it to me
(as much as I love Python).

So my proposal would be for next steps would be:

1. Identify all external commands/programs
that need to be called and why

2. Find out how to do HTTP - and more importantly
HTTPS. We currently do not check certificates
at all opening users to nasty attacks (did you
know that downloading nuget requires having
two different CA root certificates)?

3. I think current shell scripts can be reduced
to 15% of their size. Setting default variables
with out "if...fi". Proper use of "find"
to get a list of files. Probably a shell
function is needed to install nuget if needed,
shared among scripts. No idea why we
need "copy_test_overlay" in run-test.sh
and so on and so on..

4. If after this some significant logic is
left in the scripts, we can consider Python.

On the other hand, if you want python
- why not go for gyp. It probably
could replace all the scripts, cmake
and it could even generate Visual Studio
projects :)

**Comment by weshaggard** [comment]
I don't know a lot about Python but I do believe we should avoid having that dependency. I agree with @jasonwilliams200OK and @mmitche that we should stick with a simple sh script on non-windows and batch scripts on windows. These scripts are mostly going to be used for basic bootstrapping and then launching builds via msbuild or cmake. If we find ourselves doing more then that then we aren't putting the logic in the right place.

**Comment by sokket** [comment]
Mariana's work to remove scripts should take care of this issue
