### ISSUE TITLE
Add WolfSSL Support as an OpenSSL alternative

### ISSUE THREAD

**Issue by wirecat** [dotnet/corefx#42185]
WolfSSL is an SSL library targeted at embedded development that focuses on size and speed. It's also FIPS certified which is is important for anyone working with federal agencies.

WolfSSL website: https://www.wolfssl.com/
WolfSSL github: https://github.com/wolfSSL/wolfssl

I have two ideas currently on how dotnet could support WolfSSL:

1. The `System.Security.Cryptography.Native` code relies on OpenSSL, but could be extended to also support WolfSSL. The WolfSSL library provides an OpenSSL compatibility layer which could be used to get a relatively fast, but sub-optimal, implementation into dotnet. I think the [opensslshim.h](https://github.com/dotnet/corefx/blob/master/src/Native/Unix/System.Security.Cryptography.Native/opensslshim.h) and [opensslshim.c](https://github.com/dotnet/corefx/blob/master/src/Native/Unix/System.Security.Cryptography.Native/opensslshim.c) code could be updated to point at the WolfSSL compatibility layer, but I haven't done any testing yet. I'm not positive that all the functions needed in that codebase are currently covered by the WolfSSL compatibility layer, but I am investigating that.
1.  Add support for the WolfSSL API, as opposed to using the OpenSSL compatibility layer, to `System.Security.Cryptography.Native`.

Would either option be something that would be welcomed in a PR?

Am I off-base and chasing the wrong solution for replacing OpenSSL with WolfSSL in dotnet?

Thank you for the time!

**Comment by bartonjs** [comment]
Supporting libraries other than OpenSSL on Linux is not something that we're interested in at this time.

* More options means more ways that "something went wrong" errors confuse people
* More options means that we need to expose those options - how does someone assert they want the WolfSSL binding instead of the OpenSSL binding? Does one fall back to the other?
* Assuming that the WolfSSL OpenSSL bridge APIs are quirk-for-quirk compatible with the OpenSSL APIs in the first place, is there actually a significant performance difference in real-world scenarios when using it? If so, perhaps a better solution is to improve OpenSSL and benefit even more applications.  If not, it's not really worth changing.
* When we finally get to a world where distros start pulling .NET into their default package sets they'll probably build System.Security.Cryptography.Native.OpenSsl.so with direct ("non-portable") linking, so there'd not be a WolfSSL fallback there.
  * If we get a distro that wants their official packages to use WolfSSL instead of OpenSSL then we have a more compelling justification, but it would essentially mean splitting the Linux crypto PALs in half, one for OpenSSL and one for WolfSSL and a compile-time flag picks which option is the only option supported.
    * Our portable .tgz would almost certainly remain with OpenSSL.
