### ISSUE TITLE
Base64.EncodeToUtf8 sometimes returns NeedMoreData when it should return Done

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/corefx#42245]
As @gfoidl reports in https://github.com/dotnet/corefx/issues/42236#issuecomment-548148179:

```c#
using System;
using System.Buffers.Text;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Span<byte> input = stackalloc byte[3] { 0x1, 0x2, 0x3 };
            Span<byte> output = stackalloc byte[4];

            var status = Base64.EncodeToUtf8(input, output, out int read, out int written, isFinalBlock: false);
            Console.WriteLine(status);  // outputs "NeedMoreData"
        }
    }
}
```

This sample outputs `NeedsMoreData` but it should instead output `Done`.

**Comment by gfoidl** [comment]
I'll fix this (in the next couple of days).

**Comment by gfoidl** [comment]
The same applies to `DecodeFromUtf8`.

**Comment by gfoidl** [comment]
The desired behavior of `System.Buffers.Text.Base64` is summarized in the tables below.

@GrabYourPitchforks please have a look, so that I didn't miss a check or that like.
Based on that table the (unit-) tests will be adjusted.

### Encoding

| isFinalBlock | input                                      | output-buffer-length                    |    OperationStatus    | Comment                                 |
|:------------:|--------------------------------------------|-----------------------------------------|:---------------------:|-----------------------------------------|
|    `true`    | 0..MaximumEncodeLength                     | >= GetMaxEncodedToUtf8Length            |         `Done`        | padding added if input-length % 3 != 0  |
|    `true`    | 0..MaximumEncodeLength                     | < (GetMaxEncodedToUtf8Length - padding) | `DestinationTooSmall` | encoded as much as possible             |
|    `true`    | > MaximumEncodeLength                      | any                                     | `DestinationTooSmall` | encoded as much as output-buffer allows |
|              |                                            |                                         |                       |                                         |
|    `false`   | 0..MaximumEncodeLength && length % 3 == 0  | >= GetMaxEncodedToUtf8Length            |         `Done`        |                                         |
|    `false`   | 0..MaximumEncodeLength && length % 3 == 0  | < (GetMaxEncodedToUtf8Length - padding) | `DestinationTooSmall` | encoded as much as possible             |
|    `false`   | 0..MaximumEncodeLength && lenngth % 3 != 0 | >= GetMaxEncodedToUtf8Length            |     `NeedMoreData`    | encoded as much as possible             |
|    `false`   | 0..MaximumEncodeLength && lenngth % 3 != 0 | < (GetMaxEncodedToUtf8Length - padding) | `DestinationTooSmall` | encoded as much as possible             |
|    `false`   | > MaximumEncodeLength                      | any                                     | `DestinationTooSmall` | encoded as much as output-buffer allows |

### Decoding

| isFinalBlock | input                 | output-buffer-length                      |    OperationStatus    | Comment                                 |
|:------------:|-----------------------|-------------------------------------------|:---------------------:|-----------------------------------------|
|    `true`    | length % 4 == 0       | >= GetMaxDecodedFromUtf8Length            |         `Done`        |                                         |
|    `true`    | length % 4 == 0       | < (GetMaxDecodedFromUtf8Length - padding) | `DestinationTooSmall` | decoded as much as possible             |
|    `true`    | length % 4 != 0       | >= GetMaxDecodedFromUtf8Length            |     `InvalidData`     | decoded up to the closest multiple of 4 |
|    `true`    | contains invalid data | any                                       |     `InvalidData`     | decoded up to the point of invalid data |
|              |                       |                                           |                       |                                         |
|    `false`   | length % 4 == 0       | >= GetMaxDecodedFromUtf8Length            |         `Done`        |                                         |
|    `false`   | length % 4 == 0       | < (GetMaxDecodedFromUtf8Length - padding) | `DestinationTooSmall` | decoded as much as possible             |
|    `false`   | length % 4 != 0       | >= GetMaxDecodedFromUtf8Length            |     `NeedMoreData`    | decoded up to the closest multiple of 4 |
|    `false`   | length % 4 != 0       | < (GetMaxDecodedFromUtf8Length - padding) | `DestinationTooSmall` | decoded as much as possible             |
|    `false`   | contains invalid data | any                                       |     `InvalidData`     | decoded up to the point of invalid data |
