### ISSUE TITLE
Questions about the *.Fast.cs files 

### ISSUE THREAD

**Issue by CwjXFH** [dotnet/corefx#42345]
Hi,  
I noticed some .Fast.cs files were removed(or consolidate) from source files in master branch commit 'ba25a05f32b3cd0503b1a306f6e769b427456bd0'.  
Like Span.Fast.cs. Removed Span.Fast.cs file and removed the partial keyword from Span.cs. 

+ Why not code in the same file? 
+ What's the purpose of these *.Fast.cs files?

![removed *.fast.cs files](https://user-images.githubusercontent.com/11468733/68096309-e0dea200-feea-11e9-899c-3444a96afd8b.png)

And, now in the master branch, only one partial defined of `Span<T>` struct, is only one parital defined is necessary?

![parital span](https://user-images.githubusercontent.com/11468733/68096255-91987180-feea-11e9-9df0-4fb6177d563e.png)

Thanks!

**Comment by GrabYourPitchforks** [comment]
Earlier versions of packages like __System.Memory__ were built both for .NET Core and for .NET Full Framework. Depending on which target runtime you were compiling the `Span<T>` type for, you'd bring in both _Span.cs_ and _Span.Fast.cs_ (if you were compiling for .NET Core) or both _Span.cs_ and _Span.Portable.cs_ (if you were compiling for .NET Framework).

Check out the __System.Memory.csproj__ in the release/2.1 branch for an example of this: https://github.com/dotnet/corefx/blob/release/2.1/src/System.Memory/src/System.Memory.csproj. Since that package is cross-compiled for several runtimes, you can see the individual `<ItemGroup>` elements in that file which select the appropriate implementation for the target runtime.
