### ISSUE TITLE
Reasons behind having duplicate type for S.R.CS.Unsafe and Internals.R.CS.Unsafe

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/corefx#42348]
All the members are identical, but it seems weird to have two separate types that have all the same members; is there a reason behind that? It doesn't feel quite right, and would be nice if it could be merged into S.R.CS one.

**Comment by jkotas** [comment]
Internal.S.R.CS.Unsafe has a subset of methods for internal consumption by S.P.CoreLib. It is implement by complex IL patching - since it is not possible to write IL in CoreLib directly.

S.R.CS.Unsafe has all methods, it is implemented directly in IL and it ships as separate NuGet package.

If we merged these two, we would:
- We would need to use the complex IL patching (or some alternative) to implement all methods.
- S.R.CS.Unsafe NuGet package would be dead. Once the type moves from NuGet package to CoreLib, the NuGet package gets frozen and cannot evolve anymore.

**Comment by Gnbrkm41** [comment]
I see. Thanks for the clarification!
