### ISSUE TITLE
about method Write(byte[] buffer, int offset, int count)   the  class of memoryStream 

### ISSUE THREAD

**Issue by changhengyu** [dotnet/corefx#42436]
if ((count <= 8) && (buffer != _buffer))
            {
                int byteCount = count;
                while (--byteCount >= 0)
                {
                    _buffer[_position + byteCount] = buffer[offset + byteCount];
                }
            }
            else
            {
                Buffer.BlockCopy(buffer, offset, _buffer, _position, count);
            }

why does the  count of buffer more than 8 and Less than or equal to 8 use different copy method

**Comment by Gnbrkm41** [comment]
`Buffer.BlockCopy` is implemented with a private method called `Memmove` which either calls a native `memmove` function, probably written in assembly for maximum performance, or for smaller sizes, use tricks like unrolling and moving bytes in blocks to move the data more efficiently. The number 8 there probably is something that was figured out to be faster with a simple loop, because the Memmove method involves a few checks which probably isn't worth it for small data.

**Comment by changhengyu** [comment]
OK ，I see what your mean，thank you
