### ISSUE TITLE
UriTypeConverter inconsistent constructor vs full framework

### ISSUE THREAD

**Issue by iSazonov** [dotnet/corefx#42438]
In .Net Core UriTypeConverter has not explicit constructor. https://source.dot.net/#System.ComponentModel.TypeConverter/System/ComponentModel/UriTypeConverter.cs,17
In the case new instance is created with __UriKind.Absolute__.

In .Net Framework UriTypeConverter has a constructor with __UriKind.RelativeOrAbsolute default__
https://referencesource.microsoft.com/#System/net/System/_UriTypeConverter.cs,30

It is a breaking change. Discovered in PowerShell Core repo where we have to use a workaround for this.

It would be nice to get a fix before 3.1 LTS.

**Comment by ericstj** [comment]
> In the case new instance is created with UriKind.Absolute.

Can you point out where you observe the difference?  It looks to me like this was originally omitted when the source was ported to .NETCore and the port was trying to avoid the local field which was always set to `UriKind.RelativeOrAbsolute`.

Please provide a repro of the scenario where you see it failing or producing different results than desktop?  

Thanks!

**Comment by ericstj** [comment]
Related: https://github.com/dotnet/corefx/pull/39203

**Comment by iSazonov** [comment]
>  the port was trying to avoid the local field which was always set to UriKind.RelativeOrAbsolute.

A problem is just that now default is UriKind.Absolute.

> Please provide a repro of the scenario

Now TypeDescriptor.GetConverter(Uri) returns UriTypeConverter with UriKind.Absolute but we expect UriKind.RelativeOrAbsolute.

**Comment by ericstj** [comment]
The UriTypeConverter doesn't expose UriKind anywhere, it merely had an internal field with this set and that field has been eliminated since it's always expected to be RelativeOrAbsolute.

The default is not Absolute Uri.  If you convert a relative string to Uri it will still work and return a relative Uri.

```C#
using System;
public static class Program
{
    public static void Main()
    {
        var converter = new UriTypeConverter();
        PrintUri((Uri)converter.ConvertFrom("/relative"));
        PrintUri((Uri)converter.ConvertTo(new Uri("/relative", UriKind.Relative), typeof(Uri)));
    }
    static void PrintUri(Uri uri) => Console.WriteLine($"{uri} ({(uri.IsAbsoluteUri ? UriKind.Absolute : UriKind.Relative)})");
}
```

These succeed and return:
```
/relative (Relative)
/relative (Relative)
```

As far as I can tell, the only scenario that throws is the following:
```C#
(Uri)converter.ConvertFrom(new Uri("/relative", UriKind.Relative));
```

Though this seems unlikely that you'd depend on this, since it's not actually converting anything, just cloning a Uri.  For us to consider a fix here we need to see a repro of the specific problem you're hitting, similar to the samples I've provided above.

**Comment by iSazonov** [comment]
@ericstj Thanks for help! I found a root of my issue. PowerShell used Uri constructor (that is  UriKind.Absolute) before UriTypeConverter().

**Comment by ericstj** [comment]
I'm still going to clean up the scenario I pointed out since it was different for core vs desktop and looks unintentional.  If you can point out another difference we can consider it.

Thanks
