### ISSUE TITLE
System.Text.Json fails to deserialize datetime in other than ISO format.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/corefx#42445]
System.Text.Json can deserialize the  following JSON:

```
{
    "companyId":1,
    "companyName":"Wafi Solution",
    "establishmentDate":"2011-12-31T00:00:00Z",
}
```

But cannot deserialize the  following JSON:
```
{
    "companyId":1,
    "companyName":"Wafi Solution",
    "establishmentDate":"31-Dec-2011",
}
```
and throws following exception:'

> "The JSON value could not be converted to System.DateTime. Path: $.establishmentDate | LineNumber: 0 | BytePositionInLine: 79."

**Note: `NewtonsoftJson` can deserilize the above JSON without any issue.**

**Comment by ericstj** [comment]
This is by design.  System.Text.Json by default only supports a strict date-time format.  For more details see https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support.

This section describes the steps you can take to enable more flexible date-time parsing (at the cost of performance):
https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support#custom-support-for--and-

/cc @layomia
