### ISSUE TITLE
Why `System.Runtime.Caching` has dependency to `System.Security.Principal.Windows`?

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/corefx#42592]
I think this 2 are completely different things.
I like to know why and also what happens in other OS, e.g Linux? would you explain.

Thank you

**Comment by vcsjones** [comment]
It's part of the dependency graph.

<pre>
System.Runtime.Caching
↳ System.Configuration.ConfigurationManager
  ↳ System.Security.Permissions
    ↳ System.Security.AccessControl
      ↳ System.Security.Principal.Windows
</pre>

System.Runtime.Caching uses the `ConfigurationManager` to get configuration for the `system.runtime.caching/memoryCache` section.

`ConfigurationManager` has a public API, `GetRestrictedPermissions`, which has a `PermissionSet` as an out parameter, which is in `System.Security.Permissions`.  In .NET Core, this method always gives back an empty permission set. In the .NET Framework, this did a lot of `Evidence` based access.

Since `GetRestrictedPermissions` doesn't really do anything, I don't think the `System.Security.Principal.Windows` package will ever get used by `System.Runtime.Caching`. However because of the API surface, the package ends up as a dependencies a few layers down.

**Comment by StephenBonikowsky** [comment]
@vcsjones Thanks Kevin for providing @dehghani-mehdi the explanation.

@mconnew Can you confirm that there is no functional dependency on `System.Security.Principal.Windows`?

**Comment by danmosemsft** [comment]
@stephentoub this is an example of unfortunate dependency rooting.

**Comment by stephentoub** [comment]
> this is an example of unfortunate dependency rooting.

@danmosemsft, is it?  It's one thing for System.Runtime.Caching.dll to have a dependency on System.Configuration.ConfigurationManager.dll; it's another for that dependency to persist when the linker is applied to a whole app.  Presumably we're not talking about the latter here, and if in the latter case the aforementioned GetRestrictedPermissions method isn't used, I would expect it to get trimmed away, along with anything else it's keeping alive.

**Comment by danmosemsft** [comment]
@stephentoub - of course, you're right.

**Comment by stephentoub** [comment]
@danmosemsft, I just tried.  In a trimmed app that uses System.Runtime.Caching, the GetRestrictedPermissions method in System.Configuration.ConfigurationManager.dll gets linked away, as does its dependency on System.Security.Permissions.  System.Security.Principal.Windows sticks around though, because apparently (for reasons I don't yet understand and will need to look into), System.Net.Sockets has a dependency on WindowsIdentity.

**Comment by StephenBonikowsky** [comment]
I believe the initial question has been answered, do we need to keep this issue open? Is there some other action item that came from this?

**Comment by dehghani-mehdi** [comment]
@StephenBonikowsky  I don't think so

**Comment by stephentoub** [comment]
Closed due to response from OP (that was since deleted) "I don't think so"

**Comment by dehghani-mehdi** [comment]
By that, I meant the question _and the issue_ is not answered _resolved_. sorry I didn't explain well.
