### ISSUE TITLE
WebSocket state set to 'Aborted' when cancelling ReceiveAsync

### ISSUE THREAD

**Issue by SeanSnyders** [dotnet/corefx#42711]
OSX 10.14.6
.Net Core 2.2.102

Using `ClientWebSocket.ReceiveAsync()` with a `CancellationToken` and wanting to cancel my operation of waiting for data / receiving data.
Cancels works fine, but it also seems to set the `WebSocketState` to `Aborted` which is not fine. I still want to use my WebSocket afterwards for sending or whatnot, or even restarting the receiving process. I do not want it to cancel (abort?) the actual websocket connection or put the websocket into a state which it should not be in.

Am I on the wrong track here, or is there an issue here? `Aborted` state also documents as 'reserved for future use'.

This ability to not cancel the `ReceiveAsync()` (effectively I have to call it with a `CancellationToken.None`) means the caller is stuck on the receive and has to process at least some incoming data before control is given back to be able to cancel the operation in the method wrapping the `ReceiveAsync()`.

Would love some feedback on this.

**Comment by MV10** [comment]
That's just how it works. In fact, you can't even cancel the token during the close handshake routine, you have to leave your receiver open so that it doesn't trash the socket while you perform a graceful shutdown. (If you've ever done low-level winsock programming, it all actually makes sense -- unfortunately, last time I checked, the behavior wasn't documented.)

You can send while you're blocking on a receive, you just have to kick off a separate task.

I messed around with some of this for a little hobby project earlier this year, maybe this will be useful to you:

https://github.com/MV10/WebSocketExample

**Comment by tmds** [comment]
At socket level, receives can be cancelled, because you can cancel when you are waiting for some new data to come.
Sends however cannot be cancelled, because they may occur partially, and not waiting to send the remainder breaks the protocol stream.
If you look into the implementation, the Receive method is also performing some sends (ping/pong, close). These sends are also using the CancellationToken. So cancelling those requires aborting the connection.
I think, in theory, it should be possible to do those sends without awaiting them and not passing the CancellationToken. In that case, the receives would be cancellable.

**Comment by SeanSnyders** [comment]
I totally hear the comments on the underlying implementation of websockets. And that is good, but I feel the .Net classes should provide a higher level abstraction for users, especially if one supports `CancellationToken`s with the concept of `async`/`await`.
`ReceiveAsync(cancellationToken)` nowhere indicates that it will abort the socket. As the method reads, it will cancel the receive.

As a user, I want to be able to cancel my send of some data. Then I want to start sending data again.
I also want to cancel receiving of data (i.e. server please stop spamming me) and then potentially later start listening/receiving again. All on the same websocket connection.
I did not cancel my `ConnectAsync(cancellationToken)` call, which I would attribute to the connection 'concept'.
The current behaviour seems at odds with the general concept of `async`/`await` and cancellation of asynchronous methods as the methods are quite tied to global state / the state of the websocket.

Seems like a legit functionality request? Now implementation thereof might be a bit tricky to conform to the websocket standard and the underlying transport stream....

**Comment by scalablecory** [comment]
Cancellation is technically best-effort but in general I want to see it to be observed as quickly as possible. When I/O is involved this usually means aborting the entire connection due to some state that can't feasibly be instantly rolled back (like a send). There are certainly ways to design things to be less abortive, but there might be tradeoffs in happy-path performance.

The API surface of `WebSocket` does have what you need to implement this on top.

**Comment by karelz** [comment]
Triage: Looks like by design -- anything else would be fairly complicated with little benefit.

**Comment by tmds** [comment]
> The API surface of WebSocket does have what you need to implement this on top.

@SeanSnyders this is the way to go. You need to Wrap ReceiveAsync in a way it supports cancellation. When a wrapped ReceiveAsync got cancelled, the next call will use the on-going _inner_ ReceiveAsync.

**Comment by SeanSnyders** [comment]
Thanks for the suggestions. I'll look into this.
For the time being I am circumventing this situation on app logic level, but would like not to.

Might still be worthwhile pondering the suggestion of @tmds and see if those internal protocol management of receiveAsync can be made to not abort the socket.
