### ISSUE TITLE
Simplifying the OrderedEnumerable.TryGetFirst method 

### ISSUE THREAD

**Issue by piotrsz1234** [dotnet/corefx#42719]
I've noticed, that method TryGetFirst in OrderedEnumerable, after finding the matching value, is still searching. I'd like to ask, does it has to be done like this, because some of the cases, or that could be simplifyed to simple search loop.

Sorry for bad English
Regards

**Comment by stephentoub** [comment]
It needs to be this way. The "Ordered" part of the name doesn't mean it's already ordered, but that it represents something that's expected to be. As such, to find the "first" in the resulting sorted set, we need to look at every element. This is actually an optimization: the alternative would be to sort and then get the first, which would be O(n log n) rather than O(n).
