### ISSUE TITLE
Utf8JsonWriter writes invalid JSON

### ISSUE THREAD

**Issue by devhl-labs** [dotnet/corefx#42720]
The below code shows how the serializer is failing for me.  It is giving me invalid JSON.

```
/*
The below code outputs this incorrect json:
{
  "Role": 
  "Role": "admin"
}
*/


public class Test
{
    public Role Role { get; set; }
}


public static async Task Main(string[] args)
{
    JsonSerializerOptions options = new JsonSerializerOptions();

    options.WriteIndented = true;

    options.Converters.Add(new RoleConverter());

    var Test = new Test { Role = devhl.CocApi.Enums.Role.Elder };

    var c = JsonSerializer.Serialize(Test, options);
    //inspect the output and observe improper JSON
}


public class RoleConverter : JsonConverter<Role>
{
    public override Role Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        //return a Role object   
    }

    public override void Write(Utf8JsonWriter writer, Role value, JsonSerializerOptions options)
    {
        string enumMemberAttrValue = value.ToEnumMemberAttrValue();

        writer.WriteString("Role", enumMemberAttrValue);
    }
}

public static class Extensions
{
    public static string ToEnumMemberAttrValue(this Enum @enum)
    {
        var attr = @enum.GetType().GetMember(@enum.ToString()).FirstOrDefault()?.
                GetCustomAttributes(false).OfType<EnumMemberAttribute>().
                FirstOrDefault();

        if (attr == null) return @enum.ToString();

        return attr.Value;
        //returns "admin" 
    }
}

public enum Role : int
{
    [EnumMember(Value = "unknown")]
    Unknown = 0,
    [EnumMember(Value = "member")]
    Member = 10,
    [EnumMember(Value = "admin")]
    Elder = 20,
    [EnumMember(Value = "coLeader")]
    Coleader = 30,
    [EnumMember(Value = "leader")]
    Leader = 40
}
```

**Comment by layomia** [comment]
I was able to repro this: https://dotnetfiddle.net/MSphXW. I think it's a serializer bug - an issue with hooking up to your converter - rather than a writer bug.

**Comment by Backhage** [comment]
I played around with this a bit and were able to simplify the code used for repro quite a lot. It seems that I get invalid JSON as soon as I add a custom JsonConverter that calls writer.WriteString in the overrridden Write-method.

**Comment by nathan-alden-sr** [comment]
I think the mistake here is likely the developer intended `WriteStringValue` and not `WriteString`. I'm working with him offline to verify.

**Comment by pie-flavor** [comment]
@nathan-alden-sr That's definitely the fail, but maybe it's still a bug that this behavior is accepted and an exception isn't thrown?

**Comment by nathan-alden-sr** [comment]
Yeah, the bigger question is whether `Utf8JsonWriter` should be smart enough to not allow certain serializations in certain writer states. I'm surprised this went through, but I can see how maybe `System.Text.Json` is "low-level" enough to require developers to be careful of pointy edges.

**Comment by devhl-labs** [comment]
Changing to WriteStringValue resolved the issue.  Thanks.

**Comment by layomia** [comment]
> Yeah, the bigger question is whether `Utf8JsonWriter` should be smart enough to not allow certain serializations in certain writer states. I'm surprised this went through, but I can see how maybe `System.Text.Json` is "low-level" enough to require developers to be careful of pointy edges.

cc @ahsonkhan

**Comment by ahsonkhan** [comment]
The `Utf8JsonWriter` does its own validation of state (when using the writer on its own).

So, the following will throw as expected, since you are trying to produce invalid JSON:
```C#
using (var writer = new Utf8JsonWriter(new ArrayBufferWriter<byte>()))
{
    writer.WriteStartObject();
    writer.WritePropertyName("Role");
    writer.WriteString("Role", "admin");
    writer.WriteEndObject();
}
// Unhandled exception. System.InvalidOperationException: Cannot write a JSON property name following another property name. A JSON value is missing.
//    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource, Int32 currentDepth, Byte token, JsonTokenType tokenType)
//    at System.Text.Json.Utf8JsonWriter.WriteStringEscape(ReadOnlySpan`1 propertyName, ReadOnlySpan`1 value)
//    at System.Text.Json.Utf8JsonWriter.WriteString(ReadOnlySpan`1 propertyName, ReadOnlySpan`1 value)
//    at System.Text.Json.Utf8JsonWriter.WriteString(String propertyName, String value)
```

We had discussed whether we should keep validation on during serialization (but we couldn't guarantee 100% correctness to justify the performance hit). We enable "validation" in debug (to validate that the serializer implementation itself is using the `Utf8JsonWriter` correctly), but turn validation **off** for the release build due to performance. This means that the converter implementation could corrupt the state of the `Utf8JsonWriter` if written incorrectly and it's the implementors responsibility to do the right thing.

https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs#L340-L350

Validating the entire state of the writer when used within the serializer **and** custom converter isn't always feasible (and certainly costly). That's why we generally only validate that the depth hasn't been changed after returning from a custom-defined converter (i.e. either a complete new object was written, or a correctly formatted key:value pair was). We could consider adding some more validation (at the cost of some perf) but given we are handing control over user-code, we can't guarantee that the output JSON will be valid anyway when the custom converter contains incorrect or buggy, so the question is whether it's worth it.

https://github.com/dotnet/corefx/blob/a528006b4536e5b73227285b57d2a56116532506/src/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfo.cs#L592-L598

Depending on your use case and context, you could solve this problem by passing in your own `Utf8JsonWriter` to the `JsonSerializer` API that has `SkipValidation` set to false (i.e. it will validate and throw, which is the default). **At least for your use case, this could be a viable workaround to guard against invalid implementations:**

This validates and throws, as you would expect:
```C#
var output = new ArrayBufferWriter<byte>();
using (var writer = new Utf8JsonWriter(output))
{
    JsonSerializer.Serialize(writer, Test, options);
}

string json = Encoding.UTF8.GetString(output.WrittenMemory.Span);
Console.WriteLine(json);

// Unhandled exception. System.Text.Json.JsonException: The object or value could not be serialized. Path: $.Role.
//  ---> System.InvalidOperationException: Cannot write a JSON property name following another property name. A JSON value is missing.
//    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource, Int32 currentDepth, Byte token, JsonTokenType tokenType)
//    at System.Text.Json.Utf8JsonWriter.WriteStringEscape(ReadOnlySpan`1 propertyName, ReadOnlySpan`1 value)
//    at System.Text.Json.Utf8JsonWriter.WriteString(ReadOnlySpan`1 propertyName, ReadOnlySpan`1 value)
//    at System.Text.Json.Utf8JsonWriter.WriteString(String propertyName, String value)
//    at Program.RoleConverter.Write(Utf8JsonWriter writer, Role value, JsonSerializerOptions options)
//    at System.Text.Json.JsonPropertyInfoNotNullable`4.OnWrite(WriteStackFrame& current, Utf8JsonWriter writer)
//    at System.Text.Json.JsonPropertyInfo.Write(WriteStack& state, Utf8JsonWriter writer)
//    at System.Text.Json.JsonSerializer.HandleObject(JsonPropertyInfo jsonPropertyInfo, JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
//    at System.Text.Json.JsonSerializer.WriteObject(JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
//    at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
//    --- End of inner exception stack trace ---
//    at System.Text.Json.ThrowHelper.ReThrowWithPath(WriteStack& writeStack, Exception ex)
//    at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
//    at System.Text.Json.JsonSerializer.WriteCore(Utf8JsonWriter writer, PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
//    at System.Text.Json.JsonSerializer.WriteValueCore(Utf8JsonWriter writer, Object value, Type type, JsonSerializerOptions options)
//    at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue value, JsonSerializerOptions options)
```

I hope that context and the workarounds help.

**Folks on this thread,** would you prefer if the `SkipValidation` option was available to you via the `JsonSerializerOptions` (just like how it is available on `JsonWriterOptions`) to customize and turn validation back on? If so, would you ever turn on validation or leave it off regardless (or maybe do what we do and turn it on in DEBUG but leave it off for RELEASE)? That said, I would expect bugs like these in the calling code to be caught by unit tests anyway.
