### ISSUE TITLE
InvariantCulture string comparison is inconsistent between Windows and macOS

### ISSUE THREAD

**Issue by DaRosenberg** [dotnet/corefx#42746]
Verified in .NET Core 3.0 on Windows 10 1909 and macOS 10.15.1.

This expression:

```cs
System.StringComparer.InvariantCulture.Compare(".", "_")
```

Returns `-1` on Windows, but `1` on macOS.

Since the invariant culture is being used, expected result is for string comparison to behave the same.

This is a blocking issue for us, because we are building a cross-platform tool whose output goes into shared data storage, and contains sorted strings. Currently, Windows users and Mac users overwrite each others' data with changes in sorting.

**Comment by DaRosenberg** [comment]
I should also mention: we think using `StringComparer.Ordinal` is not a viable workaround because, while consistent across platforms, it produces sorting that users find unintuitive.

**Comment by scalablecory** [comment]
@tarekgh

**Comment by Gnbrkm41** [comment]
IIRC, any other comparison than Ordinal/OrdinalIgnoreCase calls into the OS for comparing strings, which Windows uses NLS (National Language Support) and macOS / Linux uses ICU (International Components for Unicode). There are some subtle differences when it comes to sorting behaviour between those two, and this seems to be one of them.

There are plans to make .NET use ICU (https://github.com/dotnet/corefx/issues/41663), which I guess would help because that will make the order consistent across OS.

**Comment by danmosemsft** [comment]
I believe @Gnbrkm41 is correct. @tarekgh can you suggest a way to achieve their scenario?

**Comment by Gnbrkm41** [comment]
A few solutions I can think of:
* When storing the data on the storage, sort the strings using `StringComparer.Ordinal` then re-sort the string with `InvariantCulture` or `CurrentCulture` on the client side after retrieval (because if user intuitiveness matters, this should be better)
* Let the server/storage do the sorting for you and re-sort after retrieving on the client side
* Get one of the many [ICU wrapper libraries from NuGet](https://www.nuget.org/packages?q=ICU) (or write your own) and use that to sort on the client side
  * conditional compiling (`#if WINDOWS`) or runtime check ([`RuntimeInformation.IsOSPlatform`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.isosplatform?view=netframework-4.8))
* Or wait until .NET that uses ICU ships 😛

**Comment by DaRosenberg** [comment]
@Gnbrkm41 Those are some really helpful suggestions, thank you!

The server/storage is Git in this case, so not much sorting to be done there... :)

I think maybe using an ICU wrapper for now would be the most feasible solution, and dropping that once .NET uses ICU internally on all platforms. We will investigate that option further.

**Comment by Gnbrkm41** [comment]
(Also just a note, new issues should be opened in [dotnet/runtime](https://github.com/dotnet/runtime) repo; it's a new repo where the source code of both the libraries and the runtime lives in)
