### ISSUE TITLE
Add Environment.MachineName to dnxcore50

### ISSUE THREAD

**Issue by spboyer** [dotnet/corefx#4306]
Need `Environment.MachineName`, `Environment.OSVersion` etc available in dnxcore50

**Comment by joshfree** [comment]
@Priya91 PTAL.

@spboyer have you looked at https://github.com/dotnet/corefx/issues/4137?

**Comment by spboyer** [comment]
@joshfree thanks,  looks like a partial solution. I see that devs are going to want log all info from the host machine, ew should have symmetry in core for the Env values.

**Comment by Priya91** [comment]
@spboyer ```Environment.OSVersion``` will not be added to .NET Core, since we don't have OS apis that can provide this exact info. This API has predominantly returned false values on Windows, and the current win32 apis are more [query based](https://msdn.microsoft.com/en-us/library/windows/desktop/dn424972(v=vs.85).aspx). On Unix platforms, we don't have a definitive way to get distro name and version, but just the kernel version, which is not as useful. Can you elaborate the scenario you need this for? If it's for debug purposes, then you can use ```RuntimeInformation.GetOSDebugName()```, which will be added soon.

Regarding exposing ```Environment.MachineName```, i think it can be exposed in ```System.Runtime.Extensions``` but will require a bump to its version, while adding it to ```RuntimeInformation``` will make this API available on all platforms. 

@weshaggard @KrzysztofCwalina How do you decide when it's best to bump the ```System.Runtime.Extensions``` contract or add a new API elsewhere, since versioning seems to be causing duplicating APIs in different namespaces and how do we decide which is a better approach.

**Comment by spboyer** [comment]
@Priya91 this information is more for logging when crashes, errors etc are happening. Sending this info to Splunk or other log catchers. Not just debug info.

**Comment by Priya91** [comment]
In that case using ```RuntimeInformation.OSDescription``` should suit your scenarios.

**Comment by Priya91** [comment]
please see issue #4741 for tracking progress on ```Environment.OSVersion```.

**Comment by davidfowl** [comment]
@Priya91 Not sure OSDescription is equivalent or `Environment.MachineName`. What's the reasoning behind not implementing this?

/cc @stephentoub

**Comment by Priya91** [comment]
@davidfowl  OSDescription is not a replacement for ```Environment.MachineName```, that's why i have kept this issue open, and redirected the other part of the issue on OSVersion to the thread opened by @stephentoub

**Comment by stephentoub** [comment]
Just to chime in, I agree MachineName should be added back (and UserName).  Doing so should be trivial.

**Comment by NickCraver** [comment]
This is a blocker on several diagnostic and logging based packages here, +1 for bringing it back.

**Comment by terrajobst** [comment]
@Priya91 I assume we can meaningfully implement this API across all platforms? In that case I don't see any issue with exposing `MachineName` on `Environment`.

@weshaggard @KrzysztofCwalina @stephentoub, thoughts?

**Comment by KrzysztofCwalina** [comment]
I have no problem with MachineName.

**Comment by stephentoub** [comment]
We should definitely add it back.

**Comment by Priya91** [comment]
On unix systems, uname -n gives the FQDN, this can be implemented to return a meaningful value on all platforms.

**Comment by joshfree** [comment]
I'm glad we're going to be able to get this into RC2 :+1:

**Comment by Priya91** [comment]
The MachineName is already implemented in coreclr pal for Unix as well using gethostname. So just exposing this in contract should be enough.

**Comment by stephentoub** [comment]
> So just exposing this in contract should be enough.

What about .NET Native?

**Comment by Priya91** [comment]
.NET Native will be using the windows implementation in mscorlib. Am i missing something?

**Comment by Priya91** [comment]
On further digging, I'll have to add MachineName implementation in corert for .NET Native, but that shouldn't block this from getting done for rc2. If the corert change doesn't go through before rc2, this can be conditionally excluded for .NET Native.

**Comment by jkotas** [comment]
Why is not `Dns.GetHostName()` sufficient equivalent of Environment.MachineName? It is the same name for typical configuration.

I do not think we should add Environment.MachineName to .NET Core because of it is mostly redundant with `Dns.GetHostName()` and it is pretty bad for layering - it makes System.Runtime.Extensions dependent on networking stack.

**Comment by NickCraver** [comment]
@jkotas These are not equivalent even today. For example, the casing differs. A move there would very subtly break many applications. For example on a VM right here:

`System.Net.Dns.GetHostName()`: `Craver-WinBook8`
`Environment.MachineName`: `CRAVER-WINBOOK8`

I can think of several instances where this matters off the top my my head, including settings that specify machine name and maybe never needed a casing-insensitive check before. On a server OS it typically will match, but locally not - this differing across configs makes the break of such a subtle change much more severe, since it's one of those problems that may be impossible to replicate locally.

For additional reasoning: we have other code that checks a string against redis with mutex locks - if that's not changed to be case-insensitive (in both directions), we'll have competing processes doing the same work creating all kinds of mess to clean up...a mess we've specifically prevented. I' argue that's not a change most developers would be cognisant of when moving to CoreCLR.

**Comment by mgravell** [comment]
The kind MS folks who helped me with SE.Redis went the  `Environment.GetEnvironmentVariable("COMPUTERNAME")` route when porting to dnx, but: that is pretty damned ugly, and relies on a magic string that there is no really good reason should exist on other platforms. The `MahineName` is much missed.

**Comment by jkotas** [comment]
`Environment.MachineName` is [documented](https://msdn.microsoft.com/en-us/library/system.environment.machinename(v=vs.110).aspx) to return NetBIOS name. NetBIOS is old Windows-centric concept. I do not think that there is exact equivalent of `Environment.MachineName` on baseline Unix. It is only available if you install Samba.

@NickCraver  How would you propose `Environment.MachineName` to be implemented on non-Windows platforms, so that it captures the difference between dns host name and NetBIOS name that matters to you?

**Comment by NickCraver** [comment]
On non-windows systems, I'd expect an un-modified `hostname` (equivalent to `uname -n`). I can't think of a case where this would break expectations. Since it's a totally new addition to those platforms, there are no existing lists of machines or such you'd expect to keep working either. IMO, the case should be maintained exactly as `hostname` returns, because it can have meaning and does make a difference in some (rather nasty) edge cases.

**Comment by jkotas** [comment]
sounds good - thank you for the feedback

**Comment by mgravell** [comment]
"Since it's a totally new addition to those platforms, there are no
existing lists of machines or such you'd expect to keep working either."

Cough *mono* cough. It would be worth checking what mono returns on those
same non-windows systems.

**Comment by NickCraver** [comment]
Well that's just...a very valid point. It's indeed  [using `uname`](https://github.com/mono/mono/blob/b7a308f660de8174b64697a422abfc7315d07b8c/mcs/class/Mono.Posix/Mono.Unix/UnixEnvironment.cs#L49), so this should maintain current Mono behavior.

**Comment by khellang** [comment]
> It would be worth checking what mono returns on those same non-windows systems.

Looks like Mono just returns [`GetEnvironmentVariable("HOSTNAME")`](https://github.com/mono/mono/blob/b7a308f660de8174b64697a422abfc7315d07b8c/mcs/class/corlib/Linux/Linux.cs#L218)...

There's also the Mono.Posix `UnixEnvironment` that [uses `uname`](https://github.com/mono/mono/blob/b7a308f660de8174b64697a422abfc7315d07b8c/mcs/class/Mono.Posix/Mono.Unix/UnixEnvironment.cs#L49).

**Comment by akoeplinger** [comment]
@khellang that looks like a left-over from very long ago (I'll see if we can purge it).

If you look into [Environment.cs#L193](https://github.com/mono/mono/blob/61c070c63fe56830beca907cb59bc3743156510f/mcs/class/corlib/System/Environment.cs#L193) you see that MachineName is an internall call into the runtime which ends up in [icall.c#L5817](https://github.com/mono/mono/blob/042146997ec71b6a5776525ee3ac232156082128/mono/metadata/icall.c#L5817) and calling `gethostname()` there.

**Comment by terrajobst** [comment]
We try to avoid having libraries having to call the runtime because the interfaces is fairly brittle and in practice that code would have to live in `mscorlib` (or the runtime specific equivalent).

I think @jkotas argument is valid from a layering standpoint. I don't think we want an API that ties the library (or the runtime for that matter) to the networking stack. If we could provide the API returning an environment variable (even if OS specific) would probably be OK, though.

**Comment by NickCraver** [comment]
@terrajobst using the environmental variable approach (on Windows) is unsafe here, since it may have changed since installation and can be altered by any number of players. It's set the same as NETBIOS when installing, but anything can change it later, so it can't be trusted. 

I'm not sure if your argument of touching the runtime applies to \*nix operating systems, but if so: I'm 100% confident the hostname/uname functions there aren't going anywhere. That would be an unimaginable breaking change. On those systems, I simply don't agree with the brittle argument. If the blocker is the runtime distinction, I'd argue this *should* be in the runtime; it's very basic level information: "where am I?" that varies across environments. The same would be true of OS versions (which I'd also like to see returned for *other* monitoring projects we're doing).

**Comment by terrajobst** [comment]
> I'm 100% confident the hostname/uname functions there aren't going anywhere. 

Fair enough. FWIW, I think we concluded the same on the other thread [here](https://github.com/dotnet/corefx/pull/5428#issuecomment-173070899).

**Comment by Priya91** [comment]
Added.
