### ISSUE TITLE
ECDsaOpenSsl tests failing on CentOS

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4337]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_centos71_debug_tst/133/consoleFull
```
      Interop+Crypto+OpenSslCryptographicException : error:100AE081:elliptic curve routines:EC_GROUP_new_by_curve_name:unknown group
19:01:48       Stack Trace:
19:01:48             at System.Security.Cryptography.ECDsaOpenSsl.GenerateKey()
19:01:48             at System.Lazy`1.CreateValue()
19:01:48             at System.Lazy`1.LazyInitValue()
19:01:48             at System.Security.Cryptography.ECDsaOpenSsl.SignHash(Byte[] hash)
19:01:48             at System.Security.Cryptography.ECDsa.SignData(Byte[] data, Int32 offset, Int32 count, HashAlgorithmName hashAlgorithm)
19:01:48             at System.Security.Cryptography.EcDsaOpenSsl.Tests.EcDsaOpenSslTests.Exercise(ECDsaOpenSsl e)
19:01:48             at System.Security.Cryptography.EcDsaOpenSsl.Tests.EcDsaOpenSslTests.KeySizeProp()
19:01:48    System.Security.Cryptography.EcDsaOpenSsl.Tests.EcDsaOpenSslTests.Ctor224 [FAIL]
19:01:48 
      Interop+Crypto+OpenSslCryptographicException : error:100AE081:elliptic curve routines:EC_GROUP_new_by_curve_name:unknown group
19:01:48       Stack Trace:
19:01:48             at System.Security.Cryptography.ECDsaOpenSsl.GenerateKey()
19:01:48             at System.Lazy`1.CreateValue()
19:01:48             at System.Lazy`1.LazyInitValue()
19:01:48             at System.Security.Cryptography.ECDsaOpenSsl.SignHash(Byte[] hash)
19:01:48             at System.Security.Cryptography.ECDsa.SignData(Byte[] data, Int32 offset, Int32 count, HashAlgorithmName hashAlgorithm)
19:01:48             at System.Security.Cryptography.EcDsaOpenSsl.Tests.EcDsaOpenSslTests.Exercise(ECDsaOpenSsl e)
19:01:48             at System.Security.Cryptography.EcDsaOpenSsl.Tests.EcDsaOpenSslTests.Ctor224()
```
Looks like this particular algorithm isn't available in the OpenSSL installed on the CentOS image.  Can we install one that has them?

cc: @bartonjs, @mmitche, @ellismg

**Comment by ellismg** [comment]
> Looks like this particular algorithm isn't available in the OpenSSL installed on the CentOS image. Can we install one that has them?

It looks like the newest version in CentOS is:

`openssl.x86_64                                               1:1.0.1e-42.el7.9`

I worry a bit about us installing third party packages which are not provided by the default package manager.  I don't think this matches the regular customer scenario.  One assumes you'll want to use the packages that are provided by the distro so when there are security or reliability issues, you can get newer versions via the normal methods.  Thoughts?

**Comment by stephentoub** [comment]
> I worry a bit about us installing third party packages which are not provided by the default package manager. I don't think this matches the regular customer scenario.

Understood.  In this case, the product code is wrapping/exposing an algorithm that just doesn't exist in the underlying implementation, so the exception is expected, but since the test was written on a Linux that had the algorithm, the test was written to expect non-exceptional results.

As such, we either need to update the OpenSSL being used to have the algorithm, or we need to update the test to somehow check whether the algorithm is available and then either expect success or exception based on that.  I'm fine with the latter if that's the preferred route.

**Comment by bartonjs** [comment]
It looks like RedHat is doing one-off decisions about what parts of ECC to allow.  In particular they seem to have left secp224r1 disabled.

Hmm.

**Comment by bartonjs** [comment]
By default, OpenSSL supports a lot of named curves (https://github.com/openssl/openssl/blob/984d6c6052169bcae8010de33f7796e455536d61/crypto/ec/ec_curve.c#L2822-L3024).  If I understand the CentOS SRC-RPM correctly, for CentOS they've reduced the curves list down to:

* SEC/NIST P-256
* SEC/NIST P-384
* SEC/NIST P-521

There are a couple of options:
* Remove SEC/NIST P-224 entirely (it's also not valid on Windows 7, 8, or 8.1 (or 10 because we haven't done the work for it)).
* Change our supported curves structure to do probing on each of the curve IDs, CentOS will not report 224 as valid, get an invalid key size exception when trying to build one.
* If EcKeyCreateByCurveName fails, throw PlatformNotSupportedException instead of CryptographicException
* Leave it the way it is
* Try loading that curve type with explicit curve parameters if EcKeyCreateByCurveName fails (or other form of support fails).  Unless CentOS has also removed support for explicit curves.

The problem with "remove secp224r1" as a strategy is the questions'll just come up again when we try to expand to support arbitrary curves, the brainpool curve suite, and other "out of the shallow end of the pool" features.

/me ponders.

**Comment by bartonjs** [comment]
Okay, I looked into this a bit more.  Making the curve work via explicit parameters seems completely doable for key creation, but it won't help when being presented as a named curve in a certificate.

We're eventually going to want to be able to create keys by OID, since there's more than one 256-bit curve.  That's going to make the notion of "supported key sizes" a bit complicated.

I think that leaves me for 1.0-rtm thinking:
* Remove secp224r1 support entirely (leaves all of our initial OSes with the same supported curves)
* Probe the known curves and remove the 224 entry if it's not found

I think I prefer the latter... it leaves us in a state of "anticipating mismatch", and leaves it as something externally detectable (by probing the KeySizes).

**Comment by joshfree** [comment]
@AtsushiKan can you investigate the probe option above please?

**Comment by bartonjs** [comment]
@AtsushiKan https://github.com/bartonjs/corefx/commit/d8610a175f4d730b9fffbeaa8d75edf795bbd2cd and https://github.com/bartonjs/corefx/commit/bdd984cd0c6531ab3a6be1b1f7c8a4006cddbc5c may help.  There's a lot of bad scaffolding in the managed code; but it does have an example of calling into the list curves API.

Those commits were from me playing around with the "what if we just do it for them" plan, which I ultimately decided was a failure.

**Comment by AtsushiKan** [comment]
Fixed by adding probing mechanism.
