### ISSUE TITLE
Perf_Process.Kill test failed in CI on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4397]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/6046/console
```
System.InvalidOperationException : Cannot process request because the process (10824) has exited.
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Windows.cs(810,0): at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Windows.cs(839,0): at System.Diagnostics.Process.GetProcessHandle(Int32 access)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Windows.cs(71,0): at System.Diagnostics.Process.Kill()
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Diagnostics.Process\tests\Performance\Perf.Process.cs(30,0): at System.Diagnostics.Tests.Perf_Process.Kill()
```

**Comment by ianhays** [comment]
It looks like the issue here is that I'm calling the ```CreateProcessInfinite``` helper function to create processes that I can kill. Despite its name, however, ```CreateProcessInfinite``` does <i>not</i> wait indefinitely. It only waits for 100000 ms i.e. 100 s. 

In a multi-threaded scenario like for the unit tests, this isn't adequate. I'll add a helper that while(true) loops around a sleep and use that instead. That should solve the issue. When the ProcessTestBase class gets disposed it kills all still-running processes that it created, so it shouldn't be a problem to loop without end.
