### ISSUE TITLE
Performance testing

### ISSUE THREAD

**Issue by Maxwe11** [dotnet/corefx#4410]
I'm trying to write own performance test but get the following error.
`msbuild /t:RebuildAndTest /p:Performance=true /p:Configuration=Release`

			System.IO.FileLoadException : Could not load file or assembly 'xunit.pe
	  rformance.core, Version=1.0.0.26, Culture=neutral, PublicKeyToken=67066efe964
	  d3b03' or one of its dependencies. The located assembly's manifest definition
	   does not match the assembly reference. (Exception from HRESULT: 0x80131040)
			Stack Trace:
				  at Microsoft.Xunit.Performance.BenchmarkTestInvoker.CallTestMetho
	  d(Object testClassInstance)
			   --- End of stack trace from previous location where exception was th
	  rown ---
				  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
	  (Task task)
				  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAn
	  dDebuggerNotification(Task task)
			   --- End of stack trace from previous location where exception was th
	  rown ---
				  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
	  (Task task)
				  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAn
	  dDebuggerNotification(Task task)

@ianhays

**Comment by ianhays** [comment]
This is a versioning issue that the perf msbuild targets aren't strong enough to protect against.

An average perf test project specifies the inclusion of "Microsoft.DotNet.Xunit.Performance" with a wildcard inclusion in its project.json. This project contains the xunit extensions required to mark a test as "Benchmark".

To actually run the perf tests as perf tests, we need the Xunit.Performance.Runner.Windows package which contains our runner exe. This package contains the xunit.performance.core that we need. When we restore the dnxcore50 folder, we copy these binaries from the package into the folder in an msbuild target "CopyXunitExecutionDesktop". This msbuild target is essentially hard coded with the current version (now 1.0.0-alpha-build0025), but it can be overridden. 

What I think happened here is that your tests project.lock.json file was restored to reference Microsoft.DotNet.Xunit.Performance version 1.0.0-alpha-build0026 which also brought in xunit.performance.core.dll of the same version. However, when we later copy the runner (and its accompanying core.dll) we overwrite the newer version with the older version 1.0.0-alpha-build0025. 

Short-term solution: Instead of referencing the wildcard Microsoft.DotNet.Xunit.Performance in your project.json, explicitly specify version 1.0.0-alpha-build0025 i.e.
```
  "dependencies": {
    "Microsoft.DotNet.xunit.performance": "1.0.0-alpha-build0025",
```

Long-term solution: I need to fix the msbuild targets to protect against this issue but I haven't thought of a good solution yet. The core.dll version is specified/used in the buildtools test-runtime project.json, the CoreFX common test-runtime project.json, the CoreFX test project's project.json, and also the buildtools PerfTargets.Targets. These are four locations with potentially differing package version numbers that need to be consolidated to avoid issues like this in the future.

**Comment by Maxwe11** [comment]
Thanks for extended reply, works for me now.
