### ISSUE TITLE
Ensure minimum GUID entropy on all platforms.

### ISSUE THREAD

**Issue by blowdart** [dotnet/corefx#4458]
GUIDs on Windows have, for years, provided 122 bits of entropy. 

This behavior needs to be enshrined and guaranteed on all platforms as people have taken dependencies upon it.

**Comment by stephentoub** [comment]
@blowdart, we're using uuid_generate / uuid_create, which represent the standard and accepted mechanism for guid/uuid generation on Unix.  Why do we believe these are insufficient, and what is it that you recommend instead?

**Comment by blowdart** [comment]
I honestly have no idea if they're sufficient or not, documented reassurance that they meet the same minimum entropy as Windows would be fine. This only came up because we're using them to seed TOTP generation and we frankly have no idea if that's safe on Linux or not.

**Comment by stephentoub** [comment]
Well, Guid.NewGuid() is implemented via uuid_generate / uuid_create:
https://github.com/dotnet/coreclr/blob/3ddea17fc4e5b0c9ff2cb0651be82594a0eddffb/src/pal/src/misc/miscpalapi.cpp#L355-L378

The man page for uuid_generate is here for Linux:
http://linux.die.net/man/3/uuid_generate
and here for OS X:
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/uuid_generate.3.html

We have no plans to provide a custom implementation, and no source of entropy that's better than the one being used.

**Comment by stephentoub** [comment]
@blowdart, it's not clear there's actually a problem here.  If you discover there is one and you have a recommendation for addressing it, please reopen this and we can look to address it.  In the meantime, I'm going to close it.  Thanks.

**Comment by GrabYourPitchforks** [comment]
@blowdart's point here is that `Guid.NewGuid()` on Windows **guarantees** a minimum of 122 bits of entropy ([see MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ms688568(v=vs.85).aspx)). For better or worse, developers have taken a dependency on this API to be a cheap, easy way to generate values with high entropy.

To provide cross-platform compatibility for this use case, you need to make sure that GUIDs when generated on non-Windows platforms also use high entropy during their generation. On Mac and Linux you can use `uuid_generate_random` rather than `uuid_generate` to pull this off. (A pRNG is better than the local time and MAC address for this use case.)

**Comment by stephentoub** [comment]
> Windows guarantees a minimum of 122 bits of entropy (see MSDN)

Where is that stated?  I'm not contending its truthfulness, but I'm not seeing it on the linked page.

**Comment by stephentoub** [comment]
In any event, if that's the desired solution, please go ahead and submit a PR to coreclr to address it.  The code that would need to be changed (what Guid.NewGuid() calls to) is at
https://github.com/dotnet/coreclr/blob/3ddea17fc4e5b0c9ff2cb0651be82594a0eddffb/src/pal/src/misc/miscpalapi.cpp#L355-L378

Thanks.

cc: @morganbr

**Comment by GrabYourPitchforks** [comment]
> Where is that stated? I'm not contending its truthfulness, but I'm not seeing it on the linked page.

`CoCreateGuid` calls `UuidCreate`, [which says](https://msdn.microsoft.com/en-us/library/windows/desktop/aa379205(v=vs.85).aspx):

> For security reasons, it is often desirable to keep ethernet addresses on networks from becoming available outside a company or organization. The UuidCreate function generates a UUID that cannot be traced to the ethernet address of the computer on which it was generated. It also cannot be associated with other UUIDs created on the same computer.

Of all the [UUID generation schemes](https://en.wikipedia.org/wiki/Universally_unique_identifier#Variants_and_versions), only version 4 has the properties described above. Indeed this is what Windows uses under the covers, and it's what developers have taken a dependency on.

**Comment by GrabYourPitchforks** [comment]
Furthermore, you probably don't want somebody like @blowdart or me submitting a PR for this. Neither of us has the skills necessary to correctly code and test this on non-Windows platforms. We're simply providing security assurance review and bringing this to your attention so that a developer knowledgeable in this area can address it before RTM before customers run into it.

**Comment by stephentoub** [comment]
> it's what developers have taken a dependency on

This thread has been windy with regards to what the core concern is.  So the concern isn't with the source of entropy currently being used, nor with guarantees made about how much entropy is available, but rather that data about ethernet addresses isn't exposed.

> you probably don't want somebody like @blowdart or me submitting a PR for this

Sure we do.  It doesn't take much, especially when the core of what's being done is changing a call from uuid_generate to instead be uuid_generate_random, when CI systems are there to do validation as part of PRs, when others who are knowledgable in the area are doing code reviews, etc.  I can take care of this one, but I really do want folks to feel empowered to not only highlight issues but also fix them, especially when they're the ones proposing the solution.
