### ISSUE TITLE
Question: What TFM should I use when building a class library?

### ISSUE THREAD

**Issue by Tasteful** [dotnet/corefx#4529]
@Eilon @davidfowl 
Regarding https://github.com/aspnet/Announcements/issues/98 we have new TFM to use, example ```net45X``` instead of ```dnx45X```. 

The link in announcement is pointing to https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md on that page no information about the new TFM.

I'm building an class library and what I understand I should use the ```netXXX``` TFM but when try to use xunit with them the library the xunit-dnx-runner only supporting ```dnxXXX``` TFM. What TFM should I use?

**Comment by Tasteful** [comment]
https://github.com/xunit/xunit/issues/683

**Comment by ericstj** [comment]
In this case XUnit is using the `dnxxxx` TFM to indicate app model.  Unit test runners have special parity to the specific app model they target since they want to mimic the application environment of that app model.  Most class libraries should choose the least limiting TFM where all their dependencies are satisfied.  For instance if all you depend on is framework APIs then choosing a portable profile with those framework APIs is the least limiting.  If you depend on some API that is only available in a specific framework (eg: the old System.Web APIs in .NET desktop) then choose `netxxx`.  If you also depend on some service provided by DNX (eg: native runtime composition) then use `dnxxxx`.  This isn't the complete decision tree but it should give you an idea about how you should think about this.

**Comment by davidfowl** [comment]
For the most part you class libraries should no longer depend on `dnxxx` the only thing left is applications or unit tests.

**Comment by jasonwilliams200OK** [comment]
@davidfowl, @ericstj, would the `dotnet apiport` project: https://github.com/Microsoft/dotnet-apiport/ guide the library devs in making decision what to depend on and foreseeing the impact that what targets will be [un]supported? If not, does APIPort project (aka `making life easier` &trade;) somehow assist in making such decisions?

**Comment by ericstj** [comment]
@jasonwilliams200OK ApiPort does not yet, but it seems like a reasonable feature request to open in the API port project.  /cc @terrajobst who is working on a representation of the packages in the backing API catalog that API port uses.

@Tasteful for a unit test runner xunit should be using dnxxxx, for xunit surface area that is consumed by tests (eg Assert library) xunit should use netstandard.  Let us know if you have any more questions, otherwise we'll close this issue out.
