### ISSUE TITLE
A bunch of tests recently started failing on OS X

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4605]
These have been consistently failing for the last few days:
```
System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateFromFile.ReadOnlyFile(access: CopyOnWrite)
System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateFromFile.ReadOnlyFile(access: ReadWrite)
System.IO.Tests.FileInfo_AppendText.WriteToReadOnlyFile_UnauthException
System.IO.Tests.File_ReadWriteAllLines_Encoded.WriteToReadOnlyFile_UnauthException
System.IO.Tests.File_AppendAllLines.WriteToReadOnlyFile_UnauthException
System.IO.Tests.File_OpenText.WriteToReadOnlyFile_UnauthException
System.IO.Tests.File_ReadWriteAllLines.WriteToReadOnlyFile_UnauthException
System.IO.Tests.FileInfo_CreateText.WriteToReadOnlyFile_UnauthException
System.IO.Tests.FileInfo_OpenText.WriteToReadOnlyFile_UnauthException
System.IO.Tests.File_ReadLines_Encoded.WriteToReadOnlyFile_UnauthException
System.IO.Tests.File_ReadWriteAllText_Encoded.WriteToReadOnlyFile_UnauthException
System.IO.Tests.File_ReadWriteAllText.WriteToReadOnlyFile_UnauthException
System.IO.Tests.File_ReadLines.WriteToReadOnlyFile_UnauthException
System.IO.Tests.File_CreateText.WriteToReadOnlyFile_UnauthException
System.IO.Tests.File_AppendAllText_Encoded.WriteToReadOnlyFile_UnauthException
System.IO.Tests.File_AppendAllText.WriteToReadOnlyFile_UnauthException
System.IO.Tests.File_AppendText.WriteToReadOnlyFile_UnauthException
System.IO.Tests.File_ReadWriteAllBytes.WriteToReadOnlyFile_UnauthException
System.IO.Tests.File_AppendAllLines_Encoded.WriteToReadOnlyFile_UnauthException
```
These are all tests that expected an UnauthorizedAccessException, and they're no longer getting one:
```
11:29:49       Expected: typeof(System.UnauthorizedAccessException)
11:29:49       Actual:   (No exception was thrown)
```

**Comment by ianhays** [comment]
We should try to resolve this in a modular enough fashion that it also resolves #5039 and #5041 at the same time.

@Priya91 I'm going to re-assign this to myself since it's System.IO stuff unless you've already been working on it.

**Comment by Priya91** [comment]
@ianhays I've assigned it to you.

**Comment by ianhays** [comment]
Did we upgrade the CI OSX machines to El Capitan before this change? I expect the failures were brought about by changes made in how El Capitan handles file permissions. 

Possible causes I can think of:
- We don't have permissions to set the file as readonly and so the subsequent writing is a valid operation. 
  - I will add a line to check this in the test before attempting writing.
- On OSX we're running the tests under elevated permissions that allow writing to readonly files. We used to not, but the OSX upgrade broke something somewhere that required the elevation.

Regardless of the cause, we should have a better way to validate permissions breaches that takes into account the permissions that the tests are being run under. I'm unaware of a good way to do this in xplat .net. 

Thoughts:
- We can't use ProcessStartInfo to verify that the UserName of the current process is Root since that isn't supported on Unix.
- The easiest solution would be to just disable these tests on Unix with the excuse that we can't know whether the operation <i>should</i> succeed.
- We could add a build property that excludes these tests unless it is set. Something like "RunTestsAsRoot". 
  - I don't like making this a compile-time decision.
- Modify the tests to accept either result of a modification to a readonly file. If the modification succeeds, validate it succeeded correctly. If it fails, validate the correct exception was thrown.
  - This only verifies that the test did what it wanted to do correctly, <b>not</b> that what it wanted to do was doing the <i>right</i> thing.
  - At least it's preferable to not doing any validation at all on Unix.

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/5520
