### ISSUE TITLE
Request for clarification on System.Data DbDataRecord / DbDataReader

### ISSUE THREAD

**Issue by mgravell** [dotnet/corefx#4646]
`DbDataReader` has a `GetEnumerator()` API which is intended to return an `IEnumerable` that exposes `IDataRecord` (often: `DbDataRecord`)  - this is often implemented via `DbEnumerator`.

On core-clr at the current time, `DbDataReader` has an `abstract IEnumerator GetEnumerator()` method that must be overridden. However, without `DbDataRecord` or  `DbEnumerator`, it is unclear how this is meant to be done in any way. I've checked the `SqlDataReader` code, and it currently refers to a local copy of a publicly declared `DbEnumerator` (et al), but these public declarations do not seem to be accessible on the currently published packages.

So; can someone clarify this?

a: is this `abstract` method an accidental inclusion that should have been dropped in the core-clr API? or
b: is this meant to be there, but the required APIs to do it are in the wrong place and not yet available?

Assuming "b", is there a timescale to get this into place so we can verify again the proposed API?

**Comment by joshfree** [comment]
ping @saurabh500 @YoungGah

**Comment by YoungGah** [comment]
@mgravell, DbDataReader.GetEnumerator was intentionally included in corefx. However, as you pointed out, it is hard to implement it without DbDataRecord and DbEnumerator. We had challenges using DbEnumerator as it only took IDataReader into its contractors prior to .NET Framework 4.5.2, and we didn't implement interfaces in corefx originally. We temporally worked around the issue by including DbDataRecord and DbEnumerator in System.Data.SqlClient, but did not expose the contract as they don't belong to SqlClient. Since we have interfaces now, we will move DbDataRecord and DbEnumerator into System.Data.Common.dll and expose the contract accordingly.

**Comment by mgravell** [comment]
Thanks; that'll be great.

**Comment by saurabh500** [comment]
DbDataRecord and DbEnumerator have been added to System.Data.Common for RTM.

**Comment by mgravell** [comment]
Much obliged.
