### ISSUE TITLE
Proposal: CompareAttribute should apply to fields, too

### ISSUE THREAD

**Issue by SetTrend** [dotnet/corefx#4693]
Currently the CompareAttribute can't be used with fields.

Particularly with ViewModels, where property logic commonly isn't applicable, fields are a valid alternative, if not even a better choice to use.

So I propose to extend all DataAnnotation attributes to be applicable to properties and fields as well.

**Comment by JonHanna** [comment]
Why "if not even a better choice to use"? When would a field be superior to a property in a model?

**Comment by SetTrend** [comment]
Well, if I'm not mistaken, compared to a property without code, like `accessor Type myProp {get; set;}` a field like `accessor Type myProp;` ...

 * is faster to type
 * results in faster code
 * results in less compiled code

**Comment by JonHanna** [comment]
It's not a lot faster to type. It does not result in faster code. The difference in compiled CIL code is minimal. The difference in jitted machine code is nil (the access gets inlined).

I'm not arguing adamantly against using fields in this way, but the only actual advantage I can think of in having a field rather than a property is the abilty to do `ref` addressing of it, which I wouldn't recommend doing in this sort of case (as a low-level thing it can be much more useful). People are more likely to go "Oh, I need to change this field to be a property" than "Oh, I need to change this property to be a field", and then they'd be better off if they'd gone with a property in the first place.

Not that I think that's a strong reason to just add another reason why they might be forced that way by not being able to use `CompareAttribute` but it does reduce just how useful allowing the attribute on a field might be.

**Comment by SetTrend** [comment]
There is a refactoring action in Visual Studio to turn a field into a property in a snap. I wouldn't call that a too strong counterargument, too.

And, well, if it's even just a bit faster - it's still faster :wink:

**Comment by karelz** [comment]
Looks like we got only 1 vote on this for last year.
The value doesn't seem to be that great to compensate for complexity of the code (don't forget that data-binding models like MVC would have to be updated as well - they validate only properties today).

Closing for now. If there is more interest in future, we can reconsider.

**Comment by SetTrend** [comment]
OK, thanks for taking the time, though.

Actually, I have a strong feeling that votes are not an ideal measurement of driving improvement.

I myself don't have the time to vote for others' ideas. And, vice versa, I don't get any votes on my ideas for years now.

Shouldn't we return to have a board that's discussing proposals on a weekly basis?

Frankly, I'm not a fan of Open Source at all. -- I'd rather pay $1,000 per year for development time than having to rely on othes' votes. Actually, I'm already paying $2,000 per year for my MSDN subscription. And I'd gladfully add another $1.000 if my proposals would be rather discussed than just ignored because no-one takes the time to deal with them.

Here's another recent example of a very useful proposal of mine, getting a minimum of attention 😞:

https://social.msdn.microsoft.com/Forums/windows/en-US/1c9f71e8-b4a4-4c9a-ad0d-81e681ee02af/proposal-visual-studios-output-panel-should-provide-information-better-and-clear?forum=visualstudiogeneral

**Comment by jnm2** [comment]
@SetTrend I don't think this would be an improvement. It's inconsistent with good modeling practices; because of that it's inconsistent with model binders. Keep in mind too that \*if\* the property happens to be simple field get/set with no validation, it is often inlined and you have runtime performance exactly on par with a field without the cost against good design.

**Comment by JonHanna** [comment]
AFAICT the only thing this would have offered is saving a developer around a dozen keystrokes. Less if their IDE had autocorrect.

**Comment by karelz** [comment]
> Shouldn't we return to have a board that's discussing proposals on a weekly basis?

That is already happening --  the "triage" is done by area experts (@lajones @divega @rowanmiller in this case).
The votes are not just votes, but also how many positively chime in the discussion -- none in this case and as you see there are couple of community votes against the proposal. Together with the expert "triage" I think it is as fair as we can get. If you have better ideas how to "vote" on issues, I am all ears.

BTW: I don't think VS team tracks all MSDN forums posts for ideas. The primary tracking system is UserVoice.

**Comment by SetTrend** [comment]
I see. Thanks for clarifying.

Yet, I don't undestand the down-voting. Fields cannot be added to interfaces - but that's not a drawback when interfaces are no requirement in a project.

When I'm creating view models, data models and other classes, converting all the fields to properties doubles workload (given that fields names are no longer than 10 characers ("`{ get; set; }`"), becoming rather tiring when I'm creating many of them (particularly for EF).

Given that MS supports fields for EF allowing fields to be comparable would only be reasonable.

PS: My MSDN forum just adds the images to my UserVoice proposal. It's linked at the end of the MSDN forum article (and vice versa).

**Comment by svick** [comment]
> When I'm creating view models, data models and other classes, converting all the fields to properties doubles workload (given that fields names are no longer than 10 characers ("`{ get; set; }`"), becoming rather tiring when I'm creating many of them (particularly for EF).

When I have to write lots of auto-properties, I use the `prop` code snippet. Using that, you don't have to type `{ get; set; }`, just the type and name.

**Comment by jnm2** [comment]
@SetTrend code snippets like the one @svick suggests are even faster than typing fields.
To refactor existing fields fast: select them all, press Ctrl+H, find `;`, replace with ` { get; set; }`, chose Selection, and press Alt+A (or flock the Replace All button).

IMO the big reason that you don't use public fields in models has nothing to do with interfaces. It's because the setters need to be checking and enforcing the invariants, for example not letting a value be less than 1. Once you have one field converted to a property, you may as well always use properties for consistency.
Allowing the outside world to reach in and touch the state of a class directly is generally poor design. Only mutating via property setters (or better yet, only mutating via task-oriented methods) provides a much less complex design.

**Comment by SetTrend** [comment]
@svick : Good idea!

I guess I'm just acquainted to using fields instead of properties from the other languages I'm working with, like `JavaScript` and `C`/`C++`. I guess I just dislike the additional effort of reminding myself about the realm I'm eventually working in.

@jnm2 : That depends on the design you're using: If you're using `POCO` entities and utilize an additional layer for validation, you'd be perfectly off using fields.

**Comment by jnm2** [comment]
@SetTrend I subscribe to the "invalid object is an anti-pattern" view, but to each his own =)

**Comment by SetTrend** [comment]
😉
