### ISSUE TITLE
Strengthen binary search to return index of first matching element

### ISSUE THREAD

**Issue by hickford** [dotnet/corefx#4698]
[As documented](https://msdn.microsoft.com/en-us/library/w4e7fxsh(v=vs.110).aspx) the behaviour of List<T>.BinarySearch and Array.BinarySearch is undefined when the sorted list contains two elements with the same value:

> If the List<T> contains more than one element with the same value, the method returns only one of the occurrences, and it might return any one of the occurrences, not necessarily the first one.

It would be useful to strengthen this to return the first matching element—for some problems this detail is important. This can be done without cost—the complexity would remain O(log n).

The binary search methods in C++, Golang and Python all return the first matching element

1. http://www.cplusplus.com/reference/algorithm/lower_bound/
1. https://golang.org/pkg/sort/#Search
2. https://docs.python.org/3/library/bisect.html#bisect.bisect_left

**Comment by hickford** [comment]
> for some problems this detail is important

Example please.

**Comment by ianhays** [comment]
The reason we're different is because our two BinarySearch implementations: [BinarySearchBitwiseEquals](https://github.com/dotnet/coreclr/blob/master/src/classlibnative/bcltype/arrayhelpers.h) (for when the object uses the Default comparer) and [Array.BinarySearch](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Array.cs) (for cases where the previous isn't applicable or fails) take a traditional iterative approach to the implementation of BinarySearch that exits the loop whenever a matching item is found.

e.g.:
```
        while (lo <= hi) {
            int i = lo + ((hi - lo) >> 1);
            if (array[i] < value) {
                lo = i + 1;
            } 
            else if (array[i] > value){
                hi = i - 1;
            }
            else {
                return i;
            }
        }
        // not found
```

The more popular approach - as you've researched - appears to be [the deferred detection of equality](https://en.wikipedia.org/wiki/Binary_search_algorithm#Deferred_detection_of_equality) in which there is no early termination of the iterative loop. This allows the search to continue for the full duration, finding the lowest index in which the value stored equals the value being searched for.

The change for us in BinarySearchBitwiseEquals would look like this:
```
        while (lo < hi) 
        {
            int i = lo + ((hi - lo) >> 1);
            if (array[i] < value) {
                lo = i + 1;
            } 
            else {
                hi = i;
            }
        }
        if ((hi == lo) && (array[lo] == value))
            return lo;
        else
            // not found
```

Because our current implementation has undefined behavior when there are duplicates, providing consistency in the behavior won't be a breaking change functionally.

There is the performance impact to consider, however. Average complexity is unchanged as you said, but edge cases where the search exits unusually early will be negatively affected by this change. I imagine we went with the implementation we have now because it is the overall faster approach but it's worth investigating if switching to the deferred method is worth the tradeoff. My impression is that it is.

**Comment by hickford** [comment]
Thanks for explaining.

**Comment by ianhays** [comment]
Of course! Thanks for bringing this up. @AlexGhiondea and I investigated it some more and ultimately decided it wasn't worth taking the perf hit and breaking the existing behavior. As such, I'm going to close out this issue and abandon my CoreCLR PR. There is some more discussion on this at https://github.com/dotnet/coreclr/pull/2447.

I'll go ahead and copy-paste a possible log(n) workaround to this issue that I posted there:

```
/// <summary>
/// Finds the first value in the given list that matches the specified value
/// </summary>
private static int DeferredBinarySearch<T>(List<T> list, T value, IComparer<T> comparer = null)
{
    int first = list.BinarySearch(0, list.Count, value, comparer);
    int high = first;
    while (high >= 0)
    {
        first = high;
        high = list.BinarySearch(0, high, value, comparer);
    }
    return first;
}
```
