### ISSUE TITLE
Improve Enumerable.Reverse() performance for IList and LinkedList

### ISSUE THREAD

**Issue by Braini01** [dotnet/corefx#4750]
I would like to suggest and discuss a possible performance improvement of the Enumerable.Reverse() extension function in the System.Linq namespace. Currently a _Buffer<TElement>_ struct is created that allocates a new array of elements in most cases, as can be seen here:

``` csharp
internal struct Buffer<TElement>
{
    internal TElement[] items;
    internal int count;

    internal Buffer(IEnumerable<TElement> source)
    {
        IArrayProvider<TElement> iterator = source as IArrayProvider<TElement>;
        if (iterator != null)
        {
            TElement[] array = iterator.ToArray();
            items = array;
            count = array.Length;
        }
        else
        {
            items = EnumerableHelpers.ToArray(source, out count);
         }
    }

    internal TElement[] ToArray()
    {
        //...
    }
}
```

For the ReverseIterator the _items_ array of the _Buffer_ struct is then iterated through from end to start. I would think that the array allocation is not always needed, so I suggest to handle the reverse iteration of _IList_ and _LinkedList_ differently. An _IList_ object could be directly used for reverse iteration like the buffer struct but without creating and allocating the in this case unneccesary buffer first. For _LinkedList_ sources the reverse iteration would be easily possible without a _Buffer_ too.
So what do you think about this? Am I missing a good reason here why this has not been done already? I could imagine the argument that Enumerable cannot handle every special collection differently, but at least _IList_ is often treated special.

Oh and btw: 
I think this

``` csharp
TElement[] array = iterator.ToArray();
items = array;
count = array.Length;
```

should be

``` csharp
items = iterator.ToArray();
count = items.Length;
```

as I don't see a reason for introducing the variable _array_.

**Comment by JonHanna** [comment]
To take your "btw" first, that adds the cost of a field access without gaining anything.

As for specialising `Reverse()`, I like the idea generally and certainly wouldn't argue against it on the basis of a policy against specialising for particular collection types (probably about half my PRs that didn't just add tests did so). It would though:

1. Change the known behaviour. Which is a sub-category of changing the observable behaviour, in that the buffering behaviour of `Reverse` is known by devs and hence more likely to be depended on in some way than with other observable changes.

2. Change the error handling behaviour. Currently you can have the explicitly documented exceptions on the call of `Reverse()` itself (call it on `null`), and any other exception caused by the source enumerable will happen on the first call to `MoveNext()`. This change would alter that.

3. Make the observable behaviour differ more between different types of sequence. In particular, the above two effects would still be as they currently are when it comes to any non-`IList<T>` sequence. I could be wrong (going just from memory here) but currently the only calls that differ in terms of whether buffering happens or not are those where the buffer is made use of entirely in the course of that call (e.g. `ToArray()`). As such, while there are differences in whether a method buffers or not depending on the type of `source` in some methods, they aren't cases where that difference affects the calling code, except to attempt to improve performance.

**Comment by svick** [comment]
I think there are similar concerns as when optimizing `Skip()` for `IList<T>` (#4551). Namely:

* What happens when the underlying collection is modified while iterating? The old implementation seems to use snapshot, your proposed implementation would always return the latest values, I think. That would include throwing exception if the collection size decreased.

 Is this an acceptable change of behavior?

* What about `ImmutableList<T>`? It implements `IList<T>` and its indexer is slow (O(log n)), so this change would likely decrease performance for that type.

**Comment by JonHanna** [comment]
It goes a wee bit beyond that. In particular, that change to `Skip()` will most often either not be noticeable or would change a case that throws to a case that doesn't, so it's unlikely to hurt any current code, whereas this changes non-throwing behaviour to different non-throwing behaviour.

**Comment by Braini01** [comment]
So a field access costs more than the array variable declaration? Okay, learned something new :)

I would at least argue or discuss a little bit over your first point @JonHanna. How do you define known behaviour? The buffering is not mentioned in the [documentation](https://msdn.microsoft.com/en-us/library/bb358497%28v=vs.110%29.aspx) so this behaviour is only known if the dev looked at the actual source code and I would think not every dev is doing that ^^

**Comment by JonHanna** [comment]
> The buffering is not mentioned in the documentation so this behaviour is only known if the dev looked at the actual source code and I would think not every dev is doing that.

Lots of devs do look at the source, and plenty look at decompilation with ILSpy or .Net Reflector. The difference in streamed and buffered behaviour is mentioned in posts like http://blogs.msdn.com/b/marcelolr/archive/2010/05/06/some-performance-notes-on-enumerable-linq-operators.aspx, in books and so on. It's certainly something that is known about.

And one can also code a dependency on a feature without understanding it! (The easiest way here would be to have a dependency on the fact that if you `foreach(var thing in things.Reverse()) doSomething(thing);` and accessing one of those `things` can throw but `doSomething` will not then you will either `doSomething` to all the things, or to none of them).

In the issue @svick linked to I said I thought its similar issues where issues should be considered and then decided were ultimately okay, but only after the considering was done. I'm more sceptical here than I was there (and I was finally convinced there, though that's not terribly important as I'm not one of the people who need to be convinced), because the impact is a bit larger. But then the gain is perhaps larger too, in removing an O(n) operation relative to the entire size rather than O(n) relative to the subset skipped over.

**Comment by comdiv** [comment]
May be where is a way to provide explicit optimization machanics, that is based on fact that developer (especially if performance is important) knows what collection exactly it uses.
So
1) default implementation must be keeped in current state - it's type agnostic, bufferized and stable - it's normal situation

2) but, while it's just extensions we can extend their set with "hinted" version on SQL manner  - if you know how your collection is used and what is it's nature - you can provide hint for Linq - how to deal with it

For example:
```
// we know that it's already array-like list and we know that by design it's "immutable"
IList<int> mylist = new List<int>{1,2,3,....,10000};
public IEnumerable<int> Back_InefficientWithLinq(){
	foreach(var i in mylist.Reverse()){ // it's really worst thing today - while buffer created
		yield return i;
	}
}
public IEnumerable<int> Back_EfficientButNotLinq() {
	for(var i=mylist.Count-1;i>=0;i--){
		yield return mylist[i];
	}
}
// so it's better if we could explain it to Linq:
public IEnumerable<int> Back_ByNewLinqHints(){
	return mylist.Reverse( CollectionHints.Immutable | CollectionHints.Indexed | CollectionHints.FixedSize );
	// or return mylist.Reverse( CollectionHints.Immutable | CollectionHints.AutoDetectFromType );
}
```

Expected that due to LinqHints.Indexed and CollectionHints.FixedSize it can use Count and [] to access elements and while it is CollectionHints.Immutable - it forced to not bufferise it. While List<int> is really well-known class - it can provide support for CollectionHints.AutoDetectFromType to determine collection nature automatically.

**Comment by JonHanna** [comment]
On the hints matter, hints are in SQL for when the developer knows something better than the database. With linq when the developer knows something better than linq they can always just not use linq for that particular case, which often isn't an option in SQL. I've loved trying to make linq better at picking up its own hints where it can, but I think the ideal is to reduce worry for the developer by letting them be confident that linq will often approach what they could get with custom code without their having to think about that problem and concentrate on defining the query. Hints introduce questions of what hint is or isn't appropriate rather than remove them, and would reduce the re-usability of chains of calls.

 To come back to optimising reverse for list. I'd really like to do this if the impact could be acceptable. There are two possible approaches:

```C#
int i = source.Count - 1;
while (i >= 0)
{
  yield return source[i];
  int count = source.Count;
  if (--i >= count)
    i = count - 1;
}
```

```C#
int count = source.Count;
for (int i = 1; i <= count; ++i)
{
  yield return source[count - i];
  count = source.Count;
}
```

The difference being how they treat changes to the size of the source while it is enumerated (if there was a separate overload for arrays it could just cycle through until it's yielded `source[0]` because an array's length is immutable).

I think the first would be the less surprising, both in not being put into possibly infinite loop by growth, and not skipping elements by shrinkage away from it's current index. (The same is also true of `ImmutableList<T>` but as well as handling that requiring an added dependency, immutable lists have such different performance characteristics to most other `IEnumerable` implementations that I think they should maybe be given a lot of linq method overloads completely separately).

A version optimised for `LinkedList<T>` would have to be either of:

```C#
for(LinkedListNode<TSource> node = source.Last; node != null; node = node.List == null ? source.Last : node.Previous)
  yield return node.Value;
```
```C#
for(LinkedListNode<TSource> node = source.Last; node != null; node = node.Previous)
{
  yield return node.Value;
  if (node.List == null) throw new InvalidOperationException();
}
```

The first of these has issues akin to the second of the cases for `IList<T>`, but can vary in behaviour much more wildly since a single removal could cause many results to be repeated. The second introduces a throw into what would have been working code. But then all of them affect working code in not buffering where they had before in terms of what happens to collections that are altered during enumeration. This is in contrast to #4551 in that with that change either an attempt that would have thrown when run against the old code is now going to work, or (if the underlying collection tolerated being mutated during enumeration) the result would be the same either way. Here either code that would have worked run against the old code will now throw an exception, or else the results will be different.

In terms of how common such code could be, it's worth considering that a common newcomer question is why code that tries to update a collection that doesn't tolerate updates during enumeration doesn't work. As such, it's reasonable to suspect that if people are writing code that tries to do that, then people are also writing code that updates across a buffering operation (indeed the general solution is to manually buffer) or code that updates collections that do tolerate such changes.

All in all, I can't say I'm really happy with either possible approach for `IList<T>`, and even less so for linked lists. About as much as I can see being safe is to make use of the buffering itself to optimise `Reverse().ToArray()` and `Reverse().ToList()` which I'm suggesting in #5486 (in what is currently the 7th commit there, but they'll be squashed into one if that PR is going to be accepted). It would also be possible to use `IPartition` to optimise `Reverse().First()` and Reverse().Last()` but they don't seem likely , and `Reverse().ElementAt()` only slightly less unlikely, so I haven't tried that.

**Comment by VSadov** [comment]
As described in comments above, there is clearly a danger of compat breaks. 
It is not hard to imagine code that currently works and will not work after this change.

The following example would be relying (intentionally or not) on the snapshotting behavior or Reverse and after the change would be broken.

```cs
foreach(var item in collection.Reverse())
{
      // user code runs between iterations -
      // change collection somehow - add or remove an element 
      DoSomething(collection)
}
```
It looks like the benefits do not justify the likelihood for breaking existing apps.
