### ISSUE TITLE
coreCLR no option for passing filepath as string inside constructors

### ISSUE THREAD

**Issue by Devmates** [dotnet/corefx#4825]
I noticed there are several constructors for IO tasks that do not include the option for passing a string in .NET Core.
```csharp
//old way
XmlDocument xdoc
xdoc.Load(@"file\path");
//new way
XmlDocument xdoc
xdoc.Load(new FileStream(@"file\path", FileMode.Open);

//old
string file = @"file\path";
var sw = new StreamWriter(file, false, new UTF8Encoding(false))
// new
string file = @"file\path";
var sw = new StreamWriter(new FileStream(file, FileMode.OpenOrCreate), new UTF8Encoding(false))
```

What is the reason behind this and is there a better way than using the FileStream constructor to pass the filepath as string?

**Comment by weshaggard** [comment]
Instead of calling FileStream directly I would suggest File.OpenText or File.CreateText. 

As for why methods like xmlDoc.Load(string) and StreamWriter(string) aren't part of .NET Core, it is mostly about layering and limiting dependencies. We have removed a number of string based file path APIs to eliminate their dependency on the FileSystem APIs, and instead they work through our Stream abstraction.
