### ISSUE TITLE
EventSource tests fail on non-windows platforms

### ISSUE THREAD

**Issue by davmason** [dotnet/corefx#4871]
The majority of the EventSource tests fail on non-windows platforms. Need to investigate further.

**Comment by stephentoub** [comment]
@davmason, I started looking at this, and they're failing due to a NullReferenceException happening inside EventSource:
```
System.NullReferenceException:System.NullReferenceException: Object reference not set to an instance of an object.
         at System.Diagnostics.Tracing.EventSource.WriteImpl(String eventName, EventSourceOptions& options, Object data, Guid* pActivityId, Guid* pRelatedActivityId, TraceLoggingEventTypes eventTypes)
```
That ends up triggering an out-of-band message, which the listener then picks up, compares to the target message, sees they don't match, and it fails.

But that NRE is concerning and something it seems we should investigate.  At least one of the problems seems to be that this WriteImpl method is dereferencing this.providerMetadata, but this.providerMetadata is null.

Can you help sort this out?

cc: @vancem

**Comment by davmason** [comment]
I have a change that enables the Linux tests. I am going to open a pull request soon to enable all the tests on Linux and fix a couple issues. There are a few places where the etw implementation wasn't properly ifdefed out and it can cause null references like you mention above.

**Comment by stephentoub** [comment]
Thanks, @davmason.
