### ISSUE TITLE
Resource editing stopped working in VS on corefx projects

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4883]
Attempting to open a Strings.resx now fails with an error like this:
![capture](https://cloud.githubusercontent.com/assets/2642209/11661432/e1eb2c5a-9d9f-11e5-80f6-83f2bf18254e.PNG)

Seems to have started happening in the last week or two.

**Comment by stephentoub** [comment]
Thanks, @weshaggard.  Your fix worked for me.

**Comment by joperezr** [comment]
Looks like this very old issue is repro-ing again. I'm trying to investigate why is this happening this time around.

**Comment by joheredi** [comment]
Hi, I was looking into this and found that changing the configuration target to other than Debug and reloading the project works around this issue

![image](https://cloud.githubusercontent.com/assets/21109913/20085616/24e2a63c-a51f-11e6-8816-f2f65920fd0a.png)

I haven't been able to pinpoint the root cause, but will keep looking

**Comment by joperezr** [comment]
That's very interesting, I wonder why having the default TargetGroup would cause Resource Editing to stop working... I'll also take a quick peek to try to figure this out

**Comment by stephentoub** [comment]
Seems to be fixed.
