### ISSUE TITLE
GZipStream always writes a header with the OS set to "Windows" even on Unix

### ISSUE THREAD

**Issue by justinvp** [dotnet/corefx#4891]
`GZipStream` [always](https://github.com/dotnet/corefx/blob/085865e6f375d11dd1d5dd815b251356b0f88d2b/src/System.IO.Compression/src/System/IO/Compression/GZipUtils.cs#L43) writes a header with the OS member set to "Windows" (0).

When running on Unix, should it be set to "Unix" (3)? Or maybe even "unknown" (255) for all OSes?

From the [RFC](http://www.zlib.org/rfc-gzip.html#header-trailer):

```
OS (Operating System)

This identifies the type of file system on which compression took place. This may be useful in determining end-of-line convention for text files. The currently defined values are as follows:

  0 - FAT filesystem (MS-DOS, OS/2, NT/Win32)
  1 - Amiga
  2 - VMS (or OpenVMS)
  3 - Unix
  4 - VM/CMS
  5 - Atari TOS
  6 - HPFS filesystem (OS/2, NT)
  7 - Macintosh
  8 - Z-System
  9 - CP/M
 10 - TOPS-20
 11 - NTFS filesystem (NT)
 12 - QDOS
 13 - Acorn RISCOS
255 - unknown
```

Now that the managed inflater/deflater implementation has been removed in #4874, perhaps it'd be a good time to refactor the gzip implementation to have zlib handle it entirely (zlib can be configured to write the gzip header/footer itself). This should take care of the header OS issue (let zlib handle it) and would reduce the number of lines of code that needs to be maintained in CoreFX, allow zlib to handle the crc32 calculation on its own, and avoid unnecessary allocations associated with having to create instances of `GZipFormatter` and intermediate `byte[]` buffers for the header/footer.

cc: @ianhays, @stephentoub

**Comment by ianhays** [comment]
>When running on Unix, should it be set to "Unix" (3)? Or maybe even "unknown" (255) for all OSes?

Thanks for bringing this up, Justin. It definitely seems that we should be setting the header os member to something more specific, and it wouldn't be difficult to change it.

>perhaps it'd be a good time to refactor the gzip implementation to have zlib handle it entirely

I'm initially concerned about making sure we don't mess up back-compat and cross-compat by using the zlib header writing instead of our own, but from the zlib docs it seems like we have to set most of the info ourselves (through inflategetheader/deflatesetheader) anyways, so that shouldn't be an issue.

The IFileFormatReader interface is already unnecessary now. The only value it adds is in its specification of the Window Size which tells ZLib to parse header information for either gzip or zlib. All of its other functionality is now dead code, and I should have refactored it out in #4874. Since this isn't being used, InflateGetHeader wouldn't be used either.

The IFileFormatWriter interface is currently still being used, but we could change that. The only thing we <i>might</i> need to keep in the class if we moved to use ZLib header writing would be the ```_headerBytes``` array. A cursory glance at it and the docs suggests that we don't keep anything valuable (i.e. non-default) in that array in the GZipFormatter class anyways, so we may be able to trash all of it.

Looks like a good proposal. This would allow us to remove the GZipDecoder.cs, GZipUtils.cs, InputBuffer.cs, and OutputBuffer.cs files.

**Comment by ianhays** [comment]
Actually, InputBuffer.cs and OutputBuffer.cs should have been removed earlier. They're already dead code.

**Comment by justinvp** [comment]
Devil's advocate: One reason why we might want to leave the OS header member as-is, or change it to 255 (unknown) for all operating systems, is to avoid unintended information disclosure.

On web servers, it's common to want to disable any HTTP response headers that broadcast information about the web server's configuration (e.g. OS and web server), to minimize the amount of information disclosed to attackers.

More info:
http://www.golemtechnologies.com/articles/server-header-security
http://www.troyhunt.com/2012/02/shhh-dont-let-your-response-headers.html

I've never heard of the gzip header being used for such purposes, but that's not to say it doesn't happen.

Should we be concerned about this? I can definitely see `GZipStream` being used to implement compression for web servers and in other server scenarios where someone might not want this information to be disclosed. That said, I don't think it's even possible to configure IIS's gzip header, for example, and I imagine it's difficult, if not impossible, to configure on other web servers. And there are certainly non-server uses of `GZipStream` where having the correct OS header may be desirable.

I guess in the future we could always add a new option to `GZipStream` to allow configuring the OS header field (maybe just to set it to unknown), if/when anyone raises this as a real concern.

**Comment by justinvp** [comment]
For reference, it looks like Java's GZIPOutputStream always writes 0 for the OS, whereas Go uses 255 by default, but is configurable.

http://stackoverflow.com/a/29012600

```
                          |    Java |          Go
ID1                       |      31 |          31
ID2                       |     139 |         139
CM (compression method)   |       8 |           8
FLG (flags)               |       0 |           0
MTIME (modification time) | 0 0 0 0 | 0 9 110 136
XFL (extra flags)         |       0 |           0
OS (operating system)     |       0 |         255
```

**Comment by ianhays** [comment]
Since we have to set the headers fields manually whether we use Zlib or a custom writer, I'm going to create a new issue (#4895) for the discussion on removing the FileFormatReader/FileFormatWriter stuff and leave this issue for the decision on what to do with the header.

**Comment by ianhays** [comment]
So back to the OS number in the header. It's an interesting point you raise about the HTTP headers and is a good point to think about. It's a bit different since the server could be Windows using archives created on Unix or whatever, but in the general cases I'd imagine they'd be the equal.

>it looks like Java's GZIPOutputStream always writes 0 for the OS

Do you have more data points by any chance? The data from that stackoverflow post shows Java with an OS of 0, but I wonder if that's because it's hard-coded like ours if that's because the poster was running on a FAT system when he ran the test.

I don't like hard-coding it to FAT now that we're using Zlib. I think that the hardcoding is a relic of the managed implementation that slipped into our zlib implementation since we stuck with the managed header writing. 

I see two good options:
1. Set OS to "unknown" 255 always. Maybe add an overload in the future if the want is there.
2. Set OS to what the OS actually is.

**Comment by JonHanna** [comment]
http://stackoverflow.com/questions/31681484/is-gzipstream-header-reliable-across-net-versions and http://stackoverflow.com/questions/4662821/is-there-a-way-to-know-if-the-byte-has-been-compressed-by-gzipstream show that people have at least considered using the header to detect the use of `GZipStream`. http://stackoverflow.com/questions/4662821/is-there-a-way-to-know-if-the-byte-has-been-compressed-by-gzipstream/26234928#26234928 shows someone confident that they've done so.

Compatibility would be broken in these cases. The lack of confidence involved in the question and the answers (including mine for that matter) suggests that maybe it wouldn't be a total shock to those affected and so they'd be able to adjust *relatively* well, but they'd still be broken by it.

**Comment by ianhays** [comment]
Thanks for the links, Jon. Changing this will certainly break someone somewhere, though I think it's a fair expectation that the OS ID in the header might change in .NET core. If we're iffy enough on the benefits of the two above options such that we're on the fence, back-compat and leaving it as is will probably win out though I personally prefer doing something more correct with the value even if it is seldom used. 

My personal preference would be option 2 above: leave the desktop Windows behavior intact (i.e. Windows is always 0) but make the other platforms set the OS correctly. That doesn't answer the security question, though.

**Comment by SamB** [comment]
It would be wise to consider reproducible builds when deciding this question.

**Comment by justinvp** [comment]
> Do you have more data points by any chance? [...] I wonder if that's because it's hard-coded like ours if that's because the poster was running on a FAT system when he ran the test.

 - I just tested Java's `GZIPOutputStream` running on OS X El Capitan (HFS+, java version 1.8.0_25), and the OS field was set to 0 (FAT).

 - I also tested `GZipStream` on Mono on OS X El Capitan (HFS+, mono version 4.0.2), and the OS field was set to 3 (Unix).

**Comment by JonHanna** [comment]
That Windows is always 0 and not 11 though NTFS is now much more common than FAT suggests that someone found some compatibility issue somewhere already.

The purist in me would like to see it default to the correct flag for the system it was done on, and configurable for cases where the user knows better, but wonders whether its strictly correct to say the compression was done on any file system if it need never involve the file system at all.

The pragmatist in me wonders when it's actually useful.

**Comment by justinvp** [comment]
I know I raised the question, but my personal preference is leaning towards just keeping the behavior as-is for compatibility.

I haven't been able to find any complaints about Java's behavior of always setting it to 0 on all platforms and am having a hard time coming up with a real-world need for it to match the underlying platform, other than for purity/correctness.

If we do change the behavior for non-Windows platforms, it's almost certainly going to break someone porting existing .NET code that depends (purposely or inadvertently) on the header OS member being set to 0. It'd be nice to save them the pain and frustration.

We can always revisit this and provide a new API to make it configurable if/when an actual need is brought forward.

**Comment by stephentoub** [comment]
If we have any plan to switch to zlib for gzip implementation, then I suggest we switch the value used in the header now, as my understanding is that zlib will write one based on the platform the zlib lib was compiled for, and if we're going to make a change that could potentially break someone, we should do it now.

Otherwise, I suggest we leave it as-is. If other major systems (e.g. Java) are using the value 0 regardless of platform / file system, then the field is relatively meaningless and we can similarly continue to output 0.

**Comment by akoeplinger** [comment]
> I also tested GZipStream on Mono on OS X El Capitan (HFS+, mono version 4.0.2), and the OS field was set to 3 (Unix).

We're using zlib for GZipStream and zlib sets the field in that case (I don't think you can change that behavior, as Stephen said).

**Comment by justinvp** [comment]
When using zlib for gzip, by default zlib writes the gzip header using an os value based on the platform the zlib lib was compiled for, but zlib also exposes `deflateSetHeader` which can be called to explicitly set whatever header values you want.

**Comment by ianhays** [comment]
As Justin said, the switch to using zlib for gzip header generation doesn't make this decision for us since we can make use of ```deflatesetheader``` to set the OS.

>When using zlib for gzip, by default zlib writes the gzip header using an os value based on the platform the zlib lib was compiled for

Don't the docs contradict this? From [the docs](http://www.zlib.net/manual.html): ```If deflateSetHeader is not used, the default gzip header has text false, the time set to zero, and os set to 255, with no extra, name, or comment fields.```

**Comment by stephentoub** [comment]
The docs appear to be wrong.

**Comment by ianhays** [comment]
That they are. I'll shoot them an email.

**Comment by justinvp** [comment]
I keep going back and forth between keeping it as-is for compat and changing the behavior... I'm on the fence.

One argument for going ahead with the header change: In .NET 4.5 we changed `GZipStream`/`DeflateStream` to use zlib under the covers by default instead of the old managed implementation (for improved compression). While the gzip headers remained the same before and after the change (because the headers were still being handled in managed), the overall output did change.

For example:

```c#
using System;
using System.IO;
using System.IO.Compression;

class Program
{
    static void Main()
    {
        var ms = new MemoryStream();

        using (var gzip = new GZipStream(ms, CompressionMode.Compress))
        {
            gzip.WriteByte(42);
        }

        Console.WriteLine(string.Join(",", ms.ToArray()));
    }
}
```

Running this on .NET 4.6 with the `<NetFx45_LegacyManagedDeflateStream enabled="1"/>` compat switch specified in `app.config`, i.e. **Old Managed Output**:

```
31,139,8,0,0,0,0,0,4,0,236,189,7,96,28,73,150,37,38,47,109,202,123,127,74,245,74,215,224,116,161,8,128,96,19,36,216,144,64,16,236,193,136,205,230,146,236,29,105,71,35,41,171,42,129,202,101,86,101,93,102,22,64,204,237,157,188,247,222,123,239,189,247,222,123,239,189,247,186,59,157,78,39,247,223,255,63,92,102,100,1,108,246,206,74,218,201,158,33,128,170,200,31,63,126,124,31,63,34,190,245,255,4,0,0,255,255,91,38,185,9,1,0,0,0
```

And then running it without the compat switch, i.e. **New zlib Output**:

```
31,139,8,0,0,0,0,0,4,0,211,2,0,91,38,185,9,1,0,0,0
```

That behavior change would have broken people in similar ways as changing the os header member (e.g. md5 checksums of files compressed using `GZipStream` would change, etc.), but I don't recall ever hearing any customer complaints about it. And googling for the `NetFx45_LegacyManagedDeflateStream` compat switch yields few search results.

**Comment by ianhays** [comment]
We've talked about several disadvantages to setting the OS field correctly: possible security risk, breaking back-compat, introducing cross-compat issues. But as Jon&Steve said earlier: <i>is it even useful?</i> Neither Java nor Go seem to care about the OS value, and the gzip docs themselves are vague on the benefits of the value being correctly set. I'm all for correctness for correctness sake, but it it breaks cross-compat it gets trickier (even though performing validation on the compressed data was inadvisable to begin with). 

So I'm on the fence. It will be slightly less effort to allow ZLib to set the header value when I do #4895. Adding in a hard-code to 0 wouldn't be particularly difficult, but we would have to modify CLRCompression to export deflatesetheader and also include the definition in the shim which would be minor hassles.

**Comment by JonHanna** [comment]
> That behavior change would have broken people in similar ways as changing the os header member (e.g. md5 checksums of files compressed using `GZipStream` would change, etc.), but I don't recall ever hearing any customer complaints about it.

I'm not sure that's a valid counter-example. The cases I found had people examining the header itself, and so they would not have been broken by a change here.

That said, I think the balance might just be in considering it undefined. If the value has to come from somewhere in the code-base, then set it to `0` for backwards compatibility and minimising disclosure, but if forcing it to `0` requires effort (whether human or processing) then since there's already an argument in favour of setting the "correct" value, risk the break.

**Comment by ianhays** [comment]
#4917 modifies the behavior by allowing ZLib to set the OS field. It was going to take a nontrivial amount of effort to add in calls to DeflateSetHeader so I left them out for now.
