### ISSUE TITLE
Implicit conversion from T to Task<T>

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/corefx#4896]
It would be nice if there were an implicit conversion from `T` to `Task<T>`; it would make the code cleaner when writing a synchronous implementation of a method that returns a `Task<T>`. (I got this idea when reading about `ValueTask<T>`, which defines an implicit conversion from `T` and from `Task<T>`)

For instance, consider this method:

```
public async Task<int> FooAsync()
{
    await BarAsync();
    return 42;
}
```

Later, after the code has shipped, I realize I no longer need to call `BarAsync`, so the implementation can become synchronous; I don't want to break the public interface, so `FooAsync` must still return a `Task<T>`. So I change the code to this:

```
public Task<int> FooAsync()
{
    return Task.FromResult(42);
}
```

In this simple case, it's not much of an issue, but in more complex methods it tends to reduce readability. With an implicit conversion, I could just write this:

```
public Task<int> FooAsync()
{
    return 42;
}
```

Another example that might be more compelling is when the return type is `Task<T>` and we want to return a value of type U, where `U : T`:

```
public Task<IEnumerable<int>> FooAsync()
{
    // Type must be specified explicitly, because Task<T> is not covariant
    return Task.FromResult<IEnumerable<int>>(new[]{1, 2, 3});
}
```

With an implicit conversion, it would "just work" without needing to specify the type:

```
public Task<IEnumerable<int>> FooAsync()
{
    return new[]{1, 2, 3};
}
```

I'm not aware of any downside to introducing this conversion; am I missing something?

(Sorry if this has already been proposed, I searched existing issues but didn't find anything relevant)

**Comment by NickCraver** [comment]
I would step back and look at it this way: If the method isn't `async` and isn't waiting on something else, why is it still returning a `Task` at all? I can't think of a case where this is correct save implementing an interface or implementing abstraction. 

To sum up the downsides: the implicit conversion introduces an inefficiency when the correct answer is usually: "this method shouldn't return a Task". IMO that downside is bigger than the wins in the cases of synchronously implementing async APIs. I think we *want* the friction that exists in such situations. It actually encourages the programmer to implement correct, pervasive, async implementations. e.g. "Is there something in here that should be async?"

**Comment by stephentoub** [comment]
> I'm not aware of any downside to introducing this conversion; am I missing something?

Thanks for the thoughtful write-up, but an implicit conversion that allocates is considered fairly bad form.  It makes it very difficult to spot potential performance problems, for example.  For that reason alone I wouldn't want to add such a conversion to such a core type, on top of Nick's comments.

**Comment by thomaslevesque** [comment]
> I would step back and look at it this way: If the method isn't async and isn't waiting on something else, why is it still returning a Task at all? I can't think of a case where this is correct save implementing an interface or implementing abstraction.

Of course, I don't write methods that return tasks when it's not necessary, but:

- in the scenario I had in mind, FooAsync is a library method, that might already be in use. If at a later time it no longer _needs_ to return a task, changing the method signature would be a breaking change for code that depends on it.

- you mentioned the other case yourself: if you implement an interface or override an abstract method, you don't get to choose the return type, even if your implementation is synchronous

> an implicit conversion that allocates is considered fairly bad form

Good point... it was a sensible choice in `ValueTask<T>`, but only because it's a struct.

Too bad we're stuck with `Task<T>` defined as a class...

**Comment by JonHanna** [comment]
In a way you would effectively get this by just taking out the call to `BarAsync()` you'd realise was unnecessary:

```C#
public async Task<int> FooAsync()
{
    return 42;
}
```

You return an `int`, you get a `Task<int>`, implicitly.

Okay, that raises warning CS1998, but then it is something that should probably be done differently and is worth having a warning about.

It's a bit more involved behind the scenes than just calling `FromResult()`, whether implicit or explicit, but that gives us more than an implicit conversion would. Consider that the following works:

```C#
public async Task<long> FooAsync()
{
    return 42;
}
```
But not:

```C#
public Task<long> FooAsync()
{
    return Task.FromResult(42); // Cannot implicitly convert from Task<int> to Task<long>.
}
```
Or for a more practical example, consider:

```C#
private async Task<ActionResult> PostPageResultAsync(IQueryable<Post> posts, int pageNum, int? year = null)
{
    if (pageNum <= 0)
        return HttpNotFound();

    DateTime now = DateTime.UtcNow;
    posts = posts.Where(po => !po.Deleted && po.PublishFrom <= now);

    int count = await posts.CountAsync();
    int totalPages = (count + PageSize - 1) / PageSize;
    if (pageNum > totalPages)
        return HttpNotFound();

    var model = new PostPage { Year = year };
    if (pageNum > 1)
        model.PrevPage = pageNum - 1;

    if (pageNum < totalPages)
        model.NextPage = pageNum + 1;

    model.Posts = await posts
        .Include(po => po.Author)
        .OrderByDescending(po => po.PublishFrom)
        .Skip((pageNum - 1) * PageSize)
        .Take(PageSize).ToListAsync();

    return View(model);
}
```

If I decided that I was better-off being synchronous with this, then an implicit conversion doesn't help, because the method needs to return a `Task<ActionResult>` but depending on the path taken, implicit conversion would mean that this would return a `Task<HttpNotFoundResult>` or a `Task<ViewResult>`.

And I don't think this example is at all far-fetched. Certainly I've had code that returned different types derived from `ActionResult` in different cases that I've moved from async to sync or vice-versa quite a few times, though at least there it's easy to just change the whole signature (since there generally isn't any third-party consumer). Comparable cases in other domains where an implicit conversion wouldn't help aren't far-fetched.

To come back to the example of:
```C#
public async Task<int> FooAsync()
{
    return 42;
}
```
If we compare what we need from this (a completed `Task<int>` with a `Result` of `42`) and what it does (create an instance of a struct implementing `IAsyncStateMachine`, set some fields, create an instance of `AsyncTaskMethodBuilder<int>` via a method call, set that as the value of another field, call `Start()` which calls into a state-machine which calls `SetResult()` on the builder, the access the builder's `Task` property which returns a `Task<int>` affected by that `SetResult()`) there is more going on here than is strictly necessary.

If all that could be optimised to be much closer to just `Task.FromResult(42)` then as well as improving this case it would also:

1. Improve performance of `async` methods that have non-awaiting paths (e.g. the `pageNum <= 0` branch in the example I gave above).
2. Reduce the size of some other state-machines used to implement `async` (fields relating to locals prior to the first `await` could likely be removed).
3. Perhaps as such improve the performance prior to that first `await`.

Now, this is for the compiler rather than the corefx library, and probably not vital (anyone bullish about the performance of such methods can refactor them to do less in the async state-machine themselves, and probably won't find they've really gained much when they do), but if it were to happen it would give you something close to the implicit `Task.FromResult()` without the down-sides.

**Comment by thomaslevesque** [comment]
Thanks Jon for your detailed answer.

> If I decided that I was better-off being synchronous with this, then an implicit conversion doesn't help, because the method needs to return a Task<ActionResult> but depending on the path taken, implicit conversion would mean that this would return a Task<HttpNotFoundResult> or a Task<ViewResult>.

I'm not sure I understand this part. Returning `HttpNotFound()` would implicitly convert a `HttpNotFoundResult` to `Task<ActionResult>`, and returning `View(model)` would also implicitly convert a `ViewResult` to a `Task<ActionResult>`. The conversion target type would be based on the method's return type, not the type of the returned value. At least that's what would happen with an implicit conversion like this in `Task<T>`:

```
public static implicit operator Task<T>(T value)
{
    return Task.FromResult<T>(value);
}
```

But anyway, the hidden allocation mentioned by Stephen is reason enough to convince me that this conversion isn't such a good idea after all... I'll close this issue now.

**Comment by JonHanna** [comment]
You're correct. I considered the chain of implicit casts incorrectly, and thought the first cast from `ViewResult` to `ActionResult` wouldn't happen, which of course is very wrong.

But yeah, hidden allocations are bad. I'd also add that implicit casts are pretty bad much of the time too.
