### ISSUE TITLE
CreateSetComparer methods for HashSet<> and SortedSet<>

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/corefx#4964]
This methods exists in the .NET Framework: [here](https://msdn.microsoft.com/en-us/library/bb335475.aspx) and [here](https://msdn.microsoft.com/en-us/library/dd321103.aspx).

I know, this methods has a some issues and I want report about it and, probably, try to fix it.

Are these methods still supported? If not, class [SortedSetEqualityComparer<T>](https://github.com/dotnet/corefx/blob/d43a8a92151b2af9073257bd3c40160dd7404927/src/System.Collections/src/System/Collections/Generic/SortedSet.cs#L2419) should be removed.

**Comment by ianhays** [comment]
The design notes say ```NetCore Design Notes: CreateSetComparer does not take into consideration the custom comparers pass to each of the sets.```. There is no mention of why they were left out. I was not here when that decision was made, but @stephentoub or @ericstj may know the reason.

I imagine the API was left out because it was decided that comparing HashSets or SortedSets isn't a frequent enough occurrence to justify the addition of a specialized function to get comparers for them. It may also just be that it was designated a low-priority item at the time with the intention of adding them back later.

**Comment by ianhays** [comment]
I removed these in #5764
