### ISSUE TITLE
UDP Socket.ConnectAsync result in  "An invalid argument was supplied Error Code:10022"

### ISSUE THREAD

**Issue by Suning79** [dotnet/corefx#4968]
For version RC1

A very simple call failed and throw exception  "An invalid argument was supplied Error Code:10022"
Repro:

```
var c = new UdpClient();
c.Client.ConnectAsync("114.114.114.114", 53).Wait();
```

It works with sync mode:

```
var c = new UdpClient();
c.Client.Connect("114.114.114.114", 53);
```

Let me know if it's not a bug

**Comment by davidsh** [comment]
@pgavlin @CIPop PTAL

**Comment by CIPop** [comment]
Thanks for reporting this @Suning79. I'm able to repro this and it appears to be a bug. 

```
     System.Net.Sockets.Tests.UdpClientTest.UdpClient_ConnectAsync_Success [FAIL]
        System.Net.Sockets.SocketException : An invalid argument was supplied
        Stack Trace:
           S:\c1\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(6029,0): at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)
           S:\c1\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(5848,0): at System.Net.Sockets.Socket.DoDnsCallback(IAsyncResult result, MultipleAddressConnectAsyncResult context)
           S:\c1\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(2419,0): at System.Net.Sockets.Socket.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
           S:\c1\src\System.Net.Sockets\src\System\Net\Sockets\SocketTaskExtensions.cs(62,0): at System.Net.Sockets.SocketTaskExtensions.<>c.<ConnectAsync>b__5_0(String targetHost, Int32 targetPort, AsyncCallback callback, Object state)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
              at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
           S:\c1\src\System.Net.Sockets\src\System\Net\Sockets\SocketTaskExtensions.cs(61,0): at System.Net.Sockets.SocketTaskExtensions.ConnectAsync(Socket socket, String host, Int32 port)
           S:\c1\src\System.Net.Sockets.Legacy\tests\FunctionalTests\UdpClientTest.cs(62,0): at System.Net.Sockets.Tests.UdpClientTest.UdpClient_ConnectAsync_Success()
```

I've verified that the following code doesn't throw on .Net Desktop:

```C#
            var c = new UdpClient();
            IAsyncResult ret = c.Client.BeginConnect("114.114.114.114", 53, null, null);
            ret.AsyncWaitHandle.WaitOne();
            c.Client.EndConnect(ret);
```

**Comment by stephentoub** [comment]
There's still a bug here, e.g. this code:
```C#
new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp).ConnectAsync("114.114.114.114", 53).Wait();
```
throws in corefx, whereas the equivalent with BeginConnect/EndConnect does not on the full framework.

The problem appears to be due to a change that was made when porting this:
http://referencesource.microsoft.com/#System/net/System/Net/Sockets/Socket.cs,2825
to this:
https://github.com/dotnet/corefx/blob/c2a6a128a6d2cdbad3a8be663d027152ca9d63bc/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L2299

With the full framework, that call to CanUseConnectEx will return false for a SocketType.Dgram socket:
http://referencesource.microsoft.com/#System/net/System/Net/Sockets/Socket.cs,59a261c980f74684
but in corefx the code path is behaving as if CanUseConnectEx always returns true.

**Comment by CIPop** [comment]
@himadrisarkar @davidsh I tried this on Desktop and Core and found the following:

* Calling Socket.Connect works on both Desktop and CoreFX
* Calling the APM or TPL implementations works only on Desktop 
* Calling `ConnectAsync(SocketEventArgs)` fails on both Desktop and CoreFX

The reason, as @stephentoub already found is that all async implementations on CoreFX call ConnectEx. 
Winsock [ConnectEx ](https://msdn.microsoft.com/en-us/library/windows/desktop/ms737606(v=vs.85).aspx) will not work with connectionless protocols such as UDP.

There are two problems:
1. The APM/TPL implementation should work the same in both CoreFX and Desktop: the code should detect the connectionless protocol and switch to call the synchronous WinSock connect instead (which in this case is not an I/O operation, it just binds the socket to a remote address).
2. The Desktop MSDN documentation or implementation has a bug: From https://msdn.microsoft.com/en-us/library/bb538102(v=vs.110).aspx:

> If you are using a connectionless protocol such as UDP, you do not have to call ConnectAsync before sending and receiving data. You can use SendToAsync and ReceiveFromAsync to communicate with a remote host. If you do call ConnectAsync, any datagrams that arrive from an address other than the specified default will be discarded. If you want to change the default remote host, call the ConnectAsync method again with the desired endpoint.

What actually happens if `ConnectAsync` is called is that `SocketEventArgs.SocketError` will be set to `InvalidArgument` and a following `SendAsync` will fail.

It's clear that we should fix 1. What do you think about fixing 2 in both CoreFX and Desktop?

**Comment by davidsh** [comment]
>It's clear that we should fix 1.

Agreed

>What do you think about fixing 2 in both CoreFX and Desktop?

We should fix for CoreFx.  We can consider for Desktop after we review app-compat.

**Comment by CIPop** [comment]
Moving post RTM as it doesn't meet the bar.

Until this is fixed, developers have the following workarounds:
1. Use the `SendAsync()` API that requires an `IPEndPoint` or `hostname / port`.
2. Use `UdpClient.Client.Connect` to bind to a remote endpoint instead of any of the Begin/End or Task async APIs.
