### ISSUE TITLE
System.Reflection.Assembly contract contains internal constructor causing friction for testing

### ISSUE THREAD

**Issue by divega** [dotnet/corefx#4997]
The contract for `System.Reflection.Assembly` contains a internal parameter-less constructor, although most implementations (all as far as I can see) have it protected. 

The internal constructor blocks compiling a type that derives from Assembly, which would be useful thing to create for testing purposes. This forces you to take different testing strategies depending on whether the tests targets .NET Core (you have to use Moq) or desktop .NET (then you can't use Moq because of `ISerializable` but you can easily create a test double that derives from Assembly). 

The internal constructor in the contract may very well be intentional and I think this is a very advanced scenario, but I wanted to raise it mainly because:
1. It would be nice if you could use a uniform and simple testing strategy for both .NET Core and desktop .NET.
2. The compilation error is very annoying and obscure: It is even hard to understand what is going on by looking at the source code of the implementation. As far I am aware you have to reverse engineer the ref assembly to see the internal constructor.
3. This might actually be a leftover. 

See https://github.com/aspnet/EntityFramework/pull/4084 where we hit this.

**Comment by weshaggard** [comment]
cc @nguerrera 

All the reflection classes, Assembly, TypeInfo, MemberInfo, etc intentionally block extensibility by making the constructors internal. This is because we cannot easily support a consistent extensible reflection surface area across all the different platforms (.NET Core, .NET Native, .NET Framework) so we block it. 

This is something we will likely revisit again in the future but it isn't high on our priority list right now.

**Comment by karelz** [comment]
Should be fixed in .NET Core 2.0 / .NET Standard 2.0
