### ISSUE TITLE
Bug in creating extension method of System.Reflection.MemberInfo

### ISSUE THREAD

**Issue by ihildebrandt** [dotnet/corefx#5031]
I ran into this while trying to port code from 4.5 to dnxcore50. The build succeeds with dnx451 but fails in dnxcore50. 

Creating an extension method called `GetCustomAttributes<TAttribute>` causes the following error: 

```
D:\Dev\dnxcore50-extensionmethod-bug\MemberInfoExtensions.cs(11,31): DNXCore,Version=v5.0 error CS0411: The type arguments for method 'MemberInfoExtensions.GetCustomAttributes<TAttribute>(MemberInfo, Func<TAttribute, bool>, bool)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
```

I attempted to reproduce the error with extension methods of other classes following a similar pattern but wasn't able to. A simple, reproduction of the bug can be found here: https://github.com/ihildebrandt/dnxcore50-extensionmethod-bug

**Comment by mellinoe** [comment]
I'm pretty sure this is because you are not referencing System.Reflection.Extensions in your project, which is the type that contains the CustomAttributesExtensions class that has the extension method you are trying to call (`GetCustomAttributes(this MemberInfo element, Type attributeType, bool inherit)`). The error seems weird because it is trying to bind back to the method you are defining (it has the same name and is applicable to the same type). Add a reference to System.Reflection.Extensions in your project and it should work.

**Comment by ihildebrandt** [comment]
You are correct, didn't realize that had been moved into a separate assembly. Thanks.
