### ISSUE TITLE
unsafe struct with fixed byte array runtime error

### ISSUE THREAD

**Issue by jageall** [dotnet/corefx#5068]
If i create an unsafe struct with an explicit layout and add a fixed byte array to access the data in a lib targeting dotnet5.4, and then try to access that struct in a unit test it compiles ok, but I get a runtime error.  The unit test lib target dnxcore50 as per the instructions on the xunit site.  If i try and access via a method in a third lib also targeting dotnet5.4 it works fine.

I have a small repo containing a reproduction of the issue here https://github.com/jageall/DNXRuntimeIssueWithFIxedByteArray

if this behaviour is by design I would expect a compile time error, not a runtime error

**Comment by jageall** [comment]
is this the correct repository for this issue or should it be somewhere else?

**Comment by gkhanna79** [comment]
@yizhang82 Can you please take a look?

**Comment by jageall** [comment]
any update on this yet?

**Comment by yizhang82** [comment]
@jageall thanks for reporting the issue. I'm still investigating but so far this does not look like a runtime issue. 

This is what I'm getting at runtime:

    FixedIssue.Class1.Test [FAIL]
      System.MissingFieldException : Field not found: 'ClassLibrary1.RuntimeIssue.Bytes'.
      Stack Trace:
           at FixedIssue.Class1.Test()

The reason is that the generated IL from the compiler is incorrect and refers to a uint8* field that does not exist. 

  IL_001b:  ldfld      uint8* [ClassLibrary1]ClassLibrary1.RuntimeIssue::Bytes
  IL_0020:  ldind.u1

The bytes field is not a uint8* but rather a struct that the C# compiler knows about. The correct code should look more like this:

  IL_000b:  ldflda     valuetype [ClassLibrary1]ClassLibrary1.Foo/'<Bytes>e__FixedBuffer' [ClassLibrary1]ClassLibrary1.Foo::Bytes
  IL_0010:  ldflda     uint8 [ClassLibrary1]ClassLibrary1.Foo/'<Bytes>e__FixedBuffer'::FixedElementField
  IL_0015:  conv.u
  IL_0016:  ldind.u1

So far this looks like a DNX configuration issue, UnitTest infrastructure or a C# compiler issue. Interestingly I couldn't repro this with VS 2015 Update 1. 

@jaredpar Does this issue look familiar to you? Otherwise I'll probably keep digging.

**Comment by joshfree** [comment]
Moving this issue to the CoreCLR repo --  https://github.com/dotnet/coreclr/issues/4854
