### ISSUE TITLE
HttpClient hangs on 206 Partial Content response until connection is closed by the server

### ISSUE THREAD

**Issue by cesarbs** [dotnet/corefx#5073]
Request:

    GET / HTTP/1.1
    Connection: Keep-Alive
    Accept-Encoding: gzip, deflate
    Range: bytes=0-10
    Host: localhost:8080

Response:

    HTTP/1.1 206 Partial Content
    Content-Length: 100
    Content-Length: 11
    Content-Range: bytes 0-10/100
    Accept-Ranges: bytes
    
    <...content...>

Code:

    var request = new HttpRequestMessage(new HttpMethod("GET"), "http://localhost:8080");
    request.Headers.Add("Range", "bytes=0-10");
    var response = await httpClient.SendAsync(request);

Expected:

`response` should be available as soon as 11 bytes are read by `HttpClient`. **This is the behavior on desktop CLR**.

Actual:

Execution hangs on `SendAsync`. If I set `httpCompletionOption` to `ResponseHeadersRead`, it hangs later when I try to read `response.Content`.

If the connection is closed by the server, `SendAsync` completes and I can read `response.Content`.

I think it is waiting for the 100 bytes indicated by the first `Content-Length` header and ignoring the latter value (11).

**Comment by cesarbs** [comment]
cc @Tratcher

**Comment by Tratcher** [comment]
Why are there two content-length headers?

**Comment by davidsh** [comment]
I do not think that having 2 'Content-Length' response headers is RFC valid. So, the behavior will be undefined and could change on different platforms.

**Comment by cesarbs** [comment]
I hit this in a Web listener response caching test. The original response had 100 bytes. The second request asks for a range and then two Content-Length headers are sent.

**Comment by JonHanna** [comment]
This actually seems like pretty reasonable behaviour. Since the buggy server has said that it's sending 11 octets (in two ways) and that it's sending 100 octets, it's reasonable to deduce that it's probably going to send either 11 or 100 octets with know way to know which (if any) contradictory message was the correct one. In which case the best bet is to try to download 100 octets and stop downloading when you've either received them or the connection was closed.

**Comment by cesarbs** [comment]
I guess it's a WebListener caching bug then. My first thought was that the two headers were valid and the first one was saying "this is the total length of the thing" and the second "this is how much of it I'm sending you".

I'm going to retest this without `Content-Length: 100`.

**Comment by davidsh** [comment]
The HTTP RFC 2616 (old RFC) and RFC 7230 (recent RFC) only allow multiple HTTP headers with the same name iff. that header field is defined as a multi-value entity whole values can be represented as a comma separated list:
http://www.ietf.org/rfc/rfc7230.txt

>Section 3.2.2
A sender MUST NOT generate multiple header fields with the same field
name in a message unless either the entire field value for that
header field is defined as a comma-separated list [i.e., #(values)]
or the header field is a well-known exception (as noted below).

Since the 'Content-Length' cannot have multiple values as a comma separated list, it therefore cannot appear multiple times in the HTTP request or response.

**Comment by davidsh** [comment]
I will close this issue for now.  Please re-open a new issue if you discover new problems.
