### ISSUE TITLE
SslStream ReadAsync and WriteAsync never continues.

### ISSUE THREAD

**Issue by xanather** [dotnet/corefx#5077]
Calling "await ReadAsync" then calling "await WriteAsync" (while ReadAsync is still waiting) results in neither continuing ever.

I tested the exact same app with .NET Framework libraries and it works fine.

Using Windows 10 PRO x64, with DNX RC1 runtime.

**Comment by davidsh** [comment]
cc: @CIPop

**Comment by davidsh** [comment]
@xanather Please post a code sample of exactly how you are using the SslStream APIs.  For example, are you calling ReadAsync and WriteAsync from different threads? It seems you must be because code like this:

```c#
SslStream stream = new SslStream(...);
await ReadAsync(stream, ...);
await WriteAsync(stream, ...);
```c#

would never execute the WriteAsync until the ReadAsync was done.

**Comment by xanather** [comment]
First I create an SslStream
```C#
SslStream stream = new SslStream(someNetworkStream, ...);
```
Then I do normal authentication (does not matter if client or server)
```C#
stream.AuthenticateAsClientAsync(...)
```

Then I read and write on two seperate threads. I call ReadAsync first, which then waits for bytes to come in.
I then call WriteAsync on a seperate thread/task. The WriteAsync never goes through thus ReadAsync never occurs (if communicating to peer which processes requests and only replies after receiving bytes).

Just ensure ReadAsync is waiting and try WriteAsync's on the same sslStream, it won't go through.
This shouldn't be normal behavior, it works fine on .NET Framework.

**Comment by jageall** [comment]
I have seen this too, and I have seen it happen cross process so definitely different threads. Same OS and version as above, but also dev builds ( last one I checked was 1.0.0-rc2-16312)

**Comment by xanather** [comment]
Is it possible this can be looked at? It basically renders SslStream unusable

**Comment by xanather** [comment]
Is it possible this could get looked at?

**Comment by CIPop** [comment]
@xanather The tests at https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs#L111 are validating the described scenario.

If you are able to repro this, please share either an entire solution via a GitHub branch or OneDrive or a single-file application through https://gist.github.com/ with the simplest repro code that hits the issue.

**Comment by xanather** [comment]
@CIPop That is not the described scenario. The scenario is where WriteAsync will not write if a ReadAsync is pending on the same SslStream, that test does not seem to verify that.

I made a example project test https://github.com/xanather/SslStreamTest/tree/master/src/SslStreamTest

Direct link to source file: https://github.com/xanather/SslStreamTest/blob/master/src/SslStreamTest/Program.cs

**Comment by stephentoub** [comment]
@cipop, @davidsh, this is related to the offline conversation we were just having about how SslStream no longer provides overrides of the various async operations.  As a result, on CoreCLR it ends up using the base Stream's default implementation, which for historical reasons serializes concurrent operations via synchronous blocking.  https://github.com/dotnet/coreclr/issues/2682 should address this by changing that serialization to be asynchronous instead of synchronous, but that's more of a stop-gap for this particular issue than a complete fix; while we should do that coreclr change regardless, the better fix for this particular issue is to reinstate SslStream's implementation of the various async overrides.

**Comment by davidsh** [comment]
@stephentoub Are you talking about this sub-item in #3114?

>Provide TPL Stream overrides for SslStream.

Can you remind me of what exactly this is?  Is it just changing the internal implementation?  Or is this adding new public API methods?

**Comment by stephentoub** [comment]
> Are you talking about this sub-item in #3114?

Yup.

> Can you remind me of what exactly this is?

In the full framework, SslStream overrides the various Begin/EndXx methods, e.g.
http://referencesource.microsoft.com/#System/net/System/Net/SecureProtocols/SslStream.cs,467
In corefx, there are no such overrides for XxAsync, so the base Stream implementations end up being used.

**Comment by CIPop** [comment]
Thanks @xanather. I was able to repro and I'll add a similar test to the FunctionalTests set.

> As a result, on CoreCLR it ends up using the base Stream's default implementation, which for historical reasons serializes concurrent operations via synchronous blocking.

@stephentoub While I agree we should have true Async APIs for SslStream, this behavior is unexpected: a TPL async API should never block in the synchronous path. 

Among other things, I'm investigating why the tests using the in-memory stream didn't catch this issue even if ReadAsync is placed before WriteAsync.

**Comment by stephentoub** [comment]
> this behavior is unexpected

Hence the PR I already submitted to CoreCLR.

**Comment by stephentoub** [comment]
Actually, I misspoke. https://github.com/dotnet/coreclr/pull/2682 will not work around this issue.  It'll prevent the WriteAsync call in the repro from synchronously blocking (the method will return a Task immediately), but due to the serialization of operations provided by the base clsss (which it must do), the ReadAsync call that was issued first will still not complete until the WriteAsync call completes asynchronously, and the WriteAsync won't complete asynchronously until the ReadAsync completes and gives up the semaphore that allows the WriteAsync operation to continue.  The solution here is for SslStream to properly override these methods as it was in the full framework.
