### ISSUE TITLE
Proposal: System.Text.RegularExpressions.RegexRunner to become a public type

### ISSUE THREAD

**Issue by mjsabby** [dotnet/corefx#5079]
Today the RegexRunner class is internal in CoreFX, because the Regex.CompileToAssembly functionality (the historically main entry point) that generates code inheriting from this class is not available in CoreFX.

The CompileToAssembly API is not the only way to create such assemblies though, one could write code that inherits from this class and all the functionality required by RegexRunner to function properly is available in CoreFX and is used by other internal classes.

The proposal is to make the RegexRunner class public, allowing scenarios where people are willing to generate code using a tool other than Regex.CompileToAssembly that targets CoreFX to be able to do so.

In fact, it is also entirely possible that a developer could use Regex.CompileToAssembly in a build step (where they may have access to the full framework) and generate an assembly that initially (i.e. the output of CompileToAssembly) compiles against mscorlib, but further processing could result in the assembly being compiled against the System.Runtime contract assemblies.

This brings a well-tested Regex interpreter implementation, the same one that is used in all other scenarios except precompilation to this scenario as well. The precompilation scenario is compelling (to us) for working set and startup performance reasons.

**Comment by mjsabby** [comment]
cc @weshaggard

**Comment by Priya91** [comment]
Proposed API Changes:

![image](https://cloud.githubusercontent.com/assets/7853870/13972631/9b0c7fea-f057-11e5-8ec5-393018fd9a87.png)
![image](https://cloud.githubusercontent.com/assets/7853870/13972648/b666bc92-f057-11e5-9fe9-536f40e1ce65.png)

cc @justinvp @mjsabby @terrajobst

**Comment by terrajobst** [comment]
In my opinion, the direction to allow built-time code generation over runtime code generation for regexes is good an in alignment with what we want to do in general. It's just a question of whether we believe we should expose the type as proposed or whether we should spend more time designing this extension point.

@weshaggard @KrzysztofCwalina @stephentoub Thoughts?

A meaningful end-to-end validation would be whether we could use this API to generate code during compilation using [Roslyn's generator API](https://github.com/dotnet/roslyn/issues/637). @mattwar

**Comment by justinvp** [comment]
I like the protected constructor design. I still think it'd be worth considering switching to `Func<RegexRunner>` instead of adding back `RegexRunnerFactory` as it would be trivial to adapt `Func<RegexRunner>` to `RegexRunnerFactory` within the desktop codebase (desktop and corefx implementations have already diverged a bit).

Remind me: Would we have to wait to add the protected constructor to .NET Core until it is added to some future release of the desktop framework, since `Regex` is an existing type?

If so, could we workaround this point-in-time limitation by introducing a new type in the inheritance hierarchy (e.g. `public abstract CompiledRegex : Regex`) that would have the protected constructor that compiled regexes would subclass (e.g. `public class MyCompiledEmailRegex : CompiledRegex`) that could be added to a desktop framework targeting pack?
