### ISSUE TITLE
Private derived types for CryptographicException

### ISSUE THREAD

**Issue by tushargupta51** [dotnet/corefx#5097]
We have tests that tries to sign some data using an asymmetric key with only public components. The action is supposed to fail and we compare the exception types to make sure that it failed with the right exception. Same tests run on net desktop and .net core.

For .net desktop, it throws System.Security.CryptographicException and it works fine. Though, when I run the tests on .net core, it throws a specific exception: Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException. Our test framework does not make use of Assert.. so can't use Assert.ThrowAny<>.

I looked at the PRs and issues that introduced the private WindowsCryptographicException and OpenSslCryptographicException but don't understand why they are left private. Why not make those publicly accessible? Is there such a plan in future?

@bartonjs

**Comment by bartonjs** [comment]
@tushargupta51 They exist as different types because Windows Crypto and OpenSsl build error states in different ways, so each of them are responsible for handling their platform-specific message loading.  They got introduced due to a shortcoming in CryptographicException's constructors: You can set the message, or the error code, but not both.

The reasons that they're not public:
* We don't think it's a good idea for people to write `catch (WindowsCryptographicException)`, but rather just `catch (CryptographicException)`
* In future versions we may seek to eliminate the derived types, and just go back to using CryptographicException directly.
* The libraries that could really expose them (Crypto.OpenSsl and Crypto.Cng) are too late... they need to already be thrown out of Crypto.Algorithms and Crypto.Encoding.  And those libraries' goal is platform-agnostic surface area.

Rather than check `ex.GetType() == typeof(CryptographicException)`, to work correctly across both full framework and core you could do either `ex is CryptographicException` or `typeof(CryptographicException).IsAssignableFrom(ex.GetType().GetTypeInfo())`.

Yeah, I know it's a bit of a pain... when we first made the change we were surprised to find that we needed to go update all of our tests :smile:.

**Comment by tushargupta51** [comment]
@bartonjs Thanks for the explanation :) I added Assert.ThrowsAny<> finally, this makes these tests look odd ones out but that is the simplest solution to go for at the moment. I opened the issue as more of a question, feel free to close it.

**Comment by bartonjs** [comment]
@tushargupta51 No worries, I'm glad for the external validation that the rationale makes sense.  If anything else feels a bit off to you, feel encouraged to speak up!
