### ISSUE TITLE
FileStream opens in async mode by default

### ISSUE THREAD

**Issue by ayende** [dotnet/corefx#5159]
The following code:

     var fs = new FileStream("vogavoa", FileMode.OpenOrCreate, FileAccess.Write);
     Console.WriteLine(fs.IsAsync);

Returns false for full .net and true for coreclr.

shouldn't the behavior be the same?

**Comment by JonHanna** [comment]
Dotnet core tends to consider asynchronous the normal (or indeed, sometimes the only) way to deal with file operations. As such `true` is the obvious default.

The older .Net frameworks, in contrast, where first written for at a time when using streams with `IsAsync` being `true` well meant the more convoluted use of `BeginRead`/`EndRead` and `BeginWrite`/`EndWrite` rather than `ReadAsync` and `WriteAsync` and so prior to version 4.5 it made more sense to default to `false`, and with 4.5 (and 4.6 later) being an in-place replacement for 4.0 it made sense to keep that default in the name of compatibility. (It would have had a strong compatibility argument even without that, as even SxS upgrade would have been a less prominent change in many ways than DNX brings).

As such having the same behaviour in the two would be very questionable.

**Comment by ayende** [comment]
However, this can easily break code that rely on it.

     var fs = new FileStream(path, FileMode.Create);
     Win32NativeFileMethods.WriteFile(fs.SafeFileHandle, ptr, remaining, out written, null);      

Now you have an invalid parameter, because the handle is async, and we didn't pass an overlap there.
That is a very subtle bug to figure out when you move the code

**Comment by stephentoub** [comment]
This was an explicit design change for .NET Core (whether it was a good one may still be open for debate).  @ericstj can comment further.

**Comment by ianhays** [comment]
Luckily it would be <i>fairly</i> easy to switch back to defaulting to synchronous FileStreams if we decide to go that route, but I'm not sure it's worth it just for the back-compat. Particularly since we'd want to maintain cross-compat by having Unix use the same default behavior.

Are there more downsides to using the overlapped FileStream as the default? The benefits of it are clear (async operations are faster since they're performing them on an overlapped stream in Windows), but the non-compat costs aren't clear to me.

**Comment by ericstj** [comment]
The change was made because it improved perf on the common case: async is slightly faster and scale out is much better.  Using async with a synchronous handle will burn a thread for every concurrent IO, using many more threadpool threads and resources that folks would expect which is one of the main driving factors behind the switch.  Sync operations are slightly slower, though usually this is unnoticeable since the cost of the context switch is much smaller than the cost of the IO itself.  We still return synchronously if the OS completes synchronously, which it does a lot even for overlapped.  We did take a lot of measurements when we first made this change to ensure it wasn't going to degrade perf in the sync case.

We did know about the impact to folks using the handle.  We actually flow the sync state of the handle to other .NET APIs that take a file handle to mitigate this.  There isn't a good way for us to mitigate the case where someone is taking the handle out of the filestream and directly passing to a P-Invoke since managed code isn't involved in that exchange.  We could try to do something in the interop layer but that's incredibly hard to get right.  We do expose the IsAsync property and we recommend that folks consider this property whenever retrieving the handle of the stream.

I'll make sure that this difference is documented better.  @ayende can you point me to some of the places you looked for information about this and I'll see if I can get it doc'ed there?

**Comment by ayende** [comment]
What killed me really was that the error was invalid parameter from Win32.
After I ruled out all of the other parameters, it took me a while to
suspect the SafeFileHandle is wrong, and then I got to reading how you
opened the file.


*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ianhays** [comment]
I'm going to close this as the discussion looks to be over. Anyone feel free to re-open it in the future with any suggestions for places where we can improve the documentation :)
