### ISSUE TITLE
Replace hand-rolled tests for exceptions with xunit's Assert.Throws

### ISSUE THREAD

**Issue by jhendrixMSFT** [dotnet/corefx#516]
There is a lot of hand-rolled exception checking in various test code.  This should be refactored to use xunit's Assert.Throws method as it improves readability and can reduce possible bugs in test code.

For an example please see PR https://github.com/dotnet/corefx/pull/512

**Comment by Clockwork-Muse** [comment]
I can take this on, shouldn't be too bad.

**Comment by Clockwork-Muse** [comment]
Hmm.... at least some of the tests mentioned in the linked issue are situations where you'd want to invoke a `fail(...)`, which doesn't exist for xUnit (and the given pattern is the recommendation, apparently).
So some of them are expecting to _not_ throw an exception, essentially, and need to fail the test if certain conditions are met.

**Comment by Clockwork-Muse** [comment]
And some of them are using the pattern to pop messages if a test is failed (`System.Linq.Parallel` is what I'm looking at right now).  Similar messages should be popped by changing things to theories, etc.

**Comment by stephentoub** [comment]
Just FYI, I fixed this kind of thing for TPL Dataflow as part of overhauling those tests.  See PR #513.

**Comment by Clockwork-Muse** [comment]
@stephentoub - Thanks for letting us know.

**Comment by Clockwork-Muse** [comment]
@stephentoub , @jhendrixMSFT - 
Before I go too much farther, I was wondering what the, err, limit was on changes.  Because currently my changes seem to be looking like this:
https://github.com/Clockwork-Muse/corefx/commit/d4d2210126d951bae1cfd78f8668436d6c4aef32
https://github.com/Clockwork-Muse/corefx/commit/a0e4af8d0f2aae212f3a7ddb630aba974bcfbbc5

(My time so far has mostly been spent figuring out how failures were reported differently for various ways to write the tests, so things would be understandable and discoverable if/when that does happen)

**Comment by YingP99** [comment]
I've written a simple tool to transform try-catch to Assert.Throws (for certain patterns). It may not fix every case, but do save you a lot of typing time. I've not figured out how to share it.
Note: it uses Roslyn SynatxRewriter, and works on cs file (no need project or solution).

**Comment by Clockwork-Muse** [comment]
@YingP99 - Thanks!
Potentially, you could share a repository with the source for the tool (ie, place a link here), which could potentially include a download link.
Unfortunately in my case, I'm on 2013 Community, and haven't installed Roslyn, so I'm not sure I could use it?  Waiting for 2015 to actually be released...

**Comment by YingP99** [comment]
Actually I've handled that case too, and it's the result of running some tool.
For using "Roslyn', you don't need wait for VS2015. It's available as Nuget packages; but you do need install MSBuild 15.0 Preview. You can download it from VS2015 download site - http://www.visualstudio.com/en-us/downloads/visual-studio-2015-downloads-vs.
The code is less than 200 lines (power of Roslyn). Let ask around to find out how to share it.

**Comment by Clockwork-Muse** [comment]
@jhendrixMSFT - Why was this closed?  As I near as I know it's an outstanding issue.  I know I'm a bit slow, but I'm working on it!

**Comment by jhendrixMSFT** [comment]
@Clockwork-Muse oops sorry about that!  Shall I assign it to you?

**Comment by Clockwork-Muse** [comment]
Sure, thanks.I've taken a slight detour at the moment through all of `Linq.Parallel`, given the prevalence of the pattern there, but I'm planning or working everything eventually.



On Wed, Mar 11, 2015 at 3:30 PM -0700, "Joel Hendrix" <notifications@github.com> wrote:
@Clockwork-Muse oops sorry about that!  Shall I assign it to you?

---

**Comment by Clockwork-Muse** [comment]
@YingP99 - Looks like I need to eat a bit of crow - there's ~1800 entries for `Assert.False(true, ...)` (mostly for basic equality tests - `Systems.Collections.Specialized` has... issues).  Do you still have the re-writer available (and up-to-date for 2015 RC)?  Link to source on GitHub I could build, or to a OneDrive folder with a .exe would be fine.

**Comment by karelz** [comment]
@Clockwork-Muse are you still working on the issue?

**Comment by Clockwork-Muse** [comment]
@karelz - yes, when I notice something new has shown up.  Other than Tasks (which I've been working on untangling the inner test framework), I believe I corrected everything that was present at the last time I was committing for this.  Since then, some new libraries, as well as use of this pattern for fail messages have shown up.

So, this tends to be an ongoing task.  You can close it if you want, since I'll keep watching for it anyways.  Probably can spin through everything current by this weekend.

**Comment by karelz** [comment]
CLosing per above comment. Thanks @Clockwork-Muse !
