### ISSUE TITLE
Windows 10: x509 GetECDsa*Key fails on new keys (secp224r1, brainpool, etc)

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#5167]
This likely applies to any curve which was added in Windows 10.

The data that DecodeECDsaPublicKey (https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Windows/X509Pal.PublicKey.cs#L64) passes into CngKey.Import ends up failing (and throwing) for curves that are not { secp256r1, secp384r1, secp521r1 }.

**Comment by joshfree** [comment]
related https://github.com/dotnet/corefx/issues/7688

**Comment by steveharter** [comment]
This should work correctly now as support for all platform curves was recently added. We could add a test for new curve types; these test should reference net463 or detect if curves are support

**Comment by joshfree** [comment]
@steveharter if you can confirm this works then please close this out or repurpose it to a 1.1 test bug as appropriate.

**Comment by steveharter** [comment]
I believe there is an issue with x509 code support w.r.t. using the new EC Curves; still researching but when importing an ecdsa key the curve name apparently needs to be specified, and that information is not being passed from the x509 side to CngKey.Import API because that API was not modified to accept the curve name. In addition, the certificate class on the x509 side does not expose the curve name.

**Comment by steveharter** [comment]
Note a certificate can contain either a curve name or explicit curve parameters – both should be supported.
