### ISSUE TITLE
Certificate validation fails on osx 10.11

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#5173]
Moved from https://github.com/dotnet/corefx/issues/4593#issuecomment-166719300

-----
I am not able to connect from OS X 10.11 to **SQL Azure** when using `Encrypt=true` in the connection string.

```
System.Data.SqlClient.SqlException : A connection was successfully established with the server, 
but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - 
An internal exception was caught)
---- System.Security.Authentication.AuthenticationException : The remote certificate is invalid 
according to the validation procedure.
```
[Full stack trace here](https://gist.github.com/natemcmaster/d4816c77789a08f78a41)

dnx 1.0.0-rc2-16348 coreclr
System.Data.SqlClient 4.0.0-rc2-23622

**Comment by bartonjs** [comment]
The root cert store that OpenSSL reads on OS X is empty by default.  You'll likely need to add the root cert to `X509Store(StoreName.Root, StoreLocation.CurrentUser)`.

Alternatively, you could fix it at the system level in a manner such as http://andatche.com/blog/2012/02/fixing-ssl-ca-certificates-with-openssl-from-macports/

**Comment by kkurni** [comment]
I try to reproed this on my ubuntu machine to connect to sql azure, and I didn't see any failure. 
Probably this is related with SSL handshake in OSX.

(Still waiting for results in OSX)

```
public void TestConnectionString(string connstr)
        {
            using (var conn = new SqlConnection(connstr))
            {
                conn.Open();
                
                var cmd = new SqlCommand("select @@Version", conn);

                using (var reader = cmd.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        Console.WriteLine(reader.GetString(0));
                    }
                }
                
            }
        }
```

**Comment by natemcmaster** [comment]
As @bartonjs suggests, this may just be an issue with how CoreCLR finds CAs on OSX. Specifying `TrustServerCertificate=True` in the connection string fixes the issue

**Comment by kkurni** [comment]
The reason why TrustServerCertificate=true works, it because it will trust whatever certificate.
https://github.com/dotnet/corefx/blob/5ddb1d4db82761091ca312a573413a2ca1bb2053/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNITcpHandle.cs#L215

We still need to fix if TrustServerCertificate=false (default value) in osx.

It potentially error in this section.
https://github.com/dotnet/corefx/blob/93797cd31234db71ea48a809f033ec46bfc0e55e/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNICommon.cs#L77-L124

**Comment by kkurni** [comment]
An update from Natemcmaster : 
He tried using the cert from curl-ca-bundle from macports by replacing /etc/openssl/cert.pem (build in OS X ca bundle) and /usr/local/etc/openssl/cert.pem (Homebrew’s OS X ca bundle.) 

But Still getting the error.

**Comment by bartonjs** [comment]
Okay, it looks like Homebrew takes the root certs out of KeyChain and writes them to `/usr/local/etc/openssl/cert.pem`, but the problem is that OpenSSL (Homebrew) is built to load certs from `/usr/local/etc/openssl/certs/*`.  This would have Just Worked if they'd put it in the right directory, but I can probably work around this.

**Comment by bartonjs** [comment]
Ah, to date I've only supported the `X509_get_default_cert_dir` loading mechanism, Homebrew was making use of the `X509_get_default_cert_file` mechanism.  That's good, it means there's no magic required.

**Comment by kkurni** [comment]
That's good news :)
