### ISSUE TITLE
Add key value to KeyNotFoundException

### ISSUE THREAD

**Issue by cdie** [dotnet/corefx#5188]
It would be great if, for example, when dictionary throws KeyNotFoundException, we can have the searched key in the exception for some traces

**Comment by OtherCrashOverride** [comment]
For the record, I am still against arbitrary leaking of data as it presents security issues and is only useful in the specific case of the key being a string.  However, the current rational is: if you are already showing some leg, you may as well lift the kilt. I believe this issue is a duplicate, but I cant find it.

Related: #1187 #3025
Related: dotnet/coreclr#1311

**Comment by JonHanna** [comment]
One effect of this would be to make anything that calculates a key based on given key and just passes back exceptions give the wrong key value.

**Comment by MgSam** [comment]
> ...is only useful in the specific case of the key being a string.

This isn't true. Having a dedicated `Key` property on the exception could hold any type.

**Comment by cdie** [comment]
@MgSam That's what I thought, but it will need a new implementation of KeyNotFound exception with generics to avoid boxing/unboxing and dynamics

**Comment by MgSam** [comment]
I don't think boxing matters. If your application is throwing a KeyNotFoundException performance is already the least of your worries.

**Comment by OtherCrashOverride** [comment]
> Having a dedicated Key property on the exception could hold any type.

The issue is whether that has any useful value.  In the case of reference types (object) as keys, you can have two identical looking objects (same property/field values) but they will generate this exception because by default they are compared by reference, not value. This limits the usefulness of this to a subset of use cases.  Since its a subset, its better served by a try/catch pattern: be it a TryAdd method or a Try/Catch block.  Anything is better than blindly passing potentially sensitive information to arbitrary exception handlers.

This has been covered already in the pre-existing flamewars referenced.  Its not a productive use of anyone's time to have a new flamewar over.  If you passionately feel CoreCLR will go the way of Zune without this feature, I can respect your opinion so please extend the same courtesy with regard to mine.

**Comment by MgSam** [comment]
> ...they will generate this exception because by default they are compared by reference, not value

Only if you are putting types in a Dictionary that don't implement GetHashCode and Equals. But why would you possibly do something like that? The number of times that you actually want to key something off the reference and not the value is vanishingly small. The vast majority of the time the Key is meaningful.

I do agree the arguments about leaking sensitive data are largely the same as the other threads and it doesn't make a ton of sense to repeat them. That being said, most of your arguments in *this* thread are about how knowing the Key is not valuable information, which is demonstrably not true. 99% of the times I've seen a KeyNotFoundException if it had contained what the key actually was it would have saved a lot of debugging time.

Also- I think you should not be so sensitive about people disagreeing with your opinions. We're discussing features of an API, not religion or politics. :)

**Comment by JonHanna** [comment]
Consider:
```C#
public CourseList GetCourseList(Student student)
{
  return _courseCache[student.ID];
}
```

Currently this method would do the correct thing in the case of a `student` object being passed without a `CourseList` stored by its `ID` in the cache, vi⁊ throw a `KeyNotFoundException` with appropriate values for all of its properties.

After this proposed change it would do something wrong, vi⁊ throw a `KeyNotFoundException` with an incorrect value for its `Key` property.

**Comment by MgSam** [comment]
@JonHanna I'm not following. Why would the value for `Key` be incorrect?

Also, it seems Github turned one of your words into a non-English character. I'm guessing that wasn't your intention.

**Comment by cdie** [comment]
@JonHanna I also not understand. If keyNotFoundException had a Key property, it will be equals to student.ID, which is the information we want ...

**Comment by JonHanna** [comment]
No, the key to the public method was `student`. The caller need not even know that students have an `ID` field or property. The correct `Key` value for the exception would be `student` but the method has to be rewritten to either throw a new `KeyNotFoundException` with that as the `Key` or at least to throw a new `KeyNotFoundException` with no `Key` set.

**Comment by cdie** [comment]
@JonHanna  So your method is not correct in this case, if it retrieves information based on student.ID, the parameter should be an int, not a Student... 
What if a class inherits of Student and redefine ID to throws exception because this field is not acurate in this case ?

**Comment by JonHanna** [comment]
@cdie no, the method retrieves information based on a `Student` or throwing `KeyNotFoundException` if that `Student` isn't found. It just happens that the implementation of this, which the caller need not care about, is based on the `ID` which the caller need not care or know about.

> What if a class inherits of Student and redefine ID to throws exception because this field is not acurate in this case ?

What's to say `Student` isn't sealed or `ID` private?

**Comment by OtherCrashOverride** [comment]
> We're discussing features of an API, not religion or politics.

Actually, it is both religion and politics.  CoreCLR is ruled by the Windows religion and the politics of ASP.Net.  DNX and NuGet are perfect examples.  Downloading and executing code and scripts from unverified sources on the internet is a very nonsecular practice.

**Comment by MgSam** [comment]
@JonHanna That argument could apply to any exception. In fact, it applies to the whole concept of exception bubbling. You're *always* leaking internal implementation details when you throw an exception. Why should the user know or care that a Dictionary is acting as a cache of courses? Why is a KeyNotFoundException more appropriate than an InvalidOperationException?

**Comment by JonHanna** [comment]
@MgSam the premise of this issue is that when one receives a `KeyNotFoundException` it is valuable to have information from it about the key that was not found. If it doesn't matter that the `Key` property isn't necessarily going to be correct, then does it matter that currently there is no such property?

**Comment by jasonwilliams200OK** [comment]
Related https://github.com/dotnet/corefx/pull/185 and https://github.com/dotnet/coreclr/pull/1452.
The decision about `ToString()` can be found here: https://github.com/dotnet/corefx/pull/185#issuecomment-65754562.

**Comment by ellismg** [comment]
I think there are two concurrent discussions going on here, depending on how you interpret the phrase: "have the searched key in the exception".

One view is that we could add a public Key property, to KeyNotFoundException which gave you back the actual Key object we used when the lookup failed.

The other view is do something like calling `ToString()` on the Key object and including that text in the exception message.

As @jasonwilliams200OK points out, we've already done the latter in dotnet/coreclr#1452 after a great deal of discussion.

So I'd like us to focus the discussion instead of if there's value is having programmatic access to the actual key object that was used when the lookup failed.  It's hard for me to think of interesting uses of this data.  If you want to log some information, the message is there and has a stringified version of the key in the exception message.

**Comment by ianhays** [comment]
I'm closing this as the Key ToString is likely adequate for most scenarios and there hasn't been any discussion in a while.

**Comment by terrajobst** [comment]
[We already include the actual key](https://github.com/dotnet/corefx/pull/185) (by [calling key.ToString()](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableDictionary_2.HashBucket.cs#L157-L166)) when we encounter duplicates. We should do the same when the indexer throws `KeyNotFoundExceptions`. Otherwise [it looks dumb](https://twitter.com/darrel_miller/status/933028568204042240).
