### ISSUE TITLE
Add CancellationToken overloads to async methods in System.Net.Security 

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#5211]
Ref: #4732

**Comment by xanather** [comment]
This would be a much wanted feature. As it stands adding a timeout to NetworkStream's/SslStream's Async Read's/Write's is problematic as it stands.

For example:
http://stackoverflow.com/questions/15273752/how-to-cancel-networkstream-readasync-without-closing-stream
http://stackoverflow.com/questions/12421989/networkstream-readasync-with-a-cancellation-token-never-cancels

Most of the current solutions involve closing the Socket after a timeout is reached in order to interrupt the read/write. This actually violates the non thread-safe rules of TcpClient and NetworkStream. It also makes it impossible to continue using the socket if one wants to.

Having a timeout on Read's can be important when making requests to a server, if the client doesn't talk to the server after some time it should drop the connection to free resources otherwise it is very vulnerable to DoS attacks. It would be nice to implement such protections correctly in code without breaking threading rules.

**Comment by xanather** [comment]
Does this have any chance of getting implemented before RTM (in march)? Is there a reason why it was delayed/deferred in https://github.com/dotnet/corefx/issues/4732?

**Comment by Maxwe11** [comment]
Highly in favor of this too. Would be nice to see this in RTM :smile:

**Comment by davidsh** [comment]
We are still reviewing this but there are many high priority items to get done for RTM and we currently marked this for post-RTM.

**Comment by SidharthNabar** [comment]
@xanather and @Maxwe11 - Completely agree with the value of this feature. However, we are currently focused on stabilizing the current set of APIs in .NET Core, adding necessary test collateral/infrastructure support; and porting necessary APIs from .NET Framework to .NET Core. Adding new APIs is prioritized after that, and given our current resources, we are not confident of being able to deliver that before RTM. If things change, we would be happy to work on these before then!

**Comment by xanather** [comment]
Is there an update on this feature now that RTM release date has been delayed?

**Comment by davidsh** [comment]
There are no plans to address this until post RTM.

**Comment by xanather** [comment]
Any updates for this feature?

**Comment by xanather** [comment]
@davidsh @himadrisarkar @CIPop Here is a list of related recent issues that have appeared on corefx in the hopes that priority of this issue will increase.

https://github.com/dotnet/corefx/issues/9423
https://github.com/dotnet/corefx/issues/5749
https://github.com/dotnet/corefx/issues/9698

I am sure there are a few others that I have missed.

Is the .net cancellation model even possible on *nix? Has this been looked at?
Please investigate, these cancellation problems bubble up onto other API's which use .net sockets directly and makes shutdown cleanup difficult/hackish among other problems.

**Comment by CIPop** [comment]
Keeping this item to track the work required for System.Net.Security and #14308 for similar work in System.Net.Sockets.

The work requires following the API review process, implementation and tests and is probably medium-large in size.

**Comment by karelz** [comment]
Duplicate of #25206
It is happening.
