### ISSUE TITLE
System.Net GlobalLog.Assert* must call Debug.Assert even if nothing is listening for the ETW events

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#5265]
The original GlobalLog code was calling `Debug.Assert`:
http://referencesource.microsoft.com/#System/net/System/Net/_LoggingObject.cs,978

We need to fix the `GlobalLog.Assert*` as well as ensuring that the Assert is not conditioned by `GlobalLog.IsEnabled` when being called.

**Comment by CIPop** [comment]
/cc: @SidharthNabar @davidsh 

Assigning to @stephentoub as he's been helping us with GlobalLog optimization.

**Comment by stephentoub** [comment]
@cipop, the GlobalLog methods should not call Debug.Assert.  Doing so would require completely redesigning the mechanism so that the call sites don't allocate at all, and I have no plans to do that (you're of course welcome to).  My suggestion would be to add Debug.Assert calls at the call sites anywhere you actually want them; it's more ok for the Debug.Assert call sites to allocate because, unlike the GlobalLog.Assert methods, they're compiled away in release builds.

**Comment by stephentoub** [comment]
(And in terms of redesigning GlobalLog, if you actually did want to do so, my suggestion would be to look over every usage and come up with a common set of things that were traceable, then design a set of Assert* APIs with those sets of arguments, so that no work need happen at all at the call sites, e.g. no computing of hash codes, no boxing, no params array allocations, no string concatenation, etc.)

**Comment by CIPop** [comment]
@josguil @stephentoub /cc: @SidharthNabar 

We're talking about old code ported from Desktop. The plan is to first ensure the same behavior which means that we should add back all Asserts as they existed in the original code (otherwise there's risk that we'll end up with new bugs). 

Not having the proper Assert statements in place is a bug (what I'm tracking with this issue).

> (And in terms of redesigning GlobalLog

I completely agree and we appreciate your help in achieving a similar behavior by wrapping the calls with IsEnabled.

**Comment by stephentoub** [comment]
FYI, a quick search of the code base shows that there are:
- 282 calls to GlobalLog.Print
- 104 calls to GlobalLog.Assert*
- 54 calls to GlobalLog.Enter/Leave
- 5 calls to GlobalLog.Dump

Only the ~100 GlobalLog.Assert* calls are relevant here, if I'm understanding the concern correctly.  I see a few paths forward:

1. Add Debug.Assert calls at each of those ~100 call sites, e.g. instead of:
```C#
if (GlobalLog.IsEnabled() && (size == 0 || size > (data == null ? 0 : data.Length - offset)))
{
    GlobalLog.Assert("SecurityBuffer::.ctor", "'size' out of range.  [" + size + "]");
}
```
you'd have:
```C#
Debug.Assert(size > 0 && size <= (data == null ? 0 : data.Length - offset), "SecurityBuffer::.ctor", "'size' out of range.  [" + size + "]");
if (GlobalLog.IsEnabled() && (size == 0 || size > (data == null ? 0 : data.Length - offset)))
{
    GlobalLog.Assert("SecurityBuffer::.ctor", "'size' out of range.  [" + size + "]");
}
```
Obviously it adds more gook at the call sites, but it maintains the goal of limited additional overheads in release builds.

2. Re-design all of the GlobalLog.Assert* overloads to be non-allocating / fast when logging is disabled, per my comment above, e.g. instead of:
```C#
if (GlobalLog.IsEnabled() && (size == 0 || size > (data == null ? 0 : data.Length - offset)))
{
    GlobalLog.Assert("SecurityBuffer::.ctor", "'size' out of range.  [" + size + "]");
}
...
internal class GlobalLog
{
    public static void Assert(string message, string detailedMessage)
    {
        GlobalLog.Log.AssertFailed(message, detailedMessage);
    }
}
```
you'd have something like:
```C#
GlobalLog.Assert(size == 0 || size > (data == null ? 0 : data.Length - offset), "SecurityBuffer::.ctor", "'size' out of range.  [{0}]", size);
...
internal class GlobalLog
{
    public static void Assert(bool condition, string format, string detailedFormat, int arg0)
    {
        Debug.Assert(condition, format, detailedFormat, arg0);
        if (!condition)
        {
            var log = GlobalLog.Log;
            if (log.IsEnabled())
            {
                string message = string.Format(format, arg0);
                string detailedMessage = string.Format(detailedFormat, arg0);
                log.AssertFailed(message, detailedMessage);
            }
        }
    }
    ... // lots of other similar Assert overloads with varying parameters
        // that enable call sites to be cheap
}
```
Folks would need to be careful not to do anything expensive in Boolean condition argument and also avoid accidentally doing expensive things in the other arguments, like string concatenation.  We'd need to be very strict about what overloads of Assert are exposed.

If your goal is to do (2), someone with much more familiarly with the area and why certain things are being logged/asserted (e.g. @cipop, @josguil, etc.) should probably do that (e.g. it's not clear to me why we have release tracing for debug asserts meant to indicate programming errors).  If you'd like to go with (1) either forever or as a temporary stop-gap before (2) is available, I'd be happy to throw that together now... it'll mean more code churn, but if you view this as an important bug (e.g. because you actually expect these asserts to fail?), it might be reasonable.

Let me know which way you'd like to go, and I can either get started or re-assign.

**Comment by stephentoub** [comment]
@cipop, I just looked at the desktop source, and I see this on all of the GlobalLog.Assert methods:
```C#
[Conditional("DEBUG")]
```
Was it intentional that these were removed for corefx?  If those were meant to be there, that would explain a lot... we could put them back and remove all of the IsEnabled goop I added, since if these call sites are only compiled into debug builds, there's no performance concern.

**Comment by CIPop** [comment]
Enabling GlobalLog in ret builds was intentional. We have had multiple past external requests.

Regarding the proposed solutions, I think solution 1 is more immediate and resolves our functional/test requirement before RTM.
Solution 2 is the right thing to do not only for Assert but for all EventSource related tracing. Unfortunately that feature will have to wait given the high number of calls made not only to GlobalLog but to other System.Net EventSources.

If you agree, we can keep this item to track an implementation for Solution 1 before RTM. I can open another Future item to track the more involved analysis and fix for Solution 2.

**Comment by stephentoub** [comment]
> If you agree

Sure, that's fine.  I'll tackle (1) shortly and then will reassign this to track (2) when that's done.

As I mentioned to you offline, though, before I do (1), one thing it'd be helpful for you to check on is why GlobalLog.Assert* even needs to exist, i.e. why is it important to trace out to an EventSource cases where the assertion failed?  If these are meant to be the equivalent of Debug.Asserts, then they really shouldn't be failing at all, as a failure would indicate a programming error that shouldn't actual ship in production.  Rather than adding call sites to Debug.Assert, I'd much rather just replace call sites with Debug.Assert... that would simplify the code nicely.

**Comment by CIPop** [comment]
Thanks @stephentoub.
/cc @davidsh 

Looking at the original implementation I see that the code was actually trying to crash the process on GlobalLog.Assert using multiple methods:
http://referencesource.microsoft.com/#System/net/System/Net/_LoggingObject.cs,980

  1. `Debug.Assert()`
  2. `Debugger.Break()` which for some reason is backed up by a call to `Kernel32::DebuggerBreak()`

Point 2 made logging important as Assert() will display the text only for debug builds.

I'm not a very big fan of this way of crashing production code (we should instead rely on Exceptions). I think we should do the following:
  * Ensure that a debug build will fail regardless of logging enabled or not when a previous `GlobalLog.Assert` variant was called
  * Transform the Assert message in Critical ETW logs. 

The last part is interesting especially if we want to extend the calls to telemetry systems that would allow us or the developer to understand if the code is hitting any of the exceptional paths in production.

One example of code that is enforcing its contract via this pattern is https://github.com/dotnet/corefx/blob/ae3455097c0de6864f11b78df817286e3a7468e1/src/System.Net.Security/src/System/Net/SecureProtocols/SslStreamContext.cs#L15

**Comment by davidsh** [comment]
>Ensure that a debug build will fail regardless of logging enabled or not when a previous GlobalLog.Assert variant was called

We should make sure that "fail" doesn't mean FailFast. That crashes the process and leaves poor debugging information (as we have seen on the CI machines).  So, we should make sure there are Debug.WriteLine() and/or OutputDebugString() so that we have sufficent information prior to the Assert ending the process.

**Comment by stephentoub** [comment]
@CIPop, @davidsh, for the example you cited, what is it you want that to look like?  It's not currently doing any "fail"ing when logging is disabled.  You want a Debug.Assert added?  A Debug.WriteLine?  I'm not clear based on your responses what you want the (1) solution to look like.

**Comment by CIPop** [comment]
@stephentoub I think we should add a Debug.Assert to all places where GlobalLog.Assert* is used. We should _not_ remove the GlobalLog.Assert* calls.

I don't think we should have any Debug.WriteLine in production code: that is unnecessarily polluting the Debug window and will interfere with actual Debug.WriteLines that the developers will use.

**Comment by stephentoub** [comment]
Got it.

**Comment by stephentoub** [comment]
Implemented the temporary part (1) solution.  Reassigning to @CIPop for the remainder.

**Comment by CIPop** [comment]
Thanks @stephentoub !
