### ISSUE TITLE
Use the Azure Sql database benchmark infrastructure to stress test System.Data

### ISSUE THREAD

**Issue by clrjunkie** [dotnet/corefx#5296]
While System.Net.Sockets provides the same "completion port" interface for both Windows and Linux
The underlying implementation for Linux is radically different and is implemented using an epoll event loop. 

This is important to keep in mind since SqlClient or any other DB driver are the most important consumers of this Api.

I suggest using Azure Sql database benchmark infrastructure to do the stress test, preferably inside azure first, so timeout handling behavior can be observed.

https://azure.microsoft.com/en-us/documentation/articles/sql-database-benchmark-overview/#schema

**Comment by stephentoub** [comment]
@clrjunkie, I'm not understanding the problem... what's the issue / action-to-be-taken here?

**Comment by clrjunkie** [comment]
@stephentoub  Stress test SqlClient under Linux using Azure benchmark infrastructure.

**Comment by clrjunkie** [comment]
@stephentoub

How can this be not for RTM schedule??

All the performance tests in the project appear trivial and are done on localhost, what production grade confidence can we derive for these?

**Comment by stephentoub** [comment]
@clrjunkie, you're asking for a very specific set of tests to be run, without additional information about what testing is already being done.  There is separate testing being done that's not on GitHub because infrastructure for things like stress testing in CI doesn't exist yet.  I'll let @saurabh500 comment on any plans around this specific set of tests, but we can't build/run every test that anyone asks for.

**Comment by clrjunkie** [comment]
@stephentoub

> you're asking for a very specific set of tests to be built/run, without additional information about what testing is already being done. 

Because what "testing is already being done" is what I see included in the project, and these are by no means sufficient for release, looping on localhost is dev test at best.

>but we can't build/run every test that anyone asks for.

Sounds a bit cynical ... 

Anyway, the azure benchmark seems good for the task at hand, because it tests the most important integration Socket  + Database Driver.

If there is a better test plan for sockets than by all means..

**Comment by stephentoub** [comment]
> Because what "testing is already being done" is what I see included in the project

No, that's what I was pointing out: there is testing being done that's not on GitHub yet.

**Comment by CIPop** [comment]
@himadrisarkar @stephentoub I think this is a System.Net item, not a System.Data based on the title and original request from @clrjunkie.

**Comment by stephentoub** [comment]
> I think this is a System.Net item, not a System.Data based on the title and original request

Potentially.  I just labeled based on the clarification of desired outcome: "Stress test SqlClient under Linux using Azure benchmark infrastructure"

**Comment by clrjunkie** [comment]
I thought it was good approach to address socket issues affecting database connectivity first as RTM seemed just around the corner. Idealy, the socket api would be stress tested independent of any consumer in a physical LAN enviroment.

**Comment by CIPop** [comment]
@clrjunkie I agree with your observation. Our SocketsPerformance tests have been disabled with #3635 and, since then, the code got stale and has some build issues in CoreFX. I'll see if I can fix the build then move them in the OuterLoop category so that they can at least be executed on a private box using loopback. 

I'll leave this issue to track System.Data performance investigations and keep #3635 to track a way to enable SocketsPerformance tests.

As @stephentoub mentioned, we are running these tests in a private environment using the old branch. It'll take some time to design and build a more complicated environment as well as better simulation tests available publicly (tracking that with #9048, post-RTM).

**Comment by karelz** [comment]
We're thinking about general stress strategy for System.Data. This is likely not to be the approach we take.
We need first rich functional test bed in the area, before we are ready to move on to stress testing.

**Comment by karelz** [comment]
That said, if anyone wants to do that we will be happy to take the benefits.

**Comment by clrjunkie** [comment]
@karlz Why this is likely not to be the approach you take for stress testing and how will anyone be aware of this if the issue is closed?

**Comment by karelz** [comment]
> Why this is likely not to be the approach you take for stress testing

@YoungGah's team (System.Data) doesn't think this is best approach. They plan to reuse the stress infra from full .NET Framework (after modification).

> how will anyone be aware of this if the issue is closed?

Which issue do you think needs to be tracked?
I think it makes sense to track: "Add more System.Data functional tests", and/or "Create System.Data stress test infra". Using Azure SQL Benchmark infra is a potential solution to the latter one (assuming someone wants to pick it up).

**Comment by clrjunkie** [comment]
@karelz I suggest you rename this issue or reference it in a newly created it issue (or an existing applicable issue) rather than simply closing it, since the fundamental problem for which the suggestion was modified remains  – System.Data did not undergo stress test, which is important enough to be considered as an open issue.

**Comment by karelz** [comment]
@clrjunkie I don't think this issue is well structured for the rename to make sense at this moment.

Also I believe we mix up things here: "Data did not undergo stress test" vs. "Add stress test infra for Data" are two different things.
IMO the former makes sense to track only if it means such infra/test bed exists, it is tracking an activity, not code deficiency. BTW: For context, we do have some level of (internal) general stress testing and that runs on Data test assets.
The latter makes more sense, however personally, I don't think tracking such issue brings much value to the project at this point (we could as well go and file 100-something of specific "add stress / perf testing for area X", which would be counter-productive).
What makes much more sense is creating issue "Increase Data test coverage" (ideally with current covergae %), given that we have test gap there. Once that issue is fixed, it will be a good time to file "Add stress tests" and "Add perf tests". And later on maybe even "Improve stress testing with end-to-end scenarios", etc.

Anyway, just my 2 cents. If you insist on creating the latter one, go ahead, I can live with it :).
