### ISSUE TITLE
Rename constant NET_NATIVE to netcore50

### ISSUE THREAD

**Issue by venkat-raman251** [dotnet/corefx#5315]
This is a tracking issue to rename this constant to follow our naming conventions.

**Comment by mellinoe** [comment]
I think I've also seen "NETNATIVE" (without the underscore) in some projects as well. Some of them might have snuck into corefx during porting in the past month

**Comment by mellinoe** [comment]
@weshaggard @venkat-raman251 There are still some instances of `NET_NATIVE` around the repo. I'm wondering if `netcore50` is still the thing that we are using?

**Comment by weshaggard** [comment]
We should use the guidance at https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/project-guidelines.md#define-naming-convention and clean-up the remaining projects to make them consistent.

**Comment by karelz** [comment]
@weshaggard are you working on it? (it's assigned to you)
Is it still actionable?

**Comment by weshaggard** [comment]
I'm not working on this. It is a clean-up item I've not looked through the source recently to see how pervasive it is currently. It is probably worth dividing it into new issues and have the owners of the libraries look into it and decided to violate our guidelines or clean it up.

**Comment by karelz** [comment]
I would love to see clear guidance "this is what has to happen". Then, we can justify "up for grabs".
Is it unclear if/what exactly we would do? Do we really need area owners to chime in? If yes, why? (hypothetical example is fine)

**Comment by weshaggard** [comment]
When we did a large code dump during the porting exercises there was a lot of code that used the define NET_NATIVE (https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=NET_NATIVE) instead of fixing that as part of the code dump we filed this tracking issue to clean these defines up to make them match our guidelines https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/project-guidelines.md#define-naming-convention. So this issue is about updating the defines in those source files to match the guidelines. The defines should match the build configuration. 

Looks like most of the projects still using NET_NATIVE are confined to Serialization and XML so we could get those owners to clean-up the source.

**Comment by karelz** [comment]
After offline chat with @weshaggard:
It turns out that some NET_NATIVE ifdef'd code will likely be targeting .NET Native (and not CoreCLR in UWP for F5), while some will be general UWP (not .NET Native specific).
Currently we do not have great way to test in UWP (.NET Native or CoreCLR for F5) - that work is in progress.

If/when anyone wants to pick up the work, please ping us - @weshaggard can provide more details and guidance in such case.
The work will likely be a little bit involved (at least on the decision side).

**Comment by stephentoub** [comment]
NET_NATIVE no longer shows up anywhere in corefx.
