### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by Bhaal22** [dotnet/corefx#535]
Hi,

Sorry if this is not the correct place to speak about that particular subject.
I was wondering if it could be a good idea to have exception specification at compile time to be sure when we use an API that we can catch a particular exception or not. 
It is a bit frustrating in .net when using external APIs that we do not know some methods are throwing which exceptions.

Thank you for your work.

**Comment by xanather** [comment]
What you are talking about is check exceptions (like what Java has). With Java you have to explicitly handle all exceptions for methods that cause them. It was a design decision to not have check methods in C#. Many methods do however say which exceptions may or may not be thrown in its intellisense descriptions.

I'm just curious what you find frustrating, in some ways I think not requiring checked exceptions is beneficial because it reduces the amount of useless try catch sections. Try only catching exceptions when there is a time when you need to handle it, otherwise let the application crash like it should and investigate why its crashing (basic testing will iron out all the main exceptions you need to handle for most applications).

**Comment by Bhaal22** [comment]
Hi,

Yes, I completely understand the design decision to not explicitely catch thrown exceptions by underlying calls. 
What I ask is a way to describe at language level that methods throws exceptions or not and not just rely on comments in Intellisense.
Maybe just a compile time warning or something like that.
If I use some APIs where developer does not maintain documentation (and it is often the case), I have no choice doing a lobal try / catch on top class Exception.
Was just an idea.

**Comment by xanather** [comment]
Usually a global try / catch exception is a bad practice, I think you should just avoid using it then handle exceptions when you actually need to. I do see what you mean though, the compiler should be able to infer what possible exceptions a method should through. However even if it did display this information I feel that manually handling all of them would still be a bad idea.

**Comment by Bhaal22** [comment]
Sure I completely agree with you.
And yes a compiler inference would be very interesting.

**Comment by mikedn** [comment]
This is a language/compiler issue, it should be in the Roslyn repository.

Personally I don't think that such a feature is worth the trouble. The very same people who don't bother documenting their code can also decorate their methods with "throws Exception" just to silence the compiler complaints.

**Comment by sharwell** [comment]
> The very same people who don't bother documenting their code can also decorate their methods with "throws Exception" just to silence the compiler complaints.

And the ones that *do* document their code now have more work to do for no benefit. This feature makes things easier only for people who are doing things the wrong way, and harder for everyone else.

**Comment by weshaggard** [comment]
Thanks @Bhaal22 for opening the discussion but as @mikedn this is more of a language discussion and is better suited for the Roslyn repo, so I'm closing this issue.
