### ISSUE TITLE
"as" used instead of cast in System.Data.SqlClient.SqlConnection.TryOpen()

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/corefx#5415]
System.Data.SqlClient.SqlConnection.TryOpen() goes like this:

     var tdsInnerConnection = (InnerConnection as SqlInternalConnectionTds);
     Debug.Assert(tdsInnerConnection.Parser != null, "Where's the parser?");
     if (!tdsInnerConnection.ConnectionOptions.Pooling)

If for any stupid reason `InnerConnection` cannot be cast to `SqlInternalConnectionTds` then `as` yields a null reference and later code yields a NullReferenceException. This causes error hiding. A cast would be better - an InvalidCastException would be thrown which would be much clearer.

**Comment by JonHanna** [comment]
When testing the assembly it would be an assertion failure either way.

If a change introducing this bug escaped testing then the NRE will be thrown on the next line, so it's not like it's hidden deep into the middle of a later call.

Assuming `isinst` is still faster than `castclass` (I'm going on old knowledge of the two so maybe improvements in the meantime have changed that), it's a reasonable optimisation.

**Comment by Dmitry-Me** [comment]
@JonHanna It would not be an assertion if `as` yields a null reference - it would be a NRE before assertion.

**Comment by JonHanna** [comment]
Well, an NRE inside the assertion. I suppose an assertion could be reasonably added above it to the effect of `Debug.Assert(tdsInnerConnection != null);`

**Comment by JonHanna** [comment]
If there's a problem here, its that we lack tests exercising it enough that if somehow something did introduce a bug where `!(InnerConnection is SqlInternalConnectionTds )` at this point, it won't throw anything at all during testing and could be merged in with that bug.

**Comment by Dmitry-Me** [comment]
@JonHanna IMO you are relying too much on testing. Thorough testing is good but it doesn't replace making code a bit easier to diagnose in production. If the object is of wrong type then the code fails in production anyway, the difference is how clear the failure is.

**Comment by JonHanna** [comment]
Thorough testing is good, and lacking in this particular place. I'm not saying it's a panacea, I'm saying it should be there.

Changing from `InnerConnection as SqlInternalConnectionTds` to `(SqlInternalConnectionTds)InnerConnection` here would result in the following difference of experience of the possible error you are talking about:

End user: Exception that might mention "NullReferenceException" becomes exception that might mention "InvalidCastException". Their experience is not improved.

Developer using assembly. `NullReferenceException` from within the call to `Open()` or `OpenAsync()` becomes `InvalidCastException` from within the call to `Open()` or `OpenAsync()`. Their experience is not improved.

Developer working on the assembly. `NullReferenceException` thrown immediately after `as` operation and hence almost certainly due to that `as` returning `null` becomes `InvalidCastException` thrown at a castclass. Improvement to their experience might save them a matter of seconds.

I'm not seeing what the gain is here.

Meanwhile, the assumption that `InnerConnection`, is of type `SqlInternalConnection` immediately after a test that it is of type `SqlInternalConnection` (one of two methods were called, both of which only return `true` if they have set `InnerConnection` to be a `SqlInternalConnection` and that return value was tested) is a reasonable one, and hence optimisations made on the back of that assumption are reasonable.
