### ISSUE TITLE
using System.Collections.Immutable and System.Runtime

### ISSUE THREAD

**Issue by christiannagel** [dotnet/corefx#5418]
With a project.json project application using the .NET Framework 4.5.x or 4.6, using System.Collections.Immutable I get this compiler error: The type 'ValueType' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Adding the NuGet package System.Runtime, either 4.0.0 or 4.0.21-rc2-* doesn't change a thing.

How can I use System.Collections.Immutable with project.json projects and .NET 4.5x or 4.6?

Thanks,
Christian

**Comment by ericstj** [comment]
What project type are you using to build this?  For CSProj and VBproj MSBuild will automatically add the System.Runtime facade to the project.  The same is required for consuming any contract-based portable library in a desktop project.

**Comment by christiannagel** [comment]
I'm using a Console Application (Package) - a .NET Core project with dnxcore50 and net46. The dnxcore50 compiles successfully, but net46 not.

**Comment by christiannagel** [comment]
See the ImmutableCollectionSample in this solution, project.json only has the dnxcore50 framework for this sample because it doesn't compile with dotnet46: https://github.com/ProfessionalCSharp/ProfessionalCSharp6/tree/master/SpecialCollections/SpecialCollections

**Comment by ericstj** [comment]
That's using DNX.  This issue should be filed in the DNX repo.

To work around the inconsistency you can add the following to your project.json:
```

  "frameworks": {
    "net46": {
      "frameworkAssemblies": {
        "System.Runtime":  "",
        "System.Resources.ResourceManager": "",
        "System.Diagnostics.Debug": "",
        "System.Collections": "",
        "System.Linq": "",
        "System.Runtime.Extensions": "",
        "System.Globalization": "",
        "System.Threading": ""
      }
    }
```

The problem is that DNX doesn't correctly match the behavior of the desktop projects.  The MSBuild-based projects automatically reference everything in the facades directory of the targeting pack but DNX did not implement this behavior.

We cannot change the packages to do this for DNX because it would break the MSBuild-based desktop projects that don't permit direct references to these assemblies by the project.  We can't fix that easily in the down-level versions of VS that the packages support.

I'd like to reiterate that you'd hit this same problem consuming any portable library in DNX.

**Comment by christiannagel** [comment]
Thanks! This is it!
Is DNX still the correct name for these project types when the DNX tools are replaced by the dotnet tools?
Thanks!
