### ISSUE TITLE
Adjust nuspec dependencies to simplify creating pure portable class lib projects

### ISSUE THREAD

**Issue by lodejard** [dotnet/corefx#5476]
For example, as a class library author I can choose a target and depends on a few of ref contract packages directly.

```json
{
    "version": "1.0.0-*",

    "dependencies": {
        "System.Collections": "4.0.11-rc2-*",
        "System.IO.FileSystem": "4.0.1-rc2-*"
    },

    "frameworks": {
        "dotnet5.6": { }
    },

    "runtimes": {
        "none": { }
    }
}
```
This works great, except the transitive dependencies don't give me the latest transitive packages. I'm afraid this means my class library won't have the latest surface area and intellisense documentation available for the 5.x TFMs I'm targeting. 

Expected:
![transitive-expected](https://cloud.githubusercontent.com/assets/1693989/12368036/3f2d5f2c-bb9c-11e5-8011-001e79308776.png)

Actual:
![transitive-actual](https://cloud.githubusercontent.com/assets/1693989/12368008/0162caec-bb9c-11e5-9451-30ff2e22bb77.png)

/cc @ericstj

**Comment by ericstj** [comment]
Right now we don't do this in order to avoid growing the patch families of the libraries: the set of packages that need to be updated in order to update a single package.  This is a generic rule in how we build our packages.

We could relax this requirement if we were able to ensure that a dependency update here would not update any implementation assembly.  That might require a bit of retro-active packaging work.

**Comment by davidfowl** [comment]
If we take the `runtime.json` out of the contract packages this would not be a problem. Referencing the highest version of packages is always safe since we introduced generations (netstandard). 

Can we just split contract packages from patch packages? That would simplify things and actually make it efficient to restore packages.

**Comment by ericstj** [comment]
In most cases they are split we have work tracking the remaining split up work.  Even once everything is split, we still need to go back and ship standalone implementation packages for the UWP libraries: both implementation and IL-only packages, that contain the exact binaries we built at UWP RTM.  This is needed to allow UWP apps to get the latest packages with generation monikers and still get their old implementation assemblies that match what is in shared-library & the .NETNative toolchain.

**Comment by lodejard** [comment]
Is there an ETA on that work? Does that mean this issue is on track to be implemented?

**Comment by ericstj** [comment]
This is just a suggestion at the moment.  We have other packaging work that needs to happen before we can get to this.  Since it isn't strictly blocking anything I can't push this in front of other work that is blocking the move of our the package build to open source and enabling NETStandard end-to-end.

**Comment by lodejard** [comment]
That's an interesting point - enabling NETStandard end-to-end - I wanted to ask about that as well.

If all of the packages are going to be re-deployed with a `(lib|ref)/netstandardx.x` - isn't compatibility with the `(lib|ref)/dotnetx.x` and `(lib|ref)/dotnet` a moot point? 

In other words - wouldn't it be a very clean approach to deploy the `ref/netstandardx.x` folders in the upcoming set of packages as reference assemblies only, and have the nuspec dependencies section for the netstandard tfm reference the current package at that point?

Because it's a new TFM it seems like it doesn't have the `dotnetx.x` and `dotnet` compatibility burden?

**Comment by davidfowl** [comment]
Given this, I think it makes sense that we're going to make netstandard not compatible with dotnet. It'll be a hard break but it makes sense as it lifts this compatibility burden.

**Comment by lodejard** [comment]
I agree completely

**Comment by ericstj** [comment]
I'm not concerned about compat with previous packages.  I'm talking about needing to update single implementation assemblies in UWP without updating the entire closure of implementation.

There are a set of implementation assemblies at the bottom of the stack in UWP that we cannot update.  The reason being that the implementation of those packages is pre-compiled into a shared native library that is meant to stay the same for all apps (with the exception of hotfix servicing for those apps).  Those packages at the bottom shipped as single packages with no runtime.json, because at that point in time we did not have a need for a seperate package.  Even today many of these remain as single packages for the same reason, but I am artificially splitting them to enable this scenario.  If we update the ref for those packages today we lose the implementation (or update the implementation as well, incidentally).

To fix this, I am trying to get everything in that shared library to split out its implementation into a separate package.  If I do that, then I can reship all the implementations from RTM as pre-versioned runtime packages and put those in a lineup for UWP.  That would let us update the dependencies on those reference packages to latest without breaking shared-library.

For things above that layer we can update, though we'd still like to not do that as a matter of practice since it makes it hard to ship a single library if you have to stabilize its entire closure.  As such we could look at a single update / baseline with RTM to get everyone on "NETStandard" packages and then only update in the future when folks need a new API.  This helps ensure we still have the servicing agility that folks demand.

**Comment by ericstj** [comment]
>  except the transitive dependencies don't give me the latest transitive packages.

This has been fixed for some time as of https://github.com/dotnet/corefx/commit/4435f9f2776ae007e05f4454675e56cf76a51975
