### ISSUE TITLE
Invalid lock in System.AppContext

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/corefx#5516]
Look into https://github.com/dotnet/corefx/blob/c8fe92337de2f82d84ad98b18883c527752c09a0/src/System.AppContext/src/System/AppContext.cs#L58

`s_switchMap` locked in `TryGetSwitch` method and `s_syncLock` in `SetSwitch`. Actually, access to the dictionary `s_switchMap` is not thread safe.

**Comment by mikedn** [comment]
Fun bug. 

Also, there's more code inside the lock than strictly required. Stuff like `isEnabled = (switchValue & SwitchValueState.HasTrueValue) == SwitchValueState.HasTrueValue;` should be outside the lock.

**Comment by JonHanna** [comment]
There's a good argument to be made for either approach to locking there, but doing a bit of each certainly doesn't give the best of both worlds!

I think it should actually be okay, because I think dictionaries with key and value-types that can be read atomically (string and int-sized enums would both count) should be safe on reads happening along with a single writer, and only one of the to places writes, so that lock should suffice.

But if I'm correct on that it's just an artefact of how the dictionary happens to be implemented, rather than something promised.

**Comment by JonHanna** [comment]
Is that `isEnabled` local meant to do anything?

**Comment by mikedn** [comment]
> should be safe on reads happening along with a single writer

That's only true for the old `Hashtable` type, it won't work well with `Dictionary<K, V>`. Granted, this dictionary is unlikely to see a lot of activity but still, it's a bug.

**Comment by JonHanna** [comment]
@mikedn it's promised with the old `Hashtable` type. The last time I looked it seemed to be true of `Dictionary` too, but only if the key and value types could be read and written atomically (which is obviously always true for `Hashtable`. But it's not promised to remain that way.

**Comment by JonHanna** [comment]
Anyway, not promised is enough to make it worth fixing the lock. @ViIvanov , @mikedn  Are either of you planning to fix it?

**Comment by mikedn** [comment]
> The last time I looked it seemed to be true of  Dictionary  too,

That's almost impossible. I say "almost" because I don't have time right now to write a test.

> Are either of you planning to fix it?

I can take care of it in about 4-5 hours if nobody else takes it.

**Comment by ViIvanov** [comment]
@JonHanna I can try fix it!

Should I also fix point from @mikedn about `isEnabled = (switchValue & SwitchValueState.HasTrueValue) == SwitchValueState.HasTrueValue;` inside lock?

**Comment by ViIvanov** [comment]
@mikedn You are the first, please do it. I can start only tomorrows evening.

**Comment by JonHanna** [comment]
I can do it right now if I'm not clashing with anyone else.

**Comment by ViIvanov** [comment]
@JonHanna Thanks!

**Comment by JonHanna** [comment]
There, that was a fruitful use of some lunch time :)

@mikedn reader with single writer: Following it through you are correct, there's a few points where overlapping operations would mess it up. (It wouldn't take much to give that guaranatee without adding much of a burden, but since it would still depend on the type of the value and key types in way that people would inevitably get wrong, it's far from being worth it.)

**Comment by mikedn** [comment]
> I say "almost" because I don't have time right now to write a test

Here's such a test I made for fun:
```C#
while (true)
{
    var d = new Dictionary<string, int>();

    var t = Task.Run(() =>
    {
        foreach (var i in Enumerable.Range(0, 1000))
            d[i.ToString()] = i;
    });

    Parallel.For(0, 1000, i =>
    {
        int v;
        if (d.TryGetValue("42", out v) && v != 42)
            throw new Exception();
    });

    t.Wait();
}
```
Bombs with a `NullReferenceException` inside `FindEntry` sooner or later.

**Comment by JonHanna** [comment]
Yep. To make it survive you have to both grab some local copies of arrays in the finding methods (the `get` on the indexer and `TryGetValue`) and add at least one memory barrier to the Resize method.
