### ISSUE TITLE
Enumerable.Sum overloads that take selectors should perform the sum themselves

### ISSUE THREAD

**Issue by fsateler** [dotnet/corefx#5549]
And should not `Select(selector).Sum()`.

When summing large sequences, the overhead added by the extra iterator is noticeable.

```csharp
void Main()
{
	int n = 10000;
	var origList = Enumerable.Range(0, n);
	
	var l = origList.Interleave(origList, origList, origList, origList).Select(i => new { k = i, val = i*i }).ToList().Take(n*4);
	
	Benchmark(() => {
		l.MySum(i => i.k);
	}, name: "SumInline");
	
	Benchmark(() => {
		l.MySum2(i => i.k);
	}, name: "SumProjection");
}

// Define other methods and classes here


static class ext {

	public static int MySum<T>(this IEnumerable<T> src, Func<T,int> val) {
		int sum = 0;
		checked {
			foreach(var d in src) {
				sum += val(d);
			}
		}
		return sum;
	}
	
	public static int MySum2<T>(this IEnumerable<T> src, Func<T,int> val) {
		return MySum2(src.Select(val));
	}

	public static int MySum2(this IEnumerable<int> src) {
		int sum = 0;
		checked {
			foreach(var d in src) {
				sum += d;
			}
		}
		return sum;
	}
}

public static void Benchmark(Action block, int ntimes = 1000, string name = "block") {
	// Precompile method
	block();
	var sw = new Stopwatch();
    sw.Start();
    for (int i=0; i < ntimes; i++) {
        block();
    }
	
	sw.Stop();
	var perLap = (double)sw.ElapsedMilliseconds/(double)ntimes;
    String.Format($"Time Taken: {sw.ElapsedMilliseconds:n}ms total, {perLap:0.000}ms p/i: {name}", sw.ElapsedMilliseconds, name).Dump();
}
```

Output is:

```
Time Taken: 1,098.00ms total, 1.098ms p/i: SumInline
Time Taken: 1,297.00ms total, 1.297ms p/i: SumProjection
```

Difference tends to move between 100 and 300 ms total (0.1-0.3ms per iteration).

**Comment by joshfree** [comment]
@VSadov PTAL

**Comment by JonHanna** [comment]
This is a classic trade-off between re-use and inline-performance.

#5820 will do this not just for `Sum` but for the other applicable aggregate methods (`Min`, `Max` and `Average`).

Pro: The performance change noted above.
Con: Duplicate code rather than reuse, with the increase in maintenance burden and chance of errors going only partly-fixed that entails.
Counter-argument Pro: Having such inline aggregation is the main thing (rather than merely convenience) thing these methods can offer over just using `Select` in the calling code.

Whether #5820 should be merged or this item closed as won't-fix goes down to those pros and cons, I think.
