### ISSUE TITLE
Implement IReadOnlyList<> in Grouping<,> class from System.Linq

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/corefx#5582]
Hello!

I talk about [class Grouping<TKey, TElement>](https://github.com/dotnet/corefx/blob/a58f490274e286d844d277f2658f2c074a4d5350/src/System.Linq/src/System/Linq/Enumerable.cs#L3544) from System.Linq. Now it declared as

# Proposed API
``` c#
public class Grouping<TKey, TElement> : 
// Existing interfaces
    IGrouping<TKey, TElement>, 
    IList<TElement> 
// Proposed interfaces
    IReadOnlyList<TElement>,
    IReadOnlyCollection<TElement>
{ …
```

# Workaround
In many scenarios I want to have a group (an instance of IGrouping<,>) as an instance of IReadOnlyCollection<> or IReadOnlyList<>. Now I have to wrap the group in a ReadOnlyCollection<> or copy it to the new List<>.

``` c#
    public static IReadOnlyCollection<TElement> AsReadOnlyCollection<TKey, TElement>(this IGrouping<TKey, TElement> group) {
      if(group == null) {
        throw new ArgumentNullException("group");
      }

      var readOnly = group as IReadOnlyCollection<TElement>;
      if(readOnly != null) {
        return readOnly;
      }

      var list = group as IList<TElement>;
      if(list != null) {
        return new ReadOnlyCollection<TElement>(list);
      }

      return new List<TElement>(group);
    }
```

I know, that not any IGrouping<,> should implement list interfaces, but in many cases I can use a fast path. All I need is add IReadOnlyList<TElement> to a list of interfaces, that Group implements.

**Comment by joshfree** [comment]
@VSadov PTAL

**Comment by JonHanna** [comment]
Because this would change the set of public interfaces that gets exposed, this would have to be considered an API change, and reviewed as such. The idea though seems like a good one to me.

**Comment by ViIvanov** [comment]
@JonHanna As I know, a Groping class was "internal" some time ago ([.NET 4.6.1](http://referencesource.microsoft.com/#System.Core/System/Linq/Enumerable.cs,7bb231e0604c79e3)). Was it shipped as "public"?

**Comment by JonHanna** [comment]
It's not 100% public now, according to the comment:

```C#
 // It is (unfortunately) common to databind directly to Grouping.Key.
// Because of this, we have to declare this internal type public so that we
// can mark the Key property for public reflection.
//
// To limit the damage, the toolchain makes this type appear in a hidden assembly.
// (This is also why it is no longer a nested type of Lookup<,>).
```

But some previous suggestions (including some of my own) about interfaces that should be implemented in certain places have raised the objections if it would be exposed, because if you can reasonably build a dependency on:

`(IReadOnlyList<int>)Enumerable.Range(0, 100).GroupBy(i => i / 10).First()`

Then you can reasonably be annoyed if somebody's implementation detail removes that interface use and your code breaks. So as such it would have to be considered part of the API, and hence changing it to be a change to the API.

**Comment by ViIvanov** [comment]
Thanks. Of course, this is very valuable rule for an API users :o) Adding interfaces to a public types is not simple, I figured it out.

**Comment by JonHanna** [comment]
In an ideal world if methods were documented as *possibly* returning a result that implemented a particular interface then people would always fast-path with the likes of:

```C#
var useful = result as UsefulType;
if (useful != null) FastPath(useful);
else SlowPath(result);
```

And there's several places I'd like to have that option as a developer. In reality though, even the careful developers would probably use `FastPath((UsefulType)result)` sometimes and then the implementation is stuck supporting it for ever more.

**Comment by ViIvanov** [comment]
I agree. This is hard, but good practice for the API`s such .NET.

**Comment by karelz** [comment]
Seems reasonable, let's review the API proposal.

**Comment by terrajobst** [comment]
The return type of Linq's `GroupBy` is ` IEnumerable<IGrouping<TKey, TSource>>`. As @JonHanna said, we can't add `IReadOnlyList` to `IGrouping` because that would be a breaking change.

We could implement `IReadOnlyList` on `Grouping` but that value seems low as the type is (effectively) no public API returns it. Callers would have to cast the value returned from the enumerable which is pretty much undiscoverable...

Unless there is a good reason to add it anyway, we're inclined to close this proposal.
