### ISSUE TITLE
X509CertificateCollection.Remove() weird error checking

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/corefx#5584]
X509CertificateCollection.Remove() disallows removing null objects but allows removing objects which are not in the collection (because it just forwards to `List.Remove()` and never checks the result). MSDN https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.x509certificatecollection.remove%28v=vs.100%29.aspx says removing elements which are not in the collection is disallowed.

If you want to allow removing elements that are not in the collection then you should also allow removing null objects - they are never in the collection.

**Comment by stephentoub** [comment]
@bartonjs, this appears to be a porting issue from the full framework.  This code:
```C#
using System.Security.Cryptography.X509Certificates;

class Program
{
    static void Main()
    {
        var c = new X509CertificateCollection();
        c.Remove(new X509Certificate());
    }
}
```
throws an exception in the full framework (matching the docs), but completes successfully with corefx.  I assume that change was unintentional.

**Comment by bartonjs** [comment]
Tracing the blame graph backwards shows it came that way from TFS.  I was hoping this was something that came in with @justinvp's cleanup of this class... not to blame Justin, but I was hoping we'd had a discussion saying we were okay with losing that exception :).

Since that exception came from CollectionBase (which I believe didn't come across), I wonder how big the fallout is.

**Comment by bartonjs** [comment]
Hmm, actually, CollectionBase does exist.  I'm confused, and looking for more information now.

**Comment by bartonjs** [comment]
Okay, the general consensus I got in chatting with people is
a) We don't like that Remove throws on missing elements in Desktop.
b) But we think it's better to match Desktop for RTM, since the package claims to be equivalent to .NET 4.6.1.

So I'm putting the exception on Remove(missingElement) back.
