### ISSUE TITLE
Use System.Buffers in more corefx libraries

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5598]
We should investigate using System.Buffers in:
- [ ] System.IO.FileSystem for the byte[] used in FileStream
- [ ] System.IO for the byte[] used in BufferedStream, the char[]s used in various readers/writes, etc.
- [x] System.Net.Http in the variety of places we create byte[] as temporary buffers
- [ ] System.Runtime.Extensions when we need temporary byte[](such as when creating random file names), in WebUtility, etc.
- [ ] ... probably other places as well

...basically anywhere we're creating arrays that aren't exposed, where we can easily clean up after them when we're done with them, and where they're used on paths that are potentially hot enough to make a measurable difference.

**Comment by benaadams** [comment]
Stream.[CopyToAsync](https://github.com/dotnet/corefx/blob/master/src/System.IO/src/System/IO/Stream.cs#L141) and [CopyTo](https://github.com/dotnet/corefx/blob/master/src/System.IO/src/System/IO/Stream.cs#L215) ?

**Comment by stephentoub** [comment]
> Stream.CopyToAsync and CopyTo ?

For CoreCLR those are currently implemented in mscorlib, which can't depend on System.Buffers.

**Comment by SajayAntony** [comment]
@mconnew worth considering rewriting BufferManager over System.Buffers.

**Comment by clrjunkie** [comment]
I think we need to consider a general interface/delegate for "Buffer Pool" to allow for alternate implementations. Users may simply choose whether to "plug-in" one buffer pool or another or not at all and see what works best for their scenario/component.

**Comment by sokket** [comment]
@stephentoub We should update this list after the last design review to find places where we can safely use Buffers without causing potential side effects

**Comment by stephentoub** [comment]
@sokket, yeah.  Most of the ones we'd envisioned won't work.  Off the top of my head, I think some in System.Net.Http may still be appropriate, and we could probably make FileStream work with some extra overhead to track whether any operation (sync or async) is still in progress... as @jkotas alluded to today, likely the only place where the extra synchronization costs would be measurable would be on ReadByte (where I expected it'd be very measurable), and we'd need to reason about whether that's acceptable.

**Comment by benaadams** [comment]
Would the addition of an InternalShared buffer pool help with any poor use code buffer pool use? Would mean a double buffer pool by default though.

**Comment by stephentoub** [comment]
> Would the addition of an InternalShared buffer pool help with any poor user code buffer pool use?

In most cases, no, e.g. in the example of CopyToAsync where the buffer is getting handed out to an arbitrary stream.  We could potentially take it further and special case by checking the concrete type of both the source and destination streams and only using the pool if they're on an allowed list, but that's cumbersome and quickly reaches a point where it's unclear it's really worthwhile.

**Comment by benaadams** [comment]
It would protect corefx for any bad Rent/Release semantics in user code though (unless they returned the buffer to a different pool, when they didn't rent it in the first place)

> CopyToAsync where the buffer is getting handed out to an arbitrary stream

If the stream kept hold of the buffer at the end of the awaited operation though that would be a bad implementation? As in a standard read/write sequence that buffer will be transformed by the calling code and or reused for the next operation. i.e. at the completion of the op the stream should forget about it - whether that's because its copied to its own buffer for example in a buffered type stream; or genuinely finished the operation.

ReadOnly and WriteOnly Spans might be interesting; to limit operation scope...

**Comment by benaadams** [comment]
Though using Spans would likely mean the api for Stream would have to change; or a new type of Stream...

**Comment by stephentoub** [comment]
> It would protect corefx for any bad Rent/Release semantics in user code though

Yes, as you say at the expense of needing to maintain a completely separate pool, if not multiple pools, given that many of the desired locations is in a completely independent assembly, and a goal is that such assemblies don't have private communication between each other.

> If the stream kept hold of the buffer at the end of the awaited operation though that would be a bad implementation?

Yes, any of the problems here would be due to bugs.  The concerns that started this discussion were that now bugs which were previously isolated now can cause system-wide corruption.  An example here would be a faulty Stream.WriteAsync implementation that accidentally completed the returned Task before it was done with the buffer.

> ReadOnly and WriteOnly Spans might be interesting

Yes, this was discussed at the design meeting today (there should be a video or something available from it).

**Comment by tibel** [comment]
Isn't pooling a technique for reducing stress on GC. So it can't be safe by definition: Buying some performance by weakening the safety net.

Safe pooling would require to extend the runtime/GC by the concept of pooling so you can return an object immediately and don't have to wait for a GC cycle (good old `malloc` and `free`). When the runtime knows about pooled objects it can handle the returning to the pool safely by setting all references to null or throwing an exception when another object holds a reference.

Why not let the application developer choose wether to use pooling or not. This could be done similar to configuring GC settings in `app.config` (don't know if this is still the case with dotnet core). The default can be Off or Safe pooling only.

pooling options:
- Off (no pooling)
- Safe (only not shared)
- Full (allow sharing of pooled objects)

Then I as the application developer (not the library developer) can enable or disable pooling. When enabling it I have to be aware that finding some issues might be harder, but I enable it as I need the performance gain it gives.
Optionally allowing to configure pooling per assembly, so I can deactivate pooling for one faulty assembly only.

**Comment by benaadams** [comment]
> Isn't pooling a technique for reducing stress on GC. 

The GC itself is essentially a pool. 

However, its also much more complex as it deals with polymorphic types; objects of different-sizes, non-predicable lifespans, and has to infer the usage relationships and reference graphs to workout when things are not longer used so their memory can be returned to the pool; without foreknowledge of the application and how it works; it also does heap defragmentation O_o

Specialist pools for specific monomorphic types can work with the GC to provide an increased benefit; much like hoisting a variable out of a loop and just resetting its values, rather than `new`ing it each iteration. 

Medium lifetime objects are especially good candidates to pool - if something is going to end up in Gen2; its better to reuse it when it does rather than throw it away and create another item that's going to end up in Gen2. Even, if you are creating a high frequency of objects that end up in Gen1, it might be better to extend their lifetime to the entire app's lifetime move them into Gen2 and reuse them to only have a few.

> So it can't be safe by definition

It can be. There are already a bunch of things pooled in .NET that people already take for granted; threads are pooled, database connections are pooled; http connections are pooled (keep-alive), string builders are pooled internally, the Immutable collections do a lot of pooling; Pinnable Buffers are pooled etc.

The issue is more that the pool must provide increased performance with GC, else there's not much point - and the GC is a pretty high bar already. Generally its working with the GC rather than working round it. 

e.g. not clogging the GC with immovable objects (pinnable buffer cache); not filling Gen2 with dead medium lifetime objects, or even removing large sized high frequency Gen0 churn objects which cause gen0 GCs (array pools). Even immutable objects like CompletedTask and Array.Empty are in a way pooled objects.

Too much pessimistic safety and you are likely to end up with worse performance than the GC; decreased sharing means more bloat, so its more about trade offs.

**Comment by iskandersierra** [comment]
Please include MemoryStream in this changes. Although due to some internal performance stuff and more public ones like GetBuffer, I think it would be better to create a new PooledMemoryStream which uses an ArrayPool<byte> to get access to byte buffers.

**Comment by sokket** [comment]
@stephentoub Did we nail down a list of places where Buffer Pooling can be safely used in the framework?

**Comment by stephentoub** [comment]
> Did we nail down a list of places where Buffer Pooling can be safely used in the framework?

No one's done an exhaustive search.  We understand the principles, but each potential case needs to be evaluated against that.

**Comment by sokket** [comment]
Gotcha, thanks for the clarification

**Comment by sokket** [comment]
I'm pushing this out past RTM since this is a perf improvement along existing pathways, some critical; to feel confident in the changes to these paths, we should have more bake than we have left until RTM (due to investigation time, coding time, and testing time). This will be a prime improvement for post 1.0-RTM

**Comment by sokket** [comment]
@stephentoub if you disagree, please let me know :)

**Comment by karelz** [comment]
@alexperovich can you please review which of the items from the list are already done?

**Comment by karelz** [comment]
@alexperovich ping?

**Comment by alexperovich** [comment]
None of them have been done. All streams get this perf for free from Stream for CopyToAsync, but the specific cases in this issue have not been done.

**Comment by stephentoub** [comment]
This issue isn't particularly actionable, as it's very broad.  We will continue to use ArrayPool in more places as opportunities present themselves.
