### ISSUE TITLE
Additional PR feedback for NegotiateStream porting

### ISSUE THREAD

**Issue by vijaykota** [dotnet/corefx#5617]
- [ ] End if / else if / else if /... waterfalls with one last "if" see detailed comment https://github.com/dotnet/corefx/pull/5581#discussion_r50420783 
- [ ] https://github.com/dotnet/corefx/pull/5581#discussion_r50420982
- [ ] #5541 (comment) 
- [ ] https://github.com/dotnet/corefx/pull/5581#discussion_r50422362- [ ] fix comment "// This is to not depend on GC&SafeHandle class if the context is not needed anymore"
- [ ] https://github.com/dotnet/corefx/pull/5581#discussion_r50426276
- [ ] use a variable instead of direct usage of number 4, 16 in the code. https://github.com/dotnet/corefx/pull/5581#discussion_r50431861
- [ ] https://github.com/dotnet/corefx/pull/5581#discussion-diff-50433441 
  https://github.com/dotnet/corefx/pull/5581#discussion_r50433347
- [ ] https://github.com/dotnet/corefx/pull/5581#discussion_r50423078
- [ ] https://github.com/dotnet/corefx/pull/5772#discussion_r51471912
- [ ] https://github.com/dotnet/corefx/pull/5772#discussion_r51472457 
- [ ] https://github.com/dotnet/corefx/pull/5772#discussion_r51473319
- [ ] https://github.com/dotnet/corefx/pull/5772#discussion_r51472857 
- [ ] https://github.com/dotnet/corefx/pull/5772#discussion_r51473345
- [ ] https://github.com/dotnet/corefx/pull/5772#discussion_r51472547
- [ ] https://github.com/dotnet/corefx/pull/5772#discussion_r51473799
- [ ] https://github.com/dotnet/corefx/pull/5772#discussion_r52743275 Need to throw more accurate exception in syn with other exception in code.

**Comment by bartonjs** [comment]
@vijaykota This issue needs specific actionable bullets.  Simply saying "address unaddressed comments" means that there's no way to track what is/isn't supposed to be done from this issue.

**Comment by davidsh** [comment]
@vijaykota See example of #2165 which has bullets for TODO items resulting from a previous PR.

**Comment by vijaykota** [comment]
Sure, @davidsh and @bartonjs. @shrutigarg, please add the itemized list to this issue. If everything is only in Windows code, you could assign the issue to NCL folks. Thanks!

**Comment by shrutigarg** [comment]
- [ ] End if / else if / else if /... waterfalls with one last "if" see detailed comment https://github.com/dotnet/corefx/pull/5581 

- [ ] add assert instead  // Server side should not request any of these flags. line 160 InternalNegoState.cs

- [ ] #5541 (comment) 

- [ ] check for  _context  null value  line 276 and 294 InternalNegoState.cs
- [ ] fix comment "// This is to not depend on GC&SafeHandle class if the context is not needed anymore"

- [ ] duplicate usage of code for (int i = message.Length - 1; i >= 0; --i)  
                    {  
                   message[i] = (byte)(statusCode & 0xFF);  
                     statusCode = (int)((uint)statusCode >> 8);  
               }  
factor it out to a method.
- [ ] use a variable instead of direct usage of number 4, 16 in the code. 

- [ ] https://github.com/dotnet/corefx/pull/5581#discussion-diff-50433441 
https://github.com/dotnet/corefx/pull/5581#discussion-diff-50433441

**Comment by shrutigarg** [comment]
updated  the list of relevant comments to be fixed in this.

**Comment by karelz** [comment]
Triage: Looks like a list of nice to have things. We don't think there is anything super-important in there. We already shipped with the code twice.
If there is anything we should truly address, please open new issues.
