### ISSUE TITLE
Add test to verify the correct bits for SqlClient

### ISSUE THREAD

**Issue by saurabh500** [dotnet/corefx#5634]
SqlClient should have a test which verifies that the correct bits are being built for the respective platforms.

**Comment by nadiatk** [comment]
The issue is complete.
Deployed System.Data.SqlClient.Tests project containing Exception test to do a simple sanity check for a specific SqlException when connecting to a non-existent sql server. The test will fail if it receives any unexpected exceptions which are typically a sign of a broken build.
