### ISSUE TITLE
Ensure that System.Net tests are executing against the checked-in implementations

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#5716]
/cc: @davidsh 

Several System.Net test assemblies are referencing externally downloaded packages for System.Net dependencies.This makes it harder to discover issues early in development (see #5708 for an example).
We should change the test csproj files to directly reference other System.Net implementations (see NameResolution, Sockets for examples).

**Comment by davidsh** [comment]
The only problem with using P2P references is that sometimes we test against "public" methods that are only public in the DLL but not really in the refs contract themselves.

Usually, this is a programming error on our part since we should make sure to use "internal" and not "public" on public classes that need assembly-level scope.

**Comment by mellinoe** [comment]
> The only problem with using P2P references is that sometimes we inadvertently test against "public" methods that are only public in the DLL but not really in the refs contract themselves.

At the very least we should be able to set something up where the implementation assembly is copied over for the test run, even if the test code is compiled against the contract/ref assembly.

**Comment by CIPop** [comment]
Verified that all tests within `System.Net.*` and `System.Private.Uri` are referencing their respective `..\src` implementations directly.
