### ISSUE TITLE
ArrayPool<T>.Rent may give back too small a buffer if bad buffer returned

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5949]
The second call to Rent here returns the previously returned array of length 1, such that the last line here throws an IndexOutOfRangeException due to getting too small a buffer back from Rent:
```C#
ArrayPool<byte>.Shared.Rent(15);
ArrayPool<byte>.Shared.Return(new byte[1]);

byte[] buffer = ArrayPool<byte>.Shared.Rent(15);
buffer[3] = 3; // throws exception
```

**Comment by AlgorithmsAreCool** [comment]
The issue looks like the unguarded usage of Utilities.SelectBucketIndex(int) in buffer DefaultArrayPool Return can violate the minimum size assumption of the class.

Any buffer smaller than length 16 should be discarded, not returned to the pool. It looks like trusting SelectBucketIndex will end up dropping undersized arrays back in _buckets[0]. Perhaps DefaultArrayPoolBucket should additionally guard itself from undersized array returns.

Also has it been noted that SelectBucketIndex(0) == 28? It doesn't harm much since it is guarded against as far as i can tell, but the valid range of the method should probably be noted somewhere

Also would it be beneficial to special case requests for 0 length arrays to return a singleton? This would let consumers write less guarded code and prevent a technically valid case from throwing.

**Comment by AlgorithmsAreCool** [comment]
I could submit a fix if it would help, it looks very minor.

**Comment by sokket** [comment]
Hmm it seems like there could be a small change to the Bucket class where, on Return, we check if the array length == the expected length and if it doesn't, just drop the array; that seems like it would be the most targeted fix. That way, if we change the bucket size algorithm to support sizes smaller than 16, we don't have another special case...does that make sense to everyone?

**Comment by stephentoub** [comment]
> we check if the array length == the expected length and if it doesn't, just drop the array

Wouldn't we want to throw?  This definitively means a buffer is being returned to the pool that didn't come from the pool, right?

**Comment by sokket** [comment]
Ah yes, sorry...throwing would be much, much better in this case

**Comment by sokket** [comment]
I have a PR out to fix this now as well as a UT to validate

**Comment by sokket** [comment]
Fixed by #5973

**Comment by rynowak** [comment]
Reopening this bug, because throwing here breaks simple usage of this API.

From: https://github.com/aspnet/Mvc/issues/4213#issuecomment-193350492

============================

This change breaks some fairly innocent looking code. Look at this unit test: https://github.com/dotnet/corefx/commit/a0d122b80dfb6975c2f0dc4325460d8890562a3b#diff-c4e5a90442584ce8373354cb1fde4e68R382 It doesn't pass the smell test once the `15` is a computed value.

You need to know now whether or not your buffer returned from `Rent` was **really** rented, which breaks the usability of this API.

**Comment by stephentoub** [comment]
@rynowak, I'm not following... what's an example where this is problematic? It's fine if 15 is computed... the failure  in  that  test isn't coming from returning the 15-length buffer.

**Comment by rynowak** [comment]
Yeah I think you're right, I shouldn't open bugs early in the morning. :laughing: 

I didn't read the test closely enough, it looked like at first to me that it was renting and then returning a 15-element buffer, and that the pool would throw on a return below its minimum size.

I'll follow up on the JSON.Net part of this.

**Comment by stephentoub** [comment]
> I'll follow up on the JSON.Net part of this.

Thanks.  If it turns out there actually is a real problem with this policy, e.g. there are real scenarios where folks would like to return non-rented buffers back to the pool, please open a new issue with details and we'll take a look.  Our goal here is of course to provide good performance and good usability... if we're falling down on those, we should address it.  The good news is the current policy is the conservative/restrictive one, and in the future it's considered non-breaking to turn a throwing case into a non-throwing one.
