### ISSUE TITLE
Expose existing FileStream.Lock() and FileStream.Unlock() APIs on MacOS/Unix

### ISSUE THREAD

**Issue by xied75** [dotnet/corefx#5964]
Dear Team,

As the subject line states we seek the consideration to add Lock() and Unlock() for FileStream in the contract. The implementation should be straight forward at least for Windows platform. Current .NET 4.61 calls Win32 LockFile underneath:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365202(v=vs.85).aspx

Although we don't have access to LockFile for UWP, we do luckily have the brother of it LockFileEx, which also supports async, which is good news.

I believe for Linux/BSD/Mac there should be easy equivalent to find as locking on file is very common in old days. Will find all the details if the team is willing to consider the proposal.

We could do our own P/Invoke to call the LockFileEx, but it would be much elegant if corefx support that out of box, unless there is significant reason to reject it.

**Comment by stephentoub** [comment]
> I believe for Linux/BSD/Mac there should be easy equivalent to find as locking on file is very common in old days. Will find all the details if the team is willing to consider the proposal.

It can be done with fcntl and F_SETLK.

**Comment by xied75** [comment]
Was testing some code found on SO: http://stackoverflow.com/questions/1784195/using-lockfileex-in-c-sharp

Using the first solution by the OP himself, the code works in normal project, once I tried it within a UWP unit test (with xunit), it gives me this:

```
0xC000000D was unhandled
Message: Unhandled exception at 0x77099B20 (ntdll.dll) in LockFileUWPTests.exe: 0xC000000D: An invalid parameter was passed to a service or function.
```

In fact calling lock() returned true, but after that if I do ReadByte() it will break.

```
fs.ReadByte() /// works
fs.lock(1L, 1000L) ///ok
fs.ReadByte() /// exception!
```

Not sure is this due to the code just set IntPtr.Zero to hEvent is the culprit, or the thread model of uwp, or even xunit runner, lacking too much knowledge.

Tried to use the 2nd answer which seems more correct to set Overlapped properly, but once within UWP I have no access to System.Threading.Overlapped class (not namespace) anymore, therefore I don't know how to do the pack() and unpack() stuff.

**Comment by terrajobst** [comment]
This would require additional APIs in .NET Framework, so I'm moving it to Future.

**Comment by stephentoub** [comment]
@terrajobst, what about:
https://msdn.microsoft.com/en-us/library/system.io.filestream.lock(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/system.io.filestream.unlock(v=vs.110).aspx
?

**Comment by terrajobst** [comment]
:smile: I see. In that case RTM seems fine :-)

I don't see a problem with exposing these APIs. @KrzysztofCwalina @weshaggard?

**Comment by weshaggard** [comment]
I don't have any real context on these perhaps @ericstj might have some ideas as to why we didn't expose them in the first place.

**Comment by ayende** [comment]
They are probably hidden because they are not portable, see: http://0pointer.de/blog/projects/locking.html

**Comment by xied75** [comment]
The blog post is surprisingly negative towards Linux, makes one want to dump the penguin forever. :)

I kind of doubt that No serious software use locks in Linux, at least __git__ does.

**Comment by ayende** [comment]
@xied75 Git doesn't use file locks. It use lock files.
In other words, it use the presence of a file to detect whatever it is lock or not, it doesn't use the flock or F_SET_LK methods.
I just grepped the git source to verify that, by the way.

**Comment by ericstj** [comment]
At the time we did the initial contract we had 3-strikes against this API.

1. Sub-file locking was not supported by all platforms.  We couldn't lock the files which we got through the WinRT broker since we didn't have a handle and WinRT didn't expose anything like sub-file locking.  That's not a blocker since there are other similar things we can't do with brokered files.

2. The failure mode for a partially locked file (Read/Write vs Open) is not something that folks harden against so we didn't want to promote this as the way to control access to a resource.  Instead folks can either use FileShare to restrict the entire file, or coordinate region access themselves if they happen to own both consumers of the file.

3. Noone asked for the API and usage data said it was rarely used.  IIRC all uses were just folks wrapping it but not actually calling it.

I don't think any of these are reason enough to not do this if we have new data, just sharing original justification.

**Comment by terrajobst** [comment]
Thanks @ericstj. My understanding is that in AppContainer a file could be lockable if it is from a location we can use Win32 but not lockable when it comes from a location that can only be accessed via the WinRT broker, right?

In that case it looks like the APIs will have to throw `NotSupportedException` as it depends on context. This tells me that FileStream would need a capability API to allow consumers to ask up front whether the particular instance supports locking, in which case I'm for postponing the APIs so that we can bring the APIs and the capability check at the same time.

**Comment by ayende** [comment]
One common use of this API in production is here:
https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Core/Store/NativeFSLockFactory.cs#L165

When we ported this to the CoreCLR we just used the native call, and since
we need to support this on Linux, we'll probably change that to use a
locking file, instead of a file lock.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by terrajobst** [comment]
@KrzysztofCwalina @ericstj @stephentoub 

So what's the conclusion? Should we expose the API? I'm favor of adding these but I think we should add a capability API. Hence I'm inclined to move these to Future and mark it as api-needs-work. Any objections to that?

**Comment by KrzysztofCwalina** [comment]
@terrajobst, your proposal sounds good to me.

**Comment by manu-silicon** [comment]
Got bitten by the lack of Lock recently. When is this planned exactly? Any help needed to get this going?

**Comment by stephentoub** [comment]
@manu-silicon, we're working on adding back to .NET Core a large number of APIs.  I expect this will be a part of that. cc: @danmosemsft

**Comment by manu-silicon** [comment]
Great! Thanks for the speedy reply.

**Comment by danmosemsft** [comment]
It will come back but we're focused on the most basic and most used types/members first.

**Comment by danmosemsft** [comment]
FileStream.Lock is tracked in https://github.com/dotnet/corefx/issues/9465. I'll assign this one specifically to @JeremyKuhne though.

**Comment by stephentoub** [comment]
Lock/Unlock have been added, but they still need a Unix implementation.

**Comment by JeremyKuhne** [comment]
@stephentoub According to the comments a Unix implementation this doesn't seem plausible. If we can't guarantee a machine-wide lock (to match Windows) I don't think we should implement it for non-Windows. Am I missing something?

**Comment by stephentoub** [comment]
> If we can't guarantee a machine-wide lock (to match Windows) I don't think we should implement it for non-Windows. Am I missing something?

We already use flock to implement FileShare even though flock only uses advisory locks.  If fcntl with F_SETLK in order to lock byte ranges is insufficient (e.g. reliability issues), then we could simply choose to use flock for this as well, essentially ignoring the specific byte ranges requested and just locking the whole file.  For better or worse we have these Lock/Unlock APIs, and IMHO we should do our best to provide some meaningful functionality rather than just throwing.

**Comment by JeremyKuhne** [comment]
> For better or worse we have these Lock/Unlock APIs, and IMHO we should do our best to provide some meaningful functionality rather than just throwing.

My problem is in how this impacts writing truly portable code. You can't meet the same expectations on Unix- yet people will assume so in their code. If this wasn't a synchronization mechanism I'd be less concerned.

Whether or not we implement something I'd like to see this get an [Obsolete] flag. It is screaming "subtle bugs" to me. We should be recommending *not* using this for cross-plat, imho. @terrajobst, What do you think about marking APIs like this?

**Comment by stephentoub** [comment]
> My problem is in how this impacts writing truly portable code. You can't meet the same expectations on Unix- yet people will assume so in their code. If this wasn't a synchronization mechanism I'd be less concerned.

I agree with the sentiment.  At the same time, desktop has an implementation, .NET Core on Windows has an implementation, and Mono has an implementation (using fcntl with F_SETLK): not providing one for .NET Core on Unix is also similarly bad for writing portable code.  There are also already many differences that stem from the underlying platforms that we're unable to smooth over, some even in this area, e.g. on Windows FileShare is enforced at the OS level, but on Unix since locks are advisory, someone can choose not to use flock and still open the file even if someone else is using it.  We have to choose our battles.

**Comment by JeremyKuhne** [comment]
> not providing one for .NET Core on Unix is also similarly bad for writing portable code

True, but only because we've chosen to expose this as part of the standard (as it is already in use). I get why that's necessary and realize that throwing defeats the existing code portability design goal. That said I'd love to do what we can to encourage people away from these sorts of APIs when writing new code. Do you agree with that sentiment? How do you think that is best accomplished?

Oh, and given that Mono uses fcntl, we probably should follow along with that I think.

**Comment by manu-silicon** [comment]
Since I've also expressed interest in this API, let me tell you about my use case which is covered by what you are proposing. What we want is to prevent multiple .NET applications we wrote to use the same file. Anything in this direction is more than welcome. Thanks for helping out.

**Comment by danmosemsft** [comment]
netstandard2.0 as these seem to be on FileStream in NS2.0

**Comment by ianhays** [comment]
resolved in https://github.com/dotnet/coreclr/pull/8233.

**Comment by stephentoub** [comment]
> resolved in dotnet/coreclr#8233.

Do we still need tests?

**Comment by ianhays** [comment]
Actually, I'm going to leave this open to track re-enabling the lock/unlock tests for Unix. I'll put up a PR for that as soon as we get a new mscorlib version in CoreFX to consume the fix

**Comment by ianhays** [comment]
@stephentoub beat me to it yet again :)

**Comment by ianhays** [comment]
Linux is up and running, but we've got a problem with MacOS.

On OSX, attempting to lock a file region via fcntl does not work when the process already holds a lock on the file regardless of whether it is shared or exclusive. Since we always take a lock when creating a FileStream - the type of which depends on the FileShare parameter passed to the constructor - we cannot ever fcntl a file open by our FileStream. This is of course different behavior than Linux where it is allowed and functions fine. [Here](http://stackoverflow.com/questions/22409780/flock-vs-lockf-on-linux) and [here](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man3/lockf.3.html) this behavior is discussed and the takeaway is that on OSX you should only ever use fcntl **or** flock, not both.

Mono gets around this issue by using a manual hashset to keep track of `FileShare` so they can call fcntl for lock/unlock . The downside is that their FileShare code is complex and doesn't function across processes like ours does.

We should decide whether we want to PlatformNotSupported OSX or go a different route e.g. using flock for everything or fcntl for everything.

**Comment by ianhays** [comment]
@stephentoub @JeremyKuhne opinions? I'm starting to think PlatformNotSupported for Lock/Unlock on OSX may be the way to go so we don't have to break our FileShare behavior.

**Comment by stephentoub** [comment]
I don't think there's value in doing something here that only helps within the same process; the primary reason you use file locking is cross-process.

If there's no other solution we can think of for macOS, seems like we really only have two options:
- Make Lock/Unlock nops on macOS
- Make Lock/Unlock throw PNSE on macOS
and I don't think nop is really valid option here (it'd be like saying `lock` in C# was a nop).  So if we can't come up with anything functional, seems like throwing on macOS is the way to go (or maybe only throw if the file was opened as something other than FileShare.None, since if it was successfully already opened as FileShare.None, making Lock/Unlock nops shouldn't be observable?)
