### ISSUE TITLE
System.Net.Cache whole namespace is not in corefx?

### ISSUE THREAD

**Issue by xied75** [dotnet/corefx#6008]
Was porting something that is doing:

```
if (u)
		request.CachePolicy = new System.Net.Cache.RequestCachePolicy (System.Net.Cache.RequestCacheLevel.Default);
else
		request.CachePolicy = new System.Net.Cache.RequestCachePolicy (System.Net.Cache.RequestCacheLevel.BypassCache);
```

Then discovered that this namespace doesn't exist in the corefx, not even asked or mentioned in issues/code.

1, Is there better practices cancelling the need of this?
2, Is the function absorbed into somewhere else?
3, Or simply missing?

**Comment by davidsh** [comment]
The System.Net.Cache namespace and associated classes and methods are not in CoreFx and there are no plans to put them in.

These classes were used initially to support a simple caching logic for the original HTTP stack using HttpWebRequest APIs

We rewrote the entire HTTP stack and there is no caching logic in it.  System.Net.Cache could not be ported as-is anyways.

The advice for customers when doing HTTP is to use the HttpClient API surface (System.Net.Http). In addition, customer needing caching logic can write their own by creating a custom handler (derived from HttpMessageHandler, DelgatingHandler) and then using that in the pipeline of handlers for the HttpClient.

cc: @CIPop @SidharthNabar

**Comment by xied75** [comment]
@davidsh Thanks a lot for the fast reply. Certain information can only surface from you guys e.g. why you created that namespace at the first place. Allow me to further question a bit so other people can reference this later.

1, what is the reasoning to have this simple cache when you designed HttpWebRequest API? Is that for performance?

2, with the new stack (System.Net.Http) what is the reasoning to no longer want/need this? Is that also because perf (i.e. the new stack is very fast, use very little resource, etc. so caching no longer help a lot... thus it can be safely ignored)

3, if caching still somehow can contribute a lot to perf/resource usage, now the decision is this is now offloaded to us, no longer offered out of box. If so some documents/example would be great helps for the community. (On the other hand, the community probably have been bypassing this simple cache from long time ago with their own solution or 3rd party packages from nuget, if this is the case, then ignore me)

4, Having looked at code with ilspy I agree with you that it can't be ported as is. Was it because the touching of WinInetCache win32 stuff?

**Comment by davidsh** [comment]
>1, what is the reasoning to have this simple cache when you designed HttpWebRequest API? Is that for performance?

The HttpWebRequest and System.Net.Cache APIs were designed a long time ago (2001 era).  The caching part was done for the usual reasons....to speed up performance for some use cases.  This is similar to why browser cache results.  There are always pros and cons to caching.  For a developer API, it was important to provide choices.

>2, with the new stack (System.Net.Http) what is the reasoning to no longer want/need this? Is that also because perf (i.e. the new stack is very fast, use very little resource, etc. so caching no longer help a lot... thus it can be safely ignored)

We could not port the existing System.Net.Cache.  The architecture did not fit the new HTTP stack architectures. In addition, the object model did not fit our vision for how we wanted to evolve the APIs

The newer System.Net.Http APIs support a "chain" of handler model making it easy to developers to provide custom behavior for the entire request/response chain.  Developers can build in caching logic, retry logic, etc. by creating custom handlers.

>3, if caching still somehow can contribute a lot to perf/resource usage, now the decision is this is now offloaded to us, no longer offered out of box. If so some documents/example would be great helps for the community. (On the other hand, the community probably have been bypassing this simple cache from long time ago with their own solution or 3rd party packages from nuget, if this is the case, then ignore me)

There are some blog articles available that describe how to create custom handlers for System.Net.Http.  See for example.

http://www.asp.net/web-api/overview/advanced/http-message-handlers

https://blogs.windows.com/buildingapps/2015/11/23/demystifying-httpclient-apis-in-the-universal-windows-platform/

>4, Having looked at code with ilspy I agree with you that it can't be ported as is. Was it because the touching of WinInetCache win32 stuff?

The existing implementation of System.Net.Cache using the Wininetcache apis (for Windows) was using outdated Winet APIs.  And since CoreFx is x-plat, there is no quick alternative for Linux, OSX. And in terms of service architectures, the use of Wininet is not optimized for high-scale service environments like ASP.NET.

**Comment by stephentoub** [comment]
It looks like the questions have been answered, so I'm closing this.  Please re-open if the questions aren't yet resolved. Thanks.
