### ISSUE TITLE
Array.IsNullOrEmpty()

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#6069]
In corefx the method string.IsNullOrEmpty as a replacement to checking if a string is null and has a length of 0.

Maybe we should have a similar API for Array that is implemented in the exact same way for string

This has the same associated benefits that string.IsNullOrEmpty has: more readability, less prone to errors etc.

**Comment by stephentoub** [comment]
What's the scenario for this?  It's very common in code to need to do:
```C#
if (str == null || str.Length == 0) { ... }
```
or the opposite:
```C#
if (str != null && str.Length > 0) { ... }
```
hence the usefulness of ```string.IsNullOrEmpty```.

But it's much more rare to need to do:
```C#
if (array == null || array.Length == 0) { ... }
```
Etc.  I'm sure it comes up now and again, but at least in my experience not nearly frequently enough to warrant a new API.

**Comment by rvhuang** [comment]
Already wanted this method hundreds years ago. It's quite annoying that I need to add this utility to every project I'm working on.

**Comment by stephentoub** [comment]
@rvhuang, can you share some examples of why it's so impactful?

**Comment by NickCraver** [comment]
I'm also curious on the use cases here. Most of the time in our code you're interested in the presence of objects you need to take action on rather than the absence. In that regard, C# 6 greatly improves this:

```C#
if (array?.Length > 0) { ... }
```

**Comment by rvhuang** [comment]
@stephentoub In reality, libraries from internal developer teams or third parties do not quite respect the convention about returning empty array instead of null reference for no result. For those people who are working on integration, a method for checking if array is null or empty is truly needed.

**Comment by stephentoub** [comment]
Can you share some examples, though?  The difference between:
```C#
if (arr == null || arr.Length == 0)
```
and:
```C#
if (Array.IsNullOrEmpty(arr))
```
is so minimal, IMO this would have to be an extremely, extremely common case for it to warrant new surface area on a core type like Array, and I'm not seeing it being so common that's warranted.

**Comment by JonHanna** [comment]
If the only .NET language was C# 6, would we even bother to have `string.IsNullOrEmpty()`? It's got no advantage over `str?.Length == 0` except for the matter of the latter not working for over a decade :wink:

What value `Array.IsNullOrEmpty()` would once have had for people using C# or VB, it no longer really has.

**Comment by MgSam** [comment]
`Array.IsNullOrEmpty` isn't really that useful as it only applies to arrays. `ICollection.IsNullOrEmpty` is far more useful. I always keep this around as an extension method to `ICollection`. 

It's extremely useful because any time you are passed a collection as a parameter, you need to properly validate it before doing any real work. Yes, you could write `if (arr == null || arr.Length == 0)`, but that doesn't read nearly as well as `if(arr.IsNullOrEmpty()) ... `

That being said, I don't think the framework has shipped any extension methods on `ICollection` as of yet, so whether or not to do so is probably a bigger discussion.

**Comment by stephentoub** [comment]
Thanks for the suggestion.  Given that ```array?.Length > 0``` is even less code than ```!Array.IsNullOrEmpty(array)```, that the general pattern works with collections as well, and that adding new APIs to a core type like Array requires significant justification, I'm going to close this out.  Thanks for the discussion.

**Comment by MgSam** [comment]
@stephentoub C# is not the only language that targets the .NET framework, and this feature only applies to the latest version of C#. Should you be making framework decisions based solely on features in the latest version of a single language?

**Comment by stephentoub** [comment]
Even without the language feature, best case such a new API saves you just a few characters, as I noted in my previous response... C# language support that makes it even nicer is just icing on the cake.  I simply do not see the value here being so great as to warrant such new APIs.
