### ISSUE TITLE
Negotiate Stream on Unix does not fail with invalid target

### ISSUE THREAD

**Issue by kapilash** [dotnet/corefx#6114]
```NegotiateStream.AuthenticateAsClientAsync```  does not fail for invalid target.

**Comment by vijaykota** [comment]
There seems to be some odd behavior in ```gss_init_sec_context``` When an invalid target is passed to it ie. a target for which Kerberos ticket cannot be obtained, the API still returns success. We need to investigate if there is a way to detect this in the shim and return an error to the managed layer

**Comment by vijaykota** [comment]
@kapilash I am seeing in my sample program that AuthenticateAsClientAsync is failing as expected with ```AuthenticationException``` because second call to gss_init_sec_context failed. So I believe the fix is only in the test case used in #6139 . Since the exception is in EndProcessAuthentication and not BeginProcessAuthentication like in invalid creds case, we need an ```Assert.ThrowsAsync```

Please reopen the issue if you are seeing different behavior.

**Comment by kapilash** [comment]
That worked. Thanks @vijaykota
