### ISSUE TITLE
Suspicious timeout computations in System.Data.SqlClient.SqlInternalConnectionTds

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/corefx#6115]
`System.Data.SqlClient.SqlInternalConnectionTds` has `LoginNoFailover()` and `LoginWithFailover()` methods which differently compute `timeoutUnitInterval`.
`LoginWithFailover()` does this:

    if (timeout.IsInfinite)
    {
      timeoutUnitInterval = checked((long)ADP.FailoverTimeoutStep * ADP.TimerFromSeconds(ADP.DefaultConnectionTimeout));
    }
    else
    {
      timeoutUnitInterval = checked((long)(ADP.FailoverTimeoutStep * timeout.MillisecondsRemaining));
    }

and `LoginNoFailover()` does this:

    if (timeout.IsInfinite)
    {
         timeoutUnitInterval = checked((long)(ADP.FailoverTimeoutStep * (1000L * ADP.DefaultConnectionTimeout)));
    }
    else
    {
          timeoutUnitInterval = checked((long)(ADP.FailoverTimeoutStep * timeout.MillisecondsRemaining));
    }

`else`-branches are exactly the same. Yet one `if` branch uses `TimerFromSeconds()` which returns number of ticks for given number of seconds and another uses multiplication by one thousand.

Why the difference?

**Comment by saurabh500** [comment]
@Dmitry-Me in case of the connections which are using MultiSubnetFailover flag relevant for AlwaysOn Availability Group, we want to start with a lower timeout the connectivity.

In case there is a failure in the connection due to the failover, we want the retry to be faster in case of MSF with AlwaysOn AG.
