### ISSUE TITLE
Referencing .NET Core project to the regular .NET csproj

### ISSUE THREAD

**Issue by zemstaspamera** [dotnet/corefx#6124]
Hello,

Is there any way to reference project created with .NET Core (dnxcore50 and dnx451) to regular C# project, for example WPF? I found a [proposition](https://github.com/NullVoxPopuli/csharp-extensions/blob/2767e8ae87dcc69a14d1a33fd63b9eef364ee1ec/project.json).which probably allows me to do what I want. However, is referencing a "net46" framework a good solution? I have not seen that before.

I'm asking because I preparing a strategy for API for corporate services based on Desktop apps and I would like to make it available also on Linux. 

Thanks for help.

**Comment by weshaggard** [comment]
@Pilchie I assume this is a question for your team.

@zemstaspamera we do hope to enable this scenario but with the current VS tools it is a little rough.

**Comment by manu-silicon** [comment]
I've build a way to do that. Check out: https://github.com/manu-silicon/corefxref. It will enable you to compile against the relatively recent version of CoreFX reference assemblies. However I'm not sure if you will be able to mix this with WPF as WPF may rely on APIs not yet present in CoreFX.

**Comment by Pilchie** [comment]
I think there are a couple of different things here that are being conflated:

* The version of the framework that the project itself is targeting.  In a project.json/xproj project this is listed in the `frameworks` section of the project.json.  It's perfectly fine to set it to something like `net46` to target the .NET Framework, version 4.6, and use WPF.  NOTE however, that this means you are NOT targeting .NET Core, and your won't support running cross platform on Linux, OSX, etc.  NOTE Also, that this means that you can't upgrade .NET packages that contain types that are part of .NET 4.6, since they will be resolved from the GAC at runtime.  If you can use only code that is supported in .NET Core, then we'd recommend using one of the `netstandard` versions described [here](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md), with the unfortunate caveat that they aren't supported quite yet, but they should be in the next release of the .NET Core tools.
* The ability to reference an existing .csproj project from a project.json/xproj project.  This is already possible, but works in a less than ideal way by creating a "wrapper" project.json around the .csproj.  We're working on a plan to make this a much nicer experience.  We're hoping to include this updated tooling in that next release of the .NET Core tools as well.
* The ability to reference a project.json/xproj project from a .csproj project.  This doesn't work today, but we have enabled it in that next version of the .NET Core tools.  This allows you to write cross-platform libraries targeting `netstandard` using project.json/xproj, and then have desktop specific apps built on top of them using .csproj for WPF, etc.

Hope this helps.  @davidfowl - anything I've missed?

**Comment by rolfik** [comment]
@Pilchie, 
> The ability to reference a project.json/xproj project from a .csproj project.
It is possible now via nuget package created from xproj, but only when You do not have the xproj and csproj project folder in the same parent folder or solution, because then "project reference to xproj" wins over "nuget package reference to xproj" and it cannot be overriden by let us say `type` attribute of the dependency in `project.json`.
Or is there a way to do it somehow?

When will be the next release of .NET Core tools (CLI?) released?

**Comment by jnm2** [comment]
How soon until I can reference an xproj project in the same solution as a full framework csproj?
Is that going to be part of the xproj -> csproj msbuild work?

It's a big holdup. Xproj is the only option atr the moment because the core library needs muti-targeting. (ECDsaCng has been available on full framework since .NET 3.5 but isn't available until `netstandard1.4`, and the top-level GUI client is `net452` so I can't use a single-target `netstandard1.2` PCL csproj.)

**Comment by Pilchie** [comment]
Tagging @davkean and @srivatsn.

**Comment by srivatsn** [comment]
Yes, once .NET Core projects are csproj based then you should be able to reference them from a full framework csproj. That work is being tracked by https://github.com/dotnet/roslyn-project-system/issues/282

**Comment by mellinoe** [comment]
We recently added [this document](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/target-dotnetcore-with-msbuild.md) which describes how you can set up cspoj's now to accomplish what you want. Keep in mind that it's fairly manual and easy to mess up right now.

**Comment by jnm2** [comment]
@mellinoe Slightly confused- which project gets this edit? The multi-target xproj or the full framework csproj?

**Comment by mellinoe** [comment]
For a class library, use the instructions at the top of the document. The `StartAction` stuff would just be for Exe projects, so not applicable in your case. And, yes, you wouldn't be modifying your .NET framework project, except potentially to make it use project.json for dependencies.

**Comment by jnm2** [comment]
The instructions at the top of the document don't seem to address the scenario where I need to target both `netstandard1.4` and `net45`. Need `ECDsaCng` in the class library whether I'm using it with a core app or a full framework app.  Am I wrong in thinking the class library needs to be xproj for that? In which case I can't use csproj?

**Comment by mellinoe** [comment]
In your case, you would probably end up having two csproj's, one for each configuration (net452, netstandard1.4). You could share common includes in a shared build file as well, if you wanted. Technically you could combine them into one file, but it would probably quickly get messy and would require lots of manual fiddling with project configurations.

This probably isn't buying you much in your particular case since you need to specifically target net452.

**Comment by jnm2** [comment]
I don't mind hacking a csproj and eschewing tooling, but maintaining two project file lists is unappealing. I'll wait then until I'm able to target both netstandard1.4 and net45 in a single csproj.

**Comment by gulbanana** [comment]
is that feature (multi-targeting from a csproj with tooling support) planned? seems a bit different to the original question of csproj->xproj references. of course it'd be great to have both.

**Comment by jnm2** [comment]
Well xproj is gong away entirely, right? And multi-targeting isn't, so it would end up in csproj, right?

**Comment by srivatsn** [comment]
Yes it's tracked here - https://github.com/dotnet/roslyn-project-system/issues/190

**Comment by gulbanana** [comment]
excellent

**Comment by karelz** [comment]
Closing, it does not look like there is anything left for corefx discussion. Work is tracked in Roslyn.
