### ISSUE TITLE
(question) How do you guys override the project.json location based on the target platform?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#6169]
Waiting for the build tools to restore right now, so I figured I would ask this question.

I'm just curious to know how you guys can do something like [this](https://github.com/dotnet/corefx/blob/ab6ec2fa803a330e73809cf478753959a36185e5/src/System.Diagnostics.Contracts/src/System.Diagnostics.Contracts.csproj#L20) in MSBuild:

```xml
<PropertyGroup Condition=" '$(TargetGroup)' == 'netcore50aot' ">
    <ProjectJson>netcore50aot\project.json</ProjectJson>
</PropertyGroup>
```

and have the `project.json` associated with your csproj file change from the top-level one to the one in `netcore50aot/`.

I've tried doing the [same thing](https://github.com/jamesqo/typed-xaml/blob/c9dad9a95687c6ce2908ba3e46f60501f785cad1/src/Typed.Xaml/Typed.Xaml.csproj#L71) as you guys are doing above in my project, but it doesn't seem to be working. I assume it's because one of the imported MSBuild projects in your repo does something with the `$(ProjectJson)` value, but I haven't been able to pinpoint exactly where that happens. Can you help?

**Comment by mellinoe** [comment]
I believe the logic is here:

https://github.com/dotnet/buildtools/blob/6e0874e84f77486e83cb60be99966377b09319a5/src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets

But I'm having trouble remembering how exactly this interacts with the built-in MSBuild targets for NuGet package asset resolution.

**Comment by jamesqo** [comment]
@mellinoe Thanks! Finally got it working using the link you posted, like this:

```xml
<Target Name="BeforeBuild">
  <PropertyGroup>
    <DnuRestore>dnu restore</DnuRestore>
    <PackagesDirectory>packages</PackagesDirectory>
  </PropertyGroup>
  <Exec Command="$(DnuRestore) $(ProjectJson) --packages $(PackagesDirectory)" />
</Target>
```

But yeah, as you mentioned, MSBuild is having a bit of trouble picking up on the references. When I compile the project, I'm getting a lot of 'type not found' errors.

**Comment by mellinoe** [comment]
It looks like the above will run restore on the project.json file that you want, but you will still need to point MSBuild to the lock file to use. I'm not 100% sure if there's an easy way to do that with the built-in NuGet targets. Did you try setting ProjectLockJson as well?

**Comment by jamesqo** [comment]
@mellinoe Ah, that must be my problem then. I have set `ProjectLockJson`, but I don't know what to do with it. Here's my full code at the moment: https://github.com/jamesqo/typed-xaml/blob/master/src/Typed.Xaml/Typed.Xaml.csproj#L77

**Comment by mellinoe** [comment]
`ProjectLockJson` is what we pass into our "PrereleaseResolveNuGetPackageAssets" target to harvest the references for your project:

https://github.com/dotnet/buildtools/blob/6e0874e84f77486e83cb60be99966377b09319a5/src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets#L77

From what I understand, there is a version of this target included with the in-box MSBuild targets (called "ResolveNuGetPackageAssets"), but the property `ProjectLockFile` is used instead of `ProjectLockJson`. Perhaps try setting both of them and see what happens? You may also be able to turn on diagnostic logging and see what parameters are passed into the ResolveNuGetPackageAssets target. That would probably give you a good idea of what's going on.

@ericstj Would be able to better answer your questions, but he's out for this week. I'm roughly familiar with how these targets work, though.

**Comment by jamesqo** [comment]
Thanks for helping. I was too lazy to create a custom MSBuild task, so I ended up creating a bunch of `csproj` files and linking them the old-fashioned way.
