### ISSUE TITLE
Infinite loop in dynamic dispatch code when calling through contravariant delegate

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/corefx#6258]
When upgrading from 23803 to 23818 of System.Linq.Expression.dll we are now seeing an infinite loop in the dynamic dispatch code. I have not been able to come up with a minimal repro that I can attach to this bug, but I have a trivial one that I can email anyone who wants it. In the bug we are calling into a delegate of type Action<... my-class>, and the target of the delegate uses an interface for the last argument. If I change the delegate to also use an interface, the issue goes away.

The infinite loop is in code labeled as 'Lightweight Function' by the managed debugger:

`System.Dynamic.Runtime.dll!System.Runtime.CompilerServices.CallSiteBinder.BindCore<System.Action<System.Runtime.CompilerServices.CallSite, System.Action<string, object, OpenDebug.DispatchResponder>, string, object, OpenDebug.DispatchResponder>>(System.Runtime.CompilerServices.CallSite<System.Action<System.Runtime.CompilerServices.CallSite, System.Action<string, object, OpenDebug.DispatchResponder>, string, object, OpenDebug.DispatchResponder>> site, object[] args) Line 133` <-- This function is called infinately
 `[Lightweight Function]` **<-- Hang here**
`OpenDebugAD7.dll!OpenDebug.DispatcherProtocol.Dispatch(string req)` <-- My code calling delegate.Invoke

Looking at the stack in Windbg, I think Windbg gives the method this name:
`26 00000027`ac5fec80 0000019d`bcc88cc8 DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Action'3<System.String,System.Object,OpenDebug.DispatchResponder>, System.String, System.Object, OpenDebug.DispatchResponder)+0x2c2`
 
This looks similar to #5610, but I should have the fix for that and I am still seeing the problem.

**Comment by stephentoub** [comment]
cc: @VSadov, @JonHanna

**Comment by JonHanna** [comment]
Could you put that trivial repro into a gist?

**Comment by gregg-miskelly** [comment]
I sent it to @VSadov. The repro contains some software that I am not allowed to release outside of Microsoft quite yet (I couldn't figure out how to come up with a totally stand alone repro, so it contains all of the code for the project I am working on). VSadov may be able to figure out what bits actually matter.

**Comment by JonHanna** [comment]
In that case you won't be able to email it to me anyway. Is it that the delegate is dynamic, the call, or both?

**Comment by gregg-miskelly** [comment]
The delegate has this signature:
Action<string, dynamic, MyClass>
The function that is the target of the delegate has this signature:
(string, dynamic, IInterface)
Where MyClass derives from IInterface

**Comment by VSadov** [comment]
Here is a small attempt to repro that I could infer from the binaries.
I did not try to repro on actual CoreFx, but I think it will repro.

I think the issue here is that we've added an optimization based on incorrect assertion that if static Expr type is sealed it is guaranteed to have values of only that type.
That is inaccurate because of delegate variance. Delegate types are sealed but could yet be assignment compatible.

```C#
    class Program
    {
        class C1 : ICloneable
        {
            public object Clone()
            {
                throw new NotImplementedException();
            }
        }

        private static Action<string, dynamic, C1> a;
        // the following change fixes the problem
        // private static Action<string, dynamic, ICloneable> a;

        private static void Foo(string s, dynamic d, ICloneable s1)
        {
            System.Console.WriteLine("hello");

            // static type
            System.Console.WriteLine("expr type: " + typeof(Action<string, dynamic, C1>));

            // dynamic type
            System.Console.WriteLine("actual type: " + a.GetType());

            // is it sealed?
            System.Console.WriteLine("issealed: " + typeof(Action<string, dynamic, C1>).IsSealed);

        }

        private static void Init()
        {
            Action<string, dynamic, ICloneable> del = Foo;        
            a = del;
        }

        static void Main(string[] args)
        {
            Init();

            dynamic arg = "ww";

            a.Invoke("qq", arg, new C1());
        }
    }
```

**Comment by JonHanna** [comment]
You're correct about the incorrect assumption, except it wasn't so much added as believed.

The assumption was in there from when the project was first added to corefx (you can see this in .NET 4.6, but if experimenting don't have the delegate in a `ConstantExpression` as that takes a different path), but would only result in false positives. When d5e3d82 fixed a different false assumption about nullable types at the same spot it "improved" the use of that assumption so that it would result in false negatives too, and this case hits that false negative getting a `false` when it should get a `true` and AFAICT keeps fixing up a call that doesn't need fixing up, forever.

#6273 removes special handling of sealed reference types entirely. It would be possible to add a check on delegate types but I'd rather remove a special case and just have `GetType()` called than special-case part of the special case because it wasn't that special after all and later hit yet another exception to the "rule".

**Comment by JonHanna** [comment]
Example test on .NET 4.6 (hence unaffectd by d5e3d82).

```C#+
Action<object> ao = x => { };
Action<string> a = x => { };
Action<string> b = ao;

var param = Expression.Parameter(typeof(Action<string>));

Func<Action<string>, bool> isActStr = Expression.Lambda<Func<Action<string>, bool>>(
	Expression.TypeEqual(param, typeof(Action<string>)),
	param
).Compile();

Console.WriteLine(isActStr(ao)); // True, should be False
Console.WriteLine(isActStr(a)); // True, correctly.
Console.WriteLine(isActStr(b)); // True, should be False

**Comment by VSadov** [comment]
Yes. I agree that original code also had this issue just manifested in another way - false positives vs. negatives.
I wonder if it is ok from compat prospective to fix the original bug though.

**Comment by JonHanna** [comment]
That certainly occurred to me when I looked at this. In particular the thought that I could "fix" it, and not actually fix @gregg-miskelly's issue in doing so did. I'm keen to hear that my repro is representative and it really is fixed.

I have a backward compatibility branch in my local repository that has the old behaviour, if necessary.

Note that the light compiler does not use `ReduceTypeEqual` at all and has behaviour matching that after #6273 is applied (just calling `obj != null && obj.GetType() == type` is simpler in the interpreter, which is cheaper depends on the number of calls to the produced delegate per compilation). Am I right in thinking that UWP uses the interpreter by default? If it turns out we have a backwards-compatibility problem with this, then we also cross-compatibility problem and will need to either weed out the cases that depend on the old behaviour or make the interpreter bug-compatible.

(And that's assuming there are no other issues with `ReduceTypeEqual`. Having so far found a false assumption [#5272], introduced a false assumption of my own [#5610] and extended the scope of a false assumption [here], I'm not going to just assume I'm not missing something else; that would be the worse assumption of all).
