### ISSUE TITLE
PostNonRewindableContentUsingAuth_NoPreAuthenticate_ThrowsInvalidOperationException failed in CI

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#6268]
See the failure [here](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_debug_tst_prtest/2123/testReport/junit/System.Net.Http.Functional.Tests/PostScenarioTest/PostNonRewindableContentUsingAuth_NoPreAuthenticate_ThrowsInvalidOperationException_serverUri__http___corefx_net_cloudapp_net_Echo_ashx_auth_basic_user_user1_password_password1_/).  Maybe this is due to a network hiccup?

**Comment by stephentoub** [comment]
> Maybe this is due to a network hiccup?

That's what I thought initially, too, but no, I caused this with #6250, and I have a fix out in #6269.  While wrapping some exceptions in IOExceptions to store them into the tasks returned from Stream.Read/WriteAsync, I wrapped one too many, including one that's only consumed internally by CurlHandler.  For exceptions other than those emerging from Stream, CurlHandler has logic based on WinHttpHandler to wrap IOExceptions in HttpRequestExceptions, and by wrapping the InvalidOperationException in an IOException accidentally, it then got wrapped again by an HttpRequestException.  There was then a race between the original InvalidOperationException getting stored in one place and the doubly-wrapped HttpRequestException getting store in another, causing these random test failures due to the wrong exception type.
