### ISSUE TITLE
MemoryMappedFileTests_CreateFromFile.TooLargeCapacity failing on RedHat 7.2

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#6279]
This fails all the time, see http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/rhel7.2_debug/

```
06:00:00    System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateFromFile.TooLargeCapacity [FAIL]
06:00:00       Assert.Throws() Failure
06:00:00       Expected: typeof(System.IO.IOException)
06:00:00       Actual:   (No exception was thrown)
06:00:00       Stack Trace:
06:00:00             at System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateFromFile.TooLargeCapacity()
```

**Comment by stephentoub** [comment]
I'm not sure what to do about this one.  The test is trying to set the size of the map to long.MaxValue and is expecting it'll fail because that's larger than the biggest possible file size.  But on RHEL, it's succeeding, and querying the length subsequently with fstat reports the file's size is 9,223,372,036,854,775,807 bytes... unless we've made some serious upgrades to our VMs, that seems, um, unlikely.

**Comment by ellismg** [comment]
I wonder if there is just a bug in the underlying OS libraries?

**Comment by stephentoub** [comment]
It looks like the issue is that ftruncate is essentially creating a sparse file.  You can see this with a simple little C program:
```C
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>

int main(int argc, char** argv)
{
    int fd = open("blah.dat", O_RDWR | O_CREAT);
    printf("%d\n", fd);
    int rv = ftruncate(fd, 9223372036854775807);
    printf("%d\n", rv);
    rv = close(fd);
    printf("%d\n", rv);
}
```
The file created then has a large size but 0 blocks associated with it:
```
$ stat blah.dat
  File: ‘blah.dat’
  Size: 9223372036854775807     Blocks: 0          IO Block: 4096   regular file
Device: 802h/2050d      Inode: 2981949     Links: 1
Access: (0330/--wx-wx---)  Uid: ( 1000/dotnet-bot)   Gid: ( 1000/dotnet-bot)
Context: unconfined_u:object_r:user_home_t:s0
Access: 2016-02-22 03:09:55.603252499 +0000
Modify: 2016-02-22 03:09:55.603252499 +0000
Change: 2016-02-22 03:09:55.603252499 +0000
 Birth: -
```
It looks like we could address this by having FileStream.SetLength use ```posix_fallocate```.  But I'm not sure we really want to force all of the space to be allocated... we may simply want to rack this up to being a bad test, or at least special-case it for RHEL.
