### ISSUE TITLE
Bug setting host to partial IPV6 address in UriBuilder

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#6351]
## Problem

This is the code for the setter of a host in UriBuilder:

```c#
public string Host
{
    get { return _host; }
    set
    {
        if (value == null) value = string.Empty;
        _host = value;
        //probable ipv6 address - Note: this is only supported for cases where the authority is inet-based.
        if (_host.IndexOf(':') >= 0)
        {
            //set brackets
            if (_host[0] != '[')
                _host = "[" + _host + "]";
        }
        _changed = true;
    }
}   
```

The setter for `UriBuilder.Host` checks to see if an IPV6 address has been provided. It follows the following alogrithm
- If the host is an IPV6 address and has does not start with a square bracket, add square brackets around the host.

The problem occurs when the host already has a square bracket at the end, but not at the start.
## Example

```
UriBuilder uriBuilder = new UriBuilder();
uriBuilder.Host = "::1]";
uriBuilder.Host; // Expects "[::1]" but gets: "[::1]]"
```
## Solution

Change the code to:

```
if (_host[0] != '[')
    _host = "[" + _host;
if (_host[host.Length - 1] != ']')
    _host = _host + "]"
```

This does have breaking change implications, and may be considered an unnecessary change, as the input host string is invalid, so strange behavior could be expected.
If fixing this seems like a good idea, I will submit a PR fixing it.

**Comment by davidsh** [comment]
Allowing this to succeed is a bug:

```c#
UriBuilder uriBuilder = new UriBuilder();
uriBuilder.Host = "::1]";
```

But I'm not sure if/when we can fix due to app-compat concerns.  We will need to review.

**Comment by karelz** [comment]
@hughbe sorry for not getting back to this issue earlier.
As said above, the type is extremely sensitive to breaking changes. If we fix it only in .NET Core, we will diverge behavior between platforms for portable libraries, which is not great either.

So the question is: How impactful is the bug? What happens if we reject it? Are there real-world examples of code which suffer from this?

**Comment by hughbe** [comment]
No problem, I've been busy too.

I understand the breaking change point. I think the problem here was slightly misunderstood. UriBuilder doesn't reject any value of the Host, and I don't think it should ever reject something like "::1]" for compat reasons.

This issue covers the fact that setting the host to "::1]" incorrectly transforms the new value, and sets host to "[::1]]"

I think it would make sense for UriBuilder not to modify the input in this case, rather than attempt to correct it to "[::1]". I also thought this would make it consistent with the input "[::1"

I.e. 

```
UriBuilder uriBuilder = new UriBuilder();
uriBuilder.Host = "::1]";
uriBuilder.Host; // Expects "::1]" but gets: "[::1]]"

uriBuilder = new UriBuilder();
uriBuilder.Host = "[::1";
uriBuilder.Host; // Expects "[::1" gets: "[::1"
```

That said, this is quite impactless, so I'd understand it might be an unecessary deviation from the full framework

**Comment by karelz** [comment]
Disclaimer: I am not expert on URI/URL spec, this is the first time I even see "[...]" syntax. I just assume it is supposed to be well-formed (using common sense, nothing else) and that's how I judge valid vs. invalid input. If that's wrong, feel free to call me out on it - I will happily readjust my view points.

@hughbe your last reply says something different than what you originally proposed (in the solution section). Your original solution would turn invalid "::1]" into valid "[::1]" and invalid "[::1" into valid "[::1]".
In your last reply you suggest to not touch invalid inputs (ending with ']', but not starting with '[') and leave them as they are instead.
Did I understand your proposal(s) correctly?

Popping one level up:
Your original proposal turns some invalid inputs into valid with your fix (they stay invalid with today's code). You second proposal suggests to leave invalid inputs intact.

Regarding your original proposal: We could take it from compat point of view as we do not have to be bug-by-bug compatible with .NET Framework. However, there's a risk some customer code depends on the fact that invalid input will not be automagically fixed into valid input ... probably low chance, but still a chance.
I am questioning value of such automagic fixing. Given there is not a real-world usage, I would suggest to NOT take it -- 0 benefit is just not worth even a little risk. It might also send the wrong message that `UriBuilder` is trying to fix incorrect inputs, encouraging more fixes in that direction.
BTW: Even today's code adds '['/']' around the URI which is IMO already somewhat "bad", I would suggest to not go deeper in that direction of autofixing wrong inputs.

Your second proposal (leave invalid input invalid) is basically removing part of the automagic fixing for invalid inputs. Compat with .NET Framework is fine here. We will likely not break anyone with the change (it still stay invalid). But it comes back to: why, should we fix it at all? What is the value? ... I see nearly none (beside general "goodness").
Just from that perspective I would NOT take the change on the basis that there is 0 benefit and there's super-low risk that any change can have unanticipated impact.
For context: Statistics from CLR code over the 10+ years say that 10% of all changes (no matter how small, well code reviewed by many strong engineers, considered safe & non-breaking, or done by the best/most experienced engineers on team), have unexpected side effects, especially in code which is known to be "sensitive" (e.g. UriBuilder, Fusion binder, etc.) - the side effects are often so small it does not matter and the upstream code can change and adjust they may be even discovered years after the code change, but it often causes someone at some point to investigate and dig through things, etc. It wastes time (at least hours or days). That's why we tend to discourage even very-low-benefit code changes in general. It's just not worth it ... (sometimes it's just not even worth the time spent in the discussions, code review, etc. ;-))

So to sum it up: Unless we have some non-trivial benefit (in real-world code), I don't think it is worth to take the change here (given the type is known to be "sensitive").

BTW: Just theoretically for completeness: If the type wasn't "sensitive", I would be more on the edge to take it / reject it. In such case my main argument for 'no' would be: Can we rather focus on things that actually do help customers and make the product better?
That means, if someone in community would really, really, really push for taking the fix, I would rather give up and take it, given there is no big harm to the change (assuming the code is not "sensitive"), just to prevent wasting time in discussions.
BTW: I should probably put this general guidance into our docs as explanation why we take / reject changes ;).

Feel free to push back if you think I am wrong either on specifics for this bug, or in the general approach (both are valuable to clarify).

**Comment by hughbe** [comment]
Thanks for spending the time considering and understanding this issue. I agree that the first proposal shouldn't be taken on the grounds of its unexpected consequences. The second one doesn't have as many, but I also agree that goodness for goodness's sake is pointless and wastes time. 

I'll close this - thanks for the time spent on it again

**Comment by karelz** [comment]
Thanks for understanding.
I'll make sure to include the general info in our contributions docs, so that it is easier to reference in future. It is IMO valuable to keep track of valuable background / context of "how to think about changes, compat, etc.". And I bet we will find more valuable guidance/context like that in future ...

**Comment by hughbe** [comment]
I'm sure you've realised, but obviously things like this start to complicate and reduce scope for external contributions. I assume some people might assume bugs are features, and either won't report or fix them

**Comment by karelz** [comment]
@hughbe I am not sure how you ended up with that impression or if I understand it properly. Can you please provide more details?

My view point is that few types are sensitive, and those will be hard to modify. However, vast majority (99.9%) of repo is open for almost any bug fixes, API additions, etc. I don't think we are discouraging anyone from contributions or bug reports. Just setting some expectations / having copy-pastable/linkable explanations of background handy.
At the end of the day it is more guidance: If you suggest a change, ideally think it through from all angles (or be prepared it will get that scrutiny) and ideally explain benefit of such change (or expect to be asked about it if in doubt). That IMO doesn't sound too discouraging.
Or did I miss anything important?

**Comment by hughbe** [comment]
Oh no, I haven't ended up with that impression. I just wanted to say I think its important in the documentation to emphasize that some areas are sensitive, whilst making clear bug fixes are welcome in less sensitive areas

**Comment by karelz** [comment]
Got it. And agreed that it has to be properly clarified - I will keep that in mind :). Thanks!
