### ISSUE TITLE
Integrate BouncyCastle into CLR Core and CoreFX

### ISSUE THREAD

**Issue by KOLANICH** [dotnet/corefx#647]
[BouncyCastle](http://www.bouncycastle.org/csharp/) is a free crypto library which implements a lot of functionality missing in System.Security.Cryptography. But it was designed in that way that they don't use System.Security.Cryptography at all and a lot of crypto primitives are reimplemented there and designed not in the best and optimal way. Also its API is not very convenient.
It is bad because better to have one implementation relying low level libraries and drivers to achieve better security and performance than a lot of different implementations with different APIs and which are incompatible with each other. For example, BC supports OpenPGP keyrings, System.Security.Cryptography doesn't and if I want to use OpenPGP-compatible crypto I have to use BC instead of System.Security.Cryptography.

So I think we should merge BC and System.Security.Cryptography. Both these projects use MIT licenses (BC uses ["an adaptation of the MIT X11 License"](http://www.bouncycastle.org/csharp/licence.html)), so I think there will be no licensing problems.

[Issue on BC bug tracker](http://www.bouncycastle.org/jira/browse/BMA-131)
[Issue on CoreCLR bug tracker](https://github.com/dotnet/coreclr/issues/74)

**Comment by Alexx999** [comment]
I believe it's not that easy with crypto - it needs all sorts of validation/verification/certification to be sure it works as expected (and has no side effects at all).
For bright example - remember that famous heartbleed thing. And that's with lib that is used everywhere.

Plus - why should it be part of CoreFx at all and not separate library?

**Comment by KOLANICH** [comment]
>I believe it's not that easy with crypto - it needs all sorts of validation/verification/certification to be sure it works as expected (and has no side effects at all).
Aggree with it. Audit is needed in any case because BC is one of the most used .net crypto libs. But audit and certification is not panacea (Dual EC DRBG is example).

>Plus - why should it be part of CoreFx at all and not separate library?
Why should System.Security.Cryptography be part of CoreFx at all and not separate library? By the same reason BC should be.

**Comment by RichiCoder1** [comment]
:+1: 
It's not unusual in the general language community for something to be developed separate or in addition to official libraries, and later get merged in because it adds a lot of value. I'd be all for merging it in, especially since .Net Core is more agile than .Net Framework.

**Comment by KOLANICH** [comment]
It was not developed in addition, it is a separate library ported from Java.

**Comment by Alexx999** [comment]
@KOLANICH Basically, CoreFx is now just a set of libraries that is developed and maintained by Microsoft.
Personally I think that having multiple APIs to do same tasks is confusing - look at XML, it has fairly high learning curve (you start looking here and there and all samples do it in different ways), plus it's hard to choose approach and sometimes it gets pretty bad when it turns out that your chosen approach lacks at some area since it's hard to make a switch.

I believe that better approach to start with is adding to current .NET CryptoAPI things that are missing now - so, we need list of thing that are present in BC but are not present in current API

**Comment by RichiCoder1** [comment]
@KOLANICH Hence why I said "seperate or in addition too" :).
@Alexx999 Agreed. I don't think @KOLANICH was suggesting a wholesale merge, but a smart absorption of functionality.

**Comment by Alexx999** [comment]
@RichiCoder1 Then we need some more info - I tried using CryptoAPI and succeeded back some time. It's hard to use - maybe, but crypto in general requires developer to know what he's doing.
Probably my point of view is a bit biased here due to my "OK" experience with crypto in .NET, and no experience with BC, so I'm asking - what's so great out there to adopt?

**Comment by KOLANICH** [comment]
>Personally I think that having multiple APIs to do same tasks is confusing

That's why we need to merge the API. We need
1 design additions to current MS API
2 implement the functionality using BC implementation
3 reimplement the functionality using low level protectons, and existing functionality
4 reimplement BC to make it rely on clrcore

**Comment by RichiCoder1** [comment]
@Alexx999 This is were I'll admit ignorance. I've only ever worked with developers who have been forced to utilize BouncyCastle to address .Net's shortcomings, so I don't have first hand experience. I do know that BC covers more variations of crytography and I believe it also provides more flexibility and ease-of-use for varations that exist with in the BCL.

I would agree with @KOLANICH

**Comment by shahid-pk** [comment]
@KOLANICH 
This can make a good api addition proposal. You should come up with an API addition proposal , following the guidelines given in contribution guidelines.

**Comment by scalablecory** [comment]
:+1: I think your end-goal -- that .NET's crypto support not be so limited -- is a good one.

**Comment by rpetrusha** [comment]
The .NET Framework team is currently in the process of reviewing and upgrading the cryptography APIs in the .NET Framework. Some of those changes will appear in the release of the .NET Framework 4.6.

Previous versions of the .NET Framework supported an earlier version of the Windows Cryptography APIs (see https://msdn.microsoft.com/library/windows/desktop/aa380255.aspx). Starting with the .NET Framework 4.6, we will begin adding new APIs that in turn rely on the Windows CNG cryptography APIs (see https://msdn.microsoft.com/library/windows/desktop/aa376214.aspx}.

The .NET Framework 4.6 adds the following new APIs to support the Windows CNG cryptography APIS:

-- A set of extension methods for X509 Certificates, X509Certificate2.GetRSAPublicKey and
    X509Certificate2.GetRSAPrivateKey, that return a CNG-based implementation rather than a
    CAPI-based implementation when possible. (Some smartcards, etc., still require CAPI, and
    these APIs handle the fallback).
  
   -- The RSACng class, which provides a CNG implementation of the RSA algorithm.
    
   -- Enhancements to the RSA API so that common actions no longer require casting.
    
This is the first step in what will be ongoing work in upgrading the cryptography APIs in the .NET Framework. In the near future, we will add GetECDsaPublicKey and GetECDsaPrivateKey to improve the usability of the ECDsa base class. Some of these future changes will be available in .NET Core right now.

**Comment by terrajobst** [comment]
Without a doubt BouncyCastle is a very useful library.

However, we don't see the CoreFX repo as the one place for the entire .NET ecosystem. This repo essentially represents 'a' slice of the entirety of the libraries folks use. There are other popular libraries that folks use day to day, for example JSON.NET.

Integrating them all in one place just doesn't make sense. Many of them already have their own GitHub projects, their own community of maintainer, and that's a good thing.

That being said, if there is work we'd need to do exchange types between S.S.C and BC, then we can certainly do the work to expose certain concepts or necessary abstractions.
