### ISSUE TITLE
Order of execution for Enumerable.Join differs between coreclr and net451

### ISSUE THREAD

**Issue by maumar** [dotnet/corefx#6477]
Order of execution for Enumerable.Join differs between coreclr and net451. End results are correct for both cases, but if customers are depending on order of execution (should they?) they might run into trouble.

Repro:

```
    public class Program
    {
        public static void Main(string[] args)
        {
            var query = Enumerable.Join<Customer, Order, int, object>(new CustomerEnumerable(), new OrderEnumerable(), c => c.Id, o => o.Id, (c, o) => new { c, o });

            var result = query.ToList();
        }
    }

    public class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class Order
    {
        public int Id { get; set; }
        public string OrderName { get; set; }
    }

    public class CustomerEnumerable : IEnumerable<Customer>
    {
        public IEnumerator<Customer> GetEnumerator()
        {
            return new CustomerEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return new CustomerEnumerator();
        }

        private class CustomerEnumerator : IEnumerator<Customer>
        {
            private int state = 0;

            public Customer Current
            {
                get
                {
                    Console.WriteLine("CustomerEnumerator Current");

                    return new Customer { Id = 1, Name = "1" };
                }
            }

            object IEnumerator.Current
            {
                get
                {
                    Console.WriteLine("CustomerEnumerator Current");

                    return new Customer { Id = 1, Name = "1" };
                }
            }

            public void Dispose()
            {
            }

            public bool MoveNext()
            {
                Console.WriteLine("CustomerEnumerator MoveNext");
                if (state == 0)
                {
                    state = 1;
                    return true;
                }

                return false;
            }

            public void Reset()
            {
            }
        }
    }

    public class OrderEnumerable : IEnumerable<Order>
    {
        public IEnumerator<Order> GetEnumerator()
        {
            return new OrderEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return new OrderEnumerator();
        }

        private class OrderEnumerator : IEnumerator<Order>
        {
            private int state = 0;

            public Order Current
            {
                get
                {
                    Console.WriteLine("OrderEnumerator Current");

                    return new Order { Id = 1, OrderName = "1" };
                }
            }

            object IEnumerator.Current
            {
                get
                {
                    Console.WriteLine("OrderEnumerator Current");

                    return new Order { Id = 1, OrderName = "1" };
                }
            }

            public void Dispose()
            {
            }

            public bool MoveNext()
            {
                Console.WriteLine("OrderEnumerator MoveNext");
                if (state == 0)
                {
                    state = 1;
                    return true;
                }

                return false;
            }

            public void Reset()
            {
            }
        }
    }
```

Result on net451:

OrderEnumerator MoveNext
OrderEnumerator Current
OrderEnumerator MoveNext
CustomerEnumerator MoveNext
CustomerEnumerator Current
CustomerEnumerator MoveNext

Result on coreclr:

CustomerEnumerator MoveNext
OrderEnumerator MoveNext
OrderEnumerator Current
OrderEnumerator MoveNext
CustomerEnumerator Current
CustomerEnumerator MoveNext

**Comment by VSadov** [comment]
Calls to Current should be ignorable, since they definitely must be idempotent. 
Without that it becomes:

Result on net451:

OrderEnumerator MoveNext
OrderEnumerator MoveNext
CustomerEnumerator MoveNext
CustomerEnumerator MoveNext

Result on coreclr:

CustomerEnumerator MoveNext
OrderEnumerator MoveNext
OrderEnumerator MoveNext
CustomerEnumerator MoveNext

I wonder, why the difference...

**Comment by VSadov** [comment]
@stephentoub @JonHanna

**Comment by JonHanna** [comment]
The same is true of `GroupJoin` as of #5372, and was pretty much the point of that PR. This behaviour with `Join` copied the change as part of #6061, which also adds taking another short-circuiting opportunity that doesn't apply to `GroupJoin`.

As such if the difference is considered a breaking change, #5372 will have to be completely undone, #6061 just made less ambitious.

I'll submit a PR soon, should we deem it so.

I'd prefer though, to leave both optimisations in there if nobody can find a good argument to consider it a break.

**Comment by JonHanna** [comment]
Okay, there's a PR to undo it. Now to argue against my PR being accepted :smile: 

Part of the observable change is that we may short-circuit and not access `inner` at all, and no further into `outer` than a single `MoveNext()`. Such short-circuiting changes were discussed before and decided as acceptable and several changes have introduced them were applicable since.

The other part of the observable change is the order of the two enumerables. It's worth noting that the in either case all of the calls on `inner` and the first call on `outer` will take place before the first element is yielded from the `join`: Consider where both have three elements.

Desktop:

1. Call to `MoveNext()` on the join made.
2. Call to `inner.MoveNext()`.
3. Call to `inner.MoveNext()`.
4. Call to `inner.MoveNext()`.
5. Call to `outer.MoveNext()`.
6. Call to `MoveNext()` on the join returns.

Corefx:

1. Call to `MoveNext()` on the join made.
2. Call to `outer.MoveNext()`.
3. Call to `inner.MoveNext()`.
4. Call to `inner.MoveNext()`.
5. Call to `inner.MoveNext()`.
6. Call to `MoveNext()` on the join returns.

As such the observable behaviour from code enumerating the results is that during the call to `MoveNext()` it made, `inner` has been enumerated entirely, and `outer` had its first element enumerated, either way. (Barring short-circuiting, as discussed above). The observed change is therefore small, comparable to others made, and perhaps less impactful than #4551 (where code that is enumerating the results could have interactions which were treated differently before and after that change.

In all, while obviously if someone has real code that is affected (rather than test code having a change in order, when the test is not guaranteeing that order because it itself is known to have an impact) the changes will have to be reverted, the degree of observable change seems to me to be minimal.

**Comment by VSadov** [comment]
I kind of think that because of internal use of Lookup, the relative enumeration order of joined sequences is already not very obvious.
Unlike crossjoin, the relative enumeration order seems unlikely to be relied on here, so perhaps we should keep optimization.

If we were ok with completely optimizing away the creation of inner lookup, we should be ok with creating the lookup after fetching one element of the outer sequence.

**Comment by JonHanna** [comment]
It seems the only issue caused for EF was with tests, and of course tests can have oddly tight dependencies they don't really need to have and don't signify a real issue (sadly the opposite is also true).

We should see if the EF team have any deeper concerns though.

**Comment by maumar** [comment]
@JonHanna is correct, for EF this is purely a test issue and the workaround is trivial, so its not a big concern from our perspective at all. 

When reporting this I wanted to make sure you were aware of the discrepancy, and whether it is acceptable degree of change from your point of view.

**Comment by JonHanna** [comment]
Can we consider this safe to close then? @VSadov ? @stephentoub ?

**Comment by VSadov** [comment]
My vote is for closing and keeping these optimizations.

**Comment by stephentoub** [comment]
Let's keep 'em.
