### ISSUE TITLE
HttpWebRequestTest.Abort_BeginGetRequestStreamThenAbort_EndGetRequestStreamThrowsWebException(remoteServer NullReferenceException

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#6487]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/1405/console

```
19:07:17    System.Net.Tests.HttpWebRequestTest.Abort_BeginGetRequestStreamThenAbort_EndGetRequestStreamThrowsWebException(remoteServer: http://corefx-net.cloudapp.net/Echo.ashx) [FAIL]
19:07:17       System.NullReferenceException : Object reference not set to an instance of an object.
19:07:17       Stack Trace:
19:07:18             at System.Net.Tests.HttpWebRequestTest.Abort_BeginGetRequestStreamThenAbort_EndGetRequestStreamThrowsWebException(Uri remoteServer)
```

**Comment by stephentoub** [comment]
@davidsh, I just took a peek at these tests, and they seem inherently racy.  Am I reading it correctly that it starts a request, then aborts it, and expects that the operation will have been canceled?  But if on rare occasion there's a blip and the request actually finishes before it can be aborted, the exception field won't be set, and it'll attempt to access the Status property off of the null field, causing such a NullReferenceException?

**Comment by davidsh** [comment]
`HttpWebRequest.Abort` has always problematic on CoreFx since we implement HttpWebRequest on top of HttpClient which is inherently async in nature.

.NET Framework behavior for HttpWebRequest.Abort and MSDN docs state that Abort() is sync in nature and will not return until the "callback" has completed.

There are some small windows of race condition inherit in the implementation of HttpWebRequest.Abort().

In terms of this specifically:

>I just took a peek at these tests, and they seem inherently racy. Am I reading it correctly that it starts a request, then aborts it, and expects that the operation will have been canceled? But if on rare occasion there's a blip and the request actually finishes before it can be aborted, the exception field won't be set, and it'll attempt to access the Status property off of the null reference, causing such a NullReferenceException?

The test itself is probably has that small window of race where the test will fail because of what you observe.  I will look into this to see if we can stabilize the test.

If we think this test is failing very often in CI, then we can disable it for now.

**Comment by stephentoub** [comment]
Thanks for the explanation.

> If we think this test is failing very often in CI, then we can disable it for now.

No, I think this is the only time we've seen it fail.  Which makes sense... if that actually is the cause, you'd expect it to fail only very rarely.

**Comment by SidharthNabar** [comment]
Moving to future since this is not high priority for RTM.

**Comment by stephentoub** [comment]
Again here:
20:36:37    System.Net.Tests.HttpWebRequestTest.Abort_BeginGetResponseThenAbort_EndGetResponseThrowsWebException(remoteServer: http://corefx-net.cloudapp.net/Echo.ashx) [FAIL]
20:36:37       System.NullReferenceException : Object reference not set to an instance of an object.
20:36:37       Stack Trace:
20:36:38             at System.Net.Tests.HttpWebRequestTest.Abort_BeginGetResponseThenAbort_EndGetResponseThrowsWebException(Uri remoteServer)

**Comment by karelz** [comment]
Tracked as part of #14519.
