### ISSUE TITLE
Feature request: Better low-level support for making use of streaming algorithms

### ISSUE THREAD

**Issue by CurtHagenlocher** [dotnet/corefx#6517]
There is a class of algorithms that works against a sequential stream of data. Typically, the algorithm is initialized with some starting state. It's then presented with a sequential stream of identically-typed elements. For each arbitrarily-chosed block of elements, the algorithm may either modify the starting state or produce an incremental block as part of an output stream, or both, depending on the algorithm in question.

Algorithms which follow this pattern include compression/decompression, encryption/decryption and hashing.

In the BCL, these algorithms are typically modeled as wrappers of System.IO.Stream. For instance, you write normally to a file by using a FileStream. But if you wrap this FileStream with a GZipStream, then writing to the wrapper will cause the file to be compressed. This is incredibly convenient when your use case exactly matches the functionality in the BCL. Where it falls apart, though, is for non-matching use cases.

For instance, let's say you want to compress a Stream while reading it. This simply isn't supported directly today. The only way to make use of GZipStream in this scenario is by creating two adapters -- one that reads from the original stream and writes to the GZipStream, and one that intercepts the writes out of the GZipStream and puts a pull interface back on top of it.

If the GZip functionality in the BCL were also exposed in a more primitive form -- for instance, something like the [Compressor interface in Hadoop](http://hadoop.apache.org/docs/current/api/org/apache/hadoop/io/compress/Compressor.html), it would be much easier to implement custom scenarios on top of the base functionality. Given a sufficiently general abstraction for the initialize/process next block/finish set of operations, it might even be possible to reduce the amount of per-algorithm code that exists simply to interface with Stream.

Unfortunately, the CoreCLR footprint appears to be going backwards in this regard. As an example, the HashAlgorithm class previously had methods for TransformBlock and TransformFinalBlock, but these have removed. The only way to make use of HashAlgorithm in a streaming fashion is to go through the pain of exposing the data as a (blocking) Stream, which can be extremely inconvenient.

**Comment by svick** [comment]
> you want to compress a Stream while reading it

Why would you want to read the compressed stream?

> one that reads from the original stream and writes to the GZipStream

That sounds a lot like [`CopyToAsync()`](https://msdn.microsoft.com/en-us/library/hh159084).

**Comment by CurtHagenlocher** [comment]
I had good reasons for wanting to compress on read. The specifics aren't really pertinent to the request, which is about providing the means to let developers build their own higher-level abstractions on top of lower-level functionality which is already present, but frustratingly inaccessible.

**Comment by ianhays** [comment]
I thought about this more over the weekend since your email thread, but I"m not sure I understand where exactly we're missing functionality compared to other APIs. Yes, there is some indirection around the zlib functions (setinput, needsinput, etc) to fit in the Stream style, but the functionality is mostly the same.

For general purposes the use case of wanting to compress a stream is definitely not rare, but the easy and most frequently used solution is to use a CopyTo, like so:

```
using (FileStream iWantToCompressThis = new FileStream("readthis", FileMode.Open))
using (MemoryStream compressed = new MemoryStream())
using (GZipStream compressor = new GZipStream(compressed, CompressionMode.Compress))
{
    iWantToCompressThis.CopyTo(compressor);
    compressor.Flush();
    // Compressed now has all of the compressed data from iWantToCompressThis
}
```

But let's say you want a more fine-grained control over the reading from the underlying stream and a copyto won't work for you. You linked an API that almost exactly matches what we use in the [underlying implementation of DeflateStream](https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression/src/System/IO/Compression/Deflater.cs), so that's what you want exposed I take it? 

>This is incredibly convenient when your use case exactly matches the functionality in the BCL. Where it falls apart, though, is for non-matching use cases.
>If the GZip functionality in the BCL were also exposed in a more primitive form -- for instance, something like the Compressor interface in Hadoop, it would be much easier to implement custom scenarios on top of the base functionality.

Would you mind posting an example of a use case that is far easier to do with the Deflater/hadoop interface than the DeflateStream interface? The only one I can think of is if you want to manually control when input is set and written to circumvent the DeflateStream buffer. 

>For instance, let's say you want to compress a Stream while reading it. This simply isn't supported directly today.

Wanting to compress a stream while reading seems like it would be <i>harder</i> with the Deflater API than it currently is, because with the current API all you need is the CopyTo I (and svick) mentioned above. I could potentially see having a method in GZipStream/DeflateStream like Write(Stream stream) that removes the middle-man for you, but that's just more high-level API, not low-level API.

**Comment by svick** [comment]
I think that specifics can be useful:

* It means alternative and possibly even better solutions can be proposed (whether in the form of new API or just using an old one).
* It helps understanding how common what you're asking for is.

**Comment by rstam** [comment]
The lack of support for incrementally computing an MD5 hash is one of several things blocking a port of the MongoDB .NET Driver to .NET Core. We rely on being able to compute the MD5 hash incrementally while we are doing other work (like incrementally uploading/downloading the chunks that make up a potentially very large GridsFS file). We never have the entire buffer in memory at once, so calling ComputeHash(byte[]) is not possible. Calling ComputeHash(Stream) is equally impractical for us.

Essentially we are going to have to write our own implementation of MD5 for .NET Core in order to be able to port the MongoDB .NET Driver to .NET Core.

I see no logical reason why the .NET Core versions of HashAlgorithm shouldn't continue to support an incremental API.

**Comment by ayende** [comment]
For example, I might want to compress data that I write to WebSocket, which
doesn't have stream interface.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by stephentoub** [comment]
cc: @bartonjs

**Comment by ianhays** [comment]
>I see no logical reason why the .NET Core versions of HashAlgorithm shouldn't continue to support an incremental API.

I don't know much about crypto(@bartonjs), but isn't that what [IncrementalHash](https://github.com/dotnet/corefx/blob/ac67ffac987d0c27236c4a6cf1255c2bcbc7fe7d/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/IncrementalHash.cs) is for?

**Comment by ianhays** [comment]
https://github.com/dotnet/corefx/issues/4123

**Comment by CurtHagenlocher** [comment]
Okay, some specifics then. In my most recent scenario, we have an internal contract for binary values which effectively looks like this:

class BinaryValue {
    public Stream Open();
}

Now I want to implement a function with the prototype
BinaryValue Compress(BinaryValue value);

Note that decompression is easy, a DecompressedBinaryValue could have an "Open" which simply returns new DeflateStream(this.baseValue.Open()). But the same thing doesn't work for compression, because of the underlying assumption that compression only happens with push and decompression only happens with pull.

To be fair, I hadn't considered CopyToAsync because I can't use it for *reasons*. But even if I could, it would force otherwise un-async-aware code to take on new dependencies, possibly add new requirements for concurrency-safety, and significantly increase resource requirements (two background threads, extra allocations, extra copies).

**Comment by CurtHagenlocher** [comment]
The very first time this API made me angry was when I was trying to implement Python's compression support for IronPython. In the end, I gave up trying to do it on top of the BCL's public API and (IIRC) just got permission to fork the code. There's been at least one other case where the existing API was not what I wanted, and that's when I ported Hive ORC file support to C#. I think I ended up using extra buffers there but eventually intend to go back and switch to p/invoke -- both for performance reasons and because support for Snappy and LZO will require some native component anyway.

**Comment by bartonjs** [comment]
@ianhays (and @rstam) Yep, the IncrementalHash class is where the incremental hash composition functionality migrated; and #4123 does explain/example it.

**Comment by ayende** [comment]
But things like compression would be very useful to have independent of the
Stream.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by rstam** [comment]
> > I see no logical reason why the .NET Core versions of HashAlgorithm shouldn't continue to support an incremental API.
>
> I don't know much about crypto(@bartonjs), but isn't that what IncrementalHash is for?

@ianhays  IncrementalHash looks promising. First I've heard of it though. A search of MSDN yields no hits.

In general, we really need some documentation that describes what *IS* in .NET Core. The discoverability of things like this is very poor.

**Comment by svick** [comment]
@CurtHagenlocher 

> To be fair, I hadn't considered CopyToAsync because I can't use it for reasons. But even if I could, it would force otherwise un-async-aware code to take on new dependencies, possibly add new requirements for concurrency-safety, and significantly increase resource requirements (two background threads, extra allocations, extra copies).

In that case, you can use the non-asynchronous (and thus blocking) `CopyTo()`. I don't think there's another choice, even if you write the code yourself: either the code is asynchronous, or it blocks. I assumed blocking would be a bigger problem, so I suggested `CopyToAsync()`.

Also, `CopyToAsync()` isn't as bad as you suggest, especially when it comes to resource consumption: it only uses one background thread at a time and only for very short periods. And I don't think there are any extra copies either.

**Comment by ayende** [comment]
CopyTo / CopyToAsync does a pretty big buffer allocation, though.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by svick** [comment]
@rstam 

> A search of MSDN yields no hits.

> In general, we really need some documentation that describes what *IS* in .NET Core. The discoverability of things like this is very poor.

That's what [dotnet.github.io/api](http://dotnet.github.io/api/index.html) is for, though it's very much a work in progress.

Specifically, [the documentation for `IncrementalHash` is supposed to be here](http://dotnet.github.io/api/System.Security.Cryptography.IncrementalHash.html). I *think* the reason why it's not really there (apart from listing the members, which is not really documentation) is #6518.

**Comment by svick** [comment]
@ayende [You can specify whatever buffer size you want.](https://msdn.microsoft.com/en-us/library/hh137801) I was wondering whether using the new `ArrayPool` might make sense, but [apparently it's not possible](https://github.com/dotnet/corefx/issues/5598#issuecomment-173726925).

**Comment by terrajobst** [comment]
@CurtHagenlocher I'm not entirely sure I understand what you're asking for. it looks like you want an easier way to:

* Wrap an existing stream to perform some processing as data is being read. Write now, you've to do the delegation yourself and make sure you override all the right methods.
* Having a way to convert from pull to push and vice versa.

Is that correct?

**Comment by CurtHagenlocher** [comment]
@terrajobst No. Ideally, I'd like to be able to consume this kind of functionality without having to implement a Stream at all.

**Comment by ayende** [comment]
Yes, but I can't provide an external buffer, or control the allocations.
If I need to run this in high perf code, I cannot call this method, because
of the allocation cost.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by psibernetic** [comment]
Aren't you really asking for a low level form IEnumerable here, something that can be written to directly (stream) or consumed with separate positions in the stream? Or is this an argument for an auto-feeding StreamWriterReader that consumes stream A -> Stream B? @ayende @CurtHagenlocher.

**Comment by xied75** [comment]
1, Finding something __New__ is not easy, e.g. the IncrementalHash, how would someone know what he doesn't Know, unless he skim the whole api again and again and can tell which is added recently.

2, Regarding the original question, I wonder if the Java pattern can be borrowed, e.g. the Filter stream. (Sometimes I think having a OutputStream and InputStream is silly, but Java stream is much lightweight to derive from, compared with .NET stream)

**Comment by veikkoeeva** [comment]
Not to pollute the thread, @xied75 do you mean something like [Streams](http://nessos.github.io/Streams/) (F#)?

**Comment by xied75** [comment]
@veikkoeeva Not really sure about F#, but this:
https://docs.oracle.com/javase/7/docs/api/java/io/FilterInputStream.html

**Comment by karelz** [comment]
Sounds like the conversation ended. There is no actionable work left. If anyone wants to propose API, please do so (feel free to file a new bug, or reopen this issue).

**Comment by mawt** [comment]
I've come across problems where the streaming API doesn't fit high throughput scenarios. 

I have a compute 'engine' that expands small inputs into a vast amount of data (the algorithm is O(n^4), with each iteration producing valuable data.) Using the TPL Dataflow API I was able to create a `[Read] -> [Expand] -> [Compute] -> [Store]` pipeline. Text compression is essential to prevent uploads backing up the producer (deflate leads to 2000% a reduction in size.) I tried adding a GzipStream transformer between `Compute` and `Store`.

My biggest problem regards how little control I have over minimum flush sizes. TextWriter's default block size is 8192 bytes. When tied directly to an HttpClient, GzipStream flushes would start too many small uploads, exhausting my upload pool, slowing the producer. In the end I had to implement a circular buffer around MemoryStream to prevent this.

I found that with the stream-centric API it's very difficult to modularise the compression. Rather than having a compression state ('i.e.' filemap, current offset, huffman table etc), I had to work around streaming/idisposable (TextWriter -> GzipStream -> MemoryStream) idiosyncrasies. Multiple copies and inability to pool large buffers lead to things ending up in the LOH and taking an age to collect. Stream semantics like explicitly calling `Close()` (to write deflate epilogue) and retaining various indexes for the circular buffer were far from straight forward. Finally, given how streams are not thread safe, I was unable to parallelize compression leading to a singularly threaded TextWriter-GzipStream-CircularBuffer-Dispatch loop blocking the producers.
