### ISSUE TITLE
Fill test gap in System.ServiceProcess.ServiceController 

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#653]
Needs a test to verify the properties of dependent services.

**Comment by LeonidVasilyev** [comment]
@Priya91 each dependent service must be tested on the same conditions as `ServiceController` tested in `ConstructWithServiceName()`, `ConstructWithDisplayName()` and `ControlCapabilities()`?

**Comment by nslottow** [comment]
Specifically, @Priya91 and I discussed asserting that the dependent services at least have the name that we expect because I spotted a bug in the dependent service name parsing logic in the initial pull request.

Fixing this entails modifying NativeTestService.cpp so one of the dependent services depends on both the main test service and the other dependent test service.  This would give us a DependentServices array with more than one element, and would cover the case that I spotted in the PR.
