### ISSUE TITLE
System.Security.Cryptography.X509Certificates.X509Store hides errors when cert collection is obtained from a closed store

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/corefx#6550]
`System.Security.Cryptography.X509Certificates.X509Store` has

```
     public X509Certificate2Collection Certificates { get {
```

which silently returns an empty collection if the store is not opened. The code to traverse a store looks something like this:

```
 using( var store = new X509Store() ) {
       store.Open( OpenFlags.ReadOnly );
       var allCerts = store.Certificates;
       //traverse allCerts
 }
```

if `Open()` call is omitted for any reason - "no problem", the code works, just looks at empty collection. This is error hiding. `Add()` and `Remove()` don't allow the store to be not opened in advanced. There's no way to check the store is opened. Something like this:

```
  void traverseCerts( X509Store store ) {
       var allCerts = store.Certificates;
       //traverse allCerts
  }
```

cannot even check the store is opened - it gets a collection anyway, maybe empty and it's empty maybe because the store is not opened or because the store is indeed empty.

The same behavior is on desktop. This is extremely inconvenient. A `IsOpened` property is surely needed. Also `Certificates` getter likely needs to throw an exception if the store is not opened in advance.

**Comment by bartonjs** [comment]
@Dmitry-Me I agree, but right now Desktop is the spec.  Behavior breaking changes between core and desktop for the same codepath is bad (it makes the code less portable) and breaking changes are pretty hard to do.

But, maybe your `isOpened` suggestion is a reasonable compromise.

**Comment by AtsushiKan** [comment]
I think there are two mitigations we could do.

1. Add an <b>IsOpen</b> property that would enable helper methods like "traverseCerts" to assert that Opened condition.

2. Add new constructor overloads that perform the open action.

        public X509Store(StoreName storeName, StoreLocation storeLocation, OpenFlags flags)
        public X509Store(string storeName, StoreLocation storeLocation, OpenFlags flags)

   Just seeing the new overloads in Intellisense should at least prompt a question (uh... what happens if I don't specify how to open), and allows writing new code that avoids the clunky "explicit call to Open that's never matched with a Close" pattern.

Both look pretty trivial to implement.

**Comment by bartonjs** [comment]
@AtsushiKan Sounds good, I'll take both :).

**Comment by AtsushiKan** [comment]
Attaching api review proposal and annotating issue as ready for review.

<b>Proposed Api additions to System.Security.Cryptography.X509Certificates.X509Store</b>

Two new constructor overloads:

        public X509Store(StoreName storeName, StoreLocation storeLocation, OpenFlags flags)
        public X509Store(string storeName, StoreLocation storeLocation, OpenFlags flags)

One new property:

        public bool IsOpen { get; }

<b>Rationale</b>

The current api design adds a extra, mandatory step to reading or writing a store:

    using (X509Store store = new X509Store(name, location))
    {
         store.Open(flags);   // <-- Ugh.
         ... do stuff ...
    }

This is a code pattern that stands out like a bug in a soup bowl, especially since there is no corresponding Close() api (it's handled in the Dispose() method.)

To add insult to injury, forgetting to call Open() causes X509Store.Certificates to return an empty collection rather than throwing an exception. This makes it that much harder to root-cause the error.

We cannot fix the api completely but we can add two mitigations:

Two new constructor overloads:

        public X509Store(StoreName storeName, StoreLocation storeLocation, OpenFlags flags)
        public X509Store(string storeName, StoreLocation storeLocation, OpenFlags flags)

These new constructors combine the construction and open in one call. The appearance of these new overloads in Intellisense will help "advertise" the issue to those tempted to use the old constructors, and allow new applications to use a more natural code pattern.

Also, one new property:

        public bool IsOpen { get; }

This would allow for better transparency into the creation/open/close semantics and allow methods that take previously opened stores to assert and/or validate the requirement that the store be open.

<b>Discussion point</b>

X509Store also contains a nullary constructor (that's equivalent to passing <b>StoreName.My</b>, <b>StoreLocation.CurrentUser</b>) Should we add a X509Store(OpenFlags) overload to correspond to that one too? I'm not sure what purpose the nullary constructor serves so I didn't propose an overload extension here. But I don't have a strong preference either way.

This also opens up the question of whether to add overloads on 4.6.x for the constructors that we didn't bring over from the full framework:

        public X509Store(StoreLocation storeLocation);
        public X509Store(StoreName storeName);
        public X509Store(string storeName);

**Comment by terrajobst** [comment]
Instead of doing a constructor I think it should be a factory method so this:


```C#
using (X509Store store = new X509Store(name, location))
{
     store.Open(flags);   // <-- Ugh.
     ... do stuff ...
}
```

would become:

```C#
using (X509Store store = X509Store.Open(name, location))
{
     ... do stuff ...
}
```

I think also adding `IsOpen` is a good thing though.

**Comment by bartonjs** [comment]
@terrajobst Presumably your static Open methods take the OpenFlags value which is what's being proposed to add to the ctor? :)

**Comment by terrajobst** [comment]
@bartonjs Yep :-)

The key point is that I don't think folks would expect that a ctor has a side effect, such as opening it.

**Comment by Dmitry-Me** [comment]
@terrajobst However a `System.IO.FileStream` constructor opens a file and everyone's okay with that.

**Comment by AtsushiKan** [comment]
The OpenFlags parameter makes the intention pretty clear, in my opinion. It actually feels more surprising that the existing constructors don’t open the store.

**Comment by karelz** [comment]
Next step: @bartonjs needs to provide the (pre-approved) API proposal.

**Comment by karelz** [comment]
@bartonjs do you have timeline for the API proposal?

**Comment by bartonjs** [comment]
# API Change
```diff
    public sealed partial class X509Store : System.IDisposable
    {
        public X509Store() { }
        public X509Store(System.IntPtr storeHandle) { }
        public X509Store(System.Security.Cryptography.X509Certificates.StoreLocation storeLocation) { }
        public X509Store(System.Security.Cryptography.X509Certificates.StoreName storeName) { }
        public X509Store(System.Security.Cryptography.X509Certificates.StoreName storeName, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation) { }
+#if netcoreapp11
+       public X509Store(System.Security.Cryptography.X509Certificates.StoreName storeName, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation, System.Security.Cryptography.X509Certificates.OpenFlags flags) { }
+#endif
        public X509Store(string storeName) { }
        public X509Store(string storeName, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation) { }
+#if netcoreapp11
+       public X509Store(string storeName, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation, System.Security.Cryptography.X509Certificates.OpenFlags flags) { }
+#endif
        public System.Security.Cryptography.X509Certificates.X509Certificate2Collection Certificates { get { throw null; } }
+#if netcoreapp11
+      public bool IsOpen { get { throw null; } }
+#endif
        public System.Security.Cryptography.X509Certificates.StoreLocation Location { get { throw null; } }
        public string Name { get { throw null; } }
        public System.IntPtr StoreHandle { get { throw null; } }
        public void Add(System.Security.Cryptography.X509Certificates.X509Certificate2 certificate) { }
        public void AddRange(System.Security.Cryptography.X509Certificates.X509Certificate2Collection certificates) { }
        public void Close() { }
        public void Dispose() { }
        public void Open(System.Security.Cryptography.X509Certificates.OpenFlags flags) { }
        public void Remove(System.Security.Cryptography.X509Certificates.X509Certificate2 certificate) { }
        public void RemoveRange(System.Security.Cryptography.X509Certificates.X509Certificate2Collection certificates) { }
}
```

# Test requirements

* Ensure that when using the new ctors that IsOpen starts as true.
* `new X509Store(Guid.NewGuid().ToString("N"), StoreLocation.CurrentUser, ReadOnly | ExistingOnly)` should throw
* Old ctors `IsOpen` is false.
* IsOpen is false after calling Close
* If #12223 has added a framework for creating temporary stores to modify them then this should create/open a new store, add some certs to it, open the store again using one of the new ctors, and ensure that the Certificates property enumerates values correctly (making sure to dispose the results to avoid test finalization)

**Comment by karelz** [comment]
Thanks! :)
Now it is up for grabs if anyone wants to implement the API
