### ISSUE TITLE
Better NETStandard meta-package support

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#6561]
Today we have a number of contracts in NETStandard.Library that are supported on various different versions of netstandard.

For some we should see about supporting them back further:
  Collections.Concurrent
  Win32.Primitives
  InteropServices.PInvoke
  Console
  FileSystem
  Sockets

Barring that we should at least partition them into dependency groups for each version of NETStandard, so that referencing the package doesn't bring in unsupported packages on a particular netstandard version.

/cc @onovotny

**Comment by onovotny** [comment]
What is the baseline version of .NET that you're supporting? 4.5? Unfortunately, I've heard a lot of requests for net40 support, so it'd be really helpful if the meta-packages could at least bring in `frameworkAssembly` references for those so we can still use the consolidated Library/Platform target when multi-targeting a project that has a net40 output.

**Comment by ericstj** [comment]
/cc @weshaggard 
Net40 doesn't support contract factoring (System.Runtime et al.) so frameworkAssembly is not sufficient.  We'd have to come up with facades generated against the 4.0 surface area.  In some cases this would produce API that is unusable since the API isn't present in net4.0.

**Comment by onovotny** [comment]
I recognize the pain, and as much as I question the need for net40, it just keeps coming back...so just trying to keep that in mind.

**Comment by davidfowl** [comment]
net40 requires cross compilation.

**Comment by ericstj** [comment]
I gather that @onovotny is ok with that.  He's asking us to make the NETStandard.Library package a *shortcut* for a handful of references that folks might take on framework assemblies.  Technically this is possible but I think it would dilute the meaning of this package a bit, and it would lead to "cliffs" where very different API is available, but there are always cliffs when cross compiling.

**Comment by onovotny** [comment]
Yup, cross-compilation. I don't want/like `net40` anymore than I'm sure you do, but unfortunately that has been a sticking point. When using the cross-compiling capabilities of xproj, this is easy to do, but instead of putting a single dependency in the project.json for `netstandard.library`, people will need to put that as a framework-specific dependency. That just adds more friction.

**Comment by davidfowl** [comment]
I don't see why you'd need any framework assemblies by default. If you need things like xml then you need to add a reference but most of the things represented as facades are in mscorlib, System, and System.Core.

**Comment by onovotny** [comment]
Let me make this more concrete:

Take the following project.json:
https://gist.github.com/onovotny/091a0b38edc918bca4eb

Ideally I'd like to put a single reference to `netstandard.library` here on the next line so it applies to everything: https://gist.github.com/onovotny/091a0b38edc918bca4eb#file-project-json-L14

That will fail today though.

Instead, I need to put `netstandard.library` in several places:
https://gist.github.com/onovotny/091a0b38edc918bca4eb#file-project-json-L87
https://gist.github.com/onovotny/091a0b38edc918bca4eb#file-project-json-L116

And possibly the `net45` and `net46` frameworks depending on what we need.

So rather than put a `netstandard.library` reference in one place, now I need them in four, just because `net40` will fail.

**Comment by davidfowl** [comment]
@ericstj @weshaggard  Is NETStandard.Library supposed to work on net45?

**Comment by ericstj** [comment]
This issue is tracking mailing that happen.

**Comment by ericstj** [comment]
re-opening until we pick up this fix in corefx.

**Comment by ericstj** [comment]
We're going to consider a smaller version of this fix for RC2.  Same result just without the buildtools update.

**Comment by onovotny** [comment]
@ericstj what does that mean exactly? I looked at the latest rc3 package (in nuget package explorer) and it looks promising - though have not tried it anywhere yet.

**Comment by ericstj** [comment]
The fix is in RC3 branch, we're looking at pulling a smaller version of the fix into the RC2 branch.

**Comment by ericstj** [comment]
Fixed in rc2
