### ISSUE TITLE
Add a production assert facility

### ISSUE THREAD

**Issue by GSPP** [dotnet/corefx#6589]
It is possible to use `Debug.Assert` in `DEBUG` builds to assert runtime conditions. The Base Class Library currently has no way to assert something in non-debug builds. That's a pity because in many applications it is a prudent choice to leave (cheap) assertions enabled in production.

Many projects do not wish to make use of Code Contracts. It seems heavy-weight to pull in Code Contracts just to have an assert method.

Please add a release build assert to the BCL.

Here are some naming proposals:

```
Debug.ReleaseAssert(...)
Assert.Debug.IsTrue(...);
Assert.Release.IsTrue(...);
```

Another thing that makes `Debug.Assert` unusable in production is that it pops up a dialog box or crashes the process. This is inappropriate with ASP.NET where you normally want to simply abort the current HTTP request and let the process live. It's also inappropriate in any form of client-side GUI app.

Frankly, the Abort-Retry-Cancel dialog that pops up is ... not very nice.

Most apps are not overly concerned with state corruption. A `FailFast`-like approach is not desirable.

Therefore, the new assert functions should merely throw an `AssertFailedException`.

If the developer chooses to add a catch-all top-level handler to his request processing then so be it. The assertion failure exception will contain the stack trace pointing to the location of the error. It will be fairly easy to debug the assertion failure from logging output.

The new assertion facility should _not_ be configurable to do something else (e.g. log and `FailFast`). Developers should be able to rely on the exact exception throwing behavior outlined above. When I see a production assert in foreign code I want to know what it does. I don't want the possibility that some developer-provided hook is called.

Another benefit is that the whole ecosystem can standardize on this `AssertFailedException` class. All tools and testing frameworks can learn to understand it.

The `AssertFailedException` is useful by itself, for example to signify unreachable code:

```
switch (...) {
 case: return 1;
 default: throw new AssertFailedException();
}
```

This would _not_ be possible with `Assert(false)` because the compiler must know that all paths return a value or throw. To help with this scenario, we could as a `class UnreachableException : AssertFailedException`. Now, tools can standardize on that one as well. When Resharper generates a `switch` it can use this exception type, for example.

In this issue I have outlined the approach that I have used over 5 years in a 100 kLOC codebase. I found it to work very well.

**Comment by svick** [comment]
Are you just asking for a more convenient way to write the following code?

```c#
if (!someCondition)
    throw new SomeException("Some condition was false.");
```

**Comment by GSPP** [comment]
Pretty much, yes. That would be the body of the method. The `Debug` one would have a `Condition("DEBUG")` attribute on it.

**Comment by eadordzhiev** [comment]
There is the `Trace.Assert()` method which is identical to `Debug.Assert()` but works in non-debug builds. The only problem is that it displays a message box when assertion fails, but you can set `AssertUiEnabled` of the current `TraceListener` to `false` to suppress it with code or `Web.config`. See [MSDN](https://msdn.microsoft.com/en-us/library/tk4kachs(v=vs.110).aspx) for more information.

**Comment by GSPP** [comment]
Thanks for bringing this to my attention.

`Trace.Assert` appears to be `[Conditional("TRACE")]` according to Reflector. That means it is not available in production builds. Also, if `AssertUiEnabled == false` the assert is disabled (according to your description). That doesn't help because it should be always on.

**Comment by Clockwork-Muse** [comment]
Last I knew, nobody was using code contracts because of the ongoing discussion over language inclusion and/or design.

Your proposed design would throw a different exception (and have different behavior) than the current `Debug.Assert`; this is likely to be surprising to developers.  Especially since they can catch the specific exception.  

The fact that you want to prevent logging or hooking is likely to just see developers blanket catching and doing those actions anyways (if they have such a cross-cutting concern).  **Whose** code are you anticipating having to read?  If it's your own code, why do you want the framework to disable this (as opposed to configuring your logging library)?  If it's somebody else's code (they're using your library), why are you expecting to dictate their logging policies?  If you're using somebody else's code (their library), why do you want them to be able to sidestep your logging?

Depending on where the `case` statement occurred, I'd often consider `ArgumentOutOfRange` (or maybe `ArgumentException`) to be a clearer exception.  Asserts lend themselves well to testing invariants, and sometimes post-conditions, which generally you should have covering tests for; in many cases, there may still be more specific exceptions available.  Do you have an expanded example use case?
`UnreachableException`, besides being a slight oxymoron (you have to reach it to throw it), has an existential conflict with good testing.  Either you have a way to hit it, in which case you're probably violating a pre-condition (see `ArgumentException`), or you can prove you don't, in which case it can be removed as dead code (okay, yes, formally you can't prove a negative, but you know what I mean).  The 'third option' which says "we don't know yet", as usual, will be indicative of insufficient testing.

**Comment by GSPP** [comment]
The documentation for `Debug.Assert` does not mention any exception being thrown at all. This is a problem because you cannot use the assert to abort what the app is doing (and not killing it outright which is unpractical in basically any web app).

I'm opposed to "hooking and reconfiguring" because **assertion behavior should not depend on configuration**. It should be reliable behavior that execution is terminated through an exception.

When I say:

```
var mailMessage = GetMailFromDB();
Assert.IsTrue(IsValid(mailMessage)); //Always supposed to be true. Safeguard.
Send(mailMessage);
```

I really do not want to continue execution in case the assert fires. If this is a library I do not want to depend on the web.config of the app hosting me.

I have no problem whatsoever with developers "blanket catching" the resulting exception. That is indeed recommended (by me). *Something* needs to have a `catch (Exception)` and report all errors at the top level of the app. Bugs are worthy of being caught and reported as well. (Might be rethrown.)

ASP.NET does it like that. Catch everything and render the yellow error page. That's good behavior.

Next problem I just found is that Windows Store apps do not support `Debug.Assert`. This leaves those app without any built-in assertion feature. Since the code size required to do what I propose is so small this should be suitable for inclusion in Windows Store apps.

You have some valid points in your last paragraph. I'll refrain from going through them because this is not essential to the issue and I don't want to derail it.

**Comment by Clockwork-Muse** [comment]
..I'm sorry, I have to question the premise of your new example.  You're grabbing a message from an external source (database, in this case): you should be checking it for validity "like normal" _and throwing regular exceptions_.  You don't want just an "it was invalid" exception here, you want a richer, more descriptive set.  Depending on setup, you might even `AggregateException` a bunch of them.  If `GetMailFromDB()` isn't guaranteed to return a valid mail, the validity checking should be throwing the relevant exception(s).  If it does return only valid mail, then normally you wouldn't check again (except in maybe `Debug` builds...)

I'm not sure what you mean by "lightweight" here.  Everything is going to require `if` statements, which are as trivial as possible.  Otherwise, you're talking about something already under discussion: Code Contracts.

**Comment by GSPP** [comment]
GetMailFromDB *is* guaranteed to return a valid mail - according to the understanding of the developer. There might be a bug, though.

If that example is not particularly great (might be) there is an ample source of real-world examples. [The corefx repo seems to think that assertions are useful.](https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=Debug.Assert) It is a valid choice by them not to compile them into production builds. Other teams might prefer differently.

Are you questioning the very usefulness of assertions? Your statements seem to imply that each and every assertion should be implemented through a "nice" exception. I could respond to that in more detail but I want to make sure I understand your counter point.

**Comment by Clockwork-Muse** [comment]
My point of view is that `Debug.Assert` is equivalent to putting `Console.WriteLine` in when you know something is going wrong and are trying to chase down where.  It's there for SAN checks that you don't usually (and often shouldn't) need, which is why they get compiled out on release builds.  They aren't meant to cover normal "error condition" checking, which is supposed to be handled with exceptions.  If one of the calls is consistently failing, you're almost certainly missing a test case (or several) and normal error checking/throwing.  
At the point that `Debug.Assert` fails, it's already too late; in most cases you should be finding and throwing much earlier.  You aren't really replacing them with "nice" exceptions, because the exceptions belong somewhere else (often in checking parameters or on method call).  It's not that asserts aren't useful, it's that their usefulness lies in a different direction.

The problem with the example as I see it is like this:
 1. If we control `GetMailFromDB`, why aren't we checking the mail is valid before returning?  (And no, you can't say "well, that's the bug", because adding the check outside isn't the correct solution then)  
 2. If we _don't_ control `GetMailFromDB`, then we're passing a confidence boundary, and anything goes.  If we don't trust the output from that method, then we have to verify it as if it was regular keyboard input.  We also don't want to just tell the maintainer "your library has a problem".  
 3. (We don't really care about the validity of the mail we get back either way; `SendMail` cares.  Why isn't it checking the validity?  This is really sorta part of both...)
 
In neither case is "You got invalid mail" going to be sufficient information to be actionable.  Which mail failed?  Why?  You're not going to want pore over a 40k word email looking for a misplaced header, only to find out that there's a bell character (whitespace) somewhere in the middle - it would be immensely helpful for the checking method to say "Yo!  Character 20,015 is a bell, we can't deal with that".  It'd be like compiling code, but instead of giving you line numbers where you're using an undefined variable, the compiler spits out "you made a mistake".


This isn't saying there couldn't be a Release assert, just that I'm not convinced the example you're using is relevant or makes a good showing.

**Comment by GSPP** [comment]
I agree that assertions are not for precondition checking. They are for documenting *and possibly validating* internal invariants.

I'll try to give plausibility to the mail example. Let's say the invariant is that there is no bell character. But it's totally fine to *store* a bell character in the database. No problem with that. Maybe these are imported mails from some other system. Who knows, they are supposed to be stored. `GetMailFromDB` therefore can't validate.

`SendMail` is merely a mail sender component. It has no business preventing bell characters.

Only the code that ties the two together has knowledge about bell chars. And the code is written so that it is impossible to draw mails from the database that have bell chars. For example:

```
void ProcessNextEligibleMail() {
 var mailMessage = GetMailFromDB(from m in db.Mails where m.IsUnsent && !m.Body.Contains("bell") select m);
 Assert.IsTrue(!mailMessage.Body.Contains("bell")); //Always supposed to be true. Safeguard.
 SendMail(mailMessage);
}
```

Now it's logically impossible to receive a bell char. Consumers of `ProcessMail` do not know what a bell char is, either. It makes no sense for an API consumer to receive a `new Ex("bell char found!")`. 

Yet, I want to document this bell char property and I want it checked in production because if we ever accidentally send a bell char we would be financially liable for 1M$ to our customer. Very important to add redundant safeguards.

I'd estimate that 99% of .NET code is very boring data shoveling business code that has quite a few uses for invariant checks. The .NET Framework has *far* higher code quality standards. In "line of business code" it often is the most economical choice to sprinkle some assertions that you *think* will always hold. If they fail, you investigate. Maybe you are underestimating with how much dirtiness competent and rational "business developers" deal every day. Invariants tend to not be black and white.

To labor the point even more: Even if it is possible to always check preconditions and invariants in a timely manner and emit nice errors this often is not the most economical choice from a business standpoint. It can be outright wrong to write code of extreme quality. I have never seen a codebase of higher quality than the BCL. It just doesn't compare to what most .NET code is about.

**Comment by Clockwork-Muse** [comment]
>Now it's logically impossible to receive a bell char. Consumers of  ProcessMail  do not know what a bell char is, either. It makes no sense for an API consumer to receive a  `new Ex("bell char found!")` . 

... you say that, but that's exactly what they're receiving, isn't it?  Your consumers are getting an exception because it found a bell character (lets ignore for a moment what specific one it might be).  It's now part of your API: "if it encounters a bell character, it throws an exception".  You're also still passing a confidence boundary, so why wouldn't a "regular" exception be appropriate?

This specific example is better, but I feel like we're heading into territory that should be covered by something else: code contracts (well, that and worry people would start using it for precondition checking).  I get the feeling that `Debug.Assert` is deliberately limited in breadth (no `IsFalse`, `DoesNotContain`, etc) specifically to restrict it to SAN checks.

**Comment by GSPP** [comment]
No bell char will ever be encountered because of `from m in db.Mails where m.IsUnsent && !m.Body.Contains("bell") select m`. `GetMailFromDB` might be defined as `return query.FirstOrDefault();`.

Under no circumstances will the caller receive an assertion failure in this piece of code.

Yes, I want Debug.Assert and the new proposed API to be only for sanity checks (I assume that's what you mean by SAN).

**Comment by Clockwork-Muse** [comment]
...and if you're that confident, why isn't it just a debug check?  I feel like the moment you make it an always-on, production release check, you're saying "I don't believe this part will always work as expected", and should be using a regular exception.  Like certain types of IO exceptions.

**Comment by joperezr** [comment]
assigning to @GSPP to get an api proposal for this Assert API

**Comment by karelz** [comment]
@GSPP if you're working on the proposal, please let us know and we will assign it to you.

Personally, I don't think a new API is worth saving just one extra line.

**Comment by wtgodbe** [comment]
Closing as abandoned
