### ISSUE TITLE
Implement a generic Enum.Parse method

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/corefx#668]
Although the Enum.TryParse method (https://msdn.microsoft.com/en-us/library/system.enum.tryparse(v=vs.110).aspx) has two generic overloads, the Enum.Parse overloads (https://msdn.microsoft.com/en-us/library/System.Enum.Parse(v=vs.110).aspx) were added to the .NET Framework in version 1.0, before the introduction of generics. They create the need for rather redundant code, such as

    Colors colorValue = (Colors) Enum.Parse(typeof(Colors), colorString);

which entails the need to add an additional cast, as well as instantiate a Type object that represents the enumeration type.

It would be nice to add generic Parse overloads that correspond to the generic TryParse overloads:

    public static TEnum Enum.Parse<TEnum>(String value);
    public static TEnum Enum.Parse<TEnum>(String value, Boolean ignoreCase);  

Note that there's also another open issue on improving the performance of Enum.TryParse at https://github.com/dotnet/corefx/issues/594.

**Comment by mellinoe** [comment]
I think for this to be feasible, we would need an enum generic type constraint, which isn't currently possible. There is some discussion on the Roslyn repo/forum around this, and it is listed as a possible point of discussion for C#7. I would definitely agree that this is a good API to add if such a feature is implemented.

**Comment by Alexx999** [comment]
Yeah, I'm now working on that Enum.TryParse issue.
And I had the same thoughts as you do - "Why not make it generic?"
Well, I came to conclusion that it will be really major breaking change, and the most viable option would be adding generic wrappers around non-generic functions because we can't remove old non-generic API.
Or create generic API in parallel to non-generic - that would be interesting in terms of possible performance benefits (but questionable because of possible maintenance problems).

I propose adding wrappers as "Step 1".

**Comment by KrzysztofCwalina** [comment]
I am closing this for now. We need language and runtime features (enum constraints) for this to be actionable.
