### ISSUE TITLE
FileVersionInfo tests' native assemblies and exes do not have sources

### ISSUE THREAD

**Issue by nslottow** [dotnet/corefx#674]
We should at least provide the sources for these native binaries so that we can tell what's going on if we hit issues.

The next time we need to make a change to these tests, it would also be worth getting the native binaries to build as vcxprojs, relying on the VS2013 prerequisite for now (see [System.ServiceProcess.ServiceController.Tests](https://github.com/dotnet/corefx/tree/v1.0/src/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.Tests) for an example).  When we start to light up tests cross-platform, we will be forced to clean this up and use CMake or some other solution for native binaries.

cc @weshaggard

**Comment by Alexx999** [comment]
I believe that sources are not *really* needed here since that binaries are never loaded and/or run.
They only serve purpose of "test data".
I even suppose that it's not that great to rebuild them since older legacy binaries built with previous versions of compilers should work fine too - that's the point of that test. It should test PE format in general.
And this will actually break cross-platform compatibility of this test since native PE executable can't be built on Linux (and we still should be testing PE on Linux since managed assemblies are PE executables even there)

**Comment by nslottow** [comment]
All good points.  I should've examined these tests more closely before filing this.  I was coming from looking at the System.ServiceProcess.ServiceController tests which got initially committed with a binary that turns out to be unnecessary.

I'll leave it up to @mellinoe to decide whether to provide source.

**Comment by weshaggard** [comment]
I agree with @alexx999 that in general we should just make the source available in case we need to examine or rebuild but it shouldn't be part of the build for these tests.

**Comment by ianhays** [comment]
In solving #3919 I was unable to find the source for these assemblies and so fixed it by manually editing the dlls. I agree with @Alexx999 that in this particular case, the source for the binaries isn't really what we care about and I would say that including it may potentially be confusing because it may imply that that source should be built.

If we can find it then it may be worth including just as an effort towards transparency in "open sourcing all the things" but I don't think it will provide much value.

**Comment by mellinoe** [comment]
TBH, I don't think this is actually important. If we need to change some of the metadata in the test files, we could just use a binary editor, or just recreate the binaries easily.
