### ISSUE TITLE
Will EF7 support UWP with SQL server when released?

### ISSUE THREAD

**Issue by jasondjelinek** [dotnet/corefx#6751]
I originally posted this question to the entity framework github repo and they said it should work, but was dependent on the SqlClient (the ADO.NET provider for SQL Server).  Can you tell me if there are plans to have SqlClient compatible with UWP?  If so what is the estimated timeline.  @YoungGah @saurabh500 

Original question with EF team's answers
https://github.com/aspnet/EntityFramework/issues/4692

Thanks,

Jason

**Comment by Mogikan** [comment]
Any updates?

**Comment by danmosemsft** [comment]
This is being discussed. Sorry for the radio silence.

**Comment by naster01** [comment]
Any feedback? This issue is breaking my UWP desktop app as I require SqlClient. Why can't we just have direct access to the CoreFx from UWP? Can anybody point me to the UWP's team or the open source repo to get lastest updates? Thx @terrajobst

**Comment by danmosemsft** [comment]
@divega @saurabh500 anything you can share here?

**Comment by divega** [comment]
EF Core has been running on UWP since 1.0 but with some limitations and issues caused by differences in the .NET Native runtime. We track the specific issues at https://github.com/aspnet/entityframework/issues/. 

EF Core 2.0 now targets .NET Standard 2.0 which means it won't work in UWP until the next version of UWP which come with support for .NET Standard 2.0 is released (you can find more details in https://github.com/aspnet/Announcements/issues/246).

From the SqlClient side of the question, I think @saurabh500 can provide more details, but my understanding is that there has been some work to enable that scenario. Once there is a version of SqlClient that works in UWP I see no reason it wouldn't work with EF Core.

**Comment by danmosemsft** [comment]
@saurabh500 can you comment? Who would own testing EF Core against UWP2.0?
Maybe this issue can be closed out.

**Comment by saurabh500** [comment]
We are working  risers supporting SqlClient on UWP . EF should take a first stab at testing

**Comment by divega** [comment]
Thanks @saurabh500 for confirming. @danmosemsft I think this can be closed since the original question has been answered. Any testing work or specific bugs that may affect the end-to-end scenario will be tracked elsewhere.

**Comment by danmosemsft** [comment]
OK!
