### ISSUE TITLE
Contract.Assert vs Debug.Assert

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#682]
Some of the CoreFX libraries use Contract.Assert.
Others use Debug.Assert.
We should be consistent, and if possible sweep the source to unify this.

**Comment by ellismg** [comment]
While Contract.Assert produces the nicer experience (the assert box is much clearer), I think I would push for Debug.Assert everywhere.  The rationale is that parts of the contract class require the rewriter to run (which we don't do) in order to be useful.  I would rather folks not have access to a type when half of the members on it are unusable in our system.

The other rationale is that having the "Debug" word there makes it clear that these contracts are not checked in release mode, which I believe is our long term plan.

I do agree that getting clean here is a good idea.

**Comment by weshaggard** [comment]
@ellismg +1 on being consistent with Debug.Assert.

**Comment by stephentoub** [comment]
I'm happy with Debug.Assert as the consistent answer.

**Comment by nguerrera** [comment]
+1 Debug.Assert for precisely the reasons that @ellismg states.

Is this something we can make the code formatter handle?

**Comment by stephentoub** [comment]
I think it'll require updating some package.config files, as IIRC some of the assemblies are missing the right reference.
