### ISSUE TITLE
Why having System.Console.dll?

### ISSUE THREAD

**Issue by linquize** [dotnet/corefx#683]
Why having a new DLL called `System.Console.dll`?
`System.Console` class is already in `mscorlib.dll` since .NET Framework 1.0

**Comment by ellismg** [comment]
One of the design goals of .NET Core was to re-factor the framework surface are into a collection of smaller assemblies, each focused on particular thing.  We wanted to remove monolithic assemblies like mscorlib which contain unrelated components that evolve at different rates.

For example, in .NET Core, there is no mscorlib.  Instead, the base types are in in System.Runtime.dll, collections are split across multiple assemblies (System.Collections.dll, System.Collections.Nongeneric.dll, etc), Console is in System.Consoel.dll, and so on.

To implement some of these contracts, we use facades, which are assemblies that contain type-forwarders to another assembly.  So the implementation of System.Runtime.dll when running on the .NET Framework is simply an assembly that says: "System.Object is in mscorlib.dll".

However, when possible we want to provide implementations that are not tied to a specific runtime (e.g. The full .NET Framework, CoreCLR, .NET Native) but instead can be used across all of them.  For that reason, we took the time to pull the implementation of System.Console.dll into it's own assembly which can work across any runtime, instead of using facades to point at mscorlib.dll

Hopefully this explains the rationale behind the move.

**Comment by linquize** [comment]
There is `mscorlib.dll` in coreclr. And it has types like `System.Object` and `System.Console`. Is it for backward compatibility so the binaries built from VS2010 can be run?

**Comment by weshaggard** [comment]
@linquize what are you expecting it to be backwards compatible with? It certainly isn't compatible with mscorlib that ships on the full .NET framework as it is much smaller. It is compatible with the mscorlib that ships for Windows Phone which also runs on CoreCLR. However for .NET Core we don't expect anyone to ever compile directly against mscorlib and instead compile against System.Runtime, etc, as @ellismg points out. So essentially mscorlib is an implementation detail on CoreCLR and for .NET Core we reserve the right to put the implementation into other factored assemblies like System.Console.dll.

This abstraction layer (i.e. compiling against System.Runtime instead of mscorlib) also helps us support things like .NET Native which doesn't have an mscorlib at all but it does support all the APIs that System.Runtime provides.

**Comment by linquize** [comment]
If I compile my program with `System.Runtime.dll` which works in CoreCLR, does it also work in Full .NET Framework?

**Comment by weshaggard** [comment]
@linquize Yes it will work on the full .NET Framework as well.

**Comment by linquize** [comment]
thanks!
