### ISSUE TITLE
ValidationAttribute _errorMessageResourceAccessor does not support UWP style Resw resources

### ISSUE THREAD

**Issue by chrisaswain** [dotnet/corefx#6830]
The ValidationAttribute needs to be updated to include support for UWP style Resw resource files that do not generate a C# code file with static properties to represent the resources in the Resw file.  It might need a new property to allow the developer to specify the `Windows.ApplicationModel.Resources.ResourceLoader` instance to use and then specify the ResourceKey.  Then just add an if block in the "private void SetupResourceAccessor(){...}" method to setup the "_errorMessageResourceAccessor" delegate to use the new ResourceLoader class to get the resource using the specified ResourceKey.  Something like:

```
_errorMessageResourceAccessor = delegate { return _theResourceLoaderToUse.GetString(_theResourceKey); };
```

Where "_theResourceLoaderToUse" and "_theResourceKey" are internal properties set by the developer.

And, instead of code like this:

```
[Required(ErrorMessageResourceType = typeof(Resources.Strings), ErrorMessageResourceName = "EmailInvalidMessage")]
```

We use code like this:

```
[Required(ErrorMessageResourceLoaderDelegate = delegate { return Windows.ApplicationModel.Resources.ResourceLoader.GetForCurrentView(); }, ErrorMessageResourceName = "EmailInvalidMessage")]
```

**Comment by divega** [comment]
Data Annotations Triage: The scenario looks valid, however we believe the proposed solution has several issues and would be insufficient, e.g.:
- We are not aware of a way to pass a delegate directly to an attribute like this
- The implementation of `ValidationAttribute` assumes `_errorMessageResourceType` will contain a property named after the resource rather than a `GetString()` method like ResourceLoader has.

There is probably value in enabling a more general way to obtain resource strings for validation attributes. This needs a bit of design. 

In the meanwhile, it is possible to copy a .Resx file project into a UWP application and use it as in any other application.

**Comment by lajones** [comment]
We are not planning on working on this. We would consider a PR, but we don't think the above approach (passing a delegate to the attribute) will work. At the moment we look for a property on a type. One alternative approach might be to recognize different patterns e.g. an Indexer property. You would then need an adapter to take the result of `.resw` files which results in a class with index properties.

**Comment by ajcvickers** [comment]
Closing since we do not plan  to implement this.
