### ISSUE TITLE
Add StringBuilder.AppendLine(char)

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefx#6869]
StringBuilder.AppendLine does not have an overload that takes a char. It might be useful to add one.

**Comment by stephentoub** [comment]
Maybe, but instead of:
```C#
builder.AppendLine('c');
```
you can achieve the same thing with:
```C#
builder.Append('c').AppendLine();
```
If it's extremely common and the implementation could avoid some overheads vs the two calls, might be worth it, but then there are all of the other Append overloads to consider.  At first blush, doesn't seem particularly valuable, but I could be wrong.

**Comment by JonHanna** [comment]
I can see more value in adding overloads that mirror all the `Append()` overloads than just one. For one thing while the API is expanded more this way, it's conceptually simpler in that if you know you can `Append()` it then you know you can `AppendLine()` it.

**Comment by jasonwilliams200OK** [comment]
:+1: overloads for the win. I proposed the similar overload in https://github.com/dotnet/coreclr/pull/2945 for `String.Join` and in the process, I also added char appended `UnSafeCharBuffer.AppendChar` for one overload of `Join`.

Considering the expansion of String-like APIs and cyclomatic complexity etc., would it make sense to refactor the code and add these as extension methods in a separate assembly (viz `System.String.Extensions`)? Some languages such as Ruby, provide quite an overwhelming amount of [string methods](http://ruby-doc.org/core-2.2.0/String.html), it would be nice to see .NET string evolution with some new (essential) methods and overloads out of the box. The extra-auxiliary methods can be obtained from foreign APIs, such as; [Humanizr](https://github.com/Humanizr/Humanizer).

**Comment by terrajobst** [comment]
We agree with @stephentoub. Appending lines with a single char doesn't seem to be too common.

**Comment by jnm2** [comment]
This is one of those things I run into all the time, so I'm naturally interested and a bit disappointed. But extension methods serve well.

**Comment by stokito** [comment]
This is a closed ticked but I'm doing an investigation for the same functionality for [JDK](https://bugs.openjdk.java.net/browse/JDK-8136584). Java doesn't have the `AppendLine` method so mostly it's used `append("str").append("\n")` instead.
I grabbed some statistics from java.base module (`java.lang`, `java.io` etc):
* char+\n: 40 usages  typical usage is: `]\n`. Can be found by regexp:  `.append\(".\\n"\)`
* char+char+\n: 38 usages  typical usage is: `);\n`. Can be found by regexp:  `.append\("..\\n"\)`
* char+char+char+\n: only 4 occurrences and without typical usage . Can be found by regexp:  `.append\("...\\n"\)`

So, for the Java core itself this may be useful to add two methods `AppendLine(char)` and even`AppendLine(char, char)`.
Other overloads for simple types like `append(int).append("\n")`, append(double).append("\n")` are not used.
But `append(Object).append("\n")` which interally calls `Object,toString()` is used quite often - 40 times.
So the `AppendLine(Object)` is also good to have.

But then I analyzed my company's projects (very large real enterprise codebase with 10+ years of development) and it turned out that `StringBuilder`s aren't so often used and the `append("\n") was used about 150 times and mostly just for SQL queries.
So for a regular coding this is not so necessary while for a platform itself or for high performance code this will be nice to have.
