### ISSUE TITLE
(API proposal) Adding a StringBuffer class with a MoveToString method

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#6893]
(Sorry for all the proposals I've been posting here lately, I promise this will be my last one for a while :smile:)
## Background

It's a common scenario to have code where you want to perform a bunch of operations on a string, like replacing a character or overwriting part of the string, but don't want to allocate a bunch of substrings. What most developers end up doing is copying the string into a temporary `char[]` or `StringBuilder`, calling the mutable counterparts of the methods in question, and then calling `ToString` on the result.

This is wasteful, since two allocations are required: one to copy the data into the mutable buffer, and one to construct a new immutable string. Each of these operations takes O(n) time.

`ImmutableArray` solves this problem by having a `MoveToImmutable` method in its 'builder' class, which simply [transfers the array reference](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray%601+Builder.cs#L198-L201) to a new `ImmutableArray` and sets its own to an empty one. This takes O(1) constant time and does not require copying any data.
## Proposal

I propose adding a `StringBuffer` class that represents a fixed-length, mutable string. Its closest counterpart would be a `char[]`, except that it would use a string as its backing store and thus could be 'moved' directly to a string. Here is a rough sketch of how it would look like:

``` csharp
public class StringBuffer
{
    private string value;

    public StringBuffer(int capacity)
    {
        this.value = string.FastAllocateString(capacity);
    }

    public StringBuffer(char[] value)
    {
        this.value = new string(value);
    }

    public StringBuffer(string value)
    {
        this.value = string.Copy(value);
    }

    public int Length => value.Length;

    public unsafe void Replace(char from, char to)
    {
        if (Length == 0) return;

        // Modify the string in-place
        fixed (char* pch = value)
        {
            for (int i = 0; i < value.Length; i++)
            {
                if (pch[i] == from) pch[i] = to;
            }
        }
    }

    // Other methods, like CopyTo or ToCharArray

    // No length-changing methods like Append,
    // since this is supposed to be a fixed-size buffer

    public string MoveToString()
    {
        // Just do a pointer swap and empty out our reference
        // No copying needed, so this takes constant time
        var result = this.value;
        this.value = string.Empty;
        return result;
    }
}
```
## Usage

Existing code that looks like this:

``` csharp
// Replace non-ASCII chars with question marks
char[] buffer = input.ToCharArray();
for (int i = 0; i < buffer.Length; i++)
{
    if (buffer[i] >= 128)
        buffer[i] = '?';
}
var output = new string(buffer);
```

could be converted to look like this:

``` csharp
var buffer = new StringBuffer(input);
for (int i = 0; i < buffer.Length; i++)
{
    if (buffer[i] >= 128)
        buffer[i] = '?';
}
var output = buffer.MoveToString();
```
## Why not add MoveToString on top of StringBuilder?
- At the moment, `StringBuilder` is implemented internally on top of a `char` array. If we wanted to add a `MoveToString` method, we would have to refactor it to use a string as its backing store instead.
- The move would only be valid if the builder's capacity was equal to its count (see [here](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray%601+Builder.cs#L193-L196) for how `ImmutableArray` handles this); if not, the data would need to be copied to a new string anyway, since there would be trailing nulls left off the end of the string.

What are your thoughts on this?

**Comment by jamesqo** [comment]
cc: @jkotas @terrajobst @KrzysztofCwalina @joshfree @justinvp

**Comment by Grauenwolf** [comment]
> since there would be trailing nulls left off the end of the string.

Is that really a problem. Looking at the string class, it does have an internal field named m_stringLength. 

http://referencesource.microsoft.com/#mscorlib/system/string.cs,8281103e6f23cb5c,references

**Comment by jamesqo** [comment]
> Looking at the string class, it does have an internal field named m_stringLength.

Yes, but simply adjusting the length and returning it would create additional complications, since the rest of the unused string would be lying around in memory. The GC would somehow have to free only part of the string for this to be feasible.

**Comment by Grauenwolf** [comment]
The wasted memory doesn't concern me. Unless you are doing something silly like allocating a huge buffer for one character, it should still be cheaper than building more stuff for the GC to deal with.

But now I wonder about thread safety when it comes to StringBuffer. 

-----Original Message-----

**Comment by KrzysztofCwalina** [comment]
@vancem, could we just add this to StringBuilder?

@jamesqo, I am not opposed to adding your proposal to corfxlab. I just want to make sure we cannot do it in StrignBuilder. This would avoid having to explain to people why we have two different APIs for mutable strings.

**Comment by vancem** [comment]
@KrzysztofCwalina  As mentioned, the current StringBuilder implementation uses a list of char[] buffers as its underlying data representation.   Thus it would be a bigger change to think about.

However there is an important thread-safety issue that needs to be addressed.   In the past StringBuidler DID use a MUTABLE STRING as its backing store, however this BREAKS the IMMUTABILITY OF STRING in a concurrent environment.   Imagine one thread executing executing mutation opeations while another thread calls MoveToString, and hands it to another API which expects the strings not to change (it does check on it, then then assumes that that check does not need to be done again).    However because the other thread is still mutating the same string, and there is no locking to avoid such races, the clients of MoveToString, sees a string that seems to mutate (and thus break its cache of some check).

This was NOT a theoretical case.   Jeff Cooperstein took all of about 1 hour to make security exploits out of it.   Thus we had to fix it.   Locks are out of the question because they are slower than the copies that you are trying to avoid, so we came up with at cheezy,painful, thread local 'psuedo' lock, that basically only did the fast 'MovToString' if it could prove that all API calls were on the same thread.   Even so the checks were moderately expensive and the current implementation of stringbuilder was typically faster.   

Now maybe we don't care about security as much as we have in the past, but dropping the invariant of immutability in strings should NOT be done lightly, and certainly not for something as constrained as non-size-changing string updates.    Event without the security issue, you have the correctness issue (people WILL assume strings are immutable, and you will introduce HARD TO FIND BUGS, but having something like StringBuffer available.   

We go so far as in the IL spec, we say it is INVALID code for you to update the characters of a string.  The technically the code above is illegal (we reserve the right to put strings in read-only memory, and we almost did exactly this at one point in the runtime's evolution).

In short, we have some history with things like this, and I would not recommend this path.

My current recommendation for things like this is that we make StringBuilder the 'mutable string' and for SOME IMPORTANT APIs you take both a String or a StringBuilder, (e.g. reading and writing to the network / files).   In this way you can avoid copies (it is always a StringBuilder and thus never needs a copy).   This also lets you store the data as UTF8 which allows for even better efficiency.

However ANY proposal for things like strings needs a bunch of prototyping associated with it.   I am generally in favor of something that eliminates buffer copies like the StringBuilder idea above, but it needs rigorous evaluation first.  

However getting back to the issue of StringBuffer, because of its thread safety issues and narrow applicability, I don't think we should encourage StringBuffer in the library.

**Comment by svick** [comment]
@vancem Wouldn't those issues be solved by not mutating any published `string`s? So, `StringBuilder`/`StringBuffer` would mutate its private `string`, but as soon as `ToString()`/`MoveToString()` was called, it wouldn't be allowed to mutate the private `string` anymore?

The `StringBuffer` proposed above achieves this by swapping the private `string` with the empty `string`. `StringBuilder` could achieve a similar effect by using copy-on-write after `ToString()` was called. This requires some copies, which is what this proposal tries to avoid, but I think those are inevitable. (And in the common case, where you don't mutate after `ToString()`, it does save a copy.)

**Comment by vancem** [comment]
@svick  Certainly the intent of the code is that once MoveToString is called, then other threads can't access the string that it just 'gave out.  What I am point out is that the code has a serisous bug.   This simply is not true without putting 'lock' statements around the calls.    Consider two threads one calling MoveToString and the other calling Replace at the same time.   Replace calls its 'fixed' and starts walking the string.  Meanwhile, MoveToString gives you THE SAME STRING DATA and returns it as a 'string' (that is as something that is supposed to be immutable.    That returned value is passed on to code that expects this.    Meanwhile, Replace continues its work, updating character in the string, but it is modifiying the string that at this point is supposed to be immutable. 

Now if you put a lock around the methods, everything works again (since one or the other methods goes first, and the other waits until it COMPLETES).   Sadly doing this is typically MORE EXPESIVE than simply doing a copy, so is pointless.  

Thus this class breaks string immutabilty.   There are things typed as 'strings' that change their value over time.   This breaks most code that looks at strings more than once (which is a lot of cases).

**Comment by svick** [comment]
@vancem I think I understand now. I didn't consider that case, because it requires that you use the `StringBuffer` incorrectly (i.e. use it from multiple threads, even thought it's not thread-safe). In such case, it's okay that the `StringBuffer` does not work correctly, but you're saying that even in that case, `string`s should still appear to be immutable. Or in other words, it's fine if incorrect use of `StringBuffer` breaks the invariants of `StringBuffer`, but it's not okay if it breaks invariants of `string`.

**Comment by jamesqo** [comment]
@vancem, you have interesting points. I'd like to address them separately:

> Imagine one thread executing executing mutation opeations while another thread calls MoveToString, and hands it to another API which expects the strings not to change 

You're right, that is a serious problem I had not forseen. I think we can work around this, however, by throwing an exception if someone attempts to simultaneously mutate/move the `StringBuffer`. Something like this:

```cs
private int state; // 0 = dormant, 1 = being mutated, 2 = being moved

public void Replace(char from, char to)
{
    if (Interlocked.CompareExchange(ref state, 1, 0) != 0)
    {
        throw new InvalidOperationException("String is already being moved/mutated!");
    }

    try { /* Do the actual work... */ }
    finally { state = 0; } // reset to inactive state
}

public string MoveToString()
{
    if (Interlocked.CompareExchange(ref state, 2, 0) != 0)
    {
        throw new InvalidOperationException("String is already being moved/mutated!");
    }

    var result = value;
    value = string.Empty;
    state = 0; // reset to inactive state
    return result;
}
```

What would you think of that? It offers perf for the vast majority of single-threaded cases, since it replaces uses of locking with `Interlocked.CompareExchange`. Meanwhile, it also guarantees memory safety in the case where it is used concurrently; it is up to the developer to ensure correctness when using it from multiple threads.

> We go so far as in the IL spec, we say it is INVALID code for you to update the characters of a string.

We do it all the time in [StringBuilder](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Text/StringBuilder.cs#L353-L354) and [String](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.cs#L772-L774) though, why not here?

**Comment by vancem** [comment]
@svick  Yes, you got it now.   As you say, it requires people to use the type without proper synchronization.   In a world we used to live in (partially trusted code), it was clear we needed to keep the invariant under all circumstances.    In a world were we may not care about sandboxing, it is not as clear, but it is also not clear that we NEVER care about sandboxing, which is what we would need before we would break the invariant.

**Comment by stephentoub** [comment]
> since it replaces uses of locking with Interlocked.CompareExchange

Interlockeds are not cheap, especially if you need to do one for potentially every single character change (you'd need such protection around the indexer's setter, for example).  Without contention, a lock is often effectively just two interlockeds.

**Comment by jamesqo** [comment]
@stephentoub Ah, I hadn't realized that. Perhaps then we could just limit the mutations of the class to a single thread, like this:

```cs
private readonly int threadId = Environment.CurrentManagedThreadId;

public void Replace(...)
{
    if (Environment.CurrentManagedThreadId != threadId)
        throw new InvalidOperationException("Can only be used from a single thread.");
}
```

?

**Comment by vancem** [comment]
@jamesqo - In fact what you describe above is roughly where we landed in a previous version of StringBuilder (we fell back to a slow path rather than simply failing).    Note that even fetching thread local variables is not as cheap as you would like (but we should fix that).    

Note that because async methods might have their callbacks on different threads, throwing an error is probably a bad idea (if you used it twice in a async method across a 'await' it would fail, which certainly would surprise people.   

But clearly you can make it work.   You would want to do some benchmarking since it is not clear what you are actualy saving here.   It would be interesting to know how large the string has to be before you win.

On a more philosophical note, I find StringBuffer too constraining as a general abstraction.   The requirement that you don't change the size of the string seems pretty limiting.

**Comment by jamesqo** [comment]
@vancem:

> Note that because async methods might have their callbacks on different threads, throwing an error is probably a bad idea

True, that's a potential gotcha, but how else would you propose I'd report errors? Other than throwing an exception, the only other alternative I can think of is something like `bool TryReplace()`, which would be counter-intuitive for most people who know their program is running on a single thread.

> On a more philosophical note, I find StringBuffer too constraining as a general abstraction. The requirement that you don't change the size of the string seems pretty limiting.

I agree, but unfortunately that's the trade-off needed to make `MoveToString` work. Otherwise, we'd essentially be building another version of `StringBuilder`.

> But clearly you can make it work. You would want to do some benchmarking since it is not clear what you are actualy saving here. It would be interesting to know how large the string has to be before you win.

Sounds great. I'll create my own repo for this and submit a PR to corefxlab (along with benchmarks) once I get the time.

**Comment by vancem** [comment]
@jamesqo you asked what to do instead of throwing errors if you are on the wrong thread.   What we did in the past was to 'make it work' (you would take a lock and to the right thing).  It makes the code more complex but avoids the pitfall.   

But taking a larger view, I don't thing this class is general purpose enough to invest in publishing and teaching people about it.   It is fine as a thing that you or others use, but it does not seem worth 'productizing'.    Thus my real advice is to simply make it work for your case, but don't bother trying to get it into corefxlab.

I realize that is not what you want to hear, but that is my recommendation.   Instead we should invest in making StringBuilder into a more fully functional 'mutable string' and minimize copies by having direct support in hot paths for it.    This idea needs to be fleshed out and vetted, but it seems like one of the more promising directions.

**Comment by AlexGhiondea** [comment]
Based on the comments on this thread it looks like we don't believe this is something we want to pursue. As @vancem said we could instead focus our attention at improving StringBuilder.
