### ISSUE TITLE
build.cmd does not build solution on HP laptop (when Platform=MCD is pre-set)

### ISSUE THREAD

**Issue by xplicit** [dotnet/corefx#69]
I've got HP laptop with windows 7. When I run build.cmd, I've got the error "configuration is invalid"

    C:\Projects\dotnet\corefx>build.cmd
    C:\Projects\dotnet\corefx\src\System.Collections.Immutable.sln.metaproj : error MSB4126: указанная конфигурация решения "Release|MCD" недопустима. Укажите допустимую конфигурац
    ию решения с помощью свойств Configuration и Platform (например, MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") или оставьте эти свойства пустыми, чтобы
    использовать конфигурацию решения по умолчанию. [C:\Projects\dotnet\corefx\src\System.Collections.Immutable.sln]

The reason of this error is that environment variable `Platform` is set to `MCD` on the laptop by default. I have to change build command in the build.cmd by adding `/p:Platform="Any CPU"` to compile the project.

Build script should check for allowed platforms and generate user-friendly error message, which says what to do to successfully compile the project when the platform is not supported.

**Comment by nguerrera** [comment]
@joshfree @terrajobst I agree in principle, but basically every single msbuild-based project is vulnerable to environment variable collision. There are any number of ways to break the build with any environment variable that appears in the common targets. Try set TargetFrameworkVersion=xyz or set OutDir=!!!, etc. etc. etc.

**Comment by joshfree** [comment]
@nguerrera fair enough.  Doing a quick search shows the HP laptop/desktop "MCD" problem is reported all over the place since at least 2011 with various msbuild based projects.

Since the problem appears to be so common, most people should be able to unblock themselves easily enough with existing information online.  However if we could add a 1-liner check and make this easier for end users by printing out a useful error message that would be a nice minor enhancement.
