### ISSUE TITLE
SqlCredential - Missing assembly/namespace DNX Core5.0

### ISSUE THREAD

**Issue by divega** [dotnet/corefx#6948]
_From @nerradchoong on March 15, 2016 20:8_

I still have this assembly missing even after adding System.Data.SqlClient namespace in the dependencies.
has it been added yet or am i missing something ? 

_Copied from original issue: aspnet/Home#1355_

**Comment by divega** [comment]
_From @Eilon on March 16, 2016 2:2_

@divega @rowanmiller ?

**Comment by divega** [comment]
It appears that SqlCredential isn't included in the .NET Core version of SqlClient. Moving the issue to this repo to give the SqlClient owners a chance to answer if this is by design.

**Comment by saurabh500** [comment]
@nerradchoong The `SqlCredential` had a dependency on `System.Security.SecureString` .
`SqlCredential` needed `System.Security.SecureString` to store the password.

https://msdn.microsoft.com/en-us/library/system.security.securestring(v=vs.110).aspx

`System.Security.SecureString` is no longer present in .Net core because of which SqlClient cannot support `SqlCredential`

**Comment by nerradchoong** [comment]
Will this be implemented down the road?

**Comment by stephentoub** [comment]
@terrajobst, @weshaggard, @pallavit, when we removed SecureString, I know we fixed up other places to work with strings, e.g. ProcessStartInfo.  Were we aware of this issue with SqlCredential?

**Comment by pallavit** [comment]
> Were we aware of this issue with SqlCredential?

No, I was not aware of this dependency. Also, I looked at the history of the project and it seems the library removed dependency on SecureString from NetCore, long before we did the analysis and that could be the reason why it was missed.
