### ISSUE TITLE
DateTimeOffset.ToString Returns Different Value between Desktop and CoreFx

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#7012]
Please see the following example,

```csharp
        string format = "HH:mm:ss.fffffffzzzzzz";
        DateTime time = new DateTime(549269870000L, DateTimeKind.Local);

        DateTimeOffset offset = DateTime.MinValue + time.TimeOfDay;
        string offsetString = offset.ToString(format, DateTimeFormatInfo.InvariantInfo);

        string timeString = time.ToString(format);
        Assert.Equal(timeString, offsetString);
```

On desktop, timeString equals offsetString; but on CoreFx, they are not equal. Note that this issue seems related to Daylight Save Time change. The assert succeeded last week before the DST change.

The issue is blocking https://github.com/dotnet/corefx/pull/6762.

**Comment by tarekgh** [comment]
I don't think there is any difference between the desktop and corefx. I am running the same code on corefx and the desktop and I am getting the exact same result. ```timeString: 15:15:26.9870000-07:00, offsetString: 15:15:26.9870000-08:00```

I believe it used to get the same value for timeString and for offsetString because we were not in the daylight saving period.

when having 
            DateTime time = new DateTime(549269870000L, DateTimeKind.Local);

and when we are in the daylight saving, we should get -07:00 because the daylight saving is on and your format pattern is requesting time only (ignoring the date) so the TZ will show as -07:00.

when doing 
            DateTimeOffset offset = DateTime.MinValue + time.TimeOfDay;

it will always have the offset from UTC when instantiating the DateTimeOffset which will be 8 hours according to the value you passed. when formatting DateTimeOffset, it will just use the stored offset.

This is kind of the original confusion problems in DateTime design and that is why DateTimeOffset is introduced to avoid such problems.
If you want to get the same results in your test, you'll need to use the date parts in your format pattern.

I'll close this issue, but feel free to reply or reopen it if you have any more follow up points. Thanks for brining the issue.
