### ISSUE TITLE
SortedList dictionary initialization with case insensitive string comparer allows duplicate keys

### ISSUE THREAD

**Issue by kingces95** [dotnet/corefx#7019]
Expected an exception when SortedList is initialized with a dictionary that contains contains keys that differ only in case and a case insensitive string comparer.

```
using System;
using System.Collections.Generic;
using static System.Diagnostics.Debug;

namespace Scratch {

    public class Program {

        public static void Main(string[] args) {

            var sortedListFromDictionary = new SortedList<string, string>(
                dictionary: new Dictionary<string, string> {
                    { "A", "A" },
                    { "a", "a" }
                },
                comparer: StringComparer.CurrentCultureIgnoreCase
            );

            var sortedListFromList = new SortedList<string, string>(StringComparer.CurrentCultureIgnoreCase);
            sortedListFromList["A"] = "A";
            sortedListFromList["a"] = "a";

            Assert(sortedListFromDictionary.Count == sortedListFromList.Count);
        }
    }
}
```

**Comment by ellismg** [comment]
The problem is that the `.ctor` does not take into account that the comparer of the source dictionary may not be the same as the comparer using to build the list, so it just blindly reaches into the dictionary to pick stuff up.

```csharp
        public SortedList(IDictionary<TKey, TValue> dictionary, IComparer<TKey> comparer)
            : this((dictionary != null ? dictionary.Count : 0), comparer)
        {
            if (dictionary == null)
                throw new ArgumentNullException(nameof(dictionary));

            dictionary.Keys.CopyTo(_keys, 0);
            dictionary.Values.CopyTo(_values, 0);
            Array.Sort<TKey, TValue>(_keys, _values, comparer);
            _size = dictionary.Count;
        }       
```

The [documentation](https://msdn.microsoft.com/en-us/library/ms132326(v=vs.110).aspx) for the `.ctor` says:

>Every key in a SortedList<TKey, TValue> must be unique according to the specified comparer; likewise, every key in the source dictionary must also be unique according to the specified comparer.

In addition it says we could throw `ArgumentException` if "dictionary contains one or more duplicate keys."

It would appear we've done the wrong thing since this type was introduced in v2.0.  I think it's a reasonable thing to fix, but it would require a quirk on Desktop.

@stephentoub and @AlexGhiondea, what do you think?

**Comment by stephentoub** [comment]
Seems reasonable to fix.

**Comment by AlexGhiondea** [comment]
This would definitively require a quirk for Desktop.

**Comment by JonHanna** [comment]
Does that affect submitting a fix?

**Comment by AlexGhiondea** [comment]
@JonHanna I don't think so. When we end up porting this change over to Desktop we are going to introduce the quirk.
