### ISSUE TITLE
Open-source System.Threading.Tasks unit tests

### ISSUE THREAD

**Issue by nslottow** [dotnet/corefx#702]
Note: The implementation of this contract lives in mscorlib in the [coreclr](https://github.com/dotnet/coreclr) repository, but we are planning to put tests in this repo and test against the NuGet package produced by the coreclr repo.

**Comment by jasonwilliams200OK** [comment]
@mellinoe any updates on this?

(Bob created a duplicate issue https://github.com/dotnet/corefx/issues/850. Would be useful to have dedup functionality implemented in Bob! :traffic_light:)

**Comment by stephentoub** [comment]
He can correct me if I'm wrong, but I believe Eric is waiting for a new xunit to be used (#1876), as it should contain a change that makes it easier to test Tasks (https://github.com/xunit/xunit/commit/2f2efc5be1be468a3efe72ff5faa858b9f99926a).

**Comment by mellinoe** [comment]
To give an update: Yeah, I'm waiting on the latest Xunit because it should let us bring our existing tests forward without having to make a ton of changes to avoid deadlocks. These are Tasks tests, so naturally there's a LOT of calls that would have to be modified...

For what it's worth, I built my own simple console test runner yesterday and tried running the tests I have ported from our internal sources, and they ran just fine without any deadlocks. I also ran them all in parallel with Task.Run and they still worked fine.

Granted, they took an insanely long time (6+ minutes) to finish, so I will still need to choose a useful subset and mark the rest as OuterLoop before they can get up into here.

**Comment by AlfredoMS** [comment]
Any updates?

**Comment by mellinoe** [comment]
We still need the latest version of Xunit. There was a PR but it went stale:

https://github.com/dotnet/corefx/pull/1876

That is still what is blocking these tests in particular.

**Comment by mellinoe** [comment]
Fixed with #2775
