### ISSUE TITLE
Easier CngKey extraction from X509Certificate/X509Certificate2

### ISSUE THREAD

**Issue by FranklinWhale** [dotnet/corefx#7026]
Please provide methods in X509Certificate/X509Certificate2 or extension methods for easier CngKey extraction from X509Certificate/X509Certificate2.There should be at least 2 methods -- one for public key and another for private key.

**Comment by vcsjones** [comment]
There are already extension methods to do this. Use `GetECDsaPrivateKey` or `GetECDsaPublicKey` extension methods. They are already available in .NET Framework 4.6.1. Both of these return an instance of `ECDsa`. You can then type check it to see if it is a `ECDsaCng` type. If so, then use the `Key` property to get the CngKey.

There are likewise methods for RSA.

**Comment by FranklinWhale** [comment]
Thanks for the information, @vcsjones. I am aware of those methods but did not expect that they return CNG keys. I think the documentation of the methods should mention this fact.

**Comment by vcsjones** [comment]
I suspect it was done this way for xplat. CngKey is obviously Windows specific, and making different extension methods for each platform seems ugly. They couldn't use a platform-independent base type because `CngKey` derives directly from object.

Instead it looks like they went down the path of using instances of the algorithms themselves, which do have abstract classes that allow for an implementation by platform. The abstract classes do not have the Key property, probably because for the same reason key isn't directly exposed off the certificate in the first place. Since you are using Windows and specifically only seem to care about CNG, you can type case the algorithm to the CNG implementation.

That's all pure speculation, @bartonjs likely can tell the exact reason.

**Comment by FranklinWhale** [comment]
Yes, my code is currently Windows-specific.

The fact that the keys returned by the extension methods are always CNG keys if CNG is supported is important. It is because importing a key to CNG has been difficult but some stronger algorithms are only available in CNG.

I really hope that the documentations of [RSACertificateExtensions](https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.rsacertificateextensions(v=vs.110).aspx) and [ECDsaCertificateExtensions](https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.ecdsacertificateextensions(v=vs.110).aspx) will be updated.

**Comment by bartonjs** [comment]
@FranklinWhale What's your scenario?

Regarding the return types of the extension methods: They return whatever "the best" answer they can on the current platform.  Right now for Windows that means CNG-preferred.  In a couple years, maybe it'll be CS9, or Coyager (Cnterprise seems like a step backwards).

You definitely shouldn't hard-cast the answer as a \*Cng type; because we absolutely don't guarantee it.  But if it does `as` as a \*Cng type, you're free to make use of that.

**Comment by FranklinWhale** [comment]
Actually I am trying to migrate code that uses Security.Cryptography.dll to .NET Framework 4.6.1.

However, I have just noticed that the RSA base class now has the necessary methods for encryption, decryption, signature generation and signature verification. I think I will try and catch those methods for NotImplementedException instead of explicitly checking for RsaCng now.

Thanks!

**Comment by bartonjs** [comment]
@FranklinWhale It sounds like the discovery of the new RSA methods has solved your underlying problem... but before hitting close I wanted to make sure I wasn't mistaken.

**Comment by FranklinWhale** [comment]
Yes. The issue can be closed. Thanks.

**Comment by bartonjs** [comment]
Cool, glad you're able to move forward :)
