### ISSUE TITLE
Add RNGCng

### ISSUE THREAD

**Issue by FranklinWhale** [dotnet/corefx#7028]
The random number generator of CNG supports CPU RNG instructions, which provides better performance and randomness. I hope RNGCng can be added to CoreFx.

**Comment by bartonjs** [comment]
The Windows RNG is CNG-based; but no concrete type is exposed (only whatever answer is returned from `RandomNumberGenerator.Create()`).  Since there are no CNG-specific knobs and switches we want to expose, the type is unnecessary.

`RandomNumberGenerator.Create()` will always do whatever "the best" answer is.

Despite the naming, the hidden RNGCryptoServiceProvider type is actually CNG-based:
https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/RNGCryptoServiceProvider.Windows.cs#L14.

Since this is asking for a thing that is already true, closing the issue.

**Comment by FranklinWhale** [comment]
Nice. Code that uses RNGCng can be changed to use RandomNumberGenerator.Create(). Thanks for the information!
