### ISSUE TITLE
API for manipulating certificates

### ISSUE THREAD

**Issue by stukselbax** [dotnet/corefx#7129]
Will you plan to add the ability to create self-signed certificates, create a certificate signing requests - CSR, sign that CSR, and so on?

**Comment by bartonjs** [comment]
It is something that we want to do, yes; but right now the focus is on making sure that the things that we already have work reliably.

**Comment by Diastro** [comment]
+1 This is also a feature we are interested in.

**Comment by karelz** [comment]
We need API proposal.

**Comment by stukselbax** [comment]
I think that current `X509Certificate2` is almost ready for this. You need to provide ability to create empty in-memory instance of `X509Certificate2`, and allow several of it properties to be initialized, via setters or other initilialization technics - SubjectName, FriendlyName, ExtensionCollection, and so on.

You also need to add ability to set public/private key pair, which must be generated by the user using one of the [existing API](https://msdn.microsoft.com/en-us/library/5e9ft273(v=vs.110).aspx) for generating them.

After all initialization work is done, you could introduce new method `X509Certificate2.Sign()` with several overloads. For example:

```csharp    
    public class  X509Certificate2
    {
        ...
        /// <summary>
        /// Creates self-signed version of current certificate.
        /// Return value is X509Certificate2, because we (must) have privateKey.
        /// </summary>
        public X509Certificate2 Sign();

        /// <summary>
        /// Signs the certificate signing request. Useful for Certificate Authorities to issue new certificates
        /// </summary>
        /// <param name="csr">X509 Certificate Signing Request</param>
        /// <returns></returns>
        public X509Certificate Sign(X509CertificateSigningRequest csr);
    }

    public class X509CertificateSigningRequest : X509Certificate
    {
    }
```

I don't know if you need to introduce new `X509CertificateSigningRequest` class, because it is effective copy of `X509Certificate`, but the purpose are different. AFAIK, OpenSSL API allows Certificate Authorities to sign X509CertificateSigningRequest (a.k.a. `X509_REQ`), so that's why I propose to introduce new class.

You also can introduce `X509Certificate.Sign()` method, but in that case you need to pass `privateKey` explicitly, through the method parameter:

```csharp    
    public class  X509Certificate
    {
        public X509Certificate Sign(AssymetricAlgorithm privateKey);

        public X509Certificate Sign(X509CertificateSigningRequest csr, AssymetricAlgorithm privateKey);
    }
```

**Comment by danroth27** [comment]
We've hit a need for this as well in [ASP.NET Core Identity Services](https://github.com/aspnet/identityservices). We need to be able to issue [JSON Web Tokens (JWT)](https://jwt.io/) that have been signed with an asymmetric key, just like [Azure AD B2C](https://azure.microsoft.com/en-us/services/active-directory-b2c/) does today. The idea is that we want ASP.NET Core Identity Services to mimic the behavior of Azure AD B2C as much as possible so that you can easily migrate an existing ASP.NET Core app to the cloud service for its identity needs. To sign the tokens the app needs a certificate. We'd like to provide tooling and automation for generating signing certificates, but there isn't a good way to do that in a cross platform way with .NET Core.

**Comment by bartonjs** [comment]
@stukselbax I'm not very keen on the idea of making X509Certificate(2) mutable.

If one ignores the problem of (IFC) Diffie-Hellman keys it feels like it boils down to:

* CertificateSigningRequest.  Should be capable of expressing the values in PKCS#10/[RFC2896](https://tools.ietf.org/html/rfc2986).
* In addition to being created, a CertificateSigningRequest should be able to be loaded and inspected.
* It should be possible to create a [ToBeSignedCertificate](https://tools.ietf.org/html/rfc3280#section-4.1.2).  Since most CA processes don't just sign a CertificateSigningRequest as-it-requests (in particular, because they'd add a CRL Distribution Point, CA Policy, or other CA-based extension) this is a different construct than the CSR.
* It should be possible to sign a ToBeSignedCertificate.  The trouble with this is something needs to know how to build the AlgorithmIdentifier block, and the signing operation needs to (via parameters or polymorphism) discover how to do so.  "Use this `AsymmetricAlgorithm` private key" isn't good enough... Should it be RSA-MD2? (Okay, no).  RSA-SHA256?  RSA-SHA512?  RSA-SHA256-PSS?  So the signing job probably needs something like AsymmetricSignatureFormatter, but including "go build me an AlgorithmIdentifier blob"

And then we probably want some accelerators around things like self-signed certificates.

Optional extra: CRL creation and reading.

The X509SignatureBuilder (or whatever) type is even needed for self-signed certificates; since RSA-PSS makes things a bit more complicated than just "an AsymmetricAlgorithm and a HashAlgorithmName".

**Comment by stukselbax** [comment]
@danroth27 We also uses certificates to sing the JWT (and for TLS, of course), and currently we have wrapper on OpenSSL API (as stated in #16111) to create self-signed certificate, CSR, and to sign that CSR.

@bartonjs Good point about the immutable X509Certificate(2) instances.

About CA: I think it is implementation detail about which extension will be included into the resulted certificate - that extensions can be stored in any place, and basically are represented as [X509Extension](https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.x509extension(v=vs.110).aspx), since [CSR attributes](https://tools.ietf.org/html/rfc2986#section-4)  could be easily transformed to [X509Extension](https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.x509extension(v=vs.110).aspx) (as OpenSSL function X509_REQ_get_extensions(X509_REQ*) do). CA-based extensions will be represented as `X509Extension` in the result (`X509Certificate`), and I think that this will not affect API that will sign "something".

I'm not so good at cryptography and could not imagine the complexity you mentioned about RSA-PSS, but I think that this is implementaion detail, which will not affect public API seriously.

`X509SignatureBuilder` looks like `EVP_MD_CTX` in OpenSSL. It must be initialized before creating resulted object (either X509Certificate or CSR, or TBSCertificate, if it will be required). But in OpenSSL you also have to initialize all properties of X509 or X509_REQ before signing. Since you want X509Certificate(2) be immutable, all information requred to fill up this instance must be somehow prepared in `X509SignatureBuilder`. This can led us to the following structure (example):

```csharp
public abstract class X509SignatureBuilder
{
    public X500DistinguishedName IssuerName { get; set; }
    public X500DistinguishedName SubjectName { get; set; }
    public AsymmetricAlgorithm PrivateKey { get; set; } // TODO - What must be instead of AsymmetricAlgorithm?
    public PublicKey PublicKey { get; set; }
    public Oid SignatureAlgorithm { get; set; }
    public int Version { get; set; }
}

public class X509CertificateBuilder : X509SignatureBuilder
{
    public X509ExtensionCollection Extensions { get; }
    public string FriendlyName { get; set; }
    public DateTime NotAfter { get; set; }
    public DateTime NotBefore { get; set; }
    public string SerialNumber { get; set; }
    public X509Certificate Sign();
    public X509Certificate Sign(X509CertificateSigningRequest csr);
}

public class X509CertificateSigningRequestBuilder : X509SignatureBuilder
{
    public X509AttributesCollection Attributes { get; }
    public X509CertificateSigningRequest Sign();
}

public class X509CertificateSigningRequest
{
    public X509AttributesCollection Attributes { get; }
    public Oid SignatureAlgorithm { get; }
    public AsnEncodedData Signature { get; }
    public X500DistinguishedName SubjectName { get; }
    public PublicKey PublicKey { get; }
}

public class X509Attribute : AsnEncodedData { // TODO }

public class X509AttributesCollection : List<X509Attribute> { // TODO }
```

Some policy-based rules can be applied to the method which signs the CSR, it is also TBD.

I'm not claiming that this is how it must be done, but glad to break the deadlock and help to fill the gap in the framework. Hope you grab it asap.

**Comment by bartonjs** [comment]
There's been some reasonable discussion here, but in order to keep with the current trend of having an API proposal be the top entry in an issue (for ease of review) and not violate my personal hesitations of editing someone else's entry, I've created an API proposal at https://github.com/dotnet/corefx/issues/17892.

**Comment by karelz** [comment]
@bartonjs FYI: What I do is just insert text above the original report and add a heading to it `## Original report` ... that way it doesn't feel as hijacking someone's work ;-)
