### ISSUE TITLE
System.IO.Compression.ZipFile tests failed in Windows outer loop

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#7197]
See: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_windows_nt_debug/131/consoleFull

There is not much output from the log.
````
02:17:11   xUnit.net console test runner (64-bit .NET Core)
02:17:11   Copyright (C) 2014 Outercurve Foundation.
02:17:11   
02:17:11   Discovering: System.IO.Compression.ZipFile.Tests
02:17:11   Discovered:  System.IO.Compression.ZipFile.Tests
02:17:11   System.IO.Compression.Tests -> d:\j\workspace\outerloop_win---069ccc6f\bin\Windows_NT.AnyCPU.Debug\System.IO.Compression.Tests\System.IO.Compression.Tests.dll
02:17:11   Starting:    System.IO.Compression.ZipFile.Tests
02:17:12   no future
02:17:12 d:\j\workspace\outerloop_win---069ccc6f\Tools\tests.targets(130,5): warning MSB3073: The command "d:\j\workspace\outerloop_win---069ccc6f\bin/tests/Windows_NT.AnyCPU.Debug/System.IO.Compression.ZipFile.Tests/dnxcore50/CoreRun.exe xunit.console.netcore.exe System.IO.Compression.ZipFile.Tests.dll  -xml testResults.xml -notrait category=nonwindowstests -notrait Benchmark=true  -notrait category=failing " exited with code 1. [d:\j\workspace\outerloop_win---069ccc6f\src\System.IO.Compression.ZipFile\tests\System.IO.Compression.ZipFile.Tests.csproj]
02:17:12 d:\j\workspace\outerloop_win---069ccc6f\Tools\tests.targets(137,5): error : One or more tests failed while running tests from 'System.IO.Compression.ZipFile.Tests' please check log for details! [d:\j\workspace\outerloop_win---069ccc6f\src\System.IO.Compression.ZipFile\tests\System.IO.Compression.ZipFile.Tests.csproj]
````

The only thing standing out is this `no future` message in the log. This message appears a couple of times in assertions in the [clrcompression source](https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=%22no+future%22).

**Comment by bjjones** [comment]
This happens when the debug version of clrcompression.dll is used. 

This was recently changed by https://github.com/dotnet/corefx/commit/abe37cde4af561274e53b4fc87ad864e8d67efe0

I would choose to just leave default build to Release, otherwise there would need to be some way to get rid the asserts. 

@ianhays

**Comment by stephentoub** [comment]
@bjjones, are the asserts highlighting a real problem?  If yes, shouldn't that be fixed?  If no, shouldn't the asserts be removed?

**Comment by bjjones** [comment]
@stephentoub these originate from the Zlib-Madler source, and I can't say for sure what their purpose is. I have experimented with removing them in the past and there was no functional issue with passing the System.IO.Compression tests. That and just looking at the context, it looks like they are only informational and there's no reason not to remove them.

**Comment by stephentoub** [comment]
Is it possible that the customizations employed by Intel is actually what's triggering these? e.g. have you hit these just using the mainline zlib source?  Seems very strange that asserts which abort the process would be in the code for informational purposes.

**Comment by bjjones** [comment]
I do not believe the Intel modifications are causing the issue. The same problem occurred for me when testing a debug build of the pre-Intel clrcompression.

Yes, it is strange that these are killing the process.

**Comment by stephentoub** [comment]
Well, as a short-term wrorkaround, it seems like we should go back to using Release.  But I'd really like to understand why these asserts are here and why it's not causing a problem for anyone else in the world using a debug build of mainline zlib (or if it has, what the discussion was in those cases).

**Comment by bjjones** [comment]
I agree. I will contact the main Intel-Zlib developer and see if he has any insight.

**Comment by stephentoub** [comment]
Thanks, @bjjones.

**Comment by bjjones** [comment]
I've been looking around and I believe I've found the issue. In `corefx/src/Native/Windows/clrcompression/zlib/zutil.h`, there is: 

`#ifdef DEBUG`
`#define Assert(cond,msg) {if(!(cond)) z_error(msg);}`

and then z_error() calls the abort. The DEBUG looks to be meant for in-depth debugging of Zlib and is not commonly used. DEBUG was defined in `corefx/src/Native/Windows/CMakeLists.txt` (likely unintentional)

`if (UPPERCASE_CMAKE_BUILD_TYPE STREQUAL DEBUG)`
   ` add_definitions(-DDEBUG)`

And then I suspect that since System.IO.Compression.ZipFile.Tests intentionally runs invalid cases on clrcompression, it is triggering these scary sounding asserts. I'm working on validating this theory with System.IO.Compression.ZipFile.Tests, but at the moment my builds of CoreFX are hanging on initialization. At the very least, removing that define has it working with my perf benchmarks.

**Comment by stephentoub** [comment]
Thanks, @bjjones.  That sounds like a fairly plausible explanation.  What did the Intel-Zlib developer say about that?  If that's the case, and DEBUG really isn't meant to be set in debug builds, the fix would just be to not set it.

**Comment by bjjones** [comment]
No response from the developer yet, I'll report back here when I get it.
