### ISSUE TITLE
Vector<T> while debugging incorrectly reports size of register

### ISSUE THREAD

**Issue by mburbea** [dotnet/corefx#7304]
The `Vector<int>` type on a machine which supports 256 bit registers will return 8, however the debug/non-accelerated version of the register only will act as a 128bit register.

This means that algorithms that look like so::
```csharp
for(var offset= 0;count >=  Vector<int>.Count; count-= Vector<int>.Count, offset+= Vector<int>.Count)
```
Will go out of bounds or skip elements potentially while debugging giving an incorrect test.

**Comment by mellinoe** [comment]
Is this when debugging .NET Framework, or CoreCLR? There does seem to be a discrepancy here with respect to debugging behavior. When debugging CoreCLR, this works as expected:

![image](https://cloud.githubusercontent.com/assets/8918977/14090413/1608ba7e-f4ef-11e5-9cc1-5318cb3cac3f.png)
````
Count: 100, offset:0
Count: 92, offset:8
Count: 84, offset:16
Count: 76, offset:24
Count: 68, offset:32
Count: 60, offset:40
Count: 52, offset:48
...
````

But .NET Framework does exhibit the behavior you suggested (always using 128-bit register size).

@CarolEidt Is this expected, currently? I know this was originally how it behaved on CoreCLR, but we changed it so that you were able to debug the real register size. Are we able to take that change to the .NET Framework as well?

**Comment by CarolEidt** [comment]
@mellinoe I think you addressed the issue you are referring to in the library, with dotnet/corefx#2971, and I can't repro the issue with the latest library, but I'm not sure what version of System.Numerics.Vectors.dll that fix would be in.

**Comment by mellinoe** [comment]
> and I can't repro the issue with the latest library

Me neither. Actually, the latest version of nuget.org (https://www.nuget.org/packages/System.Numerics.Vectors/4.1.1-beta-23516), has the above fix (#2971) included in it. @mburbea Your issue seems a little bit different, though. Could you tell us which version of the library you are testing, which version of VS, etc.

**Comment by mellinoe** [comment]
@mburbea Could you let us know a few more details if you are still able to reproduce this issue?

**Comment by mburbea** [comment]
After updating to the latest beta release I am no longer able to reproduce
it. The debugger display when I drill into properties only shows int32 1 to
4 (not the remaining 4 ints), but I do see it in the tostring.

**Comment by mellinoe** [comment]
Which version of VS are you testing with, and which version of the packages did you upgrade to? That will help narrow down my testing. Unfortunately the laptop I was testing this on (with an AVX processor) is having some issues booting into Windows right now, so I'll need to fix that before I can try to get another repro.

**Comment by karelz** [comment]
We cannot reproduce the problem. If you still have problem with the latest VS+.NET Core, please reopen
