### ISSUE TITLE
Open System.Security.Principal.WindowsIdentity

### ISSUE THREAD

**Issue by mfe-** [dotnet/corefx#7325]
As a developer I need access to the current logged in active directory user to check if the user has a specific role.

Normally I do this with:

``` csharp
WindowsIdentity currentUser = WindowsIdentity.GetCurrent(); 
var groups = currentUser.Groups; 
//or 
groups.Claims
```

So I can get the SID or the groups of the user.

Most companies want to control the access of the user with active directory. The enterprise application uses this information to determine whether a user got access or not.

If there is no api to access this information, enterprise application development with uwp becomes uninteresting. Please help us out!

**Comment by joshfree** [comment]
related active directory issue https://github.com/dotnet/corefx/issues/2089

**Comment by danroth27** [comment]
@joshfree @vibronet I think this needs to go to someone on the Identity team.

**Comment by zhenlan** [comment]
This issue is blocking the WCF Windows authentication to work on http transport for Linux and OS X (dotnet/wcf#946)

**Comment by bartonjs** [comment]
@karelz I don't think this is part of the netstandard2.0 effort (I only see it in "extensions", not "standard"), so this probably needs to be put on someone's schedule somewhere...

**Comment by karelz** [comment]
@steveharter can you help out with this one? Do we understand the work?
@zhenlan is addressing it in 1.2 sufficient?

**Comment by zhenlan** [comment]
> @zhenlan is addressing it in 1.2 sufficient?

It's still a blocking issue for WCF, but if it's too late for 1.1, I think 1.2 is the best we can have. It's not a regression from 1.0.

**Comment by steveharter** [comment]
The WindowsIdentity.* APIs exist but are not supported on Linux. Every method will throw PNSE.

@karelz is the intent to get WindowsIdentity* APIs to work on Linux?

**Comment by karelz** [comment]
@steveharter I don't know enough about the space to have an opinion. From the request it looks like it is needed & valuable. Do you have insight on the pros/cons here? Or the work involved?

@zhenlan what is your expectation in the space from user point of view?

**Comment by zhenlan** [comment]
> @zhenlan what is your expectation in the space from user point of view?

Thanks @karelz. We are currently looking through all our usage of this API in WCF code and we think we may be able to work it around by avoiding using this API in all cases (on Linux build), so we are not blocked anymore. Back to your question, we expect the API to return network credentials on Linux. I am adding @mconnew to add any more comment of our expected behavior of this API.

**Comment by karelz** [comment]
The API is available on Windows. We do not think it makes too much sense on Linux/Mac.
Please let us know if you disagree.

**Comment by karelz** [comment]
BTW #9225 tracks Unix identity feature.

**Comment by phototropic** [comment]
If this API is not expected to be implemented for Linux/Mac, what is the recommended approach for getting a principal from the Kerberos default principal defined by kinit or a keytab from ktutil? In our environment Kerberos credentials are authenticated by AD. Wouldn't it be reasonable to define a principal based on this?

**Comment by karelz** [comment]
It would definitely be reasonable to define principal based on Kerberos default principle set on Linux machines. The problem is that the story on Linux distros and Mac is fragmented. Moreover, unlike on Windows, you can have potentially multiple principals/identities per local user account. The story on Windows is simpler (1:1 mapping between Kerberos/other principal and user account).

We would love to have APIs which are able to encompass all that. Ideally even abstract away the underlying OS from the user (if possible) and the underlying protocol (Kerberos, NTLM, etc.). All that requires careful thought and lots of area expertise, especially on Linux and Mac, to form a plan and design "the right" APIs for truly x-platform identity.
We will welcome any contributions to the API design (especially based on Linux/Mac expertise). In the meantime, we can keep collecting feedback and need from customers.

Disclaimer: All my knowledge about identity, Kerberos, etc. comes from a 20 minutes crash course yesterday, so please bear with me.


Now that I have at least basic insight into the space and re-read the issue again, I realize that:
1. @mfe- was originally asking for UWP support - if that is true, it should be satisfied with UWP implementing .NET Standard 2.0 (the plans & schedule is under discussion now).
2. The issue #9225 I linked above is actually NOT tracking the feature request to have truly x-platform identity, I think we need a new issue filed.
3. @zhenlan @mconnew how did you work around the problem in WCF? Did you by a chance read any Kerberos principals from known Linux locations? Or did anything that could potentially help our effort to create x-platform identity?

**Comment by phototropic** [comment]
Thanks for the reply @karelz. I wish I had the capacity to contribute in some meaningful way, but I too am a newb when it comes to authentication and cross-platform issues.

Unfortunately for my efforts, I had to give up on implementing a web service in .net core. Without having some relatively easy way to integrate our services through Kerberos I had to redirect my efforts to do a regular Windows/IIS implementation rather than the Linux/Kestrel one I was trying to POC.

**Comment by zhenlan** [comment]
> @zhenlan @mconnew how did you work around the problem in WCF? Did you by a chance read any Kerberos principals from known Linux locations? Or did anything that could potentially help our effort to create x-platform identity?

We just fall back to use a hard coded default user. It's okay for the specific WCF scenario involved here, but I don't think it can be a solution for this API.

**Comment by karelz** [comment]
Does it make the connection basically anonymous / unauthenticated? Or is the default user some process-wide / machine-wide setting?

**Comment by zhenlan** [comment]
@karelz we are not using it for authentication.
