### ISSUE TITLE
Building individual test projects on OSX has issues

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#7375]
Right now, if you run `msbuild <testproject> /t:RebuildAndTest /p:OSGroup=OSX` on some test projects on OSX, the run fails for a few reasons. In general, it seems that we are restoring some Windows binaries which fails early on, usually before any test runs. It seems that certain tests are not fully specifying their dependencies, which results in old versions of packages being pulled in. For example, System.Globalization.Tests.csproj, if run with the above command, fails when calling `Directory.GetCurrentDirectory()` in the Xunit console runner, because the System.IO.FileSystem.dll that is deployed next to the test is the Windows version. If you explicitly add a new version of this package to the tests dependencies, it is successfully restored and the test project gets further. Then it fails because the version of System.Runtime.InteropServices.RuntimeInformation.dll is the Windows version. If you add THAT to the project.json, then the tests finally pass.

Easy repro:
````
cd src/System.Globalization/tests
<corerun> <MSBuild.exe> /t:RebuildAndTest /p:OSGroup=OSX
````

Interestingly, this issue does not occur if you ALSO pass `/p:TestWithLocalLibraries=true`. I haven't figured out what is happening in this case, but the correct DLL's seem to be copied in if this flag is set.

It also shouldn't be necessary to pass `/p:OSGroup=OSX`, either. If this is omitted, no tests are run, though. We should auto-detect this and run tests anyways. We should have the information to make this possible.

It's likely that this is also affecting the other non-Windows builds.

@Priya91, @joperezr

**Comment by joperezr** [comment]
I'm not sure why it would be restoring the wrong packages, that seems definitely wrong. I think the reason why full builds work is because when we ran the BatchRestorePackages target of build.proj we actually restore all of the packages for all of the runtimes. Regarding the need to pass in the `OSGroup`, I guess I would have to debug but one possible cause that jumps to me is that we are defaulting at the beginning of the build `OSEnvironment` to be Unix for all OSX builds [here](https://github.com/dotnet/corefx/blob/master/dir.props#L10).

**Comment by ellismg** [comment]
The not testing unless you pass an explicit OSGroup thing also happens on Windows.

**Comment by mellinoe** [comment]
This has been fixed for a while, forgot to close it out.
