### ISSUE TITLE
Code coverage builds failing due to bin clashes

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7380]
The last few code coverage builds in CI have failed, with lots of errors like this:
```
16:19:59 Error : Multiple projects built twice with the same target path d:\j\workspace\code_coverage---7bd9c464\bin\ref\System.Threading\4.0.10.0\System.Threading.dll.
16:19:59 d:\j\workspace\code_coverage---7bd9c464\build.proj -->
16:19:59   Global Properties:
16:19:59     Coverage = true
16:19:59 d:\j\workspace\code_coverage---7bd9c464\src\tests.builds -->
16:19:59   Global Properties:
16:19:59     Coverage = true
16:19:59     DefaultBuildAllTarget = BuildAndTest
16:19:59     BuildAllProjects = true
16:19:59 d:\j\workspace\code_coverage---7bd9c464\src\System.Threading\tests\System.Threading.Tests.csproj -->
16:19:59   Global Properties:
16:19:59     Coverage = true
16:19:59     BuildAllProjects = true
16:19:59     OSGroup = Windows_NT
16:19:59 d:\j\workspace\code_coverage---7bd9c464\src\System.Threading\src\System.Threading.csproj -->
16:19:59   Global Properties:
16:19:59     Coverage = true
16:19:59     BuildAllProjects = true
16:19:59     OSGroup = Windows_NT
16:19:59 d:\j\workspace\code_coverage---7bd9c464\src\System.Threading\ref\System.Threading.csproj
16:19:59   Global Properties:
16:19:59     Coverage = true
16:19:59     BuildAllProjects = true
```
and then a note at the end:
```
16:19:59 MSBUILD : error MSB4015: The build stopped unexpectedly because the "ReusableLogger" logger failed unexpectedly during shutdown.
16:19:59 System.Exception: 66 bin clashes were detected during the build.
16:19:59    at Microsoft.DotNet.Build.Tasks.BinClashLogger.Shutdown()
16:19:59    at Microsoft.Build.Evaluation.ProjectCollection.ReusableLogger.Shutdown()
16:19:59    at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownLogger(ILogger logger)
```
@ericstj, does this look familiar?

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/code_coverage_windows/204/consoleFull

**Comment by ericstj** [comment]
Those are all real errors.  The build infrastructure is causing the those projects to build more than once.  Looking at the log it seems that this is happening because the Coverage property is causing the SerializeProjects global property to be set, but only for src projects since src\src.builds imports CodeCoverage.targets. https://github.com/dotnet/corefx/blame/master/src/dirs.proj#L25

Simple fix here is to not pass "SerializeProjects" to things that aren't traversal projects, similar to other properties: https://github.com/dotnet/corefx/blob/master/dir.traversal.targets#L33

Alternatively we could re-enable parallel build during coverage if folks think the concurrency issues have been fixed in newer builds of OpenCover.
/cc @weshaggard

**Comment by stephentoub** [comment]
Thanks, Eric.  I submitted https://github.com/dotnet/corefx/pull/7509 to address this as you suggested with the "simple fix".  I don't believe the issues related to parallel builds and coverage have been fixed.

**Comment by ericstj** [comment]
Thanks Steve.
