### ISSUE TITLE
DataConstractJsonSerializer should Escape '<', '>', and '&

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#7416]
@cyberphone submitted the following suggestion in #5647

> Having looked around a bit it seems that the JSON world is rather divided and needs to consider supporting two different serializations, one which is ES6-compatible and another which is ES6-compatible but properly escaped to be declared in browser as a JavaScript object. The latter means that '<', '>', and '&' must be expressed as \unnnn. Preferably quotes around identifier-compatible property names are also dropped in the JavaScript mode.

> Well, "on the wire" only real JSON encoding makes sense, but if you express JSON as a JavaScript object embedded in an HTML page like this
> 
 ```javascript
var jsonData = {
  myprop: "</script>"
};
```
> 
> it will break in a browser so I made (in my Java tools...), JavaScript a serializer option that:
> •escapes '<', '>', and '&'
> •removes "" around properties that adhere to JavaScript identifier syntax (excluding for example "my-prop")
> •prints data in a pretty (readable) way
> 
> The cool thing is that JSON.stringify() is unaffected by this change since it using ES6 restores data to its true JSON format!
>

**Comment by shmao** [comment]
Hi @cyberphone, I'm try to better understand the issue. Can you please help me with the following questions? Thanks.
1. Can you please explain a bit on the scenario where people would want to display the serialization payload on pages/in browser? 
2. Can you please point me to the specs for the serialization that is ES6-compatible but properly escaped to be declared in browser as a JavaScript object? 
3. Is the option you made in your tool like a switch for switching between these two kinds of serializations? Do other serializers provide any similar option?

**Comment by cyberphone** [comment]
Hi @shmao I will try to answer as good as I can:
1. If you want to provide in-page data to a browser application you practically always do that in the form of a JavaScript object.  On the server you typically have the data in .NET or Java objects.  Using JSON serialization "as is" is not 100% reliable which is why a JavaScript option is useful. 
2. This is not defined in ES6, it seems to be a "convention" by browser vendors to trigger on <code>&lt;/script&gt;</code>.  FWIW, it is the default mode in the "Go" language JSON implementation to do this escaping (which is bad)
3. I made it as a parameter to the serializer. The alternative is using a JavaScript filter after serialization.  The Go folks are considering changing their serializer the way I suggested but this is not a standard feature, just a rather practical thing.

**Comment by shmao** [comment]
Thanks for answering the questions, @cyberphone . We will discuss this suggestion in our meeting. I will get back to you later.

**Comment by shmao** [comment]
@cyberphone , given that escaping those characters is not specified by any standards, we don't think adding the feature in DataContractJsonSerializer to support displaying JSON payloads in browsers would be a good idea. It would make more sense to process the payloads in a JavaScript filter, as you mentioned, before displaying them in browsers.

I'm closing the issue now. Thanks again for submitting the issue and providing us the information.
