### ISSUE TITLE
DynamicCSharpRunTest test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7543]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_release_tst_prtest/3703/console

```
17:10:10 Failed: the finalizer hasn't executed!
17:10:10    ManagedTests.DynamicCSharp.Conformance.dynamic.context.operate.regclass.regstrct029.regstrct029.Test.DynamicCSharpRunTest [FAIL]
17:10:10       Assert.Equal() Failure
17:10:10       Expected: 0
17:10:10       Actual:   2
17:10:10       Stack Trace:
17:10:11             at ManagedTests.DynamicCSharp.Conformance.dynamic.context.operate.regclass.regstrct029.regstrct029.Test.DynamicCSharpRunTest()
```

**Comment by stephentoub** [comment]
Looks very similar to https://github.com/dotnet/corefx/issues/4688 but for a different test.

**Comment by JonHanna** [comment]
Maybe related, maybe different: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_tst_prtest/70/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8 and http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_release_tst_prtest/69/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8

**Comment by OmarTawfik** [comment]
Next step: repro, and verify if it is the same race issue as #4688.

**Comment by mellinoe** [comment]
Here's another similar issue (different test case):

https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/5166/consoleFull#-18813617262d31e50d-1517-49fc-92b3-2ca637122019

Test case is  `ManagedTests.DynamicCSharp.Conformance.dynamic.context.method.genmethod.regclass.regclass018.regclass018.Test.DynamicCSharpRunTest`

**Comment by Jiayili1** [comment]
Here's another similar issue (different test case):

https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170526.01/workItem/System.Dynamic.Runtime.Tests/analysis/xunit/ManagedTests.DynamicCSharp.Conformance.dynamic.context.operate.regclass.regclass025.regclass025.Test~2FDynamicCSharpRunTest

ManagedTests.DynamicCSharp.Conformance.dynamic.context.operate.regclass.regclass025.regclass025.Test.DynamicCSharpRunTest

**Comment by mellinoe** [comment]
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release_prtest/4276/consoleFull

**Comment by stephentoub** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release_prtest/4845/

**Comment by Jiayili1** [comment]
This issue is repro on Core Tests (Master), detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170803.01/workItem/System.Dynamic.Runtime.Tests/analysis/xunit/ManagedTests.DynamicCSharp.Conformance.dynamic.context.operate.regclass.regstrct029.regstrct029.Test~2FDynamicCSharpRunTest

**Comment by JonHanna** [comment]
I think I see the race. The tests are expecting the calls to `Foo()` to keep the instances alive until after the field the finalizer changes is set to the initial value, but there's no reason to expect it will since it's an easily inlinable method that doesn't touch any local fields (really it should be inlined as absolutely nothing) or anything else that would prevent GC from collecting.

We could just re-order the static being set and the ctor, but I wouldn't want to depend on that not being re-ordered, so it's simpler just to replace the `Foo()` call with `KeepAlive()`.
