### ISSUE TITLE
FileSystemWatcher and network shares

### ISSUE THREAD

**Issue by glennc** [dotnet/corefx#7576]
This is related to this bug: https://github.com/aspnet/dotnet-watch/issues/55

The scenario is that you are running your application inside a container using dotnet-watch. Dotnet-watch will watch your files and restart your app whenever you change your code. The issue is that when using Docker your source is typically mounted using something like Samba or VirtualBox shares which means you don't get watcher events fired.

What should dotnet-watch do in this case?

My current plan is to use a polling file watcher and have a way to launch dotnet-watch in a mode that uses polling when needed. Is there something we can do in corefx to make this better or is this completely up to dotnet-watch to implement?

**Comment by sokket** [comment]
Unfortunately, watching for file changes on network shares is highly dependent on the server platform as well as the client platform. For Windows, we use the [ReadDirectoryChangesW](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365465(v=vs.85).aspx) API; RDCW cannot watch for changes on remote machines without proper server support but I do not believe Samba supports this today. It does support [FindFirstChangeNotification](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364417(v=vs.85).aspx) for determining when something (generically) has changed, though. 

On Linux distros that use inotify, getting change notifications from network-based shares is explicitly not supported via the [man page](http://man7.org/linux/man-pages/man7/inotify.7.html). 

OS X has much less documentation around this, but anything I found (nothing first-party) specified the same thing; this isn't natively supported.

All of this means that, unfortunately, the built-in FileSystemWatcher classes will work for local changes OR (potentially) remove NTFS shares since I believe NTFS forwards change notifications. Otherwise, it's all dependent on the sharing protocol to support forwarding change notifications and, currently, Samba does not support (to my knowledge, at least). This means that you'll have to implement your own polling-based watcher for network-based shares :(. 

Sorry that the inbox classes won't work for your scenario :(. I'd be happy to answer any questions you have about file system change notifications or design questions however :)
