### ISSUE TITLE
Would it be possible to remove some of the LowLevel* classes?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#7634]
As I understand it, the purpose of the `LowLevel*` classes in `Common` (such as [`LowLevelEnumerable`](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Linq/LowLevelEnumerable.cs)) is to avoid a dependency on `System.Linq` or `System.Collections`, while still being able to use features from the collection classes. Unfortunately, they have to be maintained in tandem with their counterparts and as a result are more poorly optimized (e.g. [this](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Linq/LowLevelEnumerable.cs#L33) naïve implementation of `Select`, vs. [this](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Select.cs#L12) one).

Would it be possible to move the actual sources for the collection classes into `Common`, and a partial class that simply pointed people looking for the code to the `Common` folder? For example, we do this with `Debug` today; the actual source is [here](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Diagnostics/Debug.cs) in `Common`, while the file in `System.Diagnostics` is just there to [define public visibility](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Debug/src/System/Diagnostics/Debug.Public.cs).

cc @stephentoub @JonHanna

**Comment by stephentoub** [comment]
There's complexity that comes with that kind of code sharing as well, e.g. you need to use partial classes or #ifdefs to change the visibility of the type based on what it's being compiled into, you need to separate out just those pieces that should be included in various places or else you end up bloating the places that don't need it, etc.

In some cases, e.g. LowLevelEnumerable, I don't think it's a net win.

Then there's LowLevelList and LowLevelDictionary.  It's possible there'd be value in doing so, but a) the .NET Core implementation actually uses the ```List<T>``` and ```Dictionary<T>``` implementations that are in the coreclr repo (the ones in corefx are used on corert), b) we'd need to understand what the impact on the code would be to know whether it was worthwhile, and c) we'd need to evaluate whether any changes have been made to the LowLevel implementations over time that have caused them to diverge... some of those may be by design.

All in all, I'm not seeing a whole lot of need here.

**Comment by JonHanna** [comment]
Most of the advantages of the performance improvements made to `Select` only come into play with subsequent operations, so there's an immediate question of whether such subsequent operations are made use of where LowLevelList is used. Even there though the best approach might not be to remove it but to roll that combination into e.g. `SelectToArray()` and use that (an even greater performance gain should be possible that way too).

Beyond that (and indeed, including that) I think it's a reasonable possibility to investigate and see **if** it would gain something to change, but its not immediately obvious that it would, or would significantly until that investigation is done.

**Comment by jamesqo** [comment]
I think you guys make good points; will close. :smile:
