### ISSUE TITLE
Add Split string extension that returns IEnumberable<string> instead of an array.

### ISSUE THREAD

**Issue by SunnyWar** [dotnet/corefx#7656]
It's common when parsing strings to need a specific element from a parsed string. Currently, String.Split returns a fully parsed array of all the values, whether the developer needs them all or not. It would very useful to return a IEnumerable<string> that can be used in a Linq expression. Then this can be done:

string csv = "Bill, Gates, One Microsoft Way, Redmond, WA, 98052";

var lastName = csv.EnumerateString(',').Take(2).Last();

The function would not need to fully parse the string if it is done after the second item, in this example.

I wrote something like this many years ago and have found it to be very helpful, easier to read, and in many cases, faster than using Split.

**Comment by svick** [comment]
If you want readability, then I think the existing `csv.Split(',')[1]` is much better.

If you want efficiency, then I think you don't want to allocate strings for substrings that you don't need (like `"Bill"` in your example), so you would probably want something like `csv.SplitSubstring(',', 1)` (which doesn't currently exist).

**Comment by SunnyWar** [comment]
@svick I'll tell you my motivation. Perhaps it's a corner case. At one time I needed to parse10 of millions of files a day. The overhead of all the arrays and strings from Split was killing the performance. In this example I needed to (potentially) examine every string, short-cutting the Enumeration once a target was found...so I needed them but the arrays were superfluous. Using a simple enumerator cut down dramatically on the GC load and ran quite a bit faster.

**Comment by MgSam** [comment]
@SunnyWar That sounds like a rare enough scenario that it warrants writing the code yourself rather than expecting a general purpose library method to be satisfactory.

**Comment by SunnyWar** [comment]
@svick 

> If you want efficiency, then I think you don't want to allocate strings for substrings that you don't need 

But that's exactly what String.Split does now...allocated a bunch of substrings you don't necessary need. It's exactly what I want to _not_ happen.

**Comment by svick** [comment]
@SunnyWar I guess I was thinking about implementing `EnumerateString()` in terms of `yield return`, where you would have to allocate the intermediate string (you have to `yield return` *something* before moving on to the next part of the string).

Now that I think about it, a custom implementation of `IEnumerable<string>` could allocate the string only when you get `Current`, which would mean that `csv.EnumerateString(',').ElementAt(1)` would allocate only the one string that you actually want.

Though the problem with that approach is that `Current` is not commonly assumed to be an expensive operation and for example your original code (`sv.EnumerateString(',').Take(2).Last()`) would allocate too much, because `Last()`has to get `Current` for every item.

Or are you aware of another way to avoid those allocations?

So, I still don't think a method that returns `IEnumerable<string>` is the right approach here. Probably the best option is to wait for `Span<char>` (https://github.com/dotnet/coreclr/issues/5851) and then build a `Split`-like around that.

**Comment by AlexGhiondea** [comment]
As @svick suggested, a better approach to this (that would reduce string allocations) would be to write a Split method that would return you a bunch of Span object. Using the Span you can inspect the original string without needing to allocate a new substring.

I am going to close this for now but please feel free to re-open if there are use cases for this that we haven't considered.

**Comment by MgSam** [comment]
@AlexGhiondea Is there an issue, document, or blog post somewhere specifying `Span`? I keep seeing you guys reference it but I have no idea where the its specified.

**Comment by karelz** [comment]
It's taking its shape in corefxlab repo: https://github.com/dotnet/corefxlab/blob/master/docs/specs/span.md

**Comment by MgSam** [comment]
@karelz Thanks very much. Any reason this is in a whole separate repo rather than just a branch? It makes it super annoying for those of us on the outside to try and follow the development of .NET.

**Comment by mattwarren** [comment]
@MgSam The api review is [also available](https://github.com/dotnet/apireviews/pull/33)

> Any reason this is in a whole separate repo rather than just a branch?

It's in the [CoreFXLabs repo](https://github.com/dotnet/corefxlab) because that's where all the work was initially prototyped, it's now making it's way into CoreCLR, [this issue](https://github.com/dotnet/coreclr/issues/5851) tracks that process.

**Comment by karelz** [comment]
@MgSam check out the corefxlab repo main [README.md](https://github.com/dotnet/corefxlab) -- it is about experimental things. `Span<T>` starts as experiment, only baked subsets are slowly moving to corefx when they are useful on their own.

**Comment by MgSam** [comment]
Thanks again. Exciting stuff!
