### ISSUE TITLE
Make XunitTraitDiscoverers as a part of the custom Xunit.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#770]
Inorder to skip tests and other xunit functionality, the projects require an extra project reference to XunitTraitDiscoverers. Making this a part of the netcore xunit will be good. It's basically an extension on Xunit functionalities, and we should merge these two projects.

**Comment by mellinoe** [comment]
I'm not sure we should do this, since it's an independent layer built on top of XUnit. Also, in the long-term, I hope that we won't have a forked version of XUnit in the first place. Maybe it would make more sense to simply package up our trait discoverers into their own package that is more easily referenced?

**Comment by bartonjs** [comment]
I agree with @mellinoe that we don't want to keep having a forked build of xUnit.  It might make sense to move the custom traits into dotnet/buildtools as a standalone assembly, then we can share it across dotnet/corefx and dotnet/coreclr (at least).

**Comment by weshaggard** [comment]
I agree with @mellinoe and @bartonjs that it doesn't make sense for them to go into our xunit fork as we want to eliminate that and I'm not sure these are general enough for addition into xunit it itself so I think these are just for us. 

This project is also causing #745. Right now there is only 4 cs files and two concepts, ActiveIssue and OuterLoop (so we could collapse to two files) and I'm leaning towards just making these common source file imports. These are just a attributes that no one outside of the current xunit running process and the test need to know about and xunit discovers them via the base types so it would work fine for these to be shared source code.

**Comment by weshaggard** [comment]
After a little closer looking there isn't really a good way to have these be linked shared source code because the type and assembly name need to be contained in a custom attribute.

    [TraitDiscoverer("Xunit.TraitDiscoverers.OuterLoopTestsDiscoverer", "XunitTraitsDiscoverers")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    public class OuterLoopAttribute : Attribute, ITraitAttribute
    {
        public OuterLoopAttribute() { }
    }

So it looks like we will at least need to have another library to support these so we should consider putting that library somewhere else and referencing it via a package instead of building it all the time and doing a project to project reference which also requires it be contained in every solution file in corefx.

**Comment by Clockwork-Muse** [comment]
Looking forward to this being done, because I'm hoping we can eliminate the xUnit fork and pick up a newer version (wanting a bugfix dealing with parameter display).

**Comment by weshaggard** [comment]
I'm working on turning this into a package we produce in our build tools repo. However @Clockwork-Muse that doesn't help us get closer to eliminating our xUnit fork. If you think we need to update our XUnit version please file a separate issue with the information on that.
