### ISSUE TITLE
Unified HTTP API for client and server scenarios

### ISSUE THREAD

**Issue by robertsundstrom** [dotnet/corefx#7706]
I have been looking at the potential use of HTTP in IoT scenarios, and I have been wondering and thinking about the current stack that seems incomplete.

Historically, in .NET Framework, there has been two distinct set of HTTP API:s: one for handling client scenarios (HttpClient), and another for server scenarios (HttpListener). Both are residing in the System.Net.Http namespace.

Presently, there is no HttpListener in the .NET Core stack. It made me to build my own: https://github.com/robertsundstrom/HttpListener

I wonder if there are any plans to implement the HttpListener API further down the road. In any case, I have a suggestion for that:

Merge the two API:s so that they share a common base and common constructs like: HttpRequestMessage, HttpResponseMessage, etc. 

This would mean that the HttpClient sends an HttpRequestMessage, and the HttpListener should give a HttpRequestMessage. The content should be virtually the same in each end.

Correspondingly, the HttpListener would send a HttpResponseMessage back, and the client would receive a HttpResponseMessage.

In this way we get a more flexible API that is also easier to use, because the developers do not have to handle two sets of what actually could be the same thing.

**Comment by davidsh** [comment]
There are not plans to port System.Net.HttpListener to CoreFx.

However, the ASP.NET team has produced a new 'WebListener' that is expected to take it's place.

@danroth27 and @Tratcher can comment on that.

See:
https://github.com/aspnet

**Comment by danroth27** [comment]
@DamianEdwards @davidfowl 

For HTTP server scenarios we recommend using [ASP.NET Core](https://get.asp.net). ASP.NET Core includes a very fast and light weight listener and request handling pipeline that is designed to work for everything from full featured web applications to simple Web APIs on a Raspberry Pi. You can even run the entire pipeline in memory and invoke it with an HttpClient.

We have support for using the HttpRequestMessage/HttpResponseMessage model on the server via the [Web API compat shim package](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.WebApiCompatShim). However, the core HTTP abstraction in .NET Core are HttpContext based because model is inherently more flexible. I.e. you can build the HttpRequestMessage/HttpResponseMessage model on top of HttpContext, but the reverse isn't really true.
