### ISSUE TITLE
Crc32Helper set to internal within System.IO.Compression

### ISSUE THREAD

**Issue by xied75** [dotnet/corefx#7745]
Currently we have this:
https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression/src/System/IO/Compression/Crc32Helper.cs

Yet we can't use it for our own checksum calculation. Why it can't be exposed?

Best

**Comment by ianhays** [comment]
We don't expose it for the same reason that we don't expose [the](https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression/src/System/IO/Compression/Deflater.cs) [other](https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression/src/System/IO/Compression/Inflater.cs) [Zlib](https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression/src/System/IO/Compression/ZLibNative.cs) functions. They're thin wrappers around the underlying implementation and not relevant to regular use of the main System.IO.Compression functions e.g. when using a DeflateStream or a GZipStream you don't need to call Crc32 because it's already done.

Since they're not regularly used/required (and they're really just helper functions anyways), we don't expose them. If you do need to call Crc32, I'd recommend you do what we do in the helpers and pinvoke into zlib's crc32 function.

**Comment by xied75** [comment]
When you say user does not require that, you mean users in the old world, or users in the now Opened world? In the penguin world since everything is just file, people use crc32 or other checksums a lot to ensure their file integrity. And they also quite capable of designing lots of binary format, e.g. git Pack file again, or bioinformatics tools etc.

A simple google search on "c# crc32" you will see how many people have been wanting it from 10 years ago.

Some p.s. here: what is our attitude towards Python's "battery included"? Are Open Source .NET ever want to be like that or something else?

Best

**Comment by ianhays** [comment]
>you mean users in the old world, or users in the now Opened world

Specifically users of DeflateStream/GZipStream/ZipArchive. 

>In the penguin world since everything is just file, people use crc32 or other checksums a lot to ensure their file integrity.

This issue is closely related to the discussion over at #6517. Also check out https://github.com/dotnet/corefx/issues/4123. Crypto has libraries for MD5 and SHA hashing which iirc are generally preferred to crc32 (though admittedly it's not my area of expertise). For that purpose you'd want to add crc32 support to Crypto rather than to Compression.

>Some p.s. here: what is our attitude towards Python's "battery included"? Are Open Source .NET ever want to be like that or something else?

I can't seem to find out what that actually means. Mind elaborating on that?

**Comment by xied75** [comment]
My impression is that crc32 or adler32 are used more for I/O than security, so not very sure about this should belong to Crypto.

Python has a philosophy that everything you want should be provided by the release/community for at least once, i.e. you don't need to go out again to buy battery to play the toy. 

https://en.wikipedia.org/wiki/Batteries_Included
(Item 3)

**Comment by ianhays** [comment]
>My impression is that crc32 or adler32 are used more for I/O than security, so not very sure about this should belong to Crypto.

IMO it would make more sense there than in Compression. I could also see the argument for putting it in System.IO.FileSystem. Though admittedly it'd be easier to implement in compression since it's already here, just internal.

**Comment by lextm** [comment]
@xied75 your question at top and the following comments are okay but you should notice what the Microsoft guy tries to explain.

The class you want to turn to public is under the Compression package as that package uses CRC. But it would be difficult for the Compression package owner (current at Microsoft) to expose this API, as that algorithm itself is not suitable to sit there.

As other threads have demonstrated you should propose a new API following the standard process (yes, there is a process to go as you are probably the first eager user to request it), and then via review and discussion Microsoft and the rest of the community can determine which package/namespace should this new CRC API go.

The process works fine for other new API already, so it should work for you if you try.

**Comment by ianhays** [comment]
I'm closing this for now as I don't have any plans to expose the Crc32 helper in System.IO.Compression and the discussion has digressed. Feel free to submit an API suggestion for a public CRC32 API following the [API Review process guidelines](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md).
