### ISSUE TITLE
System.Console is generation 1.3, yet it is supported by .NET 4.5 (gen 1.1). How does that work?

### ISSUE THREAD

**Issue by Flavien** [dotnet/corefx#7816]
[Question from twitter](https://twitter.com/FlavienCharlon/status/721299923224944640?lang=en): System.Console is generation 1.3, yet it is supported by .NET 4.5 (gen 1.1). How does that work?

Also, what if in the future we have a platform that supports System.IO.IsolatedStorage (1.4) but not System.IO.FileSystem (1.3)?

Paging @davidfowl for this.

**Comment by joshfree** [comment]
thanks for reporting this @Flavien

**Comment by ericstj** [comment]
The System.Console contract/package is not supported by NET 4.5.  We only support System.Console starting with .NET 4.6.
https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System.Console.builds#L18.  

IsolatedStorage and FileSystem are different: FileSystem is part of Standard Library, where IsolatedStorage builds on top of Standard Library.

For packages that build on top of Standard Library, they will come "for free" in future frameworks that implement the version of Standard Library required by the package's implementation.  In the case of IsolatedStorage it does not have a NETStandard implementation: it's implementation is platform specific since it depends on platform-specific WinRT.  It will only work on future frameworks if a platform-specific implementation is added for that platform.  Contrast this to another library like System.Collections.Immutable: this library builds on top of netstandard1.0 with no platform-specific calls so it will come for free on all future frameworks implementing netstandard.

In the case of FileSystem, this library is **part of** .NET Standard library, so a new framework must implement it if it claims to support NETStandard 1.3 or higher.  You can imagine a new framework implementing only NETStandard 1.2 and not carrying an implementation for FileSystem.

/cc @weshaggard

**Comment by Flavien** [comment]
These are all new concepts to me. Please tell me if I understand this correctly:

- You have a [small set of assemblies](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#list-of-proposed-standard-platform-contracts-from-corefx-tentative) that are platform specific and come at a specific generation. For example ``System.IO.FileSystem`` is part of generation 1.3 and above while ``System.Threading`` is part of 1.0 and above.
- Non-platform specific assemblies like ``System.Collections.Immutable`` simply target a specific generation (1.0 in that case), and have access to all assemblies of the same generation (and below), both platform-specific (like ``System.Threading``) and non-platform specific (like ``Microsoft.CSharp```), but not ``System.IO.FileSystem`` since it's a higher generation.
- There are also platform specific assemblies that are **not** part of the NETStandard (like WPF assemblies), and to use these from your project, you need to target that platform specifically (as opposed to NETStandard). ``System.Console`` for .NET 4.5 falls under that category.

Does that sound correct?

**Comment by ericstj** [comment]
This sounds mostly correct.  

We still require a reference to the "NETStandard.Library" package in order to bring in the set of references in standard library.  This small set of assemblies has behind it a strong promise that every .NET framework must implement them in order to claim support for .NET standard.

One additional piece of data is that each package may expose different API at a particular generation.  For example: `System.Threading` in `netstandard1.3` has more API than `netstandard1.2`.  In general you can think of newer NETStandard versions as supporting fewer platforms but having more API.

> platform specific assemblies that are not part of the NETStandard (like WPF assemblies)

There are actually two distinctions here.  Consider that there is a package ecosystem that defines surface area in the context of **every** .NET platform.  For packages these may still have platform specific implementations that limit availability (eg: IsolatedStorage).  There are also project types that pre-date packages and use platform-specific **reference assemblies** to represent their surface area.  These reference assemblies are specific to the platform and are missing any data encoding which other platforms they may support.

> System.Console for .NET 4.5 falls under that category.

`System.Console` the *type* happened to exist before we created the notion of nuget representing all .NET surface area.  It still exists in the classic platform-specific reference assemblies for old project types.  We did the work in the packages to represent that type starting with .NET 4.6, but didn't go back to .NET 4.5.  Work could be done to make a representation of the Console surface area back to .NET 4.5, but we'd also need to consider what to do on other existing NETStandard supporting frameworks (eg: Windows Phone, Windows Store).

**Comment by ericstj** [comment]
Closing this.  Let me know if you still have questions and I'll reopen.
