### ISSUE TITLE
Stub System.Data with type redirections to System.Data.Common

### ISSUE THREAD

**Issue by AndrewZakharkin** [dotnet/corefx#7874]
ODP.NET is complied against System.Data and now cannot be used under CoreCLR

**Comment by mgravell** [comment]
To ask the obvious question: since ODP.NET will certainly need to be re-packaged to target core-clr, can it not just *add the necessary references*? Having done multiple library conversions, I very much doubt that *just* adding some type-forwarded markers will be the thing that makes ODP.NET wbuild and work correctly against core-clr.

**Comment by AndrewZakharkin** [comment]
With the stub System.Data it won't be fully functional obviously. But it will work at least at "helloworld" level. Fair temporary solution. Now it doesn't work at all.

**Comment by saurabh500** [comment]
@AndrewZakharkin There is no plan for such forwarders in .Net core. 
The library authors will need to recompile the libraries against .Net Core.
