### ISSUE TITLE
Building System.Net.Primitives.FunctionalTests against packages fails

### ISSUE THREAD

**Issue by venkat-raman251** [dotnet/corefx#7906]
Building the FunctionalTests with /p:BuildTestsAgainstPackages=true throws errors. Currently <KeepProjectReference>true</KeepProjectReference> has been added to keep the project reference.
We should be able to remove this project reference (just reference the nupkg) and build the test project without errors.

**Comment by venkat-raman251** [comment]
@weshaggard : Who is the owner of this lib?

**Comment by davidsh** [comment]
cc: @ericstj

**Comment by weshaggard** [comment]
Since @davidsh subscribed to this issue I will assign it to him :)

For context @davidsh we are working on getting a number of our test projects such that they can build and run against our packages and not require direct access to the ProjectReferences and thus APIs only in the implementations. This enables us to get better test coverage of our actual packages and to decouple our test and product build steps. 

There are a couple options here:
1) Keep the existing test project as is so that it tests against the implementation, but if we do we should create another test project (assuming there isn't already one) that does work against packages so we get that test coverage for System.Net.Primitives.
2) Update the test project so that it works purely against the package which means it will need to only consume APIs in the public contract.

**Comment by ericstj** [comment]
Here's a sampling of the errors that the tests got when building against reference assembly rather than impl:
```
CookieContainerTest.cs(37,17): error CS1501: No overload for method 'Add' takes 1 arguments [E:\work\github\corefx\src\System.Net.Primitives\tests\FunctionalTests\System.Net.Primitives.Functional.Tests.csproj]
CookieContainerTest.cs(72,38): error CS1729: 'CookieContainer' does not contain a constructor that takes 1 arguments [E:\work\github\corefx\src\System.Net.Primitives\tests\FunctionalTests\System.Net.Primitives.Functional.Tests.csproj]
CookieCollectionTest.cs(116,29): error CS1503: Argument 1: cannot convert from 'int' to 'string' [E:\work\github\corefx\src\System.Net.Primitives\tests\FunctionalTests\System.Net.Primitives.Functional.Tests.csproj]
CookieContainerTest.cs(85,38): error CS1729: 'CookieContainer' does not contain a constructor that takes 3 arguments [E:\work\github\corefx\src\System.Net.Primitives\tests\FunctionalTests\System.Net.Primitives.Functional.Tests.csproj]
```
I believe most of these just need to be ported to use the public API, I couldn't see any value the tests were getting out of using the old desktop-only API.

**Comment by davidsh** [comment]
@weshaggard I have a question about your proposal:

>2) Update the test project so that it works purely against the package which means it will need to only consume APIs in the public contract.

For all libraries, we want to be able to test the real-time code of the product sources on both a developers machine as well as CI.  So, every library we have, say System.Net.Http as a tests project where it doesn't reference the System.Net.Http package but rather the product source via P2P reference.

This is also true to System.Net.Primitives.

So, I would not want to change the CSPROJ to use package reference instead of P2P.

However, will this build parameter ` /p:BuildTestsAgainstPackages`change the CSPROJ behavior. So, even if the CSPROJ uses P2P, it will substitute a package reference instead?

**Comment by davidsh** [comment]
cc: @CIPop

**Comment by CIPop** [comment]
@davidsh Maybe we can move the tests with internal dependencies to the UnitTests to allow the dual run of direct project reference as well as the package test?

**Comment by weshaggard** [comment]
You can continue to test some stuff as you are with a ProjectReference as one test project but we need other test projects that only build against the contracts (via packages). Those test projects give us test coverage on the actual packages to ensure they are correct as well as enable us to run a set of common tests on all the different platforms that your package supports to ensure the behavior is consistent. 

This change is a precursor to getting the test projects working on .NET Framework and .NET Native.
