### ISSUE TITLE
Building System.Sec.Crypto.Cng.Tests against packages fails

### ISSUE THREAD

**Issue by venkat-raman251** [dotnet/corefx#7908]
Building the Tests with /p:BuildTestsAgainstPackages=true throws errors. Currently <KeepProjectReference>true</KeepProjectReference> has been added to keep the project reference.
We should be able to remove this project reference (just reference the nupkg) and build the test project without errors. @bartonjs @weshaggard

**Comment by AtsushiKan** [comment]
Err... there's something in the build pipeline for this that's depending the environment variable **%BuildTestsAgainstPackages%** rather than the msbuild property **$(BuildTestsAgainstPackages)**.

If I build like this, I get the build errors (because the build pipeline isn't passing the Cng contract as a reference to csc)

`msbuild -t:clean;build;test -p:Configuration=Windows_Debug -p:BuildTestsAgainstPackages=true
`

But if I build like this:

```
set BuildTestsAgainstPackages=true
msbuild -t:clean;build;test -p:Configuration=Windows_Debug 
```

it builds, runs and tests just fine.

By the way, I get the same pair of results if I try this with SSC.X509Certificates\Tests, which is reportedly package-capable as of 14 days ago (https://github.com/dotnet/corefx/issues/7910)

So I don't think there's a Cng test issue here (other than just removing the KeepProjectReference tag.)

**Comment by bartonjs** [comment]
I really wish Josh (or github) would tell me when he reassigns things away.

The failure on this is that we have tests for AesCng/TripleDesCng, but they're not in-contract.  I'm waiting for Steve Harter's ECDsa changes so we don't have to bump it twice.

**Comment by AtsushiKan** [comment]
Oh right – I actually remember seeing those two classes missing from the contract a few days ago, but naturally, I didn’t write it down and I couldn’t get back to that exact error message because of the build pipeline issues I noted (or maybe the instructions in the issue are just inadequate.)

So do you want the bug back? It sounds like it’s already on your to-do list as soon the ECDSA stuff comes in.
