### ISSUE TITLE
Windows Process.Start does not handle unicode characters in Arguments properly

### ISSUE THREAD

**Issue by brthor** [dotnet/corefx#7935]
I discovered this while investigating https://github.com/dotnet/cli/issues/2486

I have reproed this using CoreFX version 1.0.0-rc2-24008, and 24018.

What I see happening is that the correct string is passed all the way to Process.Start, but when the process is started, the string is no longer equivalent in args. This doesn't repro on non-windows.

I've added a few cli specific tests exhibiting this here (I think the main takeaway is that it is windows only):
https://github.com/dotnet/cli/pull/2610

And I've put together an independent repro here:
https://github.com/brthor/corefx-process-unicode-repro

To use the repro, install the latest dotnet cli via https://github.com/dotnet/cli, clone the repo, and run run.cmd.

cc @piotrpMSFT @stephentoub

**Comment by gregg-miskelly** [comment]
@brthor should this be in the RC2 milestone?

**Comment by tarekgh** [comment]
@piotrpMSFT just wondering, why this is rc2?

**Comment by gregg-miskelly** [comment]
Because this breaks installing the debugger for anyone who has any special characters in their name (ex: accents).

**Comment by tarekgh** [comment]
cc @weshaggard 

There is no bug here. The parameters passed to the spawned process were sent correctly so there is no any problem in this part. the issue show up when getting the redirected output stream 
```
            var stdOut = proc.StandardOutput.ReadToEnd();
```
because .NET core by default doesn't support all encodings we used to support in the desktop (https://msdn.microsoft.com/en-us/library/system.text.encodingprovider(v=vs.110).aspx), the encoding used by the console is not one of the default supported encoding and then we'll fallback to use UTF8 encoding which produce different output then the original console encoding.

To make this work, will need to opt-in of using the full encoding. you do that by referencing ```System.Text.Encoding.CodePages``` in your project.json and then call ```Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);``` in your initialization code and everything will fully work. 

please let me know if you have any question.

**Comment by gregg-miskelly** [comment]
Sorry if I am butting in and saying something useless - but is another option to explicitly use UTF-8 in both processes so they don't need to worry about encoding?

**Comment by tarekgh** [comment]
When launching a process which using the Console, Process class doesn't know if the process to launch is really using Console or not. Also the control of the console encoding can be done either from the system settings or from the console process itself (through Console.InputEncoding and Console.OutputEncoding). so Process class cannot control the encoding there.

by the way, the link https://msdn.microsoft.com/en-us/library/system.diagnostics.process(v=vs.110).aspx is also mentioning the issue we are discussing here and how to make it work.

**Comment by tarekgh** [comment]
Closing the issue but feel free to reply back if you have any more questions.
