### ISSUE TITLE
run-tests.sh is copying files to directories

### ISSUE THREAD

**Issue by krytarowski** [dotnet/corefx#8029]
`run-tests.sh` is copying files to directories, it's bad for: limited storage and need to rollback to the state before copying files to rerun tests (takes time).

Could you please refactor it and stop duplicating files in a dir with tests?

**Comment by ellismg** [comment]
> Could you please refactor it and stop duplicating files in a dir with tests?

The goal of these tests is to not rely on a shared framework.  Instead each test gets its own complete copy of the runtime and supporting libraries.  This is in line with one of the deployment models for CoreCLR/CoreFX, you bundle everything together with your app.

On windows, we use hard linking when we build the test layouts instead of copying the artifacts to each folder.  We should be able to start doing that as well on Unix when the build is driven by MSBuild via `build.sh`.

The long term plan is to move off of `run-tests.sh` and onto `build.sh` for both building and doing test execution, just like on Windows. We can explore making tactical changes here (maybe hard link instead of copying stuff from the test overlay into the individual tests?) but we shouldn't do radical changes like trying to have one copy of the run-time that is shared across multiple tests.

**Comment by krytarowski** [comment]
Hard-linking should be fine, at the moment I'm not able to run tests on ramdisk and run tests quicker.

Thank you!
