### ISSUE TITLE
Adding a StringBuilderCache-like API to System.Buffers

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#8112]
We have a `StringBuilderCache` [class](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/IO/StringBuilderCache.cs) in `Common` that caches `StringBuilders` per-thread so a new one doesn't always have to be allocated in certain scenarios. Unfortunately, this class is compiled separately for each project, so each assembly gets a new cache. It would probably be useful to expose a central place (both in corefx and to end-users) where `StringBuilders` can be rented and returned, similarly like we do with `ArrayPool.Shared`.

**Comment by KrzysztofCwalina** [comment]
Yeah, I talked with @sokket about adding object pool to corefx. Maybe not to System.Buffers though.

**Comment by jamesqo** [comment]
@KrzysztofCwalina Why not? The [description](https://github.com/dotnet/corefx/blob/1b55230f4ed2b16a7078683305c998a4575c2854/pkg/descriptions.json#L179) in the JSON file says it "provides resource pooling of any type." Correct me if I'm wrong, but wouldn't that suit an object pool-like API?

**Comment by alexperovich** [comment]
@jamesqo Can you create an api proposal?

**Comment by danmosemsft** [comment]
Perhaps `StringBuilderCache` should be public. As well as being useful we could then reuse the cache across assemblies. I'm thinking the BCL itself might prefer to keep using its own though as it would add a point of fragility: a misbehaving user can reuse the StringBuilder after returning it.

**Comment by karelz** [comment]
We need formal API proposal - e.g. making StringBuilderCache public, but thought through from all angles as proper public API.

**Comment by jamesqo** [comment]
@karelz, yep. I didn't submit a proposal yet since I'm not sure how `StringBuilderCache` is currently written is the way to go.

Would it be feasible to add APIs to StringBuilder allowing it to use pooled `char[]`s, instead of pooling the StringBuilders themselves? That way we wouldn't have to change System.Buffers at all, just use `ArrayPool<char>.Shared.Rent`, feed it to the StringBuilder, and return it when we're done. Or if we did add new APIs, they would just wrap that logic.

**Comment by karelz** [comment]
How would the StringBuilder API look like? We do not want to mess it up too much.
Having extra Pool/Cache type helps to isolate the caching logic details in there ... (just my 2 cents, I don't have deep expertise here)

**Comment by NickCraver** [comment]
FWIW, here's what we're using at Stack Overflow: https://github.com/MiniProfiler/dotnet/blob/master/src/MiniProfiler.Shared/Internal/StringBuilderCache.cs

I agree this really should be in the BCL, we're basically copy/pasting it to every high performance project with a `StringBuilder`.

**Comment by stephentoub** [comment]
I don't think we should do this.  StringBuilderCache has its limits, and we've actually been slowly but surely decreasing the number of places we use StringBuilderCache throughout coreclr and corefx, instead preferring to use the ref struct ValueStringBuilder, which a) let's us use stack space, b) shares in the more general ArrayPool pooling rather than maintaining its own cache, c) avoids issues StringBuilderCache currently faces with regards to multiple portions of an operation each wanting their own StringBuilder (currently there's just one cached), d) avoids issues around not caching when a particular StringBuilder gets "too big" (which actually isn't all that big), etc.

Given https://github.com/dotnet/corefx/issues/28379 and a variety of related proposals like https://github.com/dotnet/corefx/issues/30114, I'm going to proactively close this one.
