### ISSUE TITLE
Allow DisplayAttribute on Class declarations

### ISSUE THREAD

**Issue by cervengoc** [dotnet/corefx#8123]
Hello, I'd like you to consider allowing `DisplayAttribute` on class declarations. Forgive me if this is a duplicate, I haven't found anything related. Some use cases for it:
- Auto-generate form captions
- Auto-generate report captions
- Use this information to extend nested property captions (like `Person.Details.Address` could get a label as `Personal info / Address`)
- Auto-generate documentation (consuming `Description` and `Order` for example)
- etc.

**Comment by joshfree** [comment]
@lajones PTAL

**Comment by divega** [comment]
Data Annotations Triage: This seems to be a reasonable request. It is likely that changes would be needed on frameworks that use data annotations such as ASP.NET Core MVC (maintained in http://github.com/aspnet/mvc/) in order for it to work end-to-end.

**Comment by brunolins16** [comment]
@divega, I'm interested in working on it. Can I PR the DisplayAttribute class changes and if accepted submit a issue on ASP.NET Core MVC repo?

**Comment by karelz** [comment]
@brunolins16 I sent you collaborator invite, so that we can assign the issue to you. Ping me once you accept the invitation and I will assign the issue to you. Assigning to myself temporarily.
Note: Being collaborator will automatically make you watch the entire repo (500+ notifications per day). I would recommend to change it to "Not Watching" to get only mentions.

**Comment by mikernet** [comment]
Just curious, how do changes like this to the .NET Core API flow back into the .NET framework? Can I expect this change to be included in .NET Framework vNext as well? This issue is forcing me to use a rather nasty kludge at the moment for required functionality of a library.
