### ISSUE TITLE
Need copy/paste-able instructions for installing Linux dependencies

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#8136]
Users who are only interested in CoreFX assemblies may only read this page:
    https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md
Which does not contain the actual package names needed, and thus can be challenging to follow.  

The CoreCLR Version does contain a copy/paste ready apt-get install.  We should either provide the same or at least a blurb saying this can be obtained there.

**Comment by mellinoe** [comment]
See: https://github.com/dotnet/corefx/pull/8109

**Comment by mellinoe** [comment]
@MattGal How does the document look now?

**Comment by Petermarcu** [comment]
Is it possible to also write down the concrete list that needs to be installed to run the output of a build? Many of the things listed are only build time dependencies and it would be good to be clear about what we require at runtime as well.

**Comment by Petermarcu** [comment]
Also an explanation of "Why" for each of our dependencies would be helpful :)

For example, something like this with a column for which are required at runtime...

clang-3.5 \ compiler
libstdc++6 \ runtime
liblldb-3.6 \ Debugging support
libgcc1 \ compiler
libc6 \ Because
libcurl3 \ Networking/Sockets 
libicu52 \ Globalization support 
liblttng-ust0 \ Diagnostic tracing (This is optional)
libssl1.0.0 \ Crypto and SSL
libtinfo5 \ terminal handling (Not sure if this is real)
libunwind8 \ Stack traces and exception handling
libuuid1 \ Guid generation
zlib1g \ Compression
gettext \ Resource loading
libcrypto \ cryptographic algorithms

**Comment by MattGal** [comment]
@mellinoe It's better, but I'd prefer it be more like the CoreCLR repo where you get the copy/paste-able command first before the list of dependencies.  What they're for is a nice addition too.

**Comment by mellinoe** [comment]
Hmm, on the one hand, the copy-paste list is useful for lots of people, but it's very specific to Ubuntu. Folks using other distros would probably prefer to see the list of dependencies first so they can figure out how to install them for their particular distro. Including the apt-get command specifically is useful because Ubuntu is the most common distro that folks on the team are using, and external folks as well, it seems.

Could you link the doc in CoreCLR that you are looking at? [This one](https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md) looks pretty much like what we have here now.

Agreed that a description of "why" for each dependency would be useful.

**Comment by vindicatorr** [comment]
+1 on seeing the deps first (archlinux newb). I like to know what's going on before I do something.
