### ISSUE TITLE
[question] Is it possible to use the locally-built corefx binaries in a console app?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#8145]
Just a question, is it possible to use the corefx binaries you built locally with a console app? This is what I've tried so far:

- `project.json` file (tagged with latest versions of the packages)

```json
{
    "frameworks": {
        "dnx451": {},
        "dnxcore50": {
            "dependencies": {
                "System.IO.FileSystem": "4.0.1-rc3-24027-0",
                "System.Runtime": "4.1.0-rc3-24027-0"
            }
        }
    }
}
```

- Batch build script

```cmd
@echo off
setlocal EnableDelayedExpansion

pushd "%~dp0"

set "CoreFxRoot=%USERPROFILE%\Code\git\corefx"
set "PackageRoot=%CoreFxRoot%\bin\packages\Release"

:: Restore the packages
call dnu restore --source "%PackageRoot%"

:: Run the app
dnx --framework dnxcore50 CoreFxTesting2

popd
```

The package restore seems to be working, but it doesn't look like the packages in the `project.json` are actually being used- I can simply exclude all of the dependencies in the `project.json` altogether, for example, and it'll still compile/run. When I run `dnu build` from the command line though, like so

```cmd
dnu build --framework dnxcore50
```

it doesn't compile successfully, instead saying that the packages don't support `dnxcore50` and giving off a bunch of compilation errors. Is it possible to use the corefx binaries from a console app, then?

**Comment by svick** [comment]
I have no idea if it's going to help, but have you tried using `dotnet` instead of `dnu` and `dnx`?

**Comment by mellinoe** [comment]
This is possible, but the `dotnet` tool (which you should switch to for the latest bits, as @svick mentioned) does not cater to this workflow. In order to get it working there, I think you would need to do one of the following:

* Build the nuget packages from corefx, put those into a folder somewhere, and set it as a package source (in NuGet.Config) for your other project. Then, list the versions you locally built in your project.json.
or
* "Publish" your project as a standalone project, and replace the published binaries with your own binaries built from here. Disclaimer: I don't actually know how to publish a "fully standalone" project using `dotnet` anymore, there is some special syntax you will probably need. Best to ask in https://github.com/dotnet/cli if you go this route.

You could also set up an MSBuild project, which would give you more flexibility but would be more difficult to get started with.

**Comment by jamesqo** [comment]
@mellinoe Thanks for helping 😄 I was finally able to get it working with your first approach, via adding a `NuGet.config` file to the app's root and switching to `dotnet` and `netstandard`. Another question, though: I was originally trying to do this for the purpose of testing some perf changes I made to mscorlib over in [coreclr](https://github.com/dotnet/coreclr/pull/4540). I followed the instructions in [Testing with CoreFX](https://github.com/dotnet/coreclr/blob/master/Documentation/building/testing-with-corefx.md) and made sure to pass in the `BUILDTOOLS_OVERRIDE_RUNTIME` property to use my copy of mscorlib (and indeed decompiling a random copy of it in the `bin/tests` directory, it looks like my changes made it in).

However, I suspect that my copy of mscorlib isn't being used, e.g. when I run the perf tests from the .NET Core app, they're much slower than if I create a traditional console application from VS, add in `NoStdLib` to the .csproj + manually reference mscorlib, and run them from there.

Would you no if/how at runtime, to get `dotnet run` to use a different mscorlib (the one I built locally in coreclr) instead of the one that's typically referenced? In other words, is it possible to override the mscorlib that's used for running a .NET Core app?

Thanks.

**Comment by mellinoe** [comment]
@ericstj , @piotrpMSFT 
Is there a way to do this with the CLI?

**Comment by ericstj** [comment]
I imagine you'd be able to do this if you were building a standalone app in the CLI and you pointed to packages you produced locally.

**Comment by jamesqo** [comment]
Everything is going fine now; thanks everyone. I ended up writing a script to simply overwrite the published mscorlib with my copy. :)
