### ISSUE TITLE
System.IO.Compression: Create ExtractToDirectory overload that accepts 'overwrite' boolean

### ISSUE THREAD

**Issue by DanAtkinson** [dotnet/corefx#8146]
Currently `ExtractToDirectory` is only useful if the target directory is virginal (eg clean or contains files which are not in the zip being extracted). If you're performing an extraction over an existing directory however, then the functionality is extremely limited because you will encounter the following example exception:

> Exception calling "ExtractToDirectory" with "2" argument(s): "The file 'D:\foo\bar.txt' already exists."

I would like to ask the developers to consider writing a new overload for the `ExtractToDirectory` method that includes an 'overwrite existing files' parameter.

Many thanks.

**Comment by joshfree** [comment]
great suggestion @DanAtkinson :)

**Comment by OperatorOverload** [comment]
I've taken a first pass at this by adding an additional signature to allow the user to specify that an overwrite should be allowed.  In some discussions on Gitter, somebody else suggested maybe it should be a new signature to the effect of "ExtractToDirectoryAndOverwrite".. I'm happy to retool using that approach if it's preferred.

Test cases also included, commit is here operatoroverload@e1ac49268f8cc894225fb743b5c7ed245b9f7985

**Comment by DanAtkinson** [comment]
Hi @operatoroverload, Thanks for doing that so quickly.

I've got to say that I hate the idea of calling it `ExtractToDirectoryAndOverwrite`. It seems to be against the general principles of the framework of using overloads rather than creating new methods for functionality that makes sense as being part of the base method from the beginning. Similarly, there is only one `CreateFromDirectory` method with multiple overloads, rather than different methods, such as `CreateFromDirectoryAtCompressionLevel`. 

I'd like to understand the reasoning for the desire to split the functionality into a completely new method however.

Many thanks, Dan

**Comment by OperatorOverload** [comment]
The reason given in Gitter was that "Personally, I dislike Boolean parameters, especially because Booleans in general represent derived information".  

It was clearly just a personal preference, but just bringing up the discussion since agreement on the API seemed to be the next step and that seemed like another reasonable suggestion.  I prefer the current implementation (hence why I implemented that way first).

**Comment by DanAtkinson** [comment]
Thanks. I understand their point but disagree with the reasoning given that boolean overloads are par for the course and are standard in many languages. Similarly, one could also argue the same about enums like [`CompressionLevel`](https://msdn.microsoft.com/en-us/library/system.io.compression.compressionlevel(v=vs.110).aspx).

Anyway, thank you for implementing it. I haven't looked at the source yet as I'm currently ill but I'll take some time next week.

Thanks, Dan

**Comment by ianhays** [comment]
:+1: for the overload, though I vaguely recall a discussion recently where we decided it's better to have a separate function than to have an optional/default parameter.

I agree that a new function name is unnecessary.

**Comment by OperatorOverload** [comment]
Happy to rework to a separate function if that's preferable, would be easy to do, just trying to learn the preferred style approach

**Comment by ianhays** [comment]
# Problem

via @DanAtkinson:

Currently ExtractToDirectory is only useful if the target directory is virginal (eg clean or contains files which are not in the zip being extracted). If you're performing an extraction over an existing directory however, then the functionality is extremely limited because you will encounter the following example exception:

Exception calling "ExtractToDirectory" with "2" argument(s): "The file 'D:\foo\bar.txt' already exists."
I would like to ask the developers to consider writing a new overload for the ExtractToDirectory method that includes an 'overwrite existing files' parameter.

Many thanks.

# Proposed API

<pre>
namespace System.IO.Compression
{
    public static partial class ZipFile
    {
        public static void CreateFromDirectory(string sourceDirectoryName, string destinationArchiveFileName) { }
        public static void CreateFromDirectory(string sourceDirectoryName, string destinationArchiveFileName, System.IO.Compression.CompressionLevel compressionLevel, bool includeBaseDirectory) { }
        public static void CreateFromDirectory(string sourceDirectoryName, string destinationArchiveFileName, System.IO.Compression.CompressionLevel compressionLevel, bool includeBaseDirectory, System.Text.Encoding entryNameEncoding) { }
        public static void ExtractToDirectory(string sourceArchiveFileName, string destinationDirectoryName) { }
        <b><i>public static void ExtractToDirectory(string sourceArchiveFileName, string destinationDirectoryName, bool overwrite) { }</i></b>
        public static void ExtractToDirectory(string sourceArchiveFileName, string destinationDirectoryName, System.Text.Encoding entryNameEncoding) { }
        <b><i>public static void ExtractToDirectory(string sourceArchiveFileName, string destinationDirectoryName, System.Text.Encoding entryNameEncoding, bool overwrite) { }</i></b>
        public static System.IO.Compression.ZipArchive Open(string archiveFileName, System.IO.Compression.ZipArchiveMode mode) { return default(System.IO.Compression.ZipArchive); }
        public static System.IO.Compression.ZipArchive Open(string archiveFileName, System.IO.Compression.ZipArchiveMode mode, System.Text.Encoding entryNameEncoding) { return default(System.IO.Compression.ZipArchive); }
        public static System.IO.Compression.ZipArchive OpenRead(string archiveFileName) { return default(System.IO.Compression.ZipArchive); }
    }
    [System.ComponentModel.EditorBrowsableAttribute((System.ComponentModel.EditorBrowsableState)(1))]
    public static partial class ZipFileExtensions
    {
        public static System.IO.Compression.ZipArchiveEntry CreateEntryFromFile(this System.IO.Compression.ZipArchive destination, string sourceFileName, string entryName) { return default(System.IO.Compression.ZipArchiveEntry); }
        public static System.IO.Compression.ZipArchiveEntry CreateEntryFromFile(this System.IO.Compression.ZipArchive destination, string sourceFileName, string entryName, System.IO.Compression.CompressionLevel compressionLevel) { return default(System.IO.Compression.ZipArchiveEntry); }
        public static void ExtractToDirectory(this System.IO.Compression.ZipArchive source, string destinationDirectoryName) { }
        <b><i><font color="red">public static void ExtractToDirectory(this System.IO.Compression.ZipArchive source, string destinationDirectoryName, bool overwrite) { }</i></b>
        public static void ExtractToFile(this System.IO.Compression.ZipArchiveEntry source, string destinationFileName) { }
        public static void ExtractToFile(this System.IO.Compression.ZipArchiveEntry source, string destinationFileName, bool overwrite) { }
    }
}
</pre>

# Options
- Rather than overload `ExtractToDirectory`, we can create new functions ```ExtractToDirectoryAndOverWrite``` and avoid the need for a boolean parameter
- We could make the overload parameter optional and have the default value be ```false```. This would avoid the need for new functions but would alter the signature of the existing functions.

# Implementation
@OperatorOverload posted a draft implementation at OperatorOverload@e1ac492.

@terrajobst @ericstj @stephentoub

**Comment by OperatorOverload** [comment]
Here's the version that matches the proposed implementation which maintains the existing function signature and adds a new function with the additional boolean parameter

OperatorOverload@9e28192ea4ed9839c240f5cf0880406d5df4e41a

**Comment by terrajobst** [comment]
Looks good. We should probably just rename the parameter to make it clear that we don't do the equivalent of deleting the destination directory before extracting:

```diff
 namespace System.IO.Compression
 {
     public static partial class ZipFile
     {
         public static void CreateFromDirectory(string sourceDirectoryName, string destinationArchiveFileName) { }
         public static void CreateFromDirectory(string sourceDirectoryName, string destinationArchiveFileName, System.IO.Compression.CompressionLevel compressionLevel, bool includeBaseDirectory) { }
         public static void CreateFromDirectory(string sourceDirectoryName, string destinationArchiveFileName, System.IO.Compression.CompressionLevel compressionLevel, bool includeBaseDirectory, System.Text.Encoding entryNameEncoding) { }
         public static void ExtractToDirectory(string sourceArchiveFileName, string destinationDirectoryName) { }
+        public static void ExtractToDirectory(string sourceArchiveFileName, string destinationDirectoryName, bool overwriteFiles) { }
         public static void ExtractToDirectory(string sourceArchiveFileName, string destinationDirectoryName, System.Text.Encoding entryNameEncoding) { }
+        public static void ExtractToDirectory(string sourceArchiveFileName, string destinationDirectoryName, System.Text.Encoding entryNameEncoding, bool overwriteFiles) { }
         public static System.IO.Compression.ZipArchive Open(string archiveFileName, System.IO.Compression.ZipArchiveMode mode) { return default(System.IO.Compression.ZipArchive); }
         public static System.IO.Compression.ZipArchive Open(string archiveFileName, System.IO.Compression.ZipArchiveMode mode, System.Text.Encoding entryNameEncoding) { return default(System.IO.Compression.ZipArchive); }
         public static System.IO.Compression.ZipArchive OpenRead(string archiveFileName) { return default(System.IO.Compression.ZipArchive); }
     }
     [System.ComponentModel.EditorBrowsableAttribute((System.ComponentModel.EditorBrowsableState)(1))]
     public static partial class ZipFileExtensions
     {
         public static System.IO.Compression.ZipArchiveEntry CreateEntryFromFile(this System.IO.Compression.ZipArchive destination, string sourceFileName, string entryName) { return default(System.IO.Compression.ZipArchiveEntry); }
         public static System.IO.Compression.ZipArchiveEntry CreateEntryFromFile(this System.IO.Compression.ZipArchive destination, string sourceFileName, string entryName, System.IO.Compression.CompressionLevel compressionLevel) { return default(System.IO.Compression.ZipArchiveEntry); }
         public static void ExtractToDirectory(this System.IO.Compression.ZipArchive source, string destinationDirectoryName) { }
+        public static void ExtractToDirectory(this System.IO.Compression.ZipArchive source, string destinationDirectoryName, bool overwriteFiles) { }
         public static void ExtractToFile(this System.IO.Compression.ZipArchiveEntry source, string destinationFileName) { }
         public static void ExtractToFile(this System.IO.Compression.ZipArchiveEntry source, string destinationFileName, bool overwrite) { }
     }
 }
 ```

**Comment by OperatorOverload** [comment]
Hi @danmosemsft.. I actually have the "fixed" version of this ready, but am having similar issues with the test build so hadn't PR'ed it until I could figure out how to fix.  In reviewing your changes and comparing with mine though, I'm seeing the "#if netcoreapp11" directive, so I'm curious how you knew to do that.  Is there documentation that indicates that?  I haven't seen it in the contributing guides, so just wondering if I missed something that I should be reading to make sure I can get these "right" in the future.

Thanks

**Comment by danmosemsft** [comment]
@OperatorOverload I should have checked with you first, but I figured it was just a matter of rebasing your change... 

The `#if netcoreapp11` is necessary because the reference assembly for an older version of .NET Core is built from the same ref file. Actually I'm not sure this is stated correctly -- @weshaggard can you clarify? Why do we still do this, and is this getting renamed to `netcoreapp20` now?

The contribution guide ought to be updated - a bunch of this is relatively new.

**Comment by OperatorOverload** [comment]
@danmosemsft Ok, that makes sense.. I'm not sure the exact state of where yours builds too, but I'll share where I'm at (should have done months ago) and maybe we can get there together.

My branch that looks very similar to yours is here: https://github.com/OperatorOverload/corefx/tree/compression_projchanges

However, the issue I've got (and have had) is that I'm getting ApiCompat errors for the functions that are added when trying to build the tests (specifically on the ones that are in the bin\obj\AnyOS.AnyCPU.Debug\System.IO.Compression.ZipFile\net46 directory).  If I pause the process doing the build right after the facade copy and before ApiCompat starts and manually drop the DLL from one directory up (one up from net46) into the PreGenFacades directory, the build will finish and then I can run tests (all 39 pass).  The error is various versions of 
`Member 'System.IO.Compression.ZipFile.ExtractToDirectory(System.String, System.String, System.Text.Encoding, System.Boolean)' does not exist in the implementation but it does exist in the contract.`

From that, what I'm concluding is that the reference to net46 means that the updated ref is making .NET 4.6 fail the contract.  I was hoping that adding your "#if netcoreapp11" would fix it, but it doesn't seem to since it's grabbing the same ref contract assembly as everything else.  I didn't have the piece previously from several months ago, and it makes sense, but I don't know how to make it take effect.

The other option here is drop net46 from the build config and just build for netcoreapp/netframework1.7, but I don't know if that's a viable approach and causes problems across the project.  

I'm sure there's also a way to handle this with MSBuild, but I'm definitely no MSBuild expert.. you may also know how to address that since you're on the inside.

**Comment by danmosemsft** [comment]
I think what you're hitting is basically what I'm asking about.

I assume in your change you have essentially the same code and tests in which case we can just use this PR.

**Comment by OperatorOverload** [comment]
The only thing I saw on yours that needs changed is that the expected
assertion types are incorrect in the tests.  You included
UnauthorizedAccess and
I put in IOException and that passes when I trade out the DLLs directly.
