### ISSUE TITLE
Implement System.IO.FileSystem.DriveInfo for Mac

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#815]
The current implementation of System.IO.FileSystem.DriveInfo on Linux uses getmntent_r and friends for accessing file system descriptions, and to my knowledge those APIs don't exist on OS X.

**Comment by jasonwilliams200OK** [comment]
Based on chat with @milizhang, @janhenke, @ghuntley and @saper at https://gitter.im/dotnet/coreclr, for OSX we can specialize it using:

```c++
<CoreFoundation/CoreFoundation.h>
<DiskArbitration/DADisk.h>
<DiskArbitration/DADissenter.h>
<DiskArbitration/DASession.h>
```

https://developer.apple.com/library/mac/documentation/DiskArbitration/Reference/DiskArbitration_header_reference/index.html (since Disk Arbitration is a framework, `-framework DiskArbitration` linker switch would be required: http://stackoverflow.com/a/29159116)

OR we can use `#include <sys/statvfs.h>` for all Unices to extend the support to FreeBSD and make Linux leverage the same implementation, as statvfs is POSIX standard. Not sure if statvfs will provide all the required functionality. If there is something missing from statvfs, we can create OS-specific partials for those methods.

**Comment by stephentoub** [comment]
@sokket actually already has an implementation for OSX, which he'll be putting up as a PR soon I believe.  He can speak more to the APIs he's used.

**Comment by sokket** [comment]
I have an implementation that should work on OS X and FreeBSD (double checking on FreeBSD now). It uses getmntinfo and statfs to get info on each mount point that the OS knows about. I'll be putting out a PR with the code this week

**Comment by ghuntley** [comment]
Excellent news @sokket. I've created you an account on the machine the port-team uses for development, it's european based but it's always on and has heaps of memory and processing power. 

    ssh sokket@freebsd-frankfurt.zbsd.org

Password authentication is disabled, use [one of your keys](https://api.github.com/users/sokket/keys).
