### ISSUE TITLE
System.Numerics.Vectors contains _._ in a non-empty ref folder

### ISSUE THREAD

**Issue by emgarten** [dotnet/corefx#8189]
System.Numerics.Vectors 4.1.1-rc2-24018 contains ``_._`` in a folder that also contains dlls. 

From ``ref/net46``:
![image](https://cloud.githubusercontent.com/assets/6381138/14932324/32c4319a-0e29-11e6-886d-604d93446be2.png)

Normally ``_._`` is added only to allow an empty folder in nupkgs (OPC does not allow completely empty folders)

Having the extra placeholder here causes problems: https://github.com/aspnet/KestrelHttpServer/issues/773

**Comment by nil4** [comment]
@joshfree @chcosta please consider fixing this for RC2, as it currently blocks ASP.NET core (Kestrel) apps from running on .NET 4.6. Due to the packaging bug, the `System.Numerics.Vectors.dll` file is not copied to the output folder on build. Please see aspnet/KestrelHttpServer#773 for the full details. /cc @davidfowl @muratg

**Comment by muratg** [comment]
cc @danroth27

**Comment by joshfree** [comment]
starting an email thread with the usual suspects

**Comment by nil4** [comment]
@joshfree still seeing this with 4.1.1-rc2-24027

**Comment by ericstj** [comment]
Issue was moved to https://github.com/dotnet/cli/issues/2824.
