### ISSUE TITLE
Can we make EventCounter work in NetStandard 1.3?

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#8223]
Currently EventCounter is only available in NetStandard 1.5.  This makes it unavailable to many (most?) CoreFx implementation assemblies.  We'd like to use EventCounter in System.Net.Sockets, but it must remain on NetStandard 1.3 (see #7833).  

We should consider making EventCounter available on 1.3, if possible.

**Comment by joshfree** [comment]
@vancem is this something that you're actually working on for RTM?

**Comment by vancem** [comment]
I am looking at this, because I do want EventCounters to be used where the are appropriate, and there is no reason they can't work on 1.3.   I will look at it this week in a time-boxed fashion and either resolve or postpone the issue.

**Comment by vancem** [comment]
After some research, I found out that there IS a reason why EventCounters can't work on NetStandard 1.3.   NetStanadard1.3 corresponds to V4.6 and the EventCounter implementation needed a change so that it could 'hook' into EventSource properly.   This change went in V4.6.2 (that is NetStandard 1.5), so that is required.   

It is theoretically possible to make a dummy EventCounter for NetStandard 1.3 that used reflection to 'light up' if it was running on an appropriately new framework, but that is non-trivial work and it not clear the value is there.  

Ideally the desire to run on V4.6 will drop even after say 1/2 year and simply requiring 1.5 is not a big deal.   This is what we hope will happen.

So We are not going to do anything at this time.
