### ISSUE TITLE
HttpClient does not support IPv6 with scope ID on Mac or Linux

### ISSUE THREAD

**Issue by mikeharder** [dotnet/corefx#8235]
**Repro Steps**
1. Start an HTTP server on an IPv6 address with a scope ID.  An example is the link-local address provided by running `ifconfig`.
2. Run `curl` to verify the server is working.
2a. On Mac, I needed to wrap the IPv6 address with brackets, and escape the `%` as `%25`.  For example: `curl http://[fe80::blah%25en0]:1234/`.
2b. On Linux, I needed to *not* wrap with brackets, and *not* escape the `%`.  For example: `curl http://fe80::blah%eth0:1234/`.
3. Call `new HttpClient().GetAsync()` using the same URL you passed to curl.

**Expected**
HttpClient works the same as curl itself.

**Actual**
HttpClient fails with an error like `System.Net.Http.CurlException: Couldn't connect to server` or `System.UriFormatException: Invalid URI`.

**Notes**
I tested many combinations of with/without brackets and with/without `%` encoded as `%25`, but none of them worked.

HttpClient on Windows does work correctly with IPv6 scope ID (tested with brackets and without encoding `%`).

Documentation for IPv6 scope ID support in Windows: https://msdn.microsoft.com/en-us/library/windows/desktop/aa385325(v=vs.85).aspx

**Curl Versions**
Mac
```
curl 7.37.1 (x86_64-apple-darwin14.0) libcurl/7.37.1 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IPv6 Largefile NTLM NTLM_WB SSL libz
```

Linux
```
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by stephentoub** [comment]
Thanks, Mike. I've investigated and know what and where the problem is, just determining what the right fix is.

**Comment by mikeharder** [comment]
Great.  I'm happy to test the PR on my Mac and Linux machines, if you can tell me the easiest way to build the affected binaries and reference them from my project.

**Comment by stephentoub** [comment]
Thanks, @mikeharder. I put up a fix at https://github.com/dotnet/corefx/pull/8249 which should hopefully address your problem (it fixes my local repro, e.g. I was able to use a url with HttpClient like http://[fe80::123:1234:1234:1234%eth0]:12345 successfully).  If you can try it out locally, that'd be great... you can build just this component by cd'ing into corefx/src/System.Net.Http/src and doing ```msbuild /t:rebuild /p:OSGroup=Linux /v:m```, and then overwriting your System.Net.Http.dll locally with the one produced... it'll need to be a relatively recent rc3 build to work, otherwise you'll likely get errors about some exports from System.Net.Http.Native.so/dylib not being found.

**Comment by mikeharder** [comment]
@stephentoub: How do I get a recent RC3 build?  I am currently using the latest RC2 build from https://github.com/dotnet/cli.
