### ISSUE TITLE
Incorporating SSH client lib in corefx? 

### ISSUE THREAD

**Issue by xied75** [dotnet/corefx#8237]
Given .Net is cross platform now, and in the *nix world SSH (server and client) is used everywhere, should we add basic SSH functionalities into corefx?

For managed implementation we can reference:
https://github.com/sshnet/SSH.NET

For native maybe we can borrow something from PowerShell team?
https://github.com/PowerShell/Win32-OpenSSH

Thoughts?

**Comment by davidsh** [comment]
cc: @CIPop @himadrisarkar

**Comment by CIPop** [comment]
/cc @joshfree @terrajobst 

@xied75, I like the idea of having a .Net library that exposes SSH client/server/SFTP. 
I don't think that CoreFX would be a good fit for such a library given that it's not necessarily a generic protocol. Why not have it as a separate project that gets downloaded from NuGet instead? 

Have you considered porting any of the following to CoreFX :
https://sshnet.codeplex.com/
https://sourceforge.net/projects/sharpssh/

**Comment by xied75** [comment]
@CIPop It might be arguable to include this inside corefx or outside, but according to [wikipedia](https://en.wikipedia.org/wiki/Secure_Shell):

> An SSH client program is typically used for establishing connections to an SSH daemon accepting remote connections. Both are commonly present on most modern operating systems, including Mac OS X, most distributions of GNU/Linux, OpenBSD, FreeBSD, NetBSD, Solaris and OpenVMS. Notably, Windows is one of the few modern desktop/server OSs that does not include SSH by default.

So to say it is not a generic protocol is very Microsoft Style. (Apparently corefx does include SSL though).

And this https://sshnet.codeplex.com/ is now https://github.com/sshnet/SSH.NET, they moved house recently.

Sharpssh is a port from Java JSch, I have very bad impression on java ports, lots of java idioms that will drive csharpers mad.

**Comment by CIPop** [comment]
@xied75 Thanks for the updated links!

I completely agree that SSH is widespread and a popular protocol. 
My argument was that SSH ("Secure Shell") is very specific in what it does: it allows remote command execution. In Windows, the equivalent to SSH would be WinRM. I'm comparing SSH with other protocols that the stack is implementing which are more generic in their applications: SSL/Kerberos for security, Sockets/HTTP.

SCP/SFTP would probably make a better case although we're not supporting other file transfer protocols such as FTP or FTPS in the current CoreFX. We're also not supporting as part of the framework other kinds of advanced file transfer APIs such as BITS or BackgroundTransfer.

I think that NuGet solves the discoverability problem and, since project.json should work with things that are outside of the CoreFX repository, making something part of the CoreFX would not change how end-users reference and use it.

**Comment by davidsh** [comment]
We think this is a useful component in general but it might be better served as a separate project/library on NuGet.

**Comment by grahamehorner** [comment]
@davidsh I would agree, as this could then be used in any number of use cases including SFTP connection via Azure Functions, Data Factory, and others including IoT devices
