### ISSUE TITLE
Use latest rc2 corefx

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#8260]
I'd like to use some features which are on the rc2 branch but which are not yet on my machine.
Is it possible to configure project.json+NuGet.conf to use the 'latest' rc2 build?

**Comment by svick** [comment]
I think what you need is:

1. Have [the dotnet-core MyGet feed](https://dotnet.myget.org/gallery/dotnet-core) configured in NuGet.Config either locally or globally. `dotnet new` used to do this automatically, but [doesn't anymore](https://github.com/dotnet/cli/pull/2319).
2. Reference the latest version of the packages from your `project.json`. Right now, for `Microsoft.NETCore.App`, that's `1.0.0-rc2-3002659`. You can also set it so that `dotnet restore` always gives you the latest version by using `*`: `1.0.0-rc2-*`.

**Comment by tmds** [comment]
@svick works fine! thanks
