### ISSUE TITLE
IPAddress.ToString behavior difference: IPv6-mapped addresses format as regular IPv6 addresses

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#8360]
From 
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/823/testReport/junit/System.PrivateUri.Tests/UriIpHostTest/UriIPv6Host_EmbeddedIPv4_Success/

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/823/

```
MESSAGE:
Assert.Equal() Failure
↓ (pos 10)
Expected: [::ffff:0:c0a8:1]
Actual: [::ffff:0:192.168.0.1]
 ↑ (pos 10)
+++++++++++++++++++
STACK TRACE:
at System.PrivateUri.Tests.UriIpHostTest.ParseIPv6Address(String ipv6String) at System.PrivateUri.Tests.UriIpHostTest.UriIPv6Host_EmbeddedIPv4_Success()
```

**Comment by ericeil** [comment]
The problem is in `IPAddress.ToString`.  On Windows, we format IPv6-mapped IPv4 addresses specially; on UNIX we treat them the same as any other IPv6 address.

**Comment by ericeil** [comment]
The issue is that this code produces different results on Windows vs. *nix:

```csharp
Console.WriteLine(IPAddress.Parse("::ffff:0:192.168.0.1");
```

On Windows, this prints:

```
::ffff:0:192.168.0.1
```

On *nix, we get:

```
::ffff:0:c0a8:1
```

The two are semantically equivalent; both are perfectly valid representations of the same IPv6 address.  So the only issue would be if someone relied on having this formatted exactly as Windows does.  I can't think of why that would be a real problem.  

@CIPop, @davidsh, do you have any thoughts on this?

**Comment by CIPop** [comment]
@ericeil I agree that this shouldn't be a big problem. I think it should be OK to document the difference in behavior for now.
