### ISSUE TITLE
IPAddress.TryParse behavior difference: dotted octal

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#8362]
In OSX _only_ there are 3 tests failing for the dotted octal IP format:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/867/

- [ ] UriIPv4Host_DottedOctalExtraLeadingZeros_Success

```
Assert.Equal() Failure\n ↓ (pos 0)\nExpected: 235.73.31.33\nActual: 157.59.25.27\n ↑ (pos 0)
+++++++++++++++++++
STACK TRACE:
at System.PrivateUri.Tests.UriIpHostTest.ParseIPv4Address(String ipv4String) at System.PrivateUri.Tests.UriIpHostTest.UriIPv4Host_DottedOctalExtraLeadingZeros_Success()
```

- [ ] UriIPv4Host_PartialOctal_Success 

```
MESSAGE:
Assert.Equal() Failure\n ↓ (pos 10)\nExpected: 157.59.25.33\nActual: 157.59.25.27\n ↑ (pos 10)
+++++++++++++++++++
STACK TRACE:
at System.PrivateUri.Tests.UriIpHostTest.ParseIPv4Address(String ipv4String) at System.PrivateUri.Tests.UriIpHostTest.UriIPv4Host_PartialOctal_Success()
```

- [ ] UriIPv4Host_DottedOctal_Success 

```
MESSAGE:
Assert.Equal() Failure\n ↓ (pos 0)\nExpected: 235.73.31.33\nActual: 157.59.25.27\n ↑ (pos 0)
+++++++++++++++++++
STACK TRACE:
at System.PrivateUri.Tests.UriIpHostTest.ParseIPv4Address(String ipv4String) at System.PrivateUri.Tests.UriIpHostTest.UriIPv4Host_DottedOctal_Success()
```

**Comment by ericeil** [comment]
It looks like what's actually inconsistent is `IPAddress.TryParse`.  On Windows, both Uri and IPAddress parse these strings as octal.  For example, if I run this program:

```csharp
        static void Main(string[] args)
        {
            var uri = new Uri("http://000235.000073.0000031.00000033");
            Console.WriteLine(uri.Host);

            IPAddress ip;
            IPAddress.TryParse("000235.000073.0000031.00000033", out ip);
            Console.WriteLine(ip);
        }
```
...The output is:

```
157.59.25.27
157.59.25.27
```

On OSX, the `Uri` behavior is consistent with what I see on Windows, but `IPAddress.TryParse` seems to be treating these as decimal, not octal, resulting in the erroneous address "235.73.31.33".

**Comment by ericeil** [comment]
a...hence the test failure, since it's comparing the Uri result with the IPAddress result.

**Comment by ericeil** [comment]
On OSX and Linux, `IPAddress.Parse` uses `getaddrinfo` to parse the string.  This is spec'd to only work for decimal, but seems to do more than that on both platforms.  On Linux, I guess it works well for both hex and octal.  On OSX, hex seems to work, but octal only *sometimes* works.  After some experimentation, I think what's going on is that `getaddrinfo` on OSX tries to parse the address as decimal *first*, and only if that fails does it try to parse it as octal.  So an address like "010.010.010.010" will parse as "10.10.10.10," but "0300.0300.0300.0300," since it's not a valid address in *decimal*, will correctly parse as "192.192.192.192."

There is a better API we can use: `inet_aton`.  This appears to work in all of the positive cases in the Uri tests.  But it appears to be much more permissive in what it will accept; many addresses fail to parse on Windows, but succeed when passed to `inet_aton`.

Whether that matters depends on how common it is to rely on IPAddress.Parse to validate input.  I'd guess this is actually reasonably common.

**Comment by ericeil** [comment]
Likely what we'll need to do, to get parity with Windows here, is implement our own parser in IPAddress.

**Comment by stephentoub** [comment]
> Likely what we'll need to do, to get parity with Windows here, is implement our own parser in IPAddress.

Ouch, but it makes sense.

**Comment by CIPop** [comment]
> Likely what we'll need to do, to get parity with Windows here, is implement our own parser in IPAddress.

Before doing so we should understand if there is any usage on OSX and octal IPv4 addresses.
Based on lessons learned with System.Uri and custom parsers, I recommend just documenting the behavior by having a few tests, specific for OSX, that validate the above description (i.e. octal works for 0300 but not for 0255).

**Comment by ericeil** [comment]
I agree that if the only issue was a failure to parse octal, I'd want to see how much usage that gets before making big changes here.  But I think the bigger issue is that the native parsers on Unix are overly permissive of "bad" address strings; failure to fail in these cases could lead to all sorts of very bad behavior in code that relies on the validation we currently provide on Windows.
 
I also agree that writing our own parser should not be taken lightly.  FWIW, I don't plan to start from scratch, but rather to adapt the parser we already use in System.Uri.  @CIPop, do you know of any issues I'm likely to run into with that?

**Comment by ericeil** [comment]
#8361 covers the difference in string validation behavior.

**Comment by ericeil** [comment]
Since the validation issue is covered elsewhere, I'm thinking we can postpone the octal string parsing issue, until we have some evidence that octal strings get used in the real world.
