### ISSUE TITLE
Alternative for Assembly.Location / bring back Assembly.Location

### ISSUE THREAD

**Issue by cdmihai** [dotnet/corefx#8398]
Getting the location of a loaded assembly is a core feature of the Assembly class. Now that the Assembly.Location property is only available in .net standard 1.5, how can code targeting lower platform versions retrieve the path where an assembly got loaded from?

Alternatively, can Assembly.Location be brought back? According to msdn it was there since 1.1: https://msdn.microsoft.com/en-us/library/system.reflection.assembly.location(v=vs.110).aspx

**Comment by ericstj** [comment]
/cc @weshaggard it was only added to the reflection contract in the 4.1.0.0 surface area of System.Reflection.  Currently that surface area is only available starting NETStandard1.5 because UWP doesn't support it.

That means that desktop suffers because it could be supported by older versions of desktop but UWP holds it back.

@weshaggard do you think we could come up with some way to support 4.1.0.0 surface area of refelction in UWP without breaking shared library?

**Comment by cdmihai** [comment]
If UWP is the only one not supporting this, doesn't it make sense to downgrade the .netstandard version that UWP supports (.netstandard1.0, or create some version in the [0,1) range to signify seriously deprecated platforms), rather than breaking everyone else? 

Then, UWP can upgrade to newer .netstandard versions at its own pace, rather than bringing all the other platforms down.

**Comment by weshaggard** [comment]
There is no good way to bring the 4.1.0.0 surface area to UWP and we cannot just move UWP down as that will give an inaccurate representation of what it contains. The entire point of netstandardx.y is to support portable libraries on the different platforms and it was computed based on what the currently have. 

@cdmihai why can you not use netstandard1.5?

**Comment by cdmihai** [comment]
MSBuild is targetting .netstandard1.3 because tasks written against MSBuild's APIs need to run on both full framework (>= net46) and .net core.

**Comment by ericstj** [comment]
@cdmihai I think a better way to handle that will be to make a reference assembly that targets 1.3, your surface area doesn't have a 1.3 dependency.  Then you can make your netstandard implementation target ns1.5 but the desktop implementation is provided by the MSBuild assemblies in either the desktop framework / OOB msbuild.  /cc @dsplaisted

**Comment by weshaggard** [comment]
As @ericstj suggests if you want to do that you need to create a reference assembly different from your implementation or you need to build multiple times. Once for .NET Framework in net46 folder and once for .NET Core in netcoreapp1.0 folder. There isn't any other way to get access APIs we are wanting and the targets you want.

**Comment by rainersigwald** [comment]
@jaredpar You wanted this too--does this address your concerns?

**Comment by jaredpar** [comment]
@rainersigwald my main concern is the ability to have a netstandard 1.3 API assembly for MSBulid that can be used for both MSBuild Desktop and MSBuild Core.  That way a single Task implementation can be used in all of the places MSBuild will be run.  This is relevant to the tasks for C#, VB, F#, NuGet, code generation, etc ...  

If this solution allows for that then it will meet our scenario.  

IMHO: just reflect into `Assembly.Location`.  It's extremely unfortunate that teams keep having to dance around this API but at this point it doesn't look to change.  Rather than make your build extremely complex I would just add the few lines of reflection and move on.

**Comment by jnm2** [comment]
Just so I understand correctly: in order to use `Assembly.Location` in a class library which will be used by both full framework and .NET Core apps, I am forced to either:

 1. Multi target (I'm blocked on this because I can't project-reference a multi-target project from the full framework csproj)
 2. Run full framework at 4.6.2 which is only in preview stage (blocked on this because I can't install preview bits on customers' computers)
 3. Creating a reference assembly isn't an option here because I want to use a project reference between the class library and the full framework csproj. Correct me if I'm wrong?

Again, correct me if I'm wrong, but any class library containing `Assembly.Location` is blocked until either the csproj work is done or 4.6.2 has long term support?
