### ISSUE TITLE
SslStream/NegotiateStream should throw InvalidCredentialException when the authentication fails and cannot be retried

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#8414]
According to MSDN: https://msdn.microsoft.com/en-us/library/system.security.authentication.invalidcredentialexception(v=vs.110).aspx 

> The exception that is thrown when authentication fails for an authentication stream and cannot be retried.

At the moment SslStream is throwing only `AuthenticationException`.

**Comment by karelz** [comment]
Next step:
1. Verify Desktop behavior
2. Fix MSDN or CoreFX to match the behavior (might have compat question 1.1->2.0)

**Comment by schen381** [comment]
In SslStream’s MSDN (https://msdn.microsoft.com/en-us/library/system.net.security.sslstream(v=vs.110).aspx)

> “If the authentication fails, you receive a AuthenticationException, and the SslStream is no longer useable. You should close this object and remove all references to it so that it can be collected by the garbage collector.” 
 
So retry authentication is not possible for SSLStream, this is the first thing we need to notice.

Second, I have tested the behavior on .Net Desktop when authentication fails. It throws AuthenticationException, same as .Net Core does.

Therefore we need to fix the MSDN instead of the code.

**Comment by karelz** [comment]
@schen381 which docs do we have to update? Can you please suggest new wording, then we should pass it to docs team.
Thanks!

**Comment by schen381** [comment]
@karelz I will discuss with Cristian offline tomorrow and follow up here. Thanks!

**Comment by schen381** [comment]
@karelz We need to change the doc for InvalidCredentialException at https://docs.microsoft.com/en-us/dotnet/api/System.Security.Authentication.InvalidCredentialException?view=netframework-4.7, and the MSDN website will be phased out redirected to the new docs website. We need to change the Remark section and remove any occurrences of "SsslStream" from it, because InvalidCredentialException only applies for NegotiateStream.

cc: @davidsh @CIPop

**Comment by karelz** [comment]
@mairaw is the above information actionable for docs team?
Should we move the bug to docs repo now?

**Comment by karelz** [comment]
Thank you @schen381!

**Comment by mairaw** [comment]
Sure, we can change the remarks to remove any mentions of SslStream from it. I'll move this issue to our repo now.

**Comment by mairaw** [comment]
Issue moved to [dotnet/docs #1941](https://github.com/dotnet/docs/issues/1941) via [**ZenHub**](https://www.zenhub.com/)
