### ISSUE TITLE
Why ImmutableList throws ArgumentOutOfRange instead of IndexOutOfRange on insertion

### ISSUE THREAD

**Issue by xperiandri** [dotnet/corefx#8449]
Why `ImmutableList<T>` throws `ArgumentOutOfRangeException` instead of `IndexOutOfRangeException` when index out of allowed range is passed to `Insert` method?

**Comment by AArnott** [comment]
Thanks for raising this, @xperiandri. We do strive for our exceptions to make sense, and be consistent across the Framework.

`ImmutableList<T>` is designed to be quite similar to `List<T>`. In particular, `List<T>.Insert` also throws `ArgumentOutOfRangeException` in the equivalent circumstance:

```
> var l = new List<string>();
> l.Insert(2, "hi");
Index must be within the bounds of the List.
Parameter name: index
  + System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
  + List<T>.Insert(int, T)
```

Note that the exception message mentions "index", but the exception type is actually an `ArgumentOutOfRangeException`. 

So `ImmutableList<T>` matches this behavior, and is by design.

I believe the intent of `IndexOutOfRangeException` is to be thrown from *indexers*, specifically. Methods should throw `ArgumentOutOfRangeException`. I believe this is expressed in [the MSDN topic for the exception][1]

[1]: https://msdn.microsoft.com/en-us/library/system.indexoutofrangeexception(v=vs.110).aspx

**Comment by xperiandri** [comment]
Looks not so obvious but with that description have sense.
Thanks.
