### ISSUE TITLE
System.Net.InternalException should include more diagnostic info

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#8517]
We throw `System.Net.InternalException` as a kind of "soft assert" in the networking code; In DEBUG builds, this will stop the process immediately, while in RELEASE builds this is just an exception, albeit an unexpected one.  In DEBUG builds, because we crash immediately, we should be able to reconstruct the state that lead to the exception, in a debugger; but in RELEASE builds this information may be long gone before we get a chance to debug.

We should consider enhancing `InternalException` to carry some state info to aid in debugging.

**Comment by ericeil** [comment]
@CIPop, @davidsh, @stephentoub, how do you guys feel about [System.Net.InternalException](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Net/InternalException.cs)?  This seems to be there for things that should *never* happen, and have bad enough consequences if they *do* happen, just doing a `Debug.Fail` isn't enough - we want to fail in Release builds as well.  But in Release builds, we fail by throwing an exception, leaving the possibility that someone might catch it and continue.  This seems to me like asking for trouble; shouldn't we just FailFast in Release builds?

**Comment by CIPop** [comment]
> shouldn't we just FailFast in Release builds

The problem is app-compat: if any 3rd party application took a dependency on catching and continuing, that app will now fail.
That being said, I'm in favor of converting this to a FailFast after ensuring that there is no case where the failure could actually be transformed into an exception (SocketException or other external type).

**Comment by CIPop** [comment]
The work required here is to replace all instances of [System.Net.InternalException](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Net/InternalException.cs) with [Environment.FailFast](https://github.com/dotnet/corefx/blob/f9c54ab8d78e60ef6d5e0d0226ad45448725cc9e/src/System.Runtime.Extensions/src/System/Environment.cs#L112).

**Comment by davidsh** [comment]
PR #13134 changed this so that the constructor for InternalException() doesn't directly call Debug.Fail. But rather it now logs into the NetEventSource.Fail.  That in turn will still call Debug.Fail.

At this point, there is no need to change how System.Net.InternalException works. Over time, though, it would be good to migrate away from using this exception. But for now, this issue can be closed.
