### ISSUE TITLE
Proposal: Introduce System.Runtime.Loader as a Desktop contract

### ISSUE THREAD

**Issue by mjsabby** [dotnet/corefx#8526]
System.Runtime.Loader is the only difference between NET462 and NETCoreApp today, this means that code that is targeting both Desktop and NETCoreApp need to have different code paths.

Adding a simple emulator of the APIs on Desktop would suffice a lot of scenarios, certainly those that want to run on NETCoreApp.

Previous discussion: #8453

**Comment by mjsabby** [comment]
cc @gkhanna79

**Comment by karelz** [comment]
@gkhanna79 is it part of the netstandard2.0 plan?

**Comment by gkhanna79** [comment]
No, not for 1.2.0.

**Comment by AlexGhiondea** [comment]
@mjsabby, @gkhanna79 do we need a formal API proposal for this?

**Comment by mellinoe** [comment]
@AlexGhiondea The request is to add support for the existing contract to desktop, not to design any new API's, I think.

**Comment by karelz** [comment]
In that case we can close it -- @AlexGhiondea's tooling for 'netfx-port-consider' will pick it up for Desktop in our next sweep.
Feel free to reopen if I am wrong.

**Comment by gkhanna79** [comment]
CC @rahku who is going to look into this once he is back from vacation.

**Comment by jeremyVignelles** [comment]
Where can I follow the implementation status of this feature?

I came across this issue and #8965 because I have an issue using this assembly in a .Net full framework. Here is my use case:

I am implementing a plugin system that will load assemblies from a folder. I want the loading logic to be used in both my .Net full and .Net core projects. That's why I created a projet targetting .net standard and placed that loading logic inside.

First try : Created a WPF app, reference that library, call the code to load the plugins, run the app and crash : `System.IO.FileNotFoundException` on `System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a`. Indeed, the assembly does not show up in my references, even though the installation was sucessful.

Inside the packages directory, I have the `System.Runtime.Loader.4.3.0/lib/net462` folder, but only a empty `_._` file inside.

That would be great if that library was available for net462 too, because I can't call `Assembly.LoadFrom` inside my netstandard library. Or maybe do you have any workaround?

**Comment by jeremyVignelles** [comment]
One month and a half later, I totally forgot about this and tried to clean up my code by removing that weird "//TODO:" (I should have written a meaningful message back then). I faced the same issue and after some search, I went back here again.

Isn't there any workaround for the use case mentionned above?

**Comment by karelz** [comment]
The API surface does not seem to be part of .NET Standard, but Platform Extensions (whatever that is).
Given that it is not available on Desktop, I am a bit surprised the package has `_._` under net462 target -- that is basically forwarding it into the platform itself. @ericstj any idea?

IMO the only workaround is to cross-compile Desktop, using `LoadFrom` and friends on Desktop.

**Comment by ericstj** [comment]
> Given that it is not available on Desktop, I am a bit surprised the package has _._ under net462 target -- that is basically forwarding it into the platform itself. @ericstj any idea?

No, that's not forwarding to the platform.  It's preventing the more generic implementation from applying, explicitly making it [*not supported*](https://github.com/dotnet/corefx/blob/release/1.1.0/src/System.Runtime.Loader/pkg/System.Runtime.Loader.pkgproj#L11) on desktop.

**Comment by karelz** [comment]
Interesting, i didn't know we use the `_._` for that too. I heard it only in the context of forwarding. Thanks for explanation!

@jeremyVignelles I think, you will need to cross-compile for now as I suggested above.

**Comment by jeremyVignelles** [comment]
what do you mean by cross-compile? Something like using `#if NETSTANDARD_..`? Then, my library needs to be built twice and used for the correct target platform?

**Comment by mellinoe** [comment]
@jeremyVignelles Yes, that is correct.
