### ISSUE TITLE
FileSystemWatcher Test failure (OSX): WaitForChangedTests.CreatedDeleted_Success

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8547]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/1149/consoleText
```
System.IO.Tests.WaitForChangedTests.CreatedDeleted_Success(changeType: Deleted) [FAIL]
        Assert.Equal() Failure
        Expected: Deleted
        Actual:   0
        Stack Trace:
              at System.IO.Tests.WaitForChangedTests.CreatedDeleted_Success(WatcherChangeTypes changeType)
```

**Comment by ianhays** [comment]
Not just failing for OSX: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/1464/

```
MESSAGE:
Assert.Equal() Failure\r\nExpected: Deleted\r\nActual: 0
+++++++++++++++++++
STACK TRACE:
at System.IO.Tests.WaitForChangedTests.CreatedDeleted_Success(WatcherChangeTypes changeType) in D:\j\workspace\windows_nt_de---4526f5ff\src\System.IO.FileSystem.Watcher\tests\FileSystemWatcher.WaitForChanged.cs:line 150
```

**Comment by stephentoub** [comment]
> Not just failing for OSX

Yes.  Although it was failing basically every run for OSX (so we disabled it for OSX), whereas I think this is the first time we've seen it fail on Windows.

**Comment by ianhays** [comment]
It's failing on OSX because of the implementation. The Windows failure looks like an intermittent timing issue.

The issue on OSX is with the test using WriteAllText to create the file. The OSX watcher is treating WriteAllText as a coalesced Creation+Modification which gets filtered (by us) to just be a modification. Here are the EventFlags being passed to the event callback by the OSX Apis for the Created part of the failing test:

```
  kFSEventStreamEventFlagItemCreated, kFSEventStreamEventFlagItemModified, kFSEventStreamEventFlagItemIsFile
  kFSEventStreamEventFlagItemCreated, kFSEventStreamEventFlagItemModified, kFSEventStreamEventFlagItemIsFile
  kFSEventStreamEventFlagItemCreated, kFSEventStreamEventFlagItemModified, kFSEventStreamEventFlagItemIsFile
  kFSEventStreamEventFlagItemCreated, kFSEventStreamEventFlagItemModified, kFSEventStreamEventFlagItemIsFile
  kFSEventStreamEventFlagItemCreated, kFSEventStreamEventFlagItemModified, kFSEventStreamEventFlagItemIsFile
  kFSEventStreamEventFlagItemCreated, kFSEventStreamEventFlagItemModified, kFSEventStreamEventFlagItemIsFile
  kFSEventStreamEventFlagItemCreated, kFSEventStreamEventFlagItemModified, kFSEventStreamEventFlagItemIsFile
  kFSEventStreamEventFlagItemCreated, kFSEventStreamEventFlagItemModified, kFSEventStreamEventFlagItemIsFile
  kFSEventStreamEventFlagItemCreated, kFSEventStreamEventFlagItemModified, kFSEventStreamEventFlagItemIsFile
  kFSEventStreamEventFlagItemCreated, kFSEventStreamEventFlagItemModified, kFSEventStreamEventFlagItemIsFile
  kFSEventStreamEventFlagItemCreated, kFSEventStreamEventFlagItemModified, kFSEventStreamEventFlagItemIsFile
  kFSEventStreamEventFlagItemCreated, kFSEventStreamEventFlagItemModified, kFSEventStreamEventFlagItemIsFile
  kFSEventStreamEventFlagItemCreated, kFSEventStreamEventFlagItemModified, kFSEventStreamEventFlagItemIsFile
```
Note that there are a bunch of them because the test is looping. Also note that Created is in every single event despite the file not being Created more than once. This is because OSX appends a Created event to *almost* every event. The only way to be sure a Creation actually happened is if the received event contains only a Creation. If it contains a modification then we have no way of knowing whether it was a modification on an existing file or a creation and modification of a new file. 

So we currently filter out those questionable creations and only raise a Created event if we're positive the file was newly created. The alternative would be to include a Created event with pretty much every other event that happens which imo is far less helpful. The tradeoff here is that with the existing implementation we're going to miss Creations that happen at the same time as other valid events **on the same file**.

In a perfect world the OSX watcher APIs would do what they're supposed to do and not coalesce events so we could get an event for every detected change, but alas. 

So here are our options:
- Rewrite the entire FSW OSX implementation using kqueues instead of FSEvents.
- Store some state to better identify what kind of changes occurred.
- Read the creation time of the file for which we receive an event. If the file was has been created since the last callback was received, raise a Created event. Not perfect since you could set the CreationTime to trigger a Created event this way.
- Forward all of those Created events that OSX is giving us (not my vote :))
- Leave it as is. Miss some Created events. Rewrite some of these tests.

**Comment by stephentoub** [comment]
> Forward all of those Created events that OSX is giving us (not my vote :))

Unfortunately this may be the least bad option.  Ignoring valid Created events because we can't differentiate them from spurious ones means we're actively losing data.

**Comment by ianhays** [comment]
>Unfortunately this may be the least bad option. Ignoring valid Created events because we can't differentiate them from spurious ones means we're actively losing data.

True, we would be missing some events. I think that's preferable to raising a bunch of invalid events though, since in that case the Created event would lose all meaning as it would be tacked onto pretty much everything.

You were correct about the event caching, by the way. The OSX file watching API has a database of events that are cached on a system-wide basis. This also explains why performing an action on a file then creating a FSW that watches that file will cause the next event to contain a flag triggered by that action even though it occurred before creating the FSW.

Example/Proof:
```
File.Create(otherFile).Dispose();
Thread.Sleep(1000);
File.SetLastWriteTime(otherFile, DateTime.Now + TimeSpan.FromSeconds(10));
Thread.Sleep(1000);
File.AppendAllText(otherFile, "size increase");
Thread.Sleep(1000);
File.SetLastAccessTime(otherFile, DateTime.Now + TimeSpan.FromSeconds(10));
Thread.Sleep(1000);
File.Delete(otherFile);
```

raises 5 separate event callbacks with flags:
```
  kFSEventStreamEventFlagItemCreated, kFSEventStreamEventFlagItemIsFile
  kFSEventStreamEventFlagItemCreated, kFSEventStreamEventFlagItemInodeMetaMod, kFSEventStreamEventFlagItemIsFile
  kFSEventStreamEventFlagItemCreated, kFSEventStreamEventFlagItemInodeMetaMod, kFSEventStreamEventFlagItemModified, kFSEventStreamEventFlagItemIsFile
  kFSEventStreamEventFlagItemCreated, kFSEventStreamEventFlagItemInodeMetaMod, kFSEventStreamEventFlagItemModified, kFSEventStreamEventFlagItemIsFile
  kFSEventStreamEventFlagItemCreated, kFSEventStreamEventFlagItemRemoved, kFSEventStreamEventFlagItemInodeMetaMod, kFSEventStreamEventFlagItemModified, kFSEventStreamEventFlagItemIsFile

```

Without the sleeps the flags are coalesced (usually into 1-2 events):
```
  kFSEventStreamEventFlagItemCreated, kFSEventStreamEventFlagItemInodeMetaMod, kFSEventStreamEventFlagItemModified, kFSEventStreamEventFlagItemIsFile
  kFSEventStreamEventFlagItemCreated, kFSEventStreamEventFlagItemRemoved, kFSEventStreamEventFlagItemInodeMetaMod, kFSEventStreamEventFlagItemModified, kFSEventStreamEventFlagItemIsFile
```

Unfortunately there doesn't seem to be a way to clear the event table as it isn't based on the event stream or the watch-loop, but rather on the os. It looks possible that [this OSX function will wipe the table up to the given EventID](https://developer.apple.com/library/mac/documentation/Darwin/Reference/FSEvents_Ref/#//apple_ref/c/func/FSEventsPurgeEventsForDeviceUpToEventId) but it requires root access and will wipe the table for **all** watchers/users.

**Comment by stephentoub** [comment]
> I think that's preferable to raising a bunch of invalid events though

What if someone is only listening for Created events? Their event may never come. What if they're using WaitForChanged to block indefinitely until Created arrives?

**Comment by stephentoub** [comment]
> Rewrite the entire FSW OSX implementation using kqueues instead of FSEvents

FWIW, this may be the right longer term solution.

**Comment by ianhays** [comment]
> What if someone is only listening for Created events? Their event may never come. What if they're using WaitForChanged to block indefinitely until Created arrives?

Fair point. It's really a question of whether it's better to receive many wrong events and never miss a true event or receive no wrong events but miss certain true events. Since FSW already warns of an occasional missed event, I opted for the latter option since it better mimics Linux&Windows behavior (and makes sharing tests easier).

This particular failure is indicative of a much bigger issue with this API in event caching. Filtering Created events like I'm doing is a band-aid solution to the most common use case but it doesn't do anything for the example I posted above. If we changed this test to instead be ```ChangedRemoved_Success``` (i.e. modify a file then delete it) then the flags would coalesce and we would filter out the Remove and only raise a Changed event. So what if someone is waiting for a Remove but we happen to modify the file near the same time? They'll be waiting for a long time for that removal.

As you said, our other option beyond filtering is to forward an event for every flag we get. This would mean you'd get a **lot** of repeat events for any one change. In the example I posted above, you'd get five created events, 3 attribute modification events, 2 modified events, and 1 removed events. Now imagine if you're modifying a file in a loop and the watcher is catching those changes... you'll get an absurd number of worthless events. At least in this case the FSW is just doing what the OSX API is telling it to, no more no less.

Either way we'll be doing it wrong, but at least the current way is faster. If you believe forwarding events for all flags is *less* wrong, I'm not strongly against changing it to do that. I'd just have to modify the OSX tests to never assert events don't happen, only that they do.

>FWIW, this may be the right longer term solution.

It's starting to look that way. The differences between FSEvents and inotify/ReadDirectoryChanges are becoming more and more difficult to reconcile.

**Comment by stephentoub** [comment]
> If you believe forwarding events for all flags is less wrong, I'm not strongly against changing it to do that. I'd just have to modify the OSX tests to never assert events don't happen, only that they do.

IMO, duplicate events are better than missing events (though both are obviously bad). An app can do a bit of work to filter out duplicates, but it can't really do anything about missing events, as it won't know to look.
