### ISSUE TITLE
.NET Platform Standard dependency clarification

### ISSUE THREAD

**Issue by axelheer** [dotnet/corefx#8650]
The [documentation](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#list-of-net-corefx-apis-and-their-associated-net-platform-standard-version) contains a table, which leads to the assumption that the following "framework reference" should work:

```
"netstandard1.1": {
  "dependencies": {
    "System.Collections": "4.0.0",
    "System.Collections.Concurrent": "4.0.0",
    "System.Globalization": "4.0.0",
    "System.Linq": "4.0.0",
    "System.Linq.Expressions": "4.0.0",
    "System.Linq.Queryable": "4.0.0",
    "System.Reflection": "4.0.0",
    "System.Reflection.Extensions": "4.0.0",
    "System.Runtime": "4.0.0",
    "System.Runtime.Extensions": "4.0.0"
  },
  "imports": "dotnet"
}
```

But it leads to warnings (not errors) like:

```
warning NU1012: Dependency conflict. System.Linq 4.0.0 expected System.Collections >= 4.0.10 but got 4.0.0
```

The corresponding [NuGet package](https://www.nuget.org/packages/System.Linq/4.0.0) has in fact a dependency to `System.Collections >= 4.0.10`, but since that table says `.NETStandard1.1` supports `System.Linq = 4.0.0` as well as `System.Collections = 4.0.0` there seems to be no way in targeting `.NETStandard1.1` with the use of `System.Linq = 4.0.0`. The higher version of `System.Collections` requires `.NETStandard1.3`.

Why is it even necessary to specify the version of the .NET Standard explicitly? Shouldn't the versions of all the dependencies be sufficient?

**Comment by ericstj** [comment]
Those aren't package versions.  They are API versions.  This is mentioned in the doc, right above the table you point out.  The latest package versions encode all the API and across all versions of netstandard.  As such you don't need to know what versions of packages to reference.  You can always just use latest.

The NETStandard version is required because it determines what version of the API you are targeting.  Since the packages encode all the API you need the netstandard version to specify which version you want out of the package.  We did this because encoding API version in package version was very confusing to folks and not the way NuGet was built to work.  Upgrading packages would result in loss of platforms.

**Comment by axelheer** [comment]
Makes sense. Thus, it's even possible to target more than one .NET Standard version. I like that.

But those System.* packages with "pre RC2" versions don't really work for targeting .NET Standard stuff, right? That can be confusing, though.

**Comment by ericstj** [comment]
NETStandard was first added in RC2.

**Comment by axelheer** [comment]
Yeah, I know. Just saying, it *can* be confusing. Maybe unlisting or updating the older non-prerelease (!) versions would help one or another dev out there.

But I figured it out by now. Thanks anyway!

**Comment by ericstj** [comment]
The update to the non-prelease versions will come when we ship .NET core, but they'll be new versions.  Perhaps we can unlist the old ones.  Ideally once we have the new packages out the NuGet tooling will lead folks only to latest.
