### ISSUE TITLE
OuterLoop: Release builds test with previous build native binaries, causing upgrade failures

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#8787]
```
MESSAGE:
System.EntryPointNotFoundException : Unable to find an entry point named 'CryptoNative_EcKeyCreateByOid' in DLL 'System.Security.Cryptography.Native'.
+++++++++++++++++++
STACK TRACE:
at Interop.Crypto.EcKeyCreateByOid(String oid) at System.Security.Cryptography.ECDsaOpenSsl.GenerateKeyLazy() at System.Lazy`1.CreateValue() at System.Lazy`1.LazyInitValue() at System.Security.Cryptography.ECDsaOpenSsl.DuplicateKeyHandle() at System.Security.Cryptography.OpenSsl.Tests.RsaOpenSslTests.VerifyDuplicateKey_ECDsaHandle()
```

To see full test log [here](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_osx_release/47/#showFailuresLink)

**Comment by Priya91** [comment]
Requires a package version update..
@MattGal The native images were copied using the ```TestWithLocalLibraries=true```. But this doesn't seem to work anymore, is there any other flag to be used?

**Comment by bartonjs** [comment]
I'm hoping that this is a "we haven't produced the right packages / off by one" error; we'll hopefully find out today.

**Comment by Priya91** [comment]
@bartonjs Bringing this to rtm, same failures happening in release builds..

**Comment by Priya91** [comment]
The failures are happening only in release build, not in debug.. Investigating.

**Comment by bartonjs** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_osx_release/50/ passed, which was after we had the new package baselines.

So some part of OuterLoop (release only, by the description of things) is causing it to run with the old native binary but the new managed binary.   Since you were looking into the infrastructure piece of the puzzle I'm sending this back to you, @Priya91.
