### ISSUE TITLE
Path Too Long Exception

### ISSUE THREAD

**Issue by dazinator** [dotnet/corefx#8810]
Raising here as per: https://github.com/aspnet/FileSystem/issues/193

I'm listing files from an `IFileProvider` by enumerating the files, and filtering based on the file extension. However when accessing `IFileInfo.PhysicalPath` I'm getting a `PathTooLongException`

![image](https://cloud.githubusercontent.com/assets/3176632/15479635/f963432a-2118-11e6-8fb8-5a801bfb7e06.png)

I'm using build `1.0.0-rc2-15922` in an ASP.NET 5 RC1 based application.

Given that the file exists (on Windows), why should it error when accessing it's path?

**Comment by JeremyKuhne** [comment]
@dazinator Can you please share the full path?

**Comment by JeremyKuhne** [comment]
It is unlikely that your path is longer than a [short.MaxValue](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/IO/PathHelper.Windows.cs#L69). The more likely scenario is that it has a segment that is too [long](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/IO/PathHelper.Windows.cs#L128).

Of course it also might be a bug in our logic.

The string, as you see, isn't accurate anymore. The 260/248 limit is now something near 32,000 on Windows (it varies due to internal system details and lack of long path support on some APIs). I'll open an issue and get it updated.

**Comment by JeremyKuhne** [comment]
Sorry- I totally misread the stack. The string is updated on CoreFx.  Your stack appears to be running on Desktop.  FileSystemInfo doesn't get FileIOPermission on Core- it doesn't even exist.

**Comment by Kaithos** [comment]
@JeremyKuhne This has been a problem in .NET since before .NET Core. The maximum length a path can be is dependent on how it is accessed. In Windows Explorer, you can make use of the full ~32000 character limit, but not through the APIs that .NET uses.

https://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx#maxpath

**Comment by dazinator** [comment]
@JeremyKuhne - ok so I think you are saying this is fexed on .net core, but as I am targeting desktop so i won;t see this fix. Do you know if this fix will also go into full / desktop .net framework or whether these is an apporpriate place to raise an issue for that?  It looks like you guys fixed it here (my guess): https://github.com/dotnet/corefx/pull/3001

**Comment by JeremyKuhne** [comment]
@dazinator 

Without seeing your path I'm going to assume it is too long (e.g. over `MAX_PATH` (260) or the directory is over 248). I initially assumed that you hit >= 260 on Core because you opened the issue here. If it is < 260 we've got an issue we need to follow up on.

@Kaithos, @dazinator

We're working towards getting the limits down in the desktop framework. In the upcoming 4.6.2 you'll be able to use `\\?\` to access files > 260 if your code is running in full trust. We also allow the OS to report back that paths are too long- this will allow long paths to work without `\\?\` when Windows removes the `MAX_PATH` check in the future.

You can add your support for the feature in general here:

[Visual Studio User Voice: Fix 260 character file name length limitation](https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/4954037-fix-260-character-file-name-length-limitation)

**Comment by dazinator** [comment]
Thank you for clarifying this
