### ISSUE TITLE
CLR throws InvalidProgramException when a class contains a single static Vector<byte> field

### ISSUE THREAD

**Issue by cesarbs** [dotnet/corefx#8825]
**Happens on full CLR only.**

Repro:

    using System.Numerics;

    namespace VectorRepro
    {
        public class Program
        {
            static Vector<byte> _vector = new Vector<byte>(42);
            //static Vector<byte> _vector2 = new Vector<byte>(43);

            public static void Main(string[] args)
            {
            }
        }
    }

Error:

    Unhandled Exception: System.TypeInitializationException: The type initializer for 'VectorRepro.Program' threw an exception. ---> System.InvalidProgramException: Common Language Runtime detected an invalid program.
       at VectorRepro.Program..cctor()
       --- End of inner exception stack trace ---
       at VectorRepro.Program.Main(String[] args)

If you uncomment the second static field, no error is thrown.

Other remarks:

* Only seems to happen with `byte`.
* Also repros if you have multiple static `Vector<byte>`s in a class and add a new class containing a single one. That's how we actually found it: https://github.com/aspnet/KestrelHttpServer/pull/874

**Comment by cesarbs** [comment]
I'm using System.Numerics.Vectors 4.1.0.

**Comment by cesarbs** [comment]
Verified on .NET 4.5.1 and 4.6.

**Comment by halter73** [comment]
This only seems to happen if `Vector.IsHardwareAccelerated == True`

**Comment by CarolEidt** [comment]
This appears to be AVX-related. I can't repro it on my non-AVX2 system, and if I set COMPlus_EnableAVX=0 on the AVX2 machine, the problem goes away. I will have a look at this.

**Comment by CarolEidt** [comment]
It would be great to have a Connect bug filed for this (http://connect.microsoft.com/).
It is indeed AVX-related. The method triggers `Compiler::compQuirkForPPP()` which works around a bug that was not exposed by jit64.It requires a method that has exactly two locals (which includes compiler temps, which is what is created in this case - and if you uncomment the second static, you get another), one of which is the temp local created for outgoing args (so there has to be a call). It's somewhat related to CoreClr Issue [5116](https://github.com/dotnet/coreclr/issues/5116) because if the constructor was recognized as an intrinsic there would not be an outgoing arg space.
It doesn't repro in the coreclr sources because we now re-type the SIMD locals in the importer, so it doesn't match the `TYP_STRUCT` condition in the quirk.

**Comment by joshfree** [comment]
@CarolEidt here's a connect bug for .NET 4.6 @ https://connect.microsoft.com/VisualStudio/feedback/details/2751596

**Comment by CarolEidt** [comment]
This has been fixed in coreclr and will be fixed in a future release of the desktop CLR. There are two workarounds:

- The first is to set COMPlus_EnableAVX=0.
- The second is to declare at least one additional local variable, as is done in this example
