### ISSUE TITLE
Any reason System.Reflection.TypeExtensions can also target Profile151

### ISSUE THREAD

**Issue by niemyjski** [dotnet/corefx#8855]
I see no reason why it can't profile 151 when it already targets a lot of similar profiles.

**Comment by ericstj** [comment]
I believe at least some version of the surface area can. We used to have a version that was building for Win8/WinPhone8.

**Comment by karelz** [comment]
@ericstj what is needed here?

**Comment by ericstj** [comment]
Profile 151 is compatible with netstandard1.2 so the ask is to cross-compile for that or earlier and include it in the package.

This particular assembly no longer has a package in corefx since its been absorbed by ns2.0 so the fix here would need to happen in servicing (or we'd need to bring back the package and continue shipping it, despite the overlap).  /CC @weshaggard

**Comment by karelz** [comment]
Given the high cost of maintaining cross-compilation of a package and given the low interest (1 vote), I would suggest to close the issue - if more folks are interested, we can reconsider later.
