### ISSUE TITLE
Reduce ETW events impact on WCF perf 

### ISSUE THREAD

**Issue by zhenlan** [dotnet/corefx#8901]
@vancem is currently looking into a fix of an ETW issue that has an impact of 2~3 times on the throughput of WCF. The fix is tracked for RTM release.

**Comment by stephentoub** [comment]
Can you provide more details on the issue?

**Comment by joshfree** [comment]
@vancem ping

**Comment by vancem** [comment]
Last Friday 5/27 I determined that the problem was actually due to a problem in the WCF EventSource.  Basically the Debug and Admin channel were 'swapped' as far as EventSource was concerned, so every Debug message was being sent (but then trimmed at the OS level but you still have all the perf overhead).   I have sent private e-mail to Zhenlan with a way to fix it for him to try out.  If that works (hopefully he can determine that today), we should not need to do anything.

**Comment by zhenlan** [comment]
We tried what Vance suggested. In a quick perf run with private, the issue does seem solved - we got 2~3 times increase in throughput. We will do more testing but I think this issue can be closed now. Thanks a lot @vancem for the help!
