### ISSUE TITLE
Obsolete Task<T>.Result, Introduce Task<T>.TryGetResult

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#8931]
Related https://github.com/dotnet/corefx/pull/8902 "Remove "Result" property of ValueTask<T>"
- `Task<T>.Result` has can have implicit blocking. If you invoke an async method in a UI app, and try to fetch the .Result of the returned task before it is completed, you’ll get a deadlock.
- `.GetAwaiter().GetResult()` will force a blocking value return if required
- An expected test to see if the result is ready without exceptions may be `task.IsCompleted`, however it should really be `task.Status == TaskStatus.RanToCompletion`

An alternative `bool TryGetResult<T>(out T value)` would be a safer option increasing the chance of writing correct code. 

It would return `true` if the task has `RanToCompletion` with the result in the out param.

It would return `false` if the task hadn't completed (or was cancelled/faulted, maybe throw exception then)

**Comment by svick** [comment]
I think that `task.Result` is still useful for .Net 4-style parallel computations. You can use `async`-`await` for those too, but it shouldn't be necessary.

I don't think that `task.GetAwaiter().GetResult()` is an acceptable alternative, but `task.Wait(); task.TryGetResult(out var result);` might be.

**Comment by GSPP** [comment]
Wouldn't it be a good idea to keep Task and ValueTask aligned where possible?

`.GetAwaiter().GetResult()` has different exception propagation behavior than Result and Wait have. In particular the fact that it tends to throw away exceptions makes this option not entirely harmless.

**Comment by nguerrera** [comment]
I think something that indicates that it will only retrieve the result if the task completed successfully should be in the name. Otherwise, I imagine the only difference between `Result` and `TryGetResult` to be that the former can raise an exception, not that the latter will never block.

Perhaps, `TryGetSuccessfulResult`?

**Comment by GSPP** [comment]
Or a boolean argument `bool allowThrow`. That way the caller is forced to pick what he wants.

**Comment by jnm2** [comment]
Given the strong warnings against using `.Result` and `.Wait()` by the [ASP.NET team](https://github.com/aspnet/Security/issues/59#issue-42333657) and Stephen Cleary [(1)](http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html), [(2)](blog.stephencleary.com/2014/12/a-tour-of-task-part-6-results.html) because of deadlocks, wrapped exceptions, and plain inefficiency, I consider them a strong code smell. They're obnoxious.

**Comment by Mike-EEE** [comment]
Nice idea, it has got my upvote.  I have added it to my [growing list of issues and discontent with TPL](https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/9126493-improve-asynchronous-programming-model).  Although this looks to fix/address a few of them. 😎

**Comment by karelz** [comment]
Looks useful. Can someone put together formal API proposal please?

**Comment by terrajobst** [comment]
Hey @stephentoub, what are your thoughts on this?

We can obviously not remove the the blocking APIs but it might be worthwhile considering doing something like obsoleting them or providing an analyzer. My gut feel is that obsoletion is the wrong thing because it's too widely used, and there are many cases where the usage is safe because the caller knows that the task has already completed (e.g. when awaiting multiple tasks).

We could also considering adding a new API that will only work when the task is completed and throw when it's not completed yet. This API should probably have a `TryXxx` counterpart.

Thoughts?

**Comment by stephentoub** [comment]
> Hey @stephentoub, what are your thoughts on this?

We should not obsolete them; as highlighted, there are valid uses.  I'd be fine with an analyzer that warned about blocking behaviors in general, not just limited to Task, but rather an analyzer that, for example, warned any time you were using a synchronous/blocking API when an asynchronous alternative existed.  I do expect that such an analyzer would have a relatively high noise to signal ratio, though.

> We could also consider adding a new API that will only work when the task is completed and throw when it's not completed yet. This API should probably have a TryXxx counterpart.

Essentially what's being proposed is:
```C#
public static bool TryGetResult<T>(this Task<T> task, out T result)
{
    if (task.Status == TaskStatus.RanToCompletion)
    {
        result = task.Result;
        return true;
    }
    result = default(T);
    return false;
}
```
? Eh.  I don't have any real problem with it, but I'm not sure how useful it is.  In my experience, if you're trying to get a task's result, you typically either want the result regardless of whether the task has already completed (e.g. ```await t;```, ```t.Result```, or ```t.GetAwaiter().GetResult()```), or you want to know the status of the task and be able to distinguish the various cases of it not having a result (not yet completed vs completed but due to error/cancellation)... for that you're going to check either its Status or its various ```Is``` properties.  In neither of those predominant use cases would TryGetResult be valuable.

My $.02.

**Comment by benaadams** [comment]
@terrajobst I think @stephentoub makes a lot of sense. Closing.

**Comment by slang25** [comment]
Another option would be to set the `SynchronizationContext` to `null` and then return it. In my experience these issues come deep into the call stack where people are well away from places that require/assume a sync context, shouldn't we be steering people towards a blocking usage that doesn't deadlock?

Something like (naming is hard!):

```csharp
public static T GetResultSafely<T>(this Task<T> task)
{
    var capturedContext = SynchonizationContext.Current;
    try {
        SynchonizationContext.SetSynchronizationContext(null);
        return task.GetAwaiter().GetResult();
    }
    finally {
        SynchonizationContext.SetSynchronizationContext(capturedContext);
    }
}
```
The xml doc comments could make it clear you will not have access the the sync context within here.
This is what I am recommending to my colleagues as we use 3rd party libraries we cannot be sure use `await` responsibly.

I'm not sure why this wouldn't be the default. Would love to hear your thoughts @stephentoub

**Comment by stephentoub** [comment]
> Would love to hear your thoughts @stephentoub

I don't see how the proposed function helps.  By the time you're blocking waiting on the task, you've already invoked the asynchronous operation that in turn may have observed the current synchronization context and captured it.  This helper would instead need to take a delegate that could be invoked while the SynchronizationContext was null, rather than taking the task to wait on.

**Comment by slang25** [comment]
Very good point @stephentoub.

```csharp
public static T ExecuteSynchronously<T>(Func<Task<T>> taskFunc)
{
    var capturedContext = SynchonizationContext.Current;
    try {
        SynchonizationContext.SetSynchronizationContext(null);
        return task.Invoke().GetAwaiter().GetResult();
    }
    finally {
        SynchonizationContext.SetSynchronizationContext(capturedContext);
    }
}
```

Would this be worth considering.

**Comment by stephentoub** [comment]
> Would this be worth considering

I don't think this is a good thing to add; I don't want to encourage more synchronous blocking on tasks by adding yet another way to do it.

If we were interested in something along those lines (I'm not saying we should), I would rather see something like:
```C#
public class SynchronizationContext
{
    public static TResult RunWithCurrent<TState, TResult>(SynchronizationContext target, Func<TState, TResult> function, TState state)
    {
        SynchronizationContext old = SynchronizationContext.Current;
        try { return function(state); }
        finally { SynchronizationContext.SetSynchronizationContext(old); }
    }
}
```
If you wanted to use that for your purposes, you could, e.g.
```C#
SynchronizationContext.RunWithCurrent(null, _ => SomeMethodAsync(), null).GetAwaiter().GetResult();
```
but it could also be used for non-Task-returning methods.

**Comment by slang25** [comment]
@stephentoub I assume you are missing a usage of `target` in there like:
```csharp
public class SynchronizationContext
{
    public static TResult RunWithCurrent<TState, TResult>(SynchronizationContext target, Func<TState, TResult> function, TState state)
    {
        SynchronizationContext old = SynchronizationContext.Current;
        try {
            SynchronizationContext.SetSynchronizationContext(target);
            return function(state);
        }
        finally { SynchronizationContext.SetSynchronizationContext(old); }
    }
}
```

**Comment by stephentoub** [comment]
Yup, was typing too quickly. Thanks.

**Comment by Drawaes** [comment]
https://github.com/aspnet/KestrelHttpServer/issues/2104#issuecomment-337346959

People are constantly caught out by this.

**Comment by Drawaes** [comment]
I am less concerned about outright deadlocks and sync contexts, but instead the threadpool starvation is the one that normally gets through testing and kills apps in prod under load

**Comment by stephentoub** [comment]
My answer here hasn't changed from before:
https://github.com/dotnet/corefx/issues/8931#issuecomment-259431624

But if the goal is to simply detect when blocking waits are being used, there are ways to do that, e.g. there's already an EventSource event for it:
```C#
using System;
using System.Diagnostics.Tracing;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static void Main()
    {
        TaskBlockingListener.Start();

        Task.Run(() => Thread.Sleep(5000)).Wait();
    }
}

public sealed class TaskBlockingListener : EventListener
{
    private static readonly Guid s_tplGuid = new Guid("2e5dba47-a3d2-4d16-8ee0-6671ffdcd7b5");
    private static readonly Lazy<TaskBlockingListener> s_listener = new Lazy<TaskBlockingListener>(() => new TaskBlockingListener());

    public static void Start() { object ignored = s_listener.Value; }

    private TaskBlockingListener() { }

    protected override void OnEventSourceCreated(EventSource eventSource)
    {
        if (eventSource.Guid == s_tplGuid)
        {
            EnableEvents(eventSource, EventLevel.Informational, (EventKeywords)3); // 3 == Task|TaskTransfer
        }
    }

    protected override void OnEventWritten(EventWrittenEventArgs eventData)
    {
        if (eventData.EventId == 10 && // TASKWAITBEGIN_ID
            eventData.Payload != null &&
            eventData.Payload.Count > 3 &&
            eventData.Payload[3] is int value && // Behavior
            value == 1) // TaskWaitBehavior.Synchronous
        {
            Console.WriteLine("Blocking on an incomplete task." + Environment.NewLine + Environment.StackTrace);
        }
    }
}
```
cc: @davidfowl

**Comment by davidfowl** [comment]
Agreed. We can remove the API and it’s still useful in a variety of cases. What we can do is use techniques like above to detect common error conditions. Maybe this could be on if a flag is set (detect blocking tasks). It would more effectively help find blocking code all over existing code bases.

**Comment by benaadams** [comment]
>  if the goal is to simply detect when blocking waits are being used, there are ways to do that,

Is a very nice diagnostic sample; is easier than trying to get people to manually spot in existing code base or wait for the next jam to get a process dump.

>  I'd be fine with an analyzer that warned about blocking behaviors in general, not just limited to Task, but rather an analyzer that, for example, warned any time you were using a synchronous/blocking API when an asynchronous alternative existed. I do expect that such an analyzer would have a relatively high noise to signal ratio, though.

Which repo should analyser issues get raised?

**Comment by Drawaes** [comment]
Maybe a listener can be added to ASP.NET by default in debug mode? It could be switched off with a launch setting.

This would be similar to how app insights runs today when you run the default asp.net core project. This would catch where the error often happens and allow for it to be turned off.

**Comment by ayende** [comment]
@stephentoub Is there a source with all these values documents? 
And will this work in a cross platform manner?

**Comment by stephentoub** [comment]
> Is there a source with all of these values documented?

I don't know if there's any documentation other than the source:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/Tasks/TPLETWProvider.cs

> And will this work in a cross platform manner?

Yes

**Comment by demosglok** [comment]
why this magic guid?
Guid("2e5dba47-a3d2-4d16-8ee0-6671ffdcd7b5");

**Comment by stephentoub** [comment]
> why this magic guid?

Every ETW provider chooses a unique ID in the form of a guid that every consumer uses to enable/listen to it.
