### ISSUE TITLE
Set up and run tests on BigEndian platforms.

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#8962]
At the moment, it appears that all tests are being run on LittleEndian platforms.  Given there are a number of packages and protocols that actually care about the endianness of the system, we should make sure our tests pass on these systems.

In theory only those packages that deal with endian-handline code would need this, but I'm not sure how easy that would be to check for...

**Comment by ellismg** [comment]
Is there an existing big-endian platform that CoreCLR works on today?

**Comment by Clockwork-Muse** [comment]
No clue!
At minimum several versions of mono do/did, including on ARM, so it's something we at least need to be aware of for the future.  I'm not sure if that would be leverageable immediately, since I haven't looked at the mono integration at all.

**Comment by stephentoub** [comment]
If in the future we support a platform that's big endian, then in support of supporting that platform we would necessarily be getting all of our tests to run on it.  And until such time, there doesn't seem to be much value in trying to set up such infrastructure, especially since we'd be attempting to run on a platform that's not supported.  I suggest we just close this for now.
