### ISSUE TITLE
[Questions] About back slash support in URI 

### ISSUE THREAD

**Issue by chinadragon0515** [dotnet/corefx#8974]
This is related to issue OData/RESTier#414
Originally I ask this with https://github.com/aspnet/HttpAbstractions/issues/643

Now we have a URL with back slash in it, like ~/service/Users('Some%5Cuser') , when the service receive the request, I find it will auto convert back slash to slash, and key is not 'Some%5Cuser' or 'Some\user' but is 'Some/user'

I did some debug, it is converted before customer's code is called, in method "System.Web.Http.dll!System.Web.Http.Routing.HttpRoute.GetRouteData(string virtualPathRoot, System.Net.Http.HttpRequestMessage request) Line 109	C#", the request original string is already with key 'Some/user'.

I did some search, I find this configuration,
  < uri>
    < schemeSettings>
      < add name="https" genericUriParserOptions="DontUnescapePathDotsAndSlashes"/>
      < add name="http" genericUriParserOptions="DontUnescapePathDotsAndSlashes"/>
    < /schemeSettings>
  < /uri>
This does not work for me, I see there is an option DontConvertPathBackslashes, but when I set here, it indicates this is not correct setting.

Can someone help to advise how I can configure a request with back slash? Or this is not supported?

**Comment by davidsh** [comment]
>< uri>
< schemeSettings>
< add name="https" genericUriParserOptions="DontUnescapePathDotsAndSlashes"/>
< add name="http" genericUriParserOptions="DontUnescapePathDotsAndSlashes"/>
< /schemeSettings>
< /uri>

.NET Core doesn't support XML config.  Is this question about .NET Framework (Desktop)?

**Comment by davidsh** [comment]
cc: @CIPop

**Comment by chinadragon0515** [comment]
@davidsh The project we create is "C# > Web > ASP.NET Web Application.", and 
In the New ASP.NET Project dialog box, select the Empty template.
Check the Web API check box.

**Comment by davidfowl** [comment]
It's not a .NET Core problem. Seems like it's a normal .NET Framework question. @chinadragon0515 These repositories are .NET Core related, not .NET Framework. The issue also looks like it might be a Web API question.

**Comment by chinadragon0515** [comment]
David, do you have any projects suggested I should ask this question? I asked here before, https://github.com/aspnet/HttpAbstractions/issues/643

**Comment by lextm** [comment]
@chinadragon0515 I will suggest you open a support case via http://support.microsoft.com with Microsoft support team as you are running a typical ASP.NET Web API applications on .NET Framework. Opening such issues on GitHub for ASP.NET Core/.NET Core is an obvious wrong approach to get it resolved, as the Core things are completely different.

If you do want to debug further, Web API on .NET Framework is open source, https://aspnetwebstack.codeplex.com/SourceControl/latest and Microsoft has .NET Framework reference source at http://referencesource.microsoft.com/ They might tell you which lines of code changed the slash miserably.

Microsoft support team has access to the whole source code and the debugging skills, so via a support case you can get the root cause identified sooner.

**Comment by chinadragon0515** [comment]
@lextm thanks. I will check the code and see how it is fixed, and I also sent a note to ASp.NET discussion group today and will see the response I got tomorrow.

I will close this issue now and will re-open the issue on ASP .NET as I think if we have document on this part, it will help to avoid confusions and further issues from consumers..
