### ISSUE TITLE
ZipArchiveEntry always writes Unicode bit for entries

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#8995]
Initial discussion here: https://github.com/dotnet/corefx/pull/8986#issuecomment-222739144

Previously we would only write the Unicode bit if
1. The system default was UTF8.
2. Any characters in the string were greater than 127.

It turns out that neither of these were very common so before the bit was rarely set, now it is always set. 

/cc @ianhays

**Comment by ianhays** [comment]
The problem is that because `DefaultSystemEncoding` is hard-coded to UTF-8, the call to `ZipHelper.RequiresUnicode` is worthless and might as well always return true.

Our options:
- Make `DefaultSystemEncoding` return Encoding.GetEncoding(0) and do not set the Unicode bit unless the encoding returned by GetEncoding is UTF8 or the entryName is a unicode string.
  - Matches desktop behavior.
- Make 'DefaultSystemEncoding' return ASCII. Do not set the unicode bit unless entryName is a unicode string.
- Leave the default as UTF8 and remove the unnecessary ZipHelper.RequiresUnicode method. Always set the Unicode bit.

**Comment by ericstj** [comment]
I wonder if #1 was ever true or if that's just an oddity of how the code was written.

If it were true, then what happens if the system default was some other multi-byte character set?  We'd be writing garbage since we'd say it isn't Unicode but write multi-byte characters  https://github.com/dotnet/corefx/blob/2ff9b2a1e367a9694af6bdaf9856ea12f9ae13cd/src/System.IO.Compression/src/System/IO/Compression/ZipArchiveEntry.cs#L47

I think the right way for this code to behave is check if the entry name can fit into IBM Code Page 437.  If so, write it as is.  If not, write as UTF8.  This sounds like your second option (not sure about equivalence between our ASCII encoding and 437).

**Comment by ianhays** [comment]
>I think the right way for this code to behave is check if the entry name can fit into IBM Code Page 437. If so, write it as is. If not, write as UTF8. 

I agree. 

>This sounds like your second option (not sure about equivalence between our ASCII encoding and 437).

[Wikipedia: CodePage 437 includes ASCII codes 32–126](https://en.wikipedia.org/wiki/Code_page_437) and they are directly translatable. 0-31 are special characters and don't align directly with ASCII.

My suggestion for that case would be modify our RequiresUnicode method to check that every byte in the string is between 32-126. If it isn't, then RequiresUnicode returns true and the Unicode bit is set.
