### ISSUE TITLE
Jenkins CI OS X slave went offline during the build

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#9018]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/osx_debug_prtest/60/consoleFull#-1250096032a6fc86e9-18e8-40d3-a876-f39e33df2c41

Slave went offline during the build
18:42:55 ERROR: Connection was broken: java.io.IOException: Connection aborted: org.jenkinsci.remoting.nio.NioChannelHub$MonoNioTransport@3b61e371[name=dci-macpro-12]
18:42:55 	at org.jenkinsci.remoting.nio.NioChannelHub$NioTransport.abort(NioChannelHub.java:208)
18:42:55 	at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:628)
18:42:55 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
18:42:55 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
18:42:55 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
18:42:55 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
18:42:55 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
18:42:55 	at java.lang.Thread.run(Thread.java:745)
18:42:55 Caused by: java.io.IOException: Connection reset by peer
18:42:55 	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
18:42:55 	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
18:42:55 	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
18:42:55 	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
18:42:55 	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:384)
18:42:55 	at org.jenkinsci.remoting.nio.FifoBuffer$Pointer.receive(FifoBuffer.java:136)
18:42:55 	at org.jenkinsci.remoting.nio.FifoBuffer.receive(FifoBuffer.java:306)
18:42:55 	at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:561)
18:42:55 	... 6 more

**Comment by mmitche** [comment]
@joshfree Alright. Man this DTAP lab connection is not great.  I'm still working with John Prather to find out why.  I may have another workaround though,

**Comment by mmitche** [comment]
When this was seen within Azure (for other connection issues) it was only seen on agents that were doing their initial handshake with JNLP (windows nodes and the macs).  SSH seemed immune.  I changed the connection method on one machine to use SSH instead.  I want to make sure stuff passes and then I'll switch the rest over

**Comment by mmitche** [comment]
@joshfree Switched all the nodes to connect VIA SSH.  I *think* this should solve the DTAP problems

**Comment by joshfree** [comment]
Thanks @mmitche! :smile:

**Comment by stephentoub** [comment]
Thank you, Matt. Fingers crossed.

**Comment by akoeplinger** [comment]
FYI we hit similar reliability issues with the JNLP slaves when we moved the Mono Jenkins to Azure. We fixed it by reducing the ping channel interval via the `hudson.slaves.ChannelPinger.pingInterval` JVM param **on the slaves** e.g. to 1.

The twist here is that you can't set this via the Jenkins slave config UI, you need to set it directly in the upstart or equivalent script that starts the Jenkins slave .jar (because it obviously isn't known when starting the slaves as opposed to the ssh based method where the master starts the slave process).

**Comment by mmitche** [comment]
@akoeplinger I think this is a different issue.  The ping is actually coming from the master and not the slave (it's an empty remote method call), so setting it on the master command line and upping the ping timeout fixes the issue.

**Comment by akoeplinger** [comment]
@mmitche the slave pings the master as well. The problem we had is that the default ping interval is 5 minutes but Azure terminates idle connections after 4 minutes. When that happened we hit these IOExceptions.

**Comment by mmitche** [comment]
@akoeplinger We set the idle connection timeout to 30 mins in Azure to avoid this.  In this case the master still thinks a node is connected even though all calls over the connection fail.  It still thinks it's connected because somehow the Channel object (now invalid) is not correctly removed  The node then tries to reconnect over and over again and you get this "Channel is already closed" exception

**Comment by akoeplinger** [comment]
@mmitche ah ok, yeah that looks like a different issue then. Might be still useful info for other people dealing with Jenkins on Azure :)

**Comment by mmitche** [comment]
Yeah.  I think that's documented somewhere on the Jenkins site.  The Jenkins issue has been filed and I've even taken a stab at debugging it, but the repro is hard to come by.
