### ISSUE TITLE
Buggy DateTime / DateTimeOffset cross-platform conversions

### ISSUE THREAD

**Issue by bchavez** [dotnet/corefx#9019]
I have the following **C#** lines in a **.NET Core Console App**:
```
new DateTimeOffset(DateTime.MinValue).Offset;
new DateTimeOffset(DateTime.MinValue).UtcTicks;
```
:clock8: Output on **Windows** `dotnet run`:
```
-08:00:00
288000000000
```
:clock7: Output on **Linux** `dotnet run`:
```
-07:53:00
283800000000
```
**I think** I *should* be getting the same result regardless of the platform I'm running on. About `4200000000` ticks and `7` minutes off?

I found this after some closer investigation of time issues with my RethinkDB database driver. See [Issue 66](https://github.com/bchavez/RethinkDb.Driver/issues/66).

I apologize for the noise if this isn't considered a bug. :crying_cat_face: 

----

##### Linux Box
```
//Timezone
root@dev1:~/temp/tester# date +'%:z %Z'
-07:00 PDT

root@dev1:~/temp/tester# dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```
##### Windows Box
```
//Timezone: Pacific Time
R:\tester>dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
```

**Comment by stephentoub** [comment]
@eerhardt can comment better, but I believe this is "by design", due to the fact that Windows and Unix/ICU have different timezone data files that differ in a few ways.

**Comment by bchavez** [comment]
Hm. Interesting. `DateTimeOffset.MinValue` is consistent cross-platform, but only the conversion calculation `DateTime -> DateTimeOffset` isn't.

C# Code:
```
DateTimeOffset.MinValue.Offset;
DateTimeOffset.MinValue.UtcTicks;
```

**Windows** `dotnet run`
```
00:00:00
0
```
**Linux** `dotnet run`
```
00:00:00
0
```
Yikes, just seems weird that writing C# code like `new DateTimeOffset(DateTime.MinValue)` is not consistent cross-platform. I guess, the guidance here is not to do any type of conversion from `DateTime` to `DateTimeOffset` to avoid cross-platform inconsistencies?

**Comment by stephentoub** [comment]
> only the conversion calculation  DateTime -> DateTimeOffset  isn't

DateTime.MinValue returns a DateTime constructed like ```new DateTime(0, DateTimeKind.Unspecified)```.  Since its DateTimeKind isn't UTC, when you construct a DateTimeOffset from it, DateTimeOffset's constructor needs to ask TimeZoneInfo for the local UTC offset for that DateTime value.  And time zone data can differ subtly from platform to platform, especially for 2000 years ago.

**Comment by stephentoub** [comment]
As an example, go to http://www.timeanddate.com/time/zone/usa/los-angeles.  Go to the "Time zone changes for:" dropdown, and select "1800-1849".  Note that it shows the UTC offset isn't -8:00, but rather is -7:52:58.

**Comment by eerhardt** [comment]
@stephentoub is correct that Windows and Unix use different data structures to handle time zones. Unix uses the [Olson time zone database](https://en.wikipedia.org/wiki/Tz_database), which is more historically accurate than the Windows data structures.

For example:

```C#
            // January 8, 1650
            var date = new DateTimeOffset(new DateTime(1650, 01, 08, 4, 3, 1));
            Console.WriteLine(date.Offset);

            // June 8, 1650
            date = new DateTimeOffset(new DateTime(1650, 06, 08, 4, 3, 1));
            Console.WriteLine(date.Offset);
```

running on my Windows machine (Central Time) produces:

```
-06:00:00
-05:00:00
```

But this doesn't make any sense because daylight savings time wasn't invented in 1650.

Similarly, like @stephentoub mentions, before the late 19th-century, standard time zones weren't invented. Instead, people used "solar" time".  See https://en.wikipedia.org/wiki/Time_zone#Early_timekeeping.

**Comment by bchavez** [comment]
Ok cool. This reaffirms my suggestion to my users not to use `MinValue` and use **nullable** `DateTime?` to indicate values not set in database driver. :octocat: 

Thanks everyone for the feedback. I really appreciate it.
