### ISSUE TITLE
Official Build Frequency?

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#9156]
Today, in the new build pipeline, we have triggers set to build CoreFX 4 times a day, every day, and CoreCLR 3 times a day, every day.

This leads to tons on version updates everyday and it's generating a lot of noise, IMHO.

I think we should consider doing some (all?) of the following:
- Reduce the frequency of triggered builds.  As we can launch these on demand and have results in an hour, there's less need to be doing them proactively.
- Don't build over the weekend.
- Have automation which auto merges green dependency updates.
- Have automation which closes old dependency updates with no comments/additional commits.

I'm interested in hearing everyone else's thoughts.

/cc @dotnet/corefx-contrib @jhendrixMSFT @eerhardt @wtgodbe

**Comment by eerhardt** [comment]
Here was the "master plan" that @piotrpMSFT and I first laid out when we were in the early stages of designing Maestro.

A lower repo can build as often as it wants, it always updates the "Latest" pointer in `dotnet/versions` with its absolute latest build. Anyone who wants to listen to the "Latest" build can do so.

Our idea was that the repo's tests could be kicked off every time the "Latest" build pointer was updated.

But there should also be another build pointer, we referred to as "LKG" (last known good).  Inter-repo coordination usually happens on LKG builds, not Latest.

A build is declared "LKG" when the repo's tests have executed and passed enough for the build to be considered "good". Each repo can decide what its metric of "good" means.  For CLI, we run all tests on every build and we expect 100% pass rate.  But CoreFX has many more tests, and we do not expect 100% pass rate.  So maybe CoreFX's pass rate is 90% (we can adjust as necessary).

A repo can also decide that not every build needs to be promoted to LKG. Only builds it wants 'downstream' repos to take should be promoted to LKG.  If you want to build every 6 hours, maybe the LKG only gets updated once or twice a day?  (Also, can we do a full test run every 6 hours? Do we need to build more often than we can run our test bed against?)

So the thought here is to define a new build pointer "LKG" that gets updated less frequently than "Latest" gets updated. And then the inter-repo coordination (CoreFX taking a new CoreCLR, or core-setup taking a new CoreFX, etc.) happens when the "LKG" build is updated.

**Comment by joshfree** [comment]
> Reduce the frequency of triggered builds

The new system has only been on a week and I know @jhendrixMSFT is trying to stabilize the new build pipeline so I understand why we're building so frequently right now (and yes there is a bit of noise.. :smile:).  When we're ready to scale back to a normal cadence, I'd probably start with building 2x per day initially for corefx - say 12n and 7pm; with official builds skipped for all of Saturday and skipped for 12n on Sunday.

I believe we're not planning to "slow down" until after the release branches are brought online and after @mmitche has a chance to make some updates to Jenkins to fill some holes in coverage that could allow a check-in to break the new build pipeline unintentionally.  @mmitche? @jhendrixMSFT?

**Comment by stephentoub** [comment]
> Today, in the new build pipeline, we have triggers set to build CoreFX 4 times a day, every day, and CoreCLR 3 times a day, every day. This leads to tons on version updates everyday and it's generating a lot of noise, IMHO

Part of the problem as well is we have three different sets of dependencies that version separately:
https://github.com/dotnet/corefx/blob/master/dir.props#L86-L88
and updates to each of those generate a PR.  Further, because the lines are next to each other, they end up conflicting, so as soon as one of the PRs is merged, the others can't be without intervention off of GitHub. If we could effectively combine those to avoid conflicts, e.g. by having the submitted PRs do all of the updates that are relevant and not just the updates for a particular set of dependencies, that would help to alleviate some of the churn here.

**Comment by weshaggard** [comment]
I agree that there is a lot of noise and also a lot of file changes and conflicts. One thing I've been thinking about is moving away from all the checked in project.json files that need to be updated every time and instead generating them as part of the build and then we could define the package dependencies in an msbuild props file or something and they could be templates to say $(CoreFXVersion) or something. That way all these updates would only ever need to update the one dir.props file in the root. That will help with a lot of this churn and conflict. I've only got some early thinking in this direction but I believe we can pull it off. I'm going to try to find some time to prototype and potentially put together a PR.

**Comment by dagood** [comment]
To stop the merge conflicts in the short term, I mentioned a workaround earlier: https://github.com/dotnet/corefx/pull/9028#issuecomment-223096061

When the dependency split came up, we talked about having these updates combined, but one issue is that we would want them separated out if one isn't working. But if that's the rare case, maybe we could handle that manually and make the automation combine--or add some easy way to generate a PR for a specific change through Maestro without hacking the version files.

I also like @eerhardt's master plan--we can keep building rapidly, but we don't need to create update PRs for every single package set.

**Comment by weshaggard** [comment]
@dagood How much work do you think it would be to partition all the project.json files? That to me seems a little to brittle. It doesn't seem like it would be too difficult to aggregate the package updates such that we only do an update once or twice a day and that update will essentially pull all the latest versions from the versions repo and ideally submit a PR that contains a commit for each version update in it.

**Comment by mmitche** [comment]
@joshfree What were those updates I was going to make? :D

**Comment by dagood** [comment]
@weshaggard Created https://github.com/dotnet/buildtools/issues/779 for partitioning. Maybe it is brittle enough to not be worth the effort. For PR combining, maybe we could change the update dependencies script to search for a PR and close or modify it. Nothing (afaik) tracks opened PRs at the moment.

**Comment by weshaggard** [comment]
@dagood Yes I don't think the partitioning is the best idea. For the aggregation I was thinking we might be able to change the triggers for the version updates to only do them at a certain time of day and then when the run the UpdateDependencies script in CoreFx could look for the latest version of all the dependencies it cares about and only submit one PR with all the dependency updates. @eerhardt how much would would it be to support time-based triggers on the versions maestro?

**Comment by weshaggard** [comment]
Or we could just turn the VSTS definitions into time based triggers.

**Comment by dagood** [comment]
A nice way to do that might be for Maestro to handle multiple `path`s, then the `maestroDelay` would be across all those paths. Then we could also reduce those 6 subscriptions to 2.

**Comment by jhendrixMSFT** [comment]
@mmitche I believe the change @joshfree is talking about is switching Jenkins to use the official build workflow (i.e. clean/sync/build scripts).

**Comment by mmitche** [comment]
@jhendrixMSFT @joshfree I thought this was already changed? I thought @ellismg did this late last week?

**Comment by eerhardt** [comment]
> @eerhardt how much would would it be to support time-based triggers on the versions maestro?

It wouldn't be a lot of work. We already have an Azure Web Job running, we could just use that to support time based. However, I don't have time to implement it this week - but that isn't stopping someone else from implementing it.  The code is in the versions repo - https://github.com/dotnet/versions/tree/master/Maestro/src.

> A nice way to do that might be for Maestro to handle multiple paths

I have been thinking about changing the structure of the subscriptions.json file. I partitioned it the wrong way. Currently it is organized by build-info paths, and then lists all the 'handlers' under the path.  But like you mention, it should be the other way - here is a 'handler' that listens to these N paths.  That way the handler is only written once.

**Comment by mellinoe** [comment]
@ellismg Has anything changed about this issue since it was filed?

**Comment by weshaggard** [comment]
One thing that has changed is that we are now aggregating and updating the auto-PR's which cuts down on the noise of updates. It still causes a lot of files to churn in the repo which we will likely be helped with our upcoming engineering push but I think there will always be a need for update our dependencies that come from outside our repo.

**Comment by dagood** [comment]
One thing to point out that we don't do is:
> Have automation which auto merges green dependency updates.

There currently isn't a plan for that, either. (Should there be?)

**Comment by karelz** [comment]
Unclear what it should track now. Things either improved or will improve shortly - let's close it and potentially reconsider in early 2017 when new engineering stuff gets in.
