### ISSUE TITLE
Come up with a plan for the NegotiateStream tests on Linux

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#9353]
The tests have both prerequisites and modify machine state during execution.

It would be great if we could eliminate the machine state modifications.

**Comment by steveharter** [comment]
See also issue #12107

**Comment by ianhays** [comment]
Closing this as https://github.com/dotnet/corefx/pull/12831 is the solution to https://github.com/dotnet/corefx/issues/12107 and it's unlikely we'll make any other improvements/modifications to these tests in the 2.0.0 timeframe.

Personally I'd prefer to leave the NegotiateStream tests as-is because they're some of the most stable tests we have for networking which is imo valuable enough to make up for the kdc setup,
