### ISSUE TITLE
Improve code coverage for System.Xml.XmlDocument

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#937]
According to the current code coverage report, this library is only at 47%.  Our general goal is closer to 90%, though this will depend on the library.  We should investigate to see whether the current coverage level is appropriate, and if not, improve our test suites to provide better coverage.

**Comment by plabovich** [comment]
@stephentoub, when you have a chance, could you please take a quick look at the PR 1269. I'd like to get feedback on the style and approach so that I can continue working on this issue.

**Comment by plabovich** [comment]
@stephentoub @krwq I've been working on tests for the next class XmlAttribute. Unfortunately, it's not possible to improve the code coverage a lot due to a technically unreachable code. There are at least 7 overridden methods in the class having code similar to:

        public override XmlNode AppendChild(XmlNode newChild)
        {
            if (PrepareOwnerElementInElementIdAttrMap())
            {
                // unreachable code as the condition is always false
                // some code plus call of the base class implementation
                ResetOwnerElementInElementIdAttrMap(/*...*/);
            }
            else
            {
                // call base implementation
            }
        }

The issue is that `PrepareOwnerElementInElementIdAttrMap` is set to always return false. The associated comment says it was left behind after removal of schema and if it were removed more methods would have to be removed and it would be harder to add schema back. I'm not sure how much of it is applicable to corefx implementation. My gut feeling says it's now. I'd like to ask for approval to remove the unreachable/unused code. 

Looking forward to hearing from you.

**Comment by stephentoub** [comment]
@krwq, is this actually dead code to be removed?

**Comment by plabovich** [comment]
@krwq, could you please take a look when you have a chance? I'd love to continue working on improving System.Xml.XmlDocument.

**Comment by krwq** [comment]
It might be a dead code but please do not remove it just yet as there was no concrete decision if we want to bring schema back as it was or make an OOB out of it or not do the work at all.

I want to be as close to desktop as possible with code for now so if I need to add schema back I can do it much easier.

**Comment by plabovich** [comment]
I see. Thanks for clarifying.

**Comment by danmosemsft** [comment]
This code was moved into System.Private.Xml. It's probably more useful to have new issue for that.
