### ISSUE TITLE
HttpWebResponse.ContentType returns empty string when response has malformed headers

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#9433]
Copied from https://github.com/dotnet/coreclr/issues/5806
/cc @erezvani1529

The content-type property is being stripped off of response if it is not in "type/subtype" format.

Information on the project and target frameworks:
- .NetCore Console App
- project.json

```JSON
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

    "dependencies": {
        "Microsoft.NETCore.App": {
            "type": "platform",
            "version": "1.0.0-rc2-3002702"
        },
        "WindowsAzure.Storage": "7.0.2-preview"
    },

  "frameworks": {
    "netcoreapp1.0": {
        "imports": [
            "dnxcore50",
            "portable-net451+win8"
        ]
    }
  }
}
```

Sample fiddler trace using WindowsAzure.Storage client library(CoreCLR RC2 release):

```
User-Agent: Azure-Storage/7.0.2-preview (.NET Core 5.0)
x-ms-content-language: languagevalue
x-ms-content-type: contenttypevalue---> Content type header is sent successfully
x-ms-client-request-id: 271c0518-3f42-4a05-89f0-27fcdf082d25
x-ms-version: 2015-07-08
x-ms-date: Wed, 08 Jun 2016 21:12:46 GMT
----------------------
Content-Type: contenttypevalue --> the stored content type returned from server
Content-Language: languagevalue
Last-Modified: Wed, 08 Jun 2016 21:12:45 GMT
ETag: "0x8D38FE1A3263418"
Server: Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: cf262393-001a-0014-27ca-c18fe2000000
x-ms-version: 2015-07-08
x-ms-type: File
Date: Wed, 08 Jun 2016 21:14:23 GMT
```
result: ContentType doesn't have the specified value (null value is retuned in the application).

Note: I have tried  the same scenario with a content-type with "type/subtype" format such as:
"contenttypeva/lue" and it works fine.

Please let me know if there are any more information required to investigate this issue.

Thanks!

**Comment by davidsh** [comment]
>result: ContentType doesn't have the specified value (null value is returned in the application).

What HttpClient API is being used to retrieve the 'Content-Type' response header?  There are several different ways to retrieve it via the `HttpResponseMessage.Content.ContentType` property or other ways.

Does this work in .NET Framework (Desktop)?

**Comment by erezvani1529** [comment]
@davidsh  Thanks for your quick response. 

We use `Content.Headers.ContentType` to get the content type out of `HttpResponseMessage`.

>>Does this work in .NET Framework (Desktop)?
Yes, it works as expected.

**Comment by davidsh** [comment]
According the RFC 7231;
https://tools.ietf.org/html/rfc7231#section-3.1.1.1

The 'Content-Type' header has the following format:

>3.1.1.1.  Media Type
   HTTP uses Internet media types [RFC2046] in the Content-Type
   (Section 3.1.1.5) and Accept (Section 5.3.2) header fields in order
   to provide open and extensible data typing and type negotiation.
   Media types define both a data format and various processing models:
   how to process that data in accordance with each context in which it
   is received.
     media-type = type "/" subtype *( OWS ";" OWS parameter )
     type       = token
     subtype    = token

There is no RFC definition for just having the `type` and no `/ subtype` portion.

**Comment by davidsh** [comment]
I investigated this.  It turns out that the `Content-Type` response header is not really removed.  It is still there in the HttpResponseMessage.Content.Headers collection.  However, the property itself, `HttpResponseMessage.Content.Headers.ContentType` returns a strongly typed object of type `MediaTypeHeaderValue`. The design of HttpClient and the Headers collection is such that a non-null value for each strongly typed property is only returned if the header value is considered "correctly formed". If the header value is not correctly formed, then it is left as-is in the header string collection but a `null` value for the property is returned. This is per-design of HttpClient.

In general, to retrieve malformed header values, you can use alternate APIs in HttpClient such as:

`HttpResponseMessage.Content.Headers.TryGetValues("Content-Type", ...)` That will return the raw string values even if they are malformed.

The RFC states that subtype is required.  So having a missing subtype as in this repro is considered a malformed response header.

**Comment by davidsh** [comment]
Also, it was mentioned above that "this works as expected on .NET Framework".

I tried this myself and it does not work on .NET Framework.  HttpClient APIs are working the same regarding this header parsing on both Desktop and .NET Core.

This code for example isolates the parsing problem:

```c#
            try
            {
                var contentType = new MediaTypeHeaderValue("foo");
                Console.WriteLine(contentType.ToString());
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
```

It will throw an expection if "foo" is used. It will work if "foo/subfoo" is used.

Note: It is possible that this works using HttpWebRequest APIs on .NET Framework (Desktop). And that is because the .ContentType property on HttpWebResponse returns a string and not a strongly typed property value.

**Comment by davidsh** [comment]
Offline discussion has clarified that this is not an HttpClient problem.  It is an app-compat behavior difference with HttpWebResponse.Content property.  On .NET Framework (Desktop), it would always return the string regardless of it being "malformed".  This broke on .NET Core because HttpWebRequest/HttpWebResponse APIs are now wrapped on top of HttpClient APIs for the implementation.  So, this problem can be mitigated in the wrapping layer.

**Comment by pemari-msft** [comment]
` HttpResponseMessage.Content.Headers.TryGetValues("Content-Type", ...) ` solved our issue. Thanks!
