### ISSUE TITLE
System.Security.Cryptography.HashAlgorithm implementation / porting ?

### ISSUE THREAD

**Issue by prajaybasu** [dotnet/corefx#9442]
[ .NET 4.6 implementation](http://referencesource.microsoft.com/#mscorlib/system/security/cryptography/hashalgorithm.cs) and [.NETCore implementation](https://dotnet.github.io/api/System.Security.Cryptography.HashAlgorithm.html).
From what I can see, HashCore() is protected, and HashAlgorithm.TransformBlock(), HashAlgorithm.TransformFinalBlock() are not implemented in .NETCore.
Is there any solution that can be recommended for porting stuff that depends on the methods mentioned before ? (I am quite new to .NETCore)

**Comment by bartonjs** [comment]
Incremental hashing was moved out of HashAlgorithm and into [IncrementalHash](https://dotnet.github.io/api/System.Security.Cryptography.IncrementalHash.html), primarily due to the unexpected interactions between TransformBlock and ComputeHash.

IncrementalHash doesn't exist in .NET Framework, but if you reference the System.Security.Cryptography.Algorithms nuget package when targeting .NET Framework the IncrementalHash class is still usable.

**Comment by bartonjs** [comment]
This seems to have addressed the question; so closing the issue.  If there's still more missing, feel free to leave more comments.
