### ISSUE TITLE
Add TryParse to XDocument

### ISSUE THREAD

**Issue by ilmax** [dotnet/corefx#9445]
Hi, this is a RFC issues to request support for a adding a `bool TryParse(string text, out XDocument document)` method to the `XDocument` class.

I've searched around the repo but cannot find anything related, so if this is a dupe feel free to close.

## Problem: 
Sometimes happens that you have to work with XML files that comes from *untrusted* sources, and you have to ensure that the file is actually well formed XML.

Currently there are [some](http://stackoverflow.com/questions/25791738/determine-whether-a-given-string-is-xml-or-not) not so nice [ways](http://stackoverflow.com/questions/117007/how-best-to-test-the-validity-of-xml-from-a-method) to verify a string is a well formed XML that involves exception handling.

None of the suggested ways looks like a clean solution to a quite common problem (at least IMO).

Please note also that other [BCL classes](http://referencesource.microsoft.com/#q=Parse) that exposes a `Parse(string source)` method usually also exposes a `bool TryParse(string source, out...)` thus adding a `TryParse` method will make `XDocument` class somewhat more consistent with other BCL classes.

## Suggestion:
add the following method

 `bool TryParse(string text, out XDocument document)` 

to `XDocument` and `XElement` classes

## Question:
Do we need feature parity with `XmlDocument` classes?
Actually `XmlDocument` exposes a `LoadXml(string xml)` so we could add a `bool TryLoadXml(string xml, out XmlDocument document)` but I really don't like the name and thus if feature parity isn't a must, I would prefer not adding it.

**Comment by weshaggard** [comment]
We reviewed this and don't fully understand the value of adding a TryParse method in this case. While consistency with other BCL types is somewhat interesting it is much more useful in those cases because you are potentially parsing a lot of them and so there is a performance issue. In this case performance isn't really going to be an issue because the exception cost is tiny compared to the cost of parsing the entire XML document. Also with the Parse methods you will get an XmlException on errors which gives additional information that points you to the parsing error which you wouldn't have in the TryParse cases. 

For similar cases the Roslyn APIs don't offer a TryParse method parsing a CS file either because you generally want more context on any errors, but even that maybe overkill for parsing XML documents which is why we have the middle ground of basic information in the XmlException.

For these reasons we don't think there is much value in adding a TryParse method to these.

**Comment by Crono1981** [comment]
@weshaggard,

Aside from convenience, a `TryParse` method would allow a dev to skip the overhead associated with try / catch blocks *and* the instantiating of a non-needed `XmlException` he/she may not even care about.

I too was very surprised to discover that no such method existed. :|
