### ISSUE TITLE
Support creating a file-based ResourceManager on .NET Core

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/corefx#947]
.NET Framework supports the creation of a file-based `ResourceManager` via the static method `ResourceManager.CreateFileBasedResourceManager`. We'd like to have this available in .NET Core for ASP.NET scenarios (e.g. deploying site as source).

**Comment by DamianEdwards** [comment]
Note, this is fine to be a new type/package rather than on the `ResourceManager` contract. We just need the functionality.

**Comment by davkean** [comment]
There's a couple of reasons why we'd probably want to make this a separate package:

1. On WinRT-based platforms, `ResourceManager` calls through WinRT APIs so that it can read from PRIs instead of ResX-based resources. We probably wouldn't light it for them. If we did, what would it do? Read resx when the rest of the platform is PRI? Read PRI? Who knows.

2. From a layering perspective, we consider _our_ file system APIs significantly higher than `ResourceManager`. `ResourceManage`r is used by nearly everything in .NET Core, so adding a dependency on file system would result in everything having a dependency on it (and introducing a number of cycles).

@DamianEdwards I do have a question:

Internally, you stated "We think the option of deploying resx files “as is” rather than have them create satellite assemblies is an attractive option for our scenarios". 

I don't understand that statement. The `CreateFileBasedResourceManager` method from .NET Framework doesn't create a `ResourceManager` around a raw ".resx", but rather around the binary resource format (ie ".resources"). You cannot copy a resx and expect it to open; you'll need to first write it to disk using ResourceWriter and then load that.

If you want to be able to deploy resx and then have ASP.NET pick it up, perhaps a better approach might be an API that takes a Stream? That way, you detect the edit to the file, load it, pass it to ResourceWriter(Stream), and then ultimately onto ResourceManager? Or an API that takes a raw ResX and wraps a ResourceManager around it?

**Comment by DamianEdwards** [comment]
@davkean Separate pacakge is fine. Yeah I just misspoke on the resx file thing :smile: 

You can see a working example of what we have in mind at https://github.com/DamianEdwards/i18nStarterWeb

It's compiling the resx files to resource files on disk during our precompilation stage and then loads them straight from there.

**Comment by davkean** [comment]
Okay, thanks.

**Comment by DamianEdwards** [comment]
@davkean I quite like the idea of a `Stream` based `ResourceManager` API, such that we could avoid hitting the disk when changing from .resx -> .resource. Then we really could just deploy resx files without any precompile or other such steps.

**Comment by davkean** [comment]
I spent some time thinking more about this, and I don't think the Stream approach will be what you want. Today if you call CreateFileBasedResourceManager you don't pass an actual resources file, but a base directory which dictates from where we would start probing for resources. If we had a method that created a ResourceManager from a stream, then you would basically be opt'ing out of probing - which is probably not want you want.

Thoughts?

// cc @ramarag

**Comment by DamianEdwards** [comment]
I was thinking it would be more of a builder/factory pattern, e.g.:

``` C#
var matcher = new Matcher();
matcher.Add("**/*.resx");
var resxFilePaths = matcher.Execute();

var builder = new ResourceManagerBuilder();

foreach (var file in resxFilePaths)
{
    CultureInfo culture = GetCultureFromFileName(file);
    string resourceName = Path.GetFileNameWithoutExtension(file);

    using (var fs = File.OpenRead(file))
    {
        var resx = XDocument.Load(fs);
        
        using (var writerStream = new MemoryStream())
        {
            var rw = new ResourceWriter(writerStream);

            foreach (var e in resx.Root.Elements("data"))
            {
                // TODO: Ignore non-string resources
                var name = e.Attribute("name").Value;
                var value = e.Element("value").Value;

                rw.AddResource(name, value);
            }

            rw.Generate();
            builder.Add(resourceName, culture, writerStream);
        }
    }
}

var resourceManager = builder.Build();
```

**Comment by davidfowl** [comment]
The idea is to opt out of probing.

**Comment by davkean** [comment]
You want to opt out of probing resource files on disk, but from Damian's example, ResourceManager would still be responsible for handling the lookup, right? Or is that what #948 is also about, enabling you guys to control it?

**Comment by davkean** [comment]
By lookup here, I mean deciding from which culture to pick a resource given a key.

**Comment by DamianEdwards** [comment]
Yeah, we'd expect lookup to still be handled by `ResourceManager`

**Comment by ramarag** [comment]
With the  67da622  you can implement your own Resource Manger for example like here
