### ISSUE TITLE
ContentEncoding header stripped out of response.header.content.contentEncoding

### ISSUE THREAD

**Issue by erezvani1529** [dotnet/corefx#9481]
When getting a response with "gzip" as the content encoding, this value is not populated into the response.Header.Content.contentEncoding object. If the value is "foo" this value is properly propagated from the response to the header object.

However, setting the AutomaticDecompression to DecompressionMethods.None on the HttpClientHandler instance is a workaround for us at the moment.

Note: this issue was originally opened in Coreclr repo ([Closed](https://github.com/dotnet/coreclr/issues/4114#issuecomment-226612226) and opened here as it is related to HttpClient)

**Comment by davidsh** [comment]
If the context is compressed and you have AutomaticDecompression turned on, then there is a transformation that happens. And thus, the resulting content is no longer compressed.  So, the 'Content-Encoding' header is stripped out since the resulting content is no longer compressed.

If you want to preserve the header, then you need to turn off AutomaticDecompression behaviors.

Basically, this is by-design.

cc: @stephentoub @CIPop

**Comment by erezvani1529** [comment]
Thanks @davidsh, that makes sense and we have already explicitly turned it off. I will close this issue.
