### ISSUE TITLE
Compat work for CodeDOM

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#9485]

**Comment by danmosemsft** [comment]
Need to discuss milestone.

**Comment by gulbanana** [comment]
could we prioritise System.CodeDom.Compiler.CompilerError? it's output by T4 templates

**Comment by danmosemsft** [comment]
@joperezr This is not in the subset of Xamarin/Unity available on mobile, so it's not a focus of this project directly. However it appears that @sepidehMS needs it for XSL. Please take a look and provide a recommendation for what to do for Core. Which parts of XSL would not work without it? How much is needed? How much work.

**Comment by mlacouture** [comment]
The WCF team needs to make the svcutil (metadata utility tool) available in netcore.  The main functionality of this tool is to generate code for referencing web services in client projects.  The desktop version of this tool makes heavy usage of the WCF Description API and the System.Runtime.Serialization API which in turn relies on CodeDom for code generation. Observe that we don't need to compile code (at least not now).   
So, in order to make this tool available in Netcore, we need to port the required API into System.ServiceModel.Description and System.Runtime.Serialization but in order to do this, System.CodeDom needs to be available in Netcore as well.  So please make this a priority.  thanks,

**Comment by danmosemsft** [comment]
To answer my own question above, seems CodeDOM is not criticacl for XSL: <msxsl:script> blocks are by design implementation-dependent and not portable.  Most stylesheets do not use them and may work without CodeDOM.

**Comment by stephentoub** [comment]
I'm working on porting System.CodeDom to corefx, though at least at first it'll be just the type model and code generator, i.e. it won't compile the resulting source into assemblies.  But that can be added subsequently, likely on top of Roslyn.

**Comment by stephentoub** [comment]
#12117

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/issues/12180 tracks adding compilation support if/when needed.
