### ISSUE TITLE
Enable (optionally) statically linking native dependencies on Linux

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#9500]
Related: dotnet/coreclr#5853

**Comment by stephentoub** [comment]
Related: https://github.com/dotnet/coreclr/issues/5853

**Comment by weshaggard** [comment]
@janvorli @stephentoub is this something we think we still want?

**Comment by janvorli** [comment]
I don't think there is anything we can statically link on corefx. There is:
* libssl - bad idea to link statically due to maintenance (updates for security fixes in libssl), different location of the certs on different distros, a lot of other second level dependencies that would need to be linked statically too so that the static linking would make sense at all.
* libcurl - similar issue to libssl w.r.t. location of SSL certs. Could be possibly solved by custom build of libcurl and configuring the locations of SSL certs at runtime from the current libssl or by platform detection. It seems we would not want to do that.
* gss - this library has a many dependencies, so linking it statically would not make much sense
* zlib - the libbsl and libcurl depend on it too, so making it static doesn't make sense, the openssl package installs it as a dependency.
* lzma - the existing static version cannot be linked into our shared library since it was not built with position independent code option. So we would need a custom build. But lzma was present by default on minimum installations of all major Linux distros I've tried. (tested on vanilla docker images of CentOS, Fedora, RHEL, OpenSuse, Debian, ArchLinux, Slaxware, Gentoo, OpenMandriva, Ubuntu). So static linking would not provide benefit here.

**Comment by weshaggard** [comment]
Thanks @janvorli so it sounds like we should just close this issue. Feel free to reactive if there is something else missing.
