### ISSUE TITLE
TryValidateObject not returning localized text after migration from RC1 to RC2

### ISSUE THREAD

**Issue by peter-bozovic** [dotnet/corefx#9535]
I have MVC project that uses some model validation outside of MVC pipe by calling directly
System.ComponentModel.DataAnnotations.Validator.TryValidateObject(...)
The project is for French market, so CurrentCulture and CurrentUICulture are both set to "fr"

In RC1, this setup was returning correctly validation error messages in French.
After migration to RC2, all messages are now in english, regardless of current culture that is set.

Do I miss something (localization package or different runtime), or is this a bug ?

**Comment by ViktorHofer** [comment]
@peter-bozovic Is this still happening with the current ASP.NET Core stable version and with the current dev master version?

**Comment by peter-bozovic** [comment]
When I use it on my local development environment (which is in French) the error messages are displayed in French (when the culture is set to "fr")
However when I deploy my solution on the Azure instance, messages are always in English, regardless if the culture is set to "en" or "fr" ...

I am using latest stable ASP.NET Core 1.1 targeting "net46" framework

**Comment by ViktorHofer** [comment]
If you are targeting net46 then this isn't any .NET Core related issue. I'm not 100% sure but I think this is because the default culture in Azure falls back to en-US.

See here: http://stackoverflow.com/questions/11135002/currentculture-incorrectly-defaulting-to-en-us-in-asp-net
And here for the solution to set it explicitely: http://stackoverflow.com/questions/41336783/set-culture-and-ui-culture-in-appsettings-json-asp-net-core-localization

I'm closing now because this isn't .NET Core related. Feel free to open again if you disagree.

**Comment by peter-bozovic** [comment]
Neither suggestion has anything to do with my issue.
My culture is correctly set and other parts are working correctly, like currency and date/time format.

Looks like translations for all cutures were included in the framework in the beginning which is not the case anymore, or the way they are retreived has changed.
So for the [Required] attribute, i'm always getting "The {0} field is required." instead of "Le champ {0} est requis." for the french culture ...

**Comment by ViktorHofer** [comment]
Oooh I thought you are probably facing one of those issues. If you are targeting net46 it shouldn't have to do anything with netcoreapp (I think). Have you already raised your concerns in the ASP.NET Core repo?
