### ISSUE TITLE
VS automatically changing solution and csproj

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#956]
What are your thoughts about VS automatically changing stuff?

I.e: https://github.com/dotnet/corefx/pull/954 VS updated version info. Also it removed new line character in the end of csproj (I removed this this change).

Should we keep that kind of changes or revert them?

I don't have strong opinion on that although I generally think that easier solution is always better: we should not manually change csproj & sln files so if VS wants to change it I would let it.

**Comment by akoeplinger** [comment]
+1. It would be nice though if this could be done for all .csproj's in a single pass so it doesn't show up randomly in a changeset (I guess this might only be possible once the VS2015 version number doesn't change anymore?).

**Comment by weshaggard** [comment]
The solution files are always bad about this which is why I've never really liked having them checked in (however I've lost that battle :)). I suspect we are going to continuously fight each other on the version as everyone will be using a different version of VS. Personally I would just undo those changes locally if that is the only change in the file. If there other changes in the file then I would submit it along with the other changes.

As for other files like csproj files we should definitely try to have a base and let the common tooling format it as it will and not fight against that.
