### ISSUE TITLE
Deprecate System.Collections.Specialized.CollectionsUtil class

### ISSUE THREAD

**Issue by ebickle** [dotnet/corefx#967]
Inside of the System.Collections.NonGeneric project is the class System.Collections.Specialized.CollectionsUtil.

There are a number of design and functional problems with the class:

* It contains only static methods, but the class itself is not static as it predates .Net 2.0. It has an implicit public constructor.
* The CreateCaseInsensitiveHashtable methods use StringComparer.CurrentCultureIgnoreCase. The String class and most other case insensitive comparisons in the .NET Framework use OrdinalIgnoreCase, following the Best Practices for Using Strings. The current implementation causes the behavior of the method to change based on the systems' Regional Options, which is likely not what the developer intended.

I recommend removing the class from corefx and marking it deprecated in the regular .NET Framework given it's extremely limited use and inherent problems.

If removing the class from corefx is not an option, alternately consider marking it deprecated and moving it from System.Collections.NonGeneric to System.Collections.Specialized to match it's containing namespace.

Any legacy dependencies on the class from within corefx should be removed in favor of an explicit Hashtable or SortedList constructor.

**Comment by weshaggard** [comment]
We have had numerous similar discussions internally about this exact class and while we agree with you in general we decided to keep it here for legacy compat reasons. The System.Collections.NonGeneric library in primarily for legacy compat reasons and in such libraries our goal is to keep the APIs as they are and not change them at all (no matter how much we dislike them :)).

**Comment by ebickle** [comment]
That's what I assumed as well :)

What are the rules and recommendations for aligning existing classes into the new corefx assemblies? In this case we have a System.Collections.Specialized class living outside of the System.Collections.Specialized namespace.

**Comment by eatdrinksleepcode** [comment]
Why not deprecate it? "Warnings as errors"?

**Comment by weshaggard** [comment]
Just about everything about that type is wrong including its namespace. While it is in the S.C.Specialized namespace it is tightly coupled with and has public APIs that return types from S.C.NonGeneric. So we kept it in that assembly instead of putting it into the Specialized assembly and requiring a dependency from Specialized to NonGeneric (at least from the public API surface). 

As for marking it as deprecated that also defeats the purpose of providing it for legacy compat. There isn't necessary any harm in using it and we wouldn't want to add noise to the very people we included this for in the first place. 

@ebickle as a general rule we do try to align namespaces with assemblies but that doesn't always work out and there are always exceptions. When writing new types however we do try and put them in the correct namespace and in the correct assembly.

**Comment by ebickle** [comment]
@weshaggard I agree, there's nothing inherently dangerous about the class. Wasn't sure of the deprecation/obsoleteattribute strategy was changing in .NET Core.

I had incorrectly assumed System.Collections.Specialized took a dependency on System.Collections.NonGeneric. Still a bit unclear how things like System.Collections.IList will fit in the new package/assembly structure.

**Comment by eatdrinksleepcode** [comment]
I understand the concern with creating noise for people who are already using it. The problem is that the type isn't only exposed to people who are already using it; it is also exposed to everyone else, including developers who are picking up the framework for the first time and don't know that there are better options available. Such people will often search the internet looking for examples or solutions for their problems, and the internet remembers many things that were once valid but no longer are.

This has been a common occurrence as I have watched the .NET Framework evolve. Deprecation was included in the platform to help it evolve without becoming cluttered and bogged down by old cruft. But in the vast majority of cases where such a mechanism is needed, it is rejected, for reasons similar to this. The result is that the experience of new and current developers who are doing active development is continually sacrificed to the constraints of the small subset of developers who are unwilling (or very rarely unable) to suffer ANY discomfort whatsoever in order to stay current with the rapid pace of development in the modern world.

If the intent is to continue catering to these developers, then the deprecation mechanism needs to be enhanced such that we can guide new developers towards the pit of success, while allowing those who choose to do so to stay in the pit they are already in.

**Comment by akoeplinger** [comment]
@eatdrinksleepcode FYI we had a similar discussion in https://github.com/dotnet/corefx/issues/384
