### ISSUE TITLE
Add Task-based async methods to Socket

### ISSUE THREAD

**Issue by GSPP** [dotnet/corefx#9697]
The Socket class is fully capable of async IO but `Task`-returning methods are missing. I find myself pulling in the same set of helper extensions each time I use async sockets.

Since sockets are a primary use case for async IO I'd find this API addition extremely useful.

Note, that the async methods on `NetworkStream` are not enough because we need async support for things like `Connect` as well.

**Comment by GSPP** [comment]
[Stephen Toub already has done some work here.] (http://blogs.msdn.com/b/pfxteam/archive/2011/12/15/10248293.aspx)

**Comment by davidsh** [comment]
cc: @CIPop @stephentoub

**Comment by CIPop** [comment]
`Socket` already has support for TPL: https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/ref/System.Net.Sockets.cs#L392

**Comment by GSPP** [comment]
Cool, that's great news! I think this issue can be closed.

Why were extension methods chosen as opposed to regular methods? This is a rare design choice.

**Comment by CIPop** [comment]
Nice! Closing.

> Why were extension methods chosen as opposed to regular methods? This is a rare design choice.

It's so that `System.Net.Sockets` is available for all platforms including .Net Desktop 4.6. The constraint we're working around is that once we release, we cannot add new APIs to the frameworks. 
Adding them as extensions allowed us to include the new APIs and their implementation in the facade lib (the glue between Core and the Desktop framework) as well as have them available within the .Net Core implementation.

Today, the implementations are the same in both cases. In the future, since for .Net Core they live next to the Socket code, they can eventually be optimized as true Task based APIs instead of wrappers over the Begin/End implementation.
