### ISSUE TITLE
ForeignKeyAttribute add cascadeDelete cascadeUpdate param

### ISSUE THREAD

**Issue by Varorbc** [dotnet/corefx#9750]
ForeignKeyAttribute add cascadeDelete cascadeUpdate param

**Comment by divega** [comment]
Data Annotations Triage: This seems like a good idea. Although we are not planning to do it in the near future we would consider a PR from someone in the community. Changes would need to happen in data persistence frameworks that reason about this attribute (such as EF Core) in order to make things work end-to-end.

**Comment by ajcvickers** [comment]
This is not something we plan to implement. We _might_ consider a community PR for it, but it would deviate the behavior in .NET Framework and .NET Core, and I'm not sure the value is worth that. For EF Core mappings, we would consider it as a [new attribute](https://github.com/aspnet/EntityFrameworkCore/issues/10864).
