### ISSUE TITLE
Create a new portable library for IO

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#9798]
There are a lot of IO utility APIs that we'd like to add to .NET. While adding methods to the existing classes (say, System.IO.Path) is a big usability plus, it is a deployment headache. Example: If we add Path.CreateRelativePath() it would create a dependency on some future version of the various runtimes (say 4.6.3 for desktop) which inhibits writing portable libraries that consume this API that has no lower level runtime dependencies.

We could easily create a library that supports standard 1.0 or 1.3 that contains the pieces people are asking for and not need to force them to a newer set of runtimes to consume the functionality. It would also facilitate getting the desired functionality to users faster as we wouldn't have nearly the same level of plumbing overhead. (For Path in particular there are a *lot* of pending functionality requests.)

Initial name ideas:

- System.IO.Portable
- System.IO.Utility
- System.IO.PathExtended

If we go with a more generic name we'd have the ability to add other functionality that we are looking to do without exploding the library count too much. (One example is adding a set of interfaces for basic IO access, say IFileSystem.)

For existing static classes we could do something like Path -> PathExtended (thinking of PathEx). The other pattern that is commonly used is "Path2".

@weshaggard, @ericstj, @terrajobst, @stephentoub

**Comment by JeremyKuhne** [comment]
If we ever get static extension methods we could potentially add them in this assembly as well.

**Comment by JeremyKuhne** [comment]
This is just an idea to stimulate discussion around facilitating forward progress. Other alternatives are welcome, say a sandbox or sample repo for example.

**Comment by ianhays** [comment]
>Example: If we add Path.CreateRelativePath() it would create a dependency on some future version of the various runtimes 

Why is this? Because it's within Runtime Extensions?

>One example is adding a set of interfaces for basic IO access, say IFileSystem.

Interesting. We talking like a streamless c-like IO API or just a basic set of FileSystem operations?

>If we ever get static extension methods we could potentially add them in this assembly as well.

+1. That would be a pleasant way to resolve this. I don't like `PathEx.Method` or `Path2.Method` since they require splitting Path in a rather unintuitive way. Something like `PathHelper.Method` would be fine for some methods, though we've already got one of those internal.

One thing I've had a few people request is a non-static Path class to make Path equality, comparison, and validation easier while solidify a string as actually being a Path e.g.
```
Path path1 = new Path("D:/git/corefx");
Path path2 = new Path("D/git/corefx/src/../");
Assert.True(path1 == path2);
```
Not really related to this issue though.

**Comment by karelz** [comment]
@JeremyKuhne says close it :)
