### ISSUE TITLE
Custom Console Colours

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/corefx#9812]
I'm working on .NET Core support in [Colorful.Console](http://colorfulconsole.com/). I've added nestandard1.3 support but it uses interop to set custom colours in the console, so I'm now looking at how to add this support for Windows, Mac and Linux to support every platform. Currently I'm using `RuntimeInformation.IsOSPlatform` to only use interop on Windows (See code [here](https://github.com/tomakita/Colorful.Console/blob/master/src/Colorful.Console/ColorMapper.cs#L93-L109)). Example of what the library can currently do using Figlet fonts:

![ascii_x1](https://cloud.githubusercontent.com/assets/2270364/16540939/3ee3d972-406e-11e6-8e71-e6918241db2d.png)

First of all, is there anything stopping built in support for this in `System.Console`? Perhaps using `System.Drawing.Color` and adding a `Background` and `Foreground` property to `System.Console`. My understanding is that `System.Drawing.Color` is coming to .NET Core soon.

Alternatively, I've been looking at the internal [ConsolePal](https://github.com/dotnet/corefx/tree/56600ecc3738940219f3c5a886c6bb0afe1f6a75/src/System.Console/src/System) classes in trying to understand how I can add this support to [Colorful.Console](http://colorfulconsole.com/). Could someone explain:

1. Why there are only Windows, WinRT and Unix versions (I guess Mac uses the same Console API as Unix but I didn't realize WinRT is totally separate too).
2. Are there any tutorials about how to compile for each platform? [System.Console.csproj](https://github.com/dotnet/corefx/blob/56600ecc3738940219f3c5a886c6bb0afe1f6a75/src/System.Console/src/System.Console.csproj) seems to contain some complicated rules around this. Also it's not an xproj, which is what I was expecting but it does have a project.json file.
3. Any guidance on understanding how ConsolePal is setting colours would help.

**Comment by stephentoub** [comment]
> Why there are only Windows, WinRT and Unix versions (I guess Mac uses the same Console API as Unix but I didn't realize WinRT is totally separate too).

Right, the Unix implementation is for any Unix target. The WinRT one is because most of the needed functionality isn't currently exposed for UWP apps.

> Are there any tutorials about how to compile for each platform?

If you're building on the target platform, you can just build and it'll pick up the right OS. If you're building on Windows,  you can cd into src\System.Console\src and do msbuild /p:OSGroup=Linux to build for Linux or substitute OSX for Linux to build for mac (though for console the resulting binary will be the same between the two).

> Any guidance on understanding how ConsolePal is setting colours would help

On Windows it calls Win32 functions. On Unix it writes out ANSI example sequences as dictated by the terminfo for the current environment.

**Comment by ianhays** [comment]
@RehanSaeed did Steve answer your question or is there anything else you were curious about?

**Comment by RehanSaeed** [comment]
Yes thank you.
