### ISSUE TITLE
Make System.Numerics.Vector(void* dataPointer, int offset) public ?

### ISSUE THREAD

**Issue by prajaybasu** [dotnet/corefx#9840]
In some scenarios, one might use this constructor in unsafe contexts using non CLS compliant types.
This should be made public for "architectural symmetry", I guess.

**Comment by benaadams** [comment]
Use the `System.Runtime.CompilerServices.Unsafe` package

usage: `Unsafe.Read<Vector<ushort>>(dataPointer + offset);`

**Comment by mellinoe** [comment]
Yes, the `Unsafe` package is our current answer for this. We originally had thought of exposing the unsafe constructor, but decided to add a more general-purpose API which can be used for other generic structures as well, since the problem is not unique to `Vector<T>`, but rather to any type wanting a generic pointer argument.
