### ISSUE TITLE
CS0012 The type 'Object' is defined in an assembly that is not referenced.

### ISSUE THREAD

**Issue by tverboon** [dotnet/corefx#9885]
The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, version=4.0.0.0, ...'

I try to instantiate a MongoClient which is still a .Net 4.5 assembly, like this:

`var client = new MongoDB.Driver.MongoClient(@"mongodb://localhost:27017/");
if (client == null)
{
       return;
}`

The build error is on the client == null line.

My project.json is as follows:

```
{
  "version": "1.0.0-*",

  "dependencies": {
    "NETStandard.Library": "1.6.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "MongoDB.Driver": "2.2.4",
    "MongoDB.Driver.Core": "2.2.4",
    "MongoDB.Bson": "2.2.4"
  },

  "frameworks": {
    "netstandard1.6": {
      "imports": "net46"
    }
  }
}
```

My VM has Win10 as OS, so I have only .Net 46x installed.

Am I doing something wrong?

**Comment by tverboon** [comment]
I figured it out: http://stackoverflow.com/a/38245660/6083098

Still, I would have thought that `"frameworks": {
    "netstandard1.6": {
      "imports": "net46"
    }
  }`

is the same as:
`"frameworks": {
    "net46": { },
  }`

But apparently it is not.

**Comment by tverboon** [comment]
Reopened it, because maybe it is not by design

**Comment by mellinoe** [comment]
This is by design. Your first version:

```
"frameworks": {
    "netstandard1.6": {
      "imports": "net46"
    }
  }
```

is basically saying: "Build me a library targetting `netstandard1.6`, but also let me reference stuff built for `net46`, even if it isn't compatible." It turns out that the assembly isn't compatible, so you can't compile. The problem is that MongoClient references a `System.Object` type which resides in mscorlib.dll. NETStandard.App, when targetting `netstandard1.6`, is going to pull in a System.Runtime.dll which references a `System.Object` type which resides in System.Runtime.dll. There is no mscorlib facade which could reconcile this discrepancy, so you get compilation errors.

If you're building for .NET Framework, use your second appoach, i.e. `"frameworks": { "net46": { }, }`.

If you want to build for .NET Core, you will need a version of MongoClient which is compatible with `netstandard`. This could then be used from a .NET Framework application.

**Comment by tverboon** [comment]
Thanks for this clear answer, it clarifies a lot for me. :smile: :thumbsup:
