### ISSUE TITLE
Environment.GetFolderPath on Windows can't use SHGetFolderPath

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#9890]
#9826 added back the full surface area of Environment.  However, GetFolderPath on Windows in the desktop framework uses SHGetFolderPath to implement this method, but that Win32 function isn't available:
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.CodeAnalysis/PackageFiles/PinvokeAnalyzer_OneCoreApis.txt
As a result, the method is mostly unusable.

**Comment by danmosemsft** [comment]
Included on list for Windows folks...

**Comment by JeremyKuhne** [comment]
This issue is blocking IsolatedStorage.

This appears to be implemented now (api-ms-win-shell-shellfolders-l1-1-0). Are there any links on how to update the API list? Any guidance on using the "right" string for the P/Invokes?

Also: we should use SHGetKnownFolderPath as it is more current (and necessary for folders we may want to expose in the future).

I'm happy to take care of this to unblock my other work.

**Comment by stephentoub** [comment]
> Are there any links on how to update the API list?

Add it to:
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.CodeAnalysis/PackageFiles/PinvokeAnalyzer_OneCoreApis.txt
Then corefx will need to consume an updated buildtools.

> Any guidance on using the "right" string for the P/Invokes?

https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/Windows/Interop.Libraries.cs

> This appears to be implemented now

If that's the case, please do go ahead and submit a PR to use it.  It still won't work for the WinRT implementation, though.
