### ISSUE TITLE
System.Drawing.Primitives NuGet type forwarders for Xamarin Platforms

### ISSUE THREAD

**Issue by migueldeicaza** [dotnet/corefx#9908]
Hello,

We have at least identified that for Xamarin.{iOS,Mac,tvOS} where we need some changes.
 
The `System.Drawing.Primitives` package that contains type definitions for the following `System.Drawing` types should contains type forwarders: `Point`, `PointF`, `Rectangle`, `RectangleF`, `Size`, `SizeF`
 
* On iOS the types live in Xamarin.iOS.dll
* On MacOS they types live in Xamarin.Mac.dll
* On tvOS the types live in Xamarin.tvOS.dll

This additionally assumes that .NET 4.5 on MacOS will continue to forward those types to `System.Drawing` for non-mobile profile based setups.
 
Sidebar: While there are alternative approaches to this, we believe that doing this in the upstream packaging of NuGet will encourage the testing-by-being-a-process dependency.

**Comment by ericstj** [comment]
As of yet we don't build any Xamarin specific facades in our build process.  The way we've been handling this to date is for any case where a Xamarin specific assembly is required we put a placeholder in the package so that it will install without providing any assets.  Xamarin adds the reference/implementation to its SDK.

If you'd like us to build facades for Xamarin profiles we would need to have packages that include the reference assemblies for your profiles (similar to the Microsoft.TargetingPack packages on https://dotnet.myget.org/gallery/dotnet-core). 

@migueldeicaza can you please let us know which of these options is the one you're asking for here?  If its the latter then I to help facilitate I'll request that we come up with a process for which Xamarin publishes targeting packs for us to consume in CoreFx.

**Comment by migueldeicaza** [comment]
Given the urgency of the matter, we will have to do this ourselves.

**Comment by ericstj** [comment]
I think we still have a problem here and would like to determine what you want moving forward.

**Comment by migueldeicaza** [comment]
We will need to have the NuGet package add the _._ markers for all Xamarin platforms, so that we can provide the forwarders for fused types.

**Comment by ericstj** [comment]
I see.  We can do that.  I'm working on a large update to enable validation for Xamarin and I will include updates that mark this contract as inbox.  I'll keep this issue open to track that work.

**Comment by ericstj** [comment]
This was fixed by https://github.com/dotnet/corefx/pull/9936.
