### ISSUE TITLE
Investigate return of System.ComponentModel.Composition.*

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#9946]
Core has System.Composition.dll 
Core does not have S.ComponentModel.Composition and System.ComponentModel.Composition.DataAnnotations. These are in Xamarin for Android (unlike System.ComponentModel.Composition.Registration)

These two need to get into Core. They are reflection heavy so that work has to happen first. I see a bit of ref.emit also, which hopefully isn't essential.

**Comment by mellinoe** [comment]
What would make this different from the other stuff we're bringing back?

**Comment by danmosemsft** [comment]
@mellinoe Nothing - I'm just tracking it.

**Comment by karelz** [comment]
Composition asked for in #3636.

**Comment by Petermarcu** [comment]
Is this in netstandard2.0 per the label? If so, please put it in the 1.2 milestone.

**Comment by weshaggard** [comment]
@danmosemsft I suspect you meant System.ComponentModel.DataAnnotations and not System.ComponentModel.Composition.DataAnnotations because I don't know anything about the later. At any rate DataAnnotations is not related to MEF v1 (i.e. System.ComponentModel.Composition). Which is not part of .NET Standard 2.0 so I'm removing the label. We should still consider adding MEF v1 to .NET Core at some point.

**Comment by danmosemsft** [comment]
Probably... Updated title. This can track any requests for it.

**Comment by karelz** [comment]
It is unclear what this one tracks -- MEF1 (Composition) or ComponentModel.DataAnnotations. If we still need to track them, let's create new separate issues for each.

**Comment by karelz** [comment]
BTW: MEF1 is tracked by #11857.
