### ISSUE TITLE
WebSocket.CloseAsync can throw when WebSocket.CloseOutputAsync has been previously called on Unix

### ISSUE THREAD

**Issue by mconnew** [dotnet/corefx#9985]
If a client calls WebSocket.CloseOutputAsync on an open WebSocket, a Close frame is sent and the WebSocket transitions into the CloseSent state. If it's then desired to wait until the response Close frame is received, for example to check the response status code that the server sends, a call to WebSocket.CloseAsync can then be made. This is necessary as otherwise the alternative is to poll the WebSocket status property until the state changes. This is also codified as CloseAsync is valid to call when the state is CloseSent. If the Close frame sent by the server is received and processed before the state check in WebSocket.CloseAsync is executed, the state will be Closed and CloseAsync will throw (only allowed states when calling CloseAsync are Open, CloseSent and CloseReceived).  
This is blocking WCF enabling the WebSockets transport for Unix platforms.

**Comment by mconnew** [comment]
@stephentoub, @CIPop, @davidsh

**Comment by stephentoub** [comment]
@mconnew, thanks for the description.  The issue you're highlighting occurs in some cases just by doing the following?
```C#
await ws.CloseOutputAsync();
await ws.CloseAsync();
```
or is there a more complicated sequence involved?  Are you using ReceiveAsync concurrently with this, or something like that?

**Comment by mconnew** [comment]
@stephentoub, I believe we still have a pending call to ReceiveAsync before we call either of those methods but we don't call anything between the call to CloseOutputAsync() and CloseAsync().

**Comment by stephentoub** [comment]
> I believe we still have a pending call to ReceiveAsync before we call either of those methods

@cipop, is this considered acceptable concurrenct usage of ClientWebSocket?  Our managed implementation currently does not expect this.  It allows at most one ReceiveAsync to be used concurrently with at most one SendAsync, but CloseAsync/CloseOutputAsync must not be used concurrently with anything else.  Violating that would explain why you're able to see the behavior you're seeing.  If the design here allows for that, I'll need to update the implementation to make such a situation more robust.

**Comment by mconnew** [comment]
@stephentoub, what are you supposed to do in the scenario where you have a pending ReceiveAsync() outstanding on a WS (one of the main reasons for WS's existence is to allow the remote end to send unsolicited data) and wish to close the connection cleanly?

**Comment by stephentoub** [comment]
> what are you supposed

I didn't define the shape of this type.  I simply implemented what I thought the semantics were.  If I got them wrong, I'll fix it.  If I got them right, then @cipop may have an answer to your question.

**Comment by CIPop** [comment]
>> I believe we still have a pending call to ReceiveAsync before we call either of those methods

> @cipop, is this considered acceptable concurrent usage of ClientWebSocket? 

I don't think we have tests for this behavior but they should be acceptable.
The only restriction for WinHTTP is having at most one pending ReceiveAsync and one pending SendAsync as there is no queuing at any layer.
Even if we consider Close*Async another type of "Send", the above rule isn't broken by the pattern described by @mconnew. Closing the _output_ is definitely an option while still waiting for data (similar to a socket unilateral shutdown). If the remote endpoint sends data, the pending ReceiveAsync should continue to work until either CloseAsync is called or the remote party closes their output or entire websocket.
We need to test that CloseAsync with a pending ReceiveAsync works.

Not really the issue here but worth clarifying: WinHTTP's APIs must not be called from two different threads for the same handle: this is hidden from the user by having locks around the pinvokes. The WinHTTP API calls have short execution times and return immediately after the async operation got started.

**Comment by stephentoub** [comment]
I will look into making it safe to use close concurrently with receive, but aside from that, isn't this same race condition possible on Windows as well, simply because the design has verification of the state done at the beginning of the operation?  If you have an outstanding call to ReceiveAsync and do:
```C#
await CloseOutputAsync();
await CloseAsync();
```
the CloseOutputAsync will send a close frame.  If the server responds and the pending ReceiveAsync processes that close frame between the two calls, it'll transition the state and CloseAsync will throw.  What am I missing?

**Comment by stephentoub** [comment]
> What am I missing?

Ok, it appears that what I'm missing is that the Windows implementation doesn't transition to the Closed state after a server responds to a CloseOutputAsync; calling CloseOutputAsync transitions to CloseSent, and then receiving the close frame further transitions it to CloseReceived.  It takes an explicit call to CloseAsync to transition it to the Closed state.  That's different from what I thought the logic was supposed to be, which was that receiving a close after one was sent transitions to Closed.  I can fix that.
