### ISSUE TITLE
Add back Environment.Is64BitXXX

### ISSUE THREAD

**Issue by blobor** [dotnet/corefx#999]
Hi all.
There are some methods that aren't yet implemented in Environment class.
- Is64BitProcess
- Is64BitOperatingSystem
- OSVersion

Will they be implemented?

**Comment by davkean** [comment]
Thanks for the issues. This is two separate requests; architecture specific properties and OS version information. We may take one of these without the other,, can you split them into two requests?

Starting in Windows 8.1, OS version information always lies - unless you've been manifested saying that you know about the new version of Windows. They do this because a lot of apps do incorrect version checks, preventing themselves from running on future versions of Windows. 

With regards to OS version information, what do you want to do with the information? What decisions do you make differently based on it?

With regard to Is64BitProcess, until we add it back, as a workaround right now, you can check the pointer size via IntPtr.Size.

**Comment by blobor** [comment]
Hi.
- I have created new issue for OS version information https://github.com/dotnet/corefx/issues/1017.
- For Is64BitProcess property I already know this workaround (mono uses it), but still I could not determine whether a given OS is 32 bit or 64 bit.

**Comment by ellismg** [comment]
@blobor For your second issue, I assume you want to detect the case where you are in a 32 bit process (running under WoW, so IntPtr.Size is 4) but running on a 64 bit OS.  What's the use case here?

**Comment by blobor** [comment]
@ellismg I have trouble with accessing windows registry. For accessing appropriate keys I was need to switch RegistryView to 32bit or 64bit depending on platform.
Also I need to load specific library on UNIX systems depending is 64 bit or not.

**Comment by Priya91** [comment]
Closing this issue, with the new APIs added to RuntimeInformation.
